{
  "name": "SemanticModel",
  "compatibilityLevel": 1200,
  "model": {
    "culture": "fi-FI",
    "dataSources": [
      {
        "name": "SqlServer dwitestvipusql VipunenTK",
        "connectionString": "Provider=SQLOLEDB.1;Data Source=dwitvipusql22;Initial Catalog=VipunenTK;Integrated Security=SSPI;Persist Security Info=false",
        "impersonationMode": "impersonateServiceAccount",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "Sarakeleveys",
        "columns": [
          {
            "name": "Sarakeleveys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Sarakeleveys"
          },
          {
            "name": "leveys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "leveys"
          }
        ],
        "partitions": [
          {
            "name": "Sarakeleveys",
            "source": {
              "query": "SELECT [dbo].[Sarakeleveys].* \t\tFROM [dbo].[Sarakeleveys]",
              "dataSource": "SqlServer dwitestvipusql VipunenTK"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization"
              },
              {
                "name": "TableWidgetSerialization"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Sarakeleveys"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "      SELECT [dbo].[Sarakeleveys].*   FROM [dbo].[Sarakeleveys] "
          }
        ]
      },
      {
        "name": "Muuttujat",
        "columns": [
          {
            "name": "Tilastovuosi",
            "dataType": "string",
            "sourceColumn": "Tilastovuosi",
            "displayFolder": "Aikamuuttujat"
          },
          {
            "name": "Aloituslukuvuosi",
            "dataType": "string",
            "sourceColumn": "Aloituslukuvuosi",
            "displayFolder": "Aikamuuttujat"
          },
          {
            "name": "Aloitusvuosi",
            "dataType": "string",
            "sourceColumn": "Aloitusvuosi",
            "displayFolder": "Aikamuuttujat"
          },
          {
            "name": "Aloituslukukausi",
            "dataType": "string",
            "sourceColumn": "Aloituslukukausi",
            "displayFolder": "Aikamuuttujat"
          },
          {
            "name": "Tarkastelujakso",
            "dataType": "string",
            "sourceColumn": "Tarkastelujakso",
            "sortByColumn": "jarj_tarkastelujakso",
            "displayFolder": "Aikamuuttujat"
          },
          {
            "name": "Pääasiallinen toiminta",
            "dataType": "string",
            "sourceColumn": "Pääasiallinen toiminta",
            "sortByColumn": "jarj_paas",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Hallinnonala",
            "dataType": "string",
            "sourceColumn": "Hallinnonala",
            "sortByColumn": "jarj_hallinnonala",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Opintojen kulku",
            "dataType": "string",
            "sourceColumn": "Opintojen kulku",
            "sortByColumn": "jarj_1a",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusala (2002)",
            "dataType": "string",
            "sourceColumn": "Koulutusala (2002)",
            "sortByColumn": "jarj_koulala2002",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusala, taso 1",
            "dataType": "string",
            "sourceColumn": "Koulutusala, taso 1",
            "sortByColumn": "jarj_koulalataso1",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Järjestämistapa",
            "dataType": "string",
            "sourceColumn": "Järjestämistapa",
            "sortByColumn": "jarj_jarjestamistapa",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Järjestämismuoto",
            "dataType": "string",
            "sourceColumn": "Järjestämismuoto",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Tutkintotyyppi",
            "dataType": "string",
            "sourceColumn": "Tutkintotyyppi",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutuksen maakunta",
            "dataType": "string",
            "sourceColumn": "Koulutuksen maakunta",
            "sortByColumn": "jarj_maakunta",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutuksen järjestäjä",
            "dataType": "string",
            "sourceColumn": "Koulutuksen järjestäjä",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "jarj_tarkastelujakso",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_tarkastelujakso"
          },
          {
            "name": "jarj_paas",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_paas"
          },
          {
            "name": "jarj_hallinnonala",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_hallinnonala"
          },
          {
            "name": "jarj_1a",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_1a"
          },
          {
            "name": "jarj_koulala2002",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_koulala2002"
          },
          {
            "name": "jarj_koulalataso1",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_koulalataso1"
          },
          {
            "name": "jarj_maakunta",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_maakunta"
          },
          {
            "name": "lkm_1vr2",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "lkm_1vr2"
          },
          {
            "name": "lkm_int2",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "lkm_int2"
          },
          {
            "name": "jarj_jarjestamistapa",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_jarjestamistapa"
          },
          {
            "name": "Suoritettu tutkinto",
            "dataType": "string",
            "sourceColumn": "Suoritettu tutkinto",
            "sortByColumn": "jarj_1c",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "paaskoodi",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "paaskoodi"
          },
          {
            "name": "jarj_1c",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_1c"
          },
          {
            "name": "Koko tutkinto/tutkinnon osa",
            "dataType": "string",
            "sourceColumn": "Koko tutkinto/tutkinnon osa",
            "sortByColumn": "jarj_kokoosa",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "aloit2",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "aloit2"
          },
          {
            "name": "opisk2",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "opisk2"
          },
          {
            "name": "tutk2",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "tutk2"
          },
          {
            "name": "jarj_kokoosa",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_kokoosa"
          },
          {
            "name": "kouljarjkoodi",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "kouljarjkoodi"
          },
          {
            "name": "aloitp2",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "aloitp2"
          },
          {
            "name": "ensisij2",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ensisij2"
          }
        ],
        "partitions": [
          {
            "name": "v_f_tab_ammatillinen_scorecard",
            "source": {
              "query": " SELECT [dbo].[v_f_tab_ammatillinen_scorecard].* FROM [dbo].[v_f_tab_ammatillinen_scorecard] ",
              "dataSource": "SqlServer dwitestvipusql VipunenTK"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tilastovuosi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>86</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Aloituslukuvuosi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>106</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Aloitusvuosi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>87</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Aloituslukukausi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>105</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tarkastelujakso</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>105</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Pääasiallinen toiminta</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>132</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Hallinnonala</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>87</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koko tutkinto/tutkinnon osa</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>162</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Opintojen kulku</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>104</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Suoritettu tutkinto</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>118</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusala (2002)</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>120</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusala, taso 1</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>122</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Järjestämistapa</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>106</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Järjestämismuoto</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>114</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tutkintotyyppi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>99</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutuksen maakunta</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>138</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutuksen järjestäjä</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>137</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj_tarkastelujakso</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>125</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj_paas</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>75</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>paaskoodi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>78</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj_hallinnonala</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>108</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj_kokoosa</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>91</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj_1a</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>64</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj_1c</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>63</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj_koulala2002</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>109</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj_koulalataso1</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>112</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj_jarjestamistapa</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>126</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj_maakunta</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>99</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>kouljarjkoodi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>90</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>lkm_1vr2</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>73</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>lkm_int2</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>69</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>aloit2</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>56</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>opisk2</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>60</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tutk2</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>55</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>aloitp2</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>62</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ensisij2</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>65</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tilastovuosi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Aloituslukuvuosi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Aloitusvuosi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Aloituslukukausi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tarkastelujakso</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Pääasiallinen toiminta</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>5</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Hallinnonala</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>6</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koko tutkinto/tutkinnon osa</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>7</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Opintojen kulku</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>8</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Suoritettu tutkinto</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>9</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusala (2002)</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>10</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusala, taso 1</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>11</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Järjestämistapa</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>12</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Järjestämismuoto</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>13</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tutkintotyyppi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>14</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutuksen maakunta</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>15</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutuksen järjestäjä</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>16</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj_tarkastelujakso</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>17</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj_paas</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>18</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>paaskoodi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>19</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj_hallinnonala</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>20</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj_kokoosa</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>21</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj_1a</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>22</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj_1c</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>23</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj_koulala2002</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>24</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj_koulalataso1</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>25</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj_jarjestamistapa</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>26</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj_maakunta</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>27</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>kouljarjkoodi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>28</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>lkm_1vr2</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>29</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>lkm_int2</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>30</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>aloit2</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>31</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>opisk2</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>32</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tutk2</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>33</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>aloitp2</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>34</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ensisij2</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>35</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>ensisij2</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "1 v. tutkinnon jälkeen",
            "expression": [
              "",
              "var lkm = SUM([lkm_1vr2])",
              "return IF(lkm = 0, BLANK(), IF(lkm < 5, \"1-4\", MROUND(lkm, 3)))",
              ""
            ],
            "displayFolder": "Työllistyminen"
          },
          {
            "name": "Henkilöt",
            "expression": [
              "",
              "var lkm = SUM([lkm_int2])",
              "return IF(lkm = 0, BLANK(), IF(lkm < 5, \"1-4\", MROUND(lkm, 3)))",
              ""
            ],
            "displayFolder": "Läpäisy"
          },
          {
            "name": "Työlliset",
            "expression": "CALCULATE([1 v. tutkinnon jälkeen], FILTER(Muuttujat, OR([paaskoodi]= \"1\", [paaskoodi] = \"2\")))",
            "formatString": "#,0",
            "displayFolder": "Työllistyminen"
          },
          {
            "name": "Suoritetut tutkinnot alkuperäisessä tutkintolajissa",
            "expression": "CALCULATE([Henkilöt], FILTER(Muuttujat, [Opintojen kulku] = \"Tutkinto alkuperäisessä tutkintolajissa\"))",
            "formatString": "#,0",
            "displayFolder": "Läpäisy"
          },
          {
            "name": "Alkuperäisessä tutkintolajissa tutkinnon suorittaneiden osuus kaikista aloittaneista",
            "expression": [
              "",
              "var osa = [Suoritetut tutkinnot alkuperäisessä tutkintolajissa]",
              "var kaikki = [Henkilöt]",
              "return IF(osa = BLANK(), BLANK(),\t",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, \"0.0 %\"",
              ", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\")))",
              ", osa / kaikki)))"
            ],
            "formatString": "#,0.0 %;-#,0.0 %;#,0.0 %",
            "displayFolder": "Läpäisy"
          },
          {
            "name": "Suoritetut tutkinnot missä tahansa tutkintolajissa",
            "expression": "CALCULATE([Henkilöt], FILTER(Muuttujat, OR(OR([Opintojen kulku] = \"Tutkinto alkuperäisessä tutkintolajissa\", [Opintojen kulku] =\"Tutkinto muussa tutkintolajissa\"), [Opintojen kulku] = \"Tutkinto muussa tutkintolajissa, kandidaatin tutkinto\")))",
            "formatString": "#,0",
            "displayFolder": "Läpäisy"
          },
          {
            "name": "Missä tahansa tutkintolajissa tutkinnon suorittaneiden osuus kaikista aloittaneista",
            "expression": [
              "",
              "var osa = [Suoritetut tutkinnot missä tahansa tutkintolajissa]",
              "var kaikki = [Henkilöt]",
              "return IF(osa = BLANK(), BLANK(),\t",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, \"0.0 %\"",
              ", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\")))",
              ", osa / kaikki)))"
            ],
            "formatString": "#,0.0 %;-#,0.0 %;#,0.0 %",
            "displayFolder": "Läpäisy"
          },
          {
            "name": "Suoritetut tutkinnot missä tahansa ammatillisen koulutuksen tutkintolajissa",
            "expression": "CALCULATE([Henkilöt], FILTER(Muuttujat, OR([Suoritettu tutkinto] = \"Ammatillinen perustutkinto\", [Suoritettu tutkinto] =\"Ammatillinen lisäkoulutus ammattitutkinto tai erikoisammattitutkinto\")))",
            "formatString": "#,0",
            "displayFolder": "Läpäisy"
          },
          {
            "name": "Missä tahansa amm. koulutuksen tutkintolajissa tutkinnon suorittaneiden osuus kaikista aloittaneista",
            "expression": [
              "",
              "var osa = [Suoritetut tutkinnot missä tahansa ammatillisen koulutuksen tutkintolajissa]",
              "var kaikki = [Henkilöt]",
              "return IF(osa = BLANK(), BLANK(),\t",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, \"0.0 %\"",
              ", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\")))",
              ", osa / kaikki)))"
            ],
            "formatString": "#,0.0 %;-#,0.0 %;#,0.0 %",
            "displayFolder": "Läpäisy"
          },
          {
            "name": "Uudet opiskelijat",
            "expression": [
              "",
              "var lkm = SUM([aloit2])",
              "return IF(lkm = 0, BLANK(), IF(lkm < 5, \"1-4\", MROUND(lkm, 3)))",
              ""
            ],
            "displayFolder": "Opiskelijat ja tutkinnot"
          },
          {
            "name": "Opiskelijat",
            "expression": [
              "",
              "var lkm = SUM([opisk2])",
              "return IF(lkm = 0, BLANK(), IF(lkm < 5, \"1-4\", MROUND(lkm, 3)))",
              ""
            ],
            "displayFolder": "Opiskelijat ja tutkinnot"
          },
          {
            "name": "Tutkinnot",
            "expression": [
              "",
              "var lkm = SUM([tutk2])",
              "return IF(lkm = 0, BLANK(), IF(lkm < 5, \"1-4\", MROUND(lkm, 3)))",
              ""
            ],
            "displayFolder": "Opiskelijat ja tutkinnot"
          },
          {
            "name": "Työllisten osuus tutkinnon suorittaneista",
            "expression": [
              "",
              "var osa  = [Työlliset]",
              "var kaikki = [1 v. tutkinnon jälkeen]",
              "return IF(osa = BLANK(), BLANK(),\t",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, \"0.0 %\"",
              ", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\")))",
              ", osa / kaikki)))"
            ],
            "formatString": "#,0.0 %;-#,0.0 %;#,0.0 %",
            "displayFolder": "Työllistyminen"
          },
          {
            "name": "Keskiarvo - työllisten osuus",
            "expression": [
              "",
              "var osa = CALCULATE([Työlliset], ALL(Muuttujat[Koulutuksen järjestäjä]), ALL(Muuttujat[Koulutuksen maakunta]), ALL(Muuttujat[Koulutusala (2002)]), ALL(Muuttujat[Koulutusala, taso 1]))",
              "var kaikki = CALCULATE([1 v. tutkinnon jälkeen], ALL(Muuttujat[Koulutuksen järjestäjä]), ALL(Muuttujat[Koulutuksen maakunta]), ALL(Muuttujat[Koulutusala (2002)]), ALL(Muuttujat[Koulutusala, taso 1]))",
              "return IF(osa = BLANK(), BLANK(),\t",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, \"0.0 %\"",
              ", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\")))",
              ", osa / kaikki)))"
            ],
            "formatString": "#,0.0 %;-#,0.0 %;#,0.0 %",
            "displayFolder": "Keskiarvot"
          },
          {
            "name": "Keskiarvo - läpäisy",
            "expression": [
              "",
              "var osa = CALCULATE([Suoritetut tutkinnot alkuperäisessä tutkintolajissa], ALL(Muuttujat[Koulutuksen järjestäjä]), ALL(Muuttujat[Koulutuksen maakunta]), ALL(Muuttujat[Koulutusala (2002)]), ALL(Muuttujat[Koulutusala, taso 1]))",
              "var kaikki = CALCULATE([Henkilöt], ALL(Muuttujat[Koulutuksen järjestäjä]), ALL(Muuttujat[Koulutuksen maakunta]), ALL(Muuttujat[Koulutusala (2002)]), ALL(Muuttujat[Koulutusala, taso 1]))",
              "return IF(osa = BLANK(), BLANK(),\t",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, \"0.0 %\"",
              ", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\")))",
              ", osa / kaikki)))"
            ],
            "formatString": "#,0.0 %;-#,0.0 %;#,0.0 %",
            "displayFolder": "Keskiarvot"
          },
          {
            "name": "Aloituspaikat",
            "expression": [
              "",
              "var lkm = sum([aloitp2])",
              "return IF(lkm = 0, BLANK(), IF(lkm < 5, \"1-4\", MROUND(lkm, 3)))",
              ""
            ],
            "displayFolder": "Haku"
          },
          {
            "name": "Ensisijaiset hakijat",
            "expression": [
              "",
              "var lkm = SUM([ensisij2])",
              "return IF(lkm = 0, BLANK(), IF(lkm < 5, \"1-4\", MROUND(lkm, 3)))",
              ""
            ],
            "displayFolder": "Haku"
          },
          {
            "name": "Ensisijaiset hakijat / Aloituspaikat",
            "expression": [
              "",
              "var hakijat = [Ensisijaiset hakijat]",
              "var paikat= [Aloituspaikat]",
              "return IF(OR(hakijat= BLANK(), paikat = BLANK()),  BLANK(),",
              "\tIF(hakijat = \"1-4\", IF(paikat= \"1-4\", CONCATENATE(FORMAT(1 / 4, \"0.0 – \"), FORMAT(4 / 1, \"0.0\")),",
              "\t\t\t   CONCATENATE(FORMAT(1 / paikat, \"0.0 – \"), FORMAT(4 / paikat, \"0.0\"))),",
              "\t     IF(paikat = \"1-4\", CONCATENATE(FORMAT(hakijat / 4, \"0.0 – \"), FORMAT(hakijat / 1, \"0.0\")),",
              "\t          hakijat / paikat)))"
            ],
            "formatString": "0.0",
            "displayFolder": "Haku"
          },
          {
            "name": "Keskiarvo - ensisijaiset hakijat / aloituspaikat",
            "expression": [
              "",
              "var hakijat = CALCULATE([Ensisijaiset hakijat], ALL(Muuttujat[Koulutuksen järjestäjä]), ALL(Muuttujat[Koulutuksen maakunta]), ALL(Muuttujat[Koulutusala (2002)]), ALL(Muuttujat[Koulutusala, taso 1]))",
              "var paikat= CALCULATE([Aloituspaikat], ALL(Muuttujat[Koulutuksen järjestäjä]), ALL(Muuttujat[Koulutuksen maakunta]), ALL(Muuttujat[Koulutusala (2002)]), ALL(Muuttujat[Koulutusala, taso 1]))",
              "return IF(OR(hakijat= BLANK(), paikat = BLANK()),  BLANK(),",
              "\tIF(hakijat = \"1-4\", IF(paikat= \"1-4\", CONCATENATE(FORMAT(1 / 4, \"0.0 – \"), FORMAT(4 / 1, \"0.0\")),",
              "\t\t\t   CONCATENATE(FORMAT(1 / paikat, \"0.0 – \"), FORMAT(4 / paikat, \"0.0\"))),",
              "\t     IF(paikat = \"1-4\", CONCATENATE(FORMAT(hakijat / 4, \"0.0 – \"), FORMAT(hakijat / 1, \"0.0\")),",
              "\t          hakijat / paikat)))"
            ],
            "formatString": "0.0",
            "displayFolder": "Keskiarvot"
          },
          {
            "name": "1 v. tutkinnon jälkeen_s",
            "expression": "IF([kytkin]=0, BLANK(), SUM([lkm_1vr2]))",
            "formatString": "#,0"
          },
          {
            "name": "Työlliset_s",
            "expression": "IF([kytkin]=0, BLANK(), CALCULATE([1 v. tutkinnon jälkeen_s], FILTER(Muuttujat, OR([paaskoodi]= \"1\", [paaskoodi] = \"2\"))))",
            "formatString": "#,0"
          },
          {
            "name": "Työllisten osuus tutkinnon suorittaneista_s",
            "expression": "IF([kytkin]=0, BLANK(), [Työlliset_s]/[1 v. tutkinnon jälkeen_s])",
            "formatString": "#,0.0 %;-#,0.0 %;#,0.0 %"
          },
          {
            "name": "Keskiarvo - työllisten osuus_s",
            "expression": "IF([kytkin]=0, BLANK(), CALCULATE([Työlliset_s], ALL(Muuttujat[Koulutuksen järjestäjä]), ALL(Muuttujat[Koulutuksen maakunta]), ALL(Muuttujat[Koulutusala (2002)]), ALL(Muuttujat[Koulutusala, taso 1]))/CALCULATE([1 v. tutkinnon jälkeen_s], ALL(Muuttujat[Koulutuksen järjestäjä]), ALL(Muuttujat[Koulutuksen maakunta]), ALL(Muuttujat[Koulutusala (2002)]), ALL(Muuttujat[Koulutusala, taso 1])))",
            "formatString": "#,0.0 %;-#,0.0 %;#,0.0 %"
          },
          {
            "name": "Aloituspaikat_s",
            "expression": "IF([kytkin]=0, BLANK(), sum([aloitp2]))",
            "formatString": "#,0"
          },
          {
            "name": "Ensisijaiset hakijat_s",
            "expression": "IF([kytkin]=0, BLANK(), SUM([ensisij2]))",
            "formatString": "#,0"
          },
          {
            "name": "Ensisijaiset hakijat / Aloituspaikat_s",
            "expression": "IF([kytkin]=0, BLANK(), [Ensisijaiset hakijat_s]/[Aloituspaikat_s])",
            "formatString": "0.0"
          },
          {
            "name": "Keskiarvo - ensisijaiset hakijat / aloituspaikat_s",
            "expression": "IF([kytkin]=0, BLANK(), CALCULATE([Ensisijaiset hakijat_s], ALL(Muuttujat[Koulutuksen järjestäjä]), ALL(Muuttujat[Koulutuksen maakunta]), ALL(Muuttujat[Koulutusala (2002)]), ALL(Muuttujat[Koulutusala, taso 1]))/CALCULATE([Aloituspaikat_s], ALL(Muuttujat[Koulutuksen järjestäjä]), ALL(Muuttujat[Koulutuksen maakunta]), ALL(Muuttujat[Koulutusala (2002)]), ALL(Muuttujat[Koulutusala, taso 1])))",
            "formatString": "0.0"
          },
          {
            "name": "Henkilöt_s",
            "expression": "IF([kytkin]=0, BLANK(), SUM([lkm_int2]))",
            "formatString": "#,0"
          },
          {
            "name": "Suoritetut tutkinnot alkuperäisessä tutkintolajissa_s",
            "expression": "IF([kytkin]=0, BLANK(), CALCULATE([Henkilöt_s], FILTER(Muuttujat, [Opintojen kulku] = \"Tutkinto alkuperäisessä tutkintolajissa\")))",
            "formatString": "#,0"
          },
          {
            "name": "Alkuperäisessä tutkintolajissa tutkinnon suorittaneiden osuus kaikista aloittaneista_s",
            "expression": "IF([kytkin]=0, BLANK(), [Suoritetut tutkinnot alkuperäisessä tutkintolajissa_s]/[Henkilöt_s])",
            "formatString": "#,0.0 %;-#,0.0 %;#,0.0 %"
          },
          {
            "name": "Suoritetut tutkinnot missä tahansa tutkintolajissa_s",
            "expression": "IF([kytkin]=0, BLANK(), CALCULATE([Henkilöt_s], FILTER(Muuttujat, OR(OR([Opintojen kulku] = \"Tutkinto alkuperäisessä tutkintolajissa\", [Opintojen kulku] =\"Tutkinto muussa tutkintolajissa\"), [Opintojen kulku] = \"Tutkinto muussa tutkintolajissa, kandidaatin tutkinto\"))))",
            "formatString": "#,0"
          },
          {
            "name": "Missä tahansa tutkintolajissa tutkinnon suorittaneiden osuus kaikista aloittaneista_s",
            "expression": "IF([kytkin]=0, BLANK(), [Suoritetut tutkinnot missä tahansa tutkintolajissa_s]/[Henkilöt_s])",
            "formatString": "#,0.0 %;-#,0.0 %;#,0.0 %"
          },
          {
            "name": "Suoritetut tutkinnot missä tahansa ammatillisen koulutuksen tutkintolajissa_s",
            "expression": "IF([kytkin]=0, BLANK(), CALCULATE([Henkilöt_s], FILTER(Muuttujat, OR([Suoritettu tutkinto] = \"Ammatillinen perustutkinto\", [Suoritettu tutkinto] =\"Ammatillinen lisäkoulutus ammattitutkinto tai erikoisammattitutkinto\"))))",
            "formatString": "#,0"
          },
          {
            "name": "Missä tahansa amm. koulutuksen tutkintolajissa tutkinnon suorittaneiden osuus kaikista aloit_s",
            "expression": "IF([kytkin]=0, BLANK(), [Suoritetut tutkinnot missä tahansa ammatillisen koulutuksen tutkintolajissa_s]/[Henkilöt_s])",
            "formatString": "#,0.0 %;-#,0.0 %;#,0.0 %"
          },
          {
            "name": "Keskiarvo - läpäisy_s",
            "expression": "IF([kytkin]=0, BLANK(), CALCULATE([Suoritetut tutkinnot alkuperäisessä tutkintolajissa_s], ALL(Muuttujat[Koulutuksen järjestäjä]), ALL(Muuttujat[Koulutuksen maakunta]), ALL(Muuttujat[Koulutusala (2002)]), ALL(Muuttujat[Koulutusala, taso 1]))/CALCULATE([Henkilöt_s], ALL(Muuttujat[Koulutuksen järjestäjä]), ALL(Muuttujat[Koulutuksen maakunta]), ALL(Muuttujat[Koulutusala (2002)]), ALL(Muuttujat[Koulutusala, taso 1])))",
            "formatString": "#,0.0 %;-#,0.0 %;#,0.0 %"
          },
          {
            "name": "Uudet opiskelijat_s",
            "expression": "IF([kytkin]=0, BLANK(), SUM([aloit2]))",
            "formatString": "#,0"
          },
          {
            "name": "Opiskelijat_s",
            "expression": "IF([kytkin]=0, BLANK(), SUM([opisk2]))",
            "formatString": "#,0"
          },
          {
            "name": "Tutkinnot_s",
            "expression": "IF([kytkin]=0, BLANK(), SUM([tutk2]))",
            "formatString": "#,0"
          },
          {
            "name": "kytkin",
            "expression": "IF(LEFT(USERNAME(), 4) = \"DWI\\\", 1, 0)",
            "formatString": "0",
            "isHidden": true
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "v_f_tab_ammatillinen_scorecard"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[v_f_tab_ammatillinen_scorecard].* FROM [dbo].[v_f_tab_ammatillinen_scorecard] "
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Tilastovuosi</string>",
              "      </key>",
              "      <value>",
              "        <int>86</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Aloituslukuvuosi</string>",
              "      </key>",
              "      <value>",
              "        <int>106</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Aloitusvuosi</string>",
              "      </key>",
              "      <value>",
              "        <int>87</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Aloituslukukausi</string>",
              "      </key>",
              "      <value>",
              "        <int>105</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tarkastelujakso</string>",
              "      </key>",
              "      <value>",
              "        <int>105</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Pääasiallinen toiminta</string>",
              "      </key>",
              "      <value>",
              "        <int>132</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Hallinnonala</string>",
              "      </key>",
              "      <value>",
              "        <int>87</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koko tutkinto/tutkinnon osa</string>",
              "      </key>",
              "      <value>",
              "        <int>162</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Opintojen kulku</string>",
              "      </key>",
              "      <value>",
              "        <int>104</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Suoritettu tutkinto</string>",
              "      </key>",
              "      <value>",
              "        <int>118</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusala (2002)</string>",
              "      </key>",
              "      <value>",
              "        <int>120</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusala, taso 1</string>",
              "      </key>",
              "      <value>",
              "        <int>122</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Järjestämistapa</string>",
              "      </key>",
              "      <value>",
              "        <int>106</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Järjestämismuoto</string>",
              "      </key>",
              "      <value>",
              "        <int>114</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tutkintotyyppi</string>",
              "      </key>",
              "      <value>",
              "        <int>99</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutuksen maakunta</string>",
              "      </key>",
              "      <value>",
              "        <int>138</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutuksen järjestäjä</string>",
              "      </key>",
              "      <value>",
              "        <int>137</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj_tarkastelujakso</string>",
              "      </key>",
              "      <value>",
              "        <int>125</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj_paas</string>",
              "      </key>",
              "      <value>",
              "        <int>75</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>paaskoodi</string>",
              "      </key>",
              "      <value>",
              "        <int>78</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj_hallinnonala</string>",
              "      </key>",
              "      <value>",
              "        <int>108</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj_kokoosa</string>",
              "      </key>",
              "      <value>",
              "        <int>91</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj_1a</string>",
              "      </key>",
              "      <value>",
              "        <int>64</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj_1c</string>",
              "      </key>",
              "      <value>",
              "        <int>63</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj_koulala2002</string>",
              "      </key>",
              "      <value>",
              "        <int>109</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj_koulalataso1</string>",
              "      </key>",
              "      <value>",
              "        <int>112</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj_jarjestamistapa</string>",
              "      </key>",
              "      <value>",
              "        <int>126</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj_maakunta</string>",
              "      </key>",
              "      <value>",
              "        <int>99</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>kouljarjkoodi</string>",
              "      </key>",
              "      <value>",
              "        <int>90</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>lkm_1vr2</string>",
              "      </key>",
              "      <value>",
              "        <int>73</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>lkm_int2</string>",
              "      </key>",
              "      <value>",
              "        <int>69</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>aloit2</string>",
              "      </key>",
              "      <value>",
              "        <int>56</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>opisk2</string>",
              "      </key>",
              "      <value>",
              "        <int>60</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tutk2</string>",
              "      </key>",
              "      <value>",
              "        <int>55</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>aloitp2</string>",
              "      </key>",
              "      <value>",
              "        <int>62</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ensisij2</string>",
              "      </key>",
              "      <value>",
              "        <int>65</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Tilastovuosi</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Aloituslukuvuosi</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Aloitusvuosi</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Aloituslukukausi</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tarkastelujakso</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Pääasiallinen toiminta</string>",
              "      </key>",
              "      <value>",
              "        <int>5</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Hallinnonala</string>",
              "      </key>",
              "      <value>",
              "        <int>6</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koko tutkinto/tutkinnon osa</string>",
              "      </key>",
              "      <value>",
              "        <int>7</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Opintojen kulku</string>",
              "      </key>",
              "      <value>",
              "        <int>8</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Suoritettu tutkinto</string>",
              "      </key>",
              "      <value>",
              "        <int>9</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusala (2002)</string>",
              "      </key>",
              "      <value>",
              "        <int>10</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusala, taso 1</string>",
              "      </key>",
              "      <value>",
              "        <int>11</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Järjestämistapa</string>",
              "      </key>",
              "      <value>",
              "        <int>12</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Järjestämismuoto</string>",
              "      </key>",
              "      <value>",
              "        <int>13</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tutkintotyyppi</string>",
              "      </key>",
              "      <value>",
              "        <int>14</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutuksen maakunta</string>",
              "      </key>",
              "      <value>",
              "        <int>15</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutuksen järjestäjä</string>",
              "      </key>",
              "      <value>",
              "        <int>16</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj_tarkastelujakso</string>",
              "      </key>",
              "      <value>",
              "        <int>17</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj_paas</string>",
              "      </key>",
              "      <value>",
              "        <int>18</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>paaskoodi</string>",
              "      </key>",
              "      <value>",
              "        <int>19</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj_hallinnonala</string>",
              "      </key>",
              "      <value>",
              "        <int>20</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj_kokoosa</string>",
              "      </key>",
              "      <value>",
              "        <int>21</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj_1a</string>",
              "      </key>",
              "      <value>",
              "        <int>22</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj_1c</string>",
              "      </key>",
              "      <value>",
              "        <int>23</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj_koulala2002</string>",
              "      </key>",
              "      <value>",
              "        <int>24</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj_koulalataso1</string>",
              "      </key>",
              "      <value>",
              "        <int>25</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj_jarjestamistapa</string>",
              "      </key>",
              "      <value>",
              "        <int>26</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj_maakunta</string>",
              "      </key>",
              "      <value>",
              "        <int>27</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>kouljarjkoodi</string>",
              "      </key>",
              "      <value>",
              "        <int>28</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>lkm_1vr2</string>",
              "      </key>",
              "      <value>",
              "        <int>29</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>lkm_int2</string>",
              "      </key>",
              "      <value>",
              "        <int>30</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>aloit2</string>",
              "      </key>",
              "      <value>",
              "        <int>31</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>opisk2</string>",
              "      </key>",
              "      <value>",
              "        <int>32</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tutk2</string>",
              "      </key>",
              "      <value>",
              "        <int>33</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>aloitp2</string>",
              "      </key>",
              "      <value>",
              "        <int>34</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ensisij2</string>",
              "      </key>",
              "      <value>",
              "        <int>35</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>ensisij2</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      }
    ],
    "perspectives": [
      {
        "name": "Scorecard",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Aloituslukukausi"
              },
              {
                "name": "Hallinnonala"
              },
              {
                "name": "Järjestämismuoto"
              },
              {
                "name": "Järjestämistapa"
              },
              {
                "name": "Koko tutkinto/tutkinnon osa"
              },
              {
                "name": "kouljarjkoodi"
              },
              {
                "name": "Koulutuksen järjestäjä"
              },
              {
                "name": "Koulutuksen maakunta"
              },
              {
                "name": "Koulutusala (2002)"
              },
              {
                "name": "Koulutusala, taso 1"
              },
              {
                "name": "Tarkastelujakso"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Tutkintotyyppi"
              }
            ],
            "measures": [
              {
                "name": "1 v. tutkinnon jälkeen"
              },
              {
                "name": "Alkuperäisessä tutkintolajissa tutkinnon suorittaneiden osuus kaikista aloittaneista"
              },
              {
                "name": "Aloituspaikat"
              },
              {
                "name": "Ensisijaiset hakijat"
              },
              {
                "name": "Ensisijaiset hakijat / Aloituspaikat"
              },
              {
                "name": "Henkilöt"
              },
              {
                "name": "Keskiarvo - ensisijaiset hakijat / aloituspaikat"
              },
              {
                "name": "Keskiarvo - läpäisy"
              },
              {
                "name": "Keskiarvo - työllisten osuus"
              },
              {
                "name": "Missä tahansa amm. koulutuksen tutkintolajissa tutkinnon suorittaneiden osuus kaikista aloittaneista"
              },
              {
                "name": "Missä tahansa tutkintolajissa tutkinnon suorittaneiden osuus kaikista aloittaneista"
              },
              {
                "name": "Opiskelijat"
              },
              {
                "name": "Suoritetut tutkinnot alkuperäisessä tutkintolajissa"
              },
              {
                "name": "Suoritetut tutkinnot missä tahansa ammatillisen koulutuksen tutkintolajissa"
              },
              {
                "name": "Suoritetut tutkinnot missä tahansa tutkintolajissa"
              },
              {
                "name": "Tutkinnot"
              },
              {
                "name": "Työlliset"
              },
              {
                "name": "Työllisten osuus tutkinnon suorittaneista"
              },
              {
                "name": "Uudet opiskelijat"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      }
    ],
    "roles": [
      {
        "name": "Luku",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "DWI\\T_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1732"
          },
          {
            "memberName": "DWI\\T_VIPU_SSAS_DB_R",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1751"
          },
          {
            "memberName": "DWI\\T_VIPU_SSAS_DB_R_TK",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1753"
          },
          {
            "memberName": "DWI\\P_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1733"
          },
          {
            "memberName": "DWI\\P_VIPU_SSAS_DB_R",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1752"
          },
          {
            "memberName": "DWI\\P_VIPU_SSAS_DB_R_TK",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1754"
          },
          {
            "memberName": "DWI\\Z_P_Antero_Full_Read_TAB",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-2272"
          }
        ]
      },
      {
        "name": "Kehitys",
        "modelPermission": "administrator",
        "members": [
          {
            "memberName": "DWI\\T_VIPU_TABOKM_DB_VipunenTK_Dev",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1364"
          },
          {
            "memberName": "DWI\\T_VIPU_TAB_DB_VipunenTK_Dev",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1363"
          }
        ]
      }
    ]
  },
  "id": "SemanticModel"
}
