ALTER PROCEDURE dbo.p_lataa_f_amk_talous_1_tuloslaskelma AS

TRUNCATE TABLE ANTERO_DW.dbo.f_amk_talous_1_tuloslaskelma

INSERT INTO dbo.f_amk_talous_1_tuloslaskelma
           (d_amk_id
           ,tilikausi
           ,aineistotyyppi
           ,liikevaihto
           ,kvarastojenl
           ,omkaytt
           ,muuttuot
           ,matyht
           ,aitata
           ,ostotilaik
           ,varastlis
           ,ulkpal
           ,hkulutyht
           ,palkat
           ,hsivukulut
           ,elakekulut
           ,msivukulut
           ,poiarvoyht
           ,poistot
           ,aalennukset
           ,vvpaalennukset
           ,muutkulut
           ,lvoitto
           ,konstuot
           ,tuotosuu
           ,tuotsamakons
           ,tuototmuilt
           ,muutkorksamkons
           ,muutkorkmuilt
           ,arvovastaasijo
           ,arvovaihtvastrah
           ,korkrahkulukons
           ,korkrahkulumuut
           ,voitto
           ,satyht
           ,sattuot
           ,satkulut
           ,voitenveroja
           ,poistoero
           ,vapehtvara
           ,rahasiirt
           ,tulovero
           ,muutverot
           ,tilvoitto
           ,okmperus
           ,akatemia
           ,tekes
           ,muuokm
           ,sosturvarah
           ,muuvaltio
           ,kunnat
           ,vottavoittelematon
           ,kotiyritys
           ,kotirah
           ,kotitalous
           ,eurah
           ,eurahyrit
           ,eurahmuu
           ,muuulkyritys
           ,muuulkmuurah
           ,maksuasetus
           ,muuliikevaihto
           ,source)
SELECT d1.id AS d_amk_id
	  ,TILIK
      ,Aineistotyyppi_osa_1
      ,LIIKEVAIHTO
      ,KVARASTOJENL
      ,OMKAYTT
      ,MUUTTUOT
      ,MATYHT
      ,AITATA
      ,OSTOTILAIK
      ,VARASTLIS
      ,ULKPAL
      ,HKULUTYHT
      ,PALKAT
      ,HSIVUKULUT
      ,ELAKEKULUT
      ,MSIVUKULUT
      ,POIARVOYHT
      ,POISTOT
      ,AALENNUKSET
      ,VVPAALENNUKSET
      ,MUUTKULUT
      ,LVOITTO
      ,KONSTUOT
      ,TUOTOSUU
      ,TUOTSAMAKONS
      ,TUOTOTMUILT
      ,MUUTKORKSAMKONS
      ,MUUTKORKMUILT
      ,ARVOVASTAASIJO
      ,ARVOVAIHTVASTRAH
      ,KORKRAHKULUKONS
      ,KORKRAHKULUMUUT
      ,VOITTO
      ,SATYHT
      ,SATTUOT
      ,SATKULUT
      ,VOITENVEROJA
      ,POISTOERO
      ,VAPEHTVARA
      ,RAHASIIRT
      ,TULOVERO
      ,MUUTVEROT
      ,TILVOITTO
      ,OKMPERUS
      ,AKATEMIA
      ,TEKES
      ,MUUOKM
      ,SOSTURVARAH
      ,MUUVALTIO
      ,KUNNAT
      ,VOTTAVOITTELEMATON
      ,KOTIYRITYS
      ,KOTIRAH
      ,KOTITALOUS
      ,EURAH
      ,EURAHYRIT
      ,EURAHMUU
      ,MUUULKYRITYS
      ,MUUULKMUURAH
      ,MAKSUASETUS
      ,MUULIIKEVAIHTO
      ,'ETL: p_lataa_f_amk_talous_1_tuloslaskelma' AS source
  FROM ANTERO_SA.dbo.SA_SUORAT_AMK_TALOUS_1_tuloslaskelma f
  INNER JOIN ANTERO_DW.dbo.d_amk d1 ON f.AMK_koodi = d1.amk_tunnus