{
  "name": "SemanticModel",
  "id": "SemanticModel",
  "compatibilityLevel": 1200,
  "model": {
    "culture": "fi-FI",
    "dataSources": [
      {
        "name": "SqlServer dwitestvipusql VipunenTK",
        "connectionString": "Provider=SQLNCLI11;Data Source=dwitvipusql22;Initial Catalog=VipunenTK;Integrated Security=SSPI;Persist Security Info=false",
        "impersonationMode": "impersonateAccount",
        "account": "dwi\\T_VIPUTK_KUUTIO",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "Muuttujat",
        "columns": [
          {
            "name": "Tilastovuosi",
            "dataType": "string",
            "sourceColumn": "Tilastovuosi"
          },
          {
            "name": "Kunta",
            "dataType": "string",
            "sourceColumn": "Kunta"
          },
          {
            "name": "Maakunta",
            "dataType": "string",
            "sourceColumn": "Maakunta",
            "sortByColumn": "Maakunta järjestys"
          },
          {
            "name": "Sektori",
            "dataType": "string",
            "sourceColumn": "Sektori"
          },
          {
            "name": "Sukupuoli",
            "dataType": "string",
            "sourceColumn": "Sukupuoli",
            "sortByColumn": "Sukupuoli järjestys"
          },
          {
            "name": "Opetussuunnitelma",
            "dataType": "string",
            "sourceColumn": "Opetussuunnitelma"
          },
          {
            "name": "Koulutuslaji",
            "dataType": "string",
            "sourceColumn": "Koulutuslaji"
          },
          {
            "name": "Järjestämistapa",
            "dataType": "string",
            "sourceColumn": "Järjestämistapa"
          },
          {
            "name": "Järjestämismuoto",
            "dataType": "string",
            "sourceColumn": "Järjestämismuoto"
          },
          {
            "name": "Aloittaneet",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Aloittaneet"
          },
          {
            "name": "Väestö 16-18",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Väestö 16-18"
          },
          {
            "name": "Väestö 19-21",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Väestö 19-21"
          },
          {
            "name": "Väestö 25-64",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Väestö 25-64"
          },
          {
            "name": "Väestö 6",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Väestö 6"
          },
          {
            "name": "Väestö 7",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Väestö 7"
          },
          {
            "name": "Maakunta järjestys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Maakunta järjestys"
          },
          {
            "name": "Sukupuoli järjestys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Sukupuoli järjestys"
          },
          {
            "name": "Koulutuksen kieli",
            "dataType": "string",
            "sourceColumn": "Koulutuksen kieli"
          },
          {
            "name": "Äidinkieli",
            "dataType": "string",
            "sourceColumn": "Äidinkieli",
            "sortByColumn": "Äidinkieli järjestys"
          },
          {
            "name": "Äidinkieli järjestys",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Äidinkieli järjestys"
          },
          {
            "name": "Statistikår",
            "dataType": "string",
            "sourceColumn": "Statistikår"
          },
          {
            "name": "Landskap",
            "dataType": "string",
            "sourceColumn": "Landskap"
          },
          {
            "name": "Kön",
            "dataType": "string",
            "sourceColumn": "Kön"
          },
          {
            "name": "Statistical year",
            "dataType": "string",
            "sourceColumn": "Statistical year"
          },
          {
            "name": "Region",
            "dataType": "string",
            "sourceColumn": "Region"
          },
          {
            "name": "Gender",
            "dataType": "string",
            "sourceColumn": "Gender"
          }
        ],
        "partitions": [
          {
            "name": "v_f_tab_indikaattorit_opiskelijat_ikäluokka",
            "source": {
              "query": "SELECT [dbo].[v_f_tab_indikaattorit_opiskelijat_ikäluokka].* FROM [dbo].[v_f_tab_indikaattorit_opiskelijat_ikäluokka]",
              "dataSource": "SqlServer dwitestvipusql VipunenTK"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": "&lt;?xml version=\"1.0\" encoding=\"UTF-16\"?&gt;&lt;Gemini xmlns=\"TableWidgetSerialization\"&gt;&lt;AnnotationContent&gt;&lt;![CDATA[&lt;?xml version=\"1.0\"?&gt;\n&lt;TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\"&gt;\n  &lt;ColumnSuggestedType /&gt;\n  &lt;ColumnFormat /&gt;\n  &lt;ColumnAccuracy /&gt;\n  &lt;ColumnCurrencySymbol /&gt;\n  &lt;ColumnPositivePattern /&gt;\n  &lt;ColumnNegativePattern /&gt;\n  &lt;ColumnWidths&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Tilastovuosi&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;86&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Kunta&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;58&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Maakunta&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;77&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Sektori&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;63&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Sukupuoli&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;75&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Opetussuunnitelma&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;122&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koulutuslaji&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;84&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Järjestämistapa&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;106&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Järjestämismuoto&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;114&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Aloittaneet&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;83&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Väestö 6&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;72&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Väestö 7&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;72&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Väestö 16-18&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;94&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Väestö 19-21&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;94&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Väestö 25-64&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;94&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Maakunta järjestys&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;122&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Sukupuoli järjestys&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;120&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koulutuksen kieli&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;108&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Äidinkieli&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;70&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Äidinkieli järjestys&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;115&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Statistikår&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;78&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Landskap&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;75&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Kön&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;48&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Statistical year&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;101&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Region&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;63&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Gender&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;65&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n  &lt;/ColumnWidths&gt;\n  &lt;ColumnDisplayIndex&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Tilastovuosi&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;0&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Kunta&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;1&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Maakunta&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;2&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Sektori&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;3&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Sukupuoli&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;4&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Opetussuunnitelma&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;5&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koulutuslaji&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;6&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Järjestämistapa&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;7&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Järjestämismuoto&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;8&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Aloittaneet&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;9&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Väestö 6&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;10&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Väestö 7&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;11&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Väestö 16-18&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;12&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Väestö 19-21&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;13&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Väestö 25-64&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;14&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Maakunta järjestys&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;15&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Sukupuoli järjestys&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;16&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koulutuksen kieli&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;17&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Äidinkieli&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;18&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Äidinkieli järjestys&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;19&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Statistikår&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;20&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Landskap&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;21&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Kön&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;22&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Statistical year&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;23&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Region&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;24&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Gender&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;25&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n  &lt;/ColumnDisplayIndex&gt;\n  &lt;ColumnFrozen /&gt;\n  &lt;ColumnChecked&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Väestö 6&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Väestö 7&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Maakunta järjestys&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Sukupuoli järjestys&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koulutuksen kieli&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Äidinkieli&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Äidinkieli järjestys&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Statistikår&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Landskap&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Kön&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Statistical year&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Region&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Gender&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n  &lt;/ColumnChecked&gt;\n  &lt;ColumnFilter /&gt;\n  &lt;SelectionFilter /&gt;\n  &lt;FilterParameters /&gt;\n  &lt;IsSortDescending&gt;false&lt;/IsSortDescending&gt;\n&lt;/TableWidgetGridSerialization&gt;]]&gt;&lt;/AnnotationContent&gt;&lt;/Gemini&gt;"
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Lukion aloittaneet (nuoret)",
            "expression": "var summa = calculate(sum(Muuttujat[Aloittaneet]),Muuttujat[Opetussuunnitelma]=\"nuorten opetussuunnitelma\")\nreturn IF(summa = 0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
            "formatString": "#,0"
          },
          {
            "name": "Lukiokoulutus, nuorten opetussuunnitelma / 16-18-vuotiaiden keskim. ikäluokka",
            "expression": "var uudet = [Lukion aloittaneet (nuoret)]\nvar vuosia = 3\nvar ka = [Keskiarvo 16-18]\nreturn IF(OR(uudet = BLANK(), ka = BLANK()), BLANK(),\nIF(FIND(\"–\", ka, 1, 0) > 0, IF(uudet = \"1-4\", CONCATENATE(FORMAT(1 / (4 / vuosia), \"0.00 – \"), FORMAT(4 / (1 / vuosia), \"0.00\")),\nCONCATENATE(FORMAT(uudet / (4 / vuosia), \"0.00 – \"), FORMAT(uudet / (1 / vuosia), \"0.00\"))),\nIF(uudet = \"1-4\", CONCATENATE(FORMAT(1 / ka, \"0.00 – \"), FORMAT(4 / ka, \"0.00\")),\nuudet / ka)))",
            "formatString": "#,0.00"
          },
          {
            "name": "Keskiarvo 16-18",
            "expression": "var vuosia = 3\nvar lkm = SUMX('Muuttujat', ROUND(vuosia * [Väestö 16-18], 0))\nreturn IF(lkm = 0, BLANK(),\nIF(lkm < 5,  CONCATENATE(FORMAT(1 / vuosia, \"0.00 – \"), FORMAT(4 / vuosia, \"0.00\")),\nMROUND(lkm, 3) / vuosia))",
            "formatString": "#,0.00"
          },
          {
            "name": "Ammtillisen peruskoulutuksen aloittaneet (nuoret)",
            "expression": "var summa = CALCULATE(sum(Muuttujat[Aloittaneet]),Muuttujat[Koulutuslaji]=\"ammatillinen perustutkinto\",Muuttujat[Järjestämismuoto]=\"Oppilaitosmuotoinen koulutus\",Muuttujat[Järjestämistapa]=\"opetussuunnitelmaperusteinen koulutus/tutkinto\")\nreturn IF(summa = 0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
            "formatString": "#,0"
          },
          {
            "name": "Keskiarvo 19-21",
            "expression": "var vuosia = 3\nvar lkm = SUMX('Muuttujat', ROUND(vuosia * [Väestö 19-21], 0))\nreturn IF(lkm = 0, BLANK(),\nIF(lkm < 5,  CONCATENATE(FORMAT(1 / vuosia, \"0.00 – \"), FORMAT(4 / vuosia, \"0.00\")),\nMROUND(lkm, 3) / vuosia))",
            "formatString": "#,0.00"
          },
          {
            "name": "Keskiarvo 25-64",
            "expression": "var vuosia = 40 \nvar lkm = SUMX('Muuttujat', ROUND(vuosia * [Väestö 25-64], 0))\nreturn IF(lkm = 0, BLANK(),\nIF(lkm < 5,  CONCATENATE(FORMAT(1 / vuosia, \"0.00 – \"), FORMAT(4 / vuosia, \"0.00\")),\nMROUND(lkm, 3) / vuosia))",
            "formatString": "#,0.00"
          },
          {
            "name": "Ops-perusteinen oppilaitosmuotoinen amm. pk / 16-18-vuotiaiden keskim. ikäluokka",
            "expression": "var uudet =  [Ammtillisen peruskoulutuksen aloittaneet (nuoret)]\nvar vuosia = 3\nvar ka = [Keskiarvo 16-18]\nreturn IF(OR(uudet = BLANK(), ka = BLANK()), BLANK(),\nIF(FIND(\"–\", ka, 1, 0) > 0, IF(uudet = \"1-4\", CONCATENATE(FORMAT(1 / (4 / vuosia), \"0.00 – \"), FORMAT(4 / (1 / vuosia), \"0.00\")),\nCONCATENATE(FORMAT(uudet / (4 / vuosia), \"0.00 – \"), FORMAT(uudet / (1 / vuosia), \"0.00\"))),\nIF(uudet = \"1-4\", CONCATENATE(FORMAT(1 / ka, \"0.00 – \"), FORMAT(4 / ka, \"0.00\")),\nuudet / ka)))",
            "formatString": "0.00"
          },
          {
            "name": "Näyttötutkintoon valmistavan peruskoulutuksen uudet opiskelijat (oppilaitosmuotoinen)",
            "expression": "var summa = CALCULATE(sum([Aloittaneet]),Muuttujat[Koulutuslaji]=\"ammatillinen perustutkinto\",Muuttujat[Järjestämistapa]=\"näyttötutkintoon valmistava koulutus/tutkinto\",Muuttujat[Järjestämismuoto]=\"Oppilaitosmuotoinen koulutus\")\nreturn IF(summa = 0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
            "formatString": "#,0"
          },
          {
            "name": "Näyttötutkintoon valmistava amm. pk, oppilaitosm. / 25-64-vuotiaiden keskim. ikäluokka",
            "expression": "var uudet =  [Näyttötutkintoon valmistavan peruskoulutuksen uudet opiskelijat (oppilaitosmuotoinen)]\nvar vuosia = 40\nvar ka = [Keskiarvo 25-64]\nreturn IF(OR(uudet = BLANK(), ka = BLANK()), BLANK(),\nIF(FIND(\"–\", ka, 1, 0) > 0, IF(uudet = \"1-4\", CONCATENATE(FORMAT(1 / (4 / vuosia), \"0.00 – \"), FORMAT(4 / (1 / vuosia), \"0.00\")),\nCONCATENATE(FORMAT(uudet / (4 / vuosia), \"0.00 – \"), FORMAT(uudet / (1 / vuosia), \"0.00\"))),\nIF(uudet = \"1-4\", CONCATENATE(FORMAT(1 / ka, \"0.00 – \"), FORMAT(4 / ka, \"0.00\")),\nuudet / ka)))",
            "formatString": "0.00"
          },
          {
            "name": "Näyttötutkintoon valmistavan peruskoulutuksen uudet opiskelijat (oppisopimus)",
            "expression": "var summa = CALCULATE(sum([Aloittaneet]),Muuttujat[Koulutuslaji]=\"ammatillinen perustutkinto\",Muuttujat[Järjestämistapa]=\"näyttötutkintoon valmistava koulutus/tutkinto\",Muuttujat[Järjestämismuoto]=\"Oppisopimuskoulutus\")\nreturn IF(summa = 0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))"
          },
          {
            "name": "Näyttötutkintoon valmistava amm. pk, oppis. / 25-64-vuotiaiden keskim. ikäluokka",
            "expression": "var uudet =  [Näyttötutkintoon valmistavan peruskoulutuksen uudet opiskelijat (oppisopimus)]\nvar vuosia = 40\nvar ka = [Keskiarvo 25-64]\nreturn IF(OR(uudet = BLANK(), ka = BLANK()), BLANK(),\nIF(FIND(\"–\", ka, 1, 0) > 0, IF(uudet = \"1-4\", CONCATENATE(FORMAT(1 / (4 / vuosia), \"0.00 – \"), FORMAT(4 / (1 / vuosia), \"0.00\")),\nCONCATENATE(FORMAT(uudet / (4 / vuosia), \"0.00 – \"), FORMAT(uudet / (1 / vuosia), \"0.00\"))),\nIF(uudet = \"1-4\", CONCATENATE(FORMAT(1 / ka, \"0.00 – \"), FORMAT(4 / ka, \"0.00\")),\nuudet / ka)))",
            "formatString": "0.00"
          },
          {
            "name": "Ammatti- ja erikoisammattitutkinnon uudet opiskelijat (oppisopimus)",
            "expression": "var summa = CALCULATE(sum([Aloittaneet]),OR(Muuttujat[Koulutuslaji]=\"Ammattitutkinto\",Muuttujat[Koulutuslaji]=\"Erikoisammattitutkinto\"),Muuttujat[Järjestämismuoto]=\"Oppisopimuskoulutus\")\nreturn IF(summa = 0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
            "formatString": "#,0"
          },
          {
            "name": "Ammatti- ja erikoisammattitutkinnon uudet opiskelijat (oppilaitosmuotoinen)",
            "expression": "var summa = CALCULATE(sum([Aloittaneet]),OR(Muuttujat[Koulutuslaji]=\"Ammattitutkinto\",Muuttujat[Koulutuslaji]=\"Erikoisammattitutkinto\"),Muuttujat[Järjestämismuoto]=\"Oppilaitosmuotoinen koulutus\")\nreturn IF(summa = 0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
            "formatString": "#,0"
          },
          {
            "name": "Amm. ja erikoisamm. tutkintoihin valmistava, oppilaitosm. / 25-64-vuotiaiden keskim. ikäluokka",
            "expression": "var uudet =  [Ammatti- ja erikoisammattitutkinnon uudet opiskelijat (oppilaitosmuotoinen)]\nvar vuosia = 40\nvar ka = [Keskiarvo 25-64]\nreturn IF(OR(uudet = BLANK(), ka = BLANK()), BLANK(),\nIF(FIND(\"–\", ka, 1, 0) > 0, IF(uudet = \"1-4\", CONCATENATE(FORMAT(1 / (4 / vuosia), \"0.00 – \"), FORMAT(4 / (1 / vuosia), \"0.00\")),\nCONCATENATE(FORMAT(uudet / (4 / vuosia), \"0.00 – \"), FORMAT(uudet / (1 / vuosia), \"0.00\"))),\nIF(uudet = \"1-4\", CONCATENATE(FORMAT(1 / ka, \"0.00 – \"), FORMAT(4 / ka, \"0.00\")),\nuudet / ka)))",
            "formatString": "0.00"
          },
          {
            "name": "Amm. ja erikoisamm. tutkintoihin valmistava, oppis. / 25-64-vuotiaiden keskim. ikäluokka",
            "expression": "var uudet =  [Ammatti- ja erikoisammattitutkinnon uudet opiskelijat (oppisopimus)]\nvar vuosia = 40\nvar ka = [Keskiarvo 25-64]\nreturn IF(OR(uudet = BLANK(), ka = BLANK()), BLANK(),\nIF(FIND(\"–\", ka, 1, 0) > 0, IF(uudet = \"1-4\", CONCATENATE(FORMAT(1 / (4 / vuosia), \"0.00 – \"), FORMAT(4 / (1 / vuosia), \"0.00\")),\nCONCATENATE(FORMAT(uudet / (4 / vuosia), \"0.00 – \"), FORMAT(uudet / (1 / vuosia), \"0.00\"))),\nIF(uudet = \"1-4\", CONCATENATE(FORMAT(1 / ka, \"0.00 – \"), FORMAT(4 / ka, \"0.00\")),\nuudet / ka)))",
            "formatString": "0.00"
          },
          {
            "name": "Ammattikorkeakoulutuksen uudet opiskelijat (nuoret)",
            "expression": "var summa = calculate(sum([Aloittaneet]),Muuttujat[Koulutuslaji]=\"Ammattikorkeakoulututkinto (päivätoteutus)\")\nreturn IF(summa = 0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
            "formatString": "#,0"
          },
          {
            "name": "Ammattikorkeakoulutuksen uudet opiskelijat (aikuiset)",
            "expression": "var summa = calculate(sum([Aloittaneet]),Muuttujat[Koulutuslaji]=\"Ammattikorkeakoulututkinto (monimuotototeutus)\")\nreturn IF(summa = 0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
            "formatString": "#,0"
          },
          {
            "name": "Amk-tutkinto / 19-21-vuotiaiden keskim. ikäluokka",
            "expression": "var uudet =  calculate(sum([Aloittaneet]), OR(Muuttujat[Koulutuslaji]=\"Ammattikorkeakoulututkinto (päivätoteutus)\", Muuttujat[Koulutuslaji]=\"Ammattikorkeakoulututkinto (monimuotototeutus)\"))\nvar vuosia = 3\nvar ka = [Keskiarvo 19-21]\nreturn IF(OR(uudet = 0, ka = BLANK()), BLANK(),\nIF(FIND(\"–\", ka, 1, 0) > 0, IF(uudet < 5, CONCATENATE(FORMAT(1 / (4 / vuosia), \"0.00 – \"), FORMAT(4 / (1 / vuosia), \"0.00\")),\nCONCATENATE(FORMAT(MROUND(uudet, 3) / (4 / vuosia), \"0.00 – \"), FORMAT(MROUND(uudet, 3) / (1 / vuosia), \"0.00\"))),\nIF(uudet < 5, CONCATENATE(FORMAT(1 / ka, \"0.00 – \"), FORMAT(4 / ka, \"0.00\")),\nMROUND(uudet, 3) / ka)))",
            "formatString": "0.00"
          },
          {
            "name": "Amk-tutkinto, aikuisten koulutus (pl. vieraskielinen koulutus) / 25-64-vuotiaiden keskim. ikäluokka",
            "expression": "var uudet =  [Ammattikorkeakoulutuksen uudet opiskelijat (aikuiset)]\nvar vuosia = 40\nvar ka = [Keskiarvo 25-64]\nreturn IF(OR(uudet = BLANK(), ka = BLANK()), BLANK(),\nIF(FIND(\"–\", ka, 1, 0) > 0, IF(uudet = \"1-4\", CONCATENATE(FORMAT(1 / (4 / vuosia), \"0.00 – \"), FORMAT(4 / (1 / vuosia), \"0.00\")),\nCONCATENATE(FORMAT(uudet / (4 / vuosia), \"0.00 – \"), FORMAT(uudet / (1 / vuosia), \"0.00\"))),\nIF(uudet = \"1-4\", CONCATENATE(FORMAT(1 / ka, \"0.00 – \"), FORMAT(4 / ka, \"0.00\")),\nuudet / ka)))",
            "formatString": "0.00"
          },
          {
            "name": "Ylemmän ammattikorkeakoulutuksen uudet opiskelijat",
            "expression": "var summa = CALCULATE(sum([Aloittaneet]),Muuttujat[Koulutuslaji]=\"Ylempi ammattikorkeakoulututkinto\")\nreturn IF(summa = 0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
            "formatString": "#,0"
          },
          {
            "name": "Ylempi amk-tutkinto / 25-64-vuotiaiden keskim. ikäluokka",
            "expression": "var uudet = [Ylemmän ammattikorkeakoulutuksen uudet opiskelijat]\nvar vuosia = 40\nvar ka = [Keskiarvo 25-64]\nreturn IF(OR(uudet = BLANK(), ka = BLANK()), BLANK(),\nIF(FIND(\"–\", ka, 1, 0) > 0, IF(uudet = \"1-4\", CONCATENATE(FORMAT(1 / (4 / vuosia), \"0.00 – \"), FORMAT(4 / (1 / vuosia), \"0.00\")),\nCONCATENATE(FORMAT(uudet / (4 / vuosia), \"0.00 – \"), FORMAT(uudet / (1 / vuosia), \"0.00\"))),\nIF(uudet = \"1-4\", CONCATENATE(FORMAT(1 / ka, \"0.00 – \"), FORMAT(4 / ka, \"0.00\")),\nuudet / ka)))",
            "formatString": "0.00"
          },
          {
            "name": "Alemman ja ylemmän korkeakoulututkinnon uudet opiskelijat",
            "expression": "var summa = CALCULATE(sum([Aloittaneet]),OR(Muuttujat[Koulutuslaji]=\"Alempi korkeakoulututkinto\",Muuttujat[Koulutuslaji]=\"Ylempi korkeakoulututkinto\"))\nreturn IF(summa = 0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
            "formatString": "#,0"
          },
          {
            "name": "Alempi tai ylempi kk-tutkinto / 19-21-vuotiaiden keskim. ikäluokka",
            "expression": "var uudet =  [Alemman ja ylemmän korkeakoulututkinnon uudet opiskelijat]\nvar vuosia = 3\nvar ka = [Keskiarvo 19-21]\nreturn IF(OR(uudet = BLANK(), ka = BLANK()), BLANK(),\nIF(FIND(\"–\", ka, 1, 0) > 0, IF(uudet = \"1-4\", CONCATENATE(FORMAT(1 / (4 / vuosia), \"0.00 – \"), FORMAT(4 / (1 / vuosia), \"0.00\")),\nCONCATENATE(FORMAT(uudet / (4 / vuosia), \"0.00 – \"), FORMAT(uudet / (1 / vuosia), \"0.00\"))),\nIF(uudet = \"1-4\", CONCATENATE(FORMAT(1 / ka, \"0.00 – \"), FORMAT(4 / ka, \"0.00\")),\nuudet / ka)))",
            "formatString": "0.00"
          },
          {
            "name": "Esiopetuksen oppilaat",
            "expression": "var summa = CALCULATE(sum([Aloittaneet]),Muuttujat[Sektori]=\"Esiopetus\")\nreturn IF(summa = 0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
            "formatString": "#,0"
          },
          {
            "name": "Perusopetuksen 1. luokan oppilaat",
            "expression": "var summa = calculate(sum([Aloittaneet]),Muuttujat[Sektori]=\"Perusopetus\")\nreturn IF(summa = 0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
            "formatString": "#,0"
          },
          {
            "name": "Esiopetus / 6-vuotiaiden ikäluokka",
            "expression": "var uudet = [Esiopetuksen oppilaat]\nvar lkm = [Määrä 6]\nreturn IF(OR(uudet = BLANK(), lkm = BLANK()), BLANK(),\nIF(uudet = \"1-4\", IF(lkm = \"1-4\", CONCATENATE(FORMAT(1 / 4, \"0.00 – \"), FORMAT(4 / 1, \"0.00\")),\nCONCATENATE(FORMAT(1 / lkm, \"0.00 – \"), FORMAT(4 / lkm, \"0.00\"))),\nIF(lkm = \"1-4\", CONCATENATE(FORMAT(uudet / 4, \"0.00 – \"), FORMAT(uudet / 1, \"0.00\")),\nuudet / lkm)))",
            "formatString": "0.00"
          },
          {
            "name": "Määrä 6",
            "expression": "var summa = sum([Väestö 6])\nreturn IF(summa = 0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
            "formatString": "#,0"
          },
          {
            "name": "Määrä 7",
            "expression": "var summa = sum([Väestö 7])\nreturn IF(summa = 0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
            "formatString": "#,0"
          },
          {
            "name": "Perusopetuksen 1. luokka / 7-vuotiaiden ikäluokka",
            "expression": "var uudet = [Perusopetuksen 1. luokan oppilaat]\nvar lkm = [Määrä 7]\nreturn IF(OR(uudet = BLANK(), lkm = BLANK()), BLANK(),\nIF(uudet = \"1-4\", IF(lkm = \"1-4\", CONCATENATE(FORMAT(1 / 4, \"0.00 – \"), FORMAT(4 / 1, \"0.00\")),\nCONCATENATE(FORMAT(1 / lkm, \"0.00 – \"), FORMAT(4 / lkm, \"0.00\"))),\nIF(lkm = \"1-4\", CONCATENATE(FORMAT(uudet / 4, \"0.00 – \"), FORMAT(uudet / 1, \"0.00\")),\nuudet / lkm)))",
            "formatString": "0.00"
          },
          {
            "name": "Gymnasieutbildning, läroplanen för unga / Medeltal för åldersgrupperna 16–18 år",
            "expression": "[Lukiokoulutus, nuorten opetussuunnitelma / 16-18-vuotiaiden keskim. ikäluokka]",
            "formatString": "0.00"
          },
          {
            "name": "General upper secondary education, curriculum for young people / Average for the age groups 16−18",
            "expression": "[Lukiokoulutus, nuorten opetussuunnitelma / 16-18-vuotiaiden keskim. ikäluokka]",
            "formatString": "0.00"
          },
          {
            "name": "Grundläggande yrkesutb., läroplansbaserad  (institut) / Medeltal för åldersgrupperna 16–18 år",
            "expression": "[Ops-perusteinen oppilaitosmuotoinen amm. pk / 16-18-vuotiaiden keskim. ikäluokka]",
            "formatString": "0.00"
          },
          {
            "name": "Vocational upper secondary ed., curriculum- and institute-based,  / Average for the age groups 16−18",
            "expression": "[Ops-perusteinen oppilaitosmuotoinen amm. pk / 16-18-vuotiaiden keskim. ikäluokka]",
            "formatString": "0.00"
          },
          {
            "name": "Grundläggande yrkesutb., förberedande (institututb.) / Medeltal för åldersgrupperna 25–64 år",
            "expression": "[Näyttötutkintoon valmistava amm. pk, oppilaitosm. / 25-64-vuotiaiden keskim. ikäluokka]",
            "formatString": "0.00"
          },
          {
            "name": "Vocational upper secondary ed., preparatory, institute-based / Average for the age groups 25−64",
            "expression": "[Näyttötutkintoon valmistava amm. pk, oppilaitosm. / 25-64-vuotiaiden keskim. ikäluokka]",
            "formatString": "0.00"
          },
          {
            "name": "Grundläggande yrkesutb., förberedande (läroavtalsutb.) / Medeltal för åldersgrupperna 25–64 år",
            "expression": "[Näyttötutkintoon valmistava amm. pk, oppis. / 25-64-vuotiaiden keskim. ikäluokka]",
            "formatString": "0.00"
          },
          {
            "name": "Vocational upper secondary ed., preparatory, apprenticeship / Average for the age groups 25−64",
            "expression": "[Näyttötutkintoon valmistava amm. pk, oppis. / 25-64-vuotiaiden keskim. ikäluokka]",
            "formatString": "0.00"
          },
          {
            "name": "Yrkes- och specialyrkesexamen., förberedande (institututb.) / Medeltal för åldersgrupperna 25–64 år",
            "expression": "[Amm. ja erikoisamm. tutkintoihin valmistava, oppilaitosm. / 25-64-vuotiaiden keskim. ikäluokka]",
            "formatString": "0.00"
          },
          {
            "name": "Further and specialist vocational, preparatory, institute-based / Average for the age groups 25−64",
            "expression": "[Amm. ja erikoisamm. tutkintoihin valmistava, oppilaitosm. / 25-64-vuotiaiden keskim. ikäluokka]",
            "formatString": "0.00"
          },
          {
            "name": "Yrkes- och specialyrkesexamen., förberedande (läroavtal) / Medeltal för åldersgrupperna 25–64 år",
            "expression": "[Amm. ja erikoisamm. tutkintoihin valmistava, oppis. / 25-64-vuotiaiden keskim. ikäluokka]",
            "formatString": "0.00"
          },
          {
            "name": "Further and specialist vocational, preparatory, apprenticeship / Average for the age groups 25−64:",
            "expression": "[Amm. ja erikoisamm. tutkintoihin valmistava, oppis. / 25-64-vuotiaiden keskim. ikäluokka]",
            "formatString": "0.00"
          },
          {
            "name": "YH-examen / Medeltal för åldersgrupperna 19–21 år",
            "expression": "[Amk-tutkinto / 19-21-vuotiaiden keskim. ikäluokka]",
            "formatString": "0.00"
          },
          {
            "name": "UAS degree / Average for the age groups 19−21",
            "expression": "[Amk-tutkinto / 19-21-vuotiaiden keskim. ikäluokka]",
            "formatString": "0.00"
          },
          {
            "name": "YH-examen, vuxenutbildning (exkl. utb. i främmande språk) / Medeltal för åldersgrupperna 25–64 år",
            "expression": "[Amk-tutkinto, aikuisten koulutus (pl. vieraskielinen koulutus) / 25-64-vuotiaiden keskim. ikäluokka]",
            "formatString": "0.00"
          },
          {
            "name": "UAS degree, adult education (excl. foreign language ed.) / Average for the age groups 25−64",
            "expression": "[Amk-tutkinto, aikuisten koulutus (pl. vieraskielinen koulutus) / 25-64-vuotiaiden keskim. ikäluokka]",
            "formatString": "0.00"
          },
          {
            "name": "Högre YH-examen / Medeltal för åldersgrupperna 25–64 år",
            "expression": "[Ylempi amk-tutkinto / 25-64-vuotiaiden keskim. ikäluokka]",
            "formatString": "0.00"
          },
          {
            "name": "UAS Master's degree / Average for the age groups 25−64",
            "expression": "[Ylempi amk-tutkinto / 25-64-vuotiaiden keskim. ikäluokka]",
            "formatString": "0.00"
          },
          {
            "name": "Lägre eller högre högskoleexamen / Medeltal för åldersgrupperna 19–21 år",
            "expression": "[Alempi tai ylempi kk-tutkinto / 19-21-vuotiaiden keskim. ikäluokka]",
            "formatString": "0.00"
          },
          {
            "name": "Bachelor's or Master's degree / Average for the age groups 19−21",
            "expression": "[Alempi tai ylempi kk-tutkinto / 19-21-vuotiaiden keskim. ikäluokka]",
            "formatString": "0.00"
          },
          {
            "name": "Förskoleundervisning / 6-åringar",
            "expression": "[Esiopetus / 6-vuotiaiden ikäluokka]",
            "formatString": "0.00"
          },
          {
            "name": "Pre-primary education / 6-year-olds",
            "expression": "[Esiopetus / 6-vuotiaiden ikäluokka]",
            "formatString": "0.00"
          },
          {
            "name": "Den grundläggande utbildningen årskurs 1 / 7-åringar",
            "expression": "[Perusopetuksen 1. luokka / 7-vuotiaiden ikäluokka]",
            "formatString": "0.00"
          },
          {
            "name": "Grade 1 of comprehensive school / 7-year-olds",
            "expression": "[Perusopetuksen 1. luokka / 7-vuotiaiden ikäluokka]",
            "formatString": "0.00"
          },
          {
            "name": "Lukion aloittaneet (nuoret)_s",
            "expression": "IF([kytkin]=0, BLANK(), calculate(sum(Muuttujat[Aloittaneet]),Muuttujat[Opetussuunnitelma]=\"nuorten opetussuunnitelma\"))",
            "formatString": "#,0"
          },
          {
            "name": "Ammtillisen peruskoulutuksen aloittaneet (nuoret)_s",
            "expression": "IF([kytkin]=0, BLANK(), CALCULATE(sum(Muuttujat[Aloittaneet]),Muuttujat[Koulutuslaji]=\"ammatillinen perustutkinto\",Muuttujat[Järjestämismuoto]=\"Oppilaitosmuotoinen koulutus\",Muuttujat[Järjestämistapa]=\"opetussuunnitelmaperusteinen koulutus/tutkinto\"))",
            "formatString": "#,0"
          },
          {
            "name": "Näyttötutkintoon valmistavan peruskoulutuksen uudet opiskelijat (oppilaitosmuotoinen)_s",
            "expression": "IF([kytkin]=0, BLANK(), CALCULATE(sum([Aloittaneet]),Muuttujat[Koulutuslaji]=\"ammatillinen perustutkinto\",Muuttujat[Järjestämistapa]=\"näyttötutkintoon valmistava koulutus/tutkinto\",Muuttujat[Järjestämismuoto]=\"Oppilaitosmuotoinen koulutus\"))",
            "formatString": "#,0"
          },
          {
            "name": "Näyttötutkintoon valmistavan peruskoulutuksen uudet opiskelijat (oppisopimus)_s",
            "expression": "IF([kytkin]=0, BLANK(), CALCULATE(sum([Aloittaneet]),Muuttujat[Koulutuslaji]=\"ammatillinen perustutkinto\",Muuttujat[Järjestämistapa]=\"näyttötutkintoon valmistava koulutus/tutkinto\",Muuttujat[Järjestämismuoto]=\"Oppisopimuskoulutus\"))"
          },
          {
            "name": "Ammatti- ja erikoisammattitutkinnon uudet opiskelijat (oppisopimus)_s",
            "expression": "IF([kytkin]=0, BLANK(), CALCULATE(sum([Aloittaneet]),OR(Muuttujat[Koulutuslaji]=\"Ammattitutkinto\",Muuttujat[Koulutuslaji]=\"Erikoisammattitutkinto\"),Muuttujat[Järjestämismuoto]=\"Oppisopimuskoulutus\"))",
            "formatString": "#,0"
          },
          {
            "name": "Ammatti- ja erikoisammattitutkinnon uudet opiskelijat (oppilaitosmuotoinen)_s",
            "expression": "IF([kytkin]=0, BLANK(), CALCULATE(sum([Aloittaneet]),OR(Muuttujat[Koulutuslaji]=\"Ammattitutkinto\",Muuttujat[Koulutuslaji]=\"Erikoisammattitutkinto\"),Muuttujat[Järjestämismuoto]=\"Oppilaitosmuotoinen koulutus\"))",
            "formatString": "#,0"
          },
          {
            "name": "Ammattikorkeakoulutuksen uudet opiskelijat (nuoret)_s",
            "expression": "IF([kytkin]=0, BLANK(), calculate(sum([Aloittaneet]),Muuttujat[Koulutuslaji]=\"Ammattikorkeakoulututkinto (päivätoteutus)\"))",
            "formatString": "#,0"
          },
          {
            "name": "Ammattikorkeakoulutuksen uudet opiskelijat (aikuiset)_s",
            "expression": "IF([kytkin]=0, BLANK(), calculate(sum([Aloittaneet]),Muuttujat[Koulutuslaji]=\"Ammattikorkeakoulututkinto (monimuotototeutus)\"))",
            "formatString": "#,0"
          },
          {
            "name": "Ylemmän ammattikorkeakoulutuksen uudet opiskelijat_s",
            "expression": "IF([kytkin]=0, BLANK(), CALCULATE(sum([Aloittaneet]),Muuttujat[Koulutuslaji]=\"Ylempi ammattikorkeakoulututkinto\"))",
            "formatString": "#,0"
          },
          {
            "name": "Alemman ja ylemmän korkeakoulututkinnon uudet opiskelijat_s",
            "expression": "IF([kytkin]=0, BLANK(), CALCULATE(sum([Aloittaneet]),OR(Muuttujat[Koulutuslaji]=\"Alempi korkeakoulututkinto\",Muuttujat[Koulutuslaji]=\"Ylempi korkeakoulututkinto\")))",
            "formatString": "#,0"
          },
          {
            "name": "Esiopetuksen oppilaat_s",
            "expression": "IF([kytkin]=0, BLANK(), CALCULATE(sum([Aloittaneet]),Muuttujat[Sektori]=\"Esiopetus\"))",
            "formatString": "#,0"
          },
          {
            "name": "Perusopetuksen 1. luokan oppilaat_s",
            "expression": "IF([kytkin]=0, BLANK(), calculate(sum([Aloittaneet]),Muuttujat[Sektori]=\"Perusopetus\"))",
            "formatString": "#,0"
          },
          {
            "name": "Keskiarvo 16-18_s",
            "expression": "IF([kytkin]=0, BLANK(), sum([Väestö 16-18]))",
            "formatString": "#,0.00"
          },
          {
            "name": "Keskiarvo 19-21_s",
            "expression": "IF([kytkin]=0, BLANK(), sum([Väestö 19-21]))",
            "formatString": "#,0.00"
          },
          {
            "name": "Keskiarvo 25-64_s",
            "expression": "IF([kytkin]=0, BLANK(), sum([Väestö 25-64]))",
            "formatString": "#,0.00"
          },
          {
            "name": "Määrä 6_s",
            "expression": "IF([kytkin]=0, BLANK(), sum([Väestö 6]))",
            "formatString": "#,0"
          },
          {
            "name": "Määrä 7_s",
            "expression": "IF([kytkin]=0, BLANK(), sum([Väestö 7]))",
            "formatString": "#,0"
          },
          {
            "name": "Lukiokoulutus, nuorten opetussuunnitelma / 16-18-vuotiaiden keskim. ikäluokka_s",
            "expression": "IF([kytkin]=0, BLANK(), [Lukion aloittaneet (nuoret)_s]/[Keskiarvo 16-18_s])",
            "formatString": "#,0.00"
          },
          {
            "name": "Ops-perusteinen oppilaitosmuotoinen amm. pk / 16-18-vuotiaiden keskim. ikäluokka_s",
            "expression": "IF([kytkin]=0, BLANK(), [Ammtillisen peruskoulutuksen aloittaneet (nuoret)_s]/[Keskiarvo 16-18_s])",
            "formatString": "0.00"
          },
          {
            "name": "Näyttötutkintoon valmistava amm. pk, oppilaitosm. / 25-64-vuotiaiden keskim. ikäluokka_s",
            "expression": "IF([kytkin]=0, BLANK(), [Näyttötutkintoon valmistavan peruskoulutuksen uudet opiskelijat (oppilaitosmuotoinen)_s]/[Keskiarvo 25-64_s])",
            "formatString": "0.00"
          },
          {
            "name": "Näyttötutkintoon valmistava amm. pk, oppis. / 25-64-vuotiaiden keskim. ikäluokka_s",
            "expression": "IF([kytkin]=0, BLANK(), [Näyttötutkintoon valmistavan peruskoulutuksen uudet opiskelijat (oppisopimus)_s]/[Keskiarvo 25-64_s])",
            "formatString": "0.00"
          },
          {
            "name": "Amm. ja erikoisamm. tutkintoihin valmistava, oppilaitosm. / 25-64-vuotiaiden keskim. ikäluokka_s",
            "expression": "IF([kytkin]=0, BLANK(), [Ammatti- ja erikoisammattitutkinnon uudet opiskelijat (oppilaitosmuotoinen)_s]/[Keskiarvo 25-64_s])",
            "formatString": "0.00"
          },
          {
            "name": "Amm. ja erikoisamm. tutkintoihin valmistava, oppis. / 25-64-vuotiaiden keskim. ikäluokka_s",
            "expression": "IF([kytkin]=0, BLANK(), [Ammatti- ja erikoisammattitutkinnon uudet opiskelijat (oppisopimus)_s]/[Keskiarvo 25-64_s])",
            "formatString": "0.00"
          },
          {
            "name": "Amk-tutkinto / 19-21-vuotiaiden keskim. ikäluokka_s",
            "expression": "IF([kytkin]=0, BLANK(), ([Ammattikorkeakoulutuksen uudet opiskelijat (nuoret)_s]+[Ammattikorkeakoulutuksen uudet opiskelijat (aikuiset)_s])/[Keskiarvo 19-21_s])",
            "formatString": "0.00"
          },
          {
            "name": "Amk-tutkinto, aikuisten koulutus (pl. vieraskielinen koulutus)/25-64-vuotiaiden keskim. ikäluokka_s",
            "expression": "IF([kytkin]=0, BLANK(), [Ammattikorkeakoulutuksen uudet opiskelijat (aikuiset)_s]/[Keskiarvo 25-64_s])",
            "formatString": "0.00"
          },
          {
            "name": "Ylempi amk-tutkinto / 25-64-vuotiaiden keskim. ikäluokka_s",
            "expression": "IF([kytkin]=0, BLANK(), [Ylemmän ammattikorkeakoulutuksen uudet opiskelijat_s]/[Keskiarvo 25-64_s])",
            "formatString": "0.00"
          },
          {
            "name": "Alempi tai ylempi kk-tutkinto / 19-21-vuotiaiden keskim. ikäluokka_s",
            "expression": "IF([kytkin]=0, BLANK(), [Alemman ja ylemmän korkeakoulututkinnon uudet opiskelijat_s]/[Keskiarvo 19-21_s])",
            "formatString": "0.00"
          },
          {
            "name": "Esiopetus / 6-vuotiaiden ikäluokka_s",
            "expression": "IF([kytkin]=0, BLANK(), [Esiopetuksen oppilaat_s]/[Määrä 6_s])",
            "formatString": "0.00"
          },
          {
            "name": "Perusopetuksen 1. luokka / 7-vuotiaiden ikäluokka_s",
            "expression": "IF([kytkin]=0, BLANK(), [Perusopetuksen 1. luokan oppilaat_s]/[Määrä 7_s])",
            "formatString": "0.00"
          },
          {
            "name": "kytkin",
            "expression": "IF(LEFT(USERNAME(), 4) = \"DWI\\\", 1, 0)",
            "formatString": "0",
            "isHidden": true
          },
          {
            "name": "Ammatillinen peruskoulutus, oppilaitosm. / 16-18-vuotiaiden keskim. ikäluokka",
            "expression": "var lkm = CALCULATE(sum(Muuttujat[Aloittaneet]),Muuttujat[Koulutuslaji]=\"ammatillinen perustutkinto\",Muuttujat[Järjestämismuoto]=\"Oppilaitosmuotoinen koulutus\")\nvar uudet = IF(lkm = 0, BLANK(), IF(lkm < 5, \"1-4\", MROUND(lkm, 3)))\nvar vuosia = 3\nvar ka = [Keskiarvo 16-18]\nreturn IF(OR(uudet = BLANK(), ka = BLANK()), BLANK(),\nIF(FIND(\"–\", ka, 1, 0) > 0, IF(uudet = \"1-4\", CONCATENATE(FORMAT(1 / (4 / vuosia), \"0.00 – \"), FORMAT(4 / (1 / vuosia), \"0.00\")),\nCONCATENATE(FORMAT(uudet / (4 / vuosia), \"0.00 – \"), FORMAT(uudet / (1 / vuosia), \"0.00\"))),\nIF(uudet = \"1-4\", CONCATENATE(FORMAT(1 / ka, \"0.00 – \"), FORMAT(4 / ka, \"0.00\")),\nuudet / ka)))",
            "formatString": "0.00"
          },
          {
            "name": "Ammatillinen peruskoulutus, oppilaitosm. / 16-18-vuotiaiden keskim. ikäluokka_s",
            "expression": "IF([kytkin]=0, BLANK(), \nvar lkm = CALCULATE(sum(Muuttujat[Aloittaneet]),Muuttujat[Koulutuslaji]=\"ammatillinen perustutkinto\",Muuttujat[Järjestämismuoto]=\"Oppilaitosmuotoinen koulutus\")\nvar ka = [Keskiarvo 16-18_s]\nreturn DIVIDE(lkm, ka))",
            "formatString": "0.00"
          },
          {
            "name": "Ammatillinen peruskoulutus, oppis. / 25-64-vuotiaiden keskim. ikäluokka",
            "expression": "var lkm = CALCULATE(sum(Muuttujat[Aloittaneet]),Muuttujat[Koulutuslaji]=\"ammatillinen perustutkinto\",Muuttujat[Järjestämismuoto]=\"Oppisopimuskoulutus\")\nvar uudet = IF(lkm = 0, BLANK(), IF(lkm < 5, \"1-4\", MROUND(lkm, 3)))\nvar vuosia = 40\nvar ka = [Keskiarvo 25-64]\nreturn IF(OR(uudet = BLANK(), ka = BLANK()), BLANK(),\nIF(FIND(\"–\", ka, 1, 0) > 0, IF(uudet = \"1-4\", CONCATENATE(FORMAT(1 / (4 / vuosia), \"0.00 – \"), FORMAT(4 / (1 / vuosia), \"0.00\")),\nCONCATENATE(FORMAT(uudet / (4 / vuosia), \"0.00 – \"), FORMAT(uudet / (1 / vuosia), \"0.00\"))),\nIF(uudet = \"1-4\", CONCATENATE(FORMAT(1 / ka, \"0.00 – \"), FORMAT(4 / ka, \"0.00\")),\nuudet / ka)))",
            "formatString": "0.00"
          },
          {
            "name": "Ammatillinen peruskoulutus, oppis. / 25-64-vuotiaiden keskim. ikäluokka_s",
            "expression": "IF([kytkin]=0, BLANK(), \nvar lkm = CALCULATE(sum(Muuttujat[Aloittaneet]),Muuttujat[Koulutuslaji]=\"ammatillinen perustutkinto\",Muuttujat[Järjestämismuoto]=\"Oppisopimuskoulutus\")\nvar ka = [Keskiarvo 25-64_s]\nreturn DIVIDE(lkm, ka))",
            "formatString": "0.00"
          },
          {
            "name": "Grundläggande yrkesutbildning, institututb. / Medeltal för åldersgrupperna 16–18 år",
            "expression": "[Ammatillinen peruskoulutus, oppilaitosm. / 16-18-vuotiaiden keskim. ikäluokka]",
            "formatString": "0.00"
          },
          {
            "name": "Vocational upper secondary ed., institute-based / Average for the age groups 16−18",
            "expression": "[Ammatillinen peruskoulutus, oppilaitosm. / 16-18-vuotiaiden keskim. ikäluokka]",
            "formatString": "0.00"
          },
          {
            "name": "Grundläggande yrkesutbildning, läroavtalsutb. / Medeltal för åldersgrupperna 25–64 år",
            "expression": "[Ammatillinen peruskoulutus, oppis. / 25-64-vuotiaiden keskim. ikäluokka]",
            "formatString": "0.00"
          },
          {
            "name": "Vocational upper secondary ed., apprenticeship / Average for the age groups 25−64",
            "expression": "[Ammatillinen peruskoulutus, oppis. / 25-64-vuotiaiden keskim. ikäluokka]",
            "formatString": "0.00"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "v_f_tab_indikaattorit_opiskelijat_ikäluokka"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[v_f_tab_indikaattorit_opiskelijat_ikäluokka].* FROM [dbo].[v_f_tab_indikaattorit_opiskelijat_ikäluokka] "
          }
        ]
      },
      {
        "name": "Sarakeleveys",
        "isHidden": true,
        "columns": [
          {
            "name": "Sarakeleveys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Sarakeleveys"
          },
          {
            "name": "leveys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "leveys"
          }
        ],
        "partitions": [
          {
            "name": "Sarakeleveys",
            "source": {
              "query": "SELECT [dbo].[Sarakeleveys].* \t\tFROM [dbo].[Sarakeleveys]",
              "dataSource": "SqlServer dwitestvipusql VipunenTK"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization"
              },
              {
                "name": "TableWidgetSerialization"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Sarakeleveys"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "      SELECT [dbo].[Sarakeleveys].*   FROM [dbo].[Sarakeleveys] "
          }
        ]
      }
    ],
    "cultures": [
      {
        "name": "en-US",
        "translations": {
          "model": {
            "name": "Model",
            "tables": [
              {
                "name": "Muuttujat",
                "translatedCaption": "Variables"
              }
            ]
          }
        }
      },
      {
        "name": "sv-SE",
        "translations": {
          "model": {
            "name": "Model",
            "tables": [
              {
                "name": "Muuttujat",
                "translatedCaption": "Variabler"
              }
            ]
          }
        }
      }
    ],
    "perspectives": [
      {
        "name": "Esiopetus",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Maakunta"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Kunta"
              }
            ],
            "measures": [
              {
                "name": "Esiopetus / 6-vuotiaiden ikäluokka"
              }
            ]
          }
        ]
      },
      {
        "name": "Perusopetus",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Maakunta"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Sukupuoli"
              },
              {
                "name": "Kunta"
              }
            ],
            "measures": [
              {
                "name": "Perusopetuksen 1. luokka / 7-vuotiaiden ikäluokka"
              }
            ]
          }
        ]
      },
      {
        "name": "Ammpk",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Maakunta"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Sukupuoli"
              },
              {
                "name": "Äidinkieli"
              },
              {
                "name": "Kunta"
              }
            ],
            "measures": [
              {
                "name": "Ammatillinen peruskoulutus, oppilaitosm. / 16-18-vuotiaiden keskim. ikäluokka"
              },
              {
                "name": "Ops-perusteinen oppilaitosmuotoinen amm. pk / 16-18-vuotiaiden keskim. ikäluokka"
              }
            ]
          }
        ]
      },
      {
        "name": "Näyttö oppil",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Maakunta"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Sukupuoli"
              },
              {
                "name": "Äidinkieli"
              },
              {
                "name": "Kunta"
              }
            ],
            "measures": [
              {
                "name": "Ammatillinen peruskoulutus, oppilaitosm. / 16-18-vuotiaiden keskim. ikäluokka"
              },
              {
                "name": "Näyttötutkintoon valmistava amm. pk, oppilaitosm. / 25-64-vuotiaiden keskim. ikäluokka"
              }
            ]
          }
        ]
      },
      {
        "name": "Näyttö oppis",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Maakunta"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Sukupuoli"
              },
              {
                "name": "Äidinkieli"
              },
              {
                "name": "Kunta"
              }
            ],
            "measures": [
              {
                "name": "Näyttötutkintoon valmistava amm. pk, oppis. / 25-64-vuotiaiden keskim. ikäluokka"
              },
              {
                "name": "Ammatillinen peruskoulutus, oppis. / 25-64-vuotiaiden keskim. ikäluokka"
              }
            ]
          }
        ]
      },
      {
        "name": "AT ja EAT oppil",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Maakunta"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Sukupuoli"
              },
              {
                "name": "Äidinkieli"
              },
              {
                "name": "Kunta"
              }
            ],
            "measures": [
              {
                "name": "Amm. ja erikoisamm. tutkintoihin valmistava, oppilaitosm. / 25-64-vuotiaiden keskim. ikäluokka"
              }
            ]
          }
        ]
      },
      {
        "name": "AT ja EAT oppis",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Maakunta"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Sukupuoli"
              },
              {
                "name": "Äidinkieli"
              },
              {
                "name": "Kunta"
              }
            ],
            "measures": [
              {
                "name": "Amm. ja erikoisamm. tutkintoihin valmistava, oppis. / 25-64-vuotiaiden keskim. ikäluokka"
              }
            ]
          }
        ]
      },
      {
        "name": "Lukio",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Maakunta"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Sukupuoli"
              },
              {
                "name": "Äidinkieli"
              },
              {
                "name": "Kunta"
              }
            ],
            "measures": [
              {
                "name": "Lukiokoulutus, nuorten opetussuunnitelma / 16-18-vuotiaiden keskim. ikäluokka"
              }
            ]
          }
        ]
      },
      {
        "name": "Yhteinen",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Maakunta"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Sukupuoli"
              },
              {
                "name": "Kunta"
              }
            ],
            "measures": [
              {
                "name": "Amk-tutkinto / 19-21-vuotiaiden keskim. ikäluokka"
              },
              {
                "name": "Ammatillinen peruskoulutus, oppilaitosm. / 16-18-vuotiaiden keskim. ikäluokka"
              },
              {
                "name": "Perusopetuksen 1. luokka / 7-vuotiaiden ikäluokka"
              },
              {
                "name": "Ylempi amk-tutkinto / 25-64-vuotiaiden keskim. ikäluokka"
              },
              {
                "name": "Amm. ja erikoisamm. tutkintoihin valmistava, oppis. / 25-64-vuotiaiden keskim. ikäluokka"
              },
              {
                "name": "Amm. ja erikoisamm. tutkintoihin valmistava, oppilaitosm. / 25-64-vuotiaiden keskim. ikäluokka"
              },
              {
                "name": "Näyttötutkintoon valmistava amm. pk, oppilaitosm. / 25-64-vuotiaiden keskim. ikäluokka"
              },
              {
                "name": "Näyttötutkintoon valmistava amm. pk, oppis. / 25-64-vuotiaiden keskim. ikäluokka"
              },
              {
                "name": "Alempi tai ylempi kk-tutkinto / 19-21-vuotiaiden keskim. ikäluokka"
              },
              {
                "name": "Esiopetus / 6-vuotiaiden ikäluokka"
              },
              {
                "name": "Ops-perusteinen oppilaitosmuotoinen amm. pk / 16-18-vuotiaiden keskim. ikäluokka"
              },
              {
                "name": "Lukiokoulutus, nuorten opetussuunnitelma / 16-18-vuotiaiden keskim. ikäluokka"
              },
              {
                "name": "Ammatillinen peruskoulutus, oppis. / 25-64-vuotiaiden keskim. ikäluokka"
              }
            ]
          }
        ]
      },
      {
        "name": "YhteinenSV",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Landskap"
              },
              {
                "name": "Statistikår"
              },
              {
                "name": "Kön"
              }
            ],
            "measures": [
              {
                "name": "Gymnasieutbildning, läroplanen för unga / Medeltal för åldersgrupperna 16–18 år"
              },
              {
                "name": "Grundläggande yrkesutb., förberedande (institututb.) / Medeltal för åldersgrupperna 25–64 år"
              },
              {
                "name": "Lägre eller högre högskoleexamen / Medeltal för åldersgrupperna 19–21 år"
              },
              {
                "name": "YH-examen / Medeltal för åldersgrupperna 19–21 år"
              },
              {
                "name": "Yrkes- och specialyrkesexamen., förberedande (läroavtal) / Medeltal för åldersgrupperna 25–64 år"
              },
              {
                "name": "Grundläggande yrkesutb., förberedande (läroavtalsutb.) / Medeltal för åldersgrupperna 25–64 år"
              },
              {
                "name": "Grundläggande yrkesutb., läroplansbaserad  (institut) / Medeltal för åldersgrupperna 16–18 år"
              },
              {
                "name": "Högre YH-examen / Medeltal för åldersgrupperna 25–64 år"
              },
              {
                "name": "Förskoleundervisning / 6-åringar"
              },
              {
                "name": "Den grundläggande utbildningen årskurs 1 / 7-åringar"
              },
              {
                "name": "Yrkes- och specialyrkesexamen., förberedande (institututb.) / Medeltal för åldersgrupperna 25–64 år"
              },
              {
                "name": "Grundläggande yrkesutbildning, institututb. / Medeltal för åldersgrupperna 16–18 år"
              },
              {
                "name": "Grundläggande yrkesutbildning, läroavtalsutb. / Medeltal för åldersgrupperna 25–64 år"
              }
            ]
          }
        ]
      },
      {
        "name": "YhteinenEN",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Statistical year"
              },
              {
                "name": "Gender"
              },
              {
                "name": "Region"
              }
            ],
            "measures": [
              {
                "name": "Further and specialist vocational, preparatory, apprenticeship / Average for the age groups 25−64:"
              },
              {
                "name": "Grade 1 of comprehensive school / 7-year-olds"
              },
              {
                "name": "Vocational upper secondary ed., curriculum- and institute-based,  / Average for the age groups 16−18"
              },
              {
                "name": "UAS degree / Average for the age groups 19−21"
              },
              {
                "name": "Vocational upper secondary ed., preparatory, apprenticeship / Average for the age groups 25−64"
              },
              {
                "name": "Vocational upper secondary ed., preparatory, institute-based / Average for the age groups 25−64"
              },
              {
                "name": "Pre-primary education / 6-year-olds"
              },
              {
                "name": "Vocational upper secondary ed., apprenticeship / Average for the age groups 25−64"
              },
              {
                "name": "Vocational upper secondary ed., institute-based / Average for the age groups 16−18"
              },
              {
                "name": "Bachelor's or Master's degree / Average for the age groups 19−21"
              },
              {
                "name": "Further and specialist vocational, preparatory, institute-based / Average for the age groups 25−64"
              },
              {
                "name": "General upper secondary education, curriculum for young people / Average for the age groups 16−18"
              },
              {
                "name": "UAS Master's degree / Average for the age groups 25−64"
              }
            ]
          }
        ]
      }
    ],
    "roles": [
      {
        "name": "Luku",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "DWI\\T_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1732"
          },
          {
            "memberName": "DWI\\T_VIPU_SSAS_DB_R",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1751"
          },
          {
            "memberName": "DWI\\T_VIPU_SSAS_DB_R_TK",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1753"
          },
          {
            "memberName": "DWI\\P_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1733"
          },
          {
            "memberName": "DWI\\P_VIPU_SSAS_DB_R",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1752"
          },
          {
            "memberName": "DWI\\P_VIPU_SSAS_DB_R_TK",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1754"
          },
          {
            "memberName": "DWI\\Z_P_Antero_Full_Read_TAB",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-2272"
          }
        ]
      }
    ]
  }
}
