{
  "name": "SemanticModel",
  "compatibilityLevel": 1200,
  "model": {
    "culture": "fi-FI",
    "dataSources": [
      {
        "name": "SqlServer dwitvipusql16 ANTERO",
        "connectionString": "Provider=SQLNCLI11;Data Source=dwitvipusql16;Initial Catalog=ANTERO;Integrated Security=SSPI;Persist Security Info=false",
        "impersonationMode": "impersonateAccount",
        "account": "dwi\\pankalai",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "Sarakeleveys",
        "columns": [
          {
            "name": "Sarakeleveys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Sarakeleveys",
            "sourceProviderType": "Char"
          },
          {
            "name": "leveys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "leveys",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Sarakeleveys",
            "dataView": "full",
            "source": {
              "query": " SELECT [dw].[Sarakeleveys].* FROM [dw].[Sarakeleveys] ",
              "dataSource": "SqlServer dwitvipusql16 ANTERO"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dw].[Sarakeleveys].* FROM [dw].[Sarakeleveys] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Sarakeleveys"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dw"
          }
        ]
      },
      {
        "name": "Muuttujat",
        "columns": [
          {
            "name": "Tilastovuosi",
            "dataType": "int64",
            "sourceColumn": "Tilastovuosi",
            "sourceProviderType": "Integer",
            "displayFolder": "Aikamuuttujat"
          },
          {
            "name": "Yliopisto",
            "dataType": "string",
            "sourceColumn": "Yliopisto",
            "sourceProviderType": "Char",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "harjoittelukoulujen_tilat",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "harjoittelukoulujen_tilat",
            "sourceProviderType": "Integer"
          },
          {
            "name": "muut_vuokratilat",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "muut_vuokratilat",
            "sourceProviderType": "Integer"
          },
          {
            "name": "yliopistokiinteistoyhtion_toimitilat_aalto_yliopistokiinteistot_oy",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "yliopistokiinteistoyhtion_toimitilat_aalto_yliopistokiinteistot_oy",
            "sourceProviderType": "Integer"
          },
          {
            "name": "yliopistokiinteistoyhtion_toimitilat_helsingin_yliopistokiinteistot_oy",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "yliopistokiinteistoyhtion_toimitilat_helsingin_yliopistokiinteistot_oy",
            "sourceProviderType": "Integer"
          },
          {
            "name": "yliopistokiinteistoyhtion_toimitilat_suomen_yliopistokiinteistot_oy",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "yliopistokiinteistoyhtion_toimitilat_suomen_yliopistokiinteistot_oy",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Koodit Yliopisto",
            "dataType": "string",
            "sourceColumn": "Koodit Yliopisto",
            "sourceProviderType": "Char",
            "displayFolder": "Koodimuuttujat"
          }
        ],
        "partitions": [
          {
            "name": "v_st_toimitilat",
            "dataView": "full",
            "source": {
              "query": " SELECT [dw].[v_st_toimitilat].* FROM [dw].[v_st_toimitilat] ",
              "dataSource": "SqlServer dwitvipusql16 ANTERO"
            }
          }
        ],
        "measures": [
          {
            "name": "Aalto Yliopistokiinteistöt Oy, m2",
            "expression": "if(sum(Muuttujat[yliopistokiinteistoyhtion_toimitilat_aalto_yliopistokiinteistot_oy])=0,blank(),sum(Muuttujat[yliopistokiinteistoyhtion_toimitilat_aalto_yliopistokiinteistot_oy]))",
            "formatString": "#,0"
          },
          {
            "name": "Helsingin Yliopistokiinteistöt Oy, m2",
            "expression": "if(sum(Muuttujat[yliopistokiinteistoyhtion_toimitilat_helsingin_yliopistokiinteistot_oy])=0,blank(),sum(Muuttujat[yliopistokiinteistoyhtion_toimitilat_helsingin_yliopistokiinteistot_oy]))",
            "formatString": "#,0"
          },
          {
            "name": "Suomen Yliopistokiinteistöt Oy, m2",
            "expression": "if(sum(Muuttujat[yliopistokiinteistoyhtion_toimitilat_suomen_yliopistokiinteistot_oy])=0,blank(),sum(Muuttujat[yliopistokiinteistoyhtion_toimitilat_suomen_yliopistokiinteistot_oy]))",
            "formatString": "#,0"
          },
          {
            "name": "Muut vuokratilat ja yliopiston suoraan omistamat tilat, m2",
            "expression": "if(sum(Muuttujat[muut_vuokratilat])=0,blank(),sum(Muuttujat[muut_vuokratilat]))",
            "formatString": "#,0"
          },
          {
            "name": "Harjoittelukoulut, m2",
            "expression": "if(Sum(Muuttujat[harjoittelukoulujen_tilat])=0,blank(),Sum(Muuttujat[harjoittelukoulujen_tilat]))",
            "formatString": "#,0"
          },
          {
            "name": "Tilat yhteensä (pl. harjoittelukoulut)",
            "expression": "[Aalto Yliopistokiinteistöt Oy, m2]+[Helsingin Yliopistokiinteistöt Oy, m2]+[Suomen Yliopistokiinteistöt Oy, m2]+[Muut vuokratilat ja yliopiston suoraan omistamat tilat, m2]",
            "formatString": "#,0"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dw].[v_st_toimitilat].* FROM [dw].[v_st_toimitilat] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "v_st_toimitilat"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dw"
          }
        ]
      }
    ],
    "perspectives": [
      {
        "name": "yo_tilat",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Koodit Yliopisto"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Yliopisto"
              }
            ],
            "measures": [
              {
                "name": "Aalto Yliopistokiinteistöt Oy, m2"
              },
              {
                "name": "Harjoittelukoulut, m2"
              },
              {
                "name": "Helsingin Yliopistokiinteistöt Oy, m2"
              },
              {
                "name": "Muut vuokratilat ja yliopiston suoraan omistamat tilat, m2"
              },
              {
                "name": "Suomen Yliopistokiinteistöt Oy, m2"
              },
              {
                "name": "Tilat yhteensä (pl. harjoittelukoulut)"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      }
    ],
    "roles": [
      {
        "name": "Luku",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "DWI\\T_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1732"
          },
          {
            "memberName": "DWI\\P_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1733"
          },
          {
            "memberName": "NT AUTHORITY\\IUSR",
            "memberId": "S-1-5-17"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "400"
      }
    ]
  },
  "id": "SemanticModel"
}