{
  "name": "SemanticModel",
  "id": "SemanticModel",
  "compatibilityLevel": 1200,
  "model": {
    "culture": "fi-FI",
    "dataSources": [
      {
        "name": "SqlServer dwitestvipusql VipunenTK",
        "connectionString": "Provider=SQLNCLI11;Data Source=dwitvipusql16;Initial Catalog=VipunenTK;Integrated Security=SSPI;Persist Security Info=false",
        "impersonationMode": "impersonateAccount",
        "account": "dwi\\T_VIPUTK_KUUTIO",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "Sarakeleveys",
        "isHidden": true,
        "columns": [
          {
            "name": "Sarakeleveys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Sarakeleveys"
          },
          {
            "name": "leveys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "leveys"
          }
        ],
        "partitions": [
          {
            "name": "Sarakeleveys",
            "source": {
              "query": "SELECT [dbo].[Sarakeleveys].* \t\tFROM [dbo].[Sarakeleveys]",
              "dataSource": "SqlServer dwitestvipusql VipunenTK"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization"
              },
              {
                "name": "TableWidgetSerialization"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Sarakeleveys"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "      SELECT [dbo].[Sarakeleveys].*   FROM [dbo].[Sarakeleveys] "
          }
        ]
      },
      {
        "name": "Muuttujat",
        "columns": [
          {
            "name": "lkm_op2",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "lkm_op2"
          },
          {
            "name": "lkm_aloit2",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "lkm_aloit2"
          },
          {
            "name": "lkm_opiskolo2",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "lkm_opiskolo2"
          },
          {
            "name": "Tilastovuosi",
            "dataType": "string",
            "sourceColumn": "Tilastovuosi",
            "displayFolder": "Aikamuuttujat"
          },
          {
            "name": "Näkökulma",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Näkökulma"
          },
          {
            "name": "Lähde",
            "dataType": "string",
            "sourceColumn": "Lähde",
            "sortByColumn": "lahde_koodi",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusnimike",
            "dataType": "string",
            "sourceColumn": "Koulutusnimike",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Opintoala",
            "dataType": "string",
            "sourceColumn": "Opintoala",
            "sortByColumn": "jarj_opintoala",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusala",
            "dataType": "string",
            "sourceColumn": "Koulutusala",
            "sortByColumn": "jarjestys_koulutusala2002",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusala (1995)",
            "dataType": "string",
            "sourceColumn": "Koulutusala (95 luokitus)",
            "sortByColumn": "jarjestys_opintoala1995",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusala (02 luokitus)",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Koulutusala (02 luokitus)",
            "sortByColumn": "jarjestys_koulutusala2002"
          },
          {
            "name": "Koulutusaste",
            "dataType": "string",
            "sourceColumn": "Koulutusaste",
            "sortByColumn": "jarjestys_koulutusaste2002",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Järjestämistapa",
            "dataType": "string",
            "sourceColumn": "Järjestämistapa",
            "sortByColumn": "jarj_jarjtapa",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Tutkintotyyppi",
            "dataType": "string",
            "sourceColumn": "Tutkintotyyppi",
            "sortByColumn": "jarj_tutktyyppi",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Hallinnonala",
            "dataType": "string",
            "sourceColumn": "Hallinnonala",
            "sortByColumn": "jarj_hallinnonala",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Opetuskieli",
            "dataType": "string",
            "sourceColumn": "Opetuskieli",
            "sortByColumn": "jarj_opetuskieli",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Nuorten koulutus/aikuiskoulutus",
            "dataType": "string",
            "sourceColumn": "Nuorten koulutus/aikuiskoulutus",
            "sortByColumn": "jarj_nuoretaikuiset",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutuksen maakunta",
            "dataType": "string",
            "sourceColumn": "Koulutuksen maakunta",
            "sortByColumn": "jarjestys_maakunta",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutuksen ELY-alue",
            "dataType": "string",
            "sourceColumn": "Koulutuksen ELY-alue",
            "sortByColumn": "jarjestys_ely",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutuksen AVI-alue",
            "dataType": "string",
            "sourceColumn": "Koulutuksen AVI-alue",
            "sortByColumn": "jarjestys_avi",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Sukupuoli",
            "dataType": "string",
            "sourceColumn": "Sukupuoli",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Nuori opiskelija/aikuisopiskelija",
            "dataType": "string",
            "sourceColumn": "Nuori opiskelija/aikuisopiskelija",
            "sortByColumn": "jarj_nuoriaikuinen",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Aloituslukukausi",
            "dataType": "string",
            "sourceColumn": "Aloituslukukausi",
            "displayFolder": "Aikamuuttujat"
          },
          {
            "name": "Aloituslukuvuosi",
            "dataType": "string",
            "sourceColumn": "Aloituslukuvuosi",
            "displayFolder": "Aikamuuttujat"
          },
          {
            "name": "Aloitusvuosi",
            "dataType": "string",
            "sourceColumn": "Aloitusvuosi",
            "displayFolder": "Aikamuuttujat"
          },
          {
            "name": "Kirjoillaolo (tammi)",
            "dataType": "string",
            "sourceColumn": "Kirjoillaolo (tammi)",
            "sortByColumn": "jarj_kirjtammi",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Kirjoillaolo (syys)",
            "dataType": "string",
            "sourceColumn": "Kirjoillaolo (syys)",
            "sortByColumn": "jarj_kirjsyys",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Kuntaryhmä",
            "dataType": "string",
            "sourceColumn": "Kuntaryhmä",
            "sortByColumn": "jarj_kuntaryhma",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Järjestämismuoto",
            "dataType": "string",
            "sourceColumn": "Järjestämismuoto",
            "sortByColumn": "jarj_jarjmuoto",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutuslaji",
            "dataType": "string",
            "sourceColumn": "Koulutuslaji",
            "sortByColumn": "jarjestys_koulutuslaji3",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Kansalaisuus (maa)",
            "dataType": "string",
            "sourceColumn": "Kansalaisuus (maa)",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Kansalaisuus (maanosa)",
            "dataType": "string",
            "sourceColumn": "Kansalaisuus (maanosa)",
            "sortByColumn": "jarjestys_maanosa",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "ETA-maan kansalainen",
            "dataType": "string",
            "sourceColumn": "ETA-maan kansalainen",
            "sortByColumn": "jarjestys_etamaa",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "EU-maan kansalainen",
            "dataType": "string",
            "sourceColumn": "EU-maan kansalainen",
            "sortByColumn": "jarjestys_eumaa",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Kansalaisuus (suomi/muu)",
            "dataType": "string",
            "sourceColumn": "Kansalaisuus (suomi/muu)",
            "sortByColumn": "jarj_kans",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Syntymämaa",
            "dataType": "string",
            "sourceColumn": "Syntymävaltio",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Syntymämaa (maanosa)",
            "dataType": "string",
            "sourceColumn": "Syntymävaltio (maanosa)",
            "sortByColumn": "jarj_syntmaanosa",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Syntymämaa (suomi/muu)",
            "dataType": "string",
            "sourceColumn": "Syntymävaltio (suomi/muu)",
            "sortByColumn": "jarj_syntsuomimuu",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Äidinkieli",
            "dataType": "string",
            "sourceColumn": "Äidinkieli",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Äidinkieli (suomi/muu)",
            "dataType": "string",
            "sourceColumn": "Äidinkieli (suomi/muu)",
            "sortByColumn": "jarj_aidinkielisuomi",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Koulutussektori",
            "dataType": "string",
            "sourceColumn": "Koulutussektori",
            "sortByColumn": "jarj_koulsektori",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "lahde_koodi",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "lahde_koodi"
          },
          {
            "name": "jarj_koulnimike",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_koulnimike"
          },
          {
            "name": "jarj_opintoala",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_opintoala"
          },
          {
            "name": "jarjestys_koulutusala2002",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarjestys_koulutusala2002"
          },
          {
            "name": "jarjestys_opintoala1995",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarjestys_opintoala1995"
          },
          {
            "name": "jarjestys_koulutusaste2002",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarjestys_koulutusaste2002"
          },
          {
            "name": "jarj_jarjtapa",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_jarjtapa"
          },
          {
            "name": "jarj_tutktyyppi",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_tutktyyppi"
          },
          {
            "name": "jarj_hallinnonala",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_hallinnonala"
          },
          {
            "name": "jarj_opetuskieli",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarj_opetuskieli"
          },
          {
            "name": "jarj_nuoretaikuiset",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_nuoretaikuiset"
          },
          {
            "name": "jarjestys_maakunta",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarjestys_maakunta"
          },
          {
            "name": "jarjestys_ely",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarjestys_ely"
          },
          {
            "name": "jarjestys_avi",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarjestys_avi"
          },
          {
            "name": "jarj_sukupuoli",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_sukupuoli"
          },
          {
            "name": "jarj_nuoriaikuinen",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_nuoriaikuinen"
          },
          {
            "name": "jarj_lukukausi",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarj_lukukausi"
          },
          {
            "name": "jarj_kirjtammi",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_kirjtammi"
          },
          {
            "name": "jarj_kirjsyys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_kirjsyys"
          },
          {
            "name": "jarj_kuntaryhma",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarj_kuntaryhma"
          },
          {
            "name": "jarj_jarjmuoto",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_jarjmuoto"
          },
          {
            "name": "jarjestys_koulutuslaji3",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarjestys_koulutuslaji3"
          },
          {
            "name": "jarj_maa",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarj_maa"
          },
          {
            "name": "jarjestys_maanosa",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarjestys_maanosa"
          },
          {
            "name": "jarjestys_etamaa",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarjestys_etamaa"
          },
          {
            "name": "jarjestys_eumaa",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarjestys_eumaa"
          },
          {
            "name": "jarj_kans",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_kans"
          },
          {
            "name": "jarj_syntvaltio",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarj_syntvaltio"
          },
          {
            "name": "jarj_syntmaanosa",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarj_syntmaanosa"
          },
          {
            "name": "jarj_syntsuomimuu",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_syntsuomimuu"
          },
          {
            "name": "jarj_aidinkieli",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarj_aidinkieli"
          },
          {
            "name": "jarj_aidinkielisuomi",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_aidinkielisuomi"
          },
          {
            "name": "jarj_koulsektori",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_koulsektori"
          },
          {
            "name": "koulutusaste2002_koodi",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "koulutusaste2002_koodi"
          },
          {
            "name": "koulutuksen_aloittamislukuvuosi",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "koulutuksen_aloittamislukuvuosi"
          },
          {
            "name": "Aineistonäkökulma",
            "dataType": "string",
            "sourceColumn": "Aineistonäkökulma",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "koodi_ai",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "koodi_ai"
          },
          {
            "name": "koodi_kan",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "koodi_kan"
          },
          {
            "name": "koodi_syn",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "koodi_syn"
          },
          {
            "name": "Utbildningsbenämning",
            "dataType": "string",
            "sourceColumn": "Utbildningsbenämning",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Utbildningsområde  (2002)",
            "dataType": "string",
            "sourceColumn": "Utbildningsområde (2002)",
            "sortByColumn": "jarjestys_koulutusala2002",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Utbildningsnivå",
            "dataType": "string",
            "sourceColumn": "Utbildningsnivå",
            "sortByColumn": "jarjestys_koulutusaste2002",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Sättet på vilket utbildningen ordnas",
            "dataType": "string",
            "sourceColumn": "Sättet på vilket utbildningen ordnas",
            "sortByColumn": "jarj_jarjtapa",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Typ av examen",
            "dataType": "string",
            "sourceColumn": "Typ av examen",
            "sortByColumn": "jarj_tutktyyppi",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Förvaltningsområde",
            "dataType": "string",
            "sourceColumn": "Förvaltningsområde",
            "sortByColumn": "jarj_hallinnonala",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Utbildningens språk",
            "dataType": "string",
            "sourceColumn": "Utbildningens språk",
            "sortByColumn": "jarj_opetuskieli",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Ungdoms-vuxenutbildning",
            "dataType": "string",
            "sourceColumn": "Ungdoms-/vuxenutbildning",
            "sortByColumn": "jarj_nuoretaikuiset",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Utbildningens landskap",
            "dataType": "string",
            "sourceColumn": "Utbildningens landskap",
            "sortByColumn": "jarjestys_maakunta",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Utbildningens NTM-område",
            "dataType": "string",
            "sourceColumn": "Utbildningens NTM-område",
            "sortByColumn": "jarjestys_ely",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Utbildningens RFV-område",
            "dataType": "string",
            "sourceColumn": "Utbildningens RFV-område",
            "sortByColumn": "jarjestys_avi",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Kön",
            "dataType": "string",
            "sourceColumn": "Kön",
            "sortByColumn": "jarj_sukupuoli",
            "displayFolder": "Personvariabler"
          },
          {
            "name": "Ungdoms-vuxenstuderande",
            "dataType": "string",
            "sourceColumn": "Ungdoms-/vuxenstuderande",
            "sortByColumn": "jarj_nuoriaikuinen",
            "displayFolder": "Personvariabler"
          },
          {
            "name": "Begynnelsetermin",
            "dataType": "string",
            "sourceColumn": "Begynnelsetermin",
            "sortByColumn": "jarj_lukukausi",
            "displayFolder": "Tidsvariabler"
          },
          {
            "name": "Begynnelseläsår",
            "dataType": "string",
            "sourceColumn": "Begynnelseläsår",
            "displayFolder": "Tidsvariabler"
          },
          {
            "name": "Begynnelseår",
            "dataType": "string",
            "sourceColumn": "Begynnelseår",
            "displayFolder": "Tidsvariabler"
          },
          {
            "name": "Inskrivning (januari)",
            "dataType": "string",
            "sourceColumn": "Inskrivning (januari)",
            "sortByColumn": "jarj_kirjtammi",
            "displayFolder": "Personvariabler"
          },
          {
            "name": "Inskrivning (september)",
            "dataType": "string",
            "sourceColumn": "Inskrivning (september)",
            "sortByColumn": "jarj_kirjsyys",
            "displayFolder": "Personvariabler"
          },
          {
            "name": "Formen i vilken utbildningen ordnas",
            "dataType": "string",
            "sourceColumn": "Formen i vilken utbildningen ordnas",
            "sortByColumn": "jarj_jarjmuoto",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Utbildningsslag",
            "dataType": "string",
            "sourceColumn": "Utbildningsslag",
            "sortByColumn": "jarjestys_koulutuslaji3",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Medborgarskap (land)",
            "dataType": "string",
            "sourceColumn": "Medborgarskap (land)",
            "sortByColumn": "jarj_maa",
            "displayFolder": "Personvariabler"
          },
          {
            "name": "Medborgarskap (världsdel)",
            "dataType": "string",
            "sourceColumn": "Medborgarskap (världsdel)",
            "sortByColumn": "jarjestys_maanosa",
            "displayFolder": "Personvariabler"
          },
          {
            "name": "Medborgare i ett EES-land",
            "dataType": "string",
            "sourceColumn": "Medborgare i ett EES-land",
            "sortByColumn": "jarjestys_etamaa",
            "displayFolder": "Personvariabler"
          },
          {
            "name": "Medborgare i ett EU-land",
            "dataType": "string",
            "sourceColumn": "Medborgare i ett EU-land",
            "sortByColumn": "jarjestys_eumaa",
            "displayFolder": "Personvariabler"
          },
          {
            "name": "Födelseland (världsdel)",
            "dataType": "string",
            "sourceColumn": "Födelseland (världsdel)",
            "sortByColumn": "jarj_syntmaanosa",
            "displayFolder": "Personvariabler"
          },
          {
            "name": "Modersmål",
            "dataType": "string",
            "sourceColumn": "Modersmål",
            "sortByColumn": "jarj_aidinkieli",
            "displayFolder": "Personvariabler"
          },
          {
            "name": "Name of education",
            "dataType": "string",
            "sourceColumn": "Name of education",
            "displayFolder": "Education variables"
          },
          {
            "name": "Subfield of education",
            "dataType": "string",
            "sourceColumn": "Subfield of education",
            "sortByColumn": "jarj_opintoala",
            "displayFolder": "Education variables"
          },
          {
            "name": "Field of education",
            "dataType": "string",
            "sourceColumn": "Field of education",
            "sortByColumn": "jarjestys_koulutusala2002",
            "displayFolder": "Education variables"
          },
          {
            "name": "Field of education  (1995)",
            "dataType": "string",
            "sourceColumn": "Field of education (1995)",
            "sortByColumn": "jarjestys_opintoala1995",
            "displayFolder": "Education variables"
          },
          {
            "name": "Field of education  (2002)",
            "dataType": "string",
            "sourceColumn": "Field of education (2002)",
            "sortByColumn": "jarjestys_koulutusala2002",
            "displayFolder": "Education variables"
          },
          {
            "name": "Level of education",
            "dataType": "string",
            "sourceColumn": "Level of education",
            "sortByColumn": "jarjestys_koulutusaste2002",
            "displayFolder": "Education variables"
          },
          {
            "name": "Method of vocational education and training",
            "dataType": "string",
            "sourceColumn": "Method of vocational education and training",
            "displayFolder": "Education variables"
          },
          {
            "name": "Qualification type",
            "dataType": "string",
            "sourceColumn": "Qualification type",
            "displayFolder": "Education variables"
          },
          {
            "name": "Administrative sector",
            "dataType": "string",
            "sourceColumn": "Administrative sector",
            "sortByColumn": "jarj_hallinnonala",
            "displayFolder": "Education variables"
          },
          {
            "name": "Language of education",
            "dataType": "string",
            "sourceColumn": "Language of education",
            "sortByColumn": "jarj_opetuskieli",
            "displayFolder": "Education variables"
          },
          {
            "name": "Youth/adult education",
            "dataType": "string",
            "sourceColumn": "Youth/adult education",
            "sortByColumn": "jarj_nuoretaikuiset",
            "displayFolder": "Education variables"
          },
          {
            "name": "Region of education",
            "dataType": "string",
            "sourceColumn": "Region of education",
            "sortByColumn": "jarjestys_maakunta",
            "displayFolder": "Education variables"
          },
          {
            "name": "ELY area of education",
            "dataType": "string",
            "sourceColumn": "ELY area of education",
            "sortByColumn": "jarjestys_ely",
            "displayFolder": "Education variables"
          },
          {
            "name": "AVI area of education",
            "dataType": "string",
            "sourceColumn": "AVI area of education",
            "sortByColumn": "jarjestys_avi",
            "displayFolder": "Education variables"
          },
          {
            "name": "Gender",
            "dataType": "string",
            "sourceColumn": "Gender",
            "sortByColumn": "jarj_sukupuoli",
            "displayFolder": "Person variables"
          },
          {
            "name": "Young person/adult student",
            "dataType": "string",
            "sourceColumn": "Young person/adult student",
            "sortByColumn": "jarj_nuoriaikuinen",
            "displayFolder": "Person variables"
          },
          {
            "name": "First term",
            "dataType": "string",
            "sourceColumn": "First term",
            "sortByColumn": "jarj_lukukausi",
            "displayFolder": "Time variables"
          },
          {
            "name": "First academic year",
            "dataType": "string",
            "sourceColumn": "First academic year",
            "displayFolder": "Time variables"
          },
          {
            "name": "Enrollment status (January)",
            "dataType": "string",
            "sourceColumn": "Enrollment status (January)",
            "sortByColumn": "jarj_kirjtammi",
            "displayFolder": "Person variables"
          },
          {
            "name": "Enrollment status (September)",
            "dataType": "string",
            "sourceColumn": "Enrollment status (September)",
            "sortByColumn": "jarj_kirjsyys",
            "displayFolder": "Person variables"
          },
          {
            "name": "Form of vocational education and training",
            "dataType": "string",
            "sourceColumn": "Form of vocational education and training",
            "sortByColumn": "jarj_jarjmuoto",
            "displayFolder": "Education variables"
          },
          {
            "name": "Form of education and training",
            "dataType": "string",
            "sourceColumn": "Form of education and training",
            "sortByColumn": "jarjestys_koulutuslaji3",
            "displayFolder": "Education variables"
          },
          {
            "name": "Nationality (country)",
            "dataType": "string",
            "sourceColumn": "Nationality (country)",
            "sortByColumn": "jarj_maa",
            "displayFolder": "Person variables"
          },
          {
            "name": "Nationality (continent)",
            "dataType": "string",
            "sourceColumn": "Nationality (continent)",
            "sortByColumn": "jarjestys_maanosa",
            "displayFolder": "Person variables"
          },
          {
            "name": "Citizen of EEA nation",
            "dataType": "string",
            "sourceColumn": "Citizen of EEA nation",
            "sortByColumn": "jarjestys_etamaa",
            "displayFolder": "Person variables"
          },
          {
            "name": "Citizen of EU nation",
            "dataType": "string",
            "sourceColumn": "Citizen of EU nation",
            "sortByColumn": "jarjestys_eumaa",
            "displayFolder": "Person variables"
          },
          {
            "name": "Country of birth",
            "dataType": "string",
            "sourceColumn": "Country of birth",
            "sortByColumn": "jarj_syntvaltio",
            "displayFolder": "Person variables"
          },
          {
            "name": "Country of birth (continent)",
            "dataType": "string",
            "sourceColumn": "Country of birth (continent)",
            "sortByColumn": "jarj_syntmaanosa",
            "displayFolder": "Person variables"
          },
          {
            "name": "Country of birth (Finland/Other)",
            "dataType": "string",
            "sourceColumn": "Country of birth (Finland/Other)",
            "sortByColumn": "jarj_syntsuomimuu",
            "displayFolder": "Person variables"
          },
          {
            "name": "Mother tongue",
            "dataType": "string",
            "sourceColumn": "Mother tongue",
            "sortByColumn": "jarj_aidinkieli",
            "displayFolder": "Person variables"
          },
          {
            "name": "Sector of education",
            "dataType": "string",
            "sourceColumn": "Sector of education",
            "sortByColumn": "jarj_koulsektori",
            "displayFolder": "Education variables"
          },
          {
            "name": "Kommungruppen",
            "dataType": "string",
            "sourceColumn": "Kommungruppen",
            "sortByColumn": "jarj_kuntaryhma",
            "displayFolder": "Personvariabler"
          },
          {
            "name": "Födelseland",
            "dataType": "string",
            "sourceColumn": "Födelseland",
            "sortByColumn": "jarj_syntvaltio",
            "displayFolder": "Personvariabler"
          },
          {
            "name": "Utbildningssektor",
            "dataType": "string",
            "sourceColumn": "Utbildningssektor",
            "sortByColumn": "jarj_koulsektori",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "First year",
            "dataType": "string",
            "sourceColumn": "First year",
            "displayFolder": "Time variables"
          },
          {
            "name": "Municipality type",
            "dataType": "string",
            "sourceColumn": "Municipality type",
            "sortByColumn": "jarj_kuntaryhma",
            "displayFolder": "Person variables"
          },
          {
            "name": "Koulutusaste, taso 1",
            "dataType": "string",
            "sourceColumn": "Koulutusaste, taso 1",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusaste, taso 2",
            "dataType": "string",
            "sourceColumn": "Koulutusaste, taso 2",
            "sortByColumn": "jarj_isced_koulast2",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusala, taso 1",
            "dataType": "string",
            "sourceColumn": "Koulutusala, taso 1",
            "sortByColumn": "jarj_isced_koulala1",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusala, taso 2",
            "dataType": "string",
            "sourceColumn": "Koulutusala, taso 2",
            "sortByColumn": "jarj_isced_koulala2",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusala, taso 3",
            "dataType": "string",
            "sourceColumn": "Koulutusala, taso 3",
            "sortByColumn": "jarj_isced_koulala3",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "OKM ohjauksen ala, korkeak.",
            "dataType": "string",
            "sourceColumn": "OKM ohjauksen ala, korkeak.",
            "sortByColumn": "jarj_isced_okmohjaus1",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Utbildn.nivå, nivå 1",
            "dataType": "string",
            "sourceColumn": "Utbildn.nivå, nivå 1",
            "sortByColumn": "jarj_isced_koulast1",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Utbildn.nivå, nivå 2",
            "dataType": "string",
            "sourceColumn": "Utbildn.nivå, nivå 2",
            "sortByColumn": "jarj_isced_koulast2",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Utbildn.område, nivå 1",
            "dataType": "string",
            "sourceColumn": "Utbildn.område, nivå 1",
            "sortByColumn": "jarj_isced_koulala1",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Utbildn.område, nivå 2",
            "dataType": "string",
            "sourceColumn": "Utbildn.område, nivå 2",
            "sortByColumn": "jarj_isced_koulala2",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Utbildn.område, nivå 3",
            "dataType": "string",
            "sourceColumn": "Utbildn.område, nivå 3",
            "sortByColumn": "jarj_isced_koulala3",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "UKM-styrningsområde högskolor",
            "dataType": "string",
            "sourceColumn": "UKM-styrningsområde, högskolor",
            "sortByColumn": "jarj_isced_okmohjaus1",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Level of education, tier 1",
            "dataType": "string",
            "sourceColumn": "Level of education, tier 1",
            "sortByColumn": "jarj_isced_koulast1",
            "displayFolder": "Education variables"
          },
          {
            "name": "Level of education, tier 2",
            "dataType": "string",
            "sourceColumn": "Level of education, tier 2",
            "sortByColumn": "jarj_isced_koulast2",
            "displayFolder": "Education variables"
          },
          {
            "name": "Field of education, tier 1",
            "dataType": "string",
            "sourceColumn": "Field of education, tier 1",
            "sortByColumn": "jarj_isced_koulala1",
            "displayFolder": "Education variables"
          },
          {
            "name": "Field of education, tier 2",
            "dataType": "string",
            "sourceColumn": "Field of education, tier 2",
            "sortByColumn": "jarj_isced_koulala2",
            "displayFolder": "Education variables"
          },
          {
            "name": "Field of education, tier 3",
            "dataType": "string",
            "sourceColumn": "Field of education, tier 3",
            "sortByColumn": "jarj_isced_koulala3",
            "displayFolder": "Education variables"
          },
          {
            "name": "Field of ed HE steering",
            "dataType": "string",
            "sourceColumn": "Field of ed., HE steering",
            "sortByColumn": "jarj_isced_okmohjaus1",
            "displayFolder": "Education variables"
          },
          {
            "name": "Koodit Koulutusnimike",
            "dataType": "string",
            "sourceColumn": "Koodit Koulutusnimike",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koodit Opintoala",
            "dataType": "string",
            "sourceColumn": "Koodit Opintoala",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koodit Koulutusala",
            "dataType": "string",
            "sourceColumn": "Koodit Koulutusala",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koodit Koulutusala (1995) luokitus",
            "dataType": "string",
            "sourceColumn": "Koodit Koulutusala (95 luokitus)",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koodit Koulutusala (2002) luokitus",
            "dataType": "string",
            "sourceColumn": "Koodit Koulutusala (02 luokitus)",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koodit Koulutuksen maakunta",
            "dataType": "string",
            "sourceColumn": "Koodit Koulutuksen maakunta",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Statistikår",
            "dataType": "string",
            "sourceColumn": "Statistikår",
            "displayFolder": "Tidsvariabler"
          },
          {
            "name": "Studieområde",
            "dataType": "string",
            "sourceColumn": "Studieområde",
            "sortByColumn": "jarj_opintoala",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Utbildningsområde",
            "dataType": "string",
            "sourceColumn": "Utbildningsområde",
            "sortByColumn": "jarjestys_koulutusala2002",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Utbildningsområde  (1995)",
            "dataType": "string",
            "sourceColumn": "Utbildningsområde (1995)",
            "sortByColumn": "jarjestys_opintoala1995",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Statistical year",
            "dataType": "string",
            "sourceColumn": "Statistical year",
            "displayFolder": "Time variables"
          },
          {
            "name": "Medborgarskap (finska/andra)",
            "dataType": "string",
            "sourceColumn": "Medborgarskap (finska/andra)",
            "sortByColumn": "jarj_kans",
            "displayFolder": "Personvariabler"
          },
          {
            "name": "Födelseland (Finland/andra)",
            "dataType": "string",
            "sourceColumn": "Födelseland (Finland/andra)",
            "sortByColumn": "jarj_syntsuomimuu",
            "displayFolder": "Personvariabler"
          },
          {
            "name": "Modersmål (finska/andra)",
            "dataType": "string",
            "sourceColumn": "Modersmål (finska/andra)",
            "sortByColumn": "jarj_aidinkielisuomi",
            "displayFolder": "Personvariabler"
          },
          {
            "name": "Nationality (Finn/Other)",
            "dataType": "string",
            "sourceColumn": "Nationality (Finn/Other)",
            "sortByColumn": "jarj_kans",
            "displayFolder": "Person variables"
          },
          {
            "name": "Mother tongue (Finnish/Other)",
            "dataType": "string",
            "sourceColumn": "Mother tongue (Finnish/Other)",
            "sortByColumn": "jarj_aidinkielisuomi",
            "displayFolder": "Person variables"
          },
          {
            "name": "jarj_isced_koulast1",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_isced_koulast1"
          },
          {
            "name": "jarj_isced_koulast2",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_isced_koulast2"
          },
          {
            "name": "jarj_isced_koulala1",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_isced_koulala1"
          },
          {
            "name": "jarj_isced_koulala2",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_isced_koulala2"
          },
          {
            "name": "jarj_isced_koulala3",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_isced_koulala3"
          },
          {
            "name": "jarj_isced_okmohjaus1",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_isced_okmohjaus1"
          },
          {
            "name": "Koulutusaste_taso2_koodi",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Koulutusaste_taso2_koodi"
          }
        ],
        "partitions": [
          {
            "name": "v_f_tab_ulkomaalaiset_maan_kansalaisuuden_aidinkielen_mukaan",
            "source": {
              "query": "SELECT [dbo].[v_f_tab_ulkomaalaiset_maan_kansalaisuuden_aidinkielen_mukaan_yo].* FROM [dbo].[v_f_tab_ulkomaalaiset_maan_kansalaisuuden_aidinkielen_mukaan_yo]",
              "dataSource": "SqlServer dwitestvipusql VipunenTK"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": "&lt;?xml version=\"1.0\" encoding=\"UTF-16\"?&gt;&lt;Gemini xmlns=\"TableWidgetSerialization\"&gt;&lt;AnnotationContent&gt;&lt;![CDATA[&lt;?xml version=\"1.0\"?&gt;\n&lt;TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\"&gt;\n  &lt;ColumnSuggestedType /&gt;\n  &lt;ColumnFormat /&gt;\n  &lt;ColumnAccuracy /&gt;\n  &lt;ColumnCurrencySymbol /&gt;\n  &lt;ColumnPositivePattern /&gt;\n  &lt;ColumnNegativePattern /&gt;\n  &lt;ColumnWidths&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;lkm_op2&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;69&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;lkm_aloit2&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;77&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;lkm_opiskolo2&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;95&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Tilastovuosi&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;86&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Näkökulma&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;81&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Lähde&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;59&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koulutusnimike&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;100&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Opintoala&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;76&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koulutusala&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;85&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koulutusala (95 luokitus)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;147&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koulutusala (02 luokitus)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;147&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koulutusaste&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;92&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Järjestämistapa&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;106&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Tutkintotyyppi&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;99&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Hallinnonala&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;87&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Opetuskieli&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;82&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Nuorten koulutus/aikuiskoulutus&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;182&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koulutuksen maakunta&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;138&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koulutuksen ELY-alue&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;132&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koulutuksen AVI-alue&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;132&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Sukupuoli&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;75&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Nuori opiskelija/aikuisopiskelija&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;174&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Aloituslukukausi&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;105&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Aloituslukuvuosi&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;106&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Aloitusvuosi&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;87&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Kirjoillaolo (tammi)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;116&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Kirjoillaolo (syys)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;110&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Kuntaryhmä&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;88&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Järjestämismuoto&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;114&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koulutuslaji&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;84&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Kansalaisuus (maa)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;122&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Kansalaisuus (maanosa)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;145&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;ETA-maan kansalainen&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;138&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;EU-maan kansalainen&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;132&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Kansalaisuus (suomi/muu)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;153&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Syntymävaltio&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;98&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Syntymävaltio (maanosa)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;152&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Syntymävaltio (suomi/muu)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;160&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Äidinkieli&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;70&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Äidinkieli (suomi/muu)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;132&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koulutussektori&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;103&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;lahde_koodi&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;87&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_koulnimike&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;100&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_opintoala&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;96&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarjestys_koulutusala2002&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;156&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarjestys_opintoala1995&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;146&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarjestys_koulutusaste2002&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;163&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_jarjtapa&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;90&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_tutktyyppi&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;101&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_hallinnonala&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;108&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_opetuskieli&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;102&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_nuoretaikuiset&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;120&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarjestys_maakunta&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;125&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarjestys_ely&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;92&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarjestys_avi&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;92&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_sukupuoli&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;96&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_nuoriaikuinen&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;115&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_lukukausi&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;95&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_kirjtammi&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;94&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_kirjsyys&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;88&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_kuntaryhma&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;109&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_jarjmuoto&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;98&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarjestys_koulutuslaji3&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;137&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_maa&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;72&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarjestys_maanosa&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;121&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarjestys_etamaa&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;114&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarjestys_eumaa&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;110&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_kans&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;74&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_syntvaltio&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;99&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_syntmaanosa&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;116&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_syntsuomimuu&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;120&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_aidinkieli&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;91&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_aidinkielisuomi&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;118&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_koulsektori&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;103&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;koulutusaste2002_koodi&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;146&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;koulutuksen_aloittamislukuvuosi&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;182&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Aineistonäkökulma&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;118&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;koodi_ai&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;69&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;koodi_kan&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;78&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;koodi_syn&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;78&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Utbildningsbenämning&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;134&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Studieområde&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;96&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Statistikår&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;78&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Utbildningsområde (2002)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;153&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Utbildningsnivå&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;102&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Sättet på vilket utbildningen ordnas&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;200&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Typ av examen&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;104&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Förvaltningsområde&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;125&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Utbildningens språk&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;123&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Ungdoms-/vuxenutbildning&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;158&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Utbildningens landskap&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;139&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Utbildningens NTM-område&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;158&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Utbildningens RFV-område&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;156&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Kön&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;48&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Ungdoms-/vuxenstuderande&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;167&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Begynnelsetermin&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;115&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Begynnelseläsår&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;108&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Begynnelseår&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;95&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Inskrivning (januari)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;126&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Inskrivning (september)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;144&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Municipality type&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;110&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Formen i vilken utbildningen ordnas&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;198&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Utbildningsslag&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;101&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Medborgarskap (land)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;135&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Medborgarskap (världsdel)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;158&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Medborgare i ett EES-land&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;155&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Medborgare i ett EU-land&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;150&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Mother tongue (Finnish/Other)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;177&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;First year&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;76&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Födelseland (världsdel)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;141&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Nationality (Finn/Other)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;144&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Modersmål&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;81&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Utbildningssektor&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;112&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Modersmål (finska/andra)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;152&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Name of education&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;120&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Subfield of education&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;131&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Field of education&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;115&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Field of education (1995)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;150&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Field of education (2002)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;150&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Level of education&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;118&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Method of vocational education and training&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;241&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Qualification type&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;114&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Administrative sector&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;131&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Language of education&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;140&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Youth/adult education&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;136&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Region of education&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;126&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;ELY area of education&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;135&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;AVI area of education&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;135&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Gender&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;65&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Young person/adult student&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;164&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;First term&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;76&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;First academic year&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;123&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Födelseland&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;87&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Enrollment status (January)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;163&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Enrollment status (September)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;176&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Kommungruppen&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;110&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Form of vocational education and training&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;229&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Form of education and training&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;177&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Nationality (country)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;129&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Nationality (continent)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;137&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Citizen of EEA nation&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;130&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Citizen of EU nation&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;124&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Födelseland (Finland/andra)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;164&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Country of birth&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;107&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Country of birth (continent)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;163&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Country of birth (Finland/Other)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;184&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Mother tongue&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;101&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Medborgarskap (finska/andra)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;175&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Sector of education&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;124&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koulutusaste, taso 1&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;129&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koulutusaste, taso 2&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;129&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koulutusala, taso 1&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;122&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koulutusala, taso 2&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;122&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koulutusala, taso 3&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;122&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;OKM ohjauksen ala, korkeak.&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;169&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Utbildn.nivå, nivå 1&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;123&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Utbildn.nivå, nivå 2&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;123&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Utbildn.område, nivå 1&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;139&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Utbildn.område, nivå 2&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;139&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Utbildn.område, nivå 3&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;139&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;UKM-styrningsområde, högskolor&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;188&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Level of education, tier 1&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;150&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Level of education, tier 2&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;150&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Field of education, tier 1&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;147&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Field of education, tier 2&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;147&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Field of education, tier 3&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;147&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Field of ed., HE steering&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;146&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koodit Koulutusnimike&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;133&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koodit Opintoala&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;109&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koodit Koulutusala&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;118&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koodit Koulutusala (95 luokitus)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;180&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koodit Koulutusala (02 luokitus)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;180&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koodit Koulutuksen maakunta&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;171&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Utbildningsområde&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;118&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Utbildningsområde (1995)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;153&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Statistical year&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;101&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_isced_koulast1&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;122&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_isced_koulast2&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;122&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_isced_koulala1&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;121&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_isced_koulala2&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;121&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_isced_koulala3&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;121&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_isced_okmohjaus1&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;139&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koulutusaste_taso2_koodi&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;196&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n  &lt;/ColumnWidths&gt;\n  &lt;ColumnDisplayIndex&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;lkm_op2&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;0&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;lkm_aloit2&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;1&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;lkm_opiskolo2&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;2&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Tilastovuosi&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;3&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Näkökulma&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;4&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Lähde&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;5&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koulutusnimike&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;6&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Opintoala&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;7&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koulutusala&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;8&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koulutusala (95 luokitus)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;9&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koulutusala (02 luokitus)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;10&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koulutusaste&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;11&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Järjestämistapa&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;12&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Tutkintotyyppi&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;13&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Hallinnonala&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;14&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Opetuskieli&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;15&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Nuorten koulutus/aikuiskoulutus&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;16&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koulutuksen maakunta&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;17&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koulutuksen ELY-alue&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;18&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koulutuksen AVI-alue&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;19&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Sukupuoli&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;20&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Nuori opiskelija/aikuisopiskelija&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;21&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Aloituslukukausi&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;22&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Aloituslukuvuosi&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;23&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Aloitusvuosi&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;24&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Kirjoillaolo (tammi)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;25&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Kirjoillaolo (syys)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;26&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Kuntaryhmä&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;27&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Järjestämismuoto&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;28&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koulutuslaji&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;29&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Kansalaisuus (maa)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;30&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Kansalaisuus (maanosa)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;31&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;ETA-maan kansalainen&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;32&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;EU-maan kansalainen&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;33&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Kansalaisuus (suomi/muu)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;34&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Syntymävaltio&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;35&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Syntymävaltio (maanosa)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;36&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Syntymävaltio (suomi/muu)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;37&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Äidinkieli&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;38&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Äidinkieli (suomi/muu)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;39&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koulutussektori&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;40&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;lahde_koodi&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;41&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_koulnimike&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;42&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_opintoala&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;43&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarjestys_koulutusala2002&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;44&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarjestys_opintoala1995&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;45&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarjestys_koulutusaste2002&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;46&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_jarjtapa&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;47&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_tutktyyppi&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;48&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_hallinnonala&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;49&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_opetuskieli&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;50&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_nuoretaikuiset&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;51&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarjestys_maakunta&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;52&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarjestys_ely&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;53&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarjestys_avi&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;54&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_sukupuoli&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;55&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_nuoriaikuinen&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;56&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_lukukausi&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;57&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_kirjtammi&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;58&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_kirjsyys&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;59&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_kuntaryhma&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;60&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_jarjmuoto&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;61&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarjestys_koulutuslaji3&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;62&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_maa&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;63&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarjestys_maanosa&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;64&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarjestys_etamaa&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;65&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarjestys_eumaa&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;66&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_kans&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;67&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_syntvaltio&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;68&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_syntmaanosa&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;69&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_syntsuomimuu&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;70&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_aidinkieli&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;71&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_aidinkielisuomi&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;72&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_koulsektori&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;73&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;koulutusaste2002_koodi&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;74&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;koulutuksen_aloittamislukuvuosi&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;75&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Aineistonäkökulma&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;76&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;koodi_ai&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;77&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;koodi_kan&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;78&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;koodi_syn&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;79&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Utbildningsbenämning&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;80&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Studieområde&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;167&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Statistikår&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;166&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Utbildningsområde (2002)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;81&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Utbildningsnivå&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;82&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Sättet på vilket utbildningen ordnas&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;83&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Typ av examen&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;84&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Förvaltningsområde&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;85&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Utbildningens språk&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;86&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Ungdoms-/vuxenutbildning&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;87&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Utbildningens landskap&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;88&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Utbildningens NTM-område&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;89&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Utbildningens RFV-område&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;90&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Kön&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;91&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Ungdoms-/vuxenstuderande&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;92&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Begynnelsetermin&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;93&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Begynnelseläsår&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;94&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Begynnelseår&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;95&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Inskrivning (januari)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;96&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Inskrivning (september)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;97&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Municipality type&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;141&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Formen i vilken utbildningen ordnas&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;98&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Utbildningsslag&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;99&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Medborgarskap (land)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;100&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Medborgarskap (världsdel)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;101&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Medborgare i ett EES-land&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;102&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Medborgare i ett EU-land&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;103&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Mother tongue (Finnish/Other)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;175&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;First year&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;140&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Födelseland (världsdel)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;104&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Nationality (Finn/Other)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;174&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Modersmål&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;105&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Utbildningssektor&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;139&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Modersmål (finska/andra)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;173&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Name of education&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;106&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Subfield of education&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;107&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Field of education&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;108&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Field of education (1995)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;109&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Field of education (2002)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;110&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Level of education&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;111&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Method of vocational education and training&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;112&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Qualification type&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;113&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Administrative sector&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;114&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Language of education&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;115&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Youth/adult education&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;116&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Region of education&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;117&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;ELY area of education&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;118&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;AVI area of education&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;119&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Gender&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;120&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Young person/adult student&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;121&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;First term&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;122&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;First academic year&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;123&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Födelseland&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;138&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Enrollment status (January)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;124&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Enrollment status (September)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;125&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Kommungruppen&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;137&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Form of vocational education and training&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;126&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Form of education and training&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;127&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Nationality (country)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;128&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Nationality (continent)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;129&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Citizen of EEA nation&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;130&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Citizen of EU nation&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;131&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Födelseland (Finland/andra)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;172&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Country of birth&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;132&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Country of birth (continent)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;133&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Country of birth (Finland/Other)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;134&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Mother tongue&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;135&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Medborgarskap (finska/andra)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;171&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Sector of education&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;136&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koulutusaste, taso 1&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;142&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koulutusaste, taso 2&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;143&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koulutusala, taso 1&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;144&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koulutusala, taso 2&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;145&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koulutusala, taso 3&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;146&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;OKM ohjauksen ala, korkeak.&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;147&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Utbildn.nivå, nivå 1&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;148&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Utbildn.nivå, nivå 2&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;149&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Utbildn.område, nivå 1&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;150&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Utbildn.område, nivå 2&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;151&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Utbildn.område, nivå 3&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;152&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;UKM-styrningsområde, högskolor&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;153&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Level of education, tier 1&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;154&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Level of education, tier 2&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;155&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Field of education, tier 1&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;156&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Field of education, tier 2&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;157&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Field of education, tier 3&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;158&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Field of ed., HE steering&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;159&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koodit Koulutusnimike&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;160&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koodit Opintoala&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;161&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koodit Koulutusala&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;162&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koodit Koulutusala (95 luokitus)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;163&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koodit Koulutusala (02 luokitus)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;164&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koodit Koulutuksen maakunta&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;165&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Utbildningsområde&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;168&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Utbildningsområde (1995)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;169&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Statistical year&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;170&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_isced_koulast1&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;176&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_isced_koulast2&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;177&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_isced_koulala1&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;178&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_isced_koulala2&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;179&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_isced_koulala3&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;180&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_isced_okmohjaus1&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;181&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koulutusaste_taso2_koodi&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;182&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n  &lt;/ColumnDisplayIndex&gt;\n  &lt;ColumnFrozen /&gt;\n  &lt;ColumnChecked&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Aineistonäkökulma&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;koodi_ai&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;koodi_kan&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;koodi_syn&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Utbildningsbenämning&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Studieområde&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Statistikår&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Utbildningsområde (2002)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Utbildningsnivå&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Sättet på vilket utbildningen ordnas&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Typ av examen&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Förvaltningsområde&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Utbildningens språk&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Ungdoms-/vuxenutbildning&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Utbildningens landskap&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Utbildningens NTM-område&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Utbildningens RFV-område&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Kön&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Ungdoms-/vuxenstuderande&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Begynnelsetermin&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Begynnelseläsår&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Begynnelseår&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Inskrivning (januari)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Inskrivning (september)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Municipality type&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Formen i vilken utbildningen ordnas&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Utbildningsslag&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Medborgarskap (land)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Medborgarskap (världsdel)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Medborgare i ett EES-land&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Medborgare i ett EU-land&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Mother tongue (Finnish/Other)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;First year&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Födelseland (världsdel)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Nationality (Finn/Other)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Modersmål&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Utbildningssektor&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Modersmål (finska/andra)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Name of education&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Subfield of education&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Field of education&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Field of education (1995)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Field of education (2002)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Level of education&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Method of vocational education and training&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Qualification type&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Administrative sector&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Language of education&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Youth/adult education&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Region of education&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;ELY area of education&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;AVI area of education&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Gender&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Young person/adult student&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;First term&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;First academic year&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Födelseland&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Enrollment status (January)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Enrollment status (September)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Kommungruppen&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Form of vocational education and training&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Form of education and training&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Nationality (country)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Nationality (continent)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Citizen of EEA nation&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Citizen of EU nation&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Födelseland (Finland/andra)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Country of birth&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Country of birth (continent)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Country of birth (Finland/Other)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Mother tongue&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Medborgarskap (finska/andra)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Sector of education&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koulutusaste, taso 1&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koulutusaste, taso 2&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koulutusala, taso 1&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koulutusala, taso 2&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koulutusala, taso 3&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;OKM ohjauksen ala, korkeak.&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Utbildn.nivå, nivå 1&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Utbildn.nivå, nivå 2&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Utbildn.område, nivå 1&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Utbildn.område, nivå 2&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Utbildn.område, nivå 3&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;UKM-styrningsområde, högskolor&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Level of education, tier 1&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Level of education, tier 2&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Field of education, tier 1&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Field of education, tier 2&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Field of education, tier 3&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Field of ed., HE steering&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koodit Koulutusnimike&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koodit Opintoala&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koodit Koulutusala&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koodit Koulutusala (95 luokitus)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koodit Koulutusala (02 luokitus)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koodit Koulutuksen maakunta&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Utbildningsområde&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Utbildningsområde (1995)&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Statistical year&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_isced_koulast1&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_isced_koulast2&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_isced_koulala1&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_isced_koulala2&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_isced_koulala3&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;jarj_isced_okmohjaus1&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koulutusaste_taso2_koodi&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n  &lt;/ColumnChecked&gt;\n  &lt;ColumnFilter /&gt;\n  &lt;SelectionFilter /&gt;\n  &lt;FilterParameters /&gt;\n  &lt;IsSortDescending&gt;false&lt;/IsSortDescending&gt;\n&lt;/TableWidgetGridSerialization&gt;]]&gt;&lt;/AnnotationContent&gt;&lt;/Gemini&gt;"
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Kaikki opiskelijat",
            "expression": "IF(SUM([lkm_op2]) = 0, BLANK(), IF(SUM([lkm_op2]) < 5, \"1-4\", MROUND(SUM([lkm_op2]), 3)))",
            "formatString": "#,0"
          },
          {
            "name": "Kaikki aloittaneet",
            "expression": "IF([lkm_aloit3] = 0, BLANK(), IF([lkm_aloit3] < 5, \"1-4\", MROUND([lkm_aloit3], 3)))",
            "formatString": "#,0"
          },
          {
            "name": "Kaikki läsnäolevaksi kirjautuneet opiskelijat",
            "expression": "IF(SUM([lkm_opiskolo2]) = 0, BLANK(), IF(SUM([lkm_opiskolo2]) < 5, \"1-4\", MROUND(SUM([lkm_opiskolo2]), 3)))",
            "formatString": "#,0"
          },
          {
            "name": "Kaikki uudet opiskelijat",
            "expression": "IF([lkm_aloit3] = 0, BLANK(), IF([lkm_aloit3] < 5, \"1-4\", MROUND([lkm_aloit3], 3)))",
            "formatString": "#,0"
          },
          {
            "name": "lkm_aloit3",
            "expression": "CALCULATE(SUM([lkm_aloit2]), FILTER('Muuttujat', [Koulutusaste_taso2_koodi] <> \"73\"), FILTER('Muuttujat', [Koulutusaste_taso2_koodi] <> \"81\"), FILTER('Muuttujat', [Koulutusaste_taso2_koodi] <> \"82\"))",
            "formatString": "#,0",
            "isHidden": true
          },
          {
            "name": "Vieraskieliset opiskelijat",
            "expression": "CALCULATE([Kaikki opiskelijat], FILTER('Muuttujat', [koodi_ai] <> \"fs\" && [koodi_ai] <> \"sv\"))",
            "formatString": "#,0"
          },
          {
            "name": "Ulkomaalaiset opiskelijat",
            "expression": "CALCULATE([Kaikki opiskelijat], FILTER('Muuttujat', [koodi_kan] <> \"1\"))",
            "formatString": "#,0"
          },
          {
            "name": "Ulkomailla syntyneet opiskelijat",
            "expression": "CALCULATE([Kaikki opiskelijat], FILTER('Muuttujat', [koodi_syn] <> \"1\"))",
            "formatString": "#,0"
          },
          {
            "name": "Ulkomaalaiset aloittaneet",
            "expression": "CALCULATE([Kaikki aloittaneet], FILTER('Muuttujat', [koodi_kan] <> \"1\"))",
            "formatString": "#,0"
          },
          {
            "name": "Vieraskieliset aloittaneet",
            "expression": "CALCULATE([Kaikki aloittaneet], FILTER('Muuttujat', [koodi_ai] <> \"fs\" && [koodi_ai] <> \"sv\"))",
            "formatString": "#,0"
          },
          {
            "name": "Ulkomailla syntyneet aloittaneet",
            "expression": "CALCULATE([Kaikki aloittaneet], FILTER('Muuttujat', [koodi_syn] <> \"1\"))",
            "formatString": "#,0"
          },
          {
            "name": "Vieraskieliset uudet opiskelijat",
            "expression": "CALCULATE([Kaikki uudet opiskelijat], FILTER('Muuttujat', [koodi_ai] <> \"fs\" && [koodi_ai] <> \"sv\"))",
            "formatString": "#,0"
          },
          {
            "name": "Ulkomaalaiset uudet opiskelijat",
            "expression": "CALCULATE([Kaikki uudet opiskelijat], FILTER('Muuttujat', [koodi_kan] <> \"1\"))",
            "formatString": "#,0"
          },
          {
            "name": "Ulkomailla syntyneet uudet opiskelijat",
            "expression": "CALCULATE([Kaikki uudet opiskelijat], FILTER('Muuttujat', [koodi_syn] <> \"1\"))",
            "formatString": "#,0"
          },
          {
            "name": "Läsnäolevaksi kirjautuneet vieraskieliset opiskelijat",
            "expression": "CALCULATE([Kaikki läsnäolevaksi kirjautuneet opiskelijat], FILTER('Muuttujat', [koodi_ai] <> \"fs\" && [koodi_ai] <> \"sv\"))",
            "formatString": "#,0"
          },
          {
            "name": "Läsnäolevaksi kirjautuneet ulkomaalaiset opiskelijat",
            "expression": "CALCULATE([Kaikki läsnäolevaksi kirjautuneet opiskelijat], FILTER('Muuttujat', [koodi_kan] <> \"1\"))",
            "formatString": "#,0"
          },
          {
            "name": "Läsnäolevaksi kirjautuneet ulkomailla syntyneet opiskelijat",
            "expression": "CALCULATE([Kaikki läsnäolevaksi kirjautuneet opiskelijat], FILTER('Muuttujat', [koodi_syn] <> \"1\"))",
            "formatString": "#,0"
          },
          {
            "name": "Vieraskielisten opiskelijoiden osuus kaikista opiskelijoista",
            "expression": "var lkm = [Vieraskieliset opiskelijat]\nreturn IF(lkm = BLANK(), BLANK(),\n\tvar kaikki = CALCULATE([Kaikki opiskelijat], ALL(Muuttujat[Äidinkieli]), ALL(Muuttujat[Äidinkieli (suomi/muu)]))\n                return IF(kaikki = \"1-4\", \"25 % – 100 %\",\n                                IF(lkm = \"1-4\", IF(kaikki > 8000, \"0.0 %\", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),\n                                     lkm / kaikki)))",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Ulkomaalaisten opiskelijoiden osuus kaikista opiskelijoista",
            "expression": "var lkm = [Ulkomaalaiset opiskelijat]\nreturn IF(lkm = BLANK(), BLANK(),\n\tvar kaikki = CALCULATE([Kaikki opiskelijat], ALL('Muuttujat'[Kansalaisuus (maanosa)]), ALL('Muuttujat'[Kansalaisuus (maa)]), ALL('Muuttujat'[Kansalaisuus (suomi/muu)]))\n                return IF(kaikki = \"1-4\", \"25 % – 100 %\",\n                                IF(lkm = \"1-4\", IF(kaikki > 8000, \"0.0 %\", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),\n                                     lkm / kaikki)))",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Ulkomailla syntyneiden opiskelijoiden osuus kaikista opiskelijoista",
            "expression": "var lkm = [Ulkomailla syntyneet opiskelijat]\nreturn IF(lkm = BLANK(), BLANK(),\n\tvar kaikki = CALCULATE([Kaikki opiskelijat], ALL(Muuttujat[Syntymämaa]), ALL(Muuttujat[Syntymämaa (maanosa)]), ALL(Muuttujat[Syntymämaa (suomi/muu)]))\n                return IF(kaikki = \"1-4\", \"25 % – 100 %\",\n                                IF(lkm = \"1-4\", IF(kaikki > 8000, \"0.0 %\", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),\n                                     lkm / kaikki)))",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Vieraskielisten aloittaneiden osuus kaikista aloittaneista",
            "expression": "var lkm = [Vieraskieliset aloittaneet]\nreturn IF(lkm = BLANK(), BLANK(),\n\tvar kaikki = CALCULATE([Kaikki aloittaneet], ALL(Muuttujat[Äidinkieli]), ALL(Muuttujat[Äidinkieli (suomi/muu)]))\n                return IF(kaikki = \"1-4\", \"25 % – 100 %\",\n                                IF(lkm = \"1-4\", IF(kaikki > 8000, \"0.0 %\", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),\n                                     lkm / kaikki)))",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Ulkomaalaisten aloittaneiden osuus kaikista aloittaneista",
            "expression": "var lkm = [Ulkomaalaiset aloittaneet]\nreturn IF(lkm = BLANK(), BLANK(),\n\tvar kaikki = CALCULATE([Kaikki aloittaneet], ALL('Muuttujat'[Kansalaisuus (maanosa)]), ALL('Muuttujat'[Kansalaisuus (maa)]), ALL('Muuttujat'[Kansalaisuus (suomi/muu)]))\n                return IF(kaikki = \"1-4\", \"25 % – 100 %\",\n                                IF(lkm = \"1-4\", IF(kaikki > 8000, \"0.0 %\", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),\n                                     lkm / kaikki)))",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Ulkomailla syntyneiden aloittaneiden osuus kaikista aloittaneista",
            "expression": "var lkm = [Ulkomailla syntyneet aloittaneet]\nreturn IF(lkm = BLANK(), BLANK(),\n\tvar kaikki = CALCULATE([Kaikki aloittaneet], ALL(Muuttujat[Syntymämaa]), ALL(Muuttujat[Syntymämaa (maanosa)]), ALL(Muuttujat[Syntymämaa (suomi/muu)]))\n                return IF(kaikki = \"1-4\", \"25 % – 100 %\",\n                                IF(lkm = \"1-4\", IF(kaikki > 8000, \"0.0 %\", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),\n                                     lkm / kaikki)))",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Vieraskielisten uusien opiskelijoiden osuus kaikista uusista opiskelijoista",
            "expression": "var lkm = [Vieraskieliset uudet opiskelijat]\nreturn IF(lkm = BLANK(), BLANK(),\n\tvar kaikki = CALCULATE([Kaikki uudet opiskelijat], ALL(Muuttujat[Äidinkieli]), ALL(Muuttujat[Äidinkieli (suomi/muu)]))\n                return IF(kaikki = \"1-4\", \"25 % – 100 %\",\n                                IF(lkm = \"1-4\", IF(kaikki > 8000, \"0.0 %\", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),\n                                     lkm / kaikki)))",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Ulkomaalaisten uusien opiskelijoiden osuus kaikista uusista opiskelijoista",
            "expression": "var lkm = [Ulkomaalaiset uudet opiskelijat]\nreturn IF(lkm = BLANK(), BLANK(),\n\tvar kaikki = CALCULATE([Kaikki uudet opiskelijat], ALL('Muuttujat'[Kansalaisuus (maanosa)]), ALL('Muuttujat'[Kansalaisuus (maa)]), ALL('Muuttujat'[Kansalaisuus (suomi/muu)]))\n                return IF(kaikki = \"1-4\", \"25 % – 100 %\",\n                                IF(lkm = \"1-4\", IF(kaikki > 8000, \"0.0 %\", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),\n                                     lkm / kaikki)))",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Ulkomailla syntyneiden uusien opiskelijoiden osuus kaikista uusista opiskelijoista",
            "expression": "var lkm = [Ulkomailla syntyneet uudet opiskelijat]\nreturn IF(lkm = BLANK(), BLANK(),\n\tvar kaikki = CALCULATE([Kaikki uudet opiskelijat], ALL(Muuttujat[Syntymämaa]), ALL(Muuttujat[Syntymämaa (maanosa)]), ALL(Muuttujat[Syntymämaa (suomi/muu)]))\n                return IF(kaikki = \"1-4\", \"25 % – 100 %\",\n                                IF(lkm = \"1-4\", IF(kaikki > 8000, \"0.0 %\", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),\n                                     lkm / kaikki)))",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Läsnäolevaksi kirj. vieraskielisten opiskelijoiden osuus kaikista läsnäolevista",
            "expression": "var lkm = [Läsnäolevaksi kirjautuneet vieraskieliset opiskelijat]\nreturn IF(lkm = BLANK(), BLANK(),\n\tvar kaikki = CALCULATE([Kaikki läsnäolevaksi kirjautuneet opiskelijat], ALL(Muuttujat[Äidinkieli]), ALL(Muuttujat[Äidinkieli (suomi/muu)]))\n                return IF(kaikki = \"1-4\", \"25 % – 100 %\",\n                                IF(lkm = \"1-4\", IF(kaikki > 8000, \"0.0 %\", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),\n                                     lkm / kaikki)))",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Läsnäolevaksi kirj. ulkomaalaisten opiskelijoiden osuus kaik. läsnäolevista",
            "expression": "var lkm = [Läsnäolevaksi kirjautuneet ulkomaalaiset opiskelijat]\nreturn IF(lkm = BLANK(), BLANK(),\n\tvar kaikki = CALCULATE([Kaikki läsnäolevaksi kirjautuneet opiskelijat], ALL('Muuttujat'[Kansalaisuus (maanosa)]), ALL('Muuttujat'[Kansalaisuus (maa)]), ALL('Muuttujat'[Kansalaisuus (suomi/muu)]))\n                return IF(kaikki = \"1-4\", \"25 % – 100 %\",\n                                IF(lkm = \"1-4\", IF(kaikki > 8000, \"0.0 %\", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),\n                                     lkm / kaikki)))",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Läsnäolevaksi kirj. ulkomailla syntyneiden opiskelijoiden osuus kaikista läsnäolevista",
            "expression": "var lkm = [Läsnäolevaksi kirjautuneet ulkomailla syntyneet opiskelijat]\nreturn IF(lkm = BLANK(), BLANK(),\n\tvar kaikki = CALCULATE([Kaikki läsnäolevaksi kirjautuneet opiskelijat], ALL(Muuttujat[Syntymämaa]), ALL(Muuttujat[Syntymämaa (maanosa)]), ALL(Muuttujat[Syntymämaa (suomi/muu)]))\n                return IF(kaikki = \"1-4\", \"25 % – 100 %\",\n                                IF(lkm = \"1-4\", IF(kaikki > 8000, \"0.0 %\", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),\n                                     lkm / kaikki)))",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Samtliga studerande",
            "expression": "IF(SUM([lkm_op2]) = 0, BLANK(), IF(SUM([lkm_op2]) < 5, \"1-4\", MROUND(SUM([lkm_op2]), 3)))",
            "formatString": "#,0"
          },
          {
            "name": "Studerande med ett främmande modersmål",
            "expression": "CALCULATE([Kaikki opiskelijat], FILTER('Muuttujat', [koodi_ai] <> \"fs\" && [koodi_ai] <> \"sv\"))",
            "formatString": "#,0"
          },
          {
            "name": "Utländska studerande",
            "expression": "CALCULATE([Kaikki opiskelijat], FILTER('Muuttujat', [koodi_kan] <> \"1\"))",
            "formatString": "#,0"
          },
          {
            "name": "Studerande som är utrikes födda",
            "expression": "CALCULATE([Kaikki opiskelijat], FILTER('Muuttujat', [koodi_syn] <> \"1\"))",
            "formatString": "#,0"
          },
          {
            "name": "Andel som studerande med ett främmande modersmål av samtliga studerande",
            "expression": "var lkm = [Vieraskieliset opiskelijat]\nreturn IF(lkm = BLANK(), BLANK(),\n\tvar kaikki = CALCULATE([Kaikki opiskelijat], ALL(Muuttujat[Modersmål]), ALL(Muuttujat[Modersmål (finska/andra)]))\n                return IF(kaikki = \"1-4\", \"25 % – 100 %\",\n                                IF(lkm = \"1-4\", IF(kaikki > 8000, \"0.0 %\", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),\n                                     lkm / kaikki)))",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Andel som utländska studerande av samtliga studerande",
            "expression": "var lkm = [Ulkomaalaiset opiskelijat]\nreturn IF(lkm = BLANK(), BLANK(),\n\tvar kaikki = CALCULATE([Kaikki opiskelijat], ALL('Muuttujat'[Medborgarskap (världsdel)]), ALL('Muuttujat'[Medborgarskap (land)]), ALL('Muuttujat'[Medborgarskap (finska/andra)]))\n                return IF(kaikki = \"1-4\", \"25 % – 100 %\",\n                                IF(lkm = \"1-4\", IF(kaikki > 8000, \"0.0 %\", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),\n                                     lkm / kaikki)))",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Andel som studerande som är utrikes födda av samtliga studerande",
            "expression": "var lkm = [Ulkomailla syntyneet opiskelijat]\nreturn IF(lkm = BLANK(), BLANK(),\n\tvar kaikki = CALCULATE([Kaikki opiskelijat], ALL(Muuttujat[Födelseland]), ALL(Muuttujat[Födelseland (världsdel)]), ALL(Muuttujat[Födelseland (Finland/andra)]))\n                return IF(kaikki = \"1-4\", \"25 % – 100 %\",\n                                IF(lkm = \"1-4\", IF(kaikki > 8000, \"0.0 %\", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),\n                                     lkm / kaikki)))",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Samtliga närvarande studerande",
            "expression": "IF(SUM([lkm_opiskolo2]) = 0, BLANK(), IF(SUM([lkm_opiskolo2]) < 5, \"1-4\", MROUND(SUM([lkm_opiskolo2]), 3)))",
            "formatString": "#,0"
          },
          {
            "name": "Samtliga nya studerande",
            "expression": "IF([lkm_aloit3] = 0, BLANK(), IF([lkm_aloit3] < 5, \"1-4\", MROUND([lkm_aloit3], 3)))",
            "formatString": "#,0"
          },
          {
            "name": "Utländska nybörjare",
            "expression": "CALCULATE([Kaikki aloittaneet], FILTER('Muuttujat', [koodi_kan] <> \"1\"))",
            "formatString": "#,0"
          },
          {
            "name": "Nybörjare med ett främmande modersmål",
            "expression": "CALCULATE([Kaikki aloittaneet], FILTER('Muuttujat', [koodi_ai] <> \"fs\" && [koodi_ai] <> \"sv\"))",
            "formatString": "#,0"
          },
          {
            "name": "Nybörjare som är utrikes födda",
            "expression": "CALCULATE([Kaikki aloittaneet], FILTER('Muuttujat', [koodi_syn] <> \"1\"))",
            "formatString": "#,0"
          },
          {
            "name": "Nya studerande med ett främmande modersmål",
            "expression": "CALCULATE([Kaikki uudet opiskelijat], FILTER('Muuttujat', [koodi_ai] <> \"fs\" && [koodi_ai] <> \"sv\"))",
            "formatString": "#,0"
          },
          {
            "name": "Utländska nya studerande",
            "expression": "CALCULATE([Kaikki uudet opiskelijat], FILTER('Muuttujat', [koodi_kan] <> \"1\"))",
            "formatString": "#,0"
          },
          {
            "name": "Samtliga nybörjare",
            "expression": "IF([lkm_aloit3] = 0, BLANK(), IF([lkm_aloit3] < 5, \"1-4\", MROUND([lkm_aloit3], 3)))",
            "formatString": "#,0"
          },
          {
            "name": "Nya studerande som är utrikes födda",
            "expression": "CALCULATE([Kaikki uudet opiskelijat], FILTER('Muuttujat', [koodi_syn] <> \"1\"))",
            "formatString": "#,0"
          },
          {
            "name": "Närvarande studerande med ett främmande modersmål",
            "expression": "CALCULATE([Kaikki läsnäolevaksi kirjautuneet opiskelijat], FILTER('Muuttujat', [koodi_ai] <> \"fs\" && [koodi_ai] <> \"sv\"))",
            "formatString": "#,0"
          },
          {
            "name": "Närvarande utländska studerande",
            "expression": "CALCULATE([Kaikki läsnäolevaksi kirjautuneet opiskelijat], FILTER('Muuttujat', [koodi_kan] <> \"1\"))",
            "formatString": "#,0"
          },
          {
            "name": "Närvarande studerande som är utrikes födda",
            "expression": "CALCULATE([Kaikki läsnäolevaksi kirjautuneet opiskelijat], FILTER('Muuttujat', [koodi_syn] <> \"1\"))",
            "formatString": "#,0"
          },
          {
            "name": "Andel som nybörjare med ett främmande modersmål av samtliga nybörjare",
            "expression": "var lkm = [Vieraskieliset aloittaneet]\nreturn IF(lkm = BLANK(), BLANK(),\n\tvar kaikki = CALCULATE([Kaikki aloittaneet], ALL(Muuttujat[Modersmål]), ALL(Muuttujat[Modersmål (finska/andra)]))\n                return IF(kaikki = \"1-4\", \"25 % – 100 %\",\n                                IF(lkm = \"1-4\", IF(kaikki > 8000, \"0.0 %\", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),\n                                     lkm / kaikki)))",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Andel som utländska nybörjare av samtliga nybörjare",
            "expression": "var lkm = [Ulkomaalaiset aloittaneet]\nreturn IF(lkm = BLANK(), BLANK(),\n\tvar kaikki = CALCULATE([Kaikki aloittaneet], ALL('Muuttujat'[Medborgarskap (världsdel)]), ALL('Muuttujat'[Medborgarskap (land)]), ALL('Muuttujat'[Medborgarskap (finska/andra)]))\n                return IF(kaikki = \"1-4\", \"25 % – 100 %\",\n                                IF(lkm = \"1-4\", IF(kaikki > 8000, \"0.0 %\", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),\n                                     lkm / kaikki)))",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Andel som nybörjare som är utrikes födda av samtliga nybörjare",
            "expression": "var lkm = [Ulkomailla syntyneet aloittaneet]\nreturn IF(lkm = BLANK(), BLANK(),\n\tvar kaikki = CALCULATE([Kaikki aloittaneet], ALL(Muuttujat[Födelseland]), ALL(Muuttujat[Födelseland (världsdel)]), ALL(Muuttujat[Födelseland (Finland/andra)]))\n                return IF(kaikki = \"1-4\", \"25 % – 100 %\",\n                                IF(lkm = \"1-4\", IF(kaikki > 8000, \"0.0 %\", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),\n                                     lkm / kaikki)))",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Andel som nya studerande med ett främmande modersmål av samtliga nya studerande",
            "expression": "var lkm = [Vieraskieliset uudet opiskelijat]\nreturn IF(lkm = BLANK(), BLANK(),\n\tvar kaikki = CALCULATE([Kaikki uudet opiskelijat], ALL(Muuttujat[Modersmål]), ALL(Muuttujat[Modersmål (finska/andra)]))\n                return IF(kaikki = \"1-4\", \"25 % – 100 %\",\n                                IF(lkm = \"1-4\", IF(kaikki > 8000, \"0.0 %\", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),\n                                     lkm / kaikki)))",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Andel som utländska nya studerande av samtliga nya studerande",
            "expression": "var lkm = [Ulkomaalaiset uudet opiskelijat]\nreturn IF(lkm = BLANK(), BLANK(),\n\tvar kaikki = CALCULATE([Kaikki uudet opiskelijat], ALL('Muuttujat'[Medborgarskap (världsdel)]), ALL('Muuttujat'[Medborgarskap (land)]), ALL('Muuttujat'[Medborgarskap (finska/andra)]))\n                return IF(kaikki = \"1-4\", \"25 % – 100 %\",\n                                IF(lkm = \"1-4\", IF(kaikki > 8000, \"0.0 %\", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),\n                                     lkm / kaikki)))",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Andel som nya studerande som är utrikes födda av samtliga nya studerande",
            "expression": "var lkm = [Ulkomailla syntyneet uudet opiskelijat]\nreturn IF(lkm = BLANK(), BLANK(),\n\tvar kaikki = CALCULATE([Kaikki uudet opiskelijat], ALL(Muuttujat[Födelseland]), ALL(Muuttujat[Födelseland (världsdel)]), ALL(Muuttujat[Födelseland (Finland/andra)]))\n                return IF(kaikki = \"1-4\", \"25 % – 100 %\",\n                                IF(lkm = \"1-4\", IF(kaikki > 8000, \"0.0 %\", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),\n                                     lkm / kaikki)))",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Andel som närvarande studerande med ett främmande modersmål av samtliga närvarande",
            "expression": "var lkm = [Läsnäolevaksi kirjautuneet vieraskieliset opiskelijat]\nreturn IF(lkm = BLANK(), BLANK(),\n\tvar kaikki = CALCULATE([Kaikki läsnäolevaksi kirjautuneet opiskelijat], ALL(Muuttujat[Modersmål]), ALL(Muuttujat[Modersmål (finska/andra)]))\n                return IF(kaikki = \"1-4\", \"25 % – 100 %\",\n                                IF(lkm = \"1-4\", IF(kaikki > 8000, \"0.0 %\", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),\n                                     lkm / kaikki)))",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Andel som närvarande utländska studerande av samtliga närvarande",
            "expression": "var lkm = [Läsnäolevaksi kirjautuneet ulkomaalaiset opiskelijat]\nreturn IF(lkm = BLANK(), BLANK(),\n\tvar kaikki = CALCULATE([Kaikki läsnäolevaksi kirjautuneet opiskelijat], ALL('Muuttujat'[Medborgarskap (världsdel)]), ALL('Muuttujat'[Medborgarskap (land)]), ALL('Muuttujat'[Medborgarskap (finska/andra)]))\n                return IF(kaikki = \"1-4\", \"25 % – 100 %\",\n                                IF(lkm = \"1-4\", IF(kaikki > 8000, \"0.0 %\", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),\n                                     lkm / kaikki)))",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Andel som närvarande studerande som är utrikes födda av samtliga närvarande",
            "expression": "var lkm = [Läsnäolevaksi kirjautuneet ulkomailla syntyneet opiskelijat]\nreturn IF(lkm = BLANK(), BLANK(),\n\tvar kaikki = CALCULATE([Kaikki läsnäolevaksi kirjautuneet opiskelijat], ALL(Muuttujat[Födelseland]), ALL(Muuttujat[Födelseland (världsdel)]), ALL(Muuttujat[Födelseland (Finland/andra)]))\n                return IF(kaikki = \"1-4\", \"25 % – 100 %\",\n                                IF(lkm = \"1-4\", IF(kaikki > 8000, \"0.0 %\", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),\n                                     lkm / kaikki)))",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "All students",
            "expression": "IF(SUM([lkm_op2]) = 0, BLANK(), IF(SUM([lkm_op2]) < 5, \"1-4\", MROUND(SUM([lkm_op2]), 3)))",
            "formatString": "#,0"
          },
          {
            "name": "Foreign-language students",
            "expression": "CALCULATE([Kaikki opiskelijat], FILTER('Muuttujat', [koodi_ai] <> \"fs\" && [koodi_ai] <> \"sv\"))",
            "formatString": "#,0"
          },
          {
            "name": "Foreign students",
            "expression": "CALCULATE([Kaikki opiskelijat], FILTER('Muuttujat', [koodi_kan] <> \"1\"))",
            "formatString": "#,0"
          },
          {
            "name": "Students born abroad",
            "expression": "CALCULATE([Kaikki opiskelijat], FILTER('Muuttujat', [koodi_syn] <> \"1\"))",
            "formatString": "#,0"
          },
          {
            "name": "All new students",
            "expression": "IF([lkm_aloit3] = 0, BLANK(), IF([lkm_aloit3] < 5, \"1-4\", MROUND([lkm_aloit3], 3)))",
            "formatString": "#,0"
          },
          {
            "name": "Foreign admitted",
            "expression": "CALCULATE([Kaikki aloittaneet], FILTER('Muuttujat', [koodi_kan] <> \"1\"))",
            "formatString": "#,0"
          },
          {
            "name": "Foreign-language admitted",
            "expression": "CALCULATE([Kaikki aloittaneet], FILTER('Muuttujat', [koodi_ai] <> \"fs\" && [koodi_ai] <> \"sv\"))",
            "formatString": "#,0"
          },
          {
            "name": "Admitted born abroad",
            "expression": "CALCULATE([Kaikki aloittaneet], FILTER('Muuttujat', [koodi_syn] <> \"1\"))",
            "formatString": "#,0"
          },
          {
            "name": "New foreign-language students",
            "expression": "CALCULATE([Kaikki uudet opiskelijat], FILTER('Muuttujat', [koodi_ai] <> \"fs\" && [koodi_ai] <> \"sv\"))",
            "formatString": "#,0"
          },
          {
            "name": "New foreign students",
            "expression": "CALCULATE([Kaikki uudet opiskelijat], FILTER('Muuttujat', [koodi_kan] <> \"1\"))",
            "formatString": "#,0"
          },
          {
            "name": "Percentage of foreign-language students (of all students)",
            "expression": "var lkm = [Vieraskieliset opiskelijat]\nreturn IF(lkm = BLANK(), BLANK(),\n\tvar kaikki = CALCULATE([Kaikki opiskelijat], ALL(Muuttujat[Mother tongue]), ALL(Muuttujat[Mother tongue (Finnish/Other)]))\n                return IF(kaikki = \"1-4\", \"25 % – 100 %\",\n                                IF(lkm = \"1-4\", IF(kaikki > 8000, \"0.0 %\", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),\n                                     lkm / kaikki)))",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Percentage of foreign students (of all students)",
            "expression": "var lkm = [Ulkomaalaiset opiskelijat]\nreturn IF(lkm = BLANK(), BLANK(),\n\tvar kaikki = CALCULATE([Kaikki opiskelijat], ALL('Muuttujat'[Nationality (continent)]), ALL('Muuttujat'[Nationality (country)]), ALL('Muuttujat'[Nationality (Finn/Other)]))\n                return IF(kaikki = \"1-4\", \"25 % – 100 %\",\n                                IF(lkm = \"1-4\", IF(kaikki > 8000, \"0.0 %\", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),\n                                     lkm / kaikki)))",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Percentage of students born abroad (of all students)",
            "expression": "var lkm = [Ulkomailla syntyneet opiskelijat]\nreturn IF(lkm = BLANK(), BLANK(),\n\tvar kaikki = CALCULATE([Kaikki opiskelijat], ALL(Muuttujat[Country of birth]), ALL(Muuttujat[Country of birth (continent)]), ALL(Muuttujat[Country of birth (Finland/Other)]))\n                return IF(kaikki = \"1-4\", \"25 % – 100 %\",\n                                IF(lkm = \"1-4\", IF(kaikki > 8000, \"0.0 %\", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),\n                                     lkm / kaikki)))",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "All students enrolled as present",
            "expression": "IF(SUM([lkm_opiskolo2]) = 0, BLANK(), IF(SUM([lkm_opiskolo2]) < 5, \"1-4\", MROUND(SUM([lkm_opiskolo2]), 3)))",
            "formatString": "#,0"
          },
          {
            "name": "All admitted",
            "expression": "IF([lkm_aloit3] = 0, BLANK(), IF([lkm_aloit3] < 5, \"1-4\", MROUND([lkm_aloit3], 3)))",
            "formatString": "#,0"
          },
          {
            "name": "New students born abroad",
            "expression": "CALCULATE([Kaikki uudet opiskelijat], FILTER('Muuttujat', [koodi_syn] <> \"1\"))",
            "formatString": "#,0"
          },
          {
            "name": "Foreign-language students enrolled as present",
            "expression": "CALCULATE([Kaikki läsnäolevaksi kirjautuneet opiskelijat], FILTER('Muuttujat', [koodi_ai] <> \"fs\" && [koodi_ai] <> \"sv\"))",
            "formatString": "#,0"
          },
          {
            "name": "Foreign students enrolled as present",
            "expression": "CALCULATE([Kaikki läsnäolevaksi kirjautuneet opiskelijat], FILTER('Muuttujat', [koodi_kan] <> \"1\"))",
            "formatString": "#,0"
          },
          {
            "name": "Students born abroad enrolled as present",
            "expression": "CALCULATE([Kaikki läsnäolevaksi kirjautuneet opiskelijat], FILTER('Muuttujat', [koodi_syn] <> \"1\"))",
            "formatString": "#,0"
          },
          {
            "name": "Percentage of foreign-language admitted (of all admitted)",
            "expression": "var lkm = [Vieraskieliset aloittaneet]\nreturn IF(lkm = BLANK(), BLANK(),\n\tvar kaikki = CALCULATE([Kaikki aloittaneet], ALL(Muuttujat[Mother tongue]), ALL(Muuttujat[Mother tongue (Finnish/Other)]))\n                return IF(kaikki = \"1-4\", \"25 % – 100 %\",\n                                IF(lkm = \"1-4\", IF(kaikki > 8000, \"0.0 %\", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),\n                                     lkm / kaikki)))",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Percentage of foreign admitted (of all admitted)",
            "expression": "var lkm = [Ulkomaalaiset aloittaneet]\nreturn IF(lkm = BLANK(), BLANK(),\n\tvar kaikki = CALCULATE([Kaikki aloittaneet], ALL('Muuttujat'[Nationality (continent)]), ALL('Muuttujat'[Nationality (country)]), ALL('Muuttujat'[Nationality (Finn/Other)]))\n                return IF(kaikki = \"1-4\", \"25 % – 100 %\",\n                                IF(lkm = \"1-4\", IF(kaikki > 8000, \"0.0 %\", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),\n                                     lkm / kaikki)))",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Percentage of admitted born abroad (of all admitted)",
            "expression": "var lkm = [Ulkomailla syntyneet aloittaneet]\nreturn IF(lkm = BLANK(), BLANK(),\n\tvar kaikki = CALCULATE([Kaikki aloittaneet], ALL(Muuttujat[Country of birth]), ALL(Muuttujat[Country of birth (continent)]), ALL(Muuttujat[Country of birth (Finland/Other)]))\n                return IF(kaikki = \"1-4\", \"25 % – 100 %\",\n                                IF(lkm = \"1-4\", IF(kaikki > 8000, \"0.0 %\", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),\n                                     lkm / kaikki)))",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Percentage of new foreign-language students (of all new students)",
            "expression": "var lkm = [Vieraskieliset uudet opiskelijat]\nreturn IF(lkm = BLANK(), BLANK(),\n\tvar kaikki = CALCULATE([Kaikki uudet opiskelijat], ALL(Muuttujat[Mother tongue]), ALL(Muuttujat[Mother tongue (Finnish/Other)]))\n                return IF(kaikki = \"1-4\", \"25 % – 100 %\",\n                                IF(lkm = \"1-4\", IF(kaikki > 8000, \"0.0 %\", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),\n                                     lkm / kaikki)))",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Percentage of new foreign students (of all new students)",
            "expression": "var lkm = [Ulkomaalaiset uudet opiskelijat]\nreturn IF(lkm = BLANK(), BLANK(),\n\tvar kaikki = CALCULATE([Kaikki uudet opiskelijat], ALL('Muuttujat'[Nationality (continent)]), ALL('Muuttujat'[Nationality (country)]), ALL('Muuttujat'[Nationality (Finn/Other)]))\n                return IF(kaikki = \"1-4\", \"25 % – 100 %\",\n                                IF(lkm = \"1-4\", IF(kaikki > 8000, \"0.0 %\", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),\n                                     lkm / kaikki)))",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Percentage of new students born abroad (of all new students)",
            "expression": "var lkm = [Ulkomailla syntyneet uudet opiskelijat]\nreturn IF(lkm = BLANK(), BLANK(),\n\tvar kaikki = CALCULATE([Kaikki uudet opiskelijat], ALL(Muuttujat[Country of birth]), ALL(Muuttujat[Country of birth (continent)]), ALL(Muuttujat[Country of birth (Finland/Other)]))\n                return IF(kaikki = \"1-4\", \"25 % – 100 %\",\n                                IF(lkm = \"1-4\", IF(kaikki > 8000, \"0.0 %\", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),\n                                     lkm / kaikki)))",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Percentage of foreign-language students enrolled as present (of all present students)",
            "expression": "var lkm = [Läsnäolevaksi kirjautuneet vieraskieliset opiskelijat]\nreturn IF(lkm = BLANK(), BLANK(),\n\tvar kaikki = CALCULATE([Kaikki läsnäolevaksi kirjautuneet opiskelijat], ALL(Muuttujat[Mother tongue]), ALL(Muuttujat[Mother tongue (Finnish/Other)]))\n                return IF(kaikki = \"1-4\", \"25 % – 100 %\",\n                                IF(lkm = \"1-4\", IF(kaikki > 8000, \"0.0 %\", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),\n                                     lkm / kaikki)))",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Percentage of foreign students enrolled as present (of all present students)",
            "expression": "var lkm = [Läsnäolevaksi kirjautuneet ulkomaalaiset opiskelijat]\nreturn IF(lkm = BLANK(), BLANK(),\n\tvar kaikki = CALCULATE([Kaikki läsnäolevaksi kirjautuneet opiskelijat], ALL('Muuttujat'[Nationality (continent)]), ALL('Muuttujat'[Nationality (country)]), ALL('Muuttujat'[Nationality (Finn/Other)]))\n                return IF(kaikki = \"1-4\", \"25 % – 100 %\",\n                                IF(lkm = \"1-4\", IF(kaikki > 8000, \"0.0 %\", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),\n                                     lkm / kaikki)))",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Percentage of students born abroad enrolled as present (of all present students)",
            "expression": "var lkm = [Läsnäolevaksi kirjautuneet ulkomailla syntyneet opiskelijat]\nreturn IF(lkm = BLANK(), BLANK(),\n\tvar kaikki = CALCULATE([Kaikki läsnäolevaksi kirjautuneet opiskelijat], ALL(Muuttujat[Country of birth]), ALL(Muuttujat[Country of birth (continent)]), ALL(Muuttujat[Country of birth (Finland/Other)]))\n                return IF(kaikki = \"1-4\", \"25 % – 100 %\",\n                                IF(lkm = \"1-4\", IF(kaikki > 8000, \"0.0 %\", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),\n                                     lkm / kaikki)))",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Kaikki opiskelijat_s",
            "expression": "IF([kytkin] = 0, BLANK(), IF(SUM([lkm_op2]) = 0, BLANK(),SUM([lkm_op2])))",
            "formatString": "#,0"
          },
          {
            "name": "Vieraskieliset opiskelijat_s",
            "expression": "IF([kytkin] = 0, BLANK(), CALCULATE([Kaikki opiskelijat_s], FILTER('Muuttujat', [koodi_ai] <> \"fs\" && [koodi_ai] <> \"sv\")))",
            "formatString": "#,0"
          },
          {
            "name": "Ulkomaalaiset opiskelijat_s",
            "expression": "IF([kytkin] = 0, BLANK(), CALCULATE([Kaikki opiskelijat_s], FILTER('Muuttujat', [koodi_kan] <> \"1\")))",
            "formatString": "#,0"
          },
          {
            "name": "Ulkomailla syntyneet opiskelijat_s",
            "expression": "IF([kytkin] = 0, BLANK(), CALCULATE([Kaikki opiskelijat_s], FILTER('Muuttujat', [koodi_syn] <> \"1\")))",
            "formatString": "#,0"
          },
          {
            "name": "Vieraskielisten opiskelijoiden osuus kaikista opiskelijoista_s",
            "expression": "IF([kytkin] = 0, BLANK(), [Vieraskieliset opiskelijat_s]/CALCULATE([Kaikki opiskelijat_s], ALL(Muuttujat[Äidinkieli]), ALL(Muuttujat[Äidinkieli (suomi/muu)])))",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Ulkomaalaisten opiskelijoiden osuus kaikista opiskelijoista_s",
            "expression": "IF([kytkin] = 0, BLANK(), [Ulkomaalaiset opiskelijat_s]/CALCULATE([Kaikki opiskelijat_s], ALL('Muuttujat'[Kansalaisuus (maanosa)]), ALL('Muuttujat'[Kansalaisuus (maa)]), ALL('Muuttujat'[Kansalaisuus (suomi/muu)])))",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Ulkomailla syntyneiden opiskelijoiden osuus kaikista opiskelijoista_s",
            "expression": "IF([kytkin] = 0, BLANK(), [Ulkomailla syntyneet opiskelijat_s]/CALCULATE([Kaikki opiskelijat_s], ALL(Muuttujat[Syntymämaa]), ALL(Muuttujat[Syntymämaa (maanosa)]), ALL(Muuttujat[Syntymämaa (suomi/muu)])))",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Kaikki aloittaneet_s",
            "expression": "IF([kytkin] = 0, BLANK(), IF([lkm_aloit3] = 0, BLANK(),[lkm_aloit3]))",
            "formatString": "#,0"
          },
          {
            "name": "Kaikki läsnäolevaksi kirjautuneet opiskelijat_s",
            "expression": "IF([kytkin] = 0, BLANK(), IF(SUM([lkm_opiskolo2]) = 0, BLANK(),SUM([lkm_opiskolo2])))",
            "formatString": "#,0"
          },
          {
            "name": "Kaikki uudet opiskelijat_s",
            "expression": "IF([kytkin] = 0, BLANK(), IF([lkm_aloit3] = 0, BLANK(),[lkm_aloit3]))",
            "formatString": "#,0"
          },
          {
            "name": "Ulkomaalaiset aloittaneet_s",
            "expression": "IF([kytkin] = 0, BLANK(), CALCULATE([Kaikki aloittaneet_s], FILTER('Muuttujat', [koodi_kan] <> \"1\")))",
            "formatString": "#,0"
          },
          {
            "name": "Vieraskieliset aloittaneet_s",
            "expression": "IF([kytkin] = 0, BLANK(), CALCULATE([Kaikki aloittaneet_s], FILTER('Muuttujat', [koodi_ai] <> \"fs\" && [koodi_ai] <> \"sv\")))",
            "formatString": "#,0"
          },
          {
            "name": "Ulkomailla syntyneet aloittaneet_s",
            "expression": "IF([kytkin] = 0, BLANK(), CALCULATE([Kaikki aloittaneet_s], FILTER('Muuttujat', [koodi_syn] <> \"1\")))",
            "formatString": "#,0"
          },
          {
            "name": "Vieraskieliset uudet opiskelijat_s",
            "expression": "IF([kytkin] = 0, BLANK(), CALCULATE([Kaikki uudet opiskelijat_s], FILTER('Muuttujat', [koodi_ai] <> \"fs\" && [koodi_ai] <> \"sv\")))",
            "formatString": "#,0"
          },
          {
            "name": "Ulkomaalaiset uudet opiskelijat_s",
            "expression": "IF([kytkin] = 0, BLANK(), CALCULATE([Kaikki uudet opiskelijat_s], FILTER('Muuttujat', [koodi_kan] <> \"1\")))",
            "formatString": "#,0"
          },
          {
            "name": "Ulkomailla syntyneet uudet opiskelijat_s",
            "expression": "IF([kytkin] = 0, BLANK(), CALCULATE([Kaikki uudet opiskelijat_s], FILTER('Muuttujat', [koodi_syn] <> \"1\")))",
            "formatString": "#,0"
          },
          {
            "name": "Läsnäolevaksi kirjautuneet vieraskieliset opiskelijat_s",
            "expression": "IF([kytkin] = 0, BLANK(), CALCULATE([Kaikki läsnäolevaksi kirjautuneet opiskelijat_s], FILTER('Muuttujat', [koodi_ai] <> \"fs\" && [koodi_ai] <> \"sv\")))",
            "formatString": "#,0"
          },
          {
            "name": "Vieraskielisten aloittaneiden osuus kaikista aloittaneista_s",
            "expression": "IF([kytkin] = 0, BLANK(), [Vieraskieliset aloittaneet_s]/CALCULATE([Kaikki aloittaneet_s], ALL(Muuttujat[Äidinkieli]), ALL(Muuttujat[Äidinkieli (suomi/muu)])))",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Ulkomaalaisten aloittaneiden osuus kaikista aloittaneista_s",
            "expression": "IF([kytkin] = 0, BLANK(), [Ulkomaalaiset aloittaneet_s]/CALCULATE([Kaikki aloittaneet_s], ALL('Muuttujat'[Kansalaisuus (maanosa)]), ALL('Muuttujat'[Kansalaisuus (maa)]), ALL('Muuttujat'[Kansalaisuus (suomi/muu)])))",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Ulkomailla syntyneiden aloittaneiden osuus kaikista aloittaneista_s",
            "expression": "IF([kytkin] = 0, BLANK(), [Ulkomailla syntyneet aloittaneet_s]/CALCULATE([Kaikki aloittaneet_s], ALL(Muuttujat[Syntymämaa]), ALL(Muuttujat[Syntymämaa (maanosa)]), ALL(Muuttujat[Syntymämaa (suomi/muu)])))",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Vieraskielisten uusien opiskelijoiden osuus kaikista uusista opiskelijoista_s",
            "expression": "IF([kytkin] = 0, BLANK(), [Vieraskieliset uudet opiskelijat_s]/CALCULATE([Kaikki uudet opiskelijat_s], ALL(Muuttujat[Äidinkieli]), ALL(Muuttujat[Äidinkieli (suomi/muu)])))",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Ulkomaalaisten uusien opiskelijoiden osuus kaikista uusista opiskelijoista_s",
            "expression": "IF([kytkin] = 0, BLANK(), [Ulkomaalaiset uudet opiskelijat_s]/CALCULATE([Kaikki uudet opiskelijat_s], ALL('Muuttujat'[Kansalaisuus (maanosa)]), ALL('Muuttujat'[Kansalaisuus (maa)]), ALL('Muuttujat'[Kansalaisuus (suomi/muu)])))",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Ulkomailla syntyneiden uusien opiskelijoiden osuus kaikista uusista opiskelijoista_s",
            "expression": "IF([kytkin] = 0, BLANK(), [Ulkomailla syntyneet uudet opiskelijat_s]/CALCULATE([Kaikki uudet opiskelijat_s], ALL(Muuttujat[Syntymämaa]), ALL(Muuttujat[Syntymämaa (maanosa)]), ALL(Muuttujat[Syntymämaa (suomi/muu)])))",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Läsnäolevaksi kirj. vieraskielisten opiskelijoiden osuus kaikista läsnäolevista_s",
            "expression": "IF([kytkin] = 0, BLANK(), [Läsnäolevaksi kirjautuneet vieraskieliset opiskelijat_s]/CALCULATE([Kaikki läsnäolevaksi kirjautuneet opiskelijat_s], ALL(Muuttujat[Äidinkieli]), ALL(Muuttujat[Äidinkieli (suomi/muu)])))",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Läsnäolevaksi kirj. ulkomaalaisten opiskelijoiden osuus kaik. läsnäolevista_s",
            "expression": "IF([kytkin] = 0, BLANK(), [Läsnäolevaksi kirjautuneet ulkomaalaiset opiskelijat_s]/CALCULATE([Kaikki läsnäolevaksi kirjautuneet opiskelijat_s], ALL('Muuttujat'[Kansalaisuus (maanosa)]), ALL('Muuttujat'[Kansalaisuus (maa)]), ALL('Muuttujat'[Kansalaisuus (suomi/muu)])))",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Läsnäolevaksi kirj. ulkomailla syntyneiden opiskelijoiden osuus kaikista läsnäolevista_s",
            "expression": "IF([kytkin] = 0, BLANK(), [Läsnäolevaksi kirjautuneet ulkomailla syntyneet opiskelijat_s]/CALCULATE([Kaikki läsnäolevaksi kirjautuneet opiskelijat_s], ALL(Muuttujat[Syntymämaa]), ALL(Muuttujat[Syntymämaa (maanosa)]), ALL(Muuttujat[Syntymämaa (suomi/muu)])))",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Läsnäolevaksi kirjautuneet ulkomaalaiset opiskelijat_s",
            "expression": "IF([kytkin] = 0, BLANK(), CALCULATE([Kaikki läsnäolevaksi kirjautuneet opiskelijat_s], FILTER('Muuttujat', [koodi_kan] <> \"1\")))",
            "formatString": "#,0"
          },
          {
            "name": "Läsnäolevaksi kirjautuneet ulkomailla syntyneet opiskelijat_s",
            "expression": "IF([kytkin] = 0, BLANK(), CALCULATE([Kaikki läsnäolevaksi kirjautuneet opiskelijat_s], FILTER('Muuttujat', [koodi_syn] <> \"1\")))",
            "formatString": "#,0"
          },
          {
            "name": "kytkin",
            "expression": "IF(LEFT(USERNAME(), 4) = \"DWI\\\", 1, 0)",
            "formatString": "0",
            "isHidden": true
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "v_f_tab_ulkomaalaiset_maan_kansalaisuuden_aidinkielen_mukaan_yo"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[v_f_tab_ulkomaalaiset_maan_kansalaisuuden_aidinkielen_mukaan_yo].* FROM [dbo].[v_f_tab_ulkomaalaiset_maan_kansalaisuuden_aidinkielen_mukaan_yo] "
          }
        ]
      }
    ],
    "cultures": [
      {
        "name": "en-US",
        "translations": {
          "model": {
            "name": "Model",
            "tables": [
              {
                "name": "Muuttujat",
                "translatedCaption": "Variables",
                "columns": [
                  {
                    "name": "Koodit Koulutusnimike",
                    "translatedCaption": "Codes Name of education",
                    "translatedDisplayFolder": "Code variables"
                  },
                  {
                    "name": "Koodit Opintoala",
                    "translatedCaption": "Codes Subfield of education",
                    "translatedDisplayFolder": "Code variables"
                  },
                  {
                    "name": "Koodit Koulutusala",
                    "translatedCaption": "Codes Field of education",
                    "translatedDisplayFolder": "Code variables"
                  },
                  {
                    "name": "Koodit Koulutusala (1995) luokitus",
                    "translatedCaption": "Codes Field of education (1995)",
                    "translatedDisplayFolder": "Code variables"
                  },
                  {
                    "name": "Koodit Koulutusala (2002) luokitus",
                    "translatedCaption": "Codes Field of education (2002)",
                    "translatedDisplayFolder": "Code variables"
                  },
                  {
                    "name": "Koodit Koulutuksen maakunta",
                    "translatedCaption": "Codes Region of education",
                    "translatedDisplayFolder": "Code variables"
                  }
                ]
              }
            ]
          }
        }
      },
      {
        "name": "sv-SE",
        "translations": {
          "model": {
            "name": "Model",
            "tables": [
              {
                "name": "Muuttujat",
                "translatedCaption": "Variabler",
                "columns": [
                  {
                    "name": "Koodit Koulutusnimike",
                    "translatedCaption": "Kod Utbilningsbenämning",
                    "translatedDisplayFolder": "Kodvariabler"
                  },
                  {
                    "name": "Koodit Opintoala",
                    "translatedCaption": "Kod Studieområde",
                    "translatedDisplayFolder": "Kodvariabler"
                  },
                  {
                    "name": "Koodit Koulutusala",
                    "translatedCaption": "Kod Utbilningsområde",
                    "translatedDisplayFolder": "Kodvariabler"
                  },
                  {
                    "name": "Koodit Koulutusala (1995) luokitus",
                    "translatedCaption": "Kod Utbilningsområde (1995)",
                    "translatedDisplayFolder": "Kodvariabler"
                  },
                  {
                    "name": "Koodit Koulutusala (2002) luokitus",
                    "translatedCaption": "Kod Utbilningsområde (2002)",
                    "translatedDisplayFolder": "Kodvariabler"
                  },
                  {
                    "name": "Koodit Koulutuksen maakunta",
                    "translatedCaption": "Kod Utbildningens landskap",
                    "translatedDisplayFolder": "Kodvariabler"
                  }
                ]
              }
            ]
          }
        }
      }
    ],
    "perspectives": [
      {
        "name": "Kansalaisuus",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Kirjoillaolo (syys)"
              },
              {
                "name": "Hallinnonala"
              },
              {
                "name": "Koulutusnimike"
              },
              {
                "name": "Aloituslukuvuosi"
              },
              {
                "name": "Koulutusala"
              },
              {
                "name": "Koulutuslaji"
              },
              {
                "name": "ETA-maan kansalainen"
              },
              {
                "name": "Koulutuksen maakunta"
              },
              {
                "name": "Sukupuoli"
              },
              {
                "name": "Näkökulma"
              },
              {
                "name": "EU-maan kansalainen"
              },
              {
                "name": "Kansalaisuus (maa)"
              },
              {
                "name": "Kansalaisuus (maanosa)"
              },
              {
                "name": "Koulutusaste"
              },
              {
                "name": "Opintoala"
              },
              {
                "name": "Aloituslukukausi"
              },
              {
                "name": "Koulutussektori"
              },
              {
                "name": "Kansalaisuus (suomi/muu)"
              },
              {
                "name": "Tilastovuosi"
              }
            ],
            "measures": [
              {
                "name": "Kaikki opiskelijat"
              },
              {
                "name": "Ulkomaalaisten opiskelijoiden osuus kaikista opiskelijoista"
              },
              {
                "name": "Ulkomaalaiset opiskelijat"
              },
              {
                "name": "Kaikki uudet opiskelijat"
              },
              {
                "name": "Ulkomaalaiset uudet opiskelijat"
              },
              {
                "name": "Ulkomaalaisten uusien opiskelijoiden osuus kaikista uusista opiskelijoista"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Syntymämaa",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Syntymämaa (suomi/muu)"
              },
              {
                "name": "Kirjoillaolo (syys)"
              },
              {
                "name": "Hallinnonala"
              },
              {
                "name": "Koulutusnimike"
              },
              {
                "name": "Syntymämaa"
              },
              {
                "name": "Syntymämaa (maanosa)"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Aloituslukuvuosi"
              },
              {
                "name": "Koulutusala"
              },
              {
                "name": "Koulutuslaji"
              },
              {
                "name": "Koulutuksen maakunta"
              },
              {
                "name": "Sukupuoli"
              },
              {
                "name": "Näkökulma"
              },
              {
                "name": "Koulutussektori"
              },
              {
                "name": "Koulutusaste"
              },
              {
                "name": "Opintoala"
              },
              {
                "name": "Aloituslukukausi"
              }
            ],
            "measures": [
              {
                "name": "Ulkomailla syntyneiden opiskelijoiden osuus kaikista opiskelijoista"
              },
              {
                "name": "Kaikki opiskelijat"
              },
              {
                "name": "Ulkomailla syntyneet uudet opiskelijat"
              },
              {
                "name": "Kaikki uudet opiskelijat"
              },
              {
                "name": "Ulkomailla syntyneet opiskelijat"
              },
              {
                "name": "Ulkomailla syntyneiden uusien opiskelijoiden osuus kaikista uusista opiskelijoista"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Äidinkieli",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Äidinkieli (suomi/muu)"
              },
              {
                "name": "Kirjoillaolo (syys)"
              },
              {
                "name": "Hallinnonala"
              },
              {
                "name": "Koulutusnimike"
              },
              {
                "name": "Aloituslukuvuosi"
              },
              {
                "name": "Koulutusala"
              },
              {
                "name": "Koulutuslaji"
              },
              {
                "name": "Koulutuksen maakunta"
              },
              {
                "name": "Sukupuoli"
              },
              {
                "name": "Äidinkieli"
              },
              {
                "name": "Näkökulma"
              },
              {
                "name": "Koulutussektori"
              },
              {
                "name": "Koulutusaste"
              },
              {
                "name": "Opintoala"
              },
              {
                "name": "Aloituslukukausi"
              },
              {
                "name": "Tilastovuosi"
              }
            ],
            "measures": [
              {
                "name": "Kaikki opiskelijat"
              },
              {
                "name": "Vieraskielisten uusien opiskelijoiden osuus kaikista uusista opiskelijoista"
              },
              {
                "name": "Vieraskieliset uudet opiskelijat"
              },
              {
                "name": "Vieraskielisten opiskelijoiden osuus kaikista opiskelijoista"
              },
              {
                "name": "Vieraskieliset opiskelijat"
              },
              {
                "name": "Kaikki uudet opiskelijat"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Kansalaisuus uudet",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Kansalaisuus (suomi/muu)"
              },
              {
                "name": "Koulutusnimike"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Hallinnonala"
              },
              {
                "name": "Koulutusala"
              },
              {
                "name": "Koulutuslaji"
              },
              {
                "name": "Koulutuksen maakunta"
              },
              {
                "name": "Sukupuoli"
              },
              {
                "name": "Näkökulma"
              },
              {
                "name": "Kansalaisuus (maa)"
              },
              {
                "name": "Kansalaisuus (maanosa)"
              },
              {
                "name": "Koulutusaste"
              },
              {
                "name": "Opintoala"
              },
              {
                "name": "Koulutussektori"
              }
            ],
            "measures": [
              {
                "name": "Kaikki uudet opiskelijat"
              },
              {
                "name": "Ulkomaalaiset uudet opiskelijat"
              },
              {
                "name": "Ulkomaalaisten uusien opiskelijoiden osuus kaikista uusista opiskelijoista"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Kansalaisuus opiskelijat",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Kansalaisuus (suomi/muu)"
              },
              {
                "name": "Koulutusnimike"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Hallinnonala"
              },
              {
                "name": "Koulutusala"
              },
              {
                "name": "Koulutuslaji"
              },
              {
                "name": "Koulutuksen maakunta"
              },
              {
                "name": "Sukupuoli"
              },
              {
                "name": "Näkökulma"
              },
              {
                "name": "Kansalaisuus (maa)"
              },
              {
                "name": "Kansalaisuus (maanosa)"
              },
              {
                "name": "Koulutusaste"
              },
              {
                "name": "Opintoala"
              },
              {
                "name": "Koulutussektori"
              }
            ],
            "measures": [
              {
                "name": "Kaikki opiskelijat"
              },
              {
                "name": "Ulkomaalaisten opiskelijoiden osuus kaikista opiskelijoista"
              },
              {
                "name": "Ulkomaalaiset opiskelijat"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Syntymämaa uudet",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Syntymämaa (suomi/muu)"
              },
              {
                "name": "Koulutusaste"
              },
              {
                "name": "Opintoala"
              },
              {
                "name": "Koulutussektori"
              },
              {
                "name": "Koulutusnimike"
              },
              {
                "name": "Syntymämaa"
              },
              {
                "name": "Syntymämaa (maanosa)"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Hallinnonala"
              },
              {
                "name": "Koulutusala"
              },
              {
                "name": "Koulutuslaji"
              },
              {
                "name": "Koulutuksen maakunta"
              },
              {
                "name": "Sukupuoli"
              },
              {
                "name": "Näkökulma"
              }
            ],
            "measures": [
              {
                "name": "Ulkomailla syntyneet uudet opiskelijat"
              },
              {
                "name": "Kaikki uudet opiskelijat"
              },
              {
                "name": "Ulkomailla syntyneiden uusien opiskelijoiden osuus kaikista uusista opiskelijoista"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Syntymämaa opiskelijat",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Syntymämaa (suomi/muu)"
              },
              {
                "name": "Koulutusaste"
              },
              {
                "name": "Opintoala"
              },
              {
                "name": "Koulutussektori"
              },
              {
                "name": "Koulutusnimike"
              },
              {
                "name": "Syntymämaa"
              },
              {
                "name": "Syntymämaa (maanosa)"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Hallinnonala"
              },
              {
                "name": "Koulutusala"
              },
              {
                "name": "Koulutuslaji"
              },
              {
                "name": "Koulutuksen maakunta"
              },
              {
                "name": "Sukupuoli"
              },
              {
                "name": "Näkökulma"
              }
            ],
            "measures": [
              {
                "name": "Ulkomailla syntyneiden opiskelijoiden osuus kaikista opiskelijoista"
              },
              {
                "name": "Kaikki opiskelijat"
              },
              {
                "name": "Ulkomailla syntyneet opiskelijat"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Äidinkieli uudet",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Koulutusaste"
              },
              {
                "name": "Opintoala"
              },
              {
                "name": "Äidinkieli (suomi/muu)"
              },
              {
                "name": "Koulutussektori"
              },
              {
                "name": "Koulutusnimike"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Hallinnonala"
              },
              {
                "name": "Koulutusala"
              },
              {
                "name": "Koulutuslaji"
              },
              {
                "name": "Koulutuksen maakunta"
              },
              {
                "name": "Sukupuoli"
              },
              {
                "name": "Äidinkieli"
              },
              {
                "name": "Näkökulma"
              }
            ],
            "measures": [
              {
                "name": "Vieraskielisten uusien opiskelijoiden osuus kaikista uusista opiskelijoista"
              },
              {
                "name": "Vieraskieliset uudet opiskelijat"
              },
              {
                "name": "Kaikki uudet opiskelijat"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Äidinkieli opiskelijat",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Koulutusaste"
              },
              {
                "name": "Opintoala"
              },
              {
                "name": "Äidinkieli (suomi/muu)"
              },
              {
                "name": "Koulutussektori"
              },
              {
                "name": "Koulutusnimike"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Hallinnonala"
              },
              {
                "name": "Koulutusala"
              },
              {
                "name": "Koulutuslaji"
              },
              {
                "name": "Koulutuksen maakunta"
              },
              {
                "name": "Sukupuoli"
              },
              {
                "name": "Äidinkieli"
              },
              {
                "name": "Näkökulma"
              }
            ],
            "measures": [
              {
                "name": "Kaikki opiskelijat"
              },
              {
                "name": "Vieraskielisten opiskelijoiden osuus kaikista opiskelijoista"
              },
              {
                "name": "Vieraskieliset opiskelijat"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "KansalaisuusSV",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Begynnelseläsår"
              },
              {
                "name": "Utbildn.område, nivå 2"
              },
              {
                "name": "Förvaltningsområde"
              },
              {
                "name": "Medborgarskap (världsdel)"
              },
              {
                "name": "Utbildningsnivå"
              },
              {
                "name": "Utbildningsområde"
              },
              {
                "name": "Medborgare i ett EES-land"
              },
              {
                "name": "Medborgarskap (land)"
              },
              {
                "name": "Utbildn.område, nivå 1"
              },
              {
                "name": "Statistikår"
              },
              {
                "name": "Begynnelsetermin"
              },
              {
                "name": "Kön"
              },
              {
                "name": "Medborgare i ett EU-land"
              },
              {
                "name": "Näkökulma"
              },
              {
                "name": "Utbildningssektor"
              },
              {
                "name": "Studieområde"
              },
              {
                "name": "Inskrivning (september)"
              },
              {
                "name": "Utbildn.nivå, nivå 2"
              },
              {
                "name": "Utbildningsslag"
              },
              {
                "name": "Utbildn.nivå, nivå 1"
              },
              {
                "name": "Utbildningens landskap"
              },
              {
                "name": "Utbildningsbenämning"
              },
              {
                "name": "Utbildn.område, nivå 3"
              },
              {
                "name": "Aineistonäkökulma"
              }
            ],
            "measures": [
              {
                "name": "Utländska nya studerande"
              },
              {
                "name": "Utländska studerande"
              },
              {
                "name": "Andel som utländska studerande av samtliga studerande"
              },
              {
                "name": "Andel som utländska nya studerande av samtliga nya studerande"
              },
              {
                "name": "Samtliga nya studerande"
              },
              {
                "name": "Samtliga studerande"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "KansalaisuusEN",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Citizen of EEA nation"
              },
              {
                "name": "Name of education"
              },
              {
                "name": "Region of education"
              },
              {
                "name": "Subfield of education"
              },
              {
                "name": "Field of education, tier 3"
              },
              {
                "name": "Administrative sector"
              },
              {
                "name": "Statistical year"
              },
              {
                "name": "Citizen of EU nation"
              },
              {
                "name": "First term"
              },
              {
                "name": "Form of education and training"
              },
              {
                "name": "Gender"
              },
              {
                "name": "Level of education"
              },
              {
                "name": "Näkökulma"
              },
              {
                "name": "Sector of education"
              },
              {
                "name": "Field of education, tier 2"
              },
              {
                "name": "Field of education"
              },
              {
                "name": "First academic year"
              },
              {
                "name": "Level of education, tier 2"
              },
              {
                "name": "Nationality (continent)"
              },
              {
                "name": "Enrollment status (September)"
              },
              {
                "name": "Level of education, tier 1"
              },
              {
                "name": "Nationality (country)"
              },
              {
                "name": "Field of education, tier 1"
              }
            ],
            "measures": [
              {
                "name": "All new students"
              },
              {
                "name": "Foreign students"
              },
              {
                "name": "Percentage of foreign students (of all students)"
              },
              {
                "name": "All students"
              },
              {
                "name": "New foreign students"
              },
              {
                "name": "Percentage of new foreign students (of all new students)"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "SyntymämaaSV",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Begynnelseläsår"
              },
              {
                "name": "Utbildn.område, nivå 2"
              },
              {
                "name": "Födelseland (världsdel)"
              },
              {
                "name": "Förvaltningsområde"
              },
              {
                "name": "Utbildningsområde"
              },
              {
                "name": "Utbildningsnivå"
              },
              {
                "name": "Statistikår"
              },
              {
                "name": "Utbildn.område, nivå 1"
              },
              {
                "name": "Utbildn.område, nivå 3"
              },
              {
                "name": "Utbildningens landskap"
              },
              {
                "name": "Utbildningsbenämning"
              },
              {
                "name": "Begynnelsetermin"
              },
              {
                "name": "Födelseland"
              },
              {
                "name": "Kön"
              },
              {
                "name": "Näkökulma"
              },
              {
                "name": "Studieområde"
              },
              {
                "name": "Utbildningssektor"
              },
              {
                "name": "Födelseland (Finland/andra)"
              },
              {
                "name": "Inskrivning (september)"
              },
              {
                "name": "Utbildn.nivå, nivå 2"
              },
              {
                "name": "Utbildn.nivå, nivå 1"
              },
              {
                "name": "Utbildningsslag"
              }
            ],
            "measures": [
              {
                "name": "Nya studerande som är utrikes födda"
              },
              {
                "name": "Andel som nya studerande som är utrikes födda av samtliga nya studerande"
              },
              {
                "name": "Andel som studerande som är utrikes födda av samtliga studerande"
              },
              {
                "name": "Studerande som är utrikes födda"
              },
              {
                "name": "Samtliga nya studerande"
              },
              {
                "name": "Samtliga studerande"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "SyntymämaaEN",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Country of birth (Finland/Other)"
              },
              {
                "name": "Name of education"
              },
              {
                "name": "Region of education"
              },
              {
                "name": "Country of birth"
              },
              {
                "name": "Field of education, tier 3"
              },
              {
                "name": "Subfield of education"
              },
              {
                "name": "Administrative sector"
              },
              {
                "name": "First term"
              },
              {
                "name": "Statistical year"
              },
              {
                "name": "Näkökulma"
              },
              {
                "name": "Field of education, tier 2"
              },
              {
                "name": "Form of education and training"
              },
              {
                "name": "Gender"
              },
              {
                "name": "Level of education"
              },
              {
                "name": "Sector of education"
              },
              {
                "name": "Field of education"
              },
              {
                "name": "First academic year"
              },
              {
                "name": "Level of education, tier 2"
              },
              {
                "name": "Country of birth (continent)"
              },
              {
                "name": "Enrollment status (September)"
              },
              {
                "name": "Field of education, tier 1"
              },
              {
                "name": "Level of education, tier 1"
              }
            ],
            "measures": [
              {
                "name": "All new students"
              },
              {
                "name": "Percentage of new students born abroad (of all new students)"
              },
              {
                "name": "Percentage of students born abroad (of all students)"
              },
              {
                "name": "All students"
              },
              {
                "name": "New students born abroad"
              },
              {
                "name": "Students born abroad"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "ÄidinkieliSV",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Begynnelseläsår"
              },
              {
                "name": "Utbildn.område, nivå 2"
              },
              {
                "name": "Förvaltningsområde"
              },
              {
                "name": "Modersmål (finska/andra)"
              },
              {
                "name": "Utbildningsnivå"
              },
              {
                "name": "Utbildningsområde"
              },
              {
                "name": "Statistikår"
              },
              {
                "name": "Utbildn.område, nivå 1"
              },
              {
                "name": "Begynnelsetermin"
              },
              {
                "name": "Kön"
              },
              {
                "name": "Näkökulma"
              },
              {
                "name": "Studieområde"
              },
              {
                "name": "Utbildningssektor"
              },
              {
                "name": "Inskrivning (september)"
              },
              {
                "name": "Utbildn.nivå, nivå 2"
              },
              {
                "name": "Utbildn.nivå, nivå 1"
              },
              {
                "name": "Utbildningsslag"
              },
              {
                "name": "Modersmål"
              },
              {
                "name": "Utbildn.område, nivå 3"
              },
              {
                "name": "Utbildningens landskap"
              },
              {
                "name": "Utbildningsbenämning"
              }
            ],
            "measures": [
              {
                "name": "Nya studerande med ett främmande modersmål"
              },
              {
                "name": "Andel som nya studerande med ett främmande modersmål av samtliga nya studerande"
              },
              {
                "name": "Studerande med ett främmande modersmål"
              },
              {
                "name": "Andel som studerande med ett främmande modersmål av samtliga studerande"
              },
              {
                "name": "Samtliga nya studerande"
              },
              {
                "name": "Samtliga studerande"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "ÄidinkieliEN",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Name of education"
              },
              {
                "name": "Region of education"
              },
              {
                "name": "Field of education, tier 3"
              },
              {
                "name": "Subfield of education"
              },
              {
                "name": "Administrative sector"
              },
              {
                "name": "First term"
              },
              {
                "name": "Mother tongue (Finnish/Other)"
              },
              {
                "name": "Statistical year"
              },
              {
                "name": "Field of education, tier 2"
              },
              {
                "name": "Form of education and training"
              },
              {
                "name": "Gender"
              },
              {
                "name": "Level of education"
              },
              {
                "name": "Mother tongue"
              },
              {
                "name": "Näkökulma"
              },
              {
                "name": "Sector of education"
              },
              {
                "name": "Field of education"
              },
              {
                "name": "First academic year"
              },
              {
                "name": "Level of education, tier 2"
              },
              {
                "name": "Enrollment status (September)"
              },
              {
                "name": "Field of education, tier 1"
              },
              {
                "name": "Level of education, tier 1"
              }
            ],
            "measures": [
              {
                "name": "All new students"
              },
              {
                "name": "Percentage of new foreign-language students (of all new students)"
              },
              {
                "name": "All students"
              },
              {
                "name": "New foreign-language students"
              },
              {
                "name": "Foreign-language students"
              },
              {
                "name": "Percentage of foreign-language students (of all students)"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Kansalaisuus uudetSV",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Utbildn.område, nivå 2"
              },
              {
                "name": "Förvaltningsområde"
              },
              {
                "name": "Medborgarskap (världsdel)"
              },
              {
                "name": "Utbildningsnivå"
              },
              {
                "name": "Utbildningsområde"
              },
              {
                "name": "Medborgarskap (land)"
              },
              {
                "name": "Statistikår"
              },
              {
                "name": "Utbildningens landskap"
              },
              {
                "name": "Utbildningsbenämning"
              },
              {
                "name": "Utbildn.område, nivå 1"
              },
              {
                "name": "Utbildn.område, nivå 3"
              },
              {
                "name": "Kön"
              },
              {
                "name": "Näkökulma"
              },
              {
                "name": "Studieområde"
              },
              {
                "name": "Utbildningssektor"
              },
              {
                "name": "Utbildn.nivå, nivå 2"
              },
              {
                "name": "Utbildningsslag"
              },
              {
                "name": "Utbildn.nivå, nivå 1"
              }
            ],
            "measures": [
              {
                "name": "Utländska nya studerande"
              },
              {
                "name": "Andel som utländska nya studerande av samtliga nya studerande"
              },
              {
                "name": "Samtliga nya studerande"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Kansalaisuus opiskelijatSV",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Utbildn.område, nivå 2"
              },
              {
                "name": "Förvaltningsområde"
              },
              {
                "name": "Medborgarskap (världsdel)"
              },
              {
                "name": "Utbildningsnivå"
              },
              {
                "name": "Utbildningsområde"
              },
              {
                "name": "Medborgarskap (land)"
              },
              {
                "name": "Statistikår"
              },
              {
                "name": "Utbildningens landskap"
              },
              {
                "name": "Utbildningsbenämning"
              },
              {
                "name": "Utbildn.område, nivå 1"
              },
              {
                "name": "Utbildn.område, nivå 3"
              },
              {
                "name": "Kön"
              },
              {
                "name": "Näkökulma"
              },
              {
                "name": "Studieområde"
              },
              {
                "name": "Utbildningssektor"
              },
              {
                "name": "Utbildn.nivå, nivå 2"
              },
              {
                "name": "Utbildningsslag"
              },
              {
                "name": "Utbildn.nivå, nivå 1"
              }
            ],
            "measures": [
              {
                "name": "Utländska studerande"
              },
              {
                "name": "Andel som utländska studerande av samtliga studerande"
              },
              {
                "name": "Samtliga studerande"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Kansalaisuus uudetEN",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Name of education"
              },
              {
                "name": "Region of education"
              },
              {
                "name": "Field of education, tier 1"
              },
              {
                "name": "Field of education, tier 3"
              },
              {
                "name": "Level of education, tier 1"
              },
              {
                "name": "Nationality (country)"
              },
              {
                "name": "Subfield of education"
              },
              {
                "name": "Administrative sector"
              },
              {
                "name": "Statistical year"
              },
              {
                "name": "Field of education, tier 2"
              },
              {
                "name": "Form of education and training"
              },
              {
                "name": "Gender"
              },
              {
                "name": "Level of education"
              },
              {
                "name": "Näkökulma"
              },
              {
                "name": "Sector of education"
              },
              {
                "name": "Field of education"
              },
              {
                "name": "Level of education, tier 2"
              },
              {
                "name": "Nationality (continent)"
              }
            ],
            "measures": [
              {
                "name": "All new students"
              },
              {
                "name": "New foreign students"
              },
              {
                "name": "Percentage of new foreign students (of all new students)"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Kansalaisuus opiskelijatEN",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Name of education"
              },
              {
                "name": "Region of education"
              },
              {
                "name": "Field of education, tier 1"
              },
              {
                "name": "Field of education, tier 3"
              },
              {
                "name": "Level of education, tier 1"
              },
              {
                "name": "Nationality (country)"
              },
              {
                "name": "Subfield of education"
              },
              {
                "name": "Administrative sector"
              },
              {
                "name": "Statistical year"
              },
              {
                "name": "Field of education, tier 2"
              },
              {
                "name": "Form of education and training"
              },
              {
                "name": "Gender"
              },
              {
                "name": "Level of education"
              },
              {
                "name": "Näkökulma"
              },
              {
                "name": "Sector of education"
              },
              {
                "name": "Field of education"
              },
              {
                "name": "Level of education, tier 2"
              },
              {
                "name": "Nationality (continent)"
              }
            ],
            "measures": [
              {
                "name": "Foreign students"
              },
              {
                "name": "Percentage of foreign students (of all students)"
              },
              {
                "name": "All students"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Syntymämaa uudetSV",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Utbildn.område, nivå 2"
              },
              {
                "name": "Födelseland (världsdel)"
              },
              {
                "name": "Förvaltningsområde"
              },
              {
                "name": "Utbildningsnivå"
              },
              {
                "name": "Utbildningsområde"
              },
              {
                "name": "Statistikår"
              },
              {
                "name": "Utbildningens landskap"
              },
              {
                "name": "Utbildningsbenämning"
              },
              {
                "name": "Utbildn.område, nivå 1"
              },
              {
                "name": "Utbildn.område, nivå 3"
              },
              {
                "name": "Födelseland"
              },
              {
                "name": "Kön"
              },
              {
                "name": "Näkökulma"
              },
              {
                "name": "Studieområde"
              },
              {
                "name": "Utbildningssektor"
              },
              {
                "name": "Utbildn.nivå, nivå 2"
              },
              {
                "name": "Utbildningsslag"
              },
              {
                "name": "Utbildn.nivå, nivå 1"
              }
            ],
            "measures": [
              {
                "name": "Andel som nya studerande som är utrikes födda av samtliga nya studerande"
              },
              {
                "name": "Nya studerande som är utrikes födda"
              },
              {
                "name": "Samtliga nya studerande"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Syntymämaa opiskelijatSV",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Utbildn.område, nivå 2"
              },
              {
                "name": "Födelseland (världsdel)"
              },
              {
                "name": "Förvaltningsområde"
              },
              {
                "name": "Utbildningsnivå"
              },
              {
                "name": "Utbildningsområde"
              },
              {
                "name": "Statistikår"
              },
              {
                "name": "Utbildningens landskap"
              },
              {
                "name": "Utbildningsbenämning"
              },
              {
                "name": "Utbildn.område, nivå 1"
              },
              {
                "name": "Utbildn.område, nivå 3"
              },
              {
                "name": "Födelseland"
              },
              {
                "name": "Kön"
              },
              {
                "name": "Näkökulma"
              },
              {
                "name": "Studieområde"
              },
              {
                "name": "Utbildningssektor"
              },
              {
                "name": "Utbildn.nivå, nivå 2"
              },
              {
                "name": "Utbildningsslag"
              },
              {
                "name": "Utbildn.nivå, nivå 1"
              }
            ],
            "measures": [
              {
                "name": "Andel som studerande som är utrikes födda av samtliga studerande"
              },
              {
                "name": "Studerande som är utrikes födda"
              },
              {
                "name": "Samtliga studerande"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Syntymämaa uudetEN",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Name of education"
              },
              {
                "name": "Region of education"
              },
              {
                "name": "Country of birth"
              },
              {
                "name": "Field of education, tier 3"
              },
              {
                "name": "Subfield of education"
              },
              {
                "name": "Administrative sector"
              },
              {
                "name": "Statistical year"
              },
              {
                "name": "Field of education, tier 2"
              },
              {
                "name": "Form of education and training"
              },
              {
                "name": "Gender"
              },
              {
                "name": "Level of education"
              },
              {
                "name": "Näkökulma"
              },
              {
                "name": "Sector of education"
              },
              {
                "name": "Field of education"
              },
              {
                "name": "Level of education, tier 2"
              },
              {
                "name": "Country of birth (continent)"
              },
              {
                "name": "Field of education, tier 1"
              },
              {
                "name": "Level of education, tier 1"
              }
            ],
            "measures": [
              {
                "name": "All new students"
              },
              {
                "name": "Percentage of new students born abroad (of all new students)"
              },
              {
                "name": "New students born abroad"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Syntymämaa opiskelijatEN",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Name of education"
              },
              {
                "name": "Region of education"
              },
              {
                "name": "Country of birth"
              },
              {
                "name": "Field of education, tier 3"
              },
              {
                "name": "Subfield of education"
              },
              {
                "name": "Administrative sector"
              },
              {
                "name": "Statistical year"
              },
              {
                "name": "Field of education, tier 2"
              },
              {
                "name": "Form of education and training"
              },
              {
                "name": "Gender"
              },
              {
                "name": "Level of education"
              },
              {
                "name": "Näkökulma"
              },
              {
                "name": "Sector of education"
              },
              {
                "name": "Field of education"
              },
              {
                "name": "Level of education, tier 2"
              },
              {
                "name": "Country of birth (continent)"
              },
              {
                "name": "Field of education, tier 1"
              },
              {
                "name": "Level of education, tier 1"
              }
            ],
            "measures": [
              {
                "name": "Percentage of students born abroad (of all students)"
              },
              {
                "name": "All students"
              },
              {
                "name": "Students born abroad"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Äidinkieli uudetSV",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Utbildn.område, nivå 2"
              },
              {
                "name": "Förvaltningsområde"
              },
              {
                "name": "Utbildn.nivå, nivå 1"
              },
              {
                "name": "Utbildningsnivå"
              },
              {
                "name": "Utbildningsområde"
              },
              {
                "name": "Utbildningsslag"
              },
              {
                "name": "Modersmål (finska/andra)"
              },
              {
                "name": "Modersmål"
              },
              {
                "name": "Statistikår"
              },
              {
                "name": "Utbildningens landskap"
              },
              {
                "name": "Utbildningsbenämning"
              },
              {
                "name": "Utbildn.område, nivå 1"
              },
              {
                "name": "Utbildn.område, nivå 3"
              },
              {
                "name": "Kön"
              },
              {
                "name": "Näkökulma"
              },
              {
                "name": "Studieområde"
              },
              {
                "name": "Utbildningssektor"
              },
              {
                "name": "Utbildn.nivå, nivå 2"
              }
            ],
            "measures": [
              {
                "name": "Nya studerande med ett främmande modersmål"
              },
              {
                "name": "Andel som nya studerande med ett främmande modersmål av samtliga nya studerande"
              },
              {
                "name": "Samtliga nya studerande"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Äidinkieli opiskelijatSV",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Utbildn.område, nivå 2"
              },
              {
                "name": "Förvaltningsområde"
              },
              {
                "name": "Utbildn.nivå, nivå 1"
              },
              {
                "name": "Utbildningsnivå"
              },
              {
                "name": "Utbildningsområde"
              },
              {
                "name": "Utbildningsslag"
              },
              {
                "name": "Modersmål (finska/andra)"
              },
              {
                "name": "Modersmål"
              },
              {
                "name": "Statistikår"
              },
              {
                "name": "Utbildningens landskap"
              },
              {
                "name": "Utbildningsbenämning"
              },
              {
                "name": "Utbildn.område, nivå 1"
              },
              {
                "name": "Utbildn.område, nivå 3"
              },
              {
                "name": "Kön"
              },
              {
                "name": "Näkökulma"
              },
              {
                "name": "Studieområde"
              },
              {
                "name": "Utbildningssektor"
              },
              {
                "name": "Utbildn.nivå, nivå 2"
              }
            ],
            "measures": [
              {
                "name": "Studerande med ett främmande modersmål"
              },
              {
                "name": "Andel som studerande med ett främmande modersmål av samtliga studerande"
              },
              {
                "name": "Samtliga studerande"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Äidinkieli uudetEN",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Name of education"
              },
              {
                "name": "Region of education"
              },
              {
                "name": "Field of education, tier 3"
              },
              {
                "name": "Subfield of education"
              },
              {
                "name": "Administrative sector"
              },
              {
                "name": "Mother tongue (Finnish/Other)"
              },
              {
                "name": "Statistical year"
              },
              {
                "name": "Field of education, tier 2"
              },
              {
                "name": "Form of education and training"
              },
              {
                "name": "Gender"
              },
              {
                "name": "Level of education"
              },
              {
                "name": "Mother tongue"
              },
              {
                "name": "Näkökulma"
              },
              {
                "name": "Sector of education"
              },
              {
                "name": "Field of education"
              },
              {
                "name": "Level of education, tier 2"
              },
              {
                "name": "Field of education, tier 1"
              },
              {
                "name": "Level of education, tier 1"
              }
            ],
            "measures": [
              {
                "name": "All new students"
              },
              {
                "name": "Percentage of new foreign-language students (of all new students)"
              },
              {
                "name": "New foreign-language students"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Äidinkieli opiskelijatEN",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Name of education"
              },
              {
                "name": "Region of education"
              },
              {
                "name": "Field of education, tier 3"
              },
              {
                "name": "Subfield of education"
              },
              {
                "name": "Administrative sector"
              },
              {
                "name": "Mother tongue (Finnish/Other)"
              },
              {
                "name": "Statistical year"
              },
              {
                "name": "Field of education, tier 2"
              },
              {
                "name": "Form of education and training"
              },
              {
                "name": "Gender"
              },
              {
                "name": "Level of education"
              },
              {
                "name": "Mother tongue"
              },
              {
                "name": "Näkökulma"
              },
              {
                "name": "Sector of education"
              },
              {
                "name": "Field of education"
              },
              {
                "name": "Level of education, tier 2"
              },
              {
                "name": "Field of education, tier 1"
              },
              {
                "name": "Level of education, tier 1"
              }
            ],
            "measures": [
              {
                "name": "All students"
              },
              {
                "name": "Foreign-language students"
              },
              {
                "name": "Percentage of foreign-language students (of all students)"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      }
    ],
    "roles": [
      {
        "name": "Luku",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "DWI\\T_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1732"
          },
          {
            "memberName": "NT AUTHORITY\\IUSR",
            "memberId": "S-1-5-17"
          },
          {
            "memberName": "DWI\\P_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1733"
          },
          {
            "memberName": "DWI\\Z_P_Antero_Read_TAB",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-4156"
          },
          {
            "memberName": "DWI\\Z_T_Antero_Read_TAB",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-4155"
          },
          {
            "memberName": "DWI\\Z_P_Antero_Full_Read_TAB",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-2272"
          }
        ]
      },
      {
        "name": "Kehitys",
        "modelPermission": "administrator",
        "members": [
          {
            "memberName": "DWI\\T_VIPU_TABOKM_DB_VipunenTK_Dev",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1364"
          },
          {
            "memberName": "DWI\\T_VIPU_TAB_DB_VipunenTK_Dev",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1363"
          },
          {
            "memberName": "DWI\\Z_P_Antero_Read_TAB",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-4156"
          },
          {
            "memberName": "DWI\\Z_T_Antero_Read_TAB",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-4155"
          }
        ]
      }
    ]
  }
}