{
  "name": "SemanticModel",
  "compatibilityLevel": 1200,
  "model": {
    "culture": "fi-FI",
    "dataSources": [
      {
        "name": "SqlServer dwitvipusql16 ANTERO",
        "connectionString": "Provider=SQLNCLI11;Data Source=dwitvipusql16;Initial Catalog=ANTERO;Integrated Security=SSPI;Persist Security Info=false",
        "impersonationMode": "impersonateServiceAccount",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "Sarakeleveys",
        "columns": [
          {
            "name": "Sarakeleveys",
            "dataType": "string",
            "sourceColumn": "Sarakeleveys",
            "sourceProviderType": "Char"
          },
          {
            "name": "leveys",
            "dataType": "string",
            "sourceColumn": "leveys",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Sarakeleveys",
            "dataView": "full",
            "source": {
              "query": " SELECT [dw].[Sarakeleveys].* FROM [dw].[Sarakeleveys] ",
              "dataSource": "SqlServer dwitvipusql16 ANTERO"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dw].[Sarakeleveys].* FROM [dw].[Sarakeleveys] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Sarakeleveys"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dw"
          }
        ]
      },
      {
        "name": "Muuttujat",
        "columns": [
          {
            "name": "Tilastovuosi",
            "dataType": "int64",
            "sourceColumn": "Tilastovuosi",
            "sourceProviderType": "Integer",
            "displayFolder": "Aikamuuttujat"
          },
          {
            "name": "Tilastokuukausi",
            "dataType": "string",
            "sourceColumn": "Tilastokuukausi",
            "sortByColumn": "jarj_tilastokuukausi",
            "sourceProviderType": "WChar",
            "displayFolder": "Aikamuuttujat"
          },
          {
            "name": "Sukupuoli",
            "dataType": "string",
            "sourceColumn": "Sukupuoli",
            "sortByColumn": "jarj_sukupuoli",
            "sourceProviderType": "WChar",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Äidinkieli",
            "dataType": "string",
            "sourceColumn": "Äidinkieli",
            "sourceProviderType": "WChar",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Ikä",
            "dataType": "string",
            "sourceColumn": "Ikä",
            "sortByColumn": "jarj_ika",
            "sourceProviderType": "WChar",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Ikäryhmä",
            "dataType": "string",
            "sourceColumn": "Ikäryhmä",
            "sortByColumn": "jarj_ikaryhma",
            "sourceProviderType": "WChar",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Hyväksytyt/hylätyt opiskelijavuodet",
            "dataType": "string",
            "sourceColumn": "Hyväksytyt/hylätyt opiskelijavuodet",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Tutkintotyypin ryhmä",
            "dataType": "string",
            "sourceColumn": "Tutkintotyypin ryhmä",
            "sortByColumn": "jarj_tutkintotyypin_ryhma",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Tutkintotyyppi",
            "dataType": "string",
            "sourceColumn": "Tutkintotyyppi",
            "sortByColumn": "jarj_tutkintotyyppi",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Tutkinto",
            "dataType": "string",
            "sourceColumn": "Tutkinto",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusala, taso 3",
            "dataType": "string",
            "sourceColumn": "Koulutusala, taso 3",
            "sortByColumn": "jarj_koulutusala_taso3",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusala, taso 2",
            "dataType": "string",
            "sourceColumn": "Koulutusala, taso 2",
            "sortByColumn": "jarj_koulutusala_taso2",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusala, taso 1",
            "dataType": "string",
            "sourceColumn": "Koulutusala, taso 1",
            "sortByColumn": "jarj_koulutusala_taso1",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Osaamisala",
            "dataType": "string",
            "sourceColumn": "Osaamisala",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Osa-aikaisuus",
            "dataType": "string",
            "sourceColumn": "Osa-aikaisuus",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Suorituksen tyyppi",
            "dataType": "string",
            "sourceColumn": "Suorituksen tyyppi",
            "sourceProviderType": "Char",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Kustannusryhmä",
            "dataType": "string",
            "sourceColumn": "Kustannusryhmä",
            "sortByColumn": "jarj_kustannusryhma",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Rahoitusmuoto",
            "dataType": "string",
            "sourceColumn": "Rahoitusmuoto",
            "sortByColumn": "jarj_rahoitusmuoto",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Erityisopetus",
            "dataType": "string",
            "sourceColumn": "Erityisopetus",
            "sortByColumn": "jarj_erityisopetus",
            "sourceProviderType": "Char",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Majoitus",
            "dataType": "string",
            "sourceColumn": "Majoitus",
            "sourceProviderType": "Char",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Oppisopimuskoulutus",
            "dataType": "string",
            "sourceColumn": "Oppisopimuskoulutus",
            "sourceProviderType": "Char",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Vankilaopetus",
            "dataType": "string",
            "sourceColumn": "Vankilaopetus",
            "sourceProviderType": "Char",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Henkilöstokoulutus",
            "dataType": "string",
            "sourceColumn": "Henkilöstokoulutus",
            "sourceProviderType": "Char",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Työvoimakoulutus",
            "dataType": "string",
            "sourceColumn": "Työvoimakoulutus",
            "sourceProviderType": "Char",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Hankintakoulutus",
            "dataType": "string",
            "sourceColumn": "Hankintakoulutus",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Hankintakoulutuksen järjestäjä",
            "dataType": "string",
            "sourceColumn": "Hankintakoulutuksen järjestäjä",
            "sourceProviderType": "WChar",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Oppilaitos",
            "dataType": "string",
            "sourceColumn": "Oppilaitos",
            "sourceProviderType": "WChar",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Koulutuksen järjestäjä",
            "dataType": "string",
            "sourceColumn": "Koulutuksen järjestäjä",
            "sourceProviderType": "WChar",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Toimipiste",
            "dataType": "string",
            "sourceColumn": "Toimipiste",
            "sourceProviderType": "WChar",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Oppilaitoksen kunta",
            "dataType": "string",
            "sourceColumn": "Oppilaitoksen kunta",
            "sourceProviderType": "WChar",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Oppilaitoksen maakunta",
            "dataType": "string",
            "sourceColumn": "Oppilaitoksen maakunta",
            "sortByColumn": "jarj_oppilaitoksen_maakunta",
            "sourceProviderType": "WChar",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Oppilaitoksen AVI",
            "dataType": "string",
            "sourceColumn": "Oppilaitoksen AVI",
            "sortByColumn": "jarj_oppilaitoksen_avi",
            "sourceProviderType": "WChar",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Oppilaitoksen ELY",
            "dataType": "string",
            "sourceColumn": "Oppilaitoksen ELY",
            "sortByColumn": "jarj_oppilaitoksen_ely",
            "sourceProviderType": "WChar",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Koul. järjestäjän kunta",
            "dataType": "string",
            "sourceColumn": "Koul. järjestäjän kunta",
            "sourceProviderType": "WChar",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Koul. järjestäjän maakunta",
            "dataType": "string",
            "sourceColumn": "Koul. järjestäjän maakunta",
            "sortByColumn": "jarj_koul_jarj_maakunta",
            "sourceProviderType": "WChar",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Koul. järjestäjän ELY",
            "dataType": "string",
            "sourceColumn": "Koul. järjestäjän ELY",
            "sortByColumn": "jarj_koul_jarj_ely",
            "sourceProviderType": "WChar",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Koul. järjestäjän AVI",
            "dataType": "string",
            "sourceColumn": "Koul. järjestäjän AVI",
            "sortByColumn": "jarj_koul_jarj_avi",
            "sourceProviderType": "WChar",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Luvaton koulutus",
            "dataType": "string",
            "sourceColumn": "Luvaton koulutus",
            "sortByColumn": "jarj_luvaton_koulutus",
            "sourceProviderType": "Char",
            "displayFolder": "Järjestämislupamuuttujat"
          },
          {
            "name": "Luvaton majoitus",
            "dataType": "string",
            "sourceColumn": "Luvaton majoitus",
            "sortByColumn": "jarj_luvaton_majoitus",
            "sourceProviderType": "Char",
            "displayFolder": "Järjestämislupamuuttujat"
          },
          {
            "name": "Luvaton korotustekijä",
            "dataType": "string",
            "sourceColumn": "Luvaton korotustekijä",
            "sortByColumn": "jarj_luvaton_korotustekija",
            "sourceProviderType": "Char",
            "displayFolder": "Järjestämislupamuuttujat"
          },
          {
            "name": "sisaopp_ylittyy",
            "dataType": "int64",
            "sourceColumn": "sisaopp_ylittyy",
            "sourceProviderType": "Integer"
          },
          {
            "name": "erityistuki_ylittyy",
            "dataType": "int64",
            "sourceColumn": "erityistuki_ylittyy",
            "sourceProviderType": "Integer"
          },
          {
            "name": "opiskelijavuodet_painottamaton",
            "dataType": "double",
            "sourceColumn": "opiskelijavuodet_painottamaton",
            "sourceProviderType": "Double"
          },
          {
            "name": "opiskelijavuodet_painotettu_yhteensa",
            "dataType": "double",
            "sourceColumn": "opiskelijavuodet_painotettu_yhteensa",
            "sourceProviderType": "Double"
          },
          {
            "name": "opiskelijavuodet_painotettu_pt",
            "dataType": "double",
            "sourceColumn": "opiskelijavuodet_painotettu_pt",
            "sourceProviderType": "Double"
          },
          {
            "name": "opiskelijavuodet_painotettu_at_eat",
            "dataType": "double",
            "sourceColumn": "opiskelijavuodet_painotettu_at_eat",
            "sourceProviderType": "Double"
          },
          {
            "name": "opiskelijavuodet_painotettu_valma_telma",
            "dataType": "double",
            "sourceColumn": "opiskelijavuodet_painotettu_valma_telma",
            "sourceProviderType": "Double"
          },
          {
            "name": "opiskelijavuodet_painotettu_opisk_valm_tukevat",
            "dataType": "double",
            "sourceColumn": "opiskelijavuodet_painotettu_opisk_valm_tukevat",
            "sourceProviderType": "Double"
          },
          {
            "name": "opiskelijavuodet_painotettu_muu",
            "dataType": "double",
            "sourceColumn": "opiskelijavuodet_painotettu_muu",
            "sourceProviderType": "Double"
          },
          {
            "name": "opiskelijavuodet_painotettu_erityistuki",
            "dataType": "double",
            "sourceColumn": "opiskelijavuodet_painotettu_erityistuki",
            "sourceProviderType": "Double"
          },
          {
            "name": "opiskelijavuodet_painotettu_erityistuki_hyv",
            "dataType": "double",
            "sourceColumn": "opiskelijavuodet_painotettu_erityistuki_hyv",
            "sourceProviderType": "Double"
          },
          {
            "name": "opiskelijavuodet_painotettu_majoitus",
            "dataType": "double",
            "sourceColumn": "opiskelijavuodet_painotettu_majoitus",
            "sourceProviderType": "Double"
          },
          {
            "name": "opiskelijavuodet_painotettu_majoitus_hyv",
            "dataType": "double",
            "sourceColumn": "opiskelijavuodet_painotettu_majoitus_hyv",
            "sourceProviderType": "Double"
          },
          {
            "name": "opiskelijavuodet_painotettu_henkilostokoulutus",
            "dataType": "double",
            "sourceColumn": "opiskelijavuodet_painotettu_henkilostokoulutus",
            "sourceProviderType": "Double"
          },
          {
            "name": "opiskelijavuodet_painotettu_tyovoimakoulutus",
            "dataType": "double",
            "sourceColumn": "opiskelijavuodet_painotettu_tyovoimakoulutus",
            "sourceProviderType": "Double"
          },
          {
            "name": "opiskelijavuodet_painotettu_vankilaopetus",
            "dataType": "double",
            "sourceColumn": "opiskelijavuodet_painotettu_vankilaopetus",
            "sourceProviderType": "Double"
          },
          {
            "name": "opiskelijavuodet_hylatyt",
            "dataType": "double",
            "sourceColumn": "opiskelijavuodet_hylatyt",
            "sourceProviderType": "Double"
          },
          {
            "name": "Koodit Koulutuksen järjestäjä",
            "dataType": "string",
            "sourceColumn": "Koodit Koulutuksen järjestäjä",
            "sourceProviderType": "Char",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koodit Hankintakoulutuksen järjestäjä",
            "dataType": "string",
            "sourceColumn": "Koodit Hankintakoulutuksen järjestäjä",
            "sourceProviderType": "Char",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koodit Oppilaitos",
            "dataType": "string",
            "sourceColumn": "Koodit Oppilaitos",
            "sourceProviderType": "Char",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koodit Tutkinto",
            "dataType": "string",
            "sourceColumn": "Koodit Tutkinto",
            "sourceProviderType": "Char",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koodit Osaamisala",
            "dataType": "string",
            "sourceColumn": "Koodit Osaamisala",
            "sourceProviderType": "WChar",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koodit Kustannusryhmä",
            "dataType": "string",
            "sourceColumn": "Koodit Kustannusryhmä",
            "sourceProviderType": "WChar",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "jarj_kustannusryhma",
            "dataType": "int64",
            "sourceColumn": "jarj_kustannusryhma",
            "sourceProviderType": "Integer"
          },
          {
            "name": "jarj_rahoitusmuoto",
            "dataType": "int64",
            "sourceColumn": "jarj_rahoitusmuoto",
            "sourceProviderType": "Integer"
          },
          {
            "name": "jarj_tilastokuukausi",
            "dataType": "int64",
            "sourceColumn": "jarj_tilastokuukausi",
            "sourceProviderType": "Integer"
          },
          {
            "name": "jarj_sukupuoli",
            "dataType": "string",
            "sourceColumn": "jarj_sukupuoli",
            "sourceProviderType": "Char"
          },
          {
            "name": "jarj_ikaryhma",
            "dataType": "string",
            "sourceColumn": "jarj_ikaryhma",
            "sourceProviderType": "WChar"
          },
          {
            "name": "jarj_ika",
            "dataType": "string",
            "sourceColumn": "jarj_ika",
            "sourceProviderType": "Char"
          },
          {
            "name": "jarj_koulutusala_taso1",
            "dataType": "string",
            "sourceColumn": "jarj_koulutusala_taso1",
            "sourceProviderType": "Char"
          },
          {
            "name": "jarj_koulutusala_taso2",
            "dataType": "string",
            "sourceColumn": "jarj_koulutusala_taso2",
            "sourceProviderType": "Char"
          },
          {
            "name": "jarj_koulutusala_taso3",
            "dataType": "string",
            "sourceColumn": "jarj_koulutusala_taso3",
            "sourceProviderType": "Char"
          },
          {
            "name": "jarj_koul_jarj_maakunta",
            "dataType": "string",
            "sourceColumn": "jarj_koul_jarj_maakunta",
            "sourceProviderType": "Char"
          },
          {
            "name": "jarj_koul_jarj_avi",
            "dataType": "string",
            "sourceColumn": "jarj_koul_jarj_avi",
            "sourceProviderType": "Char"
          },
          {
            "name": "jarj_koul_jarj_ely",
            "dataType": "string",
            "sourceColumn": "jarj_koul_jarj_ely",
            "sourceProviderType": "Char"
          },
          {
            "name": "jarj_oppilaitoksen_maakunta",
            "dataType": "string",
            "sourceColumn": "jarj_oppilaitoksen_maakunta",
            "sourceProviderType": "Char"
          },
          {
            "name": "jarj_oppilaitoksen_ely",
            "dataType": "string",
            "sourceColumn": "jarj_oppilaitoksen_ely",
            "sourceProviderType": "Char"
          },
          {
            "name": "jarj_oppilaitoksen_avi",
            "dataType": "string",
            "sourceColumn": "jarj_oppilaitoksen_avi",
            "sourceProviderType": "Char"
          },
          {
            "name": "jarj_erityisopetus",
            "dataType": "string",
            "sourceColumn": "jarj_erityisopetus",
            "sourceProviderType": "Char"
          },
          {
            "name": "jarj_tutkintotyypin_ryhma",
            "dataType": "string",
            "sourceColumn": "jarj_tutkintotyypin_ryhma",
            "sourceProviderType": "Char"
          },
          {
            "name": "jarj_tutkintotyyppi",
            "dataType": "string",
            "sourceColumn": "jarj_tutkintotyyppi",
            "sourceProviderType": "Char"
          },
          {
            "name": "jarj_hylkaamisperuste",
            "dataType": "string",
            "sourceColumn": "jarj_hylkaamisperuste",
            "sourceProviderType": "WChar"
          },
          {
            "name": "jarj_luvaton_koulutus",
            "dataType": "string",
            "sourceColumn": "jarj_luvaton_koulutus",
            "sourceProviderType": "Char"
          },
          {
            "name": "jarj_luvaton_majoitus",
            "dataType": "string",
            "sourceColumn": "jarj_luvaton_majoitus",
            "sourceProviderType": "Char"
          },
          {
            "name": "jarj_luvaton_korotustekija",
            "dataType": "string",
            "sourceColumn": "jarj_luvaton_korotustekija",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "v_amos_opiskelijavuodet_uusi",
            "dataView": "full",
            "source": {
              "query": " SELECT [dw].[v_amos_opiskelijavuodet_uusi].* FROM [dw].[v_amos_opiskelijavuodet_uusi] ",
              "dataSource": "SqlServer dwitvipusql16 ANTERO"
            }
          }
        ],
        "measures": [
          {
            "name": "Hyväksytyt opiskelijavuodet (pl. muu koulutus)",
            "expression": "[Painottamattomat opiskelijavuodet (pl. muu koulutus)]",
            "formatString": "#,0.0",
            "displayFolder": "Opiskelijavuodet"
          },
          {
            "name": "Painottamattomat opiskelijavuodet yhteensä",
            "expression": [
              "",
              "var summa = CALCULATE(CALCULATE(SUM([opiskelijavuodet_painottamaton])+[Hylätyt opiskelijavuodet],ALL(Muuttujat[Luvaton korotustekijä])),ALL(Muuttujat[Luvaton majoitus]))",
              "return IF(summa=0 || [korotusehto]=0,BLANK(),summa)"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Opiskelijavuodet"
          },
          {
            "name": "Majoituksen mukaan painotetut opiskelijavuodet",
            "expression": [
              "",
              "var summa_perus=CALCULATE(SUM(Muuttujat[opiskelijavuodet_painotettu_majoitus]),ALL(Muuttujat[Luvaton korotustekijä]))",
              "var summa_hyv=CALCULATE(SUM(Muuttujat[opiskelijavuodet_painotettu_majoitus_hyv]),ALL(Muuttujat[Luvaton korotustekijä]))",
              "var erotus=summa_perus-summa_hyv",
              "var luvaton=IF(COUNTROWS(VALUES(Muuttujat[jarj_luvaton_majoitus]))=1,IF(VALUES(Muuttujat[jarj_luvaton_majoitus])<>\"1\",1,0),0)",
              "var siirretaan_hyvaksytyksi=IF(ISFILTERED(Muuttujat[Luvaton majoitus]),CALCULATE(SUM([opiskelijavuodet_painotettu_majoitus_hyv]),Muuttujat[jarj_luvaton_majoitus]<>\"1\",ALL(Muuttujat[Luvaton majoitus])),0)",
              "var korotusehto=IF(COUNTROWS(VALUES(Muuttujat[jarj_luvaton_korotustekija]))=1,IF(VALUES(Muuttujat[jarj_luvaton_korotustekija])=\"1\",1,0),1)",
              "",
              "return IF(summa_perus=0 || korotusehto=0,BLANK(),IF(luvaton=1,erotus,summa_perus+siirretaan_hyvaksytyksi))"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Opiskelijavuodet"
          },
          {
            "name": "Painotetut opiskelijavuodet yhteensä",
            "expression": [
              "",
              "[Kustannusryhmän mukaan painotetut perustutkinnon opiskelijavuodet]+",
              "[Kustannusryhmän mukaan painotetut at- ja eat-tutkinnon opiskelijavuodet]+",
              "[Kustannusryhmän mukaan painotetut VALMA&TELMA opiskelijavuodet]+",
              "[Kustannusryhmän mukaan painotetut opiskelijavalmiuksia tukevat opiskelijavuodet]+",
              "[Kustannusryhmän mukaan painotetut muun koulutuksen opiskelijavuodet]+",
              "[Majoituksen hyväksytyt painotetut opiskelijavuodet]+",
              "[Erityistuen hyväksytyt painotetut opiskelijavuodet]+",
              "[Työvoimakoulutuksen mukaan painotetut opiskelijavuodet]+",
              "[Vankilakoulutuksen mukaan painotetut opiskelijavuodet]+",
              "[Henkilöstökoulutuksen mukaan painotetut opiskelijavuodet]"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Opiskelijavuodet"
          },
          {
            "name": "Muun koulutuksen painottamattomat opiskelijavuodet",
            "expression": [
              "",
              "var summa=CALCULATE(SUM([opiskelijavuodet_painottamaton]),FILTER(Muuttujat,[Koodit Kustannusryhmä]=\"muu\"))",
              "return IF(summa=0,BLANK(),summa)"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Opiskelijavuodet"
          },
          {
            "name": "Painottamattomat opiskelijavuodet (pl. muu koulutus)",
            "expression": [
              "",
              "var erotus = [Painottamattomat opiskelijavuodet yhteensä]-[Muun koulutuksen painottamattomat opiskelijavuodet]",
              "return IF(erotus<=0.0000001,BLANK(),erotus)"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Opiskelijavuodet"
          },
          {
            "name": "Hylätyt opiskelijavuodet",
            "expression": [
              "",
              "var summa=SUM(Muuttujat[opiskelijavuodet_hylatyt])",
              "return IF(summa=0,BLANK(),summa)"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Opiskelijavuodet"
          },
          {
            "name": "Majoituksen hyväksytyt painotetut opiskelijavuodet",
            "expression": [
              "",
              "var painotettu=[Majoituksen mukaan painotetut opiskelijavuodet]",
              "var ylittyy=MAX(Muuttujat[sisaopp_ylittyy])",
              "var hylatty_ylitys=CALCULATE(SUM(Muuttujat[opiskelijavuodet_painotettu_majoitus])-SUM(Muuttujat[opiskelijavuodet_painotettu_majoitus_hyv]),Muuttujat[sisaopp_ylittyy]=1, ALL(Muuttujat[Luvaton majoitus]))",
              "",
              "return IF(ylittyy=1,painotettu-hylatty_ylitys,painotettu)"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Opiskelijavuodet"
          },
          {
            "name": "Erityistuen hyväksytyt painotetut opiskelijavuodet",
            "expression": [
              "",
              "var summa=SUM(Muuttujat[opiskelijavuodet_painotettu_erityistuki_hyv])",
              "return IF(summa=0,BLANK(),summa)"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Opiskelijavuodet"
          },
          {
            "name": "Kustannusryhmän mukaan painotetut at- ja eat-tutkinnon opiskelijavuodet",
            "expression": [
              "",
              "var summa=CALCULATE(SUM(Muuttujat[opiskelijavuodet_painotettu_at_eat]),ALL(Muuttujat[Luvaton korotustekijä]),ALL(Muuttujat[Luvaton majoitus]))",
              "",
              "return IF(summa=0 || [korotusehto]=0,BLANK(),summa)"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Opiskelijavuodet"
          },
          {
            "name": "Työvoimakoulutuksen mukaan painotetut opiskelijavuodet",
            "expression": [
              "",
              "var summa=SUM(Muuttujat[opiskelijavuodet_painotettu_tyovoimakoulutus])",
              "return IF(summa=0,BLANK(),summa)"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Opiskelijavuodet"
          },
          {
            "name": "Erityistuen mukaan painotetut opiskelijavuodet",
            "expression": [
              "",
              "var summa=SUM(Muuttujat[opiskelijavuodet_painotettu_erityistuki])",
              "return IF(summa=0,BLANK(),summa)"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Opiskelijavuodet"
          },
          {
            "name": "Kustannusryhmän mukaan painotetut perustutkinnon opiskelijavuodet",
            "expression": [
              "",
              "var summa=CALCULATE(SUM(Muuttujat[opiskelijavuodet_painotettu_pt]),ALL(Muuttujat[Luvaton korotustekijä]),ALL(Muuttujat[Luvaton majoitus]))",
              "",
              "return IF(summa=0 || [korotusehto]=0,BLANK(),summa)"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Opiskelijavuodet"
          },
          {
            "name": "Kustannusryhmän mukaan painotetut VALMA&TELMA opiskelijavuodet",
            "expression": [
              "",
              "var summa=CALCULATE(SUM(Muuttujat[opiskelijavuodet_painotettu_valma_telma]),ALL(Muuttujat[Luvaton korotustekijä]),ALL(Muuttujat[Luvaton majoitus]))",
              "",
              "return IF(summa=0 || [korotusehto]=0,BLANK(),summa)"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Opiskelijavuodet"
          },
          {
            "name": "Kustannusryhmän mukaan painotetut opiskelijavalmiuksia tukevat opiskelijavuodet",
            "expression": [
              "",
              "var summa=CALCULATE(SUM(Muuttujat[opiskelijavuodet_painotettu_opisk_valm_tukevat]),ALL(Muuttujat[Luvaton korotustekijä]),ALL(Muuttujat[Luvaton majoitus]))",
              "",
              "return IF(summa=0 || [korotusehto]=0,BLANK(),summa)"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Opiskelijavuodet"
          },
          {
            "name": "Kustannusryhmän mukaan painotetut muun koulutuksen opiskelijavuodet",
            "expression": [
              "",
              "var summa=CALCULATE(SUM(Muuttujat[opiskelijavuodet_painotettu_muu]),ALL(Muuttujat[Luvaton korotustekijä]),ALL(Muuttujat[Luvaton majoitus]))",
              "",
              "return IF(summa=0 || [korotusehto]=0,BLANK(),summa)"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Opiskelijavuodet"
          },
          {
            "name": "Henkilöstökoulutuksen mukaan painotetut opiskelijavuodet",
            "expression": [
              "",
              "var summa=CALCULATE(SUM(Muuttujat[opiskelijavuodet_painotettu_henkilostokoulutus]),ALL(Muuttujat[Luvaton korotustekijä]))",
              "return IF(summa=0 || [korotusehto]=0,BLANK(),summa)"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Opiskelijavuodet"
          },
          {
            "name": "Vankilakoulutuksen mukaan painotetut opiskelijavuodet",
            "expression": [
              "",
              "var summa=SUM(Muuttujat[opiskelijavuodet_painotettu_vankilaopetus])",
              "return IF(summa=0,BLANK(),summa)"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Opiskelijavuodet"
          },
          {
            "name": "Profiilikerroin",
            "expression": "[Painotetut opiskelijavuodet yhteensä] / [Painottamattomat opiskelijavuodet yhteensä]",
            "formatString": "0.0000",
            "displayFolder": "Opiskelijavuodet"
          },
          {
            "name": "Kustannusryhmän mukaan painotetut perustutkinnon opiskelijavuodet %",
            "expression": "DIVIDE([Kustannusryhmän mukaan painotetut perustutkinnon opiskelijavuodet],CALCULATE([Kustannusryhmän mukaan painotetut perustutkinnon opiskelijavuodet],ALL(Muuttujat[Koulutuksen järjestäjä])))",
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Prosenttiosuudet"
          },
          {
            "name": "Kustannusryhmän mukaan painotetut at- ja eat-tutkinnon opiskelijavuodet %",
            "expression": "DIVIDE([Kustannusryhmän mukaan painotetut at- ja eat-tutkinnon opiskelijavuodet],CALCULATE([Kustannusryhmän mukaan painotetut at- ja eat-tutkinnon opiskelijavuodet],ALL(Muuttujat[Koulutuksen järjestäjä])))",
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Prosenttiosuudet"
          },
          {
            "name": "Kustannusryhmän mukaan painotetut VALMA&TELMA opiskelijavuodet %",
            "expression": "DIVIDE([Kustannusryhmän mukaan painotetut VALMA&TELMA opiskelijavuodet],CALCULATE([Kustannusryhmän mukaan painotetut VALMA&TELMA opiskelijavuodet],ALL(Muuttujat[Koulutuksen järjestäjä])))",
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Prosenttiosuudet"
          },
          {
            "name": "Kustannusryhmän mukaan painotetut opiskelijavalmiuksia tukevat opiskelijavuodet %",
            "expression": "DIVIDE([Kustannusryhmän mukaan painotetut opiskelijavalmiuksia tukevat opiskelijavuodet],CALCULATE([Kustannusryhmän mukaan painotetut opiskelijavalmiuksia tukevat opiskelijavuodet],ALL(Muuttujat[Koulutuksen järjestäjä])))",
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Prosenttiosuudet"
          },
          {
            "name": "Kustannusryhmän mukaan painotetut muun koulutuksen opiskelijavuodet %",
            "expression": "DIVIDE([Kustannusryhmän mukaan painotetut muun koulutuksen opiskelijavuodet],CALCULATE([Kustannusryhmän mukaan painotetut muun koulutuksen opiskelijavuodet],ALL(Muuttujat[Koulutuksen järjestäjä])))",
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Prosenttiosuudet"
          },
          {
            "name": "Erityistuen mukaan painotetut opiskelijavuodet %",
            "expression": "DIVIDE([Erityistuen mukaan painotetut opiskelijavuodet],CALCULATE([Erityistuen mukaan painotetut opiskelijavuodet],ALL(Muuttujat[Koulutuksen järjestäjä])))",
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Prosenttiosuudet"
          },
          {
            "name": "Majoituksen mukaan painotetut opiskelijavuodet %",
            "expression": "DIVIDE([Majoituksen mukaan painotetut opiskelijavuodet],CALCULATE([Majoituksen mukaan painotetut opiskelijavuodet],ALL(Muuttujat[Koulutuksen järjestäjä])))",
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Prosenttiosuudet"
          },
          {
            "name": "Henkilöstökoulutuksen mukaan painotetut opiskelijavuodet %",
            "expression": "DIVIDE([Henkilöstökoulutuksen mukaan painotetut opiskelijavuodet],CALCULATE([Henkilöstökoulutuksen mukaan painotetut opiskelijavuodet],ALL(Muuttujat[Koulutuksen järjestäjä])))",
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Prosenttiosuudet"
          },
          {
            "name": "Työvoimakoulutuksen mukaan painotetut opiskelijavuodet %",
            "expression": "DIVIDE([Työvoimakoulutuksen mukaan painotetut opiskelijavuodet],CALCULATE([Työvoimakoulutuksen mukaan painotetut opiskelijavuodet],ALL(Muuttujat[Koulutuksen järjestäjä])))",
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Prosenttiosuudet"
          },
          {
            "name": "Vankilakoulutuksen mukaan painotetut opiskelijavuodet %",
            "expression": "DIVIDE([Vankilakoulutuksen mukaan painotetut opiskelijavuodet],CALCULATE([Vankilakoulutuksen mukaan painotetut opiskelijavuodet],ALL(Muuttujat[Koulutuksen järjestäjä])))",
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Prosenttiosuudet"
          },
          {
            "name": "Painotetut opiskelijavuodet yhteensä %",
            "expression": "DIVIDE([Painotetut opiskelijavuodet yhteensä],CALCULATE([Painotetut opiskelijavuodet yhteensä],ALL(Muuttujat[Koulutuksen järjestäjä])))",
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Prosenttiosuudet"
          },
          {
            "name": "Painottamattomat opiskelijavuodet %",
            "expression": "[Painottamattomat opiskelijavuodet yhteensä]/CALCULATE([Painottamattomat opiskelijavuodet yhteensä],ALL(Muuttujat[Koulutuksen järjestäjä]))",
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Prosenttiosuudet"
          },
          {
            "name": "korotusehto",
            "expression": [
              " ",
              "IF(AND(",
              "\tIF(COUNTROWS(VALUES(Muuttujat[jarj_luvaton_korotustekija]))=1,IF(VALUES(Muuttujat[jarj_luvaton_korotustekija])=\"1\",1,0),1)",
              "\t,IF(COUNTROWS(VALUES(Muuttujat[jarj_luvaton_majoitus]))=1,IF(VALUES(Muuttujat[jarj_luvaton_majoitus])=\"1\",1,0),1)",
              "),1,0)"
            ],
            "formatString": "0",
            "displayFolder": "Opiskelijavuodet"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dw].[v_amos_opiskelijavuodet_uusi].* FROM [dw].[v_amos_opiskelijavuodet_uusi] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "v_amos_opiskelijavuodet_uusi"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dw"
          }
        ]
      }
    ],
    "perspectives": [
      {
        "name": "Rahoitus",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Erityisopetus"
              },
              {
                "name": "Hankintakoulutuksen järjestäjä"
              },
              {
                "name": "Hankintakoulutus"
              },
              {
                "name": "Henkilöstokoulutus"
              },
              {
                "name": "Hyväksytyt/hylätyt opiskelijavuodet"
              },
              {
                "name": "Ikä"
              },
              {
                "name": "Ikäryhmä"
              },
              {
                "name": "Koodit Hankintakoulutuksen järjestäjä"
              },
              {
                "name": "Koodit Koulutuksen järjestäjä"
              },
              {
                "name": "Koodit Oppilaitos"
              },
              {
                "name": "Koodit Osaamisala"
              },
              {
                "name": "Koodit Tutkinto"
              },
              {
                "name": "Koul. järjestäjän AVI"
              },
              {
                "name": "Koul. järjestäjän ELY"
              },
              {
                "name": "Koul. järjestäjän kunta"
              },
              {
                "name": "Koul. järjestäjän maakunta"
              },
              {
                "name": "Koulutuksen järjestäjä"
              },
              {
                "name": "Koulutusala, taso 1"
              },
              {
                "name": "Koulutusala, taso 2"
              },
              {
                "name": "Koulutusala, taso 3"
              },
              {
                "name": "Kustannusryhmä"
              },
              {
                "name": "Luvaton korotustekijä"
              },
              {
                "name": "Luvaton koulutus"
              },
              {
                "name": "Luvaton majoitus"
              },
              {
                "name": "Majoitus"
              },
              {
                "name": "Oppilaitoksen AVI"
              },
              {
                "name": "Oppilaitoksen ELY"
              },
              {
                "name": "Oppilaitoksen kunta"
              },
              {
                "name": "Oppilaitoksen maakunta"
              },
              {
                "name": "Oppilaitos"
              },
              {
                "name": "Oppisopimuskoulutus"
              },
              {
                "name": "Osa-aikaisuus"
              },
              {
                "name": "Osaamisala"
              },
              {
                "name": "Rahoitusmuoto"
              },
              {
                "name": "Sukupuoli"
              },
              {
                "name": "Suorituksen tyyppi"
              },
              {
                "name": "Tilastokuukausi"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Toimipiste"
              },
              {
                "name": "Tutkinto"
              },
              {
                "name": "Tutkintotyypin ryhmä"
              },
              {
                "name": "Tutkintotyyppi"
              },
              {
                "name": "Työvoimakoulutus"
              },
              {
                "name": "Vankilaopetus"
              },
              {
                "name": "Äidinkieli"
              }
            ],
            "measures": [
              {
                "name": "Erityistuen hyväksytyt painotetut opiskelijavuodet"
              },
              {
                "name": "Erityistuen mukaan painotetut opiskelijavuodet"
              },
              {
                "name": "Erityistuen mukaan painotetut opiskelijavuodet %"
              },
              {
                "name": "Henkilöstökoulutuksen mukaan painotetut opiskelijavuodet"
              },
              {
                "name": "Henkilöstökoulutuksen mukaan painotetut opiskelijavuodet %"
              },
              {
                "name": "Kustannusryhmän mukaan painotetut at- ja eat-tutkinnon opiskelijavuodet"
              },
              {
                "name": "Kustannusryhmän mukaan painotetut at- ja eat-tutkinnon opiskelijavuodet %"
              },
              {
                "name": "Kustannusryhmän mukaan painotetut muun koulutuksen opiskelijavuodet"
              },
              {
                "name": "Kustannusryhmän mukaan painotetut muun koulutuksen opiskelijavuodet %"
              },
              {
                "name": "Kustannusryhmän mukaan painotetut opiskelijavalmiuksia tukevat opiskelijavuodet"
              },
              {
                "name": "Kustannusryhmän mukaan painotetut opiskelijavalmiuksia tukevat opiskelijavuodet %"
              },
              {
                "name": "Kustannusryhmän mukaan painotetut perustutkinnon opiskelijavuodet"
              },
              {
                "name": "Kustannusryhmän mukaan painotetut perustutkinnon opiskelijavuodet %"
              },
              {
                "name": "Kustannusryhmän mukaan painotetut VALMA&TELMA opiskelijavuodet"
              },
              {
                "name": "Kustannusryhmän mukaan painotetut VALMA&TELMA opiskelijavuodet %"
              },
              {
                "name": "Majoituksen hyväksytyt painotetut opiskelijavuodet"
              },
              {
                "name": "Majoituksen mukaan painotetut opiskelijavuodet"
              },
              {
                "name": "Majoituksen mukaan painotetut opiskelijavuodet %"
              },
              {
                "name": "Muun koulutuksen painottamattomat opiskelijavuodet"
              },
              {
                "name": "Painotetut opiskelijavuodet yhteensä"
              },
              {
                "name": "Painotetut opiskelijavuodet yhteensä %"
              },
              {
                "name": "Painottamattomat opiskelijavuodet %"
              },
              {
                "name": "Painottamattomat opiskelijavuodet (pl. muu koulutus)"
              },
              {
                "name": "Painottamattomat opiskelijavuodet yhteensä"
              },
              {
                "name": "Profiilikerroin"
              },
              {
                "name": "Työvoimakoulutuksen mukaan painotetut opiskelijavuodet"
              },
              {
                "name": "Työvoimakoulutuksen mukaan painotetut opiskelijavuodet %"
              },
              {
                "name": "Vankilakoulutuksen mukaan painotetut opiskelijavuodet"
              },
              {
                "name": "Vankilakoulutuksen mukaan painotetut opiskelijavuodet %"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      }
    ],
    "roles": [
      {
        "name": "Luku",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "DWI\\P_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1733"
          },
          {
            "memberName": "DWI\\T_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1732"
          },
          {
            "memberName": "NT AUTHORITY\\IUSR",
            "memberId": "S-1-5-17"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "400"
      }
    ]
  },
  "id": "SemanticModel"
}