{
  "name": "SemanticModel",
  "compatibilityLevel": 1200,
  "model": {
    "culture": "fi-FI",
    "dataSources": [
      {
        "name": "SqlServer dwitvipusql22 ANTERO",
        "connectionString": "Provider=SQLOLEDB.1;Data Source=dwitvipusql22;Initial Catalog=ANTERO;Integrated Security=SSPI;Persist Security Info=false",
        "impersonationMode": "impersonateServiceAccount",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "Sarakeleveys",
        "isHidden": true,
        "columns": [
          {
            "name": "Sarakeleveys",
            "dataType": "string",
            "sourceColumn": "Sarakeleveys",
            "sourceProviderType": "Char"
          },
          {
            "name": "leveys",
            "dataType": "string",
            "sourceColumn": "leveys",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Sarakeleveys",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " \t\t\t\tSELECT [dw].[Sarakeleveys].*   FROM [dw].[Sarakeleveys] ",
              "dataSource": "SqlServer dwitvipusql22 ANTERO"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " \t\t\t\tSELECT [dw].[Sarakeleveys].*   FROM [dw].[Sarakeleveys] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Sarakeleveys"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dw"
          }
        ]
      },
      {
        "name": "Muuttujat",
        "columns": [
          {
            "name": "Koulutuksen järjestäjä",
            "dataType": "string",
            "sourceColumn": "Koulutuksen järjestäjä",
            "sourceProviderType": "WChar",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Koodit Koulutuksen järjestäjä",
            "dataType": "string",
            "sourceColumn": "Koodit Koulutuksen järjestäjä",
            "sourceProviderType": "Char",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Varainhoitovuosi",
            "dataType": "int64",
            "sourceColumn": "Varainhoitovuosi",
            "displayFolder": "Aikamuuttujat"
          },
          {
            "name": "Koulutuksen järjestäjän kunta",
            "dataType": "string",
            "sourceColumn": "Koulutuksen järjestäjän kunta",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Koulutuksen järjestäjän maakunta",
            "dataType": "string",
            "sourceColumn": "Koulutuksen järjestäjän maakunta",
            "sortByColumn": "jarj Koulutuksen järjestäjän maakunta",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "jarj Koulutuksen järjestäjän maakunta",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj Koulutuksen järjestäjän maakunta"
          },
          {
            "name": "Oppilaitos",
            "dataType": "string",
            "sourceColumn": "Oppilaitos",
            "sourceProviderType": "WChar",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Oppilaitoksen kunta",
            "dataType": "string",
            "sourceColumn": "Oppilaitoksen kunta",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Oppilaitoksen maakunta",
            "dataType": "string",
            "sourceColumn": "Oppilaitoksen maakunta",
            "sortByColumn": "jarj_oppilaitoksen_maakunta",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "jarj_oppilaitoksen_maakunta",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_oppilaitoksen_maakunta"
          },
          {
            "name": "Toimipiste",
            "dataType": "string",
            "sourceColumn": "Toimipiste",
            "sourceProviderType": "WChar",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Toimipisteen kunta",
            "dataType": "string",
            "sourceColumn": "Toimipisteen kunta",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Toimipisteen maakunta",
            "dataType": "string",
            "sourceColumn": "Toimipisteen maakunta",
            "sortByColumn": "jarjestys_toimipisteen_maakunta",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "jarjestys_toimipisteen_maakunta",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarjestys_toimipisteen_maakunta"
          },
          {
            "name": "Rahoituskausi (palautteet)",
            "dataType": "string",
            "sourceColumn": "Rahoituskausi (palautteet)",
            "displayFolder": "Aikamuuttujat"
          },
          {
            "name": "Kysely",
            "dataType": "string",
            "sourceColumn": "Kysely",
            "displayFolder": "Kyselymuuttujat"
          },
          {
            "name": "Kyselyn kohderyhmä",
            "dataType": "string",
            "sourceColumn": "Kyselyn kohderyhmä",
            "displayFolder": "Kyselymuuttujat"
          },
          {
            "name": "apusarake_pisteet",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "apusarake_pisteet"
          },
          {
            "name": "apusarake_painotetut_pisteet",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "apusarake_painotetut_pisteet"
          },
          {
            "name": "apusarake_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "apusarake_lkm"
          },
          {
            "name": "Korkeakouluopiskelija",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Korkeakouluopiskelija"
          },
          {
            "name": "Työllinen",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Työllinen"
          },
          {
            "name": "Kokonaisuus",
            "dataType": "string",
            "sourceColumn": "Kokonaisuus",
            "displayFolder": "Rahoitusmallimuuttujat"
          },
          {
            "name": "Suorituksen tyyppi",
            "dataType": "string",
            "sourceColumn": "Suorituksen tyyppi",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Ikä (maksuttomuusraja)",
            "dataType": "string",
            "sourceColumn": "Ikä (maksuttomuusraja)",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Ikäryhmä",
            "dataType": "string",
            "sourceColumn": "Ikäryhmä",
            "sortByColumn": "jarj_ikaryhma",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "jarj_ikaryhma",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarj_ikaryhma"
          },
          {
            "name": "Äidinkieli (ryhmä)",
            "dataType": "string",
            "sourceColumn": "Äidinkieli (ryhmä)",
            "sortByColumn": "jarj_aidinkieli_ryhma",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "jarj_aidinkieli_ryhma",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarj_aidinkieli_ryhma"
          },
          {
            "name": "Maksuttomuus (simulointi)",
            "dataType": "string",
            "sourceColumn": "Maksuttomuus (simulointi)",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Majoitus",
            "dataType": "string",
            "sourceColumn": "Majoitus",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Vaativa erityinen tuki",
            "dataType": "string",
            "sourceColumn": "Vaativa erityinen tuki",
            "sortByColumn": "jarjestys Vaativa erityinen tuki",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Kustannusryhmä",
            "dataType": "string",
            "sourceColumn": "Kustannusryhmä",
            "sortByColumn": "jarj_kustannusryhma",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "jarj_kustannusryhma",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarj_kustannusryhma"
          },
          {
            "name": "Tutkintotyyppi",
            "dataType": "string",
            "sourceColumn": "Tutkintotyyppi",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Tutkintotyyppi (rahoitus)",
            "dataType": "string",
            "sourceColumn": "Tutkintotyyppi (rahoitus)",
            "sortByColumn": "jarjestys Tutkintotyyppi (rahoitus)",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Tutkinto",
            "dataType": "string",
            "sourceColumn": "Tutkinto",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koodit Tutkinto",
            "dataType": "int64",
            "sourceColumn": "Koodit Tutkinto",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koulutusala, taso 1",
            "dataType": "string",
            "sourceColumn": "Koulutusala, taso 1",
            "sortByColumn": "jarj_koulutusala_taso1",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "jarj_koulutusala_taso1",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_koulutusala_taso1"
          },
          {
            "name": "Koulutusala, taso 2",
            "dataType": "string",
            "sourceColumn": "Koulutusala, taso 2",
            "sortByColumn": "jarj_koulutusala_taso2",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "jarj_koulutusala_taso2",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_koulutusala_taso2"
          },
          {
            "name": "Koulutusala, taso 3",
            "dataType": "string",
            "sourceColumn": "Koulutusala, taso 3",
            "sortByColumn": "jarj_koulutusala_taso3",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "jarj_koulutusala_taso3",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_koulutusala_taso3"
          },
          {
            "name": "Rahoitusmuoto",
            "dataType": "string",
            "sourceColumn": "Rahoitusmuoto",
            "sortByColumn": "jarj_rahoitusmuoto",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "jarj_rahoitusmuoto",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarj_rahoitusmuoto"
          },
          {
            "name": "Ei maksuttomien opiskelijavuosien enimmäismäärä",
            "dataType": "string",
            "sourceColumn": "Ei maksuttomien opiskelijavuosien enimmäismäärä",
            "formatString": "#,0",
            "sortByColumn": "jarjestys Ei maksuttomien opiskelijavuosien enimmäismäärä",
            "displayFolder": "Järjestämislupamuuttujat"
          },
          {
            "name": "Vaativan erityisen tuen opiskelijavuosien enimmäismäärä",
            "dataType": "string",
            "sourceColumn": "Vaativan erityisen tuen opiskelijavuosien enimmäismäärä",
            "formatString": "#,0",
            "sortByColumn": "jarjestys Vaativan erityisen tuen opiskelijavuosien enimmäismäärä",
            "displayFolder": "Järjestämislupamuuttujat"
          },
          {
            "name": "Luvaton koulutus",
            "dataType": "string",
            "sourceColumn": "Luvaton koulutus",
            "sortByColumn": "jarj_luvaton_koulutus",
            "displayFolder": "Järjestämislupamuuttujat"
          },
          {
            "name": "Luvaton majoitus",
            "dataType": "string",
            "sourceColumn": "Luvaton majoitus",
            "sortByColumn": "jarj_luvaton_majoitus",
            "displayFolder": "Järjestämislupamuuttujat"
          },
          {
            "name": "Luvaton korotustekijä",
            "dataType": "string",
            "sourceColumn": "Luvaton korotustekijä",
            "sortByColumn": "jarj_luvaton_korotustekija",
            "displayFolder": "Järjestämislupamuuttujat"
          },
          {
            "name": "Luvanmukainen suorituskieli",
            "dataType": "string",
            "sourceColumn": "Luvanmukainen suorituskieli",
            "sortByColumn": "jarj_suorituskieli_luvanmukainen",
            "displayFolder": "Järjestämislupamuuttujat"
          },
          {
            "name": "jarj_luvaton_koulutus",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarj_luvaton_koulutus"
          },
          {
            "name": "jarj_luvaton_majoitus",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarj_luvaton_majoitus"
          },
          {
            "name": "jarj_luvaton_korotustekija",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarj_luvaton_korotustekija"
          },
          {
            "name": "jarj_suorituskieli_luvanmukainen",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarj_suorituskieli_luvanmukainen"
          },
          {
            "name": "apusarake_opiskelijavuodet_painottamaton",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "apusarake_opiskelijavuodet_painottamaton"
          },
          {
            "name": "apusarake_opv_ei_maksuton_kerroin",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "apusarake_opv_ei_maksuton_kerroin"
          },
          {
            "name": "Hyväksytyt/hylätyt opiskelijavuodet",
            "dataType": "string",
            "sourceColumn": "Hyväksytyt/hylätyt opiskelijavuodet",
            "sortByColumn": "jarj Hyväksytyt/hylätyt opiskelijavuodet",
            "displayFolder": "Rahoitusmallimuuttujat"
          },
          {
            "name": "jarj Hyväksytyt/hylätyt opiskelijavuodet",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarj Hyväksytyt/hylätyt opiskelijavuodet"
          },
          {
            "name": "Rahoitusmuoto hyväksytään",
            "dataType": "string",
            "sourceColumn": "Rahoitusmuoto hyväksytään",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "apusarake_painottamaton_tutkinnot",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "apusarake_painottamaton_tutkinnot"
          },
          {
            "name": "apusarake_painottamaton_osaamispisteet",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "apusarake_painottamaton_osaamispisteet"
          },
          {
            "name": "apusarake_osaamispisteet_kerroin",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "apusarake_osaamispisteet_kerroin"
          },
          {
            "name": "apusarake_painotettu_tutkinnot",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "apusarake_painotettu_tutkinnot"
          },
          {
            "name": "apusarake_laskennallinen_rahoitus_rajoitekerroin",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "apusarake_laskennallinen_rahoitus_rajoitekerroin"
          },
          {
            "name": "Toteuma/Estimaatti",
            "dataType": "string",
            "sourceColumn": "Toteuma/Estimaatti",
            "displayFolder": "Rahoitusmallimuuttujat"
          },
          {
            "name": "apusarake_laskennallinen_rahoitus_osuus_ed_v",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "apusarake_laskennallinen_rahoitus_osuus_ed_v"
          },
          {
            "name": "Koul. järjestäjän PILKE-alue (kokeilu)",
            "dataType": "string",
            "sourceColumn": "Koul. järjestäjän PILKE-alue (kokeilu)",
            "sortByColumn": "jarjestys Koul. järjestäjän PILKE-alue (kokeilu)",
            "sourceProviderType": "Char",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "jarjestys Koul. järjestäjän PILKE-alue (kokeilu)",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarjestys Koul. järjestäjän PILKE-alue (kokeilu)"
          },
          {
            "name": "Tilastovuosi",
            "dataType": "string",
            "sourceColumn": "Tilastovuosi",
            "displayFolder": "Aikamuuttujat"
          },
          {
            "name": "Työvoimakoulutus",
            "dataType": "string",
            "sourceColumn": "Työvoimakoulutus",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Hankintakoulutus",
            "dataType": "string",
            "sourceColumn": "Hankintakoulutus",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Oppisopimuskoulutus",
            "dataType": "string",
            "sourceColumn": "Oppisopimuskoulutus",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Vankilaopetus",
            "dataType": "string",
            "sourceColumn": "Vankilaopetus",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Sukupuoli",
            "dataType": "string",
            "sourceColumn": "Sukupuoli",
            "sortByColumn": "jarj_sukupuoli",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "jarj_sukupuoli",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarj_sukupuoli"
          },
          {
            "name": "Suorituskieli",
            "dataType": "string",
            "sourceColumn": "Suorituskieli",
            "sortByColumn": "jarj_suorituskieli",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "jarj_suorituskieli",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_suorituskieli"
          },
          {
            "name": "Hankintakoulutuksen järjestäjä",
            "dataType": "string",
            "sourceColumn": "Hankintakoulutuksen järjestäjä",
            "sourceProviderType": "WChar",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "apusarake_laskennallinen_rahoitus_osuus",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "apusarake_laskennallinen_rahoitus_osuus"
          },
          {
            "name": "Koodit Hankintakoulutuksen järjestäjä",
            "dataType": "string",
            "sourceColumn": "Koodit Hankintakoulutuksen järjestäjä",
            "sourceProviderType": "Char",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Ikä 20/alle/yli",
            "dataType": "string",
            "sourceColumn": "Ikä 20/alle/yli",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "jarjestys Vaativa erityinen tuki",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarjestys Vaativa erityinen tuki"
          },
          {
            "name": "jarjestys Ei maksuttomien opiskelijavuosien enimmäismäärä",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarjestys Ei maksuttomien opiskelijavuosien enimmäismäärä"
          },
          {
            "name": "jarjestys Vaativan erityisen tuen opiskelijavuosien enimmäismäärä",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarjestys Vaativan erityisen tuen opiskelijavuosien enimmäismäärä"
          },
          {
            "name": "jarjestys Tutkintotyyppi (rahoitus)",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarjestys Tutkintotyyppi (rahoitus)"
          },
          {
            "name": "Rahoituskausi (pl. palautteet)",
            "dataType": "string",
            "sourceColumn": "Rahoituskausi (pl. palautteet)",
            "displayFolder": "Aikamuuttujat"
          },
          {
            "name": "suppea_sisalto_1_0",
            "dataType": "double",
            "sourceColumn": "suppea_sisalto_1_0"
          },
          {
            "name": "laaja_sisalto_1_0",
            "dataType": "double",
            "sourceColumn": "laaja_sisalto_1_0"
          },
          {
            "name": "Järjestäjärakenne",
            "dataType": "string",
            "sourceColumn": "Järjestäjärakenne",
            "sourceProviderType": "Char",
            "displayFolder": "Rahoitusmallimuuttujat"
          },
          {
            "name": "Maksuttomuus (rahoitus)",
            "dataType": "string",
            "sourceColumn": "Maksuttomuus (rahoitus)",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "apusarake_opiskelijavuodet_painotettu_lahtotaso",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "apusarake_opiskelijavuodet_painotettu_lahtotaso"
          },
          {
            "name": "apusarake_opiskelijavuodet_painotettu_kustannusryhma",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "apusarake_opiskelijavuodet_painotettu_kustannusryhma"
          },
          {
            "name": "apusarake_opiskelijavuodet_painotettu_erityistuki",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "apusarake_opiskelijavuodet_painotettu_erityistuki"
          },
          {
            "name": "apusarake_opiskelijavuodet_painotettu_majoitus",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "apusarake_opiskelijavuodet_painotettu_majoitus"
          },
          {
            "name": "Toiminnanohjauksen kokeilu",
            "dataType": "string",
            "sourceColumn": "Toiminnanohjauksen kokeilu",
            "sortByColumn": "jarjestys Toiminnanohjauksen kokeilu",
            "sourceProviderType": "Char",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "jarjestys Toiminnanohjauksen kokeilu",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarjestys Toiminnanohjauksen kokeilu",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Tilastokausi",
            "dataType": "string",
            "sourceColumn": "Tilastokausi",
            "displayFolder": "Aikamuuttujat"
          }
        ],
        "partitions": [
          {
            "name": "0",
            "source": {
              "type": "query",
              "query": " SELECT * FROM [dw].[v_amos_koonti_2027] ",
              "dataSource": "SqlServer dwitvipusql22 ANTERO"
            }
          },
          {
            "name": "1",
            "source": {
              "type": "query",
              "query": " SELECT * FROM [dw].[v_amos_koonti_2026] ",
              "dataSource": "SqlServer dwitvipusql22 ANTERO"
            }
          }
        ],
        "measures": [
          {
            "name": "painottamattomat_pisteet_yhteensa",
            "expression": "SUM(Muuttujat[apusarake_pisteet])",
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "Työllistyminen ja jatko-opintoihin siirtyminen"
          },
          {
            "name": "painotetut_pisteet_yhteensa",
            "expression": "SUM(Muuttujat[apusarake_painotetut_pisteet])",
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "Työllistyminen ja jatko-opintoihin siirtyminen"
          },
          {
            "name": "Opiskelunsa aloittaneiden palautteen pisteet, lkm",
            "expression": [
              "",
              "var lkm = CALCULATE([painottamattomat_pisteet_yhteensa], FILTER(VALUES(Muuttujat[Kysely]), Muuttujat[Kysely]=\"Aloituskysely\"))",
              "return IF(lkm > 0, lkm)"
            ],
            "formatString": "#,0",
            "displayFolder": "Opiskelijapalaute"
          },
          {
            "name": "Opiskelunsa aloittaneiden palautteen painotetut pisteet, lkm",
            "expression": [
              "",
              "var lkm = CALCULATE([painotetut_pisteet_yhteensa], FILTER(VALUES(Muuttujat[Kysely]), Muuttujat[Kysely]=\"Aloituskysely\"))",
              "return IF(lkm > 0, lkm)"
            ],
            "formatString": "#,0",
            "displayFolder": "Opiskelijapalaute"
          },
          {
            "name": "Opiskelunsa aloittaneiden palautteen painotetut pisteet, lkm, järjestäjien %-osuus",
            "expression": [
              "",
              "var osa = [Opiskelunsa aloittaneiden palautteen painotetut pisteet, lkm]",
              "var kaikki = CALCULATE(",
              "\t[Opiskelunsa aloittaneiden palautteen painotetut pisteet, lkm]",
              "\t, ALL(Muuttujat[Koulutuksen järjestäjä])",
              "\t, ALL(Muuttujat[Koodit Koulutuksen järjestäjä])",
              ")",
              "return DIVIDE(osa, kaikki)"
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %",
            "displayFolder": "Opiskelijapalaute"
          },
          {
            "name": "Opiskelunsa päättäneiden palautteen pisteet, lkm",
            "expression": [
              "",
              "var lkm = CALCULATE([painottamattomat_pisteet_yhteensa], FILTER(VALUES(Muuttujat[Kysely]), Muuttujat[Kysely]=\"Päättökysely\"))",
              "return IF(lkm > 0, lkm)"
            ],
            "formatString": "#,0",
            "displayFolder": "Opiskelijapalaute"
          },
          {
            "name": "Opiskelunsa päättäneiden palautteen painotetut pisteet, lkm",
            "expression": [
              "",
              "var p1 = 3 * CALCULATE([painotetut_pisteet_yhteensa], FILTER(VALUES(Muuttujat[Kyselyn kohderyhmä]), Muuttujat[Kyselyn kohderyhmä]=\"Koko tutkinnon suorittaneet\"))",
              "var p2 = CALCULATE([painotetut_pisteet_yhteensa], FILTER(VALUES(Muuttujat[Kyselyn kohderyhmä]), Muuttujat[Kyselyn kohderyhmä]=\"Tutkinnon osia suorittaneet\"))",
              "var lkm = p1+p2",
              "return IF(lkm > 0, lkm)"
            ],
            "formatString": "#,0",
            "displayFolder": "Opiskelijapalaute"
          },
          {
            "name": "Opiskelunsa päättäneiden palautteen painotetut pisteet, lkm, järjestäjien %-osuus",
            "expression": [
              "",
              "var osa = [Opiskelunsa päättäneiden palautteen painotetut pisteet, lkm]",
              "var kaikki = CALCULATE(",
              "\t[Opiskelunsa päättäneiden palautteen painotetut pisteet, lkm]",
              "\t, ALL(Muuttujat[Koulutuksen järjestäjä])",
              "\t, ALL(Muuttujat[Koodit Koulutuksen järjestäjä])",
              ")",
              "return DIVIDE(osa, kaikki)"
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %",
            "displayFolder": "Opiskelijapalaute"
          },
          {
            "name": "Työpaikkaohjaajakyselyn pisteet, lkm",
            "expression": [
              "",
              "var lkm = CALCULATE([painottamattomat_pisteet_yhteensa], Muuttujat[Kysely]=\"Työpaikkaohjaajakysely\")",
              "return IF(lkm > 0, lkm)"
            ],
            "formatString": "#,0",
            "displayFolder": "Työelämäpalaute"
          },
          {
            "name": "Työpaikkakyselyn pisteet, lkm",
            "expression": [
              "",
              "var lkm = CALCULATE([painottamattomat_pisteet_yhteensa], Muuttujat[Kysely]=\"Työpaikkakysely\")",
              "return IF(lkm > 0, lkm)"
            ],
            "formatString": "#,0",
            "displayFolder": "Työelämäpalaute"
          },
          {
            "name": "Työpaikkaohjaajakyselyn painotetut pisteet, lkm",
            "expression": [
              "",
              "var lkm = CALCULATE([painotetut_pisteet_yhteensa], Muuttujat[Kysely]=\"Työpaikkaohjaajakysely\")",
              "return IF(lkm > 0, lkm)"
            ],
            "formatString": "#,0",
            "displayFolder": "Työelämäpalaute"
          },
          {
            "name": "Työpaikkaohjaajakyselyn painotetut pisteet, lkm, järjestäjien %-osuus",
            "expression": [
              "",
              "var osa = [Työpaikkaohjaajakyselyn painotetut pisteet, lkm]",
              "var kaikki = CALCULATE(",
              "\t[Työpaikkaohjaajakyselyn painotetut pisteet, lkm]",
              "\t, ALL(Muuttujat[Koulutuksen järjestäjä])",
              "\t, ALL(Muuttujat[Koodit Koulutuksen järjestäjä])",
              ")",
              "return DIVIDE(osa, kaikki)"
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %",
            "displayFolder": "Työelämäpalaute"
          },
          {
            "name": "Työpaikkakyselyn pisteet, lkm, järjestäjien %-osuus",
            "expression": [
              "",
              "var osa = [Työpaikkakyselyn pisteet, lkm]",
              "var kaikki = CALCULATE(",
              "\t[Työpaikkakyselyn pisteet, lkm]",
              "\t, ALL(Muuttujat[Koulutuksen järjestäjä])",
              "\t, ALL(Muuttujat[Koodit Koulutuksen järjestäjä])",
              ")",
              "return DIVIDE(osa, kaikki)"
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %",
            "displayFolder": "Työelämäpalaute"
          },
          {
            "name": "Koulutuksen suorittaneet",
            "expression": [
              " --jo näkymässä vain ennen koulutusta ei. työll.",
              "",
              "var ehto_s = SELECTEDVALUE(Muuttujat[suppea_sisalto_1_0]) == 1",
              "var ehto = SELECTEDVALUE(Muuttujat[laaja_sisalto_1_0]) == 1",
              "",
              "var lkm_raaka = SUM(Muuttujat[apusarake_lkm])",
              "var lkm_s = IF(lkm_raaka = 0, BLANK(), lkm_raaka)",
              "var lkm = IF(lkm_raaka = 0, BLANK(), IF(lkm_raaka < 5, 2.5, MROUND(lkm_raaka, 3)))",
              "",
              "return IF(ehto_s, lkm_s, IF(ehto, lkm, BLANK()))"
            ],
            "formatString": "#,0.0",
            "isHidden": true,
            "displayFolder": "Työllistyminen ja jatko-opintoihin siirtyminen"
          },
          {
            "name": "Tutkinnot yhteensä",
            "expression": [
              "",
              "CALCULATE([Koulutuksen suorittaneet], FILTER(VALUES(Muuttujat[Suorituksen tyyppi]), Muuttujat[Suorituksen tyyppi]=\"Koko tutkinto\"))"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "Työllistyminen ja jatko-opintoihin siirtyminen"
          },
          {
            "name": "Tutkinnon osat yhteensä",
            "expression": [
              "",
              "CALCULATE([Koulutuksen suorittaneet], FILTER(VALUES(Muuttujat[Suorituksen tyyppi]), Muuttujat[Suorituksen tyyppi]=\"Tutkinnon osa/osia\"))"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "Työllistyminen ja jatko-opintoihin siirtyminen"
          },
          {
            "name": "Tutkinnon suorittaneet (ei työll. ennen koul.) työllistyneet, lkm",
            "expression": [
              "",
              "CALCULATE(",
              "\t[Tutkinnot yhteensä]",
              "\t--, FILTER(VALUES(Muuttujat[Korkeakouluopiskelija]), Muuttujat[Korkeakouluopiskelija]<>\"Korkeakouluopiskelija\")",
              "\t, FILTER(VALUES(Muuttujat[Työllinen]), Muuttujat[Työllinen]=\"Työllinen\")",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Työllistyminen ja jatko-opintoihin siirtyminen"
          },
          {
            "name": "Tutkinnon suorittaneet (ei työll. ennen koul.) jatko-opiskelijat, lkm",
            "expression": [
              "",
              "CALCULATE(",
              "\t[Tutkinnot yhteensä]",
              "\t, FILTER(VALUES(Muuttujat[Korkeakouluopiskelija]), Muuttujat[Korkeakouluopiskelija]=\"Korkeakouluopiskelija\")",
              "\t, FILTER(VALUES(Muuttujat[Työllinen]), Muuttujat[Työllinen]<>\"Työllinen\")",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Työllistyminen ja jatko-opintoihin siirtyminen"
          },
          {
            "name": "Tutkinnon osia suorittaneet (ei työll. ennen koul.) työllistyneet, lkm",
            "expression": [
              "",
              "CALCULATE(",
              "\t[Tutkinnon osat yhteensä]",
              "\t--, FILTER(VALUES(Muuttujat[Korkeakouluopiskelija]), Muuttujat[Korkeakouluopiskelija]<>\"Korkeakouluopiskelija\")",
              "\t, FILTER(VALUES(Muuttujat[Työllinen]), Muuttujat[Työllinen]=\"Työllinen\")",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Työllistyminen ja jatko-opintoihin siirtyminen"
          },
          {
            "name": "Tutkinnon osia suorittaneet (ei työll. ennen koul.) jatko-opiskelijat, lkm",
            "expression": [
              "",
              "CALCULATE(",
              "\t[Tutkinnon osat yhteensä]",
              "\t, FILTER(VALUES(Muuttujat[Korkeakouluopiskelija]), Muuttujat[Korkeakouluopiskelija]=\"Korkeakouluopiskelija\")",
              "\t, FILTER(VALUES(Muuttujat[Työllinen]), Muuttujat[Työllinen]<>\"Työllinen\")",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Työllistyminen ja jatko-opintoihin siirtyminen"
          },
          {
            "name": "Tutk. ja osia suor. (ei työll. ennen koul.) työllistyneet ja jatko-opiskelijat, lkm",
            "expression": [
              "",
              "CALCULATE(",
              "\t[Koulutuksen suorittaneet]",
              "\t, FILTER(",
              "\t\tGROUPBY(Muuttujat, [Korkeakouluopiskelija], [Työllinen])",
              "\t\t, Muuttujat[Korkeakouluopiskelija]=\"Korkeakouluopiskelija\" || Muuttujat[Työllinen]=\"Työllinen\"",
              "\t)",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Työllistyminen ja jatko-opintoihin siirtyminen"
          },
          {
            "name": "Tutkinnon suorittaneet (ei työll. ennen koul.) työllistyneet, ka",
            "expression": [
              "",
              "DIVIDE([Tutkinnon suorittaneet (ei työll. ennen koul.) työllistyneet, lkm], [kausien_lkm])"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Työllistyminen ja jatko-opintoihin siirtyminen"
          },
          {
            "name": "Tutkinnon suorittaneet (ei työll. ennen koul.) jatko-opiskelijat, ka",
            "expression": [
              "",
              "DIVIDE([Tutkinnon suorittaneet (ei työll. ennen koul.) jatko-opiskelijat, lkm], [kausien_lkm])"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Työllistyminen ja jatko-opintoihin siirtyminen"
          },
          {
            "name": "Tutkinnon osia suorittaneet (ei työll. ennen koul.) työllistyneet, ka",
            "expression": [
              "",
              "DIVIDE([Tutkinnon osia suorittaneet (ei työll. ennen koul.) työllistyneet, lkm], [kausien_lkm])"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Työllistyminen ja jatko-opintoihin siirtyminen"
          },
          {
            "name": "Tutkinnon osia suorittaneet (ei työll. ennen koul.) jatko-opiskelijat, ka",
            "expression": [
              "",
              "DIVIDE([Tutkinnon osia suorittaneet (ei työll. ennen koul.) jatko-opiskelijat, lkm], [kausien_lkm])"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Työllistyminen ja jatko-opintoihin siirtyminen"
          },
          {
            "name": "Tutk. ja osia suor. (ei työll. ennen koul.) työllistyneet ja jatko-opiskelijat, ka",
            "expression": [
              "",
              "DIVIDE([Tutk. ja osia suor. (ei työll. ennen koul.) työllistyneet ja jatko-opiskelijat, lkm], [kausien_lkm])",
              ""
            ],
            "formatString": "#,0.0",
            "displayFolder": "Työllistyminen ja jatko-opintoihin siirtyminen"
          },
          {
            "name": "Tutk. ja osia suor. (ei työll. ennen koul.) työllistyneet ja jatko-opiskelijat, ka, järj. %-osuus",
            "expression": [
              "",
              "var osa = [Tutk. ja osia suor. (ei työll. ennen koul.) työllistyneet ja jatko-opiskelijat, ka]",
              "var kaikki = CALCULATE(",
              "\t[Tutk. ja osia suor. (ei työll. ennen koul.) työllistyneet ja jatko-opiskelijat, ka]",
              "\t, ALL(Muuttujat[Koulutuksen järjestäjä])",
              "\t, ALL(Muuttujat[Koodit Koulutuksen järjestäjä])",
              ")",
              "return DIVIDE(osa, kaikki)"
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %",
            "displayFolder": "Työllistyminen ja jatko-opintoihin siirtyminen"
          },
          {
            "name": "Rahoitusosioiden osuuksilla painotetut järjestäjien osuudet yhteensä, järjestäjien %-osuus",
            "expression": [
              "",
              "0.50 * (",
              "\t0.80 * [Painotetut rahoituksen perusteena olevat opv (kust.ryhmä, tutk.tyyppi, korotukset), ka, järj.-%]",
              "\t+ 0.20 * [Painotetut rahoituksen perusteena olevat opiskelijavuodet (lähtötaso), ka, järj.-%]",
              ")",
              "+ 0.30 * [Tutkintojen painotetut pisteet ja laskentaan hyväksytyt osaamispisteet yhteensä, ka, järj. %-osuus]",
              "+ 0.18 * [Tutk. ja osia suor. (ei työll. ennen koul.) työllistyneet ja jatko-opiskelijat, ka, järj. %-osuus]",
              "+ 0.01 * (",
              "\t0.25 * [Opiskelunsa aloittaneiden palautteen painotetut pisteet, lkm, järjestäjien %-osuus] ",
              "\t+ 0.75 * [Opiskelunsa päättäneiden palautteen painotetut pisteet, lkm, järjestäjien %-osuus]",
              ")",
              "+ 0.01 * (",
              "\t0.25 * [Työpaikkakyselyn pisteet, lkm, järjestäjien %-osuus] ",
              "\t+ 0.75 * [Työpaikkaohjaajakyselyn painotetut pisteet, lkm, järjestäjien %-osuus]",
              ")"
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %",
            "displayFolder": "Kokonaisrahoitus"
          },
          {
            "name": "Painottamattomat opiskelijavuodet ilman enimmäismäärärajausta, ei maksuton, lkm",
            "expression": [
              "",
              "CALCULATE([Painottamattomat opiskelijavuodet ilman enimmäismäärärajausta, lkm], FILTER(VALUES(Muuttujat[Maksuttomuus (rahoitus)]), Muuttujat[Maksuttomuus (rahoitus)]=\"Ei maksuton (rahoitus)\"))"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Opiskelijavuodet\\Painottamaton"
          },
          {
            "name": "Painottamattomat enimmäismäärän mukaiset opiskelijavuodet, ei maksuton, lkm",
            "expression": [
              "",
              "CALCULATE(",
              "\t[Painottamattomat enimmäismäärän mukaiset opiskelijavuodet, lkm]",
              "\t,FILTER(VALUES(Muuttujat[Maksuttomuus (rahoitus)]), Muuttujat[Maksuttomuus (rahoitus)]=\"Ei maksuton (rahoitus)\")",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Opiskelijavuodet\\Painottamaton"
          },
          {
            "name": "Painottamattomat opiskelijavuodet ilman enimmäismäärärajausta, ka",
            "expression": [
              "",
              "DIVIDE([Painottamattomat opiskelijavuodet ilman enimmäismäärärajausta, lkm], [kausien_lkm])"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Opiskelijavuodet\\Painottamaton"
          },
          {
            "name": "Painottamattomat enimmäismäärän mukaiset opiskelijavuodet, ei maksuton, ka",
            "expression": [
              "",
              "DIVIDE([Painottamattomat enimmäismäärän mukaiset opiskelijavuodet, ei maksuton, lkm], [kausien_lkm])"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Opiskelijavuodet\\Painottamaton"
          },
          {
            "name": "Painotetut opiskelijavuodet (kust.ryhmä, tutk.tyyppi, korotukset), lkm",
            "expression": [
              "",
              "var summa = CALCULATE(SUM(Muuttujat[apusarake_opiskelijavuodet_painotettu_kustannusryhma]))",
              "\t+ CALCULATE(SUM(Muuttujat[apusarake_opiskelijavuodet_painotettu_erityistuki]))",
              "\t+ CALCULATE(SUM(Muuttujat[apusarake_opiskelijavuodet_painotettu_majoitus]))",
              "return IF(summa=0, BLANK(), summa)"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Opiskelijavuodet\\Painotettu (kust.ryhmä, tutk.tyyppi, korotukset)"
          },
          {
            "name": "Painotetut rahoituksen perusteena olevat opiskelijavuodet (kust.ryhmä, tutk.tyyppi, korotukset), lkm",
            "expression": [
              "",
              "var summa = CALCULATE(SUMX(Muuttujat, [apusarake_opv_ei_maksuton_kerroin] * [apusarake_opiskelijavuodet_painotettu_kustannusryhma]))",
              "\t+ CALCULATE(SUMX(Muuttujat, [apusarake_opv_ei_maksuton_kerroin] * [apusarake_opiskelijavuodet_painotettu_erityistuki]))",
              "\t+ CALCULATE(SUMX(Muuttujat, [apusarake_opv_ei_maksuton_kerroin] * [apusarake_opiskelijavuodet_painotettu_majoitus]))",
              "return IF(summa=0, BLANK(), summa)"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Opiskelijavuodet\\Painotettu (kust.ryhmä, tutk.tyyppi, korotukset)"
          },
          {
            "name": "Painotetut opiskelijavuodet (kust.ryhmä, tutk.tyyppi, korotukset), ka",
            "expression": [
              "",
              "DIVIDE([Painotetut opiskelijavuodet (kust.ryhmä, tutk.tyyppi, korotukset), lkm], [kausien_lkm])"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Opiskelijavuodet\\Painotettu (kust.ryhmä, tutk.tyyppi, korotukset)"
          },
          {
            "name": "Painotetut rahoituksen perusteena olevat opiskelijavuodet (kust.ryhmä, tutk.tyyppi, korotukset), ka",
            "expression": [
              "",
              "DIVIDE([Painotetut rahoituksen perusteena olevat opiskelijavuodet (kust.ryhmä, tutk.tyyppi, korotukset), lkm], [kausien_lkm])"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Opiskelijavuodet\\Painotettu (kust.ryhmä, tutk.tyyppi, korotukset)"
          },
          {
            "name": "Painotetut opiskelijavuodet (lähtötaso), lkm",
            "expression": [
              "",
              "var summa = CALCULATE(SUM(Muuttujat[apusarake_opiskelijavuodet_painotettu_lahtotaso]))",
              "return IF(summa=0, BLANK(), summa)"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Opiskelijavuodet\\Painotettu (lähtötaso)"
          },
          {
            "name": "Painotetut rahoituksen perusteena olevat opiskelijavuodet (lähtötaso), lkm",
            "expression": [
              "",
              "var summa = CALCULATE(SUMX(Muuttujat, [apusarake_opv_ei_maksuton_kerroin] * [apusarake_opiskelijavuodet_painotettu_lahtotaso]))",
              "return IF(summa=0, BLANK(), summa)"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Opiskelijavuodet\\Painotettu (lähtötaso)"
          },
          {
            "name": "Painotetut opiskelijavuodet (lähtötaso), ka",
            "expression": [
              "",
              "DIVIDE([Painotetut opiskelijavuodet (lähtötaso), lkm], [kausien_lkm])"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Opiskelijavuodet\\Painotettu (lähtötaso)"
          },
          {
            "name": "Painotetut rahoituksen perusteena olevat opiskelijavuodet (lähtötaso), ka",
            "expression": [
              "",
              "DIVIDE([Painotetut rahoituksen perusteena olevat opiskelijavuodet (lähtötaso), lkm], [kausien_lkm])"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Opiskelijavuodet\\Painotettu (lähtötaso)"
          },
          {
            "name": "Painotetut rahoituksen perusteena olevat opv (kust.ryhmä, tutk.tyyppi, korotukset), ka, järj.-%",
            "expression": [
              " --pidempi cultures-selite opv osalta",
              "var osa = [Painotetut rahoituksen perusteena olevat opiskelijavuodet (kust.ryhmä, tutk.tyyppi, korotukset), ka]",
              "var kaikki = CALCULATE(",
              "\t[Painotetut rahoituksen perusteena olevat opiskelijavuodet (kust.ryhmä, tutk.tyyppi, korotukset), ka]",
              "\t, ALL(Muuttujat[Koulutuksen järjestäjä])",
              "\t, ALL(Muuttujat[Koodit Koulutuksen järjestäjä])",
              ")",
              "return DIVIDE(osa, kaikki)"
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %",
            "displayFolder": "Opiskelijavuodet\\Painotettu (kust.ryhmä, tutk.tyyppi, korotukset)"
          },
          {
            "name": "Painotetut rahoituksen perusteena olevat opiskelijavuodet (lähtötaso), ka, järj.-%",
            "expression": [
              "",
              "var osa = [Painotetut rahoituksen perusteena olevat opiskelijavuodet (lähtötaso), ka]",
              "var kaikki = CALCULATE(",
              "\t[Painotetut rahoituksen perusteena olevat opiskelijavuodet (lähtötaso), ka]",
              "\t, ALL(Muuttujat[Koulutuksen järjestäjä])",
              "\t, ALL(Muuttujat[Koodit Koulutuksen järjestäjä])",
              ")",
              "return DIVIDE(osa, kaikki)"
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %",
            "displayFolder": "Opiskelijavuodet\\Painotettu (lähtötaso)"
          },
          {
            "name": "Painottamattomat enimmäismäärän mukaiset opiskelijavuodet, lkm",
            "expression": [
              "",
              "var summa = CALCULATE(SUMX(Muuttujat, [apusarake_opv_ei_maksuton_kerroin] * [apusarake_opiskelijavuodet_painottamaton]))",
              "return IF(summa=0, BLANK(), summa)"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Opiskelijavuodet\\Painottamaton"
          },
          {
            "name": "Painottamattomat opiskelijavuodet, maksuton, lkm",
            "expression": [
              "",
              "CALCULATE([Painottamattomat opiskelijavuodet ilman enimmäismäärärajausta, lkm], FILTER(VALUES(Muuttujat[Maksuttomuus (rahoitus)]), Muuttujat[Maksuttomuus (rahoitus)]=\"Maksuton (rahoitus)\"))"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Opiskelijavuodet\\Painottamaton"
          },
          {
            "name": "Painottamattomat opiskelijavuodet, maksuton, ka",
            "expression": [
              "",
              "DIVIDE([Painottamattomat opiskelijavuodet, maksuton, lkm], [kausien_lkm])"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Opiskelijavuodet\\Painottamaton"
          },
          {
            "name": "Painottamattomat enimmäismäärän mukaiset opiskelijavuodet, ka",
            "expression": [
              "",
              "DIVIDE([Painottamattomat enimmäismäärän mukaiset opiskelijavuodet, lkm], [kausien_lkm])"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Opiskelijavuodet\\Painottamaton"
          },
          {
            "name": "Painottamattomat opiskelijavuodet ilman enimmäismäärärajausta, lkm",
            "expression": [
              "",
              "var summa = CALCULATE(SUM(Muuttujat[apusarake_opiskelijavuodet_painottamaton]))",
              "return IF(summa=0, BLANK(), summa)"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Opiskelijavuodet\\Painottamaton"
          },
          {
            "name": "Painottamattomat opiskelijavuodet ilman enimmäismäärärajausta, ei maksuton, ka",
            "expression": [
              "",
              "DIVIDE([Painottamattomat opiskelijavuodet ilman enimmäismäärärajausta, ei maksuton, lkm], [kausien_lkm])"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Opiskelijavuodet\\Painottamaton"
          },
          {
            "name": "Tutk. ja osia suor. (ei työll. ennen koul.) työllistyneet ja jatko-opiskelijat, lkm, järj. %-osuus",
            "expression": [
              "",
              "var osa = [Tutk. ja osia suor. (ei työll. ennen koul.) työllistyneet ja jatko-opiskelijat, lkm]",
              "var kaikki = CALCULATE(",
              "\t[Tutk. ja osia suor. (ei työll. ennen koul.) työllistyneet ja jatko-opiskelijat, lkm]",
              "\t, ALL(Muuttujat[Koulutuksen järjestäjä])",
              "\t, ALL(Muuttujat[Koodit Koulutuksen järjestäjä])",
              ")",
              "return DIVIDE(osa, kaikki)"
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %",
            "displayFolder": "Työllistyminen ja jatko-opintoihin siirtyminen"
          },
          {
            "name": "Painotetut rahoituksen perusteena olevat opv (kust.ryhmä, tutk.tyyppi, korotukset), lkm, järj.-%",
            "expression": [
              " --pidempi cultures-selite opv osalta",
              "var osa = [Painotetut rahoituksen perusteena olevat opiskelijavuodet (kust.ryhmä, tutk.tyyppi, korotukset), lkm]",
              "var kaikki = CALCULATE(",
              "\t[Painotetut rahoituksen perusteena olevat opiskelijavuodet (kust.ryhmä, tutk.tyyppi, korotukset), lkm]",
              "\t, ALL(Muuttujat[Koulutuksen järjestäjä])",
              "\t, ALL(Muuttujat[Koodit Koulutuksen järjestäjä])",
              ")",
              "return DIVIDE(osa, kaikki)"
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %",
            "displayFolder": "Opiskelijavuodet\\Painotettu (kust.ryhmä, tutk.tyyppi, korotukset)"
          },
          {
            "name": "Painotetut rahoituksen perusteena olevat opiskelijavuodet (lähtötaso), lkm, järj.-%",
            "expression": [
              "",
              "var osa = [Painotetut rahoituksen perusteena olevat opiskelijavuodet (lähtötaso), lkm]",
              "var kaikki = CALCULATE(",
              "\t[Painotetut rahoituksen perusteena olevat opiskelijavuodet (lähtötaso), lkm]",
              "\t, ALL(Muuttujat[Koulutuksen järjestäjä])",
              "\t, ALL(Muuttujat[Koodit Koulutuksen järjestäjä])",
              ")",
              "return DIVIDE(osa, kaikki)"
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %",
            "displayFolder": "Opiskelijavuodet\\Painotettu (lähtötaso)"
          },
          {
            "name": "kausien_lkm",
            "expression": [
              " --keskiarvomittareihin jakajaksi, nykytoteutuksella eksplisiittinen kerroin 0.5 ajaisi saman",
              "2"
            ],
            "isHidden": true
          },
          {
            "name": "Tutkintojen määrä, lkm",
            "expression": [
              "",
              "var summa = CALCULATE(SUM(Muuttujat[apusarake_painottamaton_tutkinnot]))",
              "return IF(summa=0,BLANK(),summa)"
            ],
            "formatString": "#,0",
            "displayFolder": "Tutkinnot ja osaamispisteet"
          },
          {
            "name": "Tutkintojen määrä, ka",
            "expression": [
              "",
              "DIVIDE([Tutkintojen määrä, lkm], [kausien_lkm])"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Tutkinnot ja osaamispisteet"
          },
          {
            "name": "Tutkinnon osien osaamispisteet, lkm",
            "expression": [
              "",
              "var summa = CALCULATE(SUM(Muuttujat[apusarake_painottamaton_osaamispisteet]))",
              "return IF(summa=0,BLANK(),summa)"
            ],
            "formatString": "#,0",
            "displayFolder": "Tutkinnot ja osaamispisteet"
          },
          {
            "name": "Tutkinnon osien osaamispisteet, ka",
            "expression": [
              "",
              "DIVIDE([Tutkinnon osien osaamispisteet, lkm], [kausien_lkm])"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Tutkinnot ja osaamispisteet"
          },
          {
            "name": "Tutkinnon osien laskentaan hyväksytyt osaamispisteet, lkm",
            "expression": [
              "",
              "var summa = CALCULATE(SUMX(Muuttujat, [apusarake_osaamispisteet_kerroin] * [apusarake_painottamaton_osaamispisteet]))",
              "return IF(summa=0,BLANK(),summa)"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Tutkinnot ja osaamispisteet"
          },
          {
            "name": "Tutkinnon osien laskentaan hyväksytyt osaamispisteet, ka",
            "expression": [
              "",
              "DIVIDE([Tutkinnon osien laskentaan hyväksytyt osaamispisteet, lkm], [kausien_lkm])"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Tutkinnot ja osaamispisteet"
          },
          {
            "name": "Tutkintojen painotetut pisteet, lkm",
            "expression": [
              "",
              "var summa = CALCULATE(SUM(Muuttujat[apusarake_painotettu_tutkinnot]))",
              "return IF(summa=0,BLANK(),summa)"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Tutkinnot ja osaamispisteet"
          },
          {
            "name": "Tutkintojen painotetut pisteet, ka",
            "expression": [
              "",
              "DIVIDE([Tutkintojen painotetut pisteet, lkm], [kausien_lkm])"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Tutkinnot ja osaamispisteet"
          },
          {
            "name": "Tutkintojen painotetut pisteet ja laskentaan hyväksytyt osaamispisteet yhteensä, lkm",
            "expression": "[Tutkintojen painotetut pisteet, lkm] + [Tutkinnon osien laskentaan hyväksytyt osaamispisteet, lkm]",
            "formatString": "#,0.00",
            "displayFolder": "Tutkinnot ja osaamispisteet"
          },
          {
            "name": "Tutkintojen painotetut pisteet ja laskentaan hyväksytyt osaamispisteet yhteensä, ka",
            "expression": [
              "",
              "DIVIDE([Tutkintojen painotetut pisteet ja laskentaan hyväksytyt osaamispisteet yhteensä, lkm], [kausien_lkm])"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Tutkinnot ja osaamispisteet"
          },
          {
            "name": "Tutkintojen painotetut pisteet ja laskentaan hyväksytyt osaamispisteet yhteensä, lkm, järj. %-osuus",
            "expression": [
              "",
              "DIVIDE(",
              "\t[Tutkintojen painotetut pisteet ja laskentaan hyväksytyt osaamispisteet yhteensä, lkm],",
              "\tCALCULATE([Tutkintojen painotetut pisteet ja laskentaan hyväksytyt osaamispisteet yhteensä, lkm], ALL(Muuttujat[Koulutuksen järjestäjä]), ALL(Muuttujat[Koodit Koulutuksen järjestäjä]))",
              ")",
              ""
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %",
            "displayFolder": "Tutkinnot ja osaamispisteet"
          },
          {
            "name": "Tutkintojen painotetut pisteet ja laskentaan hyväksytyt osaamispisteet yhteensä, ka, järj. %-osuus",
            "expression": [
              "",
              "DIVIDE(",
              "\t[Tutkintojen painotetut pisteet ja laskentaan hyväksytyt osaamispisteet yhteensä, ka],",
              "\tCALCULATE([Tutkintojen painotetut pisteet ja laskentaan hyväksytyt osaamispisteet yhteensä, ka], ALL(Muuttujat[Koulutuksen järjestäjä]), ALL(Muuttujat[Koodit Koulutuksen järjestäjä]))",
              ")",
              ""
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %",
            "displayFolder": "Tutkinnot ja osaamispisteet"
          },
          {
            "name": "Rahoitusosuuden muutosrajoitteiden vaikutus rahoitusosuuteen",
            "expression": [
              "",
              "var rajoitettu = [Rahoitusosuuden muutosrajoitteet huomioiva järjestäjien %-osuus]",
              "var rajoittamaton = [Rahoitusosioiden osuuksilla painotetut järjestäjien osuudet yhteensä, järjestäjien %-osuus]",
              "var ehto = NOT(ISBLANK(rajoitettu) || ISBLANK(rajoittamaton))",
              "var muutos = DIVIDE(rajoitettu, rajoittamaton) - 1",
              "return IF(ehto, muutos, BLANK())"
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %",
            "displayFolder": "Kokonaisrahoitus"
          },
          {
            "name": "Rahoitusosuuden muutosrajoitteet huomioiva järjestäjien %-osuus",
            "expression": [
              "",
              "var ehto = (",
              "\tSELECTEDVALUE(Muuttujat[Varainhoitovuosi]) ",
              "\t== CALCULATE(MAX(Muuttujat[Varainhoitovuosi]), ALL(Muuttujat), Muuttujat[apusarake_laskennallinen_rahoitus_osuus_ed_v] > 0)",
              ")",
              "var taulu = ",
              "CALCULATETABLE(",
              "\tADDCOLUMNS(",
              "\t\tSUMMARIZE(Muuttujat, Muuttujat[Koodit Koulutuksen järjestäjä], Muuttujat[Koulutuksen järjestäjä])",
              "\t\t,\"osuus\",  CALCULATE([Rahoitusosioiden osuuksilla painotetut järjestäjien osuudet yhteensä, järjestäjien %-osuus])",
              "\t\t,\"kerroin\", CALCULATE(MAX(Muuttujat[apusarake_laskennallinen_rahoitus_rajoitekerroin]))",
              "\t\t,\"osuus2\", CALCULATE(MAX(Muuttujat[apusarake_laskennallinen_rahoitus_osuus]))",
              "\t)",
              ")",
              "var taulu_kaikki = ",
              "CALCULATETABLE(",
              "\tADDCOLUMNS(",
              "\t\tSUMMARIZE(Muuttujat, Muuttujat[Koodit Koulutuksen järjestäjä], Muuttujat[Koulutuksen järjestäjä])",
              "\t\t,\"osuus\",  CALCULATE([Rahoitusosioiden osuuksilla painotetut järjestäjien osuudet yhteensä, järjestäjien %-osuus])",
              "\t\t,\"kerroin\", CALCULATE(MAX(Muuttujat[apusarake_laskennallinen_rahoitus_rajoitekerroin]))",
              "\t\t,\"osuus2\", CALCULATE(MAX(Muuttujat[apusarake_laskennallinen_rahoitus_osuus]))",
              "\t)",
              "\t, ALL(Muuttujat[Koodit Koulutuksen järjestäjä]), ALL(Muuttujat[Koulutuksen järjestäjä])",
              ")",
              "var lkm1 = SUMX(taulu, IF(ISBLANK([kerroin]), [osuus2], [osuus]*[kerroin]))",
              "var lkm2 = SUMX(taulu_kaikki, IF(ISBLANK([kerroin]), [osuus2], [osuus]*[kerroin]))",
              "var lkm = DIVIDE(lkm1, lkm2)",
              "return IF(ehto, lkm, BLANK())"
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %",
            "displayFolder": "Kokonaisrahoitus"
          },
          {
            "name": "Rahoitusosioiden osuuksilla painotetut järjestäjien osuudet yhteensä, muutos ed. v. rahoitusosuuteen",
            "expression": [
              "",
              "var ehto = (",
              "\tSELECTEDVALUE(Muuttujat[Varainhoitovuosi]) ",
              "\t== CALCULATE(MAX(Muuttujat[Varainhoitovuosi]), ALL(Muuttujat), Muuttujat[apusarake_laskennallinen_rahoitus_osuus_ed_v] > 0)",
              ")",
              "var taulu = ",
              "CALCULATETABLE(",
              "\tADDCOLUMNS(",
              "\t\tSUMMARIZE(Muuttujat, Muuttujat[Koodit Koulutuksen järjestäjä], Muuttujat[Koulutuksen järjestäjä])",
              "\t\t,\"osuus\",  CALCULATE([Rahoitusosioiden osuuksilla painotetut järjestäjien osuudet yhteensä, järjestäjien %-osuus])",
              "\t\t,\"osuus_ed_v\", CALCULATE(MAX(Muuttujat[apusarake_laskennallinen_rahoitus_osuus_ed_v]))",
              "\t)/*",
              "\t, ALLEXCEPT(Muuttujat",
              "\t\t, Muuttujat[Varainhoitovuosi]",
              "\t\t, Muuttujat[Toteuma/Estimaatti]",
              "\t\t, Muuttujat[Järjestäjärakenne]",
              "\t\t, Muuttujat[Luvaton koulutus]",
              "\t\t, Muuttujat[Luvaton majoitus]",
              "\t\t, Muuttujat[Luvaton korotustekijä]",
              "\t\t, Muuttujat[Luvanmukainen suorituskieli]",
              "\t\t, Muuttujat[Rahoitusmuoto hyväksytään]",
              "\t\t, Muuttujat[Hyväksytyt/hylätyt opiskelijavuodet]",
              "\t\t, Muuttujat[Koodit Koulutuksen järjestäjä]",
              "\t\t, Muuttujat[Koulutuksen järjestäjä]",
              "\t)*/",
              ")",
              "var taulu_kaikki = ",
              "CALCULATETABLE(",
              "\tADDCOLUMNS(",
              "\t\tSUMMARIZE(Muuttujat, Muuttujat[Koodit Koulutuksen järjestäjä], Muuttujat[Koulutuksen järjestäjä])",
              "\t\t,\"osuus_ed_v\", CALCULATE(MAX(Muuttujat[apusarake_laskennallinen_rahoitus_osuus_ed_v]))",
              "\t)",
              "\t, ALL(Muuttujat[Koodit Koulutuksen järjestäjä]), ALL(Muuttujat[Koulutuksen järjestäjä])",
              ")",
              "var osuus_ed_v_yht = SUMX(taulu_kaikki, [osuus_ed_v])",
              "var muutos = DIVIDE(SUMX(taulu, osuus_ed_v_yht*[osuus] - [osuus_ed_v]), SUMX(taulu, [osuus_ed_v]))",
              "return IF(ehto, muutos, BLANK())",
              ""
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %",
            "displayFolder": "Kokonaisrahoitus"
          },
          {
            "name": "Rahoitusosuuden muutosrajoitteet huomioiva järjestäjien %-osuus, muutos ed. v. rahoitusosuuteen",
            "expression": [
              "",
              "var ehto = (",
              "\tSELECTEDVALUE(Muuttujat[Varainhoitovuosi]) ",
              "\t== CALCULATE(MAX(Muuttujat[Varainhoitovuosi]), ALL(Muuttujat), Muuttujat[apusarake_laskennallinen_rahoitus_osuus_ed_v] > 0)",
              ")",
              "var taulu = ",
              "CALCULATETABLE(",
              "\tADDCOLUMNS(",
              "\t\tSUMMARIZE(Muuttujat, Muuttujat[Koodit Koulutuksen järjestäjä], Muuttujat[Koulutuksen järjestäjä])",
              "\t\t,\"osuus\",  CALCULATE([Rahoitusosuuden muutosrajoitteet huomioiva järjestäjien %-osuus])",
              "\t\t,\"osuus_ed_v\", CALCULATE(MAX(Muuttujat[apusarake_laskennallinen_rahoitus_osuus_ed_v]))",
              "\t)",
              ")",
              "var taulu_kaikki = ",
              "CALCULATETABLE(",
              "\tADDCOLUMNS(",
              "\t\tSUMMARIZE(Muuttujat, Muuttujat[Koodit Koulutuksen järjestäjä], Muuttujat[Koulutuksen järjestäjä])",
              "\t\t,\"osuus_ed_v\", CALCULATE(MAX(Muuttujat[apusarake_laskennallinen_rahoitus_osuus_ed_v]))",
              "\t)",
              "\t, ALL(Muuttujat[Koodit Koulutuksen järjestäjä]), ALL(Muuttujat[Koulutuksen järjestäjä])",
              ")",
              "var osuus_ed_v_yht = SUMX(taulu_kaikki, [osuus_ed_v])",
              "var muutos = DIVIDE(SUMX(taulu, osuus_ed_v_yht*[osuus] - [osuus_ed_v]), SUMX(taulu, [osuus_ed_v]))",
              "return IF(ehto, muutos, BLANK())",
              ""
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %",
            "displayFolder": "Kokonaisrahoitus"
          },
          {
            "name": "Rahoitusosuuden muutosrajoitteet huomioiva järjestäjien %-osuus (kiinteä)",
            "expression": [
              "",
              "var ehto1 = HASONEVALUE(Muuttujat[Varainhoitovuosi]) ",
              "/*(",
              "\tSELECTEDVALUE(Muuttujat[Varainhoitovuosi]) ",
              "\t== CALCULATE(MAX(Muuttujat[Varainhoitovuosi]), ALL(Muuttujat), Muuttujat[apusarake_laskennallinen_rahoitus_osuus_ed_v] > 0)",
              ")*/",
              "var ehto2 = ISFILTERED(Muuttujat[Toteuma/Estimaatti])",
              "var ehto3 = (",
              "\t(ISFILTERED(Muuttujat[Koulutuksen järjestäjä]) && HASONEVALUE(Muuttujat[Koulutuksen järjestäjä]))",
              "\t|| (ISFILTERED(Muuttujat[Koodit Koulutuksen järjestäjä]) && HASONEVALUE(Muuttujat[Koodit Koulutuksen järjestäjä]))",
              ")",
              "",
              "var osuus = CALCULATE(MAX(Muuttujat[apusarake_laskennallinen_rahoitus_osuus]))",
              "\t",
              "return IF(ehto1 && ehto2 && ehto3 && osuus > 0, osuus, BLANK())"
            ],
            "formatString": "0.00000 %;-0.00000 %;0.00000 %",
            "displayFolder": "Kokonaisrahoitus"
          },
          {
            "name": "Rahoitusosioiden osuuksilla painotettu järj. %-osuus, muutos ed. v. rahoitusosuuteen (kiinteä)",
            "expression": [
              "",
              "var ehto1 = HASONEVALUE(Muuttujat[Varainhoitovuosi]) ",
              "/*(",
              "\tSELECTEDVALUE(Muuttujat[Varainhoitovuosi]) ",
              "\t== CALCULATE(MAX(Muuttujat[Varainhoitovuosi]), ALL(Muuttujat), Muuttujat[apusarake_laskennallinen_rahoitus_osuus_ed_v] > 0)",
              ")*/",
              "var ehto2 = ISFILTERED(Muuttujat[Toteuma/Estimaatti])",
              "var ehto3 = (",
              "\t(ISFILTERED(Muuttujat[Koulutuksen järjestäjä]) && HASONEVALUE(Muuttujat[Koulutuksen järjestäjä]))",
              "\t|| (ISFILTERED(Muuttujat[Koodit Koulutuksen järjestäjä]) && HASONEVALUE(Muuttujat[Koodit Koulutuksen järjestäjä]))",
              ")",
              "",
              "var osuus1 = CALCULATE(MAX(Muuttujat[apusarake_laskennallinen_rahoitus_osuus_ed_v]))",
              "",
              "var kerroin = CALCULATE(MAX(Muuttujat[apusarake_laskennallinen_rahoitus_rajoitekerroin]))",
              "var osuus = CALCULATE(MAX(Muuttujat[apusarake_laskennallinen_rahoitus_osuus]))",
              "var osuus2 = DIVIDE(osuus, kerroin)",
              "",
              "var muutos = DIVIDE(osuus2 - osuus1, osuus1)",
              "",
              "return IF(ehto1 && ehto2 && ehto3 && muutos <> 0, muutos , BLANK())"
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %",
            "displayFolder": "Kokonaisrahoitus"
          },
          {
            "name": "Rahoitusosuuden muutosrajoitteet huomioiva järj. %-osuus, muutos ed. v. rahoitusosuuteen (kiinteä)",
            "expression": [
              "",
              "var ehto1 = HASONEVALUE(Muuttujat[Varainhoitovuosi]) ",
              "/*(",
              "\tSELECTEDVALUE(Muuttujat[Varainhoitovuosi]) ",
              "\t== CALCULATE(MAX(Muuttujat[Varainhoitovuosi]), ALL(Muuttujat), Muuttujat[apusarake_laskennallinen_rahoitus_osuus_ed_v] > 0)",
              ")*/",
              "var ehto2 = ISFILTERED(Muuttujat[Toteuma/Estimaatti])",
              "var ehto3 = (",
              "\t(ISFILTERED(Muuttujat[Koulutuksen järjestäjä]) && HASONEVALUE(Muuttujat[Koulutuksen järjestäjä]))",
              "\t|| (ISFILTERED(Muuttujat[Koodit Koulutuksen järjestäjä]) && HASONEVALUE(Muuttujat[Koodit Koulutuksen järjestäjä]))",
              ")",
              "",
              "var osuus1 = CALCULATE(MAX(Muuttujat[apusarake_laskennallinen_rahoitus_osuus_ed_v]))",
              "var osuus2 = CALCULATE(MAX(Muuttujat[apusarake_laskennallinen_rahoitus_osuus]))",
              "var muutos = DIVIDE(osuus2 - osuus1, osuus1)",
              "",
              "return IF(ehto1 && ehto2 && ehto3 && muutos <> 0, muutos , BLANK())",
              ""
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %",
            "displayFolder": "Kokonaisrahoitus"
          },
          {
            "name": "Rahoitusosuuden muutosrajoitteiden vaikutus rahoitusosuuteen (kiinteä)",
            "expression": [
              "",
              "var ehto1 = HASONEVALUE(Muuttujat[Varainhoitovuosi]) ",
              "/*(",
              "\tSELECTEDVALUE(Muuttujat[Varainhoitovuosi]) ",
              "\t== CALCULATE(MAX(Muuttujat[Varainhoitovuosi]), ALL(Muuttujat), Muuttujat[apusarake_laskennallinen_rahoitus_osuus_ed_v] > 0)",
              ")*/",
              "var ehto2 = ISFILTERED(Muuttujat[Toteuma/Estimaatti])",
              "var ehto3 = (",
              "\t(ISFILTERED(Muuttujat[Koulutuksen järjestäjä]) && HASONEVALUE(Muuttujat[Koulutuksen järjestäjä]))",
              "\t|| (ISFILTERED(Muuttujat[Koodit Koulutuksen järjestäjä]) && HASONEVALUE(Muuttujat[Koodit Koulutuksen järjestäjä]))",
              ")",
              "",
              "var kerroin = CALCULATE(MAX(Muuttujat[apusarake_laskennallinen_rahoitus_rajoitekerroin]))",
              "var osuus2 = CALCULATE(MAX(Muuttujat[apusarake_laskennallinen_rahoitus_osuus]))",
              "var osuus1 = DIVIDE(osuus2, kerroin)",
              "                  ",
              "var muutos = DIVIDE(osuus2 - osuus1, osuus1)",
              "                  ",
              "return IF(ehto1 && ehto2 && ehto3 && muutos <> 0, muutos , BLANK())"
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %",
            "displayFolder": "Kokonaisrahoitus"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT * FROM [dw].[v_amos_koonti_2026] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "v_amos_koonti_2026"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dw"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Järjestäjärakenne</string>",
              "      </key>",
              "      <value>",
              "        <int>182</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutuksen järjestäjä</string>",
              "      </key>",
              "      <value>",
              "        <int>170</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit Koulutuksen järjestäjä</string>",
              "      </key>",
              "      <value>",
              "        <int>213</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tilastokausi</string>",
              "      </key>",
              "      <value>",
              "        <int>115</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Rahoituskausi</string>",
              "      </key>",
              "      <value>",
              "        <int>118</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kyselyn kohderyhmä</string>",
              "      </key>",
              "      <value>",
              "        <int>164</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kysely</string>",
              "      </key>",
              "      <value>",
              "        <int>74</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Vaikuttavuusrahoituksen peruste</string>",
              "      </key>",
              "      <value>",
              "        <int>235</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Varainhoitovuosi</string>",
              "      </key>",
              "      <value>",
              "        <int>135</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutuksen järjestäjän kunta</string>",
              "      </key>",
              "      <value>",
              "        <int>217</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutuksen järjestäjän maakunta</string>",
              "      </key>",
              "      <value>",
              "        <int>243</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj Koulutuksen järjestäjän maakunta</string>",
              "      </key>",
              "      <value>",
              "        <int>267</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Rahoituskausi (palautteet)</string>",
              "      </key>",
              "      <value>",
              "        <int>193</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Rahoitusosuus</string>",
              "      </key>",
              "      <value>",
              "        <int>124</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Suorituksen tyyppi</string>",
              "      </key>",
              "      <value>",
              "        <int>156</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>apusarake_lkm</string>",
              "      </key>",
              "      <value>",
              "        <int>126</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>apusarake_pisteet</string>",
              "      </key>",
              "      <value>",
              "        <int>145</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>apusarake_painotetut_pisteet</string>",
              "      </key>",
              "      <value>",
              "        <int>216</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Korkeakouluopiskelija</string>",
              "      </key>",
              "      <value>",
              "        <int>163</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Työllinen</string>",
              "      </key>",
              "      <value>",
              "        <int>88</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kokonaisuus</string>",
              "      </key>",
              "      <value>",
              "        <int>111</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Suorituksen tyyppi</string>",
              "      </key>",
              "      <value>",
              "        <int>150</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Opiskelijavuoden tyyppi</string>",
              "      </key>",
              "      <value>",
              "        <int>180</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ikä (maksuttomuusraja)</string>",
              "      </key>",
              "      <value>",
              "        <int>182</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ikäryhmä</string>",
              "      </key>",
              "      <value>",
              "        <int>93</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj_ikaryhma</string>",
              "      </key>",
              "      <value>",
              "        <int>119</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Äidinkieli (ryhmä)</string>",
              "      </key>",
              "      <value>",
              "        <int>137</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj_aidinkieli_ryhma</string>",
              "      </key>",
              "      <value>",
              "        <int>158</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Maksuttomuus</string>",
              "      </key>",
              "      <value>",
              "        <int>125</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Maksuttomuus</string>",
              "      </key>",
              "      <value>",
              "        <int>194</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Majoitus</string>",
              "      </key>",
              "      <value>",
              "        <int>85</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Vaativa erityinen tuki</string>",
              "      </key>",
              "      <value>",
              "        <int>161</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kustannusryhmä</string>",
              "      </key>",
              "      <value>",
              "        <int>139</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj_kustannusryhma</string>",
              "      </key>",
              "      <value>",
              "        <int>166</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tutkintotyyppi</string>",
              "      </key>",
              "      <value>",
              "        <int>125</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tutkintotyyppi (rahoitus)</string>",
              "      </key>",
              "      <value>",
              "        <int>188</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarjestys Tutkintotyyppi rahoitus</string>",
              "      </key>",
              "      <value>",
              "        <int>234</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tutkinto</string>",
              "      </key>",
              "      <value>",
              "        <int>86</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit Tutkinto</string>",
              "      </key>",
              "      <value>",
              "        <int>129</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusala, taso 1</string>",
              "      </key>",
              "      <value>",
              "        <int>150</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj_koulutusala_taso1</string>",
              "      </key>",
              "      <value>",
              "        <int>173</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Rahoitusmuoto</string>",
              "      </key>",
              "      <value>",
              "        <int>129</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj_rahoitusmuoto</string>",
              "      </key>",
              "      <value>",
              "        <int>153</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ei maksuttomien opiskelijavuosien enimmäismäärä</string>",
              "      </key>",
              "      <value>",
              "        <int>338</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Sisäoppilaitosmuotoisen majoituksen opiskelijavuosien enimmäismäärä</string>",
              "      </key>",
              "      <value>",
              "        <int>458</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Vaativan erityisen tuen opiskelijavuosien enimmäismäärä</string>",
              "      </key>",
              "      <value>",
              "        <int>375</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Luvaton koulutus</string>",
              "      </key>",
              "      <value>",
              "        <int>142</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Luvaton majoitus</string>",
              "      </key>",
              "      <value>",
              "        <int>142</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Luvaton korotustekijä</string>",
              "      </key>",
              "      <value>",
              "        <int>169</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Luvanmukainen suorituskieli</string>",
              "      </key>",
              "      <value>",
              "        <int>204</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj_luvaton_koulutus</string>",
              "      </key>",
              "      <value>",
              "        <int>169</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj_luvaton_majoitus</string>",
              "      </key>",
              "      <value>",
              "        <int>169</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj_luvaton_korotustekija</string>",
              "      </key>",
              "      <value>",
              "        <int>196</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj_suorituskieli_luvanmukainen</string>",
              "      </key>",
              "      <value>",
              "        <int>231</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>apusarake_opiskelijavuodet_painottamaton</string>",
              "      </key>",
              "      <value>",
              "        <int>300</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>apusarake_opiskelijavuodet_painotettu</string>",
              "      </key>",
              "      <value>",
              "        <int>273</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>apusarake_opv_ei_maksuton_kerroin</string>",
              "      </key>",
              "      <value>",
              "        <int>265</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Järjestäjärakenne</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutuksen järjestäjä</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit Koulutuksen järjestäjä</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tilastokausi</string>",
              "      </key>",
              "      <value>",
              "        <int>12</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Rahoituskausi</string>",
              "      </key>",
              "      <value>",
              "        <int>11</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kyselyn kohderyhmä</string>",
              "      </key>",
              "      <value>",
              "        <int>10</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kysely</string>",
              "      </key>",
              "      <value>",
              "        <int>9</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Vaikuttavuusrahoituksen peruste</string>",
              "      </key>",
              "      <value>",
              "        <int>8</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Varainhoitovuosi</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutuksen järjestäjän kunta</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutuksen järjestäjän maakunta</string>",
              "      </key>",
              "      <value>",
              "        <int>5</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj Koulutuksen järjestäjän maakunta</string>",
              "      </key>",
              "      <value>",
              "        <int>6</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Rahoituskausi (palautteet)</string>",
              "      </key>",
              "      <value>",
              "        <int>7</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Rahoitusosuus</string>",
              "      </key>",
              "      <value>",
              "        <int>13</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Suorituksen tyyppi</string>",
              "      </key>",
              "      <value>",
              "        <int>14</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>apusarake_lkm</string>",
              "      </key>",
              "      <value>",
              "        <int>15</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>apusarake_pisteet</string>",
              "      </key>",
              "      <value>",
              "        <int>16</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>apusarake_painotetut_pisteet</string>",
              "      </key>",
              "      <value>",
              "        <int>17</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Korkeakouluopiskelija</string>",
              "      </key>",
              "      <value>",
              "        <int>18</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Työllinen</string>",
              "      </key>",
              "      <value>",
              "        <int>19</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kokonaisuus</string>",
              "      </key>",
              "      <value>",
              "        <int>20</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Suorituksen tyyppi</string>",
              "      </key>",
              "      <value>",
              "        <int>21</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Opiskelijavuoden tyyppi</string>",
              "      </key>",
              "      <value>",
              "        <int>22</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ikä (maksuttomuusraja)</string>",
              "      </key>",
              "      <value>",
              "        <int>23</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ikäryhmä</string>",
              "      </key>",
              "      <value>",
              "        <int>24</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj_ikaryhma</string>",
              "      </key>",
              "      <value>",
              "        <int>25</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Äidinkieli (ryhmä)</string>",
              "      </key>",
              "      <value>",
              "        <int>26</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj_aidinkieli_ryhma</string>",
              "      </key>",
              "      <value>",
              "        <int>27</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Maksuttomuus</string>",
              "      </key>",
              "      <value>",
              "        <int>28</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Maksuttomuus</string>",
              "      </key>",
              "      <value>",
              "        <int>29</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Majoitus</string>",
              "      </key>",
              "      <value>",
              "        <int>30</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Vaativa erityinen tuki</string>",
              "      </key>",
              "      <value>",
              "        <int>31</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kustannusryhmä</string>",
              "      </key>",
              "      <value>",
              "        <int>32</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj_kustannusryhma</string>",
              "      </key>",
              "      <value>",
              "        <int>33</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tutkintotyyppi</string>",
              "      </key>",
              "      <value>",
              "        <int>34</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tutkintotyyppi (rahoitus)</string>",
              "      </key>",
              "      <value>",
              "        <int>35</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarjestys Tutkintotyyppi rahoitus</string>",
              "      </key>",
              "      <value>",
              "        <int>36</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tutkinto</string>",
              "      </key>",
              "      <value>",
              "        <int>37</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit Tutkinto</string>",
              "      </key>",
              "      <value>",
              "        <int>38</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusala, taso 1</string>",
              "      </key>",
              "      <value>",
              "        <int>39</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj_koulutusala_taso1</string>",
              "      </key>",
              "      <value>",
              "        <int>40</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Rahoitusmuoto</string>",
              "      </key>",
              "      <value>",
              "        <int>41</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj_rahoitusmuoto</string>",
              "      </key>",
              "      <value>",
              "        <int>42</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ei maksuttomien opiskelijavuosien enimmäismäärä</string>",
              "      </key>",
              "      <value>",
              "        <int>43</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Sisäoppilaitosmuotoisen majoituksen opiskelijavuosien enimmäismäärä</string>",
              "      </key>",
              "      <value>",
              "        <int>44</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Vaativan erityisen tuen opiskelijavuosien enimmäismäärä</string>",
              "      </key>",
              "      <value>",
              "        <int>45</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Luvaton koulutus</string>",
              "      </key>",
              "      <value>",
              "        <int>46</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Luvaton majoitus</string>",
              "      </key>",
              "      <value>",
              "        <int>47</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Luvaton korotustekijä</string>",
              "      </key>",
              "      <value>",
              "        <int>48</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Luvanmukainen suorituskieli</string>",
              "      </key>",
              "      <value>",
              "        <int>49</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj_luvaton_koulutus</string>",
              "      </key>",
              "      <value>",
              "        <int>50</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj_luvaton_majoitus</string>",
              "      </key>",
              "      <value>",
              "        <int>51</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj_luvaton_korotustekija</string>",
              "      </key>",
              "      <value>",
              "        <int>52</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj_suorituskieli_luvanmukainen</string>",
              "      </key>",
              "      <value>",
              "        <int>53</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>apusarake_opiskelijavuodet_painottamaton</string>",
              "      </key>",
              "      <value>",
              "        <int>54</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>apusarake_opiskelijavuodet_painotettu</string>",
              "      </key>",
              "      <value>",
              "        <int>55</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>apusarake_opv_ei_maksuton_kerroin</string>",
              "      </key>",
              "      <value>",
              "        <int>56</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Tilastokausi</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Varainhoitovuosi</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Rahoituskausi</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kyselyn kohderyhmä</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kysely</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Vaikuttavuusrahoituksen peruste</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutuksen järjestäjän kunta</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutuksen järjestäjän maakunta</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj Koulutuksen järjestäjän maakunta</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Rahoituskausi (palautteet)</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Rahoitusosuus</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Suorituksen tyyppi</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>apusarake_lkm</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Korkeakouluopiskelija</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Työllinen</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kokonaisuus</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Suorituksen tyyppi</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Opiskelijavuoden tyyppi</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ikä (maksuttomuusraja)</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ikäryhmä</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj_ikaryhma</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Äidinkieli (ryhmä)</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj_aidinkieli_ryhma</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Maksuttomuus</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Maksuttomuus</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Majoitus</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Vaativa erityinen tuki</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kustannusryhmä</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj_kustannusryhma</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tutkintotyyppi</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tutkintotyyppi (rahoitus)</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarjestys Tutkintotyyppi rahoitus</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tutkinto</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit Tutkinto</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusala, taso 1</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj_koulutusala_taso1</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Rahoitusmuoto</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj_rahoitusmuoto</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ei maksuttomien opiskelijavuosien enimmäismäärä</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Sisäoppilaitosmuotoisen majoituksen opiskelijavuosien enimmäismäärä</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Vaativan erityisen tuen opiskelijavuosien enimmäismäärä</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Luvaton koulutus</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Luvaton majoitus</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Luvaton korotustekijä</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Luvanmukainen suorituskieli</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj_luvaton_koulutus</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj_luvaton_majoitus</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj_luvaton_korotustekija</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj_suorituskieli_luvanmukainen</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>apusarake_opiskelijavuodet_painottamaton</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>apusarake_opiskelijavuodet_painotettu</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>apusarake_opv_ei_maksuton_kerroin</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      }
    ],
    "cultures": [
      {
        "name": "fi-FI",
        "translations": {
          "model": {
            "name": "Model",
            "tables": [
              {
                "name": "Muuttujat",
                "translatedCaption": "Muuttujat",
                "measures": [
                  {
                    "name": "Painotetut rahoituksen perusteena olevat opv (kust.ryhmä, tutk.tyyppi, korotukset), ka, järj.-%",
                    "translatedCaption": "Painotetut rahoituksen perusteena olevat opiskelijavuodet (kust.ryhmä, tutk.tyyppi, korotukset), ka, järj.-%"
                  },
                  {
                    "name": "Painotetut rahoituksen perusteena olevat opv (kust.ryhmä, tutk.tyyppi, korotukset), lkm, järj.-%",
                    "translatedCaption": "Painotetut rahoituksen perusteena olevat opiskelijavuodet (kust.ryhmä, tutk.tyyppi, korotukset), lkm, järj.-%"
                  }
                ]
              }
            ]
          }
        }
      }
    ],
    "perspectives": [
      {
        "name": "kaikki",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Koodit Koulutuksen järjestäjä"
              },
              {
                "name": "Koulutuksen järjestäjä"
              },
              {
                "name": "Varainhoitovuosi"
              },
              {
                "name": "Koulutuksen järjestäjän kunta"
              },
              {
                "name": "Koulutuksen järjestäjän maakunta"
              },
              {
                "name": "Oppilaitos"
              },
              {
                "name": "Oppilaitoksen kunta"
              },
              {
                "name": "Oppilaitoksen maakunta"
              },
              {
                "name": "Toimipiste"
              },
              {
                "name": "Toimipisteen kunta"
              },
              {
                "name": "Toimipisteen maakunta"
              },
              {
                "name": "Rahoituskausi (palautteet)"
              },
              {
                "name": "Äidinkieli (ryhmä)"
              },
              {
                "name": "Kokonaisuus"
              },
              {
                "name": "Koulutusala, taso 1"
              },
              {
                "name": "Koulutusala, taso 2"
              },
              {
                "name": "Koulutusala, taso 3"
              },
              {
                "name": "Kustannusryhmä"
              },
              {
                "name": "Luvanmukainen suorituskieli"
              },
              {
                "name": "Luvaton korotustekijä"
              },
              {
                "name": "Luvaton koulutus"
              },
              {
                "name": "Luvaton majoitus"
              },
              {
                "name": "Majoitus"
              },
              {
                "name": "Rahoitusmuoto"
              },
              {
                "name": "Suorituksen tyyppi"
              },
              {
                "name": "Tutkinto"
              },
              {
                "name": "Tutkintotyyppi"
              },
              {
                "name": "Tutkintotyyppi (rahoitus)"
              },
              {
                "name": "Vaativa erityinen tuki"
              },
              {
                "name": "Vaativan erityisen tuen opiskelijavuosien enimmäismäärä"
              },
              {
                "name": "Hyväksytyt/hylätyt opiskelijavuodet"
              },
              {
                "name": "Ei maksuttomien opiskelijavuosien enimmäismäärä"
              },
              {
                "name": "Ikä (maksuttomuusraja)"
              },
              {
                "name": "Ikäryhmä"
              },
              {
                "name": "Koodit Tutkinto"
              },
              {
                "name": "Rahoitusmuoto hyväksytään"
              },
              {
                "name": "Toteuma/Estimaatti"
              },
              {
                "name": "Koul. järjestäjän PILKE-alue (kokeilu)"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Suorituskieli"
              },
              {
                "name": "Työvoimakoulutus"
              },
              {
                "name": "Hankintakoulutus"
              },
              {
                "name": "Oppisopimuskoulutus"
              },
              {
                "name": "Vankilaopetus"
              },
              {
                "name": "Sukupuoli"
              },
              {
                "name": "Hankintakoulutuksen järjestäjä"
              },
              {
                "name": "Koodit Hankintakoulutuksen järjestäjä"
              },
              {
                "name": "Rahoituskausi (pl. palautteet)"
              },
              {
                "name": "Järjestäjärakenne"
              },
              {
                "name": "Maksuttomuus (rahoitus)"
              },
              {
                "name": "Toiminnanohjauksen kokeilu"
              },
              {
                "name": "Tilastokausi"
              }
            ],
            "measures": [
              {
                "name": "Opiskelunsa aloittaneiden palautteen painotetut pisteet, lkm"
              },
              {
                "name": "Opiskelunsa aloittaneiden palautteen pisteet, lkm"
              },
              {
                "name": "Opiskelunsa päättäneiden palautteen painotetut pisteet, lkm"
              },
              {
                "name": "Opiskelunsa päättäneiden palautteen pisteet, lkm"
              },
              {
                "name": "Työpaikkakyselyn pisteet, lkm"
              },
              {
                "name": "Työpaikkaohjaajakyselyn painotetut pisteet, lkm"
              },
              {
                "name": "Työpaikkaohjaajakyselyn pisteet, lkm"
              },
              {
                "name": "Tutk. ja osia suor. (ei työll. ennen koul.) työllistyneet ja jatko-opiskelijat, ka"
              },
              {
                "name": "Tutk. ja osia suor. (ei työll. ennen koul.) työllistyneet ja jatko-opiskelijat, lkm"
              },
              {
                "name": "Tutkinnon osia suorittaneet (ei työll. ennen koul.) jatko-opiskelijat, ka"
              },
              {
                "name": "Tutkinnon osia suorittaneet (ei työll. ennen koul.) jatko-opiskelijat, lkm"
              },
              {
                "name": "Tutkinnon osia suorittaneet (ei työll. ennen koul.) työllistyneet, ka"
              },
              {
                "name": "Tutkinnon osia suorittaneet (ei työll. ennen koul.) työllistyneet, lkm"
              },
              {
                "name": "Tutkinnon suorittaneet (ei työll. ennen koul.) jatko-opiskelijat, ka"
              },
              {
                "name": "Tutkinnon suorittaneet (ei työll. ennen koul.) jatko-opiskelijat, lkm"
              },
              {
                "name": "Tutkinnon suorittaneet (ei työll. ennen koul.) työllistyneet, ka"
              },
              {
                "name": "Tutkinnon suorittaneet (ei työll. ennen koul.) työllistyneet, lkm"
              },
              {
                "name": "Painotetut rahoituksen perusteena olevat opiskelijavuodet (kust.ryhmä, tutk.tyyppi, korotukset), ka"
              },
              {
                "name": "Painotetut rahoituksen perusteena olevat opiskelijavuodet (kust.ryhmä, tutk.tyyppi, korotukset), lkm"
              },
              {
                "name": "Painotetut rahoituksen perusteena olevat opiskelijavuodet (lähtötaso), ka"
              },
              {
                "name": "Painotetut rahoituksen perusteena olevat opiskelijavuodet (lähtötaso), lkm"
              },
              {
                "name": "Painotetut opiskelijavuodet (kust.ryhmä, tutk.tyyppi, korotukset), ka"
              },
              {
                "name": "Painotetut opiskelijavuodet (kust.ryhmä, tutk.tyyppi, korotukset), lkm"
              },
              {
                "name": "Painotetut opiskelijavuodet (lähtötaso), ka"
              },
              {
                "name": "Painotetut opiskelijavuodet (lähtötaso), lkm"
              },
              {
                "name": "Painottamattomat enimmäismäärän mukaiset opiskelijavuodet, ei maksuton, ka"
              },
              {
                "name": "Painottamattomat enimmäismäärän mukaiset opiskelijavuodet, ei maksuton, lkm"
              },
              {
                "name": "Painottamattomat opiskelijavuodet ilman enimmäismäärärajausta, ka"
              },
              {
                "name": "Painottamattomat opiskelijavuodet ilman enimmäismäärärajausta, ei maksuton, lkm"
              },
              {
                "name": "Painottamattomat enimmäismäärän mukaiset opiskelijavuodet, lkm"
              },
              {
                "name": "Painottamattomat enimmäismäärän mukaiset opiskelijavuodet, ka"
              },
              {
                "name": "Painottamattomat opiskelijavuodet ilman enimmäismäärärajausta, ei maksuton, ka"
              },
              {
                "name": "Painottamattomat opiskelijavuodet ilman enimmäismäärärajausta, lkm"
              },
              {
                "name": "Painottamattomat opiskelijavuodet, maksuton, ka"
              },
              {
                "name": "Painottamattomat opiskelijavuodet, maksuton, lkm"
              },
              {
                "name": "Tutkinnon osien laskentaan hyväksytyt osaamispisteet, ka"
              },
              {
                "name": "Tutkinnon osien laskentaan hyväksytyt osaamispisteet, lkm"
              },
              {
                "name": "Tutkinnon osien osaamispisteet, ka"
              },
              {
                "name": "Tutkinnon osien osaamispisteet, lkm"
              },
              {
                "name": "Tutkintojen määrä, ka"
              },
              {
                "name": "Tutkintojen määrä, lkm"
              },
              {
                "name": "Tutkintojen painotetut pisteet ja laskentaan hyväksytyt osaamispisteet yhteensä, ka"
              },
              {
                "name": "Tutkintojen painotetut pisteet ja laskentaan hyväksytyt osaamispisteet yhteensä, lkm"
              },
              {
                "name": "Tutkintojen painotetut pisteet, ka"
              },
              {
                "name": "Tutkintojen painotetut pisteet, lkm"
              },
              {
                "name": "Rahoitusosuuden muutosrajoitteet huomioiva järjestäjien %-osuus (kiinteä)"
              },
              {
                "name": "Rahoitusosuuden muutosrajoitteet huomioiva järj. %-osuus, muutos ed. v. rahoitusosuuteen (kiinteä)"
              },
              {
                "name": "Rahoitusosioiden osuuksilla painotettu järj. %-osuus, muutos ed. v. rahoitusosuuteen (kiinteä)"
              },
              {
                "name": "Rahoitusosuuden muutosrajoitteiden vaikutus rahoitusosuuteen (kiinteä)"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      }
    ],
    "roles": [
      {
        "name": "Luku",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "DWI\\P_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1733"
          },
          {
            "memberName": "DWI\\T_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1732"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "400"
      }
    ]
  },
  "id": "SemanticModel"
}