{
  "name": "SemanticModel",
  "id": "SemanticModel",
  "compatibilityLevel": 1200,
  "model": {
    "culture": "fi-FI",
    "dataSources": [
      {
        "name": "SqlServer dwitvipusql16 ANTERO",
        "connectionString": "Provider=SQLNCLI11;Data Source=dwitvipusql16;Initial Catalog=ANTERO;Integrated Security=SSPI;Persist Security Info=false",
        "impersonationMode": "impersonateAccount",
        "account": "dwi\\T_VIPUTK_KUUTIO",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "Sarakeleveys",
        "columns": [
          {
            "name": "Sarakeleveys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Sarakeleveys",
            "sourceProviderType": "Char"
          },
          {
            "name": "leveys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "leveys",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Sarakeleveys",
            "dataView": "full",
            "source": {
              "query": " SELECT [dw].[Sarakeleveys].* FROM [dw].[Sarakeleveys] ",
              "dataSource": "SqlServer dwitvipusql16 ANTERO"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dw].[Sarakeleveys].* FROM [dw].[Sarakeleveys] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Sarakeleveys"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dw"
          }
        ]
      },
      {
        "name": "Muuttujat",
        "columns": [
          {
            "name": "Tilastovuosi",
            "dataType": "int64",
            "sourceColumn": "Tilastovuosi",
            "sourceProviderType": "Integer",
            "displayFolder": "Aikamuuttujat"
          },
          {
            "name": "Koulutusala 02",
            "dataType": "string",
            "sourceColumn": "Koulutusala 02",
            "sourceProviderType": "Char",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusala 95",
            "dataType": "string",
            "sourceColumn": "Koulutusala 95",
            "sourceProviderType": "Char",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "OKM ohjauksen ala",
            "dataType": "string",
            "sourceColumn": "OKM ohjauksen ala",
            "sortByColumn": "Koodit OKM ohjauksen ala",
            "sourceProviderType": "Char",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutustyyppi",
            "dataType": "string",
            "sourceColumn": "Koulutustyyppi",
            "sourceProviderType": "Char",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Sektori",
            "dataType": "string",
            "sourceColumn": "Sektori",
            "sourceProviderType": "Char",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Ammattikorkeakoulu",
            "dataType": "string",
            "sourceColumn": "Ammattikorkeakoulu",
            "sourceProviderType": "Char",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Yliopisto",
            "dataType": "string",
            "sourceColumn": "Yliopisto",
            "sourceProviderType": "Char",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "kaikki_tutk_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "kaikki_tutk_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "tki_pisteet_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "tki_pisteet_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "tki_harj_pisteet_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "tki_harj_pisteet_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "tki_muu_pisteet_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "tki_muu_pisteet_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "vierkiel_pisteet_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "vierkiel_pisteet_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "ulkom_hyv_op_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ulkom_hyv_op_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "ulkom_harj_op_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ulkom_harj_op_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "avoinamk_op_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "avoinamk_op_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "avoinamk_op_amk_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "avoinamk_op_amk_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "avoinamk_op_yliop_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "avoinamk_op_yliop_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "avoinamk_op_kesa_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "avoinamk_op_kesa_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "avoinamk_op_kansan_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "avoinamk_op_kansan_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "avoinamk_op_kansal_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "avoinamk_op_kansal_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "avoinamk_op_muut_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "avoinamk_op_muut_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "avoinop_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "avoinop_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "avoinop_amk_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "avoinop_amk_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "avoinop_yliop_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "avoinop_yliop_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "avoinop_kesa_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "avoinop_kesa_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "avoinop_kansan_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "avoinop_kansan_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "avoinop_kansal_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "avoinop_kansal_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "avoinop_muut_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "avoinop_muut_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "kv_vaihtoopiskelijat_op_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "kv_vaihtoopiskelijat_op_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "kk_yhteistyo_op_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "kk_yhteistyo_op_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "erilopintooik_op_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "erilopintooik_op_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "erillisilla_oik_opkoul_op_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "erillisilla_oik_opkoul_op_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "mamu_op_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "mamu_op_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "erikoul_suor_op_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "erikoul_suor_op_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Koodit Koulutusala 02",
            "dataType": "int64",
            "sourceColumn": "Koodit Koulutusala 02",
            "sourceProviderType": "Integer",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koodit Koulutusala 95",
            "dataType": "string",
            "sourceColumn": "Koodit Koulutusala 95",
            "sourceProviderType": "Char",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koodit OKM ohjauksen ala",
            "dataType": "string",
            "sourceColumn": "Koodit OKM ohjauksen ala",
            "sourceProviderType": "Char",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koodit Ammattikorkeakoulu",
            "dataType": "string",
            "sourceColumn": "Koodit Ammattikorkeakoulu",
            "sourceProviderType": "Char",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koodit Yliopisto",
            "dataType": "string",
            "sourceColumn": "Koodit Yliopisto",
            "sourceProviderType": "Char",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Statistikår",
            "dataType": "int64",
            "sourceColumn": "Statistikår",
            "sourceProviderType": "Integer",
            "displayFolder": "Tidsvariabler"
          },
          {
            "name": "Utbildningsområde 02",
            "dataType": "string",
            "sourceColumn": "Utbildningsområde 02",
            "sourceProviderType": "Char",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Utbildningsområde 95",
            "dataType": "string",
            "sourceColumn": "Utbildningsområde 95",
            "sourceProviderType": "Char",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "UKM-styrningsområde",
            "dataType": "string",
            "sourceColumn": "UKM-styrningsområde",
            "sourceProviderType": "Char",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Typ av utbildning",
            "dataType": "string",
            "sourceColumn": "Typ av utbildning",
            "sourceProviderType": "Char",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Sektorn",
            "dataType": "string",
            "sourceColumn": "Sektorn",
            "sourceProviderType": "Char",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Yrkeshögskola",
            "dataType": "string",
            "sourceColumn": "Yrkeshögskola",
            "sourceProviderType": "Char",
            "displayFolder": "Organisationsvariabler"
          },
          {
            "name": "Universitet",
            "dataType": "string",
            "sourceColumn": "Universitet",
            "sourceProviderType": "Char",
            "displayFolder": "Organisationsvariabler"
          },
          {
            "name": "Field of education 02",
            "dataType": "string",
            "sourceColumn": "Field of education 02",
            "sourceProviderType": "Char",
            "displayFolder": "Education variables"
          },
          {
            "name": "Field of education 95",
            "dataType": "string",
            "sourceColumn": "Field of education 95",
            "sourceProviderType": "Char",
            "displayFolder": "Education variables"
          },
          {
            "name": "Field of education - HE steering",
            "dataType": "string",
            "sourceColumn": "Field of education - HE steering",
            "sourceProviderType": "Char",
            "displayFolder": "Education variables"
          },
          {
            "name": "Type of education",
            "dataType": "string",
            "sourceColumn": "Type of education",
            "sourceProviderType": "Char",
            "displayFolder": "Education variables"
          },
          {
            "name": "Sector",
            "dataType": "string",
            "sourceColumn": "Sector",
            "sourceProviderType": "Char",
            "displayFolder": "Education variables"
          },
          {
            "name": "University of applied sciences",
            "dataType": "string",
            "sourceColumn": "University of applied sciences",
            "sourceProviderType": "Char",
            "displayFolder": "Organisation variables"
          },
          {
            "name": "University",
            "dataType": "string",
            "sourceColumn": "University",
            "sourceProviderType": "Char",
            "displayFolder": "Organisation variables"
          },
          {
            "name": "Kod Utbildningsområde 02",
            "dataType": "int64",
            "sourceColumn": "Koodit Koulutusala 02",
            "sourceProviderType": "Integer",
            "displayFolder": "Kodvariabler"
          },
          {
            "name": "Kod Utbildningsområde 95",
            "dataType": "int64",
            "sourceColumn": "Koodit Koulutusala 95",
            "sourceProviderType": "Integer",
            "displayFolder": "Kodvariabler"
          },
          {
            "name": "Kod Yrkeshögskola",
            "dataType": "string",
            "sourceColumn": "Koodit Ammattikorkeakoulu",
            "sourceProviderType": "Char",
            "displayFolder": "Kodvariabler"
          },
          {
            "name": "Kod Universitet",
            "dataType": "string",
            "sourceColumn": "Koodit Yliopisto",
            "sourceProviderType": "Char",
            "displayFolder": "Kodvariabler"
          },
          {
            "name": "Kod UKM-styrningsområde",
            "dataType": "string",
            "sourceColumn": "Koodit OKM ohjauksen ala",
            "sourceProviderType": "Char",
            "displayFolder": "Kodvariabler"
          },
          {
            "name": "Codes Field of education 02",
            "dataType": "int64",
            "sourceColumn": "Koodit Koulutusala 02",
            "sourceProviderType": "Integer",
            "displayFolder": "Code variables"
          },
          {
            "name": "Codes Field of education 95",
            "dataType": "int64",
            "sourceColumn": "Koodit Koulutusala 95",
            "sourceProviderType": "Integer",
            "displayFolder": "Code variables"
          },
          {
            "name": "Codes University of applied sciences",
            "dataType": "string",
            "sourceColumn": "Koodit Ammattikorkeakoulu",
            "sourceProviderType": "Char",
            "displayFolder": "Code variables"
          },
          {
            "name": "Codes University",
            "dataType": "string",
            "sourceColumn": "Koodit Yliopisto",
            "sourceProviderType": "Char",
            "displayFolder": "Code variables"
          },
          {
            "name": "Codes Field of education - HE steering",
            "dataType": "string",
            "sourceColumn": "Koodit OKM ohjauksen ala",
            "sourceProviderType": "Char",
            "displayFolder": "Code variables"
          },
          {
            "name": "Statistical year",
            "dataType": "int64",
            "sourceColumn": "Statistical year",
            "sourceProviderType": "Integer",
            "displayFolder": "Time variables"
          }
        ],
        "partitions": [
          {
            "name": "v_st_opintopisteet",
            "dataView": "full",
            "source": {
              "query": " SELECT [dw].[v_st_opintopisteet].* FROM [dw].[v_st_opintopisteet] ",
              "dataSource": "SqlServer dwitvipusql16 ANTERO"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>\n<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\n  <ColumnSuggestedType />\n  <ColumnFormat />\n  <ColumnAccuracy />\n  <ColumnCurrencySymbol />\n  <ColumnPositivePattern />\n  <ColumnNegativePattern />\n  <ColumnWidths>\n    <item>\n      <key>\n        <string>Tilastovuosi</string>\n      </key>\n      <value>\n        <int>123</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Koulutusala 02</string>\n      </key>\n      <value>\n        <int>143</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Koulutusala 95</string>\n      </key>\n      <value>\n        <int>143</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>OKM ohjauksen ala</string>\n      </key>\n      <value>\n        <int>174</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Koulutustyyppi</string>\n      </key>\n      <value>\n        <int>143</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Sektori</string>\n      </key>\n      <value>\n        <int>88</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Ammattikorkeakoulu</string>\n      </key>\n      <value>\n        <int>186</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Yliopisto</string>\n      </key>\n      <value>\n        <int>100</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Statistikår</string>\n      </key>\n      <value>\n        <int>108</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Utbildningsområde 02</string>\n      </key>\n      <value>\n        <int>196</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Utbildningsområde 95</string>\n      </key>\n      <value>\n        <int>196</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>UKM-styrningsområde</string>\n      </key>\n      <value>\n        <int>195</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Typ av utbildning</string>\n      </key>\n      <value>\n        <int>163</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Sektorn</string>\n      </key>\n      <value>\n        <int>93</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Yrkeshögskola</string>\n      </key>\n      <value>\n        <int>141</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Universitet</string>\n      </key>\n      <value>\n        <int>114</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Statistical year</string>\n      </key>\n      <value>\n        <int>131</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Field of education 02</string>\n      </key>\n      <value>\n        <int>187</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Field of education 95</string>\n      </key>\n      <value>\n        <int>187</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Field of education - HE steering</string>\n      </key>\n      <value>\n        <int>261</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Type of education</string>\n      </key>\n      <value>\n        <int>166</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Sector</string>\n      </key>\n      <value>\n        <int>83</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>University of applied sciences</string>\n      </key>\n      <value>\n        <int>246</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>University</string>\n      </key>\n      <value>\n        <int>109</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>kaikki_tutk_lkm</string>\n      </key>\n      <value>\n        <int>150</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>tki_pisteet_lkm</string>\n      </key>\n      <value>\n        <int>146</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>tki_harj_pisteet_lkm</string>\n      </key>\n      <value>\n        <int>183</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>tki_muu_pisteet_lkm</string>\n      </key>\n      <value>\n        <int>187</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>vierkiel_pisteet_lkm</string>\n      </key>\n      <value>\n        <int>179</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>ulkom_hyv_op_lkm</string>\n      </key>\n      <value>\n        <int>179</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>ulkom_harj_op_lkm</string>\n      </key>\n      <value>\n        <int>182</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>avoinamk_op_lkm</string>\n      </key>\n      <value>\n        <int>169</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>avoinamk_op_amk_lkm</string>\n      </key>\n      <value>\n        <int>208</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>avoinamk_op_yliop_lkm</string>\n      </key>\n      <value>\n        <int>212</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>avoinamk_op_kesa_lkm</string>\n      </key>\n      <value>\n        <int>209</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>avoinamk_op_kansan_lkm</string>\n      </key>\n      <value>\n        <int>227</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>avoinamk_op_kansal_lkm</string>\n      </key>\n      <value>\n        <int>222</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>avoinamk_op_muut_lkm</string>\n      </key>\n      <value>\n        <int>215</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>avoinop_lkm</string>\n      </key>\n      <value>\n        <int>130</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>avoinop_amk_lkm</string>\n      </key>\n      <value>\n        <int>169</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>avoinop_yliop_lkm</string>\n      </key>\n      <value>\n        <int>173</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>avoinop_kesa_lkm</string>\n      </key>\n      <value>\n        <int>170</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>avoinop_kansan_lkm</string>\n      </key>\n      <value>\n        <int>188</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>avoinop_kansal_lkm</string>\n      </key>\n      <value>\n        <int>183</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>avoinop_muut_lkm</string>\n      </key>\n      <value>\n        <int>176</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>kv_vaihtoopiskelijat_op_lkm</string>\n      </key>\n      <value>\n        <int>240</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>kk_yhteistyo_op_lkm</string>\n      </key>\n      <value>\n        <int>189</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>erilopintooik_op_lkm</string>\n      </key>\n      <value>\n        <int>189</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>erillisilla_oik_opkoul_op_lkm</string>\n      </key>\n      <value>\n        <int>245</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>mamu_op_lkm</string>\n      </key>\n      <value>\n        <int>146</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>erikoul_suor_op_lkm</string>\n      </key>\n      <value>\n        <int>189</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Koodit Koulutusala 02</string>\n      </key>\n      <value>\n        <int>193</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Koodit Koulutusala 95</string>\n      </key>\n      <value>\n        <int>193</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Koodit OKM ohjauksen ala</string>\n      </key>\n      <value>\n        <int>224</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Koodit Ammattikorkeakoulu</string>\n      </key>\n      <value>\n        <int>236</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Koodit Yliopisto</string>\n      </key>\n      <value>\n        <int>150</int>\n      </value>\n    </item>\n  </ColumnWidths>\n  <ColumnDisplayIndex>\n    <item>\n      <key>\n        <string>Tilastovuosi</string>\n      </key>\n      <value>\n        <int>0</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Koulutusala 02</string>\n      </key>\n      <value>\n        <int>1</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Koulutusala 95</string>\n      </key>\n      <value>\n        <int>2</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>OKM ohjauksen ala</string>\n      </key>\n      <value>\n        <int>3</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Koulutustyyppi</string>\n      </key>\n      <value>\n        <int>4</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Sektori</string>\n      </key>\n      <value>\n        <int>5</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Ammattikorkeakoulu</string>\n      </key>\n      <value>\n        <int>6</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Yliopisto</string>\n      </key>\n      <value>\n        <int>7</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Statistikår</string>\n      </key>\n      <value>\n        <int>8</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Utbildningsområde 02</string>\n      </key>\n      <value>\n        <int>9</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Utbildningsområde 95</string>\n      </key>\n      <value>\n        <int>10</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>UKM-styrningsområde</string>\n      </key>\n      <value>\n        <int>11</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Typ av utbildning</string>\n      </key>\n      <value>\n        <int>12</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Sektorn</string>\n      </key>\n      <value>\n        <int>13</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Yrkeshögskola</string>\n      </key>\n      <value>\n        <int>14</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Universitet</string>\n      </key>\n      <value>\n        <int>15</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Statistical year</string>\n      </key>\n      <value>\n        <int>16</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Field of education 02</string>\n      </key>\n      <value>\n        <int>17</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Field of education 95</string>\n      </key>\n      <value>\n        <int>18</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Field of education - HE steering</string>\n      </key>\n      <value>\n        <int>19</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Type of education</string>\n      </key>\n      <value>\n        <int>20</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Sector</string>\n      </key>\n      <value>\n        <int>21</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>University of applied sciences</string>\n      </key>\n      <value>\n        <int>22</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>University</string>\n      </key>\n      <value>\n        <int>23</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>kaikki_tutk_lkm</string>\n      </key>\n      <value>\n        <int>24</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>tki_pisteet_lkm</string>\n      </key>\n      <value>\n        <int>25</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>tki_harj_pisteet_lkm</string>\n      </key>\n      <value>\n        <int>26</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>tki_muu_pisteet_lkm</string>\n      </key>\n      <value>\n        <int>27</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>vierkiel_pisteet_lkm</string>\n      </key>\n      <value>\n        <int>28</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>ulkom_hyv_op_lkm</string>\n      </key>\n      <value>\n        <int>29</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>ulkom_harj_op_lkm</string>\n      </key>\n      <value>\n        <int>30</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>avoinamk_op_lkm</string>\n      </key>\n      <value>\n        <int>31</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>avoinamk_op_amk_lkm</string>\n      </key>\n      <value>\n        <int>32</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>avoinamk_op_yliop_lkm</string>\n      </key>\n      <value>\n        <int>33</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>avoinamk_op_kesa_lkm</string>\n      </key>\n      <value>\n        <int>34</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>avoinamk_op_kansan_lkm</string>\n      </key>\n      <value>\n        <int>35</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>avoinamk_op_kansal_lkm</string>\n      </key>\n      <value>\n        <int>36</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>avoinamk_op_muut_lkm</string>\n      </key>\n      <value>\n        <int>37</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>avoinop_lkm</string>\n      </key>\n      <value>\n        <int>38</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>avoinop_amk_lkm</string>\n      </key>\n      <value>\n        <int>39</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>avoinop_yliop_lkm</string>\n      </key>\n      <value>\n        <int>40</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>avoinop_kesa_lkm</string>\n      </key>\n      <value>\n        <int>41</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>avoinop_kansan_lkm</string>\n      </key>\n      <value>\n        <int>42</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>avoinop_kansal_lkm</string>\n      </key>\n      <value>\n        <int>43</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>avoinop_muut_lkm</string>\n      </key>\n      <value>\n        <int>44</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>kv_vaihtoopiskelijat_op_lkm</string>\n      </key>\n      <value>\n        <int>45</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>kk_yhteistyo_op_lkm</string>\n      </key>\n      <value>\n        <int>46</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>erilopintooik_op_lkm</string>\n      </key>\n      <value>\n        <int>47</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>erillisilla_oik_opkoul_op_lkm</string>\n      </key>\n      <value>\n        <int>48</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>mamu_op_lkm</string>\n      </key>\n      <value>\n        <int>49</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>erikoul_suor_op_lkm</string>\n      </key>\n      <value>\n        <int>50</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Koodit Koulutusala 02</string>\n      </key>\n      <value>\n        <int>51</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Koodit Koulutusala 95</string>\n      </key>\n      <value>\n        <int>52</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Koodit OKM ohjauksen ala</string>\n      </key>\n      <value>\n        <int>53</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Koodit Ammattikorkeakoulu</string>\n      </key>\n      <value>\n        <int>54</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Koodit Yliopisto</string>\n      </key>\n      <value>\n        <int>55</int>\n      </value>\n    </item>\n  </ColumnDisplayIndex>\n  <ColumnFrozen />\n  <ColumnChecked>\n    <item>\n      <key>\n        <string>Statistikår</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Utbildningsområde 02</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Utbildningsområde 95</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>UKM-styrningsområde</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Typ av utbildning</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Sektorn</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Yrkeshögskola</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Universitet</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Statistical year</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Field of education 02</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Field of education 95</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Field of education - HE steering</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Type of education</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Sector</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>University of applied sciences</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>University</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n  </ColumnChecked>\n  <ColumnFilter />\n  <SelectionFilter />\n  <FilterParameters />\n  <IsSortDescending>false</IsSortDescending>\n</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Kaikki perustutkinto-opiskelijoiden opintopisteet",
            "expression": "if(sum([kaikki_tutk_lkm])=0,blank(),sum([kaikki_tutk_lkm])\n)",
            "formatString": "#,0"
          },
          {
            "name": "TKI opintopisteet (opinnäytetyöt)",
            "expression": "if(sum(Muuttujat[tki_pisteet_lkm])=0,blank(),sum(Muuttujat[tki_pisteet_lkm])\n)",
            "formatString": "#,0"
          },
          {
            "name": "TKI opintopisteet (harjoittelu)",
            "expression": "if(sum([tki_harj_pisteet_lkm])=0,blank(),sum([tki_harj_pisteet_lkm])\n)",
            "formatString": "#,0"
          },
          {
            "name": "TKI opintopisteet (muu)",
            "expression": "if(sum([tki_muu_pisteet_lkm])=0,blank(),sum([tki_muu_pisteet_lkm])\n)",
            "formatString": "#,0"
          },
          {
            "name": "Vieraskielisen opetuksen opintopisteet",
            "expression": "if(sum(Muuttujat[vierkiel_pisteet_lkm])=0,blank(),sum(Muuttujat[vierkiel_pisteet_lkm])\n)",
            "formatString": "#,0"
          },
          {
            "name": "Ulkomailta hyväksiluetut opintopisteet",
            "expression": "if(sum(Muuttujat[ulkom_hyv_op_lkm])=0,blank(),sum(Muuttujat[ulkom_hyv_op_lkm])\n)",
            "formatString": "#,0"
          },
          {
            "name": "Avoimen amk-opetuksen opintopisteet",
            "expression": "if(sum([avoinamk_op_lkm])=0,blank(),sum([avoinamk_op_lkm]))",
            "formatString": "#,0"
          },
          {
            "name": "Erillisten opinto-oikeuksien opintopisteet",
            "expression": "if(sum([erilopintooik_op_lkm])=0,blank(),sum([erilopintooik_op_lkm])\n)",
            "formatString": "#,0"
          },
          {
            "name": "Korkeakoulujen välisten yhteistyösopimusten opintopisteet",
            "expression": "if(sum([kk_yhteistyo_op_lkm])=0,blank(),sum([kk_yhteistyo_op_lkm])\n)",
            "formatString": "#,0"
          },
          {
            "name": "Saapuvien vaihto-opiskelijoiden opintopisteet",
            "expression": "if(sum([kv_vaihtoopiskelijat_op_lkm])=0,blank(),sum([kv_vaihtoopiskelijat_op_lkm])\n)",
            "formatString": "#,0"
          },
          {
            "name": "Maahanmuuttajien valmentavan koulutuksen opintopisteet",
            "expression": "if(sum([mamu_op_lkm])=0,blank(),sum([mamu_op_lkm])\n)",
            "formatString": "#,0"
          },
          {
            "name": "Avoimen korkeakouluopetuksen opintopisteet",
            "expression": "if(sum([avoinop_lkm])=0,blank(),sum([avoinop_lkm])\n)",
            "formatString": "#,0"
          },
          {
            "name": "Erillisten opinto-oikeuksien opintopisteet (pl. opettajankoulutus)",
            "expression": "if(sum([erilopintooik_op_lkm])=0,blank(),sum([erilopintooik_op_lkm])\n)",
            "formatString": "#,0"
          },
          {
            "name": "Erillisten opinto-oikeuksien opettajankoulutuksen opintopisteet",
            "expression": "if(sum([erillisilla_oik_opkoul_op_lkm])=0,blank(),sum([erillisilla_oik_opkoul_op_lkm])\n)",
            "formatString": "#,0"
          },
          {
            "name": "Yliopistojen järjestämän avoimen korkeakouluopetuksen opintopisteet",
            "expression": "if(sum([avoinop_yliop_lkm])=0,blank(),sum([avoinop_yliop_lkm]))",
            "formatString": "#,0"
          },
          {
            "name": "Ammattikorkeakoulujen järjestämän avoimen korkeakouluopetuksen opintopisteet",
            "expression": "if(sum([avoinop_amk_lkm])=0,blank(),sum([avoinop_amk_lkm]))",
            "formatString": "#,0"
          },
          {
            "name": "Kansalaisopistojen järjestämän avoimen korkeakouluopetuksen opintopisteet",
            "expression": "if(sum([avoinop_kansal_lkm])=0,blank(),sum([avoinop_kansal_lkm]))",
            "formatString": "#,0"
          },
          {
            "name": "Kansanopistojen järjestämän avoimen korkeakouluopetuksen opintopisteet",
            "expression": "if(sum([avoinop_kansan_lkm])=0,blank(),sum([avoinop_kansan_lkm]))",
            "formatString": "#,0"
          },
          {
            "name": "Kesäyliopistojen järjestämän avoimen korkeakouluopetuksen opintopisteet",
            "expression": "if(sum([avoinop_kesa_lkm])=0,blank(),sum([avoinop_kesa_lkm]))",
            "formatString": "#,0"
          },
          {
            "name": "Muiden järjestäjien avoimen korkeakouluopetuksen opintopisteet",
            "expression": "if(sum([avoinop_muut_lkm])=0,blank(),sum([avoinop_muut_lkm]))",
            "formatString": "#,0"
          },
          {
            "name": "Ulkomaisen harjoittelun opintopisteet",
            "expression": "if(sum(Muuttujat[ulkom_harj_op_lkm])=0,blank(),sum(Muuttujat[ulkom_harj_op_lkm]))",
            "formatString": "#,0"
          },
          {
            "name": "Erikoistumiskoulutuksessa suoritetut opintopisteet",
            "expression": "IF(SUM([erikoul_suor_op_lkm])=0,BLANK(),SUM([erikoul_suor_op_lkm]))",
            "formatString": "#,0"
          },
          {
            "name": "FUI studiepoäng (andra)",
            "expression": "if(sum([tki_muu_pisteet_lkm])=0,blank(),sum([tki_muu_pisteet_lkm])\n)",
            "formatString": "#,0"
          },
          {
            "name": "FUI studiepoäng (lärdomsprov)",
            "expression": "if(sum(Muuttujat[tki_pisteet_lkm])=0,blank(),sum(Muuttujat[tki_pisteet_lkm])\n)",
            "formatString": "#,0"
          },
          {
            "name": "FUI studiepoäng (praktik)",
            "expression": "if(sum([tki_harj_pisteet_lkm])=0,blank(),sum([tki_harj_pisteet_lkm])\n)",
            "formatString": "#,0"
          },
          {
            "name": "Studiepoäng i undervisning i främmande språk",
            "expression": "if(sum(Muuttujat[vierkiel_pisteet_lkm])=0,blank(),sum(Muuttujat[vierkiel_pisteet_lkm])\n)",
            "formatString": "#,0"
          },
          {
            "name": "Studiepoäng från utlandet som tillgodoräknats",
            "expression": "if(sum(Muuttujat[ulkom_hyv_op_lkm])=0,blank(),sum(Muuttujat[ulkom_hyv_op_lkm])\n)",
            "formatString": "#,0"
          },
          {
            "name": "Studiepoäng från praktik på utomlands",
            "expression": "if(sum(Muuttujat[ulkom_harj_op_lkm])=0,blank(),sum(Muuttujat[ulkom_harj_op_lkm]))",
            "formatString": "#,0"
          },
          {
            "name": "Studiepoäng i öppen yrkeshögskoleundervisning",
            "expression": "if(sum([avoinamk_op_lkm])=0,blank(),sum([avoinamk_op_lkm])\n)",
            "formatString": "#,0"
          },
          {
            "name": "Studiepoäng i handledande utbildning för invandrare",
            "expression": "if(sum([mamu_op_lkm])=0,blank(),sum([mamu_op_lkm])\n)",
            "formatString": "#,0"
          },
          {
            "name": "Studiepoäng för utbytesstudenter som anländer",
            "expression": "if(sum([kv_vaihtoopiskelijat_op_lkm])=0,blank(),sum([kv_vaihtoopiskelijat_op_lkm])\n)",
            "formatString": "#,0"
          },
          {
            "name": "Studiepoäng från specialiseringsutbildning",
            "expression": "IF(SUM([erikoul_suor_op_lkm])=0,BLANK(),SUM([erikoul_suor_op_lkm]))",
            "formatString": "#,0"
          },
          {
            "name": "RDI credits (internships)",
            "expression": "if(sum([tki_harj_pisteet_lkm])=0,blank(),sum([tki_harj_pisteet_lkm])\n)",
            "formatString": "#,0"
          },
          {
            "name": "RDI credits (other)",
            "expression": "if(sum([tki_muu_pisteet_lkm])=0,blank(),sum([tki_muu_pisteet_lkm])\n)",
            "formatString": "#,0"
          },
          {
            "name": "RDI credits (final projects)",
            "expression": "if(sum(Muuttujat[tki_pisteet_lkm])=0,blank(),sum(Muuttujat[tki_pisteet_lkm])\n)",
            "formatString": "#,0"
          },
          {
            "name": "Credits transferred from studies abroad",
            "expression": "if(sum(Muuttujat[ulkom_hyv_op_lkm])=0,blank(),sum(Muuttujat[ulkom_hyv_op_lkm])\n)",
            "formatString": "#,0"
          },
          {
            "name": "Credits for courses taught in a foreign language",
            "expression": "if(sum(Muuttujat[vierkiel_pisteet_lkm])=0,blank(),sum(Muuttujat[vierkiel_pisteet_lkm])\n)",
            "formatString": "#,0"
          },
          {
            "name": "Credits for foreign internships",
            "expression": "if(sum(Muuttujat[ulkom_harj_op_lkm])=0,blank(),sum(Muuttujat[ulkom_harj_op_lkm]))",
            "formatString": "#,0"
          },
          {
            "name": "Credits attained in open UAS education",
            "expression": "if(sum([avoinamk_op_lkm])=0,blank(),sum([avoinamk_op_lkm])\n)",
            "formatString": "#,0"
          },
          {
            "name": "Credits attained through the right to study individual courses (UAS)",
            "expression": "if(sum([erilopintooik_op_lkm])=0,blank(),sum([erilopintooik_op_lkm])\n)",
            "formatString": "#,0"
          },
          {
            "name": "Credits attained in ed. based on cooperative contracts between higher ed. instit",
            "expression": "if(sum([kk_yhteistyo_op_lkm])=0,blank(),sum([kk_yhteistyo_op_lkm])\n)",
            "formatString": "#,0"
          },
          {
            "name": "Credits attained in preparatory training for migrants",
            "expression": "if(sum([mamu_op_lkm])=0,blank(),sum([mamu_op_lkm])\n)",
            "formatString": "#,0"
          },
          {
            "name": "Credits attained by incoming exchange students",
            "expression": "if(sum([kv_vaihtoopiskelijat_op_lkm])=0,blank(),sum([kv_vaihtoopiskelijat_op_lkm])\n)",
            "formatString": "#,0"
          },
          {
            "name": "Credits attained in professional specialisation education",
            "expression": "IF(SUM([erikoul_suor_op_lkm])=0,BLANK(),SUM([erikoul_suor_op_lkm]))",
            "formatString": "#,0"
          },
          {
            "name": "Samtliga grundexamenstuderandes studiepoäng",
            "expression": "if(sum([kaikki_tutk_lkm])=0,blank(),sum([kaikki_tutk_lkm])\n)",
            "formatString": "#,0"
          },
          {
            "name": "Studiepoäng för särskilda studierättigheter",
            "expression": "if(sum([erilopintooik_op_lkm])=0,blank(),sum([erilopintooik_op_lkm])\n)",
            "formatString": "#,0"
          },
          {
            "name": "Studiepoäng enligt samarbetsavtal mellan högskolor",
            "expression": "if(sum([kk_yhteistyo_op_lkm])=0,blank(),sum([kk_yhteistyo_op_lkm])\n)",
            "formatString": "#,0"
          },
          {
            "name": "Lärarutbildning, studiepoäng för särskilda studierättigheter",
            "expression": "if(sum([erillisilla_oik_opkoul_op_lkm])=0,blank(),sum([erillisilla_oik_opkoul_op_lkm])\n)",
            "formatString": "#,0"
          },
          {
            "name": "Studiepoäng för särskilda studierättigheter (exkl. lärarutbildning)",
            "expression": "if(sum([erilopintooik_op_lkm])=0,blank(),sum([erilopintooik_op_lkm])\n)",
            "formatString": "#,0"
          },
          {
            "name": "Studiepoäng i öppen högskoleundervisning",
            "expression": "if(sum([avoinop_lkm])=0,blank(),sum([avoinop_lkm])\n)",
            "formatString": "#,0"
          },
          {
            "name": "Studiepoäng i öppen högre utbildning som yrkehögskolor ordnar",
            "expression": "if(sum([avoinop_amk_lkm])=0,blank(),sum([avoinop_amk_lkm]))",
            "formatString": "#,0"
          },
          {
            "name": "Studiepoäng i öppen högre utbildning som medborgarinstituten ordnar",
            "expression": "if(sum([avoinop_kansal_lkm])=0,blank(),sum([avoinop_kansal_lkm]))",
            "formatString": "#,0"
          },
          {
            "name": "Studiepoäng i öppen högre utbildning som sommar universiteten ordnar",
            "expression": "if(sum([avoinop_kesa_lkm])=0,blank(),sum([avoinop_kesa_lkm]))",
            "formatString": "#,0"
          },
          {
            "name": "Studiepoäng i öppen högre utbildning som folkhögskolor ordnar",
            "expression": "if(sum([avoinop_kansan_lkm])=0,blank(),sum([avoinop_kansan_lkm]))",
            "formatString": "#,0"
          },
          {
            "name": "Studiepoäng i öppen högre utbildning som andra organisatörer ordnar",
            "expression": "if(sum([avoinop_muut_lkm])=0,blank(),sum([avoinop_muut_lkm]))",
            "formatString": "#,0"
          },
          {
            "name": "Studiepoäng i öppen högre utbildning som universiteten ordnar",
            "expression": "if(sum([avoinop_yliop_lkm])=0,blank(),sum([avoinop_yliop_lkm]))",
            "formatString": "#,0"
          },
          {
            "name": "All credits attained by students pursuing an undergraduate degree",
            "expression": "if(sum([kaikki_tutk_lkm])=0,blank(),sum([kaikki_tutk_lkm])\n)",
            "formatString": "#,0"
          },
          {
            "name": "Credits attained in open higher education",
            "expression": "if(sum([avoinop_lkm])=0,blank(),sum([avoinop_lkm])\n)",
            "formatString": "#,0"
          },
          {
            "name": "Teacher education, credits attained through the right to study individual courses",
            "expression": "if(sum([erillisilla_oik_opkoul_op_lkm])=0,blank(),sum([erillisilla_oik_opkoul_op_lkm])\n)",
            "formatString": "#,0"
          },
          {
            "name": "Credits attained through the right to study individual courses (excl. teacher education)",
            "expression": "if(sum([erilopintooik_op_lkm])=0,blank(),sum([erilopintooik_op_lkm])\n)",
            "formatString": "#,0"
          },
          {
            "name": "Credits attained in open higher education organized by universities",
            "expression": "if(sum([avoinop_yliop_lkm])=0,blank(),sum([avoinop_yliop_lkm]))",
            "formatString": "#,0"
          },
          {
            "name": "Credits attained in open higher education organized by universities of applied sciences",
            "expression": "if(sum([avoinop_amk_lkm])=0,blank(),sum([avoinop_amk_lkm]))",
            "formatString": "#,0"
          },
          {
            "name": "Credits attained in open higher education organized by adult education centres",
            "expression": "if(sum([avoinop_kansal_lkm])=0,blank(),sum([avoinop_kansal_lkm]))",
            "formatString": "#,0"
          },
          {
            "name": "Credits attained in open higher education organized by folk high schools",
            "expression": "if(sum([avoinop_kansan_lkm])=0,blank(),sum([avoinop_kansan_lkm]))",
            "formatString": "#,0"
          },
          {
            "name": "Credits attained in open higher education organized by summer universities",
            "expression": "if(sum([avoinop_kesa_lkm])=0,blank(),sum([avoinop_kesa_lkm]))",
            "formatString": "#,0"
          },
          {
            "name": "Credits attained in open higher education organized by other providers",
            "expression": "if(sum([avoinop_muut_lkm])=0,blank(),sum([avoinop_muut_lkm]))",
            "formatString": "#,0"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dw].[v_st_opintopisteet].* FROM [dw].[v_st_opintopisteet] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "v_st_opintopisteet"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dw"
          },
          {
            "name": "TableWidgetSerialization",
            "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>\n<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\n  <ColumnSuggestedType />\n  <ColumnFormat />\n  <ColumnAccuracy />\n  <ColumnCurrencySymbol />\n  <ColumnPositivePattern />\n  <ColumnNegativePattern />\n  <ColumnWidths>\n    <item>\n      <key>\n        <string>Tilastovuosi</string>\n      </key>\n      <value>\n        <int>123</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Koulutusala 02</string>\n      </key>\n      <value>\n        <int>143</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Koulutusala 95</string>\n      </key>\n      <value>\n        <int>143</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>OKM ohjauksen ala</string>\n      </key>\n      <value>\n        <int>174</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Koulutustyyppi</string>\n      </key>\n      <value>\n        <int>143</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Sektori</string>\n      </key>\n      <value>\n        <int>88</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Ammattikorkeakoulu</string>\n      </key>\n      <value>\n        <int>186</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Yliopisto</string>\n      </key>\n      <value>\n        <int>100</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Statistikår</string>\n      </key>\n      <value>\n        <int>108</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Utbildningsområde 02</string>\n      </key>\n      <value>\n        <int>196</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Utbildningsområde 95</string>\n      </key>\n      <value>\n        <int>196</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>UKM-styrningsområde</string>\n      </key>\n      <value>\n        <int>195</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Typ av utbildning</string>\n      </key>\n      <value>\n        <int>163</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Sektorn</string>\n      </key>\n      <value>\n        <int>93</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Yrkeshögskola</string>\n      </key>\n      <value>\n        <int>141</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Universitet</string>\n      </key>\n      <value>\n        <int>114</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Statistical year</string>\n      </key>\n      <value>\n        <int>131</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Field of education 02</string>\n      </key>\n      <value>\n        <int>187</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Field of education 95</string>\n      </key>\n      <value>\n        <int>187</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Field of education - HE steering</string>\n      </key>\n      <value>\n        <int>261</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Type of education</string>\n      </key>\n      <value>\n        <int>166</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Sector</string>\n      </key>\n      <value>\n        <int>83</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>University of applied sciences</string>\n      </key>\n      <value>\n        <int>246</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>University</string>\n      </key>\n      <value>\n        <int>109</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>kaikki_tutk_lkm</string>\n      </key>\n      <value>\n        <int>150</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>tki_pisteet_lkm</string>\n      </key>\n      <value>\n        <int>146</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>tki_harj_pisteet_lkm</string>\n      </key>\n      <value>\n        <int>183</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>tki_muu_pisteet_lkm</string>\n      </key>\n      <value>\n        <int>187</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>vierkiel_pisteet_lkm</string>\n      </key>\n      <value>\n        <int>179</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>ulkom_hyv_op_lkm</string>\n      </key>\n      <value>\n        <int>179</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>ulkom_harj_op_lkm</string>\n      </key>\n      <value>\n        <int>182</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>avoinamk_op_lkm</string>\n      </key>\n      <value>\n        <int>169</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>avoinamk_op_amk_lkm</string>\n      </key>\n      <value>\n        <int>208</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>avoinamk_op_yliop_lkm</string>\n      </key>\n      <value>\n        <int>212</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>avoinamk_op_kesa_lkm</string>\n      </key>\n      <value>\n        <int>209</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>avoinamk_op_kansan_lkm</string>\n      </key>\n      <value>\n        <int>227</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>avoinamk_op_kansal_lkm</string>\n      </key>\n      <value>\n        <int>222</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>avoinamk_op_muut_lkm</string>\n      </key>\n      <value>\n        <int>215</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>avoinop_lkm</string>\n      </key>\n      <value>\n        <int>130</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>avoinop_amk_lkm</string>\n      </key>\n      <value>\n        <int>169</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>avoinop_yliop_lkm</string>\n      </key>\n      <value>\n        <int>173</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>avoinop_kesa_lkm</string>\n      </key>\n      <value>\n        <int>170</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>avoinop_kansan_lkm</string>\n      </key>\n      <value>\n        <int>188</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>avoinop_kansal_lkm</string>\n      </key>\n      <value>\n        <int>183</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>avoinop_muut_lkm</string>\n      </key>\n      <value>\n        <int>176</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>kv_vaihtoopiskelijat_op_lkm</string>\n      </key>\n      <value>\n        <int>240</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>kk_yhteistyo_op_lkm</string>\n      </key>\n      <value>\n        <int>189</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>erilopintooik_op_lkm</string>\n      </key>\n      <value>\n        <int>189</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>erillisilla_oik_opkoul_op_lkm</string>\n      </key>\n      <value>\n        <int>245</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>mamu_op_lkm</string>\n      </key>\n      <value>\n        <int>146</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>erikoul_suor_op_lkm</string>\n      </key>\n      <value>\n        <int>189</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Koodit Koulutusala 02</string>\n      </key>\n      <value>\n        <int>193</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Koodit Koulutusala 95</string>\n      </key>\n      <value>\n        <int>193</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Koodit OKM ohjauksen ala</string>\n      </key>\n      <value>\n        <int>224</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Koodit Ammattikorkeakoulu</string>\n      </key>\n      <value>\n        <int>236</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Koodit Yliopisto</string>\n      </key>\n      <value>\n        <int>150</int>\n      </value>\n    </item>\n  </ColumnWidths>\n  <ColumnDisplayIndex>\n    <item>\n      <key>\n        <string>Tilastovuosi</string>\n      </key>\n      <value>\n        <int>0</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Koulutusala 02</string>\n      </key>\n      <value>\n        <int>1</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Koulutusala 95</string>\n      </key>\n      <value>\n        <int>2</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>OKM ohjauksen ala</string>\n      </key>\n      <value>\n        <int>3</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Koulutustyyppi</string>\n      </key>\n      <value>\n        <int>4</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Sektori</string>\n      </key>\n      <value>\n        <int>5</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Ammattikorkeakoulu</string>\n      </key>\n      <value>\n        <int>6</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Yliopisto</string>\n      </key>\n      <value>\n        <int>7</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Statistikår</string>\n      </key>\n      <value>\n        <int>8</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Utbildningsområde 02</string>\n      </key>\n      <value>\n        <int>9</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Utbildningsområde 95</string>\n      </key>\n      <value>\n        <int>10</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>UKM-styrningsområde</string>\n      </key>\n      <value>\n        <int>11</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Typ av utbildning</string>\n      </key>\n      <value>\n        <int>12</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Sektorn</string>\n      </key>\n      <value>\n        <int>13</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Yrkeshögskola</string>\n      </key>\n      <value>\n        <int>14</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Universitet</string>\n      </key>\n      <value>\n        <int>15</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Statistical year</string>\n      </key>\n      <value>\n        <int>16</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Field of education 02</string>\n      </key>\n      <value>\n        <int>17</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Field of education 95</string>\n      </key>\n      <value>\n        <int>18</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Field of education - HE steering</string>\n      </key>\n      <value>\n        <int>19</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Type of education</string>\n      </key>\n      <value>\n        <int>20</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Sector</string>\n      </key>\n      <value>\n        <int>21</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>University of applied sciences</string>\n      </key>\n      <value>\n        <int>22</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>University</string>\n      </key>\n      <value>\n        <int>23</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>kaikki_tutk_lkm</string>\n      </key>\n      <value>\n        <int>24</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>tki_pisteet_lkm</string>\n      </key>\n      <value>\n        <int>25</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>tki_harj_pisteet_lkm</string>\n      </key>\n      <value>\n        <int>26</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>tki_muu_pisteet_lkm</string>\n      </key>\n      <value>\n        <int>27</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>vierkiel_pisteet_lkm</string>\n      </key>\n      <value>\n        <int>28</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>ulkom_hyv_op_lkm</string>\n      </key>\n      <value>\n        <int>29</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>ulkom_harj_op_lkm</string>\n      </key>\n      <value>\n        <int>30</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>avoinamk_op_lkm</string>\n      </key>\n      <value>\n        <int>31</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>avoinamk_op_amk_lkm</string>\n      </key>\n      <value>\n        <int>32</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>avoinamk_op_yliop_lkm</string>\n      </key>\n      <value>\n        <int>33</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>avoinamk_op_kesa_lkm</string>\n      </key>\n      <value>\n        <int>34</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>avoinamk_op_kansan_lkm</string>\n      </key>\n      <value>\n        <int>35</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>avoinamk_op_kansal_lkm</string>\n      </key>\n      <value>\n        <int>36</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>avoinamk_op_muut_lkm</string>\n      </key>\n      <value>\n        <int>37</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>avoinop_lkm</string>\n      </key>\n      <value>\n        <int>38</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>avoinop_amk_lkm</string>\n      </key>\n      <value>\n        <int>39</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>avoinop_yliop_lkm</string>\n      </key>\n      <value>\n        <int>40</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>avoinop_kesa_lkm</string>\n      </key>\n      <value>\n        <int>41</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>avoinop_kansan_lkm</string>\n      </key>\n      <value>\n        <int>42</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>avoinop_kansal_lkm</string>\n      </key>\n      <value>\n        <int>43</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>avoinop_muut_lkm</string>\n      </key>\n      <value>\n        <int>44</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>kv_vaihtoopiskelijat_op_lkm</string>\n      </key>\n      <value>\n        <int>45</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>kk_yhteistyo_op_lkm</string>\n      </key>\n      <value>\n        <int>46</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>erilopintooik_op_lkm</string>\n      </key>\n      <value>\n        <int>47</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>erillisilla_oik_opkoul_op_lkm</string>\n      </key>\n      <value>\n        <int>48</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>mamu_op_lkm</string>\n      </key>\n      <value>\n        <int>49</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>erikoul_suor_op_lkm</string>\n      </key>\n      <value>\n        <int>50</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Koodit Koulutusala 02</string>\n      </key>\n      <value>\n        <int>51</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Koodit Koulutusala 95</string>\n      </key>\n      <value>\n        <int>52</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Koodit OKM ohjauksen ala</string>\n      </key>\n      <value>\n        <int>53</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Koodit Ammattikorkeakoulu</string>\n      </key>\n      <value>\n        <int>54</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Koodit Yliopisto</string>\n      </key>\n      <value>\n        <int>55</int>\n      </value>\n    </item>\n  </ColumnDisplayIndex>\n  <ColumnFrozen />\n  <ColumnChecked>\n    <item>\n      <key>\n        <string>Statistikår</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Utbildningsområde 02</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Utbildningsområde 95</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>UKM-styrningsområde</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Typ av utbildning</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Sektorn</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Yrkeshögskola</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Universitet</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Statistical year</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Field of education 02</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Field of education 95</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Field of education - HE steering</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Type of education</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Sector</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>University of applied sciences</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>University</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n  </ColumnChecked>\n  <ColumnFilter />\n  <SelectionFilter />\n  <FilterParameters />\n  <IsSortDescending>false</IsSortDescending>\n</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
          }
        ]
      }
    ],
    "cultures": [
      {
        "name": "en-US",
        "translations": {
          "model": {
            "name": "Model",
            "tables": [
              {
                "name": "Muuttujat",
                "translatedCaption": "Variables"
              }
            ]
          }
        }
      },
      {
        "name": "sv-SE",
        "translations": {
          "model": {
            "name": "Model",
            "tables": [
              {
                "name": "Muuttujat",
                "translatedCaption": "Variabler"
              }
            ]
          }
        }
      }
    ],
    "perspectives": [
      {
        "name": "yo_tutkinto",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Koodit Koulutusala 95"
              },
              {
                "name": "Koodit OKM ohjauksen ala"
              },
              {
                "name": "Koodit Yliopisto"
              },
              {
                "name": "Koulutusala 95"
              },
              {
                "name": "OKM ohjauksen ala"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Yliopisto"
              },
              {
                "name": "Sektori"
              }
            ],
            "measures": [
              {
                "name": "Kaikki perustutkinto-opiskelijoiden opintopisteet"
              },
              {
                "name": "Ulkomailta hyväksiluetut opintopisteet"
              },
              {
                "name": "Vieraskielisen opetuksen opintopisteet"
              },
              {
                "name": "Ulkomaisen harjoittelun opintopisteet"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "yo_muut",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Koodit Koulutusala 95"
              },
              {
                "name": "Koodit OKM ohjauksen ala"
              },
              {
                "name": "Koodit Yliopisto"
              },
              {
                "name": "Koulutusala 95"
              },
              {
                "name": "OKM ohjauksen ala"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Yliopisto"
              },
              {
                "name": "Sektori"
              }
            ],
            "measures": [
              {
                "name": "Avoimen korkeakouluopetuksen opintopisteet"
              },
              {
                "name": "Erillisten opinto-oikeuksien opettajankoulutuksen opintopisteet"
              },
              {
                "name": "Erillisten opinto-oikeuksien opintopisteet (pl. opettajankoulutus)"
              },
              {
                "name": "Korkeakoulujen välisten yhteistyösopimusten opintopisteet"
              },
              {
                "name": "Saapuvien vaihto-opiskelijoiden opintopisteet"
              },
              {
                "name": "Erikoistumiskoulutuksessa suoritetut opintopisteet"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "amk_tutkinto",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Ammattikorkeakoulu"
              },
              {
                "name": "Koodit Ammattikorkeakoulu"
              },
              {
                "name": "Koodit Koulutusala 02"
              },
              {
                "name": "Koodit OKM ohjauksen ala"
              },
              {
                "name": "Koulutusala 02"
              },
              {
                "name": "Koulutustyyppi"
              },
              {
                "name": "OKM ohjauksen ala"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Sektori"
              }
            ],
            "measures": [
              {
                "name": "Kaikki perustutkinto-opiskelijoiden opintopisteet"
              },
              {
                "name": "TKI opintopisteet (harjoittelu)"
              },
              {
                "name": "TKI opintopisteet (muu)"
              },
              {
                "name": "TKI opintopisteet (opinnäytetyöt)"
              },
              {
                "name": "Ulkomailta hyväksiluetut opintopisteet"
              },
              {
                "name": "Vieraskielisen opetuksen opintopisteet"
              },
              {
                "name": "Ulkomaisen harjoittelun opintopisteet"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "amk_muut",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Ammattikorkeakoulu"
              },
              {
                "name": "Koodit Ammattikorkeakoulu"
              },
              {
                "name": "Koodit Koulutusala 02"
              },
              {
                "name": "Koodit OKM ohjauksen ala"
              },
              {
                "name": "Koulutusala 02"
              },
              {
                "name": "Koulutustyyppi"
              },
              {
                "name": "OKM ohjauksen ala"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Sektori"
              }
            ],
            "measures": [
              {
                "name": "Avoimen amk-opetuksen opintopisteet"
              },
              {
                "name": "Erillisten opinto-oikeuksien opintopisteet"
              },
              {
                "name": "Korkeakoulujen välisten yhteistyösopimusten opintopisteet"
              },
              {
                "name": "Maahanmuuttajien valmentavan koulutuksen opintopisteet"
              },
              {
                "name": "Saapuvien vaihto-opiskelijoiden opintopisteet"
              },
              {
                "name": "Erikoistumiskoulutuksessa suoritetut opintopisteet"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "yo_avoin",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Koodit Koulutusala 95"
              },
              {
                "name": "Koodit OKM ohjauksen ala"
              },
              {
                "name": "Koodit Yliopisto"
              },
              {
                "name": "Koulutusala 95"
              },
              {
                "name": "OKM ohjauksen ala"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Yliopisto"
              },
              {
                "name": "Sektori"
              }
            ],
            "measures": [
              {
                "name": "Ammattikorkeakoulujen järjestämän avoimen korkeakouluopetuksen opintopisteet"
              },
              {
                "name": "Kansalaisopistojen järjestämän avoimen korkeakouluopetuksen opintopisteet"
              },
              {
                "name": "Kansanopistojen järjestämän avoimen korkeakouluopetuksen opintopisteet"
              },
              {
                "name": "Kesäyliopistojen järjestämän avoimen korkeakouluopetuksen opintopisteet"
              },
              {
                "name": "Muiden järjestäjien avoimen korkeakouluopetuksen opintopisteet"
              },
              {
                "name": "Yliopistojen järjestämän avoimen korkeakouluopetuksen opintopisteet"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "yo_analyysi",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Koodit Koulutusala 95"
              },
              {
                "name": "Koodit OKM ohjauksen ala"
              },
              {
                "name": "Koodit Yliopisto"
              },
              {
                "name": "Koulutusala 95"
              },
              {
                "name": "OKM ohjauksen ala"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Yliopisto"
              },
              {
                "name": "Sektori"
              }
            ],
            "measures": [
              {
                "name": "Avoimen korkeakouluopetuksen opintopisteet"
              },
              {
                "name": "Erillisten opinto-oikeuksien opintopisteet (pl. opettajankoulutus)"
              },
              {
                "name": "Kaikki perustutkinto-opiskelijoiden opintopisteet"
              },
              {
                "name": "Korkeakoulujen välisten yhteistyösopimusten opintopisteet"
              },
              {
                "name": "Saapuvien vaihto-opiskelijoiden opintopisteet"
              },
              {
                "name": "Ulkomailta hyväksiluetut opintopisteet"
              },
              {
                "name": "Ulkomaisen harjoittelun opintopisteet"
              },
              {
                "name": "Vieraskielisen opetuksen opintopisteet"
              },
              {
                "name": "Erillisten opinto-oikeuksien opettajankoulutuksen opintopisteet"
              },
              {
                "name": "Erikoistumiskoulutuksessa suoritetut opintopisteet"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "amk_analyysi",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Ammattikorkeakoulu"
              },
              {
                "name": "Koodit Ammattikorkeakoulu"
              },
              {
                "name": "Koodit Koulutusala 02"
              },
              {
                "name": "Koodit OKM ohjauksen ala"
              },
              {
                "name": "Koulutusala 02"
              },
              {
                "name": "Koulutustyyppi"
              },
              {
                "name": "OKM ohjauksen ala"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Sektori"
              }
            ],
            "measures": [
              {
                "name": "Avoimen amk-opetuksen opintopisteet"
              },
              {
                "name": "Erillisten opinto-oikeuksien opintopisteet"
              },
              {
                "name": "Kaikki perustutkinto-opiskelijoiden opintopisteet"
              },
              {
                "name": "Korkeakoulujen välisten yhteistyösopimusten opintopisteet"
              },
              {
                "name": "Maahanmuuttajien valmentavan koulutuksen opintopisteet"
              },
              {
                "name": "Saapuvien vaihto-opiskelijoiden opintopisteet"
              },
              {
                "name": "TKI opintopisteet (harjoittelu)"
              },
              {
                "name": "TKI opintopisteet (muu)"
              },
              {
                "name": "TKI opintopisteet (opinnäytetyöt)"
              },
              {
                "name": "Ulkomailta hyväksiluetut opintopisteet"
              },
              {
                "name": "Ulkomaisen harjoittelun opintopisteet"
              },
              {
                "name": "Vieraskielisen opetuksen opintopisteet"
              },
              {
                "name": "Erikoistumiskoulutuksessa suoritetut opintopisteet"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "amk_tutkinto_sv",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Yrkeshögskola"
              },
              {
                "name": "Utbildningsområde 02"
              },
              {
                "name": "Typ av utbildning"
              },
              {
                "name": "UKM-styrningsområde"
              },
              {
                "name": "Statistikår"
              },
              {
                "name": "Kod Yrkeshögskola"
              },
              {
                "name": "Kod Utbildningsområde 02"
              },
              {
                "name": "Kod UKM-styrningsområde"
              },
              {
                "name": "Sektorn"
              }
            ],
            "measures": [
              {
                "name": "FUI studiepoäng (praktik)"
              },
              {
                "name": "FUI studiepoäng (andra)"
              },
              {
                "name": "FUI studiepoäng (lärdomsprov)"
              },
              {
                "name": "Studiepoäng från utlandet som tillgodoräknats"
              },
              {
                "name": "Studiepoäng i undervisning i främmande språk"
              },
              {
                "name": "Studiepoäng från praktik på utomlands"
              },
              {
                "name": "Samtliga grundexamenstuderandes studiepoäng"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "amk_analyysi_sv",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Yrkeshögskola"
              },
              {
                "name": "Utbildningsområde 02"
              },
              {
                "name": "Typ av utbildning"
              },
              {
                "name": "UKM-styrningsområde"
              },
              {
                "name": "Statistikår"
              },
              {
                "name": "Kod Yrkeshögskola"
              },
              {
                "name": "Kod Utbildningsområde 02"
              },
              {
                "name": "Kod UKM-styrningsområde"
              },
              {
                "name": "Sektorn"
              }
            ],
            "measures": [
              {
                "name": "Studiepoäng i öppen yrkeshögskoleundervisning"
              },
              {
                "name": "Studiepoäng i handledande utbildning för invandrare"
              },
              {
                "name": "Studiepoäng för utbytesstudenter som anländer"
              },
              {
                "name": "FUI studiepoäng (praktik)"
              },
              {
                "name": "FUI studiepoäng (andra)"
              },
              {
                "name": "FUI studiepoäng (lärdomsprov)"
              },
              {
                "name": "Studiepoäng från utlandet som tillgodoräknats"
              },
              {
                "name": "Studiepoäng från praktik på utomlands"
              },
              {
                "name": "Studiepoäng i undervisning i främmande språk"
              },
              {
                "name": "Studiepoäng från specialiseringsutbildning"
              },
              {
                "name": "Studiepoäng för särskilda studierättigheter"
              },
              {
                "name": "Samtliga grundexamenstuderandes studiepoäng"
              },
              {
                "name": "Studiepoäng enligt samarbetsavtal mellan högskolor"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "amk_muut_sv",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Yrkeshögskola"
              },
              {
                "name": "Utbildningsområde 02"
              },
              {
                "name": "Typ av utbildning"
              },
              {
                "name": "UKM-styrningsområde"
              },
              {
                "name": "Statistikår"
              },
              {
                "name": "Kod Yrkeshögskola"
              },
              {
                "name": "Kod Utbildningsområde 02"
              },
              {
                "name": "Kod UKM-styrningsområde"
              },
              {
                "name": "Sektorn"
              }
            ],
            "measures": [
              {
                "name": "Studiepoäng i öppen yrkeshögskoleundervisning"
              },
              {
                "name": "Studiepoäng i handledande utbildning för invandrare"
              },
              {
                "name": "Studiepoäng för utbytesstudenter som anländer"
              },
              {
                "name": "Studiepoäng från specialiseringsutbildning"
              },
              {
                "name": "Studiepoäng för särskilda studierättigheter"
              },
              {
                "name": "Studiepoäng enligt samarbetsavtal mellan högskolor"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "yo_tutkinto_sv",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Kod Utbildningsområde 95"
              },
              {
                "name": "Kod UKM-styrningsområde"
              },
              {
                "name": "Kod Universitet"
              },
              {
                "name": "Utbildningsområde 95"
              },
              {
                "name": "UKM-styrningsområde"
              },
              {
                "name": "Statistikår"
              },
              {
                "name": "Universitet"
              },
              {
                "name": "Sektorn"
              }
            ],
            "measures": [
              {
                "name": "Samtliga grundexamenstuderandes studiepoäng"
              },
              {
                "name": "Studiepoäng från utlandet som tillgodoräknats"
              },
              {
                "name": "Studiepoäng i undervisning i främmande språk"
              },
              {
                "name": "Studiepoäng från praktik på utomlands"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "yo_analyysi_sv",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Kod Utbildningsområde 95"
              },
              {
                "name": "Kod UKM-styrningsområde"
              },
              {
                "name": "Kod Universitet"
              },
              {
                "name": "Utbildningsområde 95"
              },
              {
                "name": "UKM-styrningsområde"
              },
              {
                "name": "Statistikår"
              },
              {
                "name": "Universitet"
              },
              {
                "name": "Sektorn"
              }
            ],
            "measures": [
              {
                "name": "Studiepoäng i öppen högskoleundervisning"
              },
              {
                "name": "Studiepoäng för särskilda studierättigheter (exkl. lärarutbildning)"
              },
              {
                "name": "Samtliga grundexamenstuderandes studiepoäng"
              },
              {
                "name": "Studiepoäng enligt samarbetsavtal mellan högskolor"
              },
              {
                "name": "Studiepoäng för utbytesstudenter som anländer"
              },
              {
                "name": "Studiepoäng från utlandet som tillgodoräknats"
              },
              {
                "name": "Studiepoäng i undervisning i främmande språk"
              },
              {
                "name": "Studiepoäng från praktik på utomlands"
              },
              {
                "name": "Lärarutbildning, studiepoäng för särskilda studierättigheter"
              },
              {
                "name": "Studiepoäng från specialiseringsutbildning"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "yo_muut_sv",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Kod Utbildningsområde 95"
              },
              {
                "name": "Kod UKM-styrningsområde"
              },
              {
                "name": "Kod Universitet"
              },
              {
                "name": "Utbildningsområde 95"
              },
              {
                "name": "UKM-styrningsområde"
              },
              {
                "name": "Statistikår"
              },
              {
                "name": "Universitet"
              },
              {
                "name": "Sektorn"
              }
            ],
            "measures": [
              {
                "name": "Studiepoäng i öppen högskoleundervisning"
              },
              {
                "name": "Lärarutbildning, studiepoäng för särskilda studierättigheter"
              },
              {
                "name": "Studiepoäng för särskilda studierättigheter (exkl. lärarutbildning)"
              },
              {
                "name": "Studiepoäng enligt samarbetsavtal mellan högskolor"
              },
              {
                "name": "Studiepoäng för utbytesstudenter som anländer"
              },
              {
                "name": "Studiepoäng från specialiseringsutbildning"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "yo_avoin_sv",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Kod Utbildningsområde 95"
              },
              {
                "name": "Kod UKM-styrningsområde"
              },
              {
                "name": "Kod Universitet"
              },
              {
                "name": "Utbildningsområde 95"
              },
              {
                "name": "UKM-styrningsområde"
              },
              {
                "name": "Statistikår"
              },
              {
                "name": "Universitet"
              },
              {
                "name": "Sektorn"
              }
            ],
            "measures": [
              {
                "name": "Studiepoäng i öppen högre utbildning som yrkehögskolor ordnar"
              },
              {
                "name": "Studiepoäng i öppen högre utbildning som medborgarinstituten ordnar"
              },
              {
                "name": "Studiepoäng i öppen högre utbildning som folkhögskolor ordnar"
              },
              {
                "name": "Studiepoäng i öppen högre utbildning som sommar universiteten ordnar"
              },
              {
                "name": "Studiepoäng i öppen högre utbildning som andra organisatörer ordnar"
              },
              {
                "name": "Studiepoäng i öppen högre utbildning som universiteten ordnar"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "yo_tutkinto_en",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Codes Field of education 95"
              },
              {
                "name": "Codes Field of education - HE steering"
              },
              {
                "name": "Codes University"
              },
              {
                "name": "Field of education 95"
              },
              {
                "name": "Field of education - HE steering"
              },
              {
                "name": "Statistical year"
              },
              {
                "name": "University"
              },
              {
                "name": "Sector"
              }
            ],
            "measures": [
              {
                "name": "All credits attained by students pursuing an undergraduate degree"
              },
              {
                "name": "Credits transferred from studies abroad"
              },
              {
                "name": "Credits for courses taught in a foreign language"
              },
              {
                "name": "Credits for foreign internships"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "yo_analyysi_en",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Codes Field of education 95"
              },
              {
                "name": "Codes Field of education - HE steering"
              },
              {
                "name": "Codes University"
              },
              {
                "name": "Field of education 95"
              },
              {
                "name": "Field of education - HE steering"
              },
              {
                "name": "Statistical year"
              },
              {
                "name": "University"
              },
              {
                "name": "Sector"
              }
            ],
            "measures": [
              {
                "name": "Credits attained in open higher education"
              },
              {
                "name": "Credits attained through the right to study individual courses (excl. teacher education)"
              },
              {
                "name": "All credits attained by students pursuing an undergraduate degree"
              },
              {
                "name": "Credits attained in ed. based on cooperative contracts between higher ed. instit"
              },
              {
                "name": "Credits attained by incoming exchange students"
              },
              {
                "name": "Credits transferred from studies abroad"
              },
              {
                "name": "Credits for foreign internships"
              },
              {
                "name": "Credits for courses taught in a foreign language"
              },
              {
                "name": "Teacher education, credits attained through the right to study individual courses"
              },
              {
                "name": "Credits attained in professional specialisation education"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "yo_muut_en",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Codes Field of education 95"
              },
              {
                "name": "Codes Field of education - HE steering"
              },
              {
                "name": "Codes University"
              },
              {
                "name": "Field of education 95"
              },
              {
                "name": "Field of education - HE steering"
              },
              {
                "name": "Statistical year"
              },
              {
                "name": "University"
              },
              {
                "name": "Sector"
              }
            ],
            "measures": [
              {
                "name": "Credits attained in open higher education"
              },
              {
                "name": "Teacher education, credits attained through the right to study individual courses"
              },
              {
                "name": "Credits attained through the right to study individual courses (excl. teacher education)"
              },
              {
                "name": "Credits attained in ed. based on cooperative contracts between higher ed. instit"
              },
              {
                "name": "Credits attained by incoming exchange students"
              },
              {
                "name": "Credits attained in professional specialisation education"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "yo_avoin_en",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Codes Field of education 95"
              },
              {
                "name": "Codes Field of education - HE steering"
              },
              {
                "name": "Codes University"
              },
              {
                "name": "Field of education 95"
              },
              {
                "name": "Field of education - HE steering"
              },
              {
                "name": "Statistical year"
              },
              {
                "name": "University"
              },
              {
                "name": "Sector"
              }
            ],
            "measures": [
              {
                "name": "Credits attained in open higher education organized by universities of applied sciences"
              },
              {
                "name": "Credits attained in open higher education organized by adult education centres"
              },
              {
                "name": "Credits attained in open higher education organized by folk high schools"
              },
              {
                "name": "Credits attained in open higher education organized by summer universities"
              },
              {
                "name": "Credits attained in open higher education organized by other providers"
              },
              {
                "name": "Credits attained in open higher education organized by universities"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "amk_tutkinto_en",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "University of applied sciences"
              },
              {
                "name": "Field of education 02"
              },
              {
                "name": "Type of education"
              },
              {
                "name": "Field of education - HE steering"
              },
              {
                "name": "Codes University of applied sciences"
              },
              {
                "name": "Codes Field of education 02"
              },
              {
                "name": "Codes Field of education - HE steering"
              },
              {
                "name": "Statistical year"
              },
              {
                "name": "Sector"
              }
            ],
            "measures": [
              {
                "name": "RDI credits (internships)"
              },
              {
                "name": "RDI credits (other)"
              },
              {
                "name": "RDI credits (final projects)"
              },
              {
                "name": "Credits transferred from studies abroad"
              },
              {
                "name": "Credits for courses taught in a foreign language"
              },
              {
                "name": "Credits for foreign internships"
              },
              {
                "name": "All credits attained by students pursuing an undergraduate degree"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "amk_analyysi_en",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "University of applied sciences"
              },
              {
                "name": "Field of education 02"
              },
              {
                "name": "Type of education"
              },
              {
                "name": "Field of education - HE steering"
              },
              {
                "name": "Codes University of applied sciences"
              },
              {
                "name": "Codes Field of education 02"
              },
              {
                "name": "Codes Field of education - HE steering"
              },
              {
                "name": "Statistical year"
              },
              {
                "name": "Sector"
              }
            ],
            "measures": [
              {
                "name": "Credits attained in open UAS education"
              },
              {
                "name": "Credits attained through the right to study individual courses (UAS)"
              },
              {
                "name": "Credits attained in ed. based on cooperative contracts between higher ed. instit"
              },
              {
                "name": "Credits attained in preparatory training for migrants"
              },
              {
                "name": "Credits attained by incoming exchange students"
              },
              {
                "name": "RDI credits (internships)"
              },
              {
                "name": "RDI credits (other)"
              },
              {
                "name": "RDI credits (final projects)"
              },
              {
                "name": "Credits transferred from studies abroad"
              },
              {
                "name": "Credits for foreign internships"
              },
              {
                "name": "Credits for courses taught in a foreign language"
              },
              {
                "name": "Credits attained in professional specialisation education"
              },
              {
                "name": "All credits attained by students pursuing an undergraduate degree"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "amk_muut_en",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "University of applied sciences"
              },
              {
                "name": "Field of education 02"
              },
              {
                "name": "Type of education"
              },
              {
                "name": "Field of education - HE steering"
              },
              {
                "name": "Codes University of applied sciences"
              },
              {
                "name": "Codes Field of education 02"
              },
              {
                "name": "Codes Field of education - HE steering"
              },
              {
                "name": "Statistical year"
              },
              {
                "name": "Sector"
              }
            ],
            "measures": [
              {
                "name": "Credits attained in open UAS education"
              },
              {
                "name": "Credits attained through the right to study individual courses (UAS)"
              },
              {
                "name": "Credits attained in ed. based on cooperative contracts between higher ed. instit"
              },
              {
                "name": "Credits attained in preparatory training for migrants"
              },
              {
                "name": "Credits attained by incoming exchange students"
              },
              {
                "name": "Credits attained in professional specialisation education"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      }
    ],
    "roles": [
      {
        "name": "Luku",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "DWI\\T_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1732"
          },
          {
            "memberName": "DWI\\P_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1733"
          },
          {
            "memberName": "NT AUTHORITY\\IUSR",
            "memberId": "S-1-5-17"
          },
          {
            "memberName": "DWI\\Z_T_Antero_Read_TAB",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-4155"
          },
          {
            "memberName": "DWI\\Z_P_Antero_Read_TAB",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-4156"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "400"
      }
    ]
  }
}