{
  "name": "SemanticModel",
  "compatibilityLevel": 1200,
  "model": {
    "culture": "fi-FI",
    "dataSources": [
      {
        "name": "SqlServer dwitvipusql16 ANTERO",
        "connectionString": "Provider=SQLNCLI11;Data Source=dwitvipusql16;Initial Catalog=ANTERO;Integrated Security=SSPI;Persist Security Info=false",
        "impersonationMode": "impersonateAccount",
        "account": "dwi\\pankalai",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "Sarakeleveys",
        "columns": [
          {
            "name": "Sarakeleveys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Sarakeleveys",
            "sourceProviderType": "Char"
          },
          {
            "name": "leveys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "leveys",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Sarakeleveys",
            "dataView": "full",
            "source": {
              "query": " SELECT [dw].[Sarakeleveys].* FROM [dw].[Sarakeleveys] ",
              "dataSource": "SqlServer dwitvipusql16 ANTERO"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dw].[Sarakeleveys].* FROM [dw].[Sarakeleveys] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Sarakeleveys"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dw"
          }
        ]
      },
      {
        "name": "Muuttujat",
        "columns": [
          {
            "name": "Tilastovuosi",
            "dataType": "int64",
            "sourceColumn": "Tilastovuosi",
            "sourceProviderType": "Integer",
            "displayFolder": "Aikamuuttujat"
          },
          {
            "name": "Koulutusala 02",
            "dataType": "string",
            "sourceColumn": "Koulutusala 02",
            "sourceProviderType": "Char",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusala 95",
            "dataType": "string",
            "sourceColumn": "Koulutusala 95",
            "sourceProviderType": "Char",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "OKM ohjauksen ala",
            "dataType": "string",
            "sourceColumn": "OKM ohjauksen ala",
            "sourceProviderType": "Char",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutustyyppi",
            "dataType": "string",
            "sourceColumn": "Koulutustyyppi",
            "sourceProviderType": "Char",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Sektori",
            "dataType": "string",
            "sourceColumn": "Sektori",
            "sourceProviderType": "Char",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Ammattikorkeakoulu",
            "dataType": "string",
            "sourceColumn": "Ammattikorkeakoulu",
            "sourceProviderType": "Char",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Yliopisto",
            "dataType": "string",
            "sourceColumn": "Yliopisto",
            "sourceProviderType": "Char",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "kaikki_tutk_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "kaikki_tutk_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "tki_pisteet_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "tki_pisteet_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "tki_harj_pisteet_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "tki_harj_pisteet_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "tki_muu_pisteet_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "tki_muu_pisteet_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "vierkiel_pisteet_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "vierkiel_pisteet_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "ulkom_hyv_op_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ulkom_hyv_op_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "ulkom_harj_op_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ulkom_harj_op_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "avoinamk_op_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "avoinamk_op_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "avoinamk_op_amk_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "avoinamk_op_amk_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "avoinamk_op_yliop_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "avoinamk_op_yliop_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "avoinamk_op_kesa_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "avoinamk_op_kesa_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "avoinamk_op_kansan_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "avoinamk_op_kansan_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "avoinamk_op_kansal_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "avoinamk_op_kansal_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "avoinamk_op_muut_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "avoinamk_op_muut_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "avoinop_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "avoinop_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "avoinop_amk_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "avoinop_amk_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "avoinop_yliop_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "avoinop_yliop_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "avoinop_kesa_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "avoinop_kesa_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "avoinop_kansan_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "avoinop_kansan_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "avoinop_kansal_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "avoinop_kansal_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "avoinop_muut_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "avoinop_muut_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "kv_vaihtoopiskelijat_op_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "kv_vaihtoopiskelijat_op_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "kk_yhteistyo_op_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "kk_yhteistyo_op_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "erilopintooik_op_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "erilopintooik_op_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "erillisilla_oik_opkoul_op_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "erillisilla_oik_opkoul_op_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "mamu_op_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "mamu_op_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "erikoul_suor_op_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "erikoul_suor_op_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Koodit Koulutusala 02",
            "dataType": "int64",
            "sourceColumn": "Koodit Koulutusala 02",
            "sourceProviderType": "Integer",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koodit Koulutusala 95",
            "dataType": "string",
            "sourceColumn": "Koodit Koulutusala 95",
            "sourceProviderType": "Char",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koodit OKM ohjauksen ala",
            "dataType": "string",
            "sourceColumn": "Koodit OKM ohjauksen ala",
            "sourceProviderType": "Char",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koodit Ammattikorkeakoulu",
            "dataType": "string",
            "sourceColumn": "Koodit Ammattikorkeakoulu",
            "sourceProviderType": "Char",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koodit Yliopisto",
            "dataType": "string",
            "sourceColumn": "Koodit Yliopisto",
            "sourceProviderType": "Char",
            "displayFolder": "Koodimuuttujat"
          }
        ],
        "partitions": [
          {
            "name": "v_st_opintopisteet",
            "dataView": "full",
            "source": {
              "query": " SELECT [dw].[v_st_opintopisteet].* FROM [dw].[v_st_opintopisteet] ",
              "dataSource": "SqlServer dwitvipusql16 ANTERO"
            }
          }
        ],
        "measures": [
          {
            "name": "Kaikki perustutkinto-opiskelijoiden opintopisteet",
            "expression": [
              "if(sum([kaikki_tutk_lkm])=0,blank(),sum([kaikki_tutk_lkm])",
              ")"
            ],
            "formatString": "#,0"
          },
          {
            "name": "TKI opintopisteet (opinnäytetyöt)",
            "expression": [
              "if(sum(Muuttujat[tki_pisteet_lkm])=0,blank(),sum(Muuttujat[tki_pisteet_lkm])",
              ")"
            ],
            "formatString": "#,0"
          },
          {
            "name": "TKI opintopisteet (harjoittelu)",
            "expression": [
              "if(sum([tki_harj_pisteet_lkm])=0,blank(),sum([tki_harj_pisteet_lkm])",
              ")"
            ],
            "formatString": "#,0"
          },
          {
            "name": "TKI opintopisteet (muu)",
            "expression": [
              "if(sum([tki_muu_pisteet_lkm])=0,blank(),sum([tki_muu_pisteet_lkm])",
              ")"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Vieraskielisen opetuksen opintopisteet",
            "expression": [
              "if(sum(Muuttujat[vierkiel_pisteet_lkm])=0,blank(),sum(Muuttujat[vierkiel_pisteet_lkm])",
              ")"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Ulkomailta hyväksiluetut opintopisteet",
            "expression": [
              "if(sum(Muuttujat[ulkom_hyv_op_lkm])=0,blank(),sum(Muuttujat[ulkom_hyv_op_lkm])",
              ")"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Avoimen amk-opetuksen opintopisteet",
            "expression": [
              "if(sum([avoinamk_op_lkm])=0,blank(),sum([avoinamk_op_lkm])",
              ")"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Erillisten opinto-oikeuksien opintopisteet",
            "expression": [
              "if(sum([erilopintooik_op_lkm])=0,blank(),sum([erilopintooik_op_lkm])",
              ")"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Korkeakoulujen välisten yhteistyösopimusten opintopisteet",
            "expression": [
              "if(sum([kk_yhteistyo_op_lkm])=0,blank(),sum([kk_yhteistyo_op_lkm])",
              ")"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Saapuvien vaihto-opiskelijoiden opintopisteet",
            "expression": [
              "if(sum([kv_vaihtoopiskelijat_op_lkm])=0,blank(),sum([kv_vaihtoopiskelijat_op_lkm])",
              ")"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Maahanmuuttajien valmentavan koulutuksen opintopisteet",
            "expression": [
              "if(sum([mamu_op_lkm])=0,blank(),sum([mamu_op_lkm])",
              ")"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Avoimen korkeakouluopetuksen opintopisteet",
            "expression": [
              "if(sum([avoinop_lkm])=0,blank(),sum([avoinop_lkm])",
              ")"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Erillisten opinto-oikeuksien opintopisteet (pl. opettajankoulutus)",
            "expression": [
              "if(sum([erilopintooik_op_lkm])=0,blank(),sum([erilopintooik_op_lkm])",
              ")"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Erillisten opinto-oikeuksien opettajankoulutuksen opintopisteet",
            "expression": [
              "if(sum([erillisilla_oik_opkoul_op_lkm])=0,blank(),sum([erillisilla_oik_opkoul_op_lkm])",
              ")"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Yliopistojen järjestämän avoimen korkeakouluopetuksen opintopisteet",
            "expression": "if(sum([avoinop_yliop_lkm])=0,blank(),sum([avoinop_yliop_lkm]))",
            "formatString": "#,0"
          },
          {
            "name": "Ammattikorkeakoulujen järjestämän avoimen korkeakouluopetuksen opintopisteet",
            "expression": "if(sum([avoinop_amk_lkm])=0,blank(),sum([avoinop_amk_lkm]))",
            "formatString": "#,0"
          },
          {
            "name": "Kansalaisopistojen järjestämän avoimen korkeakouluopetuksen opintopisteet",
            "expression": "if(sum([avoinop_kansal_lkm])=0,blank(),sum([avoinop_kansal_lkm]))",
            "formatString": "#,0"
          },
          {
            "name": "Kansanopistojen järjestämän avoimen korkeakouluopetuksen opintopisteet",
            "expression": "if(sum([avoinop_kansan_lkm])=0,blank(),sum([avoinop_kansan_lkm]))",
            "formatString": "#,0"
          },
          {
            "name": "Kesäyliopistojen järjestämän avoimen korkeakouluopetuksen opintopisteet",
            "expression": "if(sum([avoinop_kesa_lkm])=0,blank(),sum([avoinop_kesa_lkm]))",
            "formatString": "#,0"
          },
          {
            "name": "Muiden järjestäjien avoimen korkeakouluopetuksen opintopisteet",
            "expression": "if(sum([avoinop_muut_lkm])=0,blank(),sum([avoinop_muut_lkm]))",
            "formatString": "#,0"
          },
          {
            "name": "Ulkomaisen harjoittelun opintopisteet",
            "expression": "if(sum(Muuttujat[ulkom_harj_op_lkm])=0,blank(),sum(Muuttujat[ulkom_harj_op_lkm]))",
            "formatString": "#,0"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dw].[v_st_opintopisteet].* FROM [dw].[v_st_opintopisteet] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "v_st_opintopisteet"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dw"
          }
        ]
      }
    ],
    "perspectives": [
      {
        "name": "yo_tutkinto",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Koodit Koulutusala 95"
              },
              {
                "name": "Koodit OKM ohjauksen ala"
              },
              {
                "name": "Koodit Yliopisto"
              },
              {
                "name": "Koulutusala 95"
              },
              {
                "name": "OKM ohjauksen ala"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Yliopisto"
              }
            ],
            "measures": [
              {
                "name": "Kaikki perustutkinto-opiskelijoiden opintopisteet"
              },
              {
                "name": "Ulkomailta hyväksiluetut opintopisteet"
              },
              {
                "name": "Vieraskielisen opetuksen opintopisteet"
              },
              {
                "name": "Ulkomaisen harjoittelun opintopisteet"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "yo_muut",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Koodit Koulutusala 95"
              },
              {
                "name": "Koodit OKM ohjauksen ala"
              },
              {
                "name": "Koodit Yliopisto"
              },
              {
                "name": "Koulutusala 95"
              },
              {
                "name": "OKM ohjauksen ala"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Yliopisto"
              }
            ],
            "measures": [
              {
                "name": "Avoimen korkeakouluopetuksen opintopisteet"
              },
              {
                "name": "Erillisten opinto-oikeuksien opettajankoulutuksen opintopisteet"
              },
              {
                "name": "Erillisten opinto-oikeuksien opintopisteet (pl. opettajankoulutus)"
              },
              {
                "name": "Korkeakoulujen välisten yhteistyösopimusten opintopisteet"
              },
              {
                "name": "Saapuvien vaihto-opiskelijoiden opintopisteet"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "amk_tutkinto",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Ammattikorkeakoulu"
              },
              {
                "name": "Koodit Ammattikorkeakoulu"
              },
              {
                "name": "Koodit Koulutusala 02"
              },
              {
                "name": "Koodit OKM ohjauksen ala"
              },
              {
                "name": "Koulutusala 02"
              },
              {
                "name": "Koulutustyyppi"
              },
              {
                "name": "OKM ohjauksen ala"
              },
              {
                "name": "Tilastovuosi"
              }
            ],
            "measures": [
              {
                "name": "Kaikki perustutkinto-opiskelijoiden opintopisteet"
              },
              {
                "name": "TKI opintopisteet (harjoittelu)"
              },
              {
                "name": "TKI opintopisteet (muu)"
              },
              {
                "name": "TKI opintopisteet (opinnäytetyöt)"
              },
              {
                "name": "Ulkomailta hyväksiluetut opintopisteet"
              },
              {
                "name": "Vieraskielisen opetuksen opintopisteet"
              },
              {
                "name": "Ulkomaisen harjoittelun opintopisteet"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "amk_muut",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Ammattikorkeakoulu"
              },
              {
                "name": "Koodit Ammattikorkeakoulu"
              },
              {
                "name": "Koodit Koulutusala 02"
              },
              {
                "name": "Koodit OKM ohjauksen ala"
              },
              {
                "name": "Koulutusala 02"
              },
              {
                "name": "Koulutustyyppi"
              },
              {
                "name": "OKM ohjauksen ala"
              },
              {
                "name": "Tilastovuosi"
              }
            ],
            "measures": [
              {
                "name": "Avoimen amk-opetuksen opintopisteet"
              },
              {
                "name": "Erillisten opinto-oikeuksien opintopisteet"
              },
              {
                "name": "Korkeakoulujen välisten yhteistyösopimusten opintopisteet"
              },
              {
                "name": "Maahanmuuttajien valmentavan koulutuksen opintopisteet"
              },
              {
                "name": "Saapuvien vaihto-opiskelijoiden opintopisteet"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "yo_avoin",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Koodit Koulutusala 95"
              },
              {
                "name": "Koodit OKM ohjauksen ala"
              },
              {
                "name": "Koodit Yliopisto"
              },
              {
                "name": "Koulutusala 95"
              },
              {
                "name": "OKM ohjauksen ala"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Yliopisto"
              }
            ],
            "measures": [
              {
                "name": "Ammattikorkeakoulujen järjestämän avoimen korkeakouluopetuksen opintopisteet"
              },
              {
                "name": "Kansalaisopistojen järjestämän avoimen korkeakouluopetuksen opintopisteet"
              },
              {
                "name": "Kansanopistojen järjestämän avoimen korkeakouluopetuksen opintopisteet"
              },
              {
                "name": "Kesäyliopistojen järjestämän avoimen korkeakouluopetuksen opintopisteet"
              },
              {
                "name": "Muiden järjestäjien avoimen korkeakouluopetuksen opintopisteet"
              },
              {
                "name": "Yliopistojen järjestämän avoimen korkeakouluopetuksen opintopisteet"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "yo_analyysi",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Koodit Koulutusala 95"
              },
              {
                "name": "Koodit OKM ohjauksen ala"
              },
              {
                "name": "Koodit Yliopisto"
              },
              {
                "name": "Koulutusala 95"
              },
              {
                "name": "OKM ohjauksen ala"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Yliopisto"
              }
            ],
            "measures": [
              {
                "name": "Avoimen korkeakouluopetuksen opintopisteet"
              },
              {
                "name": "Erillisten opinto-oikeuksien opintopisteet"
              },
              {
                "name": "Erillisten opinto-oikeuksien opintopisteet (pl. opettajankoulutus)"
              },
              {
                "name": "Kaikki perustutkinto-opiskelijoiden opintopisteet"
              },
              {
                "name": "Korkeakoulujen välisten yhteistyösopimusten opintopisteet"
              },
              {
                "name": "Saapuvien vaihto-opiskelijoiden opintopisteet"
              },
              {
                "name": "Ulkomailta hyväksiluetut opintopisteet"
              },
              {
                "name": "Ulkomaisen harjoittelun opintopisteet"
              },
              {
                "name": "Vieraskielisen opetuksen opintopisteet"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "amk_analyysi",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Ammattikorkeakoulu"
              },
              {
                "name": "Koodit Ammattikorkeakoulu"
              },
              {
                "name": "Koodit Koulutusala 02"
              },
              {
                "name": "Koodit OKM ohjauksen ala"
              },
              {
                "name": "Koulutusala 02"
              },
              {
                "name": "Koulutustyyppi"
              },
              {
                "name": "OKM ohjauksen ala"
              },
              {
                "name": "Tilastovuosi"
              }
            ],
            "measures": [
              {
                "name": "Avoimen amk-opetuksen opintopisteet"
              },
              {
                "name": "Erillisten opinto-oikeuksien opintopisteet"
              },
              {
                "name": "Kaikki perustutkinto-opiskelijoiden opintopisteet"
              },
              {
                "name": "Korkeakoulujen välisten yhteistyösopimusten opintopisteet"
              },
              {
                "name": "Maahanmuuttajien valmentavan koulutuksen opintopisteet"
              },
              {
                "name": "Saapuvien vaihto-opiskelijoiden opintopisteet"
              },
              {
                "name": "TKI opintopisteet (harjoittelu)"
              },
              {
                "name": "TKI opintopisteet (muu)"
              },
              {
                "name": "TKI opintopisteet (opinnäytetyöt)"
              },
              {
                "name": "Ulkomailta hyväksiluetut opintopisteet"
              },
              {
                "name": "Ulkomaisen harjoittelun opintopisteet"
              },
              {
                "name": "Vieraskielisen opetuksen opintopisteet"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      }
    ],
    "roles": [
      {
        "name": "Luku",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "DWI\\T_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1732"
          },
          {
            "memberName": "DWI\\P_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1733"
          },
          {
            "memberName": "NT AUTHORITY\\IUSR",
            "memberId": "S-1-5-17"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "400"
      }
    ]
  },
  "id": "SemanticModel"
}