{
  "name": "SemanticModel",
  "compatibilityLevel": 1200,
  "model": {
    "culture": "fi-FI",
    "dataSources": [
      {
        "name": "SqlServer dwitvipusql22 ANTERO",
        "connectionString": "Provider=SQLOLEDB.1;Data Source=dwitvipusql22;Initial Catalog=ANTERO;Integrated Security=SSPI;Persist Security Info=false",
        "impersonationMode": "impersonateServiceAccount",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "Sarakeleveys",
        "columns": [
          {
            "name": "Sarakeleveys",
            "dataType": "string",
            "sourceColumn": "Sarakeleveys",
            "sourceProviderType": "Char"
          },
          {
            "name": "leveys",
            "dataType": "string",
            "sourceColumn": "leveys",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Sarakeleveys",
            "dataView": "full",
            "source": {
              "query": " SELECT [dw].[Sarakeleveys].* FROM [dw].[Sarakeleveys] ",
              "dataSource": "SqlServer dwitvipusql22 ANTERO"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dw].[Sarakeleveys].* FROM [dw].[Sarakeleveys] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Sarakeleveys"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dw"
          }
        ]
      },
      {
        "name": "Muuttujat",
        "columns": [
          {
            "name": "Tilastovuosi",
            "dataType": "int64",
            "sourceColumn": "Tilastovuosi",
            "sourceProviderType": "Integer",
            "displayFolder": "Aikamuuttujat"
          },
          {
            "name": "Tilastokuukausi",
            "dataType": "string",
            "sourceColumn": "Tilastokuukausi",
            "sortByColumn": "jarj Tilastokuukausi",
            "sourceProviderType": "WChar",
            "displayFolder": "Aikamuuttujat"
          },
          {
            "name": "Sukupuoli",
            "dataType": "string",
            "sourceColumn": "Sukupuoli",
            "sortByColumn": "jarj Sukupuoli",
            "sourceProviderType": "WChar",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Äidinkieli",
            "dataType": "string",
            "sourceColumn": "Äidinkieli",
            "sortByColumn": "jarj Äidinkieli",
            "sourceProviderType": "WChar",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Ikäryhmä",
            "dataType": "string",
            "sourceColumn": "Ikäryhmä",
            "sortByColumn": "jarj Ikäryhmä",
            "sourceProviderType": "WChar",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Ikä",
            "dataType": "string",
            "sourceColumn": "Ikä",
            "sortByColumn": "jarj Ikä",
            "sourceProviderType": "WChar",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Tutkinto",
            "dataType": "string",
            "sourceColumn": "Tutkinto",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusala, taso 1",
            "dataType": "string",
            "sourceColumn": "Koulutusala, taso 1",
            "sortByColumn": "jarj Koulutusala, taso 1",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusala, taso 2",
            "dataType": "string",
            "sourceColumn": "Koulutusala, taso 2",
            "sortByColumn": "jarj Koulutusala, taso 2",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusala, taso 3",
            "dataType": "string",
            "sourceColumn": "Koulutusala, taso 3",
            "sortByColumn": "jarj Koulutusala, taso 3",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Tutkintotyyppi",
            "dataType": "string",
            "sourceColumn": "Tutkintotyyppi",
            "sortByColumn": "jarj Tutkintotyyppi",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Rahoitusmuoto",
            "dataType": "string",
            "sourceColumn": "Rahoitusmuoto",
            "sortByColumn": "jarj Rahoitusmuoto",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Kustannusryhmä",
            "dataType": "string",
            "sourceColumn": "Kustannusryhmä",
            "sortByColumn": "jarj Kustannusryhmä",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Oppisopimuskoulutus",
            "dataType": "string",
            "sourceColumn": "Oppisopimuskoulutus",
            "sortByColumn": "jarj Oppisopimuskoulutus",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Erityisopetus",
            "dataType": "string",
            "sourceColumn": "Erityisopetus",
            "sortByColumn": "jarj Erityisopetus",
            "sourceProviderType": "Char",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Suorituksen tyyppi",
            "dataType": "string",
            "sourceColumn": "Suorituksen tyyppi",
            "sortByColumn": "jarj Suorituksen tyyppi",
            "sourceProviderType": "Char",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Hankintakoulutus",
            "dataType": "string",
            "sourceColumn": "Hankintakoulutus",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Hankintakoulutuksen järjestäjä",
            "dataType": "string",
            "sourceColumn": "Hankintakoulutuksen järjestäjä",
            "sourceProviderType": "WChar",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Koulutuksen järjestäjä",
            "dataType": "string",
            "sourceColumn": "Koulutuksen järjestäjä",
            "sourceProviderType": "WChar",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Koulutuksen järjestäjän AVI",
            "dataType": "string",
            "sourceColumn": "Koulutuksen järjestäjän AVI",
            "sortByColumn": "jarj Koulutuksen järjestäjän AVI",
            "sourceProviderType": "WChar",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Koulutuksen järjestäjän ELY",
            "dataType": "string",
            "sourceColumn": "Koulutuksen järjestäjän ELY",
            "sortByColumn": "jarj Koulutuksen järjestäjän ELY",
            "sourceProviderType": "WChar",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Koulutuksen järjestäjän maakunta",
            "dataType": "string",
            "sourceColumn": "Koulutuksen järjestäjän maakunta",
            "sortByColumn": "jarj Koulutuksen järjestäjän maakunta",
            "sourceProviderType": "WChar",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Koulutuksen järjestäjän kunta",
            "dataType": "string",
            "sourceColumn": "Koulutuksen järjestäjän kunta",
            "sourceProviderType": "WChar",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Oppilaitos",
            "dataType": "string",
            "sourceColumn": "Oppilaitos",
            "sourceProviderType": "WChar",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Oppilaitoksen AVI",
            "dataType": "string",
            "sourceColumn": "Oppilaitoksen AVI",
            "sortByColumn": "jarj Oppilaitoksen AVI",
            "sourceProviderType": "WChar",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Oppilaitoksen ELY",
            "dataType": "string",
            "sourceColumn": "Oppilaitoksen ELY",
            "sortByColumn": "jarj Oppilaitoksen ELY",
            "sourceProviderType": "WChar",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Oppilaitoksen maakunta",
            "dataType": "string",
            "sourceColumn": "Oppilaitoksen maakunta",
            "sortByColumn": "jarj Oppilaitoksen maakunta",
            "sourceProviderType": "WChar",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Oppilaitoksen kunta",
            "dataType": "string",
            "sourceColumn": "Oppilaitoksen kunta",
            "sourceProviderType": "WChar",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Toimipiste",
            "dataType": "string",
            "sourceColumn": "Toimipiste",
            "sourceProviderType": "WChar",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Toimipisteen AVI",
            "dataType": "string",
            "sourceColumn": "Toimipisteen AVI",
            "sortByColumn": "jarj Toimipisteen AVI",
            "sourceProviderType": "WChar",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Toimipisteen ELY",
            "dataType": "string",
            "sourceColumn": "Toimipisteen ELY",
            "sortByColumn": "jarj Toimipisteen ELY",
            "sourceProviderType": "WChar",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Toimipisteen maakunta",
            "dataType": "string",
            "sourceColumn": "Toimipisteen maakunta",
            "sortByColumn": "jarj Toimipisteen maakunta",
            "sourceProviderType": "WChar",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Toimipisteen kunta",
            "dataType": "string",
            "sourceColumn": "Toimipisteen kunta",
            "sourceProviderType": "WChar",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Luvaton koulutus",
            "dataType": "string",
            "sourceColumn": "Luvaton koulutus",
            "sortByColumn": "jarj_luvaton_koulutus",
            "sourceProviderType": "Char",
            "displayFolder": "Järjestämislupamuuttujat"
          },
          {
            "name": "Luvaton korotustekijä",
            "dataType": "string",
            "sourceColumn": "Luvaton korotustekijä",
            "sortByColumn": "jarj_luvaton_korotustekija",
            "sourceProviderType": "Char",
            "displayFolder": "Järjestämislupamuuttujat"
          },
          {
            "name": "Koodit Koulutuksen järjestäjä",
            "dataType": "string",
            "sourceColumn": "Koodit Koulutuksen järjestäjä",
            "sourceProviderType": "Char",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koodit Hankintakoulutuksen järjestäjä",
            "dataType": "string",
            "sourceColumn": "Koodit Hankintakoulutuksen järjestäjä",
            "sourceProviderType": "Char",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koodit Tutkinto",
            "dataType": "string",
            "sourceColumn": "Koodit Tutkinto",
            "sourceProviderType": "Char",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koodit Tutkintotyyppi",
            "dataType": "string",
            "sourceColumn": "Koodit Tutkintotyyppi",
            "sourceProviderType": "Char",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "painottamaton_tutkinnot",
            "dataType": "int64",
            "sourceColumn": "painottamaton_tutkinnot",
            "sourceProviderType": "Integer"
          },
          {
            "name": "painottamaton_osatutkinnot",
            "dataType": "int64",
            "sourceColumn": "painottamaton_osatutkinnot",
            "sourceProviderType": "Integer"
          },
          {
            "name": "painottamaton_osaamispisteet",
            "dataType": "double",
            "sourceColumn": "painottamaton_osaamispisteet",
            "sourceProviderType": "Double"
          },
          {
            "name": "painotettu_tutkinnot_pt_kr_pk",
            "dataType": "double",
            "sourceColumn": "painotettu_tutkinnot_pt_kr_pk",
            "sourceProviderType": "Double"
          },
          {
            "name": "painotettu_tutkinnot_at_eat_kr_pk",
            "dataType": "double",
            "sourceColumn": "painotettu_tutkinnot_at_eat_kr_pk",
            "sourceProviderType": "Double"
          },
          {
            "name": "painotettu_tutkinnot_erityistuki",
            "dataType": "double",
            "sourceColumn": "painotettu_tutkinnot_erityistuki",
            "sourceProviderType": "Double"
          },
          {
            "name": "painotettu_tutkinnot_erityistuki_hyv",
            "dataType": "double",
            "sourceColumn": "painotettu_tutkinnot_erityistuki_hyv",
            "sourceProviderType": "Double"
          },
          {
            "name": "painotettu_tutkinnon_osien_osaamispisteet_pt_kr",
            "dataType": "double",
            "sourceColumn": "painotettu_tutkinnon_osien_osaamispisteet_pt_kr",
            "sourceProviderType": "Double"
          },
          {
            "name": "painotettu_tutkinnon_osien_osaamispisteet_at_eat_kr",
            "dataType": "double",
            "sourceColumn": "painotettu_tutkinnon_osien_osaamispisteet_at_eat_kr",
            "sourceProviderType": "Double"
          },
          {
            "name": "painotettu_tutkinnon_osien_osaamispisteet_erityistuki",
            "dataType": "double",
            "sourceColumn": "painotettu_tutkinnon_osien_osaamispisteet_erityistuki",
            "sourceProviderType": "Double"
          },
          {
            "name": "painotettu_tutkinnon_osien_osaamispisteet_erityistuki_hyv",
            "dataType": "double",
            "sourceColumn": "painotettu_tutkinnon_osien_osaamispisteet_erityistuki_hyv",
            "sourceProviderType": "Double"
          },
          {
            "name": "painotettu_tutkinnot_yht",
            "dataType": "double",
            "sourceColumn": "painotettu_tutkinnot_yht",
            "sourceProviderType": "Double"
          },
          {
            "name": "painotettu_tutkinnon_osien_osaamispisteet_yht",
            "dataType": "double",
            "sourceColumn": "painotettu_tutkinnon_osien_osaamispisteet_yht",
            "sourceProviderType": "Double"
          },
          {
            "name": "leikkauskerroin2",
            "dataType": "double",
            "sourceColumn": "leikkauskerroin",
            "sourceProviderType": "Double"
          },
          {
            "name": "tavoitteelliset_opv",
            "dataType": "int64",
            "sourceColumn": "tavoitteelliset_opv",
            "sourceProviderType": "Integer"
          },
          {
            "name": "rahoitusmuoto_maksetaan",
            "dataType": "int64",
            "sourceColumn": "rahoitusmuoto_maksetaan",
            "sourceProviderType": "Integer"
          },
          {
            "name": "hyvaksytaan_rahoitukseen",
            "dataType": "int64",
            "sourceColumn": "hyvaksytaan_rahoitukseen",
            "sourceProviderType": "Integer"
          },
          {
            "name": "jarj Tilastokuukausi",
            "dataType": "int64",
            "sourceColumn": "jarj Tilastokuukausi",
            "sourceProviderType": "Integer"
          },
          {
            "name": "jarj Sukupuoli",
            "dataType": "string",
            "sourceColumn": "jarj Sukupuoli",
            "sourceProviderType": "Char"
          },
          {
            "name": "jarj Äidinkieli",
            "dataType": "int64",
            "sourceColumn": "jarj Äidinkieli",
            "sourceProviderType": "Integer"
          },
          {
            "name": "jarj Ikäryhmä",
            "dataType": "string",
            "sourceColumn": "jarj Ikäryhmä",
            "sourceProviderType": "WChar"
          },
          {
            "name": "jarj Ikä",
            "dataType": "string",
            "sourceColumn": "jarj Ikä",
            "sourceProviderType": "WChar"
          },
          {
            "name": "jarj Koulutusala, taso 1",
            "dataType": "string",
            "sourceColumn": "jarj Koulutusala, taso 1",
            "sourceProviderType": "Char"
          },
          {
            "name": "jarj Koulutusala, taso 2",
            "dataType": "string",
            "sourceColumn": "jarj Koulutusala, taso 2",
            "sourceProviderType": "Char"
          },
          {
            "name": "jarj Koulutusala, taso 3",
            "dataType": "string",
            "sourceColumn": "jarj Koulutusala, taso 3",
            "sourceProviderType": "Char"
          },
          {
            "name": "jarj Tutkintotyyppi",
            "dataType": "string",
            "sourceColumn": "jarj Tutkintotyyppi",
            "sourceProviderType": "Char"
          },
          {
            "name": "jarj Rahoitusmuoto",
            "dataType": "int64",
            "sourceColumn": "jarj Rahoitusmuoto",
            "sourceProviderType": "Integer"
          },
          {
            "name": "jarj Kustannusryhmä",
            "dataType": "int64",
            "sourceColumn": "jarj Kustannusryhmä",
            "sourceProviderType": "Integer"
          },
          {
            "name": "jarj Oppisopimuskoulutus",
            "dataType": "int64",
            "sourceColumn": "jarj Oppisopimuskoulutus",
            "sourceProviderType": "Integer"
          },
          {
            "name": "jarj Erityisopetus",
            "dataType": "string",
            "sourceColumn": "jarj Erityisopetus",
            "sourceProviderType": "Char"
          },
          {
            "name": "jarj Suorituksen tyyppi",
            "dataType": "int64",
            "sourceColumn": "jarj Suorituksen tyyppi",
            "sourceProviderType": "Integer"
          },
          {
            "name": "jarj Koulutuksen järjestäjän AVI",
            "dataType": "string",
            "sourceColumn": "jarj Koulutuksen järjestäjän AVI",
            "sourceProviderType": "Char"
          },
          {
            "name": "jarj Koulutuksen järjestäjän ELY",
            "dataType": "string",
            "sourceColumn": "jarj Koulutuksen järjestäjän ELY",
            "sourceProviderType": "Char"
          },
          {
            "name": "jarj Koulutuksen järjestäjän maakunta",
            "dataType": "string",
            "sourceColumn": "jarj Koulutuksen järjestäjän maakunta",
            "sourceProviderType": "Char"
          },
          {
            "name": "jarj Oppilaitoksen AVI",
            "dataType": "string",
            "sourceColumn": "jarj Oppilaitoksen AVI",
            "sourceProviderType": "Char"
          },
          {
            "name": "jarj Oppilaitoksen ELY",
            "dataType": "string",
            "sourceColumn": "jarj Oppilaitoksen ELY",
            "sourceProviderType": "Char"
          },
          {
            "name": "jarj Oppilaitoksen maakunta",
            "dataType": "string",
            "sourceColumn": "jarj Oppilaitoksen maakunta",
            "sourceProviderType": "Char"
          },
          {
            "name": "jarj Toimipisteen AVI",
            "dataType": "string",
            "sourceColumn": "jarj Toimipisteen AVI",
            "sourceProviderType": "Char"
          },
          {
            "name": "jarj Toimipisteen ELY",
            "dataType": "string",
            "sourceColumn": "jarj Toimipisteen ELY",
            "sourceProviderType": "Char"
          },
          {
            "name": "jarj Toimipisteen maakunta",
            "dataType": "string",
            "sourceColumn": "jarj Toimipisteen maakunta",
            "sourceProviderType": "Char"
          },
          {
            "name": "jarj_luvaton_koulutus",
            "dataType": "string",
            "sourceColumn": "jarj_luvaton_koulutus",
            "sourceProviderType": "Char"
          },
          {
            "name": "jarj_luvaton_korotustekija",
            "dataType": "string",
            "sourceColumn": "jarj_luvaton_korotustekija",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "v_amos_tutkinnot_ja_tutkinnonosat_uusi",
            "dataView": "full",
            "source": {
              "query": " SELECT [dw].[v_amos_tutkinnot_ja_tutkinnonosat_uusi].* FROM [dw].[v_amos_tutkinnot_ja_tutkinnonosat_uusi] ",
              "dataSource": "SqlServer dwitvipusql22 ANTERO"
            }
          }
        ],
        "measures": [
          {
            "name": "Tutkintojen määrä",
            "expression": [
              "",
              "var summa = CALCULATE(CALCULATE(SUM([painottamaton_tutkinnot]),FILTER(Muuttujat,[Suorituksen tyyppi]=\"Koko tutkinto\")),ALL(Muuttujat[Luvaton korotustekijä]))",
              "return IF(summa=0 || [korotusehto]=0,BLANK(),summa)"
            ],
            "formatString": "#,0",
            "displayFolder": "Painottamattomat"
          },
          {
            "name": "Tutkinnon osien määrä (suorittaa koko tutkintoa)",
            "expression": [
              "",
              "var summa = CALCULATE(CALCULATE(SUM([painottamaton_osatutkinnot]),FILTER(Muuttujat,[Suorituksen tyyppi]=\"Koko tutkinto\")),ALL(Muuttujat[Luvaton korotustekijä]))",
              "return IF(summa=0 || [korotusehto]=0,BLANK(),summa)"
            ],
            "formatString": "#,0",
            "displayFolder": "Painottamattomat"
          },
          {
            "name": "Osaamispisteiden määrä (suorittaa koko tutkintoa)",
            "expression": [
              "",
              "var summa = CALCULATE(CALCULATE(SUM([painottamaton_osaamispisteet]),FILTER(Muuttujat,[Suorituksen tyyppi]=\"Koko tutkinto\")),ALL(Muuttujat[Luvaton korotustekijä]))",
              "return IF(summa=0 || [korotusehto]=0,BLANK(),summa)"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Painottamattomat"
          },
          {
            "name": "Tutkinnon osien määrä (ei suorita koko tutkintoa)",
            "expression": [
              "",
              "var summa = CALCULATE(CALCULATE(SUM(Muuttujat[painottamaton_osatutkinnot]),FILTER(Muuttujat,[Suorituksen tyyppi]=\"Tutkinnon osa/osia\")),ALL(Muuttujat[Luvaton korotustekijä]))",
              "return IF(summa=0 || [korotusehto]=0,BLANK(),summa)"
            ],
            "formatString": "#,0",
            "displayFolder": "Painottamattomat"
          },
          {
            "name": "Osaamispisteiden määrä (ei suorita koko tutkintoa)",
            "expression": [
              "",
              "var summa = CALCULATE(CALCULATE(SUM([painottamaton_osaamispisteet]),FILTER(Muuttujat,[Suorituksen tyyppi]=\"Tutkinnon osa/osia\")),ALL(Muuttujat[Luvaton korotustekijä]))",
              "return IF(summa=0 || [korotusehto]=0,BLANK(),summa)"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Painottamattomat"
          },
          {
            "name": "Perustutkintojen kustannusryhmän ja pohjakoulutuksen mukaan painotetut pisteet",
            "expression": [
              "",
              "var summa=CALCULATE(SUM([painotettu_tutkinnot_pt_kr_pk]),ALL(Muuttujat[Luvaton korotustekijä]))",
              "return IF(summa=0 || [korotusehto]=0,BLANK(),summa)"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Painotetut"
          },
          {
            "name": "Ammatti- ja erikoisammattitutkintojen kustannusryhmän ja pohjakoulutuksen mukaan painotetut pisteet",
            "expression": [
              "",
              "var summa=CALCULATE(SUM([painotettu_tutkinnot_at_eat_kr_pk]),ALL(Muuttujat[Luvaton korotustekijä]))",
              "return IF(summa=0 || [korotusehto]=0,BLANK(),summa)"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Painotetut"
          },
          {
            "name": "Erityisen tuen mukaan painotetut tutkintojen pisteet",
            "expression": [
              "",
              "var summa=SUM(Muuttujat[painotettu_tutkinnot_erityistuki])",
              "return IF(summa=0,BLANK(),summa)"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Painotetut"
          },
          {
            "name": "Perustutkintojen osien kustannusryhmän mukaan painotetut osaamispisteet",
            "expression": [
              "",
              "var summa=CALCULATE(SUM([painotettu_tutkinnon_osien_osaamispisteet_pt_kr]),ALL(Muuttujat[Luvaton korotustekijä]))",
              "return IF(summa=0 || [korotusehto]=0,BLANK(),summa)"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Painotetut"
          },
          {
            "name": "Ammatti- ja erikoisammattitutkintojen osien kustannusryhmän mukaan painotetut osaamispisteet",
            "expression": [
              "",
              "var summa=CALCULATE(SUM([painotettu_tutkinnon_osien_osaamispisteet_at_eat_kr]),ALL(Muuttujat[Luvaton korotustekijä]))",
              "return IF(summa=0 || [korotusehto]=0,BLANK(),summa)"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Painotetut"
          },
          {
            "name": "Erityisen tuen mukaan painotetut tutkinnon osien osaamispisteet",
            "expression": [
              "",
              "var summa=SUM([painotettu_tutkinnon_osien_osaamispisteet_erityistuki])",
              "return IF(summa=0,BLANK(),summa)"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Painotetut"
          },
          {
            "name": "Tutkintojen painotetut pisteet yhteensä",
            "expression": [
              "",
              "[Perustutkintojen kustannusryhmän ja pohjakoulutuksen mukaan painotetut pisteet]",
              "+[Ammatti- ja erikoisammattitutkintojen kustannusryhmän ja pohjakoulutuksen mukaan painotetut pisteet]",
              "+[Erityisen tuen mukaan painotetut tutkintojen pisteet]"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Painotetut"
          },
          {
            "name": "Tutkinnon osien painotetut osaamispisteet yhteensä",
            "expression": [
              "",
              "[Perustutkintojen osien kustannusryhmän mukaan painotetut osaamispisteet]",
              "+[Ammatti- ja erikoisammattitutkintojen osien kustannusryhmän mukaan painotetut osaamispisteet]",
              "+[Erityisen tuen mukaan painotetut tutkinnon osien osaamispisteet]"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Painotetut"
          },
          {
            "name": "Tutkintojen ja tutkinnon osien painotetut pisteet yhteensä",
            "expression": [
              "",
              "[Tutkintojen painotetut pisteet yhteensä]",
              "+[Laskentaan hyväksytyt painotetut osaamispisteet]"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Painotetut"
          },
          {
            "name": "Perustutkintojen kustannusryhmän ja pohjakoulutuksen mukaan painotetut pisteet %",
            "expression": "DIVIDE([Perustutkintojen kustannusryhmän ja pohjakoulutuksen mukaan painotetut pisteet], CALCULATE([Perustutkintojen kustannusryhmän ja pohjakoulutuksen mukaan painotetut pisteet],ALL(Muuttujat[Koulutuksen järjestäjä])))",
            "formatString": "#,0.00 %;-#,0.00 %;#,0.00 %",
            "displayFolder": "Prosenttiosuudet"
          },
          {
            "name": "Ammatti- ja erikoisammattitutkintojen kustannusryhmän ja pohjakoulutuksen mukaan painotetut pist %",
            "expression": "DIVIDE([Ammatti- ja erikoisammattitutkintojen kustannusryhmän ja pohjakoulutuksen mukaan painotetut pisteet],CALCULATE([Ammatti- ja erikoisammattitutkintojen kustannusryhmän ja pohjakoulutuksen mukaan painotetut pisteet],ALL(Muuttujat[Koulutuksen järjestäjä])))",
            "formatString": "#,0.00 %;-#,0.00 %;#,0.00 %",
            "displayFolder": "Prosenttiosuudet"
          },
          {
            "name": "Erityisen tuen mukaan painotetut tutkintojen pisteet %",
            "expression": "DIVIDE([Erityisen tuen mukaan painotetut tutkintojen pisteet],CALCULATE([Erityisen tuen mukaan painotetut tutkintojen pisteet],ALL(Muuttujat[Koulutuksen järjestäjä])))",
            "formatString": "#,0.00 %;-#,0.00 %;#,0.00 %",
            "displayFolder": "Prosenttiosuudet"
          },
          {
            "name": "Perustutkintojen osien kustannusryhmän mukaan painotetut osaamispisteet %",
            "expression": "DIVIDE([Perustutkintojen osien kustannusryhmän mukaan painotetut osaamispisteet],CALCULATE([Perustutkintojen osien kustannusryhmän mukaan painotetut osaamispisteet],ALL(Muuttujat[Koulutuksen järjestäjä])))",
            "formatString": "#,0.00 %;-#,0.00 %;#,0.00 %",
            "displayFolder": "Prosenttiosuudet"
          },
          {
            "name": "Ammatti- ja erikoisammattitutkintojen osien kustannusryhmän mukaan painotetut osaamispisteet %",
            "expression": "DIVIDE([Ammatti- ja erikoisammattitutkintojen osien kustannusryhmän mukaan painotetut osaamispisteet],CALCULATE([Ammatti- ja erikoisammattitutkintojen osien kustannusryhmän mukaan painotetut osaamispisteet],ALL(Muuttujat[Koulutuksen järjestäjä])))",
            "formatString": "#,0.00 %;-#,0.00 %;#,0.00 %",
            "displayFolder": "Prosenttiosuudet"
          },
          {
            "name": "Erityisen tuen mukaan painotetut tutkinnon osien osaamispisteet %",
            "expression": "DIVIDE([Erityisen tuen mukaan painotetut tutkinnon osien osaamispisteet],CALCULATE([Erityisen tuen mukaan painotetut tutkinnon osien osaamispisteet],ALL(Muuttujat[Koulutuksen järjestäjä])))",
            "formatString": "#,0.00 %;-#,0.00 %;#,0.00 %",
            "displayFolder": "Prosenttiosuudet"
          },
          {
            "name": "Tutkintojen painotetut pisteet yhteensä %",
            "expression": [
              "",
              "DIVIDE(",
              "\t[Tutkintojen painotetut pisteet yhteensä],",
              "\tCALCULATE([Tutkintojen painotetut pisteet yhteensä],ALLEXCEPT(Muuttujat,Muuttujat[Rahoitusmuoto]),Muuttujat[Tilastovuosi])",
              ")"
            ],
            "formatString": "#,0.00 %;-#,0.00 %;#,0.00 %",
            "displayFolder": "Prosenttiosuudet"
          },
          {
            "name": "Tutkintojen ja tutkinnon osien painotetut pisteet, järj. %-osuus",
            "expression": [
              "",
              "DIVIDE(",
              "\t[Tutkintojen ja tutkinnon osien painotetut pisteet yhteensä],",
              "\tCALCULATE([Tutkintojen ja tutkinnon osien painotetut pisteet yhteensä],ALLEXCEPT(Muuttujat,Muuttujat[Rahoitusmuoto],Muuttujat[Tilastovuosi]))",
              ")"
            ],
            "formatString": "#,0.00 %;-#,0.00 %;#,0.00 %",
            "displayFolder": "Prosenttiosuudet"
          },
          {
            "name": "Tutkinnon osien painotetut osaamispisteet yhteensä %",
            "expression": [
              "",
              "DIVIDE(",
              "\t[Tutkinnon osien painotetut osaamispisteet yhteensä],",
              "\tCALCULATE([Tutkinnon osien painotetut osaamispisteet yhteensä],ALLEXCEPT(Muuttujat,Muuttujat[Rahoitusmuoto]),Muuttujat[Tilastovuosi])",
              ")"
            ],
            "formatString": "#,0.00 %;-#,0.00 %;#,0.00 %",
            "displayFolder": "Prosenttiosuudet"
          },
          {
            "name": "Tavoitteelliset opiskelijavuodet",
            "expression": [
              "",
              "SUMX(",
              "\tSUMMARIZE(Muuttujat,[Koodit Koulutuksen järjestäjä],[tavoitteelliset_opv])",
              "\t,[tavoitteelliset_opv]",
              ")"
            ]
          },
          {
            "name": "Maksimiosaamispisteet",
            "expression": "[Tavoitteelliset opiskelijavuodet] * 120.0"
          },
          {
            "name": "Tutkinnon osien painottamattomat osaamispisteet yhteensä",
            "expression": "[Osaamispisteiden määrä (ei suorita koko tutkintoa)]+[Osaamispisteiden määrä (suorittaa koko tutkintoa)]",
            "formatString": "#,0.00"
          },
          {
            "name": "Laskentaan hyväksytyt painotetut osaamispisteet",
            "expression": [
              "",
              "var summa1 = CALCULATE(SUMX(Muuttujat,[painotettu_tutkinnon_osien_osaamispisteet_pt_kr] * IF(Muuttujat[rahoitusmuoto_maksetaan]=1 && [hyvaksytaan_rahoitukseen]=1,[leikkauskerroin2],0)),ALL(Muuttujat[Luvaton korotustekijä]))",
              "var summa2 = CALCULATE(SUMX(Muuttujat,[painotettu_tutkinnon_osien_osaamispisteet_at_eat_kr] * IF(Muuttujat[rahoitusmuoto_maksetaan]=1 && [hyvaksytaan_rahoitukseen]=1,[leikkauskerroin2],0)),ALL(Muuttujat[Luvaton korotustekijä]))",
              "var summa3 = CALCULATE(SUMX(Muuttujat,[painotettu_tutkinnon_osien_osaamispisteet_erityistuki] * IF(Muuttujat[rahoitusmuoto_maksetaan]=1 && [hyvaksytaan_rahoitukseen]=1,[leikkauskerroin2],0)),Muuttujat[jarj_luvaton_korotustekija]=\"1\")",
              "var summa = summa1+summa2+summa3",
              "return IF(summa=0 || [korotusehto]=0,BLANK(),summa)"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Painotetut"
          },
          {
            "name": "Laskentaan hyväksytyt painottamattomat osaamispisteet",
            "expression": [
              "",
              "var summa = CALCULATE(SUMX(Muuttujat, [painottamaton_osaamispisteet] * IF(Muuttujat[rahoitusmuoto_maksetaan]=1,Muuttujat[leikkauskerroin2],0)),ALL(Muuttujat[Luvaton korotustekijä]))",
              "return IF(summa=0 || [korotusehto]=0,BLANK(),summa)"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Painottamattomat"
          },
          {
            "name": "Laskentaan hyväksytyt painotetut osaamispisteet %",
            "expression": [
              "",
              "DIVIDE(",
              "\t[Laskentaan hyväksytyt painotetut osaamispisteet]",
              "\t,CALCULATE([Laskentaan hyväksytyt painotetut osaamispisteet],ALLEXCEPT(Muuttujat,Muuttujat[Rahoitusmuoto]),Muuttujat[Tilastovuosi])",
              ")"
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %",
            "displayFolder": "Prosenttiosuudet"
          },
          {
            "name": "Leikkauskerroin",
            "expression": "AVERAGE([leikkauskerroin2])"
          },
          {
            "name": "korotusehto",
            "expression": "IF(COUNTROWS(VALUES(Muuttujat[jarj_luvaton_korotustekija]))=1,IF(VALUES(Muuttujat[jarj_luvaton_korotustekija])=\"1\",1,0),1)"
          },
          {
            "name": "Perustutkintojen määrä",
            "expression": [
              "",
              "var summa = CALCULATE(CALCULATE(SUM([painottamaton_tutkinnot]),Muuttujat[Suorituksen tyyppi]=\"Koko tutkinto\",Muuttujat[Koodit Tutkintotyyppi]=\"02\"),ALL(Muuttujat[Luvaton korotustekijä]))",
              "return IF(summa=0 || [korotusehto]=0,BLANK(),summa)"
            ],
            "formatString": "#,0",
            "displayFolder": "Painottamattomat"
          },
          {
            "name": "Ammatti- ja erikoisammattitutkintojen määrä",
            "expression": [
              "",
              "var summa = CALCULATE(CALCULATE(SUM([painottamaton_tutkinnot]),Muuttujat[Suorituksen tyyppi]=\"Koko tutkinto\",Muuttujat[Koodit Tutkintotyyppi]=\"19\" || Muuttujat[Koodit Tutkintotyyppi]=\"20\"),ALL(Muuttujat[Luvaton korotustekijä]))",
              "return IF(summa=0 || [korotusehto]=0,BLANK(),summa)"
            ],
            "formatString": "#,0",
            "displayFolder": "Painottamattomat"
          },
          {
            "name": "Perustutkintojen tutkinnon osien määrä",
            "expression": [
              "",
              "var summa = CALCULATE(CALCULATE(SUM(Muuttujat[painottamaton_osatutkinnot]),Muuttujat[Koodit Tutkintotyyppi]=\"02\"),ALL(Muuttujat[Luvaton korotustekijä]))",
              "return IF(summa=0 || [korotusehto]=0,BLANK(),summa)"
            ],
            "formatString": "#,0",
            "displayFolder": "Painottamattomat"
          },
          {
            "name": "Ammatti- ja erikoisammattitutkintojen tutkinnon osien määrä",
            "expression": [
              "",
              "var summa = CALCULATE(CALCULATE(SUM(Muuttujat[painottamaton_osatutkinnot]),Muuttujat[Koodit Tutkintotyyppi]=\"19\" || Muuttujat[Koodit Tutkintotyyppi]=\"20\"),ALL(Muuttujat[Luvaton korotustekijä]))",
              "return IF(summa=0 || [korotusehto]=0,BLANK(),summa)"
            ],
            "formatString": "#,0",
            "displayFolder": "Painottamattomat"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dw].[v_amos_tutkinnot_ja_tutkinnonosat_uusi].* FROM [dw].[v_amos_tutkinnot_ja_tutkinnonosat_uusi] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "v_amos_tutkinnot_ja_tutkinnonosat_uusi"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dw"
          }
        ]
      }
    ],
    "perspectives": [
      {
        "name": "Rahoitus",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Erityisopetus"
              },
              {
                "name": "Hankintakoulutuksen järjestäjä"
              },
              {
                "name": "Hankintakoulutus"
              },
              {
                "name": "Ikä"
              },
              {
                "name": "Ikäryhmä"
              },
              {
                "name": "Koodit Hankintakoulutuksen järjestäjä"
              },
              {
                "name": "Koodit Koulutuksen järjestäjä"
              },
              {
                "name": "Koodit Tutkinto"
              },
              {
                "name": "Koulutuksen järjestäjä"
              },
              {
                "name": "Koulutuksen järjestäjän AVI"
              },
              {
                "name": "Koulutuksen järjestäjän ELY"
              },
              {
                "name": "Koulutuksen järjestäjän kunta"
              },
              {
                "name": "Koulutuksen järjestäjän maakunta"
              },
              {
                "name": "Koulutusala, taso 1"
              },
              {
                "name": "Koulutusala, taso 2"
              },
              {
                "name": "Koulutusala, taso 3"
              },
              {
                "name": "Kustannusryhmä"
              },
              {
                "name": "Luvaton korotustekijä"
              },
              {
                "name": "Luvaton koulutus"
              },
              {
                "name": "Oppilaitoksen AVI"
              },
              {
                "name": "Oppilaitoksen ELY"
              },
              {
                "name": "Oppilaitoksen kunta"
              },
              {
                "name": "Oppilaitoksen maakunta"
              },
              {
                "name": "Oppilaitos"
              },
              {
                "name": "Oppisopimuskoulutus"
              },
              {
                "name": "Rahoitusmuoto"
              },
              {
                "name": "Sukupuoli"
              },
              {
                "name": "Suorituksen tyyppi"
              },
              {
                "name": "Tilastokuukausi"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Toimipiste"
              },
              {
                "name": "Toimipisteen AVI"
              },
              {
                "name": "Toimipisteen ELY"
              },
              {
                "name": "Toimipisteen kunta"
              },
              {
                "name": "Toimipisteen maakunta"
              },
              {
                "name": "Tutkinto"
              },
              {
                "name": "Tutkintotyyppi"
              },
              {
                "name": "Äidinkieli"
              }
            ],
            "measures": [
              {
                "name": "Ammatti- ja erikoisammattitutkintojen kustannusryhmän ja pohjakoulutuksen mukaan painotetut pist %"
              },
              {
                "name": "Ammatti- ja erikoisammattitutkintojen kustannusryhmän ja pohjakoulutuksen mukaan painotetut pisteet"
              },
              {
                "name": "Ammatti- ja erikoisammattitutkintojen osien kustannusryhmän mukaan painotetut osaamispisteet"
              },
              {
                "name": "Ammatti- ja erikoisammattitutkintojen osien kustannusryhmän mukaan painotetut osaamispisteet %"
              },
              {
                "name": "Erityisen tuen mukaan painotetut tutkinnon osien osaamispisteet"
              },
              {
                "name": "Erityisen tuen mukaan painotetut tutkinnon osien osaamispisteet %"
              },
              {
                "name": "Erityisen tuen mukaan painotetut tutkintojen pisteet"
              },
              {
                "name": "Erityisen tuen mukaan painotetut tutkintojen pisteet %"
              },
              {
                "name": "Laskentaan hyväksytyt painotetut osaamispisteet"
              },
              {
                "name": "Laskentaan hyväksytyt painotetut osaamispisteet %"
              },
              {
                "name": "Laskentaan hyväksytyt painottamattomat osaamispisteet"
              },
              {
                "name": "Osaamispisteiden määrä (ei suorita koko tutkintoa)"
              },
              {
                "name": "Osaamispisteiden määrä (suorittaa koko tutkintoa)"
              },
              {
                "name": "Perustutkintojen kustannusryhmän ja pohjakoulutuksen mukaan painotetut pisteet"
              },
              {
                "name": "Perustutkintojen kustannusryhmän ja pohjakoulutuksen mukaan painotetut pisteet %"
              },
              {
                "name": "Perustutkintojen osien kustannusryhmän mukaan painotetut osaamispisteet"
              },
              {
                "name": "Perustutkintojen osien kustannusryhmän mukaan painotetut osaamispisteet %"
              },
              {
                "name": "Tutkinnon osien määrä (ei suorita koko tutkintoa)"
              },
              {
                "name": "Tutkinnon osien määrä (suorittaa koko tutkintoa)"
              },
              {
                "name": "Tutkinnon osien painotetut osaamispisteet yhteensä"
              },
              {
                "name": "Tutkinnon osien painotetut osaamispisteet yhteensä %"
              },
              {
                "name": "Tutkintojen ja tutkinnon osien painotetut pisteet yhteensä"
              },
              {
                "name": "Tutkintojen ja tutkinnon osien painotetut pisteet, järj. %-osuus"
              },
              {
                "name": "Tutkintojen määrä"
              },
              {
                "name": "Tutkintojen painotetut pisteet yhteensä"
              },
              {
                "name": "Tutkintojen painotetut pisteet yhteensä %"
              },
              {
                "name": "Ammatti- ja erikoisammattitutkintojen määrä"
              },
              {
                "name": "Ammatti- ja erikoisammattitutkintojen tutkinnon osien määrä"
              },
              {
                "name": "Perustutkintojen määrä"
              },
              {
                "name": "Perustutkintojen tutkinnon osien määrä"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      }
    ],
    "roles": [
      {
        "name": "Luku",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "DWI\\P_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1733"
          },
          {
            "memberName": "DWI\\T_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1732"
          },
          {
            "memberName": "NT AUTHORITY\\IUSR",
            "memberId": "S-1-5-17"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "400"
      }
    ]
  },
  "id": "SemanticModel"
}
