{
  "name": "SemanticModel",
  "compatibilityLevel": 1200,
  "model": {
    "culture": "fi-FI",
    "dataSources": [
      {
        "name": "SqlServer dwitvipusql16 ANTERO",
        "connectionString": "Provider=SQLOLEDB.1;Data Source=dwitvipusql22;Initial Catalog=ANTERO;Integrated Security=SSPI;Persist Security Info=false",
        "impersonationMode": "impersonateServiceAccount",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "Muuttujat",
        "columns": [
          {
            "name": "Osa-aikaisuus",
            "dataType": "string",
            "sourceColumn": "Osa-aikaisuus",
            "sourceProviderType": "Char",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Tilastovuosi",
            "dataType": "int64",
            "sourceColumn": "Tilastovuosi",
            "sourceProviderType": "Integer",
            "displayFolder": "Aikamuuttujat"
          },
          {
            "name": "Kustannusryhmä",
            "dataType": "string",
            "sourceColumn": "Kustannusryhmä",
            "sortByColumn": "jarj_kustannusryhma",
            "sourceProviderType": "Char",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Tutkintotyyppi",
            "dataType": "string",
            "sourceColumn": "Tutkintotyyppi",
            "sortByColumn": "jarj_tutkintotyyppi",
            "sourceProviderType": "Char",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Oppisopimuskoulutus",
            "dataType": "string",
            "sourceColumn": "Oppisopimuskoulutus",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Erityisopetus",
            "dataType": "string",
            "sourceColumn": "Erityisopetus",
            "sortByColumn": "jarj_erityisopetus",
            "sourceProviderType": "Integer",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Majoitus",
            "dataType": "string",
            "sourceColumn": "Majoitus",
            "sourceProviderType": "Char",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Vankilaopetus",
            "dataType": "string",
            "sourceColumn": "Vankilaopetus",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Henkilöstokoulutus",
            "dataType": "string",
            "sourceColumn": "Henkilöstokoulutus",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Työvoimakoulutus",
            "dataType": "string",
            "sourceColumn": "Työvoimakoulutus",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Tutkinto",
            "dataType": "string",
            "sourceColumn": "Tutkinto",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Oppilaitos",
            "dataType": "string",
            "sourceColumn": "Oppilaitos",
            "sourceProviderType": "WChar",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Oppilaitoksen kunta",
            "dataType": "string",
            "sourceColumn": "Oppilaitoksen kunta",
            "sourceProviderType": "WChar",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Oppilaitoksen AVI",
            "dataType": "string",
            "sourceColumn": "Oppilaitoksen AVI",
            "sortByColumn": "jarj_oppilaitoksen_avi",
            "sourceProviderType": "WChar",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Oppilaitoksen ELY",
            "dataType": "string",
            "sourceColumn": "Oppilaitoksen ELY",
            "sortByColumn": "jarj_oppilaitoksen_ely",
            "sourceProviderType": "WChar",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Oppilaitoksen maakunta",
            "dataType": "string",
            "sourceColumn": "Oppilaitoksen maakunta",
            "sortByColumn": "jarj_oppilaitoksen_maakunta",
            "sourceProviderType": "WChar",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Koulutuksen järjestäjä",
            "dataType": "string",
            "sourceColumn": "Koulutuksen järjestäjä",
            "sourceProviderType": "WChar",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Koul. järjestäjän kunta",
            "dataType": "string",
            "sourceColumn": "Koul. järjestäjän kunta",
            "sourceProviderType": "WChar",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Koul. järjestäjän AVI",
            "dataType": "string",
            "sourceColumn": "Koul. järjestäjän AVI",
            "sortByColumn": "jarj_koul_jarj_avi",
            "sourceProviderType": "WChar",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Koul. järjestäjän ELY",
            "dataType": "string",
            "sourceColumn": "Koul. järjestäjän ELY",
            "sortByColumn": "jarj_koul_jarj_ely",
            "sourceProviderType": "WChar",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Koul. järjestäjän maakunta",
            "dataType": "string",
            "sourceColumn": "Koul. järjestäjän maakunta",
            "sortByColumn": "jarj_koul_jarj_maakunta",
            "sourceProviderType": "WChar",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Ikä",
            "dataType": "string",
            "sourceColumn": "Ikä",
            "sortByColumn": "jarj_ika",
            "sourceProviderType": "WChar",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Ikäryhmä",
            "dataType": "string",
            "sourceColumn": "Ikäryhmä",
            "sortByColumn": "jarj_ikaryhma",
            "sourceProviderType": "WChar",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Äidinkieli",
            "dataType": "string",
            "sourceColumn": "Äidinkieli",
            "sourceProviderType": "WChar",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Sukupuoli",
            "dataType": "string",
            "sourceColumn": "Sukupuoli",
            "sortByColumn": "jarj_sukupuoli",
            "sourceProviderType": "WChar",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Koulutusala, taso 1",
            "dataType": "string",
            "sourceColumn": "Koulutusala, taso 1",
            "sortByColumn": "jarj_koulutusala_taso1",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusala, taso 2",
            "dataType": "string",
            "sourceColumn": "Koulutusala, taso 2",
            "sortByColumn": "jarj_koulutusala_taso2",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusala, taso 3",
            "dataType": "string",
            "sourceColumn": "Koulutusala, taso 3",
            "sortByColumn": "jarj_koulutusala_taso3",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Tutkintotyypin ryhmä",
            "dataType": "string",
            "sourceColumn": "Tutkintotyypin ryhmä",
            "sortByColumn": "jarj_tutkintotyypin_ryhma",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Suorituksen tyyppi",
            "dataType": "string",
            "sourceColumn": "Suorituksen tyyppi",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "jarj_tutkintotyyppi",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarj_tutkintotyyppi"
          },
          {
            "name": "jarj_erityisopetus",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_erityisopetus"
          },
          {
            "name": "jarj_koulutusala_taso1",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_koulutusala_taso1"
          },
          {
            "name": "jarj_koulutusala_taso2",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_koulutusala_taso2"
          },
          {
            "name": "jarj_koulutusala_taso3",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_koulutusala_taso3"
          },
          {
            "name": "jarj_oppilaitoksen_maakunta",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_oppilaitoksen_maakunta"
          },
          {
            "name": "jarj_oppilaitoksen_avi",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_oppilaitoksen_avi"
          },
          {
            "name": "jarj_oppilaitoksen_ely",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_oppilaitoksen_ely"
          },
          {
            "name": "jarj_koul_jarj_maakunta",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_koul_jarj_maakunta"
          },
          {
            "name": "jarj_koul_jarj_avi",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_koul_jarj_avi"
          },
          {
            "name": "jarj_koul_jarj_ely",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_koul_jarj_ely"
          },
          {
            "name": "jarj_ikaryhma",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_ikaryhma"
          },
          {
            "name": "jarj_sukupuoli",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_sukupuoli"
          },
          {
            "name": "Koodit Koulutuksen järjestäjä",
            "dataType": "string",
            "sourceColumn": "Koodit Koulutuksen järjestäjä",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koodit Oppilaitos",
            "dataType": "string",
            "sourceColumn": "Koodit Oppilaitos",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koodit Tutkinto",
            "dataType": "string",
            "sourceColumn": "Koodit Tutkinto",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "jarj_tutkintotyypin_ryhma",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarj_tutkintotyypin_ryhma"
          },
          {
            "name": "jarj_kustannusryhma",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarj_kustannusryhma"
          },
          {
            "name": "Rahoitusmuoto",
            "dataType": "string",
            "sourceColumn": "Rahoitusmuoto",
            "sortByColumn": "jarj_rahoitusmuoto",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "jarj_rahoitusmuoto",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarj_rahoitusmuoto"
          },
          {
            "name": "Osaamisala",
            "dataType": "string",
            "sourceColumn": "Osaamisala",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koodit Osaamisala",
            "dataType": "string",
            "sourceColumn": "Koodit Osaamisala",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Toimipiste",
            "dataType": "string",
            "sourceColumn": "Toimipiste",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "jarj_hylkaamisperuste",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_hylkaamisperuste"
          },
          {
            "name": "jarj_ika",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarj_ika"
          },
          {
            "name": "Hyväksytyt/hylätyt opiskelijavuodet",
            "dataType": "string",
            "sourceColumn": "Hyväksytyt/hylätyt opiskelijavuodet",
            "sortByColumn": "jarj_hylkaamisperuste",
            "displayFolder": "Rahoitusmallimuuttujat"
          },
          {
            "name": "Tilastokuukausi",
            "dataType": "string",
            "sourceColumn": "Tilastokuukausi",
            "sortByColumn": "jarj_tilastokuukausi",
            "sourceProviderType": "Char",
            "displayFolder": "Aikamuuttujat"
          },
          {
            "name": "jarj_tilastokuukausi",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarj_tilastokuukausi"
          },
          {
            "name": "Luvaton koulutus",
            "dataType": "string",
            "sourceColumn": "Luvaton koulutus",
            "sortByColumn": "jarj_luvaton_koulutus",
            "displayFolder": "Järjestämislupamuuttujat"
          },
          {
            "name": "Luvaton majoitus",
            "dataType": "string",
            "sourceColumn": "Luvaton majoitus",
            "sortByColumn": "jarj_luvaton_majoitus",
            "displayFolder": "Järjestämislupamuuttujat"
          },
          {
            "name": "Luvaton korotustekijä",
            "dataType": "string",
            "sourceColumn": "Luvaton korotustekijä",
            "sortByColumn": "jarj_luvaton_korotustekija",
            "displayFolder": "Järjestämislupamuuttujat"
          },
          {
            "name": "jarj_luvaton_koulutus",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarj_luvaton_koulutus"
          },
          {
            "name": "jarj_luvaton_majoitus",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarj_luvaton_majoitus"
          },
          {
            "name": "jarj_luvaton_korotustekija",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarj_luvaton_korotustekija"
          },
          {
            "name": "Hankintakoulutus",
            "dataType": "string",
            "sourceColumn": "Hankintakoulutus",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Hankintakoulutuksen järjestäjä",
            "dataType": "string",
            "sourceColumn": "Hankintakoulutuksen järjestäjä",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Koodit Hankintakoulutuksen järjestäjä",
            "dataType": "string",
            "sourceColumn": "Koodit Hankintakoulutuksen järjestäjä",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "painottamaton",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "painottamaton"
          },
          {
            "name": "Suorituskieli",
            "dataType": "string",
            "sourceColumn": "Suorituskieli",
            "sortByColumn": "jarj_suorituskieli",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "jarj_suorituskieli",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_suorituskieli"
          },
          {
            "name": "Luvanmukainen suorituskieli",
            "dataType": "string",
            "sourceColumn": "Luvanmukainen suorituskieli",
            "sortByColumn": "jarj_suorituskieli_luvanmukainen",
            "displayFolder": "Järjestämislupamuuttujat"
          },
          {
            "name": "jarj_suorituskieli_luvanmukainen",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarj_suorituskieli_luvanmukainen"
          },
          {
            "name": "Toimipisteen kunta",
            "dataType": "string",
            "sourceColumn": "Toimipisteen kunta",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Toimipisteen maakunta",
            "dataType": "string",
            "sourceColumn": "Toimipisteen maakunta",
            "sortByColumn": "jarjestys_toimipisteen_maakunta",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Hankintakoulutuksen järjestäjän kunta",
            "dataType": "string",
            "sourceColumn": "Hankintakoulutuksen järjestäjän kunta"
          },
          {
            "name": "jarjestys_toimipisteen_maakunta",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarjestys_toimipisteen_maakunta"
          },
          {
            "name": "Koulutuksen alkamisvuosi",
            "dataType": "string",
            "sourceColumn": "Koulutuksen alkamisvuosi",
            "sourceProviderType": "WChar",
            "displayFolder": "Aikamuuttujat"
          },
          {
            "name": "Koulutuksen alkamiskuukausi",
            "dataType": "string",
            "sourceColumn": "Koulutuksen alkamiskuukausi",
            "sortByColumn": "jarj_koulutuksen_alkamiskuukausi",
            "sourceProviderType": "WChar",
            "displayFolder": "Aikamuuttujat"
          },
          {
            "name": "jarj_koulutuksen_alkamiskuukausi",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarj_koulutuksen_alkamiskuukausi"
          },
          {
            "name": "Vaativa erityinen tuki",
            "dataType": "string",
            "sourceColumn": "Vaativa erityinen tuki",
            "sortByColumn": "jarjestys Vaativa erityinen tuki",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Maksuttomuus (simulointi)",
            "dataType": "string",
            "sourceColumn": "Maksuttomuus (simulointi)",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Toisen asteen pohjakoulutus (2018-)",
            "dataType": "string",
            "sourceColumn": "Toisen asteen pohjakoulutus (2018-)",
            "sortByColumn": "jarj_toisen_asteen_pohjakoulutus_2018",
            "sourceProviderType": "WChar",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "jarj_toisen_asteen_pohjakoulutus_2018",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_toisen_asteen_pohjakoulutus_2018"
          },
          {
            "name": "Maksuttomuus (KOSKI)",
            "dataType": "string",
            "sourceColumn": "Maksuttomuus (KOSKI)",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Rahoituskausi",
            "dataType": "string",
            "sourceColumn": "Rahoituskausi",
            "sourceProviderType": "Char",
            "displayFolder": "Aikamuuttujat"
          },
          {
            "name": "Vaativan erityisen tuen opiskelijavuosien enimmäismäärä",
            "dataType": "string",
            "sourceColumn": "Vaativan erityisen tuen opiskelijavuosien enimmäismäärä",
            "sortByColumn": "jarjestys Vaativan erityisen tuen opiskelijavuosien enimmäismäärä",
            "displayFolder": "Järjestämislupamuuttujat"
          },
          {
            "name": "Ei maksuttomien opiskelijavuosien enimmäismäärä",
            "dataType": "string",
            "sourceColumn": "Ei maksuttomien opiskelijavuosien enimmäismäärä",
            "sortByColumn": "jarjestys Ei maksuttomien opiskelijavuosien enimmäismäärä",
            "displayFolder": "Järjestämislupamuuttujat"
          },
          {
            "name": "opv_ei_maksuton_kerroin",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "opv_ei_maksuton_kerroin"
          },
          {
            "name": "Toteuma/Estimaatti",
            "dataType": "string",
            "sourceColumn": "Toteuma/Estimaatti",
            "sourceProviderType": "Char",
            "displayFolder": "Rahoitusmallimuuttujat"
          },
          {
            "name": "Koul. järjestäjän PILKE-alue (kokeilu)",
            "dataType": "string",
            "sourceColumn": "Koul. järjestäjän PILKE-alue (kokeilu)",
            "sortByColumn": "jarjestys Koul. järjestäjän PILKE-alue (kokeilu)",
            "sourceProviderType": "Char",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "jarjestys Koul. järjestäjän PILKE-alue (kokeilu)",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarjestys Koul. järjestäjän PILKE-alue (kokeilu)"
          },
          {
            "name": "Tutkintotyyppi (rahoitus)",
            "dataType": "string",
            "sourceColumn": "Tutkintotyyppi (rahoitus)",
            "sortByColumn": "jarjestys Tutkintotyyppi (rahoitus)",
            "sourceProviderType": "Char",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "jarjestys Tutkintotyyppi (rahoitus)",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarjestys Tutkintotyyppi (rahoitus)"
          },
          {
            "name": "Perusop. suoritusvuosi",
            "dataType": "int64",
            "sourceColumn": "Perusop. suoritusvuosi",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Perusop. keskiarvoluokka",
            "dataType": "string",
            "sourceColumn": "Perusop. keskiarvoluokka",
            "sortByColumn": "jarj_perusop_keskiarvoluokka",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Perusop. yksilöllistäminen",
            "dataType": "string",
            "sourceColumn": "Perusop. yksilöllistäminen",
            "sortByColumn": "jarj_perusop_yksilollistaminen",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "jarj_perusop_keskiarvoluokka",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarj_perusop_keskiarvoluokka"
          },
          {
            "name": "jarj_perusop_yksilollistaminen",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarj_perusop_yksilollistaminen"
          },
          {
            "name": "Perusop. keskiarvoluokka 2",
            "dataType": "string",
            "sourceColumn": "Perusop. keskiarvoluokka 2",
            "sortByColumn": "jarj_perusop_keskiarvoluokka_2",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "jarj_perusop_keskiarvoluokka_2",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarj_perusop_keskiarvoluokka_2"
          },
          {
            "name": "jarjestys Vaativan erityisen tuen opiskelijavuosien enimmäismäärä",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarjestys Vaativan erityisen tuen opiskelijavuosien enimmäismäärä"
          },
          {
            "name": "jarjestys Ei maksuttomien opiskelijavuosien enimmäismäärä",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarjestys Ei maksuttomien opiskelijavuosien enimmäismäärä"
          },
          {
            "name": "Varainhoitovuosi",
            "dataType": "int64",
            "sourceColumn": "Varainhoitovuosi",
            "sourceProviderType": "Integer",
            "displayFolder": "Aikamuuttujat"
          },
          {
            "name": "Järjestäjärakenne",
            "dataType": "string",
            "sourceColumn": "Järjestäjärakenne",
            "sourceProviderType": "Char",
            "displayFolder": "Rahoitusmallimuuttujat"
          },
          {
            "name": "Suoritettu tutkinto, maksuttomuus (2018-)",
            "dataType": "string",
            "sourceColumn": "Suoritettu tutkinto, maksuttomuus (2018-)",
            "sortByColumn": "jarj_suoritettu_tutkinto_maksuttomuus_2018",
            "sourceProviderType": "WChar",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "jarj_suoritettu_tutkinto_maksuttomuus_2018",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_suoritettu_tutkinto_maksuttomuus_2018"
          },
          {
            "name": "Maksuttomuus (rahoitus)",
            "dataType": "string",
            "sourceColumn": "Maksuttomuus (rahoitus)",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Ikä (maksuttomuusraja)",
            "dataType": "string",
            "sourceColumn": "Ikä (maksuttomuusraja)",
            "sourceProviderType": "WChar",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "jarjestys Vaativa erityinen tuki",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarjestys Vaativa erityinen tuki"
          },
          {
            "name": "painotettu_lahtotaso",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "painotettu_lahtotaso"
          },
          {
            "name": "painotettu_kustannusryhma",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "painotettu_kustannusryhma"
          },
          {
            "name": "painotettu_erityistuki",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "painotettu_erityistuki"
          },
          {
            "name": "painotettu_majoitus",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "painotettu_majoitus"
          },
          {
            "name": "Toiminnanohjauksen kokeilu",
            "dataType": "string",
            "sourceColumn": "Toiminnanohjauksen kokeilu",
            "sortByColumn": "jarjestys Toiminnanohjauksen kokeilu",
            "sourceProviderType": "Char",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "jarjestys Toiminnanohjauksen kokeilu",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarjestys Toiminnanohjauksen kokeilu",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Tilastokausi",
            "dataType": "string",
            "sourceColumn": "Tilastokausi",
            "sourceProviderType": "Char",
            "displayFolder": "Aikamuuttujat"
          },
          {
            "name": "vuosiraportti_1_0",
            "dataType": "int64",
            "sourceColumn": "vuosiraportti_1_0"
          }
        ],
        "partitions": [
          {
            "name": "0",
            "mode": "import",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": [
                "SELECT * ",
                "FROM [dw].[v_amos_opiskelijavuodet_uusi]"
              ],
              "dataSource": "SqlServer dwitvipusql16 ANTERO"
            }
          }
        ],
        "measures": [
          {
            "name": "Painottamattomat enimmäismäärän mukaiset opiskelijavuodet, ka",
            "expression": "0.5 * [Painottamattomat enimmäismäärän mukaiset opiskelijavuodet, lkm]",
            "formatString": "#,0.00"
          },
          {
            "name": "Painotetut rahoituksen perusteena olevat opiskelijavuodet (kust.ryhmä, tutk.tyyppi, korotukset), ka",
            "expression": "0.5 * [Painotetut rahoituksen perusteena olevat opiskelijavuodet (kust.ryhmä, tutk.tyyppi, korotukset), lkm]",
            "formatString": "#,0.00"
          },
          {
            "name": "Painotetut rahoituksen perusteena olevat opiskelijavuodet (kust.ryhmä, tutk.tyyppi, korotukset), %",
            "expression": [
              "",
              "var osa = [Painotetut rahoituksen perusteena olevat opiskelijavuodet (kust.ryhmä, tutk.tyyppi, korotukset), lkm]",
              "var kaikki = CALCULATE([Painotetut rahoituksen perusteena olevat opiskelijavuodet (kust.ryhmä, tutk.tyyppi, korotukset), lkm], ALL(Muuttujat[Koulutuksen järjestäjä]), ALL(Muuttujat[Koodit Koulutuksen järjestäjä]))",
              "return DIVIDE(osa, kaikki)"
            ],
            "formatString": "#,0.00 %;-#,0.00 %;#,0.00 %"
          },
          {
            "name": "Painottamattomat opiskelijavuodet, maksuton, lkm",
            "expression": "CALCULATE([Painottamattomat opiskelijavuodet ilman enimmäismäärärajausta, lkm], FILTER(VALUES(Muuttujat[Maksuttomuus (rahoitus)]), Muuttujat[Maksuttomuus (rahoitus)]=\"Maksuton (rahoitus)\"))",
            "formatString": "#,0.00"
          },
          {
            "name": "Painottamattomat opiskelijavuodet, maksuton, ka",
            "expression": "0.5 * [Painottamattomat opiskelijavuodet, maksuton, lkm]",
            "formatString": "#,0.00"
          },
          {
            "name": "Painottamattomat enimmäismäärän mukaiset opiskelijavuodet, ei maksuton, lkm",
            "expression": "CALCULATE([Painottamattomat enimmäismäärän mukaiset opiskelijavuodet, lkm], FILTER(VALUES(Muuttujat[Maksuttomuus (rahoitus)]), Muuttujat[Maksuttomuus (rahoitus)]=\"Ei maksuton (rahoitus)\"))",
            "formatString": "#,0.00"
          },
          {
            "name": "Painottamattomat enimmäismäärän mukaiset opiskelijavuodet, ei maksuton, ka",
            "expression": "0.5 * [Painottamattomat enimmäismäärän mukaiset opiskelijavuodet, ei maksuton, lkm]",
            "formatString": "#,0.00"
          },
          {
            "name": "Lähtötason mukaan painotetut opiskelijavuodet, maksuton, lkm",
            "expression": "CALCULATE([Lähtötason mukaan painotetut opiskelijavuodet, lkm], FILTER(VALUES(Muuttujat[Maksuttomuus (rahoitus)]), Muuttujat[Maksuttomuus (rahoitus)]=\"Maksuton (rahoitus)\"))",
            "formatString": "#,0.00"
          },
          {
            "name": "Lähtötason mukaan painotetut opiskelijavuodet, maksuton, ka",
            "expression": "0.5 * [Lähtötason mukaan painotetut opiskelijavuodet, maksuton, lkm]",
            "formatString": "#,0.00"
          },
          {
            "name": "Lähtötason mukaan painotetut rahoituksen perusteena olevat opiskelijavuodet, lkm",
            "expression": [
              "",
              "var summa = CALCULATE(SUMX(Muuttujat, [opv_ei_maksuton_kerroin] * [painotettu_lahtotaso]))",
              "return IF(summa=0,BLANK(),summa)"
            ],
            "formatString": "#,0.00"
          },
          {
            "name": "Lähtötason mukaan painotetut rahoituksen perusteena olevat opiskelijavuodet, ka",
            "expression": "0.5 * [Lähtötason mukaan painotetut rahoituksen perusteena olevat opiskelijavuodet, lkm]",
            "formatString": "#,0.00"
          },
          {
            "name": "Lähtötason mukaan painotetut rahoituksen perusteena olevat opiskelijavuodet, %",
            "expression": [
              "",
              "var osa = [Lähtötason mukaan painotetut rahoituksen perusteena olevat opiskelijavuodet, ka]",
              "var kaikki = CALCULATE([Lähtötason mukaan painotetut rahoituksen perusteena olevat opiskelijavuodet, ka], ALL(Muuttujat[Koulutuksen järjestäjä]), ALL(Muuttujat[Koodit Koulutuksen järjestäjä]))",
              "return DIVIDE(osa, kaikki)"
            ],
            "formatString": "#,0.00 %;-#,0.00 %;#,0.00 %"
          },
          {
            "name": "Lähtötason mukaan painotetut enimmäismäärän mukaiset opiskelijavuodet, ei maksuton, lkm",
            "expression": "CALCULATE([Lähtötason mukaan painotetut rahoituksen perusteena olevat opiskelijavuodet, lkm], FILTER(VALUES(Muuttujat[Maksuttomuus (rahoitus)]), Muuttujat[Maksuttomuus (rahoitus)]=\"Ei maksuton (rahoitus)\"))",
            "formatString": "#,0.00"
          },
          {
            "name": "Lähtötason mukaan painotetut enimmäismäärän mukaiset opiskelijavuodet, ei maksuton, ka",
            "expression": "0.5 * [Lähtötason mukaan painotetut enimmäismäärän mukaiset opiskelijavuodet, ei maksuton, lkm]",
            "formatString": "#,0.00"
          },
          {
            "name": "Kust.ryhm. ja tutk.tyyp. mukaan painotetut rahoituksen perusteena olevat opiskelijavuodet, lkm",
            "expression": [
              "",
              "var summa = CALCULATE(SUMX(Muuttujat, [opv_ei_maksuton_kerroin] * [painotettu_kustannusryhma]))",
              "return IF(summa=0,BLANK(),summa)"
            ],
            "formatString": "#,0.00"
          },
          {
            "name": "Kust.ryhm. ja tutk.tyyp. mukaan painotetut rahoituksen perusteena olevat opiskelijavuodet, ka",
            "expression": "0.5 * [Kust.ryhm. ja tutk.tyyp. mukaan painotetut rahoituksen perusteena olevat opiskelijavuodet, lkm]",
            "formatString": "#,0.00"
          },
          {
            "name": "Majoituksen mukaan painotetut rahoituksen perusteena olevat opiskelijavuodet, lkm",
            "expression": [
              "",
              "var summa = CALCULATE(SUMX(Muuttujat, [opv_ei_maksuton_kerroin] * [painotettu_majoitus]))",
              "return IF(summa=0,BLANK(),summa)"
            ],
            "formatString": "#,0.00"
          },
          {
            "name": "Majoituksen mukaan painotetut rahoituksen perusteena olevat opiskelijavuodet, ka",
            "expression": "0.5 * [Majoituksen mukaan painotetut rahoituksen perusteena olevat opiskelijavuodet, lkm]",
            "formatString": "#,0.00"
          },
          {
            "name": "Vaativan erityisen tuen mukaan painotetut rahoituksen perusteena olevat opiskelijavuodet, lkm",
            "expression": [
              "",
              "var summa = CALCULATE(SUMX(Muuttujat, [opv_ei_maksuton_kerroin] * [painotettu_erityistuki]))",
              "return IF(summa=0,BLANK(),summa)"
            ],
            "formatString": "#,0.00"
          },
          {
            "name": "Vaativan erityisen tuen mukaan painotetut rahoituksen perusteena olevat opiskelijavuodet, ka",
            "expression": "0.5 * [Vaativan erityisen tuen mukaan painotetut rahoituksen perusteena olevat opiskelijavuodet, lkm]",
            "formatString": "#,0.00"
          },
          {
            "name": "Keskimääräinen painotus lähtötason mukaan, opiskelijavuodet, maksuton",
            "expression": "DIVIDE([Lähtötason mukaan painotetut opiskelijavuodet, maksuton, lkm], [Painottamattomat opiskelijavuodet, maksuton, lkm])",
            "formatString": "0.0000"
          },
          {
            "name": "Keskimääräinen painotus lähtötason mukaan, enimmäismäärän mukaiset opiskelijavuodet, ei maksuton",
            "expression": "DIVIDE([Lähtötason mukaan painotetut enimmäismäärän mukaiset opiskelijavuodet, ei maksuton, lkm], [Painottamattomat enimmäismäärän mukaiset opiskelijavuodet, ei maksuton, lkm])",
            "formatString": "0.0000"
          },
          {
            "name": "Keskimääräinen painotus, rahoituksen perusteena olevat opiskelijavuodet",
            "expression": "DIVIDE([Painotetut rahoituksen perusteena olevat opiskelijavuodet (kust.ryhmä, tutk.tyyppi, korotukset), lkm], [Painottamattomat enimmäismäärän mukaiset opiskelijavuodet, lkm])",
            "formatString": "0.0000"
          },
          {
            "name": "Painottamattomat enimmäismäärän mukaiset opiskelijavuodet, lkm",
            "expression": [
              "",
              "var summa = CALCULATE(SUMX(Muuttujat, [opv_ei_maksuton_kerroin] * [painottamaton]))",
              "return IF(summa=0,BLANK(),summa)"
            ],
            "formatString": "#,0.00"
          },
          {
            "name": "Painotetut rahoituksen perusteena olevat opiskelijavuodet (kust.ryhmä, tutk.tyyppi, korotukset), lkm",
            "expression": [
              "",
              "var summa = [Kust.ryhm. ja tutk.tyyp. mukaan painotetut rahoituksen perusteena olevat opiskelijavuodet, lkm]",
              "\t+ [Majoituksen mukaan painotetut rahoituksen perusteena olevat opiskelijavuodet, lkm]",
              "\t+ [Vaativan erityisen tuen mukaan painotetut rahoituksen perusteena olevat opiskelijavuodet, lkm]",
              "return IF(summa=0,BLANK(),summa)"
            ],
            "formatString": "#,0.00"
          },
          {
            "name": "Painottamattomat opiskelijavuodet ilman enimmäismäärärajausta, lkm",
            "expression": [
              "",
              "var summa = CALCULATE(SUM(Muuttujat[painottamaton]))",
              "return IF(summa=0,BLANK(),summa)"
            ],
            "formatString": "#,0.00"
          },
          {
            "name": "Painottamattomat opiskelijavuodet ilman enimmäismäärärajausta, ka",
            "expression": "0.5 * [Painottamattomat opiskelijavuodet ilman enimmäismäärärajausta, lkm]",
            "formatString": "#,0.00"
          },
          {
            "name": "Painottamattomat opiskelijavuodet ilman enimmäismäärärajausta, ei maksuton, lkm",
            "expression": "CALCULATE([Painottamattomat opiskelijavuodet ilman enimmäismäärärajausta, lkm], FILTER(VALUES(Muuttujat[Maksuttomuus (rahoitus)]), Muuttujat[Maksuttomuus (rahoitus)]=\"Ei maksuton (rahoitus)\"))",
            "formatString": "#,0.00"
          },
          {
            "name": "Painottamattomat opiskelijavuodet ilman enimmäismäärärajausta, ei maksuton, ka",
            "expression": "0.5 * [Painottamattomat opiskelijavuodet ilman enimmäismäärärajausta, ei maksuton, lkm]",
            "formatString": "#,0.00"
          },
          {
            "name": "Painottamattomat enimmäismäärän mukaiset opiskelijavuodet, ei maksuton / Painottamattomat opiskelijavuodet ilman enimmäismäärärajausta, ei maksuton",
            "expression": "DIVIDE([Painottamattomat enimmäismäärän mukaiset opiskelijavuodet, ei maksuton, lkm], [Painottamattomat opiskelijavuodet ilman enimmäismäärärajausta, ei maksuton, lkm])",
            "formatString": "#,0.000"
          },
          {
            "name": "Lähtötason mukaan painotetut opiskelijavuodet, lkm",
            "expression": [
              "",
              "var summa = CALCULATE(SUM(Muuttujat[painotettu_lahtotaso]))",
              "return IF(summa=0,BLANK(),summa)"
            ],
            "formatString": "#,0.00"
          },
          {
            "name": "Lähtötason mukaan painotetut opiskelijavuodet, ka",
            "expression": "0.5 * [Lähtötason mukaan painotetut opiskelijavuodet, lkm]",
            "formatString": "#,0.00"
          },
          {
            "name": "Lähtötason mukaan painotetut opiskelijavuodet ilman enimmäismäärärajausta, ei maksuton, lkm",
            "expression": "CALCULATE([Lähtötason mukaan painotetut opiskelijavuodet, lkm], FILTER(VALUES(Muuttujat[Maksuttomuus (rahoitus)]), Muuttujat[Maksuttomuus (rahoitus)]=\"Ei maksuton (rahoitus)\"))",
            "formatString": "#,0.00"
          },
          {
            "name": "Lähtötason mukaan painotetut opiskelijavuodet ilman enimmäismäärärajausta, ei maksuton, ka",
            "expression": "0.5 * [Lähtötason mukaan painotetut opiskelijavuodet, lkm]",
            "formatString": "#,0.00"
          },
          {
            "name": "Keskimääräinen painotus lähtötason mukaan, rahoituksen perusteena olevat opiskelijavuodet",
            "expression": "DIVIDE([Lähtötason mukaan painotetut rahoituksen perusteena olevat opiskelijavuodet, lkm], [Painottamattomat enimmäismäärän mukaiset opiskelijavuodet, lkm])",
            "formatString": "0.0000"
          },
          {
            "name": "Keskimääräinen painotus kustannusryhmän jne. mukaan, rahoituksen perusteena olevat opiskelijavuodet",
            "expression": [
              "",
              "--versio eri nimellä vuosiraporttia varten",
              "DIVIDE([Painotetut rahoituksen perusteena olevat opiskelijavuodet (kust.ryhmä, tutk.tyyppi, korotukset), lkm], [Painottamattomat enimmäismäärän mukaiset opiskelijavuodet, lkm])"
            ],
            "formatString": "0.0000"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "SELECT [dw].[v_amos_opiskelijavuodet_uusi].* FROM [dw].[v_amos_opiskelijavuodet_uusi] --ORDER BY Tilastovuosi,[Koulutuksen järjestäjä],painottamaton,painotettu"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "v_amos_opiskelijavuodet_testi"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dw"
          },
          {
            "name": "QueryEditorSerialization",
            "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dw].[v_amos_opiskelijavuodet_uusi].* FROM [dw].[v_amos_opiskelijavuodet_uusi] --ORDER BY Tilastovuosi,[Koulutuksen järjestäjä],painottamaton,painotettu</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
          }
        ]
      },
      {
        "name": "Sarakeleveys",
        "columns": [
          {
            "name": "Sarakeleveys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Sarakeleveys",
            "sourceProviderType": "Char"
          },
          {
            "name": "leveys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "leveys",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Sarakeleveys",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dw].[Sarakeleveys].* FROM [dw].[Sarakeleveys] ",
              "dataSource": "SqlServer dwitvipusql16 ANTERO"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dw].[Sarakeleveys].* FROM [dw].[Sarakeleveys] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Sarakeleveys"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dw"
          }
        ]
      }
    ],
    "cultures": [
      {
        "name": "fi-FI",
        "translations": {
          "model": {
            "name": "Model",
            "tables": [
              {
                "name": "Muuttujat",
                "translatedCaption": "Muuttujat",
                "columns": [
                  {
                    "name": "Perusop. keskiarvoluokka 2",
                    "translatedCaption": "Perusop. keskiarvoluokka"
                  }
                ]
              }
            ]
          }
        }
      }
    ],
    "perspectives": [
      {
        "name": "lahtotaso_fi",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Erityisopetus"
              },
              {
                "name": "Ikä"
              },
              {
                "name": "Ikäryhmä"
              },
              {
                "name": "Koodit Koulutuksen järjestäjä"
              },
              {
                "name": "Koodit Oppilaitos"
              },
              {
                "name": "Koodit Tutkinto"
              },
              {
                "name": "Koul. järjestäjän AVI"
              },
              {
                "name": "Koul. järjestäjän ELY"
              },
              {
                "name": "Koul. järjestäjän kunta"
              },
              {
                "name": "Koul. järjestäjän maakunta"
              },
              {
                "name": "Koulutuksen järjestäjä"
              },
              {
                "name": "Koulutusala, taso 1"
              },
              {
                "name": "Koulutusala, taso 2"
              },
              {
                "name": "Koulutusala, taso 3"
              },
              {
                "name": "Kustannusryhmä"
              },
              {
                "name": "Majoitus"
              },
              {
                "name": "Oppilaitoksen AVI"
              },
              {
                "name": "Oppilaitoksen ELY"
              },
              {
                "name": "Oppilaitoksen kunta"
              },
              {
                "name": "Oppilaitoksen maakunta"
              },
              {
                "name": "Oppilaitos"
              },
              {
                "name": "Oppisopimuskoulutus"
              },
              {
                "name": "Osa-aikaisuus"
              },
              {
                "name": "Rahoitusmuoto"
              },
              {
                "name": "Sukupuoli"
              },
              {
                "name": "Suorituksen tyyppi"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Tutkinto"
              },
              {
                "name": "Tutkintotyypin ryhmä"
              },
              {
                "name": "Tutkintotyyppi"
              },
              {
                "name": "Työvoimakoulutus"
              },
              {
                "name": "Vankilaopetus"
              },
              {
                "name": "Äidinkieli"
              },
              {
                "name": "Koodit Osaamisala"
              },
              {
                "name": "Toimipiste"
              },
              {
                "name": "Osaamisala"
              },
              {
                "name": "Hyväksytyt/hylätyt opiskelijavuodet"
              },
              {
                "name": "Tilastokuukausi"
              },
              {
                "name": "Luvaton korotustekijä"
              },
              {
                "name": "Luvaton koulutus"
              },
              {
                "name": "Luvaton majoitus"
              },
              {
                "name": "Hankintakoulutuksen järjestäjä"
              },
              {
                "name": "Hankintakoulutus"
              },
              {
                "name": "Koodit Hankintakoulutuksen järjestäjä"
              },
              {
                "name": "Suorituskieli"
              },
              {
                "name": "Luvanmukainen suorituskieli"
              },
              {
                "name": "Toimipisteen kunta"
              },
              {
                "name": "Toimipisteen maakunta"
              },
              {
                "name": "Koulutuksen alkamisvuosi"
              },
              {
                "name": "Koulutuksen alkamiskuukausi"
              },
              {
                "name": "Vaativa erityinen tuki"
              },
              {
                "name": "Toisen asteen pohjakoulutus (2018-)"
              },
              {
                "name": "Maksuttomuus (KOSKI)"
              },
              {
                "name": "Rahoituskausi"
              },
              {
                "name": "Vaativan erityisen tuen opiskelijavuosien enimmäismäärä"
              },
              {
                "name": "Ei maksuttomien opiskelijavuosien enimmäismäärä"
              },
              {
                "name": "Toteuma/Estimaatti"
              },
              {
                "name": "Koul. järjestäjän PILKE-alue (kokeilu)"
              },
              {
                "name": "Tutkintotyyppi (rahoitus)"
              },
              {
                "name": "Perusop. suoritusvuosi"
              },
              {
                "name": "Perusop. yksilöllistäminen"
              },
              {
                "name": "Varainhoitovuosi"
              },
              {
                "name": "Järjestäjärakenne"
              },
              {
                "name": "Suoritettu tutkinto, maksuttomuus (2018-)"
              },
              {
                "name": "Maksuttomuus (rahoitus)"
              },
              {
                "name": "Perusop. keskiarvoluokka 2"
              },
              {
                "name": "Ikä (maksuttomuusraja)"
              },
              {
                "name": "Toiminnanohjauksen kokeilu"
              },
              {
                "name": "Tilastokausi"
              }
            ],
            "measures": [
              {
                "name": "Painottamattomat enimmäismäärän mukaiset opiskelijavuodet, ka"
              },
              {
                "name": "Lähtötason mukaan painotetut rahoituksen perusteena olevat opiskelijavuodet, lkm"
              },
              {
                "name": "Lähtötason mukaan painotetut rahoituksen perusteena olevat opiskelijavuodet, ka"
              },
              {
                "name": "Lähtötason mukaan painotetut opiskelijavuodet, maksuton, lkm"
              },
              {
                "name": "Lähtötason mukaan painotetut opiskelijavuodet, maksuton, ka"
              },
              {
                "name": "Painottamattomat opiskelijavuodet, maksuton, ka"
              },
              {
                "name": "Painottamattomat opiskelijavuodet, maksuton, lkm"
              },
              {
                "name": "Painottamattomat enimmäismäärän mukaiset opiskelijavuodet, ei maksuton, ka"
              },
              {
                "name": "Painottamattomat enimmäismäärän mukaiset opiskelijavuodet, ei maksuton, lkm"
              },
              {
                "name": "Lähtötason mukaan painotetut enimmäismäärän mukaiset opiskelijavuodet, ei maksuton, lkm"
              },
              {
                "name": "Lähtötason mukaan painotetut enimmäismäärän mukaiset opiskelijavuodet, ei maksuton, ka"
              },
              {
                "name": "Keskimääräinen painotus lähtötason mukaan, opiskelijavuodet, maksuton"
              },
              {
                "name": "Keskimääräinen painotus lähtötason mukaan, enimmäismäärän mukaiset opiskelijavuodet, ei maksuton"
              },
              {
                "name": "Painottamattomat enimmäismäärän mukaiset opiskelijavuodet, lkm"
              },
              {
                "name": "Painottamattomat opiskelijavuodet ilman enimmäismäärärajausta, ei maksuton, ka"
              },
              {
                "name": "Painottamattomat opiskelijavuodet ilman enimmäismäärärajausta, ei maksuton, lkm"
              },
              {
                "name": "Painottamattomat opiskelijavuodet ilman enimmäismäärärajausta, ka"
              },
              {
                "name": "Painottamattomat opiskelijavuodet ilman enimmäismäärärajausta, lkm"
              },
              {
                "name": "Painottamattomat enimmäismäärän mukaiset opiskelijavuodet, ei maksuton / Painottamattomat opiskelijavuodet ilman enimmäismäärärajausta, ei maksuton"
              },
              {
                "name": "Lähtötason mukaan painotetut opiskelijavuodet ilman enimmäismäärärajausta, ei maksuton, lkm"
              },
              {
                "name": "Lähtötason mukaan painotetut opiskelijavuodet, lkm"
              },
              {
                "name": "Lähtötason mukaan painotetut opiskelijavuodet, ka"
              },
              {
                "name": "Lähtötason mukaan painotetut opiskelijavuodet ilman enimmäismäärärajausta, ei maksuton, ka"
              },
              {
                "name": "Keskimääräinen painotus lähtötason mukaan, rahoituksen perusteena olevat opiskelijavuodet"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "kustannusryhma_fi",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Erityisopetus"
              },
              {
                "name": "Ikä"
              },
              {
                "name": "Ikäryhmä"
              },
              {
                "name": "Koodit Koulutuksen järjestäjä"
              },
              {
                "name": "Koodit Oppilaitos"
              },
              {
                "name": "Koodit Tutkinto"
              },
              {
                "name": "Koul. järjestäjän AVI"
              },
              {
                "name": "Koul. järjestäjän ELY"
              },
              {
                "name": "Koul. järjestäjän kunta"
              },
              {
                "name": "Koul. järjestäjän maakunta"
              },
              {
                "name": "Koulutuksen järjestäjä"
              },
              {
                "name": "Koulutusala, taso 1"
              },
              {
                "name": "Koulutusala, taso 2"
              },
              {
                "name": "Koulutusala, taso 3"
              },
              {
                "name": "Kustannusryhmä"
              },
              {
                "name": "Majoitus"
              },
              {
                "name": "Oppilaitoksen AVI"
              },
              {
                "name": "Oppilaitoksen ELY"
              },
              {
                "name": "Oppilaitoksen kunta"
              },
              {
                "name": "Oppilaitoksen maakunta"
              },
              {
                "name": "Oppilaitos"
              },
              {
                "name": "Oppisopimuskoulutus"
              },
              {
                "name": "Osa-aikaisuus"
              },
              {
                "name": "Rahoitusmuoto"
              },
              {
                "name": "Sukupuoli"
              },
              {
                "name": "Suorituksen tyyppi"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Tutkinto"
              },
              {
                "name": "Tutkintotyypin ryhmä"
              },
              {
                "name": "Tutkintotyyppi"
              },
              {
                "name": "Työvoimakoulutus"
              },
              {
                "name": "Vankilaopetus"
              },
              {
                "name": "Äidinkieli"
              },
              {
                "name": "Koodit Osaamisala"
              },
              {
                "name": "Toimipiste"
              },
              {
                "name": "Osaamisala"
              },
              {
                "name": "Hyväksytyt/hylätyt opiskelijavuodet"
              },
              {
                "name": "Tilastokuukausi"
              },
              {
                "name": "Luvaton korotustekijä"
              },
              {
                "name": "Luvaton koulutus"
              },
              {
                "name": "Luvaton majoitus"
              },
              {
                "name": "Hankintakoulutuksen järjestäjä"
              },
              {
                "name": "Hankintakoulutus"
              },
              {
                "name": "Koodit Hankintakoulutuksen järjestäjä"
              },
              {
                "name": "Suorituskieli"
              },
              {
                "name": "Luvanmukainen suorituskieli"
              },
              {
                "name": "Toimipisteen kunta"
              },
              {
                "name": "Toimipisteen maakunta"
              },
              {
                "name": "Koulutuksen alkamisvuosi"
              },
              {
                "name": "Koulutuksen alkamiskuukausi"
              },
              {
                "name": "Vaativa erityinen tuki"
              },
              {
                "name": "Toisen asteen pohjakoulutus (2018-)"
              },
              {
                "name": "Maksuttomuus (KOSKI)"
              },
              {
                "name": "Rahoituskausi"
              },
              {
                "name": "Vaativan erityisen tuen opiskelijavuosien enimmäismäärä"
              },
              {
                "name": "Ei maksuttomien opiskelijavuosien enimmäismäärä"
              },
              {
                "name": "Toteuma/Estimaatti"
              },
              {
                "name": "Koul. järjestäjän PILKE-alue (kokeilu)"
              },
              {
                "name": "Tutkintotyyppi (rahoitus)"
              },
              {
                "name": "Perusop. suoritusvuosi"
              },
              {
                "name": "Perusop. yksilöllistäminen"
              },
              {
                "name": "Varainhoitovuosi"
              },
              {
                "name": "Järjestäjärakenne"
              },
              {
                "name": "Suoritettu tutkinto, maksuttomuus (2018-)"
              },
              {
                "name": "Maksuttomuus (rahoitus)"
              },
              {
                "name": "Perusop. keskiarvoluokka 2"
              },
              {
                "name": "Ikä (maksuttomuusraja)"
              },
              {
                "name": "Toiminnanohjauksen kokeilu"
              },
              {
                "name": "Tilastokausi"
              }
            ],
            "measures": [
              {
                "name": "Painottamattomat enimmäismäärän mukaiset opiskelijavuodet, ka"
              },
              {
                "name": "Kust.ryhm. ja tutk.tyyp. mukaan painotetut rahoituksen perusteena olevat opiskelijavuodet, lkm"
              },
              {
                "name": "Kust.ryhm. ja tutk.tyyp. mukaan painotetut rahoituksen perusteena olevat opiskelijavuodet, ka"
              },
              {
                "name": "Majoituksen mukaan painotetut rahoituksen perusteena olevat opiskelijavuodet, lkm"
              },
              {
                "name": "Majoituksen mukaan painotetut rahoituksen perusteena olevat opiskelijavuodet, ka"
              },
              {
                "name": "Vaativan erityisen tuen mukaan painotetut rahoituksen perusteena olevat opiskelijavuodet, lkm"
              },
              {
                "name": "Vaativan erityisen tuen mukaan painotetut rahoituksen perusteena olevat opiskelijavuodet, ka"
              },
              {
                "name": "Painotetut rahoituksen perusteena olevat opiskelijavuodet (kust.ryhmä, tutk.tyyppi, korotukset), ka"
              },
              {
                "name": "Keskimääräinen painotus, rahoituksen perusteena olevat opiskelijavuodet"
              },
              {
                "name": "Painottamattomat enimmäismäärän mukaiset opiskelijavuodet, lkm"
              },
              {
                "name": "Painotetut rahoituksen perusteena olevat opiskelijavuodet (kust.ryhmä, tutk.tyyppi, korotukset), lkm"
              },
              {
                "name": "Painottamattomat opiskelijavuodet ilman enimmäismäärärajausta, lkm"
              },
              {
                "name": "Painottamattomat opiskelijavuodet ilman enimmäismäärärajausta, ka"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "vuosiraportti_fi",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Ei maksuttomien opiskelijavuosien enimmäismäärä"
              },
              {
                "name": "Erityisopetus"
              },
              {
                "name": "Hankintakoulutuksen järjestäjä"
              },
              {
                "name": "Hankintakoulutus"
              },
              {
                "name": "Hyväksytyt/hylätyt opiskelijavuodet"
              },
              {
                "name": "Ikä"
              },
              {
                "name": "Ikä (maksuttomuusraja)"
              },
              {
                "name": "Ikäryhmä"
              },
              {
                "name": "Järjestäjärakenne"
              },
              {
                "name": "Koodit Hankintakoulutuksen järjestäjä"
              },
              {
                "name": "Koodit Koulutuksen järjestäjä"
              },
              {
                "name": "Koodit Oppilaitos"
              },
              {
                "name": "Koodit Osaamisala"
              },
              {
                "name": "Koodit Tutkinto"
              },
              {
                "name": "Koul. järjestäjän AVI"
              },
              {
                "name": "Koul. järjestäjän ELY"
              },
              {
                "name": "Koul. järjestäjän kunta"
              },
              {
                "name": "Koul. järjestäjän maakunta"
              },
              {
                "name": "Koul. järjestäjän PILKE-alue (kokeilu)"
              },
              {
                "name": "Koulutuksen alkamiskuukausi"
              },
              {
                "name": "Koulutuksen alkamisvuosi"
              },
              {
                "name": "Koulutuksen järjestäjä"
              },
              {
                "name": "Koulutusala, taso 1"
              },
              {
                "name": "Koulutusala, taso 2"
              },
              {
                "name": "Koulutusala, taso 3"
              },
              {
                "name": "Kustannusryhmä"
              },
              {
                "name": "Luvanmukainen suorituskieli"
              },
              {
                "name": "Luvaton korotustekijä"
              },
              {
                "name": "Luvaton koulutus"
              },
              {
                "name": "Luvaton majoitus"
              },
              {
                "name": "Majoitus"
              },
              {
                "name": "Maksuttomuus (KOSKI)"
              },
              {
                "name": "Maksuttomuus (rahoitus)"
              },
              {
                "name": "Oppilaitoksen AVI"
              },
              {
                "name": "Oppilaitoksen ELY"
              },
              {
                "name": "Oppilaitoksen kunta"
              },
              {
                "name": "Oppilaitoksen maakunta"
              },
              {
                "name": "Oppilaitos"
              },
              {
                "name": "Oppisopimuskoulutus"
              },
              {
                "name": "Osa-aikaisuus"
              },
              {
                "name": "Osaamisala"
              },
              {
                "name": "Perusop. keskiarvoluokka 2"
              },
              {
                "name": "Perusop. suoritusvuosi"
              },
              {
                "name": "Rahoitusmuoto"
              },
              {
                "name": "Sukupuoli"
              },
              {
                "name": "Suoritettu tutkinto, maksuttomuus (2018-)"
              },
              {
                "name": "Suorituksen tyyppi"
              },
              {
                "name": "Suorituskieli"
              },
              {
                "name": "Tilastokausi"
              },
              {
                "name": "Tilastokuukausi"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Toiminnanohjauksen kokeilu"
              },
              {
                "name": "Toimipiste"
              },
              {
                "name": "Toimipisteen kunta"
              },
              {
                "name": "Toimipisteen maakunta"
              },
              {
                "name": "Toisen asteen pohjakoulutus (2018-)"
              },
              {
                "name": "Tutkinto"
              },
              {
                "name": "Tutkintotyypin ryhmä"
              },
              {
                "name": "Tutkintotyyppi"
              },
              {
                "name": "Tutkintotyyppi (rahoitus)"
              },
              {
                "name": "Työvoimakoulutus"
              },
              {
                "name": "Vaativa erityinen tuki"
              },
              {
                "name": "Vaativan erityisen tuen opiskelijavuosien enimmäismäärä"
              },
              {
                "name": "Vankilaopetus"
              },
              {
                "name": "Äidinkieli"
              }
            ],
            "measures": [
              {
                "name": "Keskimääräinen painotus lähtötason mukaan, enimmäismäärän mukaiset opiskelijavuodet, ei maksuton"
              },
              {
                "name": "Keskimääräinen painotus lähtötason mukaan, opiskelijavuodet, maksuton"
              },
              {
                "name": "Keskimääräinen painotus lähtötason mukaan, rahoituksen perusteena olevat opiskelijavuodet"
              },
              {
                "name": "Kust.ryhm. ja tutk.tyyp. mukaan painotetut rahoituksen perusteena olevat opiskelijavuodet, lkm"
              },
              {
                "name": "Lähtötason mukaan painotetut enimmäismäärän mukaiset opiskelijavuodet, ei maksuton, lkm"
              },
              {
                "name": "Lähtötason mukaan painotetut opiskelijavuodet ilman enimmäismäärärajausta, ei maksuton, lkm"
              },
              {
                "name": "Lähtötason mukaan painotetut opiskelijavuodet, lkm"
              },
              {
                "name": "Lähtötason mukaan painotetut opiskelijavuodet, maksuton, lkm"
              },
              {
                "name": "Lähtötason mukaan painotetut rahoituksen perusteena olevat opiskelijavuodet, lkm"
              },
              {
                "name": "Majoituksen mukaan painotetut rahoituksen perusteena olevat opiskelijavuodet, lkm"
              },
              {
                "name": "Painotetut rahoituksen perusteena olevat opiskelijavuodet (kust.ryhmä, tutk.tyyppi, korotukset), lkm"
              },
              {
                "name": "Painottamattomat enimmäismäärän mukaiset opiskelijavuodet, ei maksuton / Painottamattomat opiskelijavuodet ilman enimmäismäärärajausta, ei maksuton"
              },
              {
                "name": "Painottamattomat enimmäismäärän mukaiset opiskelijavuodet, ei maksuton, lkm"
              },
              {
                "name": "Painottamattomat enimmäismäärän mukaiset opiskelijavuodet, lkm"
              },
              {
                "name": "Painottamattomat opiskelijavuodet ilman enimmäismäärärajausta, ei maksuton, lkm"
              },
              {
                "name": "Painottamattomat opiskelijavuodet ilman enimmäismäärärajausta, lkm"
              },
              {
                "name": "Painottamattomat opiskelijavuodet, maksuton, lkm"
              },
              {
                "name": "Vaativan erityisen tuen mukaan painotetut rahoituksen perusteena olevat opiskelijavuodet, lkm"
              },
              {
                "name": "Keskimääräinen painotus kustannusryhmän jne. mukaan, rahoituksen perusteena olevat opiskelijavuodet"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      }
    ],
    "roles": [
      {
        "name": "Role",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "DWI\\T_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1732"
          },
          {
            "memberName": "DWI\\P_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1733"
          },
          {
            "memberName": "DWI\\Z_P_Antero_Read_TAB",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-4156"
          },
          {
            "memberName": "DWI\\Z_T_Antero_Read_TAB",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-4155"
          },
          {
            "memberName": "DWI\\Z_DWIPVIPURD_Allow_F_Drive",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-5333"
          },
          {
            "memberName": "DWI\\Z_DWIPVIPURD_Allow_All_Drives",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-5673"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "400"
      }
    ]
  },
  "id": "SemanticModel"
}