{
  "name": "SemanticModel",
  "id": "SemanticModel",
  "compatibilityLevel": 1200,
  "model": {
    "culture": "fi-FI",
    "dataSources": [
      {
        "name": "SqlServer dwitvipusql16 ANTERO",
        "connectionString": "Provider=SQLNCLI11;Data Source=dwitvipusql16;Initial Catalog=ANTERO;Integrated Security=SSPI;Persist Security Info=false",
        "impersonationMode": "impersonateAccount",
        "account": "dwi\\T_VIPUTK_KUUTIO",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "Sarakeleveys",
        "columns": [
          {
            "name": "Sarakeleveys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Sarakeleveys",
            "sourceProviderType": "Char"
          },
          {
            "name": "leveys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "leveys",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Sarakeleveys",
            "dataView": "full",
            "source": {
              "query": " SELECT [dw].[Sarakeleveys].* FROM [dw].[Sarakeleveys] ",
              "dataSource": "SqlServer dwitvipusql16 ANTERO"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dw].[Sarakeleveys].* FROM [dw].[Sarakeleveys] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Sarakeleveys"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dw"
          }
        ]
      },
      {
        "name": "Muuttujat",
        "columns": [
          {
            "name": "Tilastovuosi",
            "dataType": "int64",
            "sourceColumn": "Tilastovuosi",
            "sourceProviderType": "Integer",
            "displayFolder": "Aikamuuttujat"
          },
          {
            "name": "Sukupuoli",
            "dataType": "string",
            "sourceColumn": "Sukupuoli",
            "sortByColumn": "Koodit Sukupuoli",
            "sourceProviderType": "WChar",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Yliopisto",
            "dataType": "string",
            "sourceColumn": "Yliopisto",
            "sourceProviderType": "Integer",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "suorittaneiden_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "suorittaneiden_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Koodit Yliopisto",
            "dataType": "string",
            "sourceColumn": "Koodit Yliopisto",
            "sourceProviderType": "Char",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koodit Sukupuoli",
            "dataType": "string",
            "sourceColumn": "Koodit Sukupuoli",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Opiskelijamaara_brutto",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Opiskelijamaara_brutto"
          },
          {
            "name": "suoritetut_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "suoritetut_lkm"
          },
          {
            "name": "tarjotut_lkm",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "tarjotut_lkm"
          },
          {
            "name": "OKM ohjauksen ala",
            "dataType": "string",
            "sourceColumn": "OKM ohjauksen ala",
            "sortByColumn": "Jarjestys_Ohjauksenala",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koodit Ohjauksenala",
            "dataType": "string",
            "sourceColumn": "Koodit Ohjauksenala",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "y_opiston_jarjestama_koul_tutk_opisk",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "y_opiston_jarjestama_koul_tutk_opisk"
          },
          {
            "name": "y_opiston_jarjestama_koul_ei_tutk_opisk",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "y_opiston_jarjestama_koul_ei_tutk_opisk"
          },
          {
            "name": "k_opiston_jarjestama_koul_tutk_opisk",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "k_opiston_jarjestama_koul_tutk_opisk"
          },
          {
            "name": "k_opiston_jarjestama_koul_ei_tutk_opisk",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "k_opiston_jarjestama_koul_ei_tutk_opisk"
          },
          {
            "name": "ky_opiston_jarjestama_koul_tutk_opisk",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ky_opiston_jarjestama_koul_tutk_opisk"
          },
          {
            "name": "ky_opiston_jarjestama_koul_ei_tutk_opisk",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ky_opiston_jarjestama_koul_ei_tutk_opisk"
          },
          {
            "name": "muu_jarjestama_koul_tutk_opisk",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "muu_jarjestama_koul_tutk_opisk"
          },
          {
            "name": "muu_jarjestama_koul_ei_tutk_opisk",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "muu_jarjestama_koul_ei_tutk_opisk"
          },
          {
            "name": "kt_opiston_jarjestama_koul_tutk_opisk",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "kt_opiston_jarjestama_koul_tutk_opisk"
          },
          {
            "name": "kt_opiston_jarjestama_koul_ei_tutk_opisk",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "kt_opiston_jarjestama_koul_ei_tutk_opisk"
          },
          {
            "name": "Koulutusala (1995)",
            "dataType": "string",
            "sourceColumn": "Koulutusala (1995)",
            "sortByColumn": "Jarjestys_koulutusalakoodi",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koodit Koulutusala 1995",
            "dataType": "string",
            "sourceColumn": "Koodit Koulutusala 1995",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Jarjestys_koulutusalakoodi",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Jarjestys_koulutusalakoodi"
          },
          {
            "name": "Jarjestys_Ohjauksenala",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Jarjestys_Ohjauksenala"
          },
          {
            "name": "Statistikår",
            "dataType": "int64",
            "sourceColumn": "Statistikår",
            "displayFolder": "Tidsvariabler"
          },
          {
            "name": "Kön",
            "dataType": "string",
            "sourceColumn": "Kön",
            "displayFolder": "Personvariabler"
          },
          {
            "name": "Universitet",
            "dataType": "string",
            "sourceColumn": "Universitet",
            "displayFolder": "Organisationsvariabler"
          },
          {
            "name": "UKM-styrningsområde",
            "dataType": "string",
            "sourceColumn": "UKM-styrningsområde",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Utbildningsområde (1995)",
            "dataType": "string",
            "sourceColumn": "Utbildningsområde (1995)",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Statistical year",
            "dataType": "int64",
            "sourceColumn": "Statistical year",
            "displayFolder": "Time variables"
          },
          {
            "name": "Gender",
            "dataType": "string",
            "sourceColumn": "Gender",
            "displayFolder": "Person variables"
          },
          {
            "name": "University",
            "dataType": "string",
            "sourceColumn": "University",
            "displayFolder": "Organisation variables"
          },
          {
            "name": "Field of education - HE steering",
            "dataType": "string",
            "sourceColumn": "Field of education - HE steering",
            "displayFolder": "Education variables"
          },
          {
            "name": "Field of education (1995)",
            "dataType": "string",
            "sourceColumn": "Field of education (1995)",
            "displayFolder": "Education variables"
          },
          {
            "name": "Kod Universitet",
            "dataType": "string",
            "sourceColumn": "Koodit Yliopisto",
            "sourceProviderType": "Char",
            "displayFolder": "Kodvariabler"
          },
          {
            "name": "Kod Kön",
            "dataType": "string",
            "sourceColumn": "Koodit Sukupuoli",
            "displayFolder": "Kodvariabler"
          },
          {
            "name": "Kod Utbildningsområde (1995)",
            "dataType": "string",
            "sourceColumn": "Koodit Koulutusala 1995",
            "displayFolder": "Kodvariabler"
          },
          {
            "name": "Kod UKM-styrningsområde",
            "dataType": "string",
            "sourceColumn": "Koodit Ohjauksenala",
            "displayFolder": "Kodvariabler"
          },
          {
            "name": "Codes University",
            "dataType": "string",
            "sourceColumn": "Koodit Yliopisto",
            "sourceProviderType": "Char",
            "displayFolder": "Code variables"
          },
          {
            "name": "Codes Gender",
            "dataType": "string",
            "sourceColumn": "Koodit Sukupuoli",
            "displayFolder": "Code variables"
          },
          {
            "name": "Codes Field of education (1995)",
            "dataType": "string",
            "sourceColumn": "Koodit Koulutusala 1995",
            "displayFolder": "Code variables"
          },
          {
            "name": "Codes Field of education - HE steering",
            "dataType": "string",
            "sourceColumn": "Koodit Ohjauksenala",
            "displayFolder": "Code variables"
          }
        ],
        "partitions": [
          {
            "name": "v_st_avoin_yliopisto",
            "dataView": "full",
            "source": {
              "query": " SELECT [dw].[v_st_avoin_yliopisto].* FROM [dw].[v_st_avoin_yliopisto] ",
              "dataSource": "SqlServer dwitvipusql16 ANTERO"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>\n<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\n  <ColumnSuggestedType />\n  <ColumnFormat />\n  <ColumnAccuracy />\n  <ColumnCurrencySymbol />\n  <ColumnPositivePattern />\n  <ColumnNegativePattern />\n  <ColumnWidths>\n    <item>\n      <key>\n        <string>Tilastovuosi</string>\n      </key>\n      <value>\n        <int>86</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Sukupuoli</string>\n      </key>\n      <value>\n        <int>75</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Yliopisto</string>\n      </key>\n      <value>\n        <int>69</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>suorittaneiden_lkm</string>\n      </key>\n      <value>\n        <int>120</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Koodit Yliopisto</string>\n      </key>\n      <value>\n        <int>102</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Koodit Sukupuoli</string>\n      </key>\n      <value>\n        <int>108</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>OKM ohjauksen ala</string>\n      </key>\n      <value>\n        <int>174</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Koodit Koulutusala 1995</string>\n      </key>\n      <value>\n        <int>211</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Opiskelijamaara_brutto</string>\n      </key>\n      <value>\n        <int>204</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>suoritetut_lkm</string>\n      </key>\n      <value>\n        <int>141</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>tarjotut_lkm</string>\n      </key>\n      <value>\n        <int>126</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Koodit Ohjauksenala</string>\n      </key>\n      <value>\n        <int>184</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Koulutusala (1995)</string>\n      </key>\n      <value>\n        <int>173</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Jarjestys_koulutusalakoodi</string>\n      </key>\n      <value>\n        <int>228</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Jarjestys_Ohjauksenala</string>\n      </key>\n      <value>\n        <int>204</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>y_opiston_jarjestama_koul_tutk_opisk</string>\n      </key>\n      <value>\n        <int>312</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>y_opiston_jarjestama_koul_ei_tutk_opisk</string>\n      </key>\n      <value>\n        <int>333</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>k_opiston_jarjestama_koul_tutk_opisk</string>\n      </key>\n      <value>\n        <int>312</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>k_opiston_jarjestama_koul_ei_tutk_opisk</string>\n      </key>\n      <value>\n        <int>333</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>ky_opiston_jarjestama_koul_tutk_opisk</string>\n      </key>\n      <value>\n        <int>320</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>ky_opiston_jarjestama_koul_ei_tutk_opisk</string>\n      </key>\n      <value>\n        <int>341</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>muu_jarjestama_koul_tutk_opisk</string>\n      </key>\n      <value>\n        <int>275</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>muu_jarjestama_koul_ei_tutk_opisk</string>\n      </key>\n      <value>\n        <int>296</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>kt_opiston_jarjestama_koul_tutk_opisk</string>\n      </key>\n      <value>\n        <int>317</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>kt_opiston_jarjestama_koul_ei_tutk_opisk</string>\n      </key>\n      <value>\n        <int>338</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Statistikår</string>\n      </key>\n      <value>\n        <int>108</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Kön</string>\n      </key>\n      <value>\n        <int>66</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Universitet</string>\n      </key>\n      <value>\n        <int>114</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>UKM-styrningsområde</string>\n      </key>\n      <value>\n        <int>195</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Utbildningsområde (1995)</string>\n      </key>\n      <value>\n        <int>226</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Statistical year</string>\n      </key>\n      <value>\n        <int>140</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Gender</string>\n      </key>\n      <value>\n        <int>90</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>University</string>\n      </key>\n      <value>\n        <int>109</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Field of education - HE steering</string>\n      </key>\n      <value>\n        <int>261</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Field of education (1995)</string>\n      </key>\n      <value>\n        <int>217</int>\n      </value>\n    </item>\n  </ColumnWidths>\n  <ColumnDisplayIndex>\n    <item>\n      <key>\n        <string>Tilastovuosi</string>\n      </key>\n      <value>\n        <int>0</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Sukupuoli</string>\n      </key>\n      <value>\n        <int>1</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Yliopisto</string>\n      </key>\n      <value>\n        <int>2</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>suorittaneiden_lkm</string>\n      </key>\n      <value>\n        <int>3</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Koodit Yliopisto</string>\n      </key>\n      <value>\n        <int>4</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Koodit Sukupuoli</string>\n      </key>\n      <value>\n        <int>5</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>OKM ohjauksen ala</string>\n      </key>\n      <value>\n        <int>6</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Koodit Koulutusala 1995</string>\n      </key>\n      <value>\n        <int>24</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Opiskelijamaara_brutto</string>\n      </key>\n      <value>\n        <int>7</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>suoritetut_lkm</string>\n      </key>\n      <value>\n        <int>8</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>tarjotut_lkm</string>\n      </key>\n      <value>\n        <int>9</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Koodit Ohjauksenala</string>\n      </key>\n      <value>\n        <int>10</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Koulutusala (1995)</string>\n      </key>\n      <value>\n        <int>23</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Jarjestys_koulutusalakoodi</string>\n      </key>\n      <value>\n        <int>11</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Jarjestys_Ohjauksenala</string>\n      </key>\n      <value>\n        <int>12</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>y_opiston_jarjestama_koul_tutk_opisk</string>\n      </key>\n      <value>\n        <int>13</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>y_opiston_jarjestama_koul_ei_tutk_opisk</string>\n      </key>\n      <value>\n        <int>14</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>k_opiston_jarjestama_koul_tutk_opisk</string>\n      </key>\n      <value>\n        <int>15</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>k_opiston_jarjestama_koul_ei_tutk_opisk</string>\n      </key>\n      <value>\n        <int>16</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>ky_opiston_jarjestama_koul_tutk_opisk</string>\n      </key>\n      <value>\n        <int>17</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>ky_opiston_jarjestama_koul_ei_tutk_opisk</string>\n      </key>\n      <value>\n        <int>18</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>muu_jarjestama_koul_tutk_opisk</string>\n      </key>\n      <value>\n        <int>19</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>muu_jarjestama_koul_ei_tutk_opisk</string>\n      </key>\n      <value>\n        <int>20</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>kt_opiston_jarjestama_koul_tutk_opisk</string>\n      </key>\n      <value>\n        <int>21</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>kt_opiston_jarjestama_koul_ei_tutk_opisk</string>\n      </key>\n      <value>\n        <int>22</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Statistikår</string>\n      </key>\n      <value>\n        <int>25</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Kön</string>\n      </key>\n      <value>\n        <int>26</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Universitet</string>\n      </key>\n      <value>\n        <int>27</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>UKM-styrningsområde</string>\n      </key>\n      <value>\n        <int>28</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Utbildningsområde (1995)</string>\n      </key>\n      <value>\n        <int>29</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Statistical year</string>\n      </key>\n      <value>\n        <int>30</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Gender</string>\n      </key>\n      <value>\n        <int>31</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>University</string>\n      </key>\n      <value>\n        <int>32</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Field of education - HE steering</string>\n      </key>\n      <value>\n        <int>33</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Field of education (1995)</string>\n      </key>\n      <value>\n        <int>34</int>\n      </value>\n    </item>\n  </ColumnDisplayIndex>\n  <ColumnFrozen />\n  <ColumnChecked>\n    <item>\n      <key>\n        <string>Koodit Sukupuoli</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>OKM ohjauksen ala</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Koodit Koulutusala 1995</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Opiskelijamaara_brutto</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>suoritetut_lkm</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>tarjotut_lkm</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Koodit Ohjauksenala</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Koulutusala (1995)</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Jarjestys_koulutusalakoodi</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Jarjestys_Ohjauksenala</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>y_opiston_jarjestama_koul_tutk_opisk</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>y_opiston_jarjestama_koul_ei_tutk_opisk</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>k_opiston_jarjestama_koul_tutk_opisk</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>k_opiston_jarjestama_koul_ei_tutk_opisk</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>ky_opiston_jarjestama_koul_tutk_opisk</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>ky_opiston_jarjestama_koul_ei_tutk_opisk</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>muu_jarjestama_koul_tutk_opisk</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>muu_jarjestama_koul_ei_tutk_opisk</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>kt_opiston_jarjestama_koul_tutk_opisk</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>kt_opiston_jarjestama_koul_ei_tutk_opisk</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Statistikår</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Kön</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Universitet</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>UKM-styrningsområde</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Utbildningsområde (1995)</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Statistical year</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Gender</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>University</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Field of education - HE steering</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Field of education (1995)</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n  </ColumnChecked>\n  <ColumnFilter />\n  <SelectionFilter />\n  <FilterParameters />\n  <IsSortDescending>false</IsSortDescending>\n</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Avoimen yliopisto-opetuksen opiskelijat (netto-opiskelijamäärä)",
            "expression": "IF(sum(Muuttujat[suorittaneiden_lkm])=0,BLANK(),sum(Muuttujat[suorittaneiden_lkm]))",
            "formatString": "#,0"
          },
          {
            "name": "Avoimeen yliopisto-opetukseen osallistuneet (brutto-opiskelijamäärä)",
            "expression": " IF(sum(Muuttujat[Opiskelijamaara_brutto])=0, BLANK(),sum(Muuttujat[Opiskelijamaara_brutto]))\n",
            "formatString": "#,0"
          },
          {
            "name": "Avoimessa yliopistossa tarjottujen opintopisteiden määrä",
            "expression": " IF(sum(Muuttujat[tarjotut_lkm])=0,BLANK(), sum(Muuttujat[tarjotut_lkm]))\n",
            "formatString": "#,0"
          },
          {
            "name": "Avoimessa yliopistossa suoritetut opintopisteet",
            "expression": " IF(sum(Muuttujat[suoritetut_lkm])=0,BLANK(),sum(Muuttujat[suoritetut_lkm]))\n",
            "formatString": "#,0"
          },
          {
            "name": "Yliopiston itse järjestämä koulutus - YO:n tutkinto-opiskelijat",
            "expression": "IF(sum(Muuttujat[y_opiston_jarjestama_koul_tutk_opisk])=0,BLANK(),sum(Muuttujat[y_opiston_jarjestama_koul_tutk_opisk]))\n",
            "formatString": "#,0"
          },
          {
            "name": "Yliopiston itse järjestämä koulutus - muut kuin YO:n tutkinto-opiskelijat",
            "expression": "IF(sum(Muuttujat[y_opiston_jarjestama_koul_ei_tutk_opisk])=0,BLANK(),sum(Muuttujat[y_opiston_jarjestama_koul_ei_tutk_opisk]))",
            "formatString": "#,0"
          },
          {
            "name": "Kansalais- ja työväenopistojen järjestämä koulutus - YO:n tutkinto-opiskelijat",
            "expression": "IF(sum([kt_opiston_jarjestama_koul_tutk_opisk])=0, BLANK(),sum([kt_opiston_jarjestama_koul_tutk_opisk]))",
            "formatString": "#,0"
          },
          {
            "name": "Kansalais- ja työväenopistojen järjestämä koulutus - muut kuin YO:n tutkinto-opiskelijat",
            "expression": "IF(sum([kt_opiston_jarjestama_koul_ei_tutk_opisk])=0,BLANK(),sum([kt_opiston_jarjestama_koul_ei_tutk_opisk]))",
            "formatString": "#,0"
          },
          {
            "name": "Kansanopistojen järjestämä koulutus - muut kuin YO:n tutkinto-opiskelijat",
            "expression": "IF(sum([k_opiston_jarjestama_koul_ei_tutk_opisk])=0,BLANK(), sum([k_opiston_jarjestama_koul_ei_tutk_opisk]))",
            "formatString": "#,0"
          },
          {
            "name": "Kansanopistojen järjestämä koulutus - YO:n tutkinto-opiskelijat",
            "expression": "IF(sum([k_opiston_jarjestama_koul_tutk_opisk]) = 0, BLANK(), sum([k_opiston_jarjestama_koul_tutk_opisk]))",
            "formatString": "#,0"
          },
          {
            "name": "Kesäyliopistot - muut kuin YO:n tutkinto-opiskelijat",
            "expression": "IF(sum([ky_opiston_jarjestama_koul_ei_tutk_opisk]) = 0, BLANK(), sum([ky_opiston_jarjestama_koul_ei_tutk_opisk]))",
            "formatString": "#,0"
          },
          {
            "name": "Kesäyliopistot - YO:n tutkinto-opiskelijat",
            "expression": "IF(sum([ky_opiston_jarjestama_koul_tutk_opisk]) = 0, BLANK(), sum([ky_opiston_jarjestama_koul_tutk_opisk]))",
            "formatString": "#,0"
          },
          {
            "name": "Muut järjestäjät - muut kuin YO:n tutkinto-opiskelijat",
            "expression": "IF(sum([muu_jarjestama_koul_ei_tutk_opisk]) = 0,BLANK(), sum([muu_jarjestama_koul_ei_tutk_opisk]))",
            "formatString": "#,0"
          },
          {
            "name": "Muut järjestäjät - YO:n tutkinto-opiskelijat",
            "expression": "IF(sum([muu_jarjestama_koul_tutk_opisk])=0, BLANK(), sum([muu_jarjestama_koul_tutk_opisk]))",
            "formatString": "#,0"
          },
          {
            "name": "Antal studiepoäng som erbjudits vid öppna universitet",
            "expression": " [Avoimessa yliopistossa tarjottujen opintopisteiden määrä]",
            "formatString": "#,0"
          },
          {
            "name": "Studiepoäng som avlagts vid öppet universitet",
            "expression": " [Avoimessa yliopistossa suoritetut opintopisteet]",
            "formatString": "#,0"
          },
          {
            "name": "Deltagare i den öppna universitetsundervisningen (bruttoantal studerande)",
            "expression": " [Avoimeen yliopisto-opetukseen osallistuneet (brutto-opiskelijamäärä)]",
            "formatString": "#,0"
          },
          {
            "name": "Studerande i den öppna universitetsundervisningen (nettoantal studerande)",
            "expression": " [Avoimen yliopisto-opetuksen opiskelijat (netto-opiskelijamäärä)]",
            "formatString": "#,0"
          },
          {
            "name": "Andra organisatörer – andra än univ. examensstuderande",
            "expression": " [Muut järjestäjät - muut kuin YO:n tutkinto-opiskelijat]",
            "formatString": "#,0"
          },
          {
            "name": "Andra organisatörer – univ. examensstuderande",
            "expression": " [Muut järjestäjät - YO:n tutkinto-opiskelijat]",
            "formatString": "#,0"
          },
          {
            "name": "Sommaruniversitet – andra än univ. examensstuderande",
            "expression": " [Kesäyliopistot - muut kuin YO:n tutkinto-opiskelijat]",
            "formatString": "#,0"
          },
          {
            "name": "Sommaruniversitet – univ. examensstuderande",
            "expression": " [Kesäyliopistot - YO:n tutkinto-opiskelijat]",
            "formatString": "#,0"
          },
          {
            "name": "Utbildning som ordnas av folkhögskolor – andra än univ. examensstuderande",
            "expression": " [Kansanopistojen järjestämä koulutus - muut kuin YO:n tutkinto-opiskelijat]",
            "formatString": "#,0"
          },
          {
            "name": "Utbildning som ordnas av folkhögskolor – univ. examensstuderande",
            "expression": " [Kansanopistojen järjestämä koulutus - YO:n tutkinto-opiskelijat]",
            "formatString": "#,0"
          },
          {
            "name": "Utbildning som ordnas av medborgar- och arbetarinstitut – univ. examensstuderande",
            "expression": " [Kansalais- ja työväenopistojen järjestämä koulutus - YO:n tutkinto-opiskelijat]",
            "formatString": "#,0"
          },
          {
            "name": "Utbildning som ordnas av medborgar- och arbetarinstitut – andra än univ. examensstuderande",
            "expression": " [Kansalais- ja työväenopistojen järjestämä koulutus - muut kuin YO:n tutkinto-opiskelijat]",
            "formatString": "#,0"
          },
          {
            "name": "Utbildning som universiteten ordnar – andra än univ. examensstuderande",
            "expression": " [Yliopiston itse järjestämä koulutus - muut kuin YO:n tutkinto-opiskelijat]",
            "formatString": "#,0"
          },
          {
            "name": "Utbildning som universiteten ordnar – univ. examensstuderande",
            "expression": " [Yliopiston itse järjestämä koulutus - YO:n tutkinto-opiskelijat]",
            "formatString": "#,0"
          },
          {
            "name": "Credits attained in open university education",
            "expression": " [Avoimessa yliopistossa suoritetut opintopisteet]",
            "formatString": "#,0"
          },
          {
            "name": "Number of credits offered in open university",
            "expression": " [Avoimessa yliopistossa tarjottujen opintopisteiden määrä]",
            "formatString": "#,0"
          },
          {
            "name": "Gross number of students in open university education",
            "expression": " [Avoimeen yliopisto-opetukseen osallistuneet (brutto-opiskelijamäärä)]",
            "formatString": "#,0"
          },
          {
            "name": "Net number of students in open university education",
            "expression": " [Avoimen yliopisto-opetuksen opiskelijat (netto-opiskelijamäärä)]",
            "formatString": "#,0"
          },
          {
            "name": "Summer universities - university degree students",
            "expression": " [Kesäyliopistot - YO:n tutkinto-opiskelijat]",
            "formatString": "#,0"
          },
          {
            "name": "Summer universities - other than university degree students",
            "expression": " [Kesäyliopistot - muut kuin YO:n tutkinto-opiskelijat]",
            "formatString": "#,0"
          },
          {
            "name": "Other providers - university degree students",
            "expression": " [Muut järjestäjät - YO:n tutkinto-opiskelijat]",
            "formatString": "#,0"
          },
          {
            "name": "Other providers - other than university degree students",
            "expression": " [Muut järjestäjät - muut kuin YO:n tutkinto-opiskelijat]",
            "formatString": "#,0"
          },
          {
            "name": "Education provided by universities - university degree students",
            "expression": " [Yliopiston itse järjestämä koulutus - YO:n tutkinto-opiskelijat]",
            "formatString": "#,0"
          },
          {
            "name": "Education provided by universities - other than university degree students",
            "expression": " [Yliopiston itse järjestämä koulutus - muut kuin YO:n tutkinto-opiskelijat]",
            "formatString": "#,0"
          },
          {
            "name": "Education provided by folk high schools - university degree students",
            "expression": " [Kansanopistojen järjestämä koulutus - YO:n tutkinto-opiskelijat]",
            "formatString": "#,0"
          },
          {
            "name": "Education provided by folk high schools - other than university degree students",
            "expression": " [Kansanopistojen järjestämä koulutus - muut kuin YO:n tutkinto-opiskelijat]",
            "formatString": "#,0"
          },
          {
            "name": "Education provided by adult education centres - university degree students",
            "expression": " [Kansalais- ja työväenopistojen järjestämä koulutus - YO:n tutkinto-opiskelijat]",
            "formatString": "#,0"
          },
          {
            "name": "Education provided by adult education centres - other than university degree students",
            "expression": " [Kansalais- ja työväenopistojen järjestämä koulutus - muut kuin YO:n tutkinto-opiskelijat]",
            "formatString": "#,0"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dw].[v_st_avoin_yliopisto].* FROM [dw].[v_st_avoin_yliopisto] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "v_st_avoin_yliopisto"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dw"
          },
          {
            "name": "TableWidgetSerialization",
            "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>\n<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\n  <ColumnSuggestedType />\n  <ColumnFormat />\n  <ColumnAccuracy />\n  <ColumnCurrencySymbol />\n  <ColumnPositivePattern />\n  <ColumnNegativePattern />\n  <ColumnWidths>\n    <item>\n      <key>\n        <string>Tilastovuosi</string>\n      </key>\n      <value>\n        <int>86</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Sukupuoli</string>\n      </key>\n      <value>\n        <int>75</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Yliopisto</string>\n      </key>\n      <value>\n        <int>69</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>suorittaneiden_lkm</string>\n      </key>\n      <value>\n        <int>120</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Koodit Yliopisto</string>\n      </key>\n      <value>\n        <int>102</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Koodit Sukupuoli</string>\n      </key>\n      <value>\n        <int>108</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>OKM ohjauksen ala</string>\n      </key>\n      <value>\n        <int>174</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Koodit Koulutusala 1995</string>\n      </key>\n      <value>\n        <int>211</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Opiskelijamaara_brutto</string>\n      </key>\n      <value>\n        <int>204</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>suoritetut_lkm</string>\n      </key>\n      <value>\n        <int>141</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>tarjotut_lkm</string>\n      </key>\n      <value>\n        <int>126</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Koodit Ohjauksenala</string>\n      </key>\n      <value>\n        <int>184</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Koulutusala (1995)</string>\n      </key>\n      <value>\n        <int>173</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Jarjestys_koulutusalakoodi</string>\n      </key>\n      <value>\n        <int>228</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Jarjestys_Ohjauksenala</string>\n      </key>\n      <value>\n        <int>204</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>y_opiston_jarjestama_koul_tutk_opisk</string>\n      </key>\n      <value>\n        <int>312</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>y_opiston_jarjestama_koul_ei_tutk_opisk</string>\n      </key>\n      <value>\n        <int>333</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>k_opiston_jarjestama_koul_tutk_opisk</string>\n      </key>\n      <value>\n        <int>312</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>k_opiston_jarjestama_koul_ei_tutk_opisk</string>\n      </key>\n      <value>\n        <int>333</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>ky_opiston_jarjestama_koul_tutk_opisk</string>\n      </key>\n      <value>\n        <int>320</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>ky_opiston_jarjestama_koul_ei_tutk_opisk</string>\n      </key>\n      <value>\n        <int>341</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>muu_jarjestama_koul_tutk_opisk</string>\n      </key>\n      <value>\n        <int>275</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>muu_jarjestama_koul_ei_tutk_opisk</string>\n      </key>\n      <value>\n        <int>296</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>kt_opiston_jarjestama_koul_tutk_opisk</string>\n      </key>\n      <value>\n        <int>317</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>kt_opiston_jarjestama_koul_ei_tutk_opisk</string>\n      </key>\n      <value>\n        <int>338</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Statistikår</string>\n      </key>\n      <value>\n        <int>108</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Kön</string>\n      </key>\n      <value>\n        <int>66</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Universitet</string>\n      </key>\n      <value>\n        <int>114</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>UKM-styrningsområde</string>\n      </key>\n      <value>\n        <int>195</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Utbildningsområde (1995)</string>\n      </key>\n      <value>\n        <int>226</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Statistical year</string>\n      </key>\n      <value>\n        <int>140</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Gender</string>\n      </key>\n      <value>\n        <int>90</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>University</string>\n      </key>\n      <value>\n        <int>109</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Field of education - HE steering</string>\n      </key>\n      <value>\n        <int>261</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Field of education (1995)</string>\n      </key>\n      <value>\n        <int>217</int>\n      </value>\n    </item>\n  </ColumnWidths>\n  <ColumnDisplayIndex>\n    <item>\n      <key>\n        <string>Tilastovuosi</string>\n      </key>\n      <value>\n        <int>0</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Sukupuoli</string>\n      </key>\n      <value>\n        <int>1</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Yliopisto</string>\n      </key>\n      <value>\n        <int>2</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>suorittaneiden_lkm</string>\n      </key>\n      <value>\n        <int>3</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Koodit Yliopisto</string>\n      </key>\n      <value>\n        <int>4</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Koodit Sukupuoli</string>\n      </key>\n      <value>\n        <int>5</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>OKM ohjauksen ala</string>\n      </key>\n      <value>\n        <int>6</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Koodit Koulutusala 1995</string>\n      </key>\n      <value>\n        <int>24</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Opiskelijamaara_brutto</string>\n      </key>\n      <value>\n        <int>7</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>suoritetut_lkm</string>\n      </key>\n      <value>\n        <int>8</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>tarjotut_lkm</string>\n      </key>\n      <value>\n        <int>9</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Koodit Ohjauksenala</string>\n      </key>\n      <value>\n        <int>10</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Koulutusala (1995)</string>\n      </key>\n      <value>\n        <int>23</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Jarjestys_koulutusalakoodi</string>\n      </key>\n      <value>\n        <int>11</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Jarjestys_Ohjauksenala</string>\n      </key>\n      <value>\n        <int>12</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>y_opiston_jarjestama_koul_tutk_opisk</string>\n      </key>\n      <value>\n        <int>13</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>y_opiston_jarjestama_koul_ei_tutk_opisk</string>\n      </key>\n      <value>\n        <int>14</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>k_opiston_jarjestama_koul_tutk_opisk</string>\n      </key>\n      <value>\n        <int>15</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>k_opiston_jarjestama_koul_ei_tutk_opisk</string>\n      </key>\n      <value>\n        <int>16</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>ky_opiston_jarjestama_koul_tutk_opisk</string>\n      </key>\n      <value>\n        <int>17</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>ky_opiston_jarjestama_koul_ei_tutk_opisk</string>\n      </key>\n      <value>\n        <int>18</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>muu_jarjestama_koul_tutk_opisk</string>\n      </key>\n      <value>\n        <int>19</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>muu_jarjestama_koul_ei_tutk_opisk</string>\n      </key>\n      <value>\n        <int>20</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>kt_opiston_jarjestama_koul_tutk_opisk</string>\n      </key>\n      <value>\n        <int>21</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>kt_opiston_jarjestama_koul_ei_tutk_opisk</string>\n      </key>\n      <value>\n        <int>22</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Statistikår</string>\n      </key>\n      <value>\n        <int>25</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Kön</string>\n      </key>\n      <value>\n        <int>26</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Universitet</string>\n      </key>\n      <value>\n        <int>27</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>UKM-styrningsområde</string>\n      </key>\n      <value>\n        <int>28</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Utbildningsområde (1995)</string>\n      </key>\n      <value>\n        <int>29</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Statistical year</string>\n      </key>\n      <value>\n        <int>30</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Gender</string>\n      </key>\n      <value>\n        <int>31</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>University</string>\n      </key>\n      <value>\n        <int>32</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Field of education - HE steering</string>\n      </key>\n      <value>\n        <int>33</int>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Field of education (1995)</string>\n      </key>\n      <value>\n        <int>34</int>\n      </value>\n    </item>\n  </ColumnDisplayIndex>\n  <ColumnFrozen />\n  <ColumnChecked>\n    <item>\n      <key>\n        <string>Koodit Sukupuoli</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>OKM ohjauksen ala</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Koodit Koulutusala 1995</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Opiskelijamaara_brutto</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>suoritetut_lkm</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>tarjotut_lkm</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Koodit Ohjauksenala</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Koulutusala (1995)</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Jarjestys_koulutusalakoodi</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Jarjestys_Ohjauksenala</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>y_opiston_jarjestama_koul_tutk_opisk</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>y_opiston_jarjestama_koul_ei_tutk_opisk</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>k_opiston_jarjestama_koul_tutk_opisk</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>k_opiston_jarjestama_koul_ei_tutk_opisk</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>ky_opiston_jarjestama_koul_tutk_opisk</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>ky_opiston_jarjestama_koul_ei_tutk_opisk</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>muu_jarjestama_koul_tutk_opisk</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>muu_jarjestama_koul_ei_tutk_opisk</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>kt_opiston_jarjestama_koul_tutk_opisk</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>kt_opiston_jarjestama_koul_ei_tutk_opisk</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Statistikår</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Kön</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Universitet</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>UKM-styrningsområde</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Utbildningsområde (1995)</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Statistical year</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Gender</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>University</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Field of education - HE steering</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n    <item>\n      <key>\n        <string>Field of education (1995)</string>\n      </key>\n      <value>\n        <boolean>true</boolean>\n      </value>\n    </item>\n  </ColumnChecked>\n  <ColumnFilter />\n  <SelectionFilter />\n  <FilterParameters />\n  <IsSortDescending>false</IsSortDescending>\n</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
          }
        ]
      }
    ],
    "cultures": [
      {
        "name": "en-US",
        "translations": {
          "model": {
            "name": "Model",
            "tables": [
              {
                "name": "Muuttujat",
                "translatedCaption": "Variables"
              }
            ]
          }
        }
      },
      {
        "name": "sv-SE",
        "translations": {
          "model": {
            "name": "Model",
            "tables": [
              {
                "name": "Muuttujat",
                "translatedCaption": "Variabler"
              }
            ]
          }
        }
      }
    ],
    "perspectives": [
      {
        "name": "netto_opiskelijat",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Koodit Yliopisto"
              },
              {
                "name": "Sukupuoli"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Yliopisto"
              }
            ],
            "measures": [
              {
                "name": "Avoimen yliopisto-opetuksen opiskelijat (netto-opiskelijamäärä)"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Avoin yo1",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Koodit Yliopisto"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Yliopisto"
              },
              {
                "name": "Koodit Ohjauksenala"
              },
              {
                "name": "OKM ohjauksen ala"
              },
              {
                "name": "Koodit Koulutusala 1995"
              },
              {
                "name": "Koulutusala (1995)"
              }
            ],
            "measures": [
              {
                "name": "Avoimeen yliopisto-opetukseen osallistuneet (brutto-opiskelijamäärä)"
              },
              {
                "name": "Avoimen yliopisto-opetuksen opiskelijat (netto-opiskelijamäärä)"
              },
              {
                "name": "Avoimessa yliopistossa suoritetut opintopisteet"
              },
              {
                "name": "Avoimessa yliopistossa tarjottujen opintopisteiden määrä"
              }
            ]
          }
        ]
      },
      {
        "name": "Avoin yo2",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Koodit Ohjauksenala"
              },
              {
                "name": "Koodit Yliopisto"
              },
              {
                "name": "OKM ohjauksen ala"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Yliopisto"
              },
              {
                "name": "Koodit Koulutusala 1995"
              },
              {
                "name": "Koulutusala (1995)"
              }
            ],
            "measures": [
              {
                "name": "Kansalais- ja työväenopistojen järjestämä koulutus - muut kuin YO:n tutkinto-opiskelijat"
              },
              {
                "name": "Kansalais- ja työväenopistojen järjestämä koulutus - YO:n tutkinto-opiskelijat"
              },
              {
                "name": "Kansanopistojen järjestämä koulutus - muut kuin YO:n tutkinto-opiskelijat"
              },
              {
                "name": "Kansanopistojen järjestämä koulutus - YO:n tutkinto-opiskelijat"
              },
              {
                "name": "Kesäyliopistot - muut kuin YO:n tutkinto-opiskelijat"
              },
              {
                "name": "Kesäyliopistot - YO:n tutkinto-opiskelijat"
              },
              {
                "name": "Muut järjestäjät - muut kuin YO:n tutkinto-opiskelijat"
              },
              {
                "name": "Muut järjestäjät - YO:n tutkinto-opiskelijat"
              },
              {
                "name": "Yliopiston itse järjestämä koulutus - muut kuin YO:n tutkinto-opiskelijat"
              },
              {
                "name": "Yliopiston itse järjestämä koulutus - YO:n tutkinto-opiskelijat"
              }
            ]
          }
        ]
      },
      {
        "name": "Avoin yo1_sv",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Statistikår"
              },
              {
                "name": "UKM-styrningsområde"
              },
              {
                "name": "Universitet"
              },
              {
                "name": "Utbildningsområde (1995)"
              },
              {
                "name": "Kod UKM-styrningsområde"
              },
              {
                "name": "Kod Universitet"
              },
              {
                "name": "Kod Utbildningsområde (1995)"
              }
            ],
            "measures": [
              {
                "name": "Antal studiepoäng som erbjudits vid öppna universitet"
              },
              {
                "name": "Deltagare i den öppna universitetsundervisningen (bruttoantal studerande)"
              },
              {
                "name": "Studiepoäng som avlagts vid öppet universitet"
              },
              {
                "name": "Studerande i den öppna universitetsundervisningen (nettoantal studerande)"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Avoin yo2_sv",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Statistikår"
              },
              {
                "name": "UKM-styrningsområde"
              },
              {
                "name": "Universitet"
              },
              {
                "name": "Utbildningsområde (1995)"
              },
              {
                "name": "Kod UKM-styrningsområde"
              },
              {
                "name": "Kod Universitet"
              },
              {
                "name": "Kod Utbildningsområde (1995)"
              }
            ],
            "measures": [
              {
                "name": "Andra organisatörer – andra än univ. examensstuderande"
              },
              {
                "name": "Andra organisatörer – univ. examensstuderande"
              },
              {
                "name": "Sommaruniversitet – andra än univ. examensstuderande"
              },
              {
                "name": "Sommaruniversitet – univ. examensstuderande"
              },
              {
                "name": "Utbildning som ordnas av folkhögskolor – andra än univ. examensstuderande"
              },
              {
                "name": "Utbildning som ordnas av folkhögskolor – univ. examensstuderande"
              },
              {
                "name": "Utbildning som ordnas av medborgar- och arbetarinstitut – andra än univ. examensstuderande"
              },
              {
                "name": "Utbildning som ordnas av medborgar- och arbetarinstitut – univ. examensstuderande"
              },
              {
                "name": "Utbildning som universiteten ordnar – andra än univ. examensstuderande"
              },
              {
                "name": "Utbildning som universiteten ordnar – univ. examensstuderande"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Avoin yo1_en",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Field of education - HE steering"
              },
              {
                "name": "Field of education (1995)"
              },
              {
                "name": "Statistical year"
              },
              {
                "name": "University"
              },
              {
                "name": "Codes Field of education - HE steering"
              },
              {
                "name": "Codes Field of education (1995)"
              },
              {
                "name": "Codes University"
              }
            ],
            "measures": [
              {
                "name": "Credits attained in open university education"
              },
              {
                "name": "Gross number of students in open university education"
              },
              {
                "name": "Net number of students in open university education"
              },
              {
                "name": "Number of credits offered in open university"
              }
            ]
          }
        ]
      },
      {
        "name": "Avoin yo2_en",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Field of education - HE steering"
              },
              {
                "name": "Field of education (1995)"
              },
              {
                "name": "Statistical year"
              },
              {
                "name": "University"
              },
              {
                "name": "Codes Field of education - HE steering"
              },
              {
                "name": "Codes Field of education (1995)"
              },
              {
                "name": "Codes University"
              }
            ],
            "measures": [
              {
                "name": "Education provided by adult education centres - other than university degree students"
              },
              {
                "name": "Education provided by adult education centres - university degree students"
              },
              {
                "name": "Education provided by folk high schools - other than university degree students"
              },
              {
                "name": "Education provided by folk high schools - university degree students"
              },
              {
                "name": "Education provided by universities - other than university degree students"
              },
              {
                "name": "Education provided by universities - university degree students"
              },
              {
                "name": "Other providers - other than university degree students"
              },
              {
                "name": "Other providers - university degree students"
              },
              {
                "name": "Summer universities - other than university degree students"
              },
              {
                "name": "Summer universities - university degree students"
              }
            ]
          }
        ]
      },
      {
        "name": "netto_opiskelijat_sv",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Kod Universitet"
              },
              {
                "name": "Kön"
              },
              {
                "name": "Statistikår"
              },
              {
                "name": "Universitet"
              }
            ],
            "measures": [
              {
                "name": "Studerande i den öppna universitetsundervisningen (nettoantal studerande)"
              }
            ]
          }
        ]
      },
      {
        "name": "netto_opiskelijat_en",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Codes University"
              },
              {
                "name": "Gender"
              },
              {
                "name": "Statistical year"
              },
              {
                "name": "University"
              }
            ],
            "measures": [
              {
                "name": "Net number of students in open university education"
              }
            ]
          }
        ]
      }
    ],
    "roles": [
      {
        "name": "Luku",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "DWI\\Z_T_Antero_Read_TAB",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-4155"
          },
          {
            "memberName": "DWI\\Z_P_Antero_Read_TAB",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-4156"
          },
          {
            "memberName": "DWI\\T_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1732"
          },
          {
            "memberName": "DWI\\P_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1733"
          },
          {
            "memberName": "NT AUTHORITY\\IUSR",
            "memberId": "S-1-5-17"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "400"
      }
    ]
  }
}