{
  "name": "SemanticModel",
  "compatibilityLevel": 1200,
  "model": {
    "culture": "fi-FI",
    "dataSources": [
      {
        "name": "SqlServer dwitvipusql16 antero",
        "connectionString": "Provider=SQLNCLI11;Data Source=dwitvipusql16;Initial Catalog=antero;Integrated Security=SSPI;Persist Security Info=false",
        "impersonationMode": "impersonateAccount",
        "account": "DWI\\T_VIPUTK_KUUTIO",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "Muuttujat",
        "columns": [
          {
            "name": "Tilastovuosi",
            "dataType": "int64",
            "sourceColumn": "Tilastovuosi",
            "sourceProviderType": "Integer",
            "displayFolder": "Aikamuuttujat"
          },
          {
            "name": "Tutkinto",
            "dataType": "string",
            "sourceColumn": "Tutkinto",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusala, taso 1",
            "dataType": "string",
            "sourceColumn": "Koulutusala, taso 1",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusala, taso 2",
            "dataType": "string",
            "sourceColumn": "Koulutusala, taso 2",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusala, taso 3",
            "dataType": "string",
            "sourceColumn": "Koulutusala, taso 3",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Tutkintotyyppi",
            "dataType": "string",
            "sourceColumn": "Tutkintotyyppi",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Rahoitusmuoto",
            "dataType": "string",
            "sourceColumn": "Rahoitusmuoto",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Kustannusryhmä",
            "dataType": "string",
            "sourceColumn": "Kustannusryhmä",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Erityisopetus",
            "dataType": "string",
            "sourceColumn": "Erityisopetus",
            "sourceProviderType": "Char",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Suorituksen tyyppi",
            "dataType": "string",
            "sourceColumn": "Suorituksen tyyppi",
            "sourceProviderType": "Char",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutuksen järjestäjä",
            "dataType": "string",
            "sourceColumn": "Koulutuksen järjestäjä",
            "sourceProviderType": "WChar",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Koodit Koulutuksen järjestäjä",
            "dataType": "string",
            "sourceColumn": "Koodit Koulutuksen järjestäjä",
            "sourceProviderType": "Char",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koodit Tutkinto",
            "dataType": "string",
            "sourceColumn": "Koodit Tutkinto",
            "sourceProviderType": "Char",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koodit Tutkintotyyppi",
            "dataType": "string",
            "sourceColumn": "Koodit Tutkintotyyppi",
            "sourceProviderType": "Char",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "painottamaton_tutkinnot",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "painottamaton_tutkinnot",
            "sourceProviderType": "Integer"
          },
          {
            "name": "painottamaton_osatutkinnot",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "painottamaton_osatutkinnot",
            "sourceProviderType": "Integer"
          },
          {
            "name": "painottamaton_osaamispisteet",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "painottamaton_osaamispisteet",
            "sourceProviderType": "Double"
          },
          {
            "name": "painotettu_tutkinnot_pt_kr_pk",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "painotettu_tutkinnot_pt_kr_pk",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "painotettu_tutkinnot_at_eat_kr_pk",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "painotettu_tutkinnot_at_eat_kr_pk",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "painotettu_tutkinnot_erityistuki",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "painotettu_tutkinnot_erityistuki",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "painotettu_tutkinnon_osien_osaamispisteet_pt_kr",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "painotettu_tutkinnon_osien_osaamispisteet_pt_kr",
            "sourceProviderType": "Double"
          },
          {
            "name": "painotettu_tutkinnon_osien_osaamispisteet_at_eat_kr",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "painotettu_tutkinnon_osien_osaamispisteet_at_eat_kr",
            "sourceProviderType": "Double"
          },
          {
            "name": "painotettu_tutkinnon_osien_osaamispisteet_erityistuki",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "painotettu_tutkinnon_osien_osaamispisteet_erityistuki",
            "sourceProviderType": "Double"
          },
          {
            "name": "painotettu_tutkinnot_yht",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "painotettu_tutkinnot_yht",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "painotettu_tutkinnon_osien_osaamispisteet_yht",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "painotettu_tutkinnon_osien_osaamispisteet_yht",
            "sourceProviderType": "Double"
          },
          {
            "name": "Oppisopimuskoulutus",
            "dataType": "string",
            "sourceColumn": "Oppisopimuskoulutus",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "painotettu_tutkinnon_osien_osaamispisteet_pt_kr_oikaisu",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "painotettu_tutkinnon_osien_osaamispisteet_pt_kr_oikaisu"
          },
          {
            "name": "oikaisu",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "oikaisu"
          },
          {
            "name": "painotettu_tutkinnon_osien_osaamispisteet_at_eat_kr_oikaisu",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "painotettu_tutkinnon_osien_osaamispisteet_at_eat_kr_oikaisu"
          },
          {
            "name": "painotettu_tutkinnon_osien_osaamispisteet_erityistuki_oikaisu",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "painotettu_tutkinnon_osien_osaamispisteet_erityistuki_oikaisu"
          },
          {
            "name": "leikkauskerroin2",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "leikkauskerroin"
          },
          {
            "name": "tavoitteelliset_opv",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "tavoitteelliset_opv"
          },
          {
            "name": "rahoitusmuoto_maksetaan",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "rahoitusmuoto_maksetaan"
          }
        ],
        "partitions": [
          {
            "name": "v_amos_tutkinnot_osaamispisteet",
            "dataView": "full",
            "source": {
              "query": " SELECT [dw].[v_amos_tutkinnot_ja_tutkinnonosat].* FROM [dw].[v_amos_tutkinnot_ja_tutkinnonosat] ",
              "dataSource": "SqlServer dwitvipusql16 antero"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tilastovuosi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>123</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tutkinto</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>98</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusala, taso 1</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>173</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusala, taso 2</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>173</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusala, taso 3</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>173</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tutkintotyyppi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>141</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Rahoitusmuoto</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>146</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kustannusryhmä</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>156</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Erityisopetus</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>129</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Suorituksen tyyppi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>170</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutuksen järjestäjä</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>195</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit Koulutuksen järjestäjä</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>245</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit Tutkinto</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>148</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit Tutkintotyyppi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>191</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>painottamaton_tutkinnot</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>213</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>painottamaton_osatutkinnot</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>237</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>painottamaton_osaamispisteet</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>253</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>painotettu_tutkinnot_pt_kr_pk</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>254</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>painotettu_tutkinnot_at_eat_kr_pk</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>283</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>painotettu_tutkinnot_erityistuki</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>259</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>painotettu_tutkinnon_osien_osaamispisteet_pt_kr</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>390</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>painotettu_tutkinnon_osien_osaamispisteet_at_eat_kr</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>419</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>painotettu_tutkinnon_osien_osaamispisteet_erityistuki</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>421</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>painotettu_tutkinnot_yht</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>213</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>painotettu_tutkinnon_osien_osaamispisteet_yht</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>375</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Oppisopimuskoulutus</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>192</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>painotettu_tutkinnon_osien_osaamispisteet_pt_kr_oikaisu</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>308</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>oikaisu</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>62</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>painotettu_tutkinnon_osien_osaamispisteet_at_eat_kr_oikaisu</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>330</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>painotettu_tutkinnon_osien_osaamispisteet_erityistuki_oikaisu</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>329</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>leikkauskerroin</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>145</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tavoitteelliset_opv</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>166</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>rahoitusmuoto_maksetaan</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>226</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tilastovuosi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tutkinto</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusala, taso 1</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusala, taso 2</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusala, taso 3</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tutkintotyyppi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>5</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Rahoitusmuoto</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>6</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kustannusryhmä</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>7</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Erityisopetus</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>8</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Suorituksen tyyppi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>9</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutuksen järjestäjä</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>10</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit Koulutuksen järjestäjä</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>11</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit Tutkinto</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>12</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit Tutkintotyyppi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>13</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>painottamaton_tutkinnot</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>14</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>painottamaton_osatutkinnot</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>15</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>painottamaton_osaamispisteet</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>16</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>painotettu_tutkinnot_pt_kr_pk</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>17</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>painotettu_tutkinnot_at_eat_kr_pk</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>18</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>painotettu_tutkinnot_erityistuki</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>19</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>painotettu_tutkinnon_osien_osaamispisteet_pt_kr</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>20</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>painotettu_tutkinnon_osien_osaamispisteet_at_eat_kr</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>21</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>painotettu_tutkinnon_osien_osaamispisteet_erityistuki</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>22</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>painotettu_tutkinnot_yht</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>23</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>painotettu_tutkinnon_osien_osaamispisteet_yht</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>24</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Oppisopimuskoulutus</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>25</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>painotettu_tutkinnon_osien_osaamispisteet_pt_kr_oikaisu</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>26</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>oikaisu</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>27</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>painotettu_tutkinnon_osien_osaamispisteet_at_eat_kr_oikaisu</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>28</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>painotettu_tutkinnon_osien_osaamispisteet_erityistuki_oikaisu</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>29</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>leikkauskerroin</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>30</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tavoitteelliset_opv</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>31</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>rahoitusmuoto_maksetaan</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>32</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Oppisopimuskoulutus</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>painotettu_tutkinnon_osien_osaamispisteet_pt_kr_oikaisu</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>oikaisu</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>painotettu_tutkinnon_osien_osaamispisteet_at_eat_kr_oikaisu</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>painotettu_tutkinnon_osien_osaamispisteet_erityistuki_oikaisu</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>leikkauskerroin</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tavoitteelliset_opv</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>rahoitusmuoto_maksetaan</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Tutkintojen määrä",
            "expression": [
              "",
              "var summa = CALCULATE(SUM([painottamaton_tutkinnot]),FILTER(Muuttujat,[Suorituksen tyyppi]=\"Koko tutkinto\"))",
              "return IF(summa=0,BLANK(),summa)"
            ],
            "formatString": "#,0",
            "displayFolder": "Painottamattomat"
          },
          {
            "name": "Tutkinnon osien määrä (suorittaa koko tutkintoa)",
            "expression": [
              "",
              "var summa = CALCULATE(SUM([painottamaton_osatutkinnot]),FILTER(Muuttujat,[Suorituksen tyyppi]=\"Koko tutkinto\"))",
              "return IF(summa=0,BLANK(),summa)"
            ],
            "formatString": "#,0",
            "displayFolder": "Painottamattomat"
          },
          {
            "name": "Osaamispisteiden määrä (suorittaa koko tutkintoa)",
            "expression": [
              "",
              "var summa = CALCULATE(SUM([painottamaton_osaamispisteet]),FILTER(Muuttujat,[Suorituksen tyyppi]=\"Koko tutkinto\"))",
              "return IF(summa=0,BLANK(),summa)"
            ],
            "formatString": "#,0",
            "displayFolder": "Painottamattomat"
          },
          {
            "name": "Tutkinnon osien määrä (ei suorita koko tutkintoa)",
            "expression": [
              "",
              "var summa = CALCULATE(SUM(Muuttujat[painottamaton_osatutkinnot]),FILTER(Muuttujat,[Suorituksen tyyppi]=\"Tutkinnon osa/osia\"))",
              "return IF(summa=0,BLANK(),summa)"
            ],
            "formatString": "#,0",
            "displayFolder": "Painottamattomat"
          },
          {
            "name": "Osaamispisteiden määrä (ei suorita koko tutkintoa)",
            "expression": [
              "",
              "var summa = CALCULATE(SUM([painottamaton_osaamispisteet]),FILTER(Muuttujat,[Suorituksen tyyppi]=\"Tutkinnon osa/osia\"))",
              "return IF(summa=0,BLANK(),summa)"
            ],
            "formatString": "#,0",
            "displayFolder": "Painottamattomat"
          },
          {
            "name": "Perustutkintojen kustannusryhmän ja pohjakoulutuksen mukaan painotetut pisteet",
            "expression": "SUM([painotettu_tutkinnot_pt_kr_pk])",
            "formatString": "#,0.00",
            "displayFolder": "Painotetut"
          },
          {
            "name": "Ammatti- ja erikoisammattitutkintojen kustannusryhmän ja pohjakoulutuksen mukaan painotetut pisteet",
            "expression": "SUM([painotettu_tutkinnot_at_eat_kr_pk])",
            "formatString": "#,0.00",
            "displayFolder": "Painotetut"
          },
          {
            "name": "Erityisen tuen mukaan painotetut tutkintojen pisteet",
            "expression": "SUM([painotettu_tutkinnot_erityistuki])",
            "formatString": "#,0.00",
            "displayFolder": "Painotetut"
          },
          {
            "name": "Perustutkintojen osien kustannusryhmän mukaan painotetut osaamispisteet",
            "expression": "SUM([painotettu_tutkinnon_osien_osaamispisteet_pt_kr])",
            "formatString": "#,0.00",
            "displayFolder": "Painotetut"
          },
          {
            "name": "Ammatti- ja erikoisammattitutkintojen osien kustannusryhmän mukaan painotetut osaamispisteet",
            "expression": "SUM([painotettu_tutkinnon_osien_osaamispisteet_at_eat_kr])",
            "formatString": "#,0.00",
            "displayFolder": "Painotetut"
          },
          {
            "name": "Erityisen tuen mukaan painotetut tutkinnon osien osaamispisteet",
            "expression": "SUM([painotettu_tutkinnon_osien_osaamispisteet_erityistuki])",
            "formatString": "#,0.00",
            "displayFolder": "Painotetut"
          },
          {
            "name": "Tutkintojen painotetut pisteet yhteensä",
            "expression": [
              "",
              "[Perustutkintojen kustannusryhmän ja pohjakoulutuksen mukaan painotetut pisteet]",
              "+[Ammatti- ja erikoisammattitutkintojen kustannusryhmän ja pohjakoulutuksen mukaan painotetut pisteet]",
              "+[Erityisen tuen mukaan painotetut tutkintojen pisteet]"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Painotetut"
          },
          {
            "name": "Tutkinnon osien painotetut osaamispisteet yhteensä",
            "expression": [
              "",
              "[Perustutkintojen osien kustannusryhmän mukaan painotetut osaamispisteet]",
              "+[Ammatti- ja erikoisammattitutkintojen osien kustannusryhmän mukaan painotetut osaamispisteet]",
              "+[Erityisen tuen mukaan painotetut tutkinnon osien osaamispisteet]"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Painotetut"
          },
          {
            "name": "Tutkintojen ja tutkinnon osien painotetut pisteet yhteensä",
            "expression": [
              "",
              "[Tutkintojen painotetut pisteet yhteensä]",
              "+[Tutkinnon osien painotetut osaamispisteet yhteensä]"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Painotetut"
          },
          {
            "name": "Perustutkintojen määrä",
            "expression": [
              "",
              "var summa = CALCULATE(SUM([painottamaton_tutkinnot]),Muuttujat[Suorituksen tyyppi]=\"Koko tutkinto\",Muuttujat[Koodit Tutkintotyyppi]=\"02\")",
              "return IF(summa=0,BLANK(),summa)",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Painottamattomat"
          },
          {
            "name": "Ammatti- ja erikoisammattitutkintojen määrä",
            "expression": [
              "",
              "var summa = CALCULATE(SUM([painottamaton_tutkinnot]),Muuttujat[Suorituksen tyyppi]=\"Koko tutkinto\",Muuttujat[Koodit Tutkintotyyppi]=\"19\" || Muuttujat[Koodit Tutkintotyyppi]=\"20\")",
              "return IF(summa=0,BLANK(),summa)",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Painottamattomat"
          },
          {
            "name": "Perustutkintojen tutkinnon osien määrä",
            "expression": [
              "",
              "var summa = CALCULATE(SUM(Muuttujat[painottamaton_osatutkinnot]),Muuttujat[Koodit Tutkintotyyppi]=\"02\")",
              "return IF(summa=0,BLANK(),summa)",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Painottamattomat"
          },
          {
            "name": "Ammatti- ja erikoisammattitutkintojen tutkinnon osien määrä",
            "expression": [
              "",
              "var summa = CALCULATE(SUM(Muuttujat[painottamaton_osatutkinnot]),Muuttujat[Koodit Tutkintotyyppi]=\"19\" || Muuttujat[Koodit Tutkintotyyppi]=\"20\")",
              "return IF(summa=0,BLANK(),summa)",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Painottamattomat"
          },
          {
            "name": "Perustutkintojen kustannusryhmän ja pohjakoulutuksen mukaan painotetut pisteet %",
            "expression": "SUM([painotettu_tutkinnot_pt_kr_pk]) / CALCULATE(SUM(Muuttujat[painotettu_tutkinnot_pt_kr_pk]),ALL(Muuttujat[Koulutuksen järjestäjä]))",
            "formatString": "0.00 %;-0.00 %;0.00 %",
            "displayFolder": "Prosenttiosuudet"
          },
          {
            "name": "Ammatti- ja erikoisammattitutkintojen kustannusryhmän ja pohjakoulutuksen mukaan painotetut pist %",
            "expression": "SUM([painotettu_tutkinnot_at_eat_kr_pk]) / CALCULATE(SUM(Muuttujat[painotettu_tutkinnot_at_eat_kr_pk]),ALL(Muuttujat[Koulutuksen järjestäjä]))",
            "formatString": "0.00 %;-0.00 %;0.00 %",
            "displayFolder": "Prosenttiosuudet"
          },
          {
            "name": "Erityisen tuen mukaan painotetut tutkintojen pisteet %",
            "expression": "SUM([painotettu_tutkinnot_erityistuki]) / CALCULATE(SUM([painotettu_tutkinnot_erityistuki]),ALL(Muuttujat[Koulutuksen järjestäjä]))",
            "formatString": "0.00 %;-0.00 %;0.00 %",
            "displayFolder": "Prosenttiosuudet"
          },
          {
            "name": "Perustutkintojen osien kustannusryhmän mukaan painotetut osaamispisteet %",
            "expression": "SUM([painotettu_tutkinnon_osien_osaamispisteet_pt_kr]) / CALCULATE(SUM([painotettu_tutkinnon_osien_osaamispisteet_pt_kr]),ALL(Muuttujat[Koulutuksen järjestäjä]))",
            "formatString": "0.00 %;-0.00 %;0.00 %",
            "displayFolder": "Prosenttiosuudet"
          },
          {
            "name": "Ammatti- ja erikoisammattitutkintojen osien kustannusryhmän mukaan painotetut osaamispisteet %",
            "expression": "SUM([painotettu_tutkinnon_osien_osaamispisteet_at_eat_kr]) / CALCULATE(SUM([painotettu_tutkinnon_osien_osaamispisteet_at_eat_kr]),ALL(Muuttujat[Koulutuksen järjestäjä]))",
            "formatString": "0.00 %;-0.00 %;0.00 %",
            "displayFolder": "Prosenttiosuudet"
          },
          {
            "name": "Erityisen tuen mukaan painotetut tutkinnon osien osaamispisteet %",
            "expression": "SUM([painotettu_tutkinnon_osien_osaamispisteet_erityistuki]) / CALCULATE(SUM([painotettu_tutkinnon_osien_osaamispisteet_erityistuki]),ALL(Muuttujat[Koulutuksen järjestäjä]))",
            "formatString": "0.00 %;-0.00 %;0.00 %",
            "displayFolder": "Prosenttiosuudet"
          },
          {
            "name": "Tutkintojen painotetut pisteet yhteensä %",
            "expression": [
              "",
              "(CALCULATE(",
              "[Perustutkintojen kustannusryhmän ja pohjakoulutuksen mukaan painotetut pisteet]",
              "+[Ammatti- ja erikoisammattitutkintojen kustannusryhmän ja pohjakoulutuksen mukaan painotetut pisteet]",
              "+[Erityisen tuen mukaan painotetut tutkintojen pisteet])) ",
              "/",
              "(CALCULATE(",
              "[Perustutkintojen kustannusryhmän ja pohjakoulutuksen mukaan painotetut pisteet]",
              "+[Ammatti- ja erikoisammattitutkintojen kustannusryhmän ja pohjakoulutuksen mukaan painotetut pisteet]",
              "+[Erityisen tuen mukaan painotetut tutkintojen pisteet],ALLEXCEPT(Muuttujat,Muuttujat[Rahoitusmuoto])))"
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %",
            "displayFolder": "Prosenttiosuudet"
          },
          {
            "name": "Tutkintojen ja tutkinnon osien painotetut pisteet, järj. %-osuus",
            "expression": [
              "",
              "(CALCULATE(",
              "[Tutkintojen painotetut pisteet yhteensä]",
              "+[Tutkinnon osien painotetut osaamispisteet yhteensä])) /",
              "(CALCULATE(",
              "[Tutkintojen painotetut pisteet yhteensä]",
              "+[Tutkinnon osien painotetut osaamispisteet yhteensä],ALLEXCEPT(Muuttujat,Muuttujat[Rahoitusmuoto]))",
              ")"
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %",
            "displayFolder": "Prosenttiosuudet"
          },
          {
            "name": "Tutkinnon osien painotetut osaamispisteet yhteensä %",
            "expression": [
              "",
              "CALCULATE(",
              "[Perustutkintojen osien kustannusryhmän mukaan painotetut osaamispisteet]",
              "+[Ammatti- ja erikoisammattitutkintojen osien kustannusryhmän mukaan painotetut osaamispisteet]",
              "+[Erityisen tuen mukaan painotetut tutkinnon osien osaamispisteet]) /",
              "CALCULATE(",
              "[Perustutkintojen osien kustannusryhmän mukaan painotetut osaamispisteet]",
              "+[Ammatti- ja erikoisammattitutkintojen osien kustannusryhmän mukaan painotetut osaamispisteet]",
              "+[Erityisen tuen mukaan painotetut tutkinnon osien osaamispisteet],ALLEXCEPT(Muuttujat,Muuttujat[Rahoitusmuoto]))",
              ""
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %",
            "displayFolder": "Prosenttiosuudet"
          },
          {
            "name": "Tutkintojen ja tutkinnon osien painotetut pisteet, järj. %-osuus OIKAISU",
            "expression": [
              "",
              "(",
              "\tCALCULATE(",
              "\t[Tutkintojen painotetut pisteet yhteensä]",
              "\t+[Tutkinnon osien painotetut osaamispisteet yhteensä]",
              "\t-[Tutkinnon osien painotetut osaamispisteet yhteensä OIKAISU]",
              "\t) /",
              "(CALCULATE(",
              "[Tutkintojen painotetut pisteet yhteensä]",
              "+[Tutkinnon osien painotetut osaamispisteet yhteensä],ALLEXCEPT(Muuttujat,Muuttujat[Rahoitusmuoto]))",
              ")",
              ")"
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %",
            "isHidden": true
          },
          {
            "name": "Perustutkintojen osien kustannusryhmän mukaan painotetut osaamispisteet OIKAISU",
            "expression": [
              "",
              "CALCULATE(SUM([painotettu_tutkinnon_osien_osaamispisteet_pt_kr_oikaisu]))"
            ],
            "formatString": "#,0.00",
            "isHidden": true
          },
          {
            "name": "Tutkinnon osien painotetut osaamispisteet yhteensä OIKAISU",
            "expression": [
              "",
              "CALCULATE([Perustutkintojen osien kustannusryhmän mukaan painotetut osaamispisteet OIKAISU]",
              "+[Ammatti- ja erikoisammattitutkintojen osien kustannusryhmän mukaan painotetut osaamispisteet OIKAISU]",
              "+[Erityisen tuen mukaan painotetut tutkinnon osien osaamispisteet OIKAISU]",
              ",Muuttujat[oikaisu]=1)"
            ],
            "formatString": "#,0.00",
            "isHidden": true
          },
          {
            "name": "Ammatti- ja erikoisammattitutkintojen osien kustannusryhmän mukaan painotetut osaamispisteet OIKAISU",
            "expression": "SUM([painotettu_tutkinnon_osien_osaamispisteet_at_eat_kr_oikaisu])",
            "formatString": "#,0.00",
            "isHidden": true
          },
          {
            "name": "Erityisen tuen mukaan painotetut tutkinnon osien osaamispisteet OIKAISU",
            "expression": "SUM([painotettu_tutkinnon_osien_osaamispisteet_erityistuki_oikaisu])",
            "formatString": "0.00",
            "isHidden": true
          },
          {
            "name": "Tutkinnon osien painotetut osaamispisteet yhteensä % OIKAISU",
            "expression": [
              "",
              "CALCULATE(",
              "[Tutkinnon osien painotetut osaamispisteet yhteensä]",
              "-[Tutkinnon osien painotetut osaamispisteet yhteensä OIKAISU]",
              ") ",
              "/",
              "CALCULATE(",
              "[Tutkinnon osien painotetut osaamispisteet yhteensä],ALLEXCEPT(Muuttujat,Muuttujat[Rahoitusmuoto])",
              ")",
              ""
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %",
            "isHidden": true
          },
          {
            "name": "Rahoitukseen hyväksytyt painotetut osaamispisteet",
            "expression": [
              "",
              "var summa1 = SUMX(Muuttujat,[painotettu_tutkinnon_osien_osaamispisteet_pt_kr] * IF(Muuttujat[rahoitusmuoto_maksetaan]=1,[leikkauskerroin2],0))",
              "var summa2 = SUMX(Muuttujat,[painotettu_tutkinnon_osien_osaamispisteet_at_eat_kr] * IF(Muuttujat[rahoitusmuoto_maksetaan]=1,[leikkauskerroin2],0))",
              "var summa3 = SUMX(Muuttujat,[painotettu_tutkinnon_osien_osaamispisteet_erityistuki] * IF(Muuttujat[rahoitusmuoto_maksetaan]=1,[leikkauskerroin2],0))",
              "return summa1 + summa2 + summa3"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Painotetut"
          },
          {
            "name": "Rahoitukseen hyväksytyt painottamattomat osaamispisteet",
            "expression": [
              "",
              "var summa = SUMX(Muuttujat, [painottamaton_osaamispisteet] * IF(Muuttujat[rahoitusmuoto_maksetaan]=1,Muuttujat[leikkauskerroin2],0))",
              "",
              "return IF(summa=0,BLANK(),summa)",
              ""
            ],
            "formatString": "#,0.00",
            "displayFolder": "Painottamattomat"
          },
          {
            "name": "Leikkauskerroin",
            "expression": "AVERAGE([leikkauskerroin2])",
            "formatString": "0.00"
          },
          {
            "name": "Tavoitteelliset opiskelijavuodet",
            "expression": [
              "",
              "SUMX(",
              "\tSUMMARIZE(Muuttujat,[Koodit Koulutuksen järjestäjä],[tavoitteelliset_opv])",
              "\t,[tavoitteelliset_opv]",
              ")"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Maksimiosaamispisteet",
            "expression": "[Tavoitteelliset opiskelijavuodet] * 120.0",
            "formatString": "#,0"
          },
          {
            "name": "Tutkinnon osien painottamattomat osaamispisteet yhteensä",
            "expression": "[Osaamispisteiden määrä (ei suorita koko tutkintoa)]+[Osaamispisteiden määrä (suorittaa koko tutkintoa)]",
            "formatString": "#,0.0"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dw].[v_amos_tutkinnot_ja_tutkinnonosat].* FROM [dw].[v_amos_tutkinnot_ja_tutkinnonosat] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "v_amos_tutkinnot_ja_tutkinnonosat"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dw"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Tilastovuosi</string>",
              "      </key>",
              "      <value>",
              "        <int>123</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tutkinto</string>",
              "      </key>",
              "      <value>",
              "        <int>98</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusala, taso 1</string>",
              "      </key>",
              "      <value>",
              "        <int>173</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusala, taso 2</string>",
              "      </key>",
              "      <value>",
              "        <int>173</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusala, taso 3</string>",
              "      </key>",
              "      <value>",
              "        <int>173</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tutkintotyyppi</string>",
              "      </key>",
              "      <value>",
              "        <int>141</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Rahoitusmuoto</string>",
              "      </key>",
              "      <value>",
              "        <int>146</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kustannusryhmä</string>",
              "      </key>",
              "      <value>",
              "        <int>156</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Erityisopetus</string>",
              "      </key>",
              "      <value>",
              "        <int>129</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Suorituksen tyyppi</string>",
              "      </key>",
              "      <value>",
              "        <int>170</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutuksen järjestäjä</string>",
              "      </key>",
              "      <value>",
              "        <int>195</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit Koulutuksen järjestäjä</string>",
              "      </key>",
              "      <value>",
              "        <int>245</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit Tutkinto</string>",
              "      </key>",
              "      <value>",
              "        <int>148</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit Tutkintotyyppi</string>",
              "      </key>",
              "      <value>",
              "        <int>191</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>painottamaton_tutkinnot</string>",
              "      </key>",
              "      <value>",
              "        <int>213</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>painottamaton_osatutkinnot</string>",
              "      </key>",
              "      <value>",
              "        <int>237</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>painottamaton_osaamispisteet</string>",
              "      </key>",
              "      <value>",
              "        <int>253</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>painotettu_tutkinnot_pt_kr_pk</string>",
              "      </key>",
              "      <value>",
              "        <int>254</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>painotettu_tutkinnot_at_eat_kr_pk</string>",
              "      </key>",
              "      <value>",
              "        <int>283</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>painotettu_tutkinnot_erityistuki</string>",
              "      </key>",
              "      <value>",
              "        <int>259</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>painotettu_tutkinnon_osien_osaamispisteet_pt_kr</string>",
              "      </key>",
              "      <value>",
              "        <int>390</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>painotettu_tutkinnon_osien_osaamispisteet_at_eat_kr</string>",
              "      </key>",
              "      <value>",
              "        <int>419</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>painotettu_tutkinnon_osien_osaamispisteet_erityistuki</string>",
              "      </key>",
              "      <value>",
              "        <int>421</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>painotettu_tutkinnot_yht</string>",
              "      </key>",
              "      <value>",
              "        <int>213</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>painotettu_tutkinnon_osien_osaamispisteet_yht</string>",
              "      </key>",
              "      <value>",
              "        <int>375</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Oppisopimuskoulutus</string>",
              "      </key>",
              "      <value>",
              "        <int>192</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>painotettu_tutkinnon_osien_osaamispisteet_pt_kr_oikaisu</string>",
              "      </key>",
              "      <value>",
              "        <int>308</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>oikaisu</string>",
              "      </key>",
              "      <value>",
              "        <int>62</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>painotettu_tutkinnon_osien_osaamispisteet_at_eat_kr_oikaisu</string>",
              "      </key>",
              "      <value>",
              "        <int>330</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>painotettu_tutkinnon_osien_osaamispisteet_erityistuki_oikaisu</string>",
              "      </key>",
              "      <value>",
              "        <int>329</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>leikkauskerroin</string>",
              "      </key>",
              "      <value>",
              "        <int>145</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tavoitteelliset_opv</string>",
              "      </key>",
              "      <value>",
              "        <int>166</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>rahoitusmuoto_maksetaan</string>",
              "      </key>",
              "      <value>",
              "        <int>226</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Tilastovuosi</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tutkinto</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusala, taso 1</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusala, taso 2</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusala, taso 3</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tutkintotyyppi</string>",
              "      </key>",
              "      <value>",
              "        <int>5</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Rahoitusmuoto</string>",
              "      </key>",
              "      <value>",
              "        <int>6</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kustannusryhmä</string>",
              "      </key>",
              "      <value>",
              "        <int>7</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Erityisopetus</string>",
              "      </key>",
              "      <value>",
              "        <int>8</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Suorituksen tyyppi</string>",
              "      </key>",
              "      <value>",
              "        <int>9</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutuksen järjestäjä</string>",
              "      </key>",
              "      <value>",
              "        <int>10</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit Koulutuksen järjestäjä</string>",
              "      </key>",
              "      <value>",
              "        <int>11</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit Tutkinto</string>",
              "      </key>",
              "      <value>",
              "        <int>12</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit Tutkintotyyppi</string>",
              "      </key>",
              "      <value>",
              "        <int>13</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>painottamaton_tutkinnot</string>",
              "      </key>",
              "      <value>",
              "        <int>14</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>painottamaton_osatutkinnot</string>",
              "      </key>",
              "      <value>",
              "        <int>15</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>painottamaton_osaamispisteet</string>",
              "      </key>",
              "      <value>",
              "        <int>16</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>painotettu_tutkinnot_pt_kr_pk</string>",
              "      </key>",
              "      <value>",
              "        <int>17</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>painotettu_tutkinnot_at_eat_kr_pk</string>",
              "      </key>",
              "      <value>",
              "        <int>18</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>painotettu_tutkinnot_erityistuki</string>",
              "      </key>",
              "      <value>",
              "        <int>19</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>painotettu_tutkinnon_osien_osaamispisteet_pt_kr</string>",
              "      </key>",
              "      <value>",
              "        <int>20</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>painotettu_tutkinnon_osien_osaamispisteet_at_eat_kr</string>",
              "      </key>",
              "      <value>",
              "        <int>21</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>painotettu_tutkinnon_osien_osaamispisteet_erityistuki</string>",
              "      </key>",
              "      <value>",
              "        <int>22</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>painotettu_tutkinnot_yht</string>",
              "      </key>",
              "      <value>",
              "        <int>23</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>painotettu_tutkinnon_osien_osaamispisteet_yht</string>",
              "      </key>",
              "      <value>",
              "        <int>24</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Oppisopimuskoulutus</string>",
              "      </key>",
              "      <value>",
              "        <int>25</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>painotettu_tutkinnon_osien_osaamispisteet_pt_kr_oikaisu</string>",
              "      </key>",
              "      <value>",
              "        <int>26</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>oikaisu</string>",
              "      </key>",
              "      <value>",
              "        <int>27</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>painotettu_tutkinnon_osien_osaamispisteet_at_eat_kr_oikaisu</string>",
              "      </key>",
              "      <value>",
              "        <int>28</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>painotettu_tutkinnon_osien_osaamispisteet_erityistuki_oikaisu</string>",
              "      </key>",
              "      <value>",
              "        <int>29</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>leikkauskerroin</string>",
              "      </key>",
              "      <value>",
              "        <int>30</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tavoitteelliset_opv</string>",
              "      </key>",
              "      <value>",
              "        <int>31</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>rahoitusmuoto_maksetaan</string>",
              "      </key>",
              "      <value>",
              "        <int>32</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Oppisopimuskoulutus</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>painotettu_tutkinnon_osien_osaamispisteet_pt_kr_oikaisu</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>oikaisu</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>painotettu_tutkinnon_osien_osaamispisteet_at_eat_kr_oikaisu</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>painotettu_tutkinnon_osien_osaamispisteet_erityistuki_oikaisu</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>leikkauskerroin</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tavoitteelliset_opv</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>rahoitusmuoto_maksetaan</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Sarakeleveys",
        "columns": [
          {
            "name": "Sarakeleveys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Sarakeleveys",
            "sourceProviderType": "Char"
          },
          {
            "name": "leveys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "leveys",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Sarakeleveys",
            "dataView": "full",
            "source": {
              "query": " SELECT [dw].[Sarakeleveys].* FROM [dw].[Sarakeleveys] ",
              "dataSource": "SqlServer dwitvipusql16 antero"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dw].[Sarakeleveys].* FROM [dw].[Sarakeleveys] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Sarakeleveys"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dw"
          }
        ]
      }
    ],
    "perspectives": [
      {
        "name": "Perspektiivi1",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Erityisopetus"
              },
              {
                "name": "Koodit Koulutuksen järjestäjä"
              },
              {
                "name": "Koodit Tutkinto"
              },
              {
                "name": "Koulutuksen järjestäjä"
              },
              {
                "name": "Koulutusala, taso 1"
              },
              {
                "name": "Koulutusala, taso 2"
              },
              {
                "name": "Koulutusala, taso 3"
              },
              {
                "name": "Kustannusryhmä"
              },
              {
                "name": "Rahoitusmuoto"
              },
              {
                "name": "Suorituksen tyyppi"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Tutkinto"
              },
              {
                "name": "Tutkintotyyppi"
              },
              {
                "name": "Oppisopimuskoulutus"
              }
            ],
            "measures": [
              {
                "name": "Ammatti- ja erikoisammattitutkintojen kustannusryhmän ja pohjakoulutuksen mukaan painotetut pist %"
              },
              {
                "name": "Ammatti- ja erikoisammattitutkintojen kustannusryhmän ja pohjakoulutuksen mukaan painotetut pisteet"
              },
              {
                "name": "Ammatti- ja erikoisammattitutkintojen määrä"
              },
              {
                "name": "Ammatti- ja erikoisammattitutkintojen osien kustannusryhmän mukaan painotetut osaamispisteet"
              },
              {
                "name": "Ammatti- ja erikoisammattitutkintojen osien kustannusryhmän mukaan painotetut osaamispisteet %"
              },
              {
                "name": "Ammatti- ja erikoisammattitutkintojen tutkinnon osien määrä"
              },
              {
                "name": "Erityisen tuen mukaan painotetut tutkinnon osien osaamispisteet"
              },
              {
                "name": "Erityisen tuen mukaan painotetut tutkinnon osien osaamispisteet %"
              },
              {
                "name": "Erityisen tuen mukaan painotetut tutkintojen pisteet"
              },
              {
                "name": "Erityisen tuen mukaan painotetut tutkintojen pisteet %"
              },
              {
                "name": "Osaamispisteiden määrä (ei suorita koko tutkintoa)"
              },
              {
                "name": "Osaamispisteiden määrä (suorittaa koko tutkintoa)"
              },
              {
                "name": "Perustutkintojen kustannusryhmän ja pohjakoulutuksen mukaan painotetut pisteet"
              },
              {
                "name": "Perustutkintojen kustannusryhmän ja pohjakoulutuksen mukaan painotetut pisteet %"
              },
              {
                "name": "Perustutkintojen määrä"
              },
              {
                "name": "Perustutkintojen osien kustannusryhmän mukaan painotetut osaamispisteet"
              },
              {
                "name": "Perustutkintojen osien kustannusryhmän mukaan painotetut osaamispisteet %"
              },
              {
                "name": "Perustutkintojen tutkinnon osien määrä"
              },
              {
                "name": "Tutkinnon osien määrä (ei suorita koko tutkintoa)"
              },
              {
                "name": "Tutkinnon osien määrä (suorittaa koko tutkintoa)"
              },
              {
                "name": "Tutkinnon osien painotetut osaamispisteet yhteensä"
              },
              {
                "name": "Tutkinnon osien painotetut osaamispisteet yhteensä %"
              },
              {
                "name": "Tutkintojen ja tutkinnon osien painotetut pisteet yhteensä"
              },
              {
                "name": "Tutkintojen ja tutkinnon osien painotetut pisteet, järj. %-osuus"
              },
              {
                "name": "Tutkintojen määrä"
              },
              {
                "name": "Tutkintojen painotetut pisteet yhteensä"
              },
              {
                "name": "Tutkintojen painotetut pisteet yhteensä %"
              },
              {
                "name": "Rahoitukseen hyväksytyt painotetut osaamispisteet"
              },
              {
                "name": "Rahoitukseen hyväksytyt painottamattomat osaamispisteet"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      }
    ],
    "roles": [
      {
        "name": "Luku",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "DWI\\T_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1732"
          },
          {
            "memberName": "DWI\\P_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1733"
          },
          {
            "memberName": "NT AUTHORITY\\IUSR",
            "memberId": "S-1-5-17"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "400"
      }
    ]
  },
  "id": "SemanticModel"
}