{
  "name": "SemanticModel",
  "compatibilityLevel": 1200,
  "model": {
    "culture": "fi-FI",
    "dataSources": [
      {
        "name": "ANTERO",
        "connectionString": "Provider=SQLNCLI11;Data Source=dwitvipusql16;Initial Catalog=ANTERO;Integrated Security=SSPI;Persist Security Info=false",
        "impersonationMode": "impersonateServiceAccount",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "Muuttujat",
        "columns": [
          {
            "name": "Utbildningsområde",
            "dataType": "string",
            "sourceColumn": "Utbildningsområde",
            "sourceProviderType": "Char",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Field of education",
            "dataType": "string",
            "sourceColumn": "Field of education",
            "sourceProviderType": "Char",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "tili_taso0_fi",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "tili_taso0_fi"
          },
          {
            "name": "tili_taso1_fi",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "tili_taso1_fi"
          },
          {
            "name": "tili_taso2_fi",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "tili_taso2_fi"
          },
          {
            "name": "tili_taso3_fi",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "tili_taso3_fi"
          },
          {
            "name": "tili_taso4_fi",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "tili_taso4_fi"
          },
          {
            "name": "tili_taso0_sv",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "tili_taso0_sv"
          },
          {
            "name": "tili_taso1_sv",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "tili_taso1_sv"
          },
          {
            "name": "tili_taso2_sv",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "tili_taso2_sv"
          },
          {
            "name": "tili_taso3_sv",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "tili_taso3_sv"
          },
          {
            "name": "tili_taso4_sv",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "tili_taso4_sv"
          },
          {
            "name": "tili_taso0_en",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "tili_taso0_en"
          },
          {
            "name": "tili_taso1_en",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "tili_taso1_en"
          },
          {
            "name": "tili_taso2_en",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "tili_taso2_en"
          },
          {
            "name": "tili_taso3_en",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "tili_taso3_en"
          },
          {
            "name": "tili_taso4_en",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "tili_taso4_en"
          },
          {
            "name": "arvo",
            "dataType": "int64",
            "sourceColumn": "arvo",
            "formatString": "#,0.00 \"€\";-#,0.00 \"€\";#,0.00 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1035\" DisplayName=\"€ Finnish (Finland)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "toiminto_nimi_fi",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "toiminto_nimi_fi"
          },
          {
            "name": "Tilastovuosi",
            "dataType": "int64",
            "sourceColumn": "Tilastovuosi",
            "displayFolder": "Aikamuuttujat"
          },
          {
            "name": "Yliopisto",
            "dataType": "string",
            "sourceColumn": "Yliopisto",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Koulutusala",
            "dataType": "string",
            "sourceColumn": "Koulutusala",
            "sortByColumn": "Koodit_koulutusala",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Aineisto",
            "dataType": "string",
            "sourceColumn": "Aineisto"
          },
          {
            "name": "Statistikår",
            "dataType": "int64",
            "sourceColumn": "Statistikår"
          },
          {
            "name": "Universitet",
            "dataType": "string",
            "sourceColumn": "Universitet"
          },
          {
            "name": "Material typ",
            "dataType": "string",
            "sourceColumn": "Material typ"
          },
          {
            "name": "Statistical year",
            "dataType": "int64",
            "sourceColumn": "Statistical year"
          },
          {
            "name": "University",
            "dataType": "string",
            "sourceColumn": "University"
          },
          {
            "name": "Material type",
            "dataType": "string",
            "sourceColumn": "Material type"
          },
          {
            "name": "Koodit_yliopisto",
            "dataType": "string",
            "sourceColumn": "Koodit_yliopisto"
          },
          {
            "name": "Koodit_koulutusala",
            "dataType": "string",
            "sourceColumn": "Koodit_koulutusala"
          },
          {
            "name": "Koodit_aineisto",
            "dataType": "string",
            "sourceColumn": "Koodit_aineisto"
          },
          {
            "name": "tili_taso5_fi",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "tili_taso5_fi"
          },
          {
            "name": "tili_taso5_sv",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "tili_taso5_sv"
          },
          {
            "name": "tili_taso5_en",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "tili_taso5_en"
          },
          {
            "name": "Konserni",
            "dataType": "string",
            "sourceColumn": "konserni",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Ohjauksenala_sv",
            "dataType": "string",
            "sourceColumn": "Ohjauksenala_sv"
          },
          {
            "name": "Ohjauksenala_en",
            "dataType": "string",
            "sourceColumn": "Ohjauksenala_en"
          },
          {
            "name": "Ohjauksen ala",
            "dataType": "string",
            "sourceColumn": "Ohjauksenala",
            "sortByColumn": "Koodit_ohjauksenala",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "type": "calculated",
            "name": "Suodatus tilastovuosi",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "Muuttujat[Tilastovuosi]",
            "displayFolder": "Aikamuuttujat"
          },
          {
            "name": "Koodit_ohjauksenala",
            "dataType": "int64",
            "sourceColumn": "Koodit_ohjauksenala"
          },
          {
            "type": "calculated",
            "name": "Tarkennettu toiminto",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "",
              "SWITCH(TRUE(),",
              "Muuttujat[tili_taso5_fi]=\"Esiopetus\",\"Esiopetus\",",
              "Muuttujat[tili_taso5_fi]=\"Perusopetus\",\"Perusopetus\",",
              "Muuttujat[tili_taso5_fi]=\"Lukiokoulutus\",\"Lukiokoulutus\",",
              "Muuttujat[tili_taso5_fi]=\"Harjoittelu harjoittelukoulussa\",\"Harjoittelu harjoittelukoulussa\",",
              "Muuttujat[tili_taso5_fi]=\"Harjoittelu harjoittelukoulun ulkopuolella\",\"Harjoittelu harjoittelukoulun ulkopuolella\",",
              "Muuttujat[tili_taso5_fi]=\"Opettajankoulutuksen kehittäminen\",\"Opettajankoulutuksen kehittäminen\",",
              "Muuttujat[tili_taso5_fi]=\"Perustutkintokoulutus\",\"Perustutkintokoulutus\",",
              "Muuttujat[tili_taso5_fi]=\"Perustutkintojen osat\",\"Perustutkintojen osat\",",
              "Muuttujat[tili_taso5_fi]=\"Muu koulutus\",\"Muu koulutus\",",
              "Muuttujat[tili_taso5_fi]=\"Tieteellinen tutkimus\",\"Tieteellinen tutkimus\",",
              "Muuttujat[tili_taso5_fi]=\"Tieteellinen ja taiteellinen jatkotutkintokoulutus\",\"Tieteellinen ja taiteellinen jatkotutkintokoulutus\",",
              "Muuttujat[tili_taso5_fi]=\"Erillislakien mukaiset julkisoikeudelliset suoritteet\",\"Erillislakien mukaiset julkisoikeudelliset suoritteet\",",
              "Muuttujat[tili_taso5_fi]=\"Taiteellinen toiminta\",\"Taiteellinen toiminta\",",
              "Muuttujat[tili_taso5_fi]=\"Yleistoiminnot\",\"Yleistoiminnot\",",
              "Muuttujat[tili_taso5_fi]=\"Yliopistolain mukaiset kansalliskirjastotehtävät yhteensä\",\"Yliopistolain mukaiset kansalliskirjastotehtävät yhteensä\",",
              "Muuttujat[tili_taso5_fi]=\"Kansallisen kulttuuriperinnön tallettaminen ja ylläpito\",\"Kansallisen kulttuuriperinnön tallettaminen ja ylläpito\",",
              "Muuttujat[tili_taso5_fi]=\"Muut tehtävät\",\"Muut tehtävät\",",
              "Muuttujat[tili_taso5_fi]=\"Kansalliset palvelut kirjastoille sekä korkeakoulusektorille\",\"Kansalliset palvelut kirjastoille sekä korkeakoulusektorille\"",
              ")"
            ],
            "displayFolder": "Kustannuslaji"
          },
          {
            "type": "calculated",
            "name": "Toiminto",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "",
              "SWITCH(TRUE(),Muuttujat[tili_taso5_fi]=\"Harjoittelu harjoittelukoulun ulkopuolella\",\"Opettajankoulutus ja kehitystehtävät\",",
              "Muuttujat[tili_taso5_fi]=\"Harjoittelu harjoittelukoulussa\",\"Opettajankoulutus ja kehitystehtävät\",",
              "Muuttujat[tili_taso5_fi]=\"Opettajankoulutuksen kehittäminen\",\"Opettajankoulutus ja kehitystehtävät\",",
              "Muuttujat[tili_taso5_fi]=\"Esiopetus\",\"Opetustehtävät\",",
              "Muuttujat[tili_taso5_fi]=\"Lukiokoulutus\",\"Opetustehtävät\",",
              "Muuttujat[tili_taso5_fi]=\"Perusopetus\",\"Opetustehtävät\",",
              "Muuttujat[tili_taso5_fi]=\"Muut tehtävät\",\"Muut tehtävät\",",
              "Muuttujat[tili_taso5_fi]=\"Kansallisen kulttuuriperinnön tallettaminen ja ylläpito\",\"Yliopistolain mukaiset kansalliskirjastotehtävät\",",
              "Muuttujat[tili_taso5_fi]=\"Kansalliset palvelut kirjastoille sekä korkeakoulusektorille\",\"Yliopistolain mukaiset kansalliskirjastotehtävät\",",
              "Muuttujat[tili_taso5_fi]=\"Muu koulutus\",\"Muu koulutus\",",
              "Muuttujat[tili_taso5_fi]=\"Perustutkintojen osat\",\"Perustutkintojen osat\",",
              "Muuttujat[tili_taso5_fi]=\"Perustutkintokoulutus\",\"Perustutkintokoulutus\",",
              "Muuttujat[tili_taso5_fi]=\"Erillislakien mukaiset julkisoikeudelliset suoritteet\",\"Erillislakien mukaiset julkisoikeudelliset suoritteet\",",
              "Muuttujat[tili_taso5_fi]=\"Yleistoiminnot\",\"Yleistoiminnot\",",
              "Muuttujat[tili_taso5_fi]=\"Taiteellinen toiminta\",\"Taiteellinen toiminta\",",
              "Muuttujat[tili_taso5_fi]=\"Tieteellinen ja taiteellinen jatkotutkintokoulutus\",\"Tieteellinen ja taiteellinen jatkotutkintokoulutus\",",
              "Muuttujat[tili_taso5_fi]=\"Tieteellinen tutkimus\",\"Tieteellinen tutkimus\"",
              "\t)",
              ""
            ],
            "displayFolder": "Kustannuslaji"
          },
          {
            "type": "calculated",
            "name": "Päätoiminto",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "",
              "SWITCH(TRUE(),Muuttujat[tili_taso5_fi]=\"Harjoittelu harjoittelukoulun ulkopuolella\",\"Harjoittelukoulu\",",
              "Muuttujat[tili_taso5_fi]=\"Harjoittelu harjoittelukoulussa\",\"Harjoittelukoulu\",",
              "Muuttujat[tili_taso5_fi]=\"Opettajankoulutuksen kehittäminen\",\"Harjoittelukoulu\",",
              "Muuttujat[tili_taso5_fi]=\"Esiopetus\",\"Harjoittelukoulu\",",
              "Muuttujat[tili_taso5_fi]=\"Lukiokoulutus\",\"Harjoittelukoulu\",",
              "Muuttujat[tili_taso5_fi]=\"Perusopetus\",\"Harjoittelukoulu\",",
              "Muuttujat[tili_taso5_fi]=\"Muut tehtävät\",\"Kansalliskirjasto\",",
              "Muuttujat[tili_taso5_fi]=\"Kansallisen kulttuuriperinnön tallettaminen ja ylläpito\",\"Kansalliskirjasto\",",
              "Muuttujat[tili_taso5_fi]=\"Kansalliset palvelut kirjastoille sekä korkeakoulusektorille\",\"Kansalliskirjasto\",",
              "Muuttujat[tili_taso5_fi]=\"Muu koulutus\",\"Koulutus\",",
              "Muuttujat[tili_taso5_fi]=\"Perustutkintojen osat\",\"Koulutus\",",
              "Muuttujat[tili_taso5_fi]=\"Perustutkintokoulutus\",\"Koulutus\",",
              "Muuttujat[tili_taso5_fi]=\"Erillislakien mukaiset julkisoikeudelliset suoritteet\",\"Muu yhteiskunnallinen toiminta\",",
              "Muuttujat[tili_taso5_fi]=\"Yleistoiminnot\",\"Muu yhteiskunnallinen toiminta\",",
              "Muuttujat[tili_taso5_fi]=\"Taiteellinen toiminta\",\"Taiteellinen toiminta\",",
              "Muuttujat[tili_taso5_fi]=\"Tieteellinen ja taiteellinen jatkotutkintokoulutus\",\"Tutkimus\",",
              "Muuttujat[tili_taso5_fi]=\"Tieteellinen tutkimus\",\"Tutkimus\"",
              "\t)",
              ""
            ],
            "displayFolder": "Kustannuslaji"
          },
          {
            "type": "calculated",
            "name": "Koodit_päätoiminto",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": [
              "    ",
              "SWITCH(TRUE(),Muuttujat[tili_taso5_fi]=\"Harjoittelu harjoittelukoulun ulkopuolella\",\"5\",    ",
              "Muuttujat[tili_taso5_fi]=\"Harjoittelu harjoittelukoulussa\",\"5\",    ",
              "Muuttujat[tili_taso5_fi]=\"Opettajankoulutuksen kehittäminen\",\"5\",    ",
              "Muuttujat[tili_taso5_fi]=\"Esiopetus\",\"5\",    ",
              "Muuttujat[tili_taso5_fi]=\"Lukiokoulutus\",\"5\",    ",
              "Muuttujat[tili_taso5_fi]=\"Perusopetus\",\"5\",    ",
              "Muuttujat[tili_taso5_fi]=\"Muut tehtävät\",\"6\",    ",
              "Muuttujat[tili_taso5_fi]=\"Kansallisen kulttuuriperinnön tallettaminen ja ylläpito\",\"6\",    ",
              "Muuttujat[tili_taso5_fi]=\"Kansalliset palvelut kirjastoille sekä korkeakoulusektorille\",\"6\",    ",
              "Muuttujat[tili_taso5_fi]=\"Muu koulutus\",\"1\",    ",
              "Muuttujat[tili_taso5_fi]=\"Perustutkintojen osat\",\"1\",    ",
              "Muuttujat[tili_taso5_fi]=\"Perustutkintokoulutus\",\"1\",    ",
              "Muuttujat[tili_taso5_fi]=\"Erillislakien mukaiset julkisoikeudelliset suoritteet\",\"4\",    ",
              "Muuttujat[tili_taso5_fi]=\"Yleistoiminnot\",\"4\",    ",
              "Muuttujat[tili_taso5_fi]=\"Taiteellinen toiminta\",\"3\",    ",
              "Muuttujat[tili_taso5_fi]=\"Tieteellinen ja taiteellinen jatkotutkintokoulutus\",\"2\",    ",
              "Muuttujat[tili_taso5_fi]=\"Tieteellinen tutkimus\",\"2\"    ",
              "    )"
            ]
          }
        ],
        "partitions": [
          {
            "name": "AMK_TALOUS",
            "dataView": "full",
            "source": {
              "query": " SELECT [dw].[v_yo_talous].* FROM [dw].[v_yo_talous] ",
              "dataSource": "ANTERO"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit_aineisto</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>103</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit_koulutusala</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>120</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit_yliopisto</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>105</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Material type</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>93</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Utbildningsområde</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>118</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>University</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>78</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Statistical year</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>101</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Field of education</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>115</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Material typ</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>87</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Universitet</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>82</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>arvo</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>52</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso4_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>91</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso3_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>91</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso2_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>91</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso1_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>91</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso0_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>91</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso4_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>90</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso3_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>90</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso2_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>90</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso1_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>90</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso0_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>90</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso4_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>85</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso3_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>85</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso2_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>85</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso1_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>85</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso0_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>85</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Statistikår</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>78</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Aineisto</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>68</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusala</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>85</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Yliopisto</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>69</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>toiminto_nimi_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>104</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tilastovuosi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>86</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso5_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>85</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso5_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>90</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso5_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>91</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Konserni</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>71</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Ohjauksenala</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>95</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Ohjauksenala_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>112</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Ohjauksenala_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>113</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit_ohjauksenala</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>129</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit_aineisto</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>31</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit_koulutusala</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>30</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit_yliopisto</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>29</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Material type</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>28</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Utbildningsområde</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>University</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>27</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Statistical year</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>26</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Field of education</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Material typ</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>25</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Universitet</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>24</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>arvo</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>17</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso4_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>16</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso3_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>15</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso2_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>14</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso1_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>13</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso0_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>12</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso4_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>11</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso3_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>10</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso2_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>9</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso1_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>8</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso0_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>7</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso4_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>6</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso3_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>5</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso2_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso1_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso0_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Statistikår</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>23</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Aineisto</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>22</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusala</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>21</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Yliopisto</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>20</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>toiminto_nimi_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>18</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tilastovuosi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>19</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso5_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>32</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso5_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>33</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso5_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>34</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Konserni</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>35</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Ohjauksenala</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>36</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Ohjauksenala_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>37</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Ohjauksenala_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>38</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit_ohjauksenala</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>39</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Statistical year</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>arvo</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso4_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso3_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso2_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso1_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso0_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso4_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso3_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso2_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso1_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso0_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso4_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso3_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso2_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso1_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso0_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Material typ</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Universitet</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Statistikår</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Aineisto</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>toiminto_nimi_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusala</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Yliopisto</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tilastovuosi</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>University</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Material type</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit_yliopisto</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit_koulutusala</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit_aineisto</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso5_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso5_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso5_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Ohjauksenala</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Ohjauksenala_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Ohjauksenala_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit_ohjauksenala</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Yliopiston varsinaiseen toimintaan kuuluvan liiketoiminnan tuotot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Yliopiston varsinaiseen toimintaan kuuluvan liiketoiminnan tuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Varsinainen toiminta\\Varsinaisen toiminnan tuotot"
          },
          {
            "name": "Tarvikkeet ja tavarat",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Tarvikkeet ja tavarat\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Varsinainen toiminta\\Varsinaisen toiminnan kulut\\Varsinaisen toiminnan kulut eriteltynä"
          },
          {
            "name": "Palvelujen ostot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Palvelujen ostot\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Varsinainen toiminta\\Varsinaisen toiminnan kulut\\Varsinaisen toiminnan kulut eriteltynä"
          },
          {
            "name": "Henkilöstökulut yhteensä",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso3_fi]=\"Henkilöstökulut\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Varsinainen toiminta\\Varsinaisen toiminnan kulut\\Varsinaisen toiminnan kulut eriteltynä\\Henkilökulut"
          },
          {
            "name": "Palkat ja palkkiot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Palkat ja palkkiot\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Varsinainen toiminta\\Varsinaisen toiminnan kulut\\Varsinaisen toiminnan kulut eriteltynä\\Henkilökulut"
          },
          {
            "name": "Eläkemaksut",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Eläkemaksut\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Varsinainen toiminta\\Varsinaisen toiminnan kulut\\Varsinaisen toiminnan kulut eriteltynä\\Henkilökulut"
          },
          {
            "name": "Muut henkilöstösivukulut",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Muut henkilö-sivukulut\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Varsinainen toiminta\\Varsinaisen toiminnan kulut\\Varsinaisen toiminnan kulut eriteltynä\\Henkilökulut"
          },
          {
            "name": "Poistot (vt)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Poistot\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Varsinainen toiminta\\Varsinaisen toiminnan kulut\\Varsinaisen toiminnan kulut eriteltynä"
          },
          {
            "name": "Satunnaiset tuotot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Satunnaiset tuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Satunnaiset erät"
          },
          {
            "name": "Satunnaiset kulut",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Satunnaiset kulut\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Satunnaiset erät"
          },
          {
            "name": "Tuloverot (Liiketoiminta)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Tuloverot\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Tuloverot"
          },
          {
            "name": "Suomen Akatemia avustustuotot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Suomen Akatemia avustustuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Varsinainen toiminta\\Varsinaisen toiminnan tuotot\\Avustustuotot\\Julkinen rahoitus"
          },
          {
            "name": "Business Finland avustustuotot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Business Finland avustustuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Varsinainen toiminta\\Varsinaisen toiminnan tuotot\\Avustustuotot\\Julkinen rahoitus"
          },
          {
            "name": "Muu julkinen hallinto avustustuotot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Muu julkinen hallinto avustustuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Varsinainen toiminta\\Varsinaisen toiminnan tuotot\\Avustustuotot\\Julkinen rahoitus"
          },
          {
            "name": "Valtio pl SA Business Finland ja OKMn yliopistolain muk. rahoitus avustustuotot",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"Valtio (pl. SA, Business Finland ja OKM:n yliopistolain muk. rahoitus) avustustuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Varsinainen toiminta\\Varsinaisen toiminnan tuotot\\Avustustuotot\\Julkinen rahoitus"
          },
          {
            "name": "Kunnat ja kuntayhtymät avustustuotot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Kunnat ja kuntayhtymät avustustuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Varsinainen toiminta\\Varsinaisen toiminnan tuotot\\Avustustuotot\\Julkinen rahoitus"
          },
          {
            "name": "Voittoa tavoittelemattomat yhteisöt avustustuotot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Voittoa tavoittelemattomat yhteisöt avustustuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Varsinainen toiminta\\Varsinaisen toiminnan tuotot\\Avustustuotot"
          },
          {
            "name": "Kotimaiset yritykset avustustuotot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Kotimaiset yritykset avustustuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Varsinainen toiminta\\Varsinaisen toiminnan tuotot\\Avustustuotot\\Kotimainen rahoitus"
          },
          {
            "name": "Kotimaiset rahoituslaitokset avustustuotot",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"Kotimaiset rahoituslaitokset avustustuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Varsinainen toiminta\\Varsinaisen toiminnan tuotot\\Avustustuotot\\Kotimainen rahoitus"
          },
          {
            "name": "Kotitaloudet avustustuotot",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"Kotitaloudet avustustuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Varsinainen toiminta\\Varsinaisen toiminnan tuotot\\Avustustuotot\\Kotimainen rahoitus"
          },
          {
            "name": "EU-rahoitus avustustuotot",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"EU-rahoitus avustustuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Varsinainen toiminta\\Varsinaisen toiminnan tuotot\\Avustustuotot\\Ulkomainen rahoitus"
          },
          {
            "name": "Euroopan Unionin maat - yritysrahoitus avustustuotot",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"Euroopan Unionin maat, yritysrahoitus avustustuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Varsinainen toiminta\\Varsinaisen toiminnan tuotot\\Avustustuotot\\Ulkomainen rahoitus"
          },
          {
            "name": "Euroopan Unionin maat - muu rahoitus avustustuotot",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"Euroopan Unionin maat, muu rahoitus avustustuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Varsinainen toiminta\\Varsinaisen toiminnan tuotot\\Avustustuotot\\Ulkomainen rahoitus"
          },
          {
            "name": "Muut ulkomaat - yritysrahoitus avustustuotot",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"Muut ulkomaat, yritysrahoitus avustustuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Varsinainen toiminta\\Varsinaisen toiminnan tuotot\\Avustustuotot\\Ulkomainen rahoitus"
          },
          {
            "name": "Muut ulkomaat - muu rahoitus avustustuotot",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"Muut ulkomaat, muu rahoitus avustustuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Varsinainen toiminta\\Varsinaisen toiminnan tuotot\\Avustustuotot\\Ulkomainen rahoitus"
          },
          {
            "name": "Kehittämismenot",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"Kehittämismenot\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastaavaa\\PYSYVÄT VASTAAVAT\\Aineettomat hyödykkeet"
          },
          {
            "name": "Aineettomat oikeudet",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"Aineettomat oikeudet\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastaavaa\\PYSYVÄT VASTAAVAT\\Aineettomat hyödykkeet"
          },
          {
            "name": "Liikearvo",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"Liikearvo\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastaavaa\\PYSYVÄT VASTAAVAT\\Aineettomat hyödykkeet"
          },
          {
            "name": "Muut pitkävaikutteiset menot",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"Muut pitkävaikutteiset menot\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastaavaa\\PYSYVÄT VASTAAVAT\\Aineettomat hyödykkeet"
          },
          {
            "name": "Ennakkomaksut",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"Ennakkomaksut\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastaavaa\\PYSYVÄT VASTAAVAT\\Aineettomat hyödykkeet"
          },
          {
            "name": "Maa- ja vesialueet",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"Maa- ja vesialueet\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastaavaa\\PYSYVÄT VASTAAVAT\\Aineelliset hyödykkeet"
          },
          {
            "name": "Rakennukset ja rakennelmat",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"Rakennukset ja rakennelmat\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastaavaa\\PYSYVÄT VASTAAVAT\\Aineelliset hyödykkeet"
          },
          {
            "name": "Koneet ja kalusto",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"Koneet ja kalusto\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastaavaa\\PYSYVÄT VASTAAVAT\\Aineelliset hyödykkeet"
          },
          {
            "name": "Muut aineelliset hyödykkeet",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"Muut aineelliset hyödykkeet\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastaavaa\\PYSYVÄT VASTAAVAT\\Aineelliset hyödykkeet"
          },
          {
            "name": "Ennakkomaksut ja keskeneräiset hankinnat",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"Ennakkomaksut ja keskeneräiset hankinnat\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastaavaa\\PYSYVÄT VASTAAVAT\\Aineelliset hyödykkeet"
          },
          {
            "name": "Osuudet saman konsernin yrityksissä",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso3_fi] = \"Sijoitukset\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Osuudet saman konsernin yrityksissä\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastaavaa\\PYSYVÄT VASTAAVAT\\Sijoitukset"
          },
          {
            "name": "Saamiset saman konsernin yrityksiltä",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"Saamiset saman konsernin yrityksiltä\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastaavaa\\PYSYVÄT VASTAAVAT\\Sijoitukset"
          },
          {
            "name": "Osuudet omistusyhteysyrityksissä",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"Osuudet omistusyhteysyrityksissä\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastaavaa\\PYSYVÄT VASTAAVAT\\Sijoitukset"
          },
          {
            "name": "Saamiset omistusyhteysyrityksiltä",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"Saamiset omistusyhteysyrityksiltä\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastaavaa\\PYSYVÄT VASTAAVAT\\Sijoitukset"
          },
          {
            "name": "Muut osakkeet ja osuudet",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso3_fi] = \"Sijoitukset\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Muut osakkeet ja osuudet\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastaavaa\\PYSYVÄT VASTAAVAT\\Sijoitukset"
          },
          {
            "name": "Muut saamiset",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"Muut saamiset\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastaavaa\\PYSYVÄT VASTAAVAT\\Sijoitukset"
          },
          {
            "name": "Omakatteisten rahastojen varat",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"Omakatteisten rahastojen varat\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastaavaa\\PYSYVÄT VASTAAVAT"
          },
          {
            "name": "Aineet ja tarvikkeet",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"Aineet ja tarvikkeet\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastaavaa\\VAIHTUVAT VASTAAVAT\\Vaihto-omaisuus"
          },
          {
            "name": "Keskeneräiset tuotteet",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"Keskeneräiset tuotteet\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastaavaa\\VAIHTUVAT VASTAAVAT\\Vaihto-omaisuus"
          },
          {
            "name": "Valmiit tuotteet/tavarat",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"Valmiit tuotteet/ tavarat\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastaavaa\\VAIHTUVAT VASTAAVAT\\Vaihto-omaisuus"
          },
          {
            "name": "Muu vaihto-omaisuus",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"Muu vaihto-omaisuus\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastaavaa\\VAIHTUVAT VASTAAVAT\\Vaihto-omaisuus"
          },
          {
            "name": "Ennakkomaksut (vaihto-omaisuus)",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"Ennakkomaksut (vaihto-omaisuus)\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastaavaa\\VAIHTUVAT VASTAAVAT\\Vaihto-omaisuus"
          },
          {
            "name": "Pitkäaikaiset myyntisaamiset",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"P_Myyntisaamiset\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastaavaa\\VAIHTUVAT VASTAAVAT\\Pitkäaikaiset saamiset"
          },
          {
            "name": "Pitkäaikaiset saamiset saman konsernin yrityksiltä",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"P_Saamiset saman konsernin yrityksiltä\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastaavaa\\VAIHTUVAT VASTAAVAT\\Pitkäaikaiset saamiset"
          },
          {
            "name": "Pitkäaikaiset saamiset omistusyhteysyrityksiltä",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"P_Saamiset omistusyhteysyrityksiltä\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastaavaa\\VAIHTUVAT VASTAAVAT\\Pitkäaikaiset saamiset"
          },
          {
            "name": "Pitkäaikaiset lainasaamiset",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"P_Lainasaamiset\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastaavaa\\VAIHTUVAT VASTAAVAT\\Pitkäaikaiset saamiset"
          },
          {
            "name": "Pitkäaikaiset laskennalliset verosaamiset",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"P_Laskennalliset verosaamiset\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastaavaa\\VAIHTUVAT VASTAAVAT\\Pitkäaikaiset saamiset"
          },
          {
            "name": "Pitkäaikaiset muut saamiset",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"P_Muut saamiset\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastaavaa\\VAIHTUVAT VASTAAVAT\\Pitkäaikaiset saamiset"
          },
          {
            "name": "Pitkäaikaiset siirtosaamiset",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"P_Siirtosaamiset\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastaavaa\\VAIHTUVAT VASTAAVAT\\Pitkäaikaiset saamiset"
          },
          {
            "name": "Lyhytaikaiset myyntisaamiset",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"L_Myyntisaamiset\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastaavaa\\VAIHTUVAT VASTAAVAT\\Lyhytaikaiset saamiset"
          },
          {
            "name": "Lyhytaikaiset saamiset saman konsernin yrityksiltä",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"L_Saamiset saman konsernin yrityksiltä\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastaavaa\\VAIHTUVAT VASTAAVAT\\Lyhytaikaiset saamiset"
          },
          {
            "name": "Lyhytaikaiset saamiset omistusyhteysyrityksiltä",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"L_Saamiset omistusyhteysyrityksiltä\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastaavaa\\VAIHTUVAT VASTAAVAT\\Lyhytaikaiset saamiset"
          },
          {
            "name": "Lyhytaikaiset lainasaamiset",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"L_Lainasaamiset\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastaavaa\\VAIHTUVAT VASTAAVAT\\Lyhytaikaiset saamiset"
          },
          {
            "name": "Lyhytaikaiset laskennalliset verosaamiset",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"L_Laskennalliset verosaamiset\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastaavaa\\VAIHTUVAT VASTAAVAT\\Lyhytaikaiset saamiset"
          },
          {
            "name": "Lyhytaikaiset muut saamiset",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"L_Muut saamiset\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastaavaa\\VAIHTUVAT VASTAAVAT\\Lyhytaikaiset saamiset"
          },
          {
            "name": "Lyhytaikaiset siirtosaamiset",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"L_Siirtosaamiset\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastaavaa\\VAIHTUVAT VASTAAVAT\\Lyhytaikaiset saamiset"
          },
          {
            "name": "Osuudet saman konsernin yrityksissä (Rahoitusarvopaperit)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso3_fi] = \"Rahoitusarvopaperit\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Osuudet saman konsernin yrityksissä\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastaavaa\\VAIHTUVAT VASTAAVAT\\Rahoitusarvopaperit"
          },
          {
            "name": "Muut osakkeet ja osuudet (Rahoitusarvopaperit)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso3_fi] = \"Rahoitusarvopaperit\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Muut osakkeet ja osuudet\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastaavaa\\VAIHTUVAT VASTAAVAT\\Rahoitusarvopaperit"
          },
          {
            "name": "Muut arvopaperit",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso1_fi] = \"Vastaavaa\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Muut arvopaperit\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastaavaa\\VAIHTUVAT VASTAAVAT\\Rahoitusarvopaperit"
          },
          {
            "name": "Rahat ja pankkisaamiset",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso1_fi] = \"Vastaavaa\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Rahat ja pankkisaamiset\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastaavaa\\VAIHTUVAT VASTAAVAT"
          },
          {
            "name": "Vastaavaa yhteensä",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso1_fi]=\"Vastaavaa\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastaavaa"
          },
          {
            "name": "Peruspääoma",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"Peruspääoma\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastattavaa\\OMA PÄÄOMA"
          },
          {
            "name": "Arvonkorotusrahasto",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"Arvonkorotusrahasto\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastattavaa\\OMA PÄÄOMA"
          },
          {
            "name": "Käyvän arvon rahasto",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"Käyvän arvon rahasto\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastattavaa\\OMA PÄÄOMA"
          },
          {
            "name": "Omakatteiset rahastot",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"Omakatteiset rahastot\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastattavaa\\OMA PÄÄOMA\\Sidotut rahastot"
          },
          {
            "name": "Muut sidotut rahastot",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"Muut sidotut rahastot\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastattavaa\\OMA PÄÄOMA\\Sidotut rahastot"
          },
          {
            "name": "Vapaat rahastot",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"Sijoitetun vapaan pääoman rahasto\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastattavaa\\OMA PÄÄOMA"
          },
          {
            "name": "Edellisten tilikausien voitto (tappio) (+/-)",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"Edellisten tilikausien voitto (tappio)\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastattavaa\\OMA PÄÄOMA\\Muu oma pääoma"
          },
          {
            "name": "Tilikauden voitto (tappio) (+/-)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tase\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Tilikauden voitto (tappio)\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastattavaa\\OMA PÄÄOMA\\Muu oma pääoma"
          },
          {
            "name": "Oma pääoma yhteensä",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso2_fi]=\"OMA PÄÄOMA\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastattavaa\\OMA PÄÄOMA"
          },
          {
            "name": "Tilinpäätössiirtojen kertymä (Poistoero)",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"Tilinpäätössiirtojen kertymä (Poistoero)\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastattavaa\\TILINPÄÄTÖSSIIRTYMÄT JA PAKOLLISET VARAUKSET"
          },
          {
            "name": "Eläkevaraukset",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"Eläkevaraukset\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastattavaa\\TILINPÄÄTÖSSIIRTYMÄT JA PAKOLLISET VARAUKSET\\Pakolliset varaukset"
          },
          {
            "name": "Verovaraukset",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"Verovaraukset\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastattavaa\\TILINPÄÄTÖSSIIRTYMÄT JA PAKOLLISET VARAUKSET\\Pakolliset varaukset"
          },
          {
            "name": "Muut pakolliset varaukset",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"Muut pakolliset varaukset\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastattavaa\\TILINPÄÄTÖSSIIRTYMÄT JA PAKOLLISET VARAUKSET\\Pakolliset varaukset"
          },
          {
            "name": "Pitkäaikaiset pääomalainat",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"P_Pääomalainat\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastattavaa\\VIERAS PÄÄOMA\\Pitkäaikainen vieras pääoma"
          },
          {
            "name": "Pitkäaikaiset joukkovelkakirjalainat",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"P_Joukkovelkakirjalainat\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastattavaa\\VIERAS PÄÄOMA\\Pitkäaikainen vieras pääoma"
          },
          {
            "name": "Pitkäaikaiset vaihtovelkakirjalainat",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"P_Vaihtovelkakirjalainat\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastattavaa\\VIERAS PÄÄOMA\\Pitkäaikainen vieras pääoma"
          },
          {
            "name": "Pitkäaikaiset lainat rahoituslaitoksilta",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"P_Lainat rahoituslaitoksilta\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastattavaa\\VIERAS PÄÄOMA\\Pitkäaikainen vieras pääoma"
          },
          {
            "name": "Pitkäaikaiset eläkelainat",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"P_Eläkelainat\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastattavaa\\VIERAS PÄÄOMA\\Pitkäaikainen vieras pääoma"
          },
          {
            "name": "Pitkäaikaiset saadut ennakot",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"P_Saadut ennakot\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastattavaa\\VIERAS PÄÄOMA\\Pitkäaikainen vieras pääoma"
          },
          {
            "name": "Pitkäaikaiset ostovelat",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"P_Ostovelat\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastattavaa\\VIERAS PÄÄOMA\\Pitkäaikainen vieras pääoma"
          },
          {
            "name": "Pitkäaikaiset rahoitusvekselit",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"P_Rahoitusvekselit\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastattavaa\\VIERAS PÄÄOMA\\Pitkäaikainen vieras pääoma"
          },
          {
            "name": "Pitkäaikaiset velat saman konsernin yrityksille",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"P_Velat saman konsernin yrityksille\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastattavaa\\VIERAS PÄÄOMA\\Pitkäaikainen vieras pääoma"
          },
          {
            "name": "Pitkäaikaiset velat omistusyhteysyrityksille",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"P_Velat omistusyhteysyrityksille\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastattavaa\\VIERAS PÄÄOMA\\Pitkäaikainen vieras pääoma"
          },
          {
            "name": "Pitkäaikaiset laskennalliset verovelat",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"P_Laskennaliset verovelat\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastattavaa\\VIERAS PÄÄOMA\\Pitkäaikainen vieras pääoma"
          },
          {
            "name": "Pitkäaikaiset muut velat",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"P_Muut velat\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastattavaa\\VIERAS PÄÄOMA\\Pitkäaikainen vieras pääoma"
          },
          {
            "name": "Pitkäaikaiset siirtovelat",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"P_Siirtovelat\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastattavaa\\VIERAS PÄÄOMA\\Pitkäaikainen vieras pääoma"
          },
          {
            "name": "Lyhytaikaiset pääomalainat",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"L_Pääomalainat\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastattavaa\\VIERAS PÄÄOMA\\Lyhytaikainen vieras pääoma"
          },
          {
            "name": "Lyhytaikaiset joukkovelkakirjalainat",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"L_Joukkovelkakirjalainat\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastattavaa\\VIERAS PÄÄOMA\\Lyhytaikainen vieras pääoma"
          },
          {
            "name": "Lyhytaikaiset vaihtovelkakirjalainat",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"L_Vaihtovelkakirjalainat\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastattavaa\\VIERAS PÄÄOMA\\Lyhytaikainen vieras pääoma"
          },
          {
            "name": "Lyhytaikaiset lainat rahoituslaitoksilta",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"L_Lainat rahoituslaitoksilta\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastattavaa\\VIERAS PÄÄOMA\\Lyhytaikainen vieras pääoma"
          },
          {
            "name": "Lyhytaikaiset eläkelainat",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"L_Eläkelainat\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastattavaa\\VIERAS PÄÄOMA\\Lyhytaikainen vieras pääoma"
          },
          {
            "name": "Lyhytaikaiset saadut ennakot",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"L_Saadut ennakot\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastattavaa\\VIERAS PÄÄOMA\\Lyhytaikainen vieras pääoma"
          },
          {
            "name": "Lyhytaikaiset ostovelat",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"L_Ostovelat\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastattavaa\\VIERAS PÄÄOMA\\Lyhytaikainen vieras pääoma"
          },
          {
            "name": "Lyhytaikaiset rahoitusvekselit",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"L_Rahoitusvekselit\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastattavaa\\VIERAS PÄÄOMA\\Lyhytaikainen vieras pääoma"
          },
          {
            "name": "Lyhytaikaiset velat saman konsernin yrityksille",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"L_Velat saman konsernin yrityksille\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastattavaa\\VIERAS PÄÄOMA\\Lyhytaikainen vieras pääoma"
          },
          {
            "name": "Lyhytaikaiset velat omistusyhteysyrityksille",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"L_Velat omistusyhteysyrityksille\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastattavaa\\VIERAS PÄÄOMA\\Lyhytaikainen vieras pääoma"
          },
          {
            "name": "Lyhytaikaiset laskennalliset verovelat",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"L_Laskennaliset verovelat\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastattavaa\\VIERAS PÄÄOMA\\Lyhytaikainen vieras pääoma"
          },
          {
            "name": "Lyhytaikaiset muut velat",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"L_Muut velat\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastattavaa\\VIERAS PÄÄOMA\\Lyhytaikainen vieras pääoma"
          },
          {
            "name": "Lyhytaikaiset siirtovelat",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"L_Siirtovelat\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastattavaa\\VIERAS PÄÄOMA\\Lyhytaikainen vieras pääoma"
          },
          {
            "name": "Vastattavaa yhteensä",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso1_fi]=\"Vastattavaa\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastattavaa"
          },
          {
            "name": "Omakatteisten rahastojen sijoitukset yhteensä",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso3_fi]=\"Omakatteisten rahastojen sijoitukset\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Tilastokeskuksen tarkentavat tiedot\\Omakatteisten rahastojen varat\\Omakattaisten rahastojen sijoitukset"
          },
          {
            "name": "Rahasto-osuudet",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"Rahasto-osuudet\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Tilastokeskuksen tarkentavat tiedot\\Omakatteisten rahastojen varat\\Omakattaisten rahastojen sijoitukset"
          },
          {
            "name": "Muut - osakkeet ja osuudet",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso1_fi] = \"Tilastokeskuksen tarkentavat tiedot\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Muut osakkeet ja osuudet\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Tilastokeskuksen tarkentavat tiedot\\Omakatteisten rahastojen varat\\Omakattaisten rahastojen sijoitukset"
          },
          {
            "name": "Muut - arvopaperit",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso1_fi] = \"Tilastokeskuksen tarkentavat tiedot\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Muut arvopaperit\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Tilastokeskuksen tarkentavat tiedot\\Omakatteisten rahastojen varat\\Omakattaisten rahastojen sijoitukset"
          },
          {
            "name": "Rahat ja pankkisaamiset (Omakatteisten rahastojen varat)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso1_fi] = \"Tilastokeskuksen tarkentavat tiedot\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Rahat ja pankkisaamiset\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Tilastokeskuksen tarkentavat tiedot\\Omakatteisten rahastojen varat"
          },
          {
            "name": "Muut varat",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"Muut varat\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Tilastokeskuksen tarkentavat tiedot\\Omakatteisten rahastojen varat"
          },
          {
            "name": "Tutkimusmenot yhteensä",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso0_fi]=\"Tutkimusmenot\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot"
          },
          {
            "name": "Ulkopuolinen rahoitus yhteensä",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso1_fi]=\"Kotimainen ulkopuolinen rahoitus\"),[arvo])+SUMX(FILTER(Muuttujat,[tili_taso1_fi]=\"Ulkomainen ulkopuolinen rahoitus\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot"
          },
          {
            "name": "Suomen Akatemia",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tutkimusmenot\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Suomen Akatemia\"))",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot\\Kotimainen ulkopuolinen rahoitus"
          },
          {
            "name": "Opetus- ja kulttuuriministeriö",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Muu opetus- ja kulttuuriministeriö\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot\\Kotimainen ulkopuolinen rahoitus"
          },
          {
            "name": "Business Finland",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tutkimusmenot\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Business Finland\"))",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot\\Kotimainen ulkopuolinen rahoitus"
          },
          {
            "name": "Työ- ja elinkeinoministeriö",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Muu työ- ja elinkeinoministeriö\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot\\Kotimainen ulkopuolinen rahoitus"
          },
          {
            "name": "Ulkoasiainministeriö",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Ulkoasiainministeriö\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot\\Kotimainen ulkopuolinen rahoitus"
          },
          {
            "name": "Oikeusministeriö",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Oikeusministeriö\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot\\Kotimainen ulkopuolinen rahoitus"
          },
          {
            "name": "Sisäasiainministeriö",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Sisäasiainministeriö\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot\\Kotimainen ulkopuolinen rahoitus"
          },
          {
            "name": "Puolustusministeriö",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Puolustusministeriö\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot\\Kotimainen ulkopuolinen rahoitus"
          },
          {
            "name": "Valtiovarainministeriö",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Valtiovarainministeriö\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot\\Kotimainen ulkopuolinen rahoitus"
          },
          {
            "name": "Maa- ja metsätalousministeriö",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Maa- ja metsätalousministeriö\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot\\Kotimainen ulkopuolinen rahoitus"
          },
          {
            "name": "Liikenne- ja viestintäministeriö",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Liikenne- ja viestintäministeriö\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot\\Kotimainen ulkopuolinen rahoitus"
          },
          {
            "name": "Sosiaali- ja terveysministeriö",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Sosiaali- ja terveysministeriö\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot\\Kotimainen ulkopuolinen rahoitus"
          },
          {
            "name": "Ympäristöministeriö",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Ympäristöministeriö\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot\\Kotimainen ulkopuolinen rahoitus"
          },
          {
            "name": "Kunnat ja kuntainliitot",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Kunnat ja kuntainliitot\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot\\Kotimainen ulkopuolinen rahoitus"
          },
          {
            "name": "Muu julkinen rahoitus",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Muu julkinen rahoitus\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot\\Kotimainen ulkopuolinen rahoitus"
          },
          {
            "name": "Kotimaiset yksityiset rahastot ja säätiöt",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Kotimaiset yksityiset rahastot ja säätiöt\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot\\Kotimainen ulkopuolinen rahoitus"
          },
          {
            "name": "Kotimaiset yritykset",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tutkimusmenot\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Kotimaiset yritykset\"))",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot\\Kotimainen ulkopuolinen rahoitus"
          },
          {
            "name": "Ulkomaiset yritykset",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Ulkomaiset yritykset\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot\\Ulkomainen ulkopuolinen rahoitus"
          },
          {
            "name": "EU-puiteohjelmarahoitus ja muu laadullisesti kilpailtu EU-rahoitus",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"EU-puiteohjelmarahoitus ja muu laadullisesti kilpailtu EU-rahoitus\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot\\Ulkomainen ulkopuolinen rahoitus"
          },
          {
            "name": "EAKR-rahoitus",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"EAKR- rahoitus\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot\\Ulkomainen ulkopuolinen rahoitus"
          },
          {
            "name": "ESR-rahoitus",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"ESR-rahoitus\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot\\Ulkomainen ulkopuolinen rahoitus"
          },
          {
            "name": "Muu EU-rahoitus",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Muu EU-rahoitus\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot\\Ulkomainen ulkopuolinen rahoitus"
          },
          {
            "name": "Ulkomaiset rahastot ja säätiöt",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Ulkomaiset rahastot ja säätiöt\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot\\Ulkomainen ulkopuolinen rahoitus"
          },
          {
            "name": "Kansainväliset järjestöt",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Kansainväliset järjestöt\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot\\Ulkomainen ulkopuolinen rahoitus"
          },
          {
            "name": "Muu ulkomainen rahoitus",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Muu ulkomainen rahoitus\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot\\Ulkomainen ulkopuolinen rahoitus"
          },
          {
            "name": "Perustutkintokoulutus",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Perustutkintokoulutus\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Varsinaisen toiminnan kustannukset\\Koulutus"
          },
          {
            "name": "Perustutkintojen osat",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Perustutkintojen osat\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Varsinaisen toiminnan kustannukset\\Koulutus"
          },
          {
            "name": "Muu koulutus",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Muu koulutus\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Varsinaisen toiminnan kustannukset\\Koulutus"
          },
          {
            "name": "Tutkimus yhteensä",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso1_fi]=\"Tutkimus\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Varsinaisen toiminnan kustannukset\\Tutkimus"
          },
          {
            "name": "Tieteellinen tutkimus",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Tieteellinen tutkimus\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Varsinaisen toiminnan kustannukset\\Tutkimus"
          },
          {
            "name": "Tieteellinen ja taiteellinen jatkotutkintokoulutus",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Tieteellinen ja taiteellinen jatkotutkintokoulutus\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Varsinaisen toiminnan kustannukset\\Tutkimus"
          },
          {
            "name": "Muu yhteiskunnallinen toiminta yhteensä",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso1_fi]=\"Muu yhteiskunnallinen toiminta\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Varsinaisen toiminnan kustannukset\\Muu yhteiskunnallinen toiminta yhteensä"
          },
          {
            "name": "Koulutus yhteensä",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso1_fi]=\"Koulutus\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Varsinaisen toiminnan kustannukset\\Koulutus"
          },
          {
            "name": "Yliopiston varsinaisen toiminnan kustannukset yhteensä",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso0_fi]=\"Varsinaisen toiminnan kustannukset\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Varsinaisen toiminnan kustannukset"
          },
          {
            "name": "Yliopiston oma rahoitus yhteensä",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Yliopiston oma rahoitus yhteensä\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot"
          },
          {
            "name": "Liikevaihto(Tiedot liiketoiminnasta)",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso1_fi]=\"Liikevaihto\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma"
          },
          {
            "name": "Valmiiden ja keskeneräisten tuotteiden varastojen lisäys tai vähennys",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Valmiiden ja keskeneräisten tuotteiden varastojen lisäys tai vähennys\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Liikevaihto"
          },
          {
            "name": "Valmistus omaan käyttöön",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Valmistus omaan käyttöön\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Liikevaihto"
          },
          {
            "name": "Liiketoiminnan muut tuotot",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Liiketoiminnan muut tuotot\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Liikevaihto"
          },
          {
            "name": "Materiaalit ja palvelut yhteensä",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Liiketoiminnan tuloslaskelma\"), FILTER(Muuttujat,[tili_taso2_fi]=\"Materiaalit ja palvelut\"))",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Liikevaihto"
          },
          {
            "name": "Aineet, tarvikkeet ja tavarat yhteensä",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Liiketoiminnan tuloslaskelma\"), FILTER(Muuttujat,[tili_taso3_fi]=\"Aineet, tarvikkeet ja tavarat\"))",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Liikevaihto\\Materiaalit ja palvelut"
          },
          {
            "name": "Ostot tilikauden aikana (Tiedot liiketoiminnasta)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Liiketoiminnan tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Ostot tilikauden aikana\"))",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Liikevaihto\\Materiaalit ja palvelut"
          },
          {
            "name": "Varastojen lisäys tai vähennys",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Varastojen lisäys tai vähennys\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Liikevaihto\\Materiaalit ja palvelut"
          },
          {
            "name": "Ulkopuoliset palvelut (Tiedot liiketoiminnasta)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Liiketoiminnan tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Ulkopuoliset palvelut\"))",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Liikevaihto\\Materiaalit ja palvelut"
          },
          {
            "name": "Liiketoiminnan henkilöstökulut yhteensä",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Liiketoiminnan tuloslaskelma\"), FILTER(Muuttujat,[tili_taso2_fi]=\"Henkilöstökulut\"))",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Liikevaihto"
          },
          {
            "name": "Liiketoiminnan palkat ja palkkiot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Liiketoiminnan tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Palkat ja palkkiot\"))",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Liikevaihto\\Henkilöstökulut"
          },
          {
            "name": "Liiketoiminnan henkilöstösivukulut yhteensä",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Liiketoiminnan tuloslaskelma\"), FILTER(Muuttujat,[tili_taso3_fi]=\"Henkilöstösivukulut\"))",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Liikevaihto\\Henkilöstökulut"
          },
          {
            "name": "Liiketoiminnan eläkekulut",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Liiketoiminnan tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Eläkekulut\"))",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Liikevaihto\\Henkilöstökulut"
          },
          {
            "name": "Liiketoiminnan muut henkilöstösivukulut",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Liiketoiminnan tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Muut henkilöstösivukulut\"))",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Liikevaihto\\Henkilöstökulut"
          },
          {
            "name": "Poistot ja arvonalentumiset yhteensä",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Liiketoiminnan tuloslaskelma\"), FILTER(Muuttujat,[tili_taso2_fi]=\"Poistot ja arvonalentumiset\"))",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Liikevaihto"
          },
          {
            "name": "Suunnitelman mukaiset poistot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Liiketoiminnan tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Suunnitelman mukaiset poistot\"))",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Liikevaihto\\Poistot ja arvonalentumiset"
          },
          {
            "name": "Arvonalentumiset pysyvien vastaavien hyödykkeistä",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Liiketoiminnan tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Arvonalentumiset pysyvien vastaavien hyödykkeistä\"))",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Liikevaihto\\Poistot ja arvonalentumiset"
          },
          {
            "name": "Vaihtuvien vastaavien poikkeukselliset arvonalentumiset",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Liiketoiminnan tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Vaihtuvien vastaavien poikkeukselliset arvonalentumiset\"))",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Liikevaihto\\Poistot ja arvonalentumiset"
          },
          {
            "name": "Liiketoiminnan muut kulut",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Liiketoiminnan muut kulut\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Liikevaihto"
          },
          {
            "name": "Liikevoitto tai tappio",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Liikevoitto (-tappio)\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma"
          },
          {
            "name": "Rahoitustuotot ja -kulut yhteensä",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso1_fi]=\"Rahoitustuotot ja kulut\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Rahoitustuotot ja -kulut"
          },
          {
            "name": "Tuotot osuuksista saman konsernin yrityksissä",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Liiketoiminnan tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Tuotot osuuksista saman konsernin yrityksissä\"))",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Rahoitustuotot ja -kulut"
          },
          {
            "name": "Tuotot osuuksista omistusyhteysyrityksissä",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Tuotot osuuksista omistusyhteysyrityksissä\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Rahoitustuotot ja -kulut"
          },
          {
            "name": "Tuotot muista pysyvien vastaavien sijoituksista yhteensä",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso2_fi]=\"Tuotot muista pysyvien vastaavien sijoituksista\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Rahoitustuotot ja -kulut"
          },
          {
            "name": "Tuotot muista pysyvien vastaavien sijoituksista saman konsernin yrityksiltä",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Tuotot muista pysyvien vastaavien sijoituksista saman konsernin yrityksiltä\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Rahoitustuotot ja -kulut\\Tuotot muista pysyvien vastaavien sijoituksista"
          },
          {
            "name": "Tuotot muista pysyvien vastaavien sijoituksista muilta",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Tuotot muista pysyvien vastaavien sijoituksista muilta\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Rahoitustuotot ja -kulut\\Tuotot muista pysyvien vastaavien sijoituksista"
          },
          {
            "name": "Muut korko- ja rahoitustuotot yhteensä",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso2_fi]=\"Muut korko- ja rahoitustuotot\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Rahoitustuotot ja -kulut"
          },
          {
            "name": "Muut korko- ja rahoitustuotot saman konsernin yrityksiltä",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Muut korko- ja rahoitustuotot saman konsernin yrityksiltä\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Rahoitustuotot ja -kulut\\Muut korko- ja rahoitustuotot"
          },
          {
            "name": "Muut korko- ja rahoitustuotot muilta",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Muut korko- ja rahoitustuotot muilta\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Rahoitustuotot ja -kulut\\Muut korko- ja rahoitustuotot"
          },
          {
            "name": "Arvonalentumiset pysyvien vastaavien sijoituksista",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Liiketoiminnan tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Arvonalentumiset pysyvien vastaavien sijoituksista\"))",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Rahoitustuotot ja -kulut"
          },
          {
            "name": "Arvonalentumiset vaihtuvien vastaavien rahoitusarvopapereista",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Liiketoiminnan tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Arvonalentumiset vaihtuvien vastaavien rahoitusarvopapereista\"))",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Rahoitustuotot ja -kulut"
          },
          {
            "name": "Korkokulut ja muut rahoituskulut yhteensä",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso2_fi]=\"Korkokulut ja muut rahoituskulut\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Rahoitustuotot ja -kulut"
          },
          {
            "name": "Korkokulut ja muut rahoituskulut saman konsernin yrityksille",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Korkokulut ja muut rahoituskulut saman konsernin yrityksille\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Rahoitustuotot ja -kulut\\Korkokulut ja muut rahoituskulut muille"
          },
          {
            "name": "Korkokulut ja muut rahoituskulut muille",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Korkokulut ja muut rahoituskulut muille\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Rahoitustuotot ja -kulut\\Korkokulut ja muut rahoituskulut muille"
          },
          {
            "name": "Voitto tai tappio ennen satunnaisia eriä",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Voitto (tappio) ennen satunnaisia eriä\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma"
          },
          {
            "name": "Satunnaiset erät yhteensä",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Liiketoiminnan tuloslaskelma\"), FILTER(Muuttujat,[tili_taso1_fi]=\"Satunnaiset erät\"))",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Satunnaiset erät"
          },
          {
            "name": "Liiketoiminnan satunnaiset tuotot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Liiketoiminnan tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Satunnaiset tuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Satunnaiset erät"
          },
          {
            "name": "Liiketoiminnan satunnaiset kulut",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Liiketoiminnan tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Satunnaiset kulut\"))",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Satunnaiset erät"
          },
          {
            "name": "Voitto tai tappio ennen tilinpäätössiirtoja ja veroja",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Liiketoiminnan tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Voitto (tappio) ennen tilinpäätössiirtoja ja veroja\"))",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma"
          },
          {
            "name": "Tilinpäätössiirrot yhteensä",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso1_fi]=\"Tilinpäätössiirrot ja verot\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Tilinpäätössiirrot ja verot"
          },
          {
            "name": "Poistoeron lisäys tai vähennys",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Liiketoiminnan tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Poistoeron lisäys (-) tai vähennys (+)\"))",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Tilinpäätössiirrot ja verot"
          },
          {
            "name": "Vapaaehtoisten varausten lisäys tai vähennys",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Liiketoiminnan tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Vapaaehtoisten varausten lisäys (-) tai vähennys (+)\"))",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Tilinpäätössiirrot ja verot"
          },
          {
            "name": "Liiketoiminnan tuloverot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Liiketoiminnan tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Tuloverot\"))",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Tilinpäätössiirrot ja verot"
          },
          {
            "name": "Muut välittömät verot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Liiketoiminnan tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Muut välittömät verot\"))",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Tilinpäätössiirrot ja verot"
          },
          {
            "name": "Tilikauden voitto tai tappio",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Liiketoiminnan tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Tilikauden voitto (tappio)\"))",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma"
          },
          {
            "name": "Ministeriöt yhteensä",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso4_fi]=\"Ulkoasiainministeriö\"),[arvo])+SUMX(FILTER(Muuttujat,[tili_taso4_fi]=\"Oikeusministeriö\"),[arvo])+SUMX(FILTER(Muuttujat,[tili_taso4_fi]=\"Sisäasiainministeriö\"),[arvo])+SUMX(FILTER(Muuttujat,[tili_taso4_fi]=\"Puolustusministeriö\"),[arvo])+SUMX(FILTER(Muuttujat,[tili_taso4_fi]=\"Valtiovarainministeriö \"),[arvo])+SUMX(FILTER(Muuttujat,[tili_taso4_fi]=\"Maa- ja metsätalousministeriö\"),[arvo])+SUMX(FILTER(Muuttujat,[tili_taso4_fi]=\"Liikenne- ja viestintäministeriö\"),[arvo])+SUMX(FILTER(Muuttujat,[tili_taso4_fi]=\"Sosiaali- ja terveysministeriö\"),[arvo])+SUMX(FILTER(Muuttujat,[tili_taso4_fi]=\"Ympäristöministeriö\"),[arvo])+SUMX(FILTER(Muuttujat,[tili_taso4_fi]=\"Muu opetus- ja kulttuuriministeriö\"),[arvo])+SUMX(FILTER(Muuttujat,[tili_taso4_fi]=\"Muu työ- ja elinkeinoministeriö\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot\\Kotimainen ulkopuolinen rahoitus"
          },
          {
            "name": "Muut varsinaisen toiminnan tuotot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Muut varsinaisen toiminnan tuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Varsinainen toiminta\\Varsinaisen toiminnan tuotot"
          },
          {
            "name": "Konserni - osuus osakkuusyhtiöiden tuloksesta yliopistokonserni",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Konserni; Osuus osakkuus-yhtiöiden tuloksesta\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopistokonserni\\Varsinainen toiminta\\Varsinaisen toiminnan tuotot"
          },
          {
            "name": "Avustustuotot",
            "expression": [
              "",
              "CALCULATE(SUM([arvo]), FILTER(Muuttujat, [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso3_fi]=\"Avustustuotot\"), FILTER(Muuttujat, AND(Muuttujat[tili_taso5_fi] <> \"Konserni; Avustustuotot\", Muuttujat[Konserni] = \"Ei\")))",
              "+",
              "CALCULATE(SUM([arvo]), FILTER(Muuttujat, [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso3_fi]=\"Avustustuotot\"), FILTER(Muuttujat, AND(Muuttujat[tili_taso5_fi] = \"Konserni; Avustustuotot\", Muuttujat[Konserni] = \"Kyllä\")))"
            ],
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Varsinainen toiminta\\Varsinaisen toiminnan tuotot\\Avustustuotot"
          },
          {
            "name": "Vuokrakulut",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Vuokrat\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Varsinainen toiminta\\Varsinaisen toiminnan kulut\\Varsinaisen toiminnan kulut eriteltynä\\Tilakustannukset"
          },
          {
            "name": "Muut tilakustannukset",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Muut tilakustannukset\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Varsinainen toiminta\\Varsinaisen toiminnan kulut\\Varsinaisen toiminnan kulut eriteltynä\\Tilakustannukset"
          },
          {
            "name": "Kone- ja laitevuokrat",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Kone- ja laitevuokrat\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Varsinainen toiminta\\Varsinaisen toiminnan kulut\\Varsinaisen toiminnan kulut eriteltynä"
          },
          {
            "name": "Muut varsinaisen toiminnan kulut",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Muut varsinaisen toiminnan kulut\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Varsinainen toiminta\\Varsinaisen toiminnan kulut\\Varsinaisen toiminnan kulut eriteltynä"
          },
          {
            "name": "Konserni - vähemmistöosuus yliopistokonserni",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso1_fi] = \"Varsinainen toiminta\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Konserni; Vähemmistö osuus\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopistokonserni\\Varsinainen toiminta\\Varsinaisen toiminnan kulut\\Varsinaisen toiminnan kulut eriteltynä"
          },
          {
            "name": "Varsinaisen toiminnan kulut yhteensä",
            "expression": [
              "CALCULATE",
              "(CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso2_fi]=\"Varsinaisen toiminnan kulut\"))",
              "-(CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Vars. toim. kuluista liiketoiminnan kulut\"))))"
            ],
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Varsinainen toiminta\\Varsinaisen toiminnan kulut"
          },
          {
            "name": "Vars. toim. kuluista liiketoiminnan kulut",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Vars. toim. kuluista liiketoiminnan kulut\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Varsinainen toiminta\\Varsinaisen toiminnan kulut"
          },
          {
            "name": "Varsinaisen toiminnan tuotto-kulujäämä",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Tuotto-/ kulujäämä (varsinainen toiminta)\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Varsinainen toiminta"
          },
          {
            "name": "Keräysten tuotot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Keräysten tuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Varainhankinta"
          },
          {
            "name": "Lahjoitukset yhteensä",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso2_fi]=\"Lahjoitukset\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Varainhankinta\\Lahjoitukset"
          },
          {
            "name": "Lahjoitukset yrityksiltä",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Lahjoitukset yrityksiltä\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Varainhankinta\\Lahjoitukset"
          },
          {
            "name": "Lahjoitukset kotitalouksilta",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Lahjoitukset kotitalouksilta\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Varainhankinta\\Lahjoitukset"
          },
          {
            "name": "Muut lahjoitukset",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Muut lahjoitukset\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Varainhankinta\\Lahjoitukset"
          },
          {
            "name": "Varainhankinnan liiketoiminnan tuotot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Varainhankinnan liiketoiminnan tuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Varainhankinta"
          },
          {
            "name": "Muut varainhankinnan tuotot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Muut varainhankinnan tuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Varainhankinta"
          },
          {
            "name": "Konserni- osuus osakkuusyhtiöiden tuloksesta yliopistokonserni",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Konserni; Osuus osakkuus-yhtiöiden tuloksesta\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopistokonserni\\Varainhankinta"
          },
          {
            "name": "Keräystoiminnan kulut",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Keräystoiminnan kulut\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Varainhankinta"
          },
          {
            "name": "Lahjoituksiin ja testamenttien hoitoon liittyvät kulut",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Lahjoituksiin ja testamenttien hoitoon liittyvät kulut\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Varainhankinta"
          },
          {
            "name": "Varainhankinnan liiketoiminnan kulut",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Varainhankinnan liiketoiminnan kulut\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Varainhankinta"
          },
          {
            "name": "Muut varainhankinnan kulut",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Muut varainhankinnan kulut\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Varainhankinta"
          },
          {
            "name": "Vähemmistöosuus varainhankinta",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso1_fi] = \"Varainhankinta\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Konserni; Vähemmistö osuus\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Varainhankinta"
          },
          {
            "name": "Tuotto-/kulujäämä (varainhankinta)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Tuotto-/ kulujäämä (varainhankinta)\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Varainhankinta"
          },
          {
            "name": "Konserni - osuus osakkuusyhtiöiden voitosta-tappiosta yliopistokonserni",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Konserni; Osuus osakkuusyritysten voitosta (tappiosta)\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopistokonserni\\Sijoitus- ja rahoitustoiminta"
          },
          {
            "name": "Osinkotuotot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Osinkotuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Sijoitus- ja rahoitustoiminta"
          },
          {
            "name": "Korkotuotot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Korkotuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Sijoitus- ja rahoitustoiminta"
          },
          {
            "name": "Vuokratuotot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Vuokratuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Sijoitus- ja rahoitustoiminta"
          },
          {
            "name": "Myyntivoitot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Myyntivoitot\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Sijoitus- ja rahoitustoiminta"
          },
          {
            "name": "Arvonalennusten palautukset",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Arvonalennusten palautukset\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Sijoitus- ja rahoitustoiminta"
          },
          {
            "name": "Sijoitus- ja rahoitustoiminnan liiketoiminnan tuotot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Sijoitus- ja rahoitustoiminnan liiketoiminnan tuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Sijoitus- ja rahoitustoiminta"
          },
          {
            "name": "Muut sijoitus- ja rahoitustoiminnan tuotot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Muut sijoitus- ja rahoitustoiminnan tuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Sijoitus- ja rahoitustoiminta"
          },
          {
            "name": "Korkokulut",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Korkokulut\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Sijoitus- ja rahoitustoiminta"
          },
          {
            "name": "Yhtiövastikkeet",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Yhtiövastikkeet\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Sijoitus- ja rahoitustoiminta"
          },
          {
            "name": "Myyntitappiot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Myyntitappiot\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Sijoitus- ja rahoitustoiminta"
          },
          {
            "name": "Arvonalennukset",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Arvonalennukset\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Sijoitus- ja rahoitustoiminta"
          },
          {
            "name": "Sijoitus- ja rahoitustoiminnan liiketoiminnan kulut",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Sijoitus- ja rahoitustoiminnan liiketoiminnan kulut\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Sijoitus- ja rahoitustoiminta"
          },
          {
            "name": "Muut sijoitus- ja rahoitustoiminnan kulut",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Muut sijoitus- ja rahoitustoiminnan kulut\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Sijoitus- ja rahoitustoiminta"
          },
          {
            "name": "Vähemmistöosuus yliopistokonserni",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso1_fi] = \"Sijoitus- ja rahoitustoiminta\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Vähemmistö osuus\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopistokonserni\\Sijoitus- ja rahoitustoiminta"
          },
          {
            "name": "Tuotto-/kulujäämä (sijoitus- ja rahoitustoiminta)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Tuotto-/ kulujäämä (sijoitus- ja rahoitustoiminta)\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Sijoitus- ja rahoitustoiminta"
          },
          {
            "name": "Yliopistolain mukainen valtionrahoitus (OKM)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Yliopistolain mukainen valtionrahoitus\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Yleisavustukset"
          },
          {
            "name": "Muut yleisavustukset",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Muut yleisavustukset\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Yleisavustukset"
          },
          {
            "name": "Omakatteisten rahastojen muutos",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Omakatteisten rahastojen muutos\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Omakatteisten rahastojen muutos"
          },
          {
            "name": "Tilikauden tulos",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Tilikauden tulos\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Tilikauden tulos"
          },
          {
            "name": "Poistoeron muutos",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Poistoeron muutos\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Tilinpäätössiirrot"
          },
          {
            "name": "Sidottujen rahastojen muutos",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Sidottujen rahastojen muutos\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Tilinpäätössiirrot"
          },
          {
            "name": "Tilikauden ylijäämä/alijäämä",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Tilikauden ylijäämä/alijäämä\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Tilikauden ylijäämä/alijäämä"
          },
          {
            "name": "Varsinaiseen toimintaan kuuluvan liiketoiminnan tuotot, ulkomaat",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Vars. toiminnan liiketoiminta\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\OKM:n tarkentavat tiedot\\Ulkomailta saadut tuotot"
          },
          {
            "name": "Muut varsinaisen toiminnan tuotot, ulkomaat",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Vars. toiminnan muut tuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\OKM:n tarkentavat tiedot\\Ulkomailta saadut tuotot"
          },
          {
            "name": "Yliopiston ALV-kulut yhteensä pl liiketoiminta",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Yliopiston alv-kulut yhteensä (pl. liiketoiminta)\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\OKM:n tarkentavat tiedot\\Arvonlisäverot"
          },
          {
            "name": "OKM kompensoitava ALV",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"OKM:n kompensoitava alv\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\OKM:n tarkentavat tiedot\\Arvonlisäverot"
          },
          {
            "name": "Harjoittelujen kotikuntakorvauksiin sisältyvä ALV",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Harj.koulujen kotikuntakorvauksiin sisältyvä alv\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\OKM:n tarkentavat tiedot\\Arvonlisäverot"
          },
          {
            "name": "Muiden rajoittajien kompensoimat ALV",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Muiden rahoittajien kompensoimat alv\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\OKM:n tarkentavat tiedot\\Arvonlisäverot"
          },
          {
            "name": "VM rahoitus harjoittelukouluille",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"VM:n rahoitus harjoittelukouluille\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\OKM:n tarkentavat tiedot\\Harjoittelukoulujen rahoitus"
          },
          {
            "name": "OKM rahoitus harjoittelukouluille",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"OKM:n rahoitus harjoittelukouluille\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\OKM:n tarkentavat tiedot\\Harjoittelukoulujen rahoitus"
          },
          {
            "name": "Harjoittelukoulun liiketoiminnan kulut",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Harjoittelukoulun liiketoiminnan kulut\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\OKM:n tarkentavat tiedot\\Harjoittelukoulujen rahoitus"
          },
          {
            "name": "Yliopistolle korvattu apteekkimaksu",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Yliopistolle korvattu apteekkimaksu\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\OKM:n tarkentavat tiedot\\Apteekkikompensaatiot"
          },
          {
            "name": "Yliopistolle kompensoitava apteekkivero",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Yliopistolle kompensoitava apteekkivero\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\OKM:n tarkentavat tiedot\\Apteekkikompensaatiot"
          },
          {
            "name": "Konserniliikearvo yliopistokonserni",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Konserni-liikearvo\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopistokonserni\\Vastaavaa\\PYSYVÄT VASTAAVAT\\Aineettomat hyödykkeet"
          },
          {
            "name": "Toimintapääoma",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"Toimintapääoma\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastattavaa\\OMA PÄÄOMA\\Muu oma pääoma"
          },
          {
            "name": "Vähemmistöosuudet",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"Vähemmistöosuudet\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastattavaa"
          },
          {
            "name": "Konsernireservi yliopistokonserni",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Konsernireservi\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopistokonserni\\Vastattavaa\\TILINPÄÄTÖSSIIRTYMÄT JA PAKOLLISET VARAUKSET"
          },
          {
            "name": "Omakatteisten rahastojen velat",
            "expression": "CALCULATE(SUM([arvo]), FILTER(Muuttujat,[tili_taso5_fi]=\"Omakatteisten rahastojen velat\"))",
            "formatString": "#,0",
            "displayFolder": "Tase - yliopisto\\Vastattavaa\\VIERAS PÄÄOMA"
          },
          {
            "name": "Varsinaisen toiminnan kustannukset harjoittelukoulut ja kansalliskirjasto yhteensä",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso1_fi]=\"Harjoittelukoulu\"),[arvo])+SUMX(FILTER(Muuttujat,[tili_taso1_fi]=\"Kansalliskirjasto\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Varsinaisen toiminnan kustannukset"
          },
          {
            "name": "Taiteellinen toiminta",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Taiteellinen toiminta\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Varsinaisen toiminnan kustannukset\\Taiteellinen toiminta"
          },
          {
            "name": "Erillislakien mukaiset julkisoikeudelliset suoritteet",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Erillislakien mukaiset julkisoikeudelliset suoritteet\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Varsinaisen toiminnan kustannukset\\Muu yhteiskunnallinen toiminta yhteensä"
          },
          {
            "name": "Yleistoiminnot",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Yleistoiminnot\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Varsinaisen toiminnan kustannukset\\Muu yhteiskunnallinen toiminta yhteensä"
          },
          {
            "name": "Harjoittelukoulu yhteensä",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso1_fi]=\"Harjoittelukoulu\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Varsinaisen toiminnan kustannukset\\Harjoittelukoulut"
          },
          {
            "name": "Opetustehtävät yhteensä",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso2_fi]=\"Opetustehtävät\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Varsinaisen toiminnan kustannukset\\Harjoittelukoulut\\Opetustehtävät"
          },
          {
            "name": "Esiopetus",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Esiopetus\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Varsinaisen toiminnan kustannukset\\Harjoittelukoulut\\Opetustehtävät"
          },
          {
            "name": "Perusopetus",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Perusopetus\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Varsinaisen toiminnan kustannukset\\Harjoittelukoulut\\Opetustehtävät"
          },
          {
            "name": "Lukiokoulutus",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Lukiokoulutus\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Varsinaisen toiminnan kustannukset\\Harjoittelukoulut\\Opetustehtävät"
          },
          {
            "name": "Opettajankoulutus- ja kehitystehtävät yhteensä",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso2_fi]=\"Opettajankoulutus ja kehitystehtävät\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Varsinaisen toiminnan kustannukset\\Harjoittelukoulut\\Opettajankoulutus ja kehitystehtävät"
          },
          {
            "name": "Harjoittelu harjoittelukoulussa",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Harjoittelu harjoittelukoulussa\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Varsinaisen toiminnan kustannukset\\Harjoittelukoulut\\Opettajankoulutus ja kehitystehtävät"
          },
          {
            "name": "Harjoittelu harjoittelukoulun ulkopuolella",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Harjoittelu harjoittelukoulun ulkopuolella\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Varsinaisen toiminnan kustannukset\\Harjoittelukoulut\\Opettajankoulutus ja kehitystehtävät"
          },
          {
            "name": "Opettajankoulutuksen kehittäminen",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Opettajankoulutuksen kehittäminen\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Varsinaisen toiminnan kustannukset\\Harjoittelukoulut\\Opettajankoulutus ja kehitystehtävät"
          },
          {
            "name": "Kansalliskirjasto yhteensä",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso1_fi]=\"Kansalliskirjasto\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Varsinaisen toiminnan kustannukset\\Kansalliskirjasto"
          },
          {
            "name": "Yliopistolain mukaiset kansalliskirjastotehtävät yhteensä",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Yliopistolain mukaiset kansalliskirjastotehtävät yhteensä\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Varsinaisen toiminnan kustannukset\\Kansalliskirjasto\\Yliopistolain mukaiset kansalliskirjastotehtävät"
          },
          {
            "name": "Kansallisen kulttuuriperinnön tallettaminen ja ylläpito",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Kansallisen kulttuuriperinnön tallettaminen ja ylläpito\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Varsinaisen toiminnan kustannukset\\Kansalliskirjasto\\Yliopistolain mukaiset kansalliskirjastotehtävät"
          },
          {
            "name": "Kansalliset palvelut kirjastoille sekä korkeakoulusektorille",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Kansalliset palvelut kirjastoille sekä korkeakoulusektorille\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Varsinaisen toiminnan kustannukset\\Kansalliskirjasto\\Yliopistolain mukaiset kansalliskirjastotehtävät"
          },
          {
            "name": "Muut tehtävät",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Muut tehtävät\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Varsinaisen toiminnan kustannukset\\Kansalliskirjasto\\Muut tehtävät"
          },
          {
            "name": "Varsinaisen toiminnan tuotot yhteensä",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Toiminnot yhteensä\"), FILTER('Muuttujat', [tili_taso1_fi] = \"Tuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Toiminnot yhteensä\\Tuotot"
          },
          {
            "name": "Varsinaisen toiminnan tuotot yhteensä (koulutus)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Koulutustoiminta\"), FILTER('Muuttujat', [tili_taso1_fi] = \"Tuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Koulutus\\Tuotot"
          },
          {
            "name": "Varsinaisen toiminnan tuotot yhteensä (tutkimus)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Tutkimustoiminta\"), FILTER('Muuttujat', [tili_taso1_fi] = \"Tuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Tutkimus\\Tuotot"
          },
          {
            "name": "Varsinaisen toiminnan tuotot yhteensä (taiteellinen toiminta)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Taiteellinen toiminta\"), FILTER('Muuttujat', [tili_taso1_fi] = \"Tuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Taiteellinen toiminta\\Tuotot"
          },
          {
            "name": "Varsinaisen toiminnan tuotot yhteensä (muu yhteiskunnallinen toiminta)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Muu yhteiskunnallinen toiminta\"), FILTER('Muuttujat', [tili_taso1_fi] = \"Tuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Muu yhteiskunnallinen toiminta\\Tuotot"
          },
          {
            "name": "Varsinaisen toiminnan tuotot yhteensä (harjoittelukoulut)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Harjoittelukoulu\"), FILTER('Muuttujat', [tili_taso1_fi] = \"Tuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Harjoittelukoulut\\Tuotot"
          },
          {
            "name": "Varsinaisen liiketoiminnan tuotot yhteensä (kansalliskirjasto)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Kansalliskirjasto\"), FILTER('Muuttujat', [tili_taso1_fi] = \"Tuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Kansalliskirjasto\\Tuotot"
          },
          {
            "name": "Avustustuotot (toiminnot yhteensä)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Toiminnot yhteensä\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Avustustuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Toiminnot yhteensä\\Tuotot"
          },
          {
            "name": "Avustustuotot (koulutus)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Koulutustoiminta\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Avustustuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Koulutus\\Tuotot"
          },
          {
            "name": "Avustustuotot (tutkimus)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Tutkimustoiminta\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Avustustuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Tutkimus\\Tuotot"
          },
          {
            "name": "Avustustuotot (taiteellinen toiminta)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Taiteellinen toiminta\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Avustustuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Taiteellinen toiminta\\Tuotot"
          },
          {
            "name": "Avustustuotot (muu yhteiskunnallinen toiminta)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Muu yhteiskunnallinen toiminta\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Avustustuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Muu yhteiskunnallinen toiminta\\Tuotot"
          },
          {
            "name": "Avustustuotot (harjoittelukoulut)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Harjoittelukoulu\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Avustustuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Harjoittelukoulut\\Tuotot"
          },
          {
            "name": "Avustustuotot (kansalliskirjasto)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Kansalliskirjasto\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Avustustuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Kansalliskirjasto\\Tuotot"
          },
          {
            "name": "Liiketoiminnan tuotot (toiminnot yhteensä)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Toiminnot yhteensä\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Liiketoiminnan tuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Toiminnot yhteensä\\Tuotot"
          },
          {
            "name": "Liiketoiminnan tuotot (koulutus)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Koulutustoiminta\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Liiketoiminnan tuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Koulutus\\Tuotot"
          },
          {
            "name": "Liiketoiminnan tuotot (tutkimus)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Tutkimustoiminta\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Liiketoiminnan tuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Tutkimus\\Tuotot"
          },
          {
            "name": "Liiketoiminnan tuotot (taiteellinen toiminta)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Taiteellinen toiminta\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Liiketoiminnan tuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Taiteellinen toiminta\\Tuotot"
          },
          {
            "name": "Liiketoiminnan tuotot (muu yhteiskunnallinen toiminta)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Muu yhteiskunnallinen toiminta\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Liiketoiminnan tuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Muu yhteiskunnallinen toiminta\\Tuotot"
          },
          {
            "name": "Liiketoiminnan tuotot (harjoittelukoulut)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Harjoittelukoulu\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Liiketoiminnan tuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Harjoittelukoulut\\Tuotot"
          },
          {
            "name": "Liiketoiminnan tuotot (kansalliskirjasto)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Kansalliskirjasto\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Liiketoiminnan tuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Kansalliskirjasto\\Tuotot"
          },
          {
            "name": "Muut tuotot (toiminnot yhteensä)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Toiminnot yhteensä\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Muut tuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Toiminnot yhteensä\\Tuotot"
          },
          {
            "name": "Muut tuotot (koulutus)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Koulutustoiminta\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Muut tuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Koulutus\\Tuotot"
          },
          {
            "name": "Muut tuotot (tutkimus)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Tutkimustoiminta\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Muut tuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Tutkimus\\Tuotot"
          },
          {
            "name": "Muut tuotot (taiteellinen toiminta)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Taiteellinen toiminta\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Muut tuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Taiteellinen toiminta\\Tuotot"
          },
          {
            "name": "Muut tuotot (muu yhteiskunnallinen toiminta)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Muu yhteiskunnallinen toiminta\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Muut tuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Muu yhteiskunnallinen toiminta\\Tuotot"
          },
          {
            "name": "Muut tuotot (harjoittelukoulut)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Harjoittelukoulu\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Muut tuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Harjoittelukoulut\\Tuotot"
          },
          {
            "name": "Muut tuotot (kansalliskirjasto)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Kansalliskirjasto\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Muut tuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Kansalliskirjasto\\Tuotot"
          },
          {
            "name": "Kulut yhteensä",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Toiminnot yhteensä\"), FILTER('Muuttujat', [tili_taso1_fi] = \"Kulut\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Toiminnot yhteensä\\Kulut"
          },
          {
            "name": "Kulut yhteensä (koulutus)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Koulutustoiminta\"), FILTER('Muuttujat', [tili_taso1_fi] = \"Kulut\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Koulutus\\Kulut"
          },
          {
            "name": "Kulut yhteensä (tutkimus)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Tutkimustoiminta\"), FILTER('Muuttujat', [tili_taso1_fi] = \"Kulut\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Tutkimus\\Kulut"
          },
          {
            "name": "Kulut yhteensä (taiteellinen toiminta)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Taiteellinen toiminta\"), FILTER('Muuttujat', [tili_taso1_fi] = \"Kulut\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Taiteellinen toiminta\\Kulut"
          },
          {
            "name": "Kulut yhteensä (muu yhteiskunnallinen toiminta)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Muu yhteiskunnallinen toiminta\"), FILTER('Muuttujat', [tili_taso1_fi] = \"Kulut\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Muu yhteiskunnallinen toiminta\\Kulut"
          },
          {
            "name": "Kulut yhteensä (harjoittelukoulut)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Harjoittelukoulu\"), FILTER('Muuttujat', [tili_taso1_fi] = \"Kulut\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Harjoittelukoulut\\Kulut"
          },
          {
            "name": "Kulut yhteensä (kansalliskirjasto)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Kansalliskirjasto\"), FILTER('Muuttujat', [tili_taso1_fi] = \"Kulut\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Kansalliskirjasto\\Kulut"
          },
          {
            "name": "Kulut yhteensä (yhteiskulut)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Yhteiskulut\"), FILTER('Muuttujat', [tili_taso1_fi] = \"Kulut\"),FILTER('Muuttujat',[tili_taso2_fi] = \"Kulut\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Yhteiskulut\\Kulut"
          },
          {
            "name": "Henkilöstökulut (toiminnot yhteensä)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Toiminnot yhteensä\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Henkilöstökulut\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Toiminnot yhteensä\\Kulut"
          },
          {
            "name": "Henkilöstökulut (koulutus)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Koulutustoiminta\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Henkilöstökulut\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Koulutus\\Kulut"
          },
          {
            "name": "Henkilöstökulut (tutkimus)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Tutkimustoiminta\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Henkilöstökulut\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Tutkimus\\Kulut"
          },
          {
            "name": "Henkilöstökulut (taiteellinen toiminta)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Taiteellinen toiminta\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Henkilöstökulut\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Taiteellinen toiminta\\Kulut"
          },
          {
            "name": "Henkilöstökulut (muu yhteiskunnallinen toiminta)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Muu yhteiskunnallinen toiminta\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Henkilöstökulut\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Muu yhteiskunnallinen toiminta\\Kulut"
          },
          {
            "name": "Henkilöstökulut (harjoittelukoulut)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Harjoittelukoulu\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Henkilöstökulut\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Harjoittelukoulut\\Kulut"
          },
          {
            "name": "Henkilöstökulut (kansalliskirjasto)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Kansalliskirjasto\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Henkilöstökulut\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Kansalliskirjasto\\Kulut"
          },
          {
            "name": "Henkilöstökulut (yhteiskulut)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Yhteiskulut\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Henkilöstökulut\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Yhteiskulut\\Kulut"
          },
          {
            "name": "Poistot (toiminnot yhteensä)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Toiminnot yhteensä\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Poistot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Toiminnot yhteensä\\Kulut"
          },
          {
            "name": "Poistot (koulutus)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Koulutustoiminta\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Poistot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Koulutus\\Kulut"
          },
          {
            "name": "Poistot (tutkimus)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Tutkimustoiminta\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Poistot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Tutkimus\\Kulut"
          },
          {
            "name": "Poistot (taiteellinen toiminta)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Taiteellinen toiminta\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Poistot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Taiteellinen toiminta\\Kulut"
          },
          {
            "name": "Poistot (muu yhteiskunnallinen toiminta)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Muu yhteiskunnallinen toiminta\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Poistot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Muu yhteiskunnallinen toiminta\\Kulut"
          },
          {
            "name": "Poistot (harjoittelukoulut)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Harjoittelukoulu\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Poistot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Harjoittelukoulut\\Kulut"
          },
          {
            "name": "Poistot (kansalliskirjasto)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Kansalliskirjasto\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Poistot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Kansalliskirjasto\\Kulut"
          },
          {
            "name": "Poistot (yhteiskulut)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Yhteiskulut\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Poistot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Yhteiskulut\\Kulut"
          },
          {
            "name": "Muut kulut (toiminnot yhteensä)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Toiminnot yhteensä\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Muut kulut\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Toiminnot yhteensä\\Kulut"
          },
          {
            "name": "Muut kulut (koulutus)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Koulutustoiminta\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Muut kulut\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Koulutus\\Kulut"
          },
          {
            "name": "Muut kulut (tutkimus)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Tutkimustoiminta\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Muut kulut\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Tutkimus\\Kulut"
          },
          {
            "name": "Muut kulut (taiteellinen toiminta)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Taiteellinen toiminta\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Muut kulut\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Taiteellinen toiminta\\Kulut"
          },
          {
            "name": "Muut kulut (muu yhteiskunnallinen toiminta)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Muu yhteiskunnallinen toiminta\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Muut kulut\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Muu yhteiskunnallinen toiminta\\Kulut"
          },
          {
            "name": "Muut kulut (harjoittelukoulut)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Harjoittelukoulu\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Muut kulut\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Harjoittelukoulut\\Kulut"
          },
          {
            "name": "Muut kulut (kansalliskirjasto)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Kansalliskirjasto\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Muut kulut\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Kansalliskirjasto\\Kulut"
          },
          {
            "name": "Muut kulut (yhteiskulut)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Yhteiskulut\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Muut kulut\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Yhteiskulut\\Kulut"
          },
          {
            "name": "Osuus yhteisistä kuluista (koulutus)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Koulutustoiminta\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Osuus yhteisistä kuluista\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Koulutus\\Kulut"
          },
          {
            "name": "Osuus yhteisistä kuluista (tutkimus)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Tutkimustoiminta\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Osuus yhteisistä kuluista\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Tutkimus\\Kulut"
          },
          {
            "name": "Osuus yhteisista kuluista (taiteellinen toiminta)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Taiteellinen toiminta\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Osuus yhteisistä kuluista\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Taiteellinen toiminta\\Kulut"
          },
          {
            "name": "Osuus yhteisistä kuluista (muu yhteiskunnallinen toiminta)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Muu yhteiskunnallinen toiminta\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Osuus yhteisistä kuluista\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Muu yhteiskunnallinen toiminta\\Kulut"
          },
          {
            "name": "Osuus yhteisista kuluista (harjoittelukoulut)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Harjoittelukoulu\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Osuus yhteisistä kuluista\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Harjoittelukoulut\\Kulut"
          },
          {
            "name": "Osuus yhteisista kuluista (kansalliskirjasto)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Kansalliskirjasto\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Osuus yhteisistä kuluista\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Kansalliskirjasto\\Kulut"
          },
          {
            "name": "Osuus yhteisistä kuluista (yhteiskulut)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [toiminto_nimi_fi] = \"Yhteiskulut\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Osuus yhteisistä kuluista\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Yhteiskulut\\Kulut"
          },
          {
            "name": "Varsinaisen toiminnan tuotot",
            "expression": "[Avustustuotot]+[Yliopiston varsinaiseen toimintaan kuuluvan liiketoiminnan tuotot]+[Muut varsinaisen toiminnan tuotot]",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Johdetut mittarit"
          },
          {
            "name": "Yliopiston kokonaisrahoitus",
            "expression": "[Varsinaisen toiminnan tuotot]+[Tuotto-/kulujäämä (varainhankinta)]+[Tuotto-/kulujäämä (sijoitus- ja rahoitustoiminta)]+[Yliopistolain mukainen valtionrahoitus (OKM)]+[Muut yleisavustukset]",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Johdetut mittarit"
          },
          {
            "name": "Maksuvalmius",
            "expression": "(CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tase\"), FILTER(Muuttujat,[tili_taso3_fi]=\"Lyhytaikaiset saamiset\"))+CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tase\"), FILTER(Muuttujat,[tili_taso3_fi]=\"Rahoitusarvopaperit\"))+[Rahat ja pankkisaamiset])/(CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tase\"), FILTER(Muuttujat,[tili_taso3_fi]=\"Lyhytaikainen vieras pääoma\"))-[Lyhytaikaiset saadut ennakot])",
            "formatString": "#,0.00",
            "displayFolder": "Tase - yliopisto\\Johdetut mittarit"
          },
          {
            "name": "Omavaraisuusaste",
            "expression": "[Oma pääoma yhteensä]/([Vastaavaa yhteensä]-[Lyhytaikaiset saadut ennakot])",
            "formatString": "#,0.0 %;-#,0.0 %;#,0.0 %",
            "displayFolder": "Tase - yliopisto\\Johdetut mittarit"
          },
          {
            "name": "Toimintapääoman suhde omaan pääomaan",
            "expression": "([Toimintapääoma]+[Edellisten tilikausien voitto (tappio) (+/-)]+[Tilikauden voitto (tappio) (+/-)])/[Oma pääoma yhteensä]",
            "formatString": "#,0.0 %;-#,0.0 %;#,0.0 %",
            "displayFolder": "Tase - yliopisto\\Johdetut mittarit"
          },
          {
            "name": "Liiketoiminnan nettotulos",
            "expression": "[Tilikauden voitto tai tappio]/[Liikevaihto(Tiedot liiketoiminnasta)]",
            "formatString": "#,0.00",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Johdetut mittarit"
          },
          {
            "name": "Tilikauden tuloksen osuus kokonaistuotosta",
            "expression": "[Tilikauden ylijäämä/alijäämä]/[Yliopiston kokonaisrahoitus]",
            "formatString": "#,0.0 %;-#,0.0 %;#,0.0 %",
            "displayFolder": "Tuloslaskelma - yliopisto\\Johdetut mittarit"
          },
          {
            "name": "Tilikauden tuloksen osuus kokonaistuotosta (uusi)",
            "expression": "[Tilikauden tulos]/[Yliopiston kokonaisrahoitus]",
            "formatString": "#,0.0 %;-#,0.0 %;#,0.0 %",
            "isHidden": true,
            "displayFolder": "Tuloslaskelma - yliopisto\\Johdetut mittarit"
          },
          {
            "name": "Tilikauden tuloksen osuus kokonaistuotoista ilman varainhankinta- ja sijoitustuottoja (uusi)",
            "expression": "([Tilikauden tulos]-[Tuotto-/kulujäämä (varainhankinta)]-[Tuotto-/kulujäämä (sijoitus- ja rahoitustoiminta)])/([Varsinaisen toiminnan tuotot]+[Yliopistolain mukainen valtionrahoitus (OKM)]+[Muut yleisavustukset])",
            "formatString": "#,0.0 %;-#,0.0 %;#,0.0 %",
            "isHidden": true,
            "displayFolder": "Tuloslaskelma - yliopisto\\Johdetut mittarit"
          },
          {
            "name": "Kotimaiset korkeakoulut",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Kotimaiset korkeakoulut\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot\\Kotimainen ulkopuolinen rahoitus"
          },
          {
            "name": "Tilikauden tuloksen osuus kokonaistuotoista ilman varainhankinta- ja sijoitustuottoja",
            "expression": "([Tilikauden ylijäämä/alijäämä]-[Tuotto-/kulujäämä (varainhankinta)]-[Tuotto-/kulujäämä (sijoitus- ja rahoitustoiminta)])/([Varsinaisen toiminnan tuotot]+[Yliopistolain mukainen valtionrahoitus (OKM)]+[Muut yleisavustukset])",
            "formatString": "#,0.0 %;-#,0.0 %;#,0.0 %",
            "displayFolder": "Tuloslaskelma - yliopisto\\Johdetut mittarit"
          },
          {
            "name": "Varsinaisen toiminnan kustannukset",
            "expression": " CALCULATE(SUM([arvo]),Muuttujat[tili_taso0_fi]=\"Varsinaisen toiminnan kustannukset\")",
            "formatString": "#,0"
          },
          {
            "name": "Konserni - Henkilöstökulut yhteensä",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso1_fi] = \"Varsinainen toiminta\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Konserni; Henkilöstökulut\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Varsinainen toiminta\\Varsinaisen toiminnan kulut\\Varsinaisen toiminnan kulut eriteltynä\\Henkilökulut"
          },
          {
            "name": "Konserni - Avustustuotot yhteensä",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso1_fi] = \"Varsinainen toiminta\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Konserni; Avustustuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Varsinainen toiminta\\Varsinaisen toiminnan tuotot\\Avustustuotot"
          },
          {
            "name": "Konserni - Lahjoitukset yhteensä",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso1_fi] = \"Varainhankinta\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Konserni; Lahjoitukset\"))",
            "formatString": "0",
            "displayFolder": "Tuloslaskelma - yliopisto\\Varainhankinta\\Lahjoitukset"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dw].[v_yo_talous].* FROM [dw].[v_yo_talous] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "v_yo_talous"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dw"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Koodit_aineisto</string>",
              "      </key>",
              "      <value>",
              "        <int>103</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit_koulutusala</string>",
              "      </key>",
              "      <value>",
              "        <int>120</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit_yliopisto</string>",
              "      </key>",
              "      <value>",
              "        <int>105</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Material type</string>",
              "      </key>",
              "      <value>",
              "        <int>93</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Utbildningsområde</string>",
              "      </key>",
              "      <value>",
              "        <int>118</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>University</string>",
              "      </key>",
              "      <value>",
              "        <int>78</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Statistical year</string>",
              "      </key>",
              "      <value>",
              "        <int>101</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Field of education</string>",
              "      </key>",
              "      <value>",
              "        <int>115</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Material typ</string>",
              "      </key>",
              "      <value>",
              "        <int>87</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Universitet</string>",
              "      </key>",
              "      <value>",
              "        <int>82</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>arvo</string>",
              "      </key>",
              "      <value>",
              "        <int>52</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso4_en</string>",
              "      </key>",
              "      <value>",
              "        <int>91</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso3_en</string>",
              "      </key>",
              "      <value>",
              "        <int>91</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso2_en</string>",
              "      </key>",
              "      <value>",
              "        <int>91</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso1_en</string>",
              "      </key>",
              "      <value>",
              "        <int>91</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso0_en</string>",
              "      </key>",
              "      <value>",
              "        <int>91</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso4_sv</string>",
              "      </key>",
              "      <value>",
              "        <int>90</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso3_sv</string>",
              "      </key>",
              "      <value>",
              "        <int>90</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso2_sv</string>",
              "      </key>",
              "      <value>",
              "        <int>90</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso1_sv</string>",
              "      </key>",
              "      <value>",
              "        <int>90</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso0_sv</string>",
              "      </key>",
              "      <value>",
              "        <int>90</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso4_fi</string>",
              "      </key>",
              "      <value>",
              "        <int>85</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso3_fi</string>",
              "      </key>",
              "      <value>",
              "        <int>85</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso2_fi</string>",
              "      </key>",
              "      <value>",
              "        <int>85</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso1_fi</string>",
              "      </key>",
              "      <value>",
              "        <int>85</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso0_fi</string>",
              "      </key>",
              "      <value>",
              "        <int>85</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Statistikår</string>",
              "      </key>",
              "      <value>",
              "        <int>78</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Aineisto</string>",
              "      </key>",
              "      <value>",
              "        <int>68</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusala</string>",
              "      </key>",
              "      <value>",
              "        <int>85</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Yliopisto</string>",
              "      </key>",
              "      <value>",
              "        <int>69</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>toiminto_nimi_fi</string>",
              "      </key>",
              "      <value>",
              "        <int>104</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tilastovuosi</string>",
              "      </key>",
              "      <value>",
              "        <int>86</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso5_fi</string>",
              "      </key>",
              "      <value>",
              "        <int>85</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso5_sv</string>",
              "      </key>",
              "      <value>",
              "        <int>90</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso5_en</string>",
              "      </key>",
              "      <value>",
              "        <int>91</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Konserni</string>",
              "      </key>",
              "      <value>",
              "        <int>71</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ohjauksenala</string>",
              "      </key>",
              "      <value>",
              "        <int>95</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ohjauksenala_sv</string>",
              "      </key>",
              "      <value>",
              "        <int>112</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ohjauksenala_en</string>",
              "      </key>",
              "      <value>",
              "        <int>113</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit_ohjauksenala</string>",
              "      </key>",
              "      <value>",
              "        <int>129</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Koodit_aineisto</string>",
              "      </key>",
              "      <value>",
              "        <int>31</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit_koulutusala</string>",
              "      </key>",
              "      <value>",
              "        <int>30</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit_yliopisto</string>",
              "      </key>",
              "      <value>",
              "        <int>29</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Material type</string>",
              "      </key>",
              "      <value>",
              "        <int>28</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Utbildningsområde</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>University</string>",
              "      </key>",
              "      <value>",
              "        <int>27</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Statistical year</string>",
              "      </key>",
              "      <value>",
              "        <int>26</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Field of education</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Material typ</string>",
              "      </key>",
              "      <value>",
              "        <int>25</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Universitet</string>",
              "      </key>",
              "      <value>",
              "        <int>24</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>arvo</string>",
              "      </key>",
              "      <value>",
              "        <int>17</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso4_en</string>",
              "      </key>",
              "      <value>",
              "        <int>16</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso3_en</string>",
              "      </key>",
              "      <value>",
              "        <int>15</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso2_en</string>",
              "      </key>",
              "      <value>",
              "        <int>14</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso1_en</string>",
              "      </key>",
              "      <value>",
              "        <int>13</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso0_en</string>",
              "      </key>",
              "      <value>",
              "        <int>12</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso4_sv</string>",
              "      </key>",
              "      <value>",
              "        <int>11</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso3_sv</string>",
              "      </key>",
              "      <value>",
              "        <int>10</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso2_sv</string>",
              "      </key>",
              "      <value>",
              "        <int>9</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso1_sv</string>",
              "      </key>",
              "      <value>",
              "        <int>8</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso0_sv</string>",
              "      </key>",
              "      <value>",
              "        <int>7</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso4_fi</string>",
              "      </key>",
              "      <value>",
              "        <int>6</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso3_fi</string>",
              "      </key>",
              "      <value>",
              "        <int>5</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso2_fi</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso1_fi</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso0_fi</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Statistikår</string>",
              "      </key>",
              "      <value>",
              "        <int>23</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Aineisto</string>",
              "      </key>",
              "      <value>",
              "        <int>22</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusala</string>",
              "      </key>",
              "      <value>",
              "        <int>21</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Yliopisto</string>",
              "      </key>",
              "      <value>",
              "        <int>20</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>toiminto_nimi_fi</string>",
              "      </key>",
              "      <value>",
              "        <int>18</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tilastovuosi</string>",
              "      </key>",
              "      <value>",
              "        <int>19</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso5_fi</string>",
              "      </key>",
              "      <value>",
              "        <int>32</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso5_sv</string>",
              "      </key>",
              "      <value>",
              "        <int>33</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso5_en</string>",
              "      </key>",
              "      <value>",
              "        <int>34</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Konserni</string>",
              "      </key>",
              "      <value>",
              "        <int>35</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ohjauksenala</string>",
              "      </key>",
              "      <value>",
              "        <int>36</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ohjauksenala_sv</string>",
              "      </key>",
              "      <value>",
              "        <int>37</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ohjauksenala_en</string>",
              "      </key>",
              "      <value>",
              "        <int>38</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit_ohjauksenala</string>",
              "      </key>",
              "      <value>",
              "        <int>39</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Statistical year</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>arvo</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso4_en</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso3_en</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso2_en</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso1_en</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso0_en</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso4_sv</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso3_sv</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso2_sv</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso1_sv</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso0_sv</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso4_fi</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso3_fi</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso2_fi</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso1_fi</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso0_fi</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Material typ</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Universitet</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Statistikår</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Aineisto</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>toiminto_nimi_fi</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusala</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Yliopisto</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tilastovuosi</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>University</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Material type</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit_yliopisto</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit_koulutusala</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit_aineisto</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso5_fi</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso5_sv</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso5_en</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ohjauksenala</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ohjauksenala_sv</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ohjauksenala_en</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit_ohjauksenala</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Sarakeleveys",
        "columns": [
          {
            "name": "Sarakeleveys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Sarakeleveys",
            "sourceProviderType": "Char",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "leveys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "leveys",
            "sourceProviderType": "Char",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Sarakeleveys",
            "dataView": "full",
            "source": {
              "query": " SELECT [dw].[Sarakeleveys].* FROM [dw].[Sarakeleveys] ",
              "dataSource": "ANTERO"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Sarakeleveys</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>94</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>leveys</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>61</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Sarakeleveys</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>leveys</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked />",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dw].[Sarakeleveys].* FROM [dw].[Sarakeleveys] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Sarakeleveys"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dw"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Sarakeleveys</string>",
              "      </key>",
              "      <value>",
              "        <int>94</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>leveys</string>",
              "      </key>",
              "      <value>",
              "        <int>61</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Sarakeleveys</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>leveys</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked />",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      }
    ],
    "perspectives": [
      {
        "name": "Tuloslaskelma yliopisto",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Yliopisto"
              },
              {
                "name": "Konserni"
              },
              {
                "name": "Suodatus tilastovuosi"
              }
            ],
            "measures": [
              {
                "name": "Tarvikkeet ja tavarat"
              },
              {
                "name": "Eläkemaksut"
              },
              {
                "name": "EU-rahoitus avustustuotot"
              },
              {
                "name": "Euroopan Unionin maat - muu rahoitus avustustuotot"
              },
              {
                "name": "Euroopan Unionin maat - yritysrahoitus avustustuotot"
              },
              {
                "name": "Henkilöstökulut yhteensä"
              },
              {
                "name": "Kotimaiset rahoituslaitokset avustustuotot"
              },
              {
                "name": "Kotimaiset yritykset avustustuotot"
              },
              {
                "name": "Kotitaloudet avustustuotot"
              },
              {
                "name": "Kunnat ja kuntayhtymät avustustuotot"
              },
              {
                "name": "Tuloverot (Liiketoiminta)"
              },
              {
                "name": "Muu julkinen hallinto avustustuotot"
              },
              {
                "name": "Muut henkilöstösivukulut"
              },
              {
                "name": "Muut ulkomaat - muu rahoitus avustustuotot"
              },
              {
                "name": "Muut ulkomaat - yritysrahoitus avustustuotot"
              },
              {
                "name": "Palvelujen ostot"
              },
              {
                "name": "Palkat ja palkkiot"
              },
              {
                "name": "Satunnaiset kulut"
              },
              {
                "name": "Satunnaiset tuotot"
              },
              {
                "name": "Suomen Akatemia avustustuotot"
              },
              {
                "name": "Poistot (vt)"
              },
              {
                "name": "Business Finland avustustuotot"
              },
              {
                "name": "Yliopiston varsinaiseen toimintaan kuuluvan liiketoiminnan tuotot"
              },
              {
                "name": "Voittoa tavoittelemattomat yhteisöt avustustuotot"
              },
              {
                "name": "Valtio pl SA Business Finland ja OKMn yliopistolain muk. rahoitus avustustuotot"
              },
              {
                "name": "Arvonalennukset"
              },
              {
                "name": "Arvonalennusten palautukset"
              },
              {
                "name": "Harjoittelujen kotikuntakorvauksiin sisältyvä ALV"
              },
              {
                "name": "Harjoittelukoulun liiketoiminnan kulut"
              },
              {
                "name": "Keräysten tuotot"
              },
              {
                "name": "Keräystoiminnan kulut"
              },
              {
                "name": "Kone- ja laitevuokrat"
              },
              {
                "name": "Korkokulut"
              },
              {
                "name": "Korkotuotot"
              },
              {
                "name": "Lahjoitukset kotitalouksilta"
              },
              {
                "name": "Lahjoitukset yhteensä"
              },
              {
                "name": "Lahjoitukset yrityksiltä"
              },
              {
                "name": "Lahjoituksiin ja testamenttien hoitoon liittyvät kulut"
              },
              {
                "name": "Muiden rajoittajien kompensoimat ALV"
              },
              {
                "name": "Muut lahjoitukset"
              },
              {
                "name": "Muut sijoitus- ja rahoitustoiminnan kulut"
              },
              {
                "name": "Muut sijoitus- ja rahoitustoiminnan tuotot"
              },
              {
                "name": "Muut tilakustannukset"
              },
              {
                "name": "Muut varainhankinnan kulut"
              },
              {
                "name": "Muut varainhankinnan tuotot"
              },
              {
                "name": "Muut varsinaisen toiminnan kulut"
              },
              {
                "name": "Muut varsinaisen toiminnan tuotot"
              },
              {
                "name": "Muut yleisavustukset"
              },
              {
                "name": "Myyntitappiot"
              },
              {
                "name": "Myyntivoitot"
              },
              {
                "name": "OKM kompensoitava ALV"
              },
              {
                "name": "OKM rahoitus harjoittelukouluille"
              },
              {
                "name": "Omakatteisten rahastojen muutos"
              },
              {
                "name": "Osinkotuotot"
              },
              {
                "name": "Poistoeron muutos"
              },
              {
                "name": "Sidottujen rahastojen muutos"
              },
              {
                "name": "Sijoitus- ja rahoitustoiminnan liiketoiminnan kulut"
              },
              {
                "name": "Sijoitus- ja rahoitustoiminnan liiketoiminnan tuotot"
              },
              {
                "name": "Tilikauden tulos"
              },
              {
                "name": "Tilikauden ylijäämä/alijäämä"
              },
              {
                "name": "Tuotto-/kulujäämä (sijoitus- ja rahoitustoiminta)"
              },
              {
                "name": "Tuotto-/kulujäämä (varainhankinta)"
              },
              {
                "name": "Varainhankinnan liiketoiminnan kulut"
              },
              {
                "name": "Varainhankinnan liiketoiminnan tuotot"
              },
              {
                "name": "Vars. toim. kuluista liiketoiminnan kulut"
              },
              {
                "name": "Varsinaiseen toimintaan kuuluvan liiketoiminnan tuotot, ulkomaat"
              },
              {
                "name": "Muut varsinaisen toiminnan tuotot, ulkomaat"
              },
              {
                "name": "VM rahoitus harjoittelukouluille"
              },
              {
                "name": "Vuokratuotot"
              },
              {
                "name": "Yhtiövastikkeet"
              },
              {
                "name": "Yliopistolain mukainen valtionrahoitus (OKM)"
              },
              {
                "name": "Yliopistolle kompensoitava apteekkivero"
              },
              {
                "name": "Yliopistolle korvattu apteekkimaksu"
              },
              {
                "name": "Yliopiston ALV-kulut yhteensä pl liiketoiminta"
              },
              {
                "name": "Vuokrakulut"
              },
              {
                "name": "Varsinaisen toiminnan kulut yhteensä"
              },
              {
                "name": "Varsinaisen toiminnan tuotto-kulujäämä"
              },
              {
                "name": "Avustustuotot"
              },
              {
                "name": "Varsinaisen toiminnan tuotot"
              },
              {
                "name": "Yliopiston kokonaisrahoitus"
              },
              {
                "name": "Tilikauden tuloksen osuus kokonaistuotosta"
              },
              {
                "name": "Tilikauden tuloksen osuus kokonaistuotosta (uusi)"
              },
              {
                "name": "Tilikauden tuloksen osuus kokonaistuotoista ilman varainhankinta- ja sijoitustuottoja (uusi)"
              },
              {
                "name": "Tilikauden tuloksen osuus kokonaistuotoista ilman varainhankinta- ja sijoitustuottoja"
              },
              {
                "name": "Konserni - Avustustuotot yhteensä"
              },
              {
                "name": "Konserni - Henkilöstökulut yhteensä"
              },
              {
                "name": "Konserni - Lahjoitukset yhteensä"
              },
              {
                "name": "Konserni - osuus osakkuusyhtiöiden tuloksesta yliopistokonserni"
              },
              {
                "name": "Konserni - osuus osakkuusyhtiöiden voitosta-tappiosta yliopistokonserni"
              },
              {
                "name": "Konserni - vähemmistöosuus yliopistokonserni"
              },
              {
                "name": "Konserni- osuus osakkuusyhtiöiden tuloksesta yliopistokonserni"
              },
              {
                "name": "Konserniliikearvo yliopistokonserni"
              },
              {
                "name": "Konsernireservi yliopistokonserni"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Tuloslaskelma yliopisto 1",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Yliopisto"
              },
              {
                "name": "Konserni"
              },
              {
                "name": "Suodatus tilastovuosi"
              }
            ],
            "measures": [
              {
                "name": "Aineet ja tarvikkeet"
              },
              {
                "name": "Aineettomat oikeudet"
              },
              {
                "name": "Arvonkorotusrahasto"
              },
              {
                "name": "Edellisten tilikausien voitto (tappio) (+/-)"
              },
              {
                "name": "Eläkevaraukset"
              },
              {
                "name": "Ennakkomaksut"
              },
              {
                "name": "Ennakkomaksut ja keskeneräiset hankinnat"
              },
              {
                "name": "Kehittämismenot"
              },
              {
                "name": "Keskeneräiset tuotteet"
              },
              {
                "name": "Koneet ja kalusto"
              },
              {
                "name": "Käyvän arvon rahasto"
              },
              {
                "name": "Liikearvo"
              },
              {
                "name": "Lyhytaikaiset eläkelainat"
              },
              {
                "name": "Lyhytaikaiset joukkovelkakirjalainat"
              },
              {
                "name": "Lyhytaikaiset lainasaamiset"
              },
              {
                "name": "Lyhytaikaiset lainat rahoituslaitoksilta"
              },
              {
                "name": "Lyhytaikaiset laskennalliset verosaamiset"
              },
              {
                "name": "Lyhytaikaiset laskennalliset verovelat"
              },
              {
                "name": "Lyhytaikaiset muut saamiset"
              },
              {
                "name": "Lyhytaikaiset muut velat"
              },
              {
                "name": "Lyhytaikaiset myyntisaamiset"
              },
              {
                "name": "Lyhytaikaiset ostovelat"
              },
              {
                "name": "Lyhytaikaiset pääomalainat"
              },
              {
                "name": "Lyhytaikaiset rahoitusvekselit"
              },
              {
                "name": "Lyhytaikaiset saadut ennakot"
              },
              {
                "name": "Lyhytaikaiset saamiset omistusyhteysyrityksiltä"
              },
              {
                "name": "Lyhytaikaiset saamiset saman konsernin yrityksiltä"
              },
              {
                "name": "Lyhytaikaiset siirtosaamiset"
              },
              {
                "name": "Lyhytaikaiset siirtovelat"
              },
              {
                "name": "Lyhytaikaiset vaihtovelkakirjalainat"
              },
              {
                "name": "Lyhytaikaiset velat omistusyhteysyrityksille"
              },
              {
                "name": "Lyhytaikaiset velat saman konsernin yrityksille"
              },
              {
                "name": "Maa- ja vesialueet"
              },
              {
                "name": "Muu vaihto-omaisuus"
              },
              {
                "name": "Muut - arvopaperit"
              },
              {
                "name": "Muut - osakkeet ja osuudet"
              },
              {
                "name": "Muut aineelliset hyödykkeet"
              },
              {
                "name": "Muut arvopaperit"
              },
              {
                "name": "Muut osakkeet ja osuudet"
              },
              {
                "name": "Muut osakkeet ja osuudet (Rahoitusarvopaperit)"
              },
              {
                "name": "Muut pakolliset varaukset"
              },
              {
                "name": "Muut pitkävaikutteiset menot"
              },
              {
                "name": "Muut saamiset"
              },
              {
                "name": "Muut sidotut rahastot"
              },
              {
                "name": "Muut varat"
              },
              {
                "name": "Oma pääoma yhteensä"
              },
              {
                "name": "Omakatteiset rahastot"
              },
              {
                "name": "Omakatteisten rahastojen sijoitukset yhteensä"
              },
              {
                "name": "Omakatteisten rahastojen varat"
              },
              {
                "name": "Peruspääoma"
              },
              {
                "name": "Osuudet omistusyhteysyrityksissä"
              },
              {
                "name": "Osuudet saman konsernin yrityksissä"
              },
              {
                "name": "Osuudet saman konsernin yrityksissä (Rahoitusarvopaperit)"
              },
              {
                "name": "Pitkäaikaiset eläkelainat"
              },
              {
                "name": "Pitkäaikaiset joukkovelkakirjalainat"
              },
              {
                "name": "Pitkäaikaiset lainasaamiset"
              },
              {
                "name": "Pitkäaikaiset lainat rahoituslaitoksilta"
              },
              {
                "name": "Pitkäaikaiset laskennalliset verosaamiset"
              },
              {
                "name": "Pitkäaikaiset laskennalliset verovelat"
              },
              {
                "name": "Pitkäaikaiset muut saamiset"
              },
              {
                "name": "Pitkäaikaiset muut velat"
              },
              {
                "name": "Pitkäaikaiset myyntisaamiset"
              },
              {
                "name": "Pitkäaikaiset ostovelat"
              },
              {
                "name": "Pitkäaikaiset pääomalainat"
              },
              {
                "name": "Pitkäaikaiset rahoitusvekselit"
              },
              {
                "name": "Pitkäaikaiset saadut ennakot"
              },
              {
                "name": "Pitkäaikaiset saamiset omistusyhteysyrityksiltä"
              },
              {
                "name": "Pitkäaikaiset saamiset saman konsernin yrityksiltä"
              },
              {
                "name": "Pitkäaikaiset siirtosaamiset"
              },
              {
                "name": "Pitkäaikaiset siirtovelat"
              },
              {
                "name": "Pitkäaikaiset vaihtovelkakirjalainat"
              },
              {
                "name": "Pitkäaikaiset velat omistusyhteysyrityksille"
              },
              {
                "name": "Pitkäaikaiset velat saman konsernin yrityksille"
              },
              {
                "name": "Rahasto-osuudet"
              },
              {
                "name": "Rahat ja pankkisaamiset"
              },
              {
                "name": "Rahat ja pankkisaamiset (Omakatteisten rahastojen varat)"
              },
              {
                "name": "Rakennukset ja rakennelmat"
              },
              {
                "name": "Vapaat rahastot"
              },
              {
                "name": "Saamiset omistusyhteysyrityksiltä"
              },
              {
                "name": "Saamiset saman konsernin yrityksiltä"
              },
              {
                "name": "Tilikauden voitto (tappio) (+/-)"
              },
              {
                "name": "Tilinpäätössiirtojen kertymä (Poistoero)"
              },
              {
                "name": "Ennakkomaksut (vaihto-omaisuus)"
              },
              {
                "name": "Valmiit tuotteet/tavarat"
              },
              {
                "name": "Vastaavaa yhteensä"
              },
              {
                "name": "Vastattavaa yhteensä"
              },
              {
                "name": "Verovaraukset"
              },
              {
                "name": "Toimintapääoma"
              },
              {
                "name": "Omakatteisten rahastojen velat"
              },
              {
                "name": "Maksuvalmius"
              },
              {
                "name": "Omavaraisuusaste"
              },
              {
                "name": "Toimintapääoman suhde omaan pääomaan"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Toimintokohtainen erittely",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Yliopisto"
              },
              {
                "name": "Suodatus tilastovuosi"
              }
            ],
            "measures": [
              {
                "name": "Avustustuotot (harjoittelukoulut)"
              },
              {
                "name": "Avustustuotot (kansalliskirjasto)"
              },
              {
                "name": "Avustustuotot (koulutus)"
              },
              {
                "name": "Avustustuotot (muu yhteiskunnallinen toiminta)"
              },
              {
                "name": "Avustustuotot (taiteellinen toiminta)"
              },
              {
                "name": "Avustustuotot (toiminnot yhteensä)"
              },
              {
                "name": "Avustustuotot (tutkimus)"
              },
              {
                "name": "Henkilöstökulut (harjoittelukoulut)"
              },
              {
                "name": "Henkilöstökulut (kansalliskirjasto)"
              },
              {
                "name": "Henkilöstökulut (koulutus)"
              },
              {
                "name": "Henkilöstökulut (muu yhteiskunnallinen toiminta)"
              },
              {
                "name": "Henkilöstökulut (taiteellinen toiminta)"
              },
              {
                "name": "Henkilöstökulut (toiminnot yhteensä)"
              },
              {
                "name": "Henkilöstökulut (tutkimus)"
              },
              {
                "name": "Henkilöstökulut (yhteiskulut)"
              },
              {
                "name": "Kulut yhteensä"
              },
              {
                "name": "Kulut yhteensä (harjoittelukoulut)"
              },
              {
                "name": "Kulut yhteensä (kansalliskirjasto)"
              },
              {
                "name": "Kulut yhteensä (koulutus)"
              },
              {
                "name": "Kulut yhteensä (muu yhteiskunnallinen toiminta)"
              },
              {
                "name": "Kulut yhteensä (taiteellinen toiminta)"
              },
              {
                "name": "Kulut yhteensä (tutkimus)"
              },
              {
                "name": "Kulut yhteensä (yhteiskulut)"
              },
              {
                "name": "Liiketoiminnan tuotot (harjoittelukoulut)"
              },
              {
                "name": "Liiketoiminnan tuotot (kansalliskirjasto)"
              },
              {
                "name": "Liiketoiminnan tuotot (koulutus)"
              },
              {
                "name": "Liiketoiminnan tuotot (muu yhteiskunnallinen toiminta)"
              },
              {
                "name": "Liiketoiminnan tuotot (taiteellinen toiminta)"
              },
              {
                "name": "Liiketoiminnan tuotot (toiminnot yhteensä)"
              },
              {
                "name": "Liiketoiminnan tuotot (tutkimus)"
              },
              {
                "name": "Muut kulut (harjoittelukoulut)"
              },
              {
                "name": "Muut kulut (kansalliskirjasto)"
              },
              {
                "name": "Muut kulut (koulutus)"
              },
              {
                "name": "Muut kulut (muu yhteiskunnallinen toiminta)"
              },
              {
                "name": "Muut kulut (taiteellinen toiminta)"
              },
              {
                "name": "Muut kulut (toiminnot yhteensä)"
              },
              {
                "name": "Muut kulut (tutkimus)"
              },
              {
                "name": "Muut kulut (yhteiskulut)"
              },
              {
                "name": "Muut tuotot (harjoittelukoulut)"
              },
              {
                "name": "Muut tuotot (kansalliskirjasto)"
              },
              {
                "name": "Muut tuotot (koulutus)"
              },
              {
                "name": "Muut tuotot (muu yhteiskunnallinen toiminta)"
              },
              {
                "name": "Muut tuotot (taiteellinen toiminta)"
              },
              {
                "name": "Muut tuotot (toiminnot yhteensä)"
              },
              {
                "name": "Muut tuotot (tutkimus)"
              },
              {
                "name": "Osuus yhteisista kuluista (harjoittelukoulut)"
              },
              {
                "name": "Osuus yhteisista kuluista (kansalliskirjasto)"
              },
              {
                "name": "Osuus yhteisista kuluista (taiteellinen toiminta)"
              },
              {
                "name": "Osuus yhteisistä kuluista (koulutus)"
              },
              {
                "name": "Osuus yhteisistä kuluista (muu yhteiskunnallinen toiminta)"
              },
              {
                "name": "Osuus yhteisistä kuluista (tutkimus)"
              },
              {
                "name": "Osuus yhteisistä kuluista (yhteiskulut)"
              },
              {
                "name": "Poistot (harjoittelukoulut)"
              },
              {
                "name": "Poistot (kansalliskirjasto)"
              },
              {
                "name": "Poistot (koulutus)"
              },
              {
                "name": "Poistot (muu yhteiskunnallinen toiminta)"
              },
              {
                "name": "Poistot (taiteellinen toiminta)"
              },
              {
                "name": "Poistot (toiminnot yhteensä)"
              },
              {
                "name": "Poistot (tutkimus)"
              },
              {
                "name": "Poistot (yhteiskulut)"
              },
              {
                "name": "Varsinaisen toiminnan tuotot yhteensä"
              },
              {
                "name": "Varsinaisen toiminnan tuotot yhteensä (harjoittelukoulut)"
              },
              {
                "name": "Varsinaisen liiketoiminnan tuotot yhteensä (kansalliskirjasto)"
              },
              {
                "name": "Varsinaisen toiminnan tuotot yhteensä (koulutus)"
              },
              {
                "name": "Varsinaisen toiminnan tuotot yhteensä (muu yhteiskunnallinen toiminta)"
              },
              {
                "name": "Varsinaisen toiminnan tuotot yhteensä (taiteellinen toiminta)"
              },
              {
                "name": "Varsinaisen toiminnan tuotot yhteensä (tutkimus)"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Tutkimusrahoitus",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Yliopisto"
              },
              {
                "name": "Koulutusala"
              },
              {
                "name": "Ohjauksen ala"
              },
              {
                "name": "Suodatus tilastovuosi"
              }
            ],
            "measures": [
              {
                "name": "Yliopiston oma rahoitus yhteensä"
              },
              {
                "name": "EAKR-rahoitus"
              },
              {
                "name": "ESR-rahoitus"
              },
              {
                "name": "Kansainväliset järjestöt"
              },
              {
                "name": "Kotimaiset yksityiset rahastot ja säätiöt"
              },
              {
                "name": "Kotimaiset yritykset"
              },
              {
                "name": "Kunnat ja kuntainliitot"
              },
              {
                "name": "Liikenne- ja viestintäministeriö"
              },
              {
                "name": "Maa- ja metsätalousministeriö"
              },
              {
                "name": "Muu EU-rahoitus"
              },
              {
                "name": "Muu julkinen rahoitus"
              },
              {
                "name": "Opetus- ja kulttuuriministeriö"
              },
              {
                "name": "Työ- ja elinkeinoministeriö"
              },
              {
                "name": "Muu ulkomainen rahoitus"
              },
              {
                "name": "Oikeusministeriö"
              },
              {
                "name": "Puolustusministeriö"
              },
              {
                "name": "Sisäasiainministeriö"
              },
              {
                "name": "Suomen Akatemia"
              },
              {
                "name": "EU-puiteohjelmarahoitus ja muu laadullisesti kilpailtu EU-rahoitus"
              },
              {
                "name": "Business Finland"
              },
              {
                "name": "Ulkoasiainministeriö"
              },
              {
                "name": "Ulkomaiset yritykset"
              },
              {
                "name": "Ulkomaiset rahastot ja säätiöt"
              },
              {
                "name": "Valtiovarainministeriö"
              },
              {
                "name": "Ympäristöministeriö"
              },
              {
                "name": "Tutkimusmenot yhteensä"
              },
              {
                "name": "Ministeriöt yhteensä"
              },
              {
                "name": "Ulkopuolinen rahoitus yhteensä"
              },
              {
                "name": "Sosiaali- ja terveysministeriö"
              },
              {
                "name": "Kotimaiset korkeakoulut"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Varsinaisen toiminnan kustannukset",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Yliopisto"
              },
              {
                "name": "Koulutusala"
              },
              {
                "name": "Ohjauksen ala"
              },
              {
                "name": "Suodatus tilastovuosi"
              },
              {
                "name": "Koodit_aineisto"
              }
            ],
            "measures": [
              {
                "name": "Yliopiston varsinaisen toiminnan kustannukset yhteensä"
              },
              {
                "name": "Koulutus yhteensä"
              },
              {
                "name": "Muu koulutus"
              },
              {
                "name": "Muu yhteiskunnallinen toiminta yhteensä"
              },
              {
                "name": "Perustutkintojen osat"
              },
              {
                "name": "Tutkimus yhteensä"
              },
              {
                "name": "Perustutkintokoulutus"
              },
              {
                "name": "Erillislakien mukaiset julkisoikeudelliset suoritteet"
              },
              {
                "name": "Esiopetus"
              },
              {
                "name": "Harjoittelu harjoittelukoulun ulkopuolella"
              },
              {
                "name": "Harjoittelu harjoittelukoulussa"
              },
              {
                "name": "Harjoittelukoulu yhteensä"
              },
              {
                "name": "Kansallisen kulttuuriperinnön tallettaminen ja ylläpito"
              },
              {
                "name": "Kansalliset palvelut kirjastoille sekä korkeakoulusektorille"
              },
              {
                "name": "Kansalliskirjasto yhteensä"
              },
              {
                "name": "Lukiokoulutus"
              },
              {
                "name": "Muut tehtävät"
              },
              {
                "name": "Opettajankoulutuksen kehittäminen"
              },
              {
                "name": "Opettajankoulutus- ja kehitystehtävät yhteensä"
              },
              {
                "name": "Opetustehtävät yhteensä"
              },
              {
                "name": "Perusopetus"
              },
              {
                "name": "Taiteellinen toiminta"
              },
              {
                "name": "Tieteellinen ja taiteellinen jatkotutkintokoulutus"
              },
              {
                "name": "Tieteellinen tutkimus"
              },
              {
                "name": "Yleistoiminnot"
              },
              {
                "name": "Yliopistolain mukaiset kansalliskirjastotehtävät yhteensä"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Tuloslaskelma",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Yliopisto"
              },
              {
                "name": "Suodatus tilastovuosi"
              }
            ],
            "measures": [
              {
                "name": "Aineet, tarvikkeet ja tavarat yhteensä"
              },
              {
                "name": "Arvonalentumiset pysyvien vastaavien hyödykkeistä"
              },
              {
                "name": "Arvonalentumiset pysyvien vastaavien sijoituksista"
              },
              {
                "name": "Arvonalentumiset vaihtuvien vastaavien rahoitusarvopapereista"
              },
              {
                "name": "Liiketoiminnan eläkekulut"
              },
              {
                "name": "Liiketoiminnan henkilöstökulut yhteensä"
              },
              {
                "name": "Liiketoiminnan henkilöstösivukulut yhteensä"
              },
              {
                "name": "Korkokulut ja muut rahoituskulut yhteensä"
              },
              {
                "name": "Liiketoiminnan muut kulut"
              },
              {
                "name": "Liiketoiminnan muut tuotot"
              },
              {
                "name": "Liikevaihto(Tiedot liiketoiminnasta)"
              },
              {
                "name": "Liikevoitto tai tappio"
              },
              {
                "name": "Materiaalit ja palvelut yhteensä"
              },
              {
                "name": "Korkokulut ja muut rahoituskulut muille"
              },
              {
                "name": "Muut korko- ja rahoitustuotot muilta"
              },
              {
                "name": "Tuotot muista pysyvien vastaavien sijoituksista muilta"
              },
              {
                "name": "Liiketoiminnan muut henkilöstösivukulut"
              },
              {
                "name": "Muut korko- ja rahoitustuotot yhteensä"
              },
              {
                "name": "Muut välittömät verot"
              },
              {
                "name": "Ostot tilikauden aikana (Tiedot liiketoiminnasta)"
              },
              {
                "name": "Liiketoiminnan palkat ja palkkiot"
              },
              {
                "name": "Poistoeron lisäys tai vähennys"
              },
              {
                "name": "Poistot ja arvonalentumiset yhteensä"
              },
              {
                "name": "Rahoitustuotot ja -kulut yhteensä"
              },
              {
                "name": "Korkokulut ja muut rahoituskulut saman konsernin yrityksille"
              },
              {
                "name": "Muut korko- ja rahoitustuotot saman konsernin yrityksiltä"
              },
              {
                "name": "Tuotot muista pysyvien vastaavien sijoituksista saman konsernin yrityksiltä"
              },
              {
                "name": "Satunnaiset erät yhteensä"
              },
              {
                "name": "Liiketoiminnan satunnaiset kulut"
              },
              {
                "name": "Liiketoiminnan satunnaiset tuotot"
              },
              {
                "name": "Suunnitelman mukaiset poistot"
              },
              {
                "name": "Tilikauden voitto tai tappio"
              },
              {
                "name": "Tilinpäätössiirrot yhteensä"
              },
              {
                "name": "Liiketoiminnan tuloverot"
              },
              {
                "name": "Tuotot muista pysyvien vastaavien sijoituksista yhteensä"
              },
              {
                "name": "Tuotot osuuksista omistusyhteysyrityksissä"
              },
              {
                "name": "Tuotot osuuksista saman konsernin yrityksissä"
              },
              {
                "name": "Ulkopuoliset palvelut (Tiedot liiketoiminnasta)"
              },
              {
                "name": "Vaihtuvien vastaavien poikkeukselliset arvonalentumiset"
              },
              {
                "name": "Valmiiden ja keskeneräisten tuotteiden varastojen lisäys tai vähennys"
              },
              {
                "name": "Valmistus omaan käyttöön"
              },
              {
                "name": "Vapaaehtoisten varausten lisäys tai vähennys"
              },
              {
                "name": "Varastojen lisäys tai vähennys"
              },
              {
                "name": "Voitto tai tappio ennen satunnaisia eriä"
              },
              {
                "name": "Voitto tai tappio ennen tilinpäätössiirtoja ja veroja"
              },
              {
                "name": "Liiketoiminnan nettotulos"
              },
              {
                "name": "Konserni - Avustustuotot yhteensä"
              },
              {
                "name": "Konserni - Henkilöstökulut yhteensä"
              },
              {
                "name": "Konserni - Lahjoitukset yhteensä"
              },
              {
                "name": "Konserni - osuus osakkuusyhtiöiden tuloksesta yliopistokonserni"
              },
              {
                "name": "Konserni - osuus osakkuusyhtiöiden voitosta-tappiosta yliopistokonserni"
              },
              {
                "name": "Konserni - vähemmistöosuus yliopistokonserni"
              },
              {
                "name": "Konserni- osuus osakkuusyhtiöiden tuloksesta yliopistokonserni"
              },
              {
                "name": "Konserniliikearvo yliopistokonserni"
              },
              {
                "name": "Konsernireservi yliopistokonserni"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Varsinaisen toiminnan kustannukset pivot",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Koulutusala"
              },
              {
                "name": "Ohjauksen ala"
              },
              {
                "name": "Suodatus tilastovuosi"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Yliopisto"
              },
              {
                "name": "Tarkennettu toiminto"
              },
              {
                "name": "Päätoiminto"
              },
              {
                "name": "Toiminto"
              },
              {
                "name": "Koodit_päätoiminto"
              }
            ],
            "measures": [
              {
                "name": "Varsinaisen toiminnan kustannukset"
              }
            ]
          }
        ]
      },
      {
        "name": "Tase yliopisto",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Konserni"
              },
              {
                "name": "Suodatus tilastovuosi"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Yliopisto"
              }
            ],
            "measures": [
              {
                "name": "Aineet ja tarvikkeet"
              },
              {
                "name": "Aineettomat oikeudet"
              },
              {
                "name": "Arvonkorotusrahasto"
              },
              {
                "name": "Edellisten tilikausien voitto (tappio) (+/-)"
              },
              {
                "name": "Eläkevaraukset"
              },
              {
                "name": "Ennakkomaksut"
              },
              {
                "name": "Ennakkomaksut (vaihto-omaisuus)"
              },
              {
                "name": "Ennakkomaksut ja keskeneräiset hankinnat"
              },
              {
                "name": "Kehittämismenot"
              },
              {
                "name": "Keskeneräiset tuotteet"
              },
              {
                "name": "Koneet ja kalusto"
              },
              {
                "name": "Käyvän arvon rahasto"
              },
              {
                "name": "Liikearvo"
              },
              {
                "name": "Lyhytaikaiset eläkelainat"
              },
              {
                "name": "Lyhytaikaiset joukkovelkakirjalainat"
              },
              {
                "name": "Lyhytaikaiset lainasaamiset"
              },
              {
                "name": "Lyhytaikaiset lainat rahoituslaitoksilta"
              },
              {
                "name": "Lyhytaikaiset laskennalliset verosaamiset"
              },
              {
                "name": "Lyhytaikaiset laskennalliset verovelat"
              },
              {
                "name": "Lyhytaikaiset muut saamiset"
              },
              {
                "name": "Lyhytaikaiset muut velat"
              },
              {
                "name": "Lyhytaikaiset myyntisaamiset"
              },
              {
                "name": "Lyhytaikaiset ostovelat"
              },
              {
                "name": "Lyhytaikaiset pääomalainat"
              },
              {
                "name": "Lyhytaikaiset rahoitusvekselit"
              },
              {
                "name": "Lyhytaikaiset saadut ennakot"
              },
              {
                "name": "Lyhytaikaiset saamiset omistusyhteysyrityksiltä"
              },
              {
                "name": "Lyhytaikaiset saamiset saman konsernin yrityksiltä"
              },
              {
                "name": "Lyhytaikaiset siirtosaamiset"
              },
              {
                "name": "Lyhytaikaiset siirtovelat"
              },
              {
                "name": "Lyhytaikaiset vaihtovelkakirjalainat"
              },
              {
                "name": "Lyhytaikaiset velat omistusyhteysyrityksille"
              },
              {
                "name": "Lyhytaikaiset velat saman konsernin yrityksille"
              },
              {
                "name": "Maa- ja vesialueet"
              },
              {
                "name": "Maksuvalmius"
              },
              {
                "name": "Muu vaihto-omaisuus"
              },
              {
                "name": "Muut - arvopaperit"
              },
              {
                "name": "Muut - osakkeet ja osuudet"
              },
              {
                "name": "Muut aineelliset hyödykkeet"
              },
              {
                "name": "Muut arvopaperit"
              },
              {
                "name": "Muut osakkeet ja osuudet"
              },
              {
                "name": "Muut osakkeet ja osuudet (Rahoitusarvopaperit)"
              },
              {
                "name": "Muut pakolliset varaukset"
              },
              {
                "name": "Muut pitkävaikutteiset menot"
              },
              {
                "name": "Muut saamiset"
              },
              {
                "name": "Muut sidotut rahastot"
              },
              {
                "name": "Muut varat"
              },
              {
                "name": "Omakatteisten rahastojen sijoitukset yhteensä"
              },
              {
                "name": "Omakatteisten rahastojen varat"
              },
              {
                "name": "Omakatteisten rahastojen velat"
              },
              {
                "name": "Omavaraisuusaste"
              },
              {
                "name": "Osuudet omistusyhteysyrityksissä"
              },
              {
                "name": "Osuudet saman konsernin yrityksissä"
              },
              {
                "name": "Osuudet saman konsernin yrityksissä (Rahoitusarvopaperit)"
              },
              {
                "name": "Peruspääoma"
              },
              {
                "name": "Pitkäaikaiset eläkelainat"
              },
              {
                "name": "Pitkäaikaiset joukkovelkakirjalainat"
              },
              {
                "name": "Pitkäaikaiset lainasaamiset"
              },
              {
                "name": "Pitkäaikaiset lainat rahoituslaitoksilta"
              },
              {
                "name": "Pitkäaikaiset laskennalliset verosaamiset"
              },
              {
                "name": "Pitkäaikaiset laskennalliset verovelat"
              },
              {
                "name": "Pitkäaikaiset muut saamiset"
              },
              {
                "name": "Pitkäaikaiset muut velat"
              },
              {
                "name": "Pitkäaikaiset myyntisaamiset"
              },
              {
                "name": "Pitkäaikaiset ostovelat"
              },
              {
                "name": "Pitkäaikaiset pääomalainat"
              },
              {
                "name": "Pitkäaikaiset rahoitusvekselit"
              },
              {
                "name": "Pitkäaikaiset saadut ennakot"
              },
              {
                "name": "Pitkäaikaiset saamiset omistusyhteysyrityksiltä"
              },
              {
                "name": "Pitkäaikaiset saamiset saman konsernin yrityksiltä"
              },
              {
                "name": "Pitkäaikaiset siirtosaamiset"
              },
              {
                "name": "Pitkäaikaiset siirtovelat"
              },
              {
                "name": "Pitkäaikaiset vaihtovelkakirjalainat"
              },
              {
                "name": "Pitkäaikaiset velat omistusyhteysyrityksille"
              },
              {
                "name": "Pitkäaikaiset velat saman konsernin yrityksille"
              },
              {
                "name": "Rahasto-osuudet"
              },
              {
                "name": "Rahat ja pankkisaamiset"
              },
              {
                "name": "Rahat ja pankkisaamiset (Omakatteisten rahastojen varat)"
              },
              {
                "name": "Rakennukset ja rakennelmat"
              },
              {
                "name": "Saamiset omistusyhteysyrityksiltä"
              },
              {
                "name": "Saamiset saman konsernin yrityksiltä"
              },
              {
                "name": "Tilikauden voitto (tappio) (+/-)"
              },
              {
                "name": "Tilinpäätössiirtojen kertymä (Poistoero)"
              },
              {
                "name": "Toimintapääoma"
              },
              {
                "name": "Toimintapääoman suhde omaan pääomaan"
              },
              {
                "name": "Valmiit tuotteet/tavarat"
              },
              {
                "name": "Vapaat rahastot"
              },
              {
                "name": "Vastaavaa yhteensä"
              },
              {
                "name": "Vastattavaa yhteensä"
              },
              {
                "name": "Verovaraukset"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      }
    ],
    "roles": [
      {
        "name": "Testi",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "DWI\\T_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1732"
          },
          {
            "memberName": "DWI\\T_VIPU_SSAS_DB_R",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1751"
          },
          {
            "memberName": "DWI\\T_VIPU_SSAS_DB_R_TK",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1753"
          },
          {
            "memberName": "DWI\\Z_T_Antero_Read_TAB",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-4155"
          },
          {
            "memberName": "DWI\\Z_P_Antero_Read_TAB",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-4156"
          }
        ]
      },
      {
        "name": "Tuotanto",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "DWI\\P_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1733"
          },
          {
            "memberName": "DWI\\P_VIPU_SSAS_DB_R",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1752"
          },
          {
            "memberName": "DWI\\P_VIPU_SSAS_DB_R_TK",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1754"
          },
          {
            "memberName": "NT AUTHORITY\\IUSR",
            "memberId": "S-1-5-17"
          },
          {
            "memberName": "DWI\\Z_T_Antero_Read_TAB",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-4155"
          },
          {
            "memberName": "DWI\\Z_P_Antero_Read_TAB",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-4156"
          }
        ]
      }
    ]
  },
  "id": "SemanticModel"
}