{
  "name": "SemanticModel",
  "compatibilityLevel": 1200,
  "model": {
    "culture": "fi-FI",
    "dataSources": [
      {
        "name": "SqlServer dwitvipusql16 ANTERO",
        "connectionString": "Provider=SQLNCLI11;Data Source=dwitvipusql16;Initial Catalog=ANTERO;Integrated Security=SSPI;Persist Security Info=false",
        "impersonationMode": "impersonateAccount",
        "account": "dwi\\pankalai",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "Sarakeleveys",
        "columns": [
          {
            "name": "Sarakeleveys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Sarakeleveys",
            "sourceProviderType": "Char"
          },
          {
            "name": "leveys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "leveys",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Sarakeleveys",
            "dataView": "full",
            "source": {
              "query": " SELECT [dw].[Sarakeleveys].* FROM [dw].[Sarakeleveys] ",
              "dataSource": "SqlServer dwitvipusql16 ANTERO"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dw].[Sarakeleveys].* FROM [dw].[Sarakeleveys] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Sarakeleveys"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dw"
          }
        ]
      },
      {
        "name": "Muuttujat",
        "columns": [
          {
            "name": "Tilastovuosi",
            "dataType": "int64",
            "sourceColumn": "Tilastovuosi",
            "sourceProviderType": "Integer",
            "displayFolder": "Aikamuuttujat"
          },
          {
            "name": "Lukuvuosi",
            "dataType": "string",
            "sourceColumn": "Lukuvuosi",
            "sourceProviderType": "WChar",
            "displayFolder": "Aikamuuttujat"
          },
          {
            "name": "loAloituspvm",
            "dataType": "int64",
            "sourceColumn": "loAloituspvm",
            "sourceProviderType": "BigInt"
          },
          {
            "name": "ooAloituspvm",
            "dataType": "int64",
            "sourceColumn": "ooAloituspvm",
            "sourceProviderType": "BigInt"
          },
          {
            "name": "Aika aloittamisesta",
            "dataType": "string",
            "sourceColumn": "Aika aloittamisesta",
            "sourceProviderType": "Char",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Henkilo_koodi",
            "dataType": "string",
            "sourceColumn": "Henkilo_koodi",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Sukupuoli",
            "dataType": "string",
            "sourceColumn": "Sukupuoli",
            "sourceProviderType": "WChar",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "uusi_opisk",
            "dataType": "int64",
            "sourceColumn": "uusi_opisk",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Aloittanut keväällä",
            "dataType": "string",
            "sourceColumn": "Aloittanut keväällä",
            "sourceProviderType": "Char",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Olo syksy",
            "dataType": "int64",
            "sourceColumn": "Olo syksy",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Olo kevät",
            "dataType": "int64",
            "sourceColumn": "Olo kevät",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Lasna",
            "dataType": "int64",
            "sourceColumn": "Lasna",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Suorittanut55",
            "dataType": "int64",
            "sourceColumn": "Suorittanut55",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Opintopisteet syksy",
            "dataType": "int64",
            "sourceColumn": "Opintopisteet syksy",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Opintopisteet kevät",
            "dataType": "int64",
            "sourceColumn": "Opintopisteet kevät",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Sektori",
            "dataType": "string",
            "sourceColumn": "Sektori",
            "sourceProviderType": "Char",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Korkeakoulu",
            "dataType": "string",
            "sourceColumn": "Korkeakoulu",
            "sourceProviderType": "WChar",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Tutkintokoodi",
            "dataType": "string",
            "sourceColumn": "Tutkintokoodi",
            "sourceProviderType": "Char",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Tutkinto",
            "dataType": "string",
            "sourceColumn": "Tutkinto",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "OKM ohjauksen ala",
            "dataType": "string",
            "sourceColumn": "OKM ohjauksen ala",
            "sortByColumn": "OKM ohjauksen ala jarj",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusaste, taso 1",
            "dataType": "string",
            "sourceColumn": "Koulutusaste, taso 1",
            "sortByColumn": "Koulutusaste, taso 1 jarj",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusaste, taso 2",
            "dataType": "string",
            "sourceColumn": "Koulutusaste, taso 2",
            "sortByColumn": "Koulutusaste, taso 2 jarj",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusala, taso 1",
            "dataType": "string",
            "sourceColumn": "Koulutusala, taso 1",
            "sortByColumn": "Koulutusala, taso 1 jarj",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusala, taso 2",
            "dataType": "string",
            "sourceColumn": "Koulutusala, taso 2",
            "sortByColumn": "Koulutusala, taso 2 jarj",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusala, taso 3",
            "dataType": "string",
            "sourceColumn": "Koulutusala, taso 3",
            "sortByColumn": "Koulutusala, taso 3 jarj",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "suorittanut27",
            "dataType": "int64",
            "sourceColumn": "suorittanut27",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "suorittanut55IlmanPankkia",
            "dataType": "int64",
            "sourceColumn": "suorittanut55IlmanPankkia",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "suorittanut55PankinAvulla",
            "dataType": "int64",
            "sourceColumn": "suorittanut55PankinAvulla",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "OKM ohjauksen ala jarj",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "OKM ohjauksen ala jarj",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Koulutusaste, taso 1 jarj",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Koulutusaste, taso 1 jarj",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Koulutusaste, taso 2 jarj",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Koulutusaste, taso 2 jarj",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Koulutusala, taso 1 jarj",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Koulutusala, taso 1 jarj",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Koulutusala, taso 2 jarj",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Koulutusala, taso 2 jarj",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Koulutusala, taso 3 jarj",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Koulutusala, taso 3 jarj",
            "sourceProviderType": "Integer"
          }
        ],
        "partitions": [
          {
            "name": "v_virta_otp_55_tilanne",
            "dataView": "full",
            "source": {
              "query": " SELECT [dw].[v_virta_otp_55_tilanne].* FROM [dw].[v_virta_otp_55_tilanne] ",
              "dataSource": "SqlServer dwitvipusql16 ANTERO"
            }
          }
        ],
        "measures": [
          {
            "name": "Väh. 55 op suorittaneet",
            "expression": "CALCULATE(DISTINCTCOUNT(Muuttujat[Henkilo_koodi]),Muuttujat[Suorittanut55]=1)",
            "formatString": "#,0"
          },
          {
            "name": "Väh. 55 op suorittaneet, rahoitusmalli",
            "expression": "[Väh. 55 op suorittaneet]-[Keväällä aloittaneista väh. 27 op suorittaneet]/2",
            "formatString": "#,0"
          },
          {
            "name": "Keväällä aloittaneista väh. 27 op suorittaneet",
            "expression": "CALCULATE(DISTINCTCOUNT(Muuttujat[Henkilo_koodi]),Muuttujat[suorittanut27]=1)",
            "formatString": "#,0"
          },
          {
            "name": "Suorittanut 55 op ilman pankkia",
            "expression": "calculate(DISTINCTCOUNT(Muuttujat[Henkilo_koodi]),Muuttujat[suorittanut55IlmanPankkia]=1)",
            "formatString": "#,0"
          },
          {
            "name": "Läsnäolleet",
            "expression": "calculate(DISTINCTCOUNT([Henkilo_koodi]),Muuttujat[Lasna]=1)",
            "formatString": "#,0"
          },
          {
            "name": "55 op suorittaneiden osuus",
            "expression": "[Väh. 55 op suorittaneet]/[Läsnäolleet]",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Läsnäolleet kevät",
            "expression": "CALCULATE(DISTINCTCOUNT([Henkilo_koodi]),Muuttujat[Olo kevät]=1)",
            "formatString": "#,0"
          },
          {
            "name": "Läsnäolleet syksy",
            "expression": "CALCULATE(DISTINCTCOUNT([Henkilo_koodi]),Muuttujat[Olo syksy]=1)",
            "formatString": "#,0"
          },
          {
            "name": "Väh. 55 op suorittaneet (LIVE)",
            "expression": "CALCULATE(DISTINCTCOUNT(Muuttujat[Henkilo_koodi]),Muuttujat[Suorittanut55]=1)",
            "formatString": "#,0"
          },
          {
            "name": "Väh. 55 op suorittaneet, rahoitusmalli (LIVE)",
            "expression": "[Väh. 55 op suorittaneet]-[Keväällä aloittaneista väh. 27 op suorittaneet]/2",
            "formatString": "#,0"
          },
          {
            "name": "Keväällä aloittaneista väh. 27 op suorittaneet (LIVE)",
            "expression": "CALCULATE(DISTINCTCOUNT(Muuttujat[Henkilo_koodi]),Muuttujat[suorittanut27]=1)",
            "formatString": "#,0"
          },
          {
            "name": "Suorittanut 55 op ilman pankkia (LIVE)",
            "expression": "calculate(DISTINCTCOUNT(Muuttujat[Henkilo_koodi]),Muuttujat[suorittanut55IlmanPankkia]=1)",
            "formatString": "#,0"
          },
          {
            "name": "Läsnäolleet (LIVE)",
            "expression": "calculate(DISTINCTCOUNT([Henkilo_koodi]),Muuttujat[Lasna]=1)",
            "formatString": "#,0"
          },
          {
            "name": "55 op suorittaneiden osuus (LIVE)",
            "expression": "[Väh. 55 op suorittaneet]/[Läsnäolleet]",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Läsnäolleet kevät (LIVE)",
            "expression": "CALCULATE(DISTINCTCOUNT([Henkilo_koodi]),Muuttujat[Olo kevät]=1)",
            "formatString": "#,0"
          },
          {
            "name": "Läsnäolleet syksy (LIVE)",
            "expression": "CALCULATE(DISTINCTCOUNT([Henkilo_koodi]),Muuttujat[Olo syksy]=1)",
            "formatString": "#,0"
          },
          {
            "name": "Suorittanut 55 op pankin kanssa",
            "expression": "CALCULATE(DISTINCTCOUNT([Henkilo_koodi]),Muuttujat[suorittanut55PankinAvulla]=1)",
            "formatString": "#,0"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dw].[v_virta_otp_55_tilanne].* FROM [dw].[v_virta_otp_55_tilanne] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "v_virta_otp_55_tilanne"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dw"
          }
        ]
      }
    ],
    "perspectives": [
      {
        "name": "Perus",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Aika aloittamisesta"
              },
              {
                "name": "Aloittanut keväällä"
              },
              {
                "name": "Korkeakoulu"
              },
              {
                "name": "Koulutusala, taso 1"
              },
              {
                "name": "Koulutusala, taso 2"
              },
              {
                "name": "Koulutusala, taso 3"
              },
              {
                "name": "Koulutusaste, taso 1"
              },
              {
                "name": "Koulutusaste, taso 2"
              },
              {
                "name": "Lukuvuosi"
              },
              {
                "name": "OKM ohjauksen ala"
              },
              {
                "name": "Sektori"
              },
              {
                "name": "Sukupuoli"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Tutkinto"
              },
              {
                "name": "Tutkintokoodi"
              }
            ],
            "measures": [
              {
                "name": "55 op suorittaneiden osuus"
              },
              {
                "name": "Keväällä aloittaneista väh. 27 op suorittaneet"
              },
              {
                "name": "Läsnäolleet"
              },
              {
                "name": "Suorittanut 55 op ilman pankkia"
              },
              {
                "name": "Väh. 55 op suorittaneet"
              },
              {
                "name": "Väh. 55 op suorittaneet, rahoitusmalli"
              },
              {
                "name": "Suorittanut 55 op pankin kanssa"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Perus_LIVE",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Aika aloittamisesta"
              },
              {
                "name": "Aloittanut keväällä"
              },
              {
                "name": "Korkeakoulu"
              },
              {
                "name": "Koulutusala, taso 1"
              },
              {
                "name": "Koulutusala, taso 2"
              },
              {
                "name": "Koulutusala, taso 3"
              },
              {
                "name": "Koulutusaste, taso 1"
              },
              {
                "name": "Koulutusaste, taso 2"
              },
              {
                "name": "Lukuvuosi"
              },
              {
                "name": "OKM ohjauksen ala"
              },
              {
                "name": "Sektori"
              },
              {
                "name": "Sukupuoli"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Tutkinto"
              },
              {
                "name": "Tutkintokoodi"
              }
            ],
            "measures": [
              {
                "name": "55 op suorittaneiden osuus (LIVE)"
              },
              {
                "name": "Keväällä aloittaneista väh. 27 op suorittaneet (LIVE)"
              },
              {
                "name": "Läsnäolleet (LIVE)"
              },
              {
                "name": "Suorittanut 55 op ilman pankkia (LIVE)"
              },
              {
                "name": "Väh. 55 op suorittaneet (LIVE)"
              },
              {
                "name": "Väh. 55 op suorittaneet, rahoitusmalli (LIVE)"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      }
    ],
    "roles": [
      {
        "name": "Kehitys",
        "modelPermission": "administrator",
        "members": [
          {
            "memberName": "DWI\\T_VIPU_TABOKM_DB_VipunenTK_Dev",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1364"
          },
          {
            "memberName": "DWI\\T_VIPU_TAB_DB_VipunenTK_Dev",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1363"
          },
          {
            "memberName": "DWI\\Z_P_Antero_Read_TAB",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-4156"
          },
          {
            "memberName": "DWI\\Z_T_Antero_Read_TAB",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-4155"
          }
        ]
      },
      {
        "name": "Luku",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "DWI\\T_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1732"
          },
          {
            "memberName": "NT AUTHORITY\\IUSR",
            "memberId": "S-1-5-17"
          },
          {
            "memberName": "DWI\\P_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1733"
          },
          {
            "memberName": "DWI\\Z_P_Antero_Read_TAB",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-4156"
          },
          {
            "memberName": "DWI\\Z_T_Antero_Read_TAB",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-4155"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "400"
      }
    ]
  },
  "id": "SemanticModel"
}