{
  "name": "SemanticModel",
  "compatibilityLevel": 1200,
  "model": {
    "culture": "fi-FI",
    "dataSources": [
      {
        "name": "SqlServer dwitvipusql22 VipunenTK",
        "connectionString": "Provider=SQLNCLI11;Data Source=dwitvipusql22;Initial Catalog=VipunenTK;Integrated Security=SSPI;Persist Security Info=false",
        "impersonationMode": "impersonateServiceAccount",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "Muuttujat",
        "columns": [
          {
            "name": "Tilastovuosi",
            "dataType": "string",
            "sourceColumn": "Tilastovuosi",
            "sourceProviderType": "Char"
          },
          {
            "name": "Ikäryhmä",
            "dataType": "string",
            "sourceColumn": "Ikäryhmä",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Ammattiala 1.taso",
            "dataType": "string",
            "sourceColumn": "Ammattiala 1.taso",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Ammattiala 2.taso",
            "dataType": "string",
            "sourceColumn": "Ammattiala 2.taso",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Suhteellinen ajankohta",
            "dataType": "string",
            "sourceColumn": "Suhteellinen ajankohta",
            "sourceProviderType": "WChar"
          },
          {
            "name": "ammattisiirtymat_alalta",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ammattisiirtymat_alalta",
            "sourceProviderType": "Integer"
          },
          {
            "name": "ammattisiirtymat_alalle",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ammattisiirtymat_alalle",
            "sourceProviderType": "Integer"
          },
          {
            "name": "siirtynyt_tyottomaksi",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "siirtynyt_tyottomaksi",
            "sourceProviderType": "Integer"
          },
          {
            "name": "siirtynyt_tyottomasta_tyolliseksi",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "siirtynyt_tyottomasta_tyolliseksi",
            "sourceProviderType": "Integer"
          },
          {
            "name": "siirtynyt_tyovoiman_ulkopuolelle",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "siirtynyt_tyovoiman_ulkopuolelle",
            "sourceProviderType": "Integer"
          },
          {
            "name": "siirtynyt_tyovoiman_ulkopuolelta_tyolliseksi",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "siirtynyt_tyovoiman_ulkopuolelta_tyolliseksi",
            "sourceProviderType": "Integer"
          },
          {
            "name": "siirtynyt_tuntemattomasta_tyolliseksi",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "siirtynyt_tuntemattomasta_tyolliseksi"
          },
          {
            "name": "siirtynyt_tuntemattomaksi",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "siirtynyt_tuntemattomaksi"
          }
        ],
        "partitions": [
          {
            "name": "Muuttujat",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[v_f_tab_ammattisiirtymat_tyottomat_ja_tyovoiman_ulkopuoliset].* FROM [dbo].[v_f_tab_ammattisiirtymat_tyottomat_ja_tyovoiman_ulkopuoliset] ",
              "dataSource": "SqlServer dwitvipusql22 VipunenTK"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tilastovuosi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>123</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Ikäryhmä</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>106</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Ammattiala 1.taso</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>168</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Ammattiala 2.taso</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>168</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Suhteellinen ajankohta</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>199</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ammattisiirtymat_alalta</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>204</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ammattisiirtymat_alalle</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>203</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>siirtynyt_tyottomaksi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>186</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>siirtynyt_tyottomasta_tyolliseksi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>264</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>siirtynyt_tyovoiman_ulkopuolelle</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>272</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>siirtynyt_tyovoiman_ulkopuolelta_tyolliseksi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>350</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>siirtynyt_tuntemattomasta_tyolliseksi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>300</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>siirtynyt_tuntemattomaksi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>222</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tilastovuosi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Ikäryhmä</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Ammattiala 1.taso</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Ammattiala 2.taso</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Suhteellinen ajankohta</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ammattisiirtymat_alalta</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>5</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ammattisiirtymat_alalle</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>6</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>siirtynyt_tyottomaksi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>7</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>siirtynyt_tyottomasta_tyolliseksi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>8</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>siirtynyt_tyovoiman_ulkopuolelle</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>9</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>siirtynyt_tyovoiman_ulkopuolelta_tyolliseksi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>10</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>siirtynyt_tuntemattomasta_tyolliseksi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>11</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>siirtynyt_tuntemattomaksi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>12</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>siirtynyt_tuntemattomasta_tyolliseksi</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>siirtynyt_tuntemattomaksi</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Ammattisiirtymät_s",
            "expression": " SUM(Muuttujat[ammattisiirtymat_alalle]) - SUM(Muuttujat[ammattisiirtymat_alalta])",
            "formatString": "#,0"
          },
          {
            "name": "Ammattisiirtymät alalle_s",
            "expression": " SUM([ammattisiirtymat_alalle])",
            "formatString": "#,0"
          },
          {
            "name": "Ammattisiirtymät alalta_s",
            "expression": " SUM([ammattisiirtymat_alalta])",
            "formatString": "#,0"
          },
          {
            "name": "Ammattisiirtymät KA_s",
            "expression": [
              "",
              "",
              "var taulu = SUMMARIZE(Muuttujat, Muuttujat[Tilastovuosi], \"lkm\", [Ammattisiirtymät_s])",
              "return",
              "AVERAGEX(taulu, [lkm])"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Siirtymät (työttömät)_s",
            "expression": [
              "",
              "",
              "SUM(Muuttujat[siirtynyt_tyottomasta_tyolliseksi]) - sum(Muuttujat[siirtynyt_tyottomaksi])"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Työttömäksi siirtyneet_s",
            "expression": [
              "",
              "",
              "SUM(Muuttujat[siirtynyt_tyottomaksi])"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Työttömästä työlliseksi siirtyneet_s",
            "expression": " SUM([siirtynyt_tyottomasta_tyolliseksi])",
            "formatString": "#,0"
          },
          {
            "name": "Siirtymät (työttömät) KA_s",
            "expression": [
              "",
              "",
              "var taulu = SUMMARIZE(Muuttujat, Muuttujat[Tilastovuosi], \"lkm\", [Siirtymät (työttömät)_s])",
              "RETURN",
              "AVERAGEX(taulu, [lkm])"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Siirtymät (työvoiman ulkopuoliset)_s",
            "expression": [
              "",
              "SUM(Muuttujat[siirtynyt_tyovoiman_ulkopuolelta_tyolliseksi]) + SUM(Muuttujat[siirtynyt_tuntemattomasta_tyolliseksi])  - SUM(Muuttujat[siirtynyt_tyovoiman_ulkopuolelle]) - SUM(Muuttujat[siirtynyt_tuntemattomaksi])"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Työvoiman ulkopuolelle siirtyneet_s",
            "expression": [
              "",
              "",
              "SUM(Muuttujat[siirtynyt_tyovoiman_ulkopuolelle]) + SUM(Muuttujat[siirtynyt_tuntemattomaksi])"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Työvoiman ulkopuolelta työlliseksi siirtyneet_s",
            "expression": [
              "",
              "",
              "SUM(Muuttujat[siirtynyt_tyovoiman_ulkopuolelta_tyolliseksi])"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Siirtymät (työvoiman ulkopuoliset) KA_s",
            "expression": [
              "",
              "",
              "VAR taulu = SUMMARIZE(Muuttujat, Muuttujat[Tilastovuosi], \"lkm\", [Siirtymät (työvoiman ulkopuoliset)_s])",
              "RETURN",
              "AVERAGEX(taulu, [lkm])"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Siirtymät yhteensä_s",
            "expression": [
              "",
              "",
              "[Ammattisiirtymät_s] + [Siirtymät (työttömät)_s] + [Siirtymät (työvoiman ulkopuoliset)_s]"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Siirtymät yhteensä KA_s",
            "expression": [
              "",
              "",
              "var taulu = SUMMARIZE(Muuttujat, Muuttujat[Tilastovuosi], \"lkm\", [Siirtymät yhteensä_s])",
              "RETURN",
              "AVERAGEX(taulu,[lkm])"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Siirtymät (työvoiman ulkopuoliset, pl. tuntemattomat)_s",
            "expression": [
              "",
              "SUM(Muuttujat[siirtynyt_tyovoiman_ulkopuolelta_tyolliseksi]) - SUM(Muuttujat[siirtynyt_tyovoiman_ulkopuolelle]) ",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "Työvoiman ulkopuolelle siirtyneet (pl. tuntemattomat)_s",
            "expression": [
              "",
              "",
              "SUM(Muuttujat[siirtynyt_tyovoiman_ulkopuolelle])",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "Siirtymät (työvoiman ulkopuoliset, pl. tuntemattomat) KA_s",
            "expression": [
              "",
              "",
              "VAR taulu = SUMMARIZE(Muuttujat, Muuttujat[Tilastovuosi], \"lkm\", [Siirtymät (työvoiman ulkopuoliset, pl. tuntemattomat)_s])",
              "RETURN",
              "AVERAGEX(taulu, [lkm])",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "Siirtymät yhteensä (pl. tuntemattomat)_s",
            "expression": [
              "",
              "",
              "[Ammattisiirtymät_s] + [Siirtymät (työttömät)_s] + [Siirtymät (työvoiman ulkopuoliset, pl. tuntemattomat)_s]",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "Siirtymät yhteensä (pl. tuntemattomat) KA_s",
            "expression": [
              "",
              "",
              "var taulu = SUMMARIZE(Muuttujat, Muuttujat[Tilastovuosi], \"lkm\", [Siirtymät yhteensä (pl. tuntemattomat)_s])",
              "RETURN",
              "AVERAGEX(taulu,[lkm])",
              ""
            ],
            "formatString": "#,0"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[v_f_tab_ammattisiirtymat_tyottomat_ja_tyovoiman_ulkopuoliset].* FROM [dbo].[v_f_tab_ammattisiirtymat_tyottomat_ja_tyovoiman_ulkopuoliset] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "v_f_tab_ammattisiirtymat_tyottomat_ja_tyovoiman_ulkopuoliset"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Tilastovuosi</string>",
              "      </key>",
              "      <value>",
              "        <int>123</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ikäryhmä</string>",
              "      </key>",
              "      <value>",
              "        <int>106</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ammattiala 1.taso</string>",
              "      </key>",
              "      <value>",
              "        <int>168</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ammattiala 2.taso</string>",
              "      </key>",
              "      <value>",
              "        <int>168</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Suhteellinen ajankohta</string>",
              "      </key>",
              "      <value>",
              "        <int>199</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ammattisiirtymat_alalta</string>",
              "      </key>",
              "      <value>",
              "        <int>204</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ammattisiirtymat_alalle</string>",
              "      </key>",
              "      <value>",
              "        <int>203</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>siirtynyt_tyottomaksi</string>",
              "      </key>",
              "      <value>",
              "        <int>186</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>siirtynyt_tyottomasta_tyolliseksi</string>",
              "      </key>",
              "      <value>",
              "        <int>264</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>siirtynyt_tyovoiman_ulkopuolelle</string>",
              "      </key>",
              "      <value>",
              "        <int>272</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>siirtynyt_tyovoiman_ulkopuolelta_tyolliseksi</string>",
              "      </key>",
              "      <value>",
              "        <int>350</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>siirtynyt_tuntemattomasta_tyolliseksi</string>",
              "      </key>",
              "      <value>",
              "        <int>300</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>siirtynyt_tuntemattomaksi</string>",
              "      </key>",
              "      <value>",
              "        <int>222</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Tilastovuosi</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ikäryhmä</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ammattiala 1.taso</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ammattiala 2.taso</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Suhteellinen ajankohta</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ammattisiirtymat_alalta</string>",
              "      </key>",
              "      <value>",
              "        <int>5</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ammattisiirtymat_alalle</string>",
              "      </key>",
              "      <value>",
              "        <int>6</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>siirtynyt_tyottomaksi</string>",
              "      </key>",
              "      <value>",
              "        <int>7</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>siirtynyt_tyottomasta_tyolliseksi</string>",
              "      </key>",
              "      <value>",
              "        <int>8</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>siirtynyt_tyovoiman_ulkopuolelle</string>",
              "      </key>",
              "      <value>",
              "        <int>9</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>siirtynyt_tyovoiman_ulkopuolelta_tyolliseksi</string>",
              "      </key>",
              "      <value>",
              "        <int>10</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>siirtynyt_tuntemattomasta_tyolliseksi</string>",
              "      </key>",
              "      <value>",
              "        <int>11</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>siirtynyt_tuntemattomaksi</string>",
              "      </key>",
              "      <value>",
              "        <int>12</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>siirtynyt_tuntemattomasta_tyolliseksi</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>siirtynyt_tuntemattomaksi</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      }
    ],
    "perspectives": [
      {
        "name": "Siirtymät",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Ammattiala 1.taso"
              },
              {
                "name": "Ammattiala 2.taso"
              },
              {
                "name": "Ikäryhmä"
              },
              {
                "name": "Suhteellinen ajankohta"
              },
              {
                "name": "Tilastovuosi"
              }
            ],
            "measures": [
              {
                "name": "Ammattisiirtymät alalle_s"
              },
              {
                "name": "Ammattisiirtymät alalta_s"
              },
              {
                "name": "Ammattisiirtymät_s"
              },
              {
                "name": "Siirtymät (työttömät)_s"
              },
              {
                "name": "Siirtymät (työvoiman ulkopuoliset)_s"
              },
              {
                "name": "Työttömäksi siirtyneet_s"
              },
              {
                "name": "Työttömästä työlliseksi siirtyneet_s"
              },
              {
                "name": "Työvoiman ulkopuolelle siirtyneet_s"
              },
              {
                "name": "Työvoiman ulkopuolelta työlliseksi siirtyneet_s"
              },
              {
                "name": "Siirtymät yhteensä_s"
              },
              {
                "name": "Siirtymät (työvoiman ulkopuoliset, pl. tuntemattomat)_s"
              },
              {
                "name": "Työvoiman ulkopuolelle siirtyneet (pl. tuntemattomat)_s"
              },
              {
                "name": "Siirtymät yhteensä (pl. tuntemattomat)_s"
              }
            ]
          }
        ]
      },
      {
        "name": "Siirtymät KA",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Ammattiala 1.taso"
              },
              {
                "name": "Ammattiala 2.taso"
              },
              {
                "name": "Ikäryhmä"
              },
              {
                "name": "Suhteellinen ajankohta"
              },
              {
                "name": "Tilastovuosi"
              }
            ],
            "measures": [
              {
                "name": "Ammattisiirtymät KA_s"
              },
              {
                "name": "Siirtymät (työttömät) KA_s"
              },
              {
                "name": "Siirtymät (työvoiman ulkopuoliset) KA_s"
              },
              {
                "name": "Siirtymät yhteensä KA_s"
              },
              {
                "name": "Siirtymät (työvoiman ulkopuoliset, pl. tuntemattomat) KA_s"
              },
              {
                "name": "Siirtymät yhteensä (pl. tuntemattomat) KA_s"
              }
            ]
          }
        ]
      }
    ],
    "roles": [
      {
        "name": "Luku",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "DWI\\Z_P_Antero_Full_Read_TAB",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-2272"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "400"
      }
    ]
  },
  "id": "SemanticModel"
}
