{
  "name": "SemanticModel",
  "compatibilityLevel": 1200,
  "model": {
    "culture": "fi-FI",
    "dataSources": [
      {
        "name": "SqlServer dwitestvipusql Bibliometriikka",
        "connectionString": "Provider=SQLOLEDB.1;Data Source=dwitvipusql22;Initial Catalog=Bibliometriikka;Integrated Security=SSPI;Persist Security Info=false",
        "impersonationMode": "impersonateServiceAccount",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      },
      {
        "name": "SqlServer dwitvipusql22 Bibliometriikka",
        "connectionString": "Provider=SQLOLEDB.1;Data Source=dwitvipusql22;Initial Catalog=Bibliometriikka;Integrated Security=SSPI;Persist Security Info=false",
        "impersonationMode": "impersonateServiceAccount",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      },
      {
        "name": "SqlServer dwitvipusql22 Bibliometriikka 2",
        "connectionString": "Provider=SQLOLEDB.1;Data Source=dwitvipusql22;Initial Catalog=Bibliometriikka;Integrated Security=SSPI;Persist Security Info=false",
        "impersonationMode": "impersonateServiceAccount",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      },
      {
        "name": "SqlServer dwitvipusql22 Bibliometriikka 3",
        "connectionString": "Provider=SQLOLEDB.1;Data Source=dwitvipusql22;Initial Catalog=Bibliometriikka;Integrated Security=SSPI;Persist Security Info=false",
        "impersonationMode": "impersonateServiceAccount",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "Sarakeleveys",
        "columns": [
          {
            "name": "Sarakeleveys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Sarakeleveys"
          },
          {
            "name": "leveys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "leveys"
          }
        ],
        "partitions": [
          {
            "name": "Sarakeleveys",
            "source": {
              "type": "query",
              "query": "SELECT [dbo].[Sarakeleveys].* FROM [dbo].[Sarakeleveys]",
              "dataSource": "SqlServer dwitestvipusql Bibliometriikka"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization"
              },
              {
                "name": "TableWidgetSerialization"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Sarakeleveys"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Sarakeleveys].* FROM [dbo].[Sarakeleveys] "
          }
        ]
      },
      {
        "name": "Bibliometriikka 2022",
        "columns": [
          {
            "name": "Vuosikoodi",
            "dataType": "int64",
            "sourceColumn": "Vuosikoodi",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Nelivuotiskausi",
            "dataType": "string",
            "sourceColumn": "Nelivuotiskausi",
            "sourceProviderType": "WChar",
            "displayFolder": "Aikamuuttujat"
          },
          {
            "name": "Vuosi",
            "dataType": "int64",
            "sourceColumn": "Vuosi",
            "sourceProviderType": "Integer",
            "displayFolder": "Aikamuuttujat"
          },
          {
            "name": "Maajärjestys",
            "dataType": "int64",
            "sourceColumn": "Maajärjestys",
            "sourceProviderType": "Integer"
          },
          {
            "name": "IDkoodi",
            "dataType": "int64",
            "sourceColumn": "IDkoodi",
            "sourceProviderType": "BigInt"
          },
          {
            "name": "Maa",
            "dataType": "string",
            "sourceColumn": "Maa",
            "sourceProviderType": "WChar",
            "displayFolder": "Aluemuuttujat"
          },
          {
            "name": "Manner",
            "dataType": "string",
            "sourceColumn": "Manner",
            "sortByColumn": "Mannerkoodi",
            "sourceProviderType": "WChar",
            "displayFolder": "Aluemuuttujat"
          },
          {
            "name": "Mannerkoodi",
            "dataType": "int64",
            "sourceColumn": "Mannerkoodi",
            "sourceProviderType": "Integer"
          },
          {
            "name": "EU15-maat",
            "dataType": "string",
            "sourceColumn": "EU15-maat",
            "sortByColumn": "EU15-maat jarjestys",
            "sourceProviderType": "WChar",
            "displayFolder": "Aluemuuttujat"
          },
          {
            "name": "EU15-maat jarjestys",
            "dataType": "int64",
            "sourceColumn": "EU15-maat jarjestys",
            "sourceProviderType": "Integer"
          },
          {
            "name": "EU-maat",
            "dataType": "string",
            "sourceColumn": "EU-maat",
            "sortByColumn": "EU-maat jarjestys",
            "sourceProviderType": "WChar",
            "displayFolder": "Aluemuuttujat"
          },
          {
            "name": "EU-maat jarjestys",
            "dataType": "int64",
            "sourceColumn": "EU-maat jarjestys",
            "sourceProviderType": "Integer"
          },
          {
            "name": "IC-maat",
            "dataType": "string",
            "sourceColumn": "IC-maat",
            "sourceProviderType": "WChar",
            "displayFolder": "Aluemuuttujat"
          },
          {
            "name": "OECD-maat",
            "dataType": "string",
            "sourceColumn": "OECD-maat",
            "sortByColumn": "OECD-maat jarjestys",
            "sourceProviderType": "WChar",
            "displayFolder": "Aluemuuttujat"
          },
          {
            "name": "OECD-maat jarjestys",
            "dataType": "int64",
            "sourceColumn": "OECD-maat jarjestys",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Pohjoismaat",
            "dataType": "string",
            "sourceColumn": "Pohjoismaat",
            "sortByColumn": "Pohjoismaat jarjestys",
            "sourceProviderType": "WChar",
            "displayFolder": "Aluemuuttujat"
          },
          {
            "name": "Pohjoismaat jarjestys",
            "dataType": "int64",
            "sourceColumn": "Pohjoismaat jarjestys",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Maaryhmä",
            "dataType": "string",
            "sourceColumn": "Maaryhmä",
            "sortByColumn": "Maaryhmä Järjestys",
            "sourceProviderType": "WChar",
            "displayFolder": "Aluemuuttujat"
          },
          {
            "name": "Maaryhmä Järjestys",
            "dataType": "int64",
            "sourceColumn": "Maaryhmä Järjestys",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Yhteistyö",
            "dataType": "string",
            "sourceColumn": "Yhteistyö",
            "sourceProviderType": "Char",
            "displayFolder": "Yhteistyömuuttujat"
          },
          {
            "name": "Päätieteenala koodi",
            "dataType": "int64",
            "sourceColumn": "Päätieteenala koodi",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Päätieteenala",
            "dataType": "string",
            "sourceColumn": "Päätieteenala",
            "sortByColumn": "Päätieteenala koodi",
            "sourceProviderType": "WChar",
            "displayFolder": "Tieteenalamuuttujat"
          },
          {
            "name": "Tieteenala koodi",
            "dataType": "int64",
            "sourceColumn": "Tieteenala koodi",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Tieteenalaryhmä (tieteen tila)",
            "dataType": "string",
            "sourceColumn": "Tieteenalaryhmä (tieteen tila)",
            "sortByColumn": "Tieteenala koodi",
            "sourceProviderType": "WChar",
            "displayFolder": "Tieteenalamuuttujat"
          },
          {
            "name": "Tieteenala bibliometrinen koodi",
            "dataType": "int64",
            "sourceColumn": "Tieteenala bibliometrinen koodi",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Tieteenala",
            "dataType": "string",
            "sourceColumn": "Tieteenala",
            "sourceProviderType": "WChar",
            "displayFolder": "Tieteenalamuuttujat"
          },
          {
            "name": "TRAlakoodi3",
            "dataType": "int64",
            "sourceColumn": "TRAlakoodi3",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Alanimi_taso3",
            "dataType": "string",
            "sourceColumn": "Alanimi_taso3",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Organisaatio",
            "dataType": "string",
            "sourceColumn": "Organisaatio",
            "sourceProviderType": "WChar",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Organisaatiotyyppi",
            "dataType": "string",
            "sourceColumn": "Organisaatiotyyppi",
            "sortByColumn": "Organisaatiotyyppi koodi",
            "sourceProviderType": "WChar",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Organisaatiotyyppi koodi",
            "dataType": "int64",
            "sourceColumn": "Organisaatiotyyppi koodi",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Kansainvälinen yhteistyö",
            "dataType": "string",
            "sourceColumn": "Kansainvälinen yhteistyö",
            "sourceProviderType": "WChar",
            "displayFolder": "Yhteistyömuuttujat"
          },
          {
            "name": "Kansallinen Yhteistyö",
            "dataType": "string",
            "sourceColumn": "Kansallinen Yhteistyö",
            "sourceProviderType": "WChar",
            "displayFolder": "Yhteistyömuuttujat"
          },
          {
            "name": "Kansallinen Yliopistoyhteistyö",
            "dataType": "string",
            "sourceColumn": "Kansallinen Yliopistoyhteistyö",
            "sourceProviderType": "WChar",
            "displayFolder": "Yhteistyömuuttujat"
          },
          {
            "name": "Kansallinen Yritysyhteistyö",
            "dataType": "string",
            "sourceColumn": "Kansallinen Yritysyhteistyö",
            "sourceProviderType": "WChar",
            "displayFolder": "Yhteistyömuuttujat"
          },
          {
            "name": "Julkaisut Maailma 4 vuotta",
            "dataType": "double",
            "sourceColumn": "Julkaisut Maailma 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "Top10 Julkaisut (Maailma 4v Ositettu)",
            "dataType": "double",
            "sourceColumn": "Top10 Julkaisut (Maailma 4v Ositettu)",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "Top10 Julkaisut (Maailma 4v Ositettu, Kaikki)",
            "dataType": "double",
            "sourceColumn": "Top10 Julkaisut (Maailma 4v Ositettu, Kaikki)",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "Analyysijulkaisut Maailma 4 vuotta",
            "dataType": "double",
            "sourceColumn": "Analyysijulkaisut Maailma 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "Analyysijulkaisut Maailma 4 vuotta, Kaikki",
            "dataType": "double",
            "sourceColumn": "Analyysijulkaisut Maailma 4 vuotta, Kaikki",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "TOP 10 Julkaisut Maailma 4 vuotta",
            "dataType": "double",
            "sourceColumn": "TOP 10 Julkaisut Maailma 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "TOP 10 Julkaisut Maailma 4 vuotta, Kaikki",
            "dataType": "double",
            "sourceColumn": "TOP 10 Julkaisut Maailma 4 vuotta, Kaikki",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "TOP 1 Julkaisut Maailma 4 vuotta",
            "dataType": "double",
            "sourceColumn": "TOP 1 Julkaisut Maailma 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "TOP 1 Julkaisut Maailma 4 vuotta, Kaikki",
            "dataType": "double",
            "sourceColumn": "TOP 1 Julkaisut Maailma 4 vuotta, Kaikki",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "Sisäinen kattavuus Maailma 4 vuotta",
            "dataType": "double",
            "sourceColumn": "Sisäinen kattavuus Maailma 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "Sitaatiot Maailma 4 vuotta",
            "dataType": "double",
            "sourceColumn": "Sitaatiot Maailma 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "Sitaatiot Maailma 4 vuotta, Kaikki",
            "dataType": "double",
            "sourceColumn": "Sitaatiot Maailma 4 vuotta, Kaikki",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "TOP 10 Indeksi Maailma 4 vuotta",
            "dataType": "double",
            "sourceColumn": "TOP 10 Indeksi Maailma 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "TOP 10 Indeksi Maailma 4 vuotta, Kaikki",
            "dataType": "double",
            "sourceColumn": "TOP 10 Indeksi Maailma 4 vuotta, Kaikki",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "TOP 1 Indeksi Maailma 4 vuotta",
            "dataType": "double",
            "sourceColumn": "TOP 1 Indeksi Maailma 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "TOP 1 Indeksi Maailma 4 vuotta, Kaikki",
            "dataType": "double",
            "sourceColumn": "TOP 1 Indeksi Maailma 4 vuotta, Kaikki",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "Julkaisut Suomi 4 vuotta",
            "dataType": "double",
            "sourceColumn": "Julkaisut Suomi 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "Analyysijulkaisut Suomi 4 vuotta",
            "dataType": "double",
            "sourceColumn": "Analyysijulkaisut Suomi 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "Analyysijulkaisut Suomi 4 vuotta, Kaikki",
            "dataType": "double",
            "sourceColumn": "Analyysijulkaisut Suomi 4 vuotta, Kaikki",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "TOP 10 Julkaisut Suomi 4 vuotta",
            "dataType": "double",
            "sourceColumn": "TOP 10 Julkaisut Suomi 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "TOP 10 Julkaisut Suomi 4 vuotta, Kaikki",
            "dataType": "double",
            "sourceColumn": "TOP 10 Julkaisut Suomi 4 vuotta, Kaikki",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "TOP 1 Julkaisut Suomi 4 vuotta",
            "dataType": "double",
            "sourceColumn": "TOP 1 Julkaisut Suomi 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "TOP 1 Julkaisut Suomi 4 vuotta, Kaikki",
            "dataType": "double",
            "sourceColumn": "TOP 1 Julkaisut Suomi 4 vuotta, Kaikki",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "Sisäinen kattavuus Suomi 4 vuotta",
            "dataType": "double",
            "sourceColumn": "Sisäinen kattavuus Suomi 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "Sitaatiot Suomi 4 vuotta",
            "dataType": "double",
            "sourceColumn": "Sitaatiot Suomi 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "Sitaatiot Suomi 4 vuotta, Kaikki",
            "dataType": "double",
            "sourceColumn": "Sitaatiot Suomi 4 vuotta, Kaikki",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "TOP 10 Indeksi Suomi 4 vuotta",
            "dataType": "double",
            "sourceColumn": "TOP 10 Indeksi Suomi 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "TOP 10 Indeksi Suomi 4 vuotta, Kaikki",
            "dataType": "double",
            "sourceColumn": "TOP 10 Indeksi Suomi 4 vuotta, Kaikki",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "TOP 1 Indeksi Suomi 4 vuotta",
            "dataType": "double",
            "sourceColumn": "TOP 1 Indeksi Suomi 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "TOP 1 Indeksi Suomi 4 vuotta, Kaikki",
            "dataType": "double",
            "sourceColumn": "TOP 1 Indeksi Suomi 4 vuotta, Kaikki",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "Julkaisut YTmaatBilat 4 vuotta",
            "dataType": "double",
            "sourceColumn": "Julkaisut YTmaatBilat 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "Analyysijulkaisut YTmaatBilat 4 vuotta",
            "dataType": "double",
            "sourceColumn": "Analyysijulkaisut YTmaatBilat 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "Analyysijulkaisut YTmaatBilat 4 vuotta, Kaikki",
            "dataType": "double",
            "sourceColumn": "Analyysijulkaisut YTmaatBilat 4 vuotta, Kaikki",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "TOP 10 Julkaisut YTmaatBilat 4 vuotta",
            "dataType": "double",
            "sourceColumn": "TOP 10 Julkaisut YTmaatBilat 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "TOP 10 Julkaisut YTmaatBilat 4 vuotta, Kaikki",
            "dataType": "double",
            "sourceColumn": "TOP 10 Julkaisut YTmaatBilat 4 vuotta, Kaikki",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "TOP 1 Julkaisut YTmaatBilat 4 vuotta",
            "dataType": "double",
            "sourceColumn": "TOP 1 Julkaisut YTmaatBilat 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "TOP 1 Julkaisut YTmaatBilat 4 vuotta, Kaikki",
            "dataType": "double",
            "sourceColumn": "TOP 1 Julkaisut YTmaatBilat 4 vuotta, Kaikki",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "Sitaatiot YTmaatBilat 4 vuotta",
            "dataType": "double",
            "sourceColumn": "Sitaatiot YTmaatBilat 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "Sitaatiot YTmaatBilat 4 vuotta, Kaikki",
            "dataType": "double",
            "sourceColumn": "Sitaatiot YTmaatBilat 4 vuotta, Kaikki",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "TOP 10 Indeksi YTmaatBilat 4 vuotta",
            "dataType": "double",
            "sourceColumn": "TOP 10 Indeksi YTmaatBilat 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "TOP 10 Indeksi YTmaatBilat 4 vuotta, Kaikki",
            "dataType": "double",
            "sourceColumn": "TOP 10 Indeksi YTmaatBilat 4 vuotta, Kaikki",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "TOP 1 Indeksi YTmaatBilat 4 vuotta",
            "dataType": "double",
            "sourceColumn": "TOP 1 Indeksi YTmaatBilat 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "TOP 1 Indeksi YTmaatBilat 4 vuotta, Kaikki",
            "dataType": "double",
            "sourceColumn": "TOP 1 Indeksi YTmaatBilat 4 vuotta, Kaikki",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "Julkaisut YTmaatKaikki 4 vuotta",
            "dataType": "double",
            "sourceColumn": "Julkaisut YTmaatKaikki 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "Analyysijulkaisut YTmaatKaikki 4 vuotta",
            "dataType": "double",
            "sourceColumn": "Analyysijulkaisut YTmaatKaikki 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "Analyysijulkaisut YTmaatKaikki 4 vuotta, Kaikki",
            "dataType": "double",
            "sourceColumn": "Analyysijulkaisut YTmaatKaikki 4 vuotta, Kaikki",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "TOP 10 Julkaisut YTmaatKaikki 4 vuotta",
            "dataType": "double",
            "sourceColumn": "TOP 10 Julkaisut YTmaatKaikki 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "TOP 10 Julkaisut YTmaatKaikki 4 vuotta, Kaikki",
            "dataType": "double",
            "sourceColumn": "TOP 10 Julkaisut YTmaatKaikki 4 vuotta, Kaikki",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "TOP 1 Julkaisut YTmaatKaikki 4 vuotta",
            "dataType": "double",
            "sourceColumn": "TOP 1 Julkaisut YTmaatKaikki 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "TOP 1 Julkaisut YTmaatKaikki 4 vuotta, Kaikki",
            "dataType": "double",
            "sourceColumn": "TOP 1 Julkaisut YTmaatKaikki 4 vuotta, Kaikki",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "Sitaatiot YTmaatKaikki 4 vuotta",
            "dataType": "double",
            "sourceColumn": "Sitaatiot YTmaatKaikki 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "Sitaatiot YTmaatKaikki 4 vuotta, Kaikki",
            "dataType": "double",
            "sourceColumn": "Sitaatiot YTmaatKaikki 4 vuotta, Kaikki",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "TOP 10 Indeksi YTmaatKaikki 4 vuotta",
            "dataType": "double",
            "sourceColumn": "TOP 10 Indeksi YTmaatKaikki 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "TOP 10 Indeksi YTmaatKaikki 4 vuotta, Kaikki",
            "dataType": "double",
            "sourceColumn": "TOP 10 Indeksi YTmaatKaikki 4 vuotta, Kaikki",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "TOP 1 Indeksi YTmaatKaikki 4 vuotta",
            "dataType": "double",
            "sourceColumn": "TOP 1 Indeksi YTmaatKaikki 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "TOP 1 Indeksi YTmaatKaikki 4 vuotta, Kaikki",
            "dataType": "double",
            "sourceColumn": "TOP 1 Indeksi YTmaatKaikki 4 vuotta, Kaikki",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "PID",
            "dataType": "int64",
            "sourceColumn": "PID",
            "sourceProviderType": "Integer"
          },
          {
            "name": "PID YT maat Bilat Whole",
            "dataType": "int64",
            "sourceColumn": "PID YT maat Bilat Whole",
            "sourceProviderType": "Integer"
          },
          {
            "name": "PID YT maat Kaikki Whole",
            "dataType": "int64",
            "sourceColumn": "PID YT maat Kaikki Whole",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Open Access -tyyppi",
            "dataType": "string",
            "sourceColumn": "Open Access -tyyppi",
            "sortByColumn": "Open Access jarjestys",
            "sourceProviderType": "WChar",
            "displayFolder": "Julkaisumuuttujat"
          },
          {
            "name": "Open Access jarjestys",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Open Access jarjestys",
            "sourceProviderType": "Integer"
          }
        ],
        "partitions": [
          {
            "name": "Bibliometriikka 2022",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[v_f_tab_maailma_4v_2022].* FROM [dbo].[v_f_tab_maailma_4v_2022] ",
              "dataSource": "SqlServer dwitvipusql22 Bibliometriikka 3"
            }
          }
        ],
        "measures": [
          {
            "name": "Julkaisut (Maailma 4v Ositettu, ml. ESCI) 2022",
            "expression": "SUMX(SUMMARIZE('Bibliometriikka 2022',[IDkoodi],[Julkaisut Maailma 4 vuotta]),[Julkaisut Maailma 4 vuotta])",
            "formatString": "#,0",
            "displayFolder": "Web of Science, ml. ESCI"
          },
          {
            "name": "Top10-indeksi (maailma 4v) 2022",
            "expression": [
              "",
              "var taulu = ",
              "CALCULATETABLE(",
              "\tSUMMARIZE(",
              "\t\t'Bibliometriikka 2022',",
              "\t\t'Bibliometriikka 2022'[IDkoodi],",
              "\t\t'Bibliometriikka 2022'[TOP 10 Indeksi Maailma 4 vuotta],",
              "\t\t'Bibliometriikka 2022'[TOP 10 Julkaisut Maailma 4 vuotta]),",
              "\t'Bibliometriikka 2022'[Vuosikoodi]<28)",
              "return",
              "IF(",
              "\tAND('Bibliometriikka 2022'[Julkaisut (Maailma 4v Ositettu, ml. ESCI) 2022]>=50,'Bibliometriikka 2022'[Sisäinen kattavuus (maailma 4v, ml. ESCI) 2022]>=0.4),",
              "\tDIVIDE(",
              "\t\tSUMX(taulu, [TOP 10 Indeksi Maailma 4 vuotta]), SUMX(taulu, [TOP 10 Julkaisut Maailma 4 vuotta])),BLANK())",
              ""
            ],
            "formatString": "0.00",
            "displayFolder": "Web of Science Core (vain viittausindeksit)"
          },
          {
            "name": "Sisäinen kattavuus (maailma 4v, ml. ESCI) 2022",
            "expression": "SUMX(SUMMARIZE('Bibliometriikka 2022',[IDkoodi],[Sisäinen kattavuus Maailma 4 vuotta]),[Sisäinen kattavuus Maailma 4 vuotta])/SUMX(SUMMARIZE('Bibliometriikka 2022',[IDkoodi],[Julkaisut Maailma 4 vuotta]),[Julkaisut Maailma 4 vuotta])",
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Web of Science, ml. ESCI"
          },
          {
            "name": "Top1-indeksi (maailma 4v) 2022",
            "expression": [
              "",
              "",
              "var taulu = ",
              "CALCULATETABLE(",
              "\tSUMMARIZE(",
              "\t\t'Bibliometriikka 2022', ",
              "\t\t'Bibliometriikka 2022'[IDkoodi], ",
              "\t\t'Bibliometriikka 2022'[TOP 1 Indeksi Maailma 4 vuotta], ",
              "\t\t'Bibliometriikka 2022'[TOP 1 Julkaisut Maailma 4 vuotta]),",
              "\t'Bibliometriikka 2022'[Vuosikoodi]<28)",
              "",
              "return",
              "",
              "IF(",
              "\tAND([Julkaisut (Maailma 4v Ositettu, ml. ESCI) 2022]>=50,[Sisäinen kattavuus (maailma 4v, ml. ESCI) 2022]>=0.4),",
              "\tDIVIDE(",
              "\t\tSUMX(taulu,[TOP 1 Indeksi Maailma 4 vuotta]), SUMX(taulu,[TOP 1 Julkaisut Maailma 4 vuotta])),",
              "\tBLANK())"
            ],
            "formatString": "0.00",
            "displayFolder": "Web of Science Core (vain viittausindeksit)"
          },
          {
            "name": "Viittausindeksi (Maailma 4v) 2022",
            "expression": [
              "",
              "",
              "VAR taulu = ",
              "CALCULATETABLE(",
              "\tSUMMARIZE(",
              "\t\t'Bibliometriikka 2022', ",
              "\t\t'Bibliometriikka 2022'[IDkoodi],",
              "\t\t'Bibliometriikka 2022'[Sitaatiot Maailma 4 vuotta],",
              "\t\t[Analyysijulkaisut Maailma 4 vuotta]),",
              "\t'Bibliometriikka 2022'[Vuosikoodi]<28)",
              "\t",
              "return",
              "",
              "IF(",
              "\tAND([Julkaisut (Maailma 4v Ositettu, ml. ESCI) 2022]>=50,[Sisäinen kattavuus (maailma 4v, ml. ESCI) 2022]>=0.4),",
              "\tDIVIDE(SUMX(taulu,[Sitaatiot Maailma 4 vuotta]),SUMX(taulu,[Analyysijulkaisut Maailma 4 vuotta])),BLANK())",
              ""
            ],
            "formatString": "0.00",
            "displayFolder": "Web of Science Core (vain viittausindeksit)"
          },
          {
            "name": "Top10-indeksi (YT Maat Bilat 4 vuotta) 2022",
            "expression": [
              "",
              "",
              "var taulu = ",
              "CALCULATETABLE(",
              "\tSUMMARIZE(",
              "\t\t'Bibliometriikka 2022',",
              "\t\t'Bibliometriikka 2022'[IDkoodi],",
              "\t\t'Bibliometriikka 2022'[TOP 10 Indeksi YTmaatBilat 4 vuotta],",
              "\t\t'Bibliometriikka 2022'[TOP 10 Julkaisut YTmaatBilat 4 vuotta]),",
              "\t'Bibliometriikka 2022'[Vuosikoodi]<28)",
              "",
              "return\t\t",
              "",
              "IF([Julkaisut (YT Maat Bilat 4 vuotta, ml. ESCI) 2022]>=50,DIVIDE(SUMX(taulu, [TOP 10 Indeksi YTmaatBilat 4 vuotta]),SUMX(taulu,[TOP 10 Julkaisut YTmaatBilat 4 vuotta])),BLANK())"
            ],
            "formatString": "0.00",
            "displayFolder": "Web of Science Core (vain viittausindeksit)"
          },
          {
            "name": "Julkaisut (YT Maat Bilat 4 vuotta, ml. ESCI) 2022",
            "expression": "sumx(summarize('Bibliometriikka 2022',[IDkoodi],[Julkaisut YTmaatBilat 4 vuotta]),[Julkaisut YTmaatBilat 4 vuotta])",
            "formatString": "#,0",
            "displayFolder": "Web of Science, ml. ESCI"
          },
          {
            "name": "Viittausindeksi (YT maat Bilat 4 vuotta) 2022",
            "expression": [
              "",
              "",
              "var taulu =",
              "CALCULATETABLE(",
              "\tSUMMARIZE(",
              "\t\t'Bibliometriikka 2022',",
              "\t\t'Bibliometriikka 2022'[IDkoodi],",
              "\t\t'Bibliometriikka 2022'[Sitaatiot YTmaatBilat 4 vuotta],",
              "\t\t'Bibliometriikka 2022'[Analyysijulkaisut YTmaatBilat 4 vuotta]),",
              "\t'Bibliometriikka 2022'[Vuosikoodi]<28)",
              "\t",
              "return",
              "\t\t",
              "IF([Julkaisut (YT Maat Bilat 4 vuotta, ml. ESCI) 2022]>=50,DIVIDE(SUMX(taulu, [Sitaatiot YTmaatBilat 4 vuotta]),SUMX(taulu,[Analyysijulkaisut YTmaatBilat 4 vuotta])),BLANK())"
            ],
            "formatString": "0.00",
            "displayFolder": "Web of Science Core (vain viittausindeksit)"
          },
          {
            "name": "Top1-indeksi (YT Maat Kaikki 4 vuotta) 2022",
            "expression": [
              "",
              "",
              "var taulu =",
              "CALCULATETABLE(",
              "\tSUMMARIZE(",
              "\t\t'Bibliometriikka 2022',",
              "\t\t'Bibliometriikka 2022'[IDkoodi],",
              "\t\t'Bibliometriikka 2022'[TOP 1 Indeksi YTmaatKaikki 4 vuotta],",
              "\t\t'Bibliometriikka 2022'[TOP 1 Julkaisut YTmaatKaikki 4 vuotta]),",
              "\t'Bibliometriikka 2022'[Vuosikoodi]<28)",
              "\t",
              "return",
              "",
              "IF([Julkaisut (YT Maat Kaikki 4 vuotta, ml. ESCI) 2022]>=50,DIVIDE(SUMX(taulu,[TOP 1 Indeksi YTmaatKaikki 4 vuotta]), SUMX(taulu, [TOP 1 Julkaisut YTmaatKaikki 4 vuotta])),BLANK())"
            ],
            "formatString": "0.00",
            "displayFolder": "Web of Science Core (vain viittausindeksit)"
          },
          {
            "name": "Julkaisut (YT Maat Bilat Whole, ml. ESCI) 2022",
            "expression": "CALCULATE(DISTINCTCOUNT([PID YT maat Bilat Whole]),NOT(ISBLANK('Bibliometriikka 2022'[PID YT maat Bilat Whole])))",
            "formatString": "#,0",
            "displayFolder": "Web of Science, ml. ESCI"
          },
          {
            "name": "Julkaisut (YT Maat Kaikki Whole, ml. ESCI) 2022",
            "expression": "CALCULATE(DISTINCTCOUNT([PID YT maat Kaikki Whole]),not(ISBLANK('Bibliometriikka 2022'[PID YT maat Kaikki Whole])))",
            "formatString": "0",
            "displayFolder": "Web of Science, ml. ESCI"
          },
          {
            "name": "Julkaisut (Suomi 4v Ositettu, ml. ESCI) 2022",
            "expression": "SUM([Julkaisut Suomi 4 vuotta])",
            "formatString": "#,0",
            "displayFolder": "Web of Science, ml. ESCI"
          },
          {
            "name": "Sisäinen kattavuus (suomi 4v, ml. ESCI) 2022",
            "expression": "SUM([Sisäinen kattavuus Suomi 4 vuotta])/SUM([Julkaisut Suomi 4 vuotta])",
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Web of Science, ml. ESCI"
          },
          {
            "name": "Viittausindeksi (Suomi 4v) 2022",
            "expression": "if([Julkaisut (Suomi 4v Ositettu, ml. ESCI) 2022]<50,BLANK(),CALCULATE(SUM([Sitaatiot Suomi 4 vuotta])/SUM([Analyysijulkaisut Suomi 4 vuotta])/1,FILTER('Bibliometriikka 2022','Bibliometriikka 2022'[Vuosikoodi]<28)))",
            "formatString": "0.00",
            "displayFolder": "Web of Science Core (vain viittausindeksit)"
          },
          {
            "name": "Julkaisut (Suomi 1v Osittamaton, ml. ESCI) 2022",
            "expression": "CALCULATE(DISTINCTCOUNT([PID]),NOT(ISBLANK('Bibliometriikka 2022'[PID])))",
            "formatString": "#,0",
            "displayFolder": "Web of Science, ml. ESCI"
          },
          {
            "name": "Julkaisut (YT Maat Kaikki 4 vuotta, ml. ESCI) 2022",
            "expression": "sumx(summarize('Bibliometriikka 2022',[IDkoodi],[Julkaisut YTmaatKaikki 4 vuotta]),[Julkaisut YTmaatKaikki 4 vuotta])",
            "formatString": "#,0",
            "displayFolder": "Web of Science, ml. ESCI"
          },
          {
            "name": "Top10-indeksi (YT Maat Kaikki 4 vuotta) 2022",
            "expression": [
              "",
              "",
              "var taulu = ",
              "CALCULATETABLE(",
              "\tSUMMARIZE(",
              "\t\t'Bibliometriikka 2022',",
              "\t\t'Bibliometriikka 2022'[IDkoodi],",
              "\t\t'Bibliometriikka 2022'[TOP 10 Indeksi YTmaatKaikki 4 vuotta],",
              "\t\t'Bibliometriikka 2022'[TOP 10 Julkaisut YTmaatKaikki 4 vuotta]),",
              "\t'Bibliometriikka 2022'[Vuosikoodi]<28)",
              "\t",
              "return",
              "",
              "IF([Julkaisut (YT Maat Kaikki 4 vuotta, ml. ESCI) 2022]>=50,",
              "DIVIDE(SUMX(taulu, [TOP 10 Indeksi YTmaatKaikki 4 vuotta]), SUMX(taulu, [TOP 10 Julkaisut YTmaatKaikki 4 vuotta])),BLANK())"
            ],
            "formatString": "0.00",
            "displayFolder": "Web of Science Core (vain viittausindeksit)"
          },
          {
            "name": "Viittausindeksi (YT maat Kaikki 4 vuotta) 2022",
            "expression": [
              "",
              "",
              "var taulu = ",
              "CALCULATETABLE(",
              "\tSUMMARIZE(",
              "\t\t'Bibliometriikka 2022',",
              "\t\t'Bibliometriikka 2022'[IDkoodi],",
              "\t\t'Bibliometriikka 2022'[Sitaatiot YTmaatKaikki 4 vuotta],",
              "\t\t'Bibliometriikka 2022'[Analyysijulkaisut YTmaatKaikki 4 vuotta]),",
              "\t'Bibliometriikka 2022'[Vuosikoodi]<28)",
              "\t",
              "return",
              "",
              "IF([Julkaisut (YT Maat Kaikki 4 vuotta, ml. ESCI) 2022]>=50,DIVIDE(SUMX(taulu,[Sitaatiot YTmaatKaikki 4 vuotta]),SUMX(taulu,[Analyysijulkaisut YTmaatKaikki 4 vuotta])),BLANK())"
            ],
            "formatString": "0.00",
            "displayFolder": "Web of Science Core (vain viittausindeksit)"
          },
          {
            "name": "Top 10 Julkaisut (Maailma 4v Ositettu) 2022",
            "expression": "CALCULATE(SUMX(SUMMARIZE('Bibliometriikka 2022',[IDkoodi],[Top10 Julkaisut (Maailma 4v Ositettu)]),[Top10 Julkaisut (Maailma 4v Ositettu)]),FILTER('Bibliometriikka 2022','Bibliometriikka 2022'[Vuosikoodi]<28))",
            "formatString": "#,0",
            "displayFolder": "Web of Science Core (vain viittausindeksit)"
          },
          {
            "name": "Top10-indeksi (maailma 4v, ml. ESCI) 2022",
            "expression": [
              "",
              "var taulu = ",
              "CALCULATETABLE(",
              "\tSUMMARIZE(",
              "\t\t'Bibliometriikka 2022',",
              "\t\t'Bibliometriikka 2022'[IDkoodi],",
              "\t\t'Bibliometriikka 2022'[TOP 10 Indeksi Maailma 4 vuotta, Kaikki],",
              "\t\t'Bibliometriikka 2022'[TOP 10 Julkaisut Maailma 4 vuotta, Kaikki]),",
              "\t'Bibliometriikka 2022'[Vuosikoodi]<28)",
              "return",
              "IF(",
              "\tAND('Bibliometriikka 2022'[Julkaisut (Maailma 4v Ositettu, ml. ESCI) 2022]>=50,'Bibliometriikka 2022'[Sisäinen kattavuus (maailma 4v, ml. ESCI) 2022]>=0.4),",
              "\tDIVIDE(",
              "\t\tSUMX(taulu, [TOP 10 Indeksi Maailma 4 vuotta, Kaikki]), SUMX(taulu, [TOP 10 Julkaisut Maailma 4 vuotta, Kaikki])),BLANK())"
            ],
            "formatString": "0.00",
            "displayFolder": "Web of Science, ml. ESCI"
          },
          {
            "name": "Top1-indeksi (maailma 4v, ml. ESCI) 2022",
            "expression": [
              "",
              "var taulu = ",
              "CALCULATETABLE(",
              "\tSUMMARIZE(",
              "\t\t'Bibliometriikka 2022', ",
              "\t\t'Bibliometriikka 2022'[IDkoodi], ",
              "\t\t'Bibliometriikka 2022'[TOP 1 Indeksi Maailma 4 vuotta, Kaikki], ",
              "\t\t'Bibliometriikka 2022'[TOP 1 Julkaisut Maailma 4 vuotta, Kaikki]),",
              "\t'Bibliometriikka 2022'[Vuosikoodi]<28)",
              "",
              "return",
              "",
              "IF(",
              "\tAND([Julkaisut (Maailma 4v Ositettu, ml. ESCI) 2022]>=50,[Sisäinen kattavuus (maailma 4v, ml. ESCI) 2022]>=0.4),",
              "\tDIVIDE(",
              "\t\tSUMX(taulu,[TOP 1 Indeksi Maailma 4 vuotta, Kaikki]), SUMX(taulu,[TOP 1 Julkaisut Maailma 4 vuotta, Kaikki])),",
              "\tBLANK())",
              ""
            ],
            "formatString": "0.00",
            "displayFolder": "Web of Science, ml. ESCI"
          },
          {
            "name": "Viittausindeksi (Maailma 4v, ml. ESCI) 2022",
            "expression": [
              "",
              "",
              "VAR taulu = ",
              "CALCULATETABLE(",
              "\tSUMMARIZE(",
              "\t\t'Bibliometriikka 2022', ",
              "\t\t'Bibliometriikka 2022'[IDkoodi],",
              "\t\t'Bibliometriikka 2022'[Sitaatiot Maailma 4 vuotta, Kaikki],",
              "\t\t[Analyysijulkaisut Maailma 4 vuotta, Kaikki]),",
              "\t'Bibliometriikka 2022'[Vuosikoodi]<28)",
              "\t",
              "return",
              "",
              "IF(",
              "\tAND([Julkaisut (Maailma 4v Ositettu, ml. ESCI) 2022]>=50,[Sisäinen kattavuus (maailma 4v, ml. ESCI) 2022]>=0.4),",
              "\tDIVIDE(SUMX(taulu,[Sitaatiot Maailma 4 vuotta, Kaikki]),SUMX(taulu,[Analyysijulkaisut Maailma 4 vuotta, Kaikki])),BLANK())",
              ""
            ],
            "formatString": "0.00",
            "displayFolder": "Web of Science, ml. ESCI"
          },
          {
            "name": "Top10-indeksi (YT Maat Bilat 4 vuotta, ml. ESCI) 2022",
            "expression": [
              "",
              "",
              "var taulu = ",
              "CALCULATETABLE(",
              "\tSUMMARIZE(",
              "\t\t'Bibliometriikka 2022',",
              "\t\t'Bibliometriikka 2022'[IDkoodi],",
              "\t\t'Bibliometriikka 2022'[TOP 10 Indeksi YTmaatBilat 4 vuotta, Kaikki],",
              "\t\t'Bibliometriikka 2022'[TOP 10 Julkaisut YTmaatBilat 4 vuotta, Kaikki]),",
              "\t'Bibliometriikka 2022'[Vuosikoodi]<28)",
              "",
              "return\t\t",
              "",
              "IF([Julkaisut (YT Maat Bilat 4 vuotta, ml. ESCI) 2022]>=50,DIVIDE(SUMX(taulu, [TOP 10 Indeksi YTmaatBilat 4 vuotta, Kaikki]),SUMX(taulu,[TOP 10 Julkaisut YTmaatBilat 4 vuotta, Kaikki])),BLANK())",
              ""
            ],
            "formatString": "0.00",
            "displayFolder": "Web of Science, ml. ESCI"
          },
          {
            "name": "Viittausindeksi (YT maat Bilat 4 vuotta, ml. ESCI) 2022",
            "expression": [
              "",
              "",
              "var taulu =",
              "CALCULATETABLE(",
              "\tSUMMARIZE(",
              "\t\t'Bibliometriikka 2022',",
              "\t\t'Bibliometriikka 2022'[IDkoodi],",
              "\t\t'Bibliometriikka 2022'[Sitaatiot YTmaatBilat 4 vuotta, Kaikki],",
              "\t\t'Bibliometriikka 2022'[Analyysijulkaisut YTmaatBilat 4 vuotta, Kaikki]),",
              "\t'Bibliometriikka 2022'[Vuosikoodi]<28)",
              "\t",
              "return",
              "\t\t",
              "IF([Julkaisut (YT Maat Bilat 4 vuotta, ml. ESCI) 2022]>=50,DIVIDE(SUMX(taulu, [Sitaatiot YTmaatBilat 4 vuotta, Kaikki]),SUMX(taulu,[Analyysijulkaisut YTmaatBilat 4 vuotta, Kaikki])),BLANK())",
              ""
            ],
            "formatString": "0.00",
            "displayFolder": "Web of Science, ml. ESCI"
          },
          {
            "name": "Top1-indeksi (YT Maat Kaikki 4 vuotta, ml. ESCI) 2022",
            "expression": [
              "",
              "",
              "var taulu =",
              "CALCULATETABLE(",
              "\tSUMMARIZE(",
              "\t\t'Bibliometriikka 2022',",
              "\t\t'Bibliometriikka 2022'[IDkoodi],",
              "\t\t'Bibliometriikka 2022'[TOP 1 Indeksi YTmaatKaikki 4 vuotta, Kaikki],",
              "\t\t'Bibliometriikka 2022'[TOP 1 Julkaisut YTmaatKaikki 4 vuotta, Kaikki]),",
              "\t'Bibliometriikka 2022'[Vuosikoodi]<28)",
              "\t",
              "return",
              "",
              "IF([Julkaisut (YT Maat Kaikki 4 vuotta, ml. ESCI) 2022]>=50,DIVIDE(SUMX(taulu,[TOP 1 Indeksi YTmaatKaikki 4 vuotta, Kaikki]), SUMX(taulu, [TOP 1 Julkaisut YTmaatKaikki 4 vuotta, Kaikki])),BLANK())",
              ""
            ],
            "formatString": "0.00",
            "displayFolder": "Web of Science, ml. ESCI"
          },
          {
            "name": "Viittausindeksi (Suomi 4v, ml. ESCI) 2022",
            "expression": "if([Julkaisut (Suomi 4v Ositettu, ml. ESCI) 2022]<50,BLANK(),CALCULATE(SUM([Sitaatiot Suomi 4 vuotta])/SUM([Analyysijulkaisut Suomi 4 vuotta, Kaikki])/1,FILTER('Bibliometriikka 2022','Bibliometriikka 2022'[Vuosikoodi]<28)))",
            "formatString": "0.00",
            "displayFolder": "Web of Science, ml. ESCI"
          },
          {
            "name": "Top10-indeksi (YT Maat Kaikki 4 vuotta, ml. ESCI) 2022",
            "expression": [
              "",
              "",
              "var taulu = ",
              "CALCULATETABLE(",
              "\tSUMMARIZE(",
              "\t\t'Bibliometriikka 2022',",
              "\t\t'Bibliometriikka 2022'[IDkoodi],",
              "\t\t'Bibliometriikka 2022'[TOP 10 Indeksi YTmaatKaikki 4 vuotta, Kaikki],",
              "\t\t'Bibliometriikka 2022'[TOP 10 Julkaisut YTmaatKaikki 4 vuotta, Kaikki]),",
              "\t'Bibliometriikka 2022'[Vuosikoodi]<28)",
              "\t",
              "return",
              "",
              "IF([Julkaisut (YT Maat Kaikki 4 vuotta, ml. ESCI) 2022]>=50,",
              "DIVIDE(SUMX(taulu, [TOP 10 Indeksi YTmaatKaikki 4 vuotta, Kaikki]), SUMX(taulu, [TOP 10 Julkaisut YTmaatKaikki 4 vuotta, Kaikki])),BLANK())",
              ""
            ],
            "formatString": "0.00",
            "displayFolder": "Web of Science, ml. ESCI"
          },
          {
            "name": "Viittausindeksi (YT maat Kaikki 4 vuotta, ml. ESCI) 2022",
            "expression": [
              "",
              "",
              "var taulu = ",
              "CALCULATETABLE(",
              "\tSUMMARIZE(",
              "\t\t'Bibliometriikka 2022',",
              "\t\t'Bibliometriikka 2022'[IDkoodi],",
              "\t\t'Bibliometriikka 2022'[Sitaatiot YTmaatKaikki 4 vuotta, Kaikki],",
              "\t\t'Bibliometriikka 2022'[Analyysijulkaisut YTmaatKaikki 4 vuotta, Kaikki]),",
              "\t'Bibliometriikka 2022'[Vuosikoodi]<28)",
              "\t",
              "return",
              "",
              "IF([Julkaisut (YT Maat Kaikki 4 vuotta, ml. ESCI) 2022]>=50,DIVIDE(SUMX(taulu,[Sitaatiot YTmaatKaikki 4 vuotta, Kaikki]),SUMX(taulu,[Analyysijulkaisut YTmaatKaikki 4 vuotta, Kaikki])),BLANK())",
              ""
            ],
            "formatString": "0.00",
            "displayFolder": "Web of Science, ml. ESCI"
          },
          {
            "name": "Top 10 Julkaisut (Maailma 4v Ositettu, ml. ESCI) 2022",
            "expression": "CALCULATE(SUMX(SUMMARIZE('Bibliometriikka 2022',[IDkoodi],[Top10 Julkaisut (Maailma 4v Ositettu, Kaikki)]),[Top10 Julkaisut (Maailma 4v Ositettu, Kaikki)]),FILTER('Bibliometriikka 2022','Bibliometriikka 2022'[Vuosikoodi]<28))",
            "formatString": "#,0",
            "displayFolder": "Web of Science, ml. ESCI"
          },
          {
            "name": "Top10-indeksi (Suomi 4v) 2022",
            "expression": "IF(AND([Julkaisut (Suomi 4v Ositettu, ml. ESCI) 2022]>=50,[Sisäinen kattavuus (suomi 4v, ml. ESCI) 2022]>=0.4),CALCULATE(DIVIDE((SUM([TOP 10 Indeksi Suomi 4 vuotta])/SUM([TOP 10 Julkaisut Suomi 4 vuotta])),1),'Bibliometriikka 2022'[Vuosikoodi]<28),BLANK())",
            "formatString": "0.00",
            "displayFolder": "Web of Science Core (vain viittausindeksit)"
          },
          {
            "name": "Top10-indeksi (Suomi 4v, ml. ESCI) 2022",
            "expression": "IF(AND([Julkaisut (Suomi 4v Ositettu, ml. ESCI) 2022]>=50,[Sisäinen kattavuus (suomi 4v, ml. ESCI) 2022]>=0.4),CALCULATE(DIVIDE((SUM([TOP 10 Indeksi Suomi 4 vuotta, Kaikki])/SUM([TOP 10 Julkaisut Suomi 4 vuotta, Kaikki])),1),'Bibliometriikka 2022'[Vuosikoodi]<28),BLANK())",
            "formatString": "0.00",
            "displayFolder": "Web of Science, ml. ESCI"
          },
          {
            "name": "Top1-indeksi (Suomi 4v) 2022",
            "expression": "IF(AND([Julkaisut (Suomi 4v Ositettu, ml. ESCI) 2022]>=50,[Sisäinen kattavuus (suomi 4v, ml. ESCI) 2022]>=0.4),CALCULATE(DIVIDE((SUM([TOP 1 Indeksi Suomi 4 vuotta])/SUM([TOP 1 Julkaisut Suomi 4 vuotta])),1),FILTER('Bibliometriikka 2022','Bibliometriikka 2022'[Vuosikoodi]<28)),BLANK())",
            "formatString": "0.00",
            "displayFolder": "Web of Science Core (vain viittausindeksit)"
          },
          {
            "name": "Top1-indeksi (Suomi 4v, ml. ESCI) 2022",
            "expression": "IF(AND([Julkaisut (Suomi 4v Ositettu, ml. ESCI) 2022]>=50,[Sisäinen kattavuus (suomi 4v, ml. ESCI) 2022]>=0.4),CALCULATE(DIVIDE((SUM([TOP 1 Indeksi Suomi 4 vuotta, Kaikki])/SUM([TOP 1 Julkaisut Suomi 4 vuotta, Kaikki])),1),FILTER('Bibliometriikka 2022','Bibliometriikka 2022'[Vuosikoodi]<28)),BLANK())",
            "formatString": "0.00",
            "displayFolder": "Web of Science, ml. ESCI"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[v_f_tab_maailma_4v_2022].* FROM [dbo].[v_f_tab_maailma_4v_2022] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "v_f_tab_maailma_4v_2022"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      }
    ],
    "perspectives": [
      {
        "name": "Analyysiraportti KV2022",
        "tables": [
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          },
          {
            "name": "Bibliometriikka 2022",
            "columns": [
              {
                "name": "EU15-maat"
              },
              {
                "name": "EU-maat"
              },
              {
                "name": "IC-maat"
              },
              {
                "name": "Kansainvälinen yhteistyö"
              },
              {
                "name": "Maa"
              },
              {
                "name": "Maaryhmä"
              },
              {
                "name": "Manner"
              },
              {
                "name": "Nelivuotiskausi"
              },
              {
                "name": "OECD-maat"
              },
              {
                "name": "Pohjoismaat"
              },
              {
                "name": "Päätieteenala"
              },
              {
                "name": "Tieteenala"
              },
              {
                "name": "Open Access -tyyppi"
              },
              {
                "name": "Tieteenalaryhmä (tieteen tila)"
              }
            ],
            "measures": [
              {
                "name": "Julkaisut (Maailma 4v Ositettu, ml. ESCI) 2022"
              },
              {
                "name": "Sisäinen kattavuus (maailma 4v, ml. ESCI) 2022"
              },
              {
                "name": "Top10-indeksi (maailma 4v) 2022"
              },
              {
                "name": "Top1-indeksi (maailma 4v) 2022"
              },
              {
                "name": "Viittausindeksi (Maailma 4v) 2022"
              },
              {
                "name": "Top10-indeksi (maailma 4v, ml. ESCI) 2022"
              },
              {
                "name": "Top1-indeksi (maailma 4v, ml. ESCI) 2022"
              },
              {
                "name": "Viittausindeksi (Maailma 4v, ml. ESCI) 2022"
              }
            ]
          }
        ]
      },
      {
        "name": "Analyysiraportti Suomi 2022",
        "tables": [
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          },
          {
            "name": "Bibliometriikka 2022",
            "columns": [
              {
                "name": "Kansainvälinen yhteistyö"
              },
              {
                "name": "Kansallinen Yhteistyö"
              },
              {
                "name": "Kansallinen Yliopistoyhteistyö"
              },
              {
                "name": "Kansallinen Yritysyhteistyö"
              },
              {
                "name": "Nelivuotiskausi"
              },
              {
                "name": "Organisaatio"
              },
              {
                "name": "Organisaatiotyyppi"
              },
              {
                "name": "Päätieteenala"
              },
              {
                "name": "Tieteenala"
              },
              {
                "name": "Tieteenalaryhmä (tieteen tila)"
              },
              {
                "name": "Vuosi"
              },
              {
                "name": "Open Access -tyyppi"
              },
              {
                "name": "Yhteistyö"
              }
            ],
            "measures": [
              {
                "name": "Julkaisut (Suomi 1v Osittamaton, ml. ESCI) 2022"
              },
              {
                "name": "Julkaisut (Suomi 4v Ositettu, ml. ESCI) 2022"
              },
              {
                "name": "Top10-indeksi (Suomi 4v) 2022"
              },
              {
                "name": "Viittausindeksi (Suomi 4v) 2022"
              },
              {
                "name": "Top10-indeksi (Suomi 4v, ml. ESCI) 2022"
              },
              {
                "name": "Viittausindeksi (Suomi 4v, ml. ESCI) 2022"
              },
              {
                "name": "Top1-indeksi (Suomi 4v, ml. ESCI) 2022"
              },
              {
                "name": "Top1-indeksi (Suomi 4v) 2022"
              }
            ]
          }
        ]
      },
      {
        "name": "Top 10 Julkaisut 2022",
        "tables": [
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          },
          {
            "name": "Bibliometriikka 2022",
            "columns": [
              {
                "name": "Kansainvälinen yhteistyö"
              },
              {
                "name": "Nelivuotiskausi"
              },
              {
                "name": "Päätieteenala"
              },
              {
                "name": "Tieteenala"
              },
              {
                "name": "Tieteenalaryhmä (tieteen tila)"
              },
              {
                "name": "EU15-maat"
              },
              {
                "name": "EU-maat"
              },
              {
                "name": "IC-maat"
              },
              {
                "name": "Maa"
              },
              {
                "name": "Maaryhmä"
              },
              {
                "name": "Manner"
              },
              {
                "name": "OECD-maat"
              },
              {
                "name": "Open Access -tyyppi"
              },
              {
                "name": "Pohjoismaat"
              }
            ],
            "measures": [
              {
                "name": "Top 10 Julkaisut (Maailma 4v Ositettu, ml. ESCI) 2022"
              },
              {
                "name": "Top 10 Julkaisut (Maailma 4v Ositettu) 2022"
              }
            ]
          }
        ]
      }
    ],
    "roles": [
      {
        "name": "Excel Service",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "DWI\\T_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1732"
          },
          {
            "memberName": "DWI\\P_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1733"
          },
          {
            "memberName": "DWI\\Z_P_Antero_Read_TAB",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-4156"
          },
          {
            "memberName": "DWI\\Z_T_Antero_Read_TAB",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-4155"
          },
          {
            "memberName": "DWI\\T_VIPU_SSAS_DB_R",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1751"
          },
          {
            "memberName": "DWI\\T_VIPU_SSAS_DB_R_TK",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1753"
          },
          {
            "memberName": "DWI\\P_VIPU_SSAS_DB_R",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1752"
          },
          {
            "memberName": "DWI\\P_VIPU_SSAS_DB_R_TK",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1754"
          },
          {
            "memberName": "DWI\\Z_DWIPVIPURD_Allow_F_Drive",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-5333"
          }
        ]
      },
      {
        "name": "Read Role",
        "modelPermission": "readRefresh"
      }
    ]
  },
  "id": "SemanticModel"
}