{
  "name": "SemanticModel",
  "compatibilityLevel": 1200,
  "model": {
    "culture": "fi-FI",
    "dataSources": [
      {
        "name": "SqlServer dwitvipusql16 antero",
        "connectionString": "Provider=SQLNCLI11;Data Source=dwitvipusql16;Persist Security Info=false;Integrated Security=SSPI;Initial Catalog=antero",
        "impersonationMode": "impersonateServiceAccount",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      },
      {
        "name": "SqlServer dwitvipusql16 Antero 2",
        "connectionString": "Provider=SQLNCLI11;Data Source=dwitvipusql16;Initial Catalog=Antero;Integrated Security=SSPI;Persist Security Info=false",
        "impersonationMode": "impersonateServiceAccount",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "Sarakeleveys",
        "isHidden": true,
        "columns": [
          {
            "name": "Sarakeleveys",
            "dataType": "string",
            "sourceColumn": "Sarakeleveys",
            "sourceProviderType": "Char"
          },
          {
            "name": "leveys",
            "dataType": "string",
            "sourceColumn": "leveys",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Sarakeleveys",
            "dataView": "full",
            "source": {
              "query": " SELECT [dw].[Sarakeleveys].* FROM [dw].[Sarakeleveys] ",
              "dataSource": "SqlServer dwitvipusql16 antero"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dw].[Sarakeleveys].* FROM [dw].[Sarakeleveys] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Sarakeleveys"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dw"
          }
        ]
      },
      {
        "name": "Muuttujat",
        "columns": [
          {
            "name": "tilastovuosi",
            "dataType": "int64",
            "sourceColumn": "tilastovuosi",
            "sourceProviderType": "Integer"
          },
          {
            "name": "henkilo_id",
            "dataType": "int64",
            "sourceColumn": "henkilo_id",
            "sourceProviderType": "Integer"
          },
          {
            "name": "kotikunta_fi",
            "dataType": "string",
            "sourceColumn": "kotikunta_fi",
            "sourceProviderType": "WChar"
          },
          {
            "name": "kotikunta_en",
            "dataType": "string",
            "sourceColumn": "kotikunta_en",
            "sourceProviderType": "WChar"
          },
          {
            "name": "kotikunta_sv",
            "dataType": "string",
            "sourceColumn": "kotikunta_sv",
            "sourceProviderType": "WChar"
          },
          {
            "name": "kotikunta_koodi",
            "dataType": "string",
            "sourceColumn": "kotikunta_koodi",
            "sourceProviderType": "WChar"
          },
          {
            "name": "ikä",
            "dataType": "int64",
            "sourceColumn": "ikä",
            "sourceProviderType": "Integer"
          },
          {
            "name": "ikäryhmä",
            "dataType": "string",
            "sourceColumn": "ikäryhmä",
            "sourceProviderType": "Char"
          },
          {
            "name": "aidinkieli_fi",
            "dataType": "string",
            "sourceColumn": "aidinkieli_fi",
            "sourceProviderType": "WChar"
          },
          {
            "name": "aidinkieli_en",
            "dataType": "string",
            "sourceColumn": "aidinkieli_en",
            "sourceProviderType": "WChar"
          },
          {
            "name": "aidinkieli_sv",
            "dataType": "string",
            "sourceColumn": "aidinkieli_sv",
            "sourceProviderType": "WChar"
          },
          {
            "name": "sukupuoli_fi",
            "dataType": "string",
            "sourceColumn": "sukupuoli_fi",
            "sourceProviderType": "Char"
          },
          {
            "name": "sukupuoli_en",
            "dataType": "string",
            "sourceColumn": "sukupuoli_en",
            "sourceProviderType": "WChar"
          },
          {
            "name": "sukupuoli_sv",
            "dataType": "string",
            "sourceColumn": "sukupuoli_sv",
            "sourceProviderType": "WChar"
          },
          {
            "name": "jarjestamismuoto_koodi",
            "dataType": "string",
            "sourceColumn": "jarjestamismuoto_koodi",
            "sourceProviderType": "WChar"
          },
          {
            "name": "jarjestamismuoto_fi",
            "dataType": "string",
            "sourceColumn": "jarjestamismuoto_fi",
            "sourceProviderType": "WChar"
          },
          {
            "name": "jarjestamismuoto_en",
            "dataType": "string",
            "sourceColumn": "jarjestamismuoto_en",
            "sourceProviderType": "WChar"
          },
          {
            "name": "jarjestamismuoto_sv",
            "dataType": "string",
            "sourceColumn": "jarjestamismuoto_sv",
            "sourceProviderType": "WChar"
          },
          {
            "name": "vuorohoito_kytkin_fi",
            "dataType": "string",
            "sourceColumn": "vuorohoito_kytkin_fi",
            "sourceProviderType": "WChar"
          },
          {
            "name": "vuorohoito_kytkin_en",
            "dataType": "string",
            "sourceColumn": "vuorohoito_kytkin_en",
            "sourceProviderType": "WChar"
          },
          {
            "name": "vuorohoito_kytkin_sv",
            "dataType": "string",
            "sourceColumn": "vuorohoito_kytkin_sv",
            "sourceProviderType": "WChar"
          },
          {
            "name": "kokopaivainen_vaka_kytkin_fi",
            "dataType": "string",
            "sourceColumn": "kokopaivainen_vaka_kytkin_fi",
            "sourceProviderType": "WChar"
          },
          {
            "name": "kokopaivainen_vaka_kytkin_en",
            "dataType": "string",
            "sourceColumn": "kokopaivainen_vaka_kytkin_en",
            "sourceProviderType": "WChar"
          },
          {
            "name": "kokopaivainen_vaka_kytkin_sv",
            "dataType": "string",
            "sourceColumn": "kokopaivainen_vaka_kytkin_sv",
            "sourceProviderType": "WChar"
          },
          {
            "name": "paivittainen_vaka_kytkin_fi",
            "dataType": "string",
            "sourceColumn": "paivittainen_vaka_kytkin_fi",
            "sourceProviderType": "WChar"
          },
          {
            "name": "paivittainen_vaka_kytkin_en",
            "dataType": "string",
            "sourceColumn": "paivittainen_vaka_kytkin_en",
            "sourceProviderType": "WChar"
          },
          {
            "name": "paivittainen_vaka_kytkin_sv",
            "dataType": "string",
            "sourceColumn": "paivittainen_vaka_kytkin_sv",
            "sourceProviderType": "WChar"
          },
          {
            "name": "pikakasittely_kytkin_fi",
            "dataType": "string",
            "sourceColumn": "pikakasittely_kytkin_fi",
            "sourceProviderType": "WChar"
          },
          {
            "name": "pikakasittely_kytkin_en",
            "dataType": "string",
            "sourceColumn": "pikakasittely_kytkin_en",
            "sourceProviderType": "WChar"
          },
          {
            "name": "pikakasittely_kytkin_sv",
            "dataType": "string",
            "sourceColumn": "pikakasittely_kytkin_sv",
            "sourceProviderType": "WChar"
          },
          {
            "name": "tuntimaara_viikossa",
            "dataType": "double",
            "sourceColumn": "tuntimaara_viikossa",
            "sourceProviderType": "Double"
          },
          {
            "name": "tuntimäärä_asteikko",
            "dataType": "string",
            "sourceColumn": "tuntimäärä_asteikko",
            "sourceProviderType": "Char"
          },
          {
            "name": "vakajarjestaja_nimi",
            "dataType": "string",
            "sourceColumn": "vakajarjestaja_nimi",
            "sourceProviderType": "WChar"
          },
          {
            "name": "yritysmuoto_fi",
            "dataType": "string",
            "sourceColumn": "yritysmuoto_fi",
            "sourceProviderType": "WChar"
          },
          {
            "name": "yritysmuoto_en",
            "dataType": "string",
            "sourceColumn": "yritysmuoto_en",
            "sourceProviderType": "WChar"
          },
          {
            "name": "yritysmuoto_sv",
            "dataType": "string",
            "sourceColumn": "yritysmuoto_sv",
            "sourceProviderType": "WChar"
          },
          {
            "name": "yritysmuoto_ryhma_fi",
            "dataType": "string",
            "sourceColumn": "yritysmuoto_ryhma_fi",
            "sourceProviderType": "WChar"
          },
          {
            "name": "yritystyyppi",
            "dataType": "string",
            "sourceColumn": "yritystyyppi",
            "sourceProviderType": "WChar"
          },
          {
            "name": "vakajarjestaja_kunta_fi",
            "dataType": "string",
            "sourceColumn": "vakajarjestaja_kunta_fi",
            "sourceProviderType": "WChar"
          },
          {
            "name": "vakajarjestaja_kunta_sv",
            "dataType": "string",
            "sourceColumn": "vakajarjestaja_kunta_sv",
            "sourceProviderType": "WChar"
          },
          {
            "name": "vakajarjestaja_kunta_en",
            "dataType": "string",
            "sourceColumn": "vakajarjestaja_kunta_en",
            "sourceProviderType": "WChar"
          },
          {
            "name": "toimipaikka_oid",
            "dataType": "string",
            "sourceColumn": "toimipaikka_oid",
            "sourceProviderType": "WChar"
          },
          {
            "name": "toimipaikka_maakunta_fi",
            "dataType": "string",
            "sourceColumn": "toimipaikka_maakunta_fi",
            "sourceProviderType": "WChar"
          },
          {
            "name": "toimipaikka_maakunta_en",
            "dataType": "string",
            "sourceColumn": "toimipaikka_maakunta_en",
            "sourceProviderType": "WChar"
          },
          {
            "name": "toimipaikka_maakunta_sv",
            "dataType": "string",
            "sourceColumn": "toimipaikka_maakunta_sv",
            "sourceProviderType": "WChar"
          },
          {
            "name": "toimipaikka_kunta_fi",
            "dataType": "string",
            "sourceColumn": "toimipaikka_kunta_fi",
            "sourceProviderType": "WChar"
          },
          {
            "name": "toimipaikka_kunta_en",
            "dataType": "string",
            "sourceColumn": "toimipaikka_kunta_en",
            "sourceProviderType": "WChar"
          },
          {
            "name": "toimipaikka_kunta_sv",
            "dataType": "string",
            "sourceColumn": "toimipaikka_kunta_sv",
            "sourceProviderType": "WChar"
          },
          {
            "name": "kasvatusopillinen_jarjestelma_fi",
            "dataType": "string",
            "sourceColumn": "kasvatusopillinen_jarjestelma_fi",
            "sourceProviderType": "WChar"
          },
          {
            "name": "kasvatusopillinen_jarjestelma_en",
            "dataType": "string",
            "sourceColumn": "kasvatusopillinen_jarjestelma_en",
            "sourceProviderType": "WChar"
          },
          {
            "name": "kasvatusopillinen_jarjestelma_sv",
            "dataType": "string",
            "sourceColumn": "kasvatusopillinen_jarjestelma_sv",
            "sourceProviderType": "WChar"
          },
          {
            "name": "toimintamuoto_fi",
            "dataType": "string",
            "sourceColumn": "toimintamuoto_fi",
            "sourceProviderType": "WChar"
          },
          {
            "name": "toimintamuoto_en",
            "dataType": "string",
            "sourceColumn": "toimintamuoto_en",
            "sourceProviderType": "WChar"
          },
          {
            "name": "toimintamuoto_sv",
            "dataType": "string",
            "sourceColumn": "toimintamuoto_sv",
            "sourceProviderType": "WChar"
          },
          {
            "name": "toimipaikkaluokitus_fi",
            "dataType": "string",
            "sourceColumn": "toimipaikkaluokitus_fi",
            "sourceProviderType": "WChar"
          },
          {
            "name": "toimipaikkaluokitus_en",
            "dataType": "string",
            "sourceColumn": "toimipaikkaluokitus_en",
            "sourceProviderType": "WChar"
          },
          {
            "name": "toimipaikkaluokitus_sv",
            "dataType": "string",
            "sourceColumn": "toimipaikkaluokitus_sv",
            "sourceProviderType": "WChar"
          },
          {
            "name": "tuntimäärä_asteikko_jarj",
            "dataType": "int64",
            "sourceColumn": "tuntimäärä_asteikko_jarj",
            "sourceProviderType": "Integer"
          },
          {
            "name": "ikäryhmä_jarj",
            "dataType": "int64",
            "sourceColumn": "ikäryhmä_jarj",
            "sourceProviderType": "Integer"
          },
          {
            "name": "maksutieto_id",
            "dataType": "string",
            "sourceColumn": "maksutieto_id",
            "sourceProviderType": "WChar"
          },
          {
            "name": "maksun_peruste_fi",
            "dataType": "string",
            "sourceColumn": "maksun_peruste_fi",
            "sourceProviderType": "WChar"
          },
          {
            "name": "maksun_peruste_en",
            "dataType": "string",
            "sourceColumn": "maksun_peruste_en",
            "sourceProviderType": "WChar"
          },
          {
            "name": "maksun_peruste_sv",
            "dataType": "string",
            "sourceColumn": "maksun_peruste_sv",
            "sourceProviderType": "WChar"
          },
          {
            "name": "maksun_luokka_fi",
            "dataType": "string",
            "sourceColumn": "maksun_luokka_fi",
            "sourceProviderType": "WChar"
          },
          {
            "name": "maksun_luokka_en",
            "dataType": "string",
            "sourceColumn": "maksun_luokka_en",
            "sourceProviderType": "WChar"
          },
          {
            "name": "maksun_luokka_sv",
            "dataType": "string",
            "sourceColumn": "maksun_luokka_sv",
            "sourceProviderType": "WChar"
          },
          {
            "name": "maksun_luokka_jarjestys_nro",
            "dataType": "int64",
            "sourceColumn": "maksun_luokka_jarjestys_nro",
            "sourceProviderType": "Integer"
          },
          {
            "name": "palveluseteli_arvo",
            "dataType": "double",
            "sourceColumn": "palveluseteli_arvo",
            "sourceProviderType": "Double"
          },
          {
            "name": "asiakasmaksu",
            "dataType": "double",
            "sourceColumn": "asiakasmaksu",
            "sourceProviderType": "Double"
          },
          {
            "name": "perheen_koko",
            "dataType": "int64",
            "sourceColumn": "perheen_koko",
            "sourceProviderType": "Integer"
          },
          {
            "name": "cum_sum",
            "dataType": "double",
            "sourceColumn": "cum_sum",
            "sourceProviderType": "Double"
          },
          {
            "name": "tilastovuosi_oid",
            "dataType": "string",
            "sourceColumn": "tilastovuosi_oid",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Väestö",
            "dataType": "int64",
            "sourceColumn": "Väestö",
            "sourceProviderType": "Integer"
          }
        ],
        "partitions": [
          {
            "name": "v_varda_varhaiskasvatustiedot",
            "dataView": "full",
            "source": {
              "query": " SELECT [dw].[v_varda_varhaiskasvatustiedot].* FROM [dw].[v_varda_varhaiskasvatustiedot] ",
              "dataSource": "SqlServer dwitvipusql16 Antero 2"
            }
          }
        ],
        "measures": [
          {
            "name": "Lasten lukumäärä",
            "expression": [
              "",
              "var lkm = calculate(DISTINCTCOUNT(Muuttujat[henkilo_id]),Muuttujat[henkilo_id]<>BLANK())",
              "return IF(lkm = 0, BLANK(), IF(lkm < 5, \"1-4\", MROUND(lkm, 3)))"
            ],
            "formatString": "#,0",
            "displayFolder": "Mittarit"
          },
          {
            "name": "poikia",
            "expression": [
              "",
              "var summa = COUNTROWS(FILTER(GROUPBY(Muuttujat,[henkilo_id],Muuttujat[sukupuoli_fi]), Muuttujat[sukupuoli_fi]=\"Mies\"))",
              "return IF(summa = 0, BLANK(), IF(summa < 5, \"\", MROUND(summa, 3)))"
            ],
            "formatString": "#,0",
            "displayFolder": "Mittarit"
          },
          {
            "name": "tyttöjä",
            "expression": [
              "",
              "var summa = COUNTROWS(FILTER(GROUPBY(Muuttujat,[henkilo_id],Muuttujat[sukupuoli_fi]), Muuttujat[sukupuoli_fi]=\"Nainen\"))",
              "return IF(summa = 0, BLANK(), IF(summa < 5, \"\", MROUND(summa, 3)))"
            ],
            "formatString": "#,0",
            "displayFolder": "Mittarit"
          },
          {
            "name": "Lasten osuus varhaiskasvatuksessa",
            "expression": [
              "",
              "var osa = [Lasten lukumäärä]",
              "var kaikki = [Väestö summa]",
              "return IF(kaikki=BLANK(),BLANK(),",
              "IF(osa = BLANK(), BLANK(),",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, 0,",
              "CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki))))"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Mittarit"
          },
          {
            "name": "Väestö summa",
            "expression": [
              "",
              "var lkm = if([Lasten lukumäärä]=BLANK(),BLANK(),CALCULATE(SUM(Muuttujat[Väestö]),ALLEXCEPT(Muuttujat,",
              "Muuttujat[tilastovuosi],Muuttujat[kotikunta_fi],Muuttujat[kotikunta_en],Muuttujat[kotikunta_sv],Muuttujat[kotikunta_koodi],Muuttujat[ikä],Muuttujat[ikäryhmä],Muuttujat[sukupuoli_fi],Muuttujat[sukupuoli_en],Muuttujat[sukupuoli_sv])))",
              "return IF(lkm = 0, BLANK(), IF(lkm < 5, \"1-4\", MROUND(lkm, 3)))"
            ],
            "formatString": "#,0",
            "isHidden": true
          },
          {
            "name": "Kuntien asiakasmaksu min",
            "expression": "ROUND(MINX(FILTER(Muuttujat, [jarjestamismuoto_koodi] = \"JM01\" ||  [jarjestamismuoto_koodi] = \"JM02\" || [jarjestamismuoto_koodi] = \"JM03\"),[asiakasmaksu]), 0)",
            "displayFolder": "Mittarit"
          },
          {
            "name": "Kuntien asiakasmaksu max",
            "expression": "ROUND(MAXX(FILTER(Muuttujat, [jarjestamismuoto_koodi] = \"JM01\" ||  [jarjestamismuoto_koodi] = \"JM02\" || [jarjestamismuoto_koodi] = \"JM03\"),[asiakasmaksu]), 0)",
            "displayFolder": "Mittarit"
          },
          {
            "name": "Kuntien asiakasmaksu mediaani",
            "expression": " ROUND(MEDIANX(FILTER(Muuttujat,  [jarjestamismuoto_koodi] = \"JM01\" || [jarjestamismuoto_koodi] = \"JM02\" || [jarjestamismuoto_koodi] = \"JM03\" && [asiakasmaksu] <> BLANK()),[asiakasmaksu]), 0)",
            "displayFolder": "Mittarit"
          },
          {
            "name": "Kuntien asiakasmaksu keskiarvo",
            "expression": "ROUND(AVERAGEX(FILTER(Muuttujat, [jarjestamismuoto_koodi] = \"JM01\" ||  [jarjestamismuoto_koodi] = \"JM02\" || [jarjestamismuoto_koodi] = \"JM03\"),[asiakasmaksu]), 0)",
            "displayFolder": "Mittarit"
          },
          {
            "name": "Yksityisten asiakasmaksu min",
            "expression": "ROUND(MINX(FILTER(Muuttujat, [jarjestamismuoto_koodi] = \"JM04\" || [jarjestamismuoto_koodi] = \"JM05\"),[asiakasmaksu]), 0)",
            "displayFolder": "Mittarit"
          },
          {
            "name": "Yksityisten asiakasmaksu max",
            "expression": "ROUND(MAXX(FILTER(Muuttujat, [jarjestamismuoto_koodi] = \"JM04\" || [jarjestamismuoto_koodi] = \"JM05\"),[asiakasmaksu]), 0)",
            "displayFolder": "Mittarit"
          },
          {
            "name": "Yksityisten asiakasmaksu mediaani",
            "expression": "ROUND(MEDIANX(FILTER(Muuttujat,  [jarjestamismuoto_koodi] = \"JM04\" || [jarjestamismuoto_koodi] = \"JM05\"),[asiakasmaksu]), 0)",
            "displayFolder": "Mittarit"
          },
          {
            "name": "Yksityisten asiakasmaksu keskiarvo",
            "expression": "ROUND(AVERAGEX(FILTER(Muuttujat,  [jarjestamismuoto_koodi] = \"JM04\" || [jarjestamismuoto_koodi] = \"JM05\"),[asiakasmaksu]), 0)",
            "displayFolder": "Mittarit"
          },
          {
            "name": "Kunnallisia lapsia",
            "expression": [
              "",
              "var summa = Calculate(DISTINCTCOUNT([henkilo_id]), FILTER(Muuttujat, [jarjestamismuoto_koodi]=\"JM01\" ||  [jarjestamismuoto_koodi] = \"JM02\" || [jarjestamismuoto_koodi] = \"JM03\"))",
              "return IF(summa = 0, BLANK(), IF(summa < 5, \"\", MROUND(summa, 3)))",
              ""
            ],
            "displayFolder": "Mittarit"
          },
          {
            "name": "Kunnallisia maksuja",
            "expression": [
              "",
              "var summa =  Calculate(DISTINCTCOUNT([maksutieto_id]), FILTER(Muuttujat, [jarjestamismuoto_koodi] = \"JM01\" ||  [jarjestamismuoto_koodi] = \"JM02\" || [jarjestamismuoto_koodi] = \"JM03\"))",
              "return IF(summa = 0, BLANK(), IF(summa < 5, \"\", MROUND(summa, 3)))",
              ""
            ],
            "displayFolder": "Mittarit"
          },
          {
            "name": "Yksityisiä lapsia",
            "expression": [
              "",
              "var summa =  Calculate(DISTINCTCOUNT([henkilo_id]), Muuttujat[jarjestamismuoto_koodi] = \"JM04\" || Muuttujat[jarjestamismuoto_koodi] = \"JM05\")",
              "return IF(summa = 0, BLANK(), IF(summa < 5, \"\", MROUND(summa, 3)))",
              ""
            ],
            "displayFolder": "Mittarit"
          },
          {
            "name": "Yksityisiä maksuja",
            "expression": [
              "",
              "var summa =   Calculate(DISTINCTCOUNT([maksutieto_id]), Muuttujat[jarjestamismuoto_koodi] = \"JM04\" || Muuttujat[jarjestamismuoto_koodi] = \"JM05\",Muuttujat[yritystyyppi]=\"Yksityinen\")",
              "return IF(summa = 0, BLANK(), IF(summa < 5, \"\", MROUND(summa, 3)))"
            ],
            "displayFolder": "Mittarit"
          },
          {
            "name": "Palveluseteli min",
            "expression": "ROUND(MINX(FILTER(Muuttujat, [jarjestamismuoto_koodi] = \"JM02\" || [jarjestamismuoto_koodi] = \"JM03\"),[palveluseteli_arvo]), 0)"
          },
          {
            "name": "Palveluseteli max",
            "expression": "ROUND(MAXX(FILTER(Muuttujat, [jarjestamismuoto_koodi] = \"JM02\" || [jarjestamismuoto_koodi] = \"JM03\"),[palveluseteli_arvo]), 0)"
          },
          {
            "name": "Palveluseteli mediaani",
            "expression": "ROUND(MEDIANX(FILTER(Muuttujat, [jarjestamismuoto_koodi] = \"JM02\" || [jarjestamismuoto_koodi] = \"JM03\"),[palveluseteli_arvo]), 0)"
          },
          {
            "name": "Palveluseteli keskiarvo",
            "expression": "ROUND(AVERAGEX(FILTER(Muuttujat, [jarjestamismuoto_koodi] = \"JM02\" || [jarjestamismuoto_koodi] = \"JM03\"),[palveluseteli_arvo]), 0)"
          },
          {
            "name": "Palvelusetelillä lapsia",
            "expression": [
              "",
              " var summa = Calculate(DISTINCTCOUNT([henkilo_id]), FILTER(Muuttujat, [jarjestamismuoto_koodi] = \"JM02\" || [jarjestamismuoto_koodi] = \"JM03\"))",
              "return IF(summa = 0, BLANK(), IF(summa < 5, \"\", MROUND(summa, 3)))",
              ""
            ]
          },
          {
            "name": "Palvelusetelillä maksuja",
            "expression": [
              "",
              "var summa =  Calculate(DISTINCTCOUNT([maksutieto_id]), FILTER(Muuttujat, [jarjestamismuoto_koodi] = \"JM02\" || [jarjestamismuoto_koodi] = \"JM03\"))",
              "return IF(summa = 0, BLANK(), IF(summa < 5, \"\", MROUND(summa, 3)))",
              ""
            ]
          },
          {
            "name": "Asiakasmaksun keskiarvo",
            "expression": "ROUND(AVERAGEX(FILTER(Muuttujat, [jarjestamismuoto_koodi] = \"JM02\" || [jarjestamismuoto_koodi] = \"JM03\"),[asiakasmaksu]), 0)"
          },
          {
            "name": "% osuus kunnan lapsista",
            "expression": " Format(DIVIDE([Palvelusetelillä lapsia_s], [Kunnallisia lapsia_s]), \"0.0 %\")"
          },
          {
            "name": "Palvelusetelillä lapsia_s",
            "expression": [
              " Calculate(DISTINCTCOUNT([henkilo_id]), FILTER(Muuttujat, [jarjestamismuoto_koodi] = \"JM02\" || [jarjestamismuoto_koodi] = \"JM03\"))",
              "",
              ""
            ],
            "isHidden": true
          },
          {
            "name": "Kunnallisia lapsia_s",
            "expression": " Calculate(DISTINCTCOUNT([henkilo_id]), FILTER(Muuttujat, [jarjestamismuoto_koodi]=\"JM01\" ||  [jarjestamismuoto_koodi] = \"JM02\" || [jarjestamismuoto_koodi] = \"JM03\"))",
            "isHidden": true
          },
          {
            "name": "Kunnallisen vakan kumulatiivinen summa",
            "expression": [
              " ",
              "CALCULATe([henkilo_cum_sum], filter(Muuttujat, [jarjestamismuoto_koodi]= \"JM01\" || [jarjestamismuoto_koodi] = \"JM02\" || [jarjestamismuoto_koodi] = \"JM03\"))"
            ]
          },
          {
            "name": "Palveluseteli ja ostopalvelun kumulatiivinen summa",
            "expression": " CALCULATE( sumx(VALUES(Muuttujat[cum_sum]), calculate(MAX([cum_sum]),GROUPBY(Muuttujat,[henkilo_id],[cum_sum]))), filter(Muuttujat, [jarjestamismuoto_koodi] = \"JM02\" || [jarjestamismuoto_koodi] = \"JM03\"))"
          },
          {
            "name": "Yksityisen vakan kumulatiivinen summa",
            "expression": " CALCULATE([henkilo_cum_sum], filter(Muuttujat, [jarjestamismuoto_koodi] = \"JM04\" || [jarjestamismuoto_koodi] = \"JM05\"))"
          },
          {
            "name": "henkilo_cum_sum",
            "expression": " SUMX(SUMMARIZE(Muuttujat,[henkilo_id],[cum_sum]),[cum_sum])",
            "isHidden": true
          },
          {
            "name": "Yksityisiä lapsia (ml. palveluseteli ja ostopalvelu)",
            "expression": [
              "",
              "var summa =  Calculate(DISTINCTCOUNT([henkilo_id]),  Muuttujat[jarjestamismuoto_koodi] = \"JM02\" || Muuttujat[jarjestamismuoto_koodi] = \"JM03\" || Muuttujat[jarjestamismuoto_koodi] = \"JM04\" || Muuttujat[jarjestamismuoto_koodi] = \"JM05\")",
              "return IF(summa = 0, BLANK(), IF(summa < 5, \"\", MROUND(summa, 3)))",
              ""
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dw].[v_varda_varhaiskasvatustiedot].* FROM [dw].[v_varda_varhaiskasvatustiedot] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "v_varda_varhaiskasvatustiedot"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dw"
          }
        ]
      }
    ],
    "cultures": [
      {
        "name": "fi-FI",
        "translations": {
          "model": {
            "name": "Model",
            "tables": [
              {
                "name": "Muuttujat",
                "translatedCaption": "Muuttujat",
                "columns": [
                  {
                    "name": "tilastovuosi",
                    "translatedCaption": "Tilastovuosi",
                    "translatedDisplayFolder": "Aikamuuttujat"
                  },
                  {
                    "name": "kotikunta_fi",
                    "translatedCaption": "Kotikunta",
                    "translatedDisplayFolder": "Henkilömuuttujat"
                  },
                  {
                    "name": "kotikunta_en",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Henkilömuuttujat"
                  },
                  {
                    "name": "kotikunta_sv",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Henkilömuuttujat"
                  },
                  {
                    "name": "kotikunta_koodi",
                    "translatedCaption": "Kotikuntakoodi",
                    "translatedDisplayFolder": "Koodimuuttujat"
                  },
                  {
                    "name": "ikä",
                    "translatedCaption": "Ikä",
                    "translatedDisplayFolder": "Henkilömuuttujat"
                  },
                  {
                    "name": "ikäryhmä",
                    "translatedCaption": "Ikäryhmä",
                    "translatedDisplayFolder": "Henkilömuuttujat"
                  },
                  {
                    "name": "aidinkieli_fi",
                    "translatedCaption": "Äidinkieli",
                    "translatedDisplayFolder": "Henkilömuuttujat"
                  },
                  {
                    "name": "aidinkieli_en",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Henkilömuuttujat"
                  },
                  {
                    "name": "aidinkieli_sv",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Henkilömuuttujat"
                  },
                  {
                    "name": "sukupuoli_fi",
                    "translatedCaption": "Sukupuoli",
                    "translatedDisplayFolder": "Henkilömuuttujat"
                  },
                  {
                    "name": "sukupuoli_en",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Henkilömuuttujat"
                  },
                  {
                    "name": "sukupuoli_sv",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Henkilömuuttujat"
                  },
                  {
                    "name": "jarjestamismuoto_koodi",
                    "translatedCaption": "Järjestämismuotokoodi",
                    "translatedDisplayFolder": "Koodimuuttujat"
                  },
                  {
                    "name": "jarjestamismuoto_fi",
                    "translatedCaption": "Järjestämismuoto",
                    "translatedDisplayFolder": "Koulutusmuuttujat"
                  },
                  {
                    "name": "jarjestamismuoto_en",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Koulutusmuuttujat"
                  },
                  {
                    "name": "jarjestamismuoto_sv",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Koulutusmuuttujat"
                  },
                  {
                    "name": "vuorohoito_kytkin_fi",
                    "translatedCaption": "Vuorohoitokytkin",
                    "translatedDisplayFolder": "Koulutusmuuttujat"
                  },
                  {
                    "name": "vuorohoito_kytkin_en",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Koulutusmuuttujat"
                  },
                  {
                    "name": "vuorohoito_kytkin_sv",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Koulutusmuuttujat"
                  },
                  {
                    "name": "kokopaivainen_vaka_kytkin_fi",
                    "translatedCaption": "Kokopäiväinen varhaiskasvatus",
                    "translatedDisplayFolder": "Koodimuuttujat"
                  },
                  {
                    "name": "kokopaivainen_vaka_kytkin_en",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Koodimuuttujat"
                  },
                  {
                    "name": "kokopaivainen_vaka_kytkin_sv",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Koodimuuttujat"
                  },
                  {
                    "name": "paivittainen_vaka_kytkin_fi",
                    "translatedCaption": "Päivittäinen varhaiskasvatus",
                    "translatedDisplayFolder": "Henkilömuuttujat"
                  },
                  {
                    "name": "paivittainen_vaka_kytkin_en",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Henkilömuuttujat"
                  },
                  {
                    "name": "paivittainen_vaka_kytkin_sv",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Henkilömuuttujat"
                  },
                  {
                    "name": "pikakasittely_kytkin_fi",
                    "translatedCaption": "Pikakäsittely kytkin"
                  },
                  {
                    "name": "pikakasittely_kytkin_en",
                    "translatedCaption": "."
                  },
                  {
                    "name": "pikakasittely_kytkin_sv",
                    "translatedCaption": "."
                  },
                  {
                    "name": "tuntimaara_viikossa",
                    "translatedCaption": "Tuntimäärä viikossa",
                    "translatedDisplayFolder": "Henkilömuuttujat"
                  },
                  {
                    "name": "tuntimäärä_asteikko",
                    "translatedCaption": "Tuntimäärä asteikko",
                    "translatedDisplayFolder": "Henkilömuuttujat"
                  },
                  {
                    "name": "vakajarjestaja_nimi",
                    "translatedCaption": "Varhaiskasvatustoimijan nimi",
                    "translatedDisplayFolder": "Koulutusmuuttujat"
                  },
                  {
                    "name": "yritysmuoto_fi",
                    "translatedCaption": "Yritysmuoto",
                    "translatedDisplayFolder": "Koulutusmuuttujat"
                  },
                  {
                    "name": "yritysmuoto_en",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Koulutusmuuttujat"
                  },
                  {
                    "name": "yritysmuoto_sv",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Koulutusmuuttujat"
                  },
                  {
                    "name": "yritysmuoto_ryhma_fi",
                    "translatedCaption": "Yritysmuotoryhmä",
                    "translatedDisplayFolder": "Koulutusmuuttujat"
                  },
                  {
                    "name": "yritystyyppi",
                    "translatedCaption": "Yritystyyppi",
                    "translatedDisplayFolder": "Koulutusmuuttujat"
                  },
                  {
                    "name": "vakajarjestaja_kunta_fi",
                    "translatedCaption": "Varhaiskasvatustoimijan kunta",
                    "translatedDisplayFolder": "Koulutusmuuttujat"
                  },
                  {
                    "name": "vakajarjestaja_kunta_sv",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Koulutusmuuttujat"
                  },
                  {
                    "name": "vakajarjestaja_kunta_en",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Koulutusmuuttujat"
                  },
                  {
                    "name": "toimipaikka_maakunta_fi",
                    "translatedCaption": "Toimipaikan maakunta",
                    "translatedDisplayFolder": "Koulutusmuuttujat"
                  },
                  {
                    "name": "toimipaikka_maakunta_en",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Koulutusmuuttujat"
                  },
                  {
                    "name": "toimipaikka_maakunta_sv",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Koulutusmuuttujat"
                  },
                  {
                    "name": "toimipaikka_kunta_fi",
                    "translatedCaption": "Toimipaikan kunta",
                    "translatedDisplayFolder": "Koulutusmuuttujat"
                  },
                  {
                    "name": "toimipaikka_kunta_en",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Koulutusmuuttujat"
                  },
                  {
                    "name": "toimipaikka_kunta_sv",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Koulutusmuuttujat"
                  },
                  {
                    "name": "kasvatusopillinen_jarjestelma_fi",
                    "translatedCaption": "Kasvatusopillinen järjestelmä",
                    "translatedDisplayFolder": "Koodimuuttujat"
                  },
                  {
                    "name": "kasvatusopillinen_jarjestelma_en",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Koodimuuttujat"
                  },
                  {
                    "name": "kasvatusopillinen_jarjestelma_sv",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Koodimuuttujat"
                  },
                  {
                    "name": "toimintamuoto_fi",
                    "translatedCaption": "Toimintamuoto",
                    "translatedDisplayFolder": "Koulutusmuuttujat"
                  },
                  {
                    "name": "toimintamuoto_en",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Koulutusmuuttujat"
                  },
                  {
                    "name": "toimintamuoto_sv",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Koulutusmuuttujat"
                  },
                  {
                    "name": "toimipaikkaluokitus_fi",
                    "translatedCaption": "Toimipaikkaluokitus",
                    "translatedDisplayFolder": "Koulutusmuuttujat"
                  },
                  {
                    "name": "toimipaikkaluokitus_en",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Koulutusmuuttujat"
                  },
                  {
                    "name": "toimipaikkaluokitus_sv",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Koulutusmuuttujat"
                  },
                  {
                    "name": "maksutieto_id",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Koulutusmuuttujat"
                  },
                  {
                    "name": "maksun_peruste_fi",
                    "translatedCaption": "Maksun peruste",
                    "translatedDisplayFolder": "Henkilömuuttujat"
                  },
                  {
                    "name": "maksun_peruste_en",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Henkilömuuttujat"
                  },
                  {
                    "name": "maksun_peruste_sv",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Henkilömuuttujat"
                  },
                  {
                    "name": "maksun_luokka_fi",
                    "translatedCaption": "Maksun luokka",
                    "translatedDisplayFolder": "Henkilömuuttujat"
                  },
                  {
                    "name": "maksun_luokka_en",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Henkilömuuttujat"
                  },
                  {
                    "name": "maksun_luokka_sv",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Henkilömuuttujat"
                  },
                  {
                    "name": "palveluseteli_arvo",
                    "translatedCaption": "Palvelusetelin arvo"
                  },
                  {
                    "name": "asiakasmaksu",
                    "translatedCaption": "Asiakasmaksu"
                  },
                  {
                    "name": "perheen_koko",
                    "translatedCaption": "Perheen koko"
                  },
                  {
                    "name": "cum_sum",
                    "translatedCaption": "Kumulatiivinen summa"
                  }
                ],
                "measures": [
                  {
                    "name": "Lasten lukumäärä",
                    "translatedCaption": "Lasten lukumäärä"
                  },
                  {
                    "name": "poikia",
                    "translatedCaption": "Poikia"
                  },
                  {
                    "name": "tyttöjä",
                    "translatedCaption": "Tyttöjä"
                  },
                  {
                    "name": "Lasten osuus varhaiskasvatuksessa",
                    "translatedCaption": "Lasten osuus varhaiskasvatuksessa"
                  },
                  {
                    "name": "Kuntien asiakasmaksu min",
                    "translatedCaption": "Kuntien asiakasmaksun minimiarvo"
                  },
                  {
                    "name": "Kuntien asiakasmaksu max",
                    "translatedCaption": "Kuntien asiakasmaksun maksimiarvo"
                  },
                  {
                    "name": "Kuntien asiakasmaksu mediaani",
                    "translatedCaption": "Kuntien asiakasmaksun mediaani"
                  },
                  {
                    "name": "Kuntien asiakasmaksu keskiarvo",
                    "translatedCaption": "Kuntien asiakasmaksujen keskiarvo"
                  },
                  {
                    "name": "Yksityisten asiakasmaksu min",
                    "translatedCaption": "Yksityisten asiakasmaksujen minimiarvo"
                  },
                  {
                    "name": "Yksityisten asiakasmaksu max",
                    "translatedCaption": "Yksityisten asiakasmaksujen maksimiarvo"
                  },
                  {
                    "name": "Yksityisten asiakasmaksu mediaani",
                    "translatedCaption": "Yksityisten asiakasmaksujen mediaani"
                  },
                  {
                    "name": "Yksityisten asiakasmaksu keskiarvo",
                    "translatedCaption": "Yksityisten asiakasmaksujen keskiarvo"
                  },
                  {
                    "name": "Kunnallisia lapsia",
                    "translatedCaption": "Kunnallisia lapsia"
                  },
                  {
                    "name": "Kunnallisia maksuja",
                    "translatedCaption": "Kunnallisia maksuja"
                  },
                  {
                    "name": "Yksityisiä lapsia",
                    "translatedCaption": "Yksityisiä lapsia"
                  },
                  {
                    "name": "Yksityisiä maksuja",
                    "translatedCaption": "Yksityisiä maksuja"
                  },
                  {
                    "name": "Palveluseteli min",
                    "translatedCaption": "Palvelusetelin minimiarvo"
                  },
                  {
                    "name": "Palveluseteli max",
                    "translatedCaption": "Palvelusetelin maksimiarvo"
                  },
                  {
                    "name": "Palveluseteli mediaani",
                    "translatedCaption": "Palvelusetelin mediaani"
                  },
                  {
                    "name": "Palveluseteli keskiarvo",
                    "translatedCaption": "Palvelusetelin keskiarvo"
                  },
                  {
                    "name": "Palvelusetelillä lapsia",
                    "translatedCaption": "Palvelusetelillä lapsia"
                  },
                  {
                    "name": "Palvelusetelillä maksuja",
                    "translatedCaption": "Palvelusetelillä maksuja"
                  },
                  {
                    "name": "Asiakasmaksun keskiarvo",
                    "translatedCaption": "Asiakasmaksun keskiarvo"
                  },
                  {
                    "name": "% osuus kunnan lapsista",
                    "translatedCaption": "% osuus kunnan lapsista"
                  },
                  {
                    "name": "Palvelusetelillä lapsia_s",
                    "translatedCaption": "Palvelusetelillä lapsia_s"
                  },
                  {
                    "name": "Kunnallisia lapsia_s",
                    "translatedCaption": "Kunnallisia lapsia_s"
                  },
                  {
                    "name": "Kunnallisen vakan kumulatiivinen summa",
                    "translatedCaption": "Kunnallisen varhaiskasvatuksen kumulatiivinen summa"
                  },
                  {
                    "name": "Palveluseteli ja ostopalvelun kumulatiivinen summa",
                    "translatedCaption": "Palveluseteli ja ostopalvelun kumulatiivinen summa",
                    "translatedDisplayFolder": "Henkilömuuttujat"
                  },
                  {
                    "name": "Yksityisen vakan kumulatiivinen summa",
                    "translatedCaption": "Yksityisen varhaiskasvatuksen kumulatiivinen summa"
                  },
                  {
                    "name": "henkilo_cum_sum",
                    "translatedCaption": "Henkilön kumulatiivinen summa"
                  },
                  {
                    "name": "Yksityisiä lapsia (ml. palveluseteli ja ostopalvelu)",
                    "translatedCaption": "Yksityisiä lapsia (ml. palveluseteli ja ostopalvelu)"
                  }
                ]
              }
            ]
          }
        }
      },
      {
        "name": "sv-SE",
        "translations": {
          "model": {
            "name": "Model",
            "tables": [
              {
                "name": "Muuttujat",
                "translatedCaption": "Variabler",
                "columns": [
                  {
                    "name": "tilastovuosi",
                    "translatedCaption": "Statistikår",
                    "translatedDisplayFolder": "Tidsvariabler"
                  },
                  {
                    "name": "kotikunta_fi",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Tidsvariabler"
                  },
                  {
                    "name": "kotikunta_en",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Tidsvariabler"
                  },
                  {
                    "name": "kotikunta_sv",
                    "translatedCaption": "Käännös puuttuu",
                    "translatedDisplayFolder": "Personvariabler"
                  },
                  {
                    "name": "kotikunta_koodi",
                    "translatedCaption": "Käännös puuttuu",
                    "translatedDisplayFolder": "Kodvariabler"
                  },
                  {
                    "name": "ikä",
                    "translatedCaption": "Ålder",
                    "translatedDisplayFolder": "Personvariabler"
                  },
                  {
                    "name": "ikäryhmä",
                    "translatedCaption": "Ålder grupp",
                    "translatedDisplayFolder": "Personvariabler"
                  },
                  {
                    "name": "aidinkieli_fi",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Personvariabler"
                  },
                  {
                    "name": "aidinkieli_en",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Personvariabler"
                  },
                  {
                    "name": "aidinkieli_sv",
                    "translatedCaption": "Modersmål",
                    "translatedDisplayFolder": "Personvariabler"
                  },
                  {
                    "name": "sukupuoli_fi",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Personvariabler"
                  },
                  {
                    "name": "sukupuoli_en",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Personvariabler"
                  },
                  {
                    "name": "sukupuoli_sv",
                    "translatedCaption": "Kön",
                    "translatedDisplayFolder": "Personvariabler"
                  },
                  {
                    "name": "jarjestamismuoto_koodi",
                    "translatedCaption": "Käännös puuttuu",
                    "translatedDisplayFolder": "Kodvariabler"
                  },
                  {
                    "name": "jarjestamismuoto_fi",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Personvariabler"
                  },
                  {
                    "name": "jarjestamismuoto_en",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Personvariabler"
                  },
                  {
                    "name": "jarjestamismuoto_sv",
                    "translatedCaption": "Formen i vilken utbildningen anordnas",
                    "translatedDisplayFolder": "Utbildningsvariabler"
                  },
                  {
                    "name": "vuorohoito_kytkin_fi",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Utbildningsvariabler"
                  },
                  {
                    "name": "vuorohoito_kytkin_en",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Utbildningsvariabler"
                  },
                  {
                    "name": "vuorohoito_kytkin_sv",
                    "translatedCaption": "Käännös puuttuu",
                    "translatedDisplayFolder": "Utbildningsvariabler"
                  },
                  {
                    "name": "kokopaivainen_vaka_kytkin_fi",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Utbildningsvariabler"
                  },
                  {
                    "name": "kokopaivainen_vaka_kytkin_en",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Utbildningsvariabler"
                  },
                  {
                    "name": "kokopaivainen_vaka_kytkin_sv",
                    "translatedCaption": "Käännös puuttuu",
                    "translatedDisplayFolder": "Kodvariabler"
                  },
                  {
                    "name": "paivittainen_vaka_kytkin_fi",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Kodvariabler"
                  },
                  {
                    "name": "paivittainen_vaka_kytkin_en",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Kodvariabler"
                  },
                  {
                    "name": "paivittainen_vaka_kytkin_sv",
                    "translatedCaption": "Käännös puuttuu",
                    "translatedDisplayFolder": "Personvariabler"
                  },
                  {
                    "name": "pikakasittely_kytkin_fi",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Personvariabler"
                  },
                  {
                    "name": "pikakasittely_kytkin_en",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Personvariabler"
                  },
                  {
                    "name": "pikakasittely_kytkin_sv",
                    "translatedCaption": "Käännös puuttuu"
                  },
                  {
                    "name": "tuntimaara_viikossa",
                    "translatedCaption": "Käännös puuttuu",
                    "translatedDisplayFolder": "Personvariabler"
                  },
                  {
                    "name": "tuntimäärä_asteikko",
                    "translatedCaption": "Käännös puuttuu",
                    "translatedDisplayFolder": "Personvariabler"
                  },
                  {
                    "name": "vakajarjestaja_nimi",
                    "translatedCaption": "Käännös puuttuu",
                    "translatedDisplayFolder": "Utbildningsvariabler"
                  },
                  {
                    "name": "yritysmuoto_fi",
                    "translatedCaption": "."
                  },
                  {
                    "name": "yritysmuoto_en",
                    "translatedCaption": "."
                  },
                  {
                    "name": "yritysmuoto_sv",
                    "translatedCaption": "Käännös puuttuu",
                    "translatedDisplayFolder": "Utbildningsvariabler"
                  },
                  {
                    "name": "yritysmuoto_ryhma_fi",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Personvariabler"
                  },
                  {
                    "name": "yritystyyppi",
                    "translatedCaption": "Käännös puuttuu",
                    "translatedDisplayFolder": "Utbildningsvariabler"
                  },
                  {
                    "name": "vakajarjestaja_kunta_fi",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Utbildningsvariabler"
                  },
                  {
                    "name": "vakajarjestaja_kunta_sv",
                    "translatedCaption": "Käännös puuttuu",
                    "translatedDisplayFolder": "Utbildningsvariabler"
                  },
                  {
                    "name": "vakajarjestaja_kunta_en",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Utbildningsvariabler"
                  },
                  {
                    "name": "toimipaikka_maakunta_fi",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Utbildningsvariabler"
                  },
                  {
                    "name": "toimipaikka_maakunta_en",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Utbildningsvariabler"
                  },
                  {
                    "name": "toimipaikka_maakunta_sv",
                    "translatedCaption": "Käännös puuttuu",
                    "translatedDisplayFolder": "Utbildningsvariabler"
                  },
                  {
                    "name": "toimipaikka_kunta_fi",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Utbildningsvariabler"
                  },
                  {
                    "name": "toimipaikka_kunta_en",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Utbildningsvariabler"
                  },
                  {
                    "name": "toimipaikka_kunta_sv",
                    "translatedCaption": "Käännös puuttuu",
                    "translatedDisplayFolder": "Utbildningsvariabler"
                  },
                  {
                    "name": "kasvatusopillinen_jarjestelma_fi",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Utbildningsvariabler"
                  },
                  {
                    "name": "kasvatusopillinen_jarjestelma_en",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Utbildningsvariabler"
                  },
                  {
                    "name": "kasvatusopillinen_jarjestelma_sv",
                    "translatedCaption": "Käännös puuttuu",
                    "translatedDisplayFolder": "Kodvariabler"
                  },
                  {
                    "name": "toimintamuoto_fi",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Kodvariabler"
                  },
                  {
                    "name": "toimintamuoto_en",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Kodvariabler"
                  },
                  {
                    "name": "toimintamuoto_sv",
                    "translatedCaption": "Käännös puuttuu",
                    "translatedDisplayFolder": "Utbildningsvariabler"
                  },
                  {
                    "name": "toimipaikkaluokitus_fi",
                    "translatedCaption": "."
                  },
                  {
                    "name": "toimipaikkaluokitus_en",
                    "translatedCaption": "."
                  },
                  {
                    "name": "toimipaikkaluokitus_sv",
                    "translatedCaption": "Käännös puuttuu",
                    "translatedDisplayFolder": "Utbildningsvariabler"
                  },
                  {
                    "name": "maksutieto_id",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Utbildningsvariabler"
                  },
                  {
                    "name": "maksun_peruste_fi",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Utbildningsvariabler"
                  },
                  {
                    "name": "maksun_peruste_en",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Utbildningsvariabler"
                  },
                  {
                    "name": "maksun_peruste_sv",
                    "translatedCaption": "Käännös puuttuu",
                    "translatedDisplayFolder": "Personvariabler"
                  },
                  {
                    "name": "maksun_luokka_fi",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Kodvariabler"
                  },
                  {
                    "name": "maksun_luokka_en",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Kodvariabler"
                  },
                  {
                    "name": "maksun_luokka_sv",
                    "translatedCaption": "Käännös puuttuu",
                    "translatedDisplayFolder": "Personvariabler"
                  },
                  {
                    "name": "palveluseteli_arvo",
                    "translatedCaption": "Käännös puuttuu"
                  },
                  {
                    "name": "asiakasmaksu",
                    "translatedCaption": "Käännös puuttuu"
                  },
                  {
                    "name": "perheen_koko",
                    "translatedCaption": "Käännös puuttuu"
                  },
                  {
                    "name": "cum_sum",
                    "translatedCaption": "Käännös puuttuu"
                  }
                ],
                "measures": [
                  {
                    "name": "Lasten lukumäärä",
                    "translatedCaption": "Käännös puuttuu"
                  },
                  {
                    "name": "poikia",
                    "translatedCaption": "Käännös puuttuu"
                  },
                  {
                    "name": "tyttöjä",
                    "translatedCaption": "Käännös puuttuu"
                  },
                  {
                    "name": "Lasten osuus varhaiskasvatuksessa",
                    "translatedCaption": "Käännös puuttuu"
                  },
                  {
                    "name": "Kuntien asiakasmaksu min",
                    "translatedCaption": "Käännös puuttuu"
                  },
                  {
                    "name": "Kuntien asiakasmaksu max",
                    "translatedCaption": "Käännös puuttuu"
                  },
                  {
                    "name": "Kuntien asiakasmaksu mediaani",
                    "translatedCaption": "Käännös puuttuu"
                  },
                  {
                    "name": "Kuntien asiakasmaksu keskiarvo",
                    "translatedCaption": "Käännös puuttuu"
                  },
                  {
                    "name": "Yksityisten asiakasmaksu min",
                    "translatedCaption": "Käännös puuttuu"
                  },
                  {
                    "name": "Yksityisten asiakasmaksu max",
                    "translatedCaption": "Käännös puuttuu"
                  },
                  {
                    "name": "Yksityisten asiakasmaksu mediaani",
                    "translatedCaption": "Käännös puuttuu"
                  },
                  {
                    "name": "Yksityisten asiakasmaksu keskiarvo",
                    "translatedCaption": "Käännös puuttuu"
                  },
                  {
                    "name": "Kunnallisia lapsia",
                    "translatedCaption": "Käännös puuttuu"
                  },
                  {
                    "name": "Kunnallisia maksuja",
                    "translatedCaption": "Käännös puuttuu"
                  },
                  {
                    "name": "Yksityisiä lapsia",
                    "translatedCaption": "Käännös puuttuu"
                  },
                  {
                    "name": "Yksityisiä maksuja",
                    "translatedCaption": "Käännös puuttuu"
                  },
                  {
                    "name": "Palveluseteli min",
                    "translatedCaption": "Käännös puuttuu"
                  },
                  {
                    "name": "Palveluseteli max",
                    "translatedCaption": "Käännös puuttuu"
                  },
                  {
                    "name": "Palveluseteli mediaani",
                    "translatedCaption": "Käännös puuttuu"
                  },
                  {
                    "name": "Palveluseteli keskiarvo",
                    "translatedCaption": "Käännös puuttuu"
                  },
                  {
                    "name": "Palvelusetelillä lapsia",
                    "translatedCaption": "Käännös puuttuu"
                  },
                  {
                    "name": "Palvelusetelillä maksuja",
                    "translatedCaption": "Käännös puuttuu"
                  },
                  {
                    "name": "Asiakasmaksun keskiarvo",
                    "translatedCaption": "Käännös puuttuu"
                  },
                  {
                    "name": "% osuus kunnan lapsista",
                    "translatedCaption": "Käännös puuttuu"
                  },
                  {
                    "name": "Palvelusetelillä lapsia_s",
                    "translatedCaption": "Käännös puuttuu_s"
                  },
                  {
                    "name": "Kunnallisia lapsia_s",
                    "translatedCaption": "Käännös puuttuu_s"
                  },
                  {
                    "name": "Kunnallisen vakan kumulatiivinen summa",
                    "translatedCaption": "Käännös puuttuu"
                  },
                  {
                    "name": "Palveluseteli ja ostopalvelun kumulatiivinen summa",
                    "translatedCaption": "Käännös puuttuu",
                    "translatedDisplayFolder": "Personvariabler"
                  },
                  {
                    "name": "Yksityisen vakan kumulatiivinen summa",
                    "translatedCaption": "Käännös puuttuu"
                  },
                  {
                    "name": "henkilo_cum_sum",
                    "translatedCaption": "Henkilön kumulatiivinen summa"
                  },
                  {
                    "name": "Yksityisiä lapsia (ml. palveluseteli ja ostopalvelu)",
                    "translatedCaption": "Yksityisiä lapsia (ml. palveluseteli ja ostopalvelu)"
                  }
                ]
              }
            ]
          }
        }
      },
      {
        "name": "en-US",
        "translations": {
          "model": {
            "name": "Model",
            "tables": [
              {
                "name": "Muuttujat",
                "translatedCaption": "Variables",
                "columns": [
                  {
                    "name": "tilastovuosi",
                    "translatedCaption": "Statistical year",
                    "translatedDisplayFolder": "Time variables"
                  },
                  {
                    "name": "kotikunta_fi",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Time variables"
                  },
                  {
                    "name": "kotikunta_en",
                    "translatedCaption": "Käännös puuttuu",
                    "translatedDisplayFolder": "Person variables"
                  },
                  {
                    "name": "kotikunta_sv",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Person variables"
                  },
                  {
                    "name": "kotikunta_koodi",
                    "translatedCaption": "Käännös puuttuu",
                    "translatedDisplayFolder": "Code variables"
                  },
                  {
                    "name": "ikä",
                    "translatedCaption": "Age",
                    "translatedDisplayFolder": "Person variables"
                  },
                  {
                    "name": "ikäryhmä",
                    "translatedCaption": "Age group",
                    "translatedDisplayFolder": "Person variables"
                  },
                  {
                    "name": "aidinkieli_fi",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Person variables"
                  },
                  {
                    "name": "aidinkieli_en",
                    "translatedCaption": "Mother tongue",
                    "translatedDisplayFolder": "Person variables"
                  },
                  {
                    "name": "aidinkieli_sv",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Person variables"
                  },
                  {
                    "name": "sukupuoli_fi",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Person variables"
                  },
                  {
                    "name": "sukupuoli_en",
                    "translatedCaption": "Gender",
                    "translatedDisplayFolder": "Person variables"
                  },
                  {
                    "name": "sukupuoli_sv",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Person variables"
                  },
                  {
                    "name": "jarjestamismuoto_koodi",
                    "translatedCaption": "Käännös puuttuu",
                    "translatedDisplayFolder": "Code variables"
                  },
                  {
                    "name": "jarjestamismuoto_fi",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Person variables"
                  },
                  {
                    "name": "jarjestamismuoto_en",
                    "translatedCaption": "Form of vocational education and training",
                    "translatedDisplayFolder": "Education variables"
                  },
                  {
                    "name": "jarjestamismuoto_sv",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Education variables"
                  },
                  {
                    "name": "vuorohoito_kytkin_fi",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Education variables"
                  },
                  {
                    "name": "vuorohoito_kytkin_en",
                    "translatedCaption": "Käännös puuttuu",
                    "translatedDisplayFolder": "Education variables"
                  },
                  {
                    "name": "vuorohoito_kytkin_sv",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Education variables"
                  },
                  {
                    "name": "kokopaivainen_vaka_kytkin_fi",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Education variables"
                  },
                  {
                    "name": "kokopaivainen_vaka_kytkin_en",
                    "translatedCaption": "Käännös puuttuu",
                    "translatedDisplayFolder": "Code variables"
                  },
                  {
                    "name": "kokopaivainen_vaka_kytkin_sv",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Code variables"
                  },
                  {
                    "name": "paivittainen_vaka_kytkin_fi",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Code variables"
                  },
                  {
                    "name": "paivittainen_vaka_kytkin_en",
                    "translatedCaption": "Käännös puuttuu",
                    "translatedDisplayFolder": "Person variables"
                  },
                  {
                    "name": "paivittainen_vaka_kytkin_sv",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Person variables"
                  },
                  {
                    "name": "pikakasittely_kytkin_fi",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Person variables"
                  },
                  {
                    "name": "pikakasittely_kytkin_en",
                    "translatedCaption": "Käännös puuttuu"
                  },
                  {
                    "name": "pikakasittely_kytkin_sv",
                    "translatedCaption": "."
                  },
                  {
                    "name": "tuntimaara_viikossa",
                    "translatedCaption": "Käännös puuttuu",
                    "translatedDisplayFolder": "Person variables"
                  },
                  {
                    "name": "tuntimäärä_asteikko",
                    "translatedCaption": "Käännös puuttuu",
                    "translatedDisplayFolder": "Person variables"
                  },
                  {
                    "name": "vakajarjestaja_nimi",
                    "translatedCaption": "Käännös puuttuu",
                    "translatedDisplayFolder": "Education variables"
                  },
                  {
                    "name": "yritysmuoto_fi",
                    "translatedCaption": "."
                  },
                  {
                    "name": "yritysmuoto_en",
                    "translatedCaption": "Käännös puuttuu",
                    "translatedDisplayFolder": "Education variables"
                  },
                  {
                    "name": "yritysmuoto_sv",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Education variables"
                  },
                  {
                    "name": "yritysmuoto_ryhma_fi",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Person variables"
                  },
                  {
                    "name": "yritystyyppi",
                    "translatedCaption": "Käännös puuttuu",
                    "translatedDisplayFolder": "Education variables"
                  },
                  {
                    "name": "vakajarjestaja_kunta_fi",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Education variables"
                  },
                  {
                    "name": "vakajarjestaja_kunta_sv",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Education variables"
                  },
                  {
                    "name": "vakajarjestaja_kunta_en",
                    "translatedCaption": "Käännös puuttuu",
                    "translatedDisplayFolder": "Education variables"
                  },
                  {
                    "name": "toimipaikka_maakunta_fi",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Education variables"
                  },
                  {
                    "name": "toimipaikka_maakunta_en",
                    "translatedCaption": "Käännös puuttuu",
                    "translatedDisplayFolder": "Education variables"
                  },
                  {
                    "name": "toimipaikka_maakunta_sv",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Education variables"
                  },
                  {
                    "name": "toimipaikka_kunta_fi",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Education variables"
                  },
                  {
                    "name": "toimipaikka_kunta_en",
                    "translatedCaption": "Käännös puuttuu",
                    "translatedDisplayFolder": "Education variables"
                  },
                  {
                    "name": "toimipaikka_kunta_sv",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Education variables"
                  },
                  {
                    "name": "kasvatusopillinen_jarjestelma_fi",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Education variables"
                  },
                  {
                    "name": "kasvatusopillinen_jarjestelma_en",
                    "translatedCaption": "Käännös puuttuu",
                    "translatedDisplayFolder": "Code variables"
                  },
                  {
                    "name": "kasvatusopillinen_jarjestelma_sv",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Code variables"
                  },
                  {
                    "name": "toimintamuoto_fi",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Code variables"
                  },
                  {
                    "name": "toimintamuoto_en",
                    "translatedCaption": "Käännös puuttuu",
                    "translatedDisplayFolder": "Education variables"
                  },
                  {
                    "name": "toimintamuoto_sv",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Education variables"
                  },
                  {
                    "name": "toimipaikkaluokitus_fi",
                    "translatedCaption": "."
                  },
                  {
                    "name": "toimipaikkaluokitus_en",
                    "translatedCaption": "Käännös puuttuu",
                    "translatedDisplayFolder": "Education variables"
                  },
                  {
                    "name": "toimipaikkaluokitus_sv",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Education variables"
                  },
                  {
                    "name": "maksutieto_id",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Education variables"
                  },
                  {
                    "name": "maksun_peruste_fi",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Education variables"
                  },
                  {
                    "name": "maksun_peruste_en",
                    "translatedCaption": "Käännös puuttuu",
                    "translatedDisplayFolder": "Person variables"
                  },
                  {
                    "name": "maksun_peruste_sv",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Person variables"
                  },
                  {
                    "name": "maksun_luokka_fi",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Code variables"
                  },
                  {
                    "name": "maksun_luokka_en",
                    "translatedCaption": "Käännös puuttuu",
                    "translatedDisplayFolder": "Person variables"
                  },
                  {
                    "name": "maksun_luokka_sv",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Person variables"
                  },
                  {
                    "name": "palveluseteli_arvo",
                    "translatedCaption": "Käännös puuttuu"
                  },
                  {
                    "name": "asiakasmaksu",
                    "translatedCaption": "Käännös puuttuu"
                  },
                  {
                    "name": "perheen_koko",
                    "translatedCaption": "Käännös puuttuu"
                  },
                  {
                    "name": "cum_sum",
                    "translatedCaption": "Käännös puuttuu"
                  }
                ],
                "measures": [
                  {
                    "name": "Lasten lukumäärä",
                    "translatedCaption": "Käännös puuttuu"
                  },
                  {
                    "name": "poikia",
                    "translatedCaption": "Boys"
                  },
                  {
                    "name": "tyttöjä",
                    "translatedCaption": "Girls"
                  },
                  {
                    "name": "Lasten osuus varhaiskasvatuksessa",
                    "translatedCaption": "Käännös puuttuu"
                  },
                  {
                    "name": "Kuntien asiakasmaksu min",
                    "translatedCaption": "Käännös puuttuu"
                  },
                  {
                    "name": "Kuntien asiakasmaksu max",
                    "translatedCaption": "Käännös puuttuu"
                  },
                  {
                    "name": "Kuntien asiakasmaksu mediaani",
                    "translatedCaption": "Käännös puuttuu"
                  },
                  {
                    "name": "Kuntien asiakasmaksu keskiarvo",
                    "translatedCaption": "Käännös puuttuu"
                  },
                  {
                    "name": "Yksityisten asiakasmaksu min",
                    "translatedCaption": "Käännös puuttuu"
                  },
                  {
                    "name": "Yksityisten asiakasmaksu max",
                    "translatedCaption": "Käännös puuttuu"
                  },
                  {
                    "name": "Yksityisten asiakasmaksu mediaani",
                    "translatedCaption": "Käännös puuttuu"
                  },
                  {
                    "name": "Yksityisten asiakasmaksu keskiarvo",
                    "translatedCaption": "Käännös puuttuu"
                  },
                  {
                    "name": "Kunnallisia lapsia",
                    "translatedCaption": "Käännös puuttuu"
                  },
                  {
                    "name": "Kunnallisia maksuja",
                    "translatedCaption": "Käännös puuttuu"
                  },
                  {
                    "name": "Yksityisiä lapsia",
                    "translatedCaption": "Käännös puuttuu"
                  },
                  {
                    "name": "Yksityisiä maksuja",
                    "translatedCaption": "Käännös puuttuu"
                  },
                  {
                    "name": "Palveluseteli min",
                    "translatedCaption": "Käännös puuttuu"
                  },
                  {
                    "name": "Palveluseteli max",
                    "translatedCaption": "Käännös puuttuu"
                  },
                  {
                    "name": "Palveluseteli mediaani",
                    "translatedCaption": "Käännös puuttuu"
                  },
                  {
                    "name": "Palveluseteli keskiarvo",
                    "translatedCaption": "Käännös puuttuu"
                  },
                  {
                    "name": "Palvelusetelillä lapsia",
                    "translatedCaption": "Käännös puuttuu"
                  },
                  {
                    "name": "Palvelusetelillä maksuja",
                    "translatedCaption": "Käännös puuttuu"
                  },
                  {
                    "name": "Asiakasmaksun keskiarvo",
                    "translatedCaption": "Käännös puuttuu"
                  },
                  {
                    "name": "% osuus kunnan lapsista",
                    "translatedCaption": "Käännös puuttuu"
                  },
                  {
                    "name": "Palvelusetelillä lapsia_s",
                    "translatedCaption": "Käännös puuttuu_s"
                  },
                  {
                    "name": "Kunnallisia lapsia_s",
                    "translatedCaption": "Käännös puuttuu_s"
                  },
                  {
                    "name": "Kunnallisen vakan kumulatiivinen summa",
                    "translatedCaption": "Käännös puuttuu"
                  },
                  {
                    "name": "Palveluseteli ja ostopalvelun kumulatiivinen summa",
                    "translatedCaption": "Käännös puuttuu",
                    "translatedDisplayFolder": "Person variables"
                  },
                  {
                    "name": "Yksityisen vakan kumulatiivinen summa",
                    "translatedCaption": "Käännös puuttuu"
                  },
                  {
                    "name": "henkilo_cum_sum",
                    "translatedCaption": "Henkilön kumulatiivinen summa"
                  },
                  {
                    "name": "Yksityisiä lapsia (ml. palveluseteli ja ostopalvelu)",
                    "translatedCaption": "Yksityisiä lapsia (ml. palveluseteli ja ostopalvelu)"
                  }
                ]
              }
            ]
          }
        }
      }
    ],
    "perspectives": [
      {
        "name": "toimipaikat",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "ikä"
              },
              {
                "name": "ikäryhmä"
              },
              {
                "name": "ikäryhmä_jarj"
              },
              {
                "name": "jarjestamismuoto_en"
              },
              {
                "name": "jarjestamismuoto_fi"
              },
              {
                "name": "jarjestamismuoto_sv"
              },
              {
                "name": "tilastovuosi"
              },
              {
                "name": "vakajarjestaja_kunta_en"
              },
              {
                "name": "vakajarjestaja_kunta_fi"
              },
              {
                "name": "vakajarjestaja_kunta_sv"
              },
              {
                "name": "vakajarjestaja_nimi"
              },
              {
                "name": "yritysmuoto_en"
              },
              {
                "name": "yritysmuoto_fi"
              },
              {
                "name": "yritysmuoto_sv"
              },
              {
                "name": "yritystyyppi"
              }
            ],
            "measures": [
              {
                "name": "Lasten lukumäärä"
              },
              {
                "name": "Lasten osuus varhaiskasvatuksessa"
              },
              {
                "name": "poikia"
              },
              {
                "name": "tyttöjä"
              },
              {
                "name": "Väestö summa"
              }
            ]
          }
        ]
      },
      {
        "name": "lapset",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "aidinkieli_en"
              },
              {
                "name": "aidinkieli_fi"
              },
              {
                "name": "aidinkieli_sv"
              },
              {
                "name": "ikä"
              },
              {
                "name": "ikäryhmä"
              },
              {
                "name": "jarjestamismuoto_en"
              },
              {
                "name": "jarjestamismuoto_fi"
              },
              {
                "name": "jarjestamismuoto_sv"
              },
              {
                "name": "kasvatusopillinen_jarjestelma_en"
              },
              {
                "name": "kasvatusopillinen_jarjestelma_fi"
              },
              {
                "name": "kasvatusopillinen_jarjestelma_sv"
              },
              {
                "name": "kokopaivainen_vaka_kytkin_en"
              },
              {
                "name": "kokopaivainen_vaka_kytkin_fi"
              },
              {
                "name": "kokopaivainen_vaka_kytkin_sv"
              },
              {
                "name": "kotikunta_en"
              },
              {
                "name": "kotikunta_fi"
              },
              {
                "name": "kotikunta_koodi"
              },
              {
                "name": "kotikunta_sv"
              },
              {
                "name": "paivittainen_vaka_kytkin_en"
              },
              {
                "name": "paivittainen_vaka_kytkin_fi"
              },
              {
                "name": "paivittainen_vaka_kytkin_sv"
              },
              {
                "name": "sukupuoli_en"
              },
              {
                "name": "sukupuoli_fi"
              },
              {
                "name": "sukupuoli_sv"
              },
              {
                "name": "tilastovuosi"
              },
              {
                "name": "toimintamuoto_en"
              },
              {
                "name": "toimintamuoto_fi"
              },
              {
                "name": "toimintamuoto_sv"
              },
              {
                "name": "toimipaikka_kunta_en"
              },
              {
                "name": "toimipaikka_kunta_fi"
              },
              {
                "name": "toimipaikka_kunta_sv"
              },
              {
                "name": "toimipaikka_maakunta_en"
              },
              {
                "name": "toimipaikka_maakunta_fi"
              },
              {
                "name": "toimipaikka_maakunta_sv"
              },
              {
                "name": "tuntimaara_viikossa"
              },
              {
                "name": "tuntimäärä_asteikko"
              },
              {
                "name": "tuntimäärä_asteikko_jarj"
              },
              {
                "name": "vuorohoito_kytkin_en"
              },
              {
                "name": "vuorohoito_kytkin_fi"
              },
              {
                "name": "vuorohoito_kytkin_sv"
              },
              {
                "name": "Väestö"
              },
              {
                "name": "yritysmuoto_en"
              },
              {
                "name": "yritysmuoto_fi"
              },
              {
                "name": "yritysmuoto_sv"
              },
              {
                "name": "yritystyyppi"
              }
            ],
            "measures": [
              {
                "name": "Lasten lukumäärä"
              },
              {
                "name": "Lasten osuus varhaiskasvatuksessa"
              },
              {
                "name": "poikia"
              },
              {
                "name": "tyttöjä"
              },
              {
                "name": "Väestö summa"
              }
            ]
          }
        ]
      },
      {
        "name": "maksutiedot",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "asiakasmaksu"
              },
              {
                "name": "maksun_peruste_en"
              },
              {
                "name": "maksun_peruste_fi"
              },
              {
                "name": "maksun_peruste_sv"
              },
              {
                "name": "palveluseteli_arvo"
              },
              {
                "name": "perheen_koko"
              },
              {
                "name": "tilastovuosi"
              },
              {
                "name": "toimipaikka_maakunta_en"
              },
              {
                "name": "toimipaikka_maakunta_fi"
              },
              {
                "name": "toimipaikka_maakunta_sv"
              },
              {
                "name": "yritysmuoto_en"
              },
              {
                "name": "yritysmuoto_fi"
              },
              {
                "name": "yritysmuoto_sv"
              },
              {
                "name": "yritystyyppi"
              },
              {
                "name": "ikä"
              },
              {
                "name": "ikäryhmä"
              },
              {
                "name": "maksun_luokka_en"
              },
              {
                "name": "maksun_luokka_fi"
              },
              {
                "name": "maksun_luokka_sv"
              },
              {
                "name": "toimipaikka_kunta_en"
              },
              {
                "name": "toimipaikka_kunta_fi"
              },
              {
                "name": "toimipaikka_kunta_sv"
              },
              {
                "name": "toimintamuoto_fi"
              },
              {
                "name": "toimipaikkaluokitus_fi"
              },
              {
                "name": "yritysmuoto_ryhma_fi"
              },
              {
                "name": "jarjestamismuoto_en"
              },
              {
                "name": "jarjestamismuoto_fi"
              },
              {
                "name": "jarjestamismuoto_sv"
              }
            ],
            "measures": [
              {
                "name": "Kuntien asiakasmaksu keskiarvo"
              },
              {
                "name": "Kuntien asiakasmaksu max"
              },
              {
                "name": "Kuntien asiakasmaksu mediaani"
              },
              {
                "name": "Kuntien asiakasmaksu min"
              },
              {
                "name": "Yksityisten asiakasmaksu keskiarvo"
              },
              {
                "name": "Yksityisten asiakasmaksu max"
              },
              {
                "name": "Yksityisten asiakasmaksu mediaani"
              },
              {
                "name": "Yksityisten asiakasmaksu min"
              },
              {
                "name": "Yksityisiä lapsia"
              },
              {
                "name": "Kunnallisia lapsia"
              },
              {
                "name": "Kunnallisia maksuja"
              },
              {
                "name": "Yksityisiä maksuja"
              },
              {
                "name": "Palveluseteli keskiarvo"
              },
              {
                "name": "Palveluseteli max"
              },
              {
                "name": "Palveluseteli mediaani"
              },
              {
                "name": "Palveluseteli min"
              },
              {
                "name": "Palvelusetelillä lapsia"
              },
              {
                "name": "Palvelusetelillä maksuja"
              },
              {
                "name": "Asiakasmaksun keskiarvo"
              },
              {
                "name": "% osuus kunnan lapsista"
              },
              {
                "name": "Kunnallisen vakan kumulatiivinen summa"
              },
              {
                "name": "Palveluseteli ja ostopalvelun kumulatiivinen summa"
              },
              {
                "name": "Yksityisen vakan kumulatiivinen summa"
              },
              {
                "name": "Yksityisiä lapsia (ml. palveluseteli ja ostopalvelu)"
              }
            ]
          }
        ]
      },
      {
        "name": "toimipaikat_fi",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "ikä"
              },
              {
                "name": "ikäryhmä"
              },
              {
                "name": "ikäryhmä_jarj"
              },
              {
                "name": "jarjestamismuoto_fi"
              },
              {
                "name": "tilastovuosi"
              },
              {
                "name": "vakajarjestaja_kunta_fi"
              },
              {
                "name": "vakajarjestaja_nimi"
              },
              {
                "name": "yritysmuoto_fi"
              },
              {
                "name": "yritystyyppi"
              }
            ],
            "measures": [
              {
                "name": "Lasten lukumäärä"
              },
              {
                "name": "Lasten osuus varhaiskasvatuksessa"
              },
              {
                "name": "poikia"
              },
              {
                "name": "tyttöjä"
              },
              {
                "name": "Väestö summa"
              }
            ]
          }
        ]
      },
      {
        "name": "toimipaikat_en",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "ikä"
              },
              {
                "name": "ikäryhmä"
              },
              {
                "name": "ikäryhmä_jarj"
              },
              {
                "name": "jarjestamismuoto_en"
              },
              {
                "name": "tilastovuosi"
              },
              {
                "name": "vakajarjestaja_kunta_en"
              },
              {
                "name": "vakajarjestaja_nimi"
              },
              {
                "name": "yritysmuoto_en"
              },
              {
                "name": "yritystyyppi"
              }
            ],
            "measures": [
              {
                "name": "Lasten lukumäärä"
              },
              {
                "name": "Lasten osuus varhaiskasvatuksessa"
              },
              {
                "name": "poikia"
              },
              {
                "name": "tyttöjä"
              },
              {
                "name": "Väestö summa"
              }
            ]
          }
        ]
      },
      {
        "name": "toimipaikat_sv",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "ikä"
              },
              {
                "name": "ikäryhmä"
              },
              {
                "name": "ikäryhmä_jarj"
              },
              {
                "name": "jarjestamismuoto_en"
              },
              {
                "name": "jarjestamismuoto_sv"
              },
              {
                "name": "tilastovuosi"
              },
              {
                "name": "vakajarjestaja_kunta_sv"
              },
              {
                "name": "vakajarjestaja_nimi"
              },
              {
                "name": "yritysmuoto_sv"
              },
              {
                "name": "yritystyyppi"
              }
            ],
            "measures": [
              {
                "name": "Lasten lukumäärä"
              },
              {
                "name": "Lasten osuus varhaiskasvatuksessa"
              },
              {
                "name": "poikia"
              },
              {
                "name": "tyttöjä"
              },
              {
                "name": "Väestö summa"
              }
            ]
          }
        ]
      },
      {
        "name": "lapset_fi",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "aidinkieli_fi"
              },
              {
                "name": "ikä"
              },
              {
                "name": "ikäryhmä"
              },
              {
                "name": "jarjestamismuoto_fi"
              },
              {
                "name": "kasvatusopillinen_jarjestelma_fi"
              },
              {
                "name": "kokopaivainen_vaka_kytkin_fi"
              },
              {
                "name": "kotikunta_fi"
              },
              {
                "name": "kotikunta_koodi"
              },
              {
                "name": "paivittainen_vaka_kytkin_fi"
              },
              {
                "name": "sukupuoli_fi"
              },
              {
                "name": "tilastovuosi"
              },
              {
                "name": "toimintamuoto_fi"
              },
              {
                "name": "toimipaikka_kunta_fi"
              },
              {
                "name": "toimipaikka_maakunta_fi"
              },
              {
                "name": "tuntimaara_viikossa"
              },
              {
                "name": "tuntimäärä_asteikko"
              },
              {
                "name": "tuntimäärä_asteikko_jarj"
              },
              {
                "name": "vuorohoito_kytkin_fi"
              },
              {
                "name": "Väestö"
              },
              {
                "name": "yritysmuoto_fi"
              },
              {
                "name": "yritystyyppi"
              },
              {
                "name": "yritysmuoto_ryhma_fi"
              }
            ],
            "measures": [
              {
                "name": "Lasten lukumäärä"
              },
              {
                "name": "Lasten osuus varhaiskasvatuksessa"
              },
              {
                "name": "poikia"
              },
              {
                "name": "tyttöjä"
              },
              {
                "name": "Väestö summa"
              },
              {
                "name": "Kunnallisia lapsia"
              },
              {
                "name": "Yksityisiä lapsia"
              },
              {
                "name": "Yksityisiä lapsia (ml. palveluseteli ja ostopalvelu)"
              }
            ]
          }
        ]
      },
      {
        "name": "lapset_en",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "aidinkieli_en"
              },
              {
                "name": "ikä"
              },
              {
                "name": "ikäryhmä"
              },
              {
                "name": "jarjestamismuoto_en"
              },
              {
                "name": "kasvatusopillinen_jarjestelma_en"
              },
              {
                "name": "kokopaivainen_vaka_kytkin_en"
              },
              {
                "name": "kotikunta_en"
              },
              {
                "name": "kotikunta_koodi"
              },
              {
                "name": "paivittainen_vaka_kytkin_en"
              },
              {
                "name": "sukupuoli_en"
              },
              {
                "name": "tilastovuosi"
              },
              {
                "name": "toimintamuoto_en"
              },
              {
                "name": "toimipaikka_kunta_en"
              },
              {
                "name": "toimipaikka_maakunta_en"
              },
              {
                "name": "tuntimaara_viikossa"
              },
              {
                "name": "tuntimäärä_asteikko"
              },
              {
                "name": "tuntimäärä_asteikko_jarj"
              },
              {
                "name": "vuorohoito_kytkin_en"
              },
              {
                "name": "Väestö"
              },
              {
                "name": "yritysmuoto_en"
              },
              {
                "name": "yritystyyppi"
              },
              {
                "name": "yritysmuoto_ryhma_fi"
              }
            ],
            "measures": [
              {
                "name": "Lasten lukumäärä"
              },
              {
                "name": "Lasten osuus varhaiskasvatuksessa"
              },
              {
                "name": "poikia"
              },
              {
                "name": "tyttöjä"
              },
              {
                "name": "Väestö summa"
              },
              {
                "name": "Kunnallisia lapsia"
              },
              {
                "name": "Yksityisiä lapsia"
              },
              {
                "name": "Yksityisiä lapsia (ml. palveluseteli ja ostopalvelu)"
              }
            ]
          }
        ]
      },
      {
        "name": "lapset_sv",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "aidinkieli_sv"
              },
              {
                "name": "ikä"
              },
              {
                "name": "ikäryhmä"
              },
              {
                "name": "jarjestamismuoto_sv"
              },
              {
                "name": "kasvatusopillinen_jarjestelma_sv"
              },
              {
                "name": "kokopaivainen_vaka_kytkin_sv"
              },
              {
                "name": "kotikunta_koodi"
              },
              {
                "name": "kotikunta_sv"
              },
              {
                "name": "paivittainen_vaka_kytkin_sv"
              },
              {
                "name": "sukupuoli_sv"
              },
              {
                "name": "tilastovuosi"
              },
              {
                "name": "toimintamuoto_sv"
              },
              {
                "name": "toimipaikka_kunta_sv"
              },
              {
                "name": "toimipaikka_maakunta_sv"
              },
              {
                "name": "tuntimaara_viikossa"
              },
              {
                "name": "tuntimäärä_asteikko"
              },
              {
                "name": "tuntimäärä_asteikko_jarj"
              },
              {
                "name": "vuorohoito_kytkin_sv"
              },
              {
                "name": "Väestö"
              },
              {
                "name": "yritysmuoto_sv"
              },
              {
                "name": "yritystyyppi"
              },
              {
                "name": "yritysmuoto_ryhma_fi"
              }
            ],
            "measures": [
              {
                "name": "Lasten lukumäärä"
              },
              {
                "name": "Lasten osuus varhaiskasvatuksessa"
              },
              {
                "name": "poikia"
              },
              {
                "name": "tyttöjä"
              },
              {
                "name": "Väestö summa"
              },
              {
                "name": "Kunnallisia lapsia"
              },
              {
                "name": "Yksityisiä lapsia"
              },
              {
                "name": "Yksityisiä lapsia (ml. palveluseteli ja ostopalvelu)"
              }
            ]
          }
        ]
      },
      {
        "name": "maksutiedot_fi",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "asiakasmaksu"
              },
              {
                "name": "ikä"
              },
              {
                "name": "ikäryhmä"
              },
              {
                "name": "jarjestamismuoto_fi"
              },
              {
                "name": "maksun_luokka_fi"
              },
              {
                "name": "maksun_peruste_fi"
              },
              {
                "name": "palveluseteli_arvo"
              },
              {
                "name": "perheen_koko"
              },
              {
                "name": "tilastovuosi"
              },
              {
                "name": "toimintamuoto_fi"
              },
              {
                "name": "toimipaikka_kunta_fi"
              },
              {
                "name": "toimipaikka_maakunta_fi"
              },
              {
                "name": "toimipaikkaluokitus_fi"
              },
              {
                "name": "yritysmuoto_fi"
              },
              {
                "name": "yritysmuoto_ryhma_fi"
              },
              {
                "name": "yritystyyppi"
              }
            ],
            "measures": [
              {
                "name": "% osuus kunnan lapsista"
              },
              {
                "name": "Asiakasmaksun keskiarvo"
              },
              {
                "name": "Kunnallisen vakan kumulatiivinen summa"
              },
              {
                "name": "Kunnallisia lapsia"
              },
              {
                "name": "Kunnallisia maksuja"
              },
              {
                "name": "Kuntien asiakasmaksu keskiarvo"
              },
              {
                "name": "Kuntien asiakasmaksu max"
              },
              {
                "name": "Kuntien asiakasmaksu mediaani"
              },
              {
                "name": "Kuntien asiakasmaksu min"
              },
              {
                "name": "Palveluseteli ja ostopalvelun kumulatiivinen summa"
              },
              {
                "name": "Palveluseteli keskiarvo"
              },
              {
                "name": "Palveluseteli max"
              },
              {
                "name": "Palveluseteli mediaani"
              },
              {
                "name": "Palveluseteli min"
              },
              {
                "name": "Palvelusetelillä maksuja"
              },
              {
                "name": "Yksityisen vakan kumulatiivinen summa"
              },
              {
                "name": "Yksityisiä lapsia"
              },
              {
                "name": "Yksityisiä lapsia (ml. palveluseteli ja ostopalvelu)"
              },
              {
                "name": "Yksityisiä maksuja"
              },
              {
                "name": "Yksityisten asiakasmaksu keskiarvo"
              },
              {
                "name": "Yksityisten asiakasmaksu max"
              },
              {
                "name": "Yksityisten asiakasmaksu mediaani"
              },
              {
                "name": "Yksityisten asiakasmaksu min"
              },
              {
                "name": "Palvelusetelillä lapsia"
              }
            ]
          }
        ]
      },
      {
        "name": "maksutiedot_en",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "asiakasmaksu"
              },
              {
                "name": "ikä"
              },
              {
                "name": "ikäryhmä"
              },
              {
                "name": "jarjestamismuoto_en"
              },
              {
                "name": "maksun_luokka_en"
              },
              {
                "name": "maksun_peruste_en"
              },
              {
                "name": "palveluseteli_arvo"
              },
              {
                "name": "perheen_koko"
              },
              {
                "name": "tilastovuosi"
              },
              {
                "name": "toimintamuoto_en"
              },
              {
                "name": "toimipaikka_kunta_en"
              },
              {
                "name": "toimipaikka_maakunta_en"
              },
              {
                "name": "toimipaikkaluokitus_en"
              },
              {
                "name": "yritysmuoto_en"
              },
              {
                "name": "yritysmuoto_ryhma_fi"
              },
              {
                "name": "yritystyyppi"
              }
            ],
            "measures": [
              {
                "name": "% osuus kunnan lapsista"
              },
              {
                "name": "Asiakasmaksun keskiarvo"
              },
              {
                "name": "Kunnallisen vakan kumulatiivinen summa"
              },
              {
                "name": "Kunnallisia lapsia"
              },
              {
                "name": "Kunnallisia maksuja"
              },
              {
                "name": "Kuntien asiakasmaksu keskiarvo"
              },
              {
                "name": "Kuntien asiakasmaksu max"
              },
              {
                "name": "Kuntien asiakasmaksu mediaani"
              },
              {
                "name": "Kuntien asiakasmaksu min"
              },
              {
                "name": "Palveluseteli ja ostopalvelun kumulatiivinen summa"
              },
              {
                "name": "Palveluseteli keskiarvo"
              },
              {
                "name": "Palveluseteli max"
              },
              {
                "name": "Palveluseteli mediaani"
              },
              {
                "name": "Palveluseteli min"
              },
              {
                "name": "Palvelusetelillä lapsia"
              },
              {
                "name": "Palvelusetelillä maksuja"
              },
              {
                "name": "Yksityisen vakan kumulatiivinen summa"
              },
              {
                "name": "Yksityisiä lapsia"
              },
              {
                "name": "Yksityisiä lapsia (ml. palveluseteli ja ostopalvelu)"
              },
              {
                "name": "Yksityisiä maksuja"
              },
              {
                "name": "Yksityisten asiakasmaksu keskiarvo"
              },
              {
                "name": "Yksityisten asiakasmaksu max"
              },
              {
                "name": "Yksityisten asiakasmaksu mediaani"
              },
              {
                "name": "Yksityisten asiakasmaksu min"
              }
            ]
          }
        ]
      },
      {
        "name": "maksutiedot_sv",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "asiakasmaksu"
              },
              {
                "name": "ikä"
              },
              {
                "name": "ikäryhmä"
              },
              {
                "name": "jarjestamismuoto_sv"
              },
              {
                "name": "maksun_luokka_sv"
              },
              {
                "name": "maksun_peruste_sv"
              },
              {
                "name": "palveluseteli_arvo"
              },
              {
                "name": "perheen_koko"
              },
              {
                "name": "tilastovuosi"
              },
              {
                "name": "toimintamuoto_sv"
              },
              {
                "name": "toimipaikka_kunta_sv"
              },
              {
                "name": "toimipaikka_maakunta_sv"
              },
              {
                "name": "toimipaikkaluokitus_sv"
              },
              {
                "name": "yritysmuoto_ryhma_fi"
              },
              {
                "name": "yritysmuoto_sv"
              },
              {
                "name": "yritystyyppi"
              }
            ],
            "measures": [
              {
                "name": "% osuus kunnan lapsista"
              },
              {
                "name": "Asiakasmaksun keskiarvo"
              },
              {
                "name": "Kunnallisen vakan kumulatiivinen summa"
              },
              {
                "name": "Kunnallisia lapsia"
              },
              {
                "name": "Kunnallisia maksuja"
              },
              {
                "name": "Kuntien asiakasmaksu keskiarvo"
              },
              {
                "name": "Kuntien asiakasmaksu max"
              },
              {
                "name": "Kuntien asiakasmaksu mediaani"
              },
              {
                "name": "Kuntien asiakasmaksu min"
              },
              {
                "name": "Palveluseteli ja ostopalvelun kumulatiivinen summa"
              },
              {
                "name": "Palveluseteli keskiarvo"
              },
              {
                "name": "Palveluseteli max"
              },
              {
                "name": "Palveluseteli mediaani"
              },
              {
                "name": "Palveluseteli min"
              },
              {
                "name": "Palvelusetelillä lapsia"
              },
              {
                "name": "Palvelusetelillä maksuja"
              },
              {
                "name": "Yksityisen vakan kumulatiivinen summa"
              },
              {
                "name": "Yksityisiä lapsia"
              },
              {
                "name": "Yksityisiä lapsia (ml. palveluseteli ja ostopalvelu)"
              },
              {
                "name": "Yksityisiä maksuja"
              },
              {
                "name": "Yksityisten asiakasmaksu keskiarvo"
              },
              {
                "name": "Yksityisten asiakasmaksu max"
              },
              {
                "name": "Yksityisten asiakasmaksu mediaani"
              },
              {
                "name": "Yksityisten asiakasmaksu min"
              }
            ]
          }
        ]
      }
    ],
    "roles": [
      {
        "name": "Testi",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "DWI\\T_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1732"
          },
          {
            "memberName": "NT AUTHORITY\\IUSR",
            "memberId": "S-1-5-17"
          }
        ]
      },
      {
        "name": "Tuotanto",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "DWI\\T_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1732"
          },
          {
            "memberName": "NT AUTHORITY\\IUSR",
            "memberId": "S-1-5-17"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "400"
      }
    ]
  },
  "id": "SemanticModel"
}