{
  "name": "SemanticModel",
  "compatibilityLevel": 1200,
  "model": {
    "culture": "fi-FI",
    "dataSources": [
      {
        "name": "SqlServer dwitvipusql22 ANTERO",
        "connectionString": "Provider=SQLNCLI11;Data Source=dwitvipusql22;Integrated Security=SSPI;Persist Security Info=false;Initial Catalog=ANTERO",
        "impersonationMode": "impersonateAccount",
        "account": "dwi\\t_viputk_kuutio",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      },
      {
        "name": "SqlServer dwitvipusql22 ANTERO 2",
        "connectionString": "Provider=SQLNCLI11;Data Source=dwitvipusql22;Initial Catalog=ANTERO;Integrated Security=SSPI;Persist Security Info=false",
        "impersonationMode": "impersonateAccount",
        "account": "DWI\\t_viputk_kuutio",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      },
      {
        "name": "SqlServer dwitvipusql22 VipunenTK",
        "connectionString": "Provider=SQLNCLI11;Data Source=dwitvipusql22;Initial Catalog=VipunenTK;Integrated Security=SSPI;Persist Security Info=false",
        "impersonationMode": "impersonateAccount",
        "account": "dwi\\t_viputk_kuutio",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      },
      {
        "name": "SqlServer dwitvipusql22 VipunenTK_lisatiedot",
        "connectionString": "Provider=SQLNCLI11;Data Source=dwitvipusql22;Initial Catalog=VipunenTK_lisatiedot;Integrated Security=SSPI;Persist Security Info=false",
        "impersonationMode": "impersonateAccount",
        "account": "dwi\\t_viputk_kuutio",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      },
      {
        "name": "SqlServer dwitvipusql22 VipunenTK_lisatiedot 2",
        "connectionString": "Provider=SQLNCLI11;Data Source=dwitvipusql22;Initial Catalog=VipunenTK_lisatiedot;Integrated Security=SSPI;Persist Security Info=false",
        "impersonationMode": "impersonateAccount",
        "account": "dwi\\t_viputk_kuutio",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "Sarakeleveys",
        "isHidden": true,
        "columns": [
          {
            "name": "Sarakeleveys",
            "dataType": "string",
            "sourceColumn": "Sarakeleveys",
            "sourceProviderType": "Char"
          },
          {
            "name": "leveys",
            "dataType": "string",
            "sourceColumn": "leveys",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Sarakeleveys",
            "dataView": "full",
            "source": {
              "query": " SELECT [dw].[Sarakeleveys].* FROM [dw].[Sarakeleveys] ",
              "dataSource": "SqlServer dwitvipusql22 ANTERO 2"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Sarakeleveys</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>94</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>leveys</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>61</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Sarakeleveys</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>leveys</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked />",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dw].[Sarakeleveys].* FROM [dw].[Sarakeleveys] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Sarakeleveys"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dw"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Sarakeleveys</string>",
              "      </key>",
              "      <value>",
              "        <int>94</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>leveys</string>",
              "      </key>",
              "      <value>",
              "        <int>61</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Sarakeleveys</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>leveys</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked />",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Muuttujat",
        "columns": [
          {
            "name": "Koulutusala, taso 1",
            "dataType": "string",
            "sourceColumn": "Koulutusala, taso 1",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusala, taso 2",
            "dataType": "string",
            "sourceColumn": "Koulutusala, taso 2",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusala, taso 3",
            "dataType": "string",
            "sourceColumn": "Koulutusala, taso 3",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutuksen kunta",
            "dataType": "string",
            "sourceColumn": "Kunta",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "tutkinnot",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "tutkinnot",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Yo 7v aloittaneet lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Yo 7v aloittaneet lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "5v_Aloittaneet_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "5v_Aloittaneet_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "7v_suorittaneet_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "7v_suorittaneet_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "5v_suorittaneet_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "5v_suorittaneet_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "55op suorittaneet",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "55op suorittaneet",
            "sourceProviderType": "Integer"
          },
          {
            "name": "1-14op suorittaneet",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "1-14op suorittaneet",
            "sourceProviderType": "Integer"
          },
          {
            "name": "YO Julkaisut (A1-A4, C1 ja C2) jufotaso 2 ja 3",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "YO Julkaisut (A1-A4, C1 ja C2) jufotaso 2 ja 3",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "YO Julkaisut (A1-A4, C1 ja C2) jufotaso 1-3",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "YO Julkaisut (A1-A4, C1 ja C2) jufotaso 1-3",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "Kilpailtu tutkimusrahoitus",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Kilpailtu tutkimusrahoitus",
            "sourceProviderType": "BigInt"
          },
          {
            "name": "kv_vaihtoopiskelijat_op_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "kv_vaihtoopiskelijat_op_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "ulkom_hyv_luetut_op_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ulkom_hyv_luetut_op_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "erilopintooik_op_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "erilopintooik_op_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "avoinamk_op_amk_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "avoinamk_op_amk_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "mamu_op_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "mamu_op_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "erikoul_suor_op_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "erikoul_suor_op_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "sijoittuminen_1v_tutkinnon_jalkeen",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "sijoittuminen_1v_tutkinnon_jalkeen",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Tilastovuosi",
            "dataType": "int64",
            "sourceColumn": "Tilastovuosi",
            "displayFolder": "Aikamuuttujat"
          },
          {
            "name": "Sektori",
            "dataType": "string",
            "sourceColumn": "Sektori",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "OKM ohjauksen ala",
            "dataType": "string",
            "sourceColumn": "OKM ohjauksen ala",
            "sortByColumn": "jarj. OKM ohjauksen ala",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusaste, taso 1",
            "dataType": "string",
            "sourceColumn": "Koulutusaste, taso 1",
            "sortByColumn": "jarj. koulutusaste, taso 1",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusaste, taso 2",
            "dataType": "string",
            "sourceColumn": "Koulutusaste, taso 2",
            "sortByColumn": "jarj. koulutusaste, taso 2",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Kansalaisuus",
            "dataType": "string",
            "sourceColumn": "Kansalaisuus",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "jarj. koulutusaste, taso 1",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarj. koulutusaste, taso 1"
          },
          {
            "name": "jarj. koulutusaste, taso 2",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarj. koulutusaste, taso 2"
          },
          {
            "name": "jarj. OKM ohjauksen ala",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarj. OKM ohjauksen ala"
          },
          {
            "name": "Koodit OKM ohjauksen ala",
            "dataType": "string",
            "sourceColumn": "Koodit OKM ohjauksen ala",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koodit kunta",
            "dataType": "string",
            "sourceColumn": "Koodit kunta",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "AMK Julkaisut (A-E)",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "AMK Julkaisut (A-E)"
          },
          {
            "name": "AMK julkaisut (F ja I)",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "AMK julkaisut (F ja I)"
          },
          {
            "type": "calculated",
            "name": "Organisaatio",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "SWITCH(IF(NOT(ISBLANK([Aloituslukuvuosi (läpäisy)])),Muuttujat[Organisaatio 1]),",
              "\t\"Sibelius-Akatemia\",\"Taideyliopisto\",",
              "\t\"Teatterikorkeakoulu\",\"Taideyliopisto\",",
              "\t\"Kuvataideakatemia\",\"Taideyliopisto\",",
              "SWITCH(Muuttujat[Organisaatio 1],",
              "\t\"Mikkelin Ammattikorkeakoulu\",\"Kaakkois-Suomen Ammattikorkeakoulu\",",
              "\t\"Kymenlaakson Ammattikorkeakoulu\",\"Kaakkois-Suomen Ammattikorkeakoulu\",",
              "\t\"Kemi-Tornion Ammattikorkeakoulu\",\"Lapin Ammattikorkeakoulu\",",
              "\t\"Rovaniemen Ammattikorkeakoulu\",\"Lapin Ammattikorkeakoulu\",",
              "\tMuuttujat[Organisaatio 1]))"
            ],
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Rahoitusmalliala, amk",
            "dataType": "string",
            "sourceColumn": "Rahoitusmalliala, amk",
            "sortByColumn": "jarj. rahoitusmalliala amk",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Tieteenala",
            "dataType": "string",
            "sourceColumn": "Tieteenala",
            "sortByColumn": "jarj. tieteenala",
            "displayFolder": "Tieteenalamuuttujat"
          },
          {
            "name": "Tutkijanuravaihe",
            "dataType": "string",
            "sourceColumn": "Tutkijanuravaihe",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "YO Julkaisut (A1-A4, C1) jufotaso 1-3",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "YO Julkaisut (A1-A4, C1) jufotaso 1-3"
          },
          {
            "name": "sijoittuminen_3v_tutkinnon_jalkeen",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "sijoittuminen_3v_tutkinnon_jalkeen"
          },
          {
            "name": "Ensisijainen hakija",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Ensisijainen hakija"
          },
          {
            "name": "Paikan vastaanottaneet",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Paikan vastaanottaneet"
          },
          {
            "name": "jarj. rahoitusmalliala amk",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarj. rahoitusmalliala amk"
          },
          {
            "name": "jarj. paatieteenala",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarj. paatieteenala"
          },
          {
            "name": "jarj. tieteenala",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarj. tieteenala"
          },
          {
            "name": "JulkaisuID",
            "dataType": "string",
            "sourceColumn": "JulkaisuID",
            "displayFolder": "Julkaisumuuttujat"
          },
          {
            "name": "Jufotaso",
            "dataType": "int64",
            "sourceColumn": "Jufotaso",
            "displayFolder": "Julkaisumuuttujat"
          },
          {
            "name": "Kilpailtu tutkimusrahoitus (SA,Tekes, EU-puiteohjelma)",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Kilpailtu tutkimusrahoitus (SA,Tekes, EU-puiteohjelma)"
          },
          {
            "name": "Koulutusnimike",
            "dataType": "string",
            "sourceColumn": "Koulutusnimike",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "type": "calculated",
            "name": "org_päätieteenala",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "IF(ISBLANK(Muuttujat[Päätieteenala]),BLANK(),Muuttujat[Koodit organisaatio]&\"_\"&Muuttujat[Päätieteenala])"
          },
          {
            "name": "Koodit Koulutusnimike",
            "dataType": "string",
            "sourceColumn": "Koodit Koulutusnimike",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Tieteenala_avain",
            "dataType": "string",
            "sourceColumn": "Tieteenala_avain",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "type": "calculated",
            "name": "org_TA-avain",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "Muuttujat[Koodit organisaatio]&\"_\"&Muuttujat[Tieteenala_avain]"
          },
          {
            "name": "Organisaatio 1",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Organisaatio"
          },
          {
            "name": "Koodit organisaatio",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Koodit organisaatio"
          },
          {
            "type": "calculated",
            "name": "Organisaatio koodi",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "SWITCH(IF(NOT(ISBLANK([Aloituslukuvuosi (läpäisy)])),Muuttujat[Koodit organisaatio]),",
              "\t\"01742\",\"10103\",",
              "\t\"01717\",\"10103\",",
              "\t\"01740\",\"10103\",",
              "SWITCH([Koodit organisaatio],",
              "\t\"02506\",\"10118\",",
              "\t\"02608\",\"10118\",",
              "\t\"02505\",\"10108\",",
              "\t\"02538\",\"10108\",",
              "\t[Koodit organisaatio]))"
            ],
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Tutkinnon aloitussykli",
            "dataType": "string",
            "sourceColumn": "Tutkinnon aloitussykli",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Osallistuminen huippuyksik.",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Osallistuminen huippuyksik."
          },
          {
            "name": "Akatemia profesuurit",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Akatemia profesuurit"
          },
          {
            "name": "erc,stg,cog ja adg",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "erc,stg,cog ja adg"
          },
          {
            "name": "Aloituslukuvuosi (läpäisy)",
            "dataType": "string",
            "sourceColumn": "Aloituslukuvuosi (läpäisy)",
            "displayFolder": "Aikamuuttujat"
          },
          {
            "name": "Päätieteenala",
            "dataType": "string",
            "sourceColumn": "Päätieteenala",
            "displayFolder": "Tieteenalamuuttujat"
          },
          {
            "name": "Läsnäolevat opiskelijat (55op)",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Läsnäolevat opiskelijat (55op)"
          },
          {
            "name": "Läsnäolleet opiskelijat (1-14op)",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Läsnäolleet opiskelijat (1-14op)"
          },
          {
            "name": "Yliopiston opetus- ja tutkimushenkilötyövuodet",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Yliopiston opetus- ja tutkimushenkilötyövuodet"
          },
          {
            "name": "IV tutkijanuraportaan henkilötyövuodet",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "IV tutkijanuraportaan henkilötyövuodet"
          },
          {
            "name": "Ammattikorkeakoulun opetushenkilökunta",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Ammattikorkeakoulun opetushenkilökunta"
          },
          {
            "name": "Ammattikorkeakoulun TKI-henkilökunta",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Ammattikorkeakoulun TKI-henkilökunta"
          },
          {
            "name": "YO kansainvälinen yhteisjulkaisu (A1-A4, C1 ja C2) jufotaso 1-3",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "YO kansainvälinen yhteisjulkaisu (A1-A4, C1 ja C2) jufotaso 1-3"
          },
          {
            "name": "työlliset 1v tutkinnon jälkeen",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "työlliset 1v tutkinnon jälkeen"
          },
          {
            "name": "Työlliset 3v tutkinnon jälkeen",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Työlliset 3v tutkinnon jälkeen"
          },
          {
            "name": "Työlliset 3v (ver2 10,13)",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Työlliset 3v (ver2 10,13)"
          },
          {
            "name": "Työttömät 3v (ver2, 12)",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Työttömät 3v (ver2, 12)"
          },
          {
            "name": "Kandikyselyn pistemäärä",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Kandikyselyn pistemäärä"
          },
          {
            "name": "AVOP-AMK pistemäärä",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "AVOP-AMK pistemäärä"
          },
          {
            "name": "AVOP-AMK Opiskelijapalaute_työelämä",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "AVOP-AMK Opiskelijapalaute_työelämä"
          },
          {
            "name": "AVOP-YAMK Opiskelijapalaute_työelämä",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "AVOP-YAMK Opiskelijapalaute_työelämä"
          },
          {
            "name": "Opiskelijat",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Opiskelijat"
          },
          {
            "name": "Opiskelijat_fte",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Opiskelijat_fte"
          },
          {
            "name": "Opiskelijat_lasna",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Opiskelijat_lasna"
          },
          {
            "type": "calculated",
            "name": "Org_OA",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "Muuttujat[Organisaatio koodi]&\"_\"&Muuttujat[Koodit OKM ohjauksen ala]"
          },
          {
            "name": "toimipiste_id",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "toimipiste_id"
          },
          {
            "name": "hakukohde_id",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "hakukohde_id"
          },
          {
            "name": "alpa",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "alpa"
          },
          {
            "type": "calculated",
            "name": "alpa_key",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "Muuttujat[Tilastovuosi]&\"_\"&Muuttujat[Tutkinnon aloitussykli]&\"_\"&Muuttujat[Organisaatio koodi]&\"_\"&Muuttujat[toimipiste_id]&\"_\"&Muuttujat[hakukohde_id]"
          },
          {
            "name": "Rahoitusmalliala, yo 2017-2020",
            "dataType": "string",
            "sourceColumn": "Rahoitusmalliala, yo 2017-2020",
            "sortByColumn": "jarj. rahoitusmalliala yo 2017-2020",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "jarj. rahoitusmalliala yo 2017-2020",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarj. rahoitusmalliala yo 2017-2020"
          },
          {
            "name": "Rahoitusmalliala, yo 2021-2024",
            "dataType": "string",
            "sourceColumn": "Rahoitusmalliala, yo 2021-2024",
            "sortByColumn": "jarj. rahoitusmalliala yo 2021-2024",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "jarj. rahoitusmalliala yo 2021-2024",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarj. rahoitusmalliala yo 2021-2024"
          },
          {
            "name": "Koulutusaste (2002)",
            "dataType": "string",
            "sourceColumn": "Koulutusaste 2002",
            "displayFolder": "Koulutusmuuttujat"
          }
        ],
        "partitions": [
          {
            "name": "v_indikaattori_asemointi",
            "dataView": "full",
            "source": {
              "query": " SELECT [dw].[v_indikaattori_asemointi].* FROM [dw].[v_indikaattori_asemointi]  WHERE ([Organisaatio] NOT LIKE N'%Poliisi%') ",
              "dataSource": "SqlServer dwitvipusql22 ANTERO 2"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit organisaatio</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>122</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tilastovuosi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>86</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj. OKM ohjauksen ala</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>144</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj. koulutusaste, taso 2</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>151</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj. koulutusaste, taso 1</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>151</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusala, taso 1</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>122</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusala, taso 2</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>122</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusala, taso 3</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>122</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kunta</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>58</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit kunta</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>90</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tutkinnot</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>73</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Yo 7v aloittaneet lkm</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>130</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>5v_Aloittaneet_lkm</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>122</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>7v_suorittaneet_lkm</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>128</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>5v_suorittaneet_lkm</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>128</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Sektori</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>63</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>55op suorittaneet</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>116</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>1-14op suorittaneet</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>126</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>AVOP-YAMK Opiskelijapalaute_työelämä</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>222</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>AVOP-AMK Opiskelijapalaute_työelämä</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>216</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>AVOP-AMK pistemäärä</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>138</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>AMK Julkaisut (A-E)</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>123</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>YO Julkaisut (A1-A4, C1 ja C2) jufotaso 2 ja 3</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>250</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>YO Julkaisut (A1-A4, C1 ja C2) jufotaso 1-3</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>239</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kandikyselyn pistemäärä</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>148</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kilpailtu tutkimusrahoitus</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>148</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>kv_vaihtoopiskelijat_op_lkm</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>163</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ulkom_hyv_luetut_op_lkm</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>154</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>erilopintooik_op_lkm</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>126</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>avoinamk_op_amk_lkm</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>139</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>mamu_op_lkm</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>97</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>erikoul_suor_op_lkm</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>127</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>sijoittuminen_1v_tutkinnon_jalkeen</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>199</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Työttömät 3v (ver2, 12)</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>147</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Työlliset 3v (ver2 10,13)</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>148</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Työlliset 3v tutkinnon jälkeen</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>169</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Organisaatio</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>91</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit OKM ohjauksen ala</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>154</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kansalaisuus</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>91</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusaste, taso 2</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>129</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusaste, taso 1</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>129</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>OKM ohjauksen ala</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>121</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusaste 2002</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>119</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>työlliset 1v tutkinnon jälkeen</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>167</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>YO kansainvälinen yhteisjulkaisu (A1-A4, C1 ja C2) jufotaso 1-3</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>335</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Ammattikorkeakoulun TKI-henkilökunta</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>215</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>AMK julkaisut (F ja I)</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>129</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Ammattikorkeakoulun opetushenkilökunta</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>228</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Rahoitusmalliala, amk</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>132</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj. rahoitusmalliala yo 2021-2024</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>246</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>IV tutkijanuraportaan henkilötyövuodet</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>219</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tieteenala</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>80</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tutkijanuravaihe</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>110</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>YO Julkaisut (A1-A4, C1) jufotaso 1-3</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>211</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>sijoittuminen_3v_tutkinnon_jalkeen</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>199</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Yliopiston opetus- ja tutkimushenkilötyövuodet</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>253</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Läsnäolleet opiskelijat (1-14op)</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>179</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Läsnäolevat opiskelijat (55op)</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>173</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Ensisijainen hakija</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>116</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Paikan vastaanottaneet</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>145</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj. rahoitusmalliala amk</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>148</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Rahoitusmalliala, yo 2021-2024</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>226</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj. paatieteenala</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>119</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj. tieteenala</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>101</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>JulkaisuID</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>78</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Jufotaso</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>72</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kilpailtu tutkimusrahoitus (SA,Tekes, EU-puiteohjelma)</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>289</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusnimike</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>100</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit Koulutusnimike</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>133</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Päätieteenala</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>96</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tieteenala_avain</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>112</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Aloituslukuvuosi (läpäisy)</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>150</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tutkinnon aloitussykli</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>131</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Osallistuminen huippuyksik.</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>160</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Akatemia profesuurit</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>130</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>erc,stg,cog ja adg</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>118</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Opiskelijat</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>79</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Opiskelijat_fte</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>99</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Opiskelijat_lasna</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>110</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>toimipiste_id</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>110</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>hakukohde_id</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>121</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Rahoitusmalliala, yo 2017-2020</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>226</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj. rahoitusmalliala yo 2017-2020</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>246</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>alpa</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>59</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit organisaatio</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>52</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tilastovuosi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj. OKM ohjauksen ala</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>30</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj. koulutusaste, taso 2</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>29</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj. koulutusaste, taso 1</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>28</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusala, taso 1</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusala, taso 2</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusala, taso 3</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kunta</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit kunta</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>32</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tutkinnot</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>5</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Yo 7v aloittaneet lkm</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>6</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>5v_Aloittaneet_lkm</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>7</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>7v_suorittaneet_lkm</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>8</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>5v_suorittaneet_lkm</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>9</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Sektori</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>22</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>55op suorittaneet</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>10</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>1-14op suorittaneet</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>11</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>AVOP-YAMK Opiskelijapalaute_työelämä</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>73</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>AVOP-AMK Opiskelijapalaute_työelämä</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>72</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>AVOP-AMK pistemäärä</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>71</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>AMK Julkaisut (A-E)</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>33</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>YO Julkaisut (A1-A4, C1 ja C2) jufotaso 2 ja 3</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>12</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>YO Julkaisut (A1-A4, C1 ja C2) jufotaso 1-3</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>13</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kandikyselyn pistemäärä</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>70</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kilpailtu tutkimusrahoitus</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>14</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>kv_vaihtoopiskelijat_op_lkm</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>15</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ulkom_hyv_luetut_op_lkm</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>16</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>erilopintooik_op_lkm</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>17</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>avoinamk_op_amk_lkm</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>18</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>mamu_op_lkm</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>19</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>erikoul_suor_op_lkm</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>20</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>sijoittuminen_1v_tutkinnon_jalkeen</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>21</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Työttömät 3v (ver2, 12)</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>69</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Työlliset 3v (ver2 10,13)</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>68</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Työlliset 3v tutkinnon jälkeen</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>67</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Organisaatio</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>51</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit OKM ohjauksen ala</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>31</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kansalaisuus</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>27</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusaste, taso 2</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>26</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusaste, taso 1</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>25</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>OKM ohjauksen ala</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>24</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusaste 2002</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>23</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>työlliset 1v tutkinnon jälkeen</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>66</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>YO kansainvälinen yhteisjulkaisu (A1-A4, C1 ja C2) jufotaso 1-3</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>65</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Ammattikorkeakoulun TKI-henkilökunta</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>64</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>AMK julkaisut (F ja I)</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>34</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Ammattikorkeakoulun opetushenkilökunta</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>63</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Rahoitusmalliala, amk</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>35</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj. rahoitusmalliala yo 2021-2024</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>83</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>IV tutkijanuraportaan henkilötyövuodet</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>62</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tieteenala</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>36</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tutkijanuravaihe</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>37</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>YO Julkaisut (A1-A4, C1) jufotaso 1-3</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>38</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>sijoittuminen_3v_tutkinnon_jalkeen</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>39</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Yliopiston opetus- ja tutkimushenkilötyövuodet</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>61</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Läsnäolleet opiskelijat (1-14op)</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>60</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Läsnäolevat opiskelijat (55op)</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>59</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Ensisijainen hakija</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>40</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Paikan vastaanottaneet</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>41</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj. rahoitusmalliala amk</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>42</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Rahoitusmalliala, yo 2021-2024</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>82</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj. paatieteenala</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>43</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj. tieteenala</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>44</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>JulkaisuID</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>45</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Jufotaso</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>46</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kilpailtu tutkimusrahoitus (SA,Tekes, EU-puiteohjelma)</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>47</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusnimike</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>48</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit Koulutusnimike</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>49</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Päätieteenala</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>58</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tieteenala_avain</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>50</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Aloituslukuvuosi (läpäisy)</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>57</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tutkinnon aloitussykli</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>53</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Osallistuminen huippuyksik.</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>54</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Akatemia profesuurit</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>55</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>erc,stg,cog ja adg</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>56</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Opiskelijat</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>74</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Opiskelijat_fte</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>75</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Opiskelijat_lasna</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>76</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>toimipiste_id</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>77</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>hakukohde_id</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>78</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Rahoitusmalliala, yo 2017-2020</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>79</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj. rahoitusmalliala yo 2017-2020</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>80</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>alpa</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>81</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit organisaatio</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tilastovuosi</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit kunta</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kansalaisuus</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusaste, taso 2</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusaste, taso 1</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>OKM ohjauksen ala</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusaste 2002</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Sektori</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>AVOP-YAMK Opiskelijapalaute_työelämä</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>AVOP-AMK Opiskelijapalaute_työelämä</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>AVOP-AMK pistemäärä</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Organisaatio</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit OKM ohjauksen ala</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj. koulutusaste, taso 1</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj. koulutusaste, taso 2</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj. OKM ohjauksen ala</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>AMK Julkaisut (A-E)</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>AMK julkaisut (F ja I)</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusala, taso 1</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusala, taso 2</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusala, taso 3</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kunta</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tutkinnot</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Yo 7v aloittaneet lkm</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>5v_Aloittaneet_lkm</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>7v_suorittaneet_lkm</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>5v_suorittaneet_lkm</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>55op suorittaneet</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>1-14op suorittaneet</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kandikyselyn pistemäärä</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Työttömät 3v (ver2, 12)</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Työlliset 3v (ver2 10,13)</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>YO Julkaisut (A1-A4, C1 ja C2) jufotaso 2 ja 3</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>YO Julkaisut (A1-A4, C1 ja C2) jufotaso 1-3</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Työlliset 3v tutkinnon jälkeen</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kilpailtu tutkimusrahoitus</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>kv_vaihtoopiskelijat_op_lkm</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ulkom_hyv_luetut_op_lkm</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>erilopintooik_op_lkm</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>avoinamk_op_amk_lkm</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>mamu_op_lkm</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>erikoul_suor_op_lkm</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>sijoittuminen_1v_tutkinnon_jalkeen</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>työlliset 1v tutkinnon jälkeen</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>YO kansainvälinen yhteisjulkaisu (A1-A4, C1 ja C2) jufotaso 1-3</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Ammattikorkeakoulun TKI-henkilökunta</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Ammattikorkeakoulun opetushenkilökunta</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Rahoitusmalliala, amk</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj. rahoitusmalliala yo 2021-2024</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>IV tutkijanuraportaan henkilötyövuodet</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tieteenala</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tutkijanuravaihe</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>YO Julkaisut (A1-A4, C1) jufotaso 1-3</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>sijoittuminen_3v_tutkinnon_jalkeen</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Yliopiston opetus- ja tutkimushenkilötyövuodet</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Läsnäolleet opiskelijat (1-14op)</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Läsnäolevat opiskelijat (55op)</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Ensisijainen hakija</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Paikan vastaanottaneet</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj. rahoitusmalliala amk</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Rahoitusmalliala, yo 2021-2024</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj. paatieteenala</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj. tieteenala</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>JulkaisuID</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Jufotaso</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kilpailtu tutkimusrahoitus (SA,Tekes, EU-puiteohjelma)</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusnimike</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit Koulutusnimike</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Päätieteenala</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tieteenala_avain</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Aloituslukuvuosi (läpäisy)</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tutkinnon aloitussykli</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Osallistuminen huippuyksik.</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Akatemia profesuurit</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>erc,stg,cog ja adg</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Opiskelijat</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Opiskelijat_fte</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Opiskelijat_lasna</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>toimipiste_id</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>hakukohde_id</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Rahoitusmalliala, yo 2017-2020</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj. rahoitusmalliala yo 2017-2020</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>alpa</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter>",
                  "    <item>",
                  "      <key>",
                  "        <string>Organisaatio</string>",
                  "      </key>",
                  "      <value>",
                  "        <FilterExpression xsi:type=\"ConditionalExpression\">",
                  "          <Operator>NotContains</Operator>",
                  "          <Value xsi:type=\"xsd:string\">Poliisi</Value>",
                  "        </FilterExpression>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnFilter>",
                  "  <SelectionFilter>",
                  "    <item>",
                  "      <key>",
                  "        <string>Organisaatio</string>",
                  "      </key>",
                  "      <value>",
                  "        <SelectionFilter xsi:nil=\"true\" />",
                  "      </value>",
                  "    </item>",
                  "  </SelectionFilter>",
                  "  <FilterParameters>",
                  "    <item>",
                  "      <key>",
                  "        <string>Organisaatio</string>",
                  "      </key>",
                  "      <value>",
                  "        <CommandParameters />",
                  "      </value>",
                  "    </item>",
                  "  </FilterParameters>",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Vähintään 55op suorittaneet",
            "expression": "SUM([55op suorittaneet])",
            "formatString": "### ### ###",
            "displayFolder": "Opintopisteet\\Asemointi"
          },
          {
            "name": "Vähintään 55 op suorittaneiden osuus",
            "expression": " DIVIDE([Vähintään 55op suorittaneet],SUM([Läsnäolevat opiskelijat (55op)]))",
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Opintopisteet\\Asemointi"
          },
          {
            "name": "Tutkinnot lkm",
            "expression": [
              " ",
              "var lkm = SUM([tutkinnot])",
              "return IF(lkm = 0, BLANK(), IF(lkm < 5, \"1-4\", MROUND(lkm, 3)))"
            ],
            "formatString": "### ### ###",
            "displayFolder": "Tutkinnot\\Asemointi"
          },
          {
            "name": "Ylemmät tutkinnot / opetus- ja tutkimushenkilökunta",
            "expression": [
              " ",
              "var osa = CALCULATE([Tutkinnot lkm],Muuttujat[Koulutusaste, taso 2]=\"Ylempi korkeakoulututkinto\" || Muuttujat[Koulutusaste, taso 2]=\"Ylempi ammattikorkeakoulututkinto\" || Muuttujat[Koulutusaste, taso 2]=\"Master's or equivalent level, Orientation unspecified\" )",
              "var kaikki = CALCULATE(SUM([Yliopiston opetus- ja tutkimushenkilötyövuodet])+(SUM([Ammattikorkeakoulun opetushenkilökunta])+SUM([Ammattikorkeakoulun TKI-henkilökunta])))",
              "return IF(osa = BLANK(), BLANK(),",
              "IF(osa = \"1-4\", IF(kaikki > 8000, \"0.0\",",
              "CONCATENATE(FORMAT(1 / kaikki, \"0.0 – \"), FORMAT(4 / kaikki, \"0.0\"))),",
              "osa / kaikki))"
            ],
            "formatString": "0.0",
            "displayFolder": "Tutkinnot\\Asemointi"
          },
          {
            "name": "Tohtorin tutkinnot / IV porras henkilötyövuodet",
            "expression": [
              " ",
              "var osa = CALCULATE([Tutkinnot lkm],Muuttujat[Koulutusaste, taso 2]=\"Tohtorintutkinto\")",
              "var kaikki = SUM(Muuttujat[IV tutkijanuraportaan henkilötyövuodet])",
              "return IF(osa = BLANK(), BLANK(),",
              "IF(osa = \"1-4\", IF(kaikki > 8000, \"0.0\",",
              "CONCATENATE(FORMAT(1 / kaikki, \"0.0 – \"), FORMAT(4 / kaikki, \"0.0\"))),",
              "osa / kaikki))"
            ],
            "formatString": "0.0",
            "displayFolder": "Tutkinnot\\Asemointi"
          },
          {
            "name": "Seitsemän vuoden läpäisy (yo)",
            "expression": [
              "",
              "var osa = [7v suorittaneet]",
              "var kaikki = [7v aloittaneet]",
              "return IF(osa = BLANK(), BLANK(),",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, \"0.0 %\",",
              "CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Läpäisy\\Asemointi"
          },
          {
            "name": "Viiden vuoden läpäisy (amk)",
            "expression": [
              "",
              "var osa = [5v suorittaneet]",
              "var kaikki = [5v aloittaneet]",
              "return IF(osa = BLANK(), BLANK(),",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, \"0.0 %\",",
              "CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Läpäisy\\Asemointi"
          },
          {
            "name": "Ulkomaalaisten suorittamien tutkintojen osuus",
            "expression": [
              " ",
              "var osa = CALCULATE([Tutkinnot lkm],Muuttujat[Kansalaisuus]<>\"Suomi\")",
              "var kaikki = [Tutkinnot lkm]",
              "return IF(osa = BLANK(), BLANK(),",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, \"0.0 %\",",
              "CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Tutkinnot\\Asemointi"
          },
          {
            "name": "Kilpailtu tutkimusrahoitus / IV porras henkilötyövuodet",
            "expression": " DIVIDE(SUM([Kilpailtu tutkimusrahoitus]),SUM(Muuttujat[IV tutkijanuraportaan henkilötyövuodet]))",
            "formatString": "0.0",
            "displayFolder": "Talous\\Asemointi"
          },
          {
            "name": "Yo julkaisut (jufo-tasot 2-3, A1-A4, C1 ja C2) lkm",
            "expression": " SUM([YO Julkaisut (A1-A4, C1 ja C2) jufotaso 2 ja 3])",
            "formatString": "### ### ###.###",
            "displayFolder": "Julkaisut\\Asemointi"
          },
          {
            "name": "Yo julkaisut (jufo 1-3, A1-A4, C1 ja C2) lkm",
            "expression": " SUM([YO Julkaisut (A1-A4, C1 ja C2) jufotaso 1-3])",
            "formatString": "### ### ###.###",
            "displayFolder": "Julkaisut\\Asemointi"
          },
          {
            "name": "Yo julkaisut (jufo-tasot 2-3) / opetus- ja tutkimushenkilökunta",
            "expression": " DIVIDE([Yo julkaisut (jufo-tasot 2-3, A1-A4, C1 ja C2) lkm],SUM([Yliopiston opetus- ja tutkimushenkilötyövuodet]))",
            "formatString": "0.0",
            "displayFolder": "Julkaisut\\Asemointi"
          },
          {
            "name": "Yo kansainvälisten yhteisjulkaisujen osuus (jufo 1-3 julkaisut)",
            "expression": " DIVIDE(SUM(Muuttujat[YO kansainvälinen yhteisjulkaisu (A1-A4, C1 ja C2) jufotaso 1-3]),[Yo julkaisut (jufo 1-3, A1-A4, C1 ja C2) lkm])",
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Julkaisut\\Asemointi"
          },
          {
            "name": "1-14op suorittaneet lkm",
            "expression": [
              " IF(SUM([1-14op suorittaneet]) = 0, BLANK(), IF(SUM([1-14op suorittaneet]) < 5, \"1-4\", MROUND(SUM([1-14op suorittaneet]), 3)))",
              ""
            ],
            "formatString": "### ### ###",
            "displayFolder": "Opintopisteet\\Asemointi"
          },
          {
            "name": "1-14op suorittaneiden osuus",
            "expression": [
              " ",
              "var osa = [1-14op suorittaneet lkm]",
              "var kaikki = [Lasna (1-14)]",
              "return IF(osa = BLANK(), BLANK(),",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa= \"1-4\", IF(kaikki > 8000, \"0.0 %\", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Opintopisteet\\Asemointi"
          },
          {
            "name": "Alemmat korkeakoulututkinnot /opetus- ja tutkimushenkilökunta",
            "expression": [
              " ",
              "var osa = CALCULATE([Tutkinnot lkm],Muuttujat[Koulutusaste, taso 2]=\"Alempi korkeakoulututkinto\" || Muuttujat[Koulutusaste, taso 2]=\"Ammattikorkeakoulututkinto\")",
              "var kaikki = CALCULATE(SUM([Yliopiston opetus- ja tutkimushenkilötyövuodet])+(SUM([Ammattikorkeakoulun opetushenkilökunta])+SUM([Ammattikorkeakoulun TKI-henkilökunta])))",
              "return IF(osa = BLANK(), BLANK(),",
              "IF(osa = \"1-4\", IF(kaikki > 8000, \"0.0\",",
              "CONCATENATE(FORMAT(1 / kaikki, \"0.0 – \"), FORMAT(4 / kaikki, \"0.0\"))),",
              "osa / kaikki))"
            ],
            "formatString": "0.0",
            "displayFolder": "Tutkinnot\\Asemointi"
          },
          {
            "name": "Saapuneiuden ja lähteneiden vaihto-opiskelijoiden pisteet",
            "expression": " IF(SUM([kv_vaihtoopiskelijat_op_lkm])+SUM(Muuttujat[ulkom_hyv_luetut_op_lkm])=0,BLANK(),SUM([kv_vaihtoopiskelijat_op_lkm])+SUM(Muuttujat[ulkom_hyv_luetut_op_lkm]))",
            "formatString": "### ### ###.###",
            "displayFolder": "Opintopisteet\\Asemointi"
          },
          {
            "name": "Muut kuin tutkinto-opetuksen opintopisteet",
            "expression": [
              " ",
              "\tIF(",
              "\tSUM([avoinamk_op_amk_lkm])+",
              "\tSUM(Muuttujat[erilopintooik_op_lkm])+",
              "\tSUM([mamu_op_lkm])+",
              "\tSUM([erikoul_suor_op_lkm])=0,BLANK(),",
              "\tSUM([avoinamk_op_amk_lkm])+",
              "\tSUM(Muuttujat[erilopintooik_op_lkm])+",
              "\tSUM([mamu_op_lkm])+",
              "\tSUM([erikoul_suor_op_lkm]",
              "))"
            ],
            "formatString": "### ### ###",
            "displayFolder": "Opintopisteet\\Asemointi"
          },
          {
            "name": "Työllisten osuus (1v tutkinnon jälkeen)",
            "expression": [
              " ",
              "var osa = [Työlliset (1v tutkinnon jälkeen)]",
              "var kaikki = [sijoittuminen perusjoukko 1v tutkinnon jälkeen]",
              "return IF(osa = BLANK(), BLANK(),",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, \"0.0 %\",",
              "CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Työllisyys\\Asemointi"
          },
          {
            "name": "AVOP-palautteen pisteet (rahoitusmallikysymykset)",
            "expression": " SUM([AVOP-AMK pistemäärä])",
            "formatString": "### ### ###.###",
            "displayFolder": "Opiskelijapalaute\\Asemointi"
          },
          {
            "name": "Kandipalautteen pisteet (rahoitusmallikysymykset)",
            "expression": " SUM([Kandikyselyn pistemäärä])",
            "formatString": "### ### ###.###",
            "displayFolder": "Opiskelijapalaute\\Asemointi"
          },
          {
            "name": "Tutkijanuraporras IV henkilötyövuodet",
            "expression": "SUM([IV tutkijanuraportaan henkilötyövuodet])",
            "formatString": "### ### ###.###",
            "displayFolder": "Henkilöstö\\Asemointi"
          },
          {
            "name": "lasna (55)",
            "expression": " SUM(Muuttujat[Läsnäolevat opiskelijat (55op)])",
            "formatString": "### ### ###.###",
            "displayFolder": "Opintopisteet\\Asemointi"
          },
          {
            "name": "Yo opetus- ja tutkimushenkilötyövuodet",
            "expression": " SUM([Yliopiston opetus- ja tutkimushenkilötyövuodet])",
            "formatString": "### ### ###.###",
            "displayFolder": "Henkilöstö\\Asemointi"
          },
          {
            "name": "Amk opetus- ja tki henkilötyövuodet",
            "expression": " SUM([Ammattikorkeakoulun opetushenkilökunta])+SUM([Ammattikorkeakoulun TKI-henkilökunta])",
            "formatString": "### ### ###.###",
            "displayFolder": "Henkilöstö\\Asemointi"
          },
          {
            "name": "Työlliset (1v tutkinnon jälkeen)",
            "expression": [
              "",
              "var lkm = CALCULATE(SUM(Muuttujat[työlliset 1v tutkinnon jälkeen]))",
              "return IF(lkm = 0, BLANK(), IF(lkm < 5, \"1-4\", MROUND(lkm, 3)))"
            ],
            "formatString": "### ### ###.###",
            "displayFolder": "Työllisyys\\Asemointi"
          },
          {
            "name": "sijoittuminen perusjoukko 1v tutkinnon jälkeen",
            "expression": [
              "  ",
              "var lkm= CALCULATE(SUM(Muuttujat[sijoittuminen_1v_tutkinnon_jalkeen]))",
              "return IF(lkm = 0, BLANK(), IF(lkm < 5, \"1-4\", MROUND(lkm, 3)))"
            ],
            "formatString": "### ### ###.###",
            "displayFolder": "Työllisyys\\Asemointi"
          },
          {
            "name": "Ulkomaalaisten suorittamat tutkinnot",
            "expression": "CALCULATE([Tutkinnot lkm],Muuttujat[Kansalaisuus]<>\"Suomi\")",
            "displayFolder": "Tutkinnot\\Asemointi"
          },
          {
            "name": "7v suorittaneet",
            "expression": [
              "",
              "var lkm = CALCULATE(SUM(Muuttujat[7v_suorittaneet_lkm]))",
              "return IF(lkm = 0, BLANK(), IF(lkm < 5, \"1-4\", MROUND(lkm, 3)))"
            ],
            "displayFolder": "Läpäisy\\Asemointi"
          },
          {
            "name": "7v aloittaneet",
            "expression": [
              "",
              "var lkm = CALCULATE(SUM([Yo 7v aloittaneet lkm]))",
              "return IF(lkm = 0, BLANK(), IF(lkm < 5, \"1-4\", MROUND(lkm, 3)))"
            ],
            "displayFolder": "Läpäisy\\Asemointi"
          },
          {
            "name": "5v aloittaneet",
            "expression": [
              "",
              "var lkm = CALCULATE(SUM([5v_Aloittaneet_lkm]))",
              "return IF(lkm = 0, BLANK(), IF(lkm < 5, \"1-4\", MROUND(lkm, 3)))"
            ],
            "displayFolder": "Läpäisy\\Asemointi"
          },
          {
            "name": "5v suorittaneet",
            "expression": [
              "",
              "var lkm = CALCULATE(SUM([5v_suorittaneet_lkm]))",
              "return IF(lkm = 0, BLANK(), IF(lkm < 5, \"1-4\", MROUND(lkm, 3)))"
            ],
            "displayFolder": "Läpäisy\\Asemointi"
          },
          {
            "name": "Kilpailtu tki-rahoitus",
            "expression": " SUM([Kilpailtu tutkimusrahoitus])",
            "formatString": "### ### ### ###.###",
            "displayFolder": "Talous\\asemointi"
          },
          {
            "name": "Yo kansainväliset yhteisjulkaisut",
            "expression": "SUM(Muuttujat[YO kansainvälinen yhteisjulkaisu (A1-A4, C1 ja C2) jufotaso 1-3])",
            "formatString": "### ### ###.###",
            "displayFolder": "Julkaisut\\Asemointi"
          },
          {
            "name": "Amk julkaisut (A-F, I) lkm",
            "expression": " SUM(Muuttujat[AMK Julkaisut (A-E)])+SUM([AMK julkaisut (F ja I)])",
            "displayFolder": "Julkaisut\\Asemointi"
          },
          {
            "name": "AMK julkaisut (A-F, I) / opetus- ja tutkimushenkilökunta",
            "expression": " DIVIDE([Amk julkaisut (A-F, I) lkm],SUM([Ammattikorkeakoulun opetushenkilökunta])+SUM([Ammattikorkeakoulun TKI-henkilökunta]))",
            "displayFolder": "Julkaisut\\Asemointi"
          },
          {
            "name": "Amk opetus htv",
            "expression": " SUM([Ammattikorkeakoulun opetushenkilökunta])",
            "displayFolder": "Henkilöstö\\Asemointi"
          },
          {
            "name": "Amk tki htv",
            "expression": " SUM([Ammattikorkeakoulun TKI-henkilökunta])",
            "displayFolder": "Henkilöstö\\Asemointi"
          },
          {
            "name": "AMK tutkinnot 2015-2017 KA",
            "expression": [
              " ",
              "var tut=",
              "CALCULATE(SUM(Muuttujat[tutkinnot]),",
              "\tFILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),Muuttujat[Koulutusaste, taso 2]=\"Ammattikorkeakoulututkinto\"),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]>2014&&Muuttujat[Tilastovuosi]<2018))",
              "var vuosia= CALCULATE(DISTINCTCOUNT(Muuttujat[Tilastovuosi]),FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]>2014&&Muuttujat[Tilastovuosi]<2018))",
              "",
              "return DIVIDE(tut,3)"
            ],
            "formatString": "0.0",
            "displayFolder": "Tutkinnot\\Rakenteellinen kehittäminen"
          },
          {
            "name": "Osuus alan AMK-tutkinnoista 2015-2017",
            "expression": [
              " ",
              "var kk=CALCULATE(MAXX(SUMMARIZE(Muuttujat,Muuttujat[Koulutusnimike],\"kk\",",
              "\t\tCALCULATE([Tutkinnot lkm],Muuttujat[Koulutusaste, taso 2]=\"Ammattikorkeakoulututkinto\",Muuttujat[Tilastovuosi]=2015||Muuttujat[Tilastovuosi]=2016\t\t\t||Muuttujat[Tilastovuosi]=2017)),[kk]),ALL(Muuttujat[Tilastovuosi]))",
              "var kaik=CALCULATE(MAXX(SUMMARIZE(Muuttujat,Muuttujat[Koulutusnimike],\"kaikki\",",
              "\t\tCALCULATE([Tutkinnot lkm],Muuttujat[Koulutusaste, taso 2]=\"Ammattikorkeakoulututkinto\",Muuttujat[Tilastovuosi]=2015||Muuttujat[Tilastovuosi]=2016\t\t\t||Muuttujat[Tilastovuosi]=2017)),[kaikki]),ALL(Muuttujat[Organisaatio]),ALL(Muuttujat[Tilastovuosi]))",
              "",
              "return DIVIDE(kk,kaik)",
              ""
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Tutkinnot\\Rakenteellinen kehittäminen"
          },
          {
            "name": "Ulkomaalaisten AMK-tutkintojen osuus 2015-2017",
            "expression": [
              "",
              "var kaikki=CALCULATE([Tutkinnot lkm],",
              "\tFILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),[Koulutusaste, taso 2]=\"Ammattikorkeakoulututkinto\"),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]>2014&&Muuttujat[Tilastovuosi]<2018))",
              "var ulk=CALCULATE([Tutkinnot lkm],",
              "\tFILTER(VALUES(Muuttujat[Kansalaisuus]),Muuttujat[Kansalaisuus]<>\"Suomi\"),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]>2014&&Muuttujat[Tilastovuosi]<2018),",
              "\tFILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),[Koulutusaste, taso 2]=\"Ammattikorkeakoulututkinto\"))",
              "",
              "",
              "return DIVIDE(ulk,kaikki)"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Tutkinnot\\Rakenteellinen kehittäminen"
          },
          {
            "name": "Osuus kilpaillusta tutkimusrahoituksesta 2016",
            "expression": [
              "",
              "var lask= CALCULATE(DIVIDE(CALCULATE([Kilpailtu tki-rahoitus (SA,Tekes, EU-puite)]),CALCULATE([Kilpailtu tki-rahoitus (SA,Tekes, EU-puite)],ALL(Muuttujat[Organisaatio]))),FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2016))",
              "return lask",
              ""
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "isHidden": true,
            "displayFolder": "Talous\\Rakenteellinen kehittäminen"
          },
          {
            "name": "IV portaan HTV 2017_vanha",
            "expression": "CALCULATE(SUM([Yliopiston opetus- ja tutkimushenkilötyövuodet]),FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2017),FILTER(VALUES(Muuttujat[Tutkijanuravaihe]),Muuttujat[Tutkijanuravaihe]=\"IV porras (Professori/Akatemiaprofessori/Tutkimusprofessori/Tutkimusjohtaja jne.)\"))",
            "formatString": "0.0",
            "isHidden": true,
            "displayFolder": "Henkilöstö\\Rakenteellinen kehittäminen"
          },
          {
            "name": "IV portaan HTV osuus 2017",
            "expression": [
              "",
              "var kaikki=CALCULATE([IV portaan HTV 2017_vanha],ALL(Muuttujat[Organisaatio]),ALL(Muuttujat[Organisaatio]))",
              "var kk=CALCULATE([IV portaan HTV 2017_vanha])",
              "",
              "return DIVIDE(kk,kaikki)"
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %",
            "isHidden": true,
            "displayFolder": "Henkilöstö\\Rakenteellinen kehittäminen"
          },
          {
            "name": "Tohtorin tutkinnot 2015-2017 KA_koulutusnimikkeet",
            "expression": [
              " ",
              "var tut=CALCULATE(SUM(Muuttujat[tutkinnot]),FILTER(VALUES(Muuttujat[koulutusaste, taso 2]),Muuttujat[Koulutusaste, taso 2]=\"Tohtorintutkinto\"),FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]>2014&&Muuttujat[Tilastovuosi]<2018),ALL(Muuttujat[Koulutusnimike]),ALL(Muuttujat[Koodit Koulutusnimike]))",
              "var vuosia= CALCULATE(DISTINCTCOUNT(Muuttujat[Tilastovuosi]),FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]>2014&&Muuttujat[Tilastovuosi]<2018))",
              "",
              "return DIVIDE(tut,vuosia)",
              ""
            ],
            "formatString": "0.00",
            "isHidden": true,
            "displayFolder": "Tutkinnot\\Rakenteellinen kehittäminen"
          },
          {
            "name": "Osuus ylemmistä kk-tutkinnoista 2015-2017",
            "expression": [
              "",
              "var kk=CALCULATE(MAXX(SUMMARIZE(Muuttujat,Muuttujat[Koulutusnimike],\"kk\",",
              "\t\tCALCULATE([Tutkinnot lkm],Muuttujat[Koulutusaste, taso 2]=\"Ylempi korkeakoulututkinto\",Muuttujat[Tilastovuosi]=2015||Muuttujat[Tilastovuosi]=2016\t\t\t||Muuttujat[Tilastovuosi]=2017)),[kk]),ALL(Muuttujat[Tilastovuosi]))",
              "var kaik=CALCULATE(MAXX(SUMMARIZE(Muuttujat,Muuttujat[Koulutusnimike],\"kaikki\",",
              "\t\tCALCULATE([Tutkinnot lkm],Muuttujat[Koulutusaste, taso 2]=\"Ylempi korkeakoulututkinto\",Muuttujat[Tilastovuosi]=2015||Muuttujat[Tilastovuosi]=2016\t\t\t||Muuttujat[Tilastovuosi]=2017)),[kaikki]),ALL(Muuttujat[Organisaatio]),ALL(Muuttujat[Tilastovuosi]))",
              "",
              "return DIVIDE(kk,kaik)"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Tutkinnot\\Rakenteellinen kehittäminen"
          },
          {
            "name": "Työllistyminen 1v (Ylempi kk-tutkinto) KA 2015-2017",
            "expression": [
              "",
              "var tv = CALCULATE(sum(Muuttujat[sijoittuminen_1v_tutkinnon_jalkeen]),",
              "\t\tfilter(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]>2014&&Muuttujat[Tilastovuosi]<2018),",
              "\t\tFILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),Muuttujat[Koulutusaste, taso 2]=\"Ylempi korkeakoulututkinto\"))",
              "var t = CALCULATE(sum(Muuttujat[työlliset 1v tutkinnon jälkeen]),",
              "\t\tfilter(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]>2014&&Muuttujat[Tilastovuosi]<2018),",
              "\t\tFILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),Muuttujat[Koulutusaste, taso 2]=\"Ylempi korkeakoulututkinto\"))",
              "\t",
              "return CALCULATE(DIVIDE(t,tv))"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Työllisyys\\Rakenteellinen kehittäminen"
          },
          {
            "name": "AMK julkaisut (A-E) 2015-2017",
            "expression": "CALCULATE(SUM([AMK Julkaisut (A-E)]),FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]>2014&&Muuttujat[Tilastovuosi]<2018))",
            "formatString": "### ### ###.###",
            "displayFolder": "Julkaisut\\Rakenteellinen kehittäminen"
          },
          {
            "name": "Vetovoima 2017",
            "expression": [
              "",
              "var hak=CALCULATE(DISTINCTCOUNT([Ensisijainen hakija]),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2017),",
              "\tNOT(ISBLANK(Muuttujat[Ensisijainen hakija])))",
              "var vast=CALCULATE(DISTINCTCOUNT(Muuttujat[Paikan vastaanottaneet]),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2017),",
              "\tNOT(ISBLANK(Muuttujat[Paikan vastaanottaneet])))",
              "return DIVIDE(hak,vast)"
            ],
            "formatString": "0.0",
            "displayFolder": "Haku ja valinta"
          },
          {
            "name": "AVOP-AMK työelämävalmiudet KA 2017",
            "expression": [
              " ",
              "var numero=CALCULATE(AVERAGE([AVOP-AMK Opiskelijapalaute_työelämä]),FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2017))",
              "var kaik=CALCULATE(AVERAGE([AVOP-AMK Opiskelijapalaute_työelämä]),FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2017),ALL(Muuttujat[Organisaatio]))",
              "var jako=DIVIDE(numero,kaik)",
              "return jako"
            ],
            "formatString": "0.00",
            "displayFolder": "Opiskelijapalaute\\Rakenteellinen kehittäminen"
          },
          {
            "name": "AVOP-YAMK työelämävalmiudet KA 2017",
            "expression": [
              " ",
              "var numero=CALCULATE(AVERAGE([AVOP-YAMK Opiskelijapalaute_työelämä]),FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2017))",
              "var kaik=CALCULATE(AVERAGE([AVOP-YAMK Opiskelijapalaute_työelämä]),FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2017),ALL(Muuttujat[Organisaatio]))",
              "var jako=DIVIDE(numero,kaik)",
              "return jako",
              ""
            ],
            "formatString": "0.00",
            "displayFolder": "Opiskelijapalaute\\Rakenteellinen kehittäminen"
          },
          {
            "name": "Jufo suht (1-3, A1-A4, C1) 2014-2016",
            "expression": [
              "",
              "var eka=CALCULATE(AVERAGEX(DISTINCT(Muuttujat[JulkaisuID]),CALCULATE(AVERAGE(Muuttujat[Jufotaso]),NOT(ISBLANK(Muuttujat[YO Julkaisut (A1-A4, C1) jufotaso 1-3])))),FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]>2013&&Muuttujat[Tilastovuosi]<2017))",
              "",
              "",
              "var toka=CALCULATE(AVERAGEX(DISTINCT(Muuttujat[JulkaisuID]), CALCULATE(AVERAGE(Muuttujat[Jufotaso]),NOT(ISBLANK(Muuttujat[YO Julkaisut (A1-A4, C1) jufotaso 1-3])))),ALL(Muuttujat[Organisaatio]),FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]>2013&&Muuttujat[Tilastovuosi]<2017),FILTER(VALUES(Muuttujat[Sektori]),Muuttujat[Sektori]=\"Yliopisto\"))",
              "",
              "var jako=CALCULATE(DIVIDE(eka,toka))",
              "",
              "",
              "return jako"
            ],
            "formatString": "0.00",
            "displayFolder": "Julkaisut\\Rakenteellinen kehittäminen"
          },
          {
            "name": "Kilpailtu tki-rahoitus (SA,Tekes, EU-puite)",
            "expression": " CALCULATE(SUM([Kilpailtu tutkimusrahoitus (SA,Tekes, EU-puiteohjelma)]))",
            "formatString": "### ### ###.###",
            "displayFolder": "Talous\\rakenteellinen kehittäminen"
          },
          {
            "name": "Työlliset (3v tutkinnon jälkeen)",
            "expression": [
              "",
              "var lkm = CALCULATE(SUM(Muuttujat[Työlliset 3v tutkinnon jälkeen]))",
              "return IF(lkm = 0, BLANK(), IF(lkm < 5, \"1-4\", MROUND(lkm, 3)))"
            ],
            "formatString": "### ### ###.###",
            "displayFolder": "Työllisyys\\Asemointi"
          },
          {
            "name": "sijoittuminen perusjoukko 3v tutkinnon jälkeen",
            "expression": [
              " ",
              "var lkm = CALCULATE(SUM(Muuttujat[sijoittuminen_3v_tutkinnon_jalkeen]))",
              "return IF(lkm = 0, BLANK(), IF(lkm < 5, \"1-4\", MROUND(lkm, 3)))"
            ],
            "formatString": "### ### ###.###",
            "displayFolder": "Työllisyys\\Asemointi"
          },
          {
            "name": "Työllisten osuus 3v valmistumisesta 2014-2016",
            "expression": [
              "",
              "var osuus1= CALCULATE([Työllisten osuus (3v tutkinnon jälkeen)],FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2014))",
              "var osuus2= CALCULATE([Työllisten osuus (3v tutkinnon jälkeen)],FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2015))",
              "var osuus3= CALCULATE([Työllisten osuus (3v tutkinnon jälkeen)],FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2016))",
              "",
              "var jako=DIVIDE((osuus1+osuus2+osuus3),3)",
              "",
              "return jako",
              ""
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Työllisyys\\Rakenteellinen kehittäminen"
          },
          {
            "name": "Työllisten osuus (3v tutkinnon jälkeen)",
            "expression": [
              "",
              "var osa = [Työlliset (3v tutkinnon jälkeen)]",
              "var kaikki = [sijoittuminen perusjoukko 3v tutkinnon jälkeen]",
              "return IF(osa = BLANK(), BLANK(),",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, \"0.0 %\",",
              "CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Työllisyys\\Asemointi"
          },
          {
            "name": "Työllistyminen 3v, (RAKE, ykk) KA 2015-2017_old",
            "expression": [
              "",
              "var osuus1= CALCULATE([Työllisten osuus 3v (RAKE-määritelmä)],FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2015),FILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),Muuttujat[Koulutusaste, taso 2]=\"Ylempi korkeakoulututkinto\"))",
              "var osuus2= CALCULATE([Työllisten osuus 3v (RAKE-määritelmä)],FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2016),FILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),Muuttujat[Koulutusaste, taso 2]=\"Ylempi korkeakoulututkinto\"))",
              "var osuus3= CALCULATE([Työllisten osuus 3v (RAKE-määritelmä)],FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2017),FILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),Muuttujat[Koulutusaste, taso 2]=\"Ylempi korkeakoulututkinto\"))",
              "",
              "var jako=DIVIDE((osuus1+osuus2+osuus3),3)",
              "",
              "return jako"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "isHidden": true,
            "displayFolder": "Työllisyys\\Rakenteellinen kehittäminen"
          },
          {
            "name": "Tutkijanuraporras II-IV henkilötyövuodet",
            "expression": [
              "",
              "CALCULATE(SUM(Muuttujat[Yliopiston opetus- ja tutkimushenkilötyövuodet]),",
              "\tOR(Muuttujat[Tutkijanuravaihe]=\"II porras (Tutkijatohtori jne.)\",",
              "\t\tOR(Muuttujat[Tutkijanuravaihe]=\"III porras (Yliopistonlehtori jne.)\",",
              "\t\tMuuttujat[Tutkijanuravaihe]=\"IV porras (Professori/Akatemiaprofessori/Tutkimusprofessori/Tutkimusjohtaja jne.)\"",
              "\t\t)",
              "\t)",
              ")"
            ],
            "displayFolder": "Henkilöstö\\Asemointi"
          },
          {
            "name": "Ulkomaalaisten AMK-tutkintojen osuus 2014-2016",
            "expression": [
              "",
              "var kaikki=CALCULATE([Tutkinnot lkm],",
              "\tFILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),[Koulutusaste, taso 2]=\"Ammattikorkeakoulututkinto\"),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]>2013&&Muuttujat[Tilastovuosi]<2017))",
              "var ulk=CALCULATE([Tutkinnot lkm],",
              "\tFILTER(VALUES(Muuttujat[Kansalaisuus]),Muuttujat[Kansalaisuus]<>\"Suomi\"),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]>2013&&Muuttujat[Tilastovuosi]<2017),",
              "\tFILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),[Koulutusaste, taso 2]=\"Ammattikorkeakoulututkinto\"))",
              "",
              "",
              "return DIVIDE(ulk,kaikki)",
              ""
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Tutkinnot\\Rakenteellinen kehittäminen"
          },
          {
            "name": "AMK tutkinnot 2014-2016 KA",
            "expression": [
              " ",
              "var tut=",
              "CALCULATE(SUM(Muuttujat[tutkinnot]),",
              "\tFILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),Muuttujat[Koulutusaste, taso 2]=\"Ammattikorkeakoulututkinto\"),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]>2013&&Muuttujat[Tilastovuosi]<2017))",
              "var vuosia= CALCULATE(DISTINCTCOUNT(Muuttujat[Tilastovuosi]),FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]>2013&&Muuttujat[Tilastovuosi]<2017))",
              "",
              "return DIVIDE(tut,3)",
              ""
            ],
            "formatString": "0.0",
            "displayFolder": "Tutkinnot\\Rakenteellinen kehittäminen"
          },
          {
            "name": "Vetovoima 2016",
            "expression": [
              "",
              "var hak=CALCULATE(DISTINCTCOUNT([Ensisijainen hakija]),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2016),",
              "\tNOT(ISBLANK(Muuttujat[Ensisijainen hakija])))",
              "var vast=CALCULATE(DISTINCTCOUNT(Muuttujat[Paikan vastaanottaneet]),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2016),",
              "\tNOT(ISBLANK(Muuttujat[Paikan vastaanottaneet])))",
              "return DIVIDE(hak,vast)",
              ""
            ],
            "formatString": "0.0",
            "displayFolder": "Haku ja valinta"
          },
          {
            "name": "Työllisten osuus 1v valmistumisesta 2013-2015 (RAKE, amk-tutkinto)",
            "expression": [
              "",
              "",
              "var tyolliset=CALCULATE(SUM(Muuttujat[työlliset 1v tutkinnon jälkeen]),FILTER(VALUEs(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]>2012&&Muuttujat[Tilastovuosi]<2016),FILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),Muuttujat[Koulutusaste, taso 2]=\"Ammattikorkeakoulututkinto\"))",
              "var kaik=CALCULATE(SUM(Muuttujat[sijoittuminen_1v_tutkinnon_jalkeen]),FILTER(VALUEs(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]>2012&&Muuttujat[Tilastovuosi]<2016),FILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),Muuttujat[Koulutusaste, taso 2]=\"Ammattikorkeakoulututkinto\"))",
              "var jako=CALCULATE(DIVIDE(tyolliset,kaik))",
              "",
              "return jako",
              ""
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Työllisyys\\Rakenteellinen kehittäminen"
          },
          {
            "name": "Työllisten osuus 3v valmistumisesta 2013-2015",
            "expression": [
              "",
              "var osuus1= CALCULATE([Työllisten osuus (3v tutkinnon jälkeen)],FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2013))",
              "var osuus2= CALCULATE([Työllisten osuus (3v tutkinnon jälkeen)],FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2014))",
              "var osuus3= CALCULATE([Työllisten osuus (3v tutkinnon jälkeen)],FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2015))",
              "",
              "var jako=DIVIDE((osuus1+osuus2+osuus3),3)",
              "",
              "return jako",
              ""
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Työllisyys\\Rakenteellinen kehittäminen"
          },
          {
            "name": "AVOP-AMK työelämävalmiudet KA 2016",
            "expression": [
              " ",
              "var numero=CALCULATE(AVERAGE([AVOP-AMK Opiskelijapalaute_työelämä]),FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2016))",
              "var kaik=CALCULATE(AVERAGE([AVOP-AMK Opiskelijapalaute_työelämä]),FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2016),ALL(Muuttujat[Organisaatio]))",
              "var jako=DIVIDE(numero,kaik)",
              "return jako",
              ""
            ],
            "formatString": "0.00",
            "displayFolder": "Opiskelijapalaute\\Rakenteellinen kehittäminen"
          },
          {
            "name": "AVOP-YAMK työelämävalmiude KA 2016",
            "expression": [
              " ",
              "var numero=CALCULATE(AVERAGE([AVOP-YAMK Opiskelijapalaute_työelämä]),FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2016))",
              "var kaik=CALCULATE(AVERAGE([AVOP-YAMK Opiskelijapalaute_työelämä]),FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2016),ALL(Muuttujat[Organisaatio]))",
              "var jako=DIVIDE(numero,kaik)",
              "return jako",
              ""
            ],
            "formatString": "0.00",
            "displayFolder": "Opiskelijapalaute\\Rakenteellinen kehittäminen"
          },
          {
            "name": "AMK julkaisut (A-E) 2014-2016",
            "expression": "CALCULATE(SUM([AMK Julkaisut (A-E)]),FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]>2013&&Muuttujat[Tilastovuosi]<2017))",
            "formatString": "### ### ###.###",
            "displayFolder": "Julkaisut\\Rakenteellinen kehittäminen"
          },
          {
            "name": "Amk opetuksen henkilötyövuodet 2016",
            "expression": [
              " ",
              "var htv=CALCULATE(SUM(calc_amk_htv[calc_amk_opetus_htv_2016]))",
              "var tut=CALCULATE(MIN([tutkinnot]),Muuttujat[Koulutusaste, taso 2]=\"Ammattikorkeakoulututkinto\",Muuttujat[Tilastovuosi]=2016||Muuttujat[Tilastovuosi]=2015||Muuttujat[Tilastovuosi]=2014)",
              "",
              "return htv*tut",
              ""
            ],
            "formatString": "0.0",
            "displayFolder": "Henkilöstö\\Rakenteellinen kehittäminen"
          },
          {
            "name": "Amk tki-henkilötyövuodet 2016",
            "expression": [
              " ",
              "var htv=CALCULATE(SUM(calc_amk_htv[calc_amk_TKI_htv 2016]))",
              "var tut=CALCULATE(MIN([tutkinnot]),Muuttujat[Koulutusaste, taso 2]=\"Ammattikorkeakoulututkinto\",Muuttujat[Tilastovuosi]=2016||Muuttujat[Tilastovuosi]=2015||Muuttujat[Tilastovuosi]=2014)",
              "",
              "return htv*tut",
              ""
            ],
            "formatString": "0.0",
            "displayFolder": "Henkilöstö\\Rakenteellinen kehittäminen"
          },
          {
            "name": "Osuus ylemmistä kk-tutkinnoista 2014-2016",
            "expression": [
              "",
              "var kk=CALCULATE(MAXX(SUMMARIZE(Muuttujat,Muuttujat[Koulutusnimike],\"kk\",",
              "\t\tCALCULATE([Tutkinnot lkm],Muuttujat[Koulutusaste, taso 2]=\"Ylempi korkeakoulututkinto\",Muuttujat[Tilastovuosi]=2014||Muuttujat[Tilastovuosi]=2015\t\t\t||Muuttujat[Tilastovuosi]=2016)),[kk]),ALL(Muuttujat[Tilastovuosi]))",
              "var kaik=CALCULATE(MAXX(SUMMARIZE(Muuttujat,Muuttujat[Koulutusnimike],\"kaikki\",",
              "\t\tCALCULATE([Tutkinnot lkm],Muuttujat[Koulutusaste, taso 2]=\"Ylempi korkeakoulututkinto\",Muuttujat[Tilastovuosi]=2014||Muuttujat[Tilastovuosi]=2015\t\t\t||Muuttujat[Tilastovuosi]=2016)),[kaikki]),ALL(Muuttujat[Organisaatio]),ALL(Muuttujat[Tilastovuosi]))",
              "",
              "return DIVIDE(kk,kaik)",
              ""
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Tutkinnot\\Rakenteellinen kehittäminen"
          },
          {
            "name": "Ylemmät kk-tutkinnot 2014-2016 KA",
            "expression": [
              " ",
              "var tut=CALCULATE(SUM(Muuttujat[tutkinnot]),FILTER(VALUES(Muuttujat[koulutusaste, taso 2]),Muuttujat[Koulutusaste, taso 2]=\"Ylempi korkeakoulututkinto\"),FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]>2013&&Muuttujat[Tilastovuosi]<2017))",
              "var vuosia= CALCULATE(DISTINCTCOUNT(Muuttujat[Tilastovuosi]),FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]>2013&&Muuttujat[Tilastovuosi]<2017))",
              "",
              "return DIVIDE(tut,vuosia)",
              ""
            ],
            "formatString": "0.0",
            "displayFolder": "Tutkinnot\\Rakenteellinen kehittäminen"
          },
          {
            "name": "IV portaan HTV 2016_vanha",
            "expression": "CALCULATE(SUM([Yliopiston opetus- ja tutkimushenkilötyövuodet]),FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2016),FILTER(VALUES(Muuttujat[Tutkijanuravaihe]),Muuttujat[Tutkijanuravaihe]=\"IV porras (Professori/Akatemiaprofessori/Tutkimusprofessori/Tutkimusjohtaja jne.)\"))",
            "formatString": "0.0",
            "isHidden": true,
            "displayFolder": "Henkilöstö\\Rakenteellinen kehittäminen"
          },
          {
            "name": "IV portaan HTV osuus 2016",
            "expression": [
              "",
              "var kaikki=CALCULATE([IV portaan HTV 2016_vanha],ALL(Muuttujat[Organisaatio]),ALL(Muuttujat[Organisaatio]))",
              "var kk=CALCULATE([IV portaan HTV 2016_vanha])",
              "",
              "return DIVIDE(kk,kaikki)",
              ""
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %",
            "isHidden": true,
            "displayFolder": "Henkilöstö\\Rakenteellinen kehittäminen"
          },
          {
            "name": "Osuus kilpaillusta tutkimusrahoituksesta 2017",
            "expression": [
              "",
              "var lask= CALCULATE(DIVIDE(CALCULATE([Kilpailtu tki-rahoitus (SA,Tekes, EU-puite)]),CALCULATE([Kilpailtu tki-rahoitus (SA,Tekes, EU-puite)],ALL(Muuttujat[Organisaatio]))),FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2017))",
              "return lask",
              ""
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "isHidden": true,
            "displayFolder": "Talous\\Rakenteellinen kehittäminen"
          },
          {
            "name": "Jufo suht (1-3, A1-A4, C1) 2015-2017",
            "expression": [
              "",
              "var eka=CALCULATE(AVERAGEX(DISTINCT(Muuttujat[JulkaisuID]),CALCULATE(AVERAGE(Muuttujat[Jufotaso]),NOT(ISBLANK(Muuttujat[YO Julkaisut (A1-A4, C1) jufotaso 1-3])))),FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]>2014&&Muuttujat[Tilastovuosi]<2018))",
              "",
              "",
              "var toka=CALCULATE(AVERAGEX(DISTINCT(Muuttujat[JulkaisuID]), CALCULATE(AVERAGE(Muuttujat[Jufotaso]),NOT(ISBLANK(Muuttujat[YO Julkaisut (A1-A4, C1) jufotaso 1-3])))),ALL(Muuttujat[Organisaatio]),FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]>2014&&Muuttujat[Tilastovuosi]<2018),FILTER(VALUES(Muuttujat[Sektori]),Muuttujat[Sektori]=\"Yliopisto\"))",
              "",
              "var jako=CALCULATE(DIVIDE(eka,toka))",
              "",
              "",
              "return jako",
              ""
            ],
            "formatString": "0.00",
            "displayFolder": "Julkaisut\\Rakenteellinen kehittäminen"
          },
          {
            "name": "eka",
            "expression": [
              "CALCULATE(AVERAGEX(DISTINCT(Muuttujat[JulkaisuID]),CALCULATE(AVERAGE(Muuttujat[Jufotaso]),NOT(ISBLANK(Muuttujat[YO Julkaisut (A1-A4, C1) jufotaso 1-3])))),FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]>2014&&Muuttujat[Tilastovuosi]<2018),NOT(ISBLANK(Muuttujat[YO Julkaisut (A1-A4, C1) jufotaso 1-3])))",
              ""
            ],
            "formatString": "0.00",
            "isHidden": true
          },
          {
            "name": "toka",
            "expression": [
              "CALCULATE(AVERAGEX(DISTINCT(Muuttujat[JulkaisuID]), \t\t",
              "\tCALCULATE(AVERAGE(Muuttujat[Jufotaso]),",
              "\tNOT(ISBLANK(Muuttujat[YO Julkaisut (A1-A4, C1) jufotaso 1-3])),",
              "\tALLSELECTED(Muuttujat[Tilastovuosi]))),",
              "FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]>2014&&Muuttujat[Tilastovuosi]<2018),",
              "ALL(Muuttujat[Organisaatio]),FILTER(VALUES(Muuttujat[Sektori]),Muuttujat[Sektori]=\"Yliopisto\"),",
              "NOT(ISBLANK(Muuttujat[YO Julkaisut (A1-A4, C1) jufotaso 1-3])))"
            ],
            "formatString": "0.00",
            "isHidden": true
          },
          {
            "name": "Vetovoima 2016 (Ylempi kk-tutkinto)",
            "expression": [
              "",
              "var hak=CALCULATE(DISTINCTCOUNT([Ensisijainen hakija]),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2016),",
              "\tNOT(ISBLANK(Muuttujat[Ensisijainen hakija])),",
              "\tFILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),[Koulutusaste, taso 2]=\"Ylempi korkeakoulututkinto\"))",
              "var vast=CALCULATE(DISTINCTCOUNT(Muuttujat[Paikan vastaanottaneet]),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2016),",
              "\tNOT(ISBLANK(Muuttujat[Paikan vastaanottaneet])),",
              "\tFILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),[Koulutusaste, taso 2]=\"Ylempi korkeakoulututkinto\"))",
              "return DIVIDE(hak,vast)",
              ""
            ],
            "formatString": "0.0",
            "isHidden": true,
            "displayFolder": "Haku ja valinta"
          },
          {
            "name": "Vetovoima 2017 (Ylempi kk-tutkinto)",
            "expression": [
              "",
              "var hak=CALCULATE(DISTINCTCOUNT([Ensisijainen hakija]),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2017),",
              "\tNOT(ISBLANK(Muuttujat[Ensisijainen hakija])),",
              "\tFILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),[Koulutusaste, taso 2]=\"Ylempi korkeakoulututkinto\"))",
              "var vast=CALCULATE(DISTINCTCOUNT(Muuttujat[Paikan vastaanottaneet]),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2017),",
              "\tNOT(ISBLANK(Muuttujat[Paikan vastaanottaneet])),",
              "\tFILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),[Koulutusaste, taso 2]=\"Ylempi korkeakoulututkinto\"))",
              "return DIVIDE(hak,vast)"
            ],
            "formatString": "0.0",
            "isHidden": true,
            "displayFolder": "Haku ja valinta"
          },
          {
            "name": "Jufo suht (1-3, A1-A4, C1) 2015-2017 (Tieteenala)",
            "expression": [
              "",
              "var tut=CALCULATE(MIN(Muuttujat[tutkinnot]),FILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),Muuttujat[Koulutusaste, taso 2]=\"Ylempi korkeakoulututkinto\"))",
              "var tut2=CALCULATE(DISTINCTCOUNT(Muuttujat[Koulutusnimike]),Muuttujat[Koulutusaste, taso 2]=\"Alempi korkeakoulututkinto\",NOT(ISBLANK(Muuttujat[Koulutusnimike])))",
              "var tut3=CALCULATE(DISTINCTCOUNT(Muuttujat[Koulutusnimike]),Muuttujat[Koulutusaste, taso 2]=\"Tohtorintutkinto\",NOT(ISBLANK(Muuttujat[Koulutusnimike])))",
              "",
              "var eka=AVERAGE('Org_TA jufo'[eka_juf15-17])",
              "var toka=AVERAGE('Tieteenala jufo'[toka_juf15-17])",
              "var jako=DIVIDE(eka,toka)",
              "",
              "var eka2=CALCULATE(AVERAGEX(DISTINCT(Muuttujat[JulkaisuID]),CALCULATE(AVERAGE(Muuttujat[Jufotaso]),NOT(ISBLANK(Muuttujat[YO Julkaisut (A1-A4, C1) jufotaso 1-3])),NOT(ISBLANK(Muuttujat[Tieteenala])))),FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]>2014&&Muuttujat[Tilastovuosi]<2018))",
              "var toka2=CALCULATE(AVERAGEX(DISTINCT(Muuttujat[JulkaisuID]), CALCULATE(AVERAGE(Muuttujat[Jufotaso]),NOT(ISBLANK(Muuttujat[YO Julkaisut (A1-A4, C1) jufotaso 1-3])),NOT(ISBLANK(Muuttujat[Tieteenala])))),ALL(Muuttujat[Organisaatio]),FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]>2014&&Muuttujat[Tilastovuosi]<2018),FILTER(VALUES(Muuttujat[Sektori]),Muuttujat[Sektori]=\"Yliopisto\"))",
              "var jako2=CALCULATE(DIVIDE(eka2,toka2),NOT(ISBLANK(Muuttujat[Tieteenala])))",
              "",
              "var tsek=IF(AND(ISBLANK(tut),HASONEVALUE(Muuttujat[Organisaatio])),\"blank,1\",",
              "\tIF(AND(ISBLANK(tut),NOT(HASONEVALUE(Muuttujat[Organisaatio]))),\"blank,many\",",
              "\tIF(AND(NOT(ISBLANK(tut)),HASONEVALUE(Muuttujat[Organisaatio])),\"tut,1\",",
              "\tIF(AND(NOT(ISBLANK(tut)),NOT(HASONEVALUE(Muuttujat[Organisaatio]))),\"tut,many\"))))",
              "var tsek2=AND(tut2<1,tut3<1)",
              "",
              "return   SWITCH(tsek,\"blank,1\",IF(tsek2,jako2,jako2*tut),",
              "\t\t    \"blank,many\",IF(tsek2,jako2,jako2*tut),",
              "\t\t    \"tut,1\",jako*tut,",
              "\t\t    \"tut,many\",IF(tsek2,jako2,jako2*tut))",
              ""
            ],
            "formatString": "0.00",
            "displayFolder": "Julkaisut\\Rakenteellinen kehittäminen"
          },
          {
            "name": "eka2_calc_15-17",
            "expression": "AVERAGE('Org_TA jufo'[eka_juf15-17])",
            "formatString": "0.00",
            "isHidden": true
          },
          {
            "name": "toka2_calc:14-16",
            "expression": "AVERAGE('Tieteenala jufo'[toka_juf14-16])",
            "formatString": "0.00",
            "isHidden": true
          },
          {
            "name": "Yo julkaisut (jufo 1-3, A1-A4, C1) lkm",
            "expression": " SUM([YO Julkaisut (A1-A4, C1) jufotaso 1-3])",
            "formatString": "0",
            "displayFolder": "Julkaisut\\Rakenteellinen kehittäminen"
          },
          {
            "name": "Työllisten osuus 3v (RAKE-määritelmä)",
            "expression": [
              "",
              "var osa = CALCULATE(SUM(Muuttujat[Työlliset 3v (ver2 10,13)]),Muuttujat[Työlliset 3v (ver2 10,13)]<>0,NOT(ISBLANK(Muuttujat[Työlliset 3v (ver2 10,13)])))",
              "var kaikki = MROUND(CALCULATE(SUM(Muuttujat[Työlliset 3v (ver2 10,13)]),Muuttujat[Työlliset 3v (ver2 10,13)]<>0,NOT(ISBLANK(Muuttujat[Työlliset 3v (ver2 10,13)]))) + CALCULATE(SUM(Muuttujat[Työttömät 3v (ver2, 12)]),Muuttujat[Työttömät 3v (ver2, 12)]<>0,NOT(ISBLANK(Muuttujat[Työttömät 3v (ver2, 12)]))), 3)",
              "return IF(osa = 0, BLANK(),",
              "IF(kaikki < 5, \"25 % – 100 %\",",
              "IF(osa < 5, IF(kaikki > 8000, \"0.0 %\",",
              "CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "MROUND(osa, 3) / kaikki)))"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Työllisyys\\Rakenteellinen kehittäminen"
          },
          {
            "name": "Tohtorin tutkinnot (tieteenala) 2015-2017 KA",
            "expression": [
              " ",
              "var tut=SUM(Org_tohtorit[Tohtorit calc])",
              "var tut2=CALCULATE(MIN(Muuttujat[tutkinnot]),FILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),Muuttujat[Koulutusaste, taso 2]=\"Tohtorintutkinto\"))",
              "var tut3=CALCULATE(MIN(Muuttujat[tutkinnot]),FILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),Muuttujat[Koulutusaste, taso 2]=\"Ylempi korkeakoulututkinto\"))",
              "",
              "var jako=DIVIDE(tut,3)",
              "",
              "return IF(NOT(HASONEVALUE(Muuttujat[Koulutusnimike])),",
              "\tjako,CALCULATE(jako*tut3))",
              "\t"
            ],
            "formatString": "0.0",
            "displayFolder": "Tutkinnot\\Rakenteellinen kehittäminen"
          },
          {
            "name": "dc juf",
            "expression": "CALCULATE(DISTINCTCOUNT([JulkaisuID]),NOT(ISBLANK(Muuttujat[YO Julkaisut (A1-A4, C1) jufotaso 1-3])))",
            "isHidden": true
          },
          {
            "name": "IV portaan HTV osuus 2017 (tieteenala)",
            "expression": [
              "",
              "var kaikki=CALCULATE(SUM(TA_IV[IV 2017 calc]))",
              "var kk=CALCULATE(SUM(Org_IV[IV 2017 calc]))",
              "var tut=CALCULATE(MIN(Muuttujat[tutkinnot]),Muuttujat[Koulutusaste, taso 2]=\"Ylempi korkeakoulututkinto\")",
              "var tut2=CALCULATE(DISTINCTCOUNT(Muuttujat[Koulutusnimike]),Muuttujat[Koulutusaste, taso 2]=\"Alempi korkeakoulututkinto\",NOT(ISBLANK(Muuttujat[Koulutusnimike])))",
              "var tut3=CALCULATE(DISTINCTCOUNT(Muuttujat[Koulutusnimike]),Muuttujat[Koulutusaste, taso 2]=\"Tohtorintutkinto\",NOT(ISBLANK(Muuttujat[Koulutusnimike])))",
              "",
              "var jako=DIVIDE(kk,kaikki)",
              "",
              "var tsek=IF(AND(ISBLANK(tut),HASONEVALUE(Muuttujat[Organisaatio])),\"blank,1\",",
              "\tIF(AND(ISBLANK(tut),NOT(HASONEVALUE(Muuttujat[Organisaatio]))),\"blank,many\",",
              "\tIF(AND(NOT(ISBLANK(tut)),HASONEVALUE(Muuttujat[Organisaatio])),\"tut,1\",",
              "\tIF(AND(NOT(ISBLANK(tut)),NOT(HASONEVALUE(Muuttujat[Organisaatio]))),\"tut,many\"))))",
              "",
              "var tsek2=AND(tut2<1,tut3<1)",
              "",
              "return   SWITCH(tsek,\"blank,1\",IF(tsek2,jako,jako*tut),",
              "\t\t    \"blank,many\",IF(tsek2,jako,jako*tut),",
              "\t\t    \"tut,1\",jako*tut,",
              "\t\t    \"tut,many\",IF(tsek2,jako,jako*tut))",
              ""
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Henkilöstö\\Rakenteellinen kehittäminen"
          },
          {
            "name": "IV portaan HTV osuus 2016 (tieteenala)",
            "expression": [
              "",
              "var kaikki=CALCULATE(SUM(TA_IV[IV 2016 calc]))",
              "var kk=CALCULATE(SUM(Org_IV[IV 2016 calc]))",
              "var tut=CALCULATE(MIN(Muuttujat[tutkinnot]),Muuttujat[Koulutusaste, taso 2]=\"Ylempi korkeakoulututkinto\")",
              "var tut2=CALCULATE(DISTINCTCOUNT(Muuttujat[Koulutusnimike]),Muuttujat[Koulutusaste, taso 2]=\"Alempi korkeakoulututkinto\",NOT(ISBLANK(Muuttujat[Koulutusnimike])))",
              "var tut3=CALCULATE(DISTINCTCOUNT(Muuttujat[Koulutusnimike]),Muuttujat[Koulutusaste, taso 2]=\"Tohtorintutkinto\",NOT(ISBLANK(Muuttujat[Koulutusnimike])))",
              "",
              "var jako=DIVIDE(kk,kaikki)",
              "",
              "var tsek=IF(AND(ISBLANK(tut),HASONEVALUE(Muuttujat[Organisaatio])),\"blank,1\",",
              "\tIF(AND(ISBLANK(tut),NOT(HASONEVALUE(Muuttujat[Organisaatio]))),\"blank,many\",",
              "\tIF(AND(NOT(ISBLANK(tut)),HASONEVALUE(Muuttujat[Organisaatio])),\"tut,1\",",
              "\tIF(AND(NOT(ISBLANK(tut)),NOT(HASONEVALUE(Muuttujat[Organisaatio]))),\"tut,many\"))))",
              "",
              "var tsek2=AND(tut2<1,tut3<1)",
              "",
              "return   SWITCH(tsek,\"blank,1\",IF(tsek2,jako,jako*tut),",
              "\t\t    \"blank,many\",IF(tsek2,jako,jako*tut),",
              "\t\t    \"tut,1\",jako*tut,",
              "\t\t    \"tut,many\",IF(tsek2,jako,jako*tut))",
              ""
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Henkilöstö\\Rakenteellinen kehittäminen"
          },
          {
            "name": "Osuus kilpaillusta tutkimusrahoituksesta 2016 (Tieteenala, SA,TEKES, EU-puite)",
            "expression": [
              "",
              "var kk= SUM(Org_kilprah[kilp_rah 2016 calc])",
              "var kaik=SUM(TA_kilprah[kilp_rah 2016 calc])",
              "var tut=CALCULATE(MIN(Muuttujat[tutkinnot]),Muuttujat[Koulutusaste, taso 2]=\"Ylempi korkeakoulututkinto\")",
              "var tut2=CALCULATE(DISTINCTCOUNT(Muuttujat[Koulutusnimike]),Muuttujat[Koulutusaste, taso 2]=\"Alempi korkeakoulututkinto\",NOT(ISBLANK(Muuttujat[Koulutusnimike])))",
              "var tut3=CALCULATE(DISTINCTCOUNT(Muuttujat[Koulutusnimike]),Muuttujat[Koulutusaste, taso 2]=\"Tohtorintutkinto\",NOT(ISBLANK(Muuttujat[Koulutusnimike])))",
              "",
              "var jako=DIVIDE(kk,kaik)",
              "",
              "var tsek=IF(AND(ISBLANK(tut),HASONEVALUE(Muuttujat[Organisaatio])),\"blank,1\",",
              "\tIF(AND(ISBLANK(tut),NOT(HASONEVALUE(Muuttujat[Organisaatio]))),\"blank,many\",",
              "\tIF(AND(NOT(ISBLANK(tut)),HASONEVALUE(Muuttujat[Organisaatio])),\"tut,1\",",
              "\tIF(AND(NOT(ISBLANK(tut)),NOT(HASONEVALUE(Muuttujat[Organisaatio]))),\"tut,many\"))))",
              "\t",
              "var tsek2=AND(tut2<1,tut3<1)",
              "",
              "return   SWITCH(tsek,\"blank,1\",IF(tsek2,jako,jako*tut),",
              "\t\t    \"blank,many\",IF(tsek2,jako,jako*tut),",
              "\t\t    \"tut,1\",jako*tut,",
              "\t\t    \"tut,many\",IF(tsek2,jako,jako*tut))",
              ""
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Talous\\Rakenteellinen kehittäminen"
          },
          {
            "name": "Osuus kilpaillusta tutkimusrahoituksesta 2017 (Tieteenala, SA,TEKES, EU-puite)",
            "expression": [
              "",
              "var kk= SUM(Org_kilprah[kilp_rah 2017 calc])",
              "var kaik=SUM(TA_kilprah[kilp_rah 2017 calc])",
              "var tut=CALCULATE(MIN(Muuttujat[tutkinnot]),Muuttujat[Koulutusaste, taso 2]=\"Ylempi korkeakoulututkinto\")",
              "var tut2=CALCULATE(DISTINCTCOUNT(Muuttujat[Koulutusnimike]),Muuttujat[Koulutusaste, taso 2]=\"Alempi korkeakoulututkinto\",NOT(ISBLANK(Muuttujat[Koulutusnimike])))",
              "var tut3=CALCULATE(DISTINCTCOUNT(Muuttujat[Koulutusnimike]),Muuttujat[Koulutusaste, taso 2]=\"Tohtorintutkinto\",NOT(ISBLANK(Muuttujat[Koulutusnimike])))",
              "",
              "var jako=DIVIDE(kk,kaik)",
              "",
              "var tsek=IF(AND(ISBLANK(tut),HASONEVALUE(Muuttujat[Organisaatio])),\"blank,1\",",
              "\tIF(AND(ISBLANK(tut),NOT(HASONEVALUE(Muuttujat[Organisaatio]))),\"blank,many\",",
              "\tIF(AND(NOT(ISBLANK(tut)),HASONEVALUE(Muuttujat[Organisaatio])),\"tut,1\",",
              "\tIF(AND(NOT(ISBLANK(tut)),NOT(HASONEVALUE(Muuttujat[Organisaatio]))),\"tut,many\"))))",
              "\t",
              "var tsek2=AND(tut2<1,tut3<1)",
              "",
              "return   SWITCH(tsek,\"blank,1\",IF(tsek2,jako,jako*tut),",
              "\t\t    \"blank,many\",IF(tsek2,jako,jako*tut),",
              "\t\t    \"tut,1\",jako*tut,",
              "\t\t    \"tut,many\",IF(tsek2,jako,jako*tut))",
              ""
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Talous\\Rakenteellinen kehittäminen"
          },
          {
            "name": "eka_laskentaan(jufo)",
            "expression": [
              "CALCULATE(AVERAGEX(DISTINCT(Muuttujat[JulkaisuID]),CALCULATE(AVERAGE(Muuttujat[Jufotaso]),NOT(ISBLANK(Muuttujat[YO Julkaisut (A1-A4, C1) jufotaso 1-3])))),NOT(ISBLANK(Muuttujat[YO Julkaisut (A1-A4, C1) jufotaso 1-3])))",
              ""
            ],
            "isHidden": true
          },
          {
            "name": "toka_laskentaan (jufo)",
            "expression": [
              "CALCULATE(AVERAGEX(DISTINCT(Muuttujat[JulkaisuID]), \t\t",
              "\tCALCULATE(AVERAGE(Muuttujat[Jufotaso]),",
              "\tNOT(ISBLANK(Muuttujat[YO Julkaisut (A1-A4, C1) jufotaso 1-3])),",
              "\tALLSELECTED(Muuttujat[Tilastovuosi]))),",
              "ALL(Muuttujat[Organisaatio]),FILTER(VALUES(Muuttujat[Sektori]),Muuttujat[Sektori]=\"Yliopisto\"),",
              "NOT(ISBLANK(Muuttujat[YO Julkaisut (A1-A4, C1) jufotaso 1-3])))",
              ""
            ],
            "isHidden": true
          },
          {
            "name": "eka2_calc_14-16",
            "expression": "AVERAGE('Org_TA jufo'[eka_juf14-16])",
            "formatString": "0.00",
            "isHidden": true
          },
          {
            "name": "toka2_calc:15-17",
            "expression": "AVERAGE('Tieteenala jufo'[toka_juf15-17])",
            "formatString": "0.00",
            "isHidden": true
          },
          {
            "name": "Jufo suht (1-3, A1-A4, C1) 2014-2016 (Tieteenala)",
            "expression": [
              "",
              "var tut=CALCULATE(MIN(Muuttujat[tutkinnot]),FILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),Muuttujat[Koulutusaste, taso 2]=\"Ylempi korkeakoulututkinto\"))",
              "var tut2=CALCULATE(DISTINCTCOUNT(Muuttujat[Koulutusnimike]),Muuttujat[Koulutusaste, taso 2]=\"Alempi korkeakoulututkinto\",NOT(ISBLANK(Muuttujat[Koulutusnimike])))",
              "var tut3=CALCULATE(DISTINCTCOUNT(Muuttujat[Koulutusnimike]),Muuttujat[Koulutusaste, taso 2]=\"Tohtorintutkinto\",NOT(ISBLANK(Muuttujat[Koulutusnimike])))",
              "",
              "var eka=AVERAGE('Org_TA jufo'[eka_juf14-16])",
              "var toka=AVERAGE('Tieteenala jufo'[toka_juf14-16])",
              "var jako=CALCULATE(DIVIDE(eka,toka))",
              "",
              "var eka2=CALCULATE(AVERAGEX(DISTINCT(Muuttujat[JulkaisuID]),CALCULATE(AVERAGE(Muuttujat[Jufotaso]),NOT(ISBLANK(Muuttujat[YO Julkaisut (A1-A4, C1) jufotaso 1-3])))),FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]>2013&&Muuttujat[Tilastovuosi]<2017))",
              "var toka2=CALCULATE(AVERAGEX(DISTINCT(Muuttujat[JulkaisuID]), CALCULATE(AVERAGE(Muuttujat[Jufotaso]),NOT(ISBLANK(Muuttujat[YO Julkaisut (A1-A4, C1) jufotaso 1-3])))),ALL(Muuttujat[Organisaatio]),FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]>2013&&Muuttujat[Tilastovuosi]<2017),FILTER(VALUES(Muuttujat[Sektori]),Muuttujat[Sektori]=\"Yliopisto\"))",
              "",
              "var jako2=CALCULATE(DIVIDE(eka2,toka2))",
              "",
              "var tsek=IF(AND(ISBLANK(tut),HASONEVALUE(Muuttujat[Organisaatio])),\"blank,1\",",
              "\tIF(AND(ISBLANK(tut),NOT(HASONEVALUE(Muuttujat[Organisaatio]))),\"blank,many\",",
              "\tIF(AND(NOT(ISBLANK(tut)),HASONEVALUE(Muuttujat[Organisaatio])),\"tut,1\",",
              "\tIF(AND(NOT(ISBLANK(tut)),NOT(HASONEVALUE(Muuttujat[Organisaatio]))),\"tut,many\"))))",
              "",
              "var tsek2=AND(tut2<1,tut3<1)",
              "",
              "return   SWITCH(tsek,\"blank,1\",IF(tsek2,jako2,jako2*tut),",
              "\t\t    \"blank,many\",IF(tsek2,jako2,jako2*tut),",
              "\t\t    \"tut,1\",jako*tut,",
              "\t\t    \"tut,many\",IF(tsek2,jako2,jako2*tut))",
              ""
            ],
            "formatString": "0.00",
            "displayFolder": "Julkaisut\\Rakenteellinen kehittäminen"
          },
          {
            "name": "Jufo keskiarvo",
            "expression": [
              "CALCULATE(AVERAGEX(DISTINCT(Muuttujat[JulkaisuID]),CALCULATE(AVERAGE(Muuttujat[Jufotaso]),NOT(ISBLANK(Muuttujat[YO Julkaisut (A1-A4, C1) jufotaso 1-3])))),NOT(ISBLANK(Muuttujat[YO Julkaisut (A1-A4, C1) jufotaso 1-3])))",
              ""
            ],
            "formatString": "0.00",
            "displayFolder": "Julkaisut\\Rakenteellinen kehittäminen"
          },
          {
            "name": "IV portaan HTV 2017",
            "expression": [
              "",
              "var kk=CALCULATE(SUM(Org_IV[IV 2017 calc]))",
              "var tut=CALCULATE(MIN(Muuttujat[tutkinnot]),Muuttujat[Koulutusaste, taso 2]=\"Ylempi korkeakoulututkinto\")",
              "var tut2=CALCULATE(DISTINCTCOUNT(Muuttujat[Koulutusnimike]),Muuttujat[Koulutusaste, taso 2]=\"Alempi korkeakoulututkinto\",NOT(ISBLANK(Muuttujat[Koulutusnimike])))",
              "var tut3=CALCULATE(DISTINCTCOUNT(Muuttujat[Koulutusnimike]),Muuttujat[Koulutusaste, taso 2]=\"Tohtorintutkinto\",NOT(ISBLANK(Muuttujat[Koulutusnimike])))",
              "",
              "var tsek=IF(AND(ISBLANK(tut),HASONEVALUE(Muuttujat[Organisaatio])),\"blank,1\",",
              "\tIF(AND(ISBLANK(tut),NOT(HASONEVALUE(Muuttujat[Organisaatio]))),\"blank,many\",",
              "\tIF(AND(NOT(ISBLANK(tut)),HASONEVALUE(Muuttujat[Organisaatio])),\"tut,1\",",
              "\tIF(AND(NOT(ISBLANK(tut)),NOT(HASONEVALUE(Muuttujat[Organisaatio]))),\"tut,many\"))))",
              "",
              "var tsek2=AND(tut2<1,tut3<1)",
              "",
              "return   SWITCH(tsek,\"blank,1\",IF(tsek2,kk,kk*tut),",
              "\t\t    \"blank,many\",IF(tsek2,kk,kk*tut),",
              "\t\t    \"tut,1\",kk*tut,",
              "\t\t    \"tut,many\",IF(tsek2,kk,kk*tut))",
              ""
            ],
            "formatString": "0.0",
            "displayFolder": "Henkilöstö\\Rakenteellinen kehittäminen"
          },
          {
            "name": "IV portaan HTV 2016",
            "expression": [
              "",
              "var kk=CALCULATE(SUM(Org_IV[IV 2016 calc]))",
              "var tut=CALCULATE(MIN(Muuttujat[tutkinnot]),Muuttujat[Koulutusaste, taso 2]=\"Ylempi korkeakoulututkinto\")",
              "var tut2=CALCULATE(DISTINCTCOUNT(Muuttujat[Koulutusnimike]),Muuttujat[Koulutusaste, taso 2]=\"Alempi korkeakoulututkinto\",NOT(ISBLANK(Muuttujat[Koulutusnimike])))",
              "var tut3=CALCULATE(DISTINCTCOUNT(Muuttujat[Koulutusnimike]),Muuttujat[Koulutusaste, taso 2]=\"Tohtorintutkinto\",NOT(ISBLANK(Muuttujat[Koulutusnimike])))",
              "",
              "var tsek=IF(AND(ISBLANK(tut),HASONEVALUE(Muuttujat[Organisaatio])),\"blank,1\",",
              "\tIF(AND(ISBLANK(tut),NOT(HASONEVALUE(Muuttujat[Organisaatio]))),\"blank,many\",",
              "\tIF(AND(NOT(ISBLANK(tut)),HASONEVALUE(Muuttujat[Organisaatio])),\"tut,1\",",
              "\tIF(AND(NOT(ISBLANK(tut)),NOT(HASONEVALUE(Muuttujat[Organisaatio]))),\"tut,many\"))))",
              "",
              "var tsek2=AND(tut2<1,tut3<1)",
              "",
              "return   SWITCH(tsek,\"blank,1\",IF(tsek2,kk,kk*tut),",
              "\t\t    \"blank,many\",IF(tsek2,kk,kk*tut),",
              "\t\t    \"tut,1\",kk*tut,",
              "\t\t    \"tut,many\",IF(tsek2,kk,kk*tut))",
              ""
            ],
            "formatString": "0.0",
            "displayFolder": "Henkilöstö\\Rakenteellinen kehittäminen"
          },
          {
            "name": "Työllistyminen 3v, (RAKE, ykk) KA 2014-2016_old",
            "expression": [
              "",
              "var osuus1= CALCULATE([Työllisten osuus 3v (RAKE-määritelmä)],FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2014),FILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),Muuttujat[Koulutusaste, taso 2]=\"Ylempi korkeakoulututkinto\"))",
              "var osuus2= CALCULATE([Työllisten osuus 3v (RAKE-määritelmä)],FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2015),FILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),Muuttujat[Koulutusaste, taso 2]=\"Ylempi korkeakoulututkinto\"))",
              "var osuus3= CALCULATE([Työllisten osuus 3v (RAKE-määritelmä)],FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2016),FILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),Muuttujat[Koulutusaste, taso 2]=\"Ylempi korkeakoulututkinto\"))",
              "",
              "var jako=DIVIDE((osuus1+osuus2+osuus3),3)",
              "",
              "return jako",
              ""
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "isHidden": true,
            "displayFolder": "Työllisyys\\Rakenteellinen kehittäminen"
          },
          {
            "name": "Vetovoima 2017 (I sykli)",
            "expression": [
              "",
              "var hak=CALCULATE(DISTINCTCOUNT([Ensisijainen hakija]),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2017),",
              "\tNOT(ISBLANK(Muuttujat[Ensisijainen hakija])),",
              "\tFILTER(VALUES(Muuttujat[Tutkinnon aloitussykli]),Muuttujat[Tutkinnon aloitussykli]=\"I sykli\"),",
              "\tFILTER(VALUES(Muuttujat[Sektori]),Muuttujat[Sektori]=\"Yliopisto\"))",
              "var vast=CALCULATE(DISTINCTCOUNT(Muuttujat[Paikan vastaanottaneet]),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2017),",
              "\tNOT(ISBLANK(Muuttujat[Paikan vastaanottaneet])),",
              "\tFILTER(VALUES(Muuttujat[Tutkinnon aloitussykli]),Muuttujat[Tutkinnon aloitussykli]=\"I sykli\"),",
              "\tFILTER(VALUES(Muuttujat[Sektori]),Muuttujat[Sektori]=\"Yliopisto\"))",
              "return DIVIDE(hak,vast)"
            ],
            "formatString": "0.0",
            "displayFolder": "Haku ja valinta"
          },
          {
            "name": "Vetovoima 2016 (I sykli)",
            "expression": [
              "",
              "var hak=CALCULATE(DISTINCTCOUNT([Ensisijainen hakija]),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2016),",
              "\tNOT(ISBLANK(Muuttujat[Ensisijainen hakija])),",
              "\tFILTER(VALUES(Muuttujat[Tutkinnon aloitussykli]),Muuttujat[Tutkinnon aloitussykli]=\"I sykli\"),",
              "\tFILTER(VALUES(Muuttujat[Sektori]),Muuttujat[Sektori]=\"Yliopisto\"))",
              "var vast=CALCULATE(DISTINCTCOUNT(Muuttujat[Paikan vastaanottaneet]),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2016),",
              "\tNOT(ISBLANK(Muuttujat[Paikan vastaanottaneet])),",
              "\tFILTER(VALUES(Muuttujat[Tutkinnon aloitussykli]),Muuttujat[Tutkinnon aloitussykli]=\"I sykli\"),",
              "\tFILTER(VALUES(Muuttujat[Sektori]),Muuttujat[Sektori]=\"Yliopisto\"))",
              "return DIVIDE(hak,vast)"
            ],
            "formatString": "0.0",
            "displayFolder": "Haku ja valinta"
          },
          {
            "name": "Työllistyminen 3v, (RAKE, ykk) KA 2014-2016",
            "expression": [
              "",
              "var osuus1= CALCULATE([Työllisten osuus 3v (RAKE-määritelmä)],FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2014),FILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),Muuttujat[Koulutusaste, taso 2]=\"Ylempi korkeakoulututkinto\"))",
              "var osuus2= CALCULATE([Työllisten osuus 3v (RAKE-määritelmä)],FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2015),FILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),Muuttujat[Koulutusaste, taso 2]=\"Ylempi korkeakoulututkinto\"))",
              "var osuus3= CALCULATE([Työllisten osuus 3v (RAKE-määritelmä)],FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2016),FILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),Muuttujat[Koulutusaste, taso 2]=\"Ylempi korkeakoulututkinto\"))",
              "",
              "var vuosia=CALCULATE((SWITCH(ISBLANK(osuus1),TRUE(),0,1)+SWITCH(ISBLANK(osuus2),TRUE(),0,1)+SWITCH(ISBLANK(osuus3),TRUE(),0,1)))",
              "var jako=CALCULATE(DIVIDE((osuus1+osuus2+osuus3),vuosia))",
              "",
              "return jako",
              ""
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Työllisyys\\Rakenteellinen kehittäminen"
          },
          {
            "name": "Työllistyminen 3v, (RAKE, ykk) KA 2015-2017",
            "expression": [
              "",
              "var osuus1= CALCULATE([Työllisten osuus 3v (RAKE-määritelmä)],FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2015),FILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),Muuttujat[Koulutusaste, taso 2]=\"Ylempi korkeakoulututkinto\"))",
              "var osuus2= CALCULATE([Työllisten osuus 3v (RAKE-määritelmä)],FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2016),FILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),Muuttujat[Koulutusaste, taso 2]=\"Ylempi korkeakoulututkinto\"))",
              "var osuus3= CALCULATE([Työllisten osuus 3v (RAKE-määritelmä)],FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2017),FILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),Muuttujat[Koulutusaste, taso 2]=\"Ylempi korkeakoulututkinto\"))",
              "",
              "var vuosia=CALCULATE((SWITCH(ISBLANK(osuus1),TRUE(),0,1)+SWITCH(ISBLANK(osuus2),TRUE(),0,1)+SWITCH(ISBLANK(osuus3),TRUE(),0,1)))",
              "var jako=CALCULATE(DIVIDE((osuus1+osuus2+osuus3),vuosia))",
              "",
              "return jako"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Työllisyys\\Rakenteellinen kehittäminen"
          },
          {
            "name": "Osallistumiset huippuyksiköissä 2014-2019 ja 2018-2025_pohja",
            "expression": [
              "",
              "var summa=SUM(Muuttujat[Osallistuminen huippuyksik.])",
              "return summa"
            ],
            "formatString": "0",
            "isHidden": true,
            "displayFolder": "Tutkimus"
          },
          {
            "name": "Akatemiaprofessori-myönnöt 2013-2016_pohja",
            "expression": "SUM([Akatemia profesuurit])",
            "formatString": "0",
            "isHidden": true,
            "displayFolder": "Tutkimus"
          },
          {
            "name": "ERC StG, CoG ja AdG -myönnöt 2015-2017 hauissa_pohja",
            "expression": "SUM([erc,stg,cog ja adg])",
            "formatString": "0",
            "isHidden": true,
            "displayFolder": "Tutkimus"
          },
          {
            "name": "Osallistumiset huippuyksiköissä 2014-2019 ja 2018-2025",
            "expression": [
              "",
              "var summa=SUM(ORG_lisa[osallistumiset calc])",
              "var tut=CALCULATE(MIN(Muuttujat[tutkinnot]),FILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),Muuttujat[Koulutusaste, taso 2]=\"Ylempi korkeakoulututkinto\"))",
              "var tut2=CALCULATE(DISTINCTCOUNT(Muuttujat[Koulutusnimike]),Muuttujat[Koulutusaste, taso 2]=\"Alempi korkeakoulututkinto\",NOT(ISBLANK(Muuttujat[Koulutusnimike])))",
              "var tut3=CALCULATE(DISTINCTCOUNT(Muuttujat[Koulutusnimike]),Muuttujat[Koulutusaste, taso 2]=\"Tohtorintutkinto\",NOT(ISBLANK(Muuttujat[Koulutusnimike])))",
              "",
              "",
              "var tsek=IF(AND(ISBLANK(tut),HASONEVALUE(Muuttujat[Organisaatio])),\"blank,1\",",
              "\tIF(AND(ISBLANK(tut),NOT(HASONEVALUE(Muuttujat[Organisaatio]))),\"blank,many\",",
              "\tIF(AND(NOT(ISBLANK(tut)),HASONEVALUE(Muuttujat[Organisaatio])),\"tut,1\",",
              "\tIF(AND(NOT(ISBLANK(tut)),NOT(HASONEVALUE(Muuttujat[Organisaatio]))),\"tut,many\"))))",
              "\t",
              "var tsek2=AND(tut2<1,tut3<1)",
              "",
              "return   SWITCH(tsek,\"blank,1\",IF(tsek2,summa,summa*tut),",
              "\t\t    \"blank,many\",IF(tsek2,summa,summa*tut),",
              "\t\t    \"tut,1\",summa*tut,",
              "\t\t    \"tut,many\",IF(tsek2,summa,summa*tut))"
            ],
            "displayFolder": "Tutkimus"
          },
          {
            "name": "Akatemiaprofessori-myönnöt 2013-2016",
            "expression": [
              "",
              "VAR summa=SUM(ORG_lisa[SA prof calc])",
              "",
              "var tut=CALCULATE(MIN(Muuttujat[tutkinnot]),FILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),Muuttujat[Koulutusaste, taso 2]=\"Ylempi korkeakoulututkinto\"))",
              "var tut2=CALCULATE(DISTINCTCOUNT(Muuttujat[Koulutusnimike]),Muuttujat[Koulutusaste, taso 2]=\"Alempi korkeakoulututkinto\",NOT(ISBLANK(Muuttujat[Koulutusnimike])))",
              "var tut3=CALCULATE(DISTINCTCOUNT(Muuttujat[Koulutusnimike]),Muuttujat[Koulutusaste, taso 2]=\"Tohtorintutkinto\",NOT(ISBLANK(Muuttujat[Koulutusnimike])))",
              "",
              "",
              "var tsek=IF(AND(ISBLANK(tut),HASONEVALUE(Muuttujat[Organisaatio])),\"blank,1\",",
              "\tIF(AND(ISBLANK(tut),NOT(HASONEVALUE(Muuttujat[Organisaatio]))),\"blank,many\",",
              "\tIF(AND(NOT(ISBLANK(tut)),HASONEVALUE(Muuttujat[Organisaatio])),\"tut,1\",",
              "\tIF(AND(NOT(ISBLANK(tut)),NOT(HASONEVALUE(Muuttujat[Organisaatio]))),\"tut,many\"))))",
              "\t",
              "var tsek2=AND(tut2<1,tut3<1)",
              "",
              "return   SWITCH(tsek,\"blank,1\",IF(tsek2,summa,summa*tut),",
              "\t\t    \"blank,many\",IF(tsek2,summa,summa*tut),",
              "\t\t    \"tut,1\",summa*tut,",
              "\t\t    \"tut,many\",IF(tsek2,summa,summa*tut))",
              ""
            ],
            "displayFolder": "Tutkimus"
          },
          {
            "name": "ERC StG, CoG ja AdG -myönnöt 2015-2017 hauissa",
            "expression": [
              "",
              "VAR summa=SUM(ORG_lisa[erc calc])",
              "",
              "var tut=CALCULATE(MIN(Muuttujat[tutkinnot]),FILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),Muuttujat[Koulutusaste, taso 2]=\"Ylempi korkeakoulututkinto\"))",
              "var tut2=CALCULATE(DISTINCTCOUNT(Muuttujat[Koulutusnimike]),Muuttujat[Koulutusaste, taso 2]=\"Alempi korkeakoulututkinto\",NOT(ISBLANK(Muuttujat[Koulutusnimike])))",
              "var tut3=CALCULATE(DISTINCTCOUNT(Muuttujat[Koulutusnimike]),Muuttujat[Koulutusaste, taso 2]=\"Tohtorintutkinto\",NOT(ISBLANK(Muuttujat[Koulutusnimike])))",
              "",
              "",
              "var tsek=IF(AND(ISBLANK(tut),HASONEVALUE(Muuttujat[Organisaatio])),\"blank,1\",",
              "\tIF(AND(ISBLANK(tut),NOT(HASONEVALUE(Muuttujat[Organisaatio]))),\"blank,many\",",
              "\tIF(AND(NOT(ISBLANK(tut)),HASONEVALUE(Muuttujat[Organisaatio])),\"tut,1\",",
              "\tIF(AND(NOT(ISBLANK(tut)),NOT(HASONEVALUE(Muuttujat[Organisaatio]))),\"tut,many\"))))",
              "\t",
              "var tsek2=AND(tut2<1,tut3<1)",
              "",
              "return   SWITCH(tsek,\"blank,1\",IF(tsek2,summa,summa*tut),",
              "\t\t    \"blank,many\",IF(tsek2,summa,summa*tut),",
              "\t\t    \"tut,1\",summa*tut,",
              "\t\t    \"tut,many\",IF(tsek2,summa,summa*tut))",
              ""
            ],
            "displayFolder": "Tutkimus"
          },
          {
            "name": "Työllisten osuus 1v valmistumisesta 2014-2016 (RAKE, amk-tutkinto)",
            "expression": [
              "",
              "var tyolliset=CALCULATE(SUM(Muuttujat[työlliset 1v tutkinnon jälkeen]),FILTER(VALUEs(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]>2013&&Muuttujat[Tilastovuosi]<2017),FILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),Muuttujat[Koulutusaste, taso 2]=\"Ammattikorkeakoulututkinto\"))",
              "var kaik=CALCULATE(SUM(Muuttujat[sijoittuminen_1v_tutkinnon_jalkeen]),FILTER(VALUEs(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]>2013&&Muuttujat[Tilastovuosi]<2017),FILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),Muuttujat[Koulutusaste, taso 2]=\"Ammattikorkeakoulututkinto\"))",
              "var jako=CALCULATE(DIVIDE(tyolliset,kaik))",
              "",
              "return jako",
              ""
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Työllisyys\\Rakenteellinen kehittäminen"
          },
          {
            "name": "Amk tki-henkilötyövuodet 2017",
            "expression": [
              " ",
              "var htv=CALCULATE(SUM(calc_amk_htv[calc_amk_TKI_htv 2017]))",
              "var tut=CALCULATE(MIN([tutkinnot]),Muuttujat[Koulutusaste, taso 2]=\"Ammattikorkeakoulututkinto\",Muuttujat[Tilastovuosi]=2017||Muuttujat[Tilastovuosi]=2016||Muuttujat[Tilastovuosi]=2015)",
              "",
              "return htv*tut",
              ""
            ],
            "formatString": "0.0",
            "displayFolder": "Henkilöstö\\Rakenteellinen kehittäminen"
          },
          {
            "name": "Amk opetuksen henkilötyövuodet 2017",
            "expression": [
              "",
              "var htv=CALCULATE(SUM(calc_amk_htv[calc_amk_opetus_htv_2017]))",
              "var tut=CALCULATE(MIN([tutkinnot]),Muuttujat[Koulutusaste, taso 2]=\"Ammattikorkeakoulututkinto\",Muuttujat[Tilastovuosi]=2017||Muuttujat[Tilastovuosi]=2016||Muuttujat[Tilastovuosi]=2015)",
              "",
              "return htv*tut"
            ],
            "formatString": "0.0",
            "displayFolder": "Henkilöstö\\Rakenteellinen kehittäminen"
          },
          {
            "name": "Ylemmät kk-tutkinnot 2015-2017 KA",
            "expression": [
              " ",
              "var tut=CALCULATE(SUM(Muuttujat[tutkinnot]),FILTER(VALUES(Muuttujat[koulutusaste, taso 2]),Muuttujat[Koulutusaste, taso 2]=\"Ylempi korkeakoulututkinto\"),FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]>2014&&Muuttujat[Tilastovuosi]<2018))",
              "var vuosia= CALCULATE(DISTINCTCOUNT(Muuttujat[Tilastovuosi]),FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]>2014&&Muuttujat[Tilastovuosi]<2018))",
              "",
              "return DIVIDE(tut,vuosia)",
              ""
            ],
            "formatString": "0.0",
            "displayFolder": "Tutkinnot\\Rakenteellinen kehittäminen"
          },
          {
            "name": "Vetovoima 2017 (I sykli, amk)",
            "expression": [
              "",
              "var hak=CALCULATE(DISTINCTCOUNT([Ensisijainen hakija]),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2017),",
              "\tNOT(ISBLANK(Muuttujat[Ensisijainen hakija])),",
              "\tFILTER(VALUES(Muuttujat[Tutkinnon aloitussykli]),Muuttujat[Tutkinnon aloitussykli]=\"I sykli\"),",
              "\tFILTER(VALUES(Muuttujat[Sektori]),Muuttujat[Sektori]=\"Ammattikorkeakoulu\"),",
              "\tFILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),Muuttujat[Koulutusaste, taso 2]=\"Ammattikorkeakoulututkinto\"))",
              "var vast=CALCULATE(DISTINCTCOUNT(Muuttujat[Paikan vastaanottaneet]),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2017),",
              "\tNOT(ISBLANK(Muuttujat[Paikan vastaanottaneet])),",
              "\tFILTER(VALUES(Muuttujat[Tutkinnon aloitussykli]),Muuttujat[Tutkinnon aloitussykli]=\"I sykli\"),",
              "\tFILTER(VALUES(Muuttujat[Sektori]),Muuttujat[Sektori]=\"Ammattikorkeakoulu\"),",
              "\tFILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),Muuttujat[Koulutusaste, taso 2]=\"Ammattikorkeakoulututkinto\"))",
              "return DIVIDE(hak,vast)"
            ],
            "formatString": "0.0",
            "displayFolder": "Haku ja valinta"
          },
          {
            "name": "Vetovoima 2016 (I sykli, amk)",
            "expression": [
              "",
              "var hak=CALCULATE(DISTINCTCOUNT([Ensisijainen hakija]),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2016),",
              "\tNOT(ISBLANK(Muuttujat[Ensisijainen hakija])),",
              "\tFILTER(VALUES(Muuttujat[Tutkinnon aloitussykli]),Muuttujat[Tutkinnon aloitussykli]=\"I sykli\"),",
              "\tFILTER(VALUES(Muuttujat[Sektori]),Muuttujat[Sektori]=\"Ammattikorkeakoulu\"),",
              "\tFILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),Muuttujat[Koulutusaste, taso 2]=\"Ammattikorkeakoulututkinto\"))",
              "var vast=CALCULATE(DISTINCTCOUNT(Muuttujat[Paikan vastaanottaneet]),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2016),",
              "\tNOT(ISBLANK(Muuttujat[Paikan vastaanottaneet])),",
              "\tFILTER(VALUES(Muuttujat[Tutkinnon aloitussykli]),Muuttujat[Tutkinnon aloitussykli]=\"I sykli\"),",
              "\tFILTER(VALUES(Muuttujat[Sektori]),Muuttujat[Sektori]=\"Ammattikorkeakoulu\"),",
              "\tFILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),Muuttujat[Koulutusaste, taso 2]=\"Ammattikorkeakoulututkinto\"))",
              "return DIVIDE(hak,vast)"
            ],
            "formatString": "0.0",
            "displayFolder": "Haku ja valinta"
          },
          {
            "name": "YAMK tutkinnot 2014-2016 KA",
            "expression": [
              " ",
              "var tut=",
              "CALCULATE(SUM(Muuttujat[tutkinnot]),",
              "\tFILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),Muuttujat[Koulutusaste, taso 2]=\"Ylempi ammattikorkeakoulututkinto\"),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]>2013&&Muuttujat[Tilastovuosi]<2017))",
              "var vuosia= CALCULATE(DISTINCTCOUNT(Muuttujat[Tilastovuosi]),FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]>2013&&Muuttujat[Tilastovuosi]<2017))",
              "",
              "return DIVIDE(tut,3)",
              ""
            ],
            "formatString": "0.0",
            "displayFolder": "Tutkinnot\\Rakenteellinen kehittäminen"
          },
          {
            "name": "YAMK tutkinnot 2015-2017 KA",
            "expression": [
              " ",
              "var tut=",
              "CALCULATE(SUM(Muuttujat[tutkinnot]),",
              "\tFILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),Muuttujat[Koulutusaste, taso 2]=\"Ylempi ammattikorkeakoulututkinto\"),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]>2014&&Muuttujat[Tilastovuosi]<2018))",
              "var vuosia= CALCULATE(DISTINCTCOUNT(Muuttujat[Tilastovuosi]),FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]>2014&&Muuttujat[Tilastovuosi]<2018))",
              "",
              "return DIVIDE(tut,3)"
            ],
            "formatString": "0.0",
            "displayFolder": "Tutkinnot\\Rakenteellinen kehittäminen"
          },
          {
            "name": "YAMK-tutkintojen osuus 2014-2016",
            "expression": [
              "",
              "var kk=CALCULATE(MAXX(SUMMARIZE(Muuttujat,Muuttujat[Koulutusnimike],\"kk\",",
              "\t\tCALCULATE([Tutkinnot lkm],Muuttujat[Koulutusaste, taso 2]=\"Ylempi ammattikorkeakoulututkinto\",Muuttujat[Tilastovuosi]=2014||Muuttujat[Tilastovuosi]=2015\t\t\t||Muuttujat[Tilastovuosi]=2016)),[kk]),ALL(Muuttujat[Tilastovuosi]))",
              "var kaik=CALCULATE(MAXX(SUMMARIZE(Muuttujat,Muuttujat[Koulutusnimike],\"kaikki\",",
              "\t\tCALCULATE([Tutkinnot lkm],Muuttujat[Koulutusaste, taso 2]=\"Ylempi ammattikorkeakoulututkinto\",Muuttujat[Tilastovuosi]=2014||Muuttujat[Tilastovuosi]=2015\t\t\t||Muuttujat[Tilastovuosi]=2016)),[kaikki]),ALL(Muuttujat[Organisaatio]),ALL(Muuttujat[Tilastovuosi]))",
              "",
              "return DIVIDE(kk,kaik)",
              ""
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Tutkinnot\\Rakenteellinen kehittäminen"
          },
          {
            "name": "YAMK-tutkintojen osuus 2015-2017",
            "expression": [
              "",
              "var kk=CALCULATE(MAXX(SUMMARIZE(Muuttujat,Muuttujat[Koulutusnimike],\"kk\",",
              "\t\tCALCULATE([Tutkinnot lkm],Muuttujat[Koulutusaste, taso 2]=\"Ylempi ammattikorkeakoulututkinto\",Muuttujat[Tilastovuosi]=2015||Muuttujat[Tilastovuosi]=2016\t\t\t||Muuttujat[Tilastovuosi]=2017)),[kk]),ALL(Muuttujat[Tilastovuosi]))",
              "var kaik=CALCULATE(MAXX(SUMMARIZE(Muuttujat,Muuttujat[Koulutusnimike],\"kaikki\",",
              "\t\tCALCULATE([Tutkinnot lkm],Muuttujat[Koulutusaste, taso 2]=\"Ylempi ammattikorkeakoulututkinto\",Muuttujat[Tilastovuosi]=2015||Muuttujat[Tilastovuosi]=2016\t\t\t||Muuttujat[Tilastovuosi]=2017)),[kaikki]),ALL(Muuttujat[Organisaatio]),ALL(Muuttujat[Tilastovuosi]))",
              "",
              "return DIVIDE(kk,kaik)",
              ""
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Tutkinnot\\Rakenteellinen kehittäminen"
          },
          {
            "name": "Ulkomaalaisten YAMK-tutkintojen osuus 2014-2016",
            "expression": [
              "",
              "var kaikki=CALCULATE([Tutkinnot lkm],",
              "\tFILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),[Koulutusaste, taso 2]=\"Ylempi ammattikorkeakoulututkinto\"),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]>2013&&Muuttujat[Tilastovuosi]<2017))",
              "var ulk=CALCULATE([Tutkinnot lkm],",
              "\tFILTER(VALUES(Muuttujat[Kansalaisuus]),Muuttujat[Kansalaisuus]<>\"Suomi\"),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]>2013&&Muuttujat[Tilastovuosi]<2017),",
              "\tFILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),[Koulutusaste, taso 2]=\"Ylempi ammattikorkeakoulututkinto\"))",
              "",
              "",
              "return DIVIDE(ulk,kaikki)",
              ""
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Tutkinnot\\Rakenteellinen kehittäminen"
          },
          {
            "name": "Ulkomaalaisten YAMK-tutkintojen osuus 2015-2017",
            "expression": [
              "",
              "var kaikki=CALCULATE([Tutkinnot lkm],",
              "\tFILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),[Koulutusaste, taso 2]=\"Ylempi ammattikorkeakoulututkinto\"),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]>2014&&Muuttujat[Tilastovuosi]<2018))",
              "var ulk=CALCULATE([Tutkinnot lkm],",
              "\tFILTER(VALUES(Muuttujat[Kansalaisuus]),Muuttujat[Kansalaisuus]<>\"Suomi\"),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]>2014&&Muuttujat[Tilastovuosi]<2018),",
              "\tFILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),[Koulutusaste, taso 2]=\"Ylempi ammattikorkeakoulututkinto\"))",
              "",
              "",
              "return DIVIDE(ulk,kaikki)"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Tutkinnot\\Rakenteellinen kehittäminen"
          },
          {
            "name": "Vetovoima 2016 (II sykli, yamk)",
            "expression": [
              "",
              "var hak=CALCULATE(DISTINCTCOUNT([Ensisijainen hakija]),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2016),",
              "\tNOT(ISBLANK(Muuttujat[Ensisijainen hakija])),",
              "\tFILTER(VALUES(Muuttujat[Tutkinnon aloitussykli]),Muuttujat[Tutkinnon aloitussykli]=\"II sykli\"),",
              "\tFILTER(VALUES(Muuttujat[Sektori]),Muuttujat[Sektori]=\"Ammattikorkeakoulu\"))",
              "var vast=CALCULATE(DISTINCTCOUNT(Muuttujat[Paikan vastaanottaneet]),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2016),",
              "\tNOT(ISBLANK(Muuttujat[Paikan vastaanottaneet])),",
              "\tFILTER(VALUES(Muuttujat[Tutkinnon aloitussykli]),Muuttujat[Tutkinnon aloitussykli]=\"II sykli\"),",
              "\tFILTER(VALUES(Muuttujat[Sektori]),Muuttujat[Sektori]=\"Ammattikorkeakoulu\"))",
              "return DIVIDE(hak,vast)"
            ],
            "formatString": "0.0",
            "displayFolder": "Haku ja valinta"
          },
          {
            "name": "Vetovoima 2017 (II sykli, yamk)",
            "expression": [
              "",
              "var hak=CALCULATE(DISTINCTCOUNT([Ensisijainen hakija]),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2017),",
              "\tNOT(ISBLANK(Muuttujat[Ensisijainen hakija])),",
              "\tFILTER(VALUES(Muuttujat[Tutkinnon aloitussykli]),Muuttujat[Tutkinnon aloitussykli]=\"II sykli\"),",
              "\tFILTER(VALUES(Muuttujat[Sektori]),Muuttujat[Sektori]=\"Ammattikorkeakoulu\"))",
              "var vast=CALCULATE(DISTINCTCOUNT(Muuttujat[Paikan vastaanottaneet]),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2017),",
              "\tNOT(ISBLANK(Muuttujat[Paikan vastaanottaneet])),",
              "\tFILTER(VALUES(Muuttujat[Tutkinnon aloitussykli]),Muuttujat[Tutkinnon aloitussykli]=\"II sykli\"),",
              "\tFILTER(VALUES(Muuttujat[Sektori]),Muuttujat[Sektori]=\"Ammattikorkeakoulu\"))",
              "return DIVIDE(hak,vast)"
            ],
            "formatString": "0.0",
            "displayFolder": "Haku ja valinta"
          },
          {
            "name": "Vetovoima 2018 (I sykli, amk)",
            "expression": [
              "",
              "var hak=CALCULATE(DISTINCTCOUNT([Ensisijainen hakija]),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2018),",
              "\tNOT(ISBLANK(Muuttujat[Ensisijainen hakija])),",
              "\tFILTER(VALUES(Muuttujat[Tutkinnon aloitussykli]),Muuttujat[Tutkinnon aloitussykli]=\"I sykli\"),",
              "\tFILTER(VALUES(Muuttujat[Sektori]),Muuttujat[Sektori]=\"Ammattikorkeakoulu\"),",
              "\tFILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),Muuttujat[Koulutusaste, taso 2]=\"Ammattikorkeakoulututkinto\"))",
              "var vast=CALCULATE(DISTINCTCOUNT(Muuttujat[Paikan vastaanottaneet]),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2018),",
              "\tNOT(ISBLANK(Muuttujat[Paikan vastaanottaneet])),",
              "\tFILTER(VALUES(Muuttujat[Tutkinnon aloitussykli]),Muuttujat[Tutkinnon aloitussykli]=\"I sykli\"),",
              "\tFILTER(VALUES(Muuttujat[Sektori]),Muuttujat[Sektori]=\"Ammattikorkeakoulu\"),",
              "\tFILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),Muuttujat[Koulutusaste, taso 2]=\"Ammattikorkeakoulututkinto\"))",
              "return DIVIDE(hak,vast)"
            ],
            "formatString": "0.0",
            "displayFolder": "Haku ja valinta"
          },
          {
            "name": "Vetovoima 2018 (II sykli, yamk)",
            "expression": [
              "",
              "var hak=CALCULATE(DISTINCTCOUNT([Ensisijainen hakija]),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2018),",
              "\tNOT(ISBLANK(Muuttujat[Ensisijainen hakija])),",
              "\tFILTER(VALUES(Muuttujat[Tutkinnon aloitussykli]),Muuttujat[Tutkinnon aloitussykli]=\"II sykli\"),",
              "\tFILTER(VALUES(Muuttujat[Sektori]),Muuttujat[Sektori]=\"Ammattikorkeakoulu\"))",
              "var vast=CALCULATE(DISTINCTCOUNT(Muuttujat[Paikan vastaanottaneet]),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2018),",
              "\tNOT(ISBLANK(Muuttujat[Paikan vastaanottaneet])),",
              "\tFILTER(VALUES(Muuttujat[Tutkinnon aloitussykli]),Muuttujat[Tutkinnon aloitussykli]=\"II sykli\"),",
              "\tFILTER(VALUES(Muuttujat[Sektori]),Muuttujat[Sektori]=\"Ammattikorkeakoulu\"))",
              "return DIVIDE(hak,vast)"
            ],
            "formatString": "0.0",
            "displayFolder": "Haku ja valinta"
          },
          {
            "name": "Vetovoima 2018 (I sykli)",
            "expression": [
              "",
              "var hak=CALCULATE(DISTINCTCOUNT([Ensisijainen hakija]),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2018),",
              "\tNOT(ISBLANK(Muuttujat[Ensisijainen hakija])),",
              "\tFILTER(VALUES(Muuttujat[Tutkinnon aloitussykli]),Muuttujat[Tutkinnon aloitussykli]=\"I sykli\"),",
              "\tFILTER(VALUES(Muuttujat[Sektori]),Muuttujat[Sektori]=\"Yliopisto\"))",
              "var vast=CALCULATE(DISTINCTCOUNT(Muuttujat[Paikan vastaanottaneet]),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2018),",
              "\tNOT(ISBLANK(Muuttujat[Paikan vastaanottaneet])),",
              "\tFILTER(VALUES(Muuttujat[Tutkinnon aloitussykli]),Muuttujat[Tutkinnon aloitussykli]=\"I sykli\"),",
              "\tFILTER(VALUES(Muuttujat[Sektori]),Muuttujat[Sektori]=\"Yliopisto\"))",
              "return DIVIDE(hak,vast)"
            ],
            "formatString": "0.0",
            "displayFolder": "Haku ja valinta"
          },
          {
            "name": "Työllisten osuus 1v valmistumisesta 2013-2015",
            "expression": [
              "",
              "var osuus= CALCULATE([Työllisten osuus (1v tutkinnon jälkeen)],FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]>2012&&Muuttujat[Tilastovuosi]<2016))",
              "return osuus",
              ""
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Työllisyys\\Rakenteellinen kehittäminen"
          },
          {
            "name": "Työllisten osuus 1v valmistumisesta 2014-2016",
            "expression": [
              "",
              "var osuus= CALCULATE([Työllisten osuus (1v tutkinnon jälkeen)],FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]>2013&&Muuttujat[Tilastovuosi]<2017))",
              "return osuus"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Työllisyys\\Rakenteellinen kehittäminen"
          },
          {
            "name": "Työllisten osuus 1v valmistumisesta 2014-2016 (RAKE, yamk-tutkinto)",
            "expression": [
              "",
              "",
              "var tyolliset=CALCULATE(SUM(Muuttujat[työlliset 1v tutkinnon jälkeen]),FILTER(VALUEs(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]>2013&&Muuttujat[Tilastovuosi]<2017),FILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),Muuttujat[Koulutusaste, taso 2]=\"Ylempi ammattikorkeakoulututkinto\"))",
              "var kaik=CALCULATE(SUM(Muuttujat[sijoittuminen_1v_tutkinnon_jalkeen]),FILTER(VALUEs(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]>2013&&Muuttujat[Tilastovuosi]<2017),FILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),Muuttujat[Koulutusaste, taso 2]=\"Ylempi ammattikorkeakoulututkinto\"))",
              "var jako=CALCULATE(DIVIDE(tyolliset,kaik))",
              "",
              "return jako"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Työllisyys\\Rakenteellinen kehittäminen"
          },
          {
            "name": "Työllisten osuus 1v valmistumisesta 2013-2015 (RAKE, yamk-tutkinto)",
            "expression": [
              "",
              "",
              "var osuus1= CALCULATE([Työllisten osuus (1v tutkinnon jälkeen)],FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2013),FILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),Muuttujat[Koulutusaste, taso 2]=\"Ylempi ammattikorkeakoulututkinto\"))",
              "var osuus2= CALCULATE([Työllisten osuus (1v tutkinnon jälkeen)],FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2014),FILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),Muuttujat[Koulutusaste, taso 2]=\"Ylempi ammattikorkeakoulututkinto\"))",
              "var osuus3= CALCULATE([Työllisten osuus (1v tutkinnon jälkeen)],FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2015),FILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),Muuttujat[Koulutusaste, taso 2]=\"Ylempi ammattikorkeakoulututkinto\"))",
              "",
              "var vuosia=CALCULATE((SWITCH(ISBLANK(osuus1),TRUE(),0,1)+SWITCH(ISBLANK(osuus2),TRUE(),0,1)+SWITCH(ISBLANK(osuus3),TRUE(),0,1)))",
              "var jako=CALCULATE(DIVIDE((osuus1+osuus2+osuus3),vuosia))",
              "",
              "return jako",
              ""
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Työllisyys\\Rakenteellinen kehittäminen"
          },
          {
            "name": "Osuus alan AMK-tutkinnoista 2014-2016",
            "expression": [
              " ",
              "var kk=CALCULATE(MAXX(SUMMARIZE(Muuttujat,Muuttujat[Koulutusnimike],\"kk\",",
              "\t\tCALCULATE([Tutkinnot lkm],Muuttujat[Koulutusaste, taso 2]=\"Ammattikorkeakoulututkinto\",Muuttujat[Tilastovuosi]=2014||Muuttujat[Tilastovuosi]=2015\t\t\t||Muuttujat[Tilastovuosi]=2016)),[kk]),ALL(Muuttujat[Tilastovuosi]))",
              "var kaik=CALCULATE(MAXX(SUMMARIZE(Muuttujat,Muuttujat[Koulutusnimike],\"kaikki\",",
              "\t\tCALCULATE([Tutkinnot lkm],Muuttujat[Koulutusaste, taso 2]=\"Ammattikorkeakoulututkinto\",Muuttujat[Tilastovuosi]=2014||Muuttujat[Tilastovuosi]=2015\t\t\t||Muuttujat[Tilastovuosi]=2016)),[kaikki]),ALL(Muuttujat[Organisaatio]),ALL(Muuttujat[Tilastovuosi]))",
              "",
              "return DIVIDE(kk,kaik)",
              ""
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Tutkinnot\\Rakenteellinen kehittäminen"
          },
          {
            "name": "Opiskelijat lkm",
            "expression": " IF(SUM(Muuttujat[Opiskelijat])= 0, BLANK(), IF(SUM(Muuttujat[Opiskelijat]) < 5, \"1-4\", MROUND(SUM(Muuttujat[Opiskelijat]), 3)))",
            "formatString": "### ### ###",
            "displayFolder": "Opiskelijat"
          },
          {
            "name": "Opiskelijat fte",
            "expression": " IF(SUM(Muuttujat[Opiskelijat_fte])= 0, BLANK(), IF(SUM(Muuttujat[Opiskelijat_fte]) < 5, \"1-4\", MROUND(SUM(Muuttujat[Opiskelijat_fte]), 3)))",
            "formatString": "### ### ###",
            "displayFolder": "Opiskelijat"
          },
          {
            "name": "Opiskelijat läsnä",
            "expression": " IF(SUM(Muuttujat[Opiskelijat_lasna])= 0, BLANK(), IF(SUM(Muuttujat[Opiskelijat_lasna]) < 5, \"1-4\", MROUND(SUM(Muuttujat[Opiskelijat_lasna]), 3)))",
            "formatString": "### ### ###",
            "displayFolder": "Opiskelijat"
          },
          {
            "name": "AMK julkaisut 2016-2017 KA",
            "expression": [
              "",
              "var julk=CALCULATE(SUM(calc_amk_julk[calc_amk_julk_2016-2017]))",
              "var tut=CALCULATE(MIN([tutkinnot]),Muuttujat[Koulutusaste, taso 2]=\"Ammattikorkeakoulututkinto\",Muuttujat[Tilastovuosi]=2017||Muuttujat[Tilastovuosi]=2016||Muuttujat[Tilastovuosi]=2015)",
              "var lask=CALCULATE(julk*tut,FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]>2015&&Muuttujat[Tilastovuosi]<2018))",
              "",
              "var jako=DIVIDE(lask,2)",
              "return jako"
            ],
            "formatString": "0.0",
            "displayFolder": "Julkaisut\\Rakenteellinen kehittäminen"
          },
          {
            "name": "AMK julkaisut (A-E) 2016-2017",
            "expression": "CALCULATE(SUM([AMK Julkaisut (A-E)]),FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]>2015&&Muuttujat[Tilastovuosi]<2018))",
            "displayFolder": "Julkaisut\\Rakenteellinen kehittäminen"
          },
          {
            "name": "AVOP-AMK työelämävalmiudet pisteet 2017",
            "expression": [
              " ",
              "CALCULATE(SUM(Muuttujat[AVOP-AMK Opiskelijapalaute_työelämä]),FILTER(Muuttujat,Muuttujat[Tilastovuosi]=2017))",
              ""
            ],
            "displayFolder": "Opiskelijapalaute\\Rakenteellinen kehittäminen"
          },
          {
            "name": "Työllistyminen 1v (AMK-tutkinto) KA 2015-2017",
            "expression": [
              "",
              "var tv = CALCULATE(sum(Muuttujat[sijoittuminen_1v_tutkinnon_jalkeen]),",
              "\t\tfilter(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]>2014&&Muuttujat[Tilastovuosi]<2018),",
              "\t\tFILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),Muuttujat[Koulutusaste, taso 2]=\"Ammattikorkeakoulututkinto\"))",
              "var t = CALCULATE(sum(Muuttujat[työlliset 1v tutkinnon jälkeen]),",
              "\t\tfilter(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]>2014&&Muuttujat[Tilastovuosi]<2018),",
              "\t\tFILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),Muuttujat[Koulutusaste, taso 2]=\"Ammattikorkeakoulututkinto\"))",
              "\t",
              "return CALCULATE(DIVIDE(t,tv))",
              ""
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Työllisyys\\Rakenteellinen kehittäminen"
          },
          {
            "name": "Lasna (1-14)",
            "expression": " IF(SUM([Läsnäolleet opiskelijat (1-14op)]) = 0, BLANK(), IF(SUM([Läsnäolleet opiskelijat (1-14op)]) < 5, \"1-4\", MROUND(SUM([Läsnäolleet opiskelijat (1-14op)]), 3)))",
            "formatString": "### ### ###.###",
            "displayFolder": "Opintopisteet\\Asemointi"
          },
          {
            "name": "1-14op suorittaneiden osuus_s",
            "expression": "IF([kytkin] = 0, BLANK(), DIVIDE([1-14op suorittaneet lkm_s], [Lasna (1-14)_s]))",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Lasna (1-14)_s",
            "expression": "IF([kytkin] = 0, BLANK(), SUM(Muuttujat[Läsnäolleet opiskelijat (1-14op)]))",
            "formatString": "### ### ###.###"
          },
          {
            "name": "1-14op suorittaneet lkm_s",
            "expression": "IF([kytkin] = 0, BLANK(), SUM([1-14op suorittaneet]))",
            "formatString": "### ### ###"
          },
          {
            "name": "Opiskelijat lkm_s",
            "expression": "IF([kytkin] = 0, BLANK(), CALCULATE(SUM(Muuttujat[Opiskelijat])))",
            "formatString": "### ### ###"
          },
          {
            "name": "Opiskelijat fte_s",
            "expression": "IF([kytkin] = 0, BLANK(), CALCULATE(SUM(Muuttujat[Opiskelijat_fte])))",
            "formatString": "### ### ###"
          },
          {
            "name": "Opiskelijat läsnä_s",
            "expression": "IF([kytkin] = 0, BLANK(), CALCULATE(SUM(Muuttujat[Opiskelijat_lasna])))",
            "formatString": "### ### ###"
          },
          {
            "name": "Vetovoima 2018",
            "expression": [
              "",
              "var hak=CALCULATE(DISTINCTCOUNT([Ensisijainen hakija]),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2018),",
              "\tNOT(ISBLANK(Muuttujat[Ensisijainen hakija])))",
              "var vast=CALCULATE(DISTINCTCOUNT(Muuttujat[Paikan vastaanottaneet]),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2018),",
              "\tNOT(ISBLANK(Muuttujat[Paikan vastaanottaneet])))",
              "return DIVIDE(hak,vast)",
              ""
            ],
            "formatString": "0.0",
            "displayFolder": "Haku ja valinta"
          },
          {
            "name": "Täyttöaste 2016",
            "expression": [
              "",
              "var vast=CALCULATE(DISTINCTCOUNT(Muuttujat[Paikan vastaanottaneet]),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2016),",
              "\tNOT(ISBLANK(Muuttujat[Paikan vastaanottaneet])))",
              "var alp=CALCULATE(SUM(Aloituspaikat[alpa]),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2016))",
              "return DIVIDE(vast,alp)"
            ],
            "formatString": "0.0",
            "displayFolder": "Haku ja valinta"
          },
          {
            "name": "Täyttöaste 2017",
            "expression": [
              "",
              "var vast=CALCULATE(DISTINCTCOUNT(Muuttujat[Paikan vastaanottaneet]),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2017),",
              "\tNOT(ISBLANK(Muuttujat[Paikan vastaanottaneet])))",
              "var alp=CALCULATE(SUM(Aloituspaikat[alpa]),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]), Muuttujat[Tilastovuosi]=2017))",
              "return DIVIDE(vast,alp)",
              "",
              ""
            ],
            "formatString": "0.0",
            "displayFolder": "Haku ja valinta"
          },
          {
            "name": "Täyttöaste 2018",
            "expression": [
              "",
              "var vast=CALCULATE(DISTINCTCOUNT(Muuttujat[Paikan vastaanottaneet]),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2018),",
              "\tNOT(ISBLANK(Muuttujat[Paikan vastaanottaneet])))",
              "var alp=CALCULATE(SUM(Aloituspaikat[alpa]),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2018))",
              "return DIVIDE(vast,alp)",
              ""
            ],
            "formatString": "0.0",
            "displayFolder": "Haku ja valinta"
          },
          {
            "name": "Täyttöaste 2016 (I sykli)",
            "expression": [
              "",
              "var vast=CALCULATE(DISTINCTCOUNT(Muuttujat[Paikan vastaanottaneet]),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2016),",
              "\tNOT(ISBLANK(Muuttujat[Paikan vastaanottaneet])),",
              "\tFILTER(VALUES(Muuttujat[Tutkinnon aloitussykli]),Muuttujat[Tutkinnon aloitussykli]=\"I sykli\"),",
              "\tFILTER(VALUES(Muuttujat[Sektori]),Muuttujat[Sektori]=\"Yliopisto\"))",
              "var alp=CALCULATE(SUM(Aloituspaikat[alpa]),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2016),",
              "\tFILTER(VALUES(Muuttujat[Tutkinnon aloitussykli]),Muuttujat[Tutkinnon aloitussykli]=\"I sykli\"),",
              "\tFILTER(VALUES(Muuttujat[Sektori]),Muuttujat[Sektori]=\"Yliopisto\"))",
              "return DIVIDE(vast,alp)"
            ],
            "formatString": "0.0",
            "displayFolder": "Haku ja valinta"
          },
          {
            "name": "Täyttöaste 2017 (I sykli)",
            "expression": [
              "",
              "var vast=CALCULATE(DISTINCTCOUNT(Muuttujat[Paikan vastaanottaneet]),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2017),",
              "\tNOT(ISBLANK(Muuttujat[Paikan vastaanottaneet])),",
              "\tFILTER(VALUES(Muuttujat[Tutkinnon aloitussykli]),Muuttujat[Tutkinnon aloitussykli]=\"I sykli\"),",
              "\tFILTER(VALUES(Muuttujat[Sektori]),Muuttujat[Sektori]=\"Yliopisto\"))",
              "var alp=CALCULATE(SUM(Aloituspaikat[alpa]),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2017),",
              "\tFILTER(VALUES(Muuttujat[Tutkinnon aloitussykli]),Muuttujat[Tutkinnon aloitussykli]=\"I sykli\"),",
              "\tFILTER(VALUES(Muuttujat[Sektori]),Muuttujat[Sektori]=\"Yliopisto\"))",
              "return DIVIDE(vast,alp)"
            ],
            "formatString": "0.0",
            "displayFolder": "Haku ja valinta"
          },
          {
            "name": "Täyttöaste 2018 (I sykli)",
            "expression": [
              "",
              "var vast=CALCULATE(DISTINCTCOUNT(Muuttujat[Paikan vastaanottaneet]),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2018),",
              "\tNOT(ISBLANK(Muuttujat[Paikan vastaanottaneet])),",
              "\tFILTER(VALUES(Muuttujat[Tutkinnon aloitussykli]),Muuttujat[Tutkinnon aloitussykli]=\"I sykli\"),",
              "\tFILTER(VALUES(Muuttujat[Sektori]),Muuttujat[Sektori]=\"Yliopisto\"))",
              "var alp=CALCULATE(SUM(Aloituspaikat[alpa]),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2018),",
              "\tFILTER(VALUES(Muuttujat[Tutkinnon aloitussykli]),Muuttujat[Tutkinnon aloitussykli]=\"I sykli\"),",
              "\tFILTER(VALUES(Muuttujat[Sektori]),Muuttujat[Sektori]=\"Yliopisto\"))",
              "return DIVIDE(vast,alp)"
            ],
            "formatString": "0.0",
            "displayFolder": "Haku ja valinta"
          },
          {
            "name": "Täyttöaste 2016 (I sykli, amk)",
            "expression": [
              "",
              "var vast=CALCULATE(DISTINCTCOUNT(Muuttujat[Paikan vastaanottaneet]),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2016),",
              "\tNOT(ISBLANK(Muuttujat[Paikan vastaanottaneet])),",
              "\tFILTER(VALUES(Muuttujat[Tutkinnon aloitussykli]),Muuttujat[Tutkinnon aloitussykli]=\"I sykli\"),",
              "\tFILTER(VALUES(Muuttujat[Sektori]),Muuttujat[Sektori]=\"Ammattikorkeakoulu\"),",
              "\tFILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),Muuttujat[Koulutusaste, taso 2]=\"Ammattikorkeakoulututkinto\"))",
              "var alp=CALCULATE(SUM(Aloituspaikat[alpa]),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2016),",
              "\tFILTER(VALUES(Muuttujat[Tutkinnon aloitussykli]),Muuttujat[Tutkinnon aloitussykli]=\"I sykli\"),",
              "\tFILTER(VALUES(Muuttujat[Sektori]),Muuttujat[Sektori]=\"Ammattikorkeakoulu\"),",
              "\tFILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),Muuttujat[Koulutusaste, taso 2]=\"Ammattikorkeakoulututkinto\"))",
              "return DIVIDE(vast,alp)"
            ],
            "formatString": "0.0",
            "displayFolder": "Haku ja valinta"
          },
          {
            "name": "Täyttöaste 2017 (I sykli, amk)",
            "expression": [
              "",
              "var vast=CALCULATE(DISTINCTCOUNT(Muuttujat[Paikan vastaanottaneet]),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2017),",
              "\tNOT(ISBLANK(Muuttujat[Paikan vastaanottaneet])),",
              "\tFILTER(VALUES(Muuttujat[Tutkinnon aloitussykli]),Muuttujat[Tutkinnon aloitussykli]=\"I sykli\"),",
              "\tFILTER(VALUES(Muuttujat[Sektori]),Muuttujat[Sektori]=\"Ammattikorkeakoulu\"),",
              "\tFILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),Muuttujat[Koulutusaste, taso 2]=\"Ammattikorkeakoulututkinto\"))",
              "var alp=CALCULATE(SUM(Aloituspaikat[alpa]),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2017),",
              "\tFILTER(VALUES(Muuttujat[Tutkinnon aloitussykli]),Muuttujat[Tutkinnon aloitussykli]=\"I sykli\"),",
              "\tFILTER(VALUES(Muuttujat[Sektori]),Muuttujat[Sektori]=\"Ammattikorkeakoulu\"),",
              "\tFILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),Muuttujat[Koulutusaste, taso 2]=\"Ammattikorkeakoulututkinto\"))",
              "return DIVIDE(vast,alp)"
            ],
            "formatString": "0.0",
            "displayFolder": "Haku ja valinta"
          },
          {
            "name": "Täyttöaste 2018 (I sykli, amk)",
            "expression": [
              "",
              "var vast=CALCULATE(DISTINCTCOUNT(Muuttujat[Paikan vastaanottaneet]),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2018),",
              "\tNOT(ISBLANK(Muuttujat[Paikan vastaanottaneet])),",
              "\tFILTER(VALUES(Muuttujat[Tutkinnon aloitussykli]),Muuttujat[Tutkinnon aloitussykli]=\"I sykli\"),",
              "\tFILTER(VALUES(Muuttujat[Sektori]),Muuttujat[Sektori]=\"Ammattikorkeakoulu\"),",
              "\tFILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),Muuttujat[Koulutusaste, taso 2]=\"Ammattikorkeakoulututkinto\"))",
              "var alp=CALCULATE(SUM(Aloituspaikat[alpa]),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2018),",
              "\tFILTER(VALUES(Muuttujat[Tutkinnon aloitussykli]),Muuttujat[Tutkinnon aloitussykli]=\"I sykli\"),",
              "\tFILTER(VALUES(Muuttujat[Sektori]),Muuttujat[Sektori]=\"Ammattikorkeakoulu\"),",
              "\tFILTER(VALUES(Muuttujat[Koulutusaste, taso 2]),Muuttujat[Koulutusaste, taso 2]=\"Ammattikorkeakoulututkinto\"))",
              "return DIVIDE(vast,alp)"
            ],
            "formatString": "0.0",
            "displayFolder": "Haku ja valinta"
          },
          {
            "name": "Täyttöaste 2016 (II sykli, yamk)",
            "expression": [
              "",
              "var vast=CALCULATE(DISTINCTCOUNT(Muuttujat[Paikan vastaanottaneet]),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2016),",
              "\tNOT(ISBLANK(Muuttujat[Paikan vastaanottaneet])),",
              "\tFILTER(VALUES(Muuttujat[Tutkinnon aloitussykli]),Muuttujat[Tutkinnon aloitussykli]=\"II sykli\"),",
              "\tFILTER(VALUES(Muuttujat[Sektori]),Muuttujat[Sektori]=\"Ammattikorkeakoulu\"))",
              "var alp=CALCULATE(SUM(Aloituspaikat[alpa]),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2016),",
              "\tFILTER(VALUES(Muuttujat[Tutkinnon aloitussykli]),Muuttujat[Tutkinnon aloitussykli]=\"II sykli\"),",
              "\tFILTER(VALUES(Muuttujat[Sektori]),Muuttujat[Sektori]=\"Ammattikorkeakoulu\"))",
              "return DIVIDE(vast,alp)"
            ],
            "formatString": "0.0",
            "displayFolder": "Haku ja valinta"
          },
          {
            "name": "Täyttöaste 2017 (II sykli, yamk)",
            "expression": [
              "",
              "var vast=CALCULATE(DISTINCTCOUNT(Muuttujat[Paikan vastaanottaneet]),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2017),",
              "\tNOT(ISBLANK(Muuttujat[Paikan vastaanottaneet])),",
              "\tFILTER(VALUES(Muuttujat[Tutkinnon aloitussykli]),Muuttujat[Tutkinnon aloitussykli]=\"II sykli\"),",
              "\tFILTER(VALUES(Muuttujat[Sektori]),Muuttujat[Sektori]=\"Ammattikorkeakoulu\"))",
              "var alp=CALCULATE(SUM(Aloituspaikat[alpa]),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2017),",
              "\tFILTER(VALUES(Muuttujat[Tutkinnon aloitussykli]),Muuttujat[Tutkinnon aloitussykli]=\"II sykli\"),",
              "\tFILTER(VALUES(Muuttujat[Sektori]),Muuttujat[Sektori]=\"Ammattikorkeakoulu\"))",
              "return DIVIDE(vast,alp)"
            ],
            "formatString": "0.0",
            "displayFolder": "Haku ja valinta"
          },
          {
            "name": "Täyttöaste 2018 (II sykli, yamk)",
            "expression": [
              "",
              "var vast=CALCULATE(DISTINCTCOUNT(Muuttujat[Paikan vastaanottaneet]),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2018),",
              "\tNOT(ISBLANK(Muuttujat[Paikan vastaanottaneet])),",
              "\tFILTER(VALUES(Muuttujat[Tutkinnon aloitussykli]),Muuttujat[Tutkinnon aloitussykli]=\"II sykli\"),",
              "\tFILTER(VALUES(Muuttujat[Sektori]),Muuttujat[Sektori]=\"Ammattikorkeakoulu\"))",
              "var alp=CALCULATE(SUM(Aloituspaikat[alpa]),",
              "\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2018),",
              "\tFILTER(VALUES(Muuttujat[Tutkinnon aloitussykli]),Muuttujat[Tutkinnon aloitussykli]=\"II sykli\"),",
              "\tFILTER(VALUES(Muuttujat[Sektori]),Muuttujat[Sektori]=\"Ammattikorkeakoulu\"))",
              "return DIVIDE(vast,alp)"
            ],
            "formatString": "0.0",
            "displayFolder": "Haku ja valinta"
          },
          {
            "name": "5v aloittaneet_s",
            "expression": "IF([kytkin] = 0, BLANK(), SUM(Muuttujat[5v_Aloittaneet_lkm]))"
          },
          {
            "name": "5v suorittaneet_s",
            "expression": "IF([kytkin] = 0, BLANK(), SUM(Muuttujat[5v_suorittaneet_lkm]))"
          },
          {
            "name": "7v aloittaneet_s",
            "expression": "IF([kytkin] = 0, BLANK(), SUM(Muuttujat[Yo 7v aloittaneet lkm]))"
          },
          {
            "name": "7v suorittaneet_s",
            "expression": "IF([kytkin] = 0, BLANK(), SUM(Muuttujat[7v_suorittaneet_lkm]))"
          },
          {
            "name": "Seitsemän vuoden läpäisy (yo)_s",
            "expression": " IF([kytkin] = 0, BLANK(), DIVIDE([7v suorittaneet_s], [7v aloittaneet_s]))",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Viiden vuoden läpäisy (amk)_s",
            "expression": [
              " IF([kytkin] = 0, BLANK(), DIVIDE([5v suorittaneet_s], [5v aloittaneet_s]))",
              ""
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "sijoittuminen perusjoukko 1v tutkinnon jälkeen_s",
            "expression": " IF([kytkin] = 0, BLANK(), CALCULATE(SUM(Muuttujat[sijoittuminen_1v_tutkinnon_jalkeen])))",
            "formatString": "### ### ###.###"
          },
          {
            "name": "sijoittuminen perusjoukko 3v tutkinnon jälkeen_s",
            "expression": " IF([kytkin] = 0, BLANK(), CALCULATE(SUM(Muuttujat[sijoittuminen_3v_tutkinnon_jalkeen])))",
            "formatString": "### ### ###.###"
          },
          {
            "name": "Työlliset (1v tutkinnon jälkeen)_s",
            "expression": "IF([kytkin] = 0, BLANK(), CALCULATE(SUM(Muuttujat[työlliset 1v tutkinnon jälkeen])))",
            "formatString": "### ### ###.###"
          },
          {
            "name": "Työlliset (3v tutkinnon jälkeen)_s",
            "expression": "IF([kytkin] = 0, BLANK(), CALCULATE(SUM(Muuttujat[Työlliset 3v tutkinnon jälkeen])))",
            "formatString": "### ### ###.###"
          },
          {
            "name": "kytkin",
            "expression": "IF(LEFT(USERNAME(), 4) = \"DWI\\\", 1, 0)",
            "formatString": "0",
            "isHidden": true
          },
          {
            "name": "Tutkinnot lkm_s",
            "expression": "IF([kytkin] = 0, BLANK(), SUM([tutkinnot]))"
          },
          {
            "name": "Ulkomaalaisten suorittamat tutkinnot_s",
            "expression": "IF([kytkin] = 0, BLANK(), CALCULATE([Tutkinnot lkm_s],Muuttujat[Kansalaisuus]<>\"Suomi\"))"
          },
          {
            "name": "Ulkomaalaisten suorittamien tutkintojen osuus_s",
            "expression": "IF([kytkin] = 0, BLANK(), DIVIDE(CALCULATE([Tutkinnot lkm_s],Muuttujat[Kansalaisuus]<>\"Suomi\"),[Tutkinnot lkm_s]))",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Alemmat korkeakoulututkinnot /opetus- ja tutkimushenkilökunta_s",
            "expression": "IF([kytkin] = 0, BLANK(), DIVIDE(CALCULATE([Tutkinnot lkm_s],Muuttujat[Koulutusaste, taso 2]=\"Alempi korkeakoulututkinto\" || Muuttujat[Koulutusaste, taso 2]=\"Ammattikorkeakoulututkinto\"),CALCULATE(SUM([Yliopiston opetus- ja tutkimushenkilötyövuodet])+(SUM([Ammattikorkeakoulun opetushenkilökunta])+SUM([Ammattikorkeakoulun TKI-henkilökunta])))))",
            "formatString": "0.0"
          },
          {
            "name": "Ylemmät tutkinnot / opetus- ja tutkimushenkilökunta_s",
            "expression": "IF([kytkin] = 0, BLANK(), DIVIDE(CALCULATE([Tutkinnot lkm_s],Muuttujat[Koulutusaste, taso 2]=\"Ylempi korkeakoulututkinto\" || Muuttujat[Koulutusaste, taso 2]=\"Ylempi ammattikorkeakoulututkinto\" || Muuttujat[Koulutusaste, taso 2]=\"Master's or equivalent level, Orientation unspecified\" ),CALCULATE(SUM([Yliopiston opetus- ja tutkimushenkilötyövuodet])+(SUM([Ammattikorkeakoulun opetushenkilökunta])+SUM([Ammattikorkeakoulun TKI-henkilökunta])))))",
            "formatString": "0.0"
          },
          {
            "name": "Tohtorin tutkinnot / IV porras henkilötyövuodet_s",
            "expression": "IF([kytkin] = 0, BLANK(), DIVIDE(CALCULATE([Tutkinnot lkm_s],Muuttujat[Koulutusaste, taso 2]=\"Tohtorintutkinto\"),SUM(Muuttujat[IV tutkijanuraportaan henkilötyövuodet])))",
            "formatString": "0.0"
          },
          {
            "name": "Työllisten osuus (1v tutkinnon jälkeen)_s",
            "expression": "IF([kytkin] = 0, BLANK(), DIVIDE(SUM([työlliset 1v tutkinnon jälkeen]),SUM([sijoittuminen_1v_tutkinnon_jalkeen])))",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Työllisten osuus (3v tutkinnon jälkeen)_s",
            "expression": "IF([kytkin] = 0, BLANK(), DIVIDE([Työlliset (3v tutkinnon jälkeen)_s],[sijoittuminen perusjoukko 3v tutkinnon jälkeen_s]))",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Työllisten osuus 3v (RAKE-määritelmä)_s",
            "expression": [
              "",
              "IF([kytkin] = 0, BLANK(), DIVIDE(CALCULATE(SUM(Muuttujat[Työlliset 3v (ver2 10,13)]),Muuttujat[Työlliset 3v (ver2 10,13)]<>0,NOT(ISBLANK(Muuttujat[Työlliset 3v (ver2 10,13)]))), CALCULATE(SUM(Muuttujat[Työttömät 3v (ver2, 12)]),Muuttujat[Työttömät 3v (ver2, 12)]<>0,NOT(ISBLANK(Muuttujat[Työttömät 3v (ver2, 12)])))))"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dw].[v_indikaattori_asemointi].* FROM [dw].[v_indikaattori_asemointi]  WHERE ([Organisaatio] NOT LIKE N'%Poliisi%') "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "v_indikaattori_asemointi"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dw"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Koodit organisaatio</string>",
              "      </key>",
              "      <value>",
              "        <int>122</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tilastovuosi</string>",
              "      </key>",
              "      <value>",
              "        <int>86</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj. OKM ohjauksen ala</string>",
              "      </key>",
              "      <value>",
              "        <int>144</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj. koulutusaste, taso 2</string>",
              "      </key>",
              "      <value>",
              "        <int>151</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj. koulutusaste, taso 1</string>",
              "      </key>",
              "      <value>",
              "        <int>151</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusala, taso 1</string>",
              "      </key>",
              "      <value>",
              "        <int>122</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusala, taso 2</string>",
              "      </key>",
              "      <value>",
              "        <int>122</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusala, taso 3</string>",
              "      </key>",
              "      <value>",
              "        <int>122</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kunta</string>",
              "      </key>",
              "      <value>",
              "        <int>58</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit kunta</string>",
              "      </key>",
              "      <value>",
              "        <int>90</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tutkinnot</string>",
              "      </key>",
              "      <value>",
              "        <int>73</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Yo 7v aloittaneet lkm</string>",
              "      </key>",
              "      <value>",
              "        <int>130</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>5v_Aloittaneet_lkm</string>",
              "      </key>",
              "      <value>",
              "        <int>122</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>7v_suorittaneet_lkm</string>",
              "      </key>",
              "      <value>",
              "        <int>128</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>5v_suorittaneet_lkm</string>",
              "      </key>",
              "      <value>",
              "        <int>128</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Sektori</string>",
              "      </key>",
              "      <value>",
              "        <int>63</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>55op suorittaneet</string>",
              "      </key>",
              "      <value>",
              "        <int>116</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>1-14op suorittaneet</string>",
              "      </key>",
              "      <value>",
              "        <int>126</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>AVOP-YAMK Opiskelijapalaute_työelämä</string>",
              "      </key>",
              "      <value>",
              "        <int>222</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>AVOP-AMK Opiskelijapalaute_työelämä</string>",
              "      </key>",
              "      <value>",
              "        <int>216</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>AVOP-AMK pistemäärä</string>",
              "      </key>",
              "      <value>",
              "        <int>138</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>AMK Julkaisut (A-E)</string>",
              "      </key>",
              "      <value>",
              "        <int>123</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>YO Julkaisut (A1-A4, C1 ja C2) jufotaso 2 ja 3</string>",
              "      </key>",
              "      <value>",
              "        <int>250</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>YO Julkaisut (A1-A4, C1 ja C2) jufotaso 1-3</string>",
              "      </key>",
              "      <value>",
              "        <int>239</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kandikyselyn pistemäärä</string>",
              "      </key>",
              "      <value>",
              "        <int>148</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kilpailtu tutkimusrahoitus</string>",
              "      </key>",
              "      <value>",
              "        <int>148</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>kv_vaihtoopiskelijat_op_lkm</string>",
              "      </key>",
              "      <value>",
              "        <int>163</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ulkom_hyv_luetut_op_lkm</string>",
              "      </key>",
              "      <value>",
              "        <int>154</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>erilopintooik_op_lkm</string>",
              "      </key>",
              "      <value>",
              "        <int>126</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>avoinamk_op_amk_lkm</string>",
              "      </key>",
              "      <value>",
              "        <int>139</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>mamu_op_lkm</string>",
              "      </key>",
              "      <value>",
              "        <int>97</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>erikoul_suor_op_lkm</string>",
              "      </key>",
              "      <value>",
              "        <int>127</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>sijoittuminen_1v_tutkinnon_jalkeen</string>",
              "      </key>",
              "      <value>",
              "        <int>199</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Työttömät 3v (ver2, 12)</string>",
              "      </key>",
              "      <value>",
              "        <int>147</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Työlliset 3v (ver2 10,13)</string>",
              "      </key>",
              "      <value>",
              "        <int>148</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Työlliset 3v tutkinnon jälkeen</string>",
              "      </key>",
              "      <value>",
              "        <int>169</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Organisaatio</string>",
              "      </key>",
              "      <value>",
              "        <int>91</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit OKM ohjauksen ala</string>",
              "      </key>",
              "      <value>",
              "        <int>154</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kansalaisuus</string>",
              "      </key>",
              "      <value>",
              "        <int>91</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusaste, taso 2</string>",
              "      </key>",
              "      <value>",
              "        <int>129</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusaste, taso 1</string>",
              "      </key>",
              "      <value>",
              "        <int>129</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>OKM ohjauksen ala</string>",
              "      </key>",
              "      <value>",
              "        <int>121</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusaste 2002</string>",
              "      </key>",
              "      <value>",
              "        <int>119</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>työlliset 1v tutkinnon jälkeen</string>",
              "      </key>",
              "      <value>",
              "        <int>167</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>YO kansainvälinen yhteisjulkaisu (A1-A4, C1 ja C2) jufotaso 1-3</string>",
              "      </key>",
              "      <value>",
              "        <int>335</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ammattikorkeakoulun TKI-henkilökunta</string>",
              "      </key>",
              "      <value>",
              "        <int>215</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>AMK julkaisut (F ja I)</string>",
              "      </key>",
              "      <value>",
              "        <int>129</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ammattikorkeakoulun opetushenkilökunta</string>",
              "      </key>",
              "      <value>",
              "        <int>228</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Rahoitusmalliala, amk</string>",
              "      </key>",
              "      <value>",
              "        <int>132</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj. rahoitusmalliala yo 2021-2024</string>",
              "      </key>",
              "      <value>",
              "        <int>246</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>IV tutkijanuraportaan henkilötyövuodet</string>",
              "      </key>",
              "      <value>",
              "        <int>219</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tieteenala</string>",
              "      </key>",
              "      <value>",
              "        <int>80</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tutkijanuravaihe</string>",
              "      </key>",
              "      <value>",
              "        <int>110</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>YO Julkaisut (A1-A4, C1) jufotaso 1-3</string>",
              "      </key>",
              "      <value>",
              "        <int>211</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>sijoittuminen_3v_tutkinnon_jalkeen</string>",
              "      </key>",
              "      <value>",
              "        <int>199</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Yliopiston opetus- ja tutkimushenkilötyövuodet</string>",
              "      </key>",
              "      <value>",
              "        <int>253</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Läsnäolleet opiskelijat (1-14op)</string>",
              "      </key>",
              "      <value>",
              "        <int>179</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Läsnäolevat opiskelijat (55op)</string>",
              "      </key>",
              "      <value>",
              "        <int>173</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ensisijainen hakija</string>",
              "      </key>",
              "      <value>",
              "        <int>116</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Paikan vastaanottaneet</string>",
              "      </key>",
              "      <value>",
              "        <int>145</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj. rahoitusmalliala amk</string>",
              "      </key>",
              "      <value>",
              "        <int>148</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Rahoitusmalliala, yo 2021-2024</string>",
              "      </key>",
              "      <value>",
              "        <int>226</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj. paatieteenala</string>",
              "      </key>",
              "      <value>",
              "        <int>119</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj. tieteenala</string>",
              "      </key>",
              "      <value>",
              "        <int>101</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>JulkaisuID</string>",
              "      </key>",
              "      <value>",
              "        <int>78</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Jufotaso</string>",
              "      </key>",
              "      <value>",
              "        <int>72</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kilpailtu tutkimusrahoitus (SA,Tekes, EU-puiteohjelma)</string>",
              "      </key>",
              "      <value>",
              "        <int>289</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusnimike</string>",
              "      </key>",
              "      <value>",
              "        <int>100</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit Koulutusnimike</string>",
              "      </key>",
              "      <value>",
              "        <int>133</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Päätieteenala</string>",
              "      </key>",
              "      <value>",
              "        <int>96</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tieteenala_avain</string>",
              "      </key>",
              "      <value>",
              "        <int>112</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Aloituslukuvuosi (läpäisy)</string>",
              "      </key>",
              "      <value>",
              "        <int>150</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tutkinnon aloitussykli</string>",
              "      </key>",
              "      <value>",
              "        <int>131</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Osallistuminen huippuyksik.</string>",
              "      </key>",
              "      <value>",
              "        <int>160</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Akatemia profesuurit</string>",
              "      </key>",
              "      <value>",
              "        <int>130</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>erc,stg,cog ja adg</string>",
              "      </key>",
              "      <value>",
              "        <int>118</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Opiskelijat</string>",
              "      </key>",
              "      <value>",
              "        <int>79</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Opiskelijat_fte</string>",
              "      </key>",
              "      <value>",
              "        <int>99</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Opiskelijat_lasna</string>",
              "      </key>",
              "      <value>",
              "        <int>110</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>toimipiste_id</string>",
              "      </key>",
              "      <value>",
              "        <int>110</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>hakukohde_id</string>",
              "      </key>",
              "      <value>",
              "        <int>121</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Rahoitusmalliala, yo 2017-2020</string>",
              "      </key>",
              "      <value>",
              "        <int>226</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj. rahoitusmalliala yo 2017-2020</string>",
              "      </key>",
              "      <value>",
              "        <int>246</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>alpa</string>",
              "      </key>",
              "      <value>",
              "        <int>59</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Koodit organisaatio</string>",
              "      </key>",
              "      <value>",
              "        <int>52</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tilastovuosi</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj. OKM ohjauksen ala</string>",
              "      </key>",
              "      <value>",
              "        <int>30</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj. koulutusaste, taso 2</string>",
              "      </key>",
              "      <value>",
              "        <int>29</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj. koulutusaste, taso 1</string>",
              "      </key>",
              "      <value>",
              "        <int>28</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusala, taso 1</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusala, taso 2</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusala, taso 3</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kunta</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit kunta</string>",
              "      </key>",
              "      <value>",
              "        <int>32</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tutkinnot</string>",
              "      </key>",
              "      <value>",
              "        <int>5</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Yo 7v aloittaneet lkm</string>",
              "      </key>",
              "      <value>",
              "        <int>6</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>5v_Aloittaneet_lkm</string>",
              "      </key>",
              "      <value>",
              "        <int>7</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>7v_suorittaneet_lkm</string>",
              "      </key>",
              "      <value>",
              "        <int>8</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>5v_suorittaneet_lkm</string>",
              "      </key>",
              "      <value>",
              "        <int>9</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Sektori</string>",
              "      </key>",
              "      <value>",
              "        <int>22</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>55op suorittaneet</string>",
              "      </key>",
              "      <value>",
              "        <int>10</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>1-14op suorittaneet</string>",
              "      </key>",
              "      <value>",
              "        <int>11</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>AVOP-YAMK Opiskelijapalaute_työelämä</string>",
              "      </key>",
              "      <value>",
              "        <int>73</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>AVOP-AMK Opiskelijapalaute_työelämä</string>",
              "      </key>",
              "      <value>",
              "        <int>72</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>AVOP-AMK pistemäärä</string>",
              "      </key>",
              "      <value>",
              "        <int>71</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>AMK Julkaisut (A-E)</string>",
              "      </key>",
              "      <value>",
              "        <int>33</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>YO Julkaisut (A1-A4, C1 ja C2) jufotaso 2 ja 3</string>",
              "      </key>",
              "      <value>",
              "        <int>12</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>YO Julkaisut (A1-A4, C1 ja C2) jufotaso 1-3</string>",
              "      </key>",
              "      <value>",
              "        <int>13</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kandikyselyn pistemäärä</string>",
              "      </key>",
              "      <value>",
              "        <int>70</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kilpailtu tutkimusrahoitus</string>",
              "      </key>",
              "      <value>",
              "        <int>14</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>kv_vaihtoopiskelijat_op_lkm</string>",
              "      </key>",
              "      <value>",
              "        <int>15</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ulkom_hyv_luetut_op_lkm</string>",
              "      </key>",
              "      <value>",
              "        <int>16</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>erilopintooik_op_lkm</string>",
              "      </key>",
              "      <value>",
              "        <int>17</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>avoinamk_op_amk_lkm</string>",
              "      </key>",
              "      <value>",
              "        <int>18</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>mamu_op_lkm</string>",
              "      </key>",
              "      <value>",
              "        <int>19</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>erikoul_suor_op_lkm</string>",
              "      </key>",
              "      <value>",
              "        <int>20</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>sijoittuminen_1v_tutkinnon_jalkeen</string>",
              "      </key>",
              "      <value>",
              "        <int>21</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Työttömät 3v (ver2, 12)</string>",
              "      </key>",
              "      <value>",
              "        <int>69</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Työlliset 3v (ver2 10,13)</string>",
              "      </key>",
              "      <value>",
              "        <int>68</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Työlliset 3v tutkinnon jälkeen</string>",
              "      </key>",
              "      <value>",
              "        <int>67</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Organisaatio</string>",
              "      </key>",
              "      <value>",
              "        <int>51</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit OKM ohjauksen ala</string>",
              "      </key>",
              "      <value>",
              "        <int>31</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kansalaisuus</string>",
              "      </key>",
              "      <value>",
              "        <int>27</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusaste, taso 2</string>",
              "      </key>",
              "      <value>",
              "        <int>26</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusaste, taso 1</string>",
              "      </key>",
              "      <value>",
              "        <int>25</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>OKM ohjauksen ala</string>",
              "      </key>",
              "      <value>",
              "        <int>24</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusaste 2002</string>",
              "      </key>",
              "      <value>",
              "        <int>23</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>työlliset 1v tutkinnon jälkeen</string>",
              "      </key>",
              "      <value>",
              "        <int>66</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>YO kansainvälinen yhteisjulkaisu (A1-A4, C1 ja C2) jufotaso 1-3</string>",
              "      </key>",
              "      <value>",
              "        <int>65</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ammattikorkeakoulun TKI-henkilökunta</string>",
              "      </key>",
              "      <value>",
              "        <int>64</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>AMK julkaisut (F ja I)</string>",
              "      </key>",
              "      <value>",
              "        <int>34</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ammattikorkeakoulun opetushenkilökunta</string>",
              "      </key>",
              "      <value>",
              "        <int>63</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Rahoitusmalliala, amk</string>",
              "      </key>",
              "      <value>",
              "        <int>35</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj. rahoitusmalliala yo 2021-2024</string>",
              "      </key>",
              "      <value>",
              "        <int>83</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>IV tutkijanuraportaan henkilötyövuodet</string>",
              "      </key>",
              "      <value>",
              "        <int>62</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tieteenala</string>",
              "      </key>",
              "      <value>",
              "        <int>36</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tutkijanuravaihe</string>",
              "      </key>",
              "      <value>",
              "        <int>37</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>YO Julkaisut (A1-A4, C1) jufotaso 1-3</string>",
              "      </key>",
              "      <value>",
              "        <int>38</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>sijoittuminen_3v_tutkinnon_jalkeen</string>",
              "      </key>",
              "      <value>",
              "        <int>39</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Yliopiston opetus- ja tutkimushenkilötyövuodet</string>",
              "      </key>",
              "      <value>",
              "        <int>61</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Läsnäolleet opiskelijat (1-14op)</string>",
              "      </key>",
              "      <value>",
              "        <int>60</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Läsnäolevat opiskelijat (55op)</string>",
              "      </key>",
              "      <value>",
              "        <int>59</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ensisijainen hakija</string>",
              "      </key>",
              "      <value>",
              "        <int>40</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Paikan vastaanottaneet</string>",
              "      </key>",
              "      <value>",
              "        <int>41</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj. rahoitusmalliala amk</string>",
              "      </key>",
              "      <value>",
              "        <int>42</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Rahoitusmalliala, yo 2021-2024</string>",
              "      </key>",
              "      <value>",
              "        <int>82</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj. paatieteenala</string>",
              "      </key>",
              "      <value>",
              "        <int>43</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj. tieteenala</string>",
              "      </key>",
              "      <value>",
              "        <int>44</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>JulkaisuID</string>",
              "      </key>",
              "      <value>",
              "        <int>45</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Jufotaso</string>",
              "      </key>",
              "      <value>",
              "        <int>46</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kilpailtu tutkimusrahoitus (SA,Tekes, EU-puiteohjelma)</string>",
              "      </key>",
              "      <value>",
              "        <int>47</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusnimike</string>",
              "      </key>",
              "      <value>",
              "        <int>48</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit Koulutusnimike</string>",
              "      </key>",
              "      <value>",
              "        <int>49</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Päätieteenala</string>",
              "      </key>",
              "      <value>",
              "        <int>58</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tieteenala_avain</string>",
              "      </key>",
              "      <value>",
              "        <int>50</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Aloituslukuvuosi (läpäisy)</string>",
              "      </key>",
              "      <value>",
              "        <int>57</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tutkinnon aloitussykli</string>",
              "      </key>",
              "      <value>",
              "        <int>53</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Osallistuminen huippuyksik.</string>",
              "      </key>",
              "      <value>",
              "        <int>54</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Akatemia profesuurit</string>",
              "      </key>",
              "      <value>",
              "        <int>55</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>erc,stg,cog ja adg</string>",
              "      </key>",
              "      <value>",
              "        <int>56</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Opiskelijat</string>",
              "      </key>",
              "      <value>",
              "        <int>74</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Opiskelijat_fte</string>",
              "      </key>",
              "      <value>",
              "        <int>75</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Opiskelijat_lasna</string>",
              "      </key>",
              "      <value>",
              "        <int>76</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>toimipiste_id</string>",
              "      </key>",
              "      <value>",
              "        <int>77</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>hakukohde_id</string>",
              "      </key>",
              "      <value>",
              "        <int>78</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Rahoitusmalliala, yo 2017-2020</string>",
              "      </key>",
              "      <value>",
              "        <int>79</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj. rahoitusmalliala yo 2017-2020</string>",
              "      </key>",
              "      <value>",
              "        <int>80</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>alpa</string>",
              "      </key>",
              "      <value>",
              "        <int>81</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Koodit organisaatio</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tilastovuosi</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit kunta</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kansalaisuus</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusaste, taso 2</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusaste, taso 1</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>OKM ohjauksen ala</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusaste 2002</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Sektori</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>AVOP-YAMK Opiskelijapalaute_työelämä</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>AVOP-AMK Opiskelijapalaute_työelämä</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>AVOP-AMK pistemäärä</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Organisaatio</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit OKM ohjauksen ala</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj. koulutusaste, taso 1</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj. koulutusaste, taso 2</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj. OKM ohjauksen ala</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>AMK Julkaisut (A-E)</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>AMK julkaisut (F ja I)</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusala, taso 1</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusala, taso 2</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusala, taso 3</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kunta</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tutkinnot</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Yo 7v aloittaneet lkm</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>5v_Aloittaneet_lkm</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>7v_suorittaneet_lkm</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>5v_suorittaneet_lkm</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>55op suorittaneet</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>1-14op suorittaneet</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kandikyselyn pistemäärä</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Työttömät 3v (ver2, 12)</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Työlliset 3v (ver2 10,13)</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>YO Julkaisut (A1-A4, C1 ja C2) jufotaso 2 ja 3</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>YO Julkaisut (A1-A4, C1 ja C2) jufotaso 1-3</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Työlliset 3v tutkinnon jälkeen</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kilpailtu tutkimusrahoitus</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>kv_vaihtoopiskelijat_op_lkm</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ulkom_hyv_luetut_op_lkm</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>erilopintooik_op_lkm</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>avoinamk_op_amk_lkm</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>mamu_op_lkm</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>erikoul_suor_op_lkm</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>sijoittuminen_1v_tutkinnon_jalkeen</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>työlliset 1v tutkinnon jälkeen</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>YO kansainvälinen yhteisjulkaisu (A1-A4, C1 ja C2) jufotaso 1-3</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ammattikorkeakoulun TKI-henkilökunta</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ammattikorkeakoulun opetushenkilökunta</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Rahoitusmalliala, amk</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj. rahoitusmalliala yo 2021-2024</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>IV tutkijanuraportaan henkilötyövuodet</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tieteenala</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tutkijanuravaihe</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>YO Julkaisut (A1-A4, C1) jufotaso 1-3</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>sijoittuminen_3v_tutkinnon_jalkeen</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Yliopiston opetus- ja tutkimushenkilötyövuodet</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Läsnäolleet opiskelijat (1-14op)</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Läsnäolevat opiskelijat (55op)</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ensisijainen hakija</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Paikan vastaanottaneet</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj. rahoitusmalliala amk</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Rahoitusmalliala, yo 2021-2024</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj. paatieteenala</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj. tieteenala</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>JulkaisuID</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Jufotaso</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kilpailtu tutkimusrahoitus (SA,Tekes, EU-puiteohjelma)</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusnimike</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit Koulutusnimike</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Päätieteenala</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tieteenala_avain</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Aloituslukuvuosi (läpäisy)</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tutkinnon aloitussykli</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Osallistuminen huippuyksik.</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Akatemia profesuurit</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>erc,stg,cog ja adg</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Opiskelijat</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Opiskelijat_fte</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Opiskelijat_lasna</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>toimipiste_id</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>hakukohde_id</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Rahoitusmalliala, yo 2017-2020</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj. rahoitusmalliala yo 2017-2020</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>alpa</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter>",
              "    <item>",
              "      <key>",
              "        <string>Organisaatio</string>",
              "      </key>",
              "      <value>",
              "        <FilterExpression xsi:type=\"ConditionalExpression\">",
              "          <Operator>NotContains</Operator>",
              "          <Value xsi:type=\"xsd:string\">Poliisi</Value>",
              "        </FilterExpression>",
              "      </value>",
              "    </item>",
              "  </ColumnFilter>",
              "  <SelectionFilter>",
              "    <item>",
              "      <key>",
              "        <string>Organisaatio</string>",
              "      </key>",
              "      <value>",
              "        <SelectionFilter xsi:nil=\"true\" />",
              "      </value>",
              "    </item>",
              "  </SelectionFilter>",
              "  <FilterParameters>",
              "    <item>",
              "      <key>",
              "        <string>Organisaatio</string>",
              "      </key>",
              "      <value>",
              "        <CommandParameters />",
              "      </value>",
              "    </item>",
              "  </FilterParameters>",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Org_TA jufo",
        "isHidden": true,
        "columns": [
          {
            "type": "calculated",
            "name": "org_TA-avain",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "[Organisaatio koodi]&\"_\"&[Tieteenala_avain]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Tieteenala_avain",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Muuttujat[Tieteenala_avain]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Organisaatio koodi",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Muuttujat[Organisaatio koodi]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "eka_juf15-17",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[eka_juf15-17]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "eka_juf14-16",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[eka_juf14-16]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "CALCULATETABLE(",
                "\tSUMMARIZE(Muuttujat,Muuttujat[Organisaatio koodi],Muuttujat[Tieteenala_avain],",
                "\t\"eka_juf15-17\",CALCULATE(Muuttujat[eka_laskentaan(jufo)],FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]>2014&&Muuttujat[Tilastovuosi]<2018)),",
                "\t\"eka_juf14-16\",CALCULATE(Muuttujat[eka_laskentaan(jufo)],FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]>2013&&Muuttujat[Tilastovuosi]<2017))),",
                "\tNOT(ISBLANK(Muuttujat[Tieteenala_avain])),",
                "\tMuuttujat[Sektori]=\"Yliopisto\",",
                "\tALL(Muuttujat[Organisaatio]),",
                "\tNOT(ISBLANK(Muuttujat[YO Julkaisut (A1-A4, C1) jufotaso 1-3])))"
              ]
            }
          }
        ]
      },
      {
        "name": "Tieteenala jufo",
        "isHidden": true,
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Tieteenala_avain",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Muuttujat[Tieteenala_avain]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "toka_juf15-17",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[toka_juf15-17]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "toka_juf14-16",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[toka_juf14-16]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "CALCULATETABLE(",
                "\tSUMMARIZE(Muuttujat,Muuttujat[Tieteenala_avain],",
                "\t\"toka_juf15-17\",CALCULATE(Muuttujat[toka_laskentaan (jufo)],FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]>2014&&Muuttujat[Tilastovuosi]<2018)),",
                "\t\"toka_juf14-16\",CALCULATE(Muuttujat[toka_laskentaan (jufo)],FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]>2013&&Muuttujat[Tilastovuosi]<2017))),",
                "\tNOT(ISBLANK(Muuttujat[Tieteenala_avain])),",
                "\tMuuttujat[Sektori]=\"Yliopisto\",",
                "\tALL(Muuttujat[Organisaatio]),",
                "\tNOT(ISBLANK(Muuttujat[YO Julkaisut (A1-A4, C1) jufotaso 1-3])))",
                ""
              ]
            }
          }
        ]
      },
      {
        "name": "Org_tohtorit",
        "isHidden": true,
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Tohtorit calc",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Tohtorit calc]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Tieteenala_avain",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Muuttujat[Tieteenala_avain]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Koodit organisaatio",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Muuttujat[Koodit organisaatio]"
          },
          {
            "type": "calculated",
            "name": "Org_TA-avain",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "[Koodit organisaatio]&\"_\"&[Tieteenala_avain]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "CALCULATETABLE(SUMMARIZE(Muuttujat,muuttujat[Koodit organisaatio],Muuttujat[Tieteenala_avain],\"Tohtorit calc\",",
                "\tCALCULATE(SUM(Muuttujat[tutkinnot]),FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]>2014&&Muuttujat[Tilastovuosi]<2018),Muuttujat[Koulutusaste, taso 2]=\"Tohtorintutkinto\")))"
              ]
            }
          }
        ]
      },
      {
        "name": "Org_IV",
        "isHidden": true,
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "IV 2016 calc",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[IV 2016 calc]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "IV 2017 calc",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[IV 2017 calc]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Organisaatio koodi",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Muuttujat[Organisaatio koodi]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Tieteenala_avain",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Muuttujat[Tieteenala_avain]"
          },
          {
            "type": "calculated",
            "name": "Org_TA-avain",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "Org_IV[Organisaatio koodi]&\"_\"&Org_IV[Tieteenala_avain]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": "CALCULATETABLE(SUMMARIZE(Muuttujat,Muuttujat[Organisaatio koodi],Muuttujat[Tieteenala_avain],\"IV 2016 calc\",[IV portaan HTV 2016_vanha],\"IV 2017 calc\",[IV portaan HTV 2017_vanha]),Muuttujat[Sektori]=\"Yliopisto\",NOT(ISBLANK(Muuttujat[IV tutkijanuraportaan henkilötyövuodet])),FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]>2015&&Muuttujat[Tilastovuosi]<2018))"
            }
          }
        ]
      },
      {
        "name": "TA_IV",
        "isHidden": true,
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Tieteenala_avain",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Muuttujat[Tieteenala_avain]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "IV 2016 calc",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[IV 2016 calc]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "IV 2017 calc",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[IV 2017 calc]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "CALCULATETABLE(SUMMARIZE(Muuttujat,Muuttujat[Tieteenala_avain],\"IV 2016 calc\",[IV portaan HTV 2016_vanha],\"IV 2017 calc\",[IV portaan HTV 2017_vanha]),",
                "Muuttujat[Sektori]=\"Yliopisto\",",
                "NOT(ISBLANK(Muuttujat[IV tutkijanuraportaan henkilötyövuodet])),",
                "NOT(ISBLANK(Muuttujat[Tieteenala_avain])),",
                "FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]>2015&&Muuttujat[Tilastovuosi]<2018))"
              ]
            }
          }
        ]
      },
      {
        "name": "Org_kilprah",
        "isHidden": true,
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Organisaatio koodi",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Muuttujat[Organisaatio koodi]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Tieteenala_avain",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Muuttujat[Tieteenala_avain]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "kilp_rah 2017 calc",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[kilp_rah 2017 calc]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "kilp_rah 2016 calc",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[kilp_rah 2016 calc]"
          },
          {
            "type": "calculated",
            "name": "Org_TA-avain",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "'Org_kilprah'[Organisaatio koodi]&\"_\"&'Org_kilprah'[Tieteenala_avain]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "CALCULATETABLE(SUMMARIZE(Muuttujat,Muuttujat[Organisaatio koodi],Muuttujat[Tieteenala_avain],",
                "\t\"kilp_rah 2017 calc\",CALCULATE([Kilpailtu tki-rahoitus (SA,Tekes, EU-puite)],",
                "\t\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2017)),",
                "\t\"kilp_rah 2016 calc\", CALCULATE([Kilpailtu tki-rahoitus (SA,Tekes, EU-puite)],",
                "\t\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2016))),",
                "NOT(ISBLANK(Muuttujat[Tieteenala_avain])),",
                "FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]>2015&&Muuttujat[Tilastovuosi]<2018),",
                "Muuttujat[Sektori]=\"Yliopisto\")"
              ]
            }
          }
        ]
      },
      {
        "name": "TA_kilprah",
        "isHidden": true,
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Tieteenala_avain",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Muuttujat[Tieteenala_avain]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "kilp_rah 2017 calc",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[kilp_rah 2017 calc]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "kilp_rah 2016 calc",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[kilp_rah 2016 calc]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "CALCULATETABLE(SUMMARIZE(Muuttujat,Muuttujat[Tieteenala_avain],",
                "\t\"kilp_rah 2017 calc\",CALCULATE([Kilpailtu tki-rahoitus (SA,Tekes, EU-puite)],",
                "\t\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2017)),",
                "\t\"kilp_rah 2016 calc\", CALCULATE([Kilpailtu tki-rahoitus (SA,Tekes, EU-puite)],",
                "\t\tFILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2016))),",
                "NOT(ISBLANK(Muuttujat[Tieteenala_avain])),",
                "FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]>2015&&Muuttujat[Tilastovuosi]<2018),",
                "Muuttujat[Sektori]=\"Yliopisto\")",
                ""
              ]
            }
          }
        ]
      },
      {
        "name": "ORG_lisa",
        "isHidden": true,
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Koodit organisaatio",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Muuttujat[Koodit organisaatio]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Tieteenala_avain",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Muuttujat[Tieteenala_avain]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "osallistumiset calc",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[osallistumiset calc]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "SA prof calc",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[SA prof calc]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "erc calc",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[erc calc]"
          },
          {
            "type": "calculated",
            "name": "ORG_TA-avain",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "[Koodit organisaatio]&\"_\"&'ORG_lisa'[Tieteenala_avain]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "CALCULATETABLE(SUMMARIZE(Muuttujat,muuttujat[Koodit organisaatio],Muuttujat[Tieteenala_avain],\"osallistumiset calc\",[Osallistumiset huippuyksiköissä 2014-2019 ja 2018-2025_pohja],\"SA prof calc\",[Akatemiaprofessori-myönnöt 2013-2016_pohja],\"erc calc\",[ERC StG, CoG ja AdG -myönnöt 2015-2017 hauissa_pohja]))",
                ""
              ]
            }
          }
        ]
      },
      {
        "name": "calc_amk_htv",
        "isHidden": true,
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Organisaatio",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Muuttujat[Organisaatio]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Organisaatio koodi",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Muuttujat[Organisaatio koodi]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "calc_amk_TKI_htv 2017",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[calc_amk_TKI_htv 2017]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "calc_amk_opetus_htv_2017",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[calc_amk_opetus_htv_2017]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "calc_amk_TKI_htv 2016",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[calc_amk_TKI_htv 2016]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "calc_amk_opetus_htv_2016",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[calc_amk_opetus_htv_2016]"
          },
          {
            "type": "calculated",
            "name": "Org_OA",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "'calc_amk_htv'[Organisaatio koodi]&\"_\"&'calc_amk_htv'[Koodit OKM ohjauksen ala]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Koodit OKM ohjauksen ala",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Muuttujat[Koodit OKM ohjauksen ala]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "SUMMARIZE(FILTER(Muuttujat,Muuttujat[Sektori]=\"Ammattikorkeakoulu\"),Muuttujat[Organisaatio],Muuttujat[Organisaatio koodi],Muuttujat[Koodit OKM ohjauksen ala],",
                "\"calc_amk_TKI_htv 2017\",CALCULATE(SUM(Muuttujat[Ammattikorkeakoulun TKI-henkilökunta]),FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2017)),",
                "\"calc_amk_opetus_htv_2017\",CALCULATE(SUM(Muuttujat[Ammattikorkeakoulun opetushenkilökunta]),FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2017)),",
                "\"calc_amk_TKI_htv 2016\",CALCULATE(SUM(Muuttujat[Ammattikorkeakoulun TKI-henkilökunta]),FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2016)),",
                "\"calc_amk_opetus_htv_2016\",CALCULATE(SUM(Muuttujat[Ammattikorkeakoulun opetushenkilökunta]),FILTER(VALUES(Muuttujat[Tilastovuosi]),Muuttujat[Tilastovuosi]=2016))",
                "",
                ")"
              ]
            }
          }
        ]
      },
      {
        "name": "calc_amk_julk",
        "isHidden": true,
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Organisaatio",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Muuttujat[Organisaatio]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Organisaatio koodi",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Muuttujat[Organisaatio koodi]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Koodit OKM ohjauksen ala",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Muuttujat[Koodit OKM ohjauksen ala]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "calc_amk_julk_2016",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[calc_amk_julk_2016]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "calc_amk_julk_2017",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[calc_amk_julk_2017]"
          },
          {
            "type": "calculated",
            "name": "Org_OA",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "'calc_amk_julk'[Organisaatio koodi]&\"_\"&'calc_amk_julk'[Koodit OKM ohjauksen ala]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "calc_amk_julk_2016-2017",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[calc_amk_julk_2016-2017]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "SUMMARIZE(FILTER(Muuttujat,Muuttujat[Sektori]=\"Ammattikorkeakoulu\"),Muuttujat[Organisaatio],Muuttujat[Organisaatio koodi],Muuttujat[Koodit OKM ohjauksen ala],",
                "\"calc_amk_julk_2016-2017\",[AMK julkaisut (A-E) 2016-2017],",
                "\"calc_amk_julk_2016\",CALCULATE(SUM(Muuttujat[AMK Julkaisut (A-E)]),Muuttujat[Tilastovuosi]=2016),",
                "\"calc_amk_julk_2017\",CALCULATE(SUM(Muuttujat[AMK Julkaisut (A-E)]),Muuttujat[Tilastovuosi]=2017))"
              ]
            }
          }
        ]
      },
      {
        "name": "Aloituspaikat",
        "isHidden": true,
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "alpa",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Muuttujat[alpa]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "alpa_key",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Muuttujat[alpa_key]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": "CALCULATETABLE(SUMMARIZE(Muuttujat, Muuttujat[alpa_key], Muuttujat[alpa]))"
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "4e8efa6b-3378-4cce-a603-f46c2513eaef",
        "fromTable": "Org_TA jufo",
        "fromColumn": "Tieteenala_avain",
        "toTable": "Tieteenala jufo",
        "toColumn": "Tieteenala_avain",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "22cab35f-a2d0-49b4-9f54-ba4e4c86b094",
        "fromTable": "Muuttujat",
        "fromColumn": "Tieteenala_avain",
        "toTable": "TA_IV",
        "toColumn": "Tieteenala_avain",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "77299eb2-02ca-45ec-8e6a-604ff119d3ce",
        "fromTable": "Muuttujat",
        "fromColumn": "org_TA-avain",
        "toTable": "Org_kilprah",
        "toColumn": "Org_TA-avain",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "e4a69b2a-e508-49f3-b746-8eff932c26e3",
        "fromTable": "Muuttujat",
        "fromColumn": "Tieteenala_avain",
        "toTable": "TA_kilprah",
        "toColumn": "Tieteenala_avain",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "622721ed-8380-498c-a30e-55e191b53ed1",
        "fromTable": "Muuttujat",
        "fromColumn": "org_TA-avain",
        "toTable": "Org_TA jufo",
        "toColumn": "org_TA-avain",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "74029561-8bee-4815-bbfa-66ea828e734b",
        "fromTable": "Muuttujat",
        "fromColumn": "org_TA-avain",
        "toTable": "ORG_lisa",
        "toColumn": "ORG_TA-avain",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "e9c39900-bfa6-4f39-9c24-d97b00d3d1e3",
        "fromTable": "Muuttujat",
        "fromColumn": "org_TA-avain",
        "toTable": "Org_IV",
        "toColumn": "Org_TA-avain",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "47f43858-9cea-41b6-b98d-e286270c456a",
        "fromTable": "Muuttujat",
        "fromColumn": "Org_OA",
        "toTable": "calc_amk_htv",
        "toColumn": "Org_OA",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "1804b704-aeab-4402-8add-65e348da2a4f",
        "fromTable": "Muuttujat",
        "fromColumn": "Org_OA",
        "toTable": "calc_amk_julk",
        "toColumn": "Org_OA",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "0eb16a04-0194-4df4-8d45-261feea392c3",
        "fromTable": "Muuttujat",
        "fromColumn": "org_TA-avain",
        "toTable": "Org_tohtorit",
        "toColumn": "Org_TA-avain",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "7a10dad8-fdc2-46ca-8de1-5a69d5674864",
        "fromTable": "Muuttujat",
        "fromColumn": "alpa_key",
        "toTable": "Aloituspaikat",
        "toColumn": "alpa_key",
        "crossFilteringBehavior": "bothDirections"
      }
    ],
    "perspectives": [
      {
        "name": "rakenteellinen_kehittaminen_YO",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Koulutusnimike"
              },
              {
                "name": "Organisaatio"
              },
              {
                "name": "Tieteenala"
              }
            ],
            "measures": [
              {
                "name": "Akatemiaprofessori-myönnöt 2013-2016"
              },
              {
                "name": "ERC StG, CoG ja AdG -myönnöt 2015-2017 hauissa"
              },
              {
                "name": "IV portaan HTV 2017"
              },
              {
                "name": "IV portaan HTV osuus 2017"
              },
              {
                "name": "IV portaan HTV osuus 2017 (tieteenala)"
              },
              {
                "name": "Jufo suht (1-3, A1-A4, C1) 2014-2016"
              },
              {
                "name": "Jufo suht (1-3, A1-A4, C1) 2014-2016 (Tieteenala)"
              },
              {
                "name": "Osallistumiset huippuyksiköissä 2014-2019 ja 2018-2025"
              },
              {
                "name": "Osuus kilpaillusta tutkimusrahoituksesta 2016"
              },
              {
                "name": "Osuus kilpaillusta tutkimusrahoituksesta 2016 (Tieteenala, SA,TEKES, EU-puite)"
              },
              {
                "name": "Osuus ylemmistä kk-tutkinnoista 2015-2017"
              },
              {
                "name": "Tohtorin tutkinnot (tieteenala) 2015-2017 KA"
              },
              {
                "name": "Työllistyminen 3v, (RAKE, ykk) KA 2014-2016"
              },
              {
                "name": "Vetovoima 2017 (I sykli)"
              },
              {
                "name": "Ylemmät kk-tutkinnot 2015-2017 KA"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "rakenteellinen_kehittaminen_AMK",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Koulutusnimike"
              },
              {
                "name": "OKM ohjauksen ala"
              },
              {
                "name": "Organisaatio"
              },
              {
                "name": "Rahoitusmalliala, amk"
              }
            ],
            "measures": [
              {
                "name": "Amk opetuksen henkilötyövuodet 2016"
              },
              {
                "name": "Amk opetuksen henkilötyövuodet 2017"
              },
              {
                "name": "Amk tki-henkilötyövuodet 2016"
              },
              {
                "name": "Amk tki-henkilötyövuodet 2017"
              },
              {
                "name": "AMK tutkinnot 2014-2016 KA"
              },
              {
                "name": "AMK tutkinnot 2015-2017 KA"
              },
              {
                "name": "AVOP-AMK työelämävalmiudet KA 2016"
              },
              {
                "name": "AVOP-AMK työelämävalmiudet KA 2017"
              },
              {
                "name": "Osuus alan AMK-tutkinnoista 2015-2017"
              },
              {
                "name": "Työllisten osuus 1v valmistumisesta 2013-2015 (RAKE, amk-tutkinto)"
              },
              {
                "name": "Työllisten osuus 1v valmistumisesta 2014-2016 (RAKE, amk-tutkinto)"
              },
              {
                "name": "Ulkomaalaisten AMK-tutkintojen osuus 2014-2016"
              },
              {
                "name": "Ulkomaalaisten AMK-tutkintojen osuus 2015-2017"
              },
              {
                "name": "Vetovoima 2016 (I sykli, amk)"
              },
              {
                "name": "Vetovoima 2017 (I sykli, amk)"
              },
              {
                "name": "Vetovoima 2018 (I sykli, amk)"
              },
              {
                "name": "AMK julkaisut 2016-2017 KA"
              }
            ]
          }
        ]
      },
      {
        "name": "rakenteellinen_kehittaminen_YAMK",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Koulutusnimike"
              },
              {
                "name": "OKM ohjauksen ala"
              },
              {
                "name": "Organisaatio"
              },
              {
                "name": "Rahoitusmalliala, amk"
              }
            ],
            "measures": [
              {
                "name": "Ulkomaalaisten YAMK-tutkintojen osuus 2014-2016"
              },
              {
                "name": "Ulkomaalaisten YAMK-tutkintojen osuus 2015-2017"
              },
              {
                "name": "Vetovoima 2016 (II sykli, yamk)"
              },
              {
                "name": "Vetovoima 2017 (II sykli, yamk)"
              },
              {
                "name": "Vetovoima 2018 (II sykli, yamk)"
              },
              {
                "name": "YAMK tutkinnot 2014-2016 KA"
              },
              {
                "name": "YAMK tutkinnot 2015-2017 KA"
              },
              {
                "name": "YAMK-tutkintojen osuus 2014-2016"
              },
              {
                "name": "YAMK-tutkintojen osuus 2015-2017"
              },
              {
                "name": "Työllisten osuus 1v valmistumisesta 2013-2015 (RAKE, yamk-tutkinto)"
              },
              {
                "name": "Työllisten osuus 1v valmistumisesta 2014-2016 (RAKE, yamk-tutkinto)"
              }
            ]
          }
        ]
      }
    ],
    "roles": [
      {
        "name": "Luku",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "DWI\\P_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1733"
          },
          {
            "memberName": "DWI\\T_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1732"
          },
          {
            "memberName": "DWI\\Z_P_Antero_Full_Read_TAB",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-2272"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "400"
      },
      {
        "name": "TabularEditor_SerializeOptions",
        "value": "{\"IgnoreInferredObjects\":true,\"IgnoreInferredProperties\":true,\"IgnoreTimestamps\":true,\"SplitMultilineStrings\":true,\"PrefixFilenames\":false,\"LocalTranslations\":false,\"LocalPerspectives\":false,\"Levels\":[]}"
      }
    ]
  },
  "id": "SemanticModel"
}
