{
  "name": "SemanticModel",
  "compatibilityLevel": 1200,
  "model": {
    "culture": "fi-FI",
    "dataSources": [
      {
        "name": "dwitvipusql22",
        "connectionString": "Provider=SQLNCLI11;Data Source=dwitvipusql22;Integrated Security=SSPI;Persist Security Info=false;Initial Catalog=ANTERO",
        "impersonationMode": "impersonateAccount",
        "account": "dwi\\T_VIPUTK_KUUTIO",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "v_amos_rahoitus_kriteerit",
        "columns": [
          {
            "name": "ytunnus",
            "dataType": "string",
            "sourceColumn": "ytunnus",
            "sourceProviderType": "WChar"
          },
          {
            "name": "poistuva_ytunnus",
            "dataType": "string",
            "sourceColumn": "poistuva_ytunnus"
          },
          {
            "name": "ta_ensikertainen_suoritepaatos",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ta_ensikertainen_suoritepaatos"
          },
          {
            "name": "ta_lisasuoritepaatos",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ta_lisasuoritepaatos"
          },
          {
            "name": "ta_paatokset_yhteensa",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ta_paatokset_yhteensa"
          },
          {
            "name": "ltae_mukaiset_paatokset",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ltae_mukaiset_paatokset"
          },
          {
            "name": "ltae2_mukaiset_paatokset",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ltae2_mukaiset_paatokset"
          },
          {
            "name": "ltae_mukaiset_paatokset_yhteensa",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ltae_mukaiset_paatokset_yhteensa"
          },
          {
            "name": "paatokset_yhteensa",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "paatokset_yhteensa"
          },
          {
            "name": "sp_lisays_kohdentamaton_jarj_esitys",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "sp_lisays_kohdentamaton_jarj_esitys"
          },
          {
            "name": "sp_lisays_kohdentamaton_okm_paatos",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "sp_lisays_kohdentamaton_okm_paatos"
          },
          {
            "name": "sp_lisays_kohdentamaton_tyovkoul_jarj_esitys",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "sp_lisays_kohdentamaton_tyovkoul_jarj_esitys"
          },
          {
            "name": "sp_lisays_kohdentamaton_tyovkoul_okm_paatos",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "sp_lisays_kohdentamaton_tyovkoul_okm_paatos"
          },
          {
            "name": "sp_lisays_kohdennettu_krit1_jarj_esitys",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "sp_lisays_kohdennettu_krit1_jarj_esitys"
          },
          {
            "name": "sp_lisays_kohdennettu_krit1_okm_paatos",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "sp_lisays_kohdennettu_krit1_okm_paatos"
          },
          {
            "name": "sp_lisays_kohdennettu_tyovkoul_krit1_jarj_esitys",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "sp_lisays_kohdennettu_tyovkoul_krit1_jarj_esitys"
          },
          {
            "name": "sp_lisays_kohdennettu_tyovkoul_krit1_okm_paatos",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "sp_lisays_kohdennettu_tyovkoul_krit1_okm_paatos"
          },
          {
            "name": "sp_lisays_kohdennettu_krit2_jarj_esitys",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "sp_lisays_kohdennettu_krit2_jarj_esitys"
          },
          {
            "name": "sp_lisays_kohdennettu_krit2_okm_paatos",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "sp_lisays_kohdennettu_krit2_okm_paatos"
          },
          {
            "name": "sp_lisays_kohdennettu_tyovkoul_krit2_jarj_esitys",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "sp_lisays_kohdennettu_tyovkoul_krit2_jarj_esitys"
          },
          {
            "name": "sp_lisays_kohdennettu_tyovkoul_krit2_okm_paatos",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "sp_lisays_kohdennettu_tyovkoul_krit2_okm_paatos"
          },
          {
            "name": "sp_lisays_kohdennettu_krit3_jarj_esitys",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "sp_lisays_kohdennettu_krit3_jarj_esitys"
          },
          {
            "name": "sp_lisays_kohdennettu_krit3_okm_paatos",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "sp_lisays_kohdennettu_krit3_okm_paatos"
          },
          {
            "name": "sp_lisays_kohdennettu_tyovkoul_krit3_jarj_esitys",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "sp_lisays_kohdennettu_tyovkoul_krit3_jarj_esitys"
          },
          {
            "name": "sp_lisays_kohdennettu_tyovkoul_krit3_okm_paatos",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "sp_lisays_kohdennettu_tyovkoul_krit3_okm_paatos"
          },
          {
            "name": "sp_lisays_kohdennettu_krit4_jarj_esitys",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "sp_lisays_kohdennettu_krit4_jarj_esitys"
          },
          {
            "name": "sp_lisays_kohdennettu_krit4_okm_paatos",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "sp_lisays_kohdennettu_krit4_okm_paatos"
          },
          {
            "name": "sp_lisays_kohdennettu_tyovkoul_krit4_jarj_esitys",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "sp_lisays_kohdennettu_tyovkoul_krit4_jarj_esitys"
          },
          {
            "name": "sp_lisays_kohdennettu_tyovkoul_krit4_okm_paatos",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "sp_lisays_kohdennettu_tyovkoul_krit4_okm_paatos"
          },
          {
            "name": "ta_ensikertainen_suoritepaatos_harkv_korotus",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ta_ensikertainen_suoritepaatos_harkv_korotus"
          },
          {
            "name": "ta_lisasuoritepaatos_harkv_korotus",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ta_lisasuoritepaatos_harkv_korotus"
          },
          {
            "name": "harkv_korotus_syy1_hakemus",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "harkv_korotus_syy1_hakemus"
          },
          {
            "name": "harkv_korotus_syy1_paatos",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "harkv_korotus_syy1_paatos"
          },
          {
            "name": "harkv_korotus_syy2_hakemus",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "harkv_korotus_syy2_hakemus"
          },
          {
            "name": "harkv_korotus_syy2_paatos",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "harkv_korotus_syy2_paatos"
          },
          {
            "name": "harkv_korotus_syy3_hakemus",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "harkv_korotus_syy3_hakemus"
          },
          {
            "name": "harkv_korotus_syy3_paatos",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "harkv_korotus_syy3_paatos"
          },
          {
            "name": "harkv_korotus_syy4_hakemus",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "harkv_korotus_syy4_hakemus"
          },
          {
            "name": "harkv_korotus_syy4_paatos",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "harkv_korotus_syy4_paatos"
          },
          {
            "name": "vos_ta_mukainen",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "vos_ta_mukainen"
          },
          {
            "name": "vos_ta_mukainen_sis_alv",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "vos_ta_mukainen_sis_alv"
          },
          {
            "name": "vos_ta_ja_ltae_mukainen",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "vos_ta_ja_ltae_mukainen"
          },
          {
            "name": "vos_ta_ja_ltae_mukainen_sis_alv",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "vos_ta_ja_ltae_mukainen_sis_alv"
          },
          {
            "name": "vos_ta_ja_ltae_mukainen_vertailu",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "vos_ta_ja_ltae_mukainen_vertailu"
          },
          {
            "name": "vos_ta_ja_ltae_mukainen_vertailu_sis_alv",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "vos_ta_ja_ltae_mukainen_vertailu_sis_alv"
          },
          {
            "name": "ensikertainen_sp_suoritusrahoitus",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ensikertainen_sp_suoritusrahoitus"
          },
          {
            "name": "ensikertainen_sp_tyovoimakoulutus",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ensikertainen_sp_tyovoimakoulutus"
          },
          {
            "name": "ltae_mukaiset_paatokset_ed_vuosi",
            "dataType": "double",
            "sourceColumn": "ltae_mukaiset_paatokset_ed_vuosi"
          },
          {
            "name": "jarj_luvan_opiskelijavuodet",
            "dataType": "double",
            "sourceColumn": "jarj_luvan_opiskelijavuodet"
          },
          {
            "name": "profiilikerroin_korjattu",
            "dataType": "double",
            "sourceColumn": "profiilikerroin_korjattu"
          }
        ],
        "partitions": [
          {
            "name": "v_amos_rahoitus",
            "dataView": "full",
            "source": {
              "query": "select * from [dw].[v_amos_rahoitus_kriteerit]",
              "dataSource": "dwitvipusql22"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>select * from [dw].[v_amos_rahoitus_kriteerit]</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "vos_ta_mukainen_a",
            "expression": "sum([vos_ta_mukainen])"
          },
          {
            "name": "ta_lisasuoritepaatos_a",
            "expression": "sum([ta_lisasuoritepaatos])"
          },
          {
            "name": "ltae_mukaiset_paatokset_a",
            "expression": "sum([ltae_mukaiset_paatokset])"
          },
          {
            "name": "ltae2_mukaiset_paatokset_a",
            "expression": "sum([ltae2_mukaiset_paatokset])"
          },
          {
            "name": "ltae_mukaiset_paatokset_yhteensa_a",
            "expression": "sum([ltae_mukaiset_paatokset_yhteensa])"
          },
          {
            "name": "ta_paatokset_yhteensa_a",
            "expression": "sum([ta_paatokset_yhteensa])"
          },
          {
            "name": "paatokset_yhteensa_a",
            "expression": "SUM([paatokset_yhteensa])"
          },
          {
            "name": "sp_lisays_kohdennettu_krit1_jarj_esitys_a",
            "expression": "SUM([sp_lisays_kohdennettu_krit1_jarj_esitys])"
          },
          {
            "name": "sp_lisays_kohdennettu_krit1_okm_paatos_a",
            "expression": "SUM([sp_lisays_kohdennettu_krit1_okm_paatos])"
          },
          {
            "name": "sp_lisays_kohdennettu_krit2_okm_paatos_a",
            "expression": "SUM([sp_lisays_kohdennettu_krit2_okm_paatos])"
          },
          {
            "name": "sp_lisays_kohdennettu_krit3_jarj_esitys_a",
            "expression": "SUM([sp_lisays_kohdennettu_krit3_jarj_esitys])"
          },
          {
            "name": "sp_lisays_kohdennettu_krit3_okm_paatos_a",
            "expression": "SUM([sp_lisays_kohdennettu_krit3_okm_paatos])"
          },
          {
            "name": "sp_lisays_kohdennettu_krit4_jarj_esitys_a",
            "expression": "SUM([sp_lisays_kohdennettu_krit4_jarj_esitys])"
          },
          {
            "name": "sp_lisays_kohdennettu_krit4_okm_paatos_a",
            "expression": "SUM([sp_lisays_kohdennettu_krit4_okm_paatos])"
          },
          {
            "name": "sp_lisays_kohdennettu_tyovkoul_krit1_jarj_esitys_a",
            "expression": "SUM([sp_lisays_kohdennettu_tyovkoul_krit1_jarj_esitys])"
          },
          {
            "name": "sp_lisays_kohdennettu_tyovkoul_krit1_okm_paatos_a",
            "expression": "SUM([sp_lisays_kohdennettu_tyovkoul_krit1_okm_paatos])"
          },
          {
            "name": "sp_lisays_kohdennettu_tyovkoul_krit2_jarj_esitys_a",
            "expression": "SUM([sp_lisays_kohdennettu_tyovkoul_krit2_jarj_esitys])"
          },
          {
            "name": "sp_lisays_kohdennettu_tyovkoul_krit2_okm_paatos_a",
            "expression": "SUM([sp_lisays_kohdennettu_tyovkoul_krit2_okm_paatos])"
          },
          {
            "name": "sp_lisays_kohdennettu_tyovkoul_krit3_jarj_esitys_a",
            "expression": "SUM([sp_lisays_kohdennettu_tyovkoul_krit3_jarj_esitys])"
          },
          {
            "name": "sp_lisays_kohdennettu_tyovkoul_krit3_okm_paatos_a",
            "expression": "SUM([sp_lisays_kohdennettu_tyovkoul_krit3_okm_paatos])"
          },
          {
            "name": "sp_lisays_kohdennettu_tyovkoul_krit4_jarj_esitys_a",
            "expression": "SUM([sp_lisays_kohdennettu_tyovkoul_krit4_jarj_esitys])"
          },
          {
            "name": "sp_lisays_kohdennettu_tyovkoul_krit4_okm_paatos_a",
            "expression": "SUM([sp_lisays_kohdennettu_tyovkoul_krit4_okm_paatos])"
          },
          {
            "name": "sp_lisays_kohdentamaton_jarj_esitys_a",
            "expression": "SUM([sp_lisays_kohdentamaton_jarj_esitys])"
          },
          {
            "name": "sp_lisays_kohdentamaton_okm_paatos_a",
            "expression": "SUM([sp_lisays_kohdentamaton_okm_paatos])"
          },
          {
            "name": "sp_lisays_kohdentamaton_tyovkoul_jarj_esitys_a",
            "expression": "SUM([sp_lisays_kohdentamaton_tyovkoul_jarj_esitys])"
          },
          {
            "name": "sp_lisays_kohdentamaton_tyovkoul_okm_paatos_a",
            "expression": "SUM([sp_lisays_kohdentamaton_tyovkoul_okm_paatos])"
          },
          {
            "name": "ta_ensikertainen_suoritepaatos_a",
            "expression": "SUM([ta_ensikertainen_suoritepaatos])",
            "formatString": "0"
          },
          {
            "name": "ensikertainen_sp_suoritusrahoitus_a",
            "expression": "SUM([ensikertainen_sp_suoritusrahoitus])"
          },
          {
            "name": "ensikertainen_sp_tyovoimakoulutus_a",
            "expression": "SUM([ensikertainen_sp_tyovoimakoulutus])"
          },
          {
            "name": "harkv_korotus_syy1_hakemus_a",
            "expression": "SUM([harkv_korotus_syy1_hakemus])"
          },
          {
            "name": "harkv_korotus_syy1_paatos_a",
            "expression": "SUM([harkv_korotus_syy1_paatos])"
          },
          {
            "name": "harkv_korotus_syy2_hakemus_a",
            "expression": "SUM([harkv_korotus_syy2_hakemus])"
          },
          {
            "name": "harkv_korotus_syy2_paatos_a",
            "expression": "SUM([harkv_korotus_syy2_paatos])"
          },
          {
            "name": "harkv_korotus_syy3_hakemus_a",
            "expression": "SUM([harkv_korotus_syy3_hakemus])"
          },
          {
            "name": "harkv_korotus_syy3_paatos_a",
            "expression": "SUM([harkv_korotus_syy3_paatos])"
          },
          {
            "name": "harkv_korotus_syy4_hakemus_a",
            "expression": "SUM([harkv_korotus_syy4_hakemus])"
          },
          {
            "name": "harkv_korotus_syy4_paatos_a",
            "expression": "SUM([harkv_korotus_syy4_paatos])"
          },
          {
            "name": "sp_lisays_kohdennettu_krit2_jarj_esitys_a",
            "expression": "SUM([sp_lisays_kohdennettu_krit2_jarj_esitys])"
          },
          {
            "name": "ta_ensikertainen_suoritepaatos_harkv_korotus_a",
            "expression": "sum([ta_ensikertainen_suoritepaatos_harkv_korotus])"
          },
          {
            "name": "ta_lisasuoritepaatos_harkv_korotus_a",
            "expression": "sum([ta_lisasuoritepaatos_harkv_korotus])"
          },
          {
            "name": "vos_ta_ja_ltae_mukainen_a",
            "expression": "sum([vos_ta_ja_ltae_mukainen])"
          },
          {
            "name": "vos_ta_ja_ltae_mukainen_sis_alv_a",
            "expression": "sum([vos_ta_ja_ltae_mukainen_sis_alv])"
          },
          {
            "name": "vos_ta_ja_ltae_mukainen_vertailu_a",
            "expression": "sum([vos_ta_ja_ltae_mukainen_vertailu])"
          },
          {
            "name": "vos_ta_ja_ltae_mukainen_vertailu_sis_alv_a",
            "expression": "sum([vos_ta_ja_ltae_mukainen_vertailu_sis_alv])"
          },
          {
            "name": "vos_ta_mukainen_sis_alv_a",
            "expression": "sum([vos_ta_mukainen_sis_alv])"
          },
          {
            "name": "ltae_mukaiset_paatokset_ed_vuosi_a",
            "expression": "AVERAGE([ltae_mukaiset_paatokset_ed_vuosi])"
          },
          {
            "name": "jarj_luvan_opiskelijavuodet_a",
            "expression": "sum([jarj_luvan_opiskelijavuodet])"
          },
          {
            "name": "profiilikerroin_korjattu_a",
            "expression": "average([profiilikerroin_korjattu])"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "select * from [dw].[v_amos_rahoitus_kriteerit]"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "v_amos_rahoitus"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "QueryEditorSerialization",
            "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>select * from [dw].[v_amos_rahoitus_kriteerit]</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
          }
        ]
      },
      {
        "name": "v_amos_rahoituslaskenta",
        "columns": [
          {
            "name": "Vuosi",
            "dataType": "int64",
            "sourceColumn": "Vuosi",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Vaihe",
            "dataType": "string",
            "sourceColumn": "Vaihe",
            "sourceProviderType": "Char"
          },
          {
            "name": "Koulutuksen järjestäjä",
            "dataType": "string",
            "sourceColumn": "Koulutuksen järjestäjä",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Koodit Koulutuksen järjestäjä",
            "dataType": "string",
            "sourceColumn": "Koodit Koulutuksen järjestäjä",
            "sourceProviderType": "Char"
          },
          {
            "name": "profiilikerroin",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "profiilikerroin",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "painotettu_opiskelijavuosimäärä",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "painotettu_opiskelijavuosimäärä",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "painottamaton_opiskelijavuosimaara",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "painottamaton_opiskelijavuosimaara",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "tutkintopisteiden_osuus",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "tutkintopisteiden_osuus",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "painotettu_tutkintomaara",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "painotettu_tutkintomaara",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "painottamaton_tutkintomaara",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "painottamaton_tutkintomaara",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "jarj_luvan_opiskelijavuodet",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarj_luvan_opiskelijavuodet",
            "sourceProviderType": "Integer"
          }
        ],
        "partitions": [
          {
            "name": "v_amos_rahoituslaskenta",
            "dataView": "full",
            "source": {
              "query": [
                "SELECT [dw].[v_amos_rahoituslaskenta].[Vuosi],[dw].[v_amos_rahoituslaskenta].[Vaihe],[dw].[v_amos_rahoituslaskenta].[Koulutuksen järjestäjä],[dw].[v_amos_rahoituslaskenta].[Koodit Koulutuksen järjestäjä],[dw].[v_amos_rahoituslaskenta].[profiilikerroin],[dw].[v_amos_rahoituslaskenta].[painotettu_opiskelijavuosimäärä],[dw].[v_amos_rahoituslaskenta].[painottamaton_opiskelijavuosimaara],[dw].[v_amos_rahoituslaskenta].[tutkintopisteiden_osuus],[dw].[v_amos_rahoituslaskenta].[painotettu_tutkintomaara],[dw].[v_amos_rahoituslaskenta].[painottamaton_tutkintomaara],[dw].[v_amos_rahoituslaskenta].[jarj_luvan_opiskelijavuodet] FROM [dw].[v_amos_rahoituslaskenta]",
                "where [dw].[v_amos_rahoituslaskenta].[Vuosi]>=year(getdate())-2"
              ],
              "dataSource": "dwitvipusql22"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dw].[v_amos_rahoituslaskenta].[Vuosi],[dw].[v_amos_rahoituslaskenta].[Vaihe],[dw].[v_amos_rahoituslaskenta].[Koulutuksen järjestäjä],[dw].[v_amos_rahoituslaskenta].[Koodit Koulutuksen järjestäjä],[dw].[v_amos_rahoituslaskenta].[profiilikerroin],[dw].[v_amos_rahoituslaskenta].[painotettu_opiskelijavuosimäärä],[dw].[v_amos_rahoituslaskenta].[painottamaton_opiskelijavuosimaara],[dw].[v_amos_rahoituslaskenta].[tutkintopisteiden_osuus],[dw].[v_amos_rahoituslaskenta].[painotettu_tutkintomaara],[dw].[v_amos_rahoituslaskenta].[painottamaton_tutkintomaara],[dw].[v_amos_rahoituslaskenta].[jarj_luvan_opiskelijavuodet] FROM [dw].[v_amos_rahoituslaskenta]",
                  "where [dw].[v_amos_rahoituslaskenta].[Vuosi]>=year(getdate())-2</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "profiilikerroin_a",
            "expression": "average(v_amos_rahoituslaskenta[profiilikerroin])",
            "formatString": "0.0000"
          },
          {
            "name": "painotettu_opiskelijavuosimaara_a",
            "expression": "average([painotettu_opiskelijavuosimäärä])",
            "formatString": "#,0.00"
          },
          {
            "name": "painotettu_tutkintomaara_a",
            "expression": "average([painotettu_tutkintomaara])",
            "formatString": "#,0.00"
          },
          {
            "name": "painottamaton_opiskelijavuosimaara_a",
            "expression": "average([painottamaton_opiskelijavuosimaara])",
            "formatString": "#,0.00"
          },
          {
            "name": "painottamaton_tutkintomaara_a",
            "expression": "average([painottamaton_tutkintomaara])",
            "formatString": "#,0.00"
          },
          {
            "name": "tutkintopisteiden_osuus_a",
            "expression": "average([tutkintopisteiden_osuus])"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": [
              "SELECT [dw].[v_amos_rahoituslaskenta].[Vuosi],[dw].[v_amos_rahoituslaskenta].[Vaihe],[dw].[v_amos_rahoituslaskenta].[Koulutuksen järjestäjä],[dw].[v_amos_rahoituslaskenta].[Koodit Koulutuksen järjestäjä],[dw].[v_amos_rahoituslaskenta].[profiilikerroin],[dw].[v_amos_rahoituslaskenta].[painotettu_opiskelijavuosimäärä],[dw].[v_amos_rahoituslaskenta].[painottamaton_opiskelijavuosimaara],[dw].[v_amos_rahoituslaskenta].[tutkintopisteiden_osuus],[dw].[v_amos_rahoituslaskenta].[painotettu_tutkintomaara],[dw].[v_amos_rahoituslaskenta].[painottamaton_tutkintomaara],[dw].[v_amos_rahoituslaskenta].[jarj_luvan_opiskelijavuodet] FROM [dw].[v_amos_rahoituslaskenta]",
              "where [dw].[v_amos_rahoituslaskenta].[Vuosi]>=year(getdate())-2"
            ]
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "v_amos_rahoituslaskenta"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dw"
          },
          {
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dw].[v_amos_rahoituslaskenta].[Vuosi],[dw].[v_amos_rahoituslaskenta].[Vaihe],[dw].[v_amos_rahoituslaskenta].[Koulutuksen järjestäjä],[dw].[v_amos_rahoituslaskenta].[Koodit Koulutuksen järjestäjä],[dw].[v_amos_rahoituslaskenta].[profiilikerroin],[dw].[v_amos_rahoituslaskenta].[painotettu_opiskelijavuosimäärä],[dw].[v_amos_rahoituslaskenta].[painottamaton_opiskelijavuosimaara],[dw].[v_amos_rahoituslaskenta].[tutkintopisteiden_osuus],[dw].[v_amos_rahoituslaskenta].[painotettu_tutkintomaara],[dw].[v_amos_rahoituslaskenta].[painottamaton_tutkintomaara],[dw].[v_amos_rahoituslaskenta].[jarj_luvan_opiskelijavuodet] FROM [dw].[v_amos_rahoituslaskenta]",
              "where [dw].[v_amos_rahoituslaskenta].[Vuosi]>=year(getdate())-2</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "d_amos_rajapinta_organisaatioliitokset",
        "columns": [
          {
            "name": "vanha",
            "dataType": "string",
            "sourceColumn": "vanha",
            "sourceProviderType": "Char"
          },
          {
            "name": "uusi",
            "dataType": "string",
            "sourceColumn": "uusi",
            "sourceProviderType": "Char"
          },
          {
            "name": "voimaan_alkaen",
            "dataType": "dateTime",
            "sourceColumn": "voimaan_alkaen",
            "formatString": "dd.MM.yyyy",
            "sourceProviderType": "DBDate",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1035\" Group=\"ShortDate\" FormatString=\"dd.MM.yyyy\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "kommentti",
            "dataType": "string",
            "sourceColumn": "kommentti",
            "sourceProviderType": "Char"
          },
          {
            "name": "tiedostonimi",
            "dataType": "string",
            "sourceColumn": "tiedostonimi",
            "sourceProviderType": "Char"
          },
          {
            "name": "latauspvm",
            "dataType": "dateTime",
            "sourceColumn": "latauspvm",
            "formatString": "General Date",
            "sourceProviderType": "DBDate"
          }
        ],
        "partitions": [
          {
            "name": "d_amos_organisaatioliitokset",
            "dataView": "full",
            "source": {
              "query": " SELECT [dw].[d_amos_rajapinta_organisaatioliitokset].* FROM [dw].[d_amos_rajapinta_organisaatioliitokset] ",
              "dataSource": "dwitvipusql22"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>vanha</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>81</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>uusi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>68</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>voimaan_alkaen</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>153</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>kommentti</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>115</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tiedostonimi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>126</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>latauspvm</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>111</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>vanha</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>uusi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>voimaan_alkaen</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>kommentti</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tiedostonimi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>latauspvm</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>5</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked />",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Lkm",
            "expression": "COUNTROWS(d_amos_rajapinta_organisaatioliitokset)"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dw].[d_amos_rajapinta_organisaatioliitokset].* FROM [dw].[d_amos_rajapinta_organisaatioliitokset] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "d_amos_rajapinta_organisaatioliitokset"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dw"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>vanha</string>",
              "      </key>",
              "      <value>",
              "        <int>81</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>uusi</string>",
              "      </key>",
              "      <value>",
              "        <int>68</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>voimaan_alkaen</string>",
              "      </key>",
              "      <value>",
              "        <int>153</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>kommentti</string>",
              "      </key>",
              "      <value>",
              "        <int>115</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tiedostonimi</string>",
              "      </key>",
              "      <value>",
              "        <int>126</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>latauspvm</string>",
              "      </key>",
              "      <value>",
              "        <int>111</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>vanha</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>uusi</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>voimaan_alkaen</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>kommentti</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tiedostonimi</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>latauspvm</string>",
              "      </key>",
              "      <value>",
              "        <int>5</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked />",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "d_amos_rajapinta_jakotaulu",
        "columns": [
          {
            "name": "versio",
            "dataType": "string",
            "sourceColumn": "versio",
            "sourceProviderType": "Char"
          },
          {
            "name": "kommentti",
            "dataType": "string",
            "sourceColumn": "kommentti",
            "sourceProviderType": "Char"
          },
          {
            "name": "rahoitus_mukaanlukien_alv",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "rahoitus_mukaanlukien_alv"
          },
          {
            "name": "alv",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "alv"
          },
          {
            "name": "strategiarahoitus",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "strategiarahoitus"
          },
          {
            "name": "kiky_kohdennus",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "kiky_kohdennus"
          },
          {
            "name": "jako_ja_oikaisuvara",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "jako_ja_oikaisuvara"
          },
          {
            "name": "harkinnanvarainen_perusrahoitus",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "harkinnanvarainen_perusrahoitus"
          }
        ],
        "partitions": [
          {
            "name": "d_amos_rajapinta_jakotaulu",
            "dataView": "full",
            "source": {
              "query": " SELECT [dw].[d_amos_rajapinta_jakotaulu].* FROM [dw].[d_amos_rajapinta_jakotaulu] ",
              "dataSource": "dwitvipusql22"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>strategiarahoitus</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>156</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>alv</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>59</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>rahoitus_mukaanlukien_alv</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>232</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>versio</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>81</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>kommentti</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>115</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>harkinnanvarainen_perusrahoitus</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>274</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>kiky_kohdennus</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>153</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jako_ja_oikaisuvara</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>179</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>strategiarahoitus</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>alv</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>rahoitus_mukaanlukien_alv</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>versio</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>kommentti</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>harkinnanvarainen_perusrahoitus</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>5</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>kiky_kohdennus</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>6</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jako_ja_oikaisuvara</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>7</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>rahoitus_mukaanlukien_alv</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>alv</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>strategiarahoitus</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>harkinnanvarainen_perusrahoitus</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>kiky_kohdennus</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jako_ja_oikaisuvara</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "rahoitus_mukaanlukien_alv_a",
            "expression": "AVERAGE([rahoitus_mukaanlukien_alv])"
          },
          {
            "name": "alv_a",
            "expression": "AVERAGE([alv])"
          },
          {
            "name": "jako_ja_oikaisuvara_a",
            "expression": "AVERAGE([jako_ja_oikaisuvara])"
          },
          {
            "name": "kiky_kohdennus_a",
            "expression": "AVERAGE([kiky_kohdennus])"
          },
          {
            "name": "strategiarahoitus_a",
            "expression": "AVERAGE([strategiarahoitus])"
          },
          {
            "name": "harkinnanvarainen_perusrahoitus_a",
            "expression": "AVERAGE([harkinnanvarainen_perusrahoitus])"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dw].[d_amos_rajapinta_jakotaulu].* FROM [dw].[d_amos_rajapinta_jakotaulu] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "d_amos_rajapinta_jakotaulu"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dw"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>strategiarahoitus</string>",
              "      </key>",
              "      <value>",
              "        <int>156</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>alv</string>",
              "      </key>",
              "      <value>",
              "        <int>59</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>rahoitus_mukaanlukien_alv</string>",
              "      </key>",
              "      <value>",
              "        <int>232</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>versio</string>",
              "      </key>",
              "      <value>",
              "        <int>81</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>kommentti</string>",
              "      </key>",
              "      <value>",
              "        <int>115</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>harkinnanvarainen_perusrahoitus</string>",
              "      </key>",
              "      <value>",
              "        <int>274</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>kiky_kohdennus</string>",
              "      </key>",
              "      <value>",
              "        <int>153</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jako_ja_oikaisuvara</string>",
              "      </key>",
              "      <value>",
              "        <int>179</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>strategiarahoitus</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>alv</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>rahoitus_mukaanlukien_alv</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>versio</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>kommentti</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>harkinnanvarainen_perusrahoitus</string>",
              "      </key>",
              "      <value>",
              "        <int>5</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>kiky_kohdennus</string>",
              "      </key>",
              "      <value>",
              "        <int>6</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jako_ja_oikaisuvara</string>",
              "      </key>",
              "      <value>",
              "        <int>7</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>rahoitus_mukaanlukien_alv</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>alv</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>strategiarahoitus</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>harkinnanvarainen_perusrahoitus</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>kiky_kohdennus</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jako_ja_oikaisuvara</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "v_koski_opiskelijavuodet_cultures",
        "columns": [
          {
            "name": "opiskelijavuodet",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "opiskelijavuodet",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "vuosi",
            "dataType": "int64",
            "sourceColumn": "vuosi",
            "sourceProviderType": "Integer"
          },
          {
            "name": "ytunnus",
            "dataType": "string",
            "sourceColumn": "ytunnus"
          },
          {
            "name": "tyovoimakoulutus_kytkin_fi",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "tyovoimakoulutus_kytkin_fi"
          },
          {
            "name": "kuukausi",
            "dataType": "int64",
            "sourceColumn": "kuukausi"
          },
          {
            "name": "ytm_flag",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ytm_flag"
          },
          {
            "type": "calculated",
            "name": "kuluva_kk-1",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "month(now())-1"
          }
        ],
        "partitions": [
          {
            "name": "v_koski_opiskelijavuodet_cultures",
            "dataView": "full",
            "source": {
              "query": [
                "SELECT ",
                "      [ytunnus]",
                ", [vuosi]",
                "",
                ", [kuukausi], [tyovoimakoulutus_kytkin_fi], case when cy_flag+cm_flag =2 then 1 else 0 end as ytm_flag,  sum([opiskelijavuodet])  as opiskelijavuodet FROM [dw].[v_koski_opiskelijavuodet_cultures]",
                "where vuosi>=year(getdate())-1 group by [ytunnus]",
                ", [tyovoimakoulutus_kytkin_fi], [vuosi], [kuukausi], cy_flag, cm_flag"
              ],
              "dataSource": "dwitvipusql22"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT ",
                  "      [ytunnus]",
                  ", [vuosi]",
                  "",
                  ", [kuukausi], [tyovoimakoulutus_kytkin_fi], case when cy_flag+cm_flag =2 then 1 else 0 end as ytm_flag,  sum([opiskelijavuodet])  as opiskelijavuodet FROM [dw].[v_koski_opiskelijavuodet_cultures]",
                  "where vuosi>=year(getdate())-1 group by [ytunnus]",
                  ", [tyovoimakoulutus_kytkin_fi], [vuosi], [kuukausi], cy_flag, cm_flag</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "opiskelijavuodet_a",
            "expression": "sum([opiskelijavuodet])"
          },
          {
            "name": "opiskelijavuodet_tyovoimakoulutus_a",
            "expression": "CALCULATE(sum([opiskelijavuodet]),v_koski_opiskelijavuodet_cultures[tyovoimakoulutus_kytkin_fi]=\"Kyllä\")"
          },
          {
            "name": "opiskelijavuodet_ytm_a",
            "expression": "CALCULATE(sum([opiskelijavuodet]),v_koski_opiskelijavuodet_cultures[ytm_flag]=1)"
          },
          {
            "name": "opiskelijavuodet_ytm_tyovoimakoulutus_a",
            "expression": "CALCULATE([opiskelijavuodet_ytm_a],v_koski_opiskelijavuodet_cultures[tyovoimakoulutus_kytkin_fi]=\"Kyllä\")"
          },
          {
            "name": "opiskelijavuodet_estimaatti_a",
            "expression": "12*([opiskelijavuodet_ytm_a]/(month(now())-1))"
          },
          {
            "name": "opiskelijavuodet_tyovoimakoulutus_estimaatti_a",
            "expression": "12*([opiskelijavuodet_ytm_tyovoimakoulutus_a]/(month(now())-1))"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": [
              "SELECT ",
              "      [ytunnus]",
              ", [vuosi]",
              "",
              ", [kuukausi], [tyovoimakoulutus_kytkin_fi], case when cy_flag+cm_flag =2 then 1 else 0 end as ytm_flag,  sum([opiskelijavuodet])  as opiskelijavuodet FROM [dw].[v_koski_opiskelijavuodet_cultures]",
              "where vuosi>=year(getdate())-1 group by [ytunnus]",
              ", [tyovoimakoulutus_kytkin_fi], [vuosi], [kuukausi], cy_flag, cm_flag"
            ]
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "v_koski_opiskelijavuodet_cultures"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dw"
          },
          {
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT ",
              "      [ytunnus]",
              ", [vuosi]",
              "",
              ", [kuukausi], [tyovoimakoulutus_kytkin_fi], case when cy_flag+cm_flag =2 then 1 else 0 end as ytm_flag,  sum([opiskelijavuodet])  as opiskelijavuodet FROM [dw].[v_koski_opiskelijavuodet_cultures]",
              "where vuosi>=year(getdate())-1 group by [ytunnus]",
              ", [tyovoimakoulutus_kytkin_fi], [vuosi], [kuukausi], cy_flag, cm_flag</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "v_amos_rahoitus_notes",
        "columns": [
          {
            "name": "noteid",
            "dataType": "int64",
            "sourceColumn": "noteid",
            "sourceProviderType": "Integer"
          },
          {
            "name": "pvm",
            "dataType": "dateTime",
            "sourceColumn": "pvm",
            "formatString": "dd.MM.yyyy",
            "sourceProviderType": "VarChar",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1035\" Group=\"ShortDate\" FormatString=\"dd.MM.yyyy\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "tekija",
            "dataType": "string",
            "sourceColumn": "tekija",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "kommentti",
            "dataType": "string",
            "sourceColumn": "kommentti",
            "sourceProviderType": "VarChar"
          }
        ],
        "partitions": [
          {
            "name": "d_amos_rahoitus_notes",
            "dataView": "full",
            "source": {
              "query": [
                "SELECT *",
                "  FROM [ANTERO].[dw].[v_amos_rahoitus_notes]",
                "order by pvm desc"
              ],
              "dataSource": "dwitvipusql22"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT *",
                  "  FROM [ANTERO].[dw].[v_amos_rahoitus_notes]",
                  "order by pvm desc</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Kpl",
            "expression": "COUNTROWS(v_amos_rahoitus_notes)"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": [
              "SELECT *",
              "  FROM [ANTERO].[dw].[v_amos_rahoitus_notes]",
              "order by pvm desc"
            ]
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "d_amos_rahoitus_notes"
          },
          {
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT *",
              "  FROM [ANTERO].[dw].[v_amos_rahoitus_notes]",
              "order by pvm desc</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Sarakeleveys",
        "columns": [
          {
            "name": "Sarakeleveys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Sarakeleveys",
            "sourceProviderType": "Char"
          },
          {
            "name": "leveys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "leveys",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Sarakeleveys",
            "dataView": "full",
            "source": {
              "query": " SELECT [dw].[Sarakeleveys].* FROM [dw].[Sarakeleveys] ",
              "dataSource": "dwitvipusql22"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dw].[Sarakeleveys].* FROM [dw].[Sarakeleveys] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Sarakeleveys"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dw"
          }
        ]
      }
    ],
    "perspectives": [
      {
        "name": "d_amos_organisaatioliitokset",
        "tables": [
          {
            "name": "d_amos_rajapinta_organisaatioliitokset",
            "columns": [
              {
                "name": "kommentti"
              },
              {
                "name": "latauspvm"
              },
              {
                "name": "tiedostonimi"
              },
              {
                "name": "uusi"
              },
              {
                "name": "vanha"
              },
              {
                "name": "voimaan_alkaen"
              }
            ],
            "measures": [
              {
                "name": "Lkm"
              }
            ]
          },
          {
            "name": "v_amos_rahoitus_notes",
            "columns": [
              {
                "name": "noteid"
              },
              {
                "name": "pvm"
              },
              {
                "name": "tekija"
              },
              {
                "name": "kommentti"
              }
            ],
            "measures": [
              {
                "name": "Kpl"
              }
            ]
          }
        ]
      },
      {
        "name": "v_amos_rahoituslaskenta_Anssi",
        "tables": [
          {
            "name": "v_amos_rahoituslaskenta",
            "columns": [
              {
                "name": "jarj_luvan_opiskelijavuodet"
              },
              {
                "name": "Koodit Koulutuksen järjestäjä"
              },
              {
                "name": "Koulutuksen järjestäjä"
              },
              {
                "name": "painotettu_opiskelijavuosimäärä"
              },
              {
                "name": "painotettu_tutkintomaara"
              },
              {
                "name": "painottamaton_opiskelijavuosimaara"
              },
              {
                "name": "painottamaton_tutkintomaara"
              },
              {
                "name": "profiilikerroin"
              },
              {
                "name": "tutkintopisteiden_osuus"
              },
              {
                "name": "Vaihe"
              },
              {
                "name": "Vuosi"
              }
            ],
            "measures": [
              {
                "name": "painotettu_opiskelijavuosimaara_a"
              },
              {
                "name": "painotettu_tutkintomaara_a"
              },
              {
                "name": "painottamaton_opiskelijavuosimaara_a"
              },
              {
                "name": "painottamaton_tutkintomaara_a"
              },
              {
                "name": "profiilikerroin_a"
              },
              {
                "name": "tutkintopisteiden_osuus_a"
              }
            ]
          },
          {
            "name": "v_amos_rahoitus_notes",
            "columns": [
              {
                "name": "noteid"
              },
              {
                "name": "pvm"
              },
              {
                "name": "tekija"
              },
              {
                "name": "kommentti"
              }
            ],
            "measures": [
              {
                "name": "Kpl"
              }
            ]
          }
        ]
      },
      {
        "name": "v_amos_rahoitus_kriteerit_Juha",
        "tables": [
          {
            "name": "v_amos_rahoitus_kriteerit",
            "columns": [
              {
                "name": "ytunnus"
              },
              {
                "name": "poistuva_ytunnus"
              },
              {
                "name": "ta_ensikertainen_suoritepaatos"
              },
              {
                "name": "ta_lisasuoritepaatos"
              },
              {
                "name": "ta_paatokset_yhteensa"
              },
              {
                "name": "ltae_mukaiset_paatokset"
              },
              {
                "name": "ltae2_mukaiset_paatokset"
              },
              {
                "name": "ltae_mukaiset_paatokset_yhteensa"
              },
              {
                "name": "paatokset_yhteensa"
              },
              {
                "name": "sp_lisays_kohdentamaton_jarj_esitys"
              },
              {
                "name": "sp_lisays_kohdentamaton_okm_paatos"
              },
              {
                "name": "sp_lisays_kohdentamaton_tyovkoul_jarj_esitys"
              },
              {
                "name": "sp_lisays_kohdentamaton_tyovkoul_okm_paatos"
              },
              {
                "name": "sp_lisays_kohdennettu_krit1_jarj_esitys"
              },
              {
                "name": "sp_lisays_kohdennettu_krit1_okm_paatos"
              },
              {
                "name": "sp_lisays_kohdennettu_tyovkoul_krit1_jarj_esitys"
              },
              {
                "name": "sp_lisays_kohdennettu_tyovkoul_krit1_okm_paatos"
              },
              {
                "name": "sp_lisays_kohdennettu_krit2_jarj_esitys"
              },
              {
                "name": "sp_lisays_kohdennettu_krit2_okm_paatos"
              },
              {
                "name": "sp_lisays_kohdennettu_tyovkoul_krit2_jarj_esitys"
              },
              {
                "name": "sp_lisays_kohdennettu_tyovkoul_krit2_okm_paatos"
              },
              {
                "name": "sp_lisays_kohdennettu_krit3_jarj_esitys"
              },
              {
                "name": "sp_lisays_kohdennettu_krit3_okm_paatos"
              },
              {
                "name": "sp_lisays_kohdennettu_tyovkoul_krit3_jarj_esitys"
              },
              {
                "name": "sp_lisays_kohdennettu_tyovkoul_krit3_okm_paatos"
              },
              {
                "name": "sp_lisays_kohdennettu_krit4_jarj_esitys"
              },
              {
                "name": "sp_lisays_kohdennettu_krit4_okm_paatos"
              },
              {
                "name": "sp_lisays_kohdennettu_tyovkoul_krit4_jarj_esitys"
              },
              {
                "name": "sp_lisays_kohdennettu_tyovkoul_krit4_okm_paatos"
              },
              {
                "name": "ta_ensikertainen_suoritepaatos_harkv_korotus"
              },
              {
                "name": "ta_lisasuoritepaatos_harkv_korotus"
              },
              {
                "name": "harkv_korotus_syy1_hakemus"
              },
              {
                "name": "harkv_korotus_syy1_paatos"
              },
              {
                "name": "harkv_korotus_syy2_hakemus"
              },
              {
                "name": "harkv_korotus_syy2_paatos"
              },
              {
                "name": "harkv_korotus_syy3_hakemus"
              },
              {
                "name": "harkv_korotus_syy3_paatos"
              },
              {
                "name": "harkv_korotus_syy4_hakemus"
              },
              {
                "name": "harkv_korotus_syy4_paatos"
              },
              {
                "name": "vos_ta_mukainen"
              },
              {
                "name": "vos_ta_mukainen_sis_alv"
              },
              {
                "name": "vos_ta_ja_ltae_mukainen"
              },
              {
                "name": "vos_ta_ja_ltae_mukainen_sis_alv"
              },
              {
                "name": "vos_ta_ja_ltae_mukainen_vertailu"
              },
              {
                "name": "vos_ta_ja_ltae_mukainen_vertailu_sis_alv"
              },
              {
                "name": "ensikertainen_sp_suoritusrahoitus"
              },
              {
                "name": "ensikertainen_sp_tyovoimakoulutus"
              }
            ],
            "measures": [
              {
                "name": "ltae_mukaiset_paatokset_a"
              },
              {
                "name": "ta_lisasuoritepaatos_a"
              },
              {
                "name": "vos_ta_mukainen_a"
              },
              {
                "name": "ltae_mukaiset_paatokset_yhteensa_a"
              },
              {
                "name": "ltae2_mukaiset_paatokset_a"
              },
              {
                "name": "paatokset_yhteensa_a"
              },
              {
                "name": "sp_lisays_kohdennettu_krit1_jarj_esitys_a"
              },
              {
                "name": "sp_lisays_kohdennettu_krit1_okm_paatos_a"
              },
              {
                "name": "sp_lisays_kohdennettu_krit2_okm_paatos_a"
              },
              {
                "name": "sp_lisays_kohdennettu_krit3_jarj_esitys_a"
              },
              {
                "name": "sp_lisays_kohdennettu_krit3_okm_paatos_a"
              },
              {
                "name": "sp_lisays_kohdennettu_krit4_jarj_esitys_a"
              },
              {
                "name": "sp_lisays_kohdennettu_krit4_okm_paatos_a"
              },
              {
                "name": "sp_lisays_kohdennettu_tyovkoul_krit1_jarj_esitys_a"
              },
              {
                "name": "sp_lisays_kohdennettu_tyovkoul_krit1_okm_paatos_a"
              },
              {
                "name": "sp_lisays_kohdennettu_tyovkoul_krit2_jarj_esitys_a"
              },
              {
                "name": "sp_lisays_kohdennettu_tyovkoul_krit2_okm_paatos_a"
              },
              {
                "name": "sp_lisays_kohdennettu_tyovkoul_krit3_jarj_esitys_a"
              },
              {
                "name": "sp_lisays_kohdennettu_tyovkoul_krit3_okm_paatos_a"
              },
              {
                "name": "sp_lisays_kohdennettu_tyovkoul_krit4_jarj_esitys_a"
              },
              {
                "name": "sp_lisays_kohdennettu_tyovkoul_krit4_okm_paatos_a"
              },
              {
                "name": "sp_lisays_kohdentamaton_jarj_esitys_a"
              },
              {
                "name": "sp_lisays_kohdentamaton_okm_paatos_a"
              },
              {
                "name": "sp_lisays_kohdentamaton_tyovkoul_jarj_esitys_a"
              },
              {
                "name": "sp_lisays_kohdentamaton_tyovkoul_okm_paatos_a"
              },
              {
                "name": "ta_ensikertainen_suoritepaatos_a"
              },
              {
                "name": "ta_paatokset_yhteensa_a"
              },
              {
                "name": "ensikertainen_sp_suoritusrahoitus_a"
              },
              {
                "name": "ensikertainen_sp_tyovoimakoulutus_a"
              },
              {
                "name": "harkv_korotus_syy1_hakemus_a"
              },
              {
                "name": "harkv_korotus_syy1_paatos_a"
              },
              {
                "name": "harkv_korotus_syy2_hakemus_a"
              },
              {
                "name": "harkv_korotus_syy2_paatos_a"
              },
              {
                "name": "harkv_korotus_syy3_hakemus_a"
              },
              {
                "name": "harkv_korotus_syy3_paatos_a"
              },
              {
                "name": "harkv_korotus_syy4_hakemus_a"
              },
              {
                "name": "harkv_korotus_syy4_paatos_a"
              },
              {
                "name": "vos_ta_mukainen_sis_alv_a"
              },
              {
                "name": "sp_lisays_kohdennettu_krit2_jarj_esitys_a"
              },
              {
                "name": "ta_ensikertainen_suoritepaatos_harkv_korotus_a"
              },
              {
                "name": "ta_lisasuoritepaatos_harkv_korotus_a"
              },
              {
                "name": "vos_ta_ja_ltae_mukainen_a"
              },
              {
                "name": "vos_ta_ja_ltae_mukainen_sis_alv_a"
              },
              {
                "name": "vos_ta_ja_ltae_mukainen_vertailu_a"
              },
              {
                "name": "vos_ta_ja_ltae_mukainen_vertailu_sis_alv_a"
              }
            ]
          },
          {
            "name": "v_amos_rahoitus_notes",
            "columns": [
              {
                "name": "noteid"
              },
              {
                "name": "pvm"
              },
              {
                "name": "tekija"
              },
              {
                "name": "kommentti"
              }
            ],
            "measures": [
              {
                "name": "Kpl"
              }
            ]
          }
        ]
      },
      {
        "name": "d_amos_rajapinta_jakotaulu",
        "tables": [
          {
            "name": "d_amos_rajapinta_jakotaulu",
            "columns": [
              {
                "name": "versio"
              },
              {
                "name": "kommentti"
              },
              {
                "name": "rahoitus_mukaanlukien_alv"
              },
              {
                "name": "alv"
              },
              {
                "name": "strategiarahoitus"
              },
              {
                "name": "kiky_kohdennus"
              },
              {
                "name": "jako_ja_oikaisuvara"
              },
              {
                "name": "harkinnanvarainen_perusrahoitus"
              }
            ],
            "measures": [
              {
                "name": "rahoitus_mukaanlukien_alv_a"
              },
              {
                "name": "alv_a"
              },
              {
                "name": "jako_ja_oikaisuvara_a"
              },
              {
                "name": "kiky_kohdennus_a"
              },
              {
                "name": "strategiarahoitus_a"
              },
              {
                "name": "harkinnanvarainen_perusrahoitus_a"
              }
            ]
          },
          {
            "name": "v_amos_rahoitus_notes",
            "columns": [
              {
                "name": "noteid"
              },
              {
                "name": "pvm"
              },
              {
                "name": "tekija"
              },
              {
                "name": "kommentti"
              }
            ],
            "measures": [
              {
                "name": "Kpl"
              }
            ]
          }
        ]
      },
      {
        "name": "v_koski_opiskelijavuodet_cultures",
        "tables": [
          {
            "name": "v_koski_opiskelijavuodet_cultures",
            "columns": [
              {
                "name": "opiskelijavuodet"
              },
              {
                "name": "vuosi"
              },
              {
                "name": "ytunnus"
              },
              {
                "name": "tyovoimakoulutus_kytkin_fi"
              },
              {
                "name": "kuukausi"
              },
              {
                "name": "ytm_flag"
              },
              {
                "name": "kuluva_kk-1"
              }
            ],
            "measures": [
              {
                "name": "opiskelijavuodet_a"
              },
              {
                "name": "opiskelijavuodet_tyovoimakoulutus_a"
              },
              {
                "name": "opiskelijavuodet_ytm_a"
              },
              {
                "name": "opiskelijavuodet_ytm_tyovoimakoulutus_a"
              },
              {
                "name": "opiskelijavuodet_estimaatti_a"
              },
              {
                "name": "opiskelijavuodet_tyovoimakoulutus_estimaatti_a"
              }
            ]
          },
          {
            "name": "v_amos_rahoitus_notes",
            "columns": [
              {
                "name": "noteid"
              },
              {
                "name": "pvm"
              },
              {
                "name": "tekija"
              },
              {
                "name": "kommentti"
              }
            ],
            "measures": [
              {
                "name": "Kpl"
              }
            ]
          }
        ]
      },
      {
        "name": "d_amos_rahoitus_notes",
        "tables": [
          {
            "name": "v_amos_rahoitus_notes",
            "columns": [
              {
                "name": "noteid"
              },
              {
                "name": "pvm"
              },
              {
                "name": "tekija"
              },
              {
                "name": "kommentti"
              }
            ],
            "measures": [
              {
                "name": "Kpl"
              }
            ]
          }
        ]
      }
    ],
    "roles": [
      {
        "name": "Role",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "DWI\\P_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1733"
          },
          {
            "memberName": "DWI\\T_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1732"
          },
          {
            "memberName": "NT AUTHORITY\\IUSR",
            "memberId": "S-1-5-17"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "400"
      }
    ]
  },
  "id": "SemanticModel"
}
