{
  "name": "SemanticModel",
  "compatibilityLevel": 1200,
  "model": {
    "culture": "fi-FI",
    "dataSources": [
      {
        "name": "SqlServer dwitvipusql16 ANTERO",
        "connectionString": "Provider=SQLNCLI11;Data Source=dwitvipusql16;Initial Catalog=ANTERO;Integrated Security=SSPI;Persist Security Info=false",
        "impersonationMode": "impersonateAccount",
        "account": "dwi\\pankalai",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "Sarakeleveys",
        "columns": [
          {
            "name": "Sarakeleveys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Sarakeleveys",
            "sourceProviderType": "Char"
          },
          {
            "name": "leveys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "leveys",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Sarakeleveys",
            "dataView": "full",
            "source": {
              "query": " SELECT [dw].[Sarakeleveys].* FROM [dw].[Sarakeleveys] ",
              "dataSource": "SqlServer dwitvipusql16 ANTERO"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dw].[Sarakeleveys].* FROM [dw].[Sarakeleveys] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Sarakeleveys"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dw"
          }
        ]
      },
      {
        "name": "Muuttujat",
        "columns": [
          {
            "name": "Tilastovuosi",
            "dataType": "int64",
            "sourceColumn": "Tilastovuosi",
            "sourceProviderType": "Integer",
            "displayFolder": "Aikamuuttujat"
          },
          {
            "name": "Yliopisto",
            "dataType": "string",
            "sourceColumn": "Yliopisto",
            "sourceProviderType": "Char",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "harjoittelukoulun_oppilaat_esiopetus",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "harjoittelukoulun_oppilaat_esiopetus",
            "sourceProviderType": "Integer"
          },
          {
            "name": "harjoittelukoulun_oppilaat_perusopetuksen_vuodet_1_6",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "harjoittelukoulun_oppilaat_perusopetuksen_vuodet_1_6",
            "sourceProviderType": "Integer"
          },
          {
            "name": "harjoittelukoulun_oppilaat_perusopetuksen_vuodet_7_9",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "harjoittelukoulun_oppilaat_perusopetuksen_vuodet_7_9",
            "sourceProviderType": "Integer"
          },
          {
            "name": "harjoittelukoulun_oppilaat_lukio",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "harjoittelukoulun_oppilaat_lukio",
            "sourceProviderType": "Integer"
          },
          {
            "name": "harjoittelukoulun_oppilaat_yhteensa",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "harjoittelukoulun_oppilaat_yhteensa",
            "sourceProviderType": "Integer"
          },
          {
            "name": "harjoittelukoulun_opettajankoulutustehtavien_kokonaisviikkotunnit",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "harjoittelukoulun_opettajankoulutustehtavien_kokonaisviikkotunnit",
            "sourceProviderType": "Integer"
          },
          {
            "name": "harjoittelukoulun_kokonaistuntimaara",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "harjoittelukoulun_kokonaistuntimaara",
            "sourceProviderType": "Integer"
          },
          {
            "name": "opintopisteet_lastentarha",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "opintopisteet_lastentarha",
            "sourceProviderType": "Integer"
          },
          {
            "name": "opintopisteet_luokanopettaja",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "opintopisteet_luokanopettaja",
            "sourceProviderType": "Integer"
          },
          {
            "name": "opintopisteet_aineenopettaja",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "opintopisteet_aineenopettaja",
            "sourceProviderType": "Integer"
          },
          {
            "name": "opintopisteet_erityisopettaja",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "opintopisteet_erityisopettaja",
            "sourceProviderType": "Integer"
          },
          {
            "name": "opintopisteet_opinto_ohjaaja",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "opintopisteet_opinto_ohjaaja",
            "sourceProviderType": "Integer"
          },
          {
            "name": "opintopisteet_aikuiskoulutus",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "opintopisteet_aikuiskoulutus",
            "sourceProviderType": "Integer"
          },
          {
            "name": "opintopisteet_muut",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "opintopisteet_muut",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Koodit Yliopisto",
            "dataType": "string",
            "sourceColumn": "Koodit Yliopisto",
            "sourceProviderType": "Char",
            "displayFolder": "Koodimuuttujat"
          }
        ],
        "partitions": [
          {
            "name": "v_st_harjoittelukoulut",
            "dataView": "full",
            "source": {
              "query": " SELECT [dw].[v_st_harjoittelukoulut].* FROM [dw].[v_st_harjoittelukoulut] ",
              "dataSource": "SqlServer dwitvipusql16 ANTERO"
            }
          }
        ],
        "measures": [
          {
            "name": "Oppilasmäärä: esiopetus",
            "expression": "sum([harjoittelukoulun_oppilaat_esiopetus])"
          },
          {
            "name": "Oppilasmäärä: 1–6 luokat",
            "expression": "sum([harjoittelukoulun_oppilaat_perusopetuksen_vuodet_1_6])",
            "formatString": "#,0"
          },
          {
            "name": "Oppilasmäärä: 7–9 luokat",
            "expression": "sum([harjoittelukoulun_oppilaat_perusopetuksen_vuodet_7_9])",
            "formatString": "#,0"
          },
          {
            "name": "Oppilasmäärä: lukio",
            "expression": "sum([harjoittelukoulun_oppilaat_lukio])",
            "formatString": "#,0"
          },
          {
            "name": "Oppilasmäärä: yhteensä",
            "expression": "sum([harjoittelukoulun_oppilaat_yhteensa])",
            "formatString": "#,0"
          },
          {
            "name": "Opettajakoulutustehtävien kokonaisviikkontunnit",
            "expression": "sum(Muuttujat[harjoittelukoulun_opettajankoulutustehtavien_kokonaisviikkotunnit])",
            "formatString": "#,0"
          },
          {
            "name": "Kokonaistuntimäärä",
            "expression": "sum(Muuttujat[harjoittelukoulun_kokonaistuntimaara])",
            "formatString": "#,0"
          },
          {
            "name": "Luokanopettajaharjoittelu",
            "expression": "sum([opintopisteet_luokanopettaja])",
            "formatString": "#,0"
          },
          {
            "name": "Aineopettajaharjoittelu",
            "expression": "sum(Muuttujat[opintopisteet_aineenopettaja])",
            "formatString": "#,0"
          },
          {
            "name": "Erityisopettajat",
            "expression": "sum([opintopisteet_erityisopettaja])",
            "formatString": "#,0"
          },
          {
            "name": "Opinto-ohjaajat",
            "expression": "sum([opintopisteet_opinto_ohjaaja])",
            "formatString": "#,0"
          },
          {
            "name": "Aikuiskoulutukseen painottunut harjoittelu",
            "expression": "sum([opintopisteet_aikuiskoulutus])",
            "formatString": "#,0"
          },
          {
            "name": "Muut opettajakoulutusryhmät",
            "expression": "sum([opintopisteet_muut])",
            "formatString": "#,0"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dw].[v_st_harjoittelukoulut].* FROM [dw].[v_st_harjoittelukoulut] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "v_st_harjoittelukoulut"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dw"
          }
        ]
      }
    ],
    "perspectives": [
      {
        "name": "opintopisteet",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Koodit Yliopisto"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Yliopisto"
              }
            ],
            "measures": [
              {
                "name": "Aikuiskoulutukseen painottunut harjoittelu"
              },
              {
                "name": "Aineopettajaharjoittelu"
              },
              {
                "name": "Erityisopettajat"
              },
              {
                "name": "Luokanopettajaharjoittelu"
              },
              {
                "name": "Muut opettajakoulutusryhmät"
              },
              {
                "name": "Opinto-ohjaajat"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "toiminta",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Koodit Yliopisto"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Yliopisto"
              }
            ],
            "measures": [
              {
                "name": "Kokonaistuntimäärä"
              },
              {
                "name": "Opettajakoulutustehtävien kokonaisviikkontunnit"
              },
              {
                "name": "Oppilasmäärä: 1–6 luokat"
              },
              {
                "name": "Oppilasmäärä: 7–9 luokat"
              },
              {
                "name": "Oppilasmäärä: esiopetus"
              },
              {
                "name": "Oppilasmäärä: lukio"
              },
              {
                "name": "Oppilasmäärä: yhteensä"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      }
    ],
    "roles": [
      {
        "name": "Luku",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "DWI\\T_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1732"
          },
          {
            "memberName": "DWI\\P_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1733"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "400"
      }
    ]
  },
  "id": "SemanticModel"
}