{
  "name": "SemanticModel",
  "compatibilityLevel": 1200,
  "model": {
    "culture": "fi-FI",
    "dataSources": [
      {
        "name": "SqlServer dwitvipusql22 ANTERO",
        "connectionString": "Provider=SQLOLEDB.1;Data Source=dwitvipusql22;Persist Security Info=false;Integrated Security=SSPI;Initial Catalog=ANTERO",
        "impersonationMode": "impersonateServiceAccount",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "Muuttujat",
        "columns": [
          {
            "name": "Lukumäärä",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Lukumäärä"
          },
          {
            "name": "Koulutuksen alkamisvuosi",
            "dataType": "int64",
            "sourceColumn": "Koulutuksen alkamisvuosi",
            "displayFolder": "Aikamuuttujat"
          },
          {
            "name": "Hakutyyppi",
            "dataType": "string",
            "sourceColumn": "Hakutyyppi",
            "sortByColumn": "Hakutyyppi järjestys",
            "displayFolder": "Hakumuuttujat"
          },
          {
            "name": "Hakutyyppi järjestys",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Hakutyyppi järjestys"
          },
          {
            "name": "Kotipaikan maakunta järjestys",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Kotipaikan maakunta järjestys"
          },
          {
            "name": "Sukupuoli",
            "dataType": "string",
            "sourceColumn": "Sukupuoli",
            "sortByColumn": "Sukupuoli järjestys",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Sukupuoli järjestys",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Sukupuoli järjestys"
          },
          {
            "name": "Äidinkieli",
            "dataType": "string",
            "sourceColumn": "Äidinkieli",
            "sortByColumn": "Äidinkieli versio1 järjestys",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Äidinkieli versio1 järjestys",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Äidinkieli versio1 järjestys"
          },
          {
            "name": "Ikä 5v järjestys",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Ikä 5v järjestys"
          },
          {
            "name": "Hakukohde",
            "dataType": "string",
            "sourceColumn": "Hakukohde",
            "displayFolder": "Hakumuuttujat"
          },
          {
            "name": "Hakukohteen koulutustoimija",
            "dataType": "string",
            "sourceColumn": "Hakukohteen koulutustoimija",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Korkeakoulu",
            "dataType": "string",
            "sourceColumn": "Hakukohteen oppilaitos",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Toimipiste",
            "dataType": "string",
            "sourceColumn": "Hakukohteen toimipiste",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Maakunta (hakukohde)",
            "dataType": "string",
            "sourceColumn": "Hakukohteen maakunta",
            "sortByColumn": "Hakukohteen maakunta järjestys",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Hakukohteen maakunta järjestys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Hakukohteen maakunta järjestys"
          },
          {
            "name": "Kunta (hakukohde)",
            "dataType": "string",
            "sourceColumn": "Hakukohteen kunta",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Hakutoive",
            "dataType": "string",
            "sourceColumn": "Hakutoive",
            "displayFolder": "Hakumuuttujat"
          },
          {
            "name": "Pohjakoulutus järjestys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Pohjakoulutus järjestys"
          },
          {
            "name": "Haku",
            "dataType": "string",
            "sourceColumn": "Haku",
            "displayFolder": "Hakumuuttujat"
          },
          {
            "name": "Henkilö OID",
            "dataType": "string",
            "sourceColumn": "Henkilö OID"
          },
          {
            "name": "Hakutapa",
            "dataType": "string",
            "sourceColumn": "Hakutapa",
            "sortByColumn": "Hakutapa järjestys",
            "displayFolder": "Hakumuuttujat"
          },
          {
            "name": "Kansalaisuus",
            "dataType": "string",
            "sourceColumn": "Kansalaisuus",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Opiskelun laajuus",
            "dataType": "string",
            "sourceColumn": "Opiskelun laajuus",
            "sortByColumn": "Opiskelun laajuus järjestys",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Sektori",
            "dataType": "string",
            "sourceColumn": "Sektori",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutuksen alkamiskausi",
            "dataType": "string",
            "sourceColumn": "Koulutuksen alkamiskausi",
            "displayFolder": "Aikamuuttujat"
          },
          {
            "name": "Kansalaisuus järjestys",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Kansalaisuus järjestys"
          },
          {
            "name": "Koulutuksen kieli",
            "dataType": "string",
            "sourceColumn": "Koulutuksen kieli",
            "sortByColumn": "Koulutuksen kieli järjestys",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutuksen kieli järjestys",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Koulutuksen kieli järjestys",
            "formatString": "0"
          },
          {
            "name": "alpa",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "alpa"
          },
          {
            "name": "valpa",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "valpa"
          },
          {
            "name": "Opiskelun laajuus järjestys",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Opiskelun laajuus järjestys",
            "formatString": "0"
          },
          {
            "name": "Haku AMK/YO",
            "dataType": "string",
            "sourceColumn": "Haku AMK/YO",
            "sortByColumn": "Haku AMKYO järjestys",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Hakuaika",
            "dataType": "string",
            "sourceColumn": "Hakuaika",
            "sortByColumn": "Hakuaika järjestys",
            "displayFolder": "Hakumuuttujat"
          },
          {
            "name": "Ensikertainen hakija järjestys",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Ensikertainen hakija järjestys",
            "formatString": "0"
          },
          {
            "name": "Haku AMKYO järjestys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Haku AMK/YO järjestys"
          },
          {
            "name": "Kotipaikkakunta järjestys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Kotipaikkakunta järjestys"
          },
          {
            "name": "Ensikertaisena kohdeltava hakija",
            "dataType": "string",
            "sourceColumn": "Ensikertaisena kohdeltava hakija",
            "sortByColumn": "Ensikertainen hakija järjestys",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Toisen asteen koulutuksen suoritusvuosi järjestys",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Toisen asteen koulutuksen suoritusvuosi järjestys"
          },
          {
            "name": "Kansalaisuus (ryhmä)",
            "dataType": "string",
            "sourceColumn": "Kansalaisuus (ryhmä)",
            "sortByColumn": "Kansalaisuus ryhmä järjestys",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Kansalaisuus ryhmä järjestys",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Kansalaisuus ryhmä järjestys"
          },
          {
            "name": "Kansalaisuus (maanosa)",
            "dataType": "string",
            "sourceColumn": "Kansalaisuus (maanosa)",
            "sortByColumn": "Kansalaisuus maanosa järjestys",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Tutkinnon taso (hakukohde)",
            "dataType": "string",
            "sourceColumn": "Tutkinnon taso (hakukohde)",
            "sortByColumn": "Tutkinnon taso hakukohde järjestys",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Tutkinnon taso hakukohde järjestys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Tutkinnon taso (hakukohde) järjestys"
          },
          {
            "name": "Tutkinnon aloitussykli (hakukohde)",
            "dataType": "string",
            "sourceColumn": "Tutkinnon aloitussykli (hakukohde)",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Hakijat2",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Hakijat2"
          },
          {
            "name": "Ensisijaiset hakijat2",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Ensisijaiset hakijat2"
          },
          {
            "name": "Valitut2",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Valitut2"
          },
          {
            "name": "Paikan vastaanottaneet2",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Paikan vastaanottaneet2"
          },
          {
            "type": "calculated",
            "name": "Pohjakoulutuksia per hakija",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "CALCULATE(DISTINCTCOUNT(Muuttujat[Pohjakoulutus*]),ALLEXCEPT(Muuttujat,Muuttujat[Henkilö OID],Muuttujat[Haku]))"
          },
          {
            "name": "hakukohde OID",
            "dataType": "string",
            "sourceColumn": "hakukohde OID",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "yksi_pk_per_hakija",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "yksi_pk_per_hakija"
          },
          {
            "name": "Aloittaneet2",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Aloittaneet2"
          },
          {
            "name": "Ikä järjestys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Ikä järjestys"
          },
          {
            "name": "Hakemus OID",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Hakemus OID"
          },
          {
            "name": "Kansalaisuus maanosa järjestys",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Kansalaisuus maanosa järjestys"
          },
          {
            "name": "Hakutapa järjestys",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Hakutapa järjestys"
          },
          {
            "name": "Koulutusala, taso 1",
            "dataType": "string",
            "sourceColumn": "Koulutusala, taso 1 (hakukohde)",
            "sortByColumn": "Koulutusala taso 1 järjestys",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusala, taso 2",
            "dataType": "string",
            "sourceColumn": "Koulutusala, taso 2 (hakukohde)",
            "sortByColumn": "Koulutusala taso 2 järjestys",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusala, taso 3",
            "dataType": "string",
            "sourceColumn": "Koulutusala, taso 3 (hakukohde)",
            "sortByColumn": "Koulutusala taso 3 järjestys",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "OKM ohjauksen ala",
            "dataType": "string",
            "sourceColumn": "OKM ohjauksen ala (hakukohde)",
            "sortByColumn": "OKM ohjauksen ala järjestys",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusala taso 1 järjestys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Koulutusala, taso 1 järjestys"
          },
          {
            "name": "Koulutusala taso 2 järjestys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Koulutusala, taso 2 järjestys"
          },
          {
            "name": "Koulutusala taso 3 järjestys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Koulutusala, taso 3 järjestys"
          },
          {
            "name": "OKM ohjauksen ala järjestys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "OKM ohjauksen ala järjestys"
          },
          {
            "name": "Hakuaika järjestys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Hakuaika järjestys"
          },
          {
            "name": "Ansökan YH/Univ.",
            "dataType": "string",
            "sourceColumn": "Ansökan YH/Univ.",
            "sortByColumn": "Haku AMKYO järjestys",
            "displayFolder": "Personvariabler"
          },
          {
            "name": "Sökobjekt",
            "dataType": "string",
            "sourceColumn": "Sökobjekt",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Gemensam/separat ansökan",
            "dataType": "string",
            "sourceColumn": "Gemensam/separat ansökan",
            "sortByColumn": "Hakutapa järjestys",
            "displayFolder": "Ansökningsvariabler"
          },
          {
            "name": "Typ av ansökan",
            "dataType": "string",
            "sourceColumn": "Typ av ansökan",
            "displayFolder": "Ansökningsvariabler"
          },
          {
            "name": "Högskola",
            "dataType": "string",
            "sourceColumn": "Högskola (sökobjekt)",
            "displayFolder": "Organisationsvariabler"
          },
          {
            "name": "Anstalt",
            "dataType": "string",
            "sourceColumn": "Anstalt (sökobjekt)",
            "displayFolder": "Organisationsvariabler"
          },
          {
            "name": "Landskap (sökobjekt)",
            "dataType": "string",
            "sourceColumn": "Landskap (sökobjekt)",
            "sortByColumn": "Hakukohteen maakunta järjestys",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Kommun (sökobjekt)",
            "dataType": "string",
            "sourceColumn": "Kommun (sökobjekt)",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Utb.område, nivå 1 (sökobjekt)",
            "dataType": "string",
            "sourceColumn": "Utb.område, nivå 1 (sökobjekt)",
            "sortByColumn": "Koulutusala taso 1 järjestys",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Utb.område, nivå 2 (sökobjekt)",
            "dataType": "string",
            "sourceColumn": "Utb.område, nivå 2 (sökobjekt)",
            "sortByColumn": "Koulutusala, taso 2",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Utb.område, nivå 3 (sökobjekt)",
            "dataType": "string",
            "sourceColumn": "Utb.område, nivå 3 (sökobjekt)",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "UKM-styrningsområde (sökobjekt)",
            "dataType": "string",
            "sourceColumn": "UKM-styrningsområde (sökobjekt)",
            "sortByColumn": "OKM ohjauksen ala järjestys",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Ansökningsönskemål",
            "dataType": "string",
            "sourceColumn": "Ansökningsönskemål",
            "displayFolder": "Ansökningsvariabler"
          },
          {
            "name": "Medborgarskap",
            "dataType": "string",
            "sourceColumn": "Medborgarskap",
            "displayFolder": "Personvariabler"
          },
          {
            "name": "Medborgarskap (världsdel)",
            "dataType": "string",
            "sourceColumn": "Medborgarskap (världsdel)",
            "sortByColumn": "Hakutapa järjestys",
            "displayFolder": "Personvariabler"
          },
          {
            "name": "Medborgarskap (gruppen)",
            "dataType": "string",
            "sourceColumn": "Medborgarskap (gruppen)",
            "sortByColumn": "Kansalaisuus ryhmä järjestys",
            "displayFolder": "Personvariabler"
          },
          {
            "name": "Begynnelseår",
            "dataType": "int64",
            "sourceColumn": "Begynnelseår",
            "displayFolder": "Tidsvariabler"
          },
          {
            "name": "Begynnelsetermin",
            "dataType": "string",
            "sourceColumn": "Begynnelsetermin",
            "displayFolder": "Tidsvariabler"
          },
          {
            "name": "Utbildningens språk",
            "dataType": "string",
            "sourceColumn": "Utbildningens språk",
            "sortByColumn": "Koulutuksen kieli järjestys",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Studiernas omfattning",
            "dataType": "string",
            "sourceColumn": "Studiernas omfattning",
            "sortByColumn": "Opiskelun laajuus järjestys",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Sektor",
            "dataType": "string",
            "sourceColumn": "Sektor",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Kön",
            "dataType": "string",
            "sourceColumn": "Kön",
            "displayFolder": "Personvariabler"
          },
          {
            "name": "Examensnivå (sökobjekt)",
            "dataType": "string",
            "sourceColumn": "Examensnivå (sökobjekt)",
            "sortByColumn": "Tutkinnon taso hakukohde järjestys",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Cykeln (sökobjekt)",
            "dataType": "string",
            "sourceColumn": "Cykeln (sökobjekt)",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Modersmål",
            "dataType": "string",
            "sourceColumn": "Modersmål",
            "displayFolder": "Personvariabler"
          },
          {
            "name": "Application to UAS/Univ.",
            "dataType": "string",
            "sourceColumn": "Application to UAS/Univ.",
            "sortByColumn": "Haku AMKYO järjestys",
            "displayFolder": "Person variables"
          },
          {
            "name": "Application period",
            "dataType": "string",
            "sourceColumn": "Application period",
            "sortByColumn": "Hakuaika järjestys",
            "displayFolder": "Application variables"
          },
          {
            "name": "Applied study programme",
            "dataType": "string",
            "sourceColumn": "Applied study programme",
            "displayFolder": "Education variables"
          },
          {
            "name": "Joint/separate application",
            "dataType": "string",
            "sourceColumn": "Joint/separate application",
            "sortByColumn": "Hakutapa järjestys",
            "displayFolder": "Application variables"
          },
          {
            "name": "Higher education institution",
            "dataType": "string",
            "sourceColumn": "Higher education institution",
            "displayFolder": "Organisation variables"
          },
          {
            "name": "Faculty/campus",
            "dataType": "string",
            "sourceColumn": "Faculty/campus",
            "displayFolder": "Organisation variables"
          },
          {
            "name": "Region of study programme",
            "dataType": "string",
            "sourceColumn": "Region of study programme",
            "sortByColumn": "Hakukohteen maakunta järjestys",
            "displayFolder": "Education variables"
          },
          {
            "name": "Municipality of study programme",
            "dataType": "string",
            "sourceColumn": "Municipality of study programme",
            "displayFolder": "Education variables"
          },
          {
            "name": "Field of ed., tier 1",
            "dataType": "string",
            "sourceColumn": "Field of ed., level 1",
            "sortByColumn": "Koulutusala taso 1 järjestys",
            "displayFolder": "Education variables"
          },
          {
            "name": "Field of ed., tier 2",
            "dataType": "string",
            "sourceColumn": "Field of ed., level 2",
            "sortByColumn": "Koulutusala taso 2 järjestys",
            "displayFolder": "Education variables"
          },
          {
            "name": "Field of ed., tier 3",
            "dataType": "string",
            "sourceColumn": "Field of ed., level 3",
            "sortByColumn": "Koulutusala taso 3 järjestys",
            "displayFolder": "Education variables"
          },
          {
            "name": "Field of ed., HE steering",
            "dataType": "string",
            "sourceColumn": "Field of ed., HE steering",
            "sortByColumn": "OKM ohjauksen ala järjestys",
            "displayFolder": "Education variables"
          },
          {
            "name": "Preference of study programme",
            "dataType": "string",
            "sourceColumn": "Preference of study programme",
            "displayFolder": "Application variables"
          },
          {
            "name": "Nationality",
            "dataType": "string",
            "sourceColumn": "Nationality",
            "displayFolder": "Person variables"
          },
          {
            "name": "Nationality (continent)",
            "dataType": "string",
            "sourceColumn": "Nationality (continent)",
            "sortByColumn": "Kansalaisuus maanosa järjestys",
            "displayFolder": "Person variables"
          },
          {
            "name": "Nationality (group)",
            "dataType": "string",
            "sourceColumn": "Nationality (group)",
            "sortByColumn": "Kansalaisuus ryhmä järjestys",
            "displayFolder": "Person variables"
          },
          {
            "name": "Language of education",
            "dataType": "string",
            "sourceColumn": "Language of education",
            "sortByColumn": "Koulutuksen kieli järjestys",
            "displayFolder": "Education variables"
          },
          {
            "name": "Sector",
            "dataType": "string",
            "sourceColumn": "Sector",
            "displayFolder": "Education variables"
          },
          {
            "name": "Gender",
            "dataType": "string",
            "sourceColumn": "Gender",
            "displayFolder": "Person variables"
          },
          {
            "name": "Level of degree",
            "dataType": "string",
            "sourceColumn": "Level of degree",
            "sortByColumn": "Tutkinnon taso hakukohde järjestys",
            "displayFolder": "Education variables"
          },
          {
            "name": "Mother tongue",
            "dataType": "string",
            "sourceColumn": "Mother tongue",
            "sortByColumn": "Äidinkieli versio1 järjestys",
            "displayFolder": "Person variables"
          },
          {
            "name": "Ansökningstid",
            "dataType": "string",
            "sourceColumn": "Ansökningstiden",
            "sortByColumn": "Hakuaika järjestys",
            "displayFolder": "Ansökningsvariabler"
          },
          {
            "name": "Application round",
            "dataType": "string",
            "sourceColumn": "Application round",
            "sortByColumn": "Hakutyyppi järjestys",
            "displayFolder": "Application variables"
          },
          {
            "name": "Förstagångssökande",
            "dataType": "string",
            "sourceColumn": "Förstagångssökande",
            "sortByColumn": "jarjestys_ensikertainen_hakija",
            "displayFolder": "Personvariabler"
          },
          {
            "name": "First-time applicant",
            "dataType": "string",
            "sourceColumn": "First-time applicant",
            "sortByColumn": "jarjestys_ensikertainen_hakija",
            "displayFolder": "Person variables"
          },
          {
            "name": "Year (start of studies)",
            "dataType": "int64",
            "sourceColumn": "Year (start of studies)",
            "displayFolder": "Time variables"
          },
          {
            "name": "Term (start of studies)",
            "dataType": "string",
            "sourceColumn": "Term (start of studies)",
            "displayFolder": "Time variables"
          },
          {
            "name": "Beginning cycle of education",
            "dataType": "string",
            "sourceColumn": "Beginning cycle of education",
            "displayFolder": "Education variables"
          },
          {
            "name": "Extent of the study programme",
            "dataType": "string",
            "sourceColumn": "Extent of the study programme",
            "sortByColumn": "Opiskelun laajuus järjestys",
            "displayFolder": "Education variables"
          },
          {
            "name": "Koodit Koulutusala taso 1 hakukohde",
            "dataType": "string",
            "sourceColumn": "Koodit Koulutusala, taso 1 (hakukohde)",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koodit Koulutusala taso 2 hakukohde",
            "dataType": "string",
            "sourceColumn": "Koodit Koulutusala, taso 2 (hakukohde)",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koodit Koulutusala taso 3 hakukohde",
            "dataType": "string",
            "sourceColumn": "Koodit Koulutusala, taso 3 (hakukohde)",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koodit OKM ohjauksen ala hakukohde",
            "dataType": "string",
            "sourceColumn": "Koodit OKM ohjauksen ala (hakukohde)",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koodit Koulutuksen järjestäjä",
            "dataType": "string",
            "sourceColumn": "Koodit Koulutuksen järjestäjä",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koodit Korkeakoulu",
            "dataType": "string",
            "sourceColumn": "Koodit Korkeakoulu",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koodit Maakunta hakukohde",
            "dataType": "string",
            "sourceColumn": "Koodit Maakunta hakukohde",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koodit Kunta hakukohde",
            "dataType": "string",
            "sourceColumn": "Koodit Kunta hakukohde",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koulutusaste, taso 1",
            "dataType": "string",
            "sourceColumn": "Koulutusaste, taso 1 (hakukohde)",
            "sortByColumn": "Koulutusaste taso 1 järjestys",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusaste, taso 2",
            "dataType": "string",
            "sourceColumn": "Koulutusaste, taso 2 (hakukohde)",
            "sortByColumn": "Koulutusaste taso 2 järjestys",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Utb.nivå, nivå 1",
            "dataType": "string",
            "sourceColumn": "Utb.nivå, nivå 1 (sökobjekt)",
            "sortByColumn": "Koulutusaste taso 1 järjestys",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Utb.nivå, nivå 2",
            "dataType": "string",
            "sourceColumn": "Utb.nivå, nivå 2 (sökobjekt)",
            "sortByColumn": "Koulutusaste taso 2 järjestys",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Level of ed., tier 1",
            "dataType": "string",
            "sourceColumn": "Level of ed., tier 1",
            "sortByColumn": "Koulutusaste taso 1 järjestys",
            "displayFolder": "Education variables"
          },
          {
            "name": "Level of ed., tier 2",
            "dataType": "string",
            "sourceColumn": "Level of ed., tier 2",
            "sortByColumn": "Koulutusaste taso 2 järjestys",
            "displayFolder": "Education variables"
          },
          {
            "name": "Koulutusaste taso 1 järjestys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Koulutusaste, taso 1 järjestys"
          },
          {
            "name": "Koulutusaste taso 2 järjestys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Koulutusaste, taso 2 järjestys"
          },
          {
            "name": "1 Hakukohde",
            "dataType": "string",
            "sourceColumn": "1 Hakukohde",
            "displayFolder": "Hakutoivemuuttujat"
          },
          {
            "name": "1 Koulutusala, taso 1",
            "dataType": "string",
            "sourceColumn": "1 Koulutusala, taso 1",
            "sortByColumn": "1 Koulutusala taso 1 järjestys",
            "displayFolder": "Hakutoivemuuttujat"
          },
          {
            "name": "1 Koulutusala, taso 2",
            "dataType": "string",
            "sourceColumn": "1 Koulutusala, taso 2",
            "sortByColumn": "1 Koulutusala taso 2 järjestys",
            "displayFolder": "Hakutoivemuuttujat"
          },
          {
            "name": "1 Koulutusala, taso 3",
            "dataType": "string",
            "sourceColumn": "1 Koulutusala, taso 3",
            "sortByColumn": "1 Koulutusala taso 3 järjestys",
            "displayFolder": "Hakutoivemuuttujat"
          },
          {
            "name": "2 Hakukohde",
            "dataType": "string",
            "sourceColumn": "2 Hakukohde",
            "displayFolder": "Hakutoivemuuttujat"
          },
          {
            "name": "2 Koulutusala, taso 1",
            "dataType": "string",
            "sourceColumn": "2 Koulutusala, taso 1",
            "sortByColumn": "2 Koulutusala taso 1 järjestys",
            "displayFolder": "Hakutoivemuuttujat"
          },
          {
            "name": "2 Koulutusala, taso 2",
            "dataType": "string",
            "sourceColumn": "2 Koulutusala, taso 2",
            "sortByColumn": "2 Koulutusala taso 2 järjestys",
            "displayFolder": "Hakutoivemuuttujat"
          },
          {
            "name": "2 Koulutusala, taso 3",
            "dataType": "string",
            "sourceColumn": "2 Koulutusala, taso 3",
            "sortByColumn": "2 Koulutusala taso 3 järjestys",
            "displayFolder": "Hakutoivemuuttujat"
          },
          {
            "name": "3 Hakukohde",
            "dataType": "string",
            "sourceColumn": "3 Hakukohde",
            "displayFolder": "Hakutoivemuuttujat"
          },
          {
            "name": "3 Koulutusala, taso 1",
            "dataType": "string",
            "sourceColumn": "3 Koulutusala, taso 1",
            "sortByColumn": "3 Koulutusala taso 1 järjestys",
            "displayFolder": "Hakutoivemuuttujat"
          },
          {
            "name": "3 Koulutusala, taso 2",
            "dataType": "string",
            "sourceColumn": "3 Koulutusala, taso 2",
            "sortByColumn": "3 Koulutusala taso 2 järjestys",
            "displayFolder": "Hakutoivemuuttujat"
          },
          {
            "name": "3 Koulutusala, taso 3",
            "dataType": "string",
            "sourceColumn": "3 Koulutusala, taso 3",
            "sortByColumn": "3 Koulutusala taso 3 järjestys",
            "displayFolder": "Hakutoivemuuttujat"
          },
          {
            "name": "4 Hakukohde",
            "dataType": "string",
            "sourceColumn": "4 Hakukohde",
            "displayFolder": "Hakutoivemuuttujat"
          },
          {
            "name": "4 Koulutusala, taso 1",
            "dataType": "string",
            "sourceColumn": "4 Koulutusala, taso 1",
            "sortByColumn": "4 Koulutusala taso 1 järjestys",
            "displayFolder": "Hakutoivemuuttujat"
          },
          {
            "name": "4 Koulutusala, taso 2",
            "dataType": "string",
            "sourceColumn": "4 Koulutusala, taso 2",
            "sortByColumn": "4 Koulutusala taso 2 järjestys",
            "displayFolder": "Hakutoivemuuttujat"
          },
          {
            "name": "4 Koulutusala, taso 3",
            "dataType": "string",
            "sourceColumn": "4 Koulutusala, taso 3",
            "sortByColumn": "4 Koulutusala taso 3 järjestys",
            "displayFolder": "Hakutoivemuuttujat"
          },
          {
            "name": "5 Hakukohde",
            "dataType": "string",
            "sourceColumn": "5 Hakukohde",
            "displayFolder": "Hakutoivemuuttujat"
          },
          {
            "name": "5 Koulutusala, taso 1",
            "dataType": "string",
            "sourceColumn": "5 Koulutusala, taso 1",
            "sortByColumn": "5 Koulutusala taso 1 järjestys",
            "displayFolder": "Hakutoivemuuttujat"
          },
          {
            "name": "5 Koulutusala, taso 2",
            "dataType": "string",
            "sourceColumn": "5 Koulutusala, taso 2",
            "sortByColumn": "5 Koulutusala taso 2 järjestys",
            "displayFolder": "Hakutoivemuuttujat"
          },
          {
            "name": "5 Koulutusala, taso 3",
            "dataType": "string",
            "sourceColumn": "5 Koulutusala, taso 3",
            "sortByColumn": "5 Koulutusala taso 3 järjestys",
            "displayFolder": "Hakutoivemuuttujat"
          },
          {
            "name": "6 Hakukohde",
            "dataType": "string",
            "sourceColumn": "6 Hakukohde",
            "displayFolder": "Hakutoivemuuttujat"
          },
          {
            "name": "6 Koulutusala, taso 1",
            "dataType": "string",
            "sourceColumn": "6 Koulutusala, taso 1",
            "sortByColumn": "6 Koulutusala taso 1 järjestys",
            "displayFolder": "Hakutoivemuuttujat"
          },
          {
            "name": "6 Koulutusala, taso 2",
            "dataType": "string",
            "sourceColumn": "6 Koulutusala, taso 2",
            "sortByColumn": "6 Koulutusala taso 2 järjestys",
            "displayFolder": "Hakutoivemuuttujat"
          },
          {
            "name": "6 Koulutusala, taso 3",
            "dataType": "string",
            "sourceColumn": "6 Koulutusala, taso 3",
            "sortByColumn": "6 Koulutusala taso 3 järjestys",
            "displayFolder": "Hakutoivemuuttujat"
          },
          {
            "name": "1 Sökobjekt",
            "dataType": "string",
            "sourceColumn": "1 Sökobjekt",
            "displayFolder": "Variabler för ansökningsönskemål"
          },
          {
            "name": "1 Utb.område, nivå 1",
            "dataType": "string",
            "sourceColumn": "1 Utb.område, nivå 1",
            "displayFolder": "Variabler för ansökningsönskemål"
          },
          {
            "name": "1 Utb.område, nivå 2",
            "dataType": "string",
            "sourceColumn": "1 Utb.område, nivå 2",
            "displayFolder": "Variabler för ansökningsönskemål"
          },
          {
            "name": "1 Utb.område, nivå 3",
            "dataType": "string",
            "sourceColumn": "1 Utb.område, nivå 3",
            "displayFolder": "Variabler för ansökningsönskemål"
          },
          {
            "name": "2 Sökobjekt",
            "dataType": "string",
            "sourceColumn": "2 Sökobjekt",
            "displayFolder": "Variabler för ansökningsönskemål"
          },
          {
            "name": "2 Utb.område, nivå 1",
            "dataType": "string",
            "sourceColumn": "2 Utb.område, nivå 1",
            "displayFolder": "Variabler för ansökningsönskemål"
          },
          {
            "name": "2 Utb.område, nivå 2",
            "dataType": "string",
            "sourceColumn": "2 Utb.område, nivå 2",
            "displayFolder": "Variabler för ansökningsönskemål"
          },
          {
            "name": "2 Utb.område, nivå 3",
            "dataType": "string",
            "sourceColumn": "2 Utb.område, nivå 3",
            "displayFolder": "Variabler för ansökningsönskemål"
          },
          {
            "name": "3 Sökobjekt",
            "dataType": "string",
            "sourceColumn": "3 Sökobjekt",
            "displayFolder": "Variabler för ansökningsönskemål"
          },
          {
            "name": "3 Utb.område, nivå 1",
            "dataType": "string",
            "sourceColumn": "3 Utb.område, nivå 1",
            "displayFolder": "Variabler för ansökningsönskemål"
          },
          {
            "name": "3 Utb.område, nivå 2",
            "dataType": "string",
            "sourceColumn": "3 Utb.område, nivå 2",
            "displayFolder": "Variabler för ansökningsönskemål"
          },
          {
            "name": "3 Utb.område, nivå 3",
            "dataType": "string",
            "sourceColumn": "3 Utb.område, nivå 3",
            "displayFolder": "Variabler för ansökningsönskemål"
          },
          {
            "name": "4 Sökobjekt",
            "dataType": "string",
            "sourceColumn": "4 Sökobjekt",
            "displayFolder": "Variabler för ansökningsönskemål"
          },
          {
            "name": "4 Utb.område, nivå 1",
            "dataType": "string",
            "sourceColumn": "4 Utb.område, nivå 1",
            "displayFolder": "Variabler för ansökningsönskemål"
          },
          {
            "name": "4 Utb.område, nivå 2",
            "dataType": "string",
            "sourceColumn": "4 Utb.område, nivå 2",
            "displayFolder": "Variabler för ansökningsönskemål"
          },
          {
            "name": "4 Utb.område, nivå 3",
            "dataType": "string",
            "sourceColumn": "4 Utb.område, nivå 3",
            "displayFolder": "Variabler för ansökningsönskemål"
          },
          {
            "name": "5 Sökobjekt",
            "dataType": "string",
            "sourceColumn": "5 Sökobjekt",
            "displayFolder": "Variabler för ansökningsönskemål"
          },
          {
            "name": "5 Utb.område, nivå 1",
            "dataType": "string",
            "sourceColumn": "5 Utb.område, nivå 1",
            "displayFolder": "Variabler för ansökningsönskemål"
          },
          {
            "name": "5 Utb.område, nivå 2",
            "dataType": "string",
            "sourceColumn": "5 Utb.område, nivå 2",
            "displayFolder": "Variabler för ansökningsönskemål"
          },
          {
            "name": "5 Utb.område, nivå 3",
            "dataType": "string",
            "sourceColumn": "5 Utb.område, nivå 3",
            "displayFolder": "Variabler för ansökningsönskemål"
          },
          {
            "name": "6 Sökobjekt",
            "dataType": "string",
            "sourceColumn": "6 Sökobjekt",
            "displayFolder": "Variabler för ansökningsönskemål"
          },
          {
            "name": "6 Utb.område, nivå 1",
            "dataType": "string",
            "sourceColumn": "6 Utb.område, nivå 1",
            "displayFolder": "Variabler för ansökningsönskemål"
          },
          {
            "name": "6 Utb.område, nivå 2",
            "dataType": "string",
            "sourceColumn": "6 Utb.område, nivå 2",
            "displayFolder": "Variabler för ansökningsönskemål"
          },
          {
            "name": "6 Utb.område, nivå 3",
            "dataType": "string",
            "sourceColumn": "6 Utb.område, nivå 3",
            "displayFolder": "Variabler för ansökningsönskemål"
          },
          {
            "name": "1 Study programme",
            "dataType": "string",
            "sourceColumn": "1 Study programme",
            "displayFolder": "Preference variables"
          },
          {
            "name": "1 Field of ed., tier 1",
            "dataType": "string",
            "sourceColumn": "1 Field of ed., tier 1",
            "displayFolder": "Preference variables"
          },
          {
            "name": "1 Field of ed., tier 2",
            "dataType": "string",
            "sourceColumn": "1 Field of ed., tier 2",
            "displayFolder": "Preference variables"
          },
          {
            "name": "1 Field of ed., tier 3",
            "dataType": "string",
            "sourceColumn": "1 Field of ed., tier 3",
            "displayFolder": "Preference variables"
          },
          {
            "name": "2 Study programme",
            "dataType": "string",
            "sourceColumn": "2 Study programme",
            "displayFolder": "Preference variables"
          },
          {
            "name": "2 Field of ed., tier 1",
            "dataType": "string",
            "sourceColumn": "2 Field of ed., tier 1",
            "displayFolder": "Preference variables"
          },
          {
            "name": "2 Field of ed., tier 2",
            "dataType": "string",
            "sourceColumn": "2 Field of ed., tier 2",
            "displayFolder": "Preference variables"
          },
          {
            "name": "2 Field of ed., tier 3",
            "dataType": "string",
            "sourceColumn": "2 Field of ed., tier 3",
            "displayFolder": "Preference variables"
          },
          {
            "name": "3 Study programme",
            "dataType": "string",
            "sourceColumn": "3 Study programme",
            "displayFolder": "Preference variables"
          },
          {
            "name": "3 Field of ed., tier 1",
            "dataType": "string",
            "sourceColumn": "3 Field of ed., tier 1",
            "displayFolder": "Preference variables"
          },
          {
            "name": "3 Field of ed., tier 2",
            "dataType": "string",
            "sourceColumn": "3 Field of ed., tier 2",
            "displayFolder": "Preference variables"
          },
          {
            "name": "3 Field of ed., tier 3",
            "dataType": "string",
            "sourceColumn": "3 Field of ed., tier 3",
            "displayFolder": "Preference variables"
          },
          {
            "name": "4 Study programme",
            "dataType": "string",
            "sourceColumn": "4 Study programme",
            "displayFolder": "Preference variables"
          },
          {
            "name": "4 Field of ed., tier 1",
            "dataType": "string",
            "sourceColumn": "4 Field of ed., tier 1",
            "displayFolder": "Preference variables"
          },
          {
            "name": "4 Field of ed., tier 2",
            "dataType": "string",
            "sourceColumn": "4 Field of ed., tier 2",
            "displayFolder": "Preference variables"
          },
          {
            "name": "4 Field of ed., tier 3",
            "dataType": "string",
            "sourceColumn": "4 Field of ed., tier 3",
            "displayFolder": "Preference variables"
          },
          {
            "name": "5 Study programme",
            "dataType": "string",
            "sourceColumn": "5 Study programme",
            "displayFolder": "Preference variables"
          },
          {
            "name": "5 Field of ed., tier 1",
            "dataType": "string",
            "sourceColumn": "5 Field of ed., tier 1",
            "displayFolder": "Preference variables"
          },
          {
            "name": "5 Field of ed., tier 2",
            "dataType": "string",
            "sourceColumn": "5 Field of ed., tier 2",
            "displayFolder": "Preference variables"
          },
          {
            "name": "5 Field of ed., tier 3",
            "dataType": "string",
            "sourceColumn": "5 Field of ed., tier 3",
            "displayFolder": "Preference variables"
          },
          {
            "name": "6 Study programme",
            "dataType": "string",
            "sourceColumn": "6 Study programme",
            "displayFolder": "Preference variables"
          },
          {
            "name": "6 Field of ed., tier 1",
            "dataType": "string",
            "sourceColumn": "6 Field of ed., tier 1",
            "displayFolder": "Preference variables"
          },
          {
            "name": "6 Field of ed., tier 2",
            "dataType": "string",
            "sourceColumn": "6 Field of ed., tier 2",
            "displayFolder": "Preference variables"
          },
          {
            "name": "6 Field of ed., tier 3",
            "dataType": "string",
            "sourceColumn": "6 Field of ed., tier 3",
            "displayFolder": "Preference variables"
          },
          {
            "name": "1 Koulutusala taso 1 järjestys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "1 Koulutusala, taso 1 järjestys"
          },
          {
            "name": "1 Koulutusala taso 2 järjestys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "1 Koulutusala, taso 2 järjestys"
          },
          {
            "name": "1 Koulutusala taso 3 järjestys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "1 Koulutusala, taso 3 järjestys"
          },
          {
            "name": "2 Koulutusala taso 1 järjestys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "2 Koulutusala, taso 1 järjestys"
          },
          {
            "name": "2 Koulutusala taso 2 järjestys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "2 Koulutusala, taso 2 järjestys"
          },
          {
            "name": "2 Koulutusala taso 3 järjestys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "2 Koulutusala, taso 3 järjestys"
          },
          {
            "name": "3 Koulutusala taso 1 järjestys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "3 Koulutusala, taso 1 järjestys"
          },
          {
            "name": "3 Koulutusala taso 2 järjestys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "3 Koulutusala, taso 2 järjestys"
          },
          {
            "name": "3 Koulutusala taso 3 järjestys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "3 Koulutusala, taso 3 järjestys"
          },
          {
            "name": "4 Koulutusala taso 1 järjestys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "4 Koulutusala, taso 1 järjestys"
          },
          {
            "name": "4 Koulutusala taso 2 järjestys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "4 Koulutusala, taso 2 järjestys"
          },
          {
            "name": "4 Koulutusala taso 3 järjestys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "4 Koulutusala, taso 3 järjestys"
          },
          {
            "name": "5 Koulutusala taso 1 järjestys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "5 Koulutusala, taso 1 järjestys"
          },
          {
            "name": "5 Koulutusala taso 2 järjestys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "5 Koulutusala, taso 2 järjestys"
          },
          {
            "name": "5 Koulutusala taso 3 järjestys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "5 Koulutusala, taso 3 järjestys"
          },
          {
            "name": "6 Koulutusala taso 1 järjestys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "6 Koulutusala, taso 1 järjestys"
          },
          {
            "name": "6 Koulutusala taso 2 järjestys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "6 Koulutusala, taso 2 järjestys"
          },
          {
            "name": "6 Koulutusala taso 3 järjestys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "6 Koulutusala, taso 3 järjestys"
          },
          {
            "name": "Päivitysaika",
            "dataType": "dateTime",
            "sourceColumn": "Päivitysaika",
            "displayFolder": "Aikamuuttujat"
          },
          {
            "name": "Hakutoive järjestys",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Hakutoive järjestys"
          },
          {
            "name": "Pohjakoulutuksen maa järjestys",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Pohjakoulutuksen maa järjestys"
          },
          {
            "name": "Sektori järjestys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Sektori järjestys"
          },
          {
            "name": "Tutkinnon aloitussykli hakukohde järjestys",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Tutkinnon aloitussykli (hakukohde) järjestys"
          },
          {
            "name": "1 Sektori",
            "dataType": "string",
            "sourceColumn": "1 Sektori",
            "displayFolder": "Hakutoivemuuttujat"
          },
          {
            "name": "1 Aloitussykli",
            "dataType": "string",
            "sourceColumn": "1 Aloitussykli",
            "displayFolder": "Hakutoivemuuttujat"
          },
          {
            "name": "1 Korkeakoulu",
            "dataType": "string",
            "sourceColumn": "1 Korkeakoulu",
            "displayFolder": "Hakutoivemuuttujat"
          },
          {
            "name": "2 Sektori",
            "dataType": "string",
            "sourceColumn": "2 Sektori",
            "displayFolder": "Hakutoivemuuttujat"
          },
          {
            "name": "2 Aloitussykli",
            "dataType": "string",
            "sourceColumn": "2 Aloitussykli",
            "displayFolder": "Hakutoivemuuttujat"
          },
          {
            "name": "2 Korkeakoulu",
            "dataType": "string",
            "sourceColumn": "2 Korkeakoulu",
            "displayFolder": "Hakutoivemuuttujat"
          },
          {
            "name": "3 Sektori",
            "dataType": "string",
            "sourceColumn": "3 Sektori",
            "displayFolder": "Hakutoivemuuttujat"
          },
          {
            "name": "3 Aloitussykli",
            "dataType": "string",
            "sourceColumn": "3 Aloitussykli",
            "displayFolder": "Hakutoivemuuttujat"
          },
          {
            "name": "3 Korkeakoulu",
            "dataType": "string",
            "sourceColumn": "3 Korkeakoulu",
            "displayFolder": "Hakutoivemuuttujat"
          },
          {
            "name": "4 Sektori",
            "dataType": "string",
            "sourceColumn": "4 Sektori",
            "displayFolder": "Hakutoivemuuttujat"
          },
          {
            "name": "4 Aloitussykli",
            "dataType": "string",
            "sourceColumn": "4 Aloitussykli",
            "displayFolder": "Hakutoivemuuttujat"
          },
          {
            "name": "4 Korkeakoulu",
            "dataType": "string",
            "sourceColumn": "4 Korkeakoulu",
            "displayFolder": "Hakutoivemuuttujat"
          },
          {
            "name": "5 Sektori",
            "dataType": "string",
            "sourceColumn": "5 Sektori",
            "displayFolder": "Hakutoivemuuttujat"
          },
          {
            "name": "5 Aloitussykli",
            "dataType": "string",
            "sourceColumn": "5 Aloitussykli",
            "displayFolder": "Hakutoivemuuttujat"
          },
          {
            "name": "5 Korkeakoulu",
            "dataType": "string",
            "sourceColumn": "5 Korkeakoulu",
            "displayFolder": "Hakutoivemuuttujat"
          },
          {
            "name": "6 Sektori",
            "dataType": "string",
            "sourceColumn": "6 Sektori",
            "displayFolder": "Hakutoivemuuttujat"
          },
          {
            "name": "6 Aloitussykli",
            "dataType": "string",
            "sourceColumn": "6 Aloitussykli",
            "displayFolder": "Hakutoivemuuttujat"
          },
          {
            "name": "6 Korkeakoulu",
            "dataType": "string",
            "sourceColumn": "6 Korkeakoulu",
            "displayFolder": "Hakutoivemuuttujat"
          },
          {
            "name": "1 Sektor",
            "dataType": "string",
            "sourceColumn": "1 Sektor",
            "displayFolder": "Variabler för ansökningsönskemål"
          },
          {
            "name": "1 Cykeln",
            "dataType": "string",
            "sourceColumn": "1 Cykeln",
            "displayFolder": "Variabler för ansökningsönskemål"
          },
          {
            "name": "1 Högskola",
            "dataType": "string",
            "sourceColumn": "1 Högskola",
            "displayFolder": "Variabler för ansökningsönskemål"
          },
          {
            "name": "2 Sektor",
            "dataType": "string",
            "sourceColumn": "2 Sektor",
            "displayFolder": "Variabler för ansökningsönskemål"
          },
          {
            "name": "2 Cykeln",
            "dataType": "string",
            "sourceColumn": "2 Cykeln",
            "displayFolder": "Variabler för ansökningsönskemål"
          },
          {
            "name": "2 Högskola",
            "dataType": "string",
            "sourceColumn": "2 Högskola",
            "displayFolder": "Variabler för ansökningsönskemål"
          },
          {
            "name": "3 Sektor",
            "dataType": "string",
            "sourceColumn": "3 Sektor",
            "displayFolder": "Variabler för ansökningsönskemål"
          },
          {
            "name": "3 Cykeln",
            "dataType": "string",
            "sourceColumn": "3 Cykeln",
            "displayFolder": "Variabler för ansökningsönskemål"
          },
          {
            "name": "3 Högskola",
            "dataType": "string",
            "sourceColumn": "3 Högskola",
            "displayFolder": "Variabler för ansökningsönskemål"
          },
          {
            "name": "4 Sektor",
            "dataType": "string",
            "sourceColumn": "4 Sektor",
            "displayFolder": "Variabler för ansökningsönskemål"
          },
          {
            "name": "4 Cykeln",
            "dataType": "string",
            "sourceColumn": "4 Cykeln",
            "displayFolder": "Variabler för ansökningsönskemål"
          },
          {
            "name": "4 Högskola",
            "dataType": "string",
            "sourceColumn": "4 Högskola",
            "displayFolder": "Variabler för ansökningsönskemål"
          },
          {
            "name": "5 Sektor",
            "dataType": "string",
            "sourceColumn": "5 Sektor",
            "displayFolder": "Variabler för ansökningsönskemål"
          },
          {
            "name": "5 Cykeln",
            "dataType": "string",
            "sourceColumn": "5 Cykeln",
            "displayFolder": "Variabler för ansökningsönskemål"
          },
          {
            "name": "5 Högskola",
            "dataType": "string",
            "sourceColumn": "5 Högskola",
            "displayFolder": "Variabler för ansökningsönskemål"
          },
          {
            "name": "6 Sektor",
            "dataType": "string",
            "sourceColumn": "6 Sektor",
            "displayFolder": "Variabler för ansökningsönskemål"
          },
          {
            "name": "6 Cykeln",
            "dataType": "string",
            "sourceColumn": "6 Cykeln",
            "displayFolder": "Variabler för ansökningsönskemål"
          },
          {
            "name": "6 Högskola",
            "dataType": "string",
            "sourceColumn": "6 Högskola",
            "displayFolder": "Variabler för ansökningsönskemål"
          },
          {
            "name": "1 Sector",
            "dataType": "string",
            "sourceColumn": "1 Sector",
            "displayFolder": "Preference variables"
          },
          {
            "name": "1 Beginning cycle",
            "dataType": "string",
            "sourceColumn": "1 Beginning cycle",
            "displayFolder": "Preference variables"
          },
          {
            "name": "1 HE institution",
            "dataType": "string",
            "sourceColumn": "1 HE institution",
            "displayFolder": "Preference variables"
          },
          {
            "name": "2 Sector",
            "dataType": "string",
            "sourceColumn": "2 Sector",
            "displayFolder": "Preference variables"
          },
          {
            "name": "2 Beginning cycle",
            "dataType": "string",
            "sourceColumn": "2 Beginning cycle",
            "displayFolder": "Preference variables"
          },
          {
            "name": "2 HE institution",
            "dataType": "string",
            "sourceColumn": "2 HE institution",
            "displayFolder": "Preference variables"
          },
          {
            "name": "3 Sector",
            "dataType": "string",
            "sourceColumn": "3 Sector",
            "displayFolder": "Preference variables"
          },
          {
            "name": "3 Beginning cycle",
            "dataType": "string",
            "sourceColumn": "3 Beginning cycle",
            "displayFolder": "Preference variables"
          },
          {
            "name": "3 HE institution",
            "dataType": "string",
            "sourceColumn": "3 HE institution",
            "displayFolder": "Preference variables"
          },
          {
            "name": "4 Sector",
            "dataType": "string",
            "sourceColumn": "4 Sector",
            "displayFolder": "Preference variables"
          },
          {
            "name": "4 Beginning cycle",
            "dataType": "string",
            "sourceColumn": "4 Beginning cycle",
            "displayFolder": "Preference variables"
          },
          {
            "name": "4 HE institution",
            "dataType": "string",
            "sourceColumn": "4 HE institution",
            "displayFolder": "Preference variables"
          },
          {
            "name": "5 Sector",
            "dataType": "string",
            "sourceColumn": "5 Sector",
            "displayFolder": "Preference variables"
          },
          {
            "name": "5 Beginning cycle",
            "dataType": "string",
            "sourceColumn": "5 Beginning cycle",
            "displayFolder": "Preference variables"
          },
          {
            "name": "5 HE institution",
            "dataType": "string",
            "sourceColumn": "5 HE institution",
            "displayFolder": "Preference variables"
          },
          {
            "name": "6 Sector",
            "dataType": "string",
            "sourceColumn": "6 Sector",
            "displayFolder": "Preference variables"
          },
          {
            "name": "6 Beginning cycle",
            "dataType": "string",
            "sourceColumn": "6 Beginning cycle",
            "displayFolder": "Preference variables"
          },
          {
            "name": "6 HE institution",
            "dataType": "string",
            "sourceColumn": "6 HE institution",
            "displayFolder": "Preference variables"
          },
          {
            "name": "Pisteraja",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Pisteraja"
          },
          {
            "name": "Haku OID",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Haku OID"
          },
          {
            "name": "Pisteet",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Pisteet"
          },
          {
            "name": "Yo-tutk. suor.vuosi (YTL)",
            "dataType": "string",
            "sourceColumn": "Ylioppilastutkinnon suoritusvuosi",
            "sortByColumn": "Ylioppilastutkinnon suoritusvuosi järjestys",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Valintatapajono järjestys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Valintatapajono järjestys"
          },
          {
            "name": "Hakijan kotimaakunta sama kuin hakukohteen maakunta",
            "dataType": "string",
            "sourceColumn": "Hakijan kotimaakunta sama kuin hakukohteen maakunta",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Ylioppilastutkinnon suoritusvuosi järjestys",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Ylioppilastutkinnon suoritusvuosi järjestys"
          },
          {
            "name": "Valintatapajonon nimi",
            "dataType": "string",
            "sourceColumn": "Valintatapajonon nimi",
            "displayFolder": "Hakumuuttujat"
          },
          {
            "name": "Valintatapajonon tyyppi",
            "dataType": "string",
            "sourceColumn": "Valintatapajonon tyyppi",
            "sortByColumn": "Valintatapajono järjestys",
            "displayFolder": "Hakumuuttujat"
          },
          {
            "name": "Type of admission queue",
            "dataType": "string",
            "sourceColumn": "Type of admission queue",
            "displayFolder": "Application variables"
          },
          {
            "name": "Typ av antagningskö",
            "dataType": "string",
            "sourceColumn": "Typ av antagningskö",
            "displayFolder": "Ansökningsvariabler"
          },
          {
            "name": "Namnet på antagningskö",
            "dataType": "string",
            "sourceColumn": "Namnet på antagningskö",
            "displayFolder": "Ansökningsvariabler"
          },
          {
            "name": "uusi ylioppilas2",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "uusi ylioppilas"
          },
          {
            "name": "aidosti ensikertainen",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "aidosti ensikertainen"
          },
          {
            "name": "sama kuin 1 hakukohteen sektori",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "sama kuin 1 hakukohteen sektori"
          },
          {
            "name": "sama kuin 1 hakukohteen kk",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "sama kuin 1 hakukohteen kk"
          },
          {
            "name": "sama kuin 1 hakukohteen koulutusala1",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "sama kuin 1 hakukohteen koulutusala1"
          },
          {
            "name": "ei vastaanottoa kaudella",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ei vastaanottoa kaudella"
          },
          {
            "type": "calculated",
            "name": "Uusi ylioppilas",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "IF([uusi ylioppilas2]=1,\"Kyllä\",\"Ei\")",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Aloittanut opinnot toisen asteen koulutuksen suoritusvuonna",
            "dataType": "string",
            "sourceColumn": "Aloittanut opinnot toisen asteen koulutuksen suoritusvuonna"
          },
          {
            "name": "Aloittanut opinnot ilmoittamansa pohjakoulutuksen suoritusvuonna",
            "dataType": "string",
            "sourceColumn": "Aloittanut opinnot ilmoittamansa pohjakoulutuksen suoritusvuonna"
          },
          {
            "name": "Valitut2_indikaattori",
            "dataType": "int64",
            "sourceColumn": "Valitut2_indikaattori"
          },
          {
            "name": "Paikan vastaanottaneet2_indikaattori",
            "dataType": "int64",
            "sourceColumn": "Paikan vastaanottaneet2_indikaattori"
          },
          {
            "type": "calculated",
            "name": "Henkilö OID_Hakukohde OID",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": [
              "",
              "CONCATENATE([Henkilö OID], [hakukohde OID])"
            ]
          },
          {
            "name": "Haun kohdejoukon tarkenne",
            "dataType": "string",
            "sourceColumn": "Haun kohdejoukon tarkenne",
            "displayFolder": "Hakumuuttujat"
          },
          {
            "name": "Ansökans målgrupps specifikation",
            "dataType": "string",
            "sourceColumn": "Ansökans målgrupps specifikation",
            "displayFolder": "Ansökningsvariabler"
          },
          {
            "name": "Applied study programme group specification",
            "dataType": "string",
            "sourceColumn": "Applied study programme group specification",
            "displayFolder": "Application variables"
          },
          {
            "name": "Pääasiallinen tutkinto (hakukohde)",
            "dataType": "string",
            "sourceColumn": "Pääasiallinen tutkinto (hakukohde)",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Huvudsaklig examen (ansökningsmål)",
            "dataType": "string",
            "sourceColumn": "Huvudsaklig examen (ansökningsmål)",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Main degree (applied study programme)",
            "dataType": "string",
            "sourceColumn": "Main degree (applied study programme)",
            "displayFolder": "Education variables"
          },
          {
            "name": "Koodit Pääasiallinen koulutusnimike",
            "dataType": "string",
            "sourceColumn": "Koodit Pääasiallinen koulutusnimike",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "visualisoinnit",
            "dataType": "int64",
            "sourceColumn": "visualisoinnit"
          },
          {
            "name": "Ikä*",
            "dataType": "string",
            "sourceColumn": "Ikä",
            "sortByColumn": "Ikä järjestys",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Ikäryhmä*",
            "dataType": "string",
            "sourceColumn": "Ikäryhmä",
            "sortByColumn": "Ikä 5v järjestys",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Pohjakoulutus*",
            "dataType": "string",
            "sourceColumn": "Pohjakoulutus",
            "sortByColumn": "Pohjakoulutus järjestys",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Pohjakoulutuksen maa*",
            "dataType": "string",
            "sourceColumn": "Pohjakoulutuksen maa",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Toisen asteen koulutuksen suoritusvuosi*",
            "dataType": "string",
            "sourceColumn": "Toisen asteen koulutuksen suoritusvuosi",
            "sortByColumn": "Toisen asteen koulutuksen suoritusvuosi järjestys",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Åldersgrupp*",
            "dataType": "string",
            "sourceColumn": "Åldersgrupp",
            "displayFolder": "Personvariabler"
          },
          {
            "name": "Hemkommun*",
            "dataType": "string",
            "sourceColumn": "Hemkommun",
            "displayFolder": "Personvariabler"
          },
          {
            "name": "Hemlandskap*",
            "dataType": "string",
            "sourceColumn": "Hemlandskap",
            "sortByColumn": "Kotipaikan maakunta järjestys",
            "displayFolder": "Personvariabler"
          },
          {
            "name": "Grundutbildningens land*",
            "dataType": "string",
            "sourceColumn": "Grundutbildningens land",
            "displayFolder": "Personvariabler"
          },
          {
            "name": "Grundutbildning*",
            "dataType": "string",
            "sourceColumn": "Grundutbildning",
            "displayFolder": "Personvariabler"
          },
          {
            "name": "År då andra stadiets utbildning avlagts*",
            "dataType": "string",
            "sourceColumn": "År då andra stadiets utbildning avlagts",
            "sortByColumn": "Toisen asteen koulutuksen suoritusvuosi järjestys",
            "displayFolder": "Personvariabler"
          },
          {
            "name": "Age group*",
            "dataType": "string",
            "sourceColumn": "Age group",
            "sortByColumn": "Ikä 5v järjestys",
            "displayFolder": "Person variables"
          },
          {
            "name": "Municipality of residence*",
            "dataType": "string",
            "sourceColumn": "Municipality of residence",
            "displayFolder": "Person variables"
          },
          {
            "name": "Region of residence*",
            "dataType": "string",
            "sourceColumn": "Region of residence",
            "sortByColumn": "Kotipaikan maakunta järjestys",
            "displayFolder": "Person variables"
          },
          {
            "name": "Country of prior education*",
            "dataType": "string",
            "sourceColumn": "Country of prior education",
            "displayFolder": "Person variables"
          },
          {
            "name": "Prior education*",
            "dataType": "string",
            "sourceColumn": "Prior education",
            "sortByColumn": "Pohjakoulutus järjestys",
            "displayFolder": "Person variables"
          },
          {
            "name": "Koodit Kotimaakunta hakija*",
            "dataType": "string",
            "sourceColumn": "Koodit Kotimaakunta hakija",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koodit Kotikunta hakija*",
            "dataType": "string",
            "sourceColumn": "Koodit Kotikunta hakija",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Pohjakoulutuksen maa (priorisoitu)*",
            "dataType": "string",
            "sourceColumn": "Pohjakoulutuksen maa (priorisoitu)",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Grundutbildningens land (prioriterat)*",
            "dataType": "string",
            "sourceColumn": "Grundutbildningens land (prioriterat)",
            "displayFolder": "Personvariabler"
          },
          {
            "name": "Country of prior education (prioritised)*",
            "dataType": "string",
            "sourceColumn": "Country of prior education (prioritised)",
            "displayFolder": "Person variables"
          },
          {
            "name": "Kotipaikkakunta (hakija)*",
            "dataType": "string",
            "sourceColumn": "Kotipaikkakunta",
            "sortByColumn": "Kotipaikkakunta järjestys",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Kotipaikan maakunta (hakija)*",
            "dataType": "string",
            "sourceColumn": "Kotipaikan maakunta",
            "sortByColumn": "Kotipaikan maakunta järjestys",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Graduation year (upper secondary education)*",
            "dataType": "string",
            "sourceColumn": "Graduation year (upper secondary education)",
            "sortByColumn": "Toisen asteen koulutuksen suoritusvuosi järjestys",
            "displayFolder": "Person variables"
          },
          {
            "name": "Studier som högskolan kräver vid en öppen högskola*",
            "dataType": "string",
            "sourceColumn": "Studier som högskolan kräver vid en öppen högskola*",
            "sortByColumn": "pohjakoulutus_avoin järjestys",
            "displayFolder": "Personvariabler\\Grundutbildningsvariabler"
          },
          {
            "name": "pohjakoulutus_am järjestys",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "pohjakoulutus_am järjestys"
          },
          {
            "name": "pohjakoulutus_amp järjestys",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "pohjakoulutus_amp järjestys"
          },
          {
            "name": "pohjakoulutus_amt järjestys",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "pohjakoulutus_amt järjestys"
          },
          {
            "name": "pohjakoulutus_amv järjestys",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "pohjakoulutus_amv järjestys"
          },
          {
            "name": "pohjakoulutus_avoin järjestys",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "pohjakoulutus_avoin järjestys"
          },
          {
            "name": "pohjakoulutus_kk järjestys",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "pohjakoulutus_kk järjestys"
          },
          {
            "name": "pohjakoulutus_kk_ulk järjestys",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "pohjakoulutus_kk_ulk järjestys"
          },
          {
            "name": "pohjakoulutus_lk järjestys",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "pohjakoulutus_lk järjestys"
          },
          {
            "name": "pohjakoulutus_ulk järjestys",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "pohjakoulutus_ulk järjestys"
          },
          {
            "name": "pohjakoulutus_yo järjestys",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "pohjakoulutus_yo järjestys"
          },
          {
            "name": "pohjakoulutus_yo_ammatillinen järjestys",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "pohjakoulutus_yo_ammatillinen järjestys"
          },
          {
            "name": "pohjakoulutus_yo_kansainvalinen_suomessa järjestys",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "pohjakoulutus_yo_kansainvalinen_suomessa järjestys"
          },
          {
            "name": "pohjakoulutus_yo_ulkomainen järjestys",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "pohjakoulutus_yo_ulkomainen järjestys"
          },
          {
            "name": "pohjakoulutus_muu järjestys",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "pohjakoulutus_muu järjestys"
          },
          {
            "name": "Suomessa suoritettu ammatillinen perustutkinto, kouluasteen, opistoasteen tai ammatillisen korkea-asteen tutkinto*",
            "dataType": "string",
            "sourceColumn": "Suomessa suoritettu ammatillinen perustutkinto, kouluasteen, opistoasteen tai ammatillisen korkea-asteen tutkinto*",
            "sortByColumn": "pohjakoulutus_am järjestys",
            "displayFolder": "Henkilömuuttujat\\Pohjakoulutusmuuttujat"
          },
          {
            "name": "Suomessa suoritettu ammatillinen perustutkinto*",
            "dataType": "string",
            "sourceColumn": "Suomessa suoritettu ammatillinen perustutkinto*",
            "sortByColumn": "pohjakoulutus_amp järjestys",
            "displayFolder": "Henkilömuuttujat\\Pohjakoulutusmuuttujat"
          },
          {
            "name": "Suomessa suoritettu ammatti- tai erikoisammattitutkinto*",
            "dataType": "string",
            "sourceColumn": "Suomessa suoritettu ammatti- tai erikoisammattitutkinto*",
            "sortByColumn": "pohjakoulutus_amt järjestys",
            "displayFolder": "Henkilömuuttujat\\Pohjakoulutusmuuttujat"
          },
          {
            "name": "Suomessa suoritettu kouluasteen, opistoasteen tai ammatillisen korkea-asteen tutkinto*",
            "dataType": "string",
            "sourceColumn": "Suomessa suoritettu kouluasteen, opistoasteen tai ammatillisen korkea-asteen tutkinto*",
            "sortByColumn": "pohjakoulutus_amv järjestys",
            "displayFolder": "Henkilömuuttujat\\Pohjakoulutusmuuttujat"
          },
          {
            "name": "Korkeakoulun edellyttämät avoimen korkeakoulun opinnot*",
            "dataType": "string",
            "sourceColumn": "Korkeakoulun edellyttämät avoimen korkeakoulun opinnot*",
            "sortByColumn": "pohjakoulutus_avoin järjestys",
            "displayFolder": "Henkilömuuttujat\\Pohjakoulutusmuuttujat"
          },
          {
            "name": "Suomessa suoritettu korkeakoulututkinto*",
            "dataType": "string",
            "sourceColumn": "Suomessa suoritettu korkeakoulututkinto*",
            "sortByColumn": "pohjakoulutus_kk järjestys",
            "displayFolder": "Henkilömuuttujat\\Pohjakoulutusmuuttujat"
          },
          {
            "name": "Muualla kuin Suomessa suoritettu korkeakoulututkinto*",
            "dataType": "string",
            "sourceColumn": "Muualla kuin Suomessa suoritettu korkeakoulututkinto*",
            "sortByColumn": "pohjakoulutus_kk_ulk järjestys",
            "displayFolder": "Henkilömuuttujat\\Pohjakoulutusmuuttujat"
          },
          {
            "name": "Suomessa suoritettu lukion oppimäärä ilman ylioppilastutkintoa*",
            "dataType": "string",
            "sourceColumn": "Suomessa suoritettu lukion oppimäärä ilman ylioppilastutkintoa*",
            "sortByColumn": "pohjakoulutus_lk järjestys",
            "displayFolder": "Henkilömuuttujat\\Pohjakoulutusmuuttujat"
          },
          {
            "name": "Muualla kuin Suomessa suoritettu toisen asteen koulutus, joka asianomaisessa maassa antaa hakukelpoisuuden korkeakouluun*",
            "dataType": "string",
            "sourceColumn": "Muualla kuin Suomessa suoritettu toisen asteen koulutus, joka asianomaisessa maassa antaa hakukelpoisuuden korkeakouluun*",
            "sortByColumn": "pohjakoulutus_ulk järjestys",
            "displayFolder": "Henkilömuuttujat\\Pohjakoulutusmuuttujat"
          },
          {
            "name": "Suomessa suoritettu ylioppilastutkinto*",
            "dataType": "string",
            "sourceColumn": "Suomessa suoritettu ylioppilastutkinto*",
            "sortByColumn": "pohjakoulutus_yo järjestys",
            "displayFolder": "Henkilömuuttujat\\Pohjakoulutusmuuttujat"
          },
          {
            "name": "Suomessa suoritettu kaksoistutkinto (ammatillinen perustutkinto ja ylioppilastutkinto)*",
            "dataType": "string",
            "sourceColumn": "Suomessa suoritettu kaksoistutkinto (ammatillinen perustutkinto ja ylioppilastutkinto)*",
            "sortByColumn": "pohjakoulutus_yo_ammatillinen järjestys",
            "displayFolder": "Henkilömuuttujat\\Pohjakoulutusmuuttujat"
          },
          {
            "name": "Suomessa suoritettu kansainvälinen ylioppilastutkinto (IB, EB ja RP/DIA)*",
            "dataType": "string",
            "sourceColumn": "Suomessa suoritettu kansainvälinen ylioppilastutkinto (IB, EB ja RP/DIA)*",
            "sortByColumn": "pohjakoulutus_yo_kansainvalinen_suomessa järjestys",
            "displayFolder": "Henkilömuuttujat\\Pohjakoulutusmuuttujat"
          },
          {
            "name": "Muualla kuin Suomessa suoritettu kansainvälinen ylioppilastutkinto (IB, EB ja RP/DIA)*",
            "dataType": "string",
            "sourceColumn": "Muualla kuin Suomessa suoritettu kansainvälinen ylioppilastutkinto (IB, EB ja RP/DIA)*",
            "sortByColumn": "pohjakoulutus_yo_ulkomainen järjestys",
            "displayFolder": "Henkilömuuttujat\\Pohjakoulutusmuuttujat"
          },
          {
            "name": "Muu korkeakoulukelpoisuus*",
            "dataType": "string",
            "sourceColumn": "Muu korkeakoulukelpoisuus*",
            "sortByColumn": "pohjakoulutus_muu järjestys",
            "displayFolder": "Henkilömuuttujat\\Pohjakoulutusmuuttujat"
          },
          {
            "name": "Yrkesinr. grundex., examen på skolnivå, examen på institutsnivå eller yrkesinr. examen på högre nivå som avlagts i Finland*",
            "dataType": "string",
            "sourceColumn": "Yrkesinr. grundex., examen på skolnivå, examen på institutsnivå eller yrkesinr. examen på högre nivå som avlagts i Finland*",
            "sortByColumn": "pohjakoulutus_am järjestys",
            "displayFolder": "Personvariabler\\Grundutbildningsvariabler"
          },
          {
            "name": "Yrkesinriktad grundexamen som avlagts i Finland*",
            "dataType": "string",
            "sourceColumn": "Yrkesinriktad grundexamen som avlagts i Finland*",
            "sortByColumn": "pohjakoulutus_amp järjestys",
            "displayFolder": "Personvariabler\\Grundutbildningsvariabler"
          },
          {
            "name": "Yrkesexamen eller specialyrkesexamen som avlagts i Finland*",
            "dataType": "string",
            "sourceColumn": "Yrkesexamen eller specialyrkesexamen som avlagts i Finland*",
            "sortByColumn": "pohjakoulutus_amt järjestys",
            "displayFolder": "Personvariabler\\Grundutbildningsvariabler"
          },
          {
            "name": "Yrkesinriktad examen på skolnivå, examen på institutsnivå eller yrkesinriktad examen på högre nivå som avlagts i Finland*",
            "dataType": "string",
            "sourceColumn": "Yrkesinriktad examen på skolnivå, examen på institutsnivå eller yrkesinriktad examen på högre nivå som avlagts i Finland*",
            "sortByColumn": "pohjakoulutus_amv järjestys",
            "displayFolder": "Personvariabler\\Grundutbildningsvariabler"
          },
          {
            "name": "Högskoleexamen som avlagts i Finland*",
            "dataType": "string",
            "sourceColumn": "Högskoleexamen som avlagts i Finland*",
            "sortByColumn": "pohjakoulutus_kk järjestys",
            "displayFolder": "Personvariabler\\Grundutbildningsvariabler"
          },
          {
            "name": "Högskoleexamen som avlagts annanstans än i Finland*",
            "dataType": "string",
            "sourceColumn": "Högskoleexamen som avlagts annanstans än i Finland*",
            "sortByColumn": "pohjakoulutus_kk_ulk järjestys",
            "displayFolder": "Personvariabler\\Grundutbildningsvariabler"
          },
          {
            "name": "Gymnasiets lärokurs som avlagts i Finland utan studentexamen*",
            "dataType": "string",
            "sourceColumn": "Gymnasiets lärokurs som avlagts i Finland utan studentexamen*",
            "sortByColumn": "pohjakoulutus_lk järjestys",
            "displayFolder": "Personvariabler\\Grundutbildningsvariabler"
          },
          {
            "name": "Utbildning på andra stadiet som avlagts annanstans än i Finland, och ger behörighet för högskolestudier i ifrågavarande land*",
            "dataType": "string",
            "sourceColumn": "Utbildning på andra stadiet som avlagts annanstans än i Finland, och ger behörighet för högskolestudier i ifrågavarande land*",
            "sortByColumn": "pohjakoulutus_ulk järjestys",
            "displayFolder": "Personvariabler\\Grundutbildningsvariabler"
          },
          {
            "name": "Studentexamen som avlagts i Finland*",
            "dataType": "string",
            "sourceColumn": "Studentexamen som avlagts i Finland*",
            "sortByColumn": "pohjakoulutus_yo järjestys",
            "displayFolder": "Personvariabler\\Grundutbildningsvariabler"
          },
          {
            "name": "Dubbelexamen som avlagts i Finland*",
            "dataType": "string",
            "sourceColumn": "Dubbelexamen som avlagts i Finland*",
            "sortByColumn": "pohjakoulutus_yo_ammatillinen järjestys",
            "displayFolder": "Personvariabler\\Grundutbildningsvariabler"
          },
          {
            "name": "Internationell studentexamen som avlagts i Finland (IB, EB och RP/DIA)*",
            "dataType": "string",
            "sourceColumn": "Internationell studentexamen som avlagts i Finland (IB, EB och RP/DIA)*",
            "sortByColumn": "pohjakoulutus_yo_kansainvalinen_suomessa järjestys",
            "displayFolder": "Personvariabler\\Grundutbildningsvariabler"
          },
          {
            "name": "Internationell studentexamen som avlagts annanstans än i Finland (IB, EB och RP/DIA)*",
            "dataType": "string",
            "sourceColumn": "Internationell studentexamen som avlagts annanstans än i Finland (IB, EB och RP/DIA)*",
            "sortByColumn": "pohjakoulutus_yo_ulkomainen järjestys",
            "displayFolder": "Personvariabler\\Grundutbildningsvariabler"
          },
          {
            "name": "Övrig högskolebehörighet*",
            "dataType": "string",
            "sourceColumn": "Övrig högskolebehörighet*",
            "sortByColumn": "pohjakoulutus_muu järjestys",
            "displayFolder": "Personvariabler\\Grundutbildningsvariabler"
          },
          {
            "name": "Vocat. upper sec. qualif., school-level qualif., post-sec. level qualif. or higher vocat. level qualif. cmpl. in Finland*",
            "dataType": "string",
            "sourceColumn": "Vocat. upper sec. qualif., school-level qualif., post-sec. level qualif. or higher vocat. level qualif. cmpl. in Finland*",
            "sortByColumn": "pohjakoulutus_am järjestys",
            "displayFolder": "Person variables\\Prior education variables"
          },
          {
            "name": "Vocational upper secondary qualification completed in Finland (ammatillinen perustutkinto)*",
            "dataType": "string",
            "sourceColumn": "Vocational upper secondary qualification completed in Finland (ammatillinen perustutkinto)*",
            "sortByColumn": "pohjakoulutus_amp järjestys",
            "displayFolder": "Person variables\\Prior education variables"
          },
          {
            "name": "Further or specialist vocational qualification completed in Finland (ammatti- tai erikoisammattitutkinto)*",
            "dataType": "string",
            "sourceColumn": "Further or specialist vocational qualification completed in Finland (ammatti- tai erikoisammattitutkinto)*",
            "sortByColumn": "pohjakoulutus_amt järjestys",
            "displayFolder": "Person variables\\Prior education variables"
          },
          {
            "name": "Former vocational qualification completed in Finland (kouluasteen, opistoasteen tai ammatillisen korkea-asteen tutkinto)*",
            "dataType": "string",
            "sourceColumn": "Former vocational qualification completed in Finland (kouluasteen, opistoasteen tai ammatillisen korkea-asteen tutkinto)*",
            "sortByColumn": "pohjakoulutus_amv järjestys",
            "displayFolder": "Person variables\\Prior education variables"
          },
          {
            "name": "Studies required by the higher education institution completed at open university or open polytechnic/UAS*",
            "dataType": "string",
            "sourceColumn": "Studies required by the higher education institution completed at open university or open polytechnic/UAS*",
            "sortByColumn": "pohjakoulutus_avoin järjestys",
            "displayFolder": "Person variables\\Prior education variables"
          },
          {
            "name": "Bachelor’s/Master’s/Doctoral degree completed in Finland*",
            "dataType": "string",
            "sourceColumn": "Bachelor’s/Master’s/Doctoral degree completed in Finland*",
            "sortByColumn": "pohjakoulutus_kk järjestys",
            "displayFolder": "Person variables\\Prior education variables"
          },
          {
            "name": "Bachelor’s/Master’s/Doctoral degree completed outside Finland*",
            "dataType": "string",
            "sourceColumn": "Bachelor’s/Master’s/Doctoral degree completed outside Finland*",
            "sortByColumn": "pohjakoulutus_kk_ulk järjestys",
            "displayFolder": "Person variables\\Prior education variables"
          },
          {
            "name": "General upper secondary school syllabus completed in Finland (without matriculation examination)*",
            "dataType": "string",
            "sourceColumn": "General upper secondary school syllabus completed in Finland (without matriculation examination)*",
            "sortByColumn": "pohjakoulutus_lk järjestys",
            "displayFolder": "Person variables\\Prior education variables"
          },
          {
            "name": "Upper secondary education completed outside Finland (general or vocational)*",
            "dataType": "string",
            "sourceColumn": "Upper secondary education completed outside Finland (general or vocational)*",
            "sortByColumn": "pohjakoulutus_ulk järjestys",
            "displayFolder": "Person variables\\Prior education variables"
          },
          {
            "name": "Matriculation examination completed in Finland*",
            "dataType": "string",
            "sourceColumn": "Matriculation examination completed in Finland*",
            "sortByColumn": "pohjakoulutus_yo järjestys",
            "displayFolder": "Person variables\\Prior education variables"
          },
          {
            "name": "Double upper secondary qualification completed in Finland (kaksoistutkinto)*",
            "dataType": "string",
            "sourceColumn": "Double upper secondary qualification completed in Finland (kaksoistutkinto)*",
            "sortByColumn": "pohjakoulutus_yo_ammatillinen järjestys",
            "displayFolder": "Person variables\\Prior education variables"
          },
          {
            "name": "International matriculation examination completed in Finland (IB, EB and RP/DIA)*",
            "dataType": "string",
            "sourceColumn": "International matriculation examination completed in Finland (IB, EB and RP/DIA)*",
            "sortByColumn": "pohjakoulutus_yo_kansainvalinen_suomessa järjestys",
            "displayFolder": "Person variables\\Prior education variables"
          },
          {
            "name": "International matriculation examination completed outside Finland (IB, EB and RP/DIA)*",
            "dataType": "string",
            "sourceColumn": "International matriculation examination completed outside Finland (IB, EB and RP/DIA)*",
            "sortByColumn": "pohjakoulutus_yo_ulkomainen järjestys",
            "displayFolder": "Person variables\\Prior education variables"
          },
          {
            "name": "Other eligibility for higher education*",
            "dataType": "string",
            "sourceColumn": "Other eligibility for higher education*",
            "sortByColumn": "pohjakoulutus_muu järjestys",
            "displayFolder": "Person variables\\Prior education variables"
          },
          {
            "name": "Ensikertainen hakija",
            "dataType": "string",
            "sourceColumn": "Ensikertainen hakija",
            "sortByColumn": "jarjestys_ensikertainen_hakija",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Behandlas som förstagångssökande",
            "dataType": "string",
            "sourceColumn": "Behandlas som förstagångssökande",
            "sortByColumn": "Ensikertainen hakija järjestys",
            "displayFolder": "Personvariabler"
          },
          {
            "name": "Considered as a first-time applicant",
            "dataType": "string",
            "sourceColumn": "Considered as a first-time applicant",
            "sortByColumn": "Ensikertainen hakija järjestys",
            "displayFolder": "Person variables"
          },
          {
            "name": "jarjestys_ensikertainen_hakija",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarjestys_ensikertainen_hakija"
          },
          {
            "name": "Kansainvälinen opiskelija*",
            "dataType": "string",
            "sourceColumn": "Kansainvälinen opiskelija",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Ensikertaisuuden lähde",
            "dataType": "string",
            "sourceColumn": "Ensikertaisuuden lähde"
          },
          {
            "name": "Internationell studerande*",
            "dataType": "string",
            "sourceColumn": "Internationell studerande",
            "displayFolder": "Personvariabler"
          },
          {
            "name": "International student*",
            "dataType": "string",
            "sourceColumn": "International student",
            "displayFolder": "Person variables"
          }
        ],
        "partitions": [
          {
            "name": "0",
            "source": {
              "type": "query",
              "query": "SELECT [dw].[v_haku_ja_valinta_kk].* FROM [dw].[v_haku_ja_valinta_kk] WHERE [Koulutuksen alkamisvuosi] >= year(getdate()) - 1",
              "dataSource": "SqlServer dwitvipusql22 ANTERO"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dw].[v_haku_ja_valinta_kk].* FROM [dw].[v_haku_ja_valinta_kk] WHERE [Koulutuksen alkamisvuosi] >= year(getdate()) - 1</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              }
            ]
          },
          {
            "name": "1",
            "mode": "import",
            "source": {
              "type": "query",
              "query": "SELECT [dw].[v_haku_ja_valinta_kk].* FROM [dw].[v_haku_ja_valinta_kk] WHERE [Koulutuksen alkamisvuosi] BETWEEN 2025 AND year(getdate()) - 2",
              "dataSource": "SqlServer dwitvipusql22 ANTERO"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dw].[v_haku_ja_valinta_kk].* FROM [dw].[v_haku_ja_valinta_kk] WHERE [Koulutuksen alkamisvuosi] BETWEEN 2025 AND year(getdate()) - 2</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              }
            ]
          },
          {
            "name": "2",
            "mode": "import",
            "source": {
              "type": "query",
              "query": "SELECT [dw].[v_haku_ja_valinta_kk].* FROM [dw].[v_haku_ja_valinta_kk] WHERE [Koulutuksen alkamisvuosi] = 2024",
              "dataSource": "SqlServer dwitvipusql22 ANTERO"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dw].[v_haku_ja_valinta_kk].* FROM [dw].[v_haku_ja_valinta_kk] WHERE [Koulutuksen alkamisvuosi] = 2024</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              }
            ]
          },
          {
            "name": "3",
            "mode": "import",
            "source": {
              "type": "query",
              "query": "SELECT [dw].[v_haku_ja_valinta_kk].* FROM [dw].[v_haku_ja_valinta_kk] WHERE [Koulutuksen alkamisvuosi] = 2023",
              "dataSource": "SqlServer dwitvipusql22 ANTERO"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dw].[v_haku_ja_valinta_kk].* FROM [dw].[v_haku_ja_valinta_kk] WHERE [Koulutuksen alkamisvuosi] = 2023</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              }
            ]
          },
          {
            "name": "4",
            "mode": "import",
            "source": {
              "type": "query",
              "query": "SELECT [dw].[v_haku_ja_valinta_kk].* FROM [dw].[v_haku_ja_valinta_kk] WHERE [Koulutuksen alkamisvuosi] = 2022",
              "dataSource": "SqlServer dwitvipusql22 ANTERO"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dw].[v_haku_ja_valinta_kk].* FROM [dw].[v_haku_ja_valinta_kk] WHERE [Koulutuksen alkamisvuosi] = 2022</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              }
            ]
          },
          {
            "name": "5",
            "mode": "import",
            "source": {
              "type": "query",
              "query": "SELECT [dw].[v_haku_ja_valinta_kk].* FROM [dw].[v_haku_ja_valinta_kk] WHERE [Koulutuksen alkamisvuosi] = 2021",
              "dataSource": "SqlServer dwitvipusql22 ANTERO"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dw].[v_haku_ja_valinta_kk].* FROM [dw].[v_haku_ja_valinta_kk] WHERE [Koulutuksen alkamisvuosi] = 2021</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              }
            ]
          },
          {
            "name": "6",
            "mode": "import",
            "source": {
              "type": "query",
              "query": "SELECT [dw].[v_haku_ja_valinta_kk].* FROM [dw].[v_haku_ja_valinta_kk] WHERE [Koulutuksen alkamisvuosi] BETWEEN 2019 and 2020",
              "dataSource": "SqlServer dwitvipusql22 ANTERO"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dw].[v_haku_ja_valinta_kk].* FROM [dw].[v_haku_ja_valinta_kk] WHERE [Koulutuksen alkamisvuosi] BETWEEN 2019 and 2020</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              }
            ]
          },
          {
            "name": "7",
            "mode": "import",
            "source": {
              "type": "query",
              "query": "SELECT [dw].[v_haku_ja_valinta_kk].* FROM [dw].[v_haku_ja_valinta_kk] WHERE [Koulutuksen alkamisvuosi] BETWEEN 2017 and 2018",
              "dataSource": "SqlServer dwitvipusql22 ANTERO"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dw].[v_haku_ja_valinta_kk].* FROM [dw].[v_haku_ja_valinta_kk] WHERE [Koulutuksen alkamisvuosi] BETWEEN 2017 and 2018</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              }
            ]
          },
          {
            "name": "8",
            "mode": "import",
            "source": {
              "type": "query",
              "query": "SELECT [dw].[v_haku_ja_valinta_kk].* FROM [dw].[v_haku_ja_valinta_kk] WHERE [Koulutuksen alkamisvuosi] < 2017",
              "dataSource": "SqlServer dwitvipusql22 ANTERO"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dw].[v_haku_ja_valinta_kk].* FROM [dw].[v_haku_ja_valinta_kk] WHERE [Koulutuksen alkamisvuosi] < 2017</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Kaikki hakijat",
            "expression": [
              "",
              "var lkm = calculate(DISTINCTCOUNT(Muuttujat[Henkilö OID]),Muuttujat[Lukumäärä]=1)",
              "return IF(lkm = 0, BLANK(), IF(lkm < 5, \"1-4\", MROUND(lkm, 3)))"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Valitut",
            "expression": [
              "",
              "var lkm = CALCULATE(DISTINCTCOUNT([Henkilö OID]),Muuttujat[Valitut2]=1)",
              "return IF(lkm = 0, BLANK(), IF(lkm < 5, \"1-4\", MROUND(lkm, 3)))"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Paikan vastaanottaneet",
            "expression": [
              "",
              "var lkm = calculate(DISTINCTCOUNT(Muuttujat[Henkilö OID]),Muuttujat[Paikan vastaanottaneet2]=1)",
              "return IF(lkm = 0, BLANK(), IF(lkm < 5, \"1-4\", MROUND(lkm, 3)))"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Ensisijaiset hakijat",
            "expression": [
              "",
              "var lkm = CALCULATE(DISTINCTCOUNT(Muuttujat[Henkilö OID]),Muuttujat[Ensisijaiset hakijat2]=1)",
              "return IF(lkm = 0, BLANK(), IF(lkm < 5, \"1-4\", MROUND(lkm, 3)))"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Läsnäolevaksi ilmoittautuneet",
            "expression": [
              "",
              "var lkm = calculate(DISTINCTCOUNT([Henkilö OID]),Muuttujat[Aloittaneet2]=1)",
              "return IF(lkm = 0, BLANK(), IF(lkm < 5, \"1-4\", MROUND(lkm, 3)))",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "Ensisijaiset hakijat (ammattikorkeakouluihin)",
            "expression": [
              "",
              "var lkm = CALCULATE(DISTINCTCOUNT(Muuttujat[Henkilö OID]),Muuttujat[Hakutoive]=\"1\")",
              "return IF(lkm = 0, BLANK(), IF(lkm < 5, \"1-4\", MROUND(lkm, 3)))"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Ensisijaiset hakijat (yliopistoihin)",
            "expression": [
              "",
              "var lkm = CALCULATE(DISTINCTCOUNT(Muuttujat[Henkilö OID]),Muuttujat[Hakutoive]=\"1\")",
              "return IF(lkm = 0, BLANK(), IF(lkm < 5, \"1-4\", MROUND(lkm, 3)))"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Kaikki hakijat (nettouttamaton)",
            "expression": [
              "",
              "var lkm_s = CALCULATE(DISTINCTCOUNT([Henkilö OID_Hakukohde OID]), Muuttujat[Lukumäärä] = 1)",
              "return",
              "IF(lkm_s = 0, BLANK(), IF(lkm_s < 5, \"1-4\", MROUND(lkm_s, 3)))",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "Aloittaneet",
            "expression": [
              "",
              "var lkm = calculate(DISTINCTCOUNT([Henkilö OID]),Muuttujat[Aloittaneet2]=1)",
              "return IF(lkm = 0, BLANK(), IF(lkm < 5, \"1-4\", MROUND(lkm, 3)))"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Aloituspaikat",
            "expression": "if(sum([alpa])=0,blank(),sum([alpa]))",
            "formatString": "#,0"
          },
          {
            "name": "Nybörjarplatser",
            "expression": "[Aloituspaikat]",
            "formatString": "#,0"
          },
          {
            "name": "Intake",
            "expression": "[Aloituspaikat]",
            "formatString": "#,0"
          },
          {
            "name": "Samtliga sökande",
            "expression": "[Kaikki hakijat]",
            "formatString": "#,0"
          },
          {
            "name": "All applicants",
            "expression": "[Kaikki hakijat]",
            "formatString": "#,0"
          },
          {
            "name": "Samtliga sökande (utan nettning)",
            "expression": [
              "",
              "var lkm_s = CALCULATE(DISTINCTCOUNT([Henkilö OID_Hakukohde OID]), Muuttujat[Lukumäärä] = 1)",
              "return",
              "IF(lkm_s = 0, BLANK(), IF(lkm_s < 5, \"1-4\", MROUND(lkm_s, 3)))",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "All applicants (no netting)",
            "expression": [
              "",
              "var lkm_s = CALCULATE(DISTINCTCOUNT([Henkilö OID_Hakukohde OID]), Muuttujat[Lukumäärä] = 1)",
              "return",
              "IF(lkm_s = 0, BLANK(), IF(lkm_s < 5, \"1-4\", MROUND(lkm_s, 3)))",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "Försthandssökande",
            "expression": "[Ensisijaiset hakijat]",
            "formatString": "#,0"
          },
          {
            "name": "Applicants expressing first preference",
            "expression": "[Ensisijaiset hakijat]",
            "formatString": "#,0"
          },
          {
            "name": "Försthandssökande (till YH)",
            "expression": "[Ensisijaiset hakijat (ammattikorkeakouluihin)]",
            "formatString": "#,0"
          },
          {
            "name": "Applicants expressing first preference (to UAS)",
            "expression": "[Ensisijaiset hakijat (ammattikorkeakouluihin)]",
            "formatString": "#,0"
          },
          {
            "name": "Försthandssökande (till universitet)",
            "expression": "[Ensisijaiset hakijat (yliopistoihin)]",
            "formatString": "#,0"
          },
          {
            "name": "Applicants expressing first preference (to universities)",
            "expression": "[Ensisijaiset hakijat (yliopistoihin)]",
            "formatString": "#,0"
          },
          {
            "name": "Antagna",
            "expression": "[Valitut]",
            "formatString": "#,0"
          },
          {
            "name": "Selected",
            "expression": "[Valitut]",
            "formatString": "#,0"
          },
          {
            "name": "Antal som mottagit en plats",
            "expression": "[Paikan vastaanottaneet]",
            "formatString": "#,0"
          },
          {
            "name": "Accepted a study place",
            "expression": "[Paikan vastaanottaneet]",
            "formatString": "#,0"
          },
          {
            "name": "Nybörjare",
            "expression": "[Aloittaneet]",
            "formatString": "#,0"
          },
          {
            "name": "Admitted",
            "expression": "[Aloittaneet]",
            "formatString": "#,0"
          },
          {
            "name": "Närvarande",
            "expression": "[Läsnäolevaksi ilmoittautuneet]",
            "formatString": "#,0"
          },
          {
            "name": "Enrolled as present",
            "expression": "[Läsnäolevaksi ilmoittautuneet]",
            "formatString": "#,0"
          },
          {
            "name": "Alin hyväksytty pistemäärä",
            "expression": [
              "",
              "var alin = CALCULATE(MIN(Muuttujat[Pisteet]),FILTER(Muuttujat,Muuttujat[Pisteet]>0 && Muuttujat[Valitut2]=1))",
              "var tyhja = \"−\"",
              "var ehto = ",
              "AND(",
              "\tOR(OR(ISFILTERED([Hakukohde]),ISFILTERED([Sökobjekt])),ISFILTERED([Applied study programme])), ",
              "\tAND(",
              "\t\tNOT(OR(OR(ISFILTERED([Valintatapajonon tyyppi]),ISFILTERED([Typ av antagningskö])),ISFILTERED([Type of admission queue])))",
              "\t\t,NOT(OR(ISFILTERED([Valintatapajonon nimi]),ISFILTERED([Namnet på antagningskö])))",
              "\t)",
              ")",
              "var valinnat = MAX(Muuttujat[Valitut2])",
              "return IF(valinnat=0,BLANK(),IF(AND(ehto=TRUE(),alin=0),tyhja,alin))"
            ],
            "formatString": "#,0.00"
          },
          {
            "name": "Ylin hyväksytty pistemäärä",
            "expression": [
              "",
              "var ylin = CALCULATE(MAX(Muuttujat[Pisteet]),FILTER(Muuttujat,Muuttujat[Pisteet]>0 && Muuttujat[Valitut2]=1))",
              "var tyhja = \"−\"",
              "var ehto = ",
              "AND(",
              "\tOR(OR(ISFILTERED([Hakukohde]),ISFILTERED([Sökobjekt])),ISFILTERED([Applied study programme])), ",
              "\tAND(",
              "\t\tNOT(OR(OR(ISFILTERED([Valintatapajonon tyyppi]),ISFILTERED([Typ av antagningskö])),ISFILTERED([Type of admission queue])))",
              "\t\t,NOT(OR(ISFILTERED([Valintatapajonon nimi]),ISFILTERED([Namnet på antagningskö])))",
              "\t)",
              ")",
              "var valinnat = MAX(Muuttujat[Valitut2])",
              "return IF(valinnat=0,BLANK(),IF(AND(ehto=TRUE(),ylin=0),tyhja,ylin))"
            ],
            "formatString": "#,0.00"
          },
          {
            "name": "Lowest accepted score",
            "expression": "[Alin hyväksytty pistemäärä]",
            "formatString": "#,0.00"
          },
          {
            "name": "Lägsta inträdespoäng för godkända",
            "expression": "[Alin hyväksytty pistemäärä]",
            "formatString": "#,0.00"
          },
          {
            "name": "Highest accepted score",
            "expression": "[Ylin hyväksytty pistemäärä]",
            "formatString": "#,0.00"
          },
          {
            "name": "Högsta inträdespoäng för godkända",
            "expression": "[Ylin hyväksytty pistemäärä]",
            "formatString": "#,0.00"
          },
          {
            "name": "Uusien ylioppilaiden osuus, ensisijaiset hakijat (I sykli)",
            "expression": [
              "",
              "var osa = CALCULATE([Ensisijaiset hakijat],Muuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1,Muuttujat[uusi ylioppilas2]=1)",
              "var kaikki = CALCULATE([Ensisijaiset hakijat],Muuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1)",
              "return IF(osa = BLANK(), BLANK(),",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, 0,",
              "CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))",
              ""
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Uudet ylioppilaat"
          },
          {
            "name": "Uusien ylioppilaiden osuus, hakijat (I sykli)",
            "expression": [
              "",
              "var osa = CALCULATE([Kaikki hakijat],Muuttujat[uusi ylioppilas2]=1,Muuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1)",
              "var kaikki = CALCULATE([Kaikki hakijat],Muuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1)",
              "return IF(osa = BLANK(), BLANK(),",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, 0,",
              "CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))",
              "",
              ""
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Uudet ylioppilaat"
          },
          {
            "name": "Uusien ylioppilaiden osuus, valitut (I sykli)",
            "expression": [
              "",
              "var osa = CALCULATE([Valitut_indikaattori],Muuttujat[uusi ylioppilas2]=1,Muuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1)",
              "var kaikki = CALCULATE([Valitut_indikaattori],Muuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1)",
              "return IF(osa = BLANK(), BLANK(),",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, 0,",
              "CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Uudet ylioppilaat"
          },
          {
            "name": "Uusien ylioppilaiden osuus, paikan vastaanottaneet (I sykli)",
            "expression": [
              "",
              "var osa = CALCULATE([Paikan vastaanottaneet_indikaattori],Muuttujat[uusi ylioppilas2]=1,Muuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1)",
              "var kaikki = CALCULATE([Paikan vastaanottaneet_indikaattori],Muuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1)",
              "return IF(osa = BLANK(), BLANK(),",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, 0,",
              "CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Uudet ylioppilaat"
          },
          {
            "name": "Ensikertaisten osuus, hakijat",
            "expression": [
              "",
              "var osa = CALCULATE([Kaikki hakijat],Muuttujat[aidosti ensikertainen]=1,Muuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1)",
              "var kaikki = CALCULATE([Kaikki hakijat],Muuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1)",
              "return IF(osa = BLANK(), BLANK(),",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, 0,",
              "CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Ensikertaiset (I hakusykli)"
          },
          {
            "name": "Ensikertaisten osuus, valitut",
            "expression": [
              "",
              "var osa = CALCULATE([Valitut_indikaattori],Muuttujat[aidosti ensikertainen]=1,Muuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1)",
              "var kaikki = CALCULATE([Valitut_indikaattori],Muuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1)",
              "return IF(osa = BLANK(), BLANK(),",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, 0,",
              "CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Ensikertaiset (I hakusykli)"
          },
          {
            "name": "Ensikertaisten osuus, paikan vastaanottaneet",
            "expression": [
              "",
              "var osa = CALCULATE([Paikan vastaanottaneet_indikaattori],Muuttujat[aidosti ensikertainen]=1,Muuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1)",
              "var kaikki = CALCULATE([Paikan vastaanottaneet_indikaattori],Muuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1)",
              "return IF(osa = BLANK(), BLANK(),",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, 0,",
              "CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Ensikertaiset (I hakusykli)"
          },
          {
            "name": "I hakutoiveen paikan vastaanottaneet",
            "expression": [
              "",
              "var osa = CALCULATE([Paikan vastaanottaneet_indikaattori],Muuttujat[Hakutoive]=\"1\",Muuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1,Muuttujat[Hakutapa järjestys]=1)",
              "var kaikki = CALCULATE([Paikan vastaanottaneet_indikaattori],Muuttujat[Hakutapa järjestys]=1,Muuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1)",
              "return IF(osa = BLANK(), BLANK(),",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, 0,",
              "CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))"
            ],
            "formatString": "#,0.0 %;-#,0.0 %;#,0.0 %",
            "displayFolder": "Vastaanotettu paikka suhteessa hakijan I hakutoiveeseen (I hakusykli)"
          },
          {
            "name": "Sama korkeakoulu, sama ala; paikan vastaanottaneet",
            "expression": [
              "",
              "var osa = CALCULATE([Paikan vastaanottaneet_indikaattori],Muuttujat[Hakutoive]<>\"1\",",
              "\tMuuttujat[sama kuin 1 hakukohteen sektori]=1,",
              "\tMuuttujat[sama kuin 1 hakukohteen kk]=1,",
              "\tMuuttujat[sama kuin 1 hakukohteen koulutusala1]=1,",
              "\tMuuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1,Muuttujat[Hakutapa järjestys]=1)",
              "var kaikki = CALCULATE([Paikan vastaanottaneet_indikaattori],Muuttujat[Hakutapa järjestys]=1,Muuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1)",
              "return IF(osa = BLANK(), BLANK(),",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, 0,",
              "CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))"
            ],
            "formatString": "#,0.0 %;-#,0.0 %;#,0.0 %",
            "displayFolder": "Vastaanotettu paikka suhteessa hakijan I hakutoiveeseen (I hakusykli)"
          },
          {
            "name": "Sama sektori, eri korkeakoulu, sama ala; paikan vastaanottaneet",
            "expression": [
              "",
              "var osa = CALCULATE([Paikan vastaanottaneet_indikaattori],Muuttujat[Hakutoive]<>\"1\",",
              "\tMuuttujat[sama kuin 1 hakukohteen sektori]=1,",
              "\tMuuttujat[sama kuin 1 hakukohteen kk]=0,",
              "\tMuuttujat[sama kuin 1 hakukohteen koulutusala1]=1,",
              "\tMuuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1,Muuttujat[Hakutapa järjestys]=1)",
              "var kaikki = CALCULATE([Paikan vastaanottaneet_indikaattori],Muuttujat[Hakutapa järjestys]=1,Muuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1)",
              "return IF(osa = BLANK(), BLANK(),",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, 0,",
              "CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))"
            ],
            "formatString": "#,0.0 %;-#,0.0 %;#,0.0 %",
            "displayFolder": "Vastaanotettu paikka suhteessa hakijan I hakutoiveeseen (I hakusykli)"
          },
          {
            "name": "Sama korkeakoulu, eri ala; paikan vastaanottaneet",
            "expression": [
              "",
              "var osa = CALCULATE([Paikan vastaanottaneet_indikaattori],",
              "\tMuuttujat[sama kuin 1 hakukohteen sektori]=1,",
              "\tMuuttujat[sama kuin 1 hakukohteen kk]=1,",
              "\tMuuttujat[sama kuin 1 hakukohteen koulutusala1]=0,",
              "\tMuuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1,Muuttujat[Hakutapa järjestys]=1)",
              "var kaikki = CALCULATE([Paikan vastaanottaneet_indikaattori],Muuttujat[Hakutapa järjestys]=1,Muuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1)",
              "return IF(osa = BLANK(), BLANK(),",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, 0,",
              "CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))",
              ""
            ],
            "formatString": "#,0.0 %;-#,0.0 %;#,0.0 %",
            "displayFolder": "Vastaanotettu paikka suhteessa hakijan I hakutoiveeseen (I hakusykli)"
          },
          {
            "name": "Eri sektori, sama ala; paikan vastaanottaneet",
            "expression": [
              "",
              "var osa = CALCULATE([Paikan vastaanottaneet_indikaattori],",
              "\tMuuttujat[sama kuin 1 hakukohteen sektori]=0,",
              "\tMuuttujat[sama kuin 1 hakukohteen koulutusala1]=1,",
              "\tMuuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1,Muuttujat[Hakutapa järjestys]=1)",
              "var kaikki = CALCULATE([Paikan vastaanottaneet_indikaattori],Muuttujat[Hakutapa järjestys]=1,Muuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1)",
              "return IF(osa = BLANK(), BLANK(),",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, 0,",
              "CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))",
              ""
            ],
            "formatString": "#,0.0 %;-#,0.0 %;#,0.0 %",
            "displayFolder": "Vastaanotettu paikka suhteessa hakijan I hakutoiveeseen (I hakusykli)"
          },
          {
            "name": "Eri sektori, eri ala; paikan vastaanottaneet",
            "expression": [
              "",
              "var osa = CALCULATE([Paikan vastaanottaneet_indikaattori],",
              "\tMuuttujat[sama kuin 1 hakukohteen sektori]=0,",
              "\tMuuttujat[sama kuin 1 hakukohteen koulutusala1]=0,",
              "\tMuuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1,Muuttujat[Hakutapa järjestys]=1)",
              "var kaikki = CALCULATE([Paikan vastaanottaneet_indikaattori],Muuttujat[Hakutapa järjestys]=1,Muuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1)",
              "return IF(osa = BLANK(), BLANK(),",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, 0,",
              "CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))",
              ""
            ],
            "formatString": "#,0.0 %;-#,0.0 %;#,0.0 %",
            "displayFolder": "Vastaanotettu paikka suhteessa hakijan I hakutoiveeseen (I hakusykli)"
          },
          {
            "name": "Valituista paikan vastaanottamatta jättäneiden osuus",
            "expression": [
              "",
              "var osa = CALCULATE([Valitut_indikaattori],Muuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1,Muuttujat[ei vastaanottoa kaudella]=1)",
              "var kaikki = CALCULATE([Valitut_indikaattori],Muuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1)",
              "return IF(osa = BLANK(), BLANK(),",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, 0,",
              "CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Ei opintopaikan vastaanottoa (I hakusykli)"
          },
          {
            "name": "Ei opintopaikkaa vastaanottaneiden osuus (I sykli)2",
            "expression": [
              " --too slow --added still protection just in case / jsyrjala2",
              "var taulu1 = ",
              "SUMMARIZE(",
              "\tFILTER(",
              "\t\tADDCOLUMNS(",
              "\t\t\tSUMMARIZE(FILTER(Muuttujat,Muuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1 && Muuttujat[Valitut2]=1),[Henkilö OID],[Koulutuksen alkamisvuosi],[Koulutuksen alkamiskausi])",
              "\t\t\t, \"vastaanotto_kausi\",CALCULATE(MAX(Muuttujat[Paikan vastaanottaneet2]))",
              "\t\t)",
              "\t\t,[vastaanotto_kausi]=0",
              "\t)",
              "\t,[Henkilö OID]",
              ")",
              "var lkm = CALCULATE(COUNTROWS(taulu1))",
              "var osa = IF(lkm = 0, BLANK(), IF(lkm < 5, \"1-4\", MROUND(lkm, 3)))",
              "var kaikki = CALCULATE([Valitut],Muuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1)",
              "",
              "return IF(osa = BLANK(), BLANK(),",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, 0,",
              "CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))"
            ],
            "formatString": "#,0.0 %;-#,0.0 %;#,0.0 %",
            "isHidden": true
          },
          {
            "name": "Sama sektori, eri korkeakoulu, eri ala; paikan vastaanottaneet",
            "expression": [
              "",
              "var osa = CALCULATE([Paikan vastaanottaneet_indikaattori],",
              "\tMuuttujat[sama kuin 1 hakukohteen sektori]=1,",
              "\tMuuttujat[sama kuin 1 hakukohteen kk]=0,",
              "\tMuuttujat[sama kuin 1 hakukohteen koulutusala1]=0,",
              "\tMuuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1,Muuttujat[Hakutapa järjestys]=1)",
              "var kaikki = CALCULATE([Paikan vastaanottaneet_indikaattori],Muuttujat[Hakutapa järjestys]=1,Muuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1)",
              "return IF(osa = BLANK(), BLANK(),",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, 0,",
              "CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))",
              ""
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Vastaanotettu paikka suhteessa hakijan I hakutoiveeseen (I hakusykli)"
          },
          {
            "name": "Ensisijaiset hakijat_s",
            "expression": "CALCULATE(DISTINCTCOUNT(Muuttujat[Henkilö OID]),Muuttujat[Ensisijaiset hakijat2]=1)",
            "formatString": "#,0"
          },
          {
            "name": "Kaikki hakijat_s",
            "expression": "calculate(DISTINCTCOUNT(Muuttujat[Henkilö OID]),Muuttujat[Lukumäärä]=1)",
            "formatString": "#,0"
          },
          {
            "name": "Paikan vastaanottaneet_s",
            "expression": "calculate(DISTINCTCOUNT(Muuttujat[Henkilö OID]),Muuttujat[Paikan vastaanottaneet2]=1)",
            "formatString": "#,0"
          },
          {
            "name": "Ensisijaiset hakijat (yliopistoihin)_s",
            "expression": "CALCULATE(DISTINCTCOUNT(Muuttujat[Henkilö OID]),Muuttujat[Hakutoive]=\"1\")",
            "formatString": "#,0"
          },
          {
            "name": "Ensisijaiset hakijat (ammattikorkeakouluihin)_s",
            "expression": "CALCULATE(DISTINCTCOUNT(Muuttujat[Henkilö OID]),Muuttujat[Hakutoive]=\"1\")",
            "formatString": "#,0"
          },
          {
            "name": "Kaikki hakijat (nettouttamaton)_s",
            "expression": [
              "",
              "CALCULATE(DISTINCTCOUNT([Henkilö OID_Hakukohde OID]), Muuttujat[Lukumäärä] = 1)",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "Valitut_s",
            "expression": "CALCULATE(DISTINCTCOUNT([Henkilö OID]),Muuttujat[Valitut2]=1)",
            "formatString": "#,0"
          },
          {
            "name": "Aloittaneet_s",
            "expression": "calculate(DISTINCTCOUNT([Henkilö OID]),Muuttujat[Aloittaneet2]=1)",
            "formatString": "#,0"
          },
          {
            "name": "Läsnäolevaksi ilmoittautuneet_s",
            "expression": "calculate(DISTINCTCOUNT([Henkilö OID]),Muuttujat[Aloittaneet2]=1)",
            "formatString": "#,0"
          },
          {
            "name": "Uusien ylioppilaiden osuus, paikan vastaanottaneet (I sykli)_s",
            "expression": [
              "",
              "var uusi_yo = CALCULATE([Paikan vastaanottaneet_indikaattori_s],Muuttujat[uusi ylioppilas2]=1,Muuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1)",
              "var kaikki = CALCULATE([Paikan vastaanottaneet_indikaattori_s],Muuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1)",
              "return DIVIDE(uusi_yo,kaikki)"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Uusien ylioppilaiden osuus, ensisijaiset hakijat (I sykli)_s",
            "expression": [
              "",
              "var uusi_yo = CALCULATE([Ensisijaiset hakijat_s],Muuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1,Muuttujat[uusi ylioppilas2]=1)",
              "var kaikki = CALCULATE([Ensisijaiset hakijat_s],Muuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1)",
              "return DIVIDE(uusi_yo,kaikki)"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Uusien ylioppilaiden osuus, hakijat (I sykli)_s",
            "expression": [
              "",
              "var uusi_yo = CALCULATE([Kaikki hakijat_s],Muuttujat[uusi ylioppilas2]=1,Muuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1)",
              "var kaikki = CALCULATE([Kaikki hakijat_s],Muuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1)",
              "return DIVIDE(uusi_yo,kaikki)",
              ""
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Uusien ylioppilaiden osuus, valitut (I sykli)_s",
            "expression": [
              "",
              "var uusi_yo = CALCULATE([Valitut_indikaattori_s],Muuttujat[uusi ylioppilas2]=1,Muuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1)",
              "var kaikki = CALCULATE([Valitut_indikaattori_s],Muuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1)",
              "return DIVIDE(uusi_yo,kaikki)"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Ensikertaisten osuus, hakijat_s",
            "expression": [
              "",
              "var uusi_yo = CALCULATE([Kaikki hakijat_s],Muuttujat[aidosti ensikertainen]=1,Muuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1)",
              "var kaikki = CALCULATE([Kaikki hakijat_s],Muuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1)",
              "return DIVIDE(uusi_yo,kaikki)"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Ensikertaisten osuus, valitut_s",
            "expression": [
              "",
              "var uusi_yo = CALCULATE([Valitut_indikaattori_s],Muuttujat[aidosti ensikertainen]=1,Muuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1)",
              "var kaikki = CALCULATE([Valitut_indikaattori_s],Muuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1)",
              "return DIVIDE(uusi_yo,kaikki)"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Ensikertaisten osuus, paikan vastaanottaneet_s",
            "expression": [
              "",
              "var uusi_yo = CALCULATE([Paikan vastaanottaneet_indikaattori_s],Muuttujat[aidosti ensikertainen]=1,Muuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1)",
              "var kaikki = CALCULATE([Paikan vastaanottaneet_indikaattori_s],Muuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1)",
              "return DIVIDE(uusi_yo,kaikki)"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "I hakutoiveen paikan vastaanottaneet_s",
            "expression": [
              "",
              "DIVIDE(",
              "\tCALCULATE([Paikan vastaanottaneet_indikaattori_s],Muuttujat[Hakutoive]=\"1\",Muuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1,Muuttujat[Hakutapa järjestys]=1)",
              "\t,CALCULATE([Paikan vastaanottaneet_indikaattori_s],Muuttujat[Hakutapa järjestys]=1,Muuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1)",
              ")"
            ],
            "formatString": "#,0.0 %;-#,0.0 %;#,0.0 %"
          },
          {
            "name": "Sama korkeakoulu, sama ala; paikan vastaanottaneet_s",
            "expression": [
              "",
              "DIVIDE(",
              "\tCALCULATE([Paikan vastaanottaneet_indikaattori_s],Muuttujat[Hakutoive]<>\"1\",",
              "\tMuuttujat[sama kuin 1 hakukohteen sektori]=1,",
              "\tMuuttujat[sama kuin 1 hakukohteen kk]=1,",
              "\tMuuttujat[sama kuin 1 hakukohteen koulutusala1]=1,",
              "\tMuuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1,Muuttujat[Hakutapa järjestys]=1)",
              "\t,CALCULATE([Paikan vastaanottaneet_indikaattori_s],Muuttujat[Hakutapa järjestys]=1,Muuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1)",
              ")"
            ],
            "formatString": "#,0.0 %;-#,0.0 %;#,0.0 %"
          },
          {
            "name": "Sama sektori, eri korkeakoulu, sama ala; paikan vastaanottaneet_s",
            "expression": [
              "",
              "DIVIDE(",
              "\tCALCULATE([Paikan vastaanottaneet_indikaattori_s],Muuttujat[Hakutoive]<>\"1\",",
              "\tMuuttujat[sama kuin 1 hakukohteen sektori]=1,",
              "\tMuuttujat[sama kuin 1 hakukohteen kk]=0,",
              "\tMuuttujat[sama kuin 1 hakukohteen koulutusala1]=1,",
              "\tMuuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1,Muuttujat[Hakutapa järjestys]=1)",
              "\t,CALCULATE([Paikan vastaanottaneet_indikaattori_s],Muuttujat[Hakutapa järjestys]=1,Muuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1)",
              ")"
            ],
            "formatString": "#,0.0 %;-#,0.0 %;#,0.0 %"
          },
          {
            "name": "Sama korkeakoulu, eri ala; paikan vastaanottaneet_s",
            "expression": [
              "",
              "DIVIDE(",
              "\tCALCULATE([Paikan vastaanottaneet_indikaattori_s],",
              "\tMuuttujat[sama kuin 1 hakukohteen sektori]=1,",
              "\tMuuttujat[sama kuin 1 hakukohteen kk]=1,",
              "\tMuuttujat[sama kuin 1 hakukohteen koulutusala1]=0,",
              "\tMuuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1,Muuttujat[Hakutapa järjestys]=1)",
              "\t,CALCULATE([Paikan vastaanottaneet_indikaattori_s],Muuttujat[Hakutapa järjestys]=1,Muuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1)",
              ")",
              ""
            ],
            "formatString": "#,0.0 %;-#,0.0 %;#,0.0 %"
          },
          {
            "name": "Sama sektori, eri korkeakoulu, eri ala; paikan vastaanottaneet_s",
            "expression": [
              "",
              "DIVIDE(",
              "\tCALCULATE([Paikan vastaanottaneet_indikaattori_s],",
              "\tMuuttujat[sama kuin 1 hakukohteen sektori]=1,",
              "\tMuuttujat[sama kuin 1 hakukohteen kk]=0,",
              "\tMuuttujat[sama kuin 1 hakukohteen koulutusala1]=0,",
              "\tMuuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1,Muuttujat[Hakutapa järjestys]=1)",
              "\t,CALCULATE([Paikan vastaanottaneet_indikaattori_s],Muuttujat[Hakutapa järjestys]=1,Muuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1)",
              ")",
              ""
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Eri sektori, sama ala; paikan vastaanottaneet_s",
            "expression": [
              "",
              "DIVIDE(",
              "\tCALCULATE([Paikan vastaanottaneet_indikaattori_s],",
              "\tMuuttujat[sama kuin 1 hakukohteen sektori]=0,",
              "\tMuuttujat[sama kuin 1 hakukohteen koulutusala1]=1,",
              "\tMuuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1,Muuttujat[Hakutapa järjestys]=1)",
              "\t,CALCULATE([Paikan vastaanottaneet_indikaattori_s],Muuttujat[Hakutapa järjestys]=1,Muuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1)",
              ")"
            ],
            "formatString": "#,0.0 %;-#,0.0 %;#,0.0 %"
          },
          {
            "name": "Eri sektori, eri ala; paikan vastaanottaneet_s",
            "expression": [
              "",
              "DIVIDE(",
              "\tCALCULATE([Paikan vastaanottaneet_indikaattori_s],",
              "\tMuuttujat[sama kuin 1 hakukohteen sektori]=0,",
              "\tMuuttujat[sama kuin 1 hakukohteen koulutusala1]=0,",
              "\tMuuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1,Muuttujat[Hakutapa järjestys]=1)",
              "\t,CALCULATE([Paikan vastaanottaneet_indikaattori_s],Muuttujat[Hakutapa järjestys]=1,Muuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1)",
              ")"
            ],
            "formatString": "#,0.0 %;-#,0.0 %;#,0.0 %"
          },
          {
            "name": "Valituista paikan vastaanottamatta jättäneiden osuus_s",
            "expression": [
              "",
              "var ei_vastaanottanut = CALCULATE([Valitut_indikaattori_s],Muuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1,Muuttujat[ei vastaanottoa kaudella]=1)",
              "var valitut = CALCULATE([Valitut_indikaattori_s],Muuttujat[Tutkinnon aloitussykli hakukohde järjestys]=1)",
              "return DIVIDE(ei_vastaanottanut,valitut)"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Valitut_indikaattori",
            "expression": [
              "",
              "var lkm = CALCULATE(DISTINCTCOUNT([Henkilö OID]),Muuttujat[Valitut2_indikaattori]=1)",
              "return IF(lkm = 0, BLANK(), IF(lkm < 5, \"1-4\", MROUND(lkm, 3)))",
              ""
            ]
          },
          {
            "name": "Paikan vastaanottaneet_indikaattori",
            "expression": [
              "",
              "var lkm = calculate(DISTINCTCOUNT(Muuttujat[Henkilö OID]),Muuttujat[Paikan vastaanottaneet2_indikaattori]=1)",
              "return IF(lkm = 0, BLANK(), IF(lkm < 5, \"1-4\", MROUND(lkm, 3)))"
            ]
          },
          {
            "name": "Valitut_indikaattori_s",
            "expression": "CALCULATE(DISTINCTCOUNT([Henkilö OID]),Muuttujat[Valitut2_indikaattori]=1)"
          },
          {
            "name": "Paikan vastaanottaneet_indikaattori_s",
            "expression": "calculate(DISTINCTCOUNT(Muuttujat[Henkilö OID]),Muuttujat[Paikan vastaanottaneet2_indikaattori]=1)"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dw"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "v_haku_ja_valinta_kk"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " \t\t\t\tSELECT [dw].[v_haku_ja_valinta_kk].*   FROM [dw].[v_haku_ja_valinta_kk] "
          },
          {
            "name": "QueryEditorSerialization",
            "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dw].[v_haku_ja_valinta_kk].* FROM [dw].[v_haku_ja_valinta_kk] WHERE [Koulutuksen alkamisvuosi] >= year(getdate()) - 1</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
          }
        ]
      },
      {
        "name": "Sarakeleveys",
        "isHidden": true,
        "columns": [
          {
            "name": "Sarakeleveys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Sarakeleveys"
          },
          {
            "name": "leveys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "leveys"
          }
        ],
        "partitions": [
          {
            "name": "Sarakeleveys",
            "source": {
              "type": "query",
              "query": "SELECT [dw].[Sarakeleveys].* FROM [dw].[Sarakeleveys]",
              "dataSource": "SqlServer dwitvipusql22 ANTERO"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "&lt;?xml version=\"1.0\" encoding=\"UTF-16\"?&gt;&lt;Gemini xmlns=\"TableWidgetSerialization\"&gt;&lt;AnnotationContent&gt;&lt;![CDATA[&lt;?xml version=\"1.0\"?&gt;",
                  "&lt;TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\"&gt;",
                  "  &lt;ColumnSuggestedType /&gt;",
                  "  &lt;ColumnFormat /&gt;",
                  "  &lt;ColumnAccuracy /&gt;",
                  "  &lt;ColumnCurrencySymbol /&gt;",
                  "  &lt;ColumnPositivePattern /&gt;",
                  "  &lt;ColumnNegativePattern /&gt;",
                  "  &lt;ColumnWidths&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Sarakeleveys&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;94&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;leveys&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;61&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "  &lt;/ColumnWidths&gt;",
                  "  &lt;ColumnDisplayIndex&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Sarakeleveys&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;0&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;leveys&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;1&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "  &lt;/ColumnDisplayIndex&gt;",
                  "  &lt;ColumnFrozen /&gt;",
                  "  &lt;ColumnChecked /&gt;",
                  "  &lt;ColumnFilter /&gt;",
                  "  &lt;SelectionFilter /&gt;",
                  "  &lt;FilterParameters /&gt;",
                  "  &lt;IsSortDescending&gt;false&lt;/IsSortDescending&gt;",
                  "&lt;/TableWidgetGridSerialization&gt;]]&gt;&lt;/AnnotationContent&gt;&lt;/Gemini&gt;"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dw"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Sarakeleveys"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dw].[Sarakeleveys].* FROM [dw].[Sarakeleveys] "
          }
        ]
      },
      {
        "name": "Aputaulu",
        "columns": [
          {
            "name": "Mittari",
            "dataType": "string",
            "sourceColumn": "Mittari",
            "sortByColumn": "jarjestys",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "Mätare",
            "dataType": "string",
            "sourceColumn": "Mätare",
            "sortByColumn": "jarjestys",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "Measure",
            "dataType": "string",
            "sourceColumn": "Measure",
            "sortByColumn": "jarjestys",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "jarjestys",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarjestys",
            "sourceProviderType": "Integer"
          }
        ],
        "partitions": [
          {
            "name": "Aputaulu",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": [
                "SELECT 'Aloituspaikat' as Mittari, 'Nybörjarplatser' as Mätare, 'Intake' as Measure, 1 as jarjestys",
                "UNION ALL",
                "SELECT 'Ensisijaiset hakijat' as Mittari, 'Försthandssökande' as Mätare, 'Applicants expressing first preference' as Measure, 2 as jarjestys",
                "UNION ALL",
                "SELECT 'Hakijat' as Mittari, 'Sökande' as Mätare, 'Applicants' as Measure, 3 as jarjestys",
                "UNION ALL",
                "SELECT 'Valitut' as Mittari, 'Antagna' as Mätare, 'Selected' as Measure, 4 as jarjestys",
                "UNION ALL",
                "SELECT 'Paikan vastaanottaneet' as Mittari, 'Antal som mottagit en plats' as Mätare, 'Accepted a study place' as Measure, 5 as jarjestys",
                "UNION ALL",
                "SELECT 'Läsnäolevaksi ilmoittautuneet' as Mittari, 'Anmält sig som närvarande' as Mätare, 'Enrolled as present' as Measure, 6 as jarjestys"
              ],
              "dataSource": "SqlServer dwitvipusql22 ANTERO"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT 'Aloituspaikat' as Mittari, 'Nybörjarplatser' as Mätare, 'Intake' as Measure, 1 as jarjestys",
                  "UNION ALL",
                  "SELECT 'Ensisijaiset hakijat' as Mittari, 'Försthandssökande' as Mätare, 'Applicants expressing first preference' as Measure, 2 as jarjestys",
                  "UNION ALL",
                  "SELECT 'Hakijat' as Mittari, 'Sökande' as Mätare, 'Applicants' as Measure, 3 as jarjestys",
                  "UNION ALL",
                  "SELECT 'Valitut' as Mittari, 'Antagna' as Mätare, 'Selected' as Measure, 4 as jarjestys",
                  "UNION ALL",
                  "SELECT 'Paikan vastaanottaneet' as Mittari, 'Antal som mottagit en plats' as Mätare, 'Accepted a study place' as Measure, 5 as jarjestys",
                  "UNION ALL",
                  "SELECT 'Läsnäolevaksi ilmoittautuneet' as Mittari, 'Anmält sig som närvarande' as Mätare, 'Enrolled as present' as Measure, 6 as jarjestys</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": [
              "SELECT 'Aloituspaikat' as Mittari, 'Nybörjarplatser' as Mätare, 'Intake' as Measure, 1 as jarjestys",
              "UNION ALL",
              "SELECT 'Ensisijaiset hakijat' as Mittari, 'Försthandssökande' as Mätare, 'Applicants expressing first preference' as Measure, 2 as jarjestys",
              "UNION ALL",
              "SELECT 'Hakijat' as Mittari, 'Sökande' as Mätare, 'Applicants' as Measure, 3 as jarjestys",
              "UNION ALL",
              "SELECT 'Valitut' as Mittari, 'Antagna' as Mätare, 'Selected' as Measure, 4 as jarjestys",
              "UNION ALL",
              "SELECT 'Paikan vastaanottaneet' as Mittari, 'Antal som mottagit en plats' as Mätare, 'Accepted a study place' as Measure, 5 as jarjestys",
              "UNION ALL",
              "SELECT 'Läsnäolevaksi ilmoittautuneet' as Mittari, 'Anmält sig som närvarande' as Mätare, 'Enrolled as present' as Measure, 6 as jarjestys"
            ]
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Aputaulu"
          },
          {
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT 'Aloituspaikat' as Mittari, 'Nybörjarplatser' as Mätare, 'Intake' as Measure, 1 as jarjestys",
              "UNION ALL",
              "SELECT 'Ensisijaiset hakijat' as Mittari, 'Försthandssökande' as Mätare, 'Applicants expressing first preference' as Measure, 2 as jarjestys",
              "UNION ALL",
              "SELECT 'Hakijat' as Mittari, 'Sökande' as Mätare, 'Applicants' as Measure, 3 as jarjestys",
              "UNION ALL",
              "SELECT 'Valitut' as Mittari, 'Antagna' as Mätare, 'Selected' as Measure, 4 as jarjestys",
              "UNION ALL",
              "SELECT 'Paikan vastaanottaneet' as Mittari, 'Antal som mottagit en plats' as Mätare, 'Accepted a study place' as Measure, 5 as jarjestys",
              "UNION ALL",
              "SELECT 'Läsnäolevaksi ilmoittautuneet' as Mittari, 'Anmält sig som närvarande' as Mätare, 'Enrolled as present' as Measure, 6 as jarjestys</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      }
    ],
    "cultures": [
      {
        "name": "en-US",
        "translations": {
          "model": {
            "name": "Model",
            "tables": [
              {
                "name": "Muuttujat",
                "translatedCaption": "Variables",
                "columns": [
                  {
                    "name": "Koodit Koulutusala taso 1 hakukohde",
                    "translatedCaption": "Codes Field of education, tier 1",
                    "translatedDisplayFolder": "Code variables"
                  },
                  {
                    "name": "Koodit Koulutusala taso 2 hakukohde",
                    "translatedCaption": "Codes Field of education, tier 2",
                    "translatedDisplayFolder": "Code variables"
                  },
                  {
                    "name": "Koodit Koulutusala taso 3 hakukohde",
                    "translatedCaption": "Codes Field of education, tier 3",
                    "translatedDisplayFolder": "Code variables"
                  },
                  {
                    "name": "Koodit OKM ohjauksen ala hakukohde",
                    "translatedCaption": "Codes Field of education, HE steering",
                    "translatedDisplayFolder": "Code variables"
                  },
                  {
                    "name": "Koodit Koulutuksen järjestäjä",
                    "translatedCaption": "Codes Education provider",
                    "translatedDisplayFolder": "Code variables"
                  },
                  {
                    "name": "Koodit Korkeakoulu",
                    "translatedCaption": "Codes HE institution",
                    "translatedDisplayFolder": "Code variables"
                  },
                  {
                    "name": "Koodit Maakunta hakukohde",
                    "translatedCaption": "Codes Region of study programme",
                    "translatedDisplayFolder": "Code variables"
                  },
                  {
                    "name": "Koodit Kunta hakukohde",
                    "translatedCaption": "Codes Municipality of study programme",
                    "translatedDisplayFolder": "Code variables"
                  },
                  {
                    "name": "Yo-tutk. suor.vuosi (YTL)",
                    "translatedCaption": "Yo-tutk. suor.vuosi (YTL)"
                  },
                  {
                    "name": "Koodit Pääasiallinen koulutusnimike",
                    "translatedCaption": "Codes Main name of education",
                    "translatedDisplayFolder": "Code variables"
                  },
                  {
                    "name": "Koodit Kotimaakunta hakija*",
                    "translatedCaption": "Codes Region of residence*",
                    "translatedDisplayFolder": "Code variables"
                  },
                  {
                    "name": "Koodit Kotikunta hakija*",
                    "translatedCaption": "Codes Municipality of residence*",
                    "translatedDisplayFolder": "Code variables"
                  }
                ]
              }
            ]
          }
        }
      },
      {
        "name": "sv-SE",
        "translations": {
          "model": {
            "name": "Model",
            "tables": [
              {
                "name": "Muuttujat",
                "translatedCaption": "Variabler",
                "columns": [
                  {
                    "name": "Koodit Koulutusala taso 1 hakukohde",
                    "translatedCaption": "Kod Utbildningsområde, nivå 1",
                    "translatedDisplayFolder": "Kodvariabler"
                  },
                  {
                    "name": "Koodit Koulutusala taso 2 hakukohde",
                    "translatedCaption": "Kod Utbildningsområde, nivå 2",
                    "translatedDisplayFolder": "Kodvariabler"
                  },
                  {
                    "name": "Koodit Koulutusala taso 3 hakukohde",
                    "translatedCaption": "Kod Utbildningsområde, nivå 3",
                    "translatedDisplayFolder": "Kodvariabler"
                  },
                  {
                    "name": "Koodit OKM ohjauksen ala hakukohde",
                    "translatedCaption": "Kod UKM-styrningsområde",
                    "translatedDisplayFolder": "Kodvariabler"
                  },
                  {
                    "name": "Koodit Koulutuksen järjestäjä",
                    "translatedCaption": "Kod Utbildningsanordnare",
                    "translatedDisplayFolder": "Kodvariabler"
                  },
                  {
                    "name": "Koodit Korkeakoulu",
                    "translatedCaption": "Kod Högskola",
                    "translatedDisplayFolder": "Kodvariabler"
                  },
                  {
                    "name": "Koodit Maakunta hakukohde",
                    "translatedCaption": "Kod Landskap (sökobjekt)",
                    "translatedDisplayFolder": "Kodvariabler"
                  },
                  {
                    "name": "Koodit Kunta hakukohde",
                    "translatedCaption": "Kod Kommun (sökobjekt)",
                    "translatedDisplayFolder": "Kodvariabler"
                  },
                  {
                    "name": "Yo-tutk. suor.vuosi (YTL)",
                    "translatedCaption": "Yo-tutk. suor.vuosi (YTL)"
                  },
                  {
                    "name": "Koodit Pääasiallinen koulutusnimike",
                    "translatedCaption": "Kod Huvudsaklig utbildningsbenämning",
                    "translatedDisplayFolder": "Kodvariabler"
                  },
                  {
                    "name": "Koodit Kotimaakunta hakija*",
                    "translatedCaption": "Kod Hemlandskap*",
                    "translatedDisplayFolder": "Kodvariabler"
                  },
                  {
                    "name": "Koodit Kotikunta hakija*",
                    "translatedCaption": "Kod Hemkommun*",
                    "translatedDisplayFolder": "Kodvariabler"
                  }
                ]
              }
            ]
          }
        }
      }
    ],
    "perspectives": [
      {
        "name": "Yhteinen analyysi",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Koodit Korkeakoulu"
              },
              {
                "name": "1 Sektori"
              },
              {
                "name": "4 Aloitussykli"
              },
              {
                "name": "3 Korkeakoulu"
              },
              {
                "name": "Haku AMK/YO"
              },
              {
                "name": "Hakutoive"
              },
              {
                "name": "Kansalaisuus (maanosa)"
              },
              {
                "name": "Ensikertaisena kohdeltava hakija"
              },
              {
                "name": "Ensikertainen hakija"
              },
              {
                "name": "1 Koulutusala, taso 1"
              },
              {
                "name": "2 Koulutusala, taso 1"
              },
              {
                "name": "3 Hakukohde"
              },
              {
                "name": "3 Koulutusala, taso 1"
              },
              {
                "name": "4 Koulutusala, taso 1"
              },
              {
                "name": "5 Koulutusala, taso 1"
              },
              {
                "name": "2 Aloitussykli"
              },
              {
                "name": "Koulutusala, taso 3"
              },
              {
                "name": "Koodit Koulutusala taso 2 hakukohde"
              },
              {
                "name": "Koulutusaste, taso 1"
              },
              {
                "name": "6 Koulutusala, taso 1"
              },
              {
                "name": "6 Sektori"
              },
              {
                "name": "Hakutyyppi"
              },
              {
                "name": "Äidinkieli"
              },
              {
                "name": "2 Sektori"
              },
              {
                "name": "Hakuaika"
              },
              {
                "name": "Korkeakoulu"
              },
              {
                "name": "2 Korkeakoulu"
              },
              {
                "name": "Maakunta (hakukohde)"
              },
              {
                "name": "1 Koulutusala, taso 2"
              },
              {
                "name": "2 Koulutusala, taso 2"
              },
              {
                "name": "3 Koulutusala, taso 2"
              },
              {
                "name": "Koulutusaste, taso 2"
              },
              {
                "name": "4 Hakukohde"
              },
              {
                "name": "4 Koulutusala, taso 2"
              },
              {
                "name": "5 Koulutusala, taso 2"
              },
              {
                "name": "6 Koulutusala, taso 2"
              },
              {
                "name": "Hakukohde"
              },
              {
                "name": "Koulutuksen kieli"
              },
              {
                "name": "Koodit Koulutusala taso 3 hakukohde"
              },
              {
                "name": "Koulutuksen alkamiskausi"
              },
              {
                "name": "Sukupuoli"
              },
              {
                "name": "Koulutusala, taso 2"
              },
              {
                "name": "Koodit Koulutusala taso 1 hakukohde"
              },
              {
                "name": "5 Aloitussykli"
              },
              {
                "name": "5 Sektori"
              },
              {
                "name": "6 Korkeakoulu"
              },
              {
                "name": "Tutkinnon taso (hakukohde)"
              },
              {
                "name": "3 Sektori"
              },
              {
                "name": "Kunta (hakukohde)"
              },
              {
                "name": "Kansalaisuus"
              },
              {
                "name": "OKM ohjauksen ala"
              },
              {
                "name": "1 Koulutusala, taso 3"
              },
              {
                "name": "1 Korkeakoulu"
              },
              {
                "name": "2 Koulutusala, taso 3"
              },
              {
                "name": "3 Koulutusala, taso 3"
              },
              {
                "name": "4 Koulutusala, taso 3"
              },
              {
                "name": "5 Koulutusala, taso 3"
              },
              {
                "name": "6 Koulutusala, taso 3"
              },
              {
                "name": "Kansalaisuus (ryhmä)"
              },
              {
                "name": "Koulutuksen alkamisvuosi"
              },
              {
                "name": "5 Hakukohde"
              },
              {
                "name": "3 Aloitussykli"
              },
              {
                "name": "Opiskelun laajuus"
              },
              {
                "name": "Koodit OKM ohjauksen ala hakukohde"
              },
              {
                "name": "Tutkinnon aloitussykli (hakukohde)"
              },
              {
                "name": "5 Korkeakoulu"
              },
              {
                "name": "Koodit Koulutuksen järjestäjä"
              },
              {
                "name": "Hakutapa"
              },
              {
                "name": "1 Hakukohde"
              },
              {
                "name": "1 Aloitussykli"
              },
              {
                "name": "Koulutusala, taso 1"
              },
              {
                "name": "Koodit Kunta hakukohde"
              },
              {
                "name": "4 Sektori"
              },
              {
                "name": "Toimipiste"
              },
              {
                "name": "Koodit Maakunta hakukohde"
              },
              {
                "name": "6 Hakukohde"
              },
              {
                "name": "4 Korkeakoulu"
              },
              {
                "name": "Sektori"
              },
              {
                "name": "6 Aloitussykli"
              },
              {
                "name": "2 Hakukohde"
              },
              {
                "name": "Yo-tutk. suor.vuosi (YTL)"
              },
              {
                "name": "Hakijan kotimaakunta sama kuin hakukohteen maakunta"
              },
              {
                "name": "Valintatapajonon tyyppi"
              },
              {
                "name": "Uusi ylioppilas"
              },
              {
                "name": "Haun kohdejoukon tarkenne"
              },
              {
                "name": "Pääasiallinen tutkinto (hakukohde)"
              },
              {
                "name": "Koodit Pääasiallinen koulutusnimike"
              },
              {
                "name": "Pohjakoulutus*"
              },
              {
                "name": "Ikäryhmä*"
              },
              {
                "name": "Pohjakoulutuksen maa*"
              },
              {
                "name": "Toisen asteen koulutuksen suoritusvuosi*"
              },
              {
                "name": "Koodit Kotikunta hakija*"
              },
              {
                "name": "Koodit Kotimaakunta hakija*"
              },
              {
                "name": "Pohjakoulutuksen maa (priorisoitu)*"
              },
              {
                "name": "Kotipaikan maakunta (hakija)*"
              },
              {
                "name": "Kotipaikkakunta (hakija)*"
              },
              {
                "name": "Suomessa suoritettu ammatillinen perustutkinto, kouluasteen, opistoasteen tai ammatillisen korkea-asteen tutkinto*"
              },
              {
                "name": "Suomessa suoritettu ammatillinen perustutkinto*"
              },
              {
                "name": "Suomessa suoritettu ammatti- tai erikoisammattitutkinto*"
              },
              {
                "name": "Suomessa suoritettu kouluasteen, opistoasteen tai ammatillisen korkea-asteen tutkinto*"
              },
              {
                "name": "Korkeakoulun edellyttämät avoimen korkeakoulun opinnot*"
              },
              {
                "name": "Suomessa suoritettu korkeakoulututkinto*"
              },
              {
                "name": "Muualla kuin Suomessa suoritettu korkeakoulututkinto*"
              },
              {
                "name": "Suomessa suoritettu lukion oppimäärä ilman ylioppilastutkintoa*"
              },
              {
                "name": "Muualla kuin Suomessa suoritettu toisen asteen koulutus, joka asianomaisessa maassa antaa hakukelpoisuuden korkeakouluun*"
              },
              {
                "name": "Suomessa suoritettu ylioppilastutkinto*"
              },
              {
                "name": "Suomessa suoritettu kaksoistutkinto (ammatillinen perustutkinto ja ylioppilastutkinto)*"
              },
              {
                "name": "Suomessa suoritettu kansainvälinen ylioppilastutkinto (IB, EB ja RP/DIA)*"
              },
              {
                "name": "Muualla kuin Suomessa suoritettu kansainvälinen ylioppilastutkinto (IB, EB ja RP/DIA)*"
              },
              {
                "name": "Muu korkeakoulukelpoisuus*"
              },
              {
                "name": "Kansainvälinen opiskelija*"
              }
            ],
            "measures": [
              {
                "name": "Kaikki hakijat"
              },
              {
                "name": "Aloituspaikat"
              },
              {
                "name": "Läsnäolevaksi ilmoittautuneet"
              },
              {
                "name": "Ensisijaiset hakijat"
              },
              {
                "name": "Kaikki hakijat (nettouttamaton)"
              },
              {
                "name": "Valitut"
              },
              {
                "name": "Paikan vastaanottaneet"
              },
              {
                "name": "Alin hyväksytty pistemäärä"
              },
              {
                "name": "Sama sektori, eri korkeakoulu, sama ala; paikan vastaanottaneet"
              },
              {
                "name": "Sama korkeakoulu, sama ala; paikan vastaanottaneet"
              },
              {
                "name": "Eri sektori, sama ala; paikan vastaanottaneet"
              },
              {
                "name": "Sama korkeakoulu, eri ala; paikan vastaanottaneet"
              },
              {
                "name": "I hakutoiveen paikan vastaanottaneet"
              },
              {
                "name": "Ensikertaisten osuus, hakijat"
              },
              {
                "name": "Ensikertaisten osuus, paikan vastaanottaneet"
              },
              {
                "name": "Ensikertaisten osuus, valitut"
              },
              {
                "name": "Uusien ylioppilaiden osuus, ensisijaiset hakijat (I sykli)"
              },
              {
                "name": "Uusien ylioppilaiden osuus, hakijat (I sykli)"
              },
              {
                "name": "Uusien ylioppilaiden osuus, paikan vastaanottaneet (I sykli)"
              },
              {
                "name": "Uusien ylioppilaiden osuus, valitut (I sykli)"
              },
              {
                "name": "Eri sektori, eri ala; paikan vastaanottaneet"
              },
              {
                "name": "Valituista paikan vastaanottamatta jättäneiden osuus"
              },
              {
                "name": "Ei opintopaikkaa vastaanottaneiden osuus (I sykli)2"
              },
              {
                "name": "Sama sektori, eri korkeakoulu, eri ala; paikan vastaanottaneet"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Yhteinen perus",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Kunta (hakukohde)"
              },
              {
                "name": "OKM ohjauksen ala"
              },
              {
                "name": "Korkeakoulu"
              },
              {
                "name": "Kansalaisuus (ryhmä)"
              },
              {
                "name": "Maakunta (hakukohde)"
              },
              {
                "name": "Koulutuksen alkamisvuosi"
              },
              {
                "name": "Haku AMK/YO"
              },
              {
                "name": "Koulutusaste, taso 2"
              },
              {
                "name": "Hakukohde"
              },
              {
                "name": "Sektori"
              },
              {
                "name": "Tutkinnon aloitussykli (hakukohde)"
              },
              {
                "name": "Ensikertaisena kohdeltava hakija"
              },
              {
                "name": "Ensikertainen hakija"
              },
              {
                "name": "Koulutuksen alkamiskausi"
              },
              {
                "name": "Koulutusaste, taso 1"
              },
              {
                "name": "Koulutusala, taso 3"
              },
              {
                "name": "Sukupuoli"
              },
              {
                "name": "Äidinkieli"
              },
              {
                "name": "Hakutapa"
              },
              {
                "name": "Hakutyyppi"
              },
              {
                "name": "Koulutusala, taso 2"
              },
              {
                "name": "Koulutusala, taso 1"
              },
              {
                "name": "Toimipiste"
              },
              {
                "name": "Valintatapajonon tyyppi"
              },
              {
                "name": "Pääasiallinen tutkinto (hakukohde)"
              },
              {
                "name": "Ikäryhmä*"
              },
              {
                "name": "Kotipaikkakunta (hakija)*"
              },
              {
                "name": "Kotipaikan maakunta (hakija)*"
              },
              {
                "name": "Kansainvälinen opiskelija*"
              }
            ],
            "measures": [
              {
                "name": "Kaikki hakijat"
              },
              {
                "name": "Aloituspaikat"
              },
              {
                "name": "Ensisijaiset hakijat"
              },
              {
                "name": "Paikan vastaanottaneet"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Yhteinen analyysiSV",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Utb.område, nivå 1 (sökobjekt)"
              },
              {
                "name": "Koodit Korkeakoulu"
              },
              {
                "name": "3 Utb.område, nivå 2"
              },
              {
                "name": "Ansökan YH/Univ."
              },
              {
                "name": "Ansökningsönskemål"
              },
              {
                "name": "Behandlas som förstagångssökande"
              },
              {
                "name": "Förstagångssökande"
              },
              {
                "name": "Högskola"
              },
              {
                "name": "Sökobjekt"
              },
              {
                "name": "1 Utb.område, nivå 2"
              },
              {
                "name": "4 Sökobjekt"
              },
              {
                "name": "5 Utb.område, nivå 3"
              },
              {
                "name": "Cykeln (sökobjekt)"
              },
              {
                "name": "Kommun (sökobjekt)"
              },
              {
                "name": "Sektor"
              },
              {
                "name": "4 Utb.område, nivå 3"
              },
              {
                "name": "6 Utb.område, nivå 1"
              },
              {
                "name": "Examensnivå (sökobjekt)"
              },
              {
                "name": "Medborgarskap"
              },
              {
                "name": "Studiernas omfattning"
              },
              {
                "name": "Koodit Koulutuksen järjestäjä"
              },
              {
                "name": "Koodit Koulutusala taso 2 hakukohde"
              },
              {
                "name": "2 Sökobjekt"
              },
              {
                "name": "3 Utb.område, nivå 3"
              },
              {
                "name": "5 Utb.område, nivå 1"
              },
              {
                "name": "Kön"
              },
              {
                "name": "Utb.område, nivå 2 (sökobjekt)"
              },
              {
                "name": "Koodit Kunta hakukohde"
              },
              {
                "name": "Koodit Maakunta hakukohde"
              },
              {
                "name": "2 Utb.område, nivå 3"
              },
              {
                "name": "4 Utb.område, nivå 1"
              },
              {
                "name": "Medborgarskap (världsdel)"
              },
              {
                "name": "Utb.nivå, nivå 1"
              },
              {
                "name": "Ansökningstid"
              },
              {
                "name": "Typ av ansökan"
              },
              {
                "name": "1 Utb.område, nivå 3"
              },
              {
                "name": "3 Utb.område, nivå 1"
              },
              {
                "name": "5 Sökobjekt"
              },
              {
                "name": "2 Utb.område, nivå 1"
              },
              {
                "name": "6 Utb.område, nivå 2"
              },
              {
                "name": "Koodit Koulutusala taso 3 hakukohde"
              },
              {
                "name": "3 Sökobjekt"
              },
              {
                "name": "5 Utb.område, nivå 2"
              },
              {
                "name": "Medborgarskap (gruppen)"
              },
              {
                "name": "Landskap (sökobjekt)"
              },
              {
                "name": "UKM-styrningsområde (sökobjekt)"
              },
              {
                "name": "1 Utb.område, nivå 1"
              },
              {
                "name": "Modersmål"
              },
              {
                "name": "Utb.område, nivå 3 (sökobjekt)"
              },
              {
                "name": "Koodit Koulutusala taso 1 hakukohde"
              },
              {
                "name": "1 Sökobjekt"
              },
              {
                "name": "4 Utb.område, nivå 2"
              },
              {
                "name": "Utbildningens språk"
              },
              {
                "name": "Anstalt"
              },
              {
                "name": "Utb.nivå, nivå 2"
              },
              {
                "name": "6 Sökobjekt"
              },
              {
                "name": "Gemensam/separat ansökan"
              },
              {
                "name": "6 Utb.område, nivå 3"
              },
              {
                "name": "2 Utb.område, nivå 2"
              },
              {
                "name": "Begynnelsetermin"
              },
              {
                "name": "Begynnelseår"
              },
              {
                "name": "Koodit OKM ohjauksen ala hakukohde"
              },
              {
                "name": "1 Cykeln"
              },
              {
                "name": "1 Högskola"
              },
              {
                "name": "1 Sektor"
              },
              {
                "name": "2 Cykeln"
              },
              {
                "name": "2 Högskola"
              },
              {
                "name": "2 Sektor"
              },
              {
                "name": "3 Cykeln"
              },
              {
                "name": "3 Högskola"
              },
              {
                "name": "3 Sektor"
              },
              {
                "name": "4 Cykeln"
              },
              {
                "name": "4 Högskola"
              },
              {
                "name": "4 Sektor"
              },
              {
                "name": "5 Cykeln"
              },
              {
                "name": "5 Högskola"
              },
              {
                "name": "5 Sektor"
              },
              {
                "name": "6 Cykeln"
              },
              {
                "name": "6 Högskola"
              },
              {
                "name": "6 Sektor"
              },
              {
                "name": "Ansökans målgrupps specifikation"
              },
              {
                "name": "Koodit Pääasiallinen koulutusnimike"
              },
              {
                "name": "Huvudsaklig examen (ansökningsmål)"
              },
              {
                "name": "Åldersgrupp*"
              },
              {
                "name": "Hemkommun*"
              },
              {
                "name": "Koodit Kotikunta hakija*"
              },
              {
                "name": "Grundutbildning*"
              },
              {
                "name": "Koodit Kotimaakunta hakija*"
              },
              {
                "name": "Grundutbildningens land*"
              },
              {
                "name": "År då andra stadiets utbildning avlagts*"
              },
              {
                "name": "Hemlandskap*"
              },
              {
                "name": "Grundutbildningens land (prioriterat)*"
              },
              {
                "name": "Gymnasiets lärokurs som avlagts i Finland utan studentexamen*"
              },
              {
                "name": "Högskoleexamen som avlagts annanstans än i Finland*"
              },
              {
                "name": "Högskoleexamen som avlagts i Finland*"
              },
              {
                "name": "Internationell studentexamen som avlagts annanstans än i Finland (IB, EB och RP/DIA)*"
              },
              {
                "name": "Internationell studentexamen som avlagts i Finland (IB, EB och RP/DIA)*"
              },
              {
                "name": "Studentexamen som avlagts i Finland*"
              },
              {
                "name": "Studier som högskolan kräver vid en öppen högskola*"
              },
              {
                "name": "Utbildning på andra stadiet som avlagts annanstans än i Finland, och ger behörighet för högskolestudier i ifrågavarande land*"
              },
              {
                "name": "Yrkesexamen eller specialyrkesexamen som avlagts i Finland*"
              },
              {
                "name": "Yrkesinr. grundex., examen på skolnivå, examen på institutsnivå eller yrkesinr. examen på högre nivå som avlagts i Finland*"
              },
              {
                "name": "Yrkesinriktad examen på skolnivå, examen på institutsnivå eller yrkesinriktad examen på högre nivå som avlagts i Finland*"
              },
              {
                "name": "Yrkesinriktad grundexamen som avlagts i Finland*"
              },
              {
                "name": "Övrig högskolebehörighet*"
              }
            ],
            "measures": [
              {
                "name": "Antagna"
              },
              {
                "name": "Nybörjarplatser"
              },
              {
                "name": "Samtliga sökande"
              },
              {
                "name": "Antal som mottagit en plats"
              },
              {
                "name": "Försthandssökande"
              },
              {
                "name": "Närvarande"
              },
              {
                "name": "Samtliga sökande (utan nettning)"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Yhteinen perusSV",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Anstalt"
              },
              {
                "name": "Utb.område, nivå 1 (sökobjekt)"
              },
              {
                "name": "Utb.nivå, nivå 2"
              },
              {
                "name": "Gemensam/separat ansökan"
              },
              {
                "name": "Utb.nivå, nivå 1"
              },
              {
                "name": "Ansökan YH/Univ."
              },
              {
                "name": "Typ av ansökan"
              },
              {
                "name": "Begynnelsetermin"
              },
              {
                "name": "Begynnelseår"
              },
              {
                "name": "Behandlas som förstagångssökande"
              },
              {
                "name": "Förstagångssökande"
              },
              {
                "name": "Högskola"
              },
              {
                "name": "Sökobjekt"
              },
              {
                "name": "Kön"
              },
              {
                "name": "Cykeln (sökobjekt)"
              },
              {
                "name": "Kommun (sökobjekt)"
              },
              {
                "name": "Medborgarskap (gruppen)"
              },
              {
                "name": "Sektor"
              },
              {
                "name": "Landskap (sökobjekt)"
              },
              {
                "name": "UKM-styrningsområde (sökobjekt)"
              },
              {
                "name": "Modersmål"
              },
              {
                "name": "Hemlandskap*"
              },
              {
                "name": "Åldersgrupp*"
              },
              {
                "name": "Hemkommun*"
              }
            ],
            "measures": [
              {
                "name": "Nybörjarplatser"
              },
              {
                "name": "Samtliga sökande"
              },
              {
                "name": "Antal som mottagit en plats"
              },
              {
                "name": "Försthandssökande"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Yhteinen analyysiEN",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Language of education"
              },
              {
                "name": "Koodit Korkeakoulu"
              },
              {
                "name": "4 Study programme"
              },
              {
                "name": "Level of degree"
              },
              {
                "name": "Nationality (group)"
              },
              {
                "name": "Field of ed., tier 2"
              },
              {
                "name": "Considered as a first-time applicant"
              },
              {
                "name": "First-time applicant"
              },
              {
                "name": "1 Field of ed., tier 1"
              },
              {
                "name": "2 Field of ed., tier 1"
              },
              {
                "name": "3 Field of ed., tier 1"
              },
              {
                "name": "4 Field of ed., tier 1"
              },
              {
                "name": "Extent of the study programme"
              },
              {
                "name": "Koodit Koulutusala taso 2 hakukohde"
              },
              {
                "name": "3 Study programme"
              },
              {
                "name": "5 Field of ed., tier 1"
              },
              {
                "name": "6 Field of ed., tier 1"
              },
              {
                "name": "Koodit Kunta hakukohde"
              },
              {
                "name": "Sector"
              },
              {
                "name": "Koodit Maakunta hakukohde"
              },
              {
                "name": "2 Study programme"
              },
              {
                "name": "Higher education institution"
              },
              {
                "name": "Joint/separate application"
              },
              {
                "name": "Region of study programme"
              },
              {
                "name": "Level of ed., tier 1"
              },
              {
                "name": "1 Field of ed., tier 2"
              },
              {
                "name": "2 Field of ed., tier 2"
              },
              {
                "name": "Field of ed., tier 3"
              },
              {
                "name": "Term (start of studies)"
              },
              {
                "name": "1 Study programme"
              },
              {
                "name": "3 Field of ed., tier 2"
              },
              {
                "name": "4 Field of ed., tier 2"
              },
              {
                "name": "5 Field of ed., tier 2"
              },
              {
                "name": "6 Field of ed., tier 2"
              },
              {
                "name": "Faculty/campus"
              },
              {
                "name": "Koodit Koulutusala taso 3 hakukohde"
              },
              {
                "name": "6 Study programme"
              },
              {
                "name": "Nationality"
              },
              {
                "name": "Year (start of studies)"
              },
              {
                "name": "Beginning cycle of education"
              },
              {
                "name": "Field of ed., tier 1"
              },
              {
                "name": "Koodit Koulutusala taso 1 hakukohde"
              },
              {
                "name": "Application round"
              },
              {
                "name": "Applied study programme"
              },
              {
                "name": "5 Study programme"
              },
              {
                "name": "Application to UAS/Univ."
              },
              {
                "name": "Level of ed., tier 2"
              },
              {
                "name": "Application period"
              },
              {
                "name": "Municipality of study programme"
              },
              {
                "name": "Preference of study programme"
              },
              {
                "name": "1 Field of ed., tier 3"
              },
              {
                "name": "2 Field of ed., tier 3"
              },
              {
                "name": "3 Field of ed., tier 3"
              },
              {
                "name": "4 Field of ed., tier 3"
              },
              {
                "name": "5 Field of ed., tier 3"
              },
              {
                "name": "6 Field of ed., tier 3"
              },
              {
                "name": "Field of ed., HE steering"
              },
              {
                "name": "Gender"
              },
              {
                "name": "Mother tongue"
              },
              {
                "name": "Koodit OKM ohjauksen ala hakukohde"
              },
              {
                "name": "Nationality (continent)"
              },
              {
                "name": "Koodit Koulutuksen järjestäjä"
              },
              {
                "name": "1 Beginning cycle"
              },
              {
                "name": "1 HE institution"
              },
              {
                "name": "1 Sector"
              },
              {
                "name": "2 Beginning cycle"
              },
              {
                "name": "2 HE institution"
              },
              {
                "name": "2 Sector"
              },
              {
                "name": "3 Beginning cycle"
              },
              {
                "name": "3 HE institution"
              },
              {
                "name": "3 Sector"
              },
              {
                "name": "4 Beginning cycle"
              },
              {
                "name": "4 HE institution"
              },
              {
                "name": "4 Sector"
              },
              {
                "name": "5 Beginning cycle"
              },
              {
                "name": "5 HE institution"
              },
              {
                "name": "5 Sector"
              },
              {
                "name": "6 Beginning cycle"
              },
              {
                "name": "6 HE institution"
              },
              {
                "name": "6 Sector"
              },
              {
                "name": "Applied study programme group specification"
              },
              {
                "name": "Koodit Pääasiallinen koulutusnimike"
              },
              {
                "name": "Main degree (applied study programme)"
              },
              {
                "name": "Municipality of residence*"
              },
              {
                "name": "Koodit Kotimaakunta hakija*"
              },
              {
                "name": "Age group*"
              },
              {
                "name": "Prior education*"
              },
              {
                "name": "Region of residence*"
              },
              {
                "name": "Koodit Kotikunta hakija*"
              },
              {
                "name": "Country of prior education*"
              },
              {
                "name": "Country of prior education (prioritised)*"
              },
              {
                "name": "Graduation year (upper secondary education)*"
              },
              {
                "name": "Bachelor’s/Master’s/Doctoral degree completed in Finland*"
              },
              {
                "name": "Bachelor’s/Master’s/Doctoral degree completed outside Finland*"
              },
              {
                "name": "Double upper secondary qualification completed in Finland (kaksoistutkinto)*"
              },
              {
                "name": "Former vocational qualification completed in Finland (kouluasteen, opistoasteen tai ammatillisen korkea-asteen tutkinto)*"
              },
              {
                "name": "Further or specialist vocational qualification completed in Finland (ammatti- tai erikoisammattitutkinto)*"
              },
              {
                "name": "General upper secondary school syllabus completed in Finland (without matriculation examination)*"
              },
              {
                "name": "International matriculation examination completed in Finland (IB, EB and RP/DIA)*"
              },
              {
                "name": "International matriculation examination completed outside Finland (IB, EB and RP/DIA)*"
              },
              {
                "name": "Matriculation examination completed in Finland*"
              },
              {
                "name": "Other eligibility for higher education*"
              },
              {
                "name": "Studies required by the higher education institution completed at open university or open polytechnic/UAS*"
              },
              {
                "name": "Upper secondary education completed outside Finland (general or vocational)*"
              },
              {
                "name": "Vocat. upper sec. qualif., school-level qualif., post-sec. level qualif. or higher vocat. level qualif. cmpl. in Finland*"
              },
              {
                "name": "Vocational upper secondary qualification completed in Finland (ammatillinen perustutkinto)*"
              }
            ],
            "measures": [
              {
                "name": "Accepted a study place"
              },
              {
                "name": "All applicants (no netting)"
              },
              {
                "name": "Applicants expressing first preference"
              },
              {
                "name": "Selected"
              },
              {
                "name": "All applicants"
              },
              {
                "name": "Enrolled as present"
              },
              {
                "name": "Intake"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Yhteinen perusEN",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Application to UAS/Univ."
              },
              {
                "name": "Sector"
              },
              {
                "name": "Level of ed., tier 2"
              },
              {
                "name": "Higher education institution"
              },
              {
                "name": "Joint/separate application"
              },
              {
                "name": "Municipality of study programme"
              },
              {
                "name": "Region of study programme"
              },
              {
                "name": "Level of ed., tier 1"
              },
              {
                "name": "Field of ed., HE steering"
              },
              {
                "name": "Gender"
              },
              {
                "name": "Mother tongue"
              },
              {
                "name": "Nationality (group)"
              },
              {
                "name": "Term (start of studies)"
              },
              {
                "name": "Faculty/campus"
              },
              {
                "name": "Considered as a first-time applicant"
              },
              {
                "name": "First-time applicant"
              },
              {
                "name": "Year (start of studies)"
              },
              {
                "name": "Beginning cycle of education"
              },
              {
                "name": "Field of ed., tier 1"
              },
              {
                "name": "Application round"
              },
              {
                "name": "Applied study programme"
              },
              {
                "name": "Age group*"
              },
              {
                "name": "Region of residence*"
              },
              {
                "name": "Municipality of residence*"
              }
            ],
            "measures": [
              {
                "name": "Accepted a study place"
              },
              {
                "name": "Applicants expressing first preference"
              },
              {
                "name": "All applicants"
              },
              {
                "name": "Intake"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Pisteraja",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Ensikertaisena kohdeltava hakija"
              },
              {
                "name": "Ensikertainen hakija"
              },
              {
                "name": "Haku AMK/YO"
              },
              {
                "name": "Hakukohde"
              },
              {
                "name": "Hakutapa"
              },
              {
                "name": "Hakutyyppi"
              },
              {
                "name": "Kansalaisuus (ryhmä)"
              },
              {
                "name": "Korkeakoulu"
              },
              {
                "name": "Koulutuksen alkamiskausi"
              },
              {
                "name": "Koulutuksen alkamisvuosi"
              },
              {
                "name": "Koulutusala, taso 1"
              },
              {
                "name": "Koulutusala, taso 2"
              },
              {
                "name": "Koulutusala, taso 3"
              },
              {
                "name": "Koulutusaste, taso 1"
              },
              {
                "name": "Koulutusaste, taso 2"
              },
              {
                "name": "Kunta (hakukohde)"
              },
              {
                "name": "Maakunta (hakukohde)"
              },
              {
                "name": "OKM ohjauksen ala"
              },
              {
                "name": "Sektori"
              },
              {
                "name": "Sukupuoli"
              },
              {
                "name": "Toimipiste"
              },
              {
                "name": "Tutkinnon aloitussykli (hakukohde)"
              },
              {
                "name": "Äidinkieli"
              },
              {
                "name": "Valintatapajonon nimi"
              },
              {
                "name": "Valintatapajonon tyyppi"
              },
              {
                "name": "Ikäryhmä*"
              },
              {
                "name": "Kotipaikan maakunta (hakija)*"
              },
              {
                "name": "Kotipaikkakunta (hakija)*"
              }
            ],
            "measures": [
              {
                "name": "Alin hyväksytty pistemäärä"
              },
              {
                "name": "Ylin hyväksytty pistemäärä"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "PisterajaSV",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Anstalt"
              },
              {
                "name": "Begynnelsetermin"
              },
              {
                "name": "Begynnelseår"
              },
              {
                "name": "Cykeln (sökobjekt)"
              },
              {
                "name": "Högskola"
              },
              {
                "name": "Landskap (sökobjekt)"
              },
              {
                "name": "Sektor"
              },
              {
                "name": "Sökobjekt"
              },
              {
                "name": "Typ av antagningskö"
              },
              {
                "name": "Utb.nivå, nivå 1"
              },
              {
                "name": "Utb.nivå, nivå 2"
              },
              {
                "name": "Utb.område, nivå 1 (sökobjekt)"
              },
              {
                "name": "Utb.område, nivå 2 (sökobjekt)"
              },
              {
                "name": "Utb.område, nivå 3 (sökobjekt)"
              },
              {
                "name": "Namnet på antagningskö"
              }
            ],
            "measures": [
              {
                "name": "Högsta inträdespoäng för godkända"
              },
              {
                "name": "Lägsta inträdespoäng för godkända"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "PisterajaEN",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Applied study programme"
              },
              {
                "name": "Beginning cycle of education"
              },
              {
                "name": "Faculty/campus"
              },
              {
                "name": "Field of ed., tier 1"
              },
              {
                "name": "Field of ed., tier 2"
              },
              {
                "name": "Field of ed., tier 3"
              },
              {
                "name": "Higher education institution"
              },
              {
                "name": "Level of ed., tier 1"
              },
              {
                "name": "Level of ed., tier 2"
              },
              {
                "name": "Region of study programme"
              },
              {
                "name": "Sector"
              },
              {
                "name": "Term (start of studies)"
              },
              {
                "name": "Type of admission queue"
              },
              {
                "name": "Year (start of studies)"
              }
            ],
            "measures": [
              {
                "name": "Highest accepted score"
              },
              {
                "name": "Lowest accepted score"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Yhteinen perus_s",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Hakukohde"
              },
              {
                "name": "Hakutapa"
              },
              {
                "name": "Hakutyyppi"
              },
              {
                "name": "Korkeakoulu"
              },
              {
                "name": "Koulutuksen alkamiskausi"
              },
              {
                "name": "Koulutuksen alkamisvuosi"
              },
              {
                "name": "Koulutusala, taso 1"
              },
              {
                "name": "Koulutusala, taso 2"
              },
              {
                "name": "Koulutusala, taso 3"
              },
              {
                "name": "Koulutusaste, taso 1"
              },
              {
                "name": "Koulutusaste, taso 2"
              },
              {
                "name": "Kunta (hakukohde)"
              },
              {
                "name": "Maakunta (hakukohde)"
              },
              {
                "name": "OKM ohjauksen ala"
              },
              {
                "name": "Sektori"
              },
              {
                "name": "Toimipiste"
              },
              {
                "name": "Tutkinnon aloitussykli (hakukohde)"
              },
              {
                "name": "Valintatapajonon tyyppi"
              },
              {
                "name": "Koulutuksen kieli"
              },
              {
                "name": "Pääasiallinen tutkinto (hakukohde)"
              }
            ],
            "measures": [
              {
                "name": "Paikan vastaanottaneet_s"
              },
              {
                "name": "Ensisijaiset hakijat_s"
              },
              {
                "name": "Kaikki hakijat_s"
              },
              {
                "name": "Aloituspaikat"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "OmaVipunen",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Hakuaika"
              },
              {
                "name": "Hakutapa"
              },
              {
                "name": "Hakutyyppi"
              },
              {
                "name": "Kansalaisuus"
              },
              {
                "name": "Kansalaisuus (ryhmä)"
              },
              {
                "name": "Koulutuksen alkamiskausi"
              },
              {
                "name": "Koulutuksen alkamisvuosi"
              },
              {
                "name": "Koulutuksen kieli"
              },
              {
                "name": "Koulutusala, taso 1"
              },
              {
                "name": "OKM ohjauksen ala"
              },
              {
                "name": "Sektori"
              },
              {
                "name": "Tutkinnon aloitussykli (hakukohde)"
              },
              {
                "name": "Korkeakoulu"
              }
            ],
            "measures": [
              {
                "name": "Aloittaneet"
              },
              {
                "name": "Aloituspaikat"
              },
              {
                "name": "Ensisijaiset hakijat"
              },
              {
                "name": "Kaikki hakijat"
              },
              {
                "name": "Paikan vastaanottaneet"
              },
              {
                "name": "Valitut"
              }
            ]
          }
        ]
      },
      {
        "name": "OmaVipunen_EN",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Application period"
              },
              {
                "name": "Application round"
              },
              {
                "name": "Beginning cycle of education"
              },
              {
                "name": "Field of ed., HE steering"
              },
              {
                "name": "Field of ed., tier 1"
              },
              {
                "name": "Joint/separate application"
              },
              {
                "name": "Language of education"
              },
              {
                "name": "Nationality"
              },
              {
                "name": "Nationality (group)"
              },
              {
                "name": "Sector"
              },
              {
                "name": "Term (start of studies)"
              },
              {
                "name": "Year (start of studies)"
              },
              {
                "name": "Higher education institution"
              }
            ],
            "measures": [
              {
                "name": "Accepted a study place"
              },
              {
                "name": "Admitted"
              },
              {
                "name": "All applicants"
              },
              {
                "name": "Enrolled as present"
              },
              {
                "name": "Intake"
              },
              {
                "name": "Selected"
              }
            ]
          }
        ]
      }
    ],
    "roles": [
      {
        "name": "Testi",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "DWI\\T_VIPU_SSAS_DB_R_TK",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1753"
          },
          {
            "memberName": "DWI\\T_VIPU_SSAS_DB_R",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1751"
          },
          {
            "memberName": "DWI\\T_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1732"
          },
          {
            "memberName": "DWI\\Z_DWIPVIPURD_Allow_F_Drive",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-5333"
          },
          {
            "memberName": "DWI\\Z_DWIPVIPURD_Allow_All_Drives",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-5673"
          }
        ]
      },
      {
        "name": "Tuotanto",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "DWI\\P_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1733"
          },
          {
            "memberName": "DWI\\P_VIPU_SSAS_DB_R",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1752"
          },
          {
            "memberName": "DWI\\P_VIPU_SSAS_DB_R_TK",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1754"
          },
          {
            "memberName": "DWI\\Z_DWIPVIPURD_Allow_All_Drives",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-5673"
          },
          {
            "memberName": "DWI\\Z_DWIVIPURD_Allow_E_Drive",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-5359"
          }
        ]
      }
    ]
  },
  "id": "SemanticModel"
}