{
  "name": "SemanticModel",
  "compatibilityLevel": 1200,
  "model": {
    "culture": "fi-FI",
    "dataSources": [
      {
        "name": "dwitvipusql22",
        "connectionString": "Provider=SQLOLEDB.1.1;Integrated Security=SSPI;Persist Security Info=False;Initial Catalog=ANTERO;Data Source=dwitvipusql22",
        "impersonationMode": "impersonateAccount",
        "account": "DWI\\T_VIPUTK_KUUTIO",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "Sarakeleveys",
        "isHidden": true,
        "columns": [
          {
            "name": "Sarakeleveys",
            "dataType": "string",
            "sourceColumn": "Sarakeleveys",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "leveys",
            "dataType": "string",
            "sourceColumn": "leveys",
            "sourceProviderType": "VarChar"
          }
        ],
        "partitions": [
          {
            "name": "Sarakeleveys",
            "dataView": "full",
            "source": {
              "query": [
                "SELECT [Sarakeleveys]",
                "      ,[leveys]",
                "  FROM [dw].[Sarakeleveys]"
              ],
              "dataSource": "dwitvipusql22"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [Sarakeleveys]",
                  "      ,[leveys]",
                  "  FROM [dw].[Sarakeleveys]</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": [
              "SELECT [Sarakeleveys]",
              "      ,[leveys]",
              "  FROM [dw].[Sarakeleveys]"
            ]
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Sarakeleveys"
          },
          {
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [Sarakeleveys]",
              "      ,[leveys]",
              "  FROM [dw].[Sarakeleveys]</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Muuttujat",
        "columns": [
          {
            "name": "tilv",
            "dataType": "string",
            "sourceColumn": "tilv",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "aineisto",
            "dataType": "string",
            "sourceColumn": "aineisto",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "prioriteetti",
            "dataType": "string",
            "sourceColumn": "prioriteetti",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "toteuma_tutk",
            "dataType": "string",
            "sourceColumn": "toteuma_tutk",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "tyov",
            "dataType": "string",
            "sourceColumn": "tyov",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "jarj_opisk",
            "dataType": "string",
            "sourceColumn": "jarj_opisk",
            "sortByColumn": "jarjnimi_opisk",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "jarjnimi_opisk",
            "dataType": "string",
            "sourceColumn": "jarjnimi_opisk",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "kaste_t2",
            "dataType": "string",
            "sourceColumn": "kaste_t2",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "kaste_t2ni",
            "dataType": "string",
            "sourceColumn": "kaste_t2ni",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "iscfibroad2013",
            "dataType": "string",
            "sourceColumn": "iscfibroad2013",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "kala_t1ni",
            "dataType": "string",
            "sourceColumn": "kala_t1ni",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "oppis",
            "dataType": "string",
            "sourceColumn": "oppis",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "tutklaja",
            "dataType": "string",
            "sourceColumn": "tutklaja",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "alvv",
            "dataType": "string",
            "sourceColumn": "alvv",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "allk",
            "dataType": "string",
            "sourceColumn": "allk",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "kaste_t2_e",
            "dataType": "string",
            "sourceColumn": "kaste_t2_e",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "kaste_t2ni_e",
            "dataType": "string",
            "sourceColumn": "kaste_t2ni_e",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "ptoim1r2e",
            "dataType": "string",
            "sourceColumn": "ptoim1r2e",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "kaste_t2_evj",
            "dataType": "string",
            "sourceColumn": "kaste_t2_evj",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "kaste_t2ni_evj",
            "dataType": "string",
            "sourceColumn": "kaste_t2ni_evj",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "amase",
            "dataType": "string",
            "sourceColumn": "amase",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "ptoim1r2h",
            "dataType": "string",
            "sourceColumn": "ptoim1r2h",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "kaste_t2_avh",
            "dataType": "string",
            "sourceColumn": "kaste_t2_avh",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "kaste_t2ni_avh",
            "dataType": "string",
            "sourceColumn": "kaste_t2ni_avh",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "amash",
            "dataType": "string",
            "sourceColumn": "amash",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "tutk_suor_1",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "tutk_suor_1",
            "sourceProviderType": "Integer"
          },
          {
            "name": "tutk_suor_2",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "tutk_suor_2",
            "sourceProviderType": "Integer"
          },
          {
            "name": "tutk_suor_3",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "tutk_suor_3",
            "sourceProviderType": "Integer"
          },
          {
            "name": "tutk_suor_4",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "tutk_suor_4",
            "sourceProviderType": "Integer"
          },
          {
            "name": "tutk_osia_suor_1",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "tutk_osia_suor_1",
            "sourceProviderType": "Integer"
          },
          {
            "name": "tutk_osia_suor_2",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "tutk_osia_suor_2",
            "sourceProviderType": "Integer"
          },
          {
            "name": "tutk_osia_suor_3",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "tutk_osia_suor_3",
            "sourceProviderType": "Integer"
          },
          {
            "name": "tutk_osia_suor_4",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "tutk_osia_suor_4",
            "sourceProviderType": "Integer"
          },
          {
            "name": "tutk_suor_5",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "tutk_suor_5",
            "sourceProviderType": "Integer"
          },
          {
            "name": "tutk_suor_6",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "tutk_suor_6",
            "sourceProviderType": "Integer"
          },
          {
            "name": "tutk_suor_7",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "tutk_suor_7",
            "sourceProviderType": "Integer"
          },
          {
            "name": "tutk_suor_8",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "tutk_suor_8",
            "sourceProviderType": "Integer"
          },
          {
            "name": "tutk_osia_suor_5",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "tutk_osia_suor_5",
            "sourceProviderType": "Integer"
          },
          {
            "name": "tutk_osia_suor_6",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "tutk_osia_suor_6",
            "sourceProviderType": "Integer"
          },
          {
            "name": "tutk_osia_suor_7",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "tutk_osia_suor_7",
            "sourceProviderType": "Integer"
          },
          {
            "name": "tutk_osia_suor_8",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "tutk_osia_suor_8",
            "sourceProviderType": "Integer"
          },
          {
            "name": "lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "jarjmaak",
            "dataType": "string",
            "sourceColumn": "jarjmaak"
          },
          {
            "name": "jarjmaaknimi",
            "dataType": "string",
            "sourceColumn": "jarjmaaknimi"
          },
          {
            "name": "aluekerroin",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "aluekerroin"
          },
          {
            "name": "allk_kytkin",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "allk_kytkin"
          },
          {
            "name": "amase_kytkin",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "amase_kytkin"
          },
          {
            "name": "amash_kytkin",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "amash_kytkin"
          },
          {
            "name": "oppis_kytkin",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "oppis_kytkin"
          },
          {
            "name": "prioriteetti_kytkin",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "prioriteetti_kytkin"
          },
          {
            "name": "ptoim1r2e_kytkin",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "ptoim1r2e_kytkin"
          },
          {
            "name": "ptoim1r2h_kytkin",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "ptoim1r2h_kytkin"
          },
          {
            "name": "toteuma_tutk_kytkin",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "toteuma_tutk_kytkin"
          },
          {
            "name": "tutklaja_kytkin",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "tutklaja_kytkin"
          },
          {
            "name": "tyov_kytkin",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "tyov_kytkin"
          },
          {
            "name": "amas_tilvseur",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "amas_tilvseur"
          },
          {
            "name": "amas_tilvseur_kytkin",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "amas_tilvseur_kytkin"
          },
          {
            "name": "maassaolo_tilvseur",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "maassaolo_tilvseur"
          },
          {
            "name": "maassaolo_tilvseur_kytkin",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "maassaolo_tilvseur_kytkin"
          },
          {
            "name": "ptoim1r2_tilvseur",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "ptoim1r2_tilvseur"
          },
          {
            "name": "ptoim1r2_tilvseur_kytkin",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "ptoim1r2_tilvseur_kytkin"
          },
          {
            "name": "kaste_t2_tilvseur",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "kaste_t2_tilvseur"
          },
          {
            "name": "kaste_t2ni_tilvseur",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "kaste_t2ni_tilvseur"
          },
          {
            "name": "iscfibroad2013_tilvseur",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "iscfibroad2013_tilvseur"
          },
          {
            "name": "kala_t1ni_tilvseur",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "kala_t1ni_tilvseur"
          },
          {
            "name": "suor_koko_tutk",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "suor_koko_tutk"
          },
          {
            "name": "suor_tutk_osia",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "suor_tutk_osia"
          },
          {
            "name": "tyolliset_ja_opiskelijat",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "tyolliset_ja_opiskelijat"
          },
          {
            "name": "tyolliset",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "tyolliset"
          },
          {
            "name": "opiskelijat",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "opiskelijat"
          },
          {
            "name": "tyolliset_opiskelijat_ja_tyottomat",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "tyolliset_opiskelijat_ja_tyottomat"
          },
          {
            "name": "statuskerroin",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "statuskerroin"
          },
          {
            "name": "suor_koko_tutk_yhteensa",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "suor_koko_tutk_yhteensa"
          },
          {
            "name": "tyolliset_opiskelijat_ja_tyottomat_yhteensa",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "tyolliset_opiskelijat_ja_tyottomat_yhteensa"
          },
          {
            "name": "jarjestajakerroin",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "jarjestajakerroin"
          },
          {
            "name": "tyollisten_painotetut_pisteet",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "tyollisten_painotetut_pisteet"
          },
          {
            "name": "opiskelijoiden_painotetut_pisteet",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "opiskelijoiden_painotetut_pisteet"
          },
          {
            "name": "tyollistyneet_ei_tyollisena_ennen_koulutusta",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "tyollistyneet_ei_tyollisena_ennen_koulutusta"
          },
          {
            "name": "tyollistyneet_tyollisena_ennen_koulutusta",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "tyollistyneet_tyollisena_ennen_koulutusta"
          },
          {
            "name": "jatko_opiskelijat_ei_tyollisena_ennen_koulutusta",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jatko_opiskelijat_ei_tyollisena_ennen_koulutusta"
          },
          {
            "name": "jatko_opiskelijat_tyollisena_ennen_koulutusta",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jatko_opiskelijat_tyollisena_ennen_koulutusta"
          },
          {
            "name": "luontipvm",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "luontipvm"
          },
          {
            "name": "ytunnus_jarjnimi_opisk",
            "dataType": "string",
            "sourceColumn": "ytunnus_jarjnimi_opisk",
            "sortByColumn": "jarjnimi_opisk"
          },
          {
            "name": "omistajatyyppi_koodi",
            "dataType": "string",
            "sourceColumn": "omistajatyyppi_koodi"
          },
          {
            "name": "omistajatyyppi",
            "dataType": "string",
            "sourceColumn": "omistajatyyppi"
          },
          {
            "name": "tyoton",
            "dataType": "int64",
            "sourceColumn": "tyoton"
          },
          {
            "name": "muu_tai_tuntematon",
            "dataType": "int64",
            "sourceColumn": "muu_tai_tuntematon"
          },
          {
            "name": "Tilastovuosi",
            "dataType": "string",
            "sourceColumn": "tilastovuosi"
          }
        ],
        "partitions": [
          {
            "name": "v_sa_amos_siirtotiedosto_tk1",
            "dataView": "full",
            "source": {
              "query": [
                "SELECT ",
                " * FROM [ANTERO].[sa].[d_sa_amos_spl_TK_K1_13_sopv_yy_tabular]"
              ],
              "dataSource": "dwitvipusql22"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT ",
                  " * FROM [ANTERO].[sa].[d_sa_amos_spl_TK_K1_13_sopv_yy_tabular]</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "lkm_a",
            "expression": "SUM([lkm])"
          },
          {
            "name": "tutk_osia_suor_8_a",
            "expression": "sum([tutk_osia_suor_8])"
          },
          {
            "name": "tutk_osia_suor_7_a",
            "expression": "sum([tutk_osia_suor_7])"
          },
          {
            "name": "tutk_osia_suor_6_a",
            "expression": "sum([tutk_osia_suor_6])"
          },
          {
            "name": "tutk_osia_suor_5_a",
            "expression": "sum([tutk_osia_suor_5])"
          },
          {
            "name": "tutk_suor_8_a",
            "expression": "sum([tutk_suor_8])"
          },
          {
            "name": "tutk_suor_7_a",
            "expression": "sum([tutk_suor_7])"
          },
          {
            "name": "tutk_suor_6_a",
            "expression": "sum([tutk_suor_6])"
          },
          {
            "name": "tutk_suor_5_a",
            "expression": "sum([tutk_suor_5])"
          },
          {
            "name": "tutk_osia_suor_4_a",
            "expression": "sum([tutk_osia_suor_4])"
          },
          {
            "name": "tutk_osia_suor_3_a",
            "expression": "sum([tutk_osia_suor_3])"
          },
          {
            "name": "tutk_osia_suor_2_a",
            "expression": "sum([tutk_osia_suor_2])"
          },
          {
            "name": "tutk_osia_suor_1_a",
            "expression": "sum([tutk_osia_suor_1])"
          },
          {
            "name": "tutk_suor_4_a",
            "expression": "sum([tutk_suor_4])"
          },
          {
            "name": "tutk_suor_3_a",
            "expression": "sum([tutk_suor_3])"
          },
          {
            "name": "tutk_suor_2_a",
            "expression": "sum([tutk_suor_2])"
          },
          {
            "name": "tutk_suor_1_a",
            "expression": "sum([tutk_suor_1])"
          },
          {
            "name": "jarjestajakerroin_a",
            "expression": "max([jarjestajakerroin]) ",
            "formatString": "0.00"
          },
          {
            "name": "aluekerroin_a",
            "expression": "max([aluekerroin])"
          },
          {
            "name": "suor_koko_tutk_a",
            "expression": "sum([suor_koko_tutk])"
          },
          {
            "name": "suor_tutk_osia_a",
            "expression": "sum([suor_tutk_osia])"
          },
          {
            "name": "tyolliset_ja_opiskelijat_a",
            "expression": "sum([tyolliset_ja_opiskelijat])"
          },
          {
            "name": "tyolliset_a",
            "expression": "sum([tyolliset])"
          },
          {
            "name": "opiskelijat_a",
            "expression": "sum([opiskelijat])"
          },
          {
            "name": "tyolliset_opiskelijat_ja_tyottomat_a",
            "expression": "sum([tyolliset_opiskelijat_ja_tyottomat])"
          },
          {
            "name": "statuskerroin_a",
            "expression": "MAX([statuskerroin])"
          },
          {
            "name": "tyollisten_painotetut_pisteet_a",
            "expression": "sum([tyollisten_painotetut_pisteet])",
            "formatString": "#,0.00"
          },
          {
            "name": "opiskelijoiden_painotetut_pisteet_a",
            "expression": "sum([opiskelijoiden_painotetut_pisteet])",
            "formatString": "#,0.00"
          },
          {
            "name": "tyollistyneet_ei_tyollisena_ennen_koulutusta_a",
            "expression": "sum([tyollistyneet_ei_tyollisena_ennen_koulutusta])"
          },
          {
            "name": "tyollistyneet_tyollisena_ennen_koulutusta_a",
            "expression": "sum([tyollistyneet_tyollisena_ennen_koulutusta])"
          },
          {
            "name": "jatko_opiskelijat_ei_tyollisena_ennen_koulutusta_a",
            "expression": "sum([jatko_opiskelijat_ei_tyollisena_ennen_koulutusta])"
          },
          {
            "name": "jatko_opiskelijat_tyollisena_ennen_koulutusta_a",
            "expression": "sum([jatko_opiskelijat_tyollisena_ennen_koulutusta])"
          },
          {
            "name": "tyollisten_ja_opiskelijoiden_painotetut_pisteet_yhteensa_a",
            "expression": "[tyollisten_painotetut_pisteet_a]+[opiskelijoiden_painotetut_pisteet_a]",
            "formatString": "#,0.00"
          },
          {
            "name": "tyollisten_ja_opiskelijoiden_painotetut_pisteet_suhteellinen_osuus_a",
            "expression": [
              " DIVIDE([tyollisten_ja_opiskelijoiden_painotetut_pisteet_yhteensa_a], CALCULATE([tyollisten_ja_opiskelijoiden_painotetut_pisteet_yhteensa_a], ALL(Muuttujat)))",
              "/*SUMX(Muuttujat;[tyollisten_ja_opiskelijoiden_painotetut_pisteet_yhteensa_a])/SUMX(ALL(Muuttujat);Muuttujat[tyollisten_ja_opiskelijoiden_painotetut_pisteet_yhteensa_a])*/"
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %"
          },
          {
            "name": "s_tyollistyneet_tyollisena_ennen_koulutusta_a",
            "expression": "IF(SUM([tyollistyneet_tyollisena_ennen_koulutusta]) = 0, BLANK(),IF(SUM([tyollistyneet_tyollisena_ennen_koulutusta]) < 5, \"1-4\", SUM([tyollistyneet_tyollisena_ennen_koulutusta])))",
            "formatString": "#,0"
          },
          {
            "name": "s_jatko_opiskelijat_ei_tyollisena_ennen_koulutusta_a",
            "expression": "IF(SUM([jatko_opiskelijat_ei_tyollisena_ennen_koulutusta]) = 0, BLANK(),IF(SUM([jatko_opiskelijat_ei_tyollisena_ennen_koulutusta]) <5,\"1-4\", SUM([jatko_opiskelijat_ei_tyollisena_ennen_koulutusta])))",
            "formatString": "#,0"
          },
          {
            "name": "s_jatko_opiskelijat_tyollisena_ennen_koulutusta_a",
            "expression": "IF(SUM([jatko_opiskelijat_tyollisena_ennen_koulutusta]) = 0, BLANK(),IF(SUM([jatko_opiskelijat_tyollisena_ennen_koulutusta]) < 5,\"1-4\", SUM([jatko_opiskelijat_tyollisena_ennen_koulutusta])))",
            "formatString": "#,0"
          },
          {
            "name": "s_opiskelijat_a",
            "expression": "IF(SUM([opiskelijat]) = 0, BLANK(),IF(SUM([opiskelijat]) < 5, \"1-4\",SUM([opiskelijat])))",
            "formatString": "#,0"
          },
          {
            "name": "s_suor_koko_tutk_a",
            "expression": "IF(SUM([suor_koko_tutk]) = 0, BLANK(),SUM([suor_koko_tutk]))",
            "formatString": "#,0"
          },
          {
            "name": "s_tyolliset_a",
            "expression": "IF(SUM([tyolliset]) = 0, BLANK(),IF(SUM([tyolliset]) < 5, \"1-4\", SUM([tyolliset])))",
            "formatString": "#,0"
          },
          {
            "name": "s_tyolliset_ja_opiskelijat_a",
            "expression": "IF(SUM([tyolliset_ja_opiskelijat]) = 0, BLANK(),IF(SUM([tyolliset_ja_opiskelijat]) < 5, \"1-4\", SUM([tyolliset_ja_opiskelijat])))",
            "formatString": "#,0"
          },
          {
            "name": "s_tyollistyneet_ei_tyollisena_ennen_koulutusta_a",
            "expression": "IF(SUM([tyollistyneet_ei_tyollisena_ennen_koulutusta]) = 0, BLANK(),IF(SUM([tyollistyneet_ei_tyollisena_ennen_koulutusta]) < 5, \"1-4\", SUM([tyollistyneet_ei_tyollisena_ennen_koulutusta])))",
            "formatString": "#,0"
          },
          {
            "name": "s_tyollisten_painotetut_pisteet_a",
            "expression": "IF(SUM([tyollisten_painotetut_pisteet]) = 0, BLANK(),IF(SUM([tyollisten_painotetut_pisteet]) < 5, \"1-4\",SUM([tyollisten_painotetut_pisteet])))",
            "formatString": "#,0.00"
          },
          {
            "name": "s_opiskelijoiden_painotetut_pisteet_a",
            "expression": "IF(SUM([opiskelijoiden_painotetut_pisteet]) = 0, BLANK(),IF(SUM([opiskelijoiden_painotetut_pisteet]) < 5, \"1-4\", SUM([opiskelijoiden_painotetut_pisteet])))",
            "formatString": "#,0.00"
          },
          {
            "name": "tyoton1_a",
            "expression": "sum(Muuttujat[tyoton])"
          },
          {
            "name": "muu_tai_tuntematon_a",
            "expression": "sum(Muuttujat[muu_tai_tuntematon])"
          },
          {
            "name": "s_tyoton_a",
            "expression": "IF(SUM(Muuttujat[tyoton]) = 0, BLANK(),IF(SUM(Muuttujat[tyoton]) < 5, \"1-4\", SUM(Muuttujat[tyoton])))",
            "formatString": "#,0"
          },
          {
            "name": "s_muu_tai_tuntematon_a",
            "expression": "IF(SUM([muu_tai_tuntematon]) = 0, BLANK(),IF(SUM([muu_tai_tuntematon]) < 5, \"1-4\", SUM([muu_tai_tuntematon])))",
            "formatString": "#,0"
          },
          {
            "name": "s_tyollisten_ja_opiskelijoiden_painotetut_pisteet",
            "expression": [
              " IF(SUMX(Muuttujat, [tyollisten_painotetut_pisteet] + [opiskelijoiden_painotetut_pisteet]) = 0, BLANK(), ",
              " \t\t\t\t\t\tIF(SUMX(Muuttujat, [tyollisten_painotetut_pisteet] + [opiskelijoiden_painotetut_pisteet]) < 5, \"1-4\",  SUMX(Muuttujat, [tyollisten_painotetut_pisteet] + [opiskelijoiden_painotetut_pisteet])))"
            ],
            "formatString": "#,0.00"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": [
              "SELECT ",
              " * FROM [ANTERO].[sa].[d_sa_amos_spl_TK_K1_13_sopv_yy_tabular]"
            ]
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "v_sa_amos_siirtotiedosto_tk1"
          },
          {
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT ",
              " * FROM [ANTERO].[sa].[d_sa_amos_spl_TK_K1_13_sopv_yy_tabular]</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "v_tk_4_2_paa_asiallinen_toiminta_maak",
        "columns": [
          {
            "name": "tilvasmaak",
            "dataType": "string",
            "sourceColumn": "tilvasmaak",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "paatoiminen_tyollinen",
            "dataType": "int64",
            "sourceColumn": "paatoiminen_tyollinen",
            "sourceProviderType": "Integer"
          },
          {
            "name": "tyollinen_opiskelija",
            "dataType": "int64",
            "sourceColumn": "tyollinen_opiskelija",
            "sourceProviderType": "Integer"
          },
          {
            "name": "tyolliset",
            "dataType": "int64",
            "sourceColumn": "tyolliset",
            "sourceProviderType": "Integer"
          },
          {
            "name": "yhteensa",
            "dataType": "int64",
            "sourceColumn": "yhteensa",
            "sourceProviderType": "Integer"
          },
          {
            "name": "tyolliset_per_yhteensa",
            "dataType": "double",
            "sourceColumn": "tyolliset_per_yhteensa"
          },
          {
            "name": "indeksi_jakaja",
            "dataType": "double",
            "sourceColumn": "indeksi_jakaja"
          },
          {
            "name": "aluekerroin",
            "dataType": "double",
            "sourceColumn": "aluekerroin"
          },
          {
            "name": "tyoton_tk42",
            "dataType": "int64",
            "sourceColumn": "tyoton",
            "sourceProviderType": "Integer"
          },
          {
            "name": "maakunta",
            "dataType": "string",
            "sourceColumn": "maakunta"
          }
        ],
        "partitions": [
          {
            "name": "v_tk_3_4_paa_asiallinen_toiminta_maak_jhe",
            "dataView": "full",
            "source": {
              "query": [
                "select * from",
                " [dw].[v_amos_spl_tk_4_2abc_paa_asiallinen_toiminta_maak_indeksoitu]"
              ],
              "dataSource": "dwitvipusql22"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>select * from",
                  " [dw].[v_amos_spl_tk_4_2abc_paa_asiallinen_toiminta_maak_indeksoitu]</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "paatoiminen_tyollinen_a",
            "expression": "sum([paatoiminen_tyollinen])"
          },
          {
            "name": "tyollinen_opiskelija_a",
            "expression": "sum([tyollinen_opiskelija])"
          },
          {
            "name": "tyolliset_tk42_a",
            "expression": "sum([tyolliset])"
          },
          {
            "name": "yhteensa_tk42_a",
            "expression": "sum([yhteensa])"
          },
          {
            "name": "tyolliset_per_yhteensa_a",
            "expression": "sum([tyolliset_per_yhteensa])"
          },
          {
            "name": "indeksi_jakaja_a",
            "expression": "max([indeksi_jakaja])"
          },
          {
            "name": "aluekerroin_tk42_a",
            "expression": "max([aluekerroin])"
          },
          {
            "name": "tyoton_tk42_a",
            "expression": "sum([tyoton_tk42])"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": [
              "select * from",
              " [dw].[v_amos_spl_tk_4_2abc_paa_asiallinen_toiminta_maak_indeksoitu]"
            ]
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "v_tk_3_4_paa_asiallinen_toiminta_maak_jhe"
          },
          {
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>select * from",
              " [dw].[v_amos_spl_tk_4_2abc_paa_asiallinen_toiminta_maak_indeksoitu]</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      }
    ],
    "cultures": [
      {
        "name": "fi-FI",
        "translations": {
          "model": {
            "name": "Model",
            "tables": [
              {
                "name": "Muuttujat",
                "translatedCaption": "Var",
                "columns": [
                  {
                    "name": "tilv",
                    "translatedCaption": "Tutkinnon suorittamisvuosi",
                    "translatedDisplayFolder": "Aikamuuttujat"
                  },
                  {
                    "name": "aineisto",
                    "translatedCaption": "Ennakkoaineisto/lopullinen aineisto",
                    "translatedDisplayFolder": "Tilastovuosi"
                  },
                  {
                    "name": "prioriteetti",
                    "translatedCaption": "Onko tutkinto korkein, vertailussa sekä ennen koulutuksen aloittamista (pohjakoulutus) että koulutuksen aikana suoritetut muut tutkinnot",
                    "translatedDisplayFolder": "Suoritettua tutkintoa koskevat tiedot"
                  },
                  {
                    "name": "toteuma_tutk",
                    "translatedCaption": "Suorittanut koko tutkinnon vs. tutkinnon osia",
                    "translatedDisplayFolder": "Suoritettua tutkintoa koskevat tiedot"
                  },
                  {
                    "name": "tyov",
                    "translatedCaption": "Ammatillinen koulutus, työvoimapoliittinen aikuiskoulutus?",
                    "translatedDisplayFolder": "Suoritettua tutkintoa koskevat tiedot"
                  },
                  {
                    "name": "jarj_opisk",
                    "translatedCaption": "Koulutuksen järjestäjä (opiskelun aikainen)",
                    "translatedDisplayFolder": "Suoritettua tutkintoa koskevat tiedot"
                  },
                  {
                    "name": "jarjnimi_opisk",
                    "translatedCaption": "Koulutuksen järjestäjän nimi (opiskelun aikainen)",
                    "translatedDisplayFolder": "Suoritettua tutkintoa koskevat tiedot"
                  },
                  {
                    "name": "kaste_t2",
                    "translatedCaption": "Kansall. koul.aste. taso 2",
                    "translatedDisplayFolder": "Suoritettua tutkintoa koskevat tiedot"
                  },
                  {
                    "name": "kaste_t2ni",
                    "translatedCaption": "Kansallinen koulutusaste taso 2 nimi",
                    "translatedDisplayFolder": "Suoritettua tutkintoa koskevat tiedot"
                  },
                  {
                    "name": "iscfibroad2013",
                    "translatedCaption": "Kansallinen koulutusala, taso 1",
                    "translatedDisplayFolder": "Suoritettua tutkintoa koskevat tiedot"
                  },
                  {
                    "name": "kala_t1ni",
                    "translatedCaption": "Kansallinen koulutusala, taso 1 nimi",
                    "translatedDisplayFolder": "Suoritettua tutkintoa koskevat tiedot"
                  },
                  {
                    "name": "oppis",
                    "translatedCaption": "Oppisopimuskoulutus. Koskee vain ammatillista koulutusta",
                    "translatedDisplayFolder": "Suoritettua tutkintoa koskevat tiedot"
                  },
                  {
                    "name": "tutklaja",
                    "translatedCaption": "Ammatillisen koulutuksen koulutuslaji",
                    "translatedDisplayFolder": "Suoritettua tutkintoa koskevat tiedot"
                  },
                  {
                    "name": "alvv",
                    "translatedCaption": "Tutkinnon aloittamisvuosi / kirjoihintulovuosi",
                    "translatedDisplayFolder": "Suoritettua tutkintoa koskevat tiedot"
                  },
                  {
                    "name": "allk",
                    "translatedCaption": "Tutkinnon aloittamislukukausi",
                    "translatedDisplayFolder": "Suoritettua tutkintoa koskevat tiedot"
                  },
                  {
                    "name": "kaste_t2_e",
                    "translatedCaption": "Ennen koulutuksen aloittamisajankohtaa suoritettu tutkinto",
                    "translatedDisplayFolder": "Pohjakoulutus ja opiskelua edeltävän vuoden tiedot"
                  },
                  {
                    "name": "kaste_t2ni_e",
                    "translatedCaption": "Ennen koulutuksen aloittamisajankohtaa suoritettu tutkinto",
                    "translatedDisplayFolder": "Pohjakoulutus ja opiskelua edeltävän vuoden tiedot"
                  },
                  {
                    "name": "ptoim1r2e",
                    "translatedCaption": "Aloittamisvuotta edeltävän vuoden lopun pääasiallinen toiminta",
                    "translatedDisplayFolder": "Pohjakoulutus ja opiskelua edeltävän vuoden tiedot"
                  },
                  {
                    "name": "kaste_t2_evj",
                    "translatedCaption": "Kansallinen koulutusaste taso 2 koodi",
                    "translatedDisplayFolder": "Pohjakoulutus ja opiskelua edeltävän vuoden tiedot"
                  },
                  {
                    "name": "kaste_t2ni_evj",
                    "translatedCaption": "Kansallinen koulutusaste taso 2 nimi",
                    "translatedDisplayFolder": "Pohjakoulutus ja opiskelua edeltävän vuoden tiedot"
                  },
                  {
                    "name": "amase",
                    "translatedCaption": "Ammattiasema tilastovuoden lopussa",
                    "translatedDisplayFolder": "Pohjakoulutus ja opiskelua edeltävän vuoden tiedot"
                  },
                  {
                    "name": "ptoim1r2h",
                    "translatedCaption": "Aloittamisvuoden heinäkuun lopun pääasiallinen toiminta.",
                    "translatedDisplayFolder": "Aloittamisvuoden heinäkuun lopun tiedot"
                  },
                  {
                    "name": "kaste_t2_avh",
                    "translatedCaption": "Kansallinen koulutusaste taso 2 koodi",
                    "translatedDisplayFolder": "Aloittamisvuoden heinäkuun lopun tiedot"
                  },
                  {
                    "name": "kaste_t2ni_avh",
                    "translatedCaption": "Kansallinen koulutusaste taso 2 nimi",
                    "translatedDisplayFolder": "Aloittamisvuoden heinäkuun lopun tiedot"
                  },
                  {
                    "name": "amash",
                    "translatedCaption": "Aloittamisvuoden heinäkuun ammattiasema",
                    "translatedDisplayFolder": "Aloittamisvuoden heinäkuun lopun tiedot"
                  },
                  {
                    "name": "jarjmaak",
                    "translatedCaption": "Koulutuksen järjestäjän sijaintimaakunnan koodi (opiskelun aikainen)",
                    "translatedDisplayFolder": "Suoritettua tutkintoa koskevat tiedot"
                  },
                  {
                    "name": "jarjmaaknimi",
                    "translatedCaption": "Koulutuksen järjestäjän sijaintimaakunnan nimi (opiskelun aikainen)",
                    "translatedDisplayFolder": "Suoritettua tutkintoa koskevat tiedot"
                  },
                  {
                    "name": "ytunnus_jarjnimi_opisk",
                    "translatedCaption": "Koulutuksen järjestäjän ytunnus ja nimi (opiskelun aikainen)",
                    "translatedDisplayFolder": "Suoritettua tutkintoa koskevat tiedot"
                  },
                  {
                    "name": "omistajatyyppi_koodi",
                    "translatedCaption": "Omistajatyyppi (koodi)",
                    "translatedDisplayFolder": "Suoritettua tutkintoa koskevat tiedot"
                  },
                  {
                    "name": "omistajatyyppi",
                    "translatedCaption": "Omistajatyyppi",
                    "translatedDisplayFolder": "Suoritettua tutkintoa koskevat tiedot"
                  },
                  {
                    "name": "Tilastovuosi",
                    "translatedCaption": "Tilastovuosi",
                    "translatedDisplayFolder": "Aikamuuttujat"
                  }
                ],
                "measures": [
                  {
                    "name": "lkm_a",
                    "translatedCaption": "Havaintojen lukumäärä",
                    "translatedDisplayFolder": "Lukumäärä"
                  },
                  {
                    "name": "tutk_osia_suor_8_a",
                    "translatedCaption": "Muu (kuin jatko-opiskelija, työllinen tai työtön), tutkinnon osia suorittanut, ennen koulutusta työllinen",
                    "translatedDisplayFolder": "Johdetut lukumäärämuuttujat"
                  },
                  {
                    "name": "tutk_osia_suor_7_a",
                    "translatedCaption": "Työtön, tutkinnon osia suorittanut, ennen koulutusta työllinen",
                    "translatedDisplayFolder": "Vaikuttavuuslaskenta"
                  },
                  {
                    "name": "tutk_osia_suor_6_a",
                    "translatedCaption": "Jatko-opiskelija, tutkinnon osia suorittanut, ennen koulutusta työllinen",
                    "translatedDisplayFolder": "Johdetut lukumäärämuuttujat"
                  },
                  {
                    "name": "tutk_osia_suor_5_a",
                    "translatedCaption": "Työllinen, tutkinnon osia suorittanut, ennen koulutusta työllinen",
                    "translatedDisplayFolder": "Johdetut lukumäärämuuttujat"
                  },
                  {
                    "name": "tutk_suor_8_a",
                    "translatedCaption": "Muu (kuin jatko-opiskelija, työllinen tai työtön), koko tutkinnon suorittanut, ennen koulutusta työllinen",
                    "translatedDisplayFolder": "Johdetut lukumäärämuuttujat"
                  },
                  {
                    "name": "tutk_suor_7_a",
                    "translatedCaption": "Työtön, koko tutkinnon suorittanut, ennen koulutusta työllinen",
                    "translatedDisplayFolder": "Vaikuttavuuslaskenta"
                  },
                  {
                    "name": "tutk_suor_6_a",
                    "translatedCaption": "Jatko-opiskelija, koko tutkinnon suorittanut, ennen koulutusta työllinen",
                    "translatedDisplayFolder": "Johdetut lukumäärämuuttujat"
                  },
                  {
                    "name": "tutk_suor_5_a",
                    "translatedCaption": "Työllinen, koko tutkinnon suorittanut, ennen koulutusta työllinen",
                    "translatedDisplayFolder": "Johdetut lukumäärämuuttujat"
                  },
                  {
                    "name": "tutk_osia_suor_4_a",
                    "translatedCaption": "Muu (kuin jatko-opiskelija, työllinen tai työtön), tutkinnon osia suorittanut, ennen koulutusta ei-työllinen",
                    "translatedDisplayFolder": "Johdetut lukumäärämuuttujat"
                  },
                  {
                    "name": "tutk_osia_suor_3_a",
                    "translatedCaption": "Työtön, tutkinnon osia suorittanut, ennen koulutusta ei-työllinen",
                    "translatedDisplayFolder": "Vaikuttavuuslaskenta"
                  },
                  {
                    "name": "tutk_osia_suor_2_a",
                    "translatedCaption": "Jatko-opiskelija, tutkinnon osia suorittanut, ennen koulutusta ei-työllinen",
                    "translatedDisplayFolder": "Johdetut lukumäärämuuttujat"
                  },
                  {
                    "name": "tutk_osia_suor_1_a",
                    "translatedCaption": "Työllinen, tutkinnon osia suorittanut, ennen koulutusta ei-työllinen. \n",
                    "translatedDisplayFolder": "Johdetut lukumäärämuuttujat"
                  },
                  {
                    "name": "tutk_suor_4_a",
                    "translatedCaption": "Muu (kuin jatko-opiskelija, työllinen tai työtön), koko tutkinnon suorittanut, ennen koulutusta \nei-työllinen",
                    "translatedDisplayFolder": "Johdetut lukumäärämuuttujat"
                  },
                  {
                    "name": "tutk_suor_3_a",
                    "translatedCaption": "Työtön, koko tutkinnon suorittanut, ennen koulutusta ei-työllinen",
                    "translatedDisplayFolder": "Vaikuttavuuslaskenta"
                  },
                  {
                    "name": "tutk_suor_2_a",
                    "translatedCaption": "Jatko-opiskelija, koko tutkinnon suorittanut, ennen koulutusta ei-työllinen",
                    "translatedDisplayFolder": "Johdetut lukumäärämuuttujat"
                  },
                  {
                    "name": "tutk_suor_1_a",
                    "translatedCaption": "Työllinen, koko tutkinnon suorittanut, ennen koulutusta ei-työllinen",
                    "translatedDisplayFolder": "Johdetut lukumäärämuuttujat"
                  },
                  {
                    "name": "jarjestajakerroin_a",
                    "translatedCaption": "Järjestäjäkerroin",
                    "translatedDisplayFolder": "Vaikuttavuuslaskenta"
                  },
                  {
                    "name": "aluekerroin_a",
                    "translatedCaption": "Aluekerroin",
                    "translatedDisplayFolder": "Vaikuttavuuslaskenta"
                  },
                  {
                    "name": "suor_koko_tutk_a",
                    "translatedCaption": "Tutkintojen määrä",
                    "translatedDisplayFolder": "Vaikuttavuuslaskenta"
                  },
                  {
                    "name": "suor_tutk_osia_a",
                    "translatedCaption": "Suorittanut tutkinnon osia",
                    "translatedDisplayFolder": "Lukumäärä"
                  },
                  {
                    "name": "tyolliset_ja_opiskelijat_a",
                    "translatedCaption": "Työllistyneet ja jatko-opiskelijat yhteensä",
                    "translatedDisplayFolder": "Vaikuttavuuslaskenta"
                  },
                  {
                    "name": "tyolliset_a",
                    "translatedCaption": "Työllistyneet",
                    "translatedDisplayFolder": "Vaikuttavuuslaskenta"
                  },
                  {
                    "name": "opiskelijat_a",
                    "translatedCaption": "Jatko-opiskelijat",
                    "translatedDisplayFolder": "Vaikuttavuuslaskenta"
                  },
                  {
                    "name": "tyolliset_opiskelijat_ja_tyottomat_a",
                    "translatedCaption": "Työlliset opiskelijat ja tyottomat",
                    "translatedDisplayFolder": "Vaikuttavuuslaskenta"
                  },
                  {
                    "name": "statuskerroin_a",
                    "translatedCaption": "Statuskerroin",
                    "translatedDisplayFolder": "Vaikuttavuuslaskenta"
                  },
                  {
                    "name": "tyollisten_painotetut_pisteet_a",
                    "translatedCaption": "Työllistyneet painotetut pisteet",
                    "translatedDisplayFolder": "Vaikuttavuuslaskenta"
                  },
                  {
                    "name": "opiskelijoiden_painotetut_pisteet_a",
                    "translatedCaption": "Jatko-opiskelijat painotetut pisteet",
                    "translatedDisplayFolder": "Vaikuttavuuslaskenta"
                  },
                  {
                    "name": "tyollistyneet_ei_tyollisena_ennen_koulutusta_a",
                    "translatedCaption": "Työllistyneet, ei työllisenä ennen koulutusta",
                    "translatedDisplayFolder": "Vaikuttavuuslaskenta"
                  },
                  {
                    "name": "tyollistyneet_tyollisena_ennen_koulutusta_a",
                    "translatedCaption": "Työllistyneet, työllisenä ennen koulutusta",
                    "translatedDisplayFolder": "Vaikuttavuuslaskenta"
                  },
                  {
                    "name": "jatko_opiskelijat_ei_tyollisena_ennen_koulutusta_a",
                    "translatedCaption": "Jatko-opiskelijat, ei työllisenä ennen koulutusta",
                    "translatedDisplayFolder": "Vaikuttavuuslaskenta"
                  },
                  {
                    "name": "jatko_opiskelijat_tyollisena_ennen_koulutusta_a",
                    "translatedCaption": "Jatko-opiskelijat, työllisenä ennen koulutusta",
                    "translatedDisplayFolder": "Vaikuttavuuslaskenta"
                  },
                  {
                    "name": "tyollisten_ja_opiskelijoiden_painotetut_pisteet_yhteensa_a",
                    "translatedCaption": "Työllistyneet ja jatko-opiskelijat painotetut pisteet",
                    "translatedDisplayFolder": "Vaikuttavuuslaskenta"
                  },
                  {
                    "name": "tyollisten_ja_opiskelijoiden_painotetut_pisteet_suhteellinen_osuus_a",
                    "translatedCaption": "Työllistyneet ja jatko-opiskelijat painotetut pisteet, %-osuus järjestäjittäin",
                    "translatedDisplayFolder": "Vaikuttavuuslaskenta"
                  },
                  {
                    "name": "s_tyollistyneet_tyollisena_ennen_koulutusta_a",
                    "translatedCaption": "Työllistyneet, työllisenä ennen koulutusta",
                    "translatedDisplayFolder": "Vaikuttavuuslaskenta"
                  },
                  {
                    "name": "s_jatko_opiskelijat_ei_tyollisena_ennen_koulutusta_a",
                    "translatedCaption": "Jatko-opiskelijat, ei työllisenä ennen koulutusta",
                    "translatedDisplayFolder": "Vaikuttavuuslaskenta"
                  },
                  {
                    "name": "s_jatko_opiskelijat_tyollisena_ennen_koulutusta_a",
                    "translatedCaption": "Jatko-opiskelijat, työllisenä ennen koulutusta",
                    "translatedDisplayFolder": "Vaikuttavuuslaskenta"
                  },
                  {
                    "name": "s_opiskelijat_a",
                    "translatedCaption": "Jatko-opiskelijat",
                    "translatedDisplayFolder": "Vaikuttavuuslaskenta"
                  },
                  {
                    "name": "s_suor_koko_tutk_a",
                    "translatedCaption": "Tutkintojen määrä",
                    "translatedDisplayFolder": "Vaikuttavuuslaskenta"
                  },
                  {
                    "name": "s_tyolliset_a",
                    "translatedCaption": "Työllistyneet",
                    "translatedDisplayFolder": "Vaikuttavuuslaskenta"
                  },
                  {
                    "name": "s_tyolliset_ja_opiskelijat_a",
                    "translatedCaption": "Työllistyneet ja jatko-opiskelijat yhteensä",
                    "translatedDisplayFolder": "Vaikuttavuuslaskenta"
                  },
                  {
                    "name": "s_tyollistyneet_ei_tyollisena_ennen_koulutusta_a",
                    "translatedCaption": "Työllistyneet, ei työllisenä ennen koulutusta",
                    "translatedDisplayFolder": "Vaikuttavuuslaskenta"
                  },
                  {
                    "name": "s_tyollisten_painotetut_pisteet_a",
                    "translatedCaption": "Työllistyneet painotetut pisteet",
                    "translatedDisplayFolder": "Vaikuttavuuslaskenta"
                  },
                  {
                    "name": "s_opiskelijoiden_painotetut_pisteet_a",
                    "translatedCaption": "Jatko-opiskelijat painotetut pisteet",
                    "translatedDisplayFolder": "Vaikuttavuuslaskenta"
                  },
                  {
                    "name": "tyoton1_a",
                    "translatedCaption": "Työttömät",
                    "translatedDisplayFolder": "Vaikuttavuuslaskenta"
                  },
                  {
                    "name": "muu_tai_tuntematon_a",
                    "translatedCaption": "Muussa toiminnassa",
                    "translatedDisplayFolder": "Vaikuttavuuslaskenta"
                  },
                  {
                    "name": "s_tyoton_a",
                    "translatedCaption": "Työttömät",
                    "translatedDisplayFolder": "Vaikuttavuuslaskenta"
                  },
                  {
                    "name": "s_muu_tai_tuntematon_a",
                    "translatedCaption": "Muussa toiminnassa",
                    "translatedDisplayFolder": "Vaikuttavuuslaskenta"
                  },
                  {
                    "name": "s_tyollisten_ja_opiskelijoiden_painotetut_pisteet",
                    "translatedCaption": "Työllisten ja opiskelijoiden painotetut pisteet",
                    "translatedDisplayFolder": "Vaikuttavuuslaskenta"
                  }
                ]
              },
              {
                "name": "v_tk_4_2_paa_asiallinen_toiminta_maak",
                "columns": [
                  {
                    "name": "tilvasmaak",
                    "translatedCaption": "Maakuntakoodi"
                  },
                  {
                    "name": "paatoiminen_tyollinen",
                    "translatedCaption": "Päätoimiset työlliset"
                  },
                  {
                    "name": "tyollinen_opiskelija",
                    "translatedCaption": "Työlliset opiskelijat"
                  },
                  {
                    "name": "tyolliset",
                    "translatedCaption": "Työlliset"
                  },
                  {
                    "name": "yhteensa",
                    "translatedCaption": "Työlliset ja työttömät yhteensä",
                    "translatedDisplayFolder": "Lukumäärämuuttujat"
                  },
                  {
                    "name": "tyolliset_per_yhteensa",
                    "translatedCaption": "Työlliset jaettuna työttömien ja työllisten yhteismäärällä"
                  },
                  {
                    "name": "indeksi_jakaja",
                    "translatedCaption": "Jakaja"
                  },
                  {
                    "name": "aluekerroin",
                    "translatedCaption": "Aluekerroin"
                  },
                  {
                    "name": "tyoton_tk42",
                    "translatedCaption": "Työtön (tk42)"
                  },
                  {
                    "name": "maakunta",
                    "translatedCaption": "Maakunta"
                  }
                ],
                "measures": [
                  {
                    "name": "paatoiminen_tyollinen_a",
                    "translatedCaption": "Päätoimiset työlliset"
                  },
                  {
                    "name": "tyollinen_opiskelija_a",
                    "translatedCaption": "Työlliset ja opiskelijat",
                    "translatedDisplayFolder": "Lukumäärämuuttujat"
                  },
                  {
                    "name": "tyolliset_tk42_a",
                    "translatedCaption": "Työlliset",
                    "translatedDisplayFolder": "Lukumäärämuuttujat"
                  },
                  {
                    "name": "yhteensa_tk42_a",
                    "translatedCaption": "Työlliset ja työttömät yhteensä",
                    "translatedDisplayFolder": "Lukumäärämuuttujat"
                  },
                  {
                    "name": "tyolliset_per_yhteensa_a",
                    "translatedCaption": "Työlliset jaettuna työllisten ja työttömien yhteismäärällä",
                    "translatedDisplayFolder": "Lukumäärämuuttujat"
                  },
                  {
                    "name": "aluekerroin_tk42_a",
                    "translatedCaption": "Aluekerroin"
                  },
                  {
                    "name": "tyoton_tk42_a",
                    "translatedCaption": "Työttömät",
                    "translatedDisplayFolder": "Lukumäärämuuttujat"
                  }
                ]
              }
            ]
          }
        }
      }
    ],
    "perspectives": [
      {
        "name": "Muuttujat",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "aineisto"
              },
              {
                "name": "allk"
              },
              {
                "name": "alvv"
              },
              {
                "name": "amase"
              },
              {
                "name": "amash"
              },
              {
                "name": "iscfibroad2013"
              },
              {
                "name": "jarj_opisk"
              },
              {
                "name": "jarjnimi_opisk"
              },
              {
                "name": "kala_t1ni"
              },
              {
                "name": "kaste_t2"
              },
              {
                "name": "kaste_t2_avh"
              },
              {
                "name": "kaste_t2_e"
              },
              {
                "name": "kaste_t2_evj"
              },
              {
                "name": "kaste_t2ni"
              },
              {
                "name": "kaste_t2ni_avh"
              },
              {
                "name": "kaste_t2ni_e"
              },
              {
                "name": "kaste_t2ni_evj"
              },
              {
                "name": "lkm"
              },
              {
                "name": "oppis"
              },
              {
                "name": "prioriteetti"
              },
              {
                "name": "ptoim1r2e"
              },
              {
                "name": "ptoim1r2h"
              },
              {
                "name": "tilv"
              },
              {
                "name": "toteuma_tutk"
              },
              {
                "name": "tutk_osia_suor_1"
              },
              {
                "name": "tutk_osia_suor_2"
              },
              {
                "name": "tutk_osia_suor_3"
              },
              {
                "name": "tutk_osia_suor_4"
              },
              {
                "name": "tutk_osia_suor_5"
              },
              {
                "name": "tutk_osia_suor_6"
              },
              {
                "name": "tutk_osia_suor_7"
              },
              {
                "name": "tutk_osia_suor_8"
              },
              {
                "name": "tutk_suor_1"
              },
              {
                "name": "tutk_suor_2"
              },
              {
                "name": "tutk_suor_3"
              },
              {
                "name": "tutk_suor_4"
              },
              {
                "name": "tutk_suor_5"
              },
              {
                "name": "tutk_suor_6"
              },
              {
                "name": "tutk_suor_7"
              },
              {
                "name": "tutk_suor_8"
              },
              {
                "name": "tutklaja"
              },
              {
                "name": "tyov"
              },
              {
                "name": "jarjmaak"
              },
              {
                "name": "jarjmaaknimi"
              },
              {
                "name": "aluekerroin"
              },
              {
                "name": "allk_kytkin"
              },
              {
                "name": "amase_kytkin"
              },
              {
                "name": "amash_kytkin"
              },
              {
                "name": "oppis_kytkin"
              },
              {
                "name": "prioriteetti_kytkin"
              },
              {
                "name": "ptoim1r2e_kytkin"
              },
              {
                "name": "ptoim1r2h_kytkin"
              },
              {
                "name": "toteuma_tutk_kytkin"
              },
              {
                "name": "tutklaja_kytkin"
              },
              {
                "name": "tyov_kytkin"
              },
              {
                "name": "amas_tilvseur"
              },
              {
                "name": "amas_tilvseur_kytkin"
              },
              {
                "name": "iscfibroad2013_tilvseur"
              },
              {
                "name": "kala_t1ni_tilvseur"
              },
              {
                "name": "kaste_t2_tilvseur"
              },
              {
                "name": "kaste_t2ni_tilvseur"
              },
              {
                "name": "maassaolo_tilvseur"
              },
              {
                "name": "maassaolo_tilvseur_kytkin"
              },
              {
                "name": "ptoim1r2_tilvseur"
              },
              {
                "name": "ptoim1r2_tilvseur_kytkin"
              },
              {
                "name": "suor_koko_tutk"
              },
              {
                "name": "suor_tutk_osia"
              },
              {
                "name": "opiskelijat"
              },
              {
                "name": "statuskerroin"
              },
              {
                "name": "tyolliset"
              },
              {
                "name": "tyolliset_ja_opiskelijat"
              },
              {
                "name": "tyolliset_opiskelijat_ja_tyottomat"
              },
              {
                "name": "jarjestajakerroin"
              },
              {
                "name": "opiskelijoiden_painotetut_pisteet"
              },
              {
                "name": "suor_koko_tutk_yhteensa"
              },
              {
                "name": "tyolliset_opiskelijat_ja_tyottomat_yhteensa"
              },
              {
                "name": "tyollisten_painotetut_pisteet"
              },
              {
                "name": "jatko_opiskelijat_ei_tyollisena_ennen_koulutusta"
              },
              {
                "name": "jatko_opiskelijat_tyollisena_ennen_koulutusta"
              },
              {
                "name": "tyollistyneet_ei_tyollisena_ennen_koulutusta"
              },
              {
                "name": "tyollistyneet_tyollisena_ennen_koulutusta"
              },
              {
                "name": "luontipvm"
              },
              {
                "name": "ytunnus_jarjnimi_opisk"
              },
              {
                "name": "omistajatyyppi"
              },
              {
                "name": "omistajatyyppi_koodi"
              },
              {
                "name": "Tilastovuosi"
              }
            ],
            "measures": [
              {
                "name": "lkm_a"
              },
              {
                "name": "tutk_osia_suor_5_a"
              },
              {
                "name": "tutk_osia_suor_6_a"
              },
              {
                "name": "tutk_osia_suor_7_a"
              },
              {
                "name": "tutk_osia_suor_8_a"
              },
              {
                "name": "tutk_suor_6_a"
              },
              {
                "name": "tutk_suor_7_a"
              },
              {
                "name": "tutk_suor_8_a"
              },
              {
                "name": "tutk_osia_suor_1_a"
              },
              {
                "name": "tutk_osia_suor_2_a"
              },
              {
                "name": "tutk_osia_suor_3_a"
              },
              {
                "name": "tutk_osia_suor_4_a"
              },
              {
                "name": "tutk_suor_1_a"
              },
              {
                "name": "tutk_suor_2_a"
              },
              {
                "name": "tutk_suor_3_a"
              },
              {
                "name": "tutk_suor_4_a"
              },
              {
                "name": "tutk_suor_5_a"
              },
              {
                "name": "jarjestajakerroin_a"
              },
              {
                "name": "aluekerroin_a"
              },
              {
                "name": "suor_koko_tutk_a"
              },
              {
                "name": "suor_tutk_osia_a"
              },
              {
                "name": "opiskelijat_a"
              },
              {
                "name": "statuskerroin_a"
              },
              {
                "name": "tyolliset_a"
              },
              {
                "name": "tyolliset_ja_opiskelijat_a"
              },
              {
                "name": "tyolliset_opiskelijat_ja_tyottomat_a"
              },
              {
                "name": "tyollisten_painotetut_pisteet_a"
              },
              {
                "name": "opiskelijoiden_painotetut_pisteet_a"
              },
              {
                "name": "jatko_opiskelijat_ei_tyollisena_ennen_koulutusta_a"
              },
              {
                "name": "jatko_opiskelijat_tyollisena_ennen_koulutusta_a"
              },
              {
                "name": "tyollistyneet_ei_tyollisena_ennen_koulutusta_a"
              },
              {
                "name": "tyollistyneet_tyollisena_ennen_koulutusta_a"
              },
              {
                "name": "tyollisten_ja_opiskelijoiden_painotetut_pisteet_yhteensa_a"
              },
              {
                "name": "tyollisten_ja_opiskelijoiden_painotetut_pisteet_suhteellinen_osuus_a"
              },
              {
                "name": "s_tyollisten_ja_opiskelijoiden_painotetut_pisteet"
              }
            ]
          }
        ]
      },
      {
        "name": "v_tk_4_2_paa_asiallinen_toiminta_maak",
        "tables": [
          {
            "name": "v_tk_4_2_paa_asiallinen_toiminta_maak",
            "columns": [
              {
                "name": "maakunta"
              }
            ],
            "measures": [
              {
                "name": "tyolliset_tk42_a"
              },
              {
                "name": "yhteensa_tk42_a"
              },
              {
                "name": "tyoton_tk42_a"
              }
            ]
          },
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "tilv"
              }
            ]
          }
        ]
      },
      {
        "name": "Vain_jarj_ja_vuosi",
        "tables": [
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "Sarakeleveys"
              },
              {
                "name": "leveys"
              }
            ]
          },
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "jarj_opisk"
              },
              {
                "name": "jarjnimi_opisk"
              },
              {
                "name": "ytunnus_jarjnimi_opisk"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "tilv"
              }
            ],
            "measures": [
              {
                "name": "suor_koko_tutk_a"
              },
              {
                "name": "opiskelijat_a"
              },
              {
                "name": "opiskelijoiden_painotetut_pisteet_a"
              },
              {
                "name": "tyolliset_a"
              },
              {
                "name": "tyollisten_ja_opiskelijoiden_painotetut_pisteet_yhteensa_a"
              },
              {
                "name": "tyollisten_ja_opiskelijoiden_painotetut_pisteet_suhteellinen_osuus_a"
              },
              {
                "name": "tyolliset_ja_opiskelijat_a"
              },
              {
                "name": "tyollisten_painotetut_pisteet_a"
              },
              {
                "name": "jatko_opiskelijat_ei_tyollisena_ennen_koulutusta_a"
              },
              {
                "name": "jatko_opiskelijat_tyollisena_ennen_koulutusta_a"
              },
              {
                "name": "tyollistyneet_ei_tyollisena_ennen_koulutusta_a"
              },
              {
                "name": "tyollistyneet_tyollisena_ennen_koulutusta_a"
              }
            ]
          }
        ]
      },
      {
        "name": "Painotettu",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "jarj_opisk"
              },
              {
                "name": "jarjnimi_opisk"
              },
              {
                "name": "ytunnus_jarjnimi_opisk"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "tilv"
              }
            ],
            "measures": [
              {
                "name": "jarjestajakerroin_a"
              },
              {
                "name": "aluekerroin_a"
              },
              {
                "name": "s_tyollistyneet_tyollisena_ennen_koulutusta_a"
              },
              {
                "name": "s_jatko_opiskelijat_ei_tyollisena_ennen_koulutusta_a"
              },
              {
                "name": "s_jatko_opiskelijat_tyollisena_ennen_koulutusta_a"
              },
              {
                "name": "s_suor_koko_tutk_a"
              },
              {
                "name": "s_tyollistyneet_ei_tyollisena_ennen_koulutusta_a"
              },
              {
                "name": "s_tyollisten_painotetut_pisteet_a"
              },
              {
                "name": "s_opiskelijoiden_painotetut_pisteet_a"
              },
              {
                "name": "s_muu_tai_tuntematon_a"
              },
              {
                "name": "s_tyoton_a"
              },
              {
                "name": "s_tyollisten_ja_opiskelijoiden_painotetut_pisteet"
              }
            ]
          }
        ]
      }
    ],
    "roles": [
      {
        "name": "Role",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "DWI\\P_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1733"
          },
          {
            "memberName": "DWI\\T_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1732"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "400"
      }
    ]
  },
  "id": "SemanticModel"
}
