{
  "name": "SemanticModel",
  "compatibilityLevel": 1200,
  "model": {
    "culture": "fi-FI",
    "dataSources": [
      {
        "name": "SqlServer dwitvipusql16 ANTERO",
        "connectionString": "Provider=SQLNCLI11;Data Source=dwitvipusql16;Initial Catalog=ANTERO;Integrated Security=SSPI;Persist Security Info=false",
        "impersonationMode": "impersonateServiceAccount",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "Sarakeleveys",
        "isHidden": true,
        "columns": [
          {
            "name": "Sarakeleveys",
            "dataType": "string",
            "sourceColumn": "Sarakeleveys",
            "sourceProviderType": "Char"
          },
          {
            "name": "leveys",
            "dataType": "string",
            "sourceColumn": "leveys",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Sarakeleveys",
            "dataView": "full",
            "source": {
              "query": " SELECT [dw].[Sarakeleveys].* FROM [dw].[Sarakeleveys] ",
              "dataSource": "SqlServer dwitvipusql16 ANTERO"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dw].[Sarakeleveys].* FROM [dw].[Sarakeleveys] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Sarakeleveys"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dw"
          }
        ]
      },
      {
        "name": "Muuttujat",
        "columns": [
          {
            "name": "Sektori",
            "dataType": "string",
            "sourceColumn": "Sektori",
            "sourceProviderType": "Char",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Korkeakoulu",
            "dataType": "string",
            "sourceColumn": "Korkeakoulu",
            "sourceProviderType": "WChar",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Tutkinto",
            "dataType": "string",
            "sourceColumn": "Tutkinto",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Luokittelu",
            "dataType": "string",
            "sourceColumn": "Luokittelu",
            "sourceProviderType": "Char",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Henkilo_koodi",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Henkilo_koodi",
            "sourceProviderType": "Char",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "OKM ohjauksen ala",
            "dataType": "string",
            "sourceColumn": "OKM ohjauksen ala",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusaste, taso 1",
            "dataType": "string",
            "sourceColumn": "Koulutusaste, taso 1",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusaste, taso 2",
            "dataType": "string",
            "sourceColumn": "Koulutusaste, taso 2",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusala, taso 1",
            "dataType": "string",
            "sourceColumn": "Koulutusala, taso 1",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusala, taso 2",
            "dataType": "string",
            "sourceColumn": "Koulutusala, taso 2",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusala, taso 3",
            "dataType": "string",
            "sourceColumn": "Koulutusala, taso 3",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Ikä",
            "dataType": "string",
            "sourceColumn": "Ikä",
            "sortByColumn": "Ikä jarj",
            "sourceProviderType": "SmallInt",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Ikäryhmä",
            "dataType": "string",
            "sourceColumn": "Ikäryhmä",
            "sortByColumn": "Ikäryhmä jarj",
            "sourceProviderType": "WChar",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Sukupuoli",
            "dataType": "string",
            "sourceColumn": "Sukupuoli",
            "sourceProviderType": "WChar",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Kansalaisuus",
            "dataType": "string",
            "sourceColumn": "Kansalaisuus",
            "sourceProviderType": "WChar",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Kansalaisuus (maanosa)",
            "dataType": "string",
            "sourceColumn": "Kansalaisuus (maanosa)",
            "sourceProviderType": "WChar",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Kansalaisuus (maanosa, suuralue)",
            "dataType": "string",
            "sourceColumn": "Kansalaisuus (maanosa, suuralue)",
            "sourceProviderType": "WChar",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "OKM ohjauksen ala jarj",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "OKM ohjauksen ala jarj",
            "sourceProviderType": "Char"
          },
          {
            "name": "Koulutusaste, taso 1 jarj",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Koulutusaste, taso 1 jarj",
            "sourceProviderType": "Char"
          },
          {
            "name": "Koulutusaste, taso 2 jarj",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Koulutusaste, taso 2 jarj",
            "sourceProviderType": "Char"
          },
          {
            "name": "Koulutusala, taso 1 jarj",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Koulutusala, taso 1 jarj",
            "sourceProviderType": "Char"
          },
          {
            "name": "Koulutusala, taso 2 jarj",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Koulutusala, taso 2 jarj",
            "sourceProviderType": "Char"
          },
          {
            "name": "Koulutusala, taso 3 jarj",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Koulutusala, taso 3 jarj",
            "sourceProviderType": "Char"
          },
          {
            "name": "Ikä jarj",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Ikä jarj",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Ikäryhmä jarj",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Ikäryhmä jarj",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Tilastovuosi",
            "dataType": "int64",
            "sourceColumn": "Tilastovuosi",
            "sourceProviderType": "Integer",
            "displayFolder": "Aikamuuttujat"
          }
        ],
        "partitions": [
          {
            "name": "Muuttujat",
            "dataView": "full",
            "source": {
              "query": " SELECT [dw].[v_virta_otp_yhteiskaksoistutkinnot].* FROM [dw].[v_virta_otp_yhteiskaksoistutkinnot] ",
              "dataSource": "SqlServer dwitvipusql16 ANTERO"
            }
          }
        ],
        "measures": [
          {
            "name": "Yhteistutkintoja",
            "expression": [
              "CALCULATE(DISTINCTCOUNT([Henkilo_koodi]),",
              "FILTER('Muuttujat',(",
              "'Muuttujat'[Luokittelu]=\"Kansainvälinen yhteistutkinto\" ",
              ") ) )"
            ],
            "formatString": "#,0",
            "isHidden": true
          },
          {
            "name": "Kaksoistutkintoja",
            "expression": [
              "CALCULATE(DISTINCTCOUNT([Henkilo_koodi]),",
              "FILTER('Muuttujat',(",
              "'Muuttujat'[Luokittelu]=\"Kansainvälinen kaksoistutkinto\" ",
              ") ) )"
            ],
            "formatString": "#,0",
            "isHidden": true
          },
          {
            "name": "Tutkintoja yhteensä",
            "expression": [
              "",
              "",
              "var lkm = CALCULATE(DISTINCTCOUNT([Henkilo_koodi]))",
              "",
              "RETURN IF(AND(lkm > 0, lkm < 5), \"1-4\", MROUND(lkm,3))"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Yhteis- ja kaksoistutkintojen määrä",
            "expression": [
              "",
              "",
              "var lkm = [Yhteistutkintoja]+[Kaksoistutkintoja]",
              "",
              "RETURN IF(AND(lkm > 0, lkm < 5), \"1-4\", MROUND(lkm,3))"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Yhteis- ja kaksoistutkintojen osuus",
            "expression": [
              "",
              "",
              "var osa = [Yhteis- ja kaksoistutkintojen määrä]",
              "var kaikki = [Tutkintoja yhteensä]",
              "",
              "return IF(osa = BLANK(), BLANK(),",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, 0,",
              "CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Tutkintoja yhteensä_s",
            "expression": [
              "",
              "",
              "CALCULATE(DISTINCTCOUNT([Henkilo_koodi]))",
              "",
              "",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "Yhteis- ja kaksoistutkintojen määrä_s",
            "expression": [
              "",
              "",
              "[Yhteistutkintoja]+[Kaksoistutkintoja]",
              "",
              "",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "Yhteis- ja kaksoistutkintojen osuus_s",
            "expression": [
              "",
              "",
              "DIVIDE([Yhteis- ja kaksoistutkintojen määrä_s], [Tutkintoja yhteensä_s], BLANK())"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dw].[v_virta_otp_yhteiskaksoistutkinnot].* FROM [dw].[v_virta_otp_yhteiskaksoistutkinnot] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "v_virta_otp_yhteiskaksoistutkinnot"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dw"
          }
        ]
      }
    ],
    "perspectives": [
      {
        "name": "Perus",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Ikä"
              },
              {
                "name": "Ikäryhmä"
              },
              {
                "name": "Kansalaisuus (maanosa)"
              },
              {
                "name": "Korkeakoulu"
              },
              {
                "name": "Koulutusala, taso 1"
              },
              {
                "name": "Koulutusala, taso 2"
              },
              {
                "name": "Koulutusala, taso 3"
              },
              {
                "name": "Koulutusaste, taso 1"
              },
              {
                "name": "Koulutusaste, taso 2"
              },
              {
                "name": "Luokittelu"
              },
              {
                "name": "OKM ohjauksen ala"
              },
              {
                "name": "Sektori"
              },
              {
                "name": "Sukupuoli"
              },
              {
                "name": "Tutkinto"
              },
              {
                "name": "Tilastovuosi"
              }
            ],
            "measures": [
              {
                "name": "Kaksoistutkintoja"
              },
              {
                "name": "Yhteistutkintoja"
              },
              {
                "name": "Tutkintoja yhteensä"
              },
              {
                "name": "Yhteis- ja kaksoistutkintojen määrä"
              },
              {
                "name": "Yhteis- ja kaksoistutkintojen osuus"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Perus2",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Ikä"
              },
              {
                "name": "Ikäryhmä"
              },
              {
                "name": "Kansalaisuus (maanosa)"
              },
              {
                "name": "Korkeakoulu"
              },
              {
                "name": "Koulutusala, taso 1"
              },
              {
                "name": "Koulutusala, taso 2"
              },
              {
                "name": "Koulutusala, taso 3"
              },
              {
                "name": "Koulutusaste, taso 1"
              },
              {
                "name": "Koulutusaste, taso 2"
              },
              {
                "name": "Luokittelu"
              },
              {
                "name": "OKM ohjauksen ala"
              },
              {
                "name": "Sektori"
              },
              {
                "name": "Sukupuoli"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Tutkinto"
              },
              {
                "name": "Kansalaisuus"
              }
            ],
            "measures": [
              {
                "name": "Kaksoistutkintoja"
              },
              {
                "name": "Tutkintoja yhteensä"
              },
              {
                "name": "Yhteis- ja kaksoistutkintojen määrä"
              },
              {
                "name": "Yhteis- ja kaksoistutkintojen osuus"
              },
              {
                "name": "Yhteistutkintoja"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      }
    ],
    "roles": [
      {
        "name": "Luku",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "DWI\\P_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1733"
          },
          {
            "memberName": "DWI\\T_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1732"
          },
          {
            "memberName": "DWI\\ffinnber",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1355"
          },
          {
            "memberName": "NT AUTHORITY\\IUSR",
            "memberId": "S-1-5-17"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "400"
      }
    ]
  },
  "id": "SemanticModel"
}