{
  "name": "SemanticModel",
  "compatibilityLevel": 1200,
  "model": {
    "culture": "fi-FI",
    "dataSources": [
      {
        "name": "SqlServer dwitestvipusql Bibliometriikka",
        "connectionString": "Provider=SQLOLEDB.1;Data Source=dwitvipusql22;Initial Catalog=Bibliometriikka;Integrated Security=SSPI;Persist Security Info=false",
        "impersonationMode": "impersonateServiceAccount",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      },
      {
        "name": "SqlServer dwitvipusql22 Bibliometriikka",
        "connectionString": "Provider=SQLOLEDB.1;Data Source=dwitvipusql22;Initial Catalog=Bibliometriikka;Integrated Security=SSPI;Persist Security Info=false",
        "impersonationMode": "impersonateServiceAccount",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      },
      {
        "name": "SqlServer dwitvipusql22 Bibliometriikka 2",
        "connectionString": "Provider=SQLOLEDB.1;Data Source=dwitvipusql22;Initial Catalog=Bibliometriikka;Integrated Security=SSPI;Persist Security Info=false",
        "impersonationMode": "impersonateServiceAccount",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      },
      {
        "name": "SqlServer dwitvipusql22 Bibliometriikka 3",
        "connectionString": "Provider=SQLOLEDB.1;Data Source=dwitvipusql22;Initial Catalog=Bibliometriikka;Integrated Security=SSPI;Persist Security Info=false",
        "impersonationMode": "impersonateServiceAccount",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "Sarakeleveys",
        "isHidden": true,
        "columns": [
          {
            "name": "Sarakeleveys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Sarakeleveys"
          },
          {
            "name": "leveys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "leveys"
          }
        ],
        "partitions": [
          {
            "name": "Sarakeleveys",
            "source": {
              "type": "query",
              "query": "SELECT [dbo].[Sarakeleveys].* FROM [dbo].[Sarakeleveys]",
              "dataSource": "SqlServer dwitestvipusql Bibliometriikka"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization"
              },
              {
                "name": "TableWidgetSerialization"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Sarakeleveys"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Sarakeleveys].* FROM [dbo].[Sarakeleveys] "
          }
        ]
      },
      {
        "name": "Bibliometriikka 2020",
        "columns": [
          {
            "name": "Vuosikoodi",
            "dataType": "int64",
            "sourceColumn": "Vuosikoodi",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Nelivuotiskausi",
            "dataType": "string",
            "sourceColumn": "Nelivuotiskausi",
            "sourceProviderType": "WChar",
            "displayFolder": "Aikamuuttujat"
          },
          {
            "name": "Vuosi",
            "dataType": "int64",
            "sourceColumn": "Vuosi",
            "sourceProviderType": "Integer",
            "displayFolder": "Aikamuuttujat"
          },
          {
            "name": "Maajärjestys",
            "dataType": "int64",
            "sourceColumn": "Maajärjestys",
            "sourceProviderType": "Integer"
          },
          {
            "name": "IDkoodi",
            "dataType": "int64",
            "sourceColumn": "IDkoodi",
            "sourceProviderType": "BigInt"
          },
          {
            "name": "Maa",
            "dataType": "string",
            "sourceColumn": "Maa",
            "sourceProviderType": "WChar",
            "displayFolder": "Aluemuuttujat"
          },
          {
            "name": "Manner",
            "dataType": "string",
            "sourceColumn": "Manner",
            "sourceProviderType": "WChar",
            "displayFolder": "Aluemuuttujat"
          },
          {
            "name": "Mannerkoodi",
            "dataType": "int64",
            "sourceColumn": "Mannerkoodi",
            "sourceProviderType": "Integer"
          },
          {
            "name": "EU15-maat",
            "dataType": "string",
            "sourceColumn": "EU15-maat",
            "sourceProviderType": "WChar",
            "displayFolder": "Aluemuuttujat"
          },
          {
            "name": "EU15-maat jarjestys",
            "dataType": "int64",
            "sourceColumn": "EU15-maat jarjestys",
            "sourceProviderType": "Integer"
          },
          {
            "name": "EU-maat",
            "dataType": "string",
            "sourceColumn": "EU-maat",
            "sourceProviderType": "WChar",
            "displayFolder": "Aluemuuttujat"
          },
          {
            "name": "EU-maat jarjestys",
            "dataType": "int64",
            "sourceColumn": "EU-maat jarjestys",
            "sourceProviderType": "Integer"
          },
          {
            "name": "IC-maat",
            "dataType": "string",
            "sourceColumn": "IC-maat",
            "sourceProviderType": "WChar",
            "displayFolder": "Aluemuuttujat"
          },
          {
            "name": "OECD-maat",
            "dataType": "string",
            "sourceColumn": "OECD-maat",
            "sourceProviderType": "WChar",
            "displayFolder": "Aluemuuttujat"
          },
          {
            "name": "OECD-maat jarjestys",
            "dataType": "int64",
            "sourceColumn": "OECD-maat jarjestys",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Pohjoismaat",
            "dataType": "string",
            "sourceColumn": "Pohjoismaat",
            "sourceProviderType": "WChar",
            "displayFolder": "Aluemuuttujat"
          },
          {
            "name": "Pohjoismaat jarjestys",
            "dataType": "int64",
            "sourceColumn": "Pohjoismaat jarjestys",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Maaryhmä",
            "dataType": "string",
            "sourceColumn": "Maaryhmä",
            "sourceProviderType": "WChar",
            "displayFolder": "Aluemuuttujat"
          },
          {
            "name": "Maaryhmä Järjestys",
            "dataType": "int64",
            "sourceColumn": "Maaryhmä Järjestys",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Yhteistyö",
            "dataType": "string",
            "sourceColumn": "Yhteistyö",
            "sourceProviderType": "Char",
            "displayFolder": "Yhteistyömuuttujat"
          },
          {
            "name": "Päätieteenala koodi",
            "dataType": "int64",
            "sourceColumn": "Päätieteenala koodi",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Päätieteenala",
            "dataType": "string",
            "sourceColumn": "Päätieteenala",
            "sourceProviderType": "WChar",
            "displayFolder": "Tieteenalamuuttujat"
          },
          {
            "name": "Tieteenala koodi",
            "dataType": "int64",
            "sourceColumn": "Tieteenala koodi",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Tieteenalaryhmä (tieteen tila)",
            "dataType": "string",
            "sourceColumn": "Tieteenalaryhmä (tieteen tila)",
            "sourceProviderType": "WChar",
            "displayFolder": "Tieteenalamuuttujat"
          },
          {
            "name": "Tieteenala bibliometrinen koodi",
            "dataType": "int64",
            "sourceColumn": "Tieteenala bibliometrinen koodi",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Tieteenala",
            "dataType": "string",
            "sourceColumn": "Tieteenala",
            "sourceProviderType": "WChar",
            "displayFolder": "Tieteenalamuuttujat"
          },
          {
            "name": "TRAlakoodi3",
            "dataType": "int64",
            "sourceColumn": "TRAlakoodi3",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Alanimi_taso3",
            "dataType": "string",
            "sourceColumn": "Alanimi_taso3",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Organisaatio",
            "dataType": "string",
            "sourceColumn": "Organisaatio",
            "sourceProviderType": "WChar",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Organisaatiotyyppi",
            "dataType": "string",
            "sourceColumn": "Organisaatiotyyppi",
            "sourceProviderType": "WChar",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Organisaatiotyyppi koodi",
            "dataType": "int64",
            "sourceColumn": "Organisaatiotyyppi koodi",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Kansainvälinen yhteistyö",
            "dataType": "string",
            "sourceColumn": "Kansainvälinen yhteistyö",
            "sourceProviderType": "WChar",
            "displayFolder": "Yhteistyömuuttujat"
          },
          {
            "name": "Kansallinen Yhteistyö",
            "dataType": "string",
            "sourceColumn": "Kansallinen Yhteistyö",
            "sourceProviderType": "WChar",
            "displayFolder": "Yhteistyömuuttujat"
          },
          {
            "name": "Kansallinen Yliopistoyhteistyö",
            "dataType": "string",
            "sourceColumn": "Kansallinen Yliopistoyhteistyö",
            "sourceProviderType": "WChar",
            "displayFolder": "Yhteistyömuuttujat"
          },
          {
            "name": "Kansallinen Yritysyhteistyö",
            "dataType": "string",
            "sourceColumn": "Kansallinen Yritysyhteistyö",
            "sourceProviderType": "WChar",
            "displayFolder": "Yhteistyömuuttujat"
          },
          {
            "name": "Julkaisut Maailma 4 vuotta",
            "dataType": "double",
            "sourceColumn": "Julkaisut Maailma 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "Top10 Julkaisut (Maailma 4v Ositettu)",
            "dataType": "double",
            "sourceColumn": "Top10 Julkaisut (Maailma 4v Ositettu)",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "Analyysijulkaisut Maailma 4 vuotta",
            "dataType": "double",
            "sourceColumn": "Analyysijulkaisut Maailma 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "TOP 10 Julkaisut Maailma 4 vuotta",
            "dataType": "double",
            "sourceColumn": "TOP 10 Julkaisut Maailma 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "TOP 5 Julkaisut Maailma 4 vuotta",
            "dataType": "double",
            "sourceColumn": "TOP 5 Julkaisut Maailma 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "TOP 1 Julkaisut Maailma 4 vuotta",
            "dataType": "double",
            "sourceColumn": "TOP 1 Julkaisut Maailma 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "Sisäinen kattavuus Maailma 4 vuotta",
            "dataType": "double",
            "sourceColumn": "Sisäinen kattavuus Maailma 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "Sitaatiot Maailma 4 vuotta",
            "dataType": "double",
            "sourceColumn": "Sitaatiot Maailma 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "TOP 10 Indeksi Maailma 4 vuotta",
            "dataType": "double",
            "sourceColumn": "TOP 10 Indeksi Maailma 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "TOP 5 Indeksi Maailma 4 vuotta",
            "dataType": "double",
            "sourceColumn": "TOP 5 Indeksi Maailma 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "TOP 1 Indeksi Maailma 4 vuotta",
            "dataType": "double",
            "sourceColumn": "TOP 1 Indeksi Maailma 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "Julkaisut Suomi 4 vuotta",
            "dataType": "double",
            "sourceColumn": "Julkaisut Suomi 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "Analyysijulkaisut Suomi 4 vuotta",
            "dataType": "double",
            "sourceColumn": "Analyysijulkaisut Suomi 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "Julkaisut Suomi 1 vuotta",
            "dataType": "int64",
            "sourceColumn": "Julkaisut Suomi 1 vuotta",
            "sourceProviderType": "Integer"
          },
          {
            "name": "TOP 10 Julkaisut Suomi 4 vuotta",
            "dataType": "double",
            "sourceColumn": "TOP 10 Julkaisut Suomi 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "TOP 5 Julkaisut Suomi 4 vuotta",
            "dataType": "double",
            "sourceColumn": "TOP 5 Julkaisut Suomi 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "TOP 1 Julkaisut Suomi 4 vuotta",
            "dataType": "double",
            "sourceColumn": "TOP 1 Julkaisut Suomi 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "Sisäinen kattavuus Suomi 4 vuotta",
            "dataType": "double",
            "sourceColumn": "Sisäinen kattavuus Suomi 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "Sitaatiot Suomi 4 vuotta",
            "dataType": "double",
            "sourceColumn": "Sitaatiot Suomi 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "TOP 10 Indeksi Suomi 4 vuotta",
            "dataType": "double",
            "sourceColumn": "TOP 10 Indeksi Suomi 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "TOP 5 Indeksi Suomi 4 vuotta",
            "dataType": "double",
            "sourceColumn": "TOP 5 Indeksi Suomi 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "TOP 1 Indeksi Suomi 4 vuotta",
            "dataType": "double",
            "sourceColumn": "TOP 1 Indeksi Suomi 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "TOP 10 Julkaisut Suomi 1 vuosi",
            "dataType": "int64",
            "sourceColumn": "TOP 10 Julkaisut Suomi 1 vuosi",
            "sourceProviderType": "Integer"
          },
          {
            "name": "TOP 5 Julkaisut Suomi 1 vuosi",
            "dataType": "int64",
            "sourceColumn": "TOP 5 Julkaisut Suomi 1 vuosi",
            "sourceProviderType": "Integer"
          },
          {
            "name": "TOP 1 Julkaisut Suomi 1 vuosi",
            "dataType": "int64",
            "sourceColumn": "TOP 1 Julkaisut Suomi 1 vuosi",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Sisäinen kattavuus Suomi 1 vuosi",
            "dataType": "int64",
            "sourceColumn": "Sisäinen kattavuus Suomi 1 vuosi",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Sitaatiot Suomi 1 vuosi",
            "dataType": "int64",
            "sourceColumn": "Sitaatiot Suomi 1 vuosi",
            "sourceProviderType": "Integer"
          },
          {
            "name": "TOP 10 Indeksi Suomi 1 vuosi",
            "dataType": "int64",
            "sourceColumn": "TOP 10 Indeksi Suomi 1 vuosi",
            "sourceProviderType": "Integer"
          },
          {
            "name": "TOP 5 Indeksi Suomi 1 vuosi",
            "dataType": "int64",
            "sourceColumn": "TOP 5 Indeksi Suomi 1 vuosi",
            "sourceProviderType": "Integer"
          },
          {
            "name": "TOP 1 Indeksi Suomi 1 vuosi",
            "dataType": "int64",
            "sourceColumn": "TOP 1 Indeksi Suomi 1 vuosi",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Julkaisut YTmaatBilat 4 vuotta",
            "dataType": "double",
            "sourceColumn": "Julkaisut YTmaatBilat 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "Analyysijulkaisut YTmaatBilat 4 vuotta",
            "dataType": "double",
            "sourceColumn": "Analyysijulkaisut YTmaatBilat 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "TOP 10 Julkaisut YTmaatBilat 4 vuotta",
            "dataType": "double",
            "sourceColumn": "TOP 10 Julkaisut YTmaatBilat 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "TOP 5 Julkaisut YTmaatBilat 4 vuotta",
            "dataType": "double",
            "sourceColumn": "TOP 5 Julkaisut YTmaatBilat 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "TOP 1 Julkaisut YTmaatBilat 4 vuotta",
            "dataType": "double",
            "sourceColumn": "TOP 1 Julkaisut YTmaatBilat 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "Sitaatiot YTmaatBilat 4 vuotta",
            "dataType": "double",
            "sourceColumn": "Sitaatiot YTmaatBilat 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "TOP 10 Indeksi YTmaatBilat 4 vuotta",
            "dataType": "double",
            "sourceColumn": "TOP 10 Indeksi YTmaatBilat 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "TOP 5 Indeksi YTmaatBilat 4 vuotta",
            "dataType": "double",
            "sourceColumn": "TOP 5 Indeksi YTmaatBilat 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "TOP 1 Indeksi YTmaatBilat 4 vuotta",
            "dataType": "double",
            "sourceColumn": "TOP 1 Indeksi YTmaatBilat 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "Julkaisut YTmaatKaikki 4 vuotta",
            "dataType": "double",
            "sourceColumn": "Julkaisut YTmaatKaikki 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "Analyysijulkaisut YTmaatKaikki 4 vuotta",
            "dataType": "double",
            "sourceColumn": "Analyysijulkaisut YTmaatKaikki 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "TOP 10 Julkaisut YTmaatKaikki 4 vuotta",
            "dataType": "double",
            "sourceColumn": "TOP 10 Julkaisut YTmaatKaikki 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "TOP 5 Julkaisut YTmaatKaikki 4 vuotta",
            "dataType": "double",
            "sourceColumn": "TOP 5 Julkaisut YTmaatKaikki 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "TOP 1 Julkaisut YTmaatKaikki 4 vuotta",
            "dataType": "double",
            "sourceColumn": "TOP 1 Julkaisut YTmaatKaikki 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "Sitaatiot YTmaatKaikki 4 vuotta",
            "dataType": "double",
            "sourceColumn": "Sitaatiot YTmaatKaikki 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "TOP 10 Indeksi YTmaatKaikki 4 vuotta",
            "dataType": "double",
            "sourceColumn": "TOP 10 Indeksi YTmaatKaikki 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "TOP 5 Indeksi YTmaatKaikki 4 vuotta",
            "dataType": "double",
            "sourceColumn": "TOP 5 Indeksi YTmaatKaikki 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "TOP 1 Indeksi YTmaatKaikki 4 vuotta",
            "dataType": "double",
            "sourceColumn": "TOP 1 Indeksi YTmaatKaikki 4 vuotta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "PID",
            "dataType": "int64",
            "sourceColumn": "PID",
            "sourceProviderType": "Integer"
          },
          {
            "name": "PID YT maat Bilat Whole",
            "dataType": "int64",
            "sourceColumn": "PID YT maat Bilat Whole",
            "sourceProviderType": "Integer"
          },
          {
            "name": "PID YT maat Kaikki Whole",
            "dataType": "int64",
            "sourceColumn": "PID YT maat Kaikki Whole",
            "sourceProviderType": "Integer"
          }
        ],
        "partitions": [
          {
            "name": "Bibliometriikka 2020",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[v_f_tab_maailma_4v_2020].* FROM [dbo].[v_f_tab_maailma_4v_2020] ",
              "dataSource": "SqlServer dwitvipusql22 Bibliometriikka 3"
            }
          }
        ],
        "measures": [
          {
            "name": "Julkaisut (Maailma 4v Ositettu) 2020",
            "expression": "SUMX(SUMMARIZE('Bibliometriikka 2020',[IDkoodi],[Julkaisut Maailma 4 vuotta]),[Julkaisut Maailma 4 vuotta])",
            "formatString": "#,0"
          },
          {
            "name": "Top10-indeksi (maailma 4v) 2020",
            "expression": "IF(AND([Julkaisut (Maailma 4v Ositettu) 2020]>=50,[Sisäinen kattavuus (maailma 4v) 2020]>=0.4),CALCULATE(SUMX(SUMMARIZE('Bibliometriikka 2020',[IDkoodi],[TOP 10 Indeksi Maailma 4 vuotta]),[TOP 10 Indeksi Maailma 4 vuotta])/SUMX(SUMMARIZE('Bibliometriikka 2020',[IDkoodi],[TOP 10 Julkaisut Maailma 4 vuotta]),[TOP 10 Julkaisut Maailma 4 vuotta]),FILTER('Bibliometriikka 2020','Bibliometriikka 2020'[Vuosikoodi]<26)),BLANK())",
            "formatString": "0.00"
          },
          {
            "name": "Sisäinen kattavuus (maailma 4v) 2020",
            "expression": "SUMX(SUMMARIZE('Bibliometriikka 2020',[IDkoodi],[Sisäinen kattavuus Maailma 4 vuotta]),[Sisäinen kattavuus Maailma 4 vuotta])/SUMX(SUMMARIZE('Bibliometriikka 2020',[IDkoodi],[Julkaisut Maailma 4 vuotta]),[Julkaisut Maailma 4 vuotta])",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Top5-indeksi (maailma 4v) 2020",
            "expression": "CALCULATE(SUMX(SUMMARIZE('Bibliometriikka 2020',[IDkoodi],[TOP 5 Indeksi Maailma 4 vuotta]),[TOP 5 Indeksi Maailma 4 vuotta])/SUMX(SUMMARIZE('Bibliometriikka 2020',[IDkoodi],[TOP 5 Julkaisut Maailma 4 vuotta]),[TOP 5 Julkaisut Maailma 4 vuotta]),FILTER('Bibliometriikka 2020','Bibliometriikka 2020'[Vuosikoodi]<26))",
            "formatString": "0.00"
          },
          {
            "name": "Top1-indeksi (maailma 4v) 2020",
            "expression": "IF(AND([Julkaisut (Maailma 4v Ositettu) 2020]>=50,[Sisäinen kattavuus (maailma 4v) 2020]>=0.4),CALCULATE(SUMX(SUMMARIZE('Bibliometriikka 2020',[IDkoodi],[TOP 1 Indeksi Maailma 4 vuotta]),[TOP 1 Indeksi Maailma 4 vuotta])/SUMX(SUMMARIZE('Bibliometriikka 2020',[IDkoodi],[TOP 1 Julkaisut Maailma 4 vuotta]),[TOP 1 Julkaisut Maailma 4 vuotta]),FILTER('Bibliometriikka 2020','Bibliometriikka 2020'[Vuosikoodi]<26)),BLANK())",
            "formatString": "0.00"
          },
          {
            "name": "Viittausindeksi (Maailma 4v) 2020",
            "expression": [
              "IF(AND([Julkaisut (Maailma 4v Ositettu) 2020]>=50,[Sisäinen kattavuus (maailma 4v) 2020]>=0.4),CALCULATE(SUMX(SUMMARIZE('Bibliometriikka 2020',[IDkoodi],[Sitaatiot Maailma 4 vuotta]),[Sitaatiot Maailma 4 vuotta])/SUMX(SUMMARIZE('Bibliometriikka 2020',[IDkoodi],[Analyysijulkaisut Maailma 4 vuotta]),[Analyysijulkaisut Maailma 4 vuotta]),",
              "FILTER('Bibliometriikka 2020','Bibliometriikka 2020'[Vuosikoodi]<26)),BLANK())",
              ""
            ],
            "formatString": "0.00"
          },
          {
            "name": "Top5-indeksi(Suomi 4v) 2020",
            "expression": "CALCULATE(DIVIDE((SUM([TOP 5 Indeksi Suomi 4 vuotta])/SUM([TOP 5 Julkaisut Suomi 4 vuotta])),1),FILTER('Bibliometriikka 2020','Bibliometriikka 2020'[Vuosikoodi]<26))",
            "formatString": "0.00"
          },
          {
            "name": "Top10-indeksi (YT Maat Bilat 4 vuotta) 2020",
            "expression": "IF([Julkaisut (YT Maat Bilat 4 vuotta) 2020]>=50,CALCULATE(SUMX(SUMMARIZE('Bibliometriikka 2020',[IDkoodi],[TOP 10 Indeksi YTmaatBilat 4 vuotta]),[TOP 10 Indeksi YTmaatBilat 4 vuotta])/SUMX(SUMMARIZE('Bibliometriikka 2020',[IDkoodi],[TOP 10 Julkaisut YTmaatBilat 4 vuotta]),[TOP 10 Julkaisut YTmaatBilat 4 vuotta]),FILTER('Bibliometriikka 2020','Bibliometriikka 2020'[Vuosikoodi]<26)),BLANK())",
            "formatString": "0.00"
          },
          {
            "name": "Julkaisut (YT Maat Bilat 4 vuotta) 2020",
            "expression": "sumx(summarize('Bibliometriikka 2020',[IDkoodi],[Julkaisut YTmaatBilat 4 vuotta]),[Julkaisut YTmaatBilat 4 vuotta])",
            "formatString": "#,0"
          },
          {
            "name": "Top1-indeksi (YT Maat Bilat 4 vuotta) 2020",
            "expression": "IF([Julkaisut (YT Maat Bilat 4 vuotta) 2020]>=50,CALCULATE(SUMX(SUMMARIZE('Bibliometriikka 2020',[IDkoodi],[TOP 1 Indeksi YTmaatBilat 4 vuotta]),[TOP 1 Indeksi YTmaatBilat 4 vuotta])/SUMX(SUMMARIZE('Bibliometriikka 2020',[IDkoodi],[TOP 1 Julkaisut YTmaatBilat 4 vuotta]),[TOP 1 Julkaisut YTmaatBilat 4 vuotta]),FILTER('Bibliometriikka 2020','Bibliometriikka 2020'[Vuosikoodi]<26)),BLANK())",
            "formatString": "0.00"
          },
          {
            "name": "Viittausindeksi (YT maat Bilat 4 vuotta) 2020",
            "expression": "IF([Julkaisut (YT Maat Bilat 4 vuotta) 2020]>=50,CALCULATE(SUMX(SUMMARIZE('Bibliometriikka 2020',[IDkoodi],[Sitaatiot YTmaatBilat 4 vuotta]),[Sitaatiot YTmaatBilat 4 vuotta])/SUMX(SUMMARIZE('Bibliometriikka 2020',[IDkoodi],[Analyysijulkaisut YTmaatBilat 4 vuotta]),[Analyysijulkaisut YTmaatBilat 4 vuotta]),FILTER('Bibliometriikka 2020','Bibliometriikka 2020'[Vuosikoodi]<26)),BLANK())",
            "formatString": "0.00"
          },
          {
            "name": "Top5-indeksi(Suomi 1v) 2020",
            "expression": "SUM([TOP 5 Indeksi Suomi 1 vuosi])/SUM([TOP 5 Julkaisut Suomi 1 vuosi])",
            "formatString": "0.00"
          },
          {
            "name": "Top10-indeksi(Suomi 1v) 2020",
            "expression": "SUM([TOP 10 Indeksi Suomi 1 vuosi])/SUM([TOP 10 Julkaisut Suomi 1 vuosi])",
            "formatString": "0.00"
          },
          {
            "name": "Top1-indeksi (YT Maat Kaikki 4 vuotta) 2020",
            "expression": "IF([Julkaisut (YT Maat Kaikki 4 vuotta) 2020]>=50,CALCULATE(SUMX(SUMMARIZE('Bibliometriikka 2020',[IDkoodi],[TOP 1 Indeksi YTmaatKaikki 4 vuotta]),[TOP 1 Indeksi YTmaatKaikki 4 vuotta])/SUMX(SUMMARIZE('Bibliometriikka 2020',[IDkoodi],[TOP 1 Julkaisut YTmaatKaikki 4 vuotta]),[TOP 1 Julkaisut YTmaatKaikki 4 vuotta]),FILTER('Bibliometriikka 2020','Bibliometriikka 2020'[Vuosikoodi]<26)),BLANK())",
            "formatString": "0.00"
          },
          {
            "name": "Top1-indeksi(Suomi 1v) 2020",
            "expression": "SUM([TOP 1 Indeksi Suomi 1 vuosi])/SUM([TOP 1 Julkaisut Suomi 1 vuosi])",
            "formatString": "0.00"
          },
          {
            "name": "Viittausindeksi (Suomi 1v) 2020",
            "expression": "if([Julkaisut (Suomi 1v Osittamaton) 2020]<50,BLANK(),SUM([Sitaatiot Suomi 1 vuosi])/SUM([Julkaisut Suomi 1 vuotta]))",
            "formatString": "0.00"
          },
          {
            "name": "Julkaisut (YT Maat Bilat Whole) 2020",
            "expression": "CALCULATE(DISTINCTCOUNT([PID YT maat Bilat Whole]),NOT(ISBLANK('Bibliometriikka 2020'[PID YT maat Bilat Whole])))",
            "formatString": "#,0"
          },
          {
            "name": "Julkaisut (YT Maat Kaikki Whole) 2020",
            "expression": "CALCULATE(DISTINCTCOUNT([PID YT maat Kaikki Whole]),not(ISBLANK('Bibliometriikka 2020'[PID YT maat Kaikki Whole])))",
            "formatString": "#,0"
          },
          {
            "name": "Sum of TOP 1 Indeksi Suomi 1 vuosi 2020",
            "expression": "SUM([TOP 1 Indeksi Suomi 1 vuosi])"
          },
          {
            "name": "Julkaisut (Suomi 4v Ositettu) 2020",
            "expression": "SUM([Julkaisut Suomi 4 vuotta])",
            "formatString": "#,0"
          },
          {
            "name": "Top10-indeksi(Suomi 4v) 2020",
            "expression": "IF(AND([Julkaisut (Suomi 4v Ositettu) 2020]>=50,[Sisäinen kattavuus (suomi 4v) 2020]>=0.4),CALCULATE(DIVIDE((SUM([TOP 10 Indeksi Suomi 4 vuotta])/SUM([TOP 10 Julkaisut Suomi 4 vuotta])),1),FILTER('Bibliometriikka 2020','Bibliometriikka 2020'[Vuosikoodi]<26)),BLANK())",
            "formatString": "0.00"
          },
          {
            "name": "Top1-indeksi(Suomi 4v) 2020",
            "expression": "IF(AND([Julkaisut (Suomi 4v Ositettu) 2020]>=50,[Sisäinen kattavuus (suomi 4v) 2020]>=0.4),CALCULATE(DIVIDE((SUM([TOP 1 Indeksi Suomi 4 vuotta])/SUM([TOP 1 Julkaisut Suomi 4 vuotta])),1),FILTER('Bibliometriikka 2020','Bibliometriikka 2020'[Vuosikoodi]<26)),BLANK())",
            "formatString": "0.00"
          },
          {
            "name": "Sisäinen kattavuus (suomi 4v) 2020",
            "expression": "SUM([Sisäinen kattavuus Suomi 4 vuotta])/SUM([Julkaisut Suomi 4 vuotta])",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Viittausindeksi (Suomi 4v) 2020",
            "expression": "if([Julkaisut (Suomi 4v Ositettu) 2020]<50,BLANK(),CALCULATE(SUM([Sitaatiot Suomi 4 vuotta])/SUM([Analyysijulkaisut Suomi 4 vuotta])/1,FILTER('Bibliometriikka 2020','Bibliometriikka 2020'[Vuosikoodi]<26)))",
            "formatString": "0.00"
          },
          {
            "name": "Julkaisut (Suomi 1v Osittamaton) 2020",
            "expression": "CALCULATE(DISTINCTCOUNT([PID]),NOT(ISBLANK('Bibliometriikka 2020'[PID])))",
            "formatString": "#,0"
          },
          {
            "name": "Julkaisut (YT Maat Kaikki 4 vuotta) 2020",
            "expression": "sumx(summarize('Bibliometriikka 2020',[IDkoodi],[Julkaisut YTmaatKaikki 4 vuotta]),[Julkaisut YTmaatKaikki 4 vuotta])",
            "formatString": "#,0"
          },
          {
            "name": "Top10-indeksi (YT Maat Kaikki 4 vuotta) 2020",
            "expression": "IF([Julkaisut (YT Maat Kaikki 4 vuotta) 2020]>=50,CALCULATE(SUMX(SUMMARIZE('Bibliometriikka 2020',[IDkoodi],[TOP 10 Indeksi YTmaatKaikki 4 vuotta]),[TOP 10 Indeksi YTmaatKaikki 4 vuotta])/SUMX(SUMMARIZE('Bibliometriikka 2020',[IDkoodi],[TOP 10 Julkaisut YTmaatKaikki 4 vuotta]),[TOP 10 Julkaisut YTmaatKaikki 4 vuotta]),FILTER('Bibliometriikka 2020','Bibliometriikka 2020'[Vuosikoodi]<26)),BLANK())",
            "formatString": "0.00"
          },
          {
            "name": "Viittausindeksi (YT maat Kaikki 4 vuotta) 2020",
            "expression": "IF([Julkaisut (YT Maat Kaikki 4 vuotta) 2020]>=50,CALCULATE(SUMX(SUMMARIZE('Bibliometriikka 2020',[IDkoodi],[Sitaatiot YTmaatKaikki 4 vuotta]),[Sitaatiot YTmaatKaikki 4 vuotta])/SUMX(SUMMARIZE('Bibliometriikka 2020',[IDkoodi],[Analyysijulkaisut YTmaatKaikki 4 vuotta]),[Analyysijulkaisut YTmaatKaikki 4 vuotta]),FILTER('Bibliometriikka 2020','Bibliometriikka 2020'[Vuosikoodi]<26)),BLANK())",
            "formatString": "0.00"
          },
          {
            "name": "Top 10 Julkaisut (Maailma 4v Ositettu) 2020",
            "expression": "CALCULATE(SUMX(SUMMARIZE('Bibliometriikka 2020',[IDkoodi],[Top10 Julkaisut (Maailma 4v Ositettu)]),[Top10 Julkaisut (Maailma 4v Ositettu)]),FILTER('Bibliometriikka 2020','Bibliometriikka 2020'[Vuosikoodi]<26))",
            "formatString": "#,0"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[v_f_tab_maailma_4v_2020].* FROM [dbo].[v_f_tab_maailma_4v_2020] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "v_f_tab_maailma_4v_2020"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      }
    ],
    "perspectives": [
      {
        "name": "Analyysiraportti KV2020",
        "tables": [
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          },
          {
            "name": "Bibliometriikka 2020",
            "columns": [
              {
                "name": "EU15-maat"
              },
              {
                "name": "EU-maat"
              },
              {
                "name": "IC-maat"
              },
              {
                "name": "Kansainvälinen yhteistyö"
              },
              {
                "name": "Maa"
              },
              {
                "name": "Maaryhmä"
              },
              {
                "name": "Manner"
              },
              {
                "name": "Nelivuotiskausi"
              },
              {
                "name": "OECD-maat"
              },
              {
                "name": "Pohjoismaat"
              },
              {
                "name": "Päätieteenala"
              },
              {
                "name": "Tieteenala"
              },
              {
                "name": "Tieteenalaryhmä (tieteen tila)"
              }
            ],
            "measures": [
              {
                "name": "Julkaisut (Maailma 4v Ositettu) 2020"
              },
              {
                "name": "Sisäinen kattavuus (maailma 4v) 2020"
              },
              {
                "name": "Top10-indeksi (maailma 4v) 2020"
              },
              {
                "name": "Top1-indeksi (maailma 4v) 2020"
              },
              {
                "name": "Viittausindeksi (Maailma 4v) 2020"
              }
            ]
          }
        ]
      },
      {
        "name": "Analyysiraportti Suomi 2020",
        "tables": [
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          },
          {
            "name": "Bibliometriikka 2020",
            "columns": [
              {
                "name": "Kansainvälinen yhteistyö"
              },
              {
                "name": "Kansallinen Yhteistyö"
              },
              {
                "name": "Kansallinen Yliopistoyhteistyö"
              },
              {
                "name": "Kansallinen Yritysyhteistyö"
              },
              {
                "name": "Nelivuotiskausi"
              },
              {
                "name": "Organisaatio"
              },
              {
                "name": "Organisaatiotyyppi"
              },
              {
                "name": "Päätieteenala"
              },
              {
                "name": "Tieteenala"
              },
              {
                "name": "Tieteenalaryhmä (tieteen tila)"
              },
              {
                "name": "Vuosi"
              },
              {
                "name": "Yhteistyö"
              }
            ],
            "measures": [
              {
                "name": "Julkaisut (Suomi 1v Osittamaton) 2020"
              },
              {
                "name": "Julkaisut (Suomi 4v Ositettu) 2020"
              },
              {
                "name": "Top10-indeksi(Suomi 4v) 2020"
              },
              {
                "name": "Top1-indeksi(Suomi 4v) 2020"
              },
              {
                "name": "Viittausindeksi (Suomi 4v) 2020"
              }
            ]
          }
        ]
      },
      {
        "name": "Top 10 Julkaisut 2020",
        "tables": [
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          },
          {
            "name": "Bibliometriikka 2020",
            "columns": [
              {
                "name": "Kansainvälinen yhteistyö"
              },
              {
                "name": "Nelivuotiskausi"
              },
              {
                "name": "Päätieteenala"
              },
              {
                "name": "Tieteenala"
              },
              {
                "name": "Tieteenalaryhmä (tieteen tila)"
              },
              {
                "name": "EU15-maat"
              },
              {
                "name": "EU-maat"
              },
              {
                "name": "IC-maat"
              },
              {
                "name": "Maa"
              },
              {
                "name": "Maaryhmä"
              },
              {
                "name": "Manner"
              },
              {
                "name": "OECD-maat"
              },
              {
                "name": "Pohjoismaat"
              }
            ],
            "measures": [
              {
                "name": "Top 10 Julkaisut (Maailma 4v Ositettu) 2020"
              }
            ]
          }
        ]
      }
    ],
    "roles": [
      {
        "name": "Excel Service",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "DWI\\T_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1732"
          },
          {
            "memberName": "DWI\\P_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1733"
          },
          {
            "memberName": "DWI\\Z_P_Antero_Read_TAB",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-4156"
          },
          {
            "memberName": "DWI\\Z_T_Antero_Read_TAB",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-4155"
          },
          {
            "memberName": "DWI\\T_VIPU_SSAS_DB_R",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1751"
          },
          {
            "memberName": "DWI\\T_VIPU_SSAS_DB_R_TK",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1753"
          },
          {
            "memberName": "DWI\\P_VIPU_SSAS_DB_R",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1752"
          },
          {
            "memberName": "DWI\\P_VIPU_SSAS_DB_R_TK",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1754"
          },
          {
            "memberName": "DWI\\Z_DWIPVIPURD_Allow_F_Drive",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-5333"
          }
        ]
      },
      {
        "name": "Read Role",
        "modelPermission": "readRefresh"
      }
    ]
  },
  "id": "SemanticModel"
}