{
  "name": "SemanticModel",
  "compatibilityLevel": 1200,
  "model": {
    "culture": "fi-FI",
    "dataSources": [
      {
        "name": "SqlServer dwitvipusql22.csc.fi ANTERO",
        "connectionString": "Provider=SQLOLEDB.1;Data Source=dwitvipusql22.csc.fi;Initial Catalog=ANTERO;Integrated Security=SSPI;Persist Security Info=false",
        "impersonationMode": "impersonateServiceAccount",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      },
      {
        "name": "SqlServer dwitvipusql22 antero",
        "connectionString": "Provider=SQLOLEDB.1;Data Source=dwitvipusql22;Initial Catalog=antero;Integrated Security=SSPI;Persist Security Info=false",
        "impersonationMode": "impersonateServiceAccount",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "Sarakeleveys",
        "isHidden": true,
        "columns": [
          {
            "name": "Sarakeleveys",
            "dataType": "string",
            "sourceColumn": "Sarakeleveys",
            "sourceProviderType": "Char"
          },
          {
            "name": "leveys",
            "dataType": "string",
            "sourceColumn": "leveys",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Sarakeleveys",
            "dataView": "full",
            "source": {
              "query": " SELECT [dw].[Sarakeleveys].* FROM [dw].[Sarakeleveys] ",
              "dataSource": "SqlServer dwitvipusql22.csc.fi ANTERO"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dw].[Sarakeleveys].* FROM [dw].[Sarakeleveys] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Sarakeleveys"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dw"
          }
        ]
      },
      {
        "name": "Muuttujat",
        "columns": [
          {
            "name": "Tilastovuosi",
            "dataType": "int64",
            "sourceColumn": "Tilastovuosi",
            "sourceProviderType": "Integer",
            "displayFolder": "Aikamuuttujat"
          },
          {
            "name": "Lukuvuosi",
            "dataType": "string",
            "sourceColumn": "Lukuvuosi",
            "sourceProviderType": "WChar",
            "displayFolder": "Aikamuuttujat"
          },
          {
            "name": "lo_aloituspvm",
            "dataType": "string",
            "sourceColumn": "lo_aloituspvm",
            "sourceProviderType": "Char"
          },
          {
            "name": "oo_aloituspvm",
            "dataType": "string",
            "sourceColumn": "oo_aloituspvm",
            "sourceProviderType": "Char"
          },
          {
            "name": "Aika aloittamisesta",
            "dataType": "string",
            "sourceColumn": "Aika aloittamisesta",
            "sourceProviderType": "Char",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Henkilo_koodi",
            "dataType": "string",
            "sourceColumn": "Henkilo_koodi",
            "sourceProviderType": "Char"
          },
          {
            "name": "Sukupuoli",
            "dataType": "string",
            "sourceColumn": "Sukupuoli",
            "sourceProviderType": "WChar",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "uusi_opisk",
            "dataType": "int64",
            "sourceColumn": "uusi_opisk",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Aloittanut keväällä",
            "dataType": "string",
            "sourceColumn": "Aloittanut keväällä",
            "sourceProviderType": "Char",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Olo syksy",
            "dataType": "int64",
            "sourceColumn": "Olo syksy",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Olo kevät",
            "dataType": "int64",
            "sourceColumn": "Olo kevät",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Lasna",
            "dataType": "int64",
            "sourceColumn": "Lasna",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Suorittanut55",
            "dataType": "int64",
            "sourceColumn": "Suorittanut55",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Opintopisteet syksy",
            "dataType": "int64",
            "sourceColumn": "Opintopisteet syksy",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Opintopisteet kevät",
            "dataType": "int64",
            "sourceColumn": "Opintopisteet kevät",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Sektori",
            "dataType": "string",
            "sourceColumn": "Sektori",
            "sourceProviderType": "Char",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Korkeakoulu",
            "dataType": "string",
            "sourceColumn": "Korkeakoulu",
            "sourceProviderType": "WChar",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Tutkintokoodi",
            "dataType": "string",
            "sourceColumn": "Tutkintokoodi",
            "sourceProviderType": "Char",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Tutkinto",
            "dataType": "string",
            "sourceColumn": "Tutkinto",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "OKM ohjauksen ala",
            "dataType": "string",
            "sourceColumn": "OKM ohjauksen ala",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusaste, taso 1",
            "dataType": "string",
            "sourceColumn": "Koulutusaste, taso 1",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusaste, taso 2",
            "dataType": "string",
            "sourceColumn": "Koulutusaste, taso 2",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusala, taso 1",
            "dataType": "string",
            "sourceColumn": "Koulutusala, taso 1",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusala, taso 2",
            "dataType": "string",
            "sourceColumn": "Koulutusala, taso 2",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusala, taso 3",
            "dataType": "string",
            "sourceColumn": "Koulutusala, taso 3",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "suorittanut_27",
            "dataType": "int64",
            "sourceColumn": "suorittanut_27",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "suorittanut_55_ilman_pankkia",
            "dataType": "int64",
            "sourceColumn": "suorittanut_55_ilman_pankkia",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "suorittanut_55_pankin_avulla",
            "dataType": "int64",
            "sourceColumn": "suorittanut_55_pankin_avulla",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "Ikä",
            "dataType": "int64",
            "sourceColumn": "Ikä",
            "sortByColumn": "Ikä jarj",
            "sourceProviderType": "SmallInt",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Ikäryhmä",
            "dataType": "string",
            "sourceColumn": "Ikäryhmä",
            "sortByColumn": "Ikäryhmä jarj",
            "sourceProviderType": "WChar",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "OKM ohjauksen ala jarj",
            "dataType": "string",
            "sourceColumn": "OKM ohjauksen ala jarj",
            "sourceProviderType": "Char"
          },
          {
            "name": "Koulutusaste, taso 1 jarj",
            "dataType": "string",
            "sourceColumn": "Koulutusaste, taso 1 jarj",
            "sourceProviderType": "Char"
          },
          {
            "name": "Koulutusaste, taso 2 jarj",
            "dataType": "string",
            "sourceColumn": "Koulutusaste, taso 2 jarj",
            "sourceProviderType": "Char"
          },
          {
            "name": "Koulutusala, taso 1 jarj",
            "dataType": "string",
            "sourceColumn": "Koulutusala, taso 1 jarj",
            "sourceProviderType": "Char"
          },
          {
            "name": "Koulutusala, taso 2 jarj",
            "dataType": "string",
            "sourceColumn": "Koulutusala, taso 2 jarj",
            "sourceProviderType": "Char"
          },
          {
            "name": "Koulutusala, taso 3 jarj",
            "dataType": "string",
            "sourceColumn": "Koulutusala, taso 3 jarj",
            "sourceProviderType": "Char"
          },
          {
            "name": "Opintopisteet summa",
            "dataType": "int64",
            "sourceColumn": "Opintopisteet summa",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Opintopisteryhmä1",
            "dataType": "string",
            "sourceColumn": "op suorittanut ryhmä",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Opintopisteryhmä",
            "dataType": "string",
            "sourceColumn": "Opintopisteryhmä",
            "sortByColumn": "Opintopisteryhmä jarj",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Opintopisteet summa jarj",
            "dataType": "string",
            "sourceColumn": "Opintopisteet summa jarj"
          },
          {
            "name": "Opintopisteryhmä jarj",
            "dataType": "string",
            "sourceColumn": "Opintopisteryhmä jarj"
          },
          {
            "name": "Ikä jarj",
            "dataType": "string",
            "sourceColumn": "Ikä jarj"
          },
          {
            "name": "Ikäryhmä jarj",
            "dataType": "string",
            "sourceColumn": "Ikäryhmä jarj"
          }
        ],
        "partitions": [
          {
            "name": "Muuttujat",
            "dataView": "full",
            "source": {
              "query": " SELECT [dw].[v_virta_otp_55_kuluva_lukuvuosi].* FROM [dw].[v_virta_otp_55_kuluva_lukuvuosi] ",
              "dataSource": "SqlServer dwitvipusql22.csc.fi ANTERO"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tilastovuosi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>86</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Lukuvuosi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>77</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>lo_aloituspvm</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>95</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>oo_aloituspvm</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>99</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Aika aloittamisesta</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>119</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Henkilo_koodi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>95</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Sukupuoli</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>75</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>uusi_opisk</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>79</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Aloittanut keväällä</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>119</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Olo syksy</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>76</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Olo kevät</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>76</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Lasna</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>58</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Suorittanut55</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>96</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Opintopisteet syksy</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>125</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Opintopisteet kevät</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>125</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Sektori</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>63</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Korkeakoulu</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>88</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tutkintokoodi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>94</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tutkinto</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>69</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>OKM ohjauksen ala</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>121</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusaste, taso 1</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>129</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusaste, taso 2</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>129</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusala, taso 1</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>122</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusala, taso 2</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>122</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusala, taso 3</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>122</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>suorittanut_27</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>101</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>suorittanut_55_ilman_pankkia</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>173</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>suorittanut_55_pankin_avulla</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>172</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Ikä</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>45</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Ikäryhmä</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>75</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Opintopisteet summa</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>131</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>op suorittanut ryhmä</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>131</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>OKM ohjauksen ala jarj</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>140</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusaste, taso 1 jarj</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>199</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusaste, taso 2 jarj</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>148</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusala, taso 1 jarj</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>141</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusala, taso 2 jarj</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>141</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusala, taso 3 jarj</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>141</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Opintopisteryhmä</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>164</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Opintopisteet summa jarj</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>200</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Opintopisteryhmä jarj</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>198</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Ikä jarj</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>64</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Ikäryhmä jarj</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>94</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tilastovuosi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Lukuvuosi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>lo_aloituspvm</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>oo_aloituspvm</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Aika aloittamisesta</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Henkilo_koodi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>5</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Sukupuoli</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>6</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>uusi_opisk</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>7</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Aloittanut keväällä</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>8</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Olo syksy</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>9</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Olo kevät</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>10</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Lasna</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>11</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Suorittanut55</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>12</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Opintopisteet syksy</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>13</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Opintopisteet kevät</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>14</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Sektori</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>15</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Korkeakoulu</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>16</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tutkintokoodi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>17</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tutkinto</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>18</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>OKM ohjauksen ala</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>19</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusaste, taso 1</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>20</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusaste, taso 2</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>21</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusala, taso 1</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>22</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusala, taso 2</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>23</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusala, taso 3</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>24</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>suorittanut_27</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>25</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>suorittanut_55_ilman_pankkia</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>26</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>suorittanut_55_pankin_avulla</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>27</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Ikä</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>28</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Ikäryhmä</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>29</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Opintopisteet summa</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>30</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>op suorittanut ryhmä</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>31</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>OKM ohjauksen ala jarj</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>32</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusaste, taso 1 jarj</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>33</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusaste, taso 2 jarj</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>34</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusala, taso 1 jarj</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>35</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusala, taso 2 jarj</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>36</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusala, taso 3 jarj</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>37</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Opintopisteryhmä</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>38</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Opintopisteet summa jarj</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>39</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Opintopisteryhmä jarj</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>40</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Ikä jarj</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>41</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Ikäryhmä jarj</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>42</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Opintopisteet summa</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>op suorittanut ryhmä</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Opintopisteryhmä</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Opintopisteet summa jarj</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Opintopisteryhmä jarj</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Ikä jarj</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Ikäryhmä jarj</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Väh. 55 op suorittaneet",
            "expression": [
              "",
              "var lkm = CALCULATE(DISTINCTCOUNT([Henkilo_koodi]),Muuttujat[Suorittanut55]=1)",
              "return IF(lkm = 0, BLANK(), IF(lkm < 5, \"1-4\", MROUND(lkm, 3)))"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Väh. 55 op suorittaneet, rahoitusmalli",
            "expression": [
              "",
              "var lkm = [Väh. 55 op suorittaneet]-[Keväällä aloittaneista väh. 27 op suorittaneet]/2",
              "return IF(lkm = 0, BLANK(), IF(lkm < 5, \"1-4\", MROUND(lkm, 3)))"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Keväällä aloittaneista väh. 27 op suorittaneet",
            "expression": [
              "",
              "var lkm = CALCULATE(DISTINCTCOUNT([Henkilo_koodi]),Muuttujat[suorittanut_27]=1)",
              "return IF(lkm = 0, BLANK(), IF(lkm < 5, \"1-4\", MROUND(lkm, 3)))"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Suorittanut 55 op ilman pankkia",
            "expression": [
              "",
              "var lkm = calculate(DISTINCTCOUNT([Henkilo_koodi]),Muuttujat[suorittanut_55_ilman_pankkia]=1)",
              "return IF(lkm = 0, BLANK(), IF(lkm < 5, \"1-4\", MROUND(lkm, 3)))"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Suorittanut 55 op pankin kanssa",
            "expression": [
              "",
              "var lkm = CALCULATE(DISTINCTCOUNT([Henkilo_koodi]),Muuttujat[suorittanut_55_pankin_avulla]=1)",
              "return IF(lkm = 0, BLANK(), IF(lkm < 5, \"1-4\", MROUND(lkm, 3)))"
            ],
            "formatString": "#,0"
          },
          {
            "name": "55 op suorittaneiden osuus",
            "expression": [
              "",
              "var osa = [Väh. 55 op suorittaneet]",
              "var kaikki = [Läsnäolleet]",
              "return IF(osa = BLANK(), BLANK(),",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, 0,",
              "CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))"
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %"
          },
          {
            "name": "Suorittaneet lkm yht",
            "expression": "[1-14 op]+[15-29 op suorittaneet]+[30-44 op suorittaneet]+[45-59 op suorittaneet]+[60-74 op suorittaneet]+[75-89 op suorittaneet]+[90-104 op suorittaneet]+[105-119 op suorittaneet]+[yli 120 op suorittaneet]",
            "formatString": "#,0"
          },
          {
            "name": "15-29 op suorittaneiden osuus läsnäolleista",
            "expression": [
              "",
              "var osa = [15-29 op suorittaneet]",
              "var kaikki = [Läsnäolleet]",
              "return IF(osa = BLANK(), BLANK(),",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, 0,",
              "CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))"
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %"
          },
          {
            "name": "30-44 op suorittaneiden osuus läsnäolleista",
            "expression": [
              "",
              "var osa = [30-44 op suorittaneet]",
              "var kaikki = [Läsnäolleet]",
              "return IF(osa = BLANK(), BLANK(),",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, 0,",
              "CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))"
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %"
          },
          {
            "name": "45-59 op suorittaneiden osuus läsnäolleista",
            "expression": [
              "",
              "var osa = [45-59 op suorittaneet]",
              "var kaikki = [Läsnäolleet]",
              "return IF(osa = BLANK(), BLANK(),",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, 0,",
              "CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))"
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %"
          },
          {
            "name": "60-74 op suorittaneiden osuus läsnäolleista",
            "expression": [
              "",
              "var osa = [60-74 op suorittaneet]",
              "var kaikki = [Läsnäolleet]",
              "return IF(osa = BLANK(), BLANK(),",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, 0,",
              "CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))"
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %"
          },
          {
            "name": "75-89 op suorittaneiden osuus läsnäolleista",
            "expression": [
              "",
              "var osa = [75-89 op suorittaneet]",
              "var kaikki = [Läsnäolleet]",
              "return IF(osa = BLANK(), BLANK(),",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, 0,",
              "CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))"
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %"
          },
          {
            "name": "90-104 op suorittaneiden osuus läsnäolleista",
            "expression": [
              "",
              "var osa = [90-104 op suorittaneet]",
              "var kaikki = [Läsnäolleet]",
              "return IF(osa = BLANK(), BLANK(),",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, 0,",
              "CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))"
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %"
          },
          {
            "name": "105-119 op suorittaneiden osuus läsnäolleista",
            "expression": [
              "",
              "var osa = [105-119 op suorittaneet]",
              "var kaikki = [Läsnäolleet]",
              "return IF(osa = BLANK(), BLANK(),",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, 0,",
              "CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))"
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %"
          },
          {
            "name": "yli 120 op suorittaneiden osuus läsnäolleista",
            "expression": [
              "",
              "var osa = [yli 120 op suorittaneet]",
              "var kaikki = [Läsnäolleet]",
              "return IF(osa = BLANK(), BLANK(),",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, 0,",
              "CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))"
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %"
          },
          {
            "name": "1-14 op suorittaneiden osuus 55 op suorittaneet",
            "expression": [
              "",
              "var osa = [1-14 op suorittaneet]",
              "var kaikki = [Väh. 55 op suorittaneet]",
              "return IF(osa = BLANK(), BLANK(),",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, 0,",
              "CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))"
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %"
          },
          {
            "name": "15-29 op suorittaneiden osuus 55 op suorittaneet",
            "expression": [
              "",
              "var osa = [15-29 op suorittaneet]",
              "var kaikki = [Väh. 55 op suorittaneet]",
              "return IF(osa = BLANK(), BLANK(),",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, 0,",
              "CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))"
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %"
          },
          {
            "name": "30-44 op suorittaneiden osuus 55 op suorittaneet",
            "expression": [
              "",
              "var osa = [30-44 op suorittaneet]",
              "var kaikki = [Väh. 55 op suorittaneet]",
              "return IF(osa = BLANK(), BLANK(),",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, 0,",
              "CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))"
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %"
          },
          {
            "name": "45-59 op suorittaneiden osuus 55 op suorittaneet",
            "expression": [
              "",
              "var osa = [45-59 op suorittaneet]",
              "var kaikki = [Väh. 55 op suorittaneet]",
              "return IF(osa = BLANK(), BLANK(),",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, 0,",
              "CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))"
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %"
          },
          {
            "name": "60-74 op suorittaneiden osuus 55 op suorittaneet",
            "expression": [
              "",
              "var osa = [60-74 op suorittaneet]",
              "var kaikki = [Väh. 55 op suorittaneet]",
              "return IF(osa = BLANK(), BLANK(),",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, 0,",
              "CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))"
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %"
          },
          {
            "name": "75-89 op suorittaneiden osuus 55 op suorittaneet",
            "expression": [
              "",
              "var osa = [75-89 op suorittaneet]",
              "var kaikki = [Väh. 55 op suorittaneet]",
              "return IF(osa = BLANK(), BLANK(),",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, 0,",
              "CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))"
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %"
          },
          {
            "name": "90-104 op suorittaneiden osuus 55 op suorittaneet",
            "expression": [
              "",
              "var osa = [90-104 op suorittaneet]",
              "var kaikki = [Väh. 55 op suorittaneet]",
              "return IF(osa = BLANK(), BLANK(),",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, 0,",
              "CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))"
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %"
          },
          {
            "name": "105-119 op suorittaneiden osuus 55 op suorittaneet",
            "expression": [
              "",
              "var osa = [105-119 op suorittaneet]",
              "var kaikki = [Väh. 55 op suorittaneet]",
              "return IF(osa = BLANK(), BLANK(),",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, 0,",
              "CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))"
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %"
          },
          {
            "name": "yli 120 op suorittaneiden osuus 55 op suorittaneet",
            "expression": [
              "",
              "var osa = [yli 120 op suorittaneet]",
              "var kaikki = [Väh. 55 op suorittaneet]",
              "return IF(osa = BLANK(), BLANK(),",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, 0,",
              "CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))"
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %"
          },
          {
            "name": "1-54 op suorittaneiden osuus läsnäolleista",
            "expression": [
              "",
              "var osa = [1-54 op suorittaneet]",
              "var kaikki = [Läsnäolleet]",
              "return IF(osa = BLANK(), BLANK(),",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, 0,",
              "CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))"
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %"
          },
          {
            "name": "vähintään 55 op suorittaneiden osuus läsnäolleista",
            "expression": [
              "",
              "var osa = [vähintään 55 op suorittaneet]",
              "var kaikki = [Läsnäolleet]",
              "return IF(osa = BLANK(), BLANK(),",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, 0,",
              "CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))"
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %"
          },
          {
            "name": "0 op suorittaneiden osuus läsnäolleista",
            "expression": [
              "",
              "var osa = [0 op suorittaneet]",
              "var kaikki = [Läsnäolleet]",
              "return IF(osa = BLANK(), BLANK(),",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, 0,",
              "CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))"
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %"
          },
          {
            "name": "1-14 op suorittaneiden osuus läsnäolleista",
            "expression": [
              "",
              "var osa = [1-14 op suorittaneet]",
              "var kaikki = [Läsnäolleet]",
              "return IF(osa = BLANK(), BLANK(),",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, 0,",
              "CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))"
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %"
          },
          {
            "name": "1-14 op suorittaneet",
            "expression": [
              "",
              "var minop = 1",
              "var maxop = 14",
              "var lkm = if(hasonevalue(Lukukausi[id]),switch(firstnonblank(Lukukausi[id],true()),",
              "2,calculate(DISTINCTCOUNT([Henkilo_koodi]),Muuttujat[Opintopisteet kevät]>=minop && Muuttujat[Opintopisteet kevät]<=maxop),",
              "1,calculate(DISTINCTCOUNT([Henkilo_koodi]),Muuttujat[Opintopisteet syksy]>=minop && Muuttujat[Opintopisteet syksy]<=maxop)),",
              "calculate(DISTINCTCOUNT([Henkilo_koodi]),Muuttujat[Opintopisteet summa]>=minop && Muuttujat[Opintopisteet summa]<=maxop))",
              "return IF(lkm = 0, BLANK(), IF(lkm < 5, \"1-4\", MROUND(lkm, 3)))"
            ],
            "formatString": "#,0"
          },
          {
            "name": "15-29 op suorittaneet",
            "expression": [
              "",
              "var minop = 15",
              "var maxop = 29",
              "var lkm = if(hasonevalue(Lukukausi[id]),switch(firstnonblank(Lukukausi[id],true()),",
              "2,calculate(DISTINCTCOUNT([Henkilo_koodi]),Muuttujat[Opintopisteet kevät]>=minop && Muuttujat[Opintopisteet kevät]<=maxop),",
              "1,calculate(DISTINCTCOUNT([Henkilo_koodi]),Muuttujat[Opintopisteet syksy]>=minop && Muuttujat[Opintopisteet syksy]<=maxop)),",
              "calculate(DISTINCTCOUNT([Henkilo_koodi]),Muuttujat[Opintopisteet summa]>=minop && Muuttujat[Opintopisteet summa]<=maxop))",
              "return IF(lkm = 0, BLANK(), IF(lkm < 5, \"1-4\", MROUND(lkm, 3)))"
            ],
            "formatString": "#,0"
          },
          {
            "name": "30-44 op suorittaneet",
            "expression": [
              "",
              "var minop = 30",
              "var maxop = 44",
              "var lkm = if(hasonevalue(Lukukausi[id]),switch(firstnonblank(Lukukausi[id],true()),",
              "2,calculate(DISTINCTCOUNT([Henkilo_koodi]),Muuttujat[Opintopisteet kevät]>=minop && Muuttujat[Opintopisteet kevät]<=maxop),",
              "1,calculate(DISTINCTCOUNT([Henkilo_koodi]),Muuttujat[Opintopisteet syksy]>=minop && Muuttujat[Opintopisteet syksy]<=maxop)),",
              "calculate(DISTINCTCOUNT([Henkilo_koodi]),Muuttujat[Opintopisteet summa]>=minop && Muuttujat[Opintopisteet summa]<=maxop))",
              "return IF(lkm = 0, BLANK(), IF(lkm < 5, \"1-4\", MROUND(lkm, 3)))"
            ],
            "formatString": "#,0"
          },
          {
            "name": "45-59 op suorittaneet",
            "expression": [
              "",
              "var minop = 45",
              "var maxop = 59",
              "var lkm = if(hasonevalue(Lukukausi[id]),switch(firstnonblank(Lukukausi[id],true()),",
              "2,calculate(DISTINCTCOUNT([Henkilo_koodi]),Muuttujat[Opintopisteet kevät]>=minop && Muuttujat[Opintopisteet kevät]<=maxop),",
              "1,calculate(DISTINCTCOUNT([Henkilo_koodi]),Muuttujat[Opintopisteet syksy]>=minop && Muuttujat[Opintopisteet syksy]<=maxop)),",
              "calculate(DISTINCTCOUNT([Henkilo_koodi]),Muuttujat[Opintopisteet summa]>=minop && Muuttujat[Opintopisteet summa]<=maxop))",
              "return IF(lkm = 0, BLANK(), IF(lkm < 5, \"1-4\", MROUND(lkm, 3)))"
            ],
            "formatString": "#,0"
          },
          {
            "name": "60-74 op suorittaneet",
            "expression": [
              "",
              "var minop = 60",
              "var maxop = 74",
              "var lkm = if(hasonevalue(Lukukausi[id]),switch(firstnonblank(Lukukausi[id],true()),",
              "2,calculate(DISTINCTCOUNT([Henkilo_koodi]),Muuttujat[Opintopisteet kevät]>=minop && Muuttujat[Opintopisteet kevät]<=maxop),",
              "1,calculate(DISTINCTCOUNT([Henkilo_koodi]),Muuttujat[Opintopisteet syksy]>=minop && Muuttujat[Opintopisteet syksy]<=maxop)),",
              "calculate(DISTINCTCOUNT([Henkilo_koodi]),Muuttujat[Opintopisteet summa]>=minop && Muuttujat[Opintopisteet summa]<=maxop))",
              "return IF(lkm = 0, BLANK(), IF(lkm < 5, \"1-4\", MROUND(lkm, 3)))"
            ],
            "formatString": "#,0"
          },
          {
            "name": "75-89 op suorittaneet",
            "expression": [
              "",
              "var minop = 75",
              "var maxop = 89",
              "var lkm = if(hasonevalue(Lukukausi[id]),switch(firstnonblank(Lukukausi[id],true()),",
              "2,calculate(DISTINCTCOUNT([Henkilo_koodi]),Muuttujat[Opintopisteet kevät]>=minop && Muuttujat[Opintopisteet kevät]<=maxop),",
              "1,calculate(DISTINCTCOUNT([Henkilo_koodi]),Muuttujat[Opintopisteet syksy]>=minop && Muuttujat[Opintopisteet syksy]<=maxop)),",
              "calculate(DISTINCTCOUNT([Henkilo_koodi]),Muuttujat[Opintopisteet summa]>=minop && Muuttujat[Opintopisteet summa]<=maxop))",
              "return IF(lkm = 0, BLANK(), IF(lkm < 5, \"1-4\", MROUND(lkm, 3)))"
            ],
            "formatString": "#,0"
          },
          {
            "name": "90-104 op suorittaneet",
            "expression": [
              "",
              "var minop = 90",
              "var maxop = 104",
              "var lkm = if(hasonevalue(Lukukausi[id]),switch(firstnonblank(Lukukausi[id],true()),",
              "2,calculate(DISTINCTCOUNT([Henkilo_koodi]),Muuttujat[Opintopisteet kevät]>=minop && Muuttujat[Opintopisteet kevät]<=maxop),",
              "1,calculate(DISTINCTCOUNT([Henkilo_koodi]),Muuttujat[Opintopisteet syksy]>=minop && Muuttujat[Opintopisteet syksy]<=maxop)),",
              "calculate(DISTINCTCOUNT([Henkilo_koodi]),Muuttujat[Opintopisteet summa]>=minop && Muuttujat[Opintopisteet summa]<=maxop))",
              "return IF(lkm = 0, BLANK(), IF(lkm < 5, \"1-4\", MROUND(lkm, 3)))"
            ],
            "formatString": "#,0"
          },
          {
            "name": "105-119 op suorittaneet",
            "expression": [
              "",
              "var minop = 105",
              "var maxop = 119",
              "var lkm = if(hasonevalue(Lukukausi[id]),switch(firstnonblank(Lukukausi[id],true()),",
              "2,calculate(DISTINCTCOUNT([Henkilo_koodi]),Muuttujat[Opintopisteet kevät]>=minop && Muuttujat[Opintopisteet kevät]<=maxop),",
              "1,calculate(DISTINCTCOUNT([Henkilo_koodi]),Muuttujat[Opintopisteet syksy]>=minop && Muuttujat[Opintopisteet syksy]<=maxop)),",
              "calculate(DISTINCTCOUNT([Henkilo_koodi]),Muuttujat[Opintopisteet summa]>=minop && Muuttujat[Opintopisteet summa]<=maxop))",
              "return IF(lkm = 0, BLANK(), IF(lkm < 5, \"1-4\", MROUND(lkm, 3)))"
            ],
            "formatString": "#,0"
          },
          {
            "name": "yli 120 op suorittaneet",
            "expression": [
              "",
              "var lkm = if(hasonevalue(Lukukausi[id]),switch(firstnonblank(Lukukausi[id],true()),",
              "2,calculate(DISTINCTCOUNT([Henkilo_koodi]),Muuttujat[Opintopisteet kevät]>=120),",
              "1,calculate(DISTINCTCOUNT([Henkilo_koodi]),Muuttujat[Opintopisteet syksy]>=120)),",
              "calculate(DISTINCTCOUNT([Henkilo_koodi]),Muuttujat[Opintopisteet summa]>=120))",
              "return IF(lkm = 0, BLANK(), IF(lkm < 5, \"1-4\", MROUND(lkm, 3)))"
            ],
            "formatString": "#,0"
          },
          {
            "name": "0 op suorittaneet",
            "expression": [
              "",
              "var lkm = if(hasonevalue(Lukukausi[id]),switch(firstnonblank(Lukukausi[id],true()),",
              "2,calculate(DISTINCTCOUNT([Henkilo_koodi]),Muuttujat[Opintopisteet kevät]=0,Muuttujat[Olo kevät]=1),",
              "1,calculate(DISTINCTCOUNT([Henkilo_koodi]),Muuttujat[Opintopisteet syksy]=0,Muuttujat[Olo syksy]=1)),",
              "calculate(DISTINCTCOUNT([Henkilo_koodi]),Muuttujat[Opintopisteet summa]=0,Muuttujat[Lasna]=1))",
              "return IF(lkm = 0, BLANK(), IF(lkm < 5, \"1-4\", MROUND(lkm, 3)))"
            ],
            "formatString": "#,0"
          },
          {
            "name": "1-54 op suorittaneet",
            "expression": [
              "",
              "var minop = 1",
              "var maxop = 54",
              "var lkm = if(hasonevalue(Lukukausi[id]),switch(firstnonblank(Lukukausi[id],true()),",
              "2,calculate(DISTINCTCOUNT([Henkilo_koodi]),Muuttujat[Opintopisteet kevät]>=minop && Muuttujat[Opintopisteet kevät]<=maxop),",
              "1,calculate(DISTINCTCOUNT([Henkilo_koodi]),Muuttujat[Opintopisteet syksy]>=minop && Muuttujat[Opintopisteet syksy]<=maxop)),",
              "calculate(DISTINCTCOUNT([Henkilo_koodi]),Muuttujat[Opintopisteet summa]>=minop && Muuttujat[Opintopisteet summa]<=maxop))",
              "return IF(lkm = 0, BLANK(), IF(lkm < 5, \"1-4\", MROUND(lkm, 3)))"
            ],
            "formatString": "#,0"
          },
          {
            "name": "vähintään 55 op suorittaneet",
            "expression": [
              "",
              "var lkm = if(hasonevalue(Lukukausi[id]),switch(firstnonblank(Lukukausi[id],true()),",
              "2,calculate(DISTINCTCOUNT([Henkilo_koodi]),Muuttujat[Opintopisteet kevät]>=55),",
              "1,calculate(DISTINCTCOUNT([Henkilo_koodi]),Muuttujat[Opintopisteet syksy]>=55)),",
              "calculate(DISTINCTCOUNT([Henkilo_koodi]),Muuttujat[Opintopisteet summa]>=55))",
              "return IF(lkm = 0, BLANK(), IF(lkm < 5, \"1-4\", MROUND(lkm, 3)))"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Läsnäolleet",
            "expression": [
              "",
              "var lkm = if(hasonevalue(Lukukausi[id]),switch(firstnonblank(Lukukausi[id],true()),",
              "2,calculate(DISTINCTCOUNT([Henkilo_koodi]),Muuttujat[Olo kevät]=1),",
              "1,calculate(DISTINCTCOUNT([Henkilo_koodi]),Muuttujat[Olo syksy]=1)),",
              "calculate(DISTINCTCOUNT([Henkilo_koodi]),Muuttujat[Lasna]=1))",
              "return IF(lkm = 0, BLANK(), IF(lkm < 5, \"1-4\", MROUND(lkm, 3)))"
            ],
            "formatString": "#,0"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dw].[v_virta_otp_55_kuluva_lukuvuosi].* FROM [dw].[v_virta_otp_55_kuluva_lukuvuosi] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "v_virta_otp_55_kuluva_lukuvuosi"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dw"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Tilastovuosi</string>",
              "      </key>",
              "      <value>",
              "        <int>86</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Lukuvuosi</string>",
              "      </key>",
              "      <value>",
              "        <int>77</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>lo_aloituspvm</string>",
              "      </key>",
              "      <value>",
              "        <int>95</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>oo_aloituspvm</string>",
              "      </key>",
              "      <value>",
              "        <int>99</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Aika aloittamisesta</string>",
              "      </key>",
              "      <value>",
              "        <int>119</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Henkilo_koodi</string>",
              "      </key>",
              "      <value>",
              "        <int>95</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Sukupuoli</string>",
              "      </key>",
              "      <value>",
              "        <int>75</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>uusi_opisk</string>",
              "      </key>",
              "      <value>",
              "        <int>79</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Aloittanut keväällä</string>",
              "      </key>",
              "      <value>",
              "        <int>119</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Olo syksy</string>",
              "      </key>",
              "      <value>",
              "        <int>76</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Olo kevät</string>",
              "      </key>",
              "      <value>",
              "        <int>76</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Lasna</string>",
              "      </key>",
              "      <value>",
              "        <int>58</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Suorittanut55</string>",
              "      </key>",
              "      <value>",
              "        <int>96</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Opintopisteet syksy</string>",
              "      </key>",
              "      <value>",
              "        <int>125</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Opintopisteet kevät</string>",
              "      </key>",
              "      <value>",
              "        <int>125</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Sektori</string>",
              "      </key>",
              "      <value>",
              "        <int>63</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Korkeakoulu</string>",
              "      </key>",
              "      <value>",
              "        <int>88</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tutkintokoodi</string>",
              "      </key>",
              "      <value>",
              "        <int>94</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tutkinto</string>",
              "      </key>",
              "      <value>",
              "        <int>69</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>OKM ohjauksen ala</string>",
              "      </key>",
              "      <value>",
              "        <int>121</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusaste, taso 1</string>",
              "      </key>",
              "      <value>",
              "        <int>129</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusaste, taso 2</string>",
              "      </key>",
              "      <value>",
              "        <int>129</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusala, taso 1</string>",
              "      </key>",
              "      <value>",
              "        <int>122</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusala, taso 2</string>",
              "      </key>",
              "      <value>",
              "        <int>122</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusala, taso 3</string>",
              "      </key>",
              "      <value>",
              "        <int>122</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>suorittanut_27</string>",
              "      </key>",
              "      <value>",
              "        <int>101</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>suorittanut_55_ilman_pankkia</string>",
              "      </key>",
              "      <value>",
              "        <int>173</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>suorittanut_55_pankin_avulla</string>",
              "      </key>",
              "      <value>",
              "        <int>172</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ikä</string>",
              "      </key>",
              "      <value>",
              "        <int>45</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ikäryhmä</string>",
              "      </key>",
              "      <value>",
              "        <int>75</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Opintopisteet summa</string>",
              "      </key>",
              "      <value>",
              "        <int>131</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>op suorittanut ryhmä</string>",
              "      </key>",
              "      <value>",
              "        <int>131</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>OKM ohjauksen ala jarj</string>",
              "      </key>",
              "      <value>",
              "        <int>140</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusaste, taso 1 jarj</string>",
              "      </key>",
              "      <value>",
              "        <int>199</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusaste, taso 2 jarj</string>",
              "      </key>",
              "      <value>",
              "        <int>148</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusala, taso 1 jarj</string>",
              "      </key>",
              "      <value>",
              "        <int>141</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusala, taso 2 jarj</string>",
              "      </key>",
              "      <value>",
              "        <int>141</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusala, taso 3 jarj</string>",
              "      </key>",
              "      <value>",
              "        <int>141</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Opintopisteryhmä</string>",
              "      </key>",
              "      <value>",
              "        <int>164</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Opintopisteet summa jarj</string>",
              "      </key>",
              "      <value>",
              "        <int>200</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Opintopisteryhmä jarj</string>",
              "      </key>",
              "      <value>",
              "        <int>198</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ikä jarj</string>",
              "      </key>",
              "      <value>",
              "        <int>64</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ikäryhmä jarj</string>",
              "      </key>",
              "      <value>",
              "        <int>94</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Tilastovuosi</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Lukuvuosi</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>lo_aloituspvm</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>oo_aloituspvm</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Aika aloittamisesta</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Henkilo_koodi</string>",
              "      </key>",
              "      <value>",
              "        <int>5</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Sukupuoli</string>",
              "      </key>",
              "      <value>",
              "        <int>6</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>uusi_opisk</string>",
              "      </key>",
              "      <value>",
              "        <int>7</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Aloittanut keväällä</string>",
              "      </key>",
              "      <value>",
              "        <int>8</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Olo syksy</string>",
              "      </key>",
              "      <value>",
              "        <int>9</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Olo kevät</string>",
              "      </key>",
              "      <value>",
              "        <int>10</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Lasna</string>",
              "      </key>",
              "      <value>",
              "        <int>11</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Suorittanut55</string>",
              "      </key>",
              "      <value>",
              "        <int>12</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Opintopisteet syksy</string>",
              "      </key>",
              "      <value>",
              "        <int>13</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Opintopisteet kevät</string>",
              "      </key>",
              "      <value>",
              "        <int>14</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Sektori</string>",
              "      </key>",
              "      <value>",
              "        <int>15</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Korkeakoulu</string>",
              "      </key>",
              "      <value>",
              "        <int>16</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tutkintokoodi</string>",
              "      </key>",
              "      <value>",
              "        <int>17</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tutkinto</string>",
              "      </key>",
              "      <value>",
              "        <int>18</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>OKM ohjauksen ala</string>",
              "      </key>",
              "      <value>",
              "        <int>19</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusaste, taso 1</string>",
              "      </key>",
              "      <value>",
              "        <int>20</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusaste, taso 2</string>",
              "      </key>",
              "      <value>",
              "        <int>21</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusala, taso 1</string>",
              "      </key>",
              "      <value>",
              "        <int>22</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusala, taso 2</string>",
              "      </key>",
              "      <value>",
              "        <int>23</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusala, taso 3</string>",
              "      </key>",
              "      <value>",
              "        <int>24</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>suorittanut_27</string>",
              "      </key>",
              "      <value>",
              "        <int>25</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>suorittanut_55_ilman_pankkia</string>",
              "      </key>",
              "      <value>",
              "        <int>26</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>suorittanut_55_pankin_avulla</string>",
              "      </key>",
              "      <value>",
              "        <int>27</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ikä</string>",
              "      </key>",
              "      <value>",
              "        <int>28</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ikäryhmä</string>",
              "      </key>",
              "      <value>",
              "        <int>29</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Opintopisteet summa</string>",
              "      </key>",
              "      <value>",
              "        <int>30</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>op suorittanut ryhmä</string>",
              "      </key>",
              "      <value>",
              "        <int>31</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>OKM ohjauksen ala jarj</string>",
              "      </key>",
              "      <value>",
              "        <int>32</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusaste, taso 1 jarj</string>",
              "      </key>",
              "      <value>",
              "        <int>33</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusaste, taso 2 jarj</string>",
              "      </key>",
              "      <value>",
              "        <int>34</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusala, taso 1 jarj</string>",
              "      </key>",
              "      <value>",
              "        <int>35</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusala, taso 2 jarj</string>",
              "      </key>",
              "      <value>",
              "        <int>36</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusala, taso 3 jarj</string>",
              "      </key>",
              "      <value>",
              "        <int>37</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Opintopisteryhmä</string>",
              "      </key>",
              "      <value>",
              "        <int>38</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Opintopisteet summa jarj</string>",
              "      </key>",
              "      <value>",
              "        <int>39</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Opintopisteryhmä jarj</string>",
              "      </key>",
              "      <value>",
              "        <int>40</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ikä jarj</string>",
              "      </key>",
              "      <value>",
              "        <int>41</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ikäryhmä jarj</string>",
              "      </key>",
              "      <value>",
              "        <int>42</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Opintopisteet summa</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>op suorittanut ryhmä</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Opintopisteryhmä</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Opintopisteet summa jarj</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Opintopisteryhmä jarj</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ikä jarj</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ikäryhmä jarj</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Lukukausi",
        "columns": [
          {
            "name": "id",
            "dataType": "int64",
            "sourceColumn": "id",
            "sourceProviderType": "BigInt"
          },
          {
            "name": "Lukukausi",
            "dataType": "string",
            "sourceColumn": "lukukausi_fi",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Lukukausi",
            "dataView": "full",
            "source": {
              "query": " SELECT [dw].[d_lukukausi].[id],[dw].[d_lukukausi].[lukukausi_fi] FROM [dw].[d_lukukausi] ",
              "dataSource": "SqlServer dwitvipusql22 antero"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>id</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>45</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>lukukausi_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>104</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>lukukausi_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>112</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>lukukausi_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>113</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarjestys_lukukausi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>150</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>loadtime</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>86</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>source</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>76</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>username</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>95</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>id</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>lukukausi_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>lukukausi_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>lukukausi_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarjestys_lukukausi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>loadtime</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>5</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>source</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>6</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>username</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>7</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>lukukausi_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>lukukausi_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarjestys_lukukausi</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>loadtime</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>source</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>username</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dw].[d_lukukausi].[id],[dw].[d_lukukausi].[lukukausi_fi] FROM [dw].[d_lukukausi] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "d_lukukausi"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dw"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>id</string>",
              "      </key>",
              "      <value>",
              "        <int>45</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>lukukausi_fi</string>",
              "      </key>",
              "      <value>",
              "        <int>104</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>lukukausi_sv</string>",
              "      </key>",
              "      <value>",
              "        <int>112</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>lukukausi_en</string>",
              "      </key>",
              "      <value>",
              "        <int>113</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarjestys_lukukausi</string>",
              "      </key>",
              "      <value>",
              "        <int>150</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>loadtime</string>",
              "      </key>",
              "      <value>",
              "        <int>86</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>source</string>",
              "      </key>",
              "      <value>",
              "        <int>76</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>username</string>",
              "      </key>",
              "      <value>",
              "        <int>95</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>id</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>lukukausi_fi</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>lukukausi_sv</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>lukukausi_en</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarjestys_lukukausi</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>loadtime</string>",
              "      </key>",
              "      <value>",
              "        <int>5</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>source</string>",
              "      </key>",
              "      <value>",
              "        <int>6</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>username</string>",
              "      </key>",
              "      <value>",
              "        <int>7</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>lukukausi_en</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>lukukausi_sv</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarjestys_lukukausi</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>loadtime</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>source</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>username</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      }
    ],
    "perspectives": [
      {
        "name": "Perus",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Aika aloittamisesta"
              },
              {
                "name": "Aloittanut keväällä"
              },
              {
                "name": "Ikä"
              },
              {
                "name": "Ikäryhmä"
              },
              {
                "name": "Korkeakoulu"
              },
              {
                "name": "Koulutusala, taso 1"
              },
              {
                "name": "Koulutusala, taso 2"
              },
              {
                "name": "Koulutusala, taso 3"
              },
              {
                "name": "Koulutusaste, taso 1"
              },
              {
                "name": "Koulutusaste, taso 2"
              },
              {
                "name": "Lukuvuosi"
              },
              {
                "name": "OKM ohjauksen ala"
              },
              {
                "name": "Sektori"
              },
              {
                "name": "Sukupuoli"
              },
              {
                "name": "Tutkinto"
              },
              {
                "name": "Tutkintokoodi"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Opintopisteet summa"
              },
              {
                "name": "Opintopisteryhmä"
              }
            ],
            "measures": [
              {
                "name": "Väh. 55 op suorittaneet"
              },
              {
                "name": "Väh. 55 op suorittaneet, rahoitusmalli"
              },
              {
                "name": "Keväällä aloittaneista väh. 27 op suorittaneet"
              },
              {
                "name": "Suorittanut 55 op ilman pankkia"
              },
              {
                "name": "Suorittanut 55 op pankin kanssa"
              },
              {
                "name": "55 op suorittaneiden osuus"
              },
              {
                "name": "15-29 op suorittaneiden osuus läsnäolleista"
              },
              {
                "name": "30-44 op suorittaneiden osuus läsnäolleista"
              },
              {
                "name": "45-59 op suorittaneiden osuus läsnäolleista"
              },
              {
                "name": "60-74 op suorittaneiden osuus läsnäolleista"
              },
              {
                "name": "75-89 op suorittaneiden osuus läsnäolleista"
              },
              {
                "name": "90-104 op suorittaneiden osuus läsnäolleista"
              },
              {
                "name": "105-119 op suorittaneiden osuus läsnäolleista"
              },
              {
                "name": "yli 120 op suorittaneiden osuus läsnäolleista"
              },
              {
                "name": "1-14 op suorittaneiden osuus 55 op suorittaneet"
              },
              {
                "name": "15-29 op suorittaneiden osuus 55 op suorittaneet"
              },
              {
                "name": "30-44 op suorittaneiden osuus 55 op suorittaneet"
              },
              {
                "name": "45-59 op suorittaneiden osuus 55 op suorittaneet"
              },
              {
                "name": "60-74 op suorittaneiden osuus 55 op suorittaneet"
              },
              {
                "name": "75-89 op suorittaneiden osuus 55 op suorittaneet"
              },
              {
                "name": "90-104 op suorittaneiden osuus 55 op suorittaneet"
              },
              {
                "name": "105-119 op suorittaneiden osuus 55 op suorittaneet"
              },
              {
                "name": "yli 120 op suorittaneiden osuus 55 op suorittaneet"
              },
              {
                "name": "1-54 op suorittaneiden osuus läsnäolleista"
              },
              {
                "name": "vähintään 55 op suorittaneiden osuus läsnäolleista"
              },
              {
                "name": "0 op suorittaneiden osuus läsnäolleista"
              },
              {
                "name": "1-14 op suorittaneiden osuus läsnäolleista"
              },
              {
                "name": "1-14 op suorittaneet"
              },
              {
                "name": "15-29 op suorittaneet"
              },
              {
                "name": "30-44 op suorittaneet"
              },
              {
                "name": "45-59 op suorittaneet"
              },
              {
                "name": "60-74 op suorittaneet"
              },
              {
                "name": "75-89 op suorittaneet"
              },
              {
                "name": "90-104 op suorittaneet"
              },
              {
                "name": "105-119 op suorittaneet"
              },
              {
                "name": "yli 120 op suorittaneet"
              },
              {
                "name": "0 op suorittaneet"
              },
              {
                "name": "1-54 op suorittaneet"
              },
              {
                "name": "vähintään 55 op suorittaneet"
              },
              {
                "name": "Läsnäolleet"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          },
          {
            "name": "Lukukausi",
            "columns": [
              {
                "name": "id"
              },
              {
                "name": "Lukukausi"
              }
            ]
          }
        ]
      }
    ],
    "roles": [
      {
        "name": "Luku",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "DWI\\P_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1733"
          },
          {
            "memberName": "DWI\\T_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1732"
          },
          {
            "memberName": "DWI\\ffinnber",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1355"
          },
          {
            "memberName": "NT AUTHORITY\\IUSR",
            "memberId": "S-1-5-17"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "400"
      }
    ]
  },
  "id": "SemanticModel"
}
