{
  "name": "SemanticModel",
  "compatibilityLevel": 1200,
  "model": {
    "culture": "fi-FI",
    "dataSources": [
      {
        "name": "SqlServer dwitestvipusql VipunenTK",
        "connectionString": "Provider=SQLNCLI11;Data Source=dwitvipusql22;Initial Catalog=VipunenTK;Integrated Security=SSPI;Persist Security Info=false",
        "impersonationMode": "impersonateAccount",
        "account": "dwi\\T_VIPUTK_KUUTIO",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "Sarakeleveys",
        "isHidden": true,
        "columns": [
          {
            "name": "Sarakeleveys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Sarakeleveys"
          },
          {
            "name": "leveys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "leveys"
          }
        ],
        "partitions": [
          {
            "name": "Sarakeleveys",
            "source": {
              "query": "SELECT [dbo].[Sarakeleveys].* \t\tFROM [dbo].[Sarakeleveys]",
              "dataSource": "SqlServer dwitestvipusql VipunenTK"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization"
              },
              {
                "name": "TableWidgetSerialization"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Sarakeleveys"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "      SELECT [dbo].[Sarakeleveys].*   FROM [dbo].[Sarakeleveys] "
          }
        ]
      },
      {
        "name": "Muuttujat",
        "columns": [
          {
            "name": "Tilastovuosi",
            "dataType": "string",
            "sourceColumn": "Tilastovuosi"
          },
          {
            "name": "Opetustunnit2",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Opetustunnit2"
          },
          {
            "name": "yli25v2",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "yli25v2"
          },
          {
            "name": "Statistikår",
            "dataType": "string",
            "sourceColumn": "Statistikår"
          },
          {
            "name": "Statistical year",
            "dataType": "string",
            "sourceColumn": "Statistical year"
          },
          {
            "name": "Maakunta jarj",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Maakunta jarj"
          },
          {
            "name": "Maakunta",
            "dataType": "string",
            "sourceColumn": "Maakunta"
          },
          {
            "name": "Kunta",
            "dataType": "string",
            "sourceColumn": "Kunta"
          },
          {
            "name": "Landskap",
            "dataType": "string",
            "sourceColumn": "Landskap"
          },
          {
            "name": "Kommun",
            "dataType": "string",
            "sourceColumn": "Kommun"
          },
          {
            "name": "Region",
            "dataType": "string",
            "sourceColumn": "Region"
          },
          {
            "name": "Municipality",
            "dataType": "string",
            "sourceColumn": "Municipality"
          },
          {
            "name": "Osallistuneet2",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Osallistuneet2"
          }
        ],
        "partitions": [
          {
            "name": "v_f_tab_indikaattorit_vapaa_sivistystyö_väestö",
            "source": {
              "query": "SELECT [dbo].[v_f_tab_indikaattorit_vapaa_sivistystyö_väestö].* \t\tFROM [dbo].[v_f_tab_indikaattorit_vapaa_sivistystyö_väestö]",
              "dataSource": "SqlServer dwitestvipusql VipunenTK"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "&lt;?xml version=\"1.0\" encoding=\"UTF-16\"?&gt;&lt;Gemini xmlns=\"TableWidgetSerialization\"&gt;&lt;AnnotationContent&gt;&lt;![CDATA[&lt;?xml version=\"1.0\"?&gt;",
                  "&lt;TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\"&gt;",
                  "  &lt;ColumnSuggestedType /&gt;",
                  "  &lt;ColumnFormat /&gt;",
                  "  &lt;ColumnAccuracy /&gt;",
                  "  &lt;ColumnCurrencySymbol /&gt;",
                  "  &lt;ColumnPositivePattern /&gt;",
                  "  &lt;ColumnNegativePattern /&gt;",
                  "  &lt;ColumnWidths&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Tilastovuosi&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;86&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Maakunta&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;77&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Kunta&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;58&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Opetustunnit2&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;99&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;yli25v2&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;64&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Statistikår&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;78&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Landskap&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;75&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Kommun&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;70&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Statistical year&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;101&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Region&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;63&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Municipality&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;85&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Maakunta jarj&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;96&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Osallistuneet2&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;98&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "  &lt;/ColumnWidths&gt;",
                  "  &lt;ColumnDisplayIndex&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Tilastovuosi&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;0&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Maakunta&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;1&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Kunta&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;2&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Opetustunnit2&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;3&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;yli25v2&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;4&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Statistikår&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;5&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Landskap&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;6&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Kommun&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;7&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Statistical year&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;8&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Region&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;9&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Municipality&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;10&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Maakunta jarj&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;11&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Osallistuneet2&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;12&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "  &lt;/ColumnDisplayIndex&gt;",
                  "  &lt;ColumnFrozen /&gt;",
                  "  &lt;ColumnChecked&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Maakunta&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Kunta&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Landskap&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Kommun&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Region&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Municipality&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Osallistuneet2&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "  &lt;/ColumnChecked&gt;",
                  "  &lt;ColumnFilter /&gt;",
                  "  &lt;SelectionFilter /&gt;",
                  "  &lt;FilterParameters /&gt;",
                  "  &lt;IsSortDescending&gt;false&lt;/IsSortDescending&gt;",
                  "&lt;/TableWidgetGridSerialization&gt;]]&gt;&lt;/AnnotationContent&gt;&lt;/Gemini&gt;"
                ]
              },
              {
                "name": "TableWidgetSourceTable"
              },
              {
                "name": "QueryEditorSerialization"
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Yli 25 v. väestö",
            "expression": [
              "var lkm = sum([yli25v2])",
              "return IF(lkm = 0, BLANK(), IF(lkm < 5, \"1-4\", MROUND(lkm, 3)))"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Opetustunnit",
            "expression": "sum([Opetustunnit2])",
            "formatString": "#,0"
          },
          {
            "name": "Opetustunnit suhteessa yli 25 v. väestöön (tuntia per henkilö)",
            "expression": [
              "var lkm = [Opetustunnit]",
              "var lkm2 = [Yli 25 v. väestö]",
              "return IF(lkm2 = BLANK(), BLANK(),\t",
              "IF(lkm2= \"1-4\",  CONCATENATE(FORMAT(lkm / 4, \"0.0 – \"), FORMAT(lkm / 1, \"0.0\"))",
              ", lkm / lkm2))"
            ],
            "formatString": "0.0"
          },
          {
            "name": "Osallistuneet",
            "expression": [
              "var lkm = sum([Osallistuneet2])",
              "return IF(lkm = 0, BLANK(), IF(lkm < 5, \"1-4\", MROUND(lkm, 3)))"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Osallistuneet suhteessa yli 25 v. väestöön",
            "expression": [
              "var osa = [Osallistuneet]",
              "var kaikki = [Yli 25 v. väestö]",
              "return IF(osa = BLANK(), BLANK(),\t",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, \"0.0 %\"",
              ", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Befolkning över 25 år",
            "expression": "[Yli 25 v. väestö]",
            "formatString": "#,0"
          },
          {
            "name": "Population over 25 years old",
            "expression": "[Yli 25 v. väestö]",
            "formatString": "#,0"
          },
          {
            "name": "Teaching hours",
            "expression": "sum([Opetustunnit2])",
            "formatString": "#,0"
          },
          {
            "name": "Teaching hours in comparison to population over 25 years old (hours per person)",
            "expression": "[Opetustunnit suhteessa yli 25 v. väestöön (tuntia per henkilö)]",
            "formatString": "0.0"
          },
          {
            "name": "Participants",
            "expression": "[Osallistuneet]",
            "formatString": "#,0"
          },
          {
            "name": "Participants in comparison to population over 25 years old",
            "expression": "[Osallistuneet suhteessa yli 25 v. väestöön]",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Undervisningstimmar",
            "expression": "sum([Opetustunnit2])",
            "formatString": "#,0"
          },
          {
            "name": "Undervisningstimmar i proportion till befolkning över 25 år (timmar per person)",
            "expression": "[Opetustunnit suhteessa yli 25 v. väestöön (tuntia per henkilö)]",
            "formatString": "#,0.0"
          },
          {
            "name": "Deltagare",
            "expression": "[Osallistuneet]",
            "formatString": "#,0"
          },
          {
            "name": "Deltagare i proportion till befolkning över 25 år",
            "expression": "[Osallistuneet suhteessa yli 25 v. väestöön]",
            "formatString": "#,0.0 %;-#,0.0 %;#,0.0 %"
          },
          {
            "name": "kytkin",
            "expression": "IF(LEFT(USERNAME(), 4) = \"DWI\\\", 1, 0)",
            "formatString": "0",
            "isHidden": true
          },
          {
            "name": "Yli 25 v. väestö_s",
            "expression": "IF([kytkin]=0, BLANK(), sum([yli25v2]))",
            "formatString": "#,0"
          },
          {
            "name": "Opetustunnit_s",
            "expression": "IF([kytkin]=0, BLANK(), sum([Opetustunnit2]))",
            "formatString": "#,0"
          },
          {
            "name": "Opetustunnit suhteessa yli 25 v. väestöön (tuntia per henkilö)_s",
            "expression": "IF([kytkin]=0, BLANK(), [Opetustunnit_s]/[Yli 25 v. väestö_s])",
            "formatString": "0.0"
          },
          {
            "name": "Osallistuneet_s",
            "expression": "IF([kytkin]=0, BLANK(), sum([Osallistuneet2]))",
            "formatString": "#,0"
          },
          {
            "name": "Osallistuneet suhteessa yli 25 v. väestöön_s",
            "expression": "IF([kytkin]=0, BLANK(), [Osallistuneet_s]/[Yli 25 v. väestö_s])",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "v_f_tab_indikaattorit_vapaa_sivistystyö_väestö"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "      SELECT [dbo].[v_f_tab_indikaattorit_vapaa_sivistystyö_väestö].*   FROM [dbo].[v_f_tab_indikaattorit_vapaa_sivistystyö_väestö] "
          }
        ]
      }
    ],
    "cultures": [
      {
        "name": "en-US",
        "translations": {
          "model": {
            "name": "Model",
            "tables": [
              {
                "name": "Muuttujat",
                "translatedCaption": "Variables"
              }
            ]
          }
        }
      },
      {
        "name": "sv-SE",
        "translations": {
          "model": {
            "name": "Model",
            "tables": [
              {
                "name": "Muuttujat",
                "translatedCaption": "Variabler"
              }
            ]
          }
        }
      }
    ],
    "perspectives": [
      {
        "name": "Opetustunnit",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Maakunta"
              },
              {
                "name": "Tilastovuosi"
              }
            ],
            "measures": [
              {
                "name": "Yli 25 v. väestö"
              },
              {
                "name": "Opetustunnit suhteessa yli 25 v. väestöön (tuntia per henkilö)"
              },
              {
                "name": "Opetustunnit"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Osallistuneet",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Maakunta"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Kunta"
              }
            ],
            "measures": [
              {
                "name": "Yli 25 v. väestö"
              },
              {
                "name": "Osallistuneet suhteessa yli 25 v. väestöön"
              },
              {
                "name": "Osallistuneet"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "OpetustunnitSV",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Landskap"
              },
              {
                "name": "Statistikår"
              },
              {
                "name": "Kommun"
              }
            ],
            "measures": [
              {
                "name": "Undervisningstimmar"
              },
              {
                "name": "Undervisningstimmar i proportion till befolkning över 25 år (timmar per person)"
              },
              {
                "name": "Befolkning över 25 år"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "OsallistuneetSV",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Landskap"
              },
              {
                "name": "Statistikår"
              },
              {
                "name": "Kommun"
              }
            ],
            "measures": [
              {
                "name": "Deltagare"
              },
              {
                "name": "Deltagare i proportion till befolkning över 25 år"
              },
              {
                "name": "Befolkning över 25 år"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "OpetustunnitEN",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Municipality"
              },
              {
                "name": "Statistical year"
              },
              {
                "name": "Region"
              }
            ],
            "measures": [
              {
                "name": "Population over 25 years old"
              },
              {
                "name": "Teaching hours in comparison to population over 25 years old (hours per person)"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "OsallistuneetEN",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Municipality"
              },
              {
                "name": "Statistical year"
              },
              {
                "name": "Region"
              }
            ],
            "measures": [
              {
                "name": "Participants"
              },
              {
                "name": "Population over 25 years old"
              },
              {
                "name": "Participants in comparison to population over 25 years old"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      }
    ],
    "roles": [
      {
        "name": "Luku",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "DWI\\T_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1732"
          },
          {
            "memberName": "DWI\\P_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1733"
          },
          {
            "memberName": "DWI\\Z_P_Antero_Read_TAB",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-4156"
          },
          {
            "memberName": "DWI\\Z_T_Antero_Read_TAB",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-4155"
          },
          {
            "memberName": "DWI\\Z_P_Antero_Full_Read_TAB",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-2272"
          }
        ]
      }
    ]
  },
  "id": "SemanticModel"
}
