{
  "name": "SemanticModel",
  "compatibilityLevel": 1200,
  "model": {
    "culture": "fi-FI",
    "dataSources": [
      {
        "name": "SqlServer dwitvipusql22 ANTERO",
        "connectionString": "Provider=SQLOLEDB.1;Data Source=dwitvipusql22;Initial Catalog=ANTERO;Integrated Security=SSPI;Persist Security Info=false",
        "impersonationMode": "impersonateAccount",
        "account": "dwi\\t_viputk_kuutio",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      },
      {
        "name": "SqlServer dwitvipusql22 VipunenTK_lisatiedot 2",
        "connectionString": "Provider=SQLOLEDB.1;Data Source=dwitvipusql22;Initial Catalog=VipunenTK_lisatiedot;Integrated Security=SSPI;Persist Security Info=false",
        "impersonationMode": "impersonateAccount",
        "account": "dwi\\t_viputk_kuutio",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "Sarakeleveys",
        "columns": [
          {
            "name": "Sarakeleveys",
            "dataType": "string",
            "sourceColumn": "Sarakeleveys",
            "sourceProviderType": "Char"
          },
          {
            "name": "leveys",
            "dataType": "string",
            "sourceColumn": "leveys",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Sarakeleveys",
            "dataView": "full",
            "source": {
              "query": " SELECT [dw].[Sarakeleveys].* FROM [dw].[Sarakeleveys] ",
              "dataSource": "SqlServer dwitvipusql22 ANTERO"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dw].[Sarakeleveys].* FROM [dw].[Sarakeleveys] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Sarakeleveys"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dw"
          }
        ]
      },
      {
        "name": "Muuttujat",
        "columns": [
          {
            "name": "Tilastovuosi",
            "dataType": "int64",
            "sourceColumn": "Tilastovuosi",
            "sourceProviderType": "Integer",
            "displayFolder": "Aikamuuttujat"
          },
          {
            "name": "Yliopisto",
            "dataType": "string",
            "sourceColumn": "Organisaatio",
            "sourceProviderType": "WChar",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Sektori",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Sektori",
            "sourceProviderType": "Char"
          },
          {
            "name": "Koulutusnimike",
            "dataType": "string",
            "sourceColumn": "Koulutusnimike",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusaste (2002)",
            "dataType": "string",
            "sourceColumn": "Koulutusaste 2002",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "OKM ohjauksen ala",
            "dataType": "string",
            "sourceColumn": "OKM ohjauksen ala",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Rahoitusmalliala, amk",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Rahoitusmalliala, amk",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Rahoitusmalliala, yo",
            "dataType": "string",
            "sourceColumn": "Rahoitusmalliala, yo",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusaste, taso 1",
            "dataType": "string",
            "sourceColumn": "Koulutusaste, taso 1",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusaste, taso 2",
            "dataType": "string",
            "sourceColumn": "Koulutusaste, taso 2",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusala, taso 1",
            "dataType": "string",
            "sourceColumn": "Koulutusala, taso 1",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusala, taso 2",
            "dataType": "string",
            "sourceColumn": "Koulutusala, taso 2",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusala, taso 3",
            "dataType": "string",
            "sourceColumn": "Koulutusala, taso 3",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Tutkinnon aloitussykli",
            "dataType": "string",
            "sourceColumn": "Tutkinnon aloitussykli",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Päätieteenala",
            "dataType": "string",
            "sourceColumn": "Päätieteenala",
            "sourceProviderType": "WChar",
            "displayFolder": "Tieteenalamuuttujat"
          },
          {
            "name": "Tieteenala",
            "dataType": "string",
            "sourceColumn": "Tieteenala",
            "sourceProviderType": "WChar",
            "displayFolder": "Tieteenalamuuttujat"
          },
          {
            "name": "Tieteenala avain",
            "dataType": "string",
            "sourceColumn": "Tieteenala_avain",
            "sourceProviderType": "WChar",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Tutkijanuravaihe",
            "dataType": "string",
            "sourceColumn": "Tutkijanuravaihe",
            "sourceProviderType": "Char",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Kunta",
            "dataType": "string",
            "sourceColumn": "Kunta",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Kansalaisuus",
            "dataType": "string",
            "sourceColumn": "Kansalaisuus",
            "sourceProviderType": "WChar",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "tutkinnot",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "tutkinnot",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Läsnäolevat opiskelijat (55op)",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Läsnäolevat opiskelijat (55op)",
            "sourceProviderType": "Integer"
          },
          {
            "name": "55op suorittaneet",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "55op suorittaneet",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Läsnäolleet opiskelijat (1-14op)",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Läsnäolleet opiskelijat (1-14op)",
            "sourceProviderType": "Integer"
          },
          {
            "name": "1-14op suorittaneet",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "1-14op suorittaneet",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Yliopiston opetus- ja tutkimushenkilötyövuodet",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Yliopiston opetus- ja tutkimushenkilötyövuodet",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "IV tutkijanuraportaan henkilötyövuodet",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "IV tutkijanuraportaan henkilötyövuodet",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "JulkaisuID",
            "dataType": "string",
            "sourceColumn": "JulkaisuID",
            "sourceProviderType": "Char",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Jufotaso",
            "dataType": "int64",
            "sourceColumn": "Jufotaso",
            "sourceProviderType": "Integer",
            "displayFolder": "Julkaisumuuttujat"
          },
          {
            "name": "Julkaisutyyppi",
            "dataType": "string",
            "sourceColumn": "Julkaisutyyppi",
            "sourceProviderType": "Char",
            "displayFolder": "Julkaisumuuttujat"
          },
          {
            "name": "kv_vaihtoopiskelijat_op_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "kv_vaihtoopiskelijat_op_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "ulkom_hyv_luetut_op_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ulkom_hyv_luetut_op_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "ulkom_harj_op_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ulkom_harj_op_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "avoin_op__lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "avoin_op__lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "kk_yhteistyo_op_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "kk_yhteistyo_op_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "erilopintooik_op_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "erilopintooik_op_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "erillisilla_oik_opkoul_op_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "erillisilla_oik_opkoul_op_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "erikoul_suor_op_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "erikoul_suor_op_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "sijoittuminen_1v_tutkinnon_jalkeen",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "sijoittuminen_1v_tutkinnon_jalkeen",
            "sourceProviderType": "Integer"
          },
          {
            "name": "työlliset 1v tutkinnon jälkeen",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "työlliset 1v tutkinnon jälkeen",
            "sourceProviderType": "Integer"
          },
          {
            "name": "sijoittuminen_3v_tutkinnon_jalkeen",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "sijoittuminen_3v_tutkinnon_jalkeen",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Työlliset 3v tutkinnon jälkeen",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Työlliset 3v tutkinnon jälkeen",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Työlliset 3v (ver2 10,13)",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Työlliset 3v (ver2 10,13)",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Työttömät 3v (ver2, 12)",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Työttömät 3v (ver2, 12)",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Koodit OKM ohjauksen ala",
            "dataType": "string",
            "sourceColumn": "Koodit OKM ohjauksen ala",
            "sourceProviderType": "WChar",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koodit Koulutusnimike",
            "dataType": "string",
            "sourceColumn": "Koodit Koulutusnimike",
            "sourceProviderType": "WChar",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koodit organisaatio",
            "dataType": "string",
            "sourceColumn": "Koodit organisaatio",
            "sourceProviderType": "Char",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koodit kunta",
            "dataType": "string",
            "sourceColumn": "Koodit kunta",
            "sourceProviderType": "WChar",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "jarj. koulutusaste, taso 1",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj. koulutusaste, taso 1",
            "sourceProviderType": "WChar"
          },
          {
            "name": "jarj. koulutusaste, taso 2",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj. koulutusaste, taso 2",
            "sourceProviderType": "WChar"
          },
          {
            "name": "jarj. OKM ohjauksen ala",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarj. OKM ohjauksen ala",
            "sourceProviderType": "Integer"
          },
          {
            "name": "jarj. rahoitusmalliala amk",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj. rahoitusmalliala amk",
            "sourceProviderType": "WChar"
          },
          {
            "name": "jarj. rahoitusmalliala yo",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj. rahoitusmalliala yo",
            "sourceProviderType": "WChar"
          },
          {
            "name": "jarj. paatieteenala",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj. paatieteenala",
            "sourceProviderType": "WChar"
          },
          {
            "name": "jarj. tieteenala",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj. tieteenala",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Suorittanut27",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Suorittanut27"
          },
          {
            "name": "suorittanut55ilmanPankkia",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "suorittanut55ilmanPankkia"
          },
          {
            "name": "suorittanut55pankinAvulla",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "suorittanut55pankinAvulla"
          },
          {
            "name": "Kilpailtu tutkimusrahoitus rah_malli",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Kilpailtu tutkimusrahoitus rah_malli"
          },
          {
            "name": "Läsnä kevät",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Läsnä kevät",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Läsnä syksy",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Läsnä syksy",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "type": "calculated",
            "name": "Org_tilv",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "Muuttujat[Koodit organisaatio]&\"_\"&Muuttujat[Tilastovuosi]"
          },
          {
            "name": "Ulk. kilpailtu tutkimusrahoitus",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Ulk. kilpailtu tutkimusrahoitus"
          },
          {
            "name": "Työlliset 1v (ver2 10,13)",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Työlliset 1v (ver2 10,13)"
          },
          {
            "name": "Julkaisut lukumaara",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Julkaisut lukumaara"
          },
          {
            "type": "calculated",
            "name": "Jufo-painotus nykyinen",
            "dataType": "double",
            "isDataTypeInferred": true,
            "expression": [
              "",
              "var lasku=",
              "if(AND(LEFT([Julkaisutyyppi],1)=\"A\",[Jufotaso]=0),0.1*[Julkaisut lukumaara],",
              "if(AND(LEFT([Julkaisutyyppi],1)=\"A\",[Jufotaso]=1),1*[Julkaisut lukumaara],",
              "if(AND(LEFT([Julkaisutyyppi],1)=\"A\",[Jufotaso]=2),3*[Julkaisut lukumaara],",
              "if(AND(LEFT([Julkaisutyyppi],1)=\"A\",[Jufotaso]=3),4*[Julkaisut lukumaara],",
              "if([Julkaisutyyppi]=\"B1\",0.1*[Julkaisut lukumaara],",
              "if([Julkaisutyyppi]=\"B2\",0.1*[Julkaisut lukumaara],",
              "if([Julkaisutyyppi]=\"B3\",0.1*[Julkaisut lukumaara],",
              "if(AND([Julkaisutyyppi]=\"C1\",[Jufotaso]=0),0.4*[Julkaisut lukumaara],",
              "if(AND([Julkaisutyyppi]=\"C1\",[Jufotaso]=1),4*[Julkaisut lukumaara],",
              "if(AND([Julkaisutyyppi]=\"C1\",[Jufotaso]=2),12*[Julkaisut lukumaara],",
              "if(AND([Julkaisutyyppi]=\"C1\",[Jufotaso]=3),16*[Julkaisut lukumaara],",
              "if(AND([Julkaisutyyppi]=\"C2\",[Jufotaso]=0),0.1*[Julkaisut lukumaara],",
              "if(AND([Julkaisutyyppi]=\"C2\",[Jufotaso]=1),1*[Julkaisut lukumaara],",
              "if(AND([Julkaisutyyppi]=\"C2\",[Jufotaso]=2),3*[Julkaisut lukumaara],",
              "if(AND([Julkaisutyyppi]=\"C2\",[Jufotaso]=3),4*[Julkaisut lukumaara],",
              "if([Julkaisutyyppi]=\"D1\",0.1*[Julkaisut lukumaara],",
              "if([Julkaisutyyppi]=\"D2\",0.1*[Julkaisut lukumaara],",
              "if([Julkaisutyyppi]=\"D3\",0.1*[Julkaisut lukumaara],",
              "if([Julkaisutyyppi]=\"D4\",0.1*[Julkaisut lukumaara],",
              "if([Julkaisutyyppi]=\"D5\",0.4*[Julkaisut lukumaara],",
              "if([Julkaisutyyppi]=\"D6\",0.1*[Julkaisut lukumaara],",
              "if([Julkaisutyyppi]=\"E1\",0.1*[Julkaisut lukumaara],",
              "if([Julkaisutyyppi]=\"E2\",0.4*[Julkaisut lukumaara],",
              "if([Julkaisutyyppi]=\"E3\",0.1*[Julkaisut lukumaara],",
              "0))))))))))))))))))))))))",
              "",
              "return IF(ISBLANK([Julkaisut lukumaara]),BLANK(),lasku)"
            ],
            "displayFolder": "Julkaisumuuttujat"
          },
          {
            "type": "calculated",
            "name": "Yliopisto T2",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": " SWITCH(TRUE(),Muuttujat[Yliopisto]=\"Tampereen yliopisto\",\"Tampereen yliopisto\",Muuttujat[Yliopisto]=\"Tampereen teknillinen yliopisto\",\"Tampereen yliopisto\",Muuttujat[Yliopisto])",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Tilastovuosi - rahoitusmalli",
            "dataType": "int64",
            "sourceColumn": "Tilastovuosi - rahoitusmalli",
            "displayFolder": "Aikamuuttujat"
          },
          {
            "name": "Opiskelijapalautepisteet",
            "dataType": "int64",
            "sourceColumn": "Opiskelijapalautepisteet"
          }
        ],
        "partitions": [
          {
            "name": "v_kk_rahoitusmalli_yo",
            "dataView": "full",
            "source": {
              "query": " SELECT [dw].[v_kk_rahoitusmalli_yo].* FROM [dw].[v_kk_rahoitusmalli_yo] ",
              "dataSource": "SqlServer dwitvipusql22 ANTERO"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tilastovuosi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>86</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Organisaatio</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>91</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Sektori</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>63</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusnimike</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>100</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusaste 2002</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>119</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>OKM ohjauksen ala</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>121</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Rahoitusmalliala, amk</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>132</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Rahoitusmalliala, yo</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>125</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusaste, taso 1</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>129</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusaste, taso 2</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>129</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusala, taso 1</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>122</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusala, taso 2</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>122</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusala, taso 3</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>122</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tutkinnon aloitussykli</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>131</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Päätieteenala</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>96</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tieteenala</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>80</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tieteenala_avain</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>112</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tutkijanuravaihe</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>110</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kunta</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>58</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kansalaisuus</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>91</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tutkinnot</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>73</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Läsnäolevat opiskelijat (55op)</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>173</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>55op suorittaneet</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>116</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Suorittanut27</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>96</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>suorittanut55ilmanPankkia</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>155</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>suorittanut55pankinAvulla</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>155</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Läsnäolleet opiskelijat (1-14op)</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>179</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>1-14op suorittaneet</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>126</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Yliopiston opetus- ja tutkimushenkilötyövuodet</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>253</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>IV tutkijanuraportaan henkilötyövuodet</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>219</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>JulkaisuID</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>78</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Jufotaso</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>72</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Julkaisutyyppi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>97</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Ulk. kilpailtu tutkimusrahoitus</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>168</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>kv_vaihtoopiskelijat_op_lkm</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>163</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ulkom_hyv_luetut_op_lkm</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>154</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ulkom_harj_op_lkm</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>121</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>avoin_op__lkm</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>101</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>kk_yhteistyo_op_lkm</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>130</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>erilopintooik_op_lkm</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>126</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>erillisilla_oik_opkoul_op_lkm</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>160</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>erikoul_suor_op_lkm</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>127</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>sijoittuminen_1v_tutkinnon_jalkeen</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>199</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>työlliset 1v tutkinnon jälkeen</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>167</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>sijoittuminen_3v_tutkinnon_jalkeen</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>199</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Työlliset 3v tutkinnon jälkeen</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>169</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Työlliset 3v (ver2 10,13)</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>148</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Työttömät 3v (ver2, 12)</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>147</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Opiskelijapalautepisteet</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>144</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Läsnä syksy</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>88</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Läsnä kevät</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>88</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit OKM ohjauksen ala</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>154</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit Koulutusnimike</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>133</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit organisaatio</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>122</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit kunta</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>90</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj. koulutusaste, taso 1</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>151</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj. koulutusaste, taso 2</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>151</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj. OKM ohjauksen ala</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>144</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj. rahoitusmalliala amk</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>148</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj. rahoitusmalliala yo</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>141</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj. paatieteenala</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>119</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj. tieteenala</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>101</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kilpailtu tutkimusrahoitus rah_malli</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>193</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Työlliset 1v (ver2 10,13)</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>148</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Julkaisut lukumaara</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>123</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tilastovuosi - rahoitusmalli</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>155</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tilastovuosi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Organisaatio</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Sektori</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusnimike</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusaste 2002</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>OKM ohjauksen ala</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>5</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Rahoitusmalliala, amk</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>6</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Rahoitusmalliala, yo</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>7</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusaste, taso 1</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>8</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusaste, taso 2</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>9</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusala, taso 1</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>10</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusala, taso 2</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>11</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusala, taso 3</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>12</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tutkinnon aloitussykli</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>13</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Päätieteenala</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>14</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tieteenala</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>15</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tieteenala_avain</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>16</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tutkijanuravaihe</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>17</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kunta</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>18</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kansalaisuus</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>19</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tutkinnot</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>20</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Läsnäolevat opiskelijat (55op)</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>21</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>55op suorittaneet</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>22</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Suorittanut27</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>23</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>suorittanut55ilmanPankkia</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>24</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>suorittanut55pankinAvulla</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>25</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Läsnäolleet opiskelijat (1-14op)</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>26</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>1-14op suorittaneet</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>27</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Yliopiston opetus- ja tutkimushenkilötyövuodet</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>28</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>IV tutkijanuraportaan henkilötyövuodet</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>29</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>JulkaisuID</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>30</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Jufotaso</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>31</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Julkaisutyyppi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>32</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Ulk. kilpailtu tutkimusrahoitus</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>61</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>kv_vaihtoopiskelijat_op_lkm</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>33</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ulkom_hyv_luetut_op_lkm</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>34</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ulkom_harj_op_lkm</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>35</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>avoin_op__lkm</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>36</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>kk_yhteistyo_op_lkm</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>37</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>erilopintooik_op_lkm</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>38</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>erillisilla_oik_opkoul_op_lkm</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>39</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>erikoul_suor_op_lkm</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>40</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>sijoittuminen_1v_tutkinnon_jalkeen</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>41</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>työlliset 1v tutkinnon jälkeen</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>42</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>sijoittuminen_3v_tutkinnon_jalkeen</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>43</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Työlliset 3v tutkinnon jälkeen</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>44</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Työlliset 3v (ver2 10,13)</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>45</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Työttömät 3v (ver2, 12)</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>46</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Opiskelijapalautepisteet</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>65</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Läsnä syksy</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>60</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Läsnä kevät</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>59</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit OKM ohjauksen ala</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>47</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit Koulutusnimike</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>48</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit organisaatio</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>49</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit kunta</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>50</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj. koulutusaste, taso 1</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>51</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj. koulutusaste, taso 2</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>52</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj. OKM ohjauksen ala</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>53</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj. rahoitusmalliala amk</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>54</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj. rahoitusmalliala yo</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>55</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj. paatieteenala</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>56</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj. tieteenala</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>57</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kilpailtu tutkimusrahoitus rah_malli</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>58</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Työlliset 1v (ver2 10,13)</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>62</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Julkaisut lukumaara</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>63</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tilastovuosi - rahoitusmalli</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>64</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Suorittanut27</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>suorittanut55ilmanPankkia</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>suorittanut55pankinAvulla</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tilastovuosi</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Organisaatio</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Sektori</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusnimike</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusaste 2002</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>OKM ohjauksen ala</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Rahoitusmalliala, amk</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Rahoitusmalliala, yo</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusaste, taso 1</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusaste, taso 2</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusala, taso 1</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusala, taso 2</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusala, taso 3</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tutkinnon aloitussykli</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Päätieteenala</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tieteenala</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tieteenala_avain</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tutkijanuravaihe</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kunta</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kansalaisuus</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tutkinnot</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Läsnäolevat opiskelijat (55op)</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>55op suorittaneet</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Läsnäolleet opiskelijat (1-14op)</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>1-14op suorittaneet</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Yliopiston opetus- ja tutkimushenkilötyövuodet</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>IV tutkijanuraportaan henkilötyövuodet</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>JulkaisuID</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Jufotaso</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Julkaisutyyppi</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Ulk. kilpailtu tutkimusrahoitus</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>kv_vaihtoopiskelijat_op_lkm</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ulkom_hyv_luetut_op_lkm</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ulkom_harj_op_lkm</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>avoin_op__lkm</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>kk_yhteistyo_op_lkm</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>erilopintooik_op_lkm</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>erillisilla_oik_opkoul_op_lkm</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>erikoul_suor_op_lkm</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>sijoittuminen_1v_tutkinnon_jalkeen</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>työlliset 1v tutkinnon jälkeen</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>sijoittuminen_3v_tutkinnon_jalkeen</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Työlliset 3v tutkinnon jälkeen</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Työlliset 3v (ver2 10,13)</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Työttömät 3v (ver2, 12)</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Opiskelijapalautepisteet</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Läsnä syksy</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Läsnä kevät</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit OKM ohjauksen ala</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit Koulutusnimike</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit organisaatio</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit kunta</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj. koulutusaste, taso 1</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj. koulutusaste, taso 2</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj. OKM ohjauksen ala</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj. rahoitusmalliala amk</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj. rahoitusmalliala yo</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj. paatieteenala</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>jarj. tieteenala</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kilpailtu tutkimusrahoitus rah_malli</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Työlliset 1v (ver2 10,13)</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Julkaisut lukumaara</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tilastovuosi - rahoitusmalli</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Ylempi korkeakoulututkinto summa",
            "expression": "CALCULATE(SUM(Muuttujat[tutkinnot]),Muuttujat[Koulutusaste, taso 2]=\"Ylempi korkeakoulututkinto\")",
            "formatString": "#,0",
            "displayFolder": "Summa"
          },
          {
            "name": "Alempi korkeakoulututkinto summa",
            "expression": "CALCULATE(SUM(Muuttujat[tutkinnot]),Muuttujat[Koulutusaste, taso 2]=\"Alempi korkeakoulututkinto\")",
            "formatString": "#,0",
            "displayFolder": "Summa"
          },
          {
            "name": "Suorittanut 55op summa",
            "expression": "CALCULATE(SUM([55op suorittaneet]))",
            "formatString": "#,0",
            "displayFolder": "Summa"
          },
          {
            "name": "Suorittanut 55op rahoitusmalli summa",
            "expression": [
              "",
              "var pankit=CALCULATE(SUM(Muuttujat[suorittanut55ilmanPankkia])+SUM(Muuttujat[suorittanut55pankinAvulla]))",
              "var kev=CALCULATE(DIVIDE(SUM(Muuttujat[Suorittanut27]),2))",
              "",
              "return pankit+kev"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Summa"
          },
          {
            "name": "Avoimessa yliopistossa suoritetut op summa",
            "expression": "CALCULATE(SUM([avoin_op__lkm]))",
            "formatString": "#,0",
            "displayFolder": "Summa"
          },
          {
            "name": "Erillisellä opinto-oikeudella suoritetut op summa",
            "expression": " CALCULATE(SUM([erilopintooik_op_lkm]))",
            "formatString": "#,0",
            "displayFolder": "Summa"
          },
          {
            "name": "Erikoistumiskoulutuksessa suoritetut op summa",
            "expression": " CALCULATE(SUM([erikoul_suor_op_lkm]))",
            "formatString": "#,0",
            "displayFolder": "Summa"
          },
          {
            "name": "Erillisillä opinto-oikeuksilla opettajankoulutuksen op summa",
            "expression": " CALCULATE(SUM([erillisilla_oik_opkoul_op_lkm]))",
            "displayFolder": "Summa"
          },
          {
            "name": "Korkeakoulujen välisillä sopimuksilla suoritetut op summa",
            "expression": " CALCULATE(SUM([kk_yhteistyo_op_lkm]))",
            "formatString": "#,0",
            "displayFolder": "Summa"
          },
          {
            "name": "Erilliset opinto-oikeudet summa",
            "expression": " [Avoimessa yliopistossa suoritetut op summa]+[Erillisellä opinto-oikeudella suoritetut op summa]+[Erikoistumiskoulutuksessa suoritetut op summa]+[Erillisillä opinto-oikeuksilla opettajankoulutuksen op summa]+[Korkeakoulujen välisillä sopimuksilla suoritetut op summa]",
            "formatString": "#,0",
            "displayFolder": "Summa"
          },
          {
            "name": "kv vaihto-opiskelija op summa",
            "expression": " CALCULATE(SUM(Muuttujat[kv_vaihtoopiskelijat_op_lkm]))",
            "formatString": "#,0",
            "displayFolder": "Summa"
          },
          {
            "name": "Ulkomailla hyväksiluetut op summa",
            "expression": " CALCULATE(SUM(Muuttujat[ulkom_hyv_luetut_op_lkm]))",
            "formatString": "#,0",
            "displayFolder": "Summa"
          },
          {
            "name": "Ulkomailla harjoittelussa suoritetut op summa",
            "expression": " CALCULATE(SUM(Muuttujat[ulkom_harj_op_lkm]))",
            "formatString": "#,0",
            "displayFolder": "Summa"
          },
          {
            "name": "Ulkomailla suoritetut ja kv vaihto-opiskelijoiden op summa",
            "expression": " [Ulkomailla harjoittelussa suoritetut op summa]+[Ulkomailla hyväksiluetut op summa]+[kv vaihto-opiskelija op summa]",
            "formatString": "#,0",
            "displayFolder": "Summa"
          },
          {
            "name": "Ulkomaalaisten ylemmät korkeakoulututkinnot summa",
            "expression": " CALCULATE([Ylempi korkeakoulututkinto summa],Muuttujat[Kansalaisuus]<>\"Suomi\")",
            "formatString": "#,0",
            "displayFolder": "Summa"
          },
          {
            "name": "Kandipalaute pisteet summa",
            "expression": " CALCULATE(SUM(Muuttujat[Opiskelijapalautepisteet]))",
            "formatString": "#,0",
            "displayFolder": "Summa"
          },
          {
            "name": "Työllisten lukumäärä 1v valmistumisesta summa",
            "expression": [
              " ",
              "var lasku=CALCULATE(SUM(Muuttujat[Työlliset 1v (ver2 10,13)]),Muuttujat[Koulutusaste, taso 2]=\"Ylempi korkeakoulututkinto\")",
              "",
              "return IF(lasku=0,BLANK(),IF(lasku<5,3,MROUND(lasku,3)))"
            ],
            "formatString": "#,0",
            "displayFolder": "Summa"
          },
          {
            "name": "Julkaisut summa",
            "expression": " IF(sum(Muuttujat[Julkaisut lukumaara])=0,BLANK(),SUM(Muuttujat[Julkaisut lukumaara]))",
            "formatString": "#,0",
            "displayFolder": "Summa"
          },
          {
            "name": "Julkaisut rahoitusmalli summa",
            "expression": "if(sum(Muuttujat[Jufo-painotus nykyinen])=0,blank(),sum(Muuttujat[Jufo-painotus nykyinen]))",
            "formatString": "#,0.0",
            "displayFolder": "Summa"
          },
          {
            "name": "Tohtorin tutkinnot summa",
            "expression": "CALCULATE(SUM(Muuttujat[tutkinnot]),Muuttujat[Koulutusaste, taso 2]=\"Tohtorintutkinto\")",
            "formatString": "#,0",
            "displayFolder": "Summa"
          },
          {
            "name": "Muu kilpailtu tutkimusrahoitus summa",
            "expression": "CALCULATE(SUM(Muuttujat[Kilpailtu tutkimusrahoitus rah_malli]))",
            "formatString": "#,0",
            "displayFolder": "Summa"
          },
          {
            "name": "Ulkomaalainen htv summa",
            "expression": " CALCULATE(SUM(Muuttujat[Yliopiston opetus- ja tutkimushenkilötyövuodet]),Muuttujat[Kansalaisuus]<>\"Suomi\")",
            "formatString": "#,0.0",
            "displayFolder": "Summa"
          },
          {
            "name": "Alempi korkeakoulututkinto",
            "expression": " CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],Muuttujat[Yliopisto],\"summa\",[Alempi korkeakoulututkinto summa]),[summa]))",
            "formatString": "#,0.0",
            "displayFolder": "Keskiarvo"
          },
          {
            "name": "Ylempi korkeakoulututkinto",
            "expression": " CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],Muuttujat[Yliopisto],\"summa\",[Ylempi korkeakoulututkinto summa]),[summa]))",
            "formatString": "#,0.0",
            "displayFolder": "Keskiarvo"
          },
          {
            "name": "Suorittanut 55 rahoitusmalli",
            "expression": " CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],Muuttujat[Yliopisto],\"summa\",[Suorittanut 55op rahoitusmalli summa]),[summa]))",
            "formatString": "#,0.0",
            "displayFolder": "Keskiarvo"
          },
          {
            "name": "Erilliset opinto-oikeudet",
            "expression": " CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],Muuttujat[Yliopisto],\"summa\",[Erilliset opinto-oikeudet summa]),[summa]))",
            "formatString": "#,0.0",
            "displayFolder": "Keskiarvo"
          },
          {
            "name": "Ulkomailla suoritetut ja kv vaihto-opiskelijoiden pisteet",
            "expression": " CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],Muuttujat[Yliopisto],\"summa\",[Ulkomailla suoritetut ja kv vaihto-opiskelijoiden op summa]),[summa]))",
            "formatString": "#,0.0",
            "displayFolder": "Keskiarvo"
          },
          {
            "name": "Ulkomaalaisten ylemmät kk-tutkinnot",
            "expression": " CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],Muuttujat[Yliopisto],\"summa\",[Ulkomaalaisten ylemmät korkeakoulututkinnot summa]),[summa]))",
            "formatString": "#,0.0",
            "displayFolder": "Keskiarvo"
          },
          {
            "name": "Tohtorin tutkinnot",
            "expression": " CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],Muuttujat[Yliopisto],\"summa\",[Tohtorin tutkinnot summa]),[summa]))",
            "formatString": "#,0.0",
            "displayFolder": "Keskiarvo"
          },
          {
            "name": "Julkaisut rahoitusmalli",
            "expression": " CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],Muuttujat[Yliopisto],\"summa\",[Julkaisut rahoitusmalli summa]),[summa]))",
            "formatString": "#,0.0",
            "displayFolder": "Keskiarvo"
          },
          {
            "name": "Muu kilpailtu tutkimusrahoitus",
            "expression": " CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],Muuttujat[Yliopisto],\"summa\",[Muu kilpailtu tutkimusrahoitus summa]),[summa]))",
            "formatString": "#,0.0",
            "displayFolder": "Keskiarvo"
          },
          {
            "name": "Ulkomaalainen htv",
            "expression": " CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],Muuttujat[Yliopisto],\"summa\",[Ulkomaalainen htv summa]),[summa]))",
            "formatString": "#,0.0",
            "displayFolder": "Keskiarvo"
          },
          {
            "name": "Tutkinnot summa",
            "expression": " SUM(Muuttujat[tutkinnot])",
            "formatString": "#,0",
            "displayFolder": "Summa"
          },
          {
            "name": "Työlliset 1v valmistumisesta",
            "expression": " CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],Muuttujat[Yliopisto],\"summa\",[Työllisten lukumäärä 1v valmistumisesta summa]),[summa]))",
            "formatString": "#,0.0",
            "displayFolder": "Keskiarvo"
          },
          {
            "name": "Opiskelijapalautteen pisteet",
            "expression": " CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],Muuttujat[Yliopisto],\"summa\",[Kandipalaute pisteet summa]),[summa]))",
            "formatString": "#,0.0",
            "displayFolder": "Keskiarvo"
          },
          {
            "name": "Ulkomainen kilpailtu tutkimusrahoitus summa",
            "expression": " CALCULATE(SUM(Muuttujat[Ulk. kilpailtu tutkimusrahoitus]))",
            "formatString": "#,0",
            "displayFolder": "Summa"
          },
          {
            "name": "Ulkomainen kilpailtu tutkimusrahoitus",
            "expression": "  CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],Muuttujat[Yliopisto],\"summa\",[Ulkomainen kilpailtu tutkimusrahoitus summa]),[summa]))",
            "formatString": "#,0.0",
            "displayFolder": "Keskiarvo"
          },
          {
            "name": "Alempi korkeakoulututkinto (%)",
            "expression": [
              " ",
              "var org = [Alempi korkeakoulututkinto]",
              "var kaikki = CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],\"summa\",[Alempi korkeakoulututkinto summa]),[summa]),ALL(Muuttujat[Yliopisto]))",
              "",
              "return DIVIDE(org,kaikki)"
            ],
            "formatString": "#,0.00 %;-#,0.00 %;#,0.00 %",
            "displayFolder": "Keskiarvo"
          },
          {
            "name": "Ylempi korkeakoulututkinto (%)",
            "expression": [
              " ",
              "var org = [Ylempi korkeakoulututkinto]",
              "var kaikki = CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],\"summa\",[Ylempi korkeakoulututkinto summa]),[summa]),ALL(Muuttujat[Yliopisto]))",
              "return DIVIDE(org,kaikki)"
            ],
            "formatString": "#,0.00 %;-#,0.00 %;#,0.00 %",
            "displayFolder": "Keskiarvo"
          },
          {
            "name": "Suorittanut 55 rahoitusmalli (%)",
            "expression": [
              " ",
              "var org = [Suorittanut 55 rahoitusmalli]",
              "var kaikki = CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],\"summa\",[Suorittanut 55op rahoitusmalli summa]),[summa]),ALL(Muuttujat[Yliopisto]))",
              "",
              "return DIVIDE(org,kaikki)"
            ],
            "formatString": "#,0.00 %;-#,0.00 %;#,0.00 %",
            "displayFolder": "Keskiarvo"
          },
          {
            "name": "Erilliset opinto-oikeudet (%)",
            "expression": [
              "",
              "var org = [Erilliset opinto-oikeudet]",
              "var kaikki = CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],\"summa\",[Erilliset opinto-oikeudet summa]),[summa]),ALL(Muuttujat[Yliopisto]))",
              "",
              "return DIVIDE(org,kaikki)"
            ],
            "formatString": "#,0.00 %;-#,0.00 %;#,0.00 %",
            "displayFolder": "Keskiarvo"
          },
          {
            "name": "Ulkomailla suoritetut ja kv vaihto-opiskelijoiden pisteet (%)",
            "expression": [
              " ",
              "var org= [Ulkomailla suoritetut ja kv vaihto-opiskelijoiden pisteet]",
              "var kaikki = CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],\"summa\",[Ulkomailla suoritetut ja kv vaihto-opiskelijoiden op summa]),[summa]),ALL(Muuttujat[Yliopisto]))",
              "return DIVIDE(org,kaikki)"
            ],
            "formatString": "#,0.00 %;-#,0.00 %;#,0.00 %",
            "displayFolder": "Keskiarvo"
          },
          {
            "name": "Ulkomaalaisten ylemmät kk-tutkinnot (%)",
            "expression": [
              " ",
              "var org = [Ulkomaalaisten ylemmät kk-tutkinnot]",
              "var kaikki = CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],\"summa\",[Ulkomaalaisten ylemmät korkeakoulututkinnot summa]),[summa]),ALL(Muuttujat[Yliopisto]))",
              "return DIVIDE(org,kaikki)"
            ],
            "formatString": "#,0.00 %;-#,0.00 %;#,0.00 %",
            "displayFolder": "Keskiarvo"
          },
          {
            "name": "Tohtorin tutkinnot (%)",
            "expression": [
              " ",
              "var org = [Tohtorin tutkinnot]",
              "var kaikki = CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],\"summa\",[Tohtorin tutkinnot summa]),[summa]),ALL(Muuttujat[Yliopisto]))",
              "",
              "return DIVIDE(org,kaikki)"
            ],
            "formatString": "#,0.00 %;-#,0.00 %;#,0.00 %",
            "displayFolder": "Keskiarvo"
          },
          {
            "name": "Julkaisut rahoitusmalli (%)",
            "expression": [
              " ",
              "var org = [Julkaisut rahoitusmalli]",
              "var kaikki =CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],\"summa\",[Julkaisut rahoitusmalli summa]),[summa]),ALL(Muuttujat[Yliopisto]))",
              "return DIVIDE(org,kaikki)"
            ],
            "formatString": "#,0.00 %;-#,0.00 %;#,0.00 %",
            "displayFolder": "Keskiarvo"
          },
          {
            "name": "Muu kilpailtu tutkimusrahoitus (%)",
            "expression": [
              " ",
              "var org = [Muu kilpailtu tutkimusrahoitus]",
              "var kaikki = CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],\"summa\",[Muu kilpailtu tutkimusrahoitus summa]),[summa]),ALL(Muuttujat[Yliopisto]))",
              "return DIVIDE(org,kaikki)"
            ],
            "formatString": "#,0.00 %;-#,0.00 %;#,0.00 %",
            "displayFolder": "Keskiarvo"
          },
          {
            "name": "Ulkomaalainen htv (%)",
            "expression": [
              " ",
              "var org = [Ulkomaalainen htv]",
              "var kaikki = CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],\"summa\",[Ulkomaalainen htv summa]),[summa]),ALL(Muuttujat[Yliopisto]))",
              "return DIVIDE(org,kaikki)"
            ],
            "formatString": "#,0.00 %;-#,0.00 %;#,0.00 %",
            "displayFolder": "Keskiarvo"
          },
          {
            "name": "Opiskelijapalautteen pisteet (%)",
            "expression": [
              " ",
              "var org = [Opiskelijapalautteen pisteet]",
              "var kaikki = CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],\"summa\",[Kandipalaute pisteet summa]),[summa]),ALL(Muuttujat[Yliopisto]))",
              "return DIVIDE(org,kaikki)"
            ],
            "formatString": "#,0.00 %;-#,0.00 %;#,0.00 %",
            "displayFolder": "Keskiarvo"
          },
          {
            "name": "Työlliset 1v valmistumisesta (%)",
            "expression": [
              " ",
              "var org = [Työlliset 1v valmistumisesta]",
              "var kaikki = CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],\"summa\",[Työllisten lukumäärä 1v valmistumisesta summa]),[summa]),ALL(Muuttujat[Yliopisto]))",
              "return DIVIDE(org,kaikki)"
            ],
            "formatString": "#,0.00 %;-#,0.00 %;#,0.00 %",
            "displayFolder": "Keskiarvo"
          },
          {
            "name": "Ulkomainen kilpailtu tutkimusrahoitus (%)",
            "expression": [
              "  ",
              "var org = [Ulkomainen kilpailtu tutkimusrahoitus]",
              "var kaikki = CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],\"summa\",[Ulkomainen kilpailtu tutkimusrahoitus summa]),[summa]),ALL(Muuttujat[Yliopisto]))",
              "return DIVIDE(org,kaikki)"
            ],
            "formatString": "#,0.00 %;-#,0.00 %;#,0.00 %",
            "displayFolder": "Keskiarvo"
          },
          {
            "name": "Alempi korkeakoulututkinto T2",
            "expression": " CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],Muuttujat[Yliopisto T2],\"summa\",[Alempi korkeakoulututkinto summa]),[summa]))",
            "formatString": "#,0.0",
            "displayFolder": "Keskiarvo"
          },
          {
            "name": "Ylempi korkeakoulututkinto T2",
            "expression": " CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],Muuttujat[Yliopisto T2],\"summa\",[Ylempi korkeakoulututkinto summa]),[summa]))",
            "formatString": "#,0.0",
            "displayFolder": "Keskiarvo"
          },
          {
            "name": "Suorittanut 55 rahoitusmalli T2",
            "expression": " CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],Muuttujat[Yliopisto T2],\"summa\",[Suorittanut 55op rahoitusmalli summa]),[summa]))",
            "formatString": "#,0.0",
            "displayFolder": "Keskiarvo"
          },
          {
            "name": "Erilliset opinto-oikeudet T2",
            "expression": " CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],Muuttujat[Yliopisto T2],\"summa\",[Erilliset opinto-oikeudet summa]),[summa]))",
            "formatString": "#,0.0",
            "displayFolder": "Keskiarvo"
          },
          {
            "name": "Ulkomailla suoritetut ja kv vaihto-opiskelijoiden pisteet T2",
            "expression": " CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],Muuttujat[Yliopisto T2],\"summa\",[Ulkomailla suoritetut ja kv vaihto-opiskelijoiden op summa]),[summa]))",
            "formatString": "#,0.0",
            "displayFolder": "Keskiarvo"
          },
          {
            "name": "Ulkomaalaisten ylemmät kk-tutkinnot T2",
            "expression": " CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],Muuttujat[Yliopisto T2],\"summa\",[Ulkomaalaisten ylemmät korkeakoulututkinnot summa]),[summa]))",
            "formatString": "#,0.0",
            "displayFolder": "Keskiarvo"
          },
          {
            "name": "Tohtorin tutkinnot T2",
            "expression": " CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],Muuttujat[Yliopisto T2],\"summa\",[Tohtorin tutkinnot summa]),[summa]))",
            "formatString": "#,0.0",
            "displayFolder": "Keskiarvo"
          },
          {
            "name": "Julkaisut rahoitusmalli T2",
            "expression": " CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],Muuttujat[Yliopisto T2],\"summa\",[Julkaisut rahoitusmalli summa]),[summa]))",
            "formatString": "#,0.0",
            "displayFolder": "Keskiarvo"
          },
          {
            "name": "Muu kilpailtu tutkimusrahoitus T2",
            "expression": " CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],Muuttujat[Yliopisto T2],\"summa\",[Muu kilpailtu tutkimusrahoitus summa]),[summa]))",
            "formatString": "#,0.0",
            "displayFolder": "Keskiarvo"
          },
          {
            "name": "Ulkomaalainen htv T2",
            "expression": " CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],Muuttujat[Yliopisto T2],\"summa\",[Ulkomaalainen htv summa]),[summa]))",
            "formatString": "#,0.0",
            "displayFolder": "Keskiarvo"
          },
          {
            "name": "Opintopalautteen pisteet T2",
            "expression": " CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],Muuttujat[Yliopisto T2],\"summa\",[Kandipalaute pisteet summa]),[summa]))",
            "formatString": "#,0.0",
            "displayFolder": "Keskiarvo"
          },
          {
            "name": "Työlliset 1v valmistumisesta T2",
            "expression": " CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],Muuttujat[Yliopisto T2],\"summa\",[Työllisten lukumäärä 1v valmistumisesta summa]),[summa]))",
            "formatString": "#,0.0",
            "displayFolder": "Keskiarvo"
          },
          {
            "name": "Ulkomainen kilpailtu tutkimusrahoitus T2",
            "expression": "  CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],Muuttujat[Yliopisto T2],\"summa\",[Ulkomainen kilpailtu tutkimusrahoitus summa]),[summa]))",
            "formatString": "#,0.0",
            "displayFolder": "Keskiarvo"
          },
          {
            "name": "Alempi korkeakoulututkinto (%) T2",
            "expression": [
              " ",
              "var org = [Alempi korkeakoulututkinto]",
              "var kaikki = CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],\"summa\",[Alempi korkeakoulututkinto summa]),[summa]),ALL(Muuttujat[Yliopisto T2]))",
              "",
              "return DIVIDE(org,kaikki)"
            ],
            "formatString": "#,0.00 %;-#,0.00 %;#,0.00 %",
            "displayFolder": "Keskiarvo\\% osuus"
          },
          {
            "name": "Ylempi korkeakoulututkinto (%) T2",
            "expression": [
              " ",
              "var org = [Ylempi korkeakoulututkinto]",
              "var kaikki = CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],\"summa\",[Ylempi korkeakoulututkinto summa]),[summa]),ALL(Muuttujat[Yliopisto T2]))",
              "return DIVIDE(org,kaikki)"
            ],
            "formatString": "#,0.00 %;-#,0.00 %;#,0.00 %",
            "displayFolder": "Keskiarvo\\% osuus"
          },
          {
            "name": "Suorittanut 55 rahoitusmalli (%) T2",
            "expression": [
              " ",
              "var org = [Suorittanut 55 rahoitusmalli]",
              "var kaikki = CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],\"summa\",[Suorittanut 55op rahoitusmalli summa]),[summa]),ALL(Muuttujat[Yliopisto T2]))",
              "",
              "return DIVIDE(org,kaikki)"
            ],
            "formatString": "#,0.00 %;-#,0.00 %;#,0.00 %",
            "displayFolder": "Keskiarvo\\% osuus"
          },
          {
            "name": "Erilliset opinto-oikeudet (%) T2",
            "expression": [
              "",
              "var org = [Erilliset opinto-oikeudet]",
              "var kaikki = CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],\"summa\",[Erilliset opinto-oikeudet summa]),[summa]),ALL(Muuttujat[Yliopisto T2]))",
              "",
              "return DIVIDE(org,kaikki)"
            ],
            "formatString": "#,0.00 %;-#,0.00 %;#,0.00 %",
            "displayFolder": "Keskiarvo\\% osuus"
          },
          {
            "name": "Ulkomailla suoritetut ja kv vaihto-opiskelijoiden pisteet (%) T2",
            "expression": [
              " ",
              "var org= [Ulkomailla suoritetut ja kv vaihto-opiskelijoiden pisteet]",
              "var kaikki = CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],\"summa\",[Ulkomailla suoritetut ja kv vaihto-opiskelijoiden op summa]),[summa]),ALL(Muuttujat[Yliopisto T2]))",
              "return DIVIDE(org,kaikki)"
            ],
            "formatString": "#,0.00 %;-#,0.00 %;#,0.00 %",
            "displayFolder": "Keskiarvo\\% osuus"
          },
          {
            "name": "Ulkomaalaisten ylemmät kk-tutkinnot (%) T2",
            "expression": [
              " ",
              "var org = [Ulkomaalaisten ylemmät kk-tutkinnot]",
              "var kaikki = CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],\"summa\",[Ulkomaalaisten ylemmät korkeakoulututkinnot summa]),[summa]),ALL(Muuttujat[Yliopisto T2]))",
              "return DIVIDE(org,kaikki)"
            ],
            "formatString": "#,0.00 %;-#,0.00 %;#,0.00 %",
            "displayFolder": "Keskiarvo\\% osuus"
          },
          {
            "name": "Tohtorin tutkinnot (%) T2",
            "expression": [
              " ",
              "var org = [Tohtorin tutkinnot]",
              "var kaikki = CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],\"summa\",[Tohtorin tutkinnot summa]),[summa]),ALL(Muuttujat[Yliopisto T2]))",
              "",
              "return DIVIDE(org,kaikki)"
            ],
            "formatString": "#,0.00 %;-#,0.00 %;#,0.00 %",
            "displayFolder": "Keskiarvo\\% osuus"
          },
          {
            "name": "Julkaisut rahoitusmalli (%) T2",
            "expression": [
              " ",
              "var org = [Julkaisut rahoitusmalli]",
              "var kaikki =CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],\"summa\",[Julkaisut rahoitusmalli summa]),[summa]),ALL(Muuttujat[Yliopisto T2]))",
              "return DIVIDE(org,kaikki)"
            ],
            "formatString": "#,0.00 %;-#,0.00 %;#,0.00 %",
            "displayFolder": "Keskiarvo\\% osuus"
          },
          {
            "name": "Muu kilpailtu tutkimusrahoitus (%) T2",
            "expression": [
              " ",
              "var org = [Muu kilpailtu tutkimusrahoitus]",
              "var kaikki = CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],\"summa\",[Muu kilpailtu tutkimusrahoitus summa]),[summa]),ALL(Muuttujat[Yliopisto T2]))",
              "return DIVIDE(org,kaikki)"
            ],
            "formatString": "#,0.00 %;-#,0.00 %;#,0.00 %",
            "displayFolder": "Keskiarvo\\% osuus"
          },
          {
            "name": "Ulkomaalainen htv (%) T2",
            "expression": [
              " ",
              "var org = [Ulkomaalainen htv]",
              "var kaikki = CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],\"summa\",[Ulkomaalainen htv summa]),[summa]),ALL(Muuttujat[Yliopisto T2]))",
              "return DIVIDE(org,kaikki)"
            ],
            "formatString": "#,0.00 %;-#,0.00 %;#,0.00 %",
            "displayFolder": "Keskiarvo\\% osuus"
          },
          {
            "name": "Opintopalautteen pisteet (%) T2",
            "expression": [
              " ",
              "var org = [Opiskelijapalautteen pisteet]",
              "var kaikki = CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],\"summa\",[Kandipalaute pisteet summa]),[summa]),ALL(Muuttujat[Yliopisto T2]))",
              "return DIVIDE(org,kaikki)"
            ],
            "formatString": "#,0.00 %;-#,0.00 %;#,0.00 %",
            "displayFolder": "Keskiarvo\\% osuus"
          },
          {
            "name": "Työlliset 1v valmistumisesta (%) T2",
            "expression": [
              " ",
              "var org = [Työlliset 1v valmistumisesta]",
              "var kaikki = CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],\"summa\",[Työllisten lukumäärä 1v valmistumisesta summa]),[summa]),ALL(Muuttujat[Yliopisto T2]))",
              "return DIVIDE(org,kaikki)"
            ],
            "formatString": "#,0.00 %;-#,0.00 %;#,0.00 %",
            "displayFolder": "Keskiarvo\\% osuus"
          },
          {
            "name": "Ulkomainen kilpailtu tutkimusrahoitus (%) T2",
            "expression": [
              "  ",
              "var org = [Ulkomainen kilpailtu tutkimusrahoitus]",
              "var kaikki = CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],\"summa\",[Ulkomainen kilpailtu tutkimusrahoitus summa]),[summa]),ALL(Muuttujat[Yliopisto T2]))",
              "return DIVIDE(org,kaikki)"
            ],
            "formatString": "#,0.00 %;-#,0.00 %;#,0.00 %",
            "displayFolder": "Keskiarvo\\% osuus"
          },
          {
            "name": "Rahoitusvuosi_int",
            "expression": [
              "",
              "var min_vuosi=MINX(FILTERS(Muuttujat[Tilastovuosi - rahoitusmalli]),MIN(Muuttujat[Tilastovuosi - rahoitusmalli]))",
              "var med_vuosi=MEDIANX(FILTERS(Muuttujat[Tilastovuosi - rahoitusmalli]),MEDIAN(Muuttujat[Tilastovuosi - rahoitusmalli]))",
              "var max_vuosi=MAXX(FILTERS(Muuttujat[Tilastovuosi - rahoitusmalli]),MAX(Muuttujat[Tilastovuosi - rahoitusmalli]))",
              "var min_med_max=IF(AND(max_vuosi-1=med_vuosi,med_vuosi-1=min_vuosi),TRUE(),FALSE())",
              "var count_vuosi=COUNTX(FILTERS(Muuttujat[Tilastovuosi - rahoitusmalli]),DISTINCTCOUNT(Muuttujat[Tilastovuosi - rahoitusmalli]))",
              "",
              "",
              "return SWITCH(TRUE(),",
              "\tcount_vuosi<>3,BLANK(),",
              "\tmin_med_max=FALSE(),BLANK(),",
              "\tmax_vuosi<2017,BLANK(),",
              "\tYEAR(NOW())-max_vuosi<=2,YEAR(NOW()),",
              "\tmax_vuosi+2)",
              ""
            ],
            "isHidden": true
          },
          {
            "name": "Rahoitusvuosi",
            "expression": [
              "",
              "var min_vuosi=MINX(FILTERS(Muuttujat[Tilastovuosi - rahoitusmalli]),MIN(Muuttujat[Tilastovuosi - rahoitusmalli]))",
              "var med_vuosi=MEDIANX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi - rahoitusmalli],\"dc\",MEDIAN(Muuttujat[Tilastovuosi - rahoitusmalli])),MEDIAN([dc]))",
              "var max_vuosi=MAXX(FILTERS(Muuttujat[Tilastovuosi - rahoitusmalli]),MAX(Muuttujat[Tilastovuosi - rahoitusmalli]))",
              "var min_med_max=IF(AND(max_vuosi-1=med_vuosi,med_vuosi-1=min_vuosi),TRUE(),FALSE())",
              "var count_vuosi=COUNTX(FILTERS(Muuttujat[Tilastovuosi - rahoitusmalli]),DISTINCTCOUNT(Muuttujat[Tilastovuosi - rahoitusmalli]))",
              "",
              "return SWITCH(TRUE(),",
              "\tcount_vuosi<>3,\"Valitse kolme rahoitusmallin tilastovuotta\",",
              "\tmin_med_max=FALSE(),\"Valitse peräkkäiset rahoitumallin vuodet\",",
              "\tmax_vuosi<2017,\"Ei rahoitustietoja valituille vuosille\",",
              "\tYEAR(NOW())-max_vuosi<=2,YEAR(NOW()),max_vuosi+2)",
              ""
            ],
            "displayFolder": "Aikamuuttujat"
          },
          {
            "name": "Alempi korkeakoulututkinto (perusrahoitus 1000 euroa)",
            "expression": [
              "",
              "var lasku = CALCULATE(AVERAGE(Rahoitusmalli_korkeakoulut[Rahoitus_1000_euroa]),Rahoitusmalli_korkeakoulut[Sektori]=\"Yliopisto\",Rahoitusmalli_korkeakoulut[indikaattori]=\"Alemmat korkeakoulututkinnot\")",
              "var vuosi_check = IF(HASONEVALUE(Rahoitusmalli_korkeakoulut[rahoituksen_vuosi]),",
              "\tCALCULATE(LASTNONBLANK(Rahoitusmalli_korkeakoulut[rahoituksen_vuosi],TRUE()),",
              "\t\tFILTER(Rahoitusmalli_korkeakoulut,",
              "\t\t\tAND(NOT(ISBLANK(Rahoitusmalli_korkeakoulut[rahoituksen_vuosi])),",
              "\t\t\tRahoitusmalli_korkeakoulut[rahoituksen_vuosi]=[Rahoitusvuosi_int])",
              "\t\t\t))",
              "\t\t,BLANK())",
              "return CALCULATE(lasku,Rahoitusmalli_korkeakoulut[rahoituksen_vuosi]=vuosi_check)"
            ],
            "formatString": "#,0",
            "displayFolder": "Rahoitus\\€"
          },
          {
            "name": "Ylempi korkeakoulututkinto (perusrahoitus 1000 euroa)",
            "expression": [
              " ",
              "var lasku = CALCULATE(AVERAGE(Rahoitusmalli_korkeakoulut[Rahoitus_1000_euroa]),Rahoitusmalli_korkeakoulut[Sektori]=\"Yliopisto\",Rahoitusmalli_korkeakoulut[indikaattori]=\"Ylemmät korkeakoulututkinnot\")",
              "var vuosi_check = IF(HASONEVALUE(Rahoitusmalli_korkeakoulut[rahoituksen_vuosi]),",
              "\tCALCULATE(LASTNONBLANK(Rahoitusmalli_korkeakoulut[rahoituksen_vuosi],TRUE()),",
              "\t\tFILTER(Rahoitusmalli_korkeakoulut,",
              "\t\t\tAND(NOT(ISBLANK(Rahoitusmalli_korkeakoulut[rahoituksen_vuosi])),",
              "\t\t\tRahoitusmalli_korkeakoulut[rahoituksen_vuosi]=[Rahoitusvuosi_int])",
              "\t\t\t))",
              "\t\t,BLANK())",
              "return CALCULATE(lasku,Rahoitusmalli_korkeakoulut[rahoituksen_vuosi]=vuosi_check)",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Rahoitus\\€"
          },
          {
            "name": "Suorittanut 55 (perusrahoitus 1000 euroa)",
            "expression": [
              "",
              "var lasku = CALCULATE(AVERAGE(Rahoitusmalli_korkeakoulut[Rahoitus_1000_euroa]),Rahoitusmalli_korkeakoulut[Sektori]=\"Yliopisto\",Rahoitusmalli_korkeakoulut[indikaattori]=\"55 opintopistettä suorittaneet\")",
              "var vuosi_check = IF(HASONEVALUE(Rahoitusmalli_korkeakoulut[rahoituksen_vuosi]),",
              "\tCALCULATE(LASTNONBLANK(Rahoitusmalli_korkeakoulut[rahoituksen_vuosi],TRUE()),",
              "\t\tFILTER(Rahoitusmalli_korkeakoulut,",
              "\t\t\tAND(NOT(ISBLANK(Rahoitusmalli_korkeakoulut[rahoituksen_vuosi])),",
              "\t\t\tRahoitusmalli_korkeakoulut[rahoituksen_vuosi]=[Rahoitusvuosi_int])",
              "\t\t\t))",
              "\t\t,BLANK())",
              "return CALCULATE(lasku,Rahoitusmalli_korkeakoulut[rahoituksen_vuosi]=vuosi_check)",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Rahoitus\\€"
          },
          {
            "name": "Erilliset opinto-oikeudet (perusrahoitus 1000 euroa)",
            "expression": [
              "",
              "var lasku = CALCULATE(AVERAGE(Rahoitusmalli_korkeakoulut[Rahoitus_1000_euroa]),Rahoitusmalli_korkeakoulut[Sektori]=\"Yliopisto\",Rahoitusmalli_korkeakoulut[indikaattori]=\"Avoin yo-opetus ja erilliset opinnot opintopisteet ym.\")",
              "var vuosi_check = IF(HASONEVALUE(Rahoitusmalli_korkeakoulut[rahoituksen_vuosi]),",
              "\tCALCULATE(LASTNONBLANK(Rahoitusmalli_korkeakoulut[rahoituksen_vuosi],TRUE()),",
              "\t\tFILTER(Rahoitusmalli_korkeakoulut,",
              "\t\t\tAND(NOT(ISBLANK(Rahoitusmalli_korkeakoulut[rahoituksen_vuosi])),",
              "\t\t\tRahoitusmalli_korkeakoulut[rahoituksen_vuosi]=[Rahoitusvuosi_int])",
              "\t\t\t))",
              "\t\t,BLANK())",
              "return CALCULATE(lasku,Rahoitusmalli_korkeakoulut[rahoituksen_vuosi]=vuosi_check)",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Rahoitus\\€"
          },
          {
            "name": "Ulkomailla suoritetut ja kv vaihto-opiskelijoiden pisteet (perusrahoitus 1000 euroa)",
            "expression": [
              "",
              "var lasku = CALCULATE(AVERAGE(Rahoitusmalli_korkeakoulut[Rahoitus_1000_euroa]),Rahoitusmalli_korkeakoulut[Sektori]=\"Yliopisto\",Rahoitusmalli_korkeakoulut[indikaattori]=\"Vaihto-opiskelu, opintopisteet\")",
              "var vuosi_check = IF(HASONEVALUE(Rahoitusmalli_korkeakoulut[rahoituksen_vuosi]),",
              "\tCALCULATE(LASTNONBLANK(Rahoitusmalli_korkeakoulut[rahoituksen_vuosi],TRUE()),",
              "\t\tFILTER(Rahoitusmalli_korkeakoulut,",
              "\t\t\tAND(NOT(ISBLANK(Rahoitusmalli_korkeakoulut[rahoituksen_vuosi])),",
              "\t\t\tRahoitusmalli_korkeakoulut[rahoituksen_vuosi]=[Rahoitusvuosi_int])",
              "\t\t\t))",
              "\t\t,BLANK())",
              "return CALCULATE(lasku,Rahoitusmalli_korkeakoulut[rahoituksen_vuosi]=vuosi_check)",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Rahoitus\\€"
          },
          {
            "name": "Ulkomaalaisten ylemmät kk-tutkinnot (perusrahoitus 1000 euroa)",
            "expression": [
              "",
              "var lasku = CALCULATE(AVERAGE(Rahoitusmalli_korkeakoulut[Rahoitus_1000_euroa]),Rahoitusmalli_korkeakoulut[Sektori]=\"Yliopisto\",Rahoitusmalli_korkeakoulut[indikaattori]=\"Ulkomaalaiset ylemmän kk-tutkinnon suorittaneet\")",
              "var vuosi_check = IF(HASONEVALUE(Rahoitusmalli_korkeakoulut[rahoituksen_vuosi]),",
              "\tCALCULATE(LASTNONBLANK(Rahoitusmalli_korkeakoulut[rahoituksen_vuosi],TRUE()),",
              "\t\tFILTER(Rahoitusmalli_korkeakoulut,",
              "\t\t\tAND(NOT(ISBLANK(Rahoitusmalli_korkeakoulut[rahoituksen_vuosi])),",
              "\t\t\tRahoitusmalli_korkeakoulut[rahoituksen_vuosi]=[Rahoitusvuosi_int])",
              "\t\t\t))",
              "\t\t,BLANK())",
              "return CALCULATE(lasku,Rahoitusmalli_korkeakoulut[rahoituksen_vuosi]=vuosi_check)",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Rahoitus\\€"
          },
          {
            "name": "Tohtorin tutkinnot (perusrahoitus 1000 euroa)",
            "expression": [
              "",
              "var lasku = CALCULATE(AVERAGE(Rahoitusmalli_korkeakoulut[Rahoitus_1000_euroa]),Rahoitusmalli_korkeakoulut[Sektori]=\"Yliopisto\",Rahoitusmalli_korkeakoulut[indikaattori]=\"Tohtorin tutkinnot\")",
              "var vuosi_check = IF(HASONEVALUE(Rahoitusmalli_korkeakoulut[rahoituksen_vuosi]),",
              "\tCALCULATE(LASTNONBLANK(Rahoitusmalli_korkeakoulut[rahoituksen_vuosi],TRUE()),",
              "\t\tFILTER(Rahoitusmalli_korkeakoulut,",
              "\t\t\tAND(NOT(ISBLANK(Rahoitusmalli_korkeakoulut[rahoituksen_vuosi])),",
              "\t\t\tRahoitusmalli_korkeakoulut[rahoituksen_vuosi]=[Rahoitusvuosi_int])",
              "\t\t\t))",
              "\t\t,BLANK())",
              "return CALCULATE(lasku,Rahoitusmalli_korkeakoulut[rahoituksen_vuosi]=vuosi_check)",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Rahoitus\\€"
          },
          {
            "name": "Julkaisut (perusrahoitus 1000 euroa)",
            "expression": [
              "",
              "var lasku = CALCULATE(AVERAGE(Rahoitusmalli_korkeakoulut[Rahoitus_1000_euroa]),Rahoitusmalli_korkeakoulut[Sektori]=\"Yliopisto\",Rahoitusmalli_korkeakoulut[indikaattori]=\"Julkaisut\")",
              "var vuosi_check = IF(HASONEVALUE(Rahoitusmalli_korkeakoulut[rahoituksen_vuosi]),",
              "\tCALCULATE(LASTNONBLANK(Rahoitusmalli_korkeakoulut[rahoituksen_vuosi],TRUE()),",
              "\t\tFILTER(Rahoitusmalli_korkeakoulut,",
              "\t\t\tAND(NOT(ISBLANK(Rahoitusmalli_korkeakoulut[rahoituksen_vuosi])),",
              "\t\t\tRahoitusmalli_korkeakoulut[rahoituksen_vuosi]=[Rahoitusvuosi_int])",
              "\t\t\t))",
              "\t\t,BLANK())",
              "return CALCULATE(lasku,Rahoitusmalli_korkeakoulut[rahoituksen_vuosi]=vuosi_check)",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Rahoitus\\€"
          },
          {
            "name": "Muu kilpailtu tutkimusrahoitus (perusrahoitus 1000 euroa)",
            "expression": [
              "",
              "var lasku = CALCULATE(AVERAGE(Rahoitusmalli_korkeakoulut[Rahoitus_1000_euroa]),Rahoitusmalli_korkeakoulut[Sektori]=\"Yliopisto\",Rahoitusmalli_korkeakoulut[indikaattori]=\"Muu kilpailtu tutkimusrahoitus\")",
              "var vuosi_check = IF(HASONEVALUE(Rahoitusmalli_korkeakoulut[rahoituksen_vuosi]),",
              "\tCALCULATE(LASTNONBLANK(Rahoitusmalli_korkeakoulut[rahoituksen_vuosi],TRUE()),",
              "\t\tFILTER(Rahoitusmalli_korkeakoulut,",
              "\t\t\tAND(NOT(ISBLANK(Rahoitusmalli_korkeakoulut[rahoituksen_vuosi])),",
              "\t\t\tRahoitusmalli_korkeakoulut[rahoituksen_vuosi]=[Rahoitusvuosi_int])",
              "\t\t\t))",
              "\t\t,BLANK())",
              "return CALCULATE(lasku,Rahoitusmalli_korkeakoulut[rahoituksen_vuosi]=vuosi_check)",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Rahoitus\\€"
          },
          {
            "name": "Ulkomaalainen htv (perusrahoitus 1000 euroa)",
            "expression": [
              "",
              "var lasku = CALCULATE(AVERAGE(Rahoitusmalli_korkeakoulut[Rahoitus_1000_euroa]),Rahoitusmalli_korkeakoulut[Sektori]=\"Yliopisto\",Rahoitusmalli_korkeakoulut[indikaattori]=\"Ulkomaalaiset opetus- ja tutkimushenkilökunta\")",
              "var vuosi_check = IF(HASONEVALUE(Rahoitusmalli_korkeakoulut[rahoituksen_vuosi]),",
              "\tCALCULATE(LASTNONBLANK(Rahoitusmalli_korkeakoulut[rahoituksen_vuosi],TRUE()),",
              "\t\tFILTER(Rahoitusmalli_korkeakoulut,",
              "\t\t\tAND(NOT(ISBLANK(Rahoitusmalli_korkeakoulut[rahoituksen_vuosi])),",
              "\t\t\tRahoitusmalli_korkeakoulut[rahoituksen_vuosi]=[Rahoitusvuosi_int])",
              "\t\t\t))",
              "\t\t,BLANK())",
              "return CALCULATE(lasku,Rahoitusmalli_korkeakoulut[rahoituksen_vuosi]=vuosi_check)",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Rahoitus\\€"
          },
          {
            "name": "Opiskelijapalautteen pisteet (perusrahoitus 1000 euroa)",
            "expression": [
              "",
              "var lasku = CALCULATE(AVERAGE(Rahoitusmalli_korkeakoulut[Rahoitus_1000_euroa]),Rahoitusmalli_korkeakoulut[Sektori]=\"Yliopisto\",Rahoitusmalli_korkeakoulut[indikaattori]=\"Opiskelijapalaute\")",
              "var vuosi_check = IF(HASONEVALUE(Rahoitusmalli_korkeakoulut[rahoituksen_vuosi]),",
              "\tCALCULATE(LASTNONBLANK(Rahoitusmalli_korkeakoulut[rahoituksen_vuosi],TRUE()),",
              "\t\tFILTER(Rahoitusmalli_korkeakoulut,",
              "\t\t\tAND(NOT(ISBLANK(Rahoitusmalli_korkeakoulut[rahoituksen_vuosi])),",
              "\t\t\tRahoitusmalli_korkeakoulut[rahoituksen_vuosi]=[Rahoitusvuosi_int])",
              "\t\t\t))",
              "\t\t,BLANK())",
              "return CALCULATE(lasku,Rahoitusmalli_korkeakoulut[rahoituksen_vuosi]=vuosi_check)",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Rahoitus\\€"
          },
          {
            "name": "Työlliset 1v valmistumisesta (perusrahoitus 1000 euroa)",
            "expression": [
              "",
              "var lasku = CALCULATE(AVERAGE(Rahoitusmalli_korkeakoulut[Rahoitus_1000_euroa]),Rahoitusmalli_korkeakoulut[Sektori]=\"Yliopisto\",Rahoitusmalli_korkeakoulut[indikaattori]=\"Työllistyneet ylemmän kk-tutkinnon suorittaneet\")",
              "var vuosi_check = IF(HASONEVALUE(Rahoitusmalli_korkeakoulut[rahoituksen_vuosi]),",
              "\tCALCULATE(LASTNONBLANK(Rahoitusmalli_korkeakoulut[rahoituksen_vuosi],TRUE()),",
              "\t\tFILTER(Rahoitusmalli_korkeakoulut,",
              "\t\t\tAND(NOT(ISBLANK(Rahoitusmalli_korkeakoulut[rahoituksen_vuosi])),",
              "\t\t\tRahoitusmalli_korkeakoulut[rahoituksen_vuosi]=[Rahoitusvuosi_int])",
              "\t\t\t))",
              "\t\t,BLANK())",
              "return CALCULATE(lasku,Rahoitusmalli_korkeakoulut[rahoituksen_vuosi]=vuosi_check)",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Rahoitus\\€"
          },
          {
            "name": "Ulkomainen kilpailtu tutkimusrahoitus (perusrahoitus 1000 euroa)",
            "expression": [
              "",
              "var lasku = CALCULATE(AVERAGE(Rahoitusmalli_korkeakoulut[Rahoitus_1000_euroa]),Rahoitusmalli_korkeakoulut[Sektori]=\"Yliopisto\",Rahoitusmalli_korkeakoulut[indikaattori]=\"Kansainvälinen rahoitus\")",
              "var vuosi_check = IF(HASONEVALUE(Rahoitusmalli_korkeakoulut[rahoituksen_vuosi]),",
              "\tCALCULATE(LASTNONBLANK(Rahoitusmalli_korkeakoulut[rahoituksen_vuosi],TRUE()),",
              "\t\tFILTER(Rahoitusmalli_korkeakoulut,",
              "\t\t\tAND(NOT(ISBLANK(Rahoitusmalli_korkeakoulut[rahoituksen_vuosi])),",
              "\t\t\tRahoitusmalli_korkeakoulut[rahoituksen_vuosi]=[Rahoitusvuosi_int])",
              "\t\t\t))",
              "\t\t,BLANK())",
              "return CALCULATE(lasku,Rahoitusmalli_korkeakoulut[rahoituksen_vuosi]=vuosi_check)",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Rahoitus\\€"
          },
          {
            "name": "Alempi korkeakoulututkinto (osuus rahoituksessa)",
            "expression": [
              "  CALCULATE(AVERAGE(Rahoitusmalli_korkeakoulut[osuus_rahoituksesta]),Rahoitusmalli_korkeakoulut[Sektori]=\"Yliopisto\",Rahoitusmalli_korkeakoulut[indikaattori]=\"Alemmat korkeakoulututkinnot\")",
              ""
            ],
            "formatString": "0 %;-0 %;0 %",
            "displayFolder": "Rahoitus\\%"
          },
          {
            "name": "Ylempi korkeakoulututkinto (osuus rahoituksessa)",
            "expression": [
              " CALCULATE(AVERAGE(Rahoitusmalli_korkeakoulut[osuus_rahoituksesta]),Rahoitusmalli_korkeakoulut[Sektori]=\"Yliopisto\",Rahoitusmalli_korkeakoulut[indikaattori]=\"Ylemmät korkeakoulututkinnot\")",
              ""
            ],
            "formatString": "0 %;-0 %;0 %",
            "displayFolder": "Rahoitus\\%"
          },
          {
            "name": "Suorittanut 55 (osuus rahoituksessa)",
            "expression": [
              "CALCULATE(AVERAGE(Rahoitusmalli_korkeakoulut[osuus_rahoituksesta]),Rahoitusmalli_korkeakoulut[Sektori]=\"Yliopisto\",Rahoitusmalli_korkeakoulut[indikaattori]=\"55 opintopistettä suorittaneet\")",
              ""
            ],
            "formatString": "0 %;-0 %;0 %",
            "displayFolder": "Rahoitus\\%"
          },
          {
            "name": "Erilliset opinto-oikeudet (osuus rahoituksessa)",
            "expression": [
              " CALCULATE(AVERAGE(Rahoitusmalli_korkeakoulut[osuus_rahoituksesta]),Rahoitusmalli_korkeakoulut[Sektori]=\"Yliopisto\",Rahoitusmalli_korkeakoulut[indikaattori]=\"Avoin yo-opetus ja erilliset opinnot opintopisteet ym.\")",
              ""
            ],
            "formatString": "0 %;-0 %;0 %",
            "displayFolder": "Rahoitus\\%"
          },
          {
            "name": "Ulkomailla suoritetut ja kv vaihto-opiskelijoiden pisteet (osuus rahoituksessa)",
            "expression": [
              " CALCULATE(AVERAGE(Rahoitusmalli_korkeakoulut[osuus_rahoituksesta]),Rahoitusmalli_korkeakoulut[Sektori]=\"Yliopisto\",Rahoitusmalli_korkeakoulut[indikaattori]=\"Vaihto-opiskelu, opintopisteet\")",
              ""
            ],
            "formatString": "0 %;-0 %;0 %",
            "displayFolder": "Rahoitus\\%"
          },
          {
            "name": "Ulkomaalaisten ylemmät kk-tutkinnot (osuus rahoituksessa)",
            "expression": [
              " CALCULATE(AVERAGE(Rahoitusmalli_korkeakoulut[osuus_rahoituksesta]),Rahoitusmalli_korkeakoulut[Sektori]=\"Yliopisto\",Rahoitusmalli_korkeakoulut[indikaattori]=\"Ulkomaalaiset ylemmän kk-tutkinnon suorittaneet\")",
              ""
            ],
            "formatString": "0 %;-0 %;0 %",
            "displayFolder": "Rahoitus\\%"
          },
          {
            "name": "Tohtorin tutkinnot (osuus rahoituksessa)",
            "expression": [
              "CALCULATE(AVERAGE(Rahoitusmalli_korkeakoulut[osuus_rahoituksesta]),Rahoitusmalli_korkeakoulut[Sektori]=\"Yliopisto\",Rahoitusmalli_korkeakoulut[indikaattori]=\"Tohtorin tutkinnot\")",
              ""
            ],
            "formatString": "0 %;-0 %;0 %",
            "displayFolder": "Rahoitus\\%"
          },
          {
            "name": "Julkaisut (osuus rahoituksessa)",
            "expression": [
              "CALCULATE(AVERAGE(Rahoitusmalli_korkeakoulut[osuus_rahoituksesta]),Rahoitusmalli_korkeakoulut[Sektori]=\"Yliopisto\",Rahoitusmalli_korkeakoulut[indikaattori]=\"Julkaisut\")",
              ""
            ],
            "formatString": "0 %;-0 %;0 %",
            "displayFolder": "Rahoitus\\%"
          },
          {
            "name": "Muu kilpailtu tutkimusrahoitus (osuus rahoituksessa)",
            "expression": [
              " CALCULATE(AVERAGE(Rahoitusmalli_korkeakoulut[osuus_rahoituksesta]),Rahoitusmalli_korkeakoulut[Sektori]=\"Yliopisto\",Rahoitusmalli_korkeakoulut[indikaattori]=\"Muu kilpailtu tutkimusrahoitus\")",
              ""
            ],
            "formatString": "0 %;-0 %;0 %",
            "displayFolder": "Rahoitus\\%"
          },
          {
            "name": "Ulkomaalainen htv (osuus rahoituksessa)",
            "expression": [
              " CALCULATE(AVERAGE(Rahoitusmalli_korkeakoulut[osuus_rahoituksesta]),Rahoitusmalli_korkeakoulut[Sektori]=\"Yliopisto\",Rahoitusmalli_korkeakoulut[indikaattori]=\"Ulkomaalaiset opetus- ja tutkimushenkilökunta\")",
              ""
            ],
            "formatString": "0 %;-0 %;0 %",
            "displayFolder": "Rahoitus\\%"
          },
          {
            "name": "Opiskelijapalautteen pisteet (osuus rahoituksessa)",
            "expression": [
              " CALCULATE(AVERAGE(Rahoitusmalli_korkeakoulut[osuus_rahoituksesta]),Rahoitusmalli_korkeakoulut[Sektori]=\"Yliopisto\",Rahoitusmalli_korkeakoulut[indikaattori]=\"Opiskelijapalaute\")",
              ""
            ],
            "formatString": "0 %;-0 %;0 %",
            "displayFolder": "Rahoitus\\%"
          },
          {
            "name": "Työlliset 1v valmistumisesta (osuus rahoituksessa)",
            "expression": [
              " CALCULATE(AVERAGE(Rahoitusmalli_korkeakoulut[osuus_rahoituksesta]),Rahoitusmalli_korkeakoulut[Sektori]=\"Yliopisto\",Rahoitusmalli_korkeakoulut[indikaattori]=\"Työllistyneet ylemmän kk-tutkinnon suorittaneet\")",
              ""
            ],
            "formatString": "0 %;-0 %;0 %",
            "displayFolder": "Rahoitus\\%"
          },
          {
            "name": "Ulkomainen kilpailtu tutkimusrahoitus (osuus rahoituksessa)",
            "expression": [
              " CALCULATE(AVERAGE(Rahoitusmalli_korkeakoulut[osuus_rahoituksesta]),Rahoitusmalli_korkeakoulut[Sektori]=\"Yliopisto\",Rahoitusmalli_korkeakoulut[indikaattori]=\"Kansainvälinen rahoitus\")",
              ""
            ],
            "formatString": "0 %;-0 %;0 %",
            "displayFolder": "Rahoitus\\%"
          },
          {
            "name": "Alempi korkeakoulututkinto (osuus perusrahoituksesta 1000€)",
            "expression": " CALCULATE([Alempi korkeakoulututkinto (%)]*[Alempi korkeakoulututkinto (perusrahoitus 1000 euroa)])",
            "formatString": "#,0",
            "displayFolder": "Perusrahoituksen osuus"
          },
          {
            "name": "Ylempi korkeakoulututkinto (osuus perusrahoituksesta 1000€)",
            "expression": " CALCULATE([Ylempi korkeakoulututkinto (%)]*[Ylempi korkeakoulututkinto (perusrahoitus 1000 euroa)])",
            "formatString": "#,0",
            "displayFolder": "Perusrahoituksen osuus"
          },
          {
            "name": "Suorittanut 55 (osuus perusrahoituksesta 1000€)",
            "expression": " CALCULATE([Suorittanut 55 rahoitusmalli (%)]*[Suorittanut 55 (perusrahoitus 1000 euroa)])",
            "formatString": "#,0",
            "displayFolder": "Perusrahoituksen osuus"
          },
          {
            "name": "Erilliset opinto-oikeudet (osuus perusrahoituksesta 1000€)",
            "expression": "CALCULATE([Erilliset opinto-oikeudet (%)]*[Erilliset opinto-oikeudet (perusrahoitus 1000 euroa)])",
            "formatString": "#,0",
            "displayFolder": "Perusrahoituksen osuus"
          },
          {
            "name": "Ulkomailla suoritetut ja kv vaihto-opiskelijoiden pisteet (osuus perusrahoituksesta 1000€)",
            "expression": " CALCULATE([Ulkomailla suoritetut ja kv vaihto-opiskelijoiden pisteet (%)]*[Ulkomailla suoritetut ja kv vaihto-opiskelijoiden pisteet (perusrahoitus 1000 euroa)])",
            "formatString": "#,0",
            "displayFolder": "Perusrahoituksen osuus"
          },
          {
            "name": "Ulkomaalaisten ylemmät kk-tutkinnot (osuus perusrahoituksesta 1000€)",
            "expression": " CALCULATE([Ulkomaalaisten ylemmät kk-tutkinnot (%)]*[Ulkomaalaisten ylemmät kk-tutkinnot (perusrahoitus 1000 euroa)])",
            "formatString": "#,0",
            "displayFolder": "Perusrahoituksen osuus"
          },
          {
            "name": "Tohtorin tutkinnot (osuus perusrahoituksesta 1000€)",
            "expression": " CALCULATE([Tohtorin tutkinnot (%)]*[Tohtorin tutkinnot (perusrahoitus 1000 euroa)])",
            "formatString": "#,0",
            "displayFolder": "Perusrahoituksen osuus"
          },
          {
            "name": "Julkaisut (osuus perusrahoituksesta 1000€)",
            "expression": " CALCULATE([Julkaisut rahoitusmalli (%)]*[Julkaisut (perusrahoitus 1000 euroa)])",
            "formatString": "#,0",
            "displayFolder": "Perusrahoituksen osuus"
          },
          {
            "name": "Muu kilpailtu tutkimusrahoitus (osuus perusrahoituksesta 1000€)",
            "expression": "CALCULATE([Muu kilpailtu tutkimusrahoitus (%)]*[Muu kilpailtu tutkimusrahoitus (perusrahoitus 1000 euroa)])",
            "formatString": "#,0",
            "displayFolder": "Perusrahoituksen osuus"
          },
          {
            "name": "Ulkomaalainen htv (osuus perusrahoituksesta 1000€)",
            "expression": "CALCULATE([Ulkomaalainen htv (%)]*[Ulkomaalainen htv (perusrahoitus 1000 euroa)])",
            "formatString": "#,0",
            "displayFolder": "Perusrahoituksen osuus"
          },
          {
            "name": "Opiskelijapalautteen pisteet (osuus perusrahoituksesta 1000€)",
            "expression": " CALCULATE([Opiskelijapalautteen pisteet (%)]*[Opiskelijapalautteen pisteet (perusrahoitus 1000 euroa)])",
            "formatString": "#,0",
            "displayFolder": "Perusrahoituksen osuus"
          },
          {
            "name": "Työlliset 1v valmistumisesta (osuus perusrahoituksesta 1000€)",
            "expression": " CALCULATE([Työlliset 1v valmistumisesta (%)]*[Työlliset 1v valmistumisesta (perusrahoitus 1000 euroa)])",
            "formatString": "#,0",
            "displayFolder": "Perusrahoituksen osuus"
          },
          {
            "name": "Ulkomainen kilpailtu tutkimusrahoitus (osuus perusrahoituksesta 1000€)",
            "expression": "CALCULATE([Ulkomainen kilpailtu tutkimusrahoitus (%)]*[Ulkomainen kilpailtu tutkimusrahoitus (perusrahoitus 1000 euroa)])",
            "formatString": "#,0",
            "displayFolder": "Perusrahoituksen osuus"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dw].[v_kk_rahoitusmalli_yo].* FROM [dw].[v_kk_rahoitusmalli_yo] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "v_kk_rahoitusmalli_yo"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dw"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Tilastovuosi</string>",
              "      </key>",
              "      <value>",
              "        <int>86</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Organisaatio</string>",
              "      </key>",
              "      <value>",
              "        <int>91</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Sektori</string>",
              "      </key>",
              "      <value>",
              "        <int>63</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusnimike</string>",
              "      </key>",
              "      <value>",
              "        <int>100</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusaste 2002</string>",
              "      </key>",
              "      <value>",
              "        <int>119</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>OKM ohjauksen ala</string>",
              "      </key>",
              "      <value>",
              "        <int>121</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Rahoitusmalliala, amk</string>",
              "      </key>",
              "      <value>",
              "        <int>132</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Rahoitusmalliala, yo</string>",
              "      </key>",
              "      <value>",
              "        <int>125</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusaste, taso 1</string>",
              "      </key>",
              "      <value>",
              "        <int>129</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusaste, taso 2</string>",
              "      </key>",
              "      <value>",
              "        <int>129</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusala, taso 1</string>",
              "      </key>",
              "      <value>",
              "        <int>122</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusala, taso 2</string>",
              "      </key>",
              "      <value>",
              "        <int>122</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusala, taso 3</string>",
              "      </key>",
              "      <value>",
              "        <int>122</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tutkinnon aloitussykli</string>",
              "      </key>",
              "      <value>",
              "        <int>131</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Päätieteenala</string>",
              "      </key>",
              "      <value>",
              "        <int>96</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tieteenala</string>",
              "      </key>",
              "      <value>",
              "        <int>80</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tieteenala_avain</string>",
              "      </key>",
              "      <value>",
              "        <int>112</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tutkijanuravaihe</string>",
              "      </key>",
              "      <value>",
              "        <int>110</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kunta</string>",
              "      </key>",
              "      <value>",
              "        <int>58</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kansalaisuus</string>",
              "      </key>",
              "      <value>",
              "        <int>91</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tutkinnot</string>",
              "      </key>",
              "      <value>",
              "        <int>73</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Läsnäolevat opiskelijat (55op)</string>",
              "      </key>",
              "      <value>",
              "        <int>173</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>55op suorittaneet</string>",
              "      </key>",
              "      <value>",
              "        <int>116</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Suorittanut27</string>",
              "      </key>",
              "      <value>",
              "        <int>96</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>suorittanut55ilmanPankkia</string>",
              "      </key>",
              "      <value>",
              "        <int>155</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>suorittanut55pankinAvulla</string>",
              "      </key>",
              "      <value>",
              "        <int>155</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Läsnäolleet opiskelijat (1-14op)</string>",
              "      </key>",
              "      <value>",
              "        <int>179</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>1-14op suorittaneet</string>",
              "      </key>",
              "      <value>",
              "        <int>126</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Yliopiston opetus- ja tutkimushenkilötyövuodet</string>",
              "      </key>",
              "      <value>",
              "        <int>253</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>IV tutkijanuraportaan henkilötyövuodet</string>",
              "      </key>",
              "      <value>",
              "        <int>219</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>JulkaisuID</string>",
              "      </key>",
              "      <value>",
              "        <int>78</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Jufotaso</string>",
              "      </key>",
              "      <value>",
              "        <int>72</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Julkaisutyyppi</string>",
              "      </key>",
              "      <value>",
              "        <int>97</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ulk. kilpailtu tutkimusrahoitus</string>",
              "      </key>",
              "      <value>",
              "        <int>168</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>kv_vaihtoopiskelijat_op_lkm</string>",
              "      </key>",
              "      <value>",
              "        <int>163</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ulkom_hyv_luetut_op_lkm</string>",
              "      </key>",
              "      <value>",
              "        <int>154</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ulkom_harj_op_lkm</string>",
              "      </key>",
              "      <value>",
              "        <int>121</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>avoin_op__lkm</string>",
              "      </key>",
              "      <value>",
              "        <int>101</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>kk_yhteistyo_op_lkm</string>",
              "      </key>",
              "      <value>",
              "        <int>130</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>erilopintooik_op_lkm</string>",
              "      </key>",
              "      <value>",
              "        <int>126</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>erillisilla_oik_opkoul_op_lkm</string>",
              "      </key>",
              "      <value>",
              "        <int>160</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>erikoul_suor_op_lkm</string>",
              "      </key>",
              "      <value>",
              "        <int>127</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>sijoittuminen_1v_tutkinnon_jalkeen</string>",
              "      </key>",
              "      <value>",
              "        <int>199</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>työlliset 1v tutkinnon jälkeen</string>",
              "      </key>",
              "      <value>",
              "        <int>167</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>sijoittuminen_3v_tutkinnon_jalkeen</string>",
              "      </key>",
              "      <value>",
              "        <int>199</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Työlliset 3v tutkinnon jälkeen</string>",
              "      </key>",
              "      <value>",
              "        <int>169</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Työlliset 3v (ver2 10,13)</string>",
              "      </key>",
              "      <value>",
              "        <int>148</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Työttömät 3v (ver2, 12)</string>",
              "      </key>",
              "      <value>",
              "        <int>147</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Opiskelijapalautepisteet</string>",
              "      </key>",
              "      <value>",
              "        <int>144</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Läsnä syksy</string>",
              "      </key>",
              "      <value>",
              "        <int>88</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Läsnä kevät</string>",
              "      </key>",
              "      <value>",
              "        <int>88</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit OKM ohjauksen ala</string>",
              "      </key>",
              "      <value>",
              "        <int>154</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit Koulutusnimike</string>",
              "      </key>",
              "      <value>",
              "        <int>133</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit organisaatio</string>",
              "      </key>",
              "      <value>",
              "        <int>122</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit kunta</string>",
              "      </key>",
              "      <value>",
              "        <int>90</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj. koulutusaste, taso 1</string>",
              "      </key>",
              "      <value>",
              "        <int>151</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj. koulutusaste, taso 2</string>",
              "      </key>",
              "      <value>",
              "        <int>151</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj. OKM ohjauksen ala</string>",
              "      </key>",
              "      <value>",
              "        <int>144</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj. rahoitusmalliala amk</string>",
              "      </key>",
              "      <value>",
              "        <int>148</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj. rahoitusmalliala yo</string>",
              "      </key>",
              "      <value>",
              "        <int>141</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj. paatieteenala</string>",
              "      </key>",
              "      <value>",
              "        <int>119</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj. tieteenala</string>",
              "      </key>",
              "      <value>",
              "        <int>101</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kilpailtu tutkimusrahoitus rah_malli</string>",
              "      </key>",
              "      <value>",
              "        <int>193</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Työlliset 1v (ver2 10,13)</string>",
              "      </key>",
              "      <value>",
              "        <int>148</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Julkaisut lukumaara</string>",
              "      </key>",
              "      <value>",
              "        <int>123</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tilastovuosi - rahoitusmalli</string>",
              "      </key>",
              "      <value>",
              "        <int>155</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Tilastovuosi</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Organisaatio</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Sektori</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusnimike</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusaste 2002</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>OKM ohjauksen ala</string>",
              "      </key>",
              "      <value>",
              "        <int>5</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Rahoitusmalliala, amk</string>",
              "      </key>",
              "      <value>",
              "        <int>6</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Rahoitusmalliala, yo</string>",
              "      </key>",
              "      <value>",
              "        <int>7</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusaste, taso 1</string>",
              "      </key>",
              "      <value>",
              "        <int>8</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusaste, taso 2</string>",
              "      </key>",
              "      <value>",
              "        <int>9</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusala, taso 1</string>",
              "      </key>",
              "      <value>",
              "        <int>10</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusala, taso 2</string>",
              "      </key>",
              "      <value>",
              "        <int>11</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusala, taso 3</string>",
              "      </key>",
              "      <value>",
              "        <int>12</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tutkinnon aloitussykli</string>",
              "      </key>",
              "      <value>",
              "        <int>13</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Päätieteenala</string>",
              "      </key>",
              "      <value>",
              "        <int>14</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tieteenala</string>",
              "      </key>",
              "      <value>",
              "        <int>15</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tieteenala_avain</string>",
              "      </key>",
              "      <value>",
              "        <int>16</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tutkijanuravaihe</string>",
              "      </key>",
              "      <value>",
              "        <int>17</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kunta</string>",
              "      </key>",
              "      <value>",
              "        <int>18</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kansalaisuus</string>",
              "      </key>",
              "      <value>",
              "        <int>19</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tutkinnot</string>",
              "      </key>",
              "      <value>",
              "        <int>20</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Läsnäolevat opiskelijat (55op)</string>",
              "      </key>",
              "      <value>",
              "        <int>21</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>55op suorittaneet</string>",
              "      </key>",
              "      <value>",
              "        <int>22</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Suorittanut27</string>",
              "      </key>",
              "      <value>",
              "        <int>23</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>suorittanut55ilmanPankkia</string>",
              "      </key>",
              "      <value>",
              "        <int>24</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>suorittanut55pankinAvulla</string>",
              "      </key>",
              "      <value>",
              "        <int>25</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Läsnäolleet opiskelijat (1-14op)</string>",
              "      </key>",
              "      <value>",
              "        <int>26</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>1-14op suorittaneet</string>",
              "      </key>",
              "      <value>",
              "        <int>27</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Yliopiston opetus- ja tutkimushenkilötyövuodet</string>",
              "      </key>",
              "      <value>",
              "        <int>28</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>IV tutkijanuraportaan henkilötyövuodet</string>",
              "      </key>",
              "      <value>",
              "        <int>29</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>JulkaisuID</string>",
              "      </key>",
              "      <value>",
              "        <int>30</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Jufotaso</string>",
              "      </key>",
              "      <value>",
              "        <int>31</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Julkaisutyyppi</string>",
              "      </key>",
              "      <value>",
              "        <int>32</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ulk. kilpailtu tutkimusrahoitus</string>",
              "      </key>",
              "      <value>",
              "        <int>61</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>kv_vaihtoopiskelijat_op_lkm</string>",
              "      </key>",
              "      <value>",
              "        <int>33</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ulkom_hyv_luetut_op_lkm</string>",
              "      </key>",
              "      <value>",
              "        <int>34</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ulkom_harj_op_lkm</string>",
              "      </key>",
              "      <value>",
              "        <int>35</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>avoin_op__lkm</string>",
              "      </key>",
              "      <value>",
              "        <int>36</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>kk_yhteistyo_op_lkm</string>",
              "      </key>",
              "      <value>",
              "        <int>37</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>erilopintooik_op_lkm</string>",
              "      </key>",
              "      <value>",
              "        <int>38</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>erillisilla_oik_opkoul_op_lkm</string>",
              "      </key>",
              "      <value>",
              "        <int>39</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>erikoul_suor_op_lkm</string>",
              "      </key>",
              "      <value>",
              "        <int>40</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>sijoittuminen_1v_tutkinnon_jalkeen</string>",
              "      </key>",
              "      <value>",
              "        <int>41</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>työlliset 1v tutkinnon jälkeen</string>",
              "      </key>",
              "      <value>",
              "        <int>42</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>sijoittuminen_3v_tutkinnon_jalkeen</string>",
              "      </key>",
              "      <value>",
              "        <int>43</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Työlliset 3v tutkinnon jälkeen</string>",
              "      </key>",
              "      <value>",
              "        <int>44</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Työlliset 3v (ver2 10,13)</string>",
              "      </key>",
              "      <value>",
              "        <int>45</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Työttömät 3v (ver2, 12)</string>",
              "      </key>",
              "      <value>",
              "        <int>46</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Opiskelijapalautepisteet</string>",
              "      </key>",
              "      <value>",
              "        <int>65</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Läsnä syksy</string>",
              "      </key>",
              "      <value>",
              "        <int>60</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Läsnä kevät</string>",
              "      </key>",
              "      <value>",
              "        <int>59</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit OKM ohjauksen ala</string>",
              "      </key>",
              "      <value>",
              "        <int>47</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit Koulutusnimike</string>",
              "      </key>",
              "      <value>",
              "        <int>48</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit organisaatio</string>",
              "      </key>",
              "      <value>",
              "        <int>49</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit kunta</string>",
              "      </key>",
              "      <value>",
              "        <int>50</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj. koulutusaste, taso 1</string>",
              "      </key>",
              "      <value>",
              "        <int>51</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj. koulutusaste, taso 2</string>",
              "      </key>",
              "      <value>",
              "        <int>52</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj. OKM ohjauksen ala</string>",
              "      </key>",
              "      <value>",
              "        <int>53</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj. rahoitusmalliala amk</string>",
              "      </key>",
              "      <value>",
              "        <int>54</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj. rahoitusmalliala yo</string>",
              "      </key>",
              "      <value>",
              "        <int>55</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj. paatieteenala</string>",
              "      </key>",
              "      <value>",
              "        <int>56</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj. tieteenala</string>",
              "      </key>",
              "      <value>",
              "        <int>57</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kilpailtu tutkimusrahoitus rah_malli</string>",
              "      </key>",
              "      <value>",
              "        <int>58</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Työlliset 1v (ver2 10,13)</string>",
              "      </key>",
              "      <value>",
              "        <int>62</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Julkaisut lukumaara</string>",
              "      </key>",
              "      <value>",
              "        <int>63</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tilastovuosi - rahoitusmalli</string>",
              "      </key>",
              "      <value>",
              "        <int>64</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Suorittanut27</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>suorittanut55ilmanPankkia</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>suorittanut55pankinAvulla</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tilastovuosi</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Organisaatio</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Sektori</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusnimike</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusaste 2002</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>OKM ohjauksen ala</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Rahoitusmalliala, amk</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Rahoitusmalliala, yo</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusaste, taso 1</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusaste, taso 2</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusala, taso 1</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusala, taso 2</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusala, taso 3</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tutkinnon aloitussykli</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Päätieteenala</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tieteenala</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tieteenala_avain</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tutkijanuravaihe</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kunta</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kansalaisuus</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tutkinnot</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Läsnäolevat opiskelijat (55op)</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>55op suorittaneet</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Läsnäolleet opiskelijat (1-14op)</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>1-14op suorittaneet</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Yliopiston opetus- ja tutkimushenkilötyövuodet</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>IV tutkijanuraportaan henkilötyövuodet</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>JulkaisuID</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Jufotaso</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Julkaisutyyppi</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ulk. kilpailtu tutkimusrahoitus</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>kv_vaihtoopiskelijat_op_lkm</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ulkom_hyv_luetut_op_lkm</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ulkom_harj_op_lkm</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>avoin_op__lkm</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>kk_yhteistyo_op_lkm</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>erilopintooik_op_lkm</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>erillisilla_oik_opkoul_op_lkm</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>erikoul_suor_op_lkm</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>sijoittuminen_1v_tutkinnon_jalkeen</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>työlliset 1v tutkinnon jälkeen</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>sijoittuminen_3v_tutkinnon_jalkeen</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Työlliset 3v tutkinnon jälkeen</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Työlliset 3v (ver2 10,13)</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Työttömät 3v (ver2, 12)</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Opiskelijapalautepisteet</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Läsnä syksy</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Läsnä kevät</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit OKM ohjauksen ala</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit Koulutusnimike</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit organisaatio</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit kunta</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj. koulutusaste, taso 1</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj. koulutusaste, taso 2</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj. OKM ohjauksen ala</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj. rahoitusmalliala amk</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj. rahoitusmalliala yo</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj. paatieteenala</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>jarj. tieteenala</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kilpailtu tutkimusrahoitus rah_malli</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Työlliset 1v (ver2 10,13)</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Julkaisut lukumaara</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tilastovuosi - rahoitusmalli</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "t3 - amk",
        "isHidden": true,
        "columns": [
          {
            "name": "Tilastovuosi",
            "dataType": "int64",
            "sourceColumn": "Tilastovuosi",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Organisaatio",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Organisaatio",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "Sektori",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Sektori",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "Koulutusnimike",
            "dataType": "string",
            "sourceColumn": "Koulutusnimike",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "Koulutusaste 2002",
            "dataType": "string",
            "sourceColumn": "Koulutusaste 2002",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "OKM ohjauksen ala",
            "dataType": "string",
            "sourceColumn": "OKM ohjauksen ala",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "Rahoitusmalliala, amk",
            "dataType": "string",
            "sourceColumn": "Rahoitusmalliala, amk",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "Rahoitusmalliala, yo",
            "dataType": "string",
            "sourceColumn": "Rahoitusmalliala, yo",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "Koulutusaste, taso 1",
            "dataType": "string",
            "sourceColumn": "Koulutusaste, taso 1",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "Koulutusaste, taso 2",
            "dataType": "string",
            "sourceColumn": "Koulutusaste, taso 2",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "Koulutusala, taso 1",
            "dataType": "string",
            "sourceColumn": "Koulutusala, taso 1",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "Koulutusala, taso 2",
            "dataType": "string",
            "sourceColumn": "Koulutusala, taso 2",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "Koulutusala, taso 3",
            "dataType": "string",
            "sourceColumn": "Koulutusala, taso 3",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "Päätieteenala",
            "dataType": "string",
            "sourceColumn": "Päätieteenala",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "Tieteenala",
            "dataType": "string",
            "sourceColumn": "Tieteenala",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "Tieteenala_avain",
            "dataType": "string",
            "sourceColumn": "Tieteenala_avain",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "Kunta",
            "dataType": "string",
            "sourceColumn": "Kunta",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "Kansalaisuus",
            "dataType": "string",
            "sourceColumn": "Kansalaisuus",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "tutkinnot",
            "dataType": "int64",
            "sourceColumn": "tutkinnot",
            "sourceProviderType": "Integer"
          },
          {
            "name": "koulutustyyppi",
            "dataType": "string",
            "sourceColumn": "koulutustyyppi",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "Läsnäolevat opiskelijat (55op)",
            "dataType": "int64",
            "sourceColumn": "Läsnäolevat opiskelijat (55op)",
            "sourceProviderType": "Integer"
          },
          {
            "name": "55op suorittaneet",
            "dataType": "int64",
            "sourceColumn": "55op suorittaneet",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Suorittanut27",
            "dataType": "int64",
            "sourceColumn": "Suorittanut27",
            "sourceProviderType": "Integer"
          },
          {
            "name": "suorittanut55ilmanPankkia",
            "dataType": "int64",
            "sourceColumn": "suorittanut55ilmanPankkia",
            "sourceProviderType": "Integer"
          },
          {
            "name": "suorittanut55pankinAvulla",
            "dataType": "int64",
            "sourceColumn": "suorittanut55pankinAvulla",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Läsnäolleet opiskelijat (1-14op)",
            "dataType": "int64",
            "sourceColumn": "Läsnäolleet opiskelijat (1-14op)",
            "sourceProviderType": "Integer"
          },
          {
            "name": "1-14op suorittaneet",
            "dataType": "int64",
            "sourceColumn": "1-14op suorittaneet",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Läsnä kevät",
            "dataType": "int64",
            "sourceColumn": "Läsnä kevät",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Läsnä syksy",
            "dataType": "int64",
            "sourceColumn": "Läsnä syksy",
            "sourceProviderType": "Integer"
          },
          {
            "name": "JulkaisuID",
            "dataType": "string",
            "sourceColumn": "JulkaisuID",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "Jufotaso",
            "dataType": "int64",
            "sourceColumn": "Jufotaso",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Julkaisutyyppi",
            "dataType": "string",
            "sourceColumn": "Julkaisutyyppi",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "AMK Julkaisut (A-F)",
            "dataType": "double",
            "sourceColumn": "AMK Julkaisut (A-F)",
            "sourceProviderType": "Decimal"
          },
          {
            "name": "Amk julkaisut (F-I, st)",
            "dataType": "int64",
            "sourceColumn": "Amk julkaisut (F-I, st)",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Ulkopuolinen tutkimusrahoitus",
            "dataType": "double",
            "sourceColumn": "Ulkopuolinen tutkimusrahoitus",
            "sourceProviderType": "Decimal"
          },
          {
            "name": "kv_vaihtoopiskelijat_op_lkm",
            "dataType": "int64",
            "sourceColumn": "kv_vaihtoopiskelijat_op_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "ulkom_hyv_luetut_op_lkm",
            "dataType": "int64",
            "sourceColumn": "ulkom_hyv_luetut_op_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "ulkom_harj_op_lkm",
            "dataType": "int64",
            "sourceColumn": "ulkom_harj_op_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "avoin_op__lkm",
            "dataType": "int64",
            "sourceColumn": "avoin_op__lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "kk_yhteistyo_op_lkm",
            "dataType": "int64",
            "sourceColumn": "kk_yhteistyo_op_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "erilopintooik_op_lkm",
            "dataType": "int64",
            "sourceColumn": "erilopintooik_op_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "erikoul_suor_op_lkm",
            "dataType": "int64",
            "sourceColumn": "erikoul_suor_op_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "mamu_op_lkm",
            "dataType": "int64",
            "sourceColumn": "mamu_op_lkm",
            "sourceProviderType": "Integer"
          },
          {
            "name": "sijoittuminen_1v_tutkinnon_jalkeen",
            "dataType": "int64",
            "sourceColumn": "sijoittuminen_1v_tutkinnon_jalkeen",
            "sourceProviderType": "Integer"
          },
          {
            "name": "työlliset 1v tutkinnon jälkeen",
            "dataType": "int64",
            "sourceColumn": "työlliset 1v tutkinnon jälkeen",
            "sourceProviderType": "Integer"
          },
          {
            "name": "sijoittuminen_3v_tutkinnon_jalkeen",
            "dataType": "int64",
            "sourceColumn": "sijoittuminen_3v_tutkinnon_jalkeen",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Työlliset 3v tutkinnon jälkeen",
            "dataType": "int64",
            "sourceColumn": "Työlliset 3v tutkinnon jälkeen",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Työlliset 3v (ver2 10,13)",
            "dataType": "int64",
            "sourceColumn": "Työlliset 3v (ver2 10,13)",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Työttömät 3v (ver2, 12)",
            "dataType": "int64",
            "sourceColumn": "Työttömät 3v (ver2, 12)",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Pääasiallinen toiminta okm",
            "dataType": "string",
            "sourceColumn": "Pääasiallinen toiminta okm",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "Pääasiallinen toiminta versio 2",
            "dataType": "string",
            "sourceColumn": "Pääasiallinen toiminta versio 2",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "Ammattiasema",
            "dataType": "string",
            "sourceColumn": "Ammattiasema",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "Liikkuvuusohjelma",
            "dataType": "string",
            "sourceColumn": "Liikkuvuusohjelma",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "Liikkuvuuden tyyppi",
            "dataType": "string",
            "sourceColumn": "Liikkuvuuden tyyppi",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "Liikkuvuuden kesto saapuva",
            "dataType": "double",
            "sourceColumn": "Liikkuvuuden kesto saapuva",
            "sourceProviderType": "Decimal"
          },
          {
            "name": "Liikkuvuuden kesto lähtevä",
            "dataType": "double",
            "sourceColumn": "Liikkuvuuden kesto lähtevä",
            "sourceProviderType": "Decimal"
          },
          {
            "name": "Koodit OKM ohjauksen ala",
            "dataType": "string",
            "sourceColumn": "Koodit OKM ohjauksen ala",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "Koodit Koulutusnimike",
            "dataType": "string",
            "sourceColumn": "Koodit Koulutusnimike",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "Koodit organisaatio",
            "dataType": "string",
            "sourceColumn": "Koodit organisaatio",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "Koodit kunta",
            "dataType": "string",
            "sourceColumn": "Koodit kunta",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "jarj. koulutusaste, taso 1",
            "dataType": "string",
            "sourceColumn": "jarj. koulutusaste, taso 1",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "jarj. koulutusaste, taso 2",
            "dataType": "string",
            "sourceColumn": "jarj. koulutusaste, taso 2",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "jarj. OKM ohjauksen ala",
            "dataType": "int64",
            "sourceColumn": "jarj. OKM ohjauksen ala",
            "sourceProviderType": "Integer"
          },
          {
            "name": "jarj. rahoitusmalliala amk",
            "dataType": "string",
            "sourceColumn": "jarj. rahoitusmalliala amk",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "jarj. rahoitusmalliala yo",
            "dataType": "string",
            "sourceColumn": "jarj. rahoitusmalliala yo",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "jarj. paatieteenala",
            "dataType": "string",
            "sourceColumn": "jarj. paatieteenala",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "jarj. tieteenala",
            "dataType": "string",
            "sourceColumn": "jarj. tieteenala",
            "sourceProviderType": "VarChar"
          },
          {
            "type": "calculated",
            "name": "Org_tilv",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "'t3 - amk'[Koodit organisaatio]&\"_\"&'t3 - amk'[Tilastovuosi]"
          },
          {
            "name": "Ulk. kilpailtu tutkimusrahoitus",
            "dataType": "int64",
            "sourceColumn": "Ulk. kilpailtu tutkimusrahoitus"
          },
          {
            "name": "Kilpailtu tutkimusrahoitus rah_malli",
            "dataType": "int64",
            "sourceColumn": "Kilpailtu tutkimusrahoitus rah_malli"
          },
          {
            "name": "Opetus- ja tutkimushenkilökunta",
            "dataType": "double",
            "sourceColumn": "Opetus- ja tutkimushenkilökunta"
          },
          {
            "name": "Tilastovuosi - rahoitusmalli",
            "dataType": "int64",
            "sourceColumn": "Tilastovuosi - rahoitusmalli"
          },
          {
            "name": "Opiskelijapalautepisteet",
            "dataType": "int64",
            "sourceColumn": "Opiskelijapalautepisteet"
          }
        ],
        "partitions": [
          {
            "name": "KK_rahoitusmalli_amk Tampere",
            "dataView": "full",
            "source": {
              "query": "Select * from dw.v_kk_rahoitusmalli_amk where organisaatio='Tampereen ammattikorkeakoulu'",
              "dataSource": "SqlServer dwitvipusql22 ANTERO"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>Select * from dw.v_kk_rahoitusmalli_amk where organisaatio='Tampereen ammattikorkeakoulu'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Alempi kk summa",
            "expression": " CALCULATE(SUM('t3 - amk'[tutkinnot]),'t3 - amk'[Koulutusaste, taso 2]=\"Ammattikorkeakoulututkinto\")"
          },
          {
            "name": "Ylempi kk summa",
            "expression": "CALCULATE(SUM('t3 - amk'[tutkinnot]),'t3 - amk'[Koulutusaste, taso 2]=\"Ylempi ammattikorkeakoulututkinto\")"
          },
          {
            "name": "55op rahoitusmalli amk summa",
            "expression": "CALCULATE(SUM('t3 - amk'[55op suorittaneet]))"
          },
          {
            "name": "Erilliset opinto-oikeudet amk summa",
            "expression": " CALCULATE(SUM('t3 - amk'[avoin_op__lkm])+SUM('t3 - amk'[erikoul_suor_op_lkm])+SUM('t3 - amk'[erilopintooik_op_lkm])+SUM('t3 - amk'[kk_yhteistyo_op_lkm])+SUM('t3 - amk'[mamu_op_lkm]))"
          },
          {
            "name": "Ulkomailla op ja kv vaihto op amk summa",
            "expression": "CALCULATE(SUM('t3 - amk'[kv_vaihtoopiskelijat_op_lkm])+SUM('t3 - amk'[ulkom_harj_op_lkm])+SUM('t3 - amk'[ulkom_hyv_luetut_op_lkm]))"
          },
          {
            "name": "Ulk. ylemmät kk amk summa",
            "expression": " CALCULATE(SUM('t3 - amk'[tutkinnot]),'t3 - amk'[Koulutusaste, taso 2]=\"Ylempi ammattikorkeakoulututkinto\")"
          },
          {
            "name": "Julkaisut amk summa",
            "expression": " CALCULATE(DISTINCTCOUNT(Muuttujat[JulkaisuID]))"
          },
          {
            "name": "Julkaisut rahoitusmalli amk summa",
            "expression": [
              "",
              "VAR A=CALCULATE([Julkaisut amk summa],LEFT('t3 - amk'[Julkaisutyyppi],1)=\"A\")",
              "VAR B=CALCULATE([Julkaisut amk summa],LEFT('t3 - amk'[Julkaisutyyppi],1)=\"B\")",
              "VAR C=CALCULATE([Julkaisut amk summa],LEFT('t3 - amk'[Julkaisutyyppi],1)=\"C\")",
              "VAR D=CALCULATE([Julkaisut amk summa],LEFT('t3 - amk'[Julkaisutyyppi],1)=\"D\")",
              "VAR E=CALCULATE([Julkaisut amk summa],LEFT('t3 - amk'[Julkaisutyyppi],1)=\"E\")",
              "",
              "var A_rah=CALCULATE(a*0.1,'t3 - amk'[Jufotaso]=0)+CALCULATE(A*1,'t3 - amk'[Jufotaso]=1)+CALCULATE(a*3,'t3 - amk'[Jufotaso]=2)+CALCULATE(a*4,'t3 - amk'[Jufotaso]=3)",
              "var b_rah=CALCULATE(b*0.1)",
              "var c2_rah=CALCULATE(c*0.1,'t3 - amk'[Julkaisutyyppi]=\"C2\",'t3 - amk'[Jufotaso]=0)+",
              "\tCALCULATE(c*1,'t3 - amk'[Julkaisutyyppi]=\"C2\",'t3 - amk'[Jufotaso]=1)+",
              "\tCALCULATE(c*3,'t3 - amk'[Julkaisutyyppi]=\"C2\",'t3 - amk'[Jufotaso]=2)+",
              "\tCALCULATE(c*4,'t3 - amk'[Julkaisutyyppi]=\"C2\",'t3 - amk'[Jufotaso]=3)",
              "",
              "var c1_rah=CALCULATE(c*0.4,'t3 - amk'[Julkaisutyyppi]=\"C1\",'t3 - amk'[Jufotaso]=0)+",
              "\tCALCULATE(c*4,'t3 - amk'[Julkaisutyyppi]=\"C1\",'t3 - amk'[Jufotaso]=1)+",
              "\tCALCULATE(c*12,'t3 - amk'[Julkaisutyyppi]=\"C1\",'t3 - amk'[Jufotaso]=2)+",
              "\tCALCULATE(c*16,'t3 - amk'[Julkaisutyyppi]=\"C1\",'t3 - amk'[Jufotaso]=3)",
              "var d1_4_rah=CALCULATE(D*0.1,'t3 - amk'[Julkaisutyyppi]=\"D1\"||'t3 - amk'[Julkaisutyyppi]=\"D2\"||'t3 - amk'[Julkaisutyyppi]=\"D3\"||'t3 - amk'[Julkaisutyyppi]=\"D4\")",
              "var d5_rah=CALCULATE(D*0.4,'t3 - amk'[Julkaisutyyppi]=\"D5\")",
              "var e1_3_rah=CALCULATE(E*0.1,'t3 - amk'[Julkaisutyyppi]=\"E1\"||'t3 - amk'[Julkaisutyyppi]=\"E3\")",
              "var e2_rah=CALCULATE(e*0.4,'t3 - amk'[Julkaisutyyppi]=\"E2\")",
              "",
              "return A_rah+b_rah+c1_rah+c2_rah+d1_4_rah+d5_rah+e1_3_rah+e2_rah"
            ]
          },
          {
            "name": "Ulkopuolinen tutkimusrahoitus amk summa (TK)",
            "expression": " CALCULATE(SUM('t3 - amk'[Ulkopuolinen tutkimusrahoitus]))"
          },
          {
            "name": "Opintopalautteen pisteet amk summa",
            "expression": " CALCULATE(SUM('t3 - amk'[Opiskelijapalautepisteet]))"
          },
          {
            "name": "Työlliset 1v amk summa",
            "expression": " CALCULATE(SUM('t3 - amk'[työlliset 1v tutkinnon jälkeen]),'t3 - amk'[Koulutusaste, taso 2]=\"Ammattikorkeakoulututkinto\")"
          },
          {
            "name": "Ulkomainen tutkimusrahoitus amk summa",
            "expression": " CALCULATE(SUM('t3 - amk'[Ulk. kilpailtu tutkimusrahoitus]))"
          },
          {
            "name": "Muu kilpailtu tutkimusrahoitus amk summa",
            "expression": " CALCULATE(SUM('t3 - amk'[Kilpailtu tutkimusrahoitus rah_malli]))"
          },
          {
            "name": "Ulkomaalainen htv amk summa",
            "expression": " CALCULATE(SUM('t3 - amk'[Opetus- ja tutkimushenkilökunta]),AND('t3 - amk'[Kansalaisuus]<>\"Suomi\",'t3 - amk'[Kansalaisuus]<>\"Ahvenanmaa\"))"
          },
          {
            "name": "Työlliset 1v yamk summa",
            "expression": " CALCULATE(SUM('t3 - amk'[työlliset 1v tutkinnon jälkeen]),'t3 - amk'[Koulutusaste, taso 2]=\"Ylempi ammattikorkeakoulututkinto\")"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "Select * from dw.v_kk_rahoitusmalli_amk where organisaatio='Tampereen ammattikorkeakoulu'"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "KK_rahoitusmalli_amk Tampere"
          },
          {
            "name": "QueryEditorSerialization",
            "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>Select * from dw.v_kk_rahoitusmalli_amk where organisaatio='Tampereen ammattikorkeakoulu'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
          }
        ]
      },
      {
        "name": "T3 analyysi",
        "isHidden": true,
        "columns": [
          {
            "name": "Tilastovuosi",
            "dataType": "int64",
            "sourceColumn": "Tilastovuosi",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Organisaatio",
            "dataType": "string",
            "sourceColumn": "Organisaatio",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "Koodit organisaatio",
            "dataType": "string",
            "sourceColumn": "Koodit organisaatio",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "Organisaatio T3",
            "dataType": "string",
            "sourceColumn": "Organisaatio T3",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "Koodit organisaatio T3",
            "dataType": "string",
            "sourceColumn": "Koodit organisaatio T3",
            "sourceProviderType": "VarChar"
          },
          {
            "type": "calculated",
            "name": "Org_tilv",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": " [Koodit organisaatio]&\"_\"&[Tilastovuosi]"
          }
        ],
        "partitions": [
          {
            "name": "Query T3 tilv_org",
            "dataView": "full",
            "source": {
              "query": [
                "select distinct",
                "",
                " [Tilastovuosi]",
                ",[Organisaatio]",
                ",[Koodit organisaatio]",
                ",case when [Koodit organisaatio] in ('02630','01915','01905') then 'Tampereen yliopisto T3' else Organisaatio end as [Organisaatio T3]",
                ",case when [Koodit organisaatio] in ('02630','01915','01905') then '10122' else [Koodit organisaatio] end as [Koodit organisaatio T3]",
                "",
                " from",
                "(",
                "select distinct Tilastovuosi, Organisaatio, [Koodit organisaatio] ",
                "",
                "from dw.v_kk_rahoitusmalli_yo ",
                "",
                "union all ",
                "",
                "select distinct Tilastovuosi, Organisaatio, [Koodit organisaatio] ",
                "",
                "from dw.v_kk_rahoitusmalli_amk",
                "where [Koodit organisaatio]='02630'",
                ") f"
              ],
              "dataSource": "SqlServer dwitvipusql22 ANTERO"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>select distinct",
                  "",
                  " [Tilastovuosi]",
                  ",[Organisaatio]",
                  ",[Koodit organisaatio]",
                  ",case when [Koodit organisaatio] in ('02630','01915','01905') then 'Tampereen yliopisto T3' else Organisaatio end as [Organisaatio T3]",
                  ",case when [Koodit organisaatio] in ('02630','01915','01905') then '10122' else [Koodit organisaatio] end as [Koodit organisaatio T3]",
                  "",
                  " from",
                  "(",
                  "select distinct Tilastovuosi, Organisaatio, [Koodit organisaatio] ",
                  "",
                  "from dw.v_kk_rahoitusmalli_yo ",
                  "",
                  "union all ",
                  "",
                  "select distinct Tilastovuosi, Organisaatio, [Koodit organisaatio] ",
                  "",
                  "from dw.v_kk_rahoitusmalli_amk",
                  "where [Koodit organisaatio]='02630'",
                  ") f</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Alempi korkeakoulututkinto T3",
            "expression": [
              " ",
              "var yo=CALCULATE(AVERAGEX(SUMMARIZE('Muuttujat','Muuttujat'[Tilastovuosi],'Muuttujat'[Yliopisto],\"summa\",Muuttujat[Alempi korkeakoulututkinto summa]),[summa]))",
              "var amk=CALCULATE(AVERAGEX(SUMMARIZE('t3 - amk','t3 - amk'[Tilastovuosi],'t3 - amk'[Organisaatio],\"summa\",'t3 - amk'[Alempi kk summa]),[summa]))",
              "return AVERAGEX(SUMMARIZE('T3 analyysi','T3 analyysi'[Tilastovuosi],'T3 analyysi'[Organisaatio T3],\"yht\",yo+amk),[yht])"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Keskiarvo"
          },
          {
            "name": "Suorittanut 55 rahoitusmalli T3",
            "expression": [
              " ",
              "var yo=CALCULATE(AVERAGEX(SUMMARIZE('Muuttujat','Muuttujat'[Tilastovuosi],'Muuttujat'[Yliopisto],\"summa\",Muuttujat[Suorittanut 55op rahoitusmalli summa]),[summa]))",
              "var amk = CALCULATE(AVERAGEX(SUMMARIZE('t3 - amk','t3 - amk'[Tilastovuosi],'t3 - amk'[Organisaatio],\"summa\",'t3 - amk'[55op rahoitusmalli amk summa]),[summa]))",
              "",
              "return AVERAGEX(SUMMARIZE('T3 analyysi','T3 analyysi'[Tilastovuosi],'T3 analyysi'[Organisaatio T3],\"yht\",yo+amk),[yht])"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Keskiarvo"
          },
          {
            "name": "Ylempi korkeakoulututkinto T3",
            "expression": [
              " ",
              "var yo = CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],Muuttujat[Yliopisto],\"summa\",[Ylempi korkeakoulututkinto summa]),[summa]))",
              "var amk=CALCULATE(AVERAGEX(SUMMARIZE('t3 - amk','t3 - amk'[Tilastovuosi],'t3 - amk'[Organisaatio],\"summa\",'t3 - amk'[Ylempi kk summa]),[summa]))",
              "return AVERAGEX(SUMMARIZE('T3 analyysi','T3 analyysi'[Tilastovuosi],'T3 analyysi'[Organisaatio T3],\"yht\",yo+amk),[yht])"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Keskiarvo"
          },
          {
            "name": "Erilliset opinto-oikeudet T3",
            "expression": [
              " ",
              "",
              "var yo = CALCULATE(AVERAGEX(SUMMARIZE('Muuttujat','Muuttujat'[Tilastovuosi],'Muuttujat'[Yliopisto],\"summa\",[Erilliset opinto-oikeudet summa]),[summa]))",
              "var amk=CALCULATE(AVERAGEX(SUMMARIZE('t3 - amk','t3 - amk'[Tilastovuosi],'t3 - amk'[Organisaatio],\"summa\",'t3 - amk'[Erilliset opinto-oikeudet amk summa]),[summa]))",
              "return AVERAGEX(SUMMARIZE('T3 analyysi','T3 analyysi'[Tilastovuosi],'T3 analyysi'[Organisaatio T3],\"yht\",yo+amk),[yht])"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Keskiarvo"
          },
          {
            "name": "Ulkomailla suoritetut ja kv vaihto-opiskelijoiden pisteet T3",
            "expression": [
              " ",
              "",
              "var yo = CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],Muuttujat[Yliopisto],\"summa\",[Ulkomailla suoritetut ja kv vaihto-opiskelijoiden op summa]),[summa]))",
              "var amk=CALCULATE(AVERAGEX(SUMMARIZE('t3 - amk','t3 - amk'[Tilastovuosi],'t3 - amk'[Organisaatio],\"summa\",'t3 - amk'[Ulkomailla op ja kv vaihto op amk summa]),[summa]))",
              "return AVERAGEX(SUMMARIZE('T3 analyysi','T3 analyysi'[Tilastovuosi],'T3 analyysi'[Organisaatio T3],\"yht\",yo+amk),[yht])"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Keskiarvo"
          },
          {
            "name": "Muu kilpailtu tutkimusrahoitus T3",
            "expression": [
              " ",
              "var yo = CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],Muuttujat[Yliopisto],\"summa\",[Muu kilpailtu tutkimusrahoitus summa]),[summa]))",
              "var amk = CALCULATE(AVERAGEX(SUMMARIZE('t3 - amk','t3 - amk'[Tilastovuosi],'t3 - amk'[Organisaatio],\"summa\",[Muu kilpailtu tutkimusrahoitus amk summa]),[summa]))",
              "return AVERAGEX(SUMMARIZE('T3 analyysi','T3 analyysi'[Tilastovuosi],'T3 analyysi'[Organisaatio T3],\"yht\",yo+amk),[yht])",
              ""
            ],
            "formatString": "#,0.0",
            "displayFolder": "Keskiarvo"
          },
          {
            "name": "Ulkomainen tutkimusrahoitus T3",
            "expression": [
              "",
              "var yo = CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],Muuttujat[Yliopisto],\"summa\",[Ulkomainen kilpailtu tutkimusrahoitus summa]),[summa]))",
              "var amk = CALCULATE(AVERAGEX(SUMMARIZE('t3 - amk','t3 - amk'[Tilastovuosi],'t3 - amk'[Organisaatio],\"summa\",[Ulkomainen tutkimusrahoitus amk summa]),[summa]))",
              "return AVERAGEX(SUMMARIZE('T3 analyysi','T3 analyysi'[Tilastovuosi],'T3 analyysi'[Organisaatio T3],\"yht\",yo+amk),[yht])"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Keskiarvo"
          },
          {
            "name": "Ulkomaalaisten ylemmät kk-tutkinnot T3",
            "expression": [
              " ",
              "var yo = CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],Muuttujat[Yliopisto],\"summa\",[Ulkomaalaisten ylemmät korkeakoulututkinnot summa]),[summa]))",
              "var amk = CALCULATE(AVERAGEX(SUMMARIZE('t3 - amk','t3 - amk'[Tilastovuosi],'t3 - amk'[Organisaatio],\"summa\",[Ulk. ylemmät kk amk summa]),[summa]))",
              "",
              "return AVERAGEX(SUMMARIZE('T3 analyysi','T3 analyysi'[Tilastovuosi],'T3 analyysi'[Organisaatio T3],\"yht\",yo+amk),[yht])"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Keskiarvo"
          },
          {
            "name": "Tohtorin tutkinnot T3",
            "expression": " CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],Muuttujat[Yliopisto],\"summa\",[Tohtorin tutkinnot summa]),[summa]))",
            "formatString": "#,0.0",
            "displayFolder": "Keskiarvo"
          },
          {
            "name": "Julkaisut rahoitusmalli T3",
            "expression": [
              " ",
              "var yo = CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],Muuttujat[Yliopisto],\"summa\",[Julkaisut rahoitusmalli summa]),[summa]))",
              "var amk =CALCULATE(AVERAGEX(SUMMARIZE('t3 - amk','t3 - amk'[Tilastovuosi],'t3 - amk'[Organisaatio],\"summa\",[Julkaisut rahoitusmalli amk summa]),[summa]))",
              "",
              "return AVERAGEX(SUMMARIZE('T3 analyysi','T3 analyysi'[Tilastovuosi],'T3 analyysi'[Organisaatio T3],\"yht\",yo+amk),[yht])"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Keskiarvo"
          },
          {
            "name": "Ulkomaalainen htv T3",
            "expression": [
              " ",
              "var yo = CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],Muuttujat[Yliopisto],\"summa\",[Ulkomaalainen htv summa]),[summa]))",
              "var amk = CALCULATE(AVERAGEX(SUMMARIZE('t3 - amk','t3 - amk'[Tilastovuosi],'t3 - amk'[Organisaatio],\"summa\",[Ulkomaalainen htv amk summa]),[summa]))",
              "",
              "return AVERAGEX(SUMMARIZE('T3 analyysi','T3 analyysi'[Tilastovuosi],'T3 analyysi'[Organisaatio T3],\"yht\",yo+amk),[yht])"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Keskiarvo"
          },
          {
            "name": "Opintopalautteen pisteet T3",
            "expression": [
              " ",
              "var yo = CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],Muuttujat[Yliopisto],\"summa\",[Kandipalaute pisteet summa]),[summa]))",
              "var amk = CALCULATE(AVERAGEX(SUMMARIZE('t3 - amk','t3 - amk'[Tilastovuosi],'t3 - amk'[Organisaatio],\"summa\",[Opintopalautteen pisteet amk summa]),[summa]))",
              "",
              "return AVERAGEX(SUMMARIZE('T3 analyysi','T3 analyysi'[Tilastovuosi],'T3 analyysi'[Organisaatio T3],\"yht\",yo+amk),[yht])"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Keskiarvo"
          },
          {
            "name": "Työlliset 1v valmistumisesta T3",
            "expression": [
              " ",
              "var yo = CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],Muuttujat[Yliopisto],\"summa\",[Työllisten lukumäärä 1v valmistumisesta summa]),[summa]))",
              "var amk = CALCULATE(AVERAGEX(SUMMARIZE('t3 - amk','t3 - amk'[Tilastovuosi],'t3 - amk'[Organisaatio],\"summa\",[Työlliset 1v yamk summa]),[summa]))",
              "",
              "return AVERAGEX(SUMMARIZE('T3 analyysi','T3 analyysi'[Tilastovuosi],'T3 analyysi'[Organisaatio T3],\"yht\",yo+amk),[yht])"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Keskiarvo"
          },
          {
            "name": "Työlliset 1v valmistumisesta T3 (%)",
            "expression": [
              " ",
              "var yo_k = CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],\"summa\",[Työllisten lukumäärä 1v valmistumisesta summa]),[summa]),ALL('T3 analyysi'[Organisaatio],'T3 analyysi'[Organisaatio T3]))",
              "var amk_k = CALCULATE(AVERAGEX(SUMMARIZE('t3 - amk','t3 - amk'[Tilastovuosi],\"summa\",[Työlliset 1v yamk summa]),[summa]),ALL('T3 analyysi'[Organisaatio],'T3 analyysi'[Organisaatio T3]))",
              "",
              "var yht = [Työlliset 1v valmistumisesta T3]",
              "var yht_k = AVERAGEX(SUMMARIZE('T3 analyysi','T3 analyysi'[Tilastovuosi],\"yht\",yo_k+amk_k),[yht])",
              "",
              "return DIVIDE(yht,yht_k)",
              ""
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %",
            "displayFolder": "Keskiarvo\\% osuus"
          },
          {
            "name": "Alempi korkeakoulututkinto T3 (%)",
            "expression": [
              " ",
              "var yo_k = CALCULATE(AVERAGEX(SUMMARIZE('Muuttujat','Muuttujat'[Tilastovuosi],\"summa\",Muuttujat[Alempi korkeakoulututkinto summa]),[summa]),ALL('T3 analyysi'[Organisaatio],'T3 analyysi'[Organisaatio T3]))",
              "var amk_k = CALCULATE(AVERAGEX(SUMMARIZE('t3 - amk','t3 - amk'[Tilastovuosi],\"summa\",'t3 - amk'[Alempi kk summa]),[summa]),ALL('T3 analyysi'[Organisaatio],'T3 analyysi'[Organisaatio T3]))",
              "",
              "var yht = [Alempi korkeakoulututkinto T3]",
              "var yht_k = AVERAGEX(SUMMARIZE('T3 analyysi','T3 analyysi'[Tilastovuosi],\"yht\",yo_k+amk_k),[yht])",
              "",
              "return DIVIDE(yht,yht_k)"
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %",
            "displayFolder": "Keskiarvo\\% osuus"
          },
          {
            "name": "Ylempi korkeakoulututkinto T3 (%)",
            "expression": [
              " ",
              "var yo_k = CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],\"summa\",[Ylempi korkeakoulututkinto summa]),[summa]),ALL('T3 analyysi'[Organisaatio],'T3 analyysi'[Organisaatio T3]))",
              "var amk_k =CALCULATE(AVERAGEX(SUMMARIZE('t3 - amk','t3 - amk'[Tilastovuosi],\"summa\",'t3 - amk'[Ylempi kk summa]),[summa]),ALL('T3 analyysi'[Organisaatio],'T3 analyysi'[Organisaatio T3]))",
              "",
              "var yht = [Ylempi korkeakoulututkinto T3]",
              "var yht_k = AVERAGEX(SUMMARIZE('T3 analyysi','T3 analyysi'[Tilastovuosi],\"yht\",yo_k+amk_k),[yht])",
              "",
              "return DIVIDE(yht,yht_k)",
              ""
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %",
            "displayFolder": "Keskiarvo\\% osuus"
          },
          {
            "name": "Tohtorin tutkinnot T3 (%)",
            "expression": [
              " ",
              "var yht = [Tohtorin tutkinnot T3]",
              "var yht_k = CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],\"summa\",[Tohtorin tutkinnot summa]),[summa]),ALL('T3 analyysi'[Organisaatio],'T3 analyysi'[Organisaatio T3]))",
              "",
              "return DIVIDE(yht,yht_k)",
              ""
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %",
            "displayFolder": "Keskiarvo\\% osuus"
          },
          {
            "name": "Suorittanut 55 rahoitusmalli T3 (%)",
            "expression": [
              " ",
              "var yo_k=CALCULATE(AVERAGEX(SUMMARIZE('Muuttujat','Muuttujat'[Tilastovuosi],\"summa\",Muuttujat[Suorittanut 55op rahoitusmalli summa]),[summa]),ALL('T3 analyysi'[Organisaatio],'T3 analyysi'[Organisaatio T3]))",
              "var amk_k = CALCULATE(AVERAGEX(SUMMARIZE('t3 - amk','t3 - amk'[Tilastovuosi],\"summa\",'t3 - amk'[55op rahoitusmalli amk summa]),[summa]),ALL('T3 analyysi'[Organisaatio],'T3 analyysi'[Organisaatio T3]))",
              "",
              "var yht = [Suorittanut 55 rahoitusmalli T3]",
              "var yht_k = AVERAGEX(SUMMARIZE('T3 analyysi','T3 analyysi'[Tilastovuosi],\"yht\",yo_k+amk_k),[yht])",
              "",
              "return DIVIDE(yht,yht_k)",
              ""
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %",
            "displayFolder": "Keskiarvo\\% osuus"
          },
          {
            "name": "Muu kilpailtu tutkimusrahoitus T3 (%)",
            "expression": [
              " ",
              "var yo_k = CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],\"summa\",[Muu kilpailtu tutkimusrahoitus summa]),[summa]),ALL('T3 analyysi'[Organisaatio],'T3 analyysi'[Organisaatio T3]))",
              "var amk_k = CALCULATE(AVERAGEX(SUMMARIZE('t3 - amk','t3 - amk'[Tilastovuosi],\"summa\",[Muu kilpailtu tutkimusrahoitus amk summa]),[summa]),ALL('T3 analyysi'[Organisaatio],'T3 analyysi'[Organisaatio T3]))",
              "",
              "var yht = [Muu kilpailtu tutkimusrahoitus T3]",
              "var yht_k = AVERAGEX(SUMMARIZE('T3 analyysi','T3 analyysi'[Tilastovuosi],\"yht\",yo_k+amk_k),[yht])",
              "",
              "return DIVIDE(yht,yht_k)",
              ""
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %",
            "displayFolder": "Keskiarvo\\% osuus"
          },
          {
            "name": "Julkaisut rahoitusmalli T3 (%)",
            "expression": [
              " ",
              "var yo_k = CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],\"summa\",[Julkaisut rahoitusmalli summa]),[summa]),ALL('T3 analyysi'[Organisaatio],'T3 analyysi'[Organisaatio T3]))",
              "var amk_k =CALCULATE(AVERAGEX(SUMMARIZE('t3 - amk','t3 - amk'[Tilastovuosi],\"summa\",[Julkaisut rahoitusmalli amk summa]),[summa]),ALL('T3 analyysi'[Organisaatio],'T3 analyysi'[Organisaatio T3]))",
              "",
              "var yht = [Julkaisut rahoitusmalli T3]",
              "var yht_k = AVERAGEX(SUMMARIZE('T3 analyysi','T3 analyysi'[Tilastovuosi],\"yht\",yo_k+amk_k),[yht])",
              "",
              "return DIVIDE(yht,yht_k)",
              ""
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %",
            "displayFolder": "Keskiarvo\\% osuus"
          },
          {
            "name": "Erilliset opinto-oikeudet T3 (%)",
            "expression": [
              " ",
              "",
              "var yo_k = CALCULATE(AVERAGEX(SUMMARIZE('Muuttujat','Muuttujat'[Tilastovuosi],\"summa\",[Erilliset opinto-oikeudet summa]),[summa]),ALL('T3 analyysi'[Organisaatio],'T3 analyysi'[Organisaatio T3]))",
              "var amk_k=CALCULATE(AVERAGEX(SUMMARIZE('t3 - amk','t3 - amk'[Tilastovuosi],\"summa\",'t3 - amk'[Erilliset opinto-oikeudet amk summa]),[summa]),ALL('T3 analyysi'[Organisaatio],'T3 analyysi'[Organisaatio T3]))",
              "",
              "var yht = [Erilliset opinto-oikeudet T3]",
              "var yht_k = AVERAGEX(SUMMARIZE('T3 analyysi','T3 analyysi'[Tilastovuosi],\"yht\",yo_k+amk_k),[yht])",
              "",
              "return DIVIDE(yht,yht_k)",
              ""
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %",
            "displayFolder": "Keskiarvo\\% osuus"
          },
          {
            "name": "Ulkomainen tutkimusrahoitus T3 (%)",
            "expression": [
              "",
              "var yo_k = CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],\"summa\",[Ulkomainen kilpailtu tutkimusrahoitus summa]),[summa]),ALL('T3 analyysi'[Organisaatio],'T3 analyysi'[Organisaatio T3]))",
              "var amk_k = CALCULATE(AVERAGEX(SUMMARIZE('t3 - amk','t3 - amk'[Tilastovuosi],\"summa\",[Ulkomainen tutkimusrahoitus amk summa]),[summa]),ALL('T3 analyysi'[Organisaatio],'T3 analyysi'[Organisaatio T3]))",
              "var yht = [Ulkomainen tutkimusrahoitus T3]",
              "var yht_k = AVERAGEX(SUMMARIZE('T3 analyysi','T3 analyysi'[Tilastovuosi],\"yht\",yo_k+amk_k),[yht])",
              "",
              "return DIVIDE(yht,yht_k)",
              ""
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %",
            "displayFolder": "Keskiarvo\\% osuus"
          },
          {
            "name": "Ulkomaalainen htv T3 (%)",
            "expression": [
              " ",
              "var yo_k = CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],\"summa\",[Ulkomaalainen htv summa]),[summa]),ALL('T3 analyysi'[Organisaatio],'T3 analyysi'[Organisaatio T3]))",
              "var amk_k = CALCULATE(AVERAGEX(SUMMARIZE('t3 - amk','t3 - amk'[Tilastovuosi],\"summa\",[Ulkomaalainen htv amk summa]),[summa]),ALL('T3 analyysi'[Organisaatio],'T3 analyysi'[Organisaatio T3]))",
              "",
              "var yht = [Ulkomaalainen htv T3]",
              "var yht_k = AVERAGEX(SUMMARIZE('T3 analyysi','T3 analyysi'[Tilastovuosi],\"yht\",yo_k+amk_k),[yht])",
              "",
              "return DIVIDE(yht,yht_k)",
              ""
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %",
            "displayFolder": "Keskiarvo\\% osuus"
          },
          {
            "name": "Ulkomailla suoritetut ja kv vaihto-opiskelijoiden pisteet T3 (%)",
            "expression": [
              " ",
              "",
              "var yo_k = CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],\"summa\",[Ulkomailla suoritetut ja kv vaihto-opiskelijoiden op summa]),[summa]),ALL('T3 analyysi'[Organisaatio],'T3 analyysi'[Organisaatio T3]))",
              "var amk_k=CALCULATE(AVERAGEX(SUMMARIZE('t3 - amk','t3 - amk'[Tilastovuosi],\"summa\",'t3 - amk'[Ulkomailla op ja kv vaihto op amk summa]),[summa]),ALL('T3 analyysi'[Organisaatio],'T3 analyysi'[Organisaatio T3]))",
              "",
              "var yht = [Ulkomailla suoritetut ja kv vaihto-opiskelijoiden pisteet T3]",
              "var yht_k = AVERAGEX(SUMMARIZE('T3 analyysi','T3 analyysi'[Tilastovuosi],\"yht\",yo_k+amk_k),[yht])",
              "",
              "return DIVIDE(yht,yht_k)",
              ""
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %",
            "displayFolder": "Keskiarvo\\% osuus"
          },
          {
            "name": "Ulkomaalaisten ylemmät kk-tutkinnot T3 (%)",
            "expression": [
              " ",
              "var yo_k = CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],\"summa\",[Ulkomaalaisten ylemmät korkeakoulututkinnot summa]),[summa]),ALL('T3 analyysi'[Organisaatio],'T3 analyysi'[Organisaatio T3]))",
              "var amk_k = CALCULATE(AVERAGEX(SUMMARIZE('t3 - amk','t3 - amk'[Tilastovuosi],\"summa\",[Ulk. ylemmät kk amk summa]),[summa]),ALL('T3 analyysi'[Organisaatio],'T3 analyysi'[Organisaatio T3]))",
              "",
              "var yht = [Ulkomaalaisten ylemmät kk-tutkinnot T3]",
              "var yht_k = AVERAGEX(SUMMARIZE('T3 analyysi','T3 analyysi'[Tilastovuosi],\"yht\",yo_k+amk_k),[yht])",
              "",
              "return DIVIDE(yht,yht_k)",
              ""
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %",
            "displayFolder": "Keskiarvo\\% osuus"
          },
          {
            "name": "Opintopalautteen pisteet T3 (%)",
            "expression": [
              " ",
              "var yo_k = CALCULATE(AVERAGEX(SUMMARIZE(Muuttujat,Muuttujat[Tilastovuosi],\"summa\",[Kandipalaute pisteet summa]),[summa]),ALL('T3 analyysi'[Organisaatio],'T3 analyysi'[Organisaatio T3]))",
              "var amk_k = CALCULATE(AVERAGEX(SUMMARIZE('t3 - amk','t3 - amk'[Tilastovuosi],\"summa\",[Opintopalautteen pisteet amk summa]),[summa]),ALL('T3 analyysi'[Organisaatio],'T3 analyysi'[Organisaatio T3]))",
              "",
              "var yht = [Opintopalautteen pisteet T3]",
              "var yht_k = AVERAGEX(SUMMARIZE('T3 analyysi','T3 analyysi'[Tilastovuosi],\"yht\",yo_k+amk_k),[yht])",
              "",
              "return DIVIDE(yht,yht_k)",
              ""
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %",
            "displayFolder": "Keskiarvo\\% osuus"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": [
              "select distinct",
              "",
              " [Tilastovuosi]",
              ",[Organisaatio]",
              ",[Koodit organisaatio]",
              ",case when [Koodit organisaatio] in ('02630','01915','01905') then 'Tampereen yliopisto T3' else Organisaatio end as [Organisaatio T3]",
              ",case when [Koodit organisaatio] in ('02630','01915','01905') then '10122' else [Koodit organisaatio] end as [Koodit organisaatio T3]",
              "",
              " from",
              "(",
              "select distinct Tilastovuosi, Organisaatio, [Koodit organisaatio] ",
              "",
              "from dw.v_kk_rahoitusmalli_yo ",
              "",
              "union all ",
              "",
              "select distinct Tilastovuosi, Organisaatio, [Koodit organisaatio] ",
              "",
              "from dw.v_kk_rahoitusmalli_amk",
              "where [Koodit organisaatio]='02630'",
              ") f"
            ]
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Query T3 tilv_org"
          },
          {
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>select distinct",
              "",
              " [Tilastovuosi]",
              ",[Organisaatio]",
              ",[Koodit organisaatio]",
              ",case when [Koodit organisaatio] in ('02630','01915','01905') then 'Tampereen yliopisto T3' else Organisaatio end as [Organisaatio T3]",
              ",case when [Koodit organisaatio] in ('02630','01915','01905') then '10122' else [Koodit organisaatio] end as [Koodit organisaatio T3]",
              "",
              " from",
              "(",
              "select distinct Tilastovuosi, Organisaatio, [Koodit organisaatio] ",
              "",
              "from dw.v_kk_rahoitusmalli_yo ",
              "",
              "union all ",
              "",
              "select distinct Tilastovuosi, Organisaatio, [Koodit organisaatio] ",
              "",
              "from dw.v_kk_rahoitusmalli_amk",
              "where [Koodit organisaatio]='02630'",
              ") f</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Rahoitusmalli_korkeakoulut",
        "isHidden": true,
        "columns": [
          {
            "name": "id",
            "dataType": "int64",
            "sourceColumn": "id",
            "sourceProviderType": "Integer"
          },
          {
            "name": "rahoituksen_vuosi",
            "dataType": "int64",
            "sourceColumn": "rahoituksen_vuosi",
            "sourceProviderType": "WChar"
          },
          {
            "name": "sektori",
            "dataType": "string",
            "sourceColumn": "sektori",
            "sourceProviderType": "WChar"
          },
          {
            "name": "rahoituksen_kategoria",
            "dataType": "string",
            "sourceColumn": "rahoituksen_kategoria",
            "sourceProviderType": "WChar"
          },
          {
            "name": "indikaattori",
            "dataType": "string",
            "sourceColumn": "indikaattori",
            "sourceProviderType": "WChar"
          },
          {
            "name": "rahoitus_1000_euroa",
            "dataType": "int64",
            "sourceColumn": "rahoitus_1000_euroa",
            "sourceProviderType": "Integer"
          },
          {
            "name": "osuus_rahoituksesta",
            "dataType": "double",
            "sourceColumn": "osuus_rahoituksesta",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "tietolahde",
            "dataType": "string",
            "sourceColumn": "tietolahde",
            "sourceProviderType": "WChar"
          },
          {
            "name": "user",
            "dataType": "string",
            "sourceColumn": "user",
            "sourceProviderType": "WChar"
          },
          {
            "name": "luotu",
            "dataType": "dateTime",
            "sourceColumn": "luotu",
            "formatString": "General Date",
            "sourceProviderType": "DBDate"
          }
        ],
        "partitions": [
          {
            "name": "Rahoitusmalli_korkeakoulut",
            "dataView": "full",
            "source": {
              "query": "SELECT [dbo].[Rahoitusmalli_korkeakoulut].* FROM [dbo].[Rahoitusmalli_korkeakoulut] WHERE sektori='Yliopisto'",
              "dataSource": "SqlServer dwitvipusql22 VipunenTK_lisatiedot 2"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[Rahoitusmalli_korkeakoulut].* FROM [dbo].[Rahoitusmalli_korkeakoulut] WHERE sektori='Yliopisto'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "SELECT [dbo].[Rahoitusmalli_korkeakoulut].* FROM [dbo].[Rahoitusmalli_korkeakoulut] WHERE sektori='Yliopisto'"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Rahoitusmalli_korkeakoulut"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "QueryEditorSerialization",
            "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[Rahoitusmalli_korkeakoulut].* FROM [dbo].[Rahoitusmalli_korkeakoulut] WHERE sektori='Yliopisto'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "b3f419db-05d7-44d4-80e1-831858e817fd",
        "fromTable": "t3 - amk",
        "fromColumn": "Org_tilv",
        "toTable": "T3 analyysi",
        "toColumn": "Org_tilv"
      },
      {
        "name": "04e9fe0d-3447-4f8f-ad73-c01464bf9e72",
        "fromTable": "Muuttujat",
        "fromColumn": "Org_tilv",
        "toTable": "T3 analyysi",
        "toColumn": "Org_tilv"
      }
    ],
    "perspectives": [
      {
        "name": "Rahoitusmalli_vuosi_keskiarvo",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Yliopisto"
              },
              {
                "name": "Yliopisto T2"
              },
              {
                "name": "Tilastovuosi - rahoitusmalli"
              }
            ],
            "measures": [
              {
                "name": "Alempi korkeakoulututkinto"
              },
              {
                "name": "Erilliset opinto-oikeudet"
              },
              {
                "name": "Julkaisut rahoitusmalli"
              },
              {
                "name": "Muu kilpailtu tutkimusrahoitus"
              },
              {
                "name": "Suorittanut 55 rahoitusmalli"
              },
              {
                "name": "Tohtorin tutkinnot"
              },
              {
                "name": "Ulkomaalainen htv"
              },
              {
                "name": "Ulkomaalaisten ylemmät kk-tutkinnot"
              },
              {
                "name": "Ulkomailla suoritetut ja kv vaihto-opiskelijoiden pisteet"
              },
              {
                "name": "Ylempi korkeakoulututkinto"
              },
              {
                "name": "Opiskelijapalautteen pisteet"
              },
              {
                "name": "Työlliset 1v valmistumisesta"
              },
              {
                "name": "Alempi korkeakoulututkinto (%)"
              },
              {
                "name": "Erilliset opinto-oikeudet (%)"
              },
              {
                "name": "Julkaisut rahoitusmalli (%)"
              },
              {
                "name": "Muu kilpailtu tutkimusrahoitus (%)"
              },
              {
                "name": "Opiskelijapalautteen pisteet (%)"
              },
              {
                "name": "Tohtorin tutkinnot (%)"
              },
              {
                "name": "Työlliset 1v valmistumisesta (%)"
              },
              {
                "name": "Ulkomaalainen htv (%)"
              },
              {
                "name": "Ulkomaalaisten ylemmät kk-tutkinnot (%)"
              },
              {
                "name": "Ulkomailla suoritetut ja kv vaihto-opiskelijoiden pisteet (%)"
              },
              {
                "name": "Ulkomainen kilpailtu tutkimusrahoitus (%)"
              },
              {
                "name": "Ylempi korkeakoulututkinto (%)"
              },
              {
                "name": "Suorittanut 55 rahoitusmalli (%)"
              },
              {
                "name": "Ulkomainen kilpailtu tutkimusrahoitus"
              },
              {
                "name": "Alempi korkeakoulututkinto (osuus perusrahoituksesta 1000€)"
              },
              {
                "name": "Erilliset opinto-oikeudet (osuus perusrahoituksesta 1000€)"
              },
              {
                "name": "Julkaisut (osuus perusrahoituksesta 1000€)"
              },
              {
                "name": "Muu kilpailtu tutkimusrahoitus (osuus perusrahoituksesta 1000€)"
              },
              {
                "name": "Opiskelijapalautteen pisteet (osuus perusrahoituksesta 1000€)"
              },
              {
                "name": "Rahoitusvuosi"
              },
              {
                "name": "Suorittanut 55 (osuus perusrahoituksesta 1000€)"
              },
              {
                "name": "Tohtorin tutkinnot (osuus perusrahoituksesta 1000€)"
              },
              {
                "name": "Työlliset 1v valmistumisesta (osuus perusrahoituksesta 1000€)"
              },
              {
                "name": "Ulkomaalainen htv (osuus perusrahoituksesta 1000€)"
              },
              {
                "name": "Ulkomaalaisten ylemmät kk-tutkinnot (osuus perusrahoituksesta 1000€)"
              },
              {
                "name": "Ulkomailla suoritetut ja kv vaihto-opiskelijoiden pisteet (osuus perusrahoituksesta 1000€)"
              },
              {
                "name": "Ulkomainen kilpailtu tutkimusrahoitus (osuus perusrahoituksesta 1000€)"
              },
              {
                "name": "Ylempi korkeakoulututkinto (osuus perusrahoituksesta 1000€)"
              }
            ]
          }
        ]
      },
      {
        "name": "Analyysi_summa",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Jufotaso"
              },
              {
                "name": "Julkaisutyyppi"
              },
              {
                "name": "Koulutusala, taso 1"
              },
              {
                "name": "Koulutusala, taso 2"
              },
              {
                "name": "Koulutusala, taso 3"
              },
              {
                "name": "Koulutusaste (2002)"
              },
              {
                "name": "Koulutusaste, taso 1"
              },
              {
                "name": "Koulutusaste, taso 2"
              },
              {
                "name": "OKM ohjauksen ala"
              },
              {
                "name": "Päätieteenala"
              },
              {
                "name": "Rahoitusmalliala, yo"
              },
              {
                "name": "Tieteenala"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Yliopisto"
              }
            ],
            "measures": [
              {
                "name": "Suorittanut 55op rahoitusmalli summa"
              },
              {
                "name": "Alempi korkeakoulututkinto summa"
              },
              {
                "name": "Avoimessa yliopistossa suoritetut op summa"
              },
              {
                "name": "Erikoistumiskoulutuksessa suoritetut op summa"
              },
              {
                "name": "Erillisellä opinto-oikeudella suoritetut op summa"
              },
              {
                "name": "Erilliset opinto-oikeudet summa"
              },
              {
                "name": "Erillisillä opinto-oikeuksilla opettajankoulutuksen op summa"
              },
              {
                "name": "Julkaisut rahoitusmalli summa"
              },
              {
                "name": "Julkaisut summa"
              },
              {
                "name": "Kandipalaute pisteet summa"
              },
              {
                "name": "Korkeakoulujen välisillä sopimuksilla suoritetut op summa"
              },
              {
                "name": "kv vaihto-opiskelija op summa"
              },
              {
                "name": "Muu kilpailtu tutkimusrahoitus summa"
              },
              {
                "name": "Suorittanut 55op summa"
              },
              {
                "name": "Tohtorin tutkinnot summa"
              },
              {
                "name": "Työllisten lukumäärä 1v valmistumisesta summa"
              },
              {
                "name": "Ulkomaalainen htv summa"
              },
              {
                "name": "Ulkomaalaisten ylemmät korkeakoulututkinnot summa"
              },
              {
                "name": "Ulkomailla harjoittelussa suoritetut op summa"
              },
              {
                "name": "Ulkomailla hyväksiluetut op summa"
              },
              {
                "name": "Ulkomailla suoritetut ja kv vaihto-opiskelijoiden op summa"
              },
              {
                "name": "Ulkomainen kilpailtu tutkimusrahoitus summa"
              },
              {
                "name": "Ylempi korkeakoulututkinto summa"
              }
            ]
          }
        ]
      },
      {
        "name": "T2 analyysi",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Yliopisto T2"
              }
            ],
            "measures": [
              {
                "name": "Alempi korkeakoulututkinto (%) T2"
              },
              {
                "name": "Alempi korkeakoulututkinto T2"
              },
              {
                "name": "Erilliset opinto-oikeudet (%) T2"
              },
              {
                "name": "Erilliset opinto-oikeudet T2"
              },
              {
                "name": "Julkaisut rahoitusmalli (%) T2"
              },
              {
                "name": "Julkaisut rahoitusmalli T2"
              },
              {
                "name": "Muu kilpailtu tutkimusrahoitus (%) T2"
              },
              {
                "name": "Muu kilpailtu tutkimusrahoitus T2"
              },
              {
                "name": "Opintopalautteen pisteet (%) T2"
              },
              {
                "name": "Opintopalautteen pisteet T2"
              },
              {
                "name": "Suorittanut 55 rahoitusmalli (%) T2"
              },
              {
                "name": "Suorittanut 55 rahoitusmalli T2"
              },
              {
                "name": "Tohtorin tutkinnot (%) T2"
              },
              {
                "name": "Tohtorin tutkinnot T2"
              },
              {
                "name": "Työlliset 1v valmistumisesta (%) T2"
              },
              {
                "name": "Työlliset 1v valmistumisesta T2"
              },
              {
                "name": "Ulkomaalainen htv (%) T2"
              },
              {
                "name": "Ulkomaalainen htv T2"
              },
              {
                "name": "Ulkomaalaisten ylemmät kk-tutkinnot (%) T2"
              },
              {
                "name": "Ulkomaalaisten ylemmät kk-tutkinnot T2"
              },
              {
                "name": "Ulkomailla suoritetut ja kv vaihto-opiskelijoiden pisteet (%) T2"
              },
              {
                "name": "Ulkomailla suoritetut ja kv vaihto-opiskelijoiden pisteet T2"
              },
              {
                "name": "Ulkomainen kilpailtu tutkimusrahoitus (%) T2"
              },
              {
                "name": "Ulkomainen kilpailtu tutkimusrahoitus T2"
              },
              {
                "name": "Ylempi korkeakoulututkinto (%) T2"
              },
              {
                "name": "Ylempi korkeakoulututkinto T2"
              }
            ]
          }
        ]
      }
    ],
    "roles": [
      {
        "name": "Luku",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "DWI\\P_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1733"
          },
          {
            "memberName": "DWI\\T_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1732"
          },
          {
            "memberName": "DWI\\TVipuPbiRead",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-2143"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "400"
      }
    ]
  },
  "id": "SemanticModel"
}
