{
  "name": "SemanticModel",
  "compatibilityLevel": 1200,
  "model": {
    "culture": "fi-FI",
    "dataSources": [
      {
        "name": "SqlServer dwitestvipusql VipunenTK",
        "connectionString": "Provider=SQLOLEDB.1;Data Source=dwitvipusql22;Initial Catalog=VipunenTK;Integrated Security=SSPI;Persist Security Info=false",
        "impersonationMode": "impersonateServiceAccount",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "Sarakeleveys",
        "columns": [
          {
            "name": "Sarakeleveys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Sarakeleveys"
          },
          {
            "name": "leveys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "leveys"
          }
        ],
        "partitions": [
          {
            "name": "Sarakeleveys",
            "source": {
              "type": "query",
              "query": "SELECT [dbo].[Sarakeleveys].* \t\tFROM [dbo].[Sarakeleveys]",
              "dataSource": "SqlServer dwitestvipusql VipunenTK"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization"
              },
              {
                "name": "TableWidgetSerialization"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Sarakeleveys"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "      SELECT [dbo].[Sarakeleveys].*   FROM [dbo].[Sarakeleveys] "
          }
        ]
      },
      {
        "name": "Muuttujat",
        "columns": [
          {
            "name": "Tilastovuosi",
            "dataType": "string",
            "sourceColumn": "Tilastovuosi",
            "displayFolder": "Aikamuuttujat"
          },
          {
            "name": "Aineisto",
            "dataType": "string",
            "sourceColumn": "Aineisto",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Aineisto_OTV",
            "dataType": "string",
            "sourceColumn": "Aineisto_OTV",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Kaikkien asteiden koulutus",
            "dataType": "string",
            "sourceColumn": "Kaikkien asteiden koulutus",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "OTV_Tilv",
            "dataType": "string",
            "sourceColumn": "OTV_Tilv",
            "displayFolder": "Aikamuuttujat"
          },
          {
            "name": "Äidinkieli",
            "dataType": "string",
            "sourceColumn": "Äidinkieli",
            "sortByColumn": "jarj_aidinkieli",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Äidinkieli (väestörakenne)",
            "dataType": "string",
            "sourceColumn": "Äidinkieli (väestörakenne)",
            "sortByColumn": "jarj_aidinkieli2",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Äidinkieli (suomi/muu)",
            "dataType": "string",
            "sourceColumn": "Äidinkieli (suomi/muu)",
            "sortByColumn": "jarj_aidinkieli3",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Asuinalueen AVI",
            "dataType": "string",
            "sourceColumn": "Asuinalueen AVI",
            "sortByColumn": "jarj_as_avi",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Asuinalueen ELY",
            "dataType": "string",
            "sourceColumn": "Asuinalueen ELY",
            "sortByColumn": "jarj_as_ely",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Asuinkunnan kielisuhde",
            "dataType": "string",
            "sourceColumn": "Asuinkunnan kielisuhde",
            "sortByColumn": "jarj_as_kielisuhde",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Asuinmaakunta",
            "dataType": "string",
            "sourceColumn": "Asuinmaakunta",
            "sortByColumn": "jarj_as_maakunta",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Asuinkunta",
            "dataType": "string",
            "sourceColumn": "Asuinkunta",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Til.v:tta edeltävä AVI",
            "dataType": "string",
            "sourceColumn": "Til.v:tta edeltävä AVI",
            "sortByColumn": "jarj_as_avi1x",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Til.v:tta edeltävä ELY",
            "dataType": "string",
            "sourceColumn": "Til.v:tta edeltävä ELY",
            "sortByColumn": "jarj_as_ely1x",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Til.v:tta ed. asuinkunnan kielisuhde",
            "dataType": "string",
            "sourceColumn": "Til.v:tta ed. asuinkunnan kielisuhde",
            "sortByColumn": "jarj_as_kielisuhde1x",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Til.v:tta ed. asuinmaakunta",
            "dataType": "string",
            "sourceColumn": "Til.v:tta ed. asuinmaakunta",
            "sortByColumn": "jarj_as_maakunta1x",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Til.v:tta ed. asuinkunta",
            "dataType": "string",
            "sourceColumn": "Til.v:tta ed. asuinkunta",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "2v til.v:tta ed. AVI",
            "dataType": "string",
            "sourceColumn": "2v til.v:tta ed. AVI",
            "sortByColumn": "jarj_as_avi2x",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "2v til.v:tta ed. ELY",
            "dataType": "string",
            "sourceColumn": "2v til.v:tta ed. ELY",
            "sortByColumn": "jarj_as_ely2x",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "2v til.v:tta ed. asuinkunnan kielisuhde",
            "dataType": "string",
            "sourceColumn": "2v til.v:tta ed. asuinkunnan kielisuhde",
            "sortByColumn": "jarj_as_kielisuhde2x",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "2v til.v:tta ed. asuinmaakunta",
            "dataType": "string",
            "sourceColumn": "2v til.v:tta ed. asuinmaakunta",
            "sortByColumn": "jarj_as_maakunta2x",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "2v til.v:tta ed. asuinkunta",
            "dataType": "string",
            "sourceColumn": "2v til.v:tta ed. asuinkunta",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Sukupuoli",
            "dataType": "string",
            "sourceColumn": "Sukupuoli",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Ikä",
            "dataType": "string",
            "sourceColumn": "Ikä",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Ikäryhmä",
            "dataType": "string",
            "sourceColumn": "Ikäryhmä",
            "sortByColumn": "jarj_ika5v",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Syntymävuosi",
            "dataType": "string",
            "sourceColumn": "Syntymävuosi",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Syntymäkuukausi",
            "dataType": "string",
            "sourceColumn": "Syntymäkuukausi",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Tutkinto (amk)",
            "dataType": "string",
            "sourceColumn": "Tutkinto (amk)",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Tutkinto (yo)",
            "dataType": "string",
            "sourceColumn": "Tutkinto (yo)",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutustyyppi",
            "dataType": "string",
            "sourceColumn": "Koulutustyyppi",
            "sortByColumn": "jarj_koultyyppi",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Kansalaisuus",
            "dataType": "string",
            "sourceColumn": "Kansalaisuus",
            "sortByColumn": "jarj_kansalaisuus",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Kansalaisuus (väestörakenne)",
            "dataType": "string",
            "sourceColumn": "Kansalaisuus (väestörakenne)",
            "sortByColumn": "jarj_kansalaisuus2",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Kansalaisuus (suomi/muu)",
            "dataType": "string",
            "sourceColumn": "Kansalaisuus (suomi/muu)",
            "sortByColumn": "jarj_kansalaisuus3",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Oppilaitos",
            "dataType": "string",
            "sourceColumn": "Oppilaitos",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Yliopisto",
            "dataType": "string",
            "sourceColumn": "Yliopisto",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Ammattikorkeakoulu",
            "dataType": "string",
            "sourceColumn": "Ammattikorkeakoulu",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Opetuskieli",
            "dataType": "string",
            "sourceColumn": "Opetuskieli",
            "sortByColumn": "jarjestys_opetuskieli",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Oppil. omistajatyyppi",
            "dataType": "string",
            "sourceColumn": "Oppil. omistajatyyppi",
            "sortByColumn": "jarjestys_omistajatyyppi",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Oppilaitostyyppi",
            "dataType": "string",
            "sourceColumn": "Oppilaitostyyppi",
            "sortByColumn": "jarjestys_oppilaitostyyppi",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Koulutuksen järjestäjä",
            "dataType": "string",
            "sourceColumn": "Koulutuksen järjestäjä",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Koul. järj. omistajatyyppi",
            "dataType": "string",
            "sourceColumn": "Koul. järj. omistajatyyppi",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Lähde",
            "dataType": "string",
            "sourceColumn": "Lähde",
            "sortByColumn": "lahde_koodi",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusohjelma",
            "dataType": "string",
            "sourceColumn": "Koulutusohjelma",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Kirjoillaolo (syys)",
            "dataType": "string",
            "sourceColumn": "Kirjoillaolo (syys)",
            "sortByColumn": "jarj_kirjolosyys",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Kirjoillaolo (tammi)",
            "dataType": "string",
            "sourceColumn": "Kirjoillaolo (tammi)",
            "sortByColumn": "jarj_kirjolotammi",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Rahoituslähde",
            "dataType": "string",
            "sourceColumn": "Rahoituslähde",
            "sortByColumn": "jarj_rahoitus",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Suuntautumisvaihtoehto",
            "dataType": "string",
            "sourceColumn": "Suuntautumisvaihtoehto",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutuksen kieli",
            "dataType": "string",
            "sourceColumn": "Koulutuksen kieli",
            "sortByColumn": "jarj_koulkiel",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Ensisijainen opinto-oikeus",
            "dataType": "string",
            "sourceColumn": "Ensisijainen opinto-oikeus",
            "sortByColumn": "jarj_ensop",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Tilauskoulutuksen sijaintimaa",
            "dataType": "string",
            "sourceColumn": "Tilauskoulutuksen sijaintimaa",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutussektori",
            "dataType": "string",
            "sourceColumn": "Koulutussektori",
            "sortByColumn": "jarj_koulsek",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Hallinnonala",
            "dataType": "string",
            "sourceColumn": "Hallinnonala",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusnimike",
            "dataType": "string",
            "sourceColumn": "Koulutusnimike",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutuslaji",
            "dataType": "string",
            "sourceColumn": "Koulutuslaji",
            "sortByColumn": "jarj_koullaji",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutuslaji2",
            "dataType": "string",
            "sourceColumn": "Koulutuslaji2",
            "sortByColumn": "jarj_koullaji2",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutuksen AVI",
            "dataType": "string",
            "sourceColumn": "Koulutuksen AVI",
            "sortByColumn": "jarjestys_avi",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutuksen ELY",
            "dataType": "string",
            "sourceColumn": "Koulutuksen ELY",
            "sortByColumn": "jarjestys_ely",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutuksen maakunta",
            "dataType": "string",
            "sourceColumn": "Koulutuksen maakunta",
            "sortByColumn": "jarjestys_maakunta",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koul. kunnan kielisuhde",
            "dataType": "string",
            "sourceColumn": "Koul. kunnan kielisuhde",
            "sortByColumn": "jarjestys_kielisuhde",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutuksen kunta",
            "dataType": "string",
            "sourceColumn": "Koulutuksen kunta",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Maakunta",
            "dataType": "string",
            "sourceColumn": "Maakunta",
            "sortByColumn": "jarj_kmaakunta2",
            "displayFolder": "Aluemuuttujat"
          },
          {
            "name": "Kunta",
            "dataType": "string",
            "sourceColumn": "Kunta",
            "displayFolder": "Aluemuuttujat"
          },
          {
            "name": "Koul. järjestäjän AVI",
            "dataType": "string",
            "sourceColumn": "Koul. järjestäjän AVI",
            "sortByColumn": "jarjestys_avi2",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Koul. järjestäjän ELY",
            "dataType": "string",
            "sourceColumn": "Koul. järjestäjän ELY",
            "sortByColumn": "jarjestys_ely2",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Koul. järjestäjän maakunta",
            "dataType": "string",
            "sourceColumn": "Koul. järjestäjän maakunta",
            "sortByColumn": "jarjestys_maakunta2",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Koul. järj. kunnan kielisuhde",
            "dataType": "string",
            "sourceColumn": "Koul. järj. kunnan kielisuhde",
            "sortByColumn": "jarjestys_kielisuhde2",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Koul. järjestäjän kunta",
            "dataType": "string",
            "sourceColumn": "Koul. järjestäjän kunta",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Oppilaitoksen AVI",
            "dataType": "string",
            "sourceColumn": "Oppilaitoksen AVI",
            "sortByColumn": "jarjestys_avi3",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Oppilaitoksen ELY",
            "dataType": "string",
            "sourceColumn": "Oppilaitoksen ELY",
            "sortByColumn": "jarjestys_ely3",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Oppilaitoksen maakunta",
            "dataType": "string",
            "sourceColumn": "Oppilaitoksen maakunta",
            "sortByColumn": "jarjestys_maakunta3",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Oppil. kunnan kielisuhde",
            "dataType": "string",
            "sourceColumn": "Oppil. kunnan kielisuhde",
            "sortByColumn": "jarjestys_kielisuhde3",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Oppilaitoksen kunta",
            "dataType": "string",
            "sourceColumn": "Oppilaitoksen kunta",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Kirjoihintulovuosi",
            "dataType": "string",
            "sourceColumn": "Kirjoihintulovuosi",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Kirjoihintulokausi",
            "dataType": "string",
            "sourceColumn": "Kirjoihintulokausi",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Kirjoihintulovuosi kk-sek",
            "dataType": "string",
            "sourceColumn": "Kirjoihintulovuosi (kk-sek.)",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Kirjoihintulovuosi kk-sek läsna",
            "dataType": "string",
            "sourceColumn": "Kirjoihintulovuosi (kk-sek. läsna)",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Kirjoihintulovuosi sek",
            "dataType": "string",
            "sourceColumn": "Kirjoihintulovuosi (sek.)",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Kirjoihintulovuosi sek läsnä",
            "dataType": "string",
            "sourceColumn": "Kirjoihintulovuosi (sek. läsnä)",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Kirjoihintulovuosi kk",
            "dataType": "string",
            "sourceColumn": "Kirjoihintulovuosi (kk)",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Kirjoihintulokausi kk",
            "dataType": "string",
            "sourceColumn": "Kirjoihintulokausi (kk)",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Kirjoihintulovuosi kk läsnä",
            "dataType": "string",
            "sourceColumn": "Kirjoihintulovuosi (kk läsnä)",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Kirjoihintulovuosi opala",
            "dataType": "string",
            "sourceColumn": "Kirjoihintulovuosi (op.ala)",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Kirjoihintulovuosi opala läsnä",
            "dataType": "string",
            "sourceColumn": "Kirjoihintulovuosi (op.ala läsnä)",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Kirjoihintulovuosi tutk",
            "dataType": "string",
            "sourceColumn": "Kirjoihintulovuosi (tutk.)",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Kirjoihintulokausi tutk",
            "dataType": "string",
            "sourceColumn": "Kirjoihintulokausi (tutk.)",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Suorittanut väh. 55 op",
            "dataType": "string",
            "sourceColumn": "Suorittanut väh. 55 op",
            "sortByColumn": "jarj_vah55",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Opiskelijan FTE-tieto",
            "dataType": "string",
            "sourceColumn": "Opiskelijan FTE-tieto",
            "sortByColumn": "jarj_op_fte",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Yliopistotunnus",
            "dataType": "string",
            "sourceColumn": "Yliopistotunnus",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Tiedekunta",
            "dataType": "string",
            "sourceColumn": "Tiedekunta",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Uusi/vanha opiskelija",
            "dataType": "string",
            "sourceColumn": "Uusi/vanha opiskelija",
            "sortByColumn": "jarj_uusivanha",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Opettajankelpoisuus",
            "dataType": "string",
            "sourceColumn": "Opettajankelpoisuus",
            "sortByColumn": "jarj_opettajankelpoisuus",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Hyväksytty avoimen yliop. suoritusten kautta",
            "dataType": "string",
            "sourceColumn": "Hyväksytty avoimen yliop. suoritusten kautta",
            "sortByColumn": "jarj_avoinvayla",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Tutkinnon suoritusvuosi",
            "dataType": "string",
            "sourceColumn": "Tutkinnon suoritusvuosi",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Tutk. suorituslukukausi",
            "dataType": "string",
            "sourceColumn": "Tutk. suorituslukukausi",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Tutk. suorituskuukausi",
            "dataType": "string",
            "sourceColumn": "Tutk. suorituskuukausi",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Kansalaisuus (maanosa)",
            "dataType": "string",
            "sourceColumn": "Kansalaisuus (maanosa)",
            "sortByColumn": "jarj_kans_maanosa",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "EU-maan kansalainen",
            "dataType": "string",
            "sourceColumn": "EU-maan kansalainen",
            "sortByColumn": "jarjestys_eumaa",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "ETA-maan kansalainen",
            "dataType": "string",
            "sourceColumn": "ETA-maan kansalainen",
            "sortByColumn": "jarjestys_etamaa",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Pohjoismaan kansalainen",
            "dataType": "string",
            "sourceColumn": "Pohjoismaan kansalainen",
            "sortByColumn": "jarj_pohj_kans",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "aineisto_otv_jarj",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "aineisto_otv_jarj"
          },
          {
            "name": "jarj_aidinkieli",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_aidinkieli"
          },
          {
            "name": "jarj_aidinkieli2",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_aidinkieli2"
          },
          {
            "name": "jarj_aidinkieli3",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_aidinkieli3"
          },
          {
            "name": "jarj_as_avi",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_as_avi"
          },
          {
            "name": "jarj_as_ely",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_as_ely"
          },
          {
            "name": "jarj_as_kielisuhde",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_as_kielisuhde"
          },
          {
            "name": "jarj_as_maakunta",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_as_maakunta"
          },
          {
            "name": "jarj_as_kunta",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_as_kunta"
          },
          {
            "name": "jarj_as_avi1x",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_as_avi1x"
          },
          {
            "name": "jarj_as_ely1x",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_as_ely1x"
          },
          {
            "name": "jarj_as_kielisuhde1x",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_as_kielisuhde1x"
          },
          {
            "name": "jarj_as_maakunta1x",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_as_maakunta1x"
          },
          {
            "name": "jarj_as_kunta1x",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_as_kunta1x"
          },
          {
            "name": "jarj_as_avi2x",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_as_avi2x"
          },
          {
            "name": "jarj_as_ely2x",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_as_ely2x"
          },
          {
            "name": "jarj_as_kielisuhde2x",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_as_kielisuhde2x"
          },
          {
            "name": "jarj_as_maakunta2x",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_as_maakunta2x"
          },
          {
            "name": "jarj_as_kunta2x",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_as_kunta2x"
          },
          {
            "name": "jarjestys_ika",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarjestys_ika"
          },
          {
            "name": "jarj_ika5v",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_ika5v"
          },
          {
            "name": "jarj_syntv",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_syntv"
          },
          {
            "name": "jarj_tutk_amk",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_tutk_amk"
          },
          {
            "name": "jarj_tutk_yo",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_tutk_yo"
          },
          {
            "name": "jarj_koultyyppi",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_koultyyppi"
          },
          {
            "name": "jarj_kansalaisuus",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_kansalaisuus"
          },
          {
            "name": "jarj_kansalaisuus2",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_kansalaisuus2"
          },
          {
            "name": "jarj_kansalaisuus3",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_kansalaisuus3"
          },
          {
            "name": "jarjestys_oppilaitos",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarjestys_oppilaitos"
          },
          {
            "name": "jarjestys_opetuskieli",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarjestys_opetuskieli"
          },
          {
            "name": "jarjestys_omistajatyyppi",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarjestys_omistajatyyppi"
          },
          {
            "name": "jarjestys_oppilaitostyyppi",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarjestys_oppilaitostyyppi"
          },
          {
            "name": "jarj_koulohjelma_amk",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_koulohjelma_amk"
          },
          {
            "name": "jarj_kirjolosyys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_kirjolosyys"
          },
          {
            "name": "jarj_kirjolotammi",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_kirjolotammi"
          },
          {
            "name": "jarj_rahoitus",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_rahoitus"
          },
          {
            "name": "jarj_suunnvaiht",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarj_suunnvaiht"
          },
          {
            "name": "jarj_koulkiel",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarj_koulkiel"
          },
          {
            "name": "jarj_koulkiel2",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarj_koulkiel2"
          },
          {
            "name": "jarj_ensop",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_ensop"
          },
          {
            "name": "jarj_tilauskoul",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_tilauskoul"
          },
          {
            "name": "jarj_koulsek",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_koulsek"
          },
          {
            "name": "jarj_hallinnonala",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_hallinnonala"
          },
          {
            "name": "jarjestys_koulutusaste2002",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarjestys_koulutusaste2002"
          },
          {
            "name": "jarjestys_koulutusala2002",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarjestys_koulutusala2002"
          },
          {
            "name": "jarjestys_opintoala1995",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarjestys_opintoala1995"
          },
          {
            "name": "jarjestys_opintoala2002",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarjestys_opintoala2002"
          },
          {
            "name": "jarj_koulnimike",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_koulnimike"
          },
          {
            "name": "jarj_koullaji",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_koullaji"
          },
          {
            "name": "jarj_koullaji2",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_koullaji2"
          },
          {
            "name": "jarjestys_avi",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarjestys_avi"
          },
          {
            "name": "jarjestys_ely",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarjestys_ely"
          },
          {
            "name": "jarjestys_maakunta",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarjestys_maakunta"
          },
          {
            "name": "jarjestys_kielisuhde",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarjestys_kielisuhde"
          },
          {
            "name": "jarj_kunta",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_kunta"
          },
          {
            "name": "jarj_kmaakunta2",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_kmaakunta2"
          },
          {
            "name": "jarj_kkunta2",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_kkunta2"
          },
          {
            "name": "jarjestys_avi2",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarjestys_avi2"
          },
          {
            "name": "jarjestys_ely2",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarjestys_ely2"
          },
          {
            "name": "jarjestys_maakunta2",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarjestys_maakunta2"
          },
          {
            "name": "jarjestys_kielisuhde2",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarjestys_kielisuhde2"
          },
          {
            "name": "jarj_kunta2",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_kunta2"
          },
          {
            "name": "jarjestys_avi3",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarjestys_avi3"
          },
          {
            "name": "jarjestys_ely3",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarjestys_ely3"
          },
          {
            "name": "jarjestys_maakunta3",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarjestys_maakunta3"
          },
          {
            "name": "jarjestys_kielisuhde3",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarjestys_kielisuhde3"
          },
          {
            "name": "jarj_kunta3",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_kunta3"
          },
          {
            "name": "jarj_lukukausi",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_lukukausi"
          },
          {
            "name": "jarj_lukukausi_kk",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_lukukausi_kk"
          },
          {
            "name": "jarj_vah55",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarj_vah55"
          },
          {
            "name": "jarj_op_fte",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_op_fte"
          },
          {
            "name": "jarj_tiedekunta",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_tiedekunta"
          },
          {
            "name": "jarj_uusivanha",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_uusivanha"
          },
          {
            "name": "jarj_opettajankelpoisuus",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_opettajankelpoisuus"
          },
          {
            "name": "jarj_avoinvayla",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_avoinvayla"
          },
          {
            "name": "jarj_suor_kk",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_suor_kk"
          },
          {
            "name": "jarj_kans_maanosa",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarj_kans_maanosa"
          },
          {
            "name": "jarjestys_eumaa",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarjestys_eumaa"
          },
          {
            "name": "jarjestys_etamaa",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarjestys_etamaa"
          },
          {
            "name": "jarj_pohj_kans",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_pohj_kans"
          },
          {
            "name": "aineisto_koodi",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "aineisto_koodi"
          },
          {
            "name": "ainesto_koodi_otv",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "ainesto_koodi_otv"
          },
          {
            "name": "aidinkieli_koodi",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "aidinkieli_koodi"
          },
          {
            "name": "aidinkieli2_koodi",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "aidinkieli2_koodi"
          },
          {
            "name": "aidinkieli3_koodi",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "aidinkieli3_koodi"
          },
          {
            "name": "Koodit Asuinmaakunta",
            "dataType": "string",
            "sourceColumn": "Koodit Asuinmaakunta",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koodit Asuinkunta",
            "dataType": "string",
            "sourceColumn": "Koodit Asuinkunta",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "asmaak1xmk",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "asmaak1xmk"
          },
          {
            "name": "asmaak1xk",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "asmaak1xk"
          },
          {
            "name": "syntk",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "syntk"
          },
          {
            "name": "Koodit Tutkinto amk",
            "dataType": "string",
            "sourceColumn": "Koodit Tutkinto (amk)",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koodit Tutkinto yo",
            "dataType": "string",
            "sourceColumn": "Koodit Tutkinto (yo)",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koodit Koulutustyyppi",
            "dataType": "string",
            "sourceColumn": "Koodit Koulutustyyppi",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "kansalaisuus_koodi",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "kansalaisuus_koodi"
          },
          {
            "name": "kansalaisuus2_koodi",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "kansalaisuus2_koodi"
          },
          {
            "name": "kansalaisuus3_koodi",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "kansalaisuus3_koodi"
          },
          {
            "name": "Koodit Oppilaitos",
            "dataType": "string",
            "sourceColumn": "Koodit Oppilaitos",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koodit Koulutuksen järjestäjä",
            "dataType": "string",
            "sourceColumn": "Koodit Koulutuksen järjestäjä",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "lahde_koodi",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "lahde_koodi"
          },
          {
            "name": "Koodit Koulutusohjelma",
            "dataType": "string",
            "sourceColumn": "Koodit Koulutusohjelma",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "kirjoillaolosyys_koodi",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "kirjoillaolosyys_koodi"
          },
          {
            "name": "kirjoillaolotammi_koodi",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "kirjoillaolotammi_koodi"
          },
          {
            "name": "ensiop",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "ensiop"
          },
          {
            "name": "Koodit Koulutusnimike",
            "dataType": "string",
            "sourceColumn": "Koodit Koulutusnimike",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koodit Koulutuksen maakunta",
            "dataType": "string",
            "sourceColumn": "Koodit Koulutuksen maakunta",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koodit Koulutuksen kunta",
            "dataType": "string",
            "sourceColumn": "Koodit Koulutuksen kunta",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koodit Maakunta",
            "dataType": "string",
            "sourceColumn": "Koodit Maakunta",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koodit Kunta",
            "dataType": "string",
            "sourceColumn": "Koodit Kunta",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koodit Koul järj maakunta",
            "dataType": "string",
            "sourceColumn": "Koodit Koul. järj. maakunta",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koodit Koul järj kunta",
            "dataType": "string",
            "sourceColumn": "Koodit Koul. järj. kunta",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koodit Oppil maakunta",
            "dataType": "string",
            "sourceColumn": "Koodit Oppil. maakunta",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koodit Oppil kunta",
            "dataType": "string",
            "sourceColumn": "Koodit Oppil. kunta",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "alvv",
            "dataType": "int64",
            "sourceColumn": "alvv",
            "displayFolder": "Aloitusvuosimuuttujat"
          },
          {
            "name": "alkk",
            "dataType": "int64",
            "sourceColumn": "alkk",
            "displayFolder": "Aloitusvuosimuuttujat"
          },
          {
            "name": "alvv_kksek",
            "dataType": "int64",
            "sourceColumn": "alvv_kksek",
            "displayFolder": "Aloitusvuosimuuttujat"
          },
          {
            "name": "alvv_kksek_lasna",
            "dataType": "int64",
            "sourceColumn": "alvv_kksek_lasna",
            "displayFolder": "Aloitusvuosimuuttujat"
          },
          {
            "name": "alvv_sek",
            "dataType": "int64",
            "sourceColumn": "alvv_sek",
            "displayFolder": "Aloitusvuosimuuttujat"
          },
          {
            "name": "alvv_sek_lasna",
            "dataType": "int64",
            "sourceColumn": "alvv_sek_lasna",
            "displayFolder": "Aloitusvuosimuuttujat"
          },
          {
            "name": "alvv_kk",
            "dataType": "int64",
            "sourceColumn": "alvv_kk",
            "displayFolder": "Aloitusvuosimuuttujat"
          },
          {
            "name": "alkk_kk",
            "dataType": "int64",
            "sourceColumn": "alkk_kk",
            "displayFolder": "Aloitusvuosimuuttujat"
          },
          {
            "name": "alvv_kk_lasna",
            "dataType": "int64",
            "sourceColumn": "alvv_kk_lasna",
            "displayFolder": "Aloitusvuosimuuttujat"
          },
          {
            "name": "alvv_opa",
            "dataType": "int64",
            "sourceColumn": "alvv_opa",
            "displayFolder": "Aloitusvuosimuuttujat"
          },
          {
            "name": "alvv_opa_lasna",
            "dataType": "int64",
            "sourceColumn": "alvv_opa_lasna",
            "displayFolder": "Aloitusvuosimuuttujat"
          },
          {
            "name": "kirtu1v",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "kirtu1v"
          },
          {
            "name": "kirtu1k",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "kirtu1k"
          },
          {
            "name": "op55_koodi",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "op55_koodi"
          },
          {
            "name": "suorv",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "suorv"
          },
          {
            "name": "suor_lk",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "suor_lk"
          },
          {
            "name": "suor_kk",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "suor_kk"
          },
          {
            "name": "Statistikår",
            "dataType": "string",
            "sourceColumn": "Statistikår",
            "displayFolder": "Tidsvariabler"
          },
          {
            "name": "Modersmål",
            "dataType": "string",
            "sourceColumn": "Modersmål",
            "sortByColumn": "jarj_aidinkieli",
            "displayFolder": "Personvariabler"
          },
          {
            "name": "Modersmål (utbildningsstruktur)",
            "dataType": "string",
            "sourceColumn": "Modersmål (utbildningsstruktur)",
            "sortByColumn": "jarj_aidinkieli2",
            "displayFolder": "Personvariabler"
          },
          {
            "name": "Modersmål (finska/andra)",
            "dataType": "string",
            "sourceColumn": "Modersmål (finska/andra)SV",
            "sortByColumn": "jarj_aidinkieli3",
            "displayFolder": "Personvariabler"
          },
          {
            "name": "Bostadslandskap",
            "dataType": "string",
            "sourceColumn": "Bostadslandskap",
            "sortByColumn": "jarj_as_maakunta",
            "displayFolder": "Personvariabler"
          },
          {
            "name": "Bostadskommun",
            "dataType": "string",
            "sourceColumn": "Bostadskommun",
            "displayFolder": "Personvariabler"
          },
          {
            "name": "Kön",
            "dataType": "string",
            "sourceColumn": "Kön",
            "displayFolder": "Personvariabler"
          },
          {
            "name": "Ålder",
            "dataType": "string",
            "sourceColumn": "Ålder",
            "displayFolder": "Personvariabler"
          },
          {
            "name": "Åldersgrupp",
            "dataType": "string",
            "sourceColumn": "Åldersgrupp",
            "sortByColumn": "jarj_ika5v",
            "displayFolder": "Personvariabler"
          },
          {
            "name": "Födelseår",
            "dataType": "string",
            "sourceColumn": "Födelseår",
            "displayFolder": "Personvariabler"
          },
          {
            "name": "Examen (yrkehögskola)",
            "dataType": "string",
            "sourceColumn": "Examen (yrkehögskola)",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Examen (universitet)",
            "dataType": "string",
            "sourceColumn": "Examen (universitet)",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Typ av utbildning",
            "dataType": "string",
            "sourceColumn": "Typ av utbildning",
            "sortByColumn": "jarj_koultyyppi",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Medborgarskap",
            "dataType": "string",
            "sourceColumn": "Medborgarskap",
            "sortByColumn": "jarj_kansalaisuus",
            "displayFolder": "Personvariabler"
          },
          {
            "name": "Medborgarskap (utbildningsstruktur)",
            "dataType": "string",
            "sourceColumn": "Medborgarskap (utbildningsstruktur)",
            "sortByColumn": "jarj_kansalaisuus2",
            "displayFolder": "Personvariabler"
          },
          {
            "name": "Medborgarskap (finländare/andra)",
            "dataType": "string",
            "sourceColumn": "Medborgarskap (finska/andra)",
            "sortByColumn": "jarj_kansalaisuus3",
            "displayFolder": "Personvariabler"
          },
          {
            "name": "Läroanstalt",
            "dataType": "string",
            "sourceColumn": "Läroanstalt",
            "displayFolder": "Organisationsvariabler"
          },
          {
            "name": "Universitet",
            "dataType": "string",
            "sourceColumn": "Universitet",
            "displayFolder": "Organisationsvariabler"
          },
          {
            "name": "Yrkeshögskola",
            "dataType": "string",
            "sourceColumn": "Yrkeshögskola",
            "displayFolder": "Organisationsvariabler"
          },
          {
            "name": "Utbildningsprogram",
            "dataType": "string",
            "sourceColumn": "Utbildningsprogram",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Inskrivning (september)",
            "dataType": "string",
            "sourceColumn": "Inskrivning (september)",
            "sortByColumn": "jarj_kirjolosyys",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Inskrivning (januari)",
            "dataType": "string",
            "sourceColumn": "Inskrivning (januari)",
            "sortByColumn": "jarj_kirjolotammi",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Finansieringskälla",
            "dataType": "string",
            "sourceColumn": "Finansieringskälla",
            "sortByColumn": "jarj_rahoitus",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Utbildningssektor",
            "dataType": "string",
            "sourceColumn": "Utbildningssektor",
            "sortByColumn": "jarj_koulsek",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Utbildningsbenämning",
            "dataType": "string",
            "sourceColumn": "Utbildningsbenämning",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Utbildningsslag",
            "dataType": "string",
            "sourceColumn": "Utbildningsslag",
            "sortByColumn": "jarj_koullaji",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Utbildningsslag2",
            "dataType": "string",
            "sourceColumn": "Utbildningsslag2",
            "sortByColumn": "jarj_koullaji2",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Utbildningens landskap",
            "dataType": "string",
            "sourceColumn": "Utbildningens landskap",
            "sortByColumn": "jarjestys_maakunta",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Utbildningens kommun",
            "dataType": "string",
            "sourceColumn": "Utbildningens kommun",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Landskap",
            "dataType": "string",
            "sourceColumn": "Landskap",
            "sortByColumn": "jarj_kmaakunta2",
            "displayFolder": "Landskapvariabler"
          },
          {
            "name": "Kommun",
            "dataType": "string",
            "sourceColumn": "Kommun",
            "displayFolder": "Landskapvariabler"
          },
          {
            "name": "År då utbildningen avlagts",
            "dataType": "string",
            "sourceColumn": "År då utbildningen avlagts",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Medborgarskap (världsdel)",
            "dataType": "string",
            "sourceColumn": "Medborgarskap (världsdel)",
            "sortByColumn": "jarj_kans_maanosa",
            "displayFolder": "Personvariabler"
          },
          {
            "name": "Medborgare i ett EU-land",
            "dataType": "string",
            "sourceColumn": "Medborgare i ett EU-land",
            "sortByColumn": "jarjestys_eumaa",
            "displayFolder": "Personvariabler"
          },
          {
            "name": "Medborgare i ett EES-land",
            "dataType": "string",
            "sourceColumn": "Medborgare i ett EES-land",
            "sortByColumn": "jarjestys_etamaa",
            "displayFolder": "Personvariabler"
          },
          {
            "name": "Medborgare i ett nordiskt land",
            "dataType": "string",
            "sourceColumn": "Medborgare i ett nordiskt land",
            "sortByColumn": "jarj_pohj_kans",
            "displayFolder": "Personvariabler"
          },
          {
            "name": "Statistical year",
            "dataType": "string",
            "sourceColumn": "Statistical year",
            "displayFolder": "Time variables"
          },
          {
            "name": "Mother tongue",
            "dataType": "string",
            "sourceColumn": "Mother tongue",
            "sortByColumn": "jarj_aidinkieli",
            "displayFolder": "Person variables"
          },
          {
            "name": "Mother tongue (ed. structure)",
            "dataType": "string",
            "sourceColumn": "Mother tongue (ed. structure)",
            "sortByColumn": "jarj_aidinkieli2",
            "displayFolder": "Person variables"
          },
          {
            "name": "Mother tongue (Finnish/other)",
            "dataType": "string",
            "sourceColumn": "Mother tongue (Finnish/Other)",
            "sortByColumn": "jarj_aidinkieli3",
            "displayFolder": "Person variables"
          },
          {
            "name": "Region of residence",
            "dataType": "string",
            "sourceColumn": "Region of residence",
            "sortByColumn": "jarj_as_maakunta",
            "displayFolder": "Person variables"
          },
          {
            "name": "Municipality of residence",
            "dataType": "string",
            "sourceColumn": "Municipality of residence",
            "displayFolder": "Person variables"
          },
          {
            "name": "Gender",
            "dataType": "string",
            "sourceColumn": "Gender",
            "displayFolder": "Person variables"
          },
          {
            "name": "Age",
            "dataType": "string",
            "sourceColumn": "Age",
            "displayFolder": "Person variables"
          },
          {
            "name": "Agegroup",
            "dataType": "string",
            "sourceColumn": "Agegroup",
            "sortByColumn": "jarj_ika5v",
            "displayFolder": "Person variables"
          },
          {
            "name": "Year of birth",
            "dataType": "string",
            "sourceColumn": "Year of birth",
            "displayFolder": "Person variables"
          },
          {
            "name": "Degree (polytechnic)",
            "dataType": "string",
            "sourceColumn": "Degree (polytechnic)",
            "displayFolder": "Education variables"
          },
          {
            "name": "Degree (university)",
            "dataType": "string",
            "sourceColumn": "Degree (university)",
            "displayFolder": "Education variables"
          },
          {
            "name": "Type of education",
            "dataType": "string",
            "sourceColumn": "Type of education",
            "sortByColumn": "jarj_koultyyppi",
            "displayFolder": "Education variables"
          },
          {
            "name": "Nationality",
            "dataType": "string",
            "sourceColumn": "Nationality",
            "sortByColumn": "jarj_kansalaisuus",
            "displayFolder": "Person variables"
          },
          {
            "name": "Nationality (ed. structure)",
            "dataType": "string",
            "sourceColumn": "Nationality (ed. structure)",
            "sortByColumn": "jarj_kansalaisuus2",
            "displayFolder": "Person variables"
          },
          {
            "name": "Nationality (Finn/other)",
            "dataType": "string",
            "sourceColumn": "Nationality (Finn/Other)",
            "sortByColumn": "jarj_kansalaisuus3",
            "displayFolder": "Person variables"
          },
          {
            "name": "Educational institution",
            "dataType": "string",
            "sourceColumn": "Educational institution",
            "displayFolder": "Organisation variables"
          },
          {
            "name": "University",
            "dataType": "string",
            "sourceColumn": "University",
            "displayFolder": "Organisation variables"
          },
          {
            "name": "Polytechnic",
            "dataType": "string",
            "sourceColumn": "Polytechnic",
            "displayFolder": "Organisation variables"
          },
          {
            "name": "Degree programme",
            "dataType": "string",
            "sourceColumn": "Degree programme",
            "displayFolder": "Education variables"
          },
          {
            "name": "Enrollment status (sept.)",
            "dataType": "string",
            "sourceColumn": "Enrollment status (sept.)",
            "sortByColumn": "jarj_kirjolosyys",
            "displayFolder": "Education variables"
          },
          {
            "name": "Enrollment status (jan.)",
            "dataType": "string",
            "sourceColumn": "Enrollment status (jan.)",
            "sortByColumn": "jarj_kirjolotammi",
            "displayFolder": "Education variables"
          },
          {
            "name": "Source of funding",
            "dataType": "string",
            "sourceColumn": "Source of funding",
            "sortByColumn": "jarj_rahoitus",
            "displayFolder": "Education variables"
          },
          {
            "name": "Sector of education",
            "dataType": "string",
            "sourceColumn": "Sector of education",
            "sortByColumn": "jarj_koulsek",
            "displayFolder": "Education variables"
          },
          {
            "name": "Name of education",
            "dataType": "string",
            "sourceColumn": "Name of education",
            "displayFolder": "Education variables"
          },
          {
            "name": "Form of education",
            "dataType": "string",
            "sourceColumn": "Form of education",
            "sortByColumn": "jarj_koullaji",
            "displayFolder": "Education variables"
          },
          {
            "name": "Form of education2",
            "dataType": "string",
            "sourceColumn": "Form of education2",
            "sortByColumn": "jarj_koullaji2",
            "displayFolder": "Education variables"
          },
          {
            "name": "Region of education",
            "dataType": "string",
            "sourceColumn": "Region of education",
            "sortByColumn": "jarjestys_maakunta",
            "displayFolder": "Education variables"
          },
          {
            "name": "Municipality of education",
            "dataType": "string",
            "sourceColumn": "Municipality of education",
            "displayFolder": "Education variables"
          },
          {
            "name": "Region",
            "dataType": "string",
            "sourceColumn": "Region",
            "sortByColumn": "jarj_kmaakunta2",
            "displayFolder": "Region variables"
          },
          {
            "name": "Municipality",
            "dataType": "string",
            "sourceColumn": "Municipality",
            "displayFolder": "Region variables"
          },
          {
            "name": "Year of enrollment",
            "dataType": "string",
            "sourceColumn": "Year of enrollment",
            "displayFolder": "Education variables"
          },
          {
            "name": "Term of enrollment",
            "dataType": "string",
            "sourceColumn": "Term of enrollment",
            "displayFolder": "Education variables"
          },
          {
            "name": "Year of enrollment HE sec",
            "dataType": "string",
            "sourceColumn": "Year of enrollment (HE sec.)",
            "displayFolder": "Education variables"
          },
          {
            "name": "Year of enrollment HE sec present",
            "dataType": "string",
            "sourceColumn": "Year of enrollment (HE sec. present)",
            "displayFolder": "Education variables"
          },
          {
            "name": "Year of enrollment sec",
            "dataType": "string",
            "sourceColumn": "Year of enrollment (sec.)",
            "displayFolder": "Education variables"
          },
          {
            "name": "Year of enrollment sec present",
            "dataType": "string",
            "sourceColumn": "Year of enrollment (sec. present)",
            "displayFolder": "Education variables"
          },
          {
            "name": "Year of enrollment ed inst",
            "dataType": "string",
            "sourceColumn": "Year of enrollment (ed. inst.)",
            "displayFolder": "Education variables"
          },
          {
            "name": "Term of enrollment ed inst",
            "dataType": "string",
            "sourceColumn": "Term of enrollment (ed. inst.)",
            "displayFolder": "Education variables"
          },
          {
            "name": "Year of enrollment ed inst present",
            "dataType": "string",
            "sourceColumn": "Year of enrollment (ed. inst. present)",
            "displayFolder": "Education variables"
          },
          {
            "name": "Year of enrollment subfield of ed",
            "dataType": "string",
            "sourceColumn": "Year of enrollment (subfield of ed.)",
            "displayFolder": "Education variables"
          },
          {
            "name": "Year of enrollment subfield of ed present",
            "dataType": "string",
            "sourceColumn": "Year of enrollment (subfield of ed. present)",
            "displayFolder": "Education variables"
          },
          {
            "name": "Year of enrollment degree",
            "dataType": "string",
            "sourceColumn": "Year of enrollment (degree)",
            "displayFolder": "Education variables"
          },
          {
            "name": "Term of enrollment degree",
            "dataType": "string",
            "sourceColumn": "Term of enrollment (degree)",
            "displayFolder": "Education variables"
          },
          {
            "name": "Year of graduation",
            "dataType": "string",
            "sourceColumn": "Year of graduation",
            "displayFolder": "Education variables"
          },
          {
            "name": "Term of graduation",
            "dataType": "string",
            "sourceColumn": "Term of graduation",
            "displayFolder": "Education variables"
          },
          {
            "name": "Month of graduation",
            "dataType": "string",
            "sourceColumn": "Month of graduation",
            "displayFolder": "Education variables"
          },
          {
            "name": "Nationality (continent)",
            "dataType": "string",
            "sourceColumn": "Nationality (continent)",
            "sortByColumn": "jarj_kans_maanosa",
            "displayFolder": "Person variables"
          },
          {
            "name": "Citizen of EU nation",
            "dataType": "string",
            "sourceColumn": "Citizen of EU nation",
            "sortByColumn": "jarjestys_eumaa",
            "displayFolder": "Person variables"
          },
          {
            "name": "Citizen of EEA nation",
            "dataType": "string",
            "sourceColumn": "Citizen of EEA nation",
            "sortByColumn": "jarjestys_etamaa",
            "displayFolder": "Person variables"
          },
          {
            "name": "Citizen of a nordic nation",
            "dataType": "string",
            "sourceColumn": "Citizen of a nordic nation",
            "sortByColumn": "jarj_pohj_kans",
            "displayFolder": "Person variables"
          },
          {
            "name": "Koulutusaste, taso 1",
            "dataType": "string",
            "sourceColumn": "Koulutusaste, taso 1",
            "sortByColumn": "jarj_isced_koulast1",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusaste, taso 2",
            "dataType": "string",
            "sourceColumn": "Koulutusaste, taso 2",
            "sortByColumn": "jarj_isced_koulast2",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusala, taso 1",
            "dataType": "string",
            "sourceColumn": "Koulutusala, taso 1",
            "sortByColumn": "jarj_isced_koulala1",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusala, taso 2",
            "dataType": "string",
            "sourceColumn": "Koulutusala, taso 2",
            "sortByColumn": "jarj_isced_koulala2",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusala, taso 3",
            "dataType": "string",
            "sourceColumn": "Koulutusala, taso 3",
            "sortByColumn": "jarj_isced_koulala3",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "OKM ohjauksen ala korkeak.",
            "dataType": "string",
            "sourceColumn": "OKM ohjauksen ala, korkeak.",
            "sortByColumn": "jarj_isced_okmohjaus1",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Utbildn.nivå, nivå 1",
            "dataType": "string",
            "sourceColumn": "Utbildn.nivå, nivå 1",
            "sortByColumn": "jarj_isced_koulast1",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Utbildn.nivå, nivå 2",
            "dataType": "string",
            "sourceColumn": "Utbildn.nivå, nivå 2",
            "sortByColumn": "jarj_isced_koulast2",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Utbildn.område, nivå 1",
            "dataType": "string",
            "sourceColumn": "Utbildn.område, nivå 1",
            "sortByColumn": "jarj_isced_koulala1",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Utbildn.område, nivå 2",
            "dataType": "string",
            "sourceColumn": "Utbildn.område, nivå 2",
            "sortByColumn": "jarj_isced_koulala2",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Utbildn.område, nivå 3",
            "dataType": "string",
            "sourceColumn": "Utbildn.område, nivå 3",
            "sortByColumn": "jarj_isced_koulala3",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "UKM-styrningsområde högskolor",
            "dataType": "string",
            "sourceColumn": "UKM-styrningsområde, högskolor",
            "sortByColumn": "jarj_isced_okmohjaus1",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Level of ed., tier 1",
            "dataType": "string",
            "sourceColumn": "Level of ed., tier 1",
            "sortByColumn": "jarj_isced_koulast1",
            "displayFolder": "Education variables"
          },
          {
            "name": "Level of ed., tier 2",
            "dataType": "string",
            "sourceColumn": "Level of ed., tier 2",
            "sortByColumn": "jarj_isced_koulast2",
            "displayFolder": "Education variables"
          },
          {
            "name": "Field of education, tier 1",
            "dataType": "string",
            "sourceColumn": "Field of education, tier 1",
            "displayFolder": "Education variables"
          },
          {
            "name": "Field of education, tier 2",
            "dataType": "string",
            "sourceColumn": "Field of education, tier 2",
            "displayFolder": "Education variables"
          },
          {
            "name": "Field of education, tier 3",
            "dataType": "string",
            "sourceColumn": "Field of education, tier 3",
            "displayFolder": "Education variables"
          },
          {
            "name": "Field of ed. HE steering",
            "dataType": "string",
            "sourceColumn": "Field of ed., HE steering",
            "sortByColumn": "jarj_isced_okmohjaus1",
            "displayFolder": "Education variables"
          },
          {
            "name": "jarj_isced_koulast1",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_isced_koulast1"
          },
          {
            "name": "jarj_isced_koulast2",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_isced_koulast2"
          },
          {
            "name": "jarj_isced_koulala1",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_isced_koulala1"
          },
          {
            "name": "jarj_isced_koulala2",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_isced_koulala2"
          },
          {
            "name": "jarj_isced_koulala3",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_isced_koulala3"
          },
          {
            "name": "jarj_isced_okmohjaus1",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_isced_okmohjaus1"
          },
          {
            "name": "Koodit Koulutusaste taso 1",
            "dataType": "string",
            "sourceColumn": "Koodit Koulutusaste, taso 1",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koodit Koulutusaste taso 2",
            "dataType": "string",
            "sourceColumn": "Koodit Koulutusaste, taso 2",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koodit Koulutusala taso 1",
            "dataType": "string",
            "sourceColumn": "Koodit Koulutusala, taso 1",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koodit Koulutusala taso 2",
            "dataType": "string",
            "sourceColumn": "Koodit Koulutusala, taso 2",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koodit Koulutusala taso 3",
            "dataType": "string",
            "sourceColumn": "Koodit Koulutusala, taso 3",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koodit OKM ohjauksen ala korkeak",
            "dataType": "string",
            "sourceColumn": "Koodit OKM ohjauksen ala, korkeak.",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Opisk2",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Opisk2"
          },
          {
            "name": "Aloit2",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Aloit2"
          },
          {
            "name": "lkm_op55",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "lkm_op55"
          },
          {
            "name": "lkm_op0",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "lkm_op0"
          },
          {
            "name": "lkm_op1_14",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "lkm_op1_14"
          },
          {
            "name": "lkm_op15_29",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "lkm_op15_29"
          },
          {
            "name": "lkm_op30_44",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "lkm_op30_44"
          },
          {
            "name": "lkm_op45_59",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "lkm_op45_59"
          },
          {
            "name": "lkm_op60_74",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "lkm_op60_74"
          },
          {
            "name": "lkm_op75_89",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "lkm_op75_89"
          },
          {
            "name": "lkm_op90_104",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "lkm_op90_104"
          },
          {
            "name": "lkm_op105_119",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "lkm_op105_119"
          },
          {
            "name": "lkm_op120_",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "lkm_op120_"
          },
          {
            "name": "aloittaneet_kirjoihintulovuosi",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "aloittaneet_kirjoihintulovuosi"
          },
          {
            "name": "aloittaneet_korkeakoulusektori",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "aloittaneet_korkeakoulusektori"
          },
          {
            "name": "aloittaneet_korkeakoulusektori_lasnaoleva",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "aloittaneet_korkeakoulusektori_lasnaoleva"
          },
          {
            "name": "aloittaneet_sektori",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "aloittaneet_sektori"
          },
          {
            "name": "aloittaneet_sektori_lasnaoleva",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "aloittaneet_sektori_lasnaoleva"
          },
          {
            "name": "aloittaneet_korkeakoulu",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "aloittaneet_korkeakoulu"
          },
          {
            "name": "aloittaneet_korkeakoulu_lasnaoleva",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "aloittaneet_korkeakoulu_lasnaoleva"
          },
          {
            "name": "aloittaneet_opintoala",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "aloittaneet_opintoala"
          },
          {
            "name": "aloittaneet_opintoala_lasnaoleva",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "aloittaneet_opintoala_lasnaoleva"
          },
          {
            "name": "opiskelijat_lasna",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "opiskelijat_lasna"
          },
          {
            "name": "opiskelijat_fte",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "opiskelijat_fte"
          },
          {
            "name": "lkm_lasnalk",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "lkm_lasnalk"
          },
          {
            "name": "lkm_poissalk",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "lkm_poissalk"
          },
          {
            "name": "op_suoritettavien_laajuus",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "op_suoritettavien_laajuus"
          },
          {
            "name": "op_edellinen_syksy",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "op_edellinen_syksy"
          },
          {
            "name": "op_edellinen_kevat",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "op_edellinen_kevat"
          },
          {
            "name": "op_kertyma_edel_lkv_loppu",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "op_kertyma_edel_lkv_loppu"
          },
          {
            "name": "Tutk2",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Tutk2"
          },
          {
            "name": "op_amk_yhteensa",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "op_amk_yhteensa"
          },
          {
            "name": "op_amk_yleissiv_amm_opplait",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "op_amk_yleissiv_amm_opplait"
          },
          {
            "name": "op_amk_muualla",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "op_amk_muualla"
          },
          {
            "name": "op_amk_oma_amk",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "op_amk_oma_amk"
          },
          {
            "name": "op_amk_muu_amk",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "op_amk_muu_amk"
          },
          {
            "name": "op_amk_yliopistoissa",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "op_amk_yliopistoissa"
          },
          {
            "name": "op_amk_ulkomailla",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "op_amk_ulkomailla"
          },
          {
            "name": "op_yo_yhteensa",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "op_yo_yhteensa"
          },
          {
            "name": "op_yo_ulkomailla",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "op_yo_ulkomailla"
          },
          {
            "name": "op_yo_muualla",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "op_yo_muualla"
          },
          {
            "name": "op_yo_oma_yo",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "op_yo_oma_yo"
          },
          {
            "name": "op_yo_avoimessa",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "op_yo_avoimessa"
          },
          {
            "name": "op_yo_muu_yo",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "op_yo_muu_yo"
          },
          {
            "name": "op_yo_ammattikorkeakouluissa",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "op_yo_ammattikorkeakouluissa"
          },
          {
            "name": "ika19_21_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ika19_21_lkm"
          },
          {
            "name": "ika20_24_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ika20_24_lkm"
          },
          {
            "name": "ika25_34_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ika25_34_lkm"
          },
          {
            "name": "ika25_64_lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ika25_64_lkm"
          },
          {
            "name": "Kirjoihintulovuosi (TK määritelmä)",
            "dataType": "string",
            "sourceColumn": "Kirjoihintulovuosi (TK määritelmä)",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Year of enrollment (Statistic Finland's definition)",
            "dataType": "string",
            "sourceColumn": "Year of enrollment (Statistic Finland's definition)",
            "displayFolder": "Education variables"
          },
          {
            "name": "Tutkinto-oikeusvuosi",
            "dataType": "string",
            "sourceColumn": "Tutkinto-oikeusvuosi",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Päätieteenala",
            "dataType": "string",
            "sourceColumn": "Päätieteenala",
            "sortByColumn": "jarjestys_paatieteenala2010",
            "displayFolder": "Tieteenalamuuttujat"
          },
          {
            "name": "Tieteenala",
            "dataType": "string",
            "sourceColumn": "Tieteenala",
            "sortByColumn": "jarjestys_tieteenala2010",
            "displayFolder": "Tieteenalamuuttujat"
          },
          {
            "name": "jarjestys_paatieteenala2010",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarjestys_paatieteenala2010"
          },
          {
            "name": "jarjestys_tieteenala2010",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarjestys_tieteenala2010"
          },
          {
            "name": "Huvudsakligt vetenskapsområde",
            "dataType": "string",
            "sourceColumn": "Huvudsakligt vetenskapsområde",
            "sortByColumn": "jarjestys_paatieteenala2010",
            "displayFolder": "Variabler för vetenskapsgren"
          },
          {
            "name": "Vetenskapsområde",
            "dataType": "string",
            "sourceColumn": "Vetenskapsområde",
            "sortByColumn": "jarjestys_tieteenala2010",
            "displayFolder": "Variabler för vetenskapsgren"
          },
          {
            "name": "Main discipline",
            "dataType": "string",
            "sourceColumn": "Main discipline",
            "sortByColumn": "jarjestys_paatieteenala2010",
            "displayFolder": "Discipline variables"
          },
          {
            "name": "Discipline",
            "dataType": "string",
            "sourceColumn": "Discipline",
            "sortByColumn": "jarjestys_tieteenala2010",
            "displayFolder": "Discipline variables"
          },
          {
            "name": "jarj_rahoitusala2016_yo",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_rahoitusala2016_yo"
          },
          {
            "name": "jarj_rahoitusala2016_amk",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_rahoitusala2016_amk"
          },
          {
            "name": "jarj_rahoitusala2021_yo",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarj_rahoitusala2021_yo"
          },
          {
            "name": "Rahoitusmallialat yo 2017-2020",
            "dataType": "string",
            "sourceColumn": "Rahoitusmallialat yo 2017-2020",
            "sortByColumn": "jarj_rahoitusala2016_yo",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Rahoitusmallialat amk 2017-2020",
            "dataType": "string",
            "sourceColumn": "Rahoitusmallialat amk 2017-2020",
            "sortByColumn": "jarj_rahoitusala2016_amk",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Rahoitusmallialat yo 2021-2024",
            "dataType": "string",
            "sourceColumn": "Rahoitusmallialat yo 2021-2024",
            "sortByColumn": "jarj_rahoitusala2021_yo",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Rahoitusmallialat amk 2021-2024",
            "dataType": "string",
            "sourceColumn": "Rahoitusmallialat amk 2021-2024",
            "sortByColumn": "jarj_rahoitusala2016_amk",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Oppilaitos (tilastovuosi)",
            "dataType": "string",
            "sourceColumn": "Oppilaitos (tilastovuosi)",
            "sortByColumn": "jarjestys_oppilaitos_tilv",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Koulutuksen järjestäjä (tilastovuosi)",
            "dataType": "string",
            "sourceColumn": "Koulutuksen järjestäjä (tilastovuosi)",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "jarjestys_oppilaitos_tilv",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarjestys_oppilaitos_tilv"
          },
          {
            "name": "Koulutusaste (2002) ",
            "dataType": "string",
            "sourceColumn": "Koulutusaste (2002)",
            "sortByColumn": "jarjestys_koulutusaste2002",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusala (2002) ",
            "dataType": "string",
            "sourceColumn": "Koulutusala (2002)",
            "sortByColumn": "jarjestys_koulutusala2002",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koulutusala (1995) ",
            "dataType": "string",
            "sourceColumn": "Koulutusala (1995)",
            "sortByColumn": "jarjestys_opintoala1995",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Opintoala (2002) ",
            "dataType": "string",
            "sourceColumn": "Opintoala (2002)",
            "sortByColumn": "jarjestys_opintoala2002",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Koodit Koulutusaste (2002)",
            "dataType": "string",
            "sourceColumn": "Koodit Koulutusaste 2002",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koodit Koulutusala (2002)",
            "dataType": "string",
            "sourceColumn": "Koodit Koulutusala 2002",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koodit Koulutusala (1995)",
            "dataType": "string",
            "sourceColumn": "Koodit Koulutusala 1995",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Koodit Opintoala (2002)",
            "dataType": "string",
            "sourceColumn": "Koodit Opintoala 2002",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Utbildningsnivå (2002) ",
            "dataType": "string",
            "sourceColumn": "Utbildningsnivå (2002)",
            "sortByColumn": "jarjestys_koulutusaste2002",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Utbildningsområde (2002) ",
            "dataType": "string",
            "sourceColumn": "Utbildningsområde (2002)",
            "sortByColumn": "jarjestys_koulutusala2002",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Utbildningsområde (1995) ",
            "dataType": "string",
            "sourceColumn": "Utbildningsområde (1995)",
            "sortByColumn": "jarjestys_opintoala1995",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Studieområde (2002) ",
            "dataType": "string",
            "sourceColumn": "Studieområde (2002)",
            "sortByColumn": "jarjestys_opintoala2002",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Level of education (2002) ",
            "dataType": "string",
            "sourceColumn": "Level of education (2002)",
            "sortByColumn": "jarjestys_koulutusaste2002",
            "displayFolder": "Education variables"
          },
          {
            "name": "Field of education (2002) ",
            "dataType": "string",
            "sourceColumn": "Field of education (2002)",
            "sortByColumn": "jarjestys_koulutusala2002",
            "displayFolder": "Education variables"
          },
          {
            "name": "Field of education (1995) ",
            "dataType": "string",
            "sourceColumn": "Field of education (1995)",
            "sortByColumn": "jarjestys_opintoala1995",
            "displayFolder": "Education variables"
          },
          {
            "name": "Subfield of ed. (2002) ",
            "dataType": "string",
            "sourceColumn": "Subfield of ed. (2002)",
            "sortByColumn": "jarjestys_opintoala2002",
            "displayFolder": "Education variables"
          },
          {
            "name": "Aloit3",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Aloit3"
          },
          {
            "name": "Kansainvälinen opiskelija",
            "dataType": "string",
            "sourceColumn": "Kansainvälinen opiskelija",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Kansalaisuus (ennakko)",
            "dataType": "string",
            "sourceColumn": "Kansalaisuus (ennakko)",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Liikkuvuuden kesto",
            "dataType": "string",
            "sourceColumn": "Liikkuvuuden kesto",
            "sortByColumn": "jarjestys_liikkuvuuden_kesto",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Mobilitetens längd",
            "dataType": "string",
            "sourceColumn": "Mobilitetens längd",
            "sortByColumn": "jarjestys_liikkuvuuden_kesto",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Duration of mobility",
            "dataType": "string",
            "sourceColumn": "Duration of mobility",
            "sortByColumn": "jarjestys_liikkuvuuden_kesto",
            "displayFolder": "Education variables"
          },
          {
            "name": "jarjestys_liikkuvuuden_kesto",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarjestys_liikkuvuuden_kesto"
          },
          {
            "type": "calculated",
            "name": "apusarake_yliopistojen_rahoitusmalli",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": [
              " ",
              "IF([Koulutusaste, taso 2] = \"Alempi korkeakoulututkinto\", 1, IF([Koodit Koulutusnimike] in {\"772101\", \"772201\"}, 1, 0))"
            ]
          }
        ],
        "partitions": [
          {
            "name": "7",
            "source": {
              "type": "query",
              "query": [
                "SELECT [dbo].[v_f_tab_otv_korkeakoulut_yhteiset].* FROM [dbo].[v_f_tab_otv_korkeakoulut_yhteiset] ",
                "WHERE [Tilastovuosi] between 2000 and 2002"
              ],
              "dataSource": "SqlServer dwitestvipusql VipunenTK"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[v_f_tab_otv_korkeakoulut_yhteiset].* FROM [dbo].[v_f_tab_otv_korkeakoulut_yhteiset] \r",
                  "WHERE [Tilastovuosi] between 2000 and 2002</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "6",
            "mode": "import",
            "source": {
              "type": "query",
              "query": [
                "SELECT [dbo].[v_f_tab_otv_korkeakoulut_yhteiset].* FROM [dbo].[v_f_tab_otv_korkeakoulut_yhteiset] ",
                "WHERE [Tilastovuosi] between 2003 and 2005"
              ],
              "dataSource": "SqlServer dwitestvipusql VipunenTK"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[v_f_tab_otv_korkeakoulut_yhteiset].* FROM [dbo].[v_f_tab_otv_korkeakoulut_yhteiset] \r",
                  "WHERE [Tilastovuosi] between 2003 and 2005</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "5",
            "mode": "import",
            "source": {
              "type": "query",
              "query": [
                "SELECT [dbo].[v_f_tab_otv_korkeakoulut_yhteiset].* FROM [dbo].[v_f_tab_otv_korkeakoulut_yhteiset] ",
                "WHERE [Tilastovuosi] between 2006 and 2008"
              ],
              "dataSource": "SqlServer dwitestvipusql VipunenTK"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[v_f_tab_otv_korkeakoulut_yhteiset].* FROM [dbo].[v_f_tab_otv_korkeakoulut_yhteiset] \r",
                  "WHERE [Tilastovuosi] between 2006 and 2008</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "4",
            "mode": "import",
            "source": {
              "type": "query",
              "query": [
                "SELECT [dbo].[v_f_tab_otv_korkeakoulut_yhteiset].* FROM [dbo].[v_f_tab_otv_korkeakoulut_yhteiset] ",
                "WHERE [Tilastovuosi] between 2009 and 2011"
              ],
              "dataSource": "SqlServer dwitestvipusql VipunenTK"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[v_f_tab_otv_korkeakoulut_yhteiset].* FROM [dbo].[v_f_tab_otv_korkeakoulut_yhteiset] \r",
                  "WHERE [Tilastovuosi] between 2009 and 2011</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "3",
            "mode": "import",
            "source": {
              "type": "query",
              "query": [
                "SELECT [dbo].[v_f_tab_otv_korkeakoulut_yhteiset].* FROM [dbo].[v_f_tab_otv_korkeakoulut_yhteiset] ",
                "WHERE [Tilastovuosi] between 2012 and 2014"
              ],
              "dataSource": "SqlServer dwitestvipusql VipunenTK"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[v_f_tab_otv_korkeakoulut_yhteiset].* FROM [dbo].[v_f_tab_otv_korkeakoulut_yhteiset] \r",
                  "WHERE [Tilastovuosi] between 2012 and 2014</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "2",
            "mode": "import",
            "source": {
              "type": "query",
              "query": [
                "SELECT [dbo].[v_f_tab_otv_korkeakoulut_yhteiset].* FROM [dbo].[v_f_tab_otv_korkeakoulut_yhteiset] ",
                "WHERE [Tilastovuosi] between 2015 and 2017"
              ],
              "dataSource": "SqlServer dwitestvipusql VipunenTK"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[v_f_tab_otv_korkeakoulut_yhteiset].* FROM [dbo].[v_f_tab_otv_korkeakoulut_yhteiset] \r",
                  "WHERE [Tilastovuosi] between 2015 and 2017</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "1",
            "mode": "import",
            "source": {
              "type": "query",
              "query": [
                "SELECT [dbo].[v_f_tab_otv_korkeakoulut_yhteiset].* FROM [dbo].[v_f_tab_otv_korkeakoulut_yhteiset] ",
                "",
                "WHERE [Tilastovuosi] between 2018 and YEAR(getdate())-2"
              ],
              "dataSource": "SqlServer dwitestvipusql VipunenTK"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[v_f_tab_otv_korkeakoulut_yhteiset].* FROM [dbo].[v_f_tab_otv_korkeakoulut_yhteiset] \r",
                  "\r",
                  "WHERE [Tilastovuosi] between 2018 and YEAR(getdate())-2</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "0",
            "mode": "import",
            "source": {
              "type": "query",
              "query": [
                "SELECT [dbo].[v_f_tab_otv_korkeakoulut_yhteiset].* FROM [dbo].[v_f_tab_otv_korkeakoulut_yhteiset] ",
                "",
                "WHERE [Tilastovuosi] >= YEAR(getdate())-1"
              ],
              "dataSource": "SqlServer dwitestvipusql VipunenTK"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[v_f_tab_otv_korkeakoulut_yhteiset].* FROM [dbo].[v_f_tab_otv_korkeakoulut_yhteiset] \r",
                  "\r",
                  "WHERE [Tilastovuosi] >= YEAR(getdate())-1</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Opiskelijat",
            "expression": [
              "",
              "var summa = SUM([Opisk2])",
              "return IF(summa=0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "Uudet opiskelijat",
            "expression": [
              "",
              "var summa =CALCULATE(SUM([Aloit2]), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"91\"))",
              "return IF(summa=0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "Yli 55 op suorittaneet (kirjoihintulovuosi eri kuin tilastovuosi)",
            "expression": [
              "",
              "var summa = CALCULATE(SUM([lkm_op55]), FILTER('Muuttujat', [Kirjoihintulovuosi] <> [Tilastovuosi]), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"73\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"81\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"82\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"91\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"91\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"62\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"71\"))",
              "return IF(summa=0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Opintopisteet_opiskelijat"
          },
          {
            "name": "0 op suorittaneet (ml. poissaolevat, kirjoihintulovuosi eri kuin tilastovuosi)",
            "expression": [
              "",
              "var summa = CALCULATE(SUM([lkm_op0]), FILTER(Muuttujat, [Kirjoihintulovuosi] <> [Tilastovuosi]))",
              "return IF(summa=0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Opintopisteet_opiskelijat"
          },
          {
            "name": "1-14 op suorittaneet",
            "expression": [
              "",
              "var summa = SUM([lkm_op1_14])",
              "return IF(summa=0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Opintopisteet_opiskelijat"
          },
          {
            "name": "15-29 op suorittaneet",
            "expression": [
              "",
              "var summa = SUM([lkm_op15_29])",
              "return IF(summa=0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Opintopisteet_opiskelijat"
          },
          {
            "name": "30-44 op suorittaneet",
            "expression": [
              "",
              "var summa = SUM([lkm_op30_44])",
              "return IF(summa=0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Opintopisteet_opiskelijat"
          },
          {
            "name": "45-59 op suorittaneet",
            "expression": [
              "",
              "var summa = SUM([lkm_op45_59])",
              "return IF(summa=0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Opintopisteet_opiskelijat"
          },
          {
            "name": "60-74 op suorittaneet",
            "expression": [
              "",
              "var summa = SUM([lkm_op60_74])",
              "return IF(summa=0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Opintopisteet_opiskelijat"
          },
          {
            "name": "75-89 op suorittaneet",
            "expression": [
              "",
              "var summa = SUM([lkm_op75_89])",
              "return IF(summa=0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Opintopisteet_opiskelijat"
          },
          {
            "name": "90-104 op suorittaneet",
            "expression": [
              "",
              "var summa =SUM([lkm_op90_104])",
              "return IF(summa=0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Opintopisteet_opiskelijat"
          },
          {
            "name": "105-119 op suorittaneet",
            "expression": [
              "",
              "var summa = SUM([lkm_op105_119])",
              "return IF(summa=0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Opintopisteet_opiskelijat"
          },
          {
            "name": "Yli 120 op suorittaneet",
            "expression": [
              "",
              "var summa = SUM([lkm_op120_])",
              "return IF(summa=0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Opintopisteet_opiskelijat"
          },
          {
            "name": "Aloittaneet (kirjoihintulovuosi)",
            "expression": [
              "",
              "var summa = SUM([aloittaneet_kirjoihintulovuosi])",
              "return IF(summa=0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "Aloittaneet (korkeakoulusektori)",
            "expression": [
              "",
              "var summa = SUM([aloittaneet_korkeakoulusektori])",
              "return IF(summa=0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "Aloittaneet (korkeakoulusektori läsnäoleva)",
            "expression": [
              "",
              "var summa = SUM([aloittaneet_korkeakoulusektori_lasnaoleva])",
              "return IF(summa=0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "Aloittaneet (sektori)",
            "expression": [
              "",
              "var summa = SUM([aloittaneet_sektori])",
              "return IF(summa=0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "Aloittaneet (sektori läsnäoleva)",
            "expression": [
              "",
              "var summa = SUM([aloittaneet_sektori_lasnaoleva])",
              "return IF(summa=0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "Aloittaneet (korkeakoulu)",
            "expression": [
              "",
              "var summa = SUM([aloittaneet_korkeakoulu])",
              "return IF(summa=0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "Aloittaneet (korkeakoulu läsnäoleva)",
            "expression": [
              "",
              "var summa = SUM([aloittaneet_korkeakoulu_lasnaoleva])",
              "return IF(summa=0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "Aloittaneet (opintoala)",
            "expression": [
              "",
              "var summa = SUM([aloittaneet_opintoala])",
              "return IF(summa=0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "Aloittaneet (opintoala läsnäoleva)",
            "expression": [
              "",
              "var summa = SUM([aloittaneet_opintoala_lasnaoleva])",
              "return IF(summa=0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "Opiskelijat (läsnä)",
            "expression": [
              "",
              "var summa = SUM([opiskelijat_lasna])",
              "return IF(summa=0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "Opiskelijat FTE",
            "expression": [
              "",
              "var summa = SUM([opiskelijat_fte])",
              "return IF(summa=0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
              ""
            ],
            "formatString": "#,0.0"
          },
          {
            "name": "Tutkinnot",
            "expression": [
              "",
              "var summa = CALCULATE(SUM([Tutk2]), FILTER('Muuttujat', [Koodit Koulutustyyppi] <> \"3\"), FILTER('Muuttujat', [Koodit Koulutustyyppi] <> \"5\"))",
              "return IF(summa=0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "19-21 vuotiaiden keskimääräinen ikäluokka",
            "expression": [
              "",
              "var lkm = SUM([ika19_21_lkm])",
              "var vuosia = 3",
              "return IF(lkm = 0, BLANK(),",
              "\tIF(lkm < 5, CONCATENATE(FORMAT(1 / vuosia, \"0.0 – \"), FORMAT(4 / vuosia, \"0.0\")),",
              "\t     MROUND(lkm, 3) / vuosia))"
            ],
            "formatString": "#,0.0"
          },
          {
            "name": "20-24 vuotiaiden keskimääräinen ikäluokka",
            "expression": [
              "",
              "var lkm = SUM([ika20_24_lkm])",
              "var vuosia = 5",
              "return IF(lkm = 0, BLANK(),",
              "\tIF(lkm < 5, CONCATENATE(FORMAT(1 / vuosia, \"0.0 – \"), FORMAT(4 / vuosia, \"0.0\")),",
              "\t     MROUND(lkm, 3) / vuosia))"
            ],
            "formatString": "#,0.0"
          },
          {
            "name": "25-34 vuotiaiden keskimääräinen ikäluokka",
            "expression": [
              "",
              "var lkm = SUM([ika25_34_lkm])",
              "var vuosia = 10",
              "return IF(lkm = 0, BLANK(),",
              "\tIF(lkm < 5, CONCATENATE(FORMAT(1 / vuosia, \"0.0 – \"), FORMAT(4 / vuosia, \"0.0\")),",
              "\t     MROUND(lkm, 3) / vuosia))",
              ""
            ],
            "formatString": "#,0.0"
          },
          {
            "name": "25-64 vuotiaiden keskimääräinen ikäluokka",
            "expression": [
              "",
              "var lkm = SUM([ika25_64_lkm])",
              "var vuosia = 40",
              "return IF(lkm = 0, BLANK(),",
              "\tIF(lkm < 5, CONCATENATE(FORMAT(1 / vuosia, \"0.0 – \"), FORMAT(4 / vuosia, \"0.0\")),",
              "\t     MROUND(lkm, 3) / vuosia))",
              ""
            ],
            "formatString": "#,0.0"
          },
          {
            "name": "Aloittaneet",
            "expression": [
              "",
              "var summa = CALCULATE(SUM([Aloit2]), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"91\"))",
              "return IF(summa=0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "Alemman ja ylemmän kk-tutkinnon opiskelijat (kirjoihintulovuosi eri kuin tilastovuosi)",
            "expression": [
              "",
              "var summa = CALCULATE(SUM([Opisk2]), FILTER('Muuttujat', [Kirjoihintulovuosi] <> [Tilastovuosi]), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"73\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"81\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"82\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"91\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"91\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"62\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"71\"), FILTER('Muuttujat', [kirjoillaolosyys_koodi] <> \"2\"))",
              "return IF(summa=0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "Yli 55 op suorittaneiden osuus (kirjoihintulovuosi eri kuin tilastovuosi)",
            "expression": [
              "",
              "var lkm = [Yli 55 op suorittaneet (kirjoihintulovuosi eri kuin tilastovuosi)]",
              "var kaikki = [Alemman ja ylemmän kk-tutkinnon opiskelijat (kirjoihintulovuosi eri kuin tilastovuosi)]",
              "return IF(lkm = BLANK(), BLANK(),",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(lkm = \"1-4\", IF(kaikki > 8000, \"0.0 %\",",
              "CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "lkm / kaikki)))",
              ""
            ],
            "formatString": "#,0.0 %;-#,0.0 %;#,0.0 %",
            "displayFolder": "Opintopisteet_opiskelijat"
          },
          {
            "name": "Yli 55 op suorittaneet (amk, kirjoihintulovuosi eri kuin tilastovuosi)",
            "expression": [
              "",
              "var summa = CALCULATE(SUM([lkm_op55]), FILTER('Muuttujat', [Kirjoihintulovuosi] <> [Tilastovuosi]), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"73\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"81\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"82\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"91\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"63\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"72\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"71\"))",
              "return IF(summa=0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Opintopisteet_opiskelijat"
          },
          {
            "name": "Amk opiskelijat (kirjoihintulovuosi eri kuin tilastovuosi)",
            "expression": [
              "",
              "var summa =CALCULATE(SUM([Opisk2]), FILTER('Muuttujat', [Kirjoihintulovuosi] <> [Tilastovuosi]), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"73\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"81\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"82\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"91\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"63\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"72\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"71\"))",
              "return IF(summa=0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "Yli 55 op suorittaneiden osuus (amk, kirjoihintulovuosi eri kuin tilastovuosi)",
            "expression": [
              "",
              "var lkm = [Yli 55 op suorittaneet (amk, kirjoihintulovuosi eri kuin tilastovuosi)]",
              "var kaikki = [Amk opiskelijat (kirjoihintulovuosi eri kuin tilastovuosi)]",
              "return IF(lkm = BLANK(), BLANK(),",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(lkm = \"1-4\", IF(kaikki > 8000, \"0.0 %\",",
              "CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "lkm / kaikki)))",
              ""
            ],
            "formatString": "#,0.0 %;-#,0.0 %;#,0.0 %",
            "displayFolder": "Opintopisteet_opiskelijat"
          },
          {
            "name": "Alemman ja ylemmän korkeakoulututkinnon uudet opiskelijat",
            "expression": [
              "",
              "var summa = CALCULATE(SUM([Aloit2]), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"73\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"81\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"82\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"91\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"62\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"71\"))",
              "return IF(summa=0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "Ammattikorkeakoulujen nuorten koulutuksen uudet opiskelijat",
            "expression": [
              "",
              "var summa = CALCULATE(SUM([Aloit2]), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"73\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"81\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"82\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"91\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"63\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"71\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"72\"), FILTER('Muuttujat', [Koodit Koulutustyyppi] <> \"2\"))",
              "return IF(summa=0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "Ammattikorkeakoulujen aikuiskoulutuksen uudet opiskelijat",
            "expression": [
              "",
              "var summa = CALCULATE(SUM([Aloit2]), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"73\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"81\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"82\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"91\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"63\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"71\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"72\"), FILTER('Muuttujat', [Koodit Koulutustyyppi] <> \"1\"))",
              "return IF(summa=0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "Ylemmän ammattikorkeakoulututkinnon uudet opiskelijat",
            "expression": [
              "",
              "var summa = CALCULATE(SUM([Aloit2]), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"73\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"81\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"82\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"91\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"63\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"72\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"62\"))",
              "return IF(summa=0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "Alemman ja ylemmän korkeakoulututk. uudet opiskelijat / 19-21 vuotiaiden keskimääräinen ikäluokka",
            "expression": [
              "",
              "var uudet = [Alemman ja ylemmän korkeakoulututkinnon uudet opiskelijat] ",
              "var vuosia = 3",
              "var ka = [19-21 vuotiaiden keskimääräinen ikäluokka]",
              "return IF(OR(uudet = BLANK(), ka = BLANK()), BLANK(),",
              "IF(FIND(\"–\", ka, 1, 0) > 0, IF(uudet = \"1-4\", CONCATENATE(FORMAT(1 / (4 / vuosia), \"0.0 – \"), FORMAT(4 / (1 / vuosia), \"0.0\")),",
              "CONCATENATE(FORMAT(uudet / (4 / vuosia), \"0.0 – \"), FORMAT(uudet / (1 / vuosia), \"0.0\"))),",
              "IF(uudet = \"1-4\", CONCATENATE(FORMAT(1 / ka, \"0.0 – \"), FORMAT(4 / ka, \"0.0\")),",
              "uudet / ka)))"
            ],
            "formatString": "#,0.0"
          },
          {
            "name": "Ammattikorkeak. nuorten koulutuksen uudet opiskelijat / 19-21 vuotiaiden keskimääräinen ikäluokka",
            "expression": [
              "",
              "var uudet = [Ammattikorkeakoulujen nuorten koulutuksen uudet opiskelijat]",
              "var vuosia = 3",
              "var ka = [19-21 vuotiaiden keskimääräinen ikäluokka]",
              "return IF(OR(uudet = BLANK(), ka = BLANK()), BLANK(),",
              "IF(FIND(\"–\", ka, 1, 0) > 0, IF(uudet = \"1-4\", CONCATENATE(FORMAT(1 / (4 / vuosia), \"0.0 – \"), FORMAT(4 / (1 / vuosia), \"0.0\")),",
              "CONCATENATE(FORMAT(uudet / (4 / vuosia), \"0.0 – \"), FORMAT(uudet / (1 / vuosia), \"0.0\"))),",
              "IF(uudet = \"1-4\", CONCATENATE(FORMAT(1 / ka, \"0.0 – \"), FORMAT(4 / ka, \"0.0\")),",
              "uudet / ka)))"
            ],
            "formatString": "#,0.0"
          },
          {
            "name": "Ammattikorkeak. aikuiskoulutuksen uudet opiskelijat / 25-64 vuotiaiden keskimääräinen ikäluokka",
            "expression": [
              "",
              "var uudet = [Ammattikorkeakoulujen aikuiskoulutuksen uudet opiskelijat]",
              "var vuosia = 40",
              "var ka = [25-64 vuotiaiden keskimääräinen ikäluokka]",
              "return IF(OR(uudet = BLANK(), ka = BLANK()), BLANK(),",
              "IF(FIND(\"–\", ka, 1, 0) > 0, IF(uudet = \"1-4\", CONCATENATE(FORMAT(1 / (4 / vuosia), \"0.0 – \"), FORMAT(4 / (1 / vuosia), \"0.0\")),",
              "CONCATENATE(FORMAT(uudet / (4 / vuosia), \"0.0 – \"), FORMAT(uudet / (1 / vuosia), \"0.0\"))),",
              "IF(uudet = \"1-4\", CONCATENATE(FORMAT(1 / ka, \"0.0 – \"), FORMAT(4 / ka, \"0.0\")),",
              "uudet / ka)))"
            ],
            "formatString": "#,0.0"
          },
          {
            "name": "Ylemmän ammattikorkeakoulututkinnon uudet opiskelijat / 25-64 vuotiaiden keskimääräinen ikäluokka",
            "expression": [
              "",
              "var uudet = [Ylemmän ammattikorkeakoulututkinnon uudet opiskelijat]",
              "var vuosia = 40",
              "var ka = [25-64 vuotiaiden keskimääräinen ikäluokka]",
              "return IF(OR(uudet = BLANK(), ka = BLANK()), BLANK(),",
              "IF(FIND(\"–\", ka, 1, 0) > 0, IF(uudet = \"1-4\", CONCATENATE(FORMAT(1 / (4 / vuosia), \"0.0 – \"), FORMAT(4 / (1 / vuosia), \"0.0\")),",
              "CONCATENATE(FORMAT(uudet / (4 / vuosia), \"0.0 – \"), FORMAT(uudet / (1 / vuosia), \"0.0\"))),",
              "IF(uudet = \"1-4\", CONCATENATE(FORMAT(1 / ka, \"0.0 – \"), FORMAT(4 / ka, \"0.0\")),",
              "uudet / ka)))"
            ],
            "formatString": "#,0.0"
          },
          {
            "name": "Ulkomaalaiset opiskelijat",
            "expression": [
              "",
              "var summa = CALCULATE(SUM([Opisk2]), FILTER('Muuttujat', [Kansalaisuus] <> \"suomi\"),FILTER(Muuttujat,[Aineisto]=\"Lopullinen\"))",
              "return IF(summa=0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "Uudet ulkomaalaiset opiskelijat",
            "expression": [
              "",
              "var summa =CALCULATE(SUM([Opisk2]), FILTER('Muuttujat', [Kansalaisuus] <> \"suomi\"),FILTER(Muuttujat,[Aineisto]=\"Lopullinen\"), FILTER('Muuttujat', [Kirjoihintulovuosi] = [Tilastovuosi]), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"73\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"81\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"82\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"91\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"91\"))",
              "return IF(summa=0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "Ulkomaalaiset opiskelijat FTE",
            "expression": [
              "",
              "var summa = CALCULATE(SUM([opiskelijat_fte]), FILTER('Muuttujat', [Kansalaisuus] <> \"suomi\"),FILTER(Muuttujat,[Aineisto]=\"Lopullinen\"))",
              "return IF(summa=0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "Ulkomaalaisten opiskelijoiden suorittamat tutkinnot",
            "expression": [
              "",
              "var summa = CALCULATE(SUM([Tutk2]), FILTER('Muuttujat', [Kansalaisuus] <> \"suomi\"),FILTER(Muuttujat,[Aineisto]=\"Lopullinen\"))",
              "return IF(summa=0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "Studenter",
            "expression": "[Opiskelijat]",
            "formatString": "#,0"
          },
          {
            "name": "Nya studenter",
            "expression": "[Uudet opiskelijat]",
            "formatString": "#,0"
          },
          {
            "name": "Utländska studenter",
            "expression": "[Ulkomaalaiset opiskelijat]",
            "formatString": "#,0"
          },
          {
            "name": "Studenter som avlagt mer än 55 sp",
            "expression": "[Yli 55 op suorittaneet (kirjoihintulovuosi eri kuin tilastovuosi)]",
            "formatString": "#,0"
          },
          {
            "name": "Studenter i lägre och högre högskoleexamen",
            "expression": "[Alemman ja ylemmän kk-tutkinnon opiskelijat (kirjoihintulovuosi eri kuin tilastovuosi)]",
            "formatString": "#,0"
          },
          {
            "name": "Andel som avlagt mer än 55 sp",
            "expression": "[Yli 55 op suorittaneiden osuus (kirjoihintulovuosi eri kuin tilastovuosi)]",
            "formatString": "#,0.0 %;-#,0.0 %;#,0.0 %"
          },
          {
            "name": "Studenter som avlagt mer än 55 sp (yrkehögskola)",
            "expression": "[Yli 55 op suorittaneet (amk, kirjoihintulovuosi eri kuin tilastovuosi)]",
            "formatString": "#,0"
          },
          {
            "name": "Yrkehögskolestudenter",
            "expression": "[Amk opiskelijat (kirjoihintulovuosi eri kuin tilastovuosi)]",
            "formatString": "#,0"
          },
          {
            "name": "Andel som avlagt mer än 55 sp (yrkehögskola)",
            "expression": "[Yli 55 op suorittaneiden osuus (amk, kirjoihintulovuosi eri kuin tilastovuosi)]",
            "formatString": "#,0.0 %;-#,0.0 %;#,0.0 %"
          },
          {
            "name": "Nya utländska studenter",
            "expression": "[Uudet ulkomaalaiset opiskelijat]",
            "formatString": "#,0"
          },
          {
            "name": "0 sp",
            "expression": "[0 op suorittaneet (ml. poissaolevat, kirjoihintulovuosi eri kuin tilastovuosi)]",
            "formatString": "#,0",
            "displayFolder": "Studiepoöng_studerande"
          },
          {
            "name": "1-14 sp",
            "expression": "[1-14 op suorittaneet]",
            "formatString": "#,0",
            "displayFolder": "Studiepoöng_studerande"
          },
          {
            "name": "15-29 sp",
            "expression": "[15-29 op suorittaneet]",
            "formatString": "#,0",
            "displayFolder": "Studiepoöng_studerande"
          },
          {
            "name": "30-44 sp",
            "expression": "[30-44 op suorittaneet]",
            "formatString": "#,0",
            "displayFolder": "Studiepoöng_studerande"
          },
          {
            "name": "45-59 sp",
            "expression": "[45-59 op suorittaneet]",
            "formatString": "#,0",
            "displayFolder": "Studiepoöng_studerande"
          },
          {
            "name": "60-74 sp",
            "expression": "[60-74 op suorittaneet]",
            "formatString": "#,0",
            "displayFolder": "Studiepoöng_studerande"
          },
          {
            "name": "75-89 sp",
            "expression": "[75-89 op suorittaneet]",
            "formatString": "#,0",
            "displayFolder": "Studiepoöng_studerande"
          },
          {
            "name": "90-104 sp",
            "expression": "[90-104 op suorittaneet]",
            "formatString": "#,0",
            "displayFolder": "Studiepoöng_studerande"
          },
          {
            "name": "105-119 sp",
            "expression": "[105-119 op suorittaneet]",
            "formatString": "#,0",
            "displayFolder": "Studiepoöng_studerande"
          },
          {
            "name": "Över 120 sp",
            "expression": "[Yli 120 op suorittaneet]",
            "formatString": "#,0",
            "displayFolder": "Studiepoöng_studerande"
          },
          {
            "name": "Nybörjare inskrivningår",
            "expression": "[Aloittaneet (kirjoihintulovuosi)]",
            "formatString": "#,0"
          },
          {
            "name": "Nybörjare inskrivningår i högskolsektor",
            "expression": "[Aloittaneet (korkeakoulusektori)]",
            "formatString": "#,0"
          },
          {
            "name": "Nybörjare inskrivningår i högskolsektor närvarande",
            "expression": "[Aloittaneet (korkeakoulusektori läsnäoleva)]",
            "formatString": "#,0"
          },
          {
            "name": "Nybörjare inskrivningår sektor",
            "expression": "[Aloittaneet (sektori)]",
            "formatString": "#,0"
          },
          {
            "name": "Nybörjare inskrivningår sektor närvarande",
            "expression": "[Aloittaneet (sektori läsnäoleva)]",
            "formatString": "#,0"
          },
          {
            "name": "Nybörjare inskrivningår högskolen",
            "expression": "[Aloittaneet (korkeakoulu)]",
            "formatString": "#,0"
          },
          {
            "name": "Nybörjare inskrivningår högskolen närvarande",
            "expression": "[Aloittaneet (korkeakoulu läsnäoleva)]",
            "formatString": "#,0"
          },
          {
            "name": "Nybörjare inskrivningår studieområde",
            "expression": "[Aloittaneet (opintoala)]",
            "formatString": "#,0"
          },
          {
            "name": "Nybörjare inskrivningår studieområde närvarande",
            "expression": "[Aloittaneet (opintoala läsnäoleva)]",
            "formatString": "#,0"
          },
          {
            "name": "Studenter (närvarande)",
            "expression": "[Opiskelijat (läsnä)]",
            "formatString": "#,0"
          },
          {
            "name": "Studenter FTE",
            "expression": "[Opiskelijat FTE]",
            "formatString": "#,0.0"
          },
          {
            "name": "Utländska studenter FTE",
            "expression": "[Ulkomaalaiset opiskelijat FTE]",
            "formatString": "#,0"
          },
          {
            "name": "Examina",
            "expression": "[Tutkinnot]",
            "formatString": "#,0"
          },
          {
            "name": "Examina som avlagts av utländska studenter",
            "expression": "[Ulkomaalaisten opiskelijoiden suorittamat tutkinnot]",
            "formatString": "#,0"
          },
          {
            "name": "Students",
            "expression": "[Opiskelijat]",
            "formatString": "#,0"
          },
          {
            "name": "New students",
            "expression": "[Uudet opiskelijat]",
            "formatString": "#,0"
          },
          {
            "name": "Foreign students",
            "expression": "[Ulkomaalaiset opiskelijat]",
            "formatString": "#,0"
          },
          {
            "name": "Students who attained more than 55 credits",
            "expression": "[Yli 55 op suorittaneet (kirjoihintulovuosi eri kuin tilastovuosi)]",
            "formatString": "#,0"
          },
          {
            "name": "Bachelor's and Master's degree students",
            "expression": "[Alemman ja ylemmän kk-tutkinnon opiskelijat (kirjoihintulovuosi eri kuin tilastovuosi)]",
            "formatString": "#,0"
          },
          {
            "name": "Percentage of students who attained more than 55 credits",
            "expression": "[Yli 55 op suorittaneiden osuus (kirjoihintulovuosi eri kuin tilastovuosi)]",
            "formatString": "#,0.0 %;-#,0.0 %;#,0.0 %"
          },
          {
            "name": "Students who attained more than 55 credits (polytechnic)",
            "expression": "[Yli 55 op suorittaneet (amk, kirjoihintulovuosi eri kuin tilastovuosi)]",
            "formatString": "#,0"
          },
          {
            "name": "Polytechnic degree students",
            "expression": "[Amk opiskelijat (kirjoihintulovuosi eri kuin tilastovuosi)]",
            "formatString": "#,0"
          },
          {
            "name": "Percentage of students who attained more than 55 credits (polytechnic)",
            "expression": "[Yli 55 op suorittaneiden osuus (amk, kirjoihintulovuosi eri kuin tilastovuosi)]",
            "formatString": "#,0.0 %;-#,0.0 %;#,0.0 %"
          },
          {
            "name": "New foreign students",
            "expression": "[Uudet ulkomaalaiset opiskelijat]",
            "formatString": "#,0"
          },
          {
            "name": "0 credits",
            "expression": "[0 op suorittaneet (ml. poissaolevat, kirjoihintulovuosi eri kuin tilastovuosi)]",
            "formatString": "#,0",
            "displayFolder": "Credits_students"
          },
          {
            "name": "1-14 credits",
            "expression": "[1-14 op suorittaneet]",
            "formatString": "#,0",
            "displayFolder": "Credits_students"
          },
          {
            "name": "15-29 credits",
            "expression": "[15-29 op suorittaneet]",
            "formatString": "#,0",
            "displayFolder": "Credits_students"
          },
          {
            "name": "30-44 credits",
            "expression": "[30-44 op suorittaneet]",
            "formatString": "#,0",
            "displayFolder": "Credits_students"
          },
          {
            "name": "45-59 credits",
            "expression": "[45-59 op suorittaneet]",
            "formatString": "#,0",
            "displayFolder": "Credits_students"
          },
          {
            "name": "60-74 credits",
            "expression": "[60-74 op suorittaneet]",
            "formatString": "#,0",
            "displayFolder": "Credits_students"
          },
          {
            "name": "75-89 credits",
            "expression": "[75-89 op suorittaneet]",
            "formatString": "#,0",
            "displayFolder": "Credits_students"
          },
          {
            "name": "90-104 credits",
            "expression": "[90-104 op suorittaneet]",
            "formatString": "#,0",
            "displayFolder": "Credits_students"
          },
          {
            "name": "105-119 credits",
            "expression": "[105-119 op suorittaneet]",
            "formatString": "#,0",
            "displayFolder": "Credits_students"
          },
          {
            "name": "Over 120 credits",
            "expression": "[Yli 120 op suorittaneet]",
            "formatString": "#,0",
            "displayFolder": "Credits_students"
          },
          {
            "name": "New students enrollment year",
            "expression": "[Aloittaneet (kirjoihintulovuosi)]",
            "formatString": "#,0"
          },
          {
            "name": "New students enrollment year in higher education sector",
            "expression": "[Aloittaneet (korkeakoulusektori)]",
            "formatString": "#,0"
          },
          {
            "name": "New students enrollment year in higher education sector present",
            "expression": "[Aloittaneet (korkeakoulusektori läsnäoleva)]",
            "formatString": "#,0"
          },
          {
            "name": "New students enrollment year in education sector",
            "expression": "[Aloittaneet (sektori)]",
            "formatString": "#,0"
          },
          {
            "name": "New students enrollment year in education sector present",
            "expression": "[Aloittaneet (sektori läsnäoleva)]",
            "formatString": "#,0"
          },
          {
            "name": "New students enrollment year in the institution",
            "expression": "[Aloittaneet (korkeakoulu)]",
            "formatString": "#,0"
          },
          {
            "name": "New students enrollment year in the institution present",
            "expression": "[Aloittaneet (korkeakoulu läsnäoleva)]",
            "formatString": "#,0"
          },
          {
            "name": "New students enrollment year in subfield of education",
            "expression": "[Aloittaneet (opintoala)]",
            "formatString": "#,0"
          },
          {
            "name": "New students enrollment year in subfield of education present",
            "expression": "[Aloittaneet (opintoala läsnäoleva)]",
            "formatString": "#,0"
          },
          {
            "name": "Students (present)",
            "expression": "[Opiskelijat (läsnä)]",
            "formatString": "#,0"
          },
          {
            "name": "Students FTE",
            "expression": "[Opiskelijat FTE]",
            "formatString": "#,0.0"
          },
          {
            "name": "Foreign students FTE",
            "expression": "[Ulkomaalaiset opiskelijat FTE]",
            "formatString": "#,0"
          },
          {
            "name": "Degrees",
            "expression": "[Tutkinnot]",
            "formatString": "#,0"
          },
          {
            "name": "Degrees attained by foreign students",
            "expression": "[Ulkomaalaisten opiskelijoiden suorittamat tutkinnot]",
            "formatString": "#,0"
          },
          {
            "name": "Aloittaneet (TK määritelmä)",
            "expression": [
              "",
              "var summa = CALCULATE(SUM([Opisk2]), FILTER('Muuttujat', [Kirjoihintulovuosi (TK määritelmä)] = [Tilastovuosi]),FILTER('Muuttujat', [Kirjoihintulovuosi] = [Tilastovuosi]),FILTER('Muuttujat', [Koodit Koulutusaste taso 2] = \"62\" || [Koodit Koulutusaste taso 2]=\"71\"))+CALCULATE(SUM([aloittaneet_kirjoihintulovuosi]), FILTER('Muuttujat', OR([lahde_koodi] = \"41\", [lahde_koodi] = \"42\")),FILTER(Muuttujat,[Koodit Koulutusaste taso 2]<>\"91\"),FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"63\"),FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"72\"))+CALCULATE(SUM([Opisk2]), FILTER('Muuttujat', [Tutkinto-oikeusvuosi] = [Tilastovuosi]),FILTER(Muuttujat,[Koodit Koulutusaste taso 2]=\"63\" || [Koodit Koulutusaste taso 2]=\"72\"))",
              "return IF(summa=0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "Nybörjare (Statistikcentralens definition)",
            "expression": "[Aloittaneet (TK määritelmä)]",
            "formatString": "#,0"
          },
          {
            "name": "New students (Statistic Finland's definition)",
            "expression": "[Aloittaneet (TK määritelmä)]",
            "formatString": "#,0"
          },
          {
            "name": "Opiskelijat_s",
            "expression": "IF([kytkin] = 0, BLANK(), SUM([Opisk2]))",
            "formatString": "#,0"
          },
          {
            "name": "Uudet opiskelijat_s",
            "expression": "IF([kytkin] = 0, BLANK(), CALCULATE(SUM([Aloit2]), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"91\")))",
            "formatString": "#,0"
          },
          {
            "name": "Yli 55 op suorittaneet (kirjoihintulovuosi eri kuin tilastovuosi)_s",
            "expression": "IF([kytkin] = 0, BLANK(), CALCULATE(SUM([lkm_op55]), FILTER('Muuttujat', [Kirjoihintulovuosi] <> [Tilastovuosi]), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"73\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"81\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"82\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"91\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"91\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"62\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"71\")))",
            "formatString": "#,0",
            "displayFolder": "Opintopisteet_opiskelijat"
          },
          {
            "name": "Aloittaneet_s",
            "expression": "IF([kytkin] = 0, BLANK(), CALCULATE(SUM([Aloit2]), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"91\")))",
            "formatString": "#,0"
          },
          {
            "name": "Alemman ja ylemmän kk-tutkinnon opiskelijat (kirjoihintulovuosi eri kuin tilastovuosi)_s",
            "expression": "IF([kytkin] = 0, BLANK(), CALCULATE(SUM([Opisk2]), FILTER('Muuttujat', [Kirjoihintulovuosi] <> [Tilastovuosi]), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"73\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"81\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"82\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"91\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"91\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"62\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"71\"), FILTER('Muuttujat', [kirjoillaolosyys_koodi] <> \"2\")))",
            "formatString": "#,0"
          },
          {
            "name": "Yli 55 op suorittaneiden osuus (kirjoihintulovuosi eri kuin tilastovuosi)_s",
            "expression": "IF([kytkin] = 0, BLANK(), [Yli 55 op suorittaneet (kirjoihintulovuosi eri kuin tilastovuosi)_s]/[Alemman ja ylemmän kk-tutkinnon opiskelijat (kirjoihintulovuosi eri kuin tilastovuosi)_s])",
            "formatString": "#,0.0 %;-#,0.0 %;#,0.0 %",
            "displayFolder": "Opintopisteet_opiskelijat"
          },
          {
            "name": "Yli 55 op suorittaneet (amk, kirjoihintulovuosi eri kuin tilastovuosi)_s",
            "expression": "IF([kytkin] = 0, BLANK(), CALCULATE(SUM([lkm_op55]), FILTER('Muuttujat', [Kirjoihintulovuosi] <> [Tilastovuosi]), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"73\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"81\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"82\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"91\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"63\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"72\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"71\")))",
            "formatString": "#,0",
            "displayFolder": "Opintopisteet_opiskelijat"
          },
          {
            "name": "Amk opiskelijat (kirjoihintulovuosi eri kuin tilastovuosi)_s",
            "expression": "IF([kytkin] = 0, BLANK(), CALCULATE(SUM([Opisk2]), FILTER('Muuttujat', [Kirjoihintulovuosi] <> [Tilastovuosi]), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"73\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"81\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"82\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"91\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"63\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"72\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"71\")))",
            "formatString": "#,0"
          },
          {
            "name": "Yli 55 op suorittaneiden osuus (amk, kirjoihintulovuosi eri kuin tilastovuosi)_s",
            "expression": "IF([kytkin] = 0, BLANK(), [Yli 55 op suorittaneet (amk, kirjoihintulovuosi eri kuin tilastovuosi)_s]/[Amk opiskelijat (kirjoihintulovuosi eri kuin tilastovuosi)_s])",
            "formatString": "#,0.0 %;-#,0.0 %;#,0.0 %",
            "displayFolder": "Opintopisteet_opiskelijat"
          },
          {
            "name": "Uudet ulkomaalaiset opiskelijat_s",
            "expression": "IF([kytkin] = 0, BLANK(), CALCULATE(SUM([Opisk2]), FILTER('Muuttujat', [Kansalaisuus] <> \"suomi\"),FILTER(Muuttujat,[Aineisto]=\"Lopullinen\"), FILTER('Muuttujat', [Kirjoihintulovuosi] = [Tilastovuosi]), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"73\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"81\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"82\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"91\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"91\")))",
            "formatString": "#,0"
          },
          {
            "name": "Ulkomaalaiset opiskelijat_s",
            "expression": "IF([kytkin] = 0, BLANK(), CALCULATE(SUM([Opisk2]), FILTER('Muuttujat', [Kansalaisuus] <> \"suomi\"),FILTER(Muuttujat,[Aineisto]=\"Lopullinen\")))",
            "formatString": "#,0"
          },
          {
            "name": "0 op suorittaneet (ml. poissaolevat, kirjoihintulovuosi eri kuin tilastovuosi)_s",
            "expression": [
              "IF([kytkin] = 0, BLANK(), CALCULATE(SUM([lkm_op0]), FILTER(Muuttujat, [Kirjoihintulovuosi] <> [Tilastovuosi])))",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Opintopisteet_opiskelijat"
          },
          {
            "name": "1-14 op suorittaneet_s",
            "expression": "IF([kytkin] = 0, BLANK(), SUM([lkm_op1_14]))",
            "formatString": "#,0",
            "displayFolder": "Opintopisteet_opiskelijat"
          },
          {
            "name": "15-29 op suorittaneet_s",
            "expression": "IF([kytkin] = 0, BLANK(), SUM([lkm_op15_29]))",
            "formatString": "#,0",
            "displayFolder": "Opintopisteet_opiskelijat"
          },
          {
            "name": "30-44 op suorittaneet_s",
            "expression": "IF([kytkin] = 0, BLANK(), SUM([lkm_op30_44]))",
            "formatString": "#,0",
            "displayFolder": "Opintopisteet_opiskelijat"
          },
          {
            "name": "45-59 op suorittaneet_s",
            "expression": "IF([kytkin] = 0, BLANK(), SUM([lkm_op45_59]))",
            "formatString": "#,0",
            "displayFolder": "Opintopisteet_opiskelijat"
          },
          {
            "name": "60-74 op suorittaneet_s",
            "expression": "IF([kytkin] = 0, BLANK(), SUM([lkm_op60_74]))",
            "formatString": "#,0",
            "displayFolder": "Opintopisteet_opiskelijat"
          },
          {
            "name": "75-89 op suorittaneet_s",
            "expression": "IF([kytkin] = 0, BLANK(), SUM([lkm_op75_89]))",
            "formatString": "#,0",
            "displayFolder": "Opintopisteet_opiskelijat"
          },
          {
            "name": "90-104 op suorittaneet_s",
            "expression": "IF([kytkin] = 0, BLANK(), SUM([lkm_op90_104]))",
            "formatString": "#,0",
            "displayFolder": "Opintopisteet_opiskelijat"
          },
          {
            "name": "105-119 op suorittaneet_s",
            "expression": "IF([kytkin] = 0, BLANK(), SUM([lkm_op105_119]))",
            "formatString": "#,0",
            "displayFolder": "Opintopisteet_opiskelijat"
          },
          {
            "name": "Yli 120 op suorittaneet_s",
            "expression": "IF([kytkin] = 0, BLANK(), SUM([lkm_op120_]))",
            "formatString": "#,0",
            "displayFolder": "Opintopisteet_opiskelijat"
          },
          {
            "name": "Aloittaneet (kirjoihintulovuosi)_s",
            "expression": "IF([kytkin] = 0, BLANK(), SUM([aloittaneet_kirjoihintulovuosi]))",
            "formatString": "#,0"
          },
          {
            "name": "Aloittaneet (korkeakoulusektori)_s",
            "expression": "IF([kytkin] = 0, BLANK(), SUM([aloittaneet_korkeakoulusektori]))",
            "formatString": "#,0"
          },
          {
            "name": "Aloittaneet (korkeakoulusektori läsnäoleva)_s",
            "expression": "IF([kytkin] = 0, BLANK(), SUM([aloittaneet_korkeakoulusektori_lasnaoleva]))",
            "formatString": "#,0"
          },
          {
            "name": "Aloittaneet (sektori)_s",
            "expression": "IF([kytkin] = 0, BLANK(), SUM([aloittaneet_sektori]))",
            "formatString": "#,0"
          },
          {
            "name": "Aloittaneet (sektori läsnäoleva)_s",
            "expression": "IF([kytkin] = 0, BLANK(), SUM([aloittaneet_sektori_lasnaoleva]))",
            "formatString": "#,0"
          },
          {
            "name": "Aloittaneet (korkeakoulu)_s",
            "expression": "IF([kytkin] = 0, BLANK(), SUM([aloittaneet_korkeakoulu]))",
            "formatString": "#,0"
          },
          {
            "name": "Aloittaneet (korkeakoulu läsnäoleva)_s",
            "expression": "IF([kytkin] = 0, BLANK(), SUM([aloittaneet_korkeakoulu_lasnaoleva]))",
            "formatString": "#,0"
          },
          {
            "name": "Aloittaneet (opintoala)_s",
            "expression": "IF([kytkin] = 0, BLANK(), SUM([aloittaneet_opintoala]))",
            "formatString": "#,0"
          },
          {
            "name": "Aloittaneet (TK määritelmä)_s",
            "expression": "IF([kytkin] = 0, BLANK(), CALCULATE(SUM([Opisk2]), FILTER('Muuttujat', [Kirjoihintulovuosi (TK määritelmä)] = [Tilastovuosi]),FILTER('Muuttujat', [Kirjoihintulovuosi] = [Tilastovuosi]),FILTER('Muuttujat', [Koodit Koulutusaste taso 2] = \"62\" || [Koodit Koulutusaste taso 2]=\"71\"))+CALCULATE(SUM([aloittaneet_kirjoihintulovuosi]), FILTER('Muuttujat', OR([lahde_koodi] = \"41\", [lahde_koodi] = \"42\")),FILTER(Muuttujat,[Koodit Koulutusaste taso 2]<>\"91\"),FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"63\"),FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"72\"))+CALCULATE(SUM([Opisk2]), FILTER('Muuttujat', [Tutkinto-oikeusvuosi] = [Tilastovuosi]),FILTER(Muuttujat,[Koodit Koulutusaste taso 2]=\"63\" || [Koodit Koulutusaste taso 2]=\"72\")))",
            "formatString": "#,0"
          },
          {
            "name": "Aloittaneet (opintoala läsnäoleva)_s",
            "expression": "IF([kytkin] = 0, BLANK(), SUM([aloittaneet_opintoala_lasnaoleva]))",
            "formatString": "#,0"
          },
          {
            "name": "Opiskelijat (läsnä)_s",
            "expression": "IF([kytkin] = 0, BLANK(), SUM([opiskelijat_lasna]))",
            "formatString": "#,0"
          },
          {
            "name": "Ulkomaalaiset opiskelijat FTE_s",
            "expression": "IF([kytkin] = 0, BLANK(), CALCULATE(SUM([opiskelijat_fte]), FILTER('Muuttujat', [Kansalaisuus] <> \"suomi\"),FILTER(Muuttujat,[Aineisto]=\"Lopullinen\")))",
            "formatString": "#,0"
          },
          {
            "name": "Opiskelijat FTE_s",
            "expression": "IF([kytkin] = 0, BLANK(), SUM([opiskelijat_fte]))",
            "formatString": "#,0.0"
          },
          {
            "name": "Tutkinnot_s",
            "expression": "IF([kytkin] = 0, BLANK(), CALCULATE(SUM([Tutk2]), FILTER('Muuttujat', [Koodit Koulutustyyppi] <> \"3\"), FILTER('Muuttujat', [Koodit Koulutustyyppi] <> \"5\")))",
            "formatString": "#,0"
          },
          {
            "name": "Ulkomaalaisten opiskelijoiden suorittamat tutkinnot_s",
            "expression": "IF([kytkin] = 0, BLANK(), CALCULATE(SUM([Tutk2]), FILTER('Muuttujat', [Kansalaisuus] <> \"suomi\"),FILTER(Muuttujat,[Aineisto]=\"Lopullinen\")))",
            "formatString": "#,0"
          },
          {
            "name": "19-21 vuotiaiden keskimääräinen ikäluokka_s",
            "expression": "IF([kytkin] = 0, BLANK(), SUM([ika19_21_lkm])/3)",
            "formatString": "#,0.0"
          },
          {
            "name": "20-24 vuotiaiden keskimääräinen ikäluokka_s",
            "expression": "IF([kytkin] = 0, BLANK(), SUM([ika20_24_lkm])/5)",
            "formatString": "#,0.0"
          },
          {
            "name": "25-34 vuotiaiden keskimääräinen ikäluokka_s",
            "expression": "IF([kytkin] = 0, BLANK(), SUM([ika25_34_lkm])/10)",
            "formatString": "#,0.0"
          },
          {
            "name": "25-64 vuotiaiden keskimääräinen ikäluokka_s",
            "expression": "IF([kytkin] = 0, BLANK(), SUM([ika25_64_lkm])/40)",
            "formatString": "#,0.0"
          },
          {
            "name": "Alemman ja ylemmän korkeakoulututkinnon uudet opiskelijat_s",
            "expression": "IF([kytkin] = 0, BLANK(), CALCULATE(SUM([Aloit2]), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"73\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"81\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"82\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"91\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"62\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"71\")))",
            "formatString": "#,0"
          },
          {
            "name": "Ammattikorkeakoulujen nuorten koulutuksen uudet opiskelijat_s",
            "expression": "IF([kytkin] = 0, BLANK(), CALCULATE(SUM([Aloit2]), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"73\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"81\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"82\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"91\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"63\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"71\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"72\"), FILTER('Muuttujat', [Koodit Koulutustyyppi] <> \"2\")))",
            "formatString": "#,0"
          },
          {
            "name": "Ammattikorkeakoulujen aikuiskoulutuksen uudet opiskelijat_s",
            "expression": "IF([kytkin] = 0, BLANK(), CALCULATE(SUM([Aloit2]), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"73\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"81\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"82\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"91\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"63\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"71\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"72\"), FILTER('Muuttujat', [Koodit Koulutustyyppi] <> \"1\")))",
            "formatString": "#,0"
          },
          {
            "name": "Ylemmän ammattikorkeakoulututkinnon uudet opiskelijat_s",
            "expression": "IF([kytkin] = 0, BLANK(), CALCULATE(SUM([Aloit2]), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"73\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"81\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"82\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"91\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"63\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"72\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"62\")))",
            "formatString": "#,0"
          },
          {
            "name": "Alemman ja ylemmän korkeakoulututk. uudet opiskelijat / 19-21 vuotiaiden keskimääräinen ikäluokka_s",
            "expression": "IF([kytkin] = 0, BLANK(), [Alemman ja ylemmän kk-tutkinnon opiskelijat (kirjoihintulovuosi eri kuin tilastovuosi)_s]/[19-21 vuotiaiden keskimääräinen ikäluokka_s])",
            "formatString": "#,0.0"
          },
          {
            "name": "Ammattikorkeak. nuorten koulutuksen uudet opiskelijat / 19-21 vuotiaiden keskimääräinen ikäluokka_s",
            "expression": "IF([kytkin] = 0, BLANK(), [Ammattikorkeakoulujen nuorten koulutuksen uudet opiskelijat_s]/[19-21 vuotiaiden keskimääräinen ikäluokka_s])",
            "formatString": "#,0.0"
          },
          {
            "name": "Ammattikorkeak. aikuiskoulutuksen uudet opiskelijat / 25-64 vuotiaiden keskimääräinen ikäluokka_s",
            "expression": "IF([kytkin] = 0, BLANK(), [Ammattikorkeakoulujen aikuiskoulutuksen uudet opiskelijat_s]/[25-64 vuotiaiden keskimääräinen ikäluokka_s])",
            "formatString": "#,0.0"
          },
          {
            "name": "Ylemmän ammattikorkeakoulututkinnon uudet opiskelijat / 25-64 vuotiaiden keskimääräinen ikäluokka_s",
            "expression": "IF([kytkin] = 0, BLANK(), [Ylemmän ammattikorkeakoulututkinnon uudet opiskelijat_s]/[25-64 vuotiaiden keskimääräinen ikäluokka_s])",
            "formatString": "#,0.0"
          },
          {
            "name": "kytkin",
            "expression": "IF(LEFT(USERNAME(), 4) = \"DWI\\\", 1, 0)",
            "formatString": "0",
            "isHidden": true
          },
          {
            "name": "Opintopisteiden kertymä_s",
            "expression": " IF([kytkin] = 0, BLANK(), CALCULATE(SUM(Muuttujat[op_kertyma_edel_lkv_loppu]), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"73\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"81\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"82\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"91\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"91\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"61\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"71\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"51\")))"
          },
          {
            "name": "Opintopisteiden kertymä",
            "expression": [
              " ",
              "IF(sum(Muuttujat[Opisk2]) < 5, BLANK(), ",
              "CALCULATE(SUM(Muuttujat[op_kertyma_edel_lkv_loppu])",
              ", FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"73\")",
              ", FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"81\")",
              ", FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"82\")",
              ", FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"91\")",
              ", FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"61\")",
              ", FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"71\")",
              ", FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"51\")))"
            ]
          },
          {
            "name": "Uudet opiskelijat lkm_s",
            "expression": [
              " ",
              "--suojaamattomiin raportteihin, saa suodattua vain muuttujilla jotka api-taulussa opiskelijat_ja_tutkinnot sekä ilman sukupuolta myös kirjoihintulovuodella",
              "var ehto = ISFILTERED(Muuttujat[Sukupuoli]) && ISFILTERED(Muuttujat[Kirjoihintulovuosi])",
              "var lkm =  CALCULATE(SUM([Aloit3]) --huom. ei Aloit2, josta rajattu näkymässä 8-aste\t\t",
              "\t, ALLEXCEPT(Muuttujat",
              "\t\t, Muuttujat[Tilastovuosi]",
              "\t\t, Muuttujat[Aineisto]",
              "\t\t, Muuttujat[Koulutussektori]",
              "\t\t, Muuttujat[Oppilaitos], Muuttujat[Koodit Oppilaitos]",
              "\t\t, Muuttujat[Oppilaitos (tilastovuosi)]",
              "\t\t, Muuttujat[Koulutusnimike], Muuttujat[Koodit Koulutusnimike]",
              "\t\t, Muuttujat[Sukupuoli]",
              "\t\t, Muuttujat[Kirjoihintulovuosi]",
              "\t\t, Muuttujat[Koulutusaste, taso 1], Muuttujat[Koodit Koulutusaste taso 1]",
              "\t\t, Muuttujat[Koulutusaste, taso 2], Muuttujat[Koodit Koulutusaste taso 2]",
              "\t\t, Muuttujat[Koulutusala, taso 1], Muuttujat[Koodit Koulutusala taso 1]",
              "\t\t, Muuttujat[Koulutusala, taso 2], Muuttujat[Koodit Koulutusala taso 2]",
              "\t\t, Muuttujat[Koulutusala, taso 3], Muuttujat[Koodit Koulutusala taso 3]",
              "\t\t, Muuttujat[OKM ohjauksen ala korkeak.], Muuttujat[Koodit OKM ohjauksen ala korkeak]",
              "\t\t, Muuttujat[Rahoitusmallialat amk 2017-2020], Muuttujat[Rahoitusmallialat amk 2021-2024]",
              "\t\t, Muuttujat[Rahoitusmallialat yo 2017-2020], Muuttujat[Rahoitusmallialat yo 2021-2024])",
              "\t--poistetaan lääkärit ja erikoistumiset (koultyp <> 1, 2, 6)",
              "\t, FILTER(Muuttujat, [Koodit Koulutusaste taso 2] <> \"73\" && [Koodit Koulutusaste taso 2] <> \"91\")",
              "\t, FILTER(Muuttujat, [Tilastovuosi] <> \"2000\" && [Tilastovuosi] <> \"2001\" && [Tilastovuosi] <> \"2002\"  && [Tilastovuosi] <> \"2003\" && [Tilastovuosi] <> \"2004\" && [Tilastovuosi] <> \"2005\" && [Tilastovuosi] <> \"2006\" && [Tilastovuosi] <> \"2007\" && [Tilastovuosi] <> \"2008\" && [Tilastovuosi] <> \"2009\"))",
              "\t",
              "return IF(ehto || lkm = 0, BLANK(), lkm)"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Opiskelijat lkm_s",
            "expression": [
              " ",
              "--suojaamattomiin raportteihin, saa suodattua vain muuttujilla jotka api-taulussa opiskelijat_ja_tutkinnot sekä ilman sukupuolta myös kirjoihintulovuodella",
              "var ehto = ISFILTERED(Muuttujat[Sukupuoli]) && ISFILTERED(Muuttujat[Kirjoihintulovuosi])",
              "var lkm =  CALCULATE(SUM([Opisk2])",
              "\t, ALLEXCEPT(Muuttujat",
              "\t\t, Muuttujat[Tilastovuosi]",
              "\t\t, Muuttujat[Aineisto]",
              "\t\t, Muuttujat[Koulutussektori]",
              "\t\t, Muuttujat[Oppilaitos], Muuttujat[Koodit Oppilaitos]",
              "\t\t, Muuttujat[Oppilaitos (tilastovuosi)]",
              "\t\t, Muuttujat[Koulutusnimike], Muuttujat[Koodit Koulutusnimike]",
              "\t\t, Muuttujat[Sukupuoli]",
              "\t\t, Muuttujat[Kirjoihintulovuosi]",
              "\t\t, Muuttujat[Koulutusaste, taso 1], Muuttujat[Koodit Koulutusaste taso 1]",
              "\t\t, Muuttujat[Koulutusaste, taso 2], Muuttujat[Koodit Koulutusaste taso 2]",
              "\t\t, Muuttujat[Koulutusala, taso 1], Muuttujat[Koodit Koulutusala taso 1]",
              "\t\t, Muuttujat[Koulutusala, taso 2], Muuttujat[Koodit Koulutusala taso 2]",
              "\t\t, Muuttujat[Koulutusala, taso 3], Muuttujat[Koodit Koulutusala taso 3]",
              "\t\t, Muuttujat[OKM ohjauksen ala korkeak.], Muuttujat[Koodit OKM ohjauksen ala korkeak]",
              "\t\t, Muuttujat[Rahoitusmallialat amk 2017-2020], Muuttujat[Rahoitusmallialat amk 2021-2024]",
              "\t\t, Muuttujat[Rahoitusmallialat yo 2017-2020], Muuttujat[Rahoitusmallialat yo 2021-2024])",
              "\t--poistetaan lääkärit ja erikoistumiset (koultyp <> 1, 2, 6)",
              "\t, FILTER(Muuttujat, [Koodit Koulutusaste taso 2] <> \"73\" && [Koodit Koulutusaste taso 2] <> \"91\")",
              "\t, FILTER(Muuttujat, [Tilastovuosi] <> \"2000\" && [Tilastovuosi] <> \"2001\" && [Tilastovuosi] <> \"2002\"  && [Tilastovuosi] <> \"2003\" && [Tilastovuosi] <> \"2004\" && [Tilastovuosi] <> \"2005\" && [Tilastovuosi] <> \"2006\" && [Tilastovuosi] <> \"2007\" && [Tilastovuosi] <> \"2008\" && [Tilastovuosi] <> \"2009\"))",
              "",
              "return IF(ehto || lkm = 0, BLANK(), lkm)"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Tutkinnot lkm_s",
            "expression": [
              " ",
              "--suojaamattomiin raportteihin, saa suodattua vain muuttujilla jotka api-taulussa opiskelijat_ja_tutkinnot sekä ilman sukupuolta myös kirjoihintulovuodella",
              "var ehto = ISFILTERED(Muuttujat[Sukupuoli]) && ISFILTERED(Muuttujat[Kirjoihintulovuosi])",
              "var lkm =  CALCULATE(SUM([Tutk2])",
              "\t, ALLEXCEPT(Muuttujat",
              "\t\t, Muuttujat[Tilastovuosi]",
              "\t\t, Muuttujat[Aineisto]",
              "\t\t, Muuttujat[Koulutussektori]",
              "\t\t, Muuttujat[Oppilaitos], Muuttujat[Koodit Oppilaitos]",
              "\t\t, Muuttujat[Oppilaitos (tilastovuosi)]",
              "\t\t, Muuttujat[Koulutusnimike], Muuttujat[Koodit Koulutusnimike]",
              "\t\t, Muuttujat[Sukupuoli]",
              "\t\t, Muuttujat[Kirjoihintulovuosi]",
              "\t\t, Muuttujat[Koulutusaste, taso 1], Muuttujat[Koodit Koulutusaste taso 1]",
              "\t\t, Muuttujat[Koulutusaste, taso 2], Muuttujat[Koodit Koulutusaste taso 2]",
              "\t\t, Muuttujat[Koulutusala, taso 1], Muuttujat[Koodit Koulutusala taso 1]",
              "\t\t, Muuttujat[Koulutusala, taso 2], Muuttujat[Koodit Koulutusala taso 2]",
              "\t\t, Muuttujat[Koulutusala, taso 3], Muuttujat[Koodit Koulutusala taso 3]",
              "\t\t, Muuttujat[OKM ohjauksen ala korkeak.], Muuttujat[Koodit OKM ohjauksen ala korkeak]",
              "\t\t, Muuttujat[Rahoitusmallialat amk 2017-2020], Muuttujat[Rahoitusmallialat amk 2021-2024]",
              "\t\t, Muuttujat[Rahoitusmallialat yo 2017-2020], Muuttujat[Rahoitusmallialat yo 2021-2024])",
              "\t--poistetaan lääkärit ja erikoistumiset (koultyp <> 1, 2, 6)",
              "\t, FILTER(Muuttujat, [Koodit Koulutusaste taso 2] <> \"73\" && [Koodit Koulutusaste taso 2] <> \"91\")",
              "\t, FILTER(Muuttujat, [Tilastovuosi] <> \"2000\" && [Tilastovuosi] <> \"2001\" && [Tilastovuosi] <> \"2002\"  && [Tilastovuosi] <> \"2003\" && [Tilastovuosi] <> \"2004\" && [Tilastovuosi] <> \"2005\" && [Tilastovuosi] <> \"2006\" && [Tilastovuosi] <> \"2007\" && [Tilastovuosi] <> \"2008\" && [Tilastovuosi] <> \"2009\"))",
              "\t",
              "return IF(ehto || lkm = 0, BLANK(), lkm)"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Opiskelijat FTE lkm_s",
            "expression": [
              " ",
              "--suojaamattomiin raportteihin, saa suodattua vain muuttujilla jotka api-taulussa opiskelijat_ja_tutkinnot sekä ilman sukupuolta myös kirjoihintulovuodella",
              "var ehto = ISFILTERED(Muuttujat[Sukupuoli]) && ISFILTERED(Muuttujat[Kirjoihintulovuosi])",
              "var lkm =  CALCULATE(SUM([opiskelijat_fte])",
              "\t, ALLEXCEPT(Muuttujat",
              "\t\t, Muuttujat[Tilastovuosi]",
              "\t\t, Muuttujat[Aineisto]",
              "\t\t, Muuttujat[Koulutussektori]",
              "\t\t, Muuttujat[Oppilaitos], Muuttujat[Koodit Oppilaitos]",
              "\t\t, Muuttujat[Oppilaitos (tilastovuosi)]",
              "\t\t, Muuttujat[Koulutusnimike], Muuttujat[Koodit Koulutusnimike]",
              "\t\t, Muuttujat[Sukupuoli]",
              "\t\t, Muuttujat[Kirjoihintulovuosi]",
              "\t\t, Muuttujat[Koulutusaste, taso 1], Muuttujat[Koodit Koulutusaste taso 1]",
              "\t\t, Muuttujat[Koulutusaste, taso 2], Muuttujat[Koodit Koulutusaste taso 2]",
              "\t\t, Muuttujat[Koulutusala, taso 1], Muuttujat[Koodit Koulutusala taso 1]",
              "\t\t, Muuttujat[Koulutusala, taso 2], Muuttujat[Koodit Koulutusala taso 2]",
              "\t\t, Muuttujat[Koulutusala, taso 3], Muuttujat[Koodit Koulutusala taso 3]",
              "\t\t, Muuttujat[OKM ohjauksen ala korkeak.], Muuttujat[Koodit OKM ohjauksen ala korkeak]",
              "\t\t, Muuttujat[Rahoitusmallialat amk 2017-2020], Muuttujat[Rahoitusmallialat amk 2021-2024]",
              "\t\t, Muuttujat[Rahoitusmallialat yo 2017-2020], Muuttujat[Rahoitusmallialat yo 2021-2024])",
              "\t--poistetaan lääkärit ja erikoistumiset (koultyp <> 1, 2, 6)",
              "\t, FILTER(Muuttujat, [Koodit Koulutusaste taso 2] <> \"73\" && [Koodit Koulutusaste taso 2] <> \"91\")",
              "\t, FILTER(Muuttujat, [Tilastovuosi] <> \"2000\" && [Tilastovuosi] <> \"2001\" && [Tilastovuosi] <> \"2002\"  && [Tilastovuosi] <> \"2003\" && [Tilastovuosi] <> \"2004\" && [Tilastovuosi] <> \"2005\" && [Tilastovuosi] <> \"2006\" && [Tilastovuosi] <> \"2007\" && [Tilastovuosi] <> \"2008\" && [Tilastovuosi] <> \"2009\"))",
              "",
              "return IF(ehto || lkm = 0, BLANK(), lkm)",
              "",
              ""
            ],
            "formatString": "#,0.0"
          },
          {
            "name": "Kansainväliset opiskelijat FTE",
            "expression": [
              "",
              "var summa = ",
              "CALCULATE(",
              "\tSUM([opiskelijat_fte])",
              "\t, KEEPFILTERS(Muuttujat[Kansainvälinen opiskelija]=\"Kyllä\")",
              "\t, KEEPFILTERS(Muuttujat[Aineisto]=\"Lopullinen\")",
              "\t, KEEPFILTERS(Muuttujat[Koodit Koulutusaste taso 2] <> \"73\")",
              "\t, KEEPFILTERS(Muuttujat[Koodit Koulutusaste taso 2] <> \"91\")",
              ")",
              "return IF(summa=0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Uudet kansainväliset opiskelijat",
            "expression": [
              "",
              "var summa = ",
              "CALCULATE(",
              "\tSUM([Aloit2])",
              "\t, KEEPFILTERS(Muuttujat[Kansainvälinen opiskelija]=\"Kyllä\")",
              "\t, KEEPFILTERS(Muuttujat[Aineisto]=\"Lopullinen\")",
              "\t, KEEPFILTERS(Muuttujat[Koodit Koulutusaste taso 2] <> \"73\")",
              "\t, KEEPFILTERS(Muuttujat[Koodit Koulutusaste taso 2] <> \"91\")",
              ")",
              "return IF(summa=0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Kansainväliset opiskelijat",
            "expression": [
              "",
              "var summa = ",
              "CALCULATE(",
              "\tSUM([Opisk2])",
              "\t, KEEPFILTERS(Muuttujat[Kansainvälinen opiskelija]=\"Kyllä\")",
              "\t, KEEPFILTERS(Muuttujat[Aineisto]=\"Lopullinen\")",
              "\t, KEEPFILTERS(Muuttujat[Koodit Koulutusaste taso 2] <> \"73\")",
              "\t, KEEPFILTERS(Muuttujat[Koodit Koulutusaste taso 2] <> \"91\")",
              ")",
              "return IF(summa=0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Kansainvälisten opiskelijoiden suorittamat tutkinnot",
            "expression": [
              "",
              "var summa = ",
              "CALCULATE(",
              "\tSUM([Tutk2])",
              "\t, KEEPFILTERS(Muuttujat[Kansainvälinen opiskelija]=\"Kyllä\")",
              "\t, KEEPFILTERS(Muuttujat[Aineisto]=\"Lopullinen\")",
              "\t, KEEPFILTERS(Muuttujat[Koodit Koulutusaste taso 2] <> \"73\")",
              "\t, KEEPFILTERS(Muuttujat[Koodit Koulutusaste taso 2] <> \"91\")",
              ")",
              "return IF(summa=0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Opintopisteet yhteensä, amk",
            "expression": [
              "",
              "var summa = CALCULATE(SUM([op_amk_yhteensa]), FILTER('Muuttujat', [Kirjoihintulovuosi] <> [Tilastovuosi]), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"73\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"81\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"82\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"91\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"61\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"71\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"51\"))",
              "return IF(summa=0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))"
            ]
          },
          {
            "name": "Yleissivistävissä ja ammatillisissa oppilaitoksissa (Suomessa) suoritetut opintopisteet, amk",
            "expression": [
              "",
              "var summa = CALCULATE(SUM([op_amk_yleissiv_amm_opplait]), FILTER('Muuttujat', [Kirjoihintulovuosi] <> [Tilastovuosi]), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"73\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"81\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"82\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"91\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"61\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"71\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"51\"))",
              "return IF(summa=0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
              ""
            ],
            "displayFolder": "Opintopisteet_tutkinnot"
          },
          {
            "name": "Muualla suoritetut opintopisteet, amk",
            "expression": [
              "",
              "var summa = CALCULATE(SUM([op_amk_muualla]), FILTER('Muuttujat', [Kirjoihintulovuosi] <> [Tilastovuosi]), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"73\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"81\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"82\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"91\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"61\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"71\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"51\"))",
              "return IF(summa=0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
              ""
            ],
            "displayFolder": "Opintopisteet_tutkinnot"
          },
          {
            "name": "Omassa ammattikorkeakoulussa suoritetut opintopisteet, amk",
            "expression": [
              "",
              "var summa = CALCULATE(SUM([op_amk_oma_amk]), FILTER('Muuttujat', [Kirjoihintulovuosi] <> [Tilastovuosi]), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"73\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"81\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"82\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"91\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"61\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"71\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"51\"))",
              "return IF(summa=0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
              ""
            ],
            "displayFolder": "Opintopisteet_tutkinnot"
          },
          {
            "name": "Muissa ammattikorkeakouluissa (Suomessa) suoritetut opintopisteet, amk",
            "expression": [
              "",
              "var summa = CALCULATE(SUM([op_amk_muu_amk]), FILTER('Muuttujat', [Kirjoihintulovuosi] <> [Tilastovuosi]), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"73\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"81\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"82\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"91\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"61\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"71\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"51\"))",
              "return IF(summa=0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
              ""
            ],
            "displayFolder": "Opintopisteet_tutkinnot"
          },
          {
            "name": "Yliopistoissa (Suomessa) suoritetut opintopisteet, amk",
            "expression": [
              "",
              "var summa = CALCULATE(SUM([op_amk_yliopistoissa]), FILTER('Muuttujat', [Kirjoihintulovuosi] <> [Tilastovuosi]), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"73\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"81\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"82\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"91\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"61\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"71\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"51\"))",
              "return IF(summa=0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
              ""
            ],
            "displayFolder": "Opintopisteet_tutkinnot"
          },
          {
            "name": "Ulkomailla suoritetut opintopisteet, amk",
            "expression": [
              "",
              "var summa = CALCULATE(SUM([op_amk_ulkomailla]), FILTER('Muuttujat', [Kirjoihintulovuosi] <> [Tilastovuosi]), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"73\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"81\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"82\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"91\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"61\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"71\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"51\"))",
              "return IF(summa=0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
              ""
            ],
            "displayFolder": "Opintopisteet_tutkinnot"
          },
          {
            "name": "Opintopisteet yhteensä, yliop.",
            "expression": [
              "",
              "var summa = CALCULATE(SUM([op_yo_yhteensa]), FILTER('Muuttujat', [Kirjoihintulovuosi] <> [Tilastovuosi]), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"73\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"81\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"82\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"91\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"61\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"71\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"51\"))",
              "return IF(summa=0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
              ""
            ],
            "displayFolder": "Opintopisteet_tutkinnot"
          },
          {
            "name": "Ulkomailla suoritetut opintopisteet, yliop.",
            "expression": [
              "",
              "var summa = CALCULATE(SUM([op_yo_ulkomailla]), FILTER('Muuttujat', [Kirjoihintulovuosi] <> [Tilastovuosi]), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"73\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"81\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"82\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"91\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"61\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"71\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"51\"))",
              "return IF(summa=0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
              ""
            ],
            "displayFolder": "Opintopisteet_tutkinnot"
          },
          {
            "name": "Muualla suoritetut opintopisteet, yliop.",
            "expression": [
              "",
              "var summa = CALCULATE(SUM([op_yo_muualla]), FILTER('Muuttujat', [Kirjoihintulovuosi] <> [Tilastovuosi]), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"73\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"81\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"82\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"91\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"61\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"71\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"51\"))",
              "return IF(summa=0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
              ""
            ],
            "displayFolder": "Opintopisteet_tutkinnot"
          },
          {
            "name": "Omassa yliopistossa suoritetut opintopisteet (pl. avoin yliopisto), yliop.",
            "expression": [
              "",
              "var summa = CALCULATE(SUM([op_yo_oma_yo]), FILTER('Muuttujat', [Kirjoihintulovuosi] <> [Tilastovuosi]), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"73\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"81\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"82\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"91\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"61\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"71\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"51\"))",
              "return IF(summa=0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
              ""
            ],
            "displayFolder": "Opintopisteet_tutkinnot"
          },
          {
            "name": "Avoimessa yliopistossa suoritetut opintopisteet (joko oma tai muu yliopisto), yliop.",
            "expression": [
              "",
              "var summa = CALCULATE(SUM([op_yo_avoimessa]), FILTER('Muuttujat', [Kirjoihintulovuosi] <> [Tilastovuosi]), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"73\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"81\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"82\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"91\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"61\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"71\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"51\"))",
              "return IF(summa=0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
              ""
            ]
          },
          {
            "name": "Muissa yliopistoissa suoritetut opintopisteet (pl. avoin yliopisto), yliop.",
            "expression": [
              "",
              "var summa = CALCULATE(SUM([op_yo_muu_yo]), FILTER('Muuttujat', [Kirjoihintulovuosi] <> [Tilastovuosi]), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"73\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"81\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"82\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"91\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"61\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"71\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"51\"))",
              "return IF(summa=0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
              ""
            ],
            "displayFolder": "Opintopisteet_tutkinnot"
          },
          {
            "name": "Ammattikorkeakouluissa suoritetut opintopisteet, yliop.",
            "expression": [
              "",
              "var summa = CALCULATE(SUM([op_yo_ammattikorkeakouluissa]), FILTER('Muuttujat', [Kirjoihintulovuosi] <> [Tilastovuosi]), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"73\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"81\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"82\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"91\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"61\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"71\"), FILTER('Muuttujat',  [Koodit Koulutusaste taso 2] <> \"51\"))",
              "return IF(summa=0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))",
              ""
            ]
          },
          {
            "name": "Opintopisteet yhteensä, amk_s",
            "expression": "IF([kytkin] = 0, BLANK(), CALCULATE(SUM([op_amk_yhteensa]), FILTER('Muuttujat', [Kirjoihintulovuosi] <> [Tilastovuosi]), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"73\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"81\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"82\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"91\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"61\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"71\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"51\")))"
          },
          {
            "name": "Yleissivistävissä ja ammatillisissa oppilaitoksissa (Suomessa) suoritetut opintopisteet, amk_s",
            "expression": "IF([kytkin] = 0, BLANK(), CALCULATE(SUM([op_amk_yleissiv_amm_opplait]), FILTER('Muuttujat', [Kirjoihintulovuosi] <> [Tilastovuosi]), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"73\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"81\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"82\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"91\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"61\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"71\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"51\")))",
            "displayFolder": "Opintopisteet_tutkinnot"
          },
          {
            "name": "Muualla suoritetut opintopisteet, amk_s",
            "expression": "IF([kytkin] = 0, BLANK(), CALCULATE(SUM([op_amk_muualla]), FILTER('Muuttujat', [Kirjoihintulovuosi] <> [Tilastovuosi]), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"73\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"81\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"82\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"91\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"61\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"71\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"51\")))",
            "displayFolder": "Opintopisteet_tutkinnot"
          },
          {
            "name": "Omassa ammattikorkeakoulussa suoritetut opintopisteet, amk_s",
            "expression": "IF([kytkin] = 0, BLANK(), CALCULATE(SUM([op_amk_oma_amk]), FILTER('Muuttujat', [Kirjoihintulovuosi] <> [Tilastovuosi]), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"73\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"81\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"82\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"91\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"61\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"71\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"51\")))",
            "displayFolder": "Opintopisteet_tutkinnot"
          },
          {
            "name": "Muissa ammattikorkeakouluissa (Suomessa) suoritetut opintopisteet, amk_s",
            "expression": "IF([kytkin] = 0, BLANK(), CALCULATE(SUM([op_amk_muu_amk]), FILTER('Muuttujat', [Kirjoihintulovuosi] <> [Tilastovuosi]), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"73\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"81\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"82\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"91\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"61\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"71\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"51\")))",
            "displayFolder": "Opintopisteet_tutkinnot"
          },
          {
            "name": "Yliopistoissa (Suomessa) suoritetut opintopisteet, amk_s",
            "expression": "IF([kytkin] = 0, BLANK(), CALCULATE(SUM([op_amk_yliopistoissa]), FILTER('Muuttujat', [Kirjoihintulovuosi] <> [Tilastovuosi]), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"73\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"81\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"82\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"91\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"61\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"71\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"51\")))",
            "displayFolder": "Opintopisteet_tutkinnot"
          },
          {
            "name": "Ulkomailla suoritetut opintopisteet, amk_s",
            "expression": "IF([kytkin] = 0, BLANK(), CALCULATE(SUM([op_amk_ulkomailla]), FILTER('Muuttujat', [Kirjoihintulovuosi] <> [Tilastovuosi]), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"73\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"81\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"82\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"91\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"61\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"71\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"51\")))",
            "displayFolder": "Opintopisteet_tutkinnot"
          },
          {
            "name": "Opintopisteet yhteensä, yliop._s",
            "expression": "IF([kytkin] = 0, BLANK(), CALCULATE(SUM([op_yo_yhteensa]), FILTER('Muuttujat', [Kirjoihintulovuosi] <> [Tilastovuosi]), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"73\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"81\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"82\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"91\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"61\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"71\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"51\")))",
            "displayFolder": "Opintopisteet_tutkinnot"
          },
          {
            "name": "Ulkomailla suoritetut opintopisteet, yliop._s",
            "expression": "IF([kytkin] = 0, BLANK(), CALCULATE(SUM([op_yo_ulkomailla]), FILTER('Muuttujat', [Kirjoihintulovuosi] <> [Tilastovuosi]), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"73\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"81\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"82\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"91\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"61\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"71\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"51\")))",
            "displayFolder": "Opintopisteet_tutkinnot"
          },
          {
            "name": "Muualla suoritetut opintopisteet, yliop._s",
            "expression": "IF([kytkin] = 0, BLANK(), CALCULATE(SUM([op_yo_muualla]), FILTER('Muuttujat', [Kirjoihintulovuosi] <> [Tilastovuosi]), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"73\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"81\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"82\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"91\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"61\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"71\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"51\")))",
            "displayFolder": "Opintopisteet_tutkinnot"
          },
          {
            "name": "Omassa yliopistossa suoritetut opintopisteet (pl. avoin yliopisto), yliop._s",
            "expression": "IF([kytkin] = 0, BLANK(), CALCULATE(SUM([op_yo_oma_yo]), FILTER('Muuttujat', [Kirjoihintulovuosi] <> [Tilastovuosi]), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"73\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"81\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"82\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"91\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"61\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"71\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"51\")))",
            "displayFolder": "Opintopisteet_tutkinnot"
          },
          {
            "name": "Avoimessa yliopistossa suoritetut opintopisteet (joko oma tai muu yliopisto), yliop._s",
            "expression": "IF([kytkin] = 0, BLANK(), CALCULATE(SUM([op_yo_avoimessa]), FILTER('Muuttujat', [Kirjoihintulovuosi] <> [Tilastovuosi]), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"73\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"81\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"82\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"91\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"61\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"71\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"51\")))",
            "displayFolder": "Opintopisteet_tutkinnot"
          },
          {
            "name": "Muissa yliopistoissa suoritetut opintopisteet (pl. avoin yliopisto), yliop._s",
            "expression": "IF([kytkin] = 0, BLANK(), CALCULATE(SUM([op_yo_muu_yo]), FILTER('Muuttujat', [Kirjoihintulovuosi] <> [Tilastovuosi]), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"73\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"81\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"82\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"91\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"61\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"71\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"51\")))",
            "displayFolder": "Opintopisteet_tutkinnot"
          },
          {
            "name": "Ammattikorkeakouluissa suoritetut opintopisteet, yliop._s",
            "expression": "IF([kytkin] = 0, BLANK(), CALCULATE(SUM([op_yo_ammattikorkeakouluissa]), FILTER('Muuttujat', [Kirjoihintulovuosi] <> [Tilastovuosi]), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"73\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"81\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"82\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"91\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"61\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"71\"), FILTER('Muuttujat', [Koodit Koulutusaste taso 2] <> \"51\")))"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "v_f_tab_otv_korkeakoulut_yhteiset"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[v_f_tab_otv_korkeakoulut_yhteiset].* FROM [dbo].[v_f_tab_otv_korkeakoulut_yhteiset] "
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>\r",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r",
              "  <ColumnSuggestedType />\r",
              "  <ColumnFormat />\r",
              "  <ColumnAccuracy />\r",
              "  <ColumnCurrencySymbol />\r",
              "  <ColumnPositivePattern />\r",
              "  <ColumnNegativePattern />\r",
              "  <ColumnWidths>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Tilastovuosi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>86</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Päätieteenala</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>96</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Tieteenala</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>80</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Aineisto</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>68</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Aineisto_OTV</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>94</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Kaikkien asteiden koulutus</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>155</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>OTV_Tilv</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>72</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Äidinkieli</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>70</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Äidinkieli (väestörakenne)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>153</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Äidinkieli (suomi/muu)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>132</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Asuinalueen AVI</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>108</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Asuinalueen ELY</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>108</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Asuinkunnan kielisuhde</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>140</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Asuinmaakunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>103</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Asuinkunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>83</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Til.v:tta edeltävä AVI</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>133</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Til.v:tta edeltävä ELY</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>133</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Til.v:tta ed. asuinkunnan kielisuhde</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>199</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Til.v:tta ed. asuinmaakunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>162</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Til.v:tta ed. asuinkunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>142</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>2v til.v:tta ed. AVI</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>120</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>2v til.v:tta ed. ELY</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>120</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>2v til.v:tta ed. asuinkunnan kielisuhde</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>212</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>2v til.v:tta ed. asuinmaakunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>175</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>2v til.v:tta ed. asuinkunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>155</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Sukupuoli</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>75</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Ikä</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>45</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Ikäryhmä</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>75</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Syntymävuosi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>97</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Syntymäkuukausi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>113</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Tutkinto (amk)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>99</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Tutkinto (yo)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>92</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koulutustyyppi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>101</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Kansalaisuus</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>91</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Kansalaisuus (väestörakenne)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>174</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Tutkinto-oikeusvuosi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>128</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Kansalaisuus (suomi/muu)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>153</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Oppilaitos</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>77</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Yliopisto</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>69</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Ammattikorkeakoulu</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>126</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Opetuskieli</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>82</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Oppil. omistajatyyppi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>131</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Oppilaitostyyppi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>107</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koulutuksen järjestäjä</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>137</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koul. järj. omistajatyyppi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>150</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Lähde</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>59</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koulutusohjelma</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>108</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Kirjoillaolo (syys)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>110</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Kirjoillaolo (tammi)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>116</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Rahoituslähde</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>98</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Suuntautumisvaihtoehto</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>147</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koulutuksen kieli</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>108</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Ensisijainen opinto-oikeus</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>152</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Tilauskoulutuksen sijaintimaa</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>167</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koulutussektori</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>103</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Hallinnonala</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>87</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koulutusaste (2002)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>127</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koulutusala (2002)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>120</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koulutusala (1995)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>120</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Opintoala (2002)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>111</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koulutusnimike</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>100</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koulutuslaji</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>84</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koulutuslaji2</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>90</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koulutuksen AVI</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>108</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koulutuksen ELY</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>108</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koulutuksen maakunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>138</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koul. kunnan kielisuhde</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>141</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koulutuksen kunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>118</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Maakunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>77</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Kunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>58</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koul. järjestäjän AVI</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>129</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koul. järjestäjän ELY</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>129</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koul. järjestäjän maakunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>159</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koul. järj. kunnan kielisuhde</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>164</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koul. järjestäjän kunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>139</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Oppilaitoksen AVI</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>114</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Oppilaitoksen ELY</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>114</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Oppilaitoksen maakunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>144</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Oppil. kunnan kielisuhde</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>145</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Oppilaitoksen kunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>124</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Kirjoihintulovuosi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>110</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Kirjoihintulokausi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>109</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Kirjoihintulovuosi (kk-sek.)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>155</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Kirjoihintulovuosi (kk-sek. läsna)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>183</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Kirjoihintulovuosi (sek.)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>141</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Kirjoihintulovuosi (sek. läsnä)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>169</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Kirjoihintulovuosi (kk)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>131</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Kirjoihintulokausi (kk)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>130</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Kirjoihintulovuosi (kk läsnä)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>159</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Kirjoihintulovuosi (op.ala)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>151</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Kirjoihintulovuosi (op.ala läsnä)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>179</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Kirjoihintulovuosi (tutk.)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>144</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Kirjoihintulokausi (tutk.)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>143</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Kirjoihintulovuosi (TK määritelmä)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>188</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Suorittanut väh. 55 op</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>139</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Opiskelijan FTE-tieto</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>128</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Yliopistotunnus</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>102</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Tiedekunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>83</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Uusi/vanha opiskelija</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>130</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Opettajankelpoisuus</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>128</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Hyväksytty avoimen yliop. suoritusten kautta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>248</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Tutkinnon suoritusvuosi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>143</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Tutk. suorituslukukausi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>139</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Tutk. suorituskuukausi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>137</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Kansalaisuus (maanosa)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>145</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>EU-maan kansalainen</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>132</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>ETA-maan kansalainen</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>138</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Pohjoismaan kansalainen</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>149</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>aineisto_otv_jarj</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>111</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_aidinkieli</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>91</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_aidinkieli2</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>97</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_aidinkieli3</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>97</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_as_avi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>83</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_as_ely</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>83</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_as_kielisuhde</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>115</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_as_maakunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>116</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_as_kunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>96</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_as_avi1x</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>95</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_as_ely1x</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>95</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_as_kielisuhde1x</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>127</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_as_maakunta1x</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>128</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_as_kunta1x</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>108</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_as_avi2x</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>95</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_as_ely2x</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>95</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_as_kielisuhde2x</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>127</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_as_maakunta2x</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>128</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_as_kunta2x</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>108</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarjestys_ika</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>91</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_ika5v</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>77</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_syntv</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>79</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_tutk_amk</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>96</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_tutk_yo</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>89</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_koultyyppi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>101</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_kansalaisuus</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>112</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_kansalaisuus2</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>118</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_kansalaisuus3</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>118</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarjestys_paatieteenala2010</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>168</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarjestys_tieteenala2010</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>150</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarjestys_oppilaitos</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>123</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarjestys_opetuskieli</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>128</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarjestys_omistajatyyppi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>148</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarjestys_oppilaitostyyppi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>153</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_koulohjelma_amk</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>133</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_kirjolosyys</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>102</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_kirjolotammi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>108</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_rahoitus</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>91</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_suunnvaiht</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>105</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_koulkiel</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>86</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_koulkiel2</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>92</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_ensop</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>81</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_tilauskoul</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>96</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_koulsek</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>87</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_hallinnonala</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>108</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarjestys_koulutusaste2002</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>163</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarjestys_koulutusala2002</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>156</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarjestys_opintoala1995</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>146</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarjestys_opintoala2002</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>146</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_koulnimike</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>100</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_koullaji</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>84</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_koullaji2</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>90</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarjestys_avi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>92</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarjestys_ely</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>92</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarjestys_maakunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>125</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarjestys_kielisuhde</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>124</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_kunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>79</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_kmaakunta2</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>110</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_kkunta2</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>90</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarjestys_avi2</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>98</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarjestys_ely2</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>98</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarjestys_maakunta2</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>131</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarjestys_kielisuhde2</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>130</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_kunta2</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>85</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarjestys_avi3</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>98</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarjestys_ely3</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>98</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarjestys_maakunta3</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>131</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarjestys_kielisuhde3</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>130</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_kunta3</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>85</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_lukukausi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>95</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_lukukausi_kk</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>111</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_vah55</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>82</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_op_fte</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>84</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_tiedekunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>103</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_uusivanha</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>101</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_opettajankelpoisuus</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>148</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_avoinvayla</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>104</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_suor_kk</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>89</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_kans_maanosa</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>123</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarjestys_eumaa</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>110</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarjestys_etamaa</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>114</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_pohj_kans</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>101</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>aineisto_koodi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>98</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>ainesto_koodi_otv</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>118</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>aidinkieli_koodi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>100</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>aidinkieli2_koodi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>106</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>aidinkieli3_koodi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>106</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koodit Asuinmaakunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>136</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koodit Asuinkunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>116</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>asmaak1xmk</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>91</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>asmaak1xk</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>83</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>syntk</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>56</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koodit Tutkinto (amk)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>132</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koodit Tutkinto (yo)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>125</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koodit Koulutustyyppi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>134</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>kansalaisuus_koodi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>121</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>kansalaisuus2_koodi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>127</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>kansalaisuus3_koodi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>127</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koodit Oppilaitos</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>110</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koodit Koulutuksen järjestäjä</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>170</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>lahde_koodi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>87</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koodit Koulutusohjelma</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>141</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>kirjoillaolosyys_koodi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>129</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>kirjoillaolotammi_koodi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>135</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>ensiop</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>61</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koodit Koulutusaste 2002</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>152</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koodit Koulutusala 2002</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>145</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koodit Koulutusala 1995</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>145</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koodit Opintoala 2002</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>136</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koodit Koulutusnimike</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>133</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koodit Koulutuksen maakunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>171</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koodit Koulutuksen kunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>151</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koodit Maakunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>110</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koodit Kunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>91</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koodit Koul. järj. maakunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>160</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koodit Koul. järj. kunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>140</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koodit Oppil. maakunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>141</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koodit Oppil. kunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>121</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>alvv</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>50</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>alkk</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>48</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>alvv_kksek</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>82</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>alvv_kksek_lasna</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>113</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>alvv_sek</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>72</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>alvv_sek_lasna</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>103</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>alvv_kk</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>66</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>alkk_kk</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>64</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>alvv_kk_lasna</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>97</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>alvv_opa</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>74</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>alvv_opa_lasna</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>105</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>kirtu1v</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>63</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>kirtu1k</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>62</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>op55_koodi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>85</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>suorv</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>57</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>suor_lk</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>64</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>suor_kk</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>67</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Statistikår</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>78</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Huvudsakligt vetenskapsområde</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>185</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Vetenskapsområde</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>121</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Modersmål</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>81</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Modersmål (utbildningsstruktur)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>181</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Modersmål (finska/andra)SV</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>164</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Bostadslandskap</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>110</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Bostadskommun</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>107</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Kön</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>48</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Ålder</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>55</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Åldersgrupp</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>88</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Födelseår</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>77</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Examen (yrkehögskola)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>142</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Examen (universitet)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>130</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Typ av utbildning</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>112</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Medborgarskap</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>104</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Medborgarskap (utbildningsstruktur)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>204</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Medborgarskap (finska/andra)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>175</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Läroanstalt</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>84</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Universitet</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>82</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Yrkeshögskola</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>98</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Utbildningsprogram</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>122</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Inskrivning (september)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>144</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Inskrivning (januari)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>126</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Finansieringskälla</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>113</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Utbildningssektor</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>112</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Utbildningsnivå (2002)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>137</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Utbildningsområde (2002)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>153</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Utbildningsområde (1995)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>153</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Studieområde (2002)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>131</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Utbildningsbenämning</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>134</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Utbildningsslag</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>101</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Utbildningsslag2</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>107</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Utbildningens landskap</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>139</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Utbildningens kommun</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>136</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Landskap</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>75</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Kommun</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>70</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>År då utbildningen avlagts</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>155</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Medborgarskap (världsdel)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>158</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Medborgare i ett EU-land</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>150</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Medborgare i ett EES-land</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>155</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Medborgare i ett nordiskt land</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>174</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Statistical year</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>101</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Main discipline</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>97</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Discipline</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>73</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Mother tongue</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>101</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Mother tongue (ed. structure)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>175</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Mother tongue (Finnish/Other)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>177</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Region of residence</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>125</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Municipality of residence</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>147</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Gender</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>65</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Age</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>49</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Agegroup</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>77</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Year of birth</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>90</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Degree (polytechnic)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>130</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Degree (university)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>123</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Type of education</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>117</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Nationality</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>81</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Nationality (ed. structure)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>155</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Nationality (Finn/Other)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>144</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Educational institution</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>135</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>University</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>78</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Polytechnic</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>84</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Degree programme</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>122</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Enrollment status (sept.)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>149</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Enrollment status (jan.)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>143</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Source of funding</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>115</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Sector of education</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>124</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Level of education (2002)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>153</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Field of education (2002)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>150</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Field of education (1995)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>150</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Subfield of ed. (2002)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>135</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Name of education</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>120</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Form of education</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>117</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Form of education2</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>123</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Region of education</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>126</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Municipality of education</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>148</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Region</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>63</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Municipality</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>85</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Year of enrollment</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>118</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Term of enrollment</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>120</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Year of enrollment (HE sec.)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>165</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Year of enrollment (HE sec. present)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>205</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Year of enrollment (sec.)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>149</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Year of enrollment (sec. present)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>189</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Year of enrollment (ed. inst.)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>169</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Term of enrollment (ed. inst.)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>171</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Year of enrollment (ed. inst. present)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>209</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Year of enrollment (subfield of ed.)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>198</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Year of enrollment (subfield of ed. present)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>238</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Year of enrollment (degree)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>163</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Term of enrollment (degree)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>165</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Year of enrollment (Statistic Finland's definition)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>258</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Year of graduation</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>120</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Term of graduation</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>122</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Month of graduation</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>128</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Nationality (continent)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>137</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Citizen of EU nation</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>124</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Citizen of EEA nation</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>130</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Citizen of a nordic nation</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>149</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koulutusaste, taso 1</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>129</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koulutusaste, taso 2</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>129</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koulutusala, taso 1</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>122</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koulutusala, taso 2</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>122</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koulutusala, taso 3</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>122</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>OKM ohjauksen ala, korkeak.</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>169</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Utbildn.nivå, nivå 1</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>123</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Utbildn.nivå, nivå 2</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>123</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Utbildn.område, nivå 1</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>139</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Utbildn.område, nivå 2</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>139</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Utbildn.område, nivå 3</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>139</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>UKM-styrningsområde, högskolor</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>188</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Level of ed., tier 1</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>119</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Level of ed., tier 2</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>119</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Field of education, tier 1</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>147</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Field of education, tier 2</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>147</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Field of education, tier 3</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>147</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Field of ed., HE steering</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>146</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_isced_koulast1</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>122</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_isced_koulast2</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>122</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_isced_koulala1</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>121</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_isced_koulala2</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>121</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_isced_koulala3</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>121</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_isced_okmohjaus1</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>139</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koodit Koulutusaste, taso 1</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>162</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koodit Koulutusaste, taso 2</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>162</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koodit Koulutusala, taso 1</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>155</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koodit Koulutusala, taso 2</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>155</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koodit Koulutusala, taso 3</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>155</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koodit OKM ohjauksen ala, korkeak.</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>202</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_rahoitusala2016_amk</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>194</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_rahoitusala2016_yo</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>184</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Opisk2</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>62</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Aloit2</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>57</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>lkm_op55</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>75</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>lkm_op0</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>69</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>lkm_op1_14</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>87</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>lkm_op15_29</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>93</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>lkm_op30_44</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>93</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>lkm_op45_59</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>93</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>lkm_op60_74</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>93</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>lkm_op75_89</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>93</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>lkm_op90_104</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>99</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>lkm_op105_119</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>105</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>lkm_op120_</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>87</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>aloittaneet_kirjoihintulovuosi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>167</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>aloittaneet_korkeakoulusektori</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>177</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>aloittaneet_korkeakoulusektori_lasnaoleva</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>234</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>aloittaneet_sektori</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>120</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>aloittaneet_sektori_lasnaoleva</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>177</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>aloittaneet_korkeakoulu</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>145</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>aloittaneet_korkeakoulu_lasnaoleva</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>202</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>aloittaneet_opintoala</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>132</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>aloittaneet_opintoala_lasnaoleva</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>189</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>opiskelijat_lasna</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>108</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>opiskelijat_fte</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>97</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>lkm_lasnalk</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>83</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>lkm_poissalk</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>88</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>op_suoritettavien_laajuus</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>155</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>op_edellinen_syksy</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>123</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>op_edellinen_kevat</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>123</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>op_kertyma_edel_lkv_loppu</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>164</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Tutk2</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>57</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>op_amk_yhteensa</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>118</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>op_amk_yleissiv_amm_opplait</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>173</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>op_amk_muualla</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>109</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>op_amk_oma_amk</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>118</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>op_amk_muu_amk</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>118</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>op_amk_yliopistoissa</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>130</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>op_amk_ulkomailla</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>118</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>op_yo_yhteensa</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>111</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>op_yo_ulkomailla</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>111</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>op_yo_muualla</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>102</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>op_yo_oma_yo</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>104</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>op_yo_avoimessa</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>116</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>op_yo_muu_yo</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>104</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>op_yo_ammattikorkeakouluissa</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>179</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>ika19_21_lkm</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>94</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>ika20_24_lkm</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>94</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>ika25_34_lkm</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>94</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>ika25_64_lkm</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>94</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_rahoitusala2021_yo</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>184</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Rahoitusmallialat yo 2017-2020</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>227</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Rahoitusmallialat amk 2017-2020</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>237</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Rahoitusmallialat yo 2021-2024</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>227</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Rahoitusmallialat amk 2021-2024</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>237</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Oppilaitos (tilastovuosi)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>174</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koulutuksen järjestäjä (tilastovuosi)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>251</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarjestys_oppilaitos_tilv</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>176</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Aloit3</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>68</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Kansalaisuus (ennakko)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>176</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Kansainvälinen opiskelija</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>180</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Liikkuvuuden kesto</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>152</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Mobilitetens längd</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>142</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Duration of mobility</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>155</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarjestys_liikkuvuuden_kesto</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>211</int>\r",
              "      </value>\r",
              "    </item>\r",
              "  </ColumnWidths>\r",
              "  <ColumnDisplayIndex>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Tilastovuosi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>0</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Päätieteenala</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>1</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Tieteenala</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>2</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Aineisto</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>3</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Aineisto_OTV</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>4</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Kaikkien asteiden koulutus</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>5</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>OTV_Tilv</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>6</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Äidinkieli</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>7</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Äidinkieli (väestörakenne)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>8</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Äidinkieli (suomi/muu)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>9</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Asuinalueen AVI</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>10</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Asuinalueen ELY</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>11</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Asuinkunnan kielisuhde</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>12</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Asuinmaakunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>13</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Asuinkunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>14</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Til.v:tta edeltävä AVI</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>15</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Til.v:tta edeltävä ELY</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>16</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Til.v:tta ed. asuinkunnan kielisuhde</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>17</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Til.v:tta ed. asuinmaakunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>18</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Til.v:tta ed. asuinkunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>19</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>2v til.v:tta ed. AVI</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>20</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>2v til.v:tta ed. ELY</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>21</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>2v til.v:tta ed. asuinkunnan kielisuhde</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>22</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>2v til.v:tta ed. asuinmaakunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>23</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>2v til.v:tta ed. asuinkunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>24</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Sukupuoli</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>25</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Ikä</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>26</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Ikäryhmä</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>27</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Syntymävuosi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>28</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Syntymäkuukausi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>29</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Tutkinto (amk)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>30</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Tutkinto (yo)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>31</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koulutustyyppi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>32</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Kansalaisuus</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>33</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Kansalaisuus (väestörakenne)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>34</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Tutkinto-oikeusvuosi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>35</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Kansalaisuus (suomi/muu)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>36</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Oppilaitos</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>37</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Yliopisto</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>38</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Ammattikorkeakoulu</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>39</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Opetuskieli</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>40</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Oppil. omistajatyyppi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>41</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Oppilaitostyyppi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>42</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koulutuksen järjestäjä</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>43</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koul. järj. omistajatyyppi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>44</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Lähde</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>45</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koulutusohjelma</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>46</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Kirjoillaolo (syys)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>47</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Kirjoillaolo (tammi)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>48</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Rahoituslähde</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>49</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Suuntautumisvaihtoehto</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>50</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koulutuksen kieli</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>51</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Ensisijainen opinto-oikeus</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>52</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Tilauskoulutuksen sijaintimaa</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>53</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koulutussektori</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>54</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Hallinnonala</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>55</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koulutusaste (2002)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>56</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koulutusala (2002)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>57</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koulutusala (1995)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>58</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Opintoala (2002)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>59</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koulutusnimike</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>60</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koulutuslaji</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>61</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koulutuslaji2</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>62</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koulutuksen AVI</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>63</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koulutuksen ELY</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>64</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koulutuksen maakunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>65</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koul. kunnan kielisuhde</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>66</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koulutuksen kunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>67</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Maakunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>68</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Kunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>69</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koul. järjestäjän AVI</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>70</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koul. järjestäjän ELY</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>71</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koul. järjestäjän maakunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>72</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koul. järj. kunnan kielisuhde</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>73</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koul. järjestäjän kunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>74</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Oppilaitoksen AVI</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>75</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Oppilaitoksen ELY</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>76</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Oppilaitoksen maakunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>77</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Oppil. kunnan kielisuhde</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>78</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Oppilaitoksen kunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>79</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Kirjoihintulovuosi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>80</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Kirjoihintulokausi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>81</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Kirjoihintulovuosi (kk-sek.)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>82</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Kirjoihintulovuosi (kk-sek. läsna)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>83</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Kirjoihintulovuosi (sek.)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>84</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Kirjoihintulovuosi (sek. läsnä)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>85</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Kirjoihintulovuosi (kk)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>86</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Kirjoihintulokausi (kk)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>87</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Kirjoihintulovuosi (kk läsnä)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>88</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Kirjoihintulovuosi (op.ala)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>89</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Kirjoihintulovuosi (op.ala läsnä)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>90</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Kirjoihintulovuosi (tutk.)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>91</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Kirjoihintulokausi (tutk.)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>92</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Kirjoihintulovuosi (TK määritelmä)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>93</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Suorittanut väh. 55 op</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>94</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Opiskelijan FTE-tieto</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>95</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Yliopistotunnus</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>96</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Tiedekunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>97</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Uusi/vanha opiskelija</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>98</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Opettajankelpoisuus</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>99</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Hyväksytty avoimen yliop. suoritusten kautta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>100</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Tutkinnon suoritusvuosi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>101</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Tutk. suorituslukukausi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>102</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Tutk. suorituskuukausi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>103</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Kansalaisuus (maanosa)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>104</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>EU-maan kansalainen</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>105</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>ETA-maan kansalainen</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>106</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Pohjoismaan kansalainen</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>107</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>aineisto_otv_jarj</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>108</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_aidinkieli</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>109</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_aidinkieli2</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>110</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_aidinkieli3</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>111</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_as_avi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>112</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_as_ely</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>113</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_as_kielisuhde</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>114</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_as_maakunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>115</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_as_kunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>116</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_as_avi1x</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>117</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_as_ely1x</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>118</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_as_kielisuhde1x</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>119</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_as_maakunta1x</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>120</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_as_kunta1x</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>121</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_as_avi2x</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>122</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_as_ely2x</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>123</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_as_kielisuhde2x</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>124</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_as_maakunta2x</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>125</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_as_kunta2x</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>126</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarjestys_ika</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>127</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_ika5v</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>128</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_syntv</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>129</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_tutk_amk</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>130</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_tutk_yo</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>131</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_koultyyppi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>132</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_kansalaisuus</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>133</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_kansalaisuus2</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>134</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_kansalaisuus3</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>135</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarjestys_paatieteenala2010</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>136</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarjestys_tieteenala2010</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>137</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarjestys_oppilaitos</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>138</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarjestys_opetuskieli</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>139</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarjestys_omistajatyyppi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>140</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarjestys_oppilaitostyyppi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>141</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_koulohjelma_amk</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>142</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_kirjolosyys</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>143</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_kirjolotammi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>144</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_rahoitus</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>145</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_suunnvaiht</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>146</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_koulkiel</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>147</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_koulkiel2</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>148</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_ensop</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>149</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_tilauskoul</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>150</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_koulsek</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>151</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_hallinnonala</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>152</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarjestys_koulutusaste2002</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>153</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarjestys_koulutusala2002</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>154</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarjestys_opintoala1995</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>155</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarjestys_opintoala2002</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>156</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_koulnimike</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>157</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_koullaji</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>158</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_koullaji2</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>159</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarjestys_avi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>160</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarjestys_ely</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>161</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarjestys_maakunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>162</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarjestys_kielisuhde</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>163</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_kunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>164</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_kmaakunta2</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>165</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_kkunta2</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>166</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarjestys_avi2</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>167</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarjestys_ely2</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>168</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarjestys_maakunta2</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>169</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarjestys_kielisuhde2</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>170</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_kunta2</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>171</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarjestys_avi3</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>172</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarjestys_ely3</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>173</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarjestys_maakunta3</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>174</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarjestys_kielisuhde3</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>175</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_kunta3</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>176</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_lukukausi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>177</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_lukukausi_kk</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>178</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_vah55</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>179</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_op_fte</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>180</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_tiedekunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>181</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_uusivanha</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>182</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_opettajankelpoisuus</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>183</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_avoinvayla</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>184</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_suor_kk</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>185</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_kans_maanosa</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>186</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarjestys_eumaa</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>187</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarjestys_etamaa</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>188</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_pohj_kans</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>189</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>aineisto_koodi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>190</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>ainesto_koodi_otv</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>191</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>aidinkieli_koodi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>192</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>aidinkieli2_koodi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>193</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>aidinkieli3_koodi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>194</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koodit Asuinmaakunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>195</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koodit Asuinkunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>196</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>asmaak1xmk</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>197</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>asmaak1xk</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>198</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>syntk</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>199</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koodit Tutkinto (amk)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>200</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koodit Tutkinto (yo)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>201</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koodit Koulutustyyppi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>202</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>kansalaisuus_koodi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>203</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>kansalaisuus2_koodi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>204</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>kansalaisuus3_koodi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>205</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koodit Oppilaitos</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>206</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koodit Koulutuksen järjestäjä</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>207</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>lahde_koodi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>208</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koodit Koulutusohjelma</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>209</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>kirjoillaolosyys_koodi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>210</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>kirjoillaolotammi_koodi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>211</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>ensiop</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>212</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koodit Koulutusaste 2002</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>213</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koodit Koulutusala 2002</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>214</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koodit Koulutusala 1995</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>215</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koodit Opintoala 2002</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>216</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koodit Koulutusnimike</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>217</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koodit Koulutuksen maakunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>218</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koodit Koulutuksen kunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>219</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koodit Maakunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>220</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koodit Kunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>221</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koodit Koul. järj. maakunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>222</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koodit Koul. järj. kunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>223</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koodit Oppil. maakunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>224</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koodit Oppil. kunta</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>225</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>alvv</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>226</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>alkk</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>227</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>alvv_kksek</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>228</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>alvv_kksek_lasna</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>229</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>alvv_sek</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>230</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>alvv_sek_lasna</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>231</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>alvv_kk</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>232</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>alkk_kk</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>233</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>alvv_kk_lasna</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>234</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>alvv_opa</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>235</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>alvv_opa_lasna</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>236</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>kirtu1v</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>237</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>kirtu1k</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>238</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>op55_koodi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>239</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>suorv</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>240</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>suor_lk</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>241</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>suor_kk</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>242</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Statistikår</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>243</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Huvudsakligt vetenskapsområde</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>244</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Vetenskapsområde</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>245</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Modersmål</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>246</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Modersmål (utbildningsstruktur)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>247</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Modersmål (finska/andra)SV</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>248</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Bostadslandskap</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>249</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Bostadskommun</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>250</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Kön</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>251</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Ålder</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>252</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Åldersgrupp</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>253</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Födelseår</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>254</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Examen (yrkehögskola)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>255</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Examen (universitet)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>256</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Typ av utbildning</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>257</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Medborgarskap</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>258</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Medborgarskap (utbildningsstruktur)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>259</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Medborgarskap (finska/andra)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>260</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Läroanstalt</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>261</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Universitet</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>262</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Yrkeshögskola</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>263</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Utbildningsprogram</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>264</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Inskrivning (september)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>265</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Inskrivning (januari)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>266</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Finansieringskälla</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>267</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Utbildningssektor</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>268</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Utbildningsnivå (2002)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>269</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Utbildningsområde (2002)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>270</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Utbildningsområde (1995)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>271</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Studieområde (2002)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>272</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Utbildningsbenämning</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>273</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Utbildningsslag</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>274</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Utbildningsslag2</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>275</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Utbildningens landskap</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>276</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Utbildningens kommun</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>277</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Landskap</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>278</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Kommun</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>279</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>År då utbildningen avlagts</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>280</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Medborgarskap (världsdel)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>281</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Medborgare i ett EU-land</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>282</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Medborgare i ett EES-land</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>283</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Medborgare i ett nordiskt land</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>284</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Statistical year</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>285</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Main discipline</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>286</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Discipline</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>287</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Mother tongue</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>288</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Mother tongue (ed. structure)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>289</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Mother tongue (Finnish/Other)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>290</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Region of residence</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>291</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Municipality of residence</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>292</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Gender</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>293</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Age</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>294</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Agegroup</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>295</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Year of birth</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>296</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Degree (polytechnic)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>297</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Degree (university)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>298</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Type of education</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>299</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Nationality</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>300</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Nationality (ed. structure)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>301</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Nationality (Finn/Other)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>302</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Educational institution</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>303</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>University</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>304</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Polytechnic</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>305</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Degree programme</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>306</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Enrollment status (sept.)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>307</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Enrollment status (jan.)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>308</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Source of funding</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>309</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Sector of education</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>310</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Level of education (2002)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>311</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Field of education (2002)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>312</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Field of education (1995)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>313</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Subfield of ed. (2002)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>314</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Name of education</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>315</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Form of education</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>316</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Form of education2</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>317</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Region of education</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>318</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Municipality of education</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>319</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Region</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>320</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Municipality</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>321</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Year of enrollment</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>322</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Term of enrollment</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>323</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Year of enrollment (HE sec.)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>324</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Year of enrollment (HE sec. present)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>325</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Year of enrollment (sec.)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>326</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Year of enrollment (sec. present)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>327</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Year of enrollment (ed. inst.)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>328</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Term of enrollment (ed. inst.)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>329</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Year of enrollment (ed. inst. present)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>330</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Year of enrollment (subfield of ed.)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>331</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Year of enrollment (subfield of ed. present)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>332</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Year of enrollment (degree)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>333</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Term of enrollment (degree)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>334</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Year of enrollment (Statistic Finland's definition)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>335</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Year of graduation</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>336</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Term of graduation</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>337</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Month of graduation</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>338</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Nationality (continent)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>339</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Citizen of EU nation</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>340</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Citizen of EEA nation</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>341</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Citizen of a nordic nation</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>342</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koulutusaste, taso 1</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>343</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koulutusaste, taso 2</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>344</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koulutusala, taso 1</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>345</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koulutusala, taso 2</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>346</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koulutusala, taso 3</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>347</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>OKM ohjauksen ala, korkeak.</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>348</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Utbildn.nivå, nivå 1</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>349</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Utbildn.nivå, nivå 2</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>350</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Utbildn.område, nivå 1</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>351</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Utbildn.område, nivå 2</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>352</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Utbildn.område, nivå 3</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>353</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>UKM-styrningsområde, högskolor</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>354</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Level of ed., tier 1</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>355</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Level of ed., tier 2</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>356</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Field of education, tier 1</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>357</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Field of education, tier 2</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>358</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Field of education, tier 3</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>359</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Field of ed., HE steering</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>360</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_isced_koulast1</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>361</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_isced_koulast2</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>362</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_isced_koulala1</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>363</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_isced_koulala2</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>364</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_isced_koulala3</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>365</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_isced_okmohjaus1</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>366</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koodit Koulutusaste, taso 1</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>367</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koodit Koulutusaste, taso 2</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>368</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koodit Koulutusala, taso 1</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>369</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koodit Koulutusala, taso 2</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>370</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koodit Koulutusala, taso 3</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>371</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koodit OKM ohjauksen ala, korkeak.</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>372</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_rahoitusala2016_amk</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>423</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_rahoitusala2016_yo</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>422</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Opisk2</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>373</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Aloit2</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>374</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>lkm_op55</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>375</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>lkm_op0</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>376</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>lkm_op1_14</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>377</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>lkm_op15_29</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>378</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>lkm_op30_44</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>379</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>lkm_op45_59</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>380</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>lkm_op60_74</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>381</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>lkm_op75_89</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>382</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>lkm_op90_104</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>383</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>lkm_op105_119</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>384</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>lkm_op120_</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>385</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>aloittaneet_kirjoihintulovuosi</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>386</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>aloittaneet_korkeakoulusektori</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>387</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>aloittaneet_korkeakoulusektori_lasnaoleva</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>388</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>aloittaneet_sektori</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>389</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>aloittaneet_sektori_lasnaoleva</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>390</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>aloittaneet_korkeakoulu</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>391</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>aloittaneet_korkeakoulu_lasnaoleva</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>392</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>aloittaneet_opintoala</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>393</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>aloittaneet_opintoala_lasnaoleva</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>394</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>opiskelijat_lasna</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>395</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>opiskelijat_fte</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>396</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>lkm_lasnalk</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>397</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>lkm_poissalk</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>398</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>op_suoritettavien_laajuus</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>399</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>op_edellinen_syksy</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>400</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>op_edellinen_kevat</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>401</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>op_kertyma_edel_lkv_loppu</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>402</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Tutk2</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>403</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>op_amk_yhteensa</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>404</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>op_amk_yleissiv_amm_opplait</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>405</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>op_amk_muualla</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>406</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>op_amk_oma_amk</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>407</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>op_amk_muu_amk</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>408</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>op_amk_yliopistoissa</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>409</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>op_amk_ulkomailla</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>410</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>op_yo_yhteensa</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>411</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>op_yo_ulkomailla</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>412</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>op_yo_muualla</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>413</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>op_yo_oma_yo</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>414</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>op_yo_avoimessa</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>415</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>op_yo_muu_yo</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>416</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>op_yo_ammattikorkeakouluissa</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>417</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>ika19_21_lkm</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>418</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>ika20_24_lkm</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>419</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>ika25_34_lkm</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>420</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>ika25_64_lkm</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>421</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_rahoitusala2021_yo</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>424</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Rahoitusmallialat yo 2017-2020</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>425</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Rahoitusmallialat amk 2017-2020</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>426</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Rahoitusmallialat yo 2021-2024</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>427</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Rahoitusmallialat amk 2021-2024</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>428</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Oppilaitos (tilastovuosi)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>429</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koulutuksen järjestäjä (tilastovuosi)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>430</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarjestys_oppilaitos_tilv</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>431</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Aloit3</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>432</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Kansalaisuus (ennakko)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>433</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Kansainvälinen opiskelija</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>434</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Liikkuvuuden kesto</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>435</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Mobilitetens längd</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>436</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Duration of mobility</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>437</int>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarjestys_liikkuvuuden_kesto</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <int>438</int>\r",
              "      </value>\r",
              "    </item>\r",
              "  </ColumnDisplayIndex>\r",
              "  <ColumnFrozen />\r",
              "  <ColumnChecked>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Päätieteenala</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <boolean>true</boolean>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Tieteenala</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <boolean>true</boolean>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarjestys_paatieteenala2010</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <boolean>true</boolean>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarjestys_tieteenala2010</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <boolean>true</boolean>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Huvudsakligt vetenskapsområde</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <boolean>true</boolean>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Vetenskapsområde</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <boolean>true</boolean>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Main discipline</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <boolean>true</boolean>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Discipline</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <boolean>true</boolean>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_rahoitusala2016_yo</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <boolean>true</boolean>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_rahoitusala2016_amk</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <boolean>true</boolean>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarj_rahoitusala2021_yo</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <boolean>true</boolean>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Rahoitusmallialat yo 2017-2020</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <boolean>true</boolean>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Rahoitusmallialat amk 2017-2020</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <boolean>true</boolean>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Rahoitusmallialat yo 2021-2024</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <boolean>true</boolean>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Rahoitusmallialat amk 2021-2024</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <boolean>true</boolean>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Oppilaitos (tilastovuosi)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <boolean>true</boolean>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Koulutuksen järjestäjä (tilastovuosi)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <boolean>true</boolean>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarjestys_oppilaitos_tilv</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <boolean>true</boolean>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Aloit3</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <boolean>true</boolean>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Kansalaisuus (ennakko)</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <boolean>true</boolean>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Kansainvälinen opiskelija</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <boolean>true</boolean>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Liikkuvuuden kesto</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <boolean>true</boolean>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Mobilitetens längd</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <boolean>true</boolean>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>Duration of mobility</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <boolean>true</boolean>\r",
              "      </value>\r",
              "    </item>\r",
              "    <item>\r",
              "      <key>\r",
              "        <string>jarjestys_liikkuvuuden_kesto</string>\r",
              "      </key>\r",
              "      <value>\r",
              "        <boolean>true</boolean>\r",
              "      </value>\r",
              "    </item>\r",
              "  </ColumnChecked>\r",
              "  <ColumnFilter />\r",
              "  <SelectionFilter />\r",
              "  <FilterParameters />\r",
              "  <IsSortDescending>false</IsSortDescending>\r",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      }
    ],
    "cultures": [
      {
        "name": "sv-SE",
        "translations": {
          "model": {
            "name": "Model",
            "tables": [
              {
                "name": "Muuttujat",
                "translatedCaption": "Variabler",
                "columns": [
                  {
                    "name": "Koodit Asuinmaakunta",
                    "translatedCaption": "Kod Bostadslandskap",
                    "translatedDisplayFolder": "Kodvariabler"
                  },
                  {
                    "name": "Koodit Asuinkunta",
                    "translatedCaption": "Kod Bostadskommun",
                    "translatedDisplayFolder": "Kodvariabler"
                  },
                  {
                    "name": "Koodit Tutkinto amk",
                    "translatedCaption": "Kod Examen (yrkeshögskola)",
                    "translatedDisplayFolder": "Kodvariabler"
                  },
                  {
                    "name": "Koodit Tutkinto yo",
                    "translatedCaption": "Kod Examen (universitet)",
                    "translatedDisplayFolder": "Kodvariabler"
                  },
                  {
                    "name": "Koodit Koulutustyyppi",
                    "translatedCaption": "Kod Typ av utbildning",
                    "translatedDisplayFolder": "Kodvariabler"
                  },
                  {
                    "name": "Koodit Oppilaitos",
                    "translatedCaption": "Kod Läroanstalt",
                    "translatedDisplayFolder": "Kodvariabler"
                  },
                  {
                    "name": "Koodit Koulutuksen järjestäjä",
                    "translatedCaption": "Kod Utbildningsanordnare",
                    "translatedDisplayFolder": "Kodvariabler"
                  },
                  {
                    "name": "Koodit Koulutusohjelma",
                    "translatedCaption": "Kod Utbildningsprogram",
                    "translatedDisplayFolder": "Kodvariabler"
                  },
                  {
                    "name": "Koodit Koulutusnimike",
                    "translatedCaption": "Kod Utbildningsbenämning",
                    "translatedDisplayFolder": "Kodvariabler"
                  },
                  {
                    "name": "Koodit Koulutuksen maakunta",
                    "translatedCaption": "Kod Utbildningens landskap",
                    "translatedDisplayFolder": "Kodvariabler"
                  },
                  {
                    "name": "Koodit Koulutuksen kunta",
                    "translatedCaption": "Kod Utbildningens kommun",
                    "translatedDisplayFolder": "Kodvariabler"
                  },
                  {
                    "name": "Koodit Maakunta",
                    "translatedCaption": "Kod Lanskap",
                    "translatedDisplayFolder": "Kodvariabler"
                  },
                  {
                    "name": "Koodit Kunta",
                    "translatedCaption": "Kod Kommun",
                    "translatedDisplayFolder": "Kodvariabler"
                  },
                  {
                    "name": "Koodit Koul järj maakunta",
                    "translatedCaption": "Kod Utb.anordnarens landskap",
                    "translatedDisplayFolder": "Kodvariabler"
                  },
                  {
                    "name": "Koodit Koul järj kunta",
                    "translatedCaption": "Kod Utb.anordnarens kommun",
                    "translatedDisplayFolder": "Kodvariabler"
                  },
                  {
                    "name": "Koodit Oppil maakunta",
                    "translatedCaption": "Kod Läroanstaltens lanskap",
                    "translatedDisplayFolder": "Kodvariabler"
                  },
                  {
                    "name": "Koodit Oppil kunta",
                    "translatedCaption": "Kod Läroanstaltens kommun",
                    "translatedDisplayFolder": "Kodvariabler"
                  },
                  {
                    "name": "Koodit Koulutusaste taso 1",
                    "translatedCaption": "Kod Utbildningsnivå, nivå 1",
                    "translatedDisplayFolder": "Kodvariabler"
                  },
                  {
                    "name": "Koodit Koulutusaste taso 2",
                    "translatedCaption": "Kod Utbildningsnivå, nivå 2",
                    "translatedDisplayFolder": "Kodvariabler"
                  },
                  {
                    "name": "Koodit Koulutusala taso 1",
                    "translatedCaption": "Kod Utbildningsområde, nivå 1",
                    "translatedDisplayFolder": "Kodvariabler"
                  },
                  {
                    "name": "Koodit Koulutusala taso 2",
                    "translatedCaption": "Kod Utbildningsområde, nivå 2",
                    "translatedDisplayFolder": "Kodvariabler"
                  },
                  {
                    "name": "Koodit Koulutusala taso 3",
                    "translatedCaption": "Kod Utbildningsområde, nivå 3",
                    "translatedDisplayFolder": "Kodvariabler"
                  },
                  {
                    "name": "Koodit OKM ohjauksen ala korkeak",
                    "translatedCaption": "Kod UKM-styrningsområde",
                    "translatedDisplayFolder": "Kodvariabler"
                  },
                  {
                    "name": "Koodit Koulutusaste (2002)",
                    "translatedCaption": "Kod Utbildningsnivå 2002",
                    "translatedDisplayFolder": "Kodvariabler"
                  },
                  {
                    "name": "Koodit Koulutusala (2002)",
                    "translatedCaption": "Kod Utbildningsområde 2002",
                    "translatedDisplayFolder": "Kodvariabler"
                  },
                  {
                    "name": "Koodit Koulutusala (1995)",
                    "translatedCaption": "Kod Utbildningsområde 1995",
                    "translatedDisplayFolder": "Kodvariabler"
                  },
                  {
                    "name": "Koodit Opintoala (2002)",
                    "translatedCaption": "Kod Studieområde 2002",
                    "translatedDisplayFolder": "Kodvariabler"
                  }
                ]
              }
            ]
          }
        }
      },
      {
        "name": "en-US",
        "translations": {
          "model": {
            "name": "Model",
            "tables": [
              {
                "name": "Muuttujat",
                "translatedCaption": "Variables",
                "columns": [
                  {
                    "name": "Koodit Asuinmaakunta",
                    "translatedCaption": "Codes Region of residence",
                    "translatedDisplayFolder": "Code variables"
                  },
                  {
                    "name": "Koodit Asuinkunta",
                    "translatedCaption": "Codes Municipality of residence",
                    "translatedDisplayFolder": "Code variables"
                  },
                  {
                    "name": "Koodit Tutkinto amk",
                    "translatedCaption": "Codes Degree (UAS)",
                    "translatedDisplayFolder": "Code variables"
                  },
                  {
                    "name": "Koodit Tutkinto yo",
                    "translatedCaption": "Codes Degree (university)",
                    "translatedDisplayFolder": "Code variables"
                  },
                  {
                    "name": "Koodit Koulutustyyppi",
                    "translatedCaption": "Codes Type of education",
                    "translatedDisplayFolder": "Code variables"
                  },
                  {
                    "name": "Koodit Oppilaitos",
                    "translatedCaption": "Codes Educational institution",
                    "translatedDisplayFolder": "Code variables"
                  },
                  {
                    "name": "Koodit Koulutuksen järjestäjä",
                    "translatedCaption": "Codes Education provider",
                    "translatedDisplayFolder": "Code variables"
                  },
                  {
                    "name": "Koodit Koulutusohjelma",
                    "translatedCaption": "Codes Degree programme",
                    "translatedDisplayFolder": "Code variables"
                  },
                  {
                    "name": "Koodit Koulutusnimike",
                    "translatedCaption": "Codes Name of education",
                    "translatedDisplayFolder": "Code variables"
                  },
                  {
                    "name": "Koodit Koulutuksen maakunta",
                    "translatedCaption": "Codes Region of education",
                    "translatedDisplayFolder": "Code variables"
                  },
                  {
                    "name": "Koodit Koulutuksen kunta",
                    "translatedCaption": "Codes Municipality of education",
                    "translatedDisplayFolder": "Code variables"
                  },
                  {
                    "name": "Koodit Maakunta",
                    "translatedCaption": "Codes Region",
                    "translatedDisplayFolder": "Code variables"
                  },
                  {
                    "name": "Koodit Kunta",
                    "translatedCaption": "Codes Municipality",
                    "translatedDisplayFolder": "Code variables"
                  },
                  {
                    "name": "Koodit Koul järj maakunta",
                    "translatedCaption": "Codes Region of education provider",
                    "translatedDisplayFolder": "Code variables"
                  },
                  {
                    "name": "Koodit Koul järj kunta",
                    "translatedCaption": "Codes Municipality of education provider",
                    "translatedDisplayFolder": "Code variables"
                  },
                  {
                    "name": "Koodit Oppil maakunta",
                    "translatedCaption": "Codes Region of ed. institution",
                    "translatedDisplayFolder": "Code variables"
                  },
                  {
                    "name": "Koodit Oppil kunta",
                    "translatedCaption": "Codes Municipality of ed. institution",
                    "translatedDisplayFolder": "Code variables"
                  },
                  {
                    "name": "Koodit Koulutusaste taso 1",
                    "translatedCaption": "Codes Level of education, tier 1",
                    "translatedDisplayFolder": "Code variables"
                  },
                  {
                    "name": "Koodit Koulutusaste taso 2",
                    "translatedCaption": "Codes Level of education, tier 2",
                    "translatedDisplayFolder": "Code variables"
                  },
                  {
                    "name": "Koodit Koulutusala taso 1",
                    "translatedCaption": "Codes Field of education, tier 1",
                    "translatedDisplayFolder": "Code variables"
                  },
                  {
                    "name": "Koodit Koulutusala taso 2",
                    "translatedCaption": "Codes Field of education, tier 2",
                    "translatedDisplayFolder": "Code variables"
                  },
                  {
                    "name": "Koodit Koulutusala taso 3",
                    "translatedCaption": "Codes Field of education, tier 3",
                    "translatedDisplayFolder": "Code variables"
                  },
                  {
                    "name": "Koodit OKM ohjauksen ala korkeak",
                    "translatedCaption": "Codes Field of ed. HE steering",
                    "translatedDisplayFolder": "Code variables"
                  },
                  {
                    "name": "Koodit Koulutusaste (2002)",
                    "translatedCaption": "Codes Level of education 2002",
                    "translatedDisplayFolder": "Code variables"
                  },
                  {
                    "name": "Koodit Koulutusala (2002)",
                    "translatedCaption": "Codes Field of education 2002",
                    "translatedDisplayFolder": "Code variables"
                  },
                  {
                    "name": "Koodit Koulutusala (1995)",
                    "translatedCaption": "Codes Field of education 1995",
                    "translatedDisplayFolder": "Code variables"
                  },
                  {
                    "name": "Koodit Opintoala (2002)",
                    "translatedCaption": "Codes Subfield of education 2002",
                    "translatedDisplayFolder": "Code variables"
                  }
                ]
              }
            ]
          }
        }
      }
    ],
    "perspectives": [
      {
        "name": "Analyysi",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Koodit Koulutusala taso 2"
              },
              {
                "name": "Koulutusala, taso 2"
              },
              {
                "name": "Asuinmaakunta"
              },
              {
                "name": "Koulutustyyppi"
              },
              {
                "name": "Ikä"
              },
              {
                "name": "Kirjoihintulovuosi opala"
              },
              {
                "name": "Ensisijainen opinto-oikeus"
              },
              {
                "name": "Kirjoihintulovuosi kk-sek"
              },
              {
                "name": "Koulutussektori"
              },
              {
                "name": "Syntymävuosi"
              },
              {
                "name": "Til.v:tta ed. asuinmaakunta"
              },
              {
                "name": "Kirjoihintulovuosi sek läsnä"
              },
              {
                "name": "Koodit OKM ohjauksen ala korkeak"
              },
              {
                "name": "Äidinkieli"
              },
              {
                "name": "Kirjoihintulovuosi kk-sek läsna"
              },
              {
                "name": "Koodit Koulutusala taso 3"
              },
              {
                "name": "Koodit Koulutusaste taso 1"
              },
              {
                "name": "Koulutusala, taso 3"
              },
              {
                "name": "Koulutusaste, taso 1"
              },
              {
                "name": "Koodit Koulutusohjelma"
              },
              {
                "name": "Koodit Oppilaitos"
              },
              {
                "name": "Kirjoihintulovuosi tutk"
              },
              {
                "name": "Kirjoillaolo (syys)"
              },
              {
                "name": "Koodit Asuinkunta"
              },
              {
                "name": "Koodit Koulutuksen kunta"
              },
              {
                "name": "Koodit Koulutustyyppi"
              },
              {
                "name": "Kirjoihintulovuosi"
              },
              {
                "name": "Koulutusnimike"
              },
              {
                "name": "Oppilaitos"
              },
              {
                "name": "Kirjoihintulovuosi opala läsnä"
              },
              {
                "name": "Koodit Koulutusala taso 1"
              },
              {
                "name": "Asuinkunta"
              },
              {
                "name": "Koulutuksen maakunta"
              },
              {
                "name": "Til.v:tta ed. asuinkunta"
              },
              {
                "name": "Tutkinto (yo)"
              },
              {
                "name": "Koulutusala, taso 1"
              },
              {
                "name": "Koulutusohjelma"
              },
              {
                "name": "Rahoituslähde"
              },
              {
                "name": "Tutkinto (amk)"
              },
              {
                "name": "Ikäryhmä"
              },
              {
                "name": "Koodit Koulutusaste taso 2"
              },
              {
                "name": "Koulutusaste, taso 2"
              },
              {
                "name": "OKM ohjauksen ala korkeak."
              },
              {
                "name": "Koodit Asuinmaakunta"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Koodit Koulutuksen maakunta"
              },
              {
                "name": "Koulutuksen kunta"
              },
              {
                "name": "Koulutuslaji"
              },
              {
                "name": "Sukupuoli"
              },
              {
                "name": "Kirjoihintulovuosi kk läsnä"
              },
              {
                "name": "Kirjoihintulovuosi kk"
              },
              {
                "name": "Kansalaisuus"
              },
              {
                "name": "Koodit Koulutusnimike"
              },
              {
                "name": "Kirjoihintulovuosi sek"
              },
              {
                "name": "Kirjoillaolo (tammi)"
              },
              {
                "name": "Oppilaitos (tilastovuosi)"
              },
              {
                "name": "Koodit Koulutusala (2002)"
              },
              {
                "name": "Koulutusala (1995) "
              },
              {
                "name": "Koodit Koulutusaste (2002)"
              },
              {
                "name": "Koodit Opintoala (2002)"
              },
              {
                "name": "Koulutusala (2002) "
              },
              {
                "name": "Koulutusaste (2002) "
              },
              {
                "name": "Koodit Koulutusala (1995)"
              },
              {
                "name": "Opintoala (2002) "
              },
              {
                "name": "Kansainvälinen opiskelija"
              },
              {
                "name": "Liikkuvuuden kesto"
              }
            ],
            "measures": [
              {
                "name": "75-89 op suorittaneet"
              },
              {
                "name": "90-104 op suorittaneet"
              },
              {
                "name": "Opiskelijat FTE"
              },
              {
                "name": "Yli 55 op suorittaneiden osuus (kirjoihintulovuosi eri kuin tilastovuosi)"
              },
              {
                "name": "105-119 op suorittaneet"
              },
              {
                "name": "60-74 op suorittaneet"
              },
              {
                "name": "Aloittaneet (sektori)"
              },
              {
                "name": "1-14 op suorittaneet"
              },
              {
                "name": "Aloittaneet (korkeakoulu läsnäoleva)"
              },
              {
                "name": "Aloittaneet (korkeakoulu)"
              },
              {
                "name": "Opiskelijat (läsnä)"
              },
              {
                "name": "45-59 op suorittaneet"
              },
              {
                "name": "Opiskelijat"
              },
              {
                "name": "Ulkomaalaisten opiskelijoiden suorittamat tutkinnot"
              },
              {
                "name": "Yli 55 op suorittaneiden osuus (amk, kirjoihintulovuosi eri kuin tilastovuosi)"
              },
              {
                "name": "Aloittaneet (kirjoihintulovuosi)"
              },
              {
                "name": "Aloittaneet (opintoala läsnäoleva)"
              },
              {
                "name": "Aloittaneet (sektori läsnäoleva)"
              },
              {
                "name": "Uudet ulkomaalaiset opiskelijat"
              },
              {
                "name": "Yli 120 op suorittaneet"
              },
              {
                "name": "30-44 op suorittaneet"
              },
              {
                "name": "Amk opiskelijat (kirjoihintulovuosi eri kuin tilastovuosi)"
              },
              {
                "name": "Yli 55 op suorittaneet (kirjoihintulovuosi eri kuin tilastovuosi)"
              },
              {
                "name": "Aloittaneet (TK määritelmä)"
              },
              {
                "name": "0 op suorittaneet (ml. poissaolevat, kirjoihintulovuosi eri kuin tilastovuosi)"
              },
              {
                "name": "Alemman ja ylemmän kk-tutkinnon opiskelijat (kirjoihintulovuosi eri kuin tilastovuosi)"
              },
              {
                "name": "Aloittaneet (opintoala)"
              },
              {
                "name": "Ulkomaalaiset opiskelijat"
              },
              {
                "name": "Ulkomaalaiset opiskelijat FTE"
              },
              {
                "name": "15-29 op suorittaneet"
              },
              {
                "name": "Yli 55 op suorittaneet (amk, kirjoihintulovuosi eri kuin tilastovuosi)"
              },
              {
                "name": "Aloittaneet (korkeakoulusektori läsnäoleva)"
              },
              {
                "name": "Aloittaneet (korkeakoulusektori)"
              },
              {
                "name": "Tutkinnot"
              },
              {
                "name": "Uudet opiskelijat"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Ulkomaalaiset",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Koodit Koulutusnimike"
              },
              {
                "name": "Koodit Koulutusala taso 2"
              },
              {
                "name": "Koulutusala, taso 2"
              },
              {
                "name": "Asuinmaakunta"
              },
              {
                "name": "Koulutustyyppi"
              },
              {
                "name": "Ikä"
              },
              {
                "name": "Koulutussektori"
              },
              {
                "name": "Syntymävuosi"
              },
              {
                "name": "Koodit OKM ohjauksen ala korkeak"
              },
              {
                "name": "Koodit Koulutuksen maakunta"
              },
              {
                "name": "Koulutuksen kunta"
              },
              {
                "name": "Koulutuslaji"
              },
              {
                "name": "Sukupuoli"
              },
              {
                "name": "Koodit Koulutusala taso 3"
              },
              {
                "name": "Koodit Koulutusaste taso 1"
              },
              {
                "name": "Koulutusala, taso 3"
              },
              {
                "name": "Koulutusaste, taso 1"
              },
              {
                "name": "Koodit Koulutusohjelma"
              },
              {
                "name": "Koodit Oppilaitos"
              },
              {
                "name": "Kirjoillaolo (syys)"
              },
              {
                "name": "Koodit Asuinkunta"
              },
              {
                "name": "Koodit Koulutuksen kunta"
              },
              {
                "name": "Koodit Koulutustyyppi"
              },
              {
                "name": "Koulutusnimike"
              },
              {
                "name": "Oppilaitos"
              },
              {
                "name": "Koodit Koulutusala taso 1"
              },
              {
                "name": "Asuinkunta"
              },
              {
                "name": "Koulutuksen maakunta"
              },
              {
                "name": "Koulutusala, taso 1"
              },
              {
                "name": "Koulutusohjelma"
              },
              {
                "name": "Ikäryhmä"
              },
              {
                "name": "Koodit Koulutusaste taso 2"
              },
              {
                "name": "Koulutusaste, taso 2"
              },
              {
                "name": "OKM ohjauksen ala korkeak."
              },
              {
                "name": "Koodit Asuinmaakunta"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Kirjoillaolo (tammi)"
              },
              {
                "name": "Kansalaisuus"
              },
              {
                "name": "Oppilaitos (tilastovuosi)"
              },
              {
                "name": "Koodit Koulutusala (1995)"
              },
              {
                "name": "Opintoala (2002) "
              },
              {
                "name": "Koodit Koulutusala (2002)"
              },
              {
                "name": "Koulutusala (1995) "
              },
              {
                "name": "Koodit Koulutusaste (2002)"
              },
              {
                "name": "Koodit Opintoala (2002)"
              },
              {
                "name": "Koulutusala (2002) "
              },
              {
                "name": "Koulutusaste (2002) "
              },
              {
                "name": "Kansainvälinen opiskelija"
              }
            ],
            "measures": [
              {
                "name": "Uudet ulkomaalaiset opiskelijat"
              },
              {
                "name": "Ulkomaalaiset opiskelijat"
              },
              {
                "name": "Ulkomaalaiset opiskelijat FTE"
              },
              {
                "name": "Ulkomaalaisten opiskelijoiden suorittamat tutkinnot"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Indikaattori 1",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Äidinkieli (suomi/muu)"
              },
              {
                "name": "Kansalaisuus (suomi/muu)"
              },
              {
                "name": "Koodit Maakunta"
              },
              {
                "name": "Maakunta"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Sukupuoli"
              },
              {
                "name": "Koodit Kunta"
              },
              {
                "name": "Kunta"
              },
              {
                "name": "Kansainvälinen opiskelija"
              }
            ],
            "measures": [
              {
                "name": "20-24 vuotiaiden keskimääräinen ikäluokka"
              },
              {
                "name": "25-34 vuotiaiden keskimääräinen ikäluokka"
              },
              {
                "name": "Ammattikorkeak. aikuiskoulutuksen uudet opiskelijat / 25-64 vuotiaiden keskimääräinen ikäluokka"
              },
              {
                "name": "Ammattikorkeakoulujen nuorten koulutuksen uudet opiskelijat"
              },
              {
                "name": "Ylemmän ammattikorkeakoulututkinnon uudet opiskelijat / 25-64 vuotiaiden keskimääräinen ikäluokka"
              },
              {
                "name": "25-64 vuotiaiden keskimääräinen ikäluokka"
              },
              {
                "name": "Alemman ja ylemmän korkeakoulututk. uudet opiskelijat / 19-21 vuotiaiden keskimääräinen ikäluokka"
              },
              {
                "name": "Alemman ja ylemmän korkeakoulututkinnon uudet opiskelijat"
              },
              {
                "name": "Ylemmän ammattikorkeakoulututkinnon uudet opiskelijat"
              },
              {
                "name": "19-21 vuotiaiden keskimääräinen ikäluokka"
              },
              {
                "name": "Ammattikorkeak. nuorten koulutuksen uudet opiskelijat / 19-21 vuotiaiden keskimääräinen ikäluokka"
              },
              {
                "name": "Ammattikorkeakoulujen aikuiskoulutuksen uudet opiskelijat"
              }
            ]
          }
        ]
      },
      {
        "name": "AnalyysiSV",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Koodit Koulutusala taso 2"
              },
              {
                "name": "Utbildn.område, nivå 2"
              },
              {
                "name": "Koodit Koulutusnimike"
              },
              {
                "name": "Läroanstalt"
              },
              {
                "name": "Koodit Tutkinto yo"
              },
              {
                "name": "UKM-styrningsområde högskolor"
              },
              {
                "name": "Utbildningssektor"
              },
              {
                "name": "Åldersgrupp"
              },
              {
                "name": "Utbildn.nivå, nivå 2"
              },
              {
                "name": "Koodit OKM ohjauksen ala korkeak"
              },
              {
                "name": "Medborgarskap"
              },
              {
                "name": "Utbildningsslag"
              },
              {
                "name": "Finansieringskälla"
              },
              {
                "name": "Koodit Koulutusala taso 3"
              },
              {
                "name": "Koodit Koulutusaste taso 1"
              },
              {
                "name": "Typ av utbildning"
              },
              {
                "name": "Utbildn.område, nivå 3"
              },
              {
                "name": "Utbildningens landskap"
              },
              {
                "name": "Utbildningsbenämning"
              },
              {
                "name": "Koodit Koulutusohjelma"
              },
              {
                "name": "Kön"
              },
              {
                "name": "Koodit Asuinkunta"
              },
              {
                "name": "Koodit Koulutuksen kunta"
              },
              {
                "name": "Koodit Koulutustyyppi"
              },
              {
                "name": "Koodit Koulutusala taso 1"
              },
              {
                "name": "Statistikår"
              },
              {
                "name": "Utbildn.område, nivå 1"
              },
              {
                "name": "Bostadslandskap"
              },
              {
                "name": "Koodit Tutkinto amk"
              },
              {
                "name": "Ålder"
              },
              {
                "name": "Examen (universitet)"
              },
              {
                "name": "Examen (yrkehögskola)"
              },
              {
                "name": "Födelseår"
              },
              {
                "name": "Koodit Koulutusaste taso 2"
              },
              {
                "name": "Bostadskommun"
              },
              {
                "name": "Koodit Asuinmaakunta"
              },
              {
                "name": "Utbildn.nivå, nivå 1"
              },
              {
                "name": "Utbildningens kommun"
              },
              {
                "name": "Utbildningsprogram"
              },
              {
                "name": "Koodit Koulutuksen maakunta"
              },
              {
                "name": "Modersmål"
              },
              {
                "name": "Inskrivning (januari)"
              },
              {
                "name": "Koodit Koulutusala (1995)"
              },
              {
                "name": "Studieområde (2002) "
              },
              {
                "name": "Koodit Koulutusala (2002)"
              },
              {
                "name": "Utbildningsområde (1995) "
              },
              {
                "name": "Koodit Koulutusaste (2002)"
              },
              {
                "name": "Koodit Opintoala (2002)"
              },
              {
                "name": "Utbildningsområde (2002) "
              },
              {
                "name": "Utbildningsnivå (2002) "
              },
              {
                "name": "Mobilitetens längd"
              }
            ],
            "measures": [
              {
                "name": "105-119 sp"
              },
              {
                "name": "Studenter FTE"
              },
              {
                "name": "15-29 sp"
              },
              {
                "name": "Studenter som avlagt mer än 55 sp"
              },
              {
                "name": "Över 120 sp"
              },
              {
                "name": "Nya studenter"
              },
              {
                "name": "Utländska studenter"
              },
              {
                "name": "Utländska studenter FTE"
              },
              {
                "name": "60-74 sp"
              },
              {
                "name": "Examina"
              },
              {
                "name": "Studenter som avlagt mer än 55 sp (yrkehögskola)"
              },
              {
                "name": "75-89 sp"
              },
              {
                "name": "Andel som avlagt mer än 55 sp"
              },
              {
                "name": "Andel som avlagt mer än 55 sp (yrkehögskola)"
              },
              {
                "name": "Nybörjare inskrivningår studieområde"
              },
              {
                "name": "Studenter (närvarande)"
              },
              {
                "name": "Studenter i lägre och högre högskoleexamen"
              },
              {
                "name": "Nybörjare inskrivningår"
              },
              {
                "name": "Nybörjare inskrivningår sektor närvarande"
              },
              {
                "name": "Studenter"
              },
              {
                "name": "30-44 sp"
              },
              {
                "name": "45-59 sp"
              },
              {
                "name": "Nybörjare inskrivningår högskolen"
              },
              {
                "name": "Nybörjare inskrivningår högskolen närvarande"
              },
              {
                "name": "Nybörjare inskrivningår sektor"
              },
              {
                "name": "Nybörjare (Statistikcentralens definition)"
              },
              {
                "name": "0 sp"
              },
              {
                "name": "1-14 sp"
              },
              {
                "name": "Nya utländska studenter"
              },
              {
                "name": "Yrkehögskolestudenter"
              },
              {
                "name": "Nybörjare inskrivningår studieområde närvarande"
              },
              {
                "name": "Examina som avlagts av utländska studenter"
              },
              {
                "name": "90-104 sp"
              },
              {
                "name": "Nybörjare inskrivningår i högskolsektor"
              },
              {
                "name": "Nybörjare inskrivningår i högskolsektor närvarande"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "UlkomaalaisetSV",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Koodit Koulutusala taso 2"
              },
              {
                "name": "Koodit Koulutusnimike"
              },
              {
                "name": "Utbildn.område, nivå 2"
              },
              {
                "name": "Läroanstalt"
              },
              {
                "name": "Koodit Tutkinto yo"
              },
              {
                "name": "UKM-styrningsområde högskolor"
              },
              {
                "name": "Utbildningssektor"
              },
              {
                "name": "Åldersgrupp"
              },
              {
                "name": "Utbildn.nivå, nivå 2"
              },
              {
                "name": "Koodit OKM ohjauksen ala korkeak"
              },
              {
                "name": "Utbildningsslag"
              },
              {
                "name": "Koodit Koulutusala taso 3"
              },
              {
                "name": "Koodit Koulutusaste taso 1"
              },
              {
                "name": "Typ av utbildning"
              },
              {
                "name": "Utbildn.område, nivå 3"
              },
              {
                "name": "Utbildningens landskap"
              },
              {
                "name": "Utbildningsbenämning"
              },
              {
                "name": "Koodit Koulutusohjelma"
              },
              {
                "name": "Kön"
              },
              {
                "name": "Inskrivning (januari)"
              },
              {
                "name": "Koodit Asuinkunta"
              },
              {
                "name": "Koodit Koulutuksen kunta"
              },
              {
                "name": "Koodit Koulutustyyppi"
              },
              {
                "name": "Koodit Koulutusala taso 1"
              },
              {
                "name": "Statistikår"
              },
              {
                "name": "Utbildn.område, nivå 1"
              },
              {
                "name": "Bostadslandskap"
              },
              {
                "name": "Koodit Tutkinto amk"
              },
              {
                "name": "Ålder"
              },
              {
                "name": "Födelseår"
              },
              {
                "name": "Koodit Koulutusaste taso 2"
              },
              {
                "name": "Bostadskommun"
              },
              {
                "name": "Koodit Asuinmaakunta"
              },
              {
                "name": "Utbildn.nivå, nivå 1"
              },
              {
                "name": "Utbildningens kommun"
              },
              {
                "name": "Utbildningsprogram"
              },
              {
                "name": "Koodit Koulutuksen maakunta"
              },
              {
                "name": "Modersmål"
              },
              {
                "name": "Koodit Koulutusala (1995)"
              },
              {
                "name": "Studieområde (2002) "
              },
              {
                "name": "Koodit Koulutusala (2002)"
              },
              {
                "name": "Utbildningsområde (1995) "
              },
              {
                "name": "Koodit Koulutusaste (2002)"
              },
              {
                "name": "Koodit Opintoala (2002)"
              },
              {
                "name": "Utbildningsområde (2002) "
              },
              {
                "name": "Utbildningsnivå (2002) "
              }
            ],
            "measures": [
              {
                "name": "Examina som avlagts av utländska studenter"
              },
              {
                "name": "Utländska studenter"
              },
              {
                "name": "Utländska studenter FTE"
              },
              {
                "name": "Nya utländska studenter"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "AnalyysiEN",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Agegroup"
              },
              {
                "name": "Koodit Koulutusala taso 2"
              },
              {
                "name": "Name of education"
              },
              {
                "name": "Region of education"
              },
              {
                "name": "Degree programme"
              },
              {
                "name": "Field of education, tier 3"
              },
              {
                "name": "Degree (university)"
              },
              {
                "name": "Koodit Tutkinto yo"
              },
              {
                "name": "Sector of education"
              },
              {
                "name": "Year of birth"
              },
              {
                "name": "Year of enrollment HE sec"
              },
              {
                "name": "Age"
              },
              {
                "name": "Field of education, tier 1"
              },
              {
                "name": "Form of education"
              },
              {
                "name": "Koodit OKM ohjauksen ala korkeak"
              },
              {
                "name": "Year of enrollment ed inst present"
              },
              {
                "name": "Koodit Koulutusala taso 3"
              },
              {
                "name": "Koodit Koulutusaste taso 1"
              },
              {
                "name": "Municipality of residence"
              },
              {
                "name": "Year of enrollment sec"
              },
              {
                "name": "Koodit Koulutusohjelma"
              },
              {
                "name": "Koodit Asuinkunta"
              },
              {
                "name": "Koodit Koulutuksen kunta"
              },
              {
                "name": "Koodit Koulutustyyppi"
              },
              {
                "name": "Year of enrollment ed inst"
              },
              {
                "name": "Educational institution"
              },
              {
                "name": "Koodit Koulutusala taso 1"
              },
              {
                "name": "Level of ed., tier 1"
              },
              {
                "name": "Type of education"
              },
              {
                "name": "Statistical year"
              },
              {
                "name": "Field of education, tier 2"
              },
              {
                "name": "Koodit Tutkinto amk"
              },
              {
                "name": "Source of funding"
              },
              {
                "name": "Degree (polytechnic)"
              },
              {
                "name": "Koodit Koulutusaste taso 2"
              },
              {
                "name": "Year of enrollment"
              },
              {
                "name": "Year of enrollment subfield of ed present"
              },
              {
                "name": "Koodit Asuinmaakunta"
              },
              {
                "name": "Nationality"
              },
              {
                "name": "Year of enrollment sec present"
              },
              {
                "name": "Koodit Koulutuksen maakunta"
              },
              {
                "name": "Year of enrollment HE sec present"
              },
              {
                "name": "Year of enrollment subfield of ed"
              },
              {
                "name": "Enrollment status (sept.)"
              },
              {
                "name": "Year of enrollment degree"
              },
              {
                "name": "Koodit Koulutusnimike"
              },
              {
                "name": "Level of ed., tier 2"
              },
              {
                "name": "Field of ed. HE steering"
              },
              {
                "name": "Gender"
              },
              {
                "name": "Mother tongue"
              },
              {
                "name": "Municipality of education"
              },
              {
                "name": "Region of residence"
              },
              {
                "name": "Koodit Koulutusala (2002)"
              },
              {
                "name": "Koodit Koulutusaste (2002)"
              },
              {
                "name": "Koodit Opintoala (2002)"
              },
              {
                "name": "Field of education (1995) "
              },
              {
                "name": "Subfield of ed. (2002) "
              },
              {
                "name": "Field of education (2002) "
              },
              {
                "name": "Koodit Koulutusala (1995)"
              },
              {
                "name": "Level of education (2002) "
              },
              {
                "name": "Duration of mobility"
              }
            ],
            "measures": [
              {
                "name": "75-89 credits"
              },
              {
                "name": "45-59 credits"
              },
              {
                "name": "New students enrollment year in the institution present"
              },
              {
                "name": "1-14 credits"
              },
              {
                "name": "15-29 credits"
              },
              {
                "name": "New foreign students"
              },
              {
                "name": "Students who attained more than 55 credits (polytechnic)"
              },
              {
                "name": "90-104 credits"
              },
              {
                "name": "Degrees attained by foreign students"
              },
              {
                "name": "New students enrollment year in higher education sector present"
              },
              {
                "name": "New students enrollment year in subfield of education present"
              },
              {
                "name": "Over 120 credits"
              },
              {
                "name": "Polytechnic degree students"
              },
              {
                "name": "Students"
              },
              {
                "name": "105-119 credits"
              },
              {
                "name": "New students enrollment year in subfield of education"
              },
              {
                "name": "Percentage of students who attained more than 55 credits"
              },
              {
                "name": "0 credits"
              },
              {
                "name": "60-74 credits"
              },
              {
                "name": "Foreign students"
              },
              {
                "name": "New students enrollment year in higher education sector"
              },
              {
                "name": "New students"
              },
              {
                "name": "Percentage of students who attained more than 55 credits (polytechnic)"
              },
              {
                "name": "Students FTE"
              },
              {
                "name": "30-44 credits"
              },
              {
                "name": "Bachelor's and Master's degree students"
              },
              {
                "name": "Foreign students FTE"
              },
              {
                "name": "New students enrollment year"
              },
              {
                "name": "New students enrollment year in education sector present"
              },
              {
                "name": "New students enrollment year in the institution"
              },
              {
                "name": "Students (present)"
              },
              {
                "name": "Students who attained more than 55 credits"
              },
              {
                "name": "Degrees"
              },
              {
                "name": "New students enrollment year in education sector"
              },
              {
                "name": "New students (Statistic Finland's definition)"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "UlkomaalaisetEN",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Agegroup"
              },
              {
                "name": "Koodit Koulutusala taso 2"
              },
              {
                "name": "Koodit Koulutusnimike"
              },
              {
                "name": "Level of ed., tier 2"
              },
              {
                "name": "Name of education"
              },
              {
                "name": "Region of education"
              },
              {
                "name": "Degree programme"
              },
              {
                "name": "Field of education, tier 3"
              },
              {
                "name": "Degree (university)"
              },
              {
                "name": "Field of ed. HE steering"
              },
              {
                "name": "Gender"
              },
              {
                "name": "Koodit Tutkinto yo"
              },
              {
                "name": "Mother tongue"
              },
              {
                "name": "Municipality of education"
              },
              {
                "name": "Region of residence"
              },
              {
                "name": "Sector of education"
              },
              {
                "name": "Degree (polytechnic)"
              },
              {
                "name": "Koodit Koulutusaste taso 2"
              },
              {
                "name": "Age"
              },
              {
                "name": "Field of education, tier 1"
              },
              {
                "name": "Form of education"
              },
              {
                "name": "Koodit Asuinmaakunta"
              },
              {
                "name": "Koodit OKM ohjauksen ala korkeak"
              },
              {
                "name": "Koodit Koulutuksen maakunta"
              },
              {
                "name": "Koodit Koulutusala taso 3"
              },
              {
                "name": "Koodit Koulutusaste taso 1"
              },
              {
                "name": "Municipality of residence"
              },
              {
                "name": "Enrollment status (sept.)"
              },
              {
                "name": "Koodit Koulutusohjelma"
              },
              {
                "name": "Koodit Asuinkunta"
              },
              {
                "name": "Koodit Koulutuksen kunta"
              },
              {
                "name": "Koodit Koulutustyyppi"
              },
              {
                "name": "Educational institution"
              },
              {
                "name": "Koodit Koulutusala taso 1"
              },
              {
                "name": "Level of ed., tier 1"
              },
              {
                "name": "Type of education"
              },
              {
                "name": "Statistical year"
              },
              {
                "name": "Field of education, tier 2"
              },
              {
                "name": "Koodit Tutkinto amk"
              },
              {
                "name": "Koodit Koulutusala (1995)"
              },
              {
                "name": "Level of education (2002) "
              },
              {
                "name": "Koodit Koulutusala (2002)"
              },
              {
                "name": "Field of education (2002) "
              },
              {
                "name": "Koodit Koulutusaste (2002)"
              },
              {
                "name": "Koodit Opintoala (2002)"
              },
              {
                "name": "Field of education (1995) "
              },
              {
                "name": "Subfield of ed. (2002) "
              }
            ],
            "measures": [
              {
                "name": "Foreign students"
              },
              {
                "name": "New foreign students"
              },
              {
                "name": "Degrees attained by foreign students"
              },
              {
                "name": "Foreign students FTE"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Raportit",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Koodit Koulutusala taso 2"
              },
              {
                "name": "Koulutusala, taso 2"
              },
              {
                "name": "Asuinmaakunta"
              },
              {
                "name": "Koulutustyyppi"
              },
              {
                "name": "Ensisijainen opinto-oikeus"
              },
              {
                "name": "Ikä"
              },
              {
                "name": "Koulutussektori"
              },
              {
                "name": "Koodit OKM ohjauksen ala korkeak"
              },
              {
                "name": "Syntymävuosi"
              },
              {
                "name": "Til.v:tta ed. asuinmaakunta"
              },
              {
                "name": "Koodit Koulutusala taso 3"
              },
              {
                "name": "Koodit Koulutusaste taso 1"
              },
              {
                "name": "Koulutusala, taso 3"
              },
              {
                "name": "Koulutusaste, taso 1"
              },
              {
                "name": "Äidinkieli"
              },
              {
                "name": "Koodit Koulutusohjelma"
              },
              {
                "name": "Koodit Oppilaitos"
              },
              {
                "name": "Kirjoillaolo (syys)"
              },
              {
                "name": "Koodit Asuinkunta"
              },
              {
                "name": "Koodit Koulutuksen kunta"
              },
              {
                "name": "Koodit Koulutustyyppi"
              },
              {
                "name": "Koodit Koulutusala taso 1"
              },
              {
                "name": "Koulutusnimike"
              },
              {
                "name": "Oppilaitos"
              },
              {
                "name": "Asuinkunta"
              },
              {
                "name": "Koulutuksen maakunta"
              },
              {
                "name": "Koulutusala, taso 1"
              },
              {
                "name": "Til.v:tta ed. asuinkunta"
              },
              {
                "name": "Tutkinto (yo)"
              },
              {
                "name": "Koulutusohjelma"
              },
              {
                "name": "Rahoituslähde"
              },
              {
                "name": "Tutkinto (amk)"
              },
              {
                "name": "Ikäryhmä"
              },
              {
                "name": "Koodit Koulutusaste taso 2"
              },
              {
                "name": "Koulutusaste, taso 2"
              },
              {
                "name": "OKM ohjauksen ala korkeak."
              },
              {
                "name": "Koodit Asuinmaakunta"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Koodit Koulutuksen maakunta"
              },
              {
                "name": "Koulutuksen kunta"
              },
              {
                "name": "Koulutuslaji"
              },
              {
                "name": "Sukupuoli"
              },
              {
                "name": "Kansalaisuus"
              },
              {
                "name": "Koodit Koulutusnimike"
              },
              {
                "name": "Kirjoillaolo (tammi)"
              },
              {
                "name": "Oppilaitos (tilastovuosi)"
              },
              {
                "name": "Koodit Koulutusala (2002)"
              },
              {
                "name": "Koulutusala (1995) "
              },
              {
                "name": "Koodit Koulutusaste (2002)"
              },
              {
                "name": "Koodit Opintoala (2002)"
              },
              {
                "name": "Koulutusala (2002) "
              },
              {
                "name": "Koulutusaste (2002) "
              },
              {
                "name": "Koodit Koulutusala (1995)"
              },
              {
                "name": "Opintoala (2002) "
              },
              {
                "name": "Kansainvälinen opiskelija"
              }
            ],
            "measures": [
              {
                "name": "Aloittaneet (korkeakoulusektori läsnäoleva)"
              },
              {
                "name": "Opiskelijat FTE"
              },
              {
                "name": "Aloittaneet (opintoala läsnäoleva)"
              },
              {
                "name": "Aloittaneet (sektori läsnäoleva)"
              },
              {
                "name": "Aloittaneet (korkeakoulusektori)"
              },
              {
                "name": "Aloittaneet (sektori)"
              },
              {
                "name": "Aloittaneet (TK määritelmä)"
              },
              {
                "name": "Amk opiskelijat (kirjoihintulovuosi eri kuin tilastovuosi)"
              },
              {
                "name": "Tutkinnot"
              },
              {
                "name": "Uudet opiskelijat"
              },
              {
                "name": "Aloittaneet (korkeakoulu läsnäoleva)"
              },
              {
                "name": "Aloittaneet (korkeakoulu)"
              },
              {
                "name": "Aloittaneet (opintoala)"
              },
              {
                "name": "Opiskelijat (läsnä)"
              },
              {
                "name": "Opiskelijat"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "RaportitSV",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Koodit Koulutusala taso 2"
              },
              {
                "name": "Utbildn.område, nivå 2"
              },
              {
                "name": "Koodit Koulutusnimike"
              },
              {
                "name": "Läroanstalt"
              },
              {
                "name": "Koodit Tutkinto yo"
              },
              {
                "name": "UKM-styrningsområde högskolor"
              },
              {
                "name": "Utbildningssektor"
              },
              {
                "name": "Åldersgrupp"
              },
              {
                "name": "Utbildn.nivå, nivå 2"
              },
              {
                "name": "Koodit OKM ohjauksen ala korkeak"
              },
              {
                "name": "Medborgarskap"
              },
              {
                "name": "Utbildningsslag"
              },
              {
                "name": "Finansieringskälla"
              },
              {
                "name": "Koodit Koulutusala taso 3"
              },
              {
                "name": "Koodit Koulutusaste taso 1"
              },
              {
                "name": "Typ av utbildning"
              },
              {
                "name": "Utbildn.område, nivå 3"
              },
              {
                "name": "Utbildningens landskap"
              },
              {
                "name": "Utbildningsbenämning"
              },
              {
                "name": "Koodit Koulutusohjelma"
              },
              {
                "name": "Kön"
              },
              {
                "name": "Koodit Asuinkunta"
              },
              {
                "name": "Koodit Koulutuksen kunta"
              },
              {
                "name": "Koodit Koulutustyyppi"
              },
              {
                "name": "Koodit Koulutusala taso 1"
              },
              {
                "name": "Statistikår"
              },
              {
                "name": "Utbildn.område, nivå 1"
              },
              {
                "name": "Bostadslandskap"
              },
              {
                "name": "Koodit Tutkinto amk"
              },
              {
                "name": "Ålder"
              },
              {
                "name": "Examen (universitet)"
              },
              {
                "name": "Examen (yrkehögskola)"
              },
              {
                "name": "Födelseår"
              },
              {
                "name": "Koodit Koulutusaste taso 2"
              },
              {
                "name": "Bostadskommun"
              },
              {
                "name": "Koodit Asuinmaakunta"
              },
              {
                "name": "Utbildn.nivå, nivå 1"
              },
              {
                "name": "Utbildningens kommun"
              },
              {
                "name": "Utbildningsprogram"
              },
              {
                "name": "Koodit Koulutuksen maakunta"
              },
              {
                "name": "Modersmål"
              },
              {
                "name": "Inskrivning (januari)"
              },
              {
                "name": "Koodit Koulutusala (1995)"
              },
              {
                "name": "Studieområde (2002) "
              },
              {
                "name": "Koodit Koulutusala (2002)"
              },
              {
                "name": "Utbildningsområde (1995) "
              },
              {
                "name": "Koodit Koulutusaste (2002)"
              },
              {
                "name": "Koodit Opintoala (2002)"
              },
              {
                "name": "Utbildningsområde (2002) "
              },
              {
                "name": "Utbildningsnivå (2002) "
              }
            ],
            "measures": [
              {
                "name": "Nybörjare inskrivningår studieområde"
              },
              {
                "name": "Nybörjare inskrivningår studieområde närvarande"
              },
              {
                "name": "Studenter (närvarande)"
              },
              {
                "name": "Studenter FTE"
              },
              {
                "name": "Nybörjare inskrivningår sektor närvarande"
              },
              {
                "name": "Studenter"
              },
              {
                "name": "Nya studenter"
              },
              {
                "name": "Nybörjare (Statistikcentralens definition)"
              },
              {
                "name": "Nybörjare inskrivningår högskolen"
              },
              {
                "name": "Nybörjare inskrivningår högskolen närvarande"
              },
              {
                "name": "Nybörjare inskrivningår i högskolsektor"
              },
              {
                "name": "Nybörjare inskrivningår i högskolsektor närvarande"
              },
              {
                "name": "Nybörjare inskrivningår sektor"
              },
              {
                "name": "Examina"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "RaportitEN",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Agegroup"
              },
              {
                "name": "Koodit Koulutusala taso 2"
              },
              {
                "name": "Koodit Koulutusnimike"
              },
              {
                "name": "Level of ed., tier 2"
              },
              {
                "name": "Name of education"
              },
              {
                "name": "Region of education"
              },
              {
                "name": "Degree programme"
              },
              {
                "name": "Field of education, tier 3"
              },
              {
                "name": "Degree (university)"
              },
              {
                "name": "Field of ed. HE steering"
              },
              {
                "name": "Gender"
              },
              {
                "name": "Koodit Tutkinto yo"
              },
              {
                "name": "Mother tongue"
              },
              {
                "name": "Municipality of education"
              },
              {
                "name": "Region of residence"
              },
              {
                "name": "Sector of education"
              },
              {
                "name": "Year of birth"
              },
              {
                "name": "Age"
              },
              {
                "name": "Field of education, tier 1"
              },
              {
                "name": "Form of education"
              },
              {
                "name": "Koodit Asuinmaakunta"
              },
              {
                "name": "Koodit OKM ohjauksen ala korkeak"
              },
              {
                "name": "Nationality"
              },
              {
                "name": "Koodit Koulutuksen maakunta"
              },
              {
                "name": "Koodit Koulutusala taso 3"
              },
              {
                "name": "Koodit Koulutusaste taso 1"
              },
              {
                "name": "Municipality of residence"
              },
              {
                "name": "Enrollment status (sept.)"
              },
              {
                "name": "Koodit Koulutusohjelma"
              },
              {
                "name": "Koodit Asuinkunta"
              },
              {
                "name": "Koodit Koulutuksen kunta"
              },
              {
                "name": "Koodit Koulutustyyppi"
              },
              {
                "name": "Educational institution"
              },
              {
                "name": "Koodit Koulutusala taso 1"
              },
              {
                "name": "Level of ed., tier 1"
              },
              {
                "name": "Type of education"
              },
              {
                "name": "Statistical year"
              },
              {
                "name": "Field of education, tier 2"
              },
              {
                "name": "Koodit Tutkinto amk"
              },
              {
                "name": "Source of funding"
              },
              {
                "name": "Degree (polytechnic)"
              },
              {
                "name": "Koodit Koulutusaste taso 2"
              },
              {
                "name": "Koodit Koulutusala (1995)"
              },
              {
                "name": "Level of education (2002) "
              },
              {
                "name": "Koodit Koulutusala (2002)"
              },
              {
                "name": "Koodit Koulutusaste (2002)"
              },
              {
                "name": "Koodit Opintoala (2002)"
              },
              {
                "name": "Field of education (1995) "
              },
              {
                "name": "Subfield of ed. (2002) "
              },
              {
                "name": "Field of education (2002) "
              }
            ],
            "measures": [
              {
                "name": "Degrees"
              },
              {
                "name": "New students (Statistic Finland's definition)"
              },
              {
                "name": "New students enrollment year in education sector"
              },
              {
                "name": "New students enrollment year in higher education sector"
              },
              {
                "name": "New students enrollment year in the institution present"
              },
              {
                "name": "New students"
              },
              {
                "name": "Students FTE"
              },
              {
                "name": "New students enrollment year in education sector present"
              },
              {
                "name": "New students enrollment year in higher education sector present"
              },
              {
                "name": "New students enrollment year in subfield of education present"
              },
              {
                "name": "New students enrollment year in the institution"
              },
              {
                "name": "Students"
              },
              {
                "name": "Students (present)"
              },
              {
                "name": "New students enrollment year in subfield of education"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Opiskelijat_ja_tutkinnot",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Aineisto"
              },
              {
                "name": "Koodit Koulutusala taso 1"
              },
              {
                "name": "Koodit Koulutusala taso 2"
              },
              {
                "name": "Koodit Koulutusala taso 3"
              },
              {
                "name": "Koodit Koulutusaste taso 1"
              },
              {
                "name": "Koodit Koulutusaste taso 2"
              },
              {
                "name": "Koodit Koulutusnimike"
              },
              {
                "name": "Koodit OKM ohjauksen ala korkeak"
              },
              {
                "name": "Koodit Oppilaitos"
              },
              {
                "name": "Koulutusala, taso 1"
              },
              {
                "name": "Koulutusala, taso 2"
              },
              {
                "name": "Koulutusala, taso 3"
              },
              {
                "name": "Koulutusaste, taso 1"
              },
              {
                "name": "Koulutusaste, taso 2"
              },
              {
                "name": "Koulutusnimike"
              },
              {
                "name": "Koulutussektori"
              },
              {
                "name": "OKM ohjauksen ala korkeak."
              },
              {
                "name": "Oppilaitos"
              },
              {
                "name": "Rahoitusmallialat amk 2017-2020"
              },
              {
                "name": "Rahoitusmallialat amk 2021-2024"
              },
              {
                "name": "Rahoitusmallialat yo 2017-2020"
              },
              {
                "name": "Rahoitusmallialat yo 2021-2024"
              },
              {
                "name": "Rahoituslähde"
              },
              {
                "name": "Sukupuoli"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Oppilaitos (tilastovuosi)"
              },
              {
                "name": "Lähde"
              }
            ],
            "measures": [
              {
                "name": "Opiskelijat lkm_s"
              },
              {
                "name": "Tutkinnot lkm_s"
              },
              {
                "name": "Uudet opiskelijat lkm_s"
              },
              {
                "name": "Opiskelijat FTE lkm_s"
              }
            ]
          }
        ]
      },
      {
        "name": "Kansainväliset",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Asuinkunta"
              },
              {
                "name": "Asuinmaakunta"
              },
              {
                "name": "Ikä"
              },
              {
                "name": "Ikäryhmä"
              },
              {
                "name": "Kansalaisuus"
              },
              {
                "name": "Kirjoillaolo (syys)"
              },
              {
                "name": "Kirjoillaolo (tammi)"
              },
              {
                "name": "Koodit Asuinkunta"
              },
              {
                "name": "Koodit Asuinmaakunta"
              },
              {
                "name": "Koodit Koulutuksen kunta"
              },
              {
                "name": "Koodit Koulutuksen maakunta"
              },
              {
                "name": "Koodit Koulutusala (1995)"
              },
              {
                "name": "Koodit Koulutusala (2002)"
              },
              {
                "name": "Koodit Koulutusala taso 1"
              },
              {
                "name": "Koodit Koulutusala taso 2"
              },
              {
                "name": "Koodit Koulutusala taso 3"
              },
              {
                "name": "Koodit Koulutusaste (2002)"
              },
              {
                "name": "Koodit Koulutusaste taso 1"
              },
              {
                "name": "Koodit Koulutusaste taso 2"
              },
              {
                "name": "Koodit Koulutusnimike"
              },
              {
                "name": "Koodit Koulutusohjelma"
              },
              {
                "name": "Koodit Koulutustyyppi"
              },
              {
                "name": "Koodit OKM ohjauksen ala korkeak"
              },
              {
                "name": "Koodit Opintoala (2002)"
              },
              {
                "name": "Koodit Oppilaitos"
              },
              {
                "name": "Koulutuksen kunta"
              },
              {
                "name": "Koulutuksen maakunta"
              },
              {
                "name": "Koulutusala (1995) "
              },
              {
                "name": "Koulutusala (2002) "
              },
              {
                "name": "Koulutusala, taso 1"
              },
              {
                "name": "Koulutusala, taso 2"
              },
              {
                "name": "Koulutusala, taso 3"
              },
              {
                "name": "Koulutusaste (2002) "
              },
              {
                "name": "Koulutusaste, taso 1"
              },
              {
                "name": "Koulutusaste, taso 2"
              },
              {
                "name": "Koulutuslaji"
              },
              {
                "name": "Koulutusnimike"
              },
              {
                "name": "Koulutusohjelma"
              },
              {
                "name": "Koulutussektori"
              },
              {
                "name": "Koulutustyyppi"
              },
              {
                "name": "OKM ohjauksen ala korkeak."
              },
              {
                "name": "Opintoala (2002) "
              },
              {
                "name": "Oppilaitos"
              },
              {
                "name": "Oppilaitos (tilastovuosi)"
              },
              {
                "name": "Sukupuoli"
              },
              {
                "name": "Syntymävuosi"
              },
              {
                "name": "Tilastovuosi"
              }
            ],
            "measures": [
              {
                "name": "Uudet kansainväliset opiskelijat"
              },
              {
                "name": "Kansainväliset opiskelijat"
              },
              {
                "name": "Kansainväliset opiskelijat FTE"
              },
              {
                "name": "Kansainvälisten opiskelijoiden suorittamat tutkinnot"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Opiskelijat_ja_tutkinnot_kirjoihintulovuosi",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Aineisto"
              },
              {
                "name": "Kirjoihintulovuosi"
              },
              {
                "name": "Koodit Koulutusala taso 1"
              },
              {
                "name": "Koodit Koulutusala taso 2"
              },
              {
                "name": "Koodit Koulutusala taso 3"
              },
              {
                "name": "Koodit Koulutusaste taso 1"
              },
              {
                "name": "Koodit Koulutusaste taso 2"
              },
              {
                "name": "Koodit Koulutusnimike"
              },
              {
                "name": "Koodit OKM ohjauksen ala korkeak"
              },
              {
                "name": "Koodit Oppilaitos"
              },
              {
                "name": "Koulutusala, taso 1"
              },
              {
                "name": "Koulutusala, taso 2"
              },
              {
                "name": "Koulutusala, taso 3"
              },
              {
                "name": "Koulutusaste, taso 1"
              },
              {
                "name": "Koulutusaste, taso 2"
              },
              {
                "name": "Koulutusnimike"
              },
              {
                "name": "Koulutussektori"
              },
              {
                "name": "OKM ohjauksen ala korkeak."
              },
              {
                "name": "Oppilaitos"
              },
              {
                "name": "Oppilaitos (tilastovuosi)"
              },
              {
                "name": "Rahoitusmallialat amk 2017-2020"
              },
              {
                "name": "Rahoitusmallialat amk 2021-2024"
              },
              {
                "name": "Rahoitusmallialat yo 2017-2020"
              },
              {
                "name": "Rahoitusmallialat yo 2021-2024"
              },
              {
                "name": "Tilastovuosi"
              }
            ],
            "measures": [
              {
                "name": "Opiskelijat FTE lkm_s"
              },
              {
                "name": "Opiskelijat lkm_s"
              },
              {
                "name": "Tutkinnot lkm_s"
              },
              {
                "name": "Uudet opiskelijat lkm_s"
              }
            ]
          }
        ]
      },
      {
        "name": "Raportit ennakko",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Koodit Koulutusala taso 2"
              },
              {
                "name": "Koulutusala, taso 2"
              },
              {
                "name": "Asuinmaakunta"
              },
              {
                "name": "Koulutustyyppi"
              },
              {
                "name": "Ensisijainen opinto-oikeus"
              },
              {
                "name": "Ikä"
              },
              {
                "name": "Koulutussektori"
              },
              {
                "name": "Koodit OKM ohjauksen ala korkeak"
              },
              {
                "name": "Syntymävuosi"
              },
              {
                "name": "Til.v:tta ed. asuinmaakunta"
              },
              {
                "name": "Koodit Koulutusala taso 3"
              },
              {
                "name": "Koodit Koulutusaste taso 1"
              },
              {
                "name": "Koulutusala, taso 3"
              },
              {
                "name": "Koulutusaste, taso 1"
              },
              {
                "name": "Äidinkieli"
              },
              {
                "name": "Koodit Koulutusohjelma"
              },
              {
                "name": "Koodit Oppilaitos"
              },
              {
                "name": "Kirjoillaolo (syys)"
              },
              {
                "name": "Koodit Asuinkunta"
              },
              {
                "name": "Koodit Koulutuksen kunta"
              },
              {
                "name": "Koodit Koulutustyyppi"
              },
              {
                "name": "Koodit Koulutusala taso 1"
              },
              {
                "name": "Koulutusnimike"
              },
              {
                "name": "Oppilaitos"
              },
              {
                "name": "Asuinkunta"
              },
              {
                "name": "Koulutuksen maakunta"
              },
              {
                "name": "Koulutusala, taso 1"
              },
              {
                "name": "Til.v:tta ed. asuinkunta"
              },
              {
                "name": "Tutkinto (yo)"
              },
              {
                "name": "Koulutusohjelma"
              },
              {
                "name": "Rahoituslähde"
              },
              {
                "name": "Tutkinto (amk)"
              },
              {
                "name": "Ikäryhmä"
              },
              {
                "name": "Koodit Koulutusaste taso 2"
              },
              {
                "name": "Koulutusaste, taso 2"
              },
              {
                "name": "OKM ohjauksen ala korkeak."
              },
              {
                "name": "Koodit Asuinmaakunta"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Koodit Koulutuksen maakunta"
              },
              {
                "name": "Koulutuksen kunta"
              },
              {
                "name": "Koulutuslaji"
              },
              {
                "name": "Sukupuoli"
              },
              {
                "name": "Kansalaisuus (ennakko)"
              },
              {
                "name": "Koodit Koulutusnimike"
              },
              {
                "name": "Kirjoillaolo (tammi)"
              },
              {
                "name": "Oppilaitos (tilastovuosi)"
              },
              {
                "name": "Koodit Koulutusala (2002)"
              },
              {
                "name": "Koulutusala (1995) "
              },
              {
                "name": "Koodit Koulutusaste (2002)"
              },
              {
                "name": "Koodit Opintoala (2002)"
              },
              {
                "name": "Koulutusala (2002) "
              },
              {
                "name": "Koulutusaste (2002) "
              },
              {
                "name": "Koodit Koulutusala (1995)"
              },
              {
                "name": "Opintoala (2002) "
              },
              {
                "name": "Kansainvälinen opiskelija"
              }
            ],
            "measures": [
              {
                "name": "Aloittaneet (korkeakoulusektori läsnäoleva)"
              },
              {
                "name": "Opiskelijat FTE"
              },
              {
                "name": "Aloittaneet (opintoala läsnäoleva)"
              },
              {
                "name": "Aloittaneet (sektori läsnäoleva)"
              },
              {
                "name": "Aloittaneet (korkeakoulusektori)"
              },
              {
                "name": "Aloittaneet (sektori)"
              },
              {
                "name": "Aloittaneet (TK määritelmä)"
              },
              {
                "name": "Amk opiskelijat (kirjoihintulovuosi eri kuin tilastovuosi)"
              },
              {
                "name": "Tutkinnot"
              },
              {
                "name": "Uudet opiskelijat"
              },
              {
                "name": "Aloittaneet (korkeakoulu läsnäoleva)"
              },
              {
                "name": "Aloittaneet (korkeakoulu)"
              },
              {
                "name": "Aloittaneet (opintoala)"
              },
              {
                "name": "Opiskelijat (läsnä)"
              },
              {
                "name": "Opiskelijat"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Indikaattori_AMK",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "OKM ohjauksen ala korkeak."
              },
              {
                "name": "Oppilaitos"
              },
              {
                "name": "Rahoitusmallialat amk 2017-2020"
              },
              {
                "name": "Rahoitusmallialat amk 2021-2024"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Koulutusala, taso 1"
              },
              {
                "name": "Koulutusala, taso 2"
              },
              {
                "name": "Koulutusala, taso 3"
              },
              {
                "name": "Koodit Koulutusnimike"
              },
              {
                "name": "Koulutusnimike"
              }
            ],
            "measures": [
              {
                "name": "Aloittaneet (korkeakoulusektori)_s"
              }
            ]
          }
        ]
      },
      {
        "name": "Indikaattori_YO",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "OKM ohjauksen ala korkeak."
              },
              {
                "name": "Oppilaitos"
              },
              {
                "name": "Rahoitusmallialat yo 2017-2020"
              },
              {
                "name": "Rahoitusmallialat yo 2021-2024"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Koulutusala, taso 1"
              },
              {
                "name": "Koulutusala, taso 2"
              },
              {
                "name": "Koulutusala, taso 3"
              },
              {
                "name": "apusarake_yliopistojen_rahoitusmalli"
              },
              {
                "name": "Koodit Koulutusnimike"
              },
              {
                "name": "Koulutusnimike"
              }
            ],
            "measures": [
              {
                "name": "Aloittaneet (korkeakoulusektori)_s"
              }
            ]
          }
        ]
      }
    ],
    "roles": [
      {
        "name": "Luku",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "DWI\\T_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1732"
          },
          {
            "memberName": "DWI\\P_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1733"
          },
          {
            "memberName": "DWI\\Z_P_Antero_Read_TAB",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-4156"
          },
          {
            "memberName": "DWI\\Z_T_Antero_Read_TAB",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-4155"
          },
          {
            "memberName": "DWI\\Z_P_Antero_Full_Read_TAB",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-2272"
          }
        ]
      },
      {
        "name": "Kehitys",
        "modelPermission": "administrator",
        "members": [
          {
            "memberName": "DWI\\T_VIPU_TABOKM_DB_VipunenTK_Dev",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1364"
          },
          {
            "memberName": "DWI\\T_VIPU_TAB_DB_VipunenTK_Dev",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1363"
          },
          {
            "memberName": "DWI\\Z_P_Antero_Read_TAB",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-4156"
          },
          {
            "memberName": "DWI\\Z_T_Antero_Read_TAB",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-4155"
          }
        ]
      }
    ]
  },
  "id": "SemanticModel"
}