USE [VipunenTK_DW]
GO

/****** Object:  Table [dbo].[_koulutukseen_sijoittuneet_8v_tarkastelu]    Script Date: 22.10.2024 9:33:42 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[_koulutukseen_sijoittuneet_8v_tarkastelu]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[_koulutukseen_sijoittuneet_8v_tarkastelu](
	[rivinumero] [int] NOT NULL,
	[tarkastelujakso] [nvarchar](20) NOT NULL,
	[tilv] [nvarchar](4) NOT NULL,
	[tilv_date] [date] NULL,
	[tutkryh] [int] NOT NULL,
	[suorv] [nvarchar](4) NOT NULL,
	[suorlk] [nvarchar](6) NOT NULL,
	[sp] [int] NOT NULL,
	[syntv] [nvarchar](8) NOT NULL,
	[aikielir1] [nvarchar](2) NOT NULL,
	[tutkkaskun] [nvarchar](3) NOT NULL,
	[kansalr1] [int] NOT NULL,
	[pohjmaa] [int] NOT NULL,
	[eumaa] [int] NOT NULL,
	[etamaa] [int] NOT NULL,
	[tunn] [nvarchar](10) NOT NULL,
	[jarj] [nvarchar](10) NOT NULL,
	[kkielir1] [nvarchar](4) NOT NULL,
	[tutklaja] [int] NOT NULL,
	[tutktav] [int] NOT NULL,
	[aikoul] [int] NOT NULL,
	[tutkmaak] [nvarchar](2) NOT NULL,
	[koulutus_1] [nvarchar](6) NULL,
	[oppilaitos_1] [nvarchar](10) NULL,
	[koulutuksen_jarjestaja_1] [nvarchar](10) NULL,
	[koulutuksen_maakunta_1] [nvarchar](2) NULL,
	[koulutus_2] [nvarchar](6) NULL,
	[oppilaitos_2] [nvarchar](5) NULL,
	[koulutuksen_jarjestaja_2] [nvarchar](10) NULL,
	[koulutuksen_maakunta_2] [nvarchar](2) NULL,
	[monihaku] [int] NOT NULL,
	[paaasiallinen_toiminta] [int] NULL,
	[ammattiasema] [int] NULL,
	[lkm] [int] NOT NULL,
	[pohjkoulk] [nvarchar](6) NOT NULL,
	[tietolahde] [varchar](255) NOT NULL,
	[aineisto] [nvarchar](8) NOT NULL,
	[opintotuki_ulkom] [nvarchar](2) NOT NULL,
	[lukiokoulutuksessa] [int] NOT NULL,
	[ammatillisessa_koulutuksessa] [int] NOT NULL,
	[ammattikorkeakoulutuksessa] [int] NOT NULL,
	[yliopistokoulutuksessa] [int] NOT NULL,
	[lukiokoulutuksessa_ja_ammatillisessa_koulutuksessa] [int] NOT NULL,
	[toisen_asteen_ammatillisessa_koulutuksessa_ja_korkeakoulutuksessa] [int] NOT NULL,
	[ammattikorkeakoulutuksessa_ja_yliopistokoulutuksessa] [int] NOT NULL,
	[koulutuksen_paattaneiden_toiminta] [int] NOT NULL,
	[ika_1v] [nvarchar](10) NOT NULL,
	[ika_5v] [nvarchar](10) NOT NULL,
	[ika_1v_suorv] [nvarchar](10) NULL,
	[opisk_lu] [int] NULL,
	[opisk_amm_pk] [int] NULL,
	[opisk_amm_at] [int] NULL,
	[opisk_amm_eat] [int] NULL,
	[opisk_amm] [int] NULL,
	[opisk_amk] [int] NULL,
	[opisk_yo] [int] NULL,
	[opisk_amk_koulala1] [int] NULL,
	[opisk_amk_koulala2] [int] NULL,
	[opisk_amk_koulala3] [int] NULL,
	[opisk_amk_koulala4] [int] NULL,
	[opisk_amk_koulala5] [int] NULL,
	[opisk_amk_koulala6] [int] NULL,
	[opisk_amk_koulala7] [int] NULL,
	[opisk_amk_koulala8] [int] NULL,
	[opisk_amk_koulala9] [int] NULL,
	[opisk_amk_koulala10] [int] NULL,
	[opisk_yo_koulala1] [int] NULL,
	[opisk_yo_koulala2] [int] NULL,
	[opisk_yo_koulala3] [int] NULL,
	[opisk_yo_koulala4] [int] NULL,
	[opisk_yo_koulala5] [int] NULL,
	[opisk_yo_koulala6] [int] NULL,
	[opisk_yo_koulala7] [int] NULL,
	[opisk_yo_koulala8] [int] NULL,
	[opisk_yo_koulala9] [int] NULL,
	[opisk_yo_koulala10] [int] NULL,
	[opisk_vah2_koulala] [int] NULL,
	[haku_amm] [int] NULL,
	[haku_amk] [int] NULL,
	[haku_yo] [int] NULL,
	[eihaku_kk_eiopisk] [int] NULL,
	[eihaku_kk_eiopisk_kk_opisk_ta] [int] NULL,
	[eihaku_kk_eiopisk_kk_opisk_lu] [int] NULL,
	[eihaku_kk_eiopisk_kk_opisk_pk] [int] NULL,
	[eihaku_kk_eiopisk_kk_opisk_at] [int] NULL,
	[eihaku_kk_eiopisk_kk_opisk_eat] [int] NULL,
	[haku_kk_eiopisk_kk] [int] NULL,
	[haku_kk_eiopisk_kk_eiopisk_ta] [int] NULL,
	[haku_kk_eiopisk_kk_opisk_ta] [int] NULL,
	[haku_amk_eiopisk_kk] [int] NULL,
	[haku_yo_eiopisk_kk] [int] NULL,
	[haku_amkyo_eiopisk_kk] [int] NULL,
	[opisk_kk] [int] NULL,
	[opisk_kk_eiopisk_ta] [int] NULL,
	[opisk_kk_opisk_ta] [int] NULL,
	[opisk_vain_amk] [int] NULL,
	[opisk_vain_yo] [int] NULL,
	[opisk_amkyo] [int] NULL
) ON [PRIMARY]
END
GO


