USE [VipunenTK_DW]
GO

/****** Object:  Table [dbo].[sa_5_4_Sektoritutkimuslaitosten_tutkimus_ja_kehitys]    Script Date: 29.1.2025 15.30.10 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[sa_5_4_Sektoritutkimuslaitosten_tutkimus_ja_kehitys]') AND type in (N'U')) 
   DROP TABLE [dbo].[sa_5_4_Sektoritutkimuslaitosten_tutkimus_ja_kehitys]
GO

CREATE TABLE [dbo].[sa_5_4_Sektoritutkimuslaitosten_tutkimus_ja_kehitys](
	[tilv] [nvarchar](4) NULL,
	[tilv_date] [date] NULL,
	[NIMI] [varchar](35) NULL,
	[NIMI2] [varchar](35) NULL,
	[TK_koodi] [varchar](5) NULL,
	[TOLKM] [int] NULL,
	[NTOLKM] [int] NULL,
	[TOTTV] [decimal](10, 3) NULL,
	[LISLKM] [int] NULL,
	[NLISLKM] [int] NULL,
	[LISTTV] [decimal](10, 3) NULL,
	[DILKM] [int] NULL,
	[NDIPLKM] [int] NULL,
	[DIPTTV] [decimal](10, 3) NULL,
	[INSLKM] [int] NULL,
	[NOPINS] [int] NULL,
	[OPINSTTV] [decimal](10, 3) NULL,
	[YHTE] [decimal](10, 3) NULL,
	[NYHTE] [decimal](10, 3) NULL,
	[YHTTTV] [decimal](10, 3) NULL,
	[PAME] [decimal](10, 3) NULL,
	[OSTPAL] [decimal](10, 3) NULL,
	[YHME] [decimal](10, 3) NULL,
	[TEKES] [decimal](10, 3) NULL,
	[MTEM] [decimal](10, 3) NULL,
	[AKATEMIA] [decimal](10, 3) NULL,
	[GRAD] [decimal](10, 3) NULL,
	[MOPEM] [decimal](10, 3) NULL,
	[LIIKM] [decimal](10, 3) NULL,
	[MAAM] [decimal](10, 3) NULL,
	[OM] [decimal](10, 3) NULL,
	[PM] [decimal](10, 3) NULL,
	[SISAM] [decimal](10, 3) NULL,
	[SOSM] [decimal](10, 3) NULL,
	[UM] [decimal](10, 3) NULL,
	[VN] [decimal](10, 3) NULL,
	[VM] [decimal](10, 3) NULL,
	[YMP] [decimal](10, 3) NULL,
	[MUUJU] [decimal](10, 3) NULL,
	[RAHAS] [decimal](10, 3) NULL,
	[KOTIM] [decimal](10, 3) NULL,
	[ULKOY] [decimal](10, 3) NULL,
	[UEU] [decimal](10, 3) NULL,
	[EUPUITE] [numeric](1, 1) NULL,
	[EAKR] [numeric](1, 1) NULL,
	[ESR] [numeric](1, 1) NULL,
	[MUUEU] [numeric](1, 1) NULL,
	[MULKO] [decimal](10, 3) NULL,
	[UYHTE] [decimal](10, 3) NULL,
	[KUNTA1] [varchar](3) NULL,
	[KUNTA2] [varchar](3) NULL,
	[KUNTA3] [varchar](3) NULL,
	[KUNTA4] [varchar](3) NULL,
	[KUNTA5] [varchar](3) NULL,
	[KUNTA6] [varchar](3) NULL,
	[KUNTA7] [varchar](3) NULL,
	[KUNTA8] [varchar](3) NULL,
	[KUNTA9] [varchar](3) NULL,
	[KUNTA10] [varchar](3) NULL,
	[KUNTA11] [varchar](3) NULL,
	[KUNTA12] [varchar](3) NULL,
	[KUNTA13] [varchar](3) NULL,
	[KUNTA14] [varchar](3) NULL,
	[KUNTA15] [varchar](3) NULL,
	[KUNTA16] [varchar](3) NULL,
	[KUNTA17] [varchar](3) NULL,
	[KUNTA18] [varchar](3) NULL,
	[KUNTA19] [varchar](3) NULL,
	[KUNTA20] [varchar](3) NULL,
	[KUNTA21] [varchar](3) NULL,
	[KUNTA22] [varchar](3) NULL,
	[KUNTA23] [varchar](3) NULL,
	[KUNTA24] [varchar](3) NULL,
	[KUNTA25] [varchar](3) NULL,
	[HENLKMY] [int] NULL,
	[TYOVY] [decimal](10, 3) NULL,
	[TKMENOY] [decimal](10, 3) NULL,
	[HENLKM1] [int] NULL,
	[HENLKM2] [int] NULL,
	[HENLKM3] [int] NULL,
	[HENLKM4] [int] NULL,
	[HENLKM5] [int] NULL,
	[HENLKM6] [int] NULL,
	[HENLKM7] [int] NULL,
	[HENLKM8] [int] NULL,
	[HENLKM9] [int] NULL,
	[HENLKM10] [int] NULL,
	[HENLKM11] [int] NULL,
	[HENLKM12] [int] NULL,
	[HENLKM13] [int] NULL,
	[HENLKM14] [int] NULL,
	[HENLKM15] [int] NULL,
	[HENLKM16] [int] NULL,
	[HENLKM17] [int] NULL,
	[HENLKM18] [int] NULL,
	[HENLKM19] [int] NULL,
	[HENLKM20] [int] NULL,
	[HENLKM21] [int] NULL,
	[HENLKM22] [int] NULL,
	[HENLKM23] [int] NULL,
	[HENLKM24] [int] NULL,
	[HENLKM25] [int] NULL,
	[TYOV1] [decimal](10, 3) NULL,
	[TYOV2] [decimal](10, 3) NULL,
	[TYOV3] [decimal](10, 3) NULL,
	[TYOV4] [decimal](10, 3) NULL,
	[TYOV5] [decimal](10, 3) NULL,
	[TYOV6] [decimal](10, 3) NULL,
	[TYOV7] [decimal](10, 3) NULL,
	[TYOV8] [decimal](10, 3) NULL,
	[TYOV9] [decimal](10, 3) NULL,
	[TYOV10] [decimal](10, 3) NULL,
	[TYOV11] [decimal](10, 3) NULL,
	[TYOV12] [decimal](10, 3) NULL,
	[TYOV13] [decimal](10, 3) NULL,
	[TYOV14] [decimal](10, 3) NULL,
	[TYOV15] [decimal](10, 3) NULL,
	[TYOV16] [decimal](10, 3) NULL,
	[TYOV17] [decimal](10, 3) NULL,
	[TYOV18] [decimal](10, 3) NULL,
	[TYOV19] [decimal](10, 3) NULL,
	[TYOV20] [decimal](10, 3) NULL,
	[TYOV21] [decimal](10, 3) NULL,
	[TYOV22] [decimal](10, 3) NULL,
	[TYOV23] [decimal](10, 3) NULL,
	[TYOV24] [decimal](10, 3) NULL,
	[TYOV25] [decimal](10, 3) NULL,
	[TKMENO1] [decimal](10, 3) NULL,
	[TKMENO2] [decimal](10, 3) NULL,
	[TKMENO3] [decimal](10, 3) NULL,
	[TKMENO4] [decimal](10, 3) NULL,
	[TKMENO5] [decimal](10, 3) NULL,
	[TKMENO6] [decimal](10, 3) NULL,
	[TKMENO7] [decimal](10, 3) NULL,
	[TKMENO8] [decimal](10, 3) NULL,
	[TKMENO9] [decimal](10, 3) NULL,
	[TKMENO10] [decimal](10, 3) NULL,
	[TKMENO11] [decimal](10, 3) NULL,
	[TKMENO12] [decimal](10, 3) NULL,
	[TKMENO13] [decimal](10, 3) NULL,
	[TKMENO14] [decimal](10, 3) NULL,
	[TKMENO15] [decimal](10, 3) NULL,
	[TKMENO16] [decimal](10, 3) NULL,
	[TKMENO17] [decimal](10, 3) NULL,
	[TKMENO18] [decimal](10, 3) NULL,
	[TKMENO19] [decimal](10, 3) NULL,
	[TKMENO20] [decimal](10, 3) NULL,
	[TKMENO21] [decimal](10, 3) NULL,
	[TKMENO22] [decimal](10, 3) NULL,
	[TKMENO23] [decimal](10, 3) NULL,
	[TKMENO24] [decimal](10, 3) NULL,
	[TKMENO25] [decimal](10, 3) NULL,
	[TA1] [varchar](10) NULL,
	[TA2] [varchar](10) NULL,
	[TA3] [varchar](10) NULL,
	[TA4] [varchar](10) NULL,
	[TA5] [varchar](10) NULL,
	[TA6] [varchar](10) NULL,
	[TA7] [varchar](10) NULL,
	[TA8] [varchar](10) NULL,
	[TA9] [varchar](10) NULL,
	[TA10] [varchar](10) NULL,
	[TA11] [varchar](10) NULL,
	[TA12] [varchar](10) NULL,
	[TA13] [varchar](10) NULL,
	[TA14] [varchar](10) NULL,
	[TA15] [varchar](10) NULL,
	[TA16] [varchar](10) NULL,
	[TA17] [varchar](10) NULL,
	[TA18] [varchar](10) NULL,
	[TA1P] [decimal](10, 3) NULL,
	[TA2P] [decimal](10, 3) NULL,
	[TA3P] [decimal](10, 3) NULL,
	[TA4P] [decimal](10, 3) NULL,
	[TA5P] [decimal](10, 3) NULL,
	[TA6P] [decimal](10, 3) NULL,
	[TA7P] [decimal](10, 3) NULL,
	[TA8P] [decimal](10, 3) NULL,
	[TA9P] [decimal](10, 3) NULL,
	[TA10P] [decimal](10, 3) NULL,
	[TA11P] [decimal](10, 3) NULL,
	[TA12P] [decimal](10, 3) NULL,
	[TA13P] [decimal](10, 3) NULL,
	[TA14P] [decimal](10, 3) NULL,
	[TA15P] [decimal](10, 3) NULL,
	[TA16P] [decimal](10, 3) NULL,
	[TA17P] [decimal](10, 3) NULL,
	[TA18P] [decimal](10, 3) NULL,
	[tk_arvio] [decimal](13, 3) NULL,
	[tk_arvioe] [decimal](10, 3) NULL,
	[KMENO] [decimal](10, 3) NULL,
	[HMENO] [decimal](10, 3) NULL,
	[TUTLKM] [int] NULL,
	[NTUTLKM] [int] NULL,
	[TUTTTV] [decimal](10, 3) NULL,
	[MTKLKM] [int] NULL,
	[NMTKLKM] [int] NULL,
	[MTKTTV] [decimal](10, 3) NULL,
	[YHTE2] [int] NULL,
	[NYHTE2] [int] NULL,
	[MKOULKM] [int] NULL,
	[NMKOULKM] [int] NULL,
	[MKOUTTV] [decimal](10, 3) NULL,
	[OPISTLKM] [int] NULL,
	[NOPISTLKM] [int] NULL,
	[OPISTTTV] [decimal](10, 3) NULL,
	[KUNNAT] [decimal](10, 3) NULL,
	[MKVJ] [decimal](10, 3) NULL,
	[ORAHAS] [decimal](10, 3) NULL,
	[BUDJETTI] [decimal](10, 3) NULL,
	[AORAHAS] [decimal](10, 3) NULL,
	[phy1] [int] NULL,
	[phy2] [int] NULL,
	[phy3] [int] NULL,
	[phy4] [int] NULL,
	[phy5] [int] NULL,
	[phy6] [int] NULL,
	[phyy] [int] NULL,
	[phn1] [int] NULL,
	[phn2] [int] NULL,
	[phn3] [int] NULL,
	[phn4] [int] NULL,
	[phn5] [int] NULL,
	[phn6] [int] NULL,
	[phny] [int] NULL,
	[pty1] [int] NULL,
	[pty2] [int] NULL,
	[pty3] [int] NULL,
	[pty4] [int] NULL,
	[pty5] [int] NULL,
	[pty6] [int] NULL,
	[ptyy] [int] NULL,
	[ptn1] [int] NULL,
	[ptn2] [int] NULL,
	[ptn3] [int] NULL,
	[ptn4] [int] NULL,
	[ptn5] [int] NULL,
	[ptn6] [int] NULL,
	[ptny] [int] NULL,
	[RKORK] [decimal](10, 3) NULL,
	[halue] [decimal](10, 3) NULL,
	[tietolahde] [nvarchar](50) NULL,
	[rivinumero] [int] NULL
) ON [PRIMARY]
GO


