USE [ANTERO]
GO
IF NOT EXISTS (select * from INFORMATION_SCHEMA.COLUMNS
    where TABLE_SCHEMA='sa' and TABLE_NAME='SA_SUORAT_YO_TALOUS_4_tutkimusmenot'
    and COLUMN_NAME='KOTIKK')
BEGIN
ALTER TABLE [sa].[SA_SUORAT_YO_TALOUS_4_tutkimusmenot] ADD KOTIKK INT NULL;
END
