USE [VipunenTK_DW]
GO

/****** Object:  Table [dbo].[f_2_8_Korkeakouluopiskelijat]    Script Date: 5.11.2025 10.25.02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[f_2_8_Korkeakouluopiskelijat]') AND type in (N'U'))
  DROP TABLE [dbo].[f_2_8_Korkeakouluopiskelijat]
GO

CREATE TABLE [dbo].[f_2_8_Korkeakouluopiskelijat](
	[tilastointivuosi] [varchar](4) NULL,
	[tilv_date] [date] NULL,
	[aineisto] [varchar](1) NULL,
	[lahde] [varchar](2) NULL,
	[oppilaitos] [varchar](5) NULL,
	[koulutuksen_jarjestaja] [varchar](10) NULL,
	[koulutusluokitus] [varchar](6) NULL,
	[koulutuksen_kunta] [varchar](3) NULL,
	[sukupuoli] [varchar](1) NULL,
	[aidinkieli_versio1x] [varchar](2) NULL,
	[syntymavuosi] [varchar](4) NULL,
	[kotikunta] [varchar](6) NULL,
	[kotikunta1x] [varchar](3) NULL,
	[kotikunta2x] [varchar](3) NULL,
	[kansalaisuus_versio2] [varchar](1) NULL,
	[kvopisk] [varchar](1) NULL,
	[suormaa] [varchar](1) NULL,
	[kirjoihintulovuosi] [varchar](10) NULL,
	[jarjestys_kirjoihintulovuosi] [int] NULL,
	[kirjoihintulokausi] [varchar](1) NULL,
	[opiskelijan_olo_tamm] [varchar](1) NULL,
	[opiskelijan_olo_syys] [varchar](1) NULL,
	[rahoituslahde] [varchar](1) NULL,
	[opiskelijan_fte_tieto] [varchar](1) NULL,
	[kirjoihintulovuosi_korkeakoulusektori] [varchar](4) NULL,
	[kirjoihintulovuosi_korkeakoulusektori_lasnaoleva] [varchar](4) NULL,
	[kirjoihintulovuosi_sektori] [varchar](4) NULL,
	[kirjoihintulovuosi_sektori_lasnaoleva] [varchar](4) NULL,
	[kirjoihintulovuosi_korkeakoulu] [varchar](4) NULL,
	[kirjoihintulovuosi_korkeakoulu_lasnaoleva] [varchar](4) NULL,
	[kirjoihintulovuosi_opintoala] [varchar](4) NULL,
	[kirjoihintulovuosi_opintoala_lasnaoleva] [varchar](4) NULL,
	[lukumaara] [int] NULL,
	[lkm_op0] [int] NULL,
	[lkm_op1_14] [int] NULL,
	[lkm_op15_29] [int] NULL,
	[lkm_op30_44] [int] NULL,
	[lkm_op45_59] [int] NULL,
	[lkm_op60_74] [int] NULL,
	[lkm_op75_89] [int] NULL,
	[lkm_op90_104] [int] NULL,
	[lkm_op105_119] [int] NULL,
	[lkm_op120_] [int] NULL,
	[vahintaan_55_op_suorittanut] [varchar](1) NULL,
	[op_edellinen_syksy] [int] NULL,
	[op_edellinen_kevat] [int] NULL,
	[op_kertyma_edel_lkv_loppu] [int] NULL,
	[tutkinto_amk] [varchar](3) NULL,
	[koulutusohjelma_amk] [varchar](4) NULL,
	[suuntautumisvaihtoehto_amk] [varchar](5) NULL,
	[koulutustyyppi] [varchar](1) NULL,
	[koulutuksen_kieli] [varchar](2) NULL,
	[lkm_lasnalk] [int] NULL,
	[lkm_poissalk] [int] NULL,
	[op_suoritettavien_laajuus] [int] NULL,
	[kirjoihintulovuosi_tutkinto] [varchar](4) NULL,
	[kirjoihintulokausi_tutkinto] [varchar](1) NULL,
	[ensisijainen_opintooikeus] [varchar](1) NULL,
	[tilauskoulutuksen_sijaintimaa] [varchar](1) NULL,
	[tutkinto_yo] [varchar](3) NULL,
	[koulutusohjelma_yo] [varchar](4) NULL,
	[paaaine_yo] [varchar](4) NULL,
	[yliopisto] [varchar](2) NULL,
	[tiedekunta_yo] [varchar](2) NULL,
	[uusi_vanha_opiskelija] [varchar](1) NULL,
	[tutkintooikeusvuosi] [varchar](4) NULL,
	[opiskelumuoto] [varchar](1) NULL,
	[opettajankelpoisuus] [varchar](1) NULL,
	[avoinvayla] [varchar](1) NULL,
	[tietolahde] [nvarchar](250) NULL,
	[rivinumero] [varchar](10) NULL,
	[aineistotunnus] [varchar](6) NOT NULL,
	[koulutussektori] [nvarchar](2) NULL,
	[ika_1v] [nvarchar](4) NULL,
	[aloittaneet] [int] NULL,
	[aloittaneet_kirjoihintulovuosi] [int] NULL,
	[aloittaneet_korkeakoulusektori] [int] NULL,
	[aloittaneet_korkeakoulusektori_lasnaoleva] [int] NULL,
	[aloittaneet_sektori] [int] NULL,
	[aloittaneet_sektori_lasnaoleva] [int] NULL,
	[aloittaneet_korkeakoulu] [int] NULL,
	[aloittaneet_korkeakoulu_lasnaoleva] [int] NULL,
	[aloittaneet_opintoala] [int] NULL,
	[aloittaneet_opintoala_lasnaoleva] [int] NULL,
	[opiskelijat] [int] NULL,
	[opiskelijat_lasna] [int] NULL,
	[opiskelijat_fte] [decimal](18, 1) NULL,
	[koulutuslaji_OKM_avain] [int] NOT NULL,
	[koulutusryhma_avain] [int] NULL,
	[ikaryhma1_avain] [varchar](10) NULL,
	[ikaryhma2_avain] [varchar](10) NOT NULL,
	[laak] [varchar](1) NULL,
	[ltop] [int] NULL
) ON [PRIMARY]
GO


