USE [ANTERO]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [AVUSTUSTUOTOT] [bigint]
ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [LIIKTUOTOT] [bigint]
ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [OSUUSTULOS] [bigint]
ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [ULKLIIKTOIM] [bigint]
ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [KVARVONMUUTOS] [bigint]
ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [VARSSIJTUOT] [bigint]
ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [MUUTKORKORAHTUOTOT] [bigint]
ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [ARVONALENTUMISETPAL] [bigint]
ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [RAHOITUSTUOTOT] [bigint]
ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [SIDOTUT] [bigint]
ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [SIIRTOSIDOTUSTA] [bigint]
ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [SIIRTOSIDOTTUUN] [bigint]
ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [OMAKATTEISET] [bigint]
ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [SIIRTORAHASTOSTA] [bigint]
ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [SIIRTORAHASTOON] [bigint]
ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [VAHEMMISTOOSUUDET] [bigint]
ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [KORKVARSTOIMALV] [bigint]
ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [OKMKOMPENS] [bigint]
ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [HARJOITTELUKOULUJENVM] [bigint]
ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [MUURAHKOMP] [bigint]
ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [VMRAHHARJKOULU] [bigint]
ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [OKMRAHHARJKOULU] [bigint]
ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [HARJKOULUKULUYHT] [bigint]
ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [KONELAITE] [bigint]
ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [KERLAHJKOTITAL] [bigint]
ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [KERLAHJYRI] [bigint]
ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [KERLAHJMUUT] [bigint]
ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [VARAINHANKINTA] [bigint]
ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [MUUVARAINHANKINTA] [bigint]
ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [KERLAHJKULU] [bigint]
ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [VARAINHANKINTAKUL] [bigint]
ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [MUUTVARAINHANKINTAKUL] [bigint]
ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [VARAINHANKINTATUOT] [bigint]
ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [OSINKOTUOTOT] [bigint]
ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [KORKOTUOTOT] [bigint]
ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [MYYNTITUOTOT] [bigint]
ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [VUOKRATUOTOT] [bigint]
ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [MUUTTUOTOT_3] [bigint]
ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [KORKOKULUT] [bigint]
ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [VUOKRAKULUT] [bigint]
ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [MYYNTITAPPIOT] [bigint]
ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [LUKUKAUSIMAKSUT] [bigint]
ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [PYSYVAISLUONTOINEN] [bigint]
ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [MUUTMUUTTUOT] [bigint]
ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [KULUTYHT] [bigint]
ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [MUUTKULUTYHT] [bigint]
ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [TILAKUSTANNUKSET] [bigint]
ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [MUUTVHKULUT] [bigint]

GO
