USE ANTERO

GO

IF NOT EXISTS
	(SELECT * FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_SCHEMA='dw'
	AND TABLE_NAME='d_hakuaika' AND COLUMN_NAME = 'alkuPvm')
BEGIN
ALTER TABLE dw.d_hakuaika
add alkuPvm date;
END

GO

IF NOT EXISTS
	(SELECT * FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_SCHEMA='dw'
	AND TABLE_NAME='d_hakuaika' AND COLUMN_NAME = 'loppuPvm')
BEGIN
ALTER TABLE dw.d_hakuaika
add loppuPvm date;
END