USE [VipunenTK_SA]
GO

/****** Object:  View [dbo].[v_sa_2_18_Paivahoidossa_jarjestettava_esiopetus]    Script Date: 10.12.2018 7:32:52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO






ALTER VIEW [dbo].[v_sa_2_18_Paivahoidossa_jarjestettava_esiopetus] AS
SELECT [tilv]
      ,[jarjnim]
      ,[jarj]
      ,[tiedtype]
      ,[popy]
	  ,[popyn] = NULL
      ,[jmamu]
      ,[psisa]
      ,[jmamusisa]
      ,[pteho]
      ,[pertu]
      ,[pertuv]
      ,[pertum]
      ,[ptehoerop]
      ,[pviertu]
      ,[pviertuv]
      ,[pviertum]
      ,[pvimuut]
      ,[pviop]
      ,[pkuertu]
      ,[pkuertuv]
      ,[pkuertum]
      ,[pkumuut]
      ,[pkuop]
      ,[ppid5v]
      ,[pmuu5v]
      ,[pop5v]
      ,[apip1]
      ,[apip2]
      ,[apip39]
      ,[apipy]
      ,[oma3s]
      ,[osto3s]
      ,[avust3s]
      ,[syk3s]
      ,[oma4s]
      ,[osto4s]
      ,[avust4s]
      ,[syk4s]
      ,[omams]
      ,[ostoms]
      ,[avustms]
      ,[sykms]
      ,[omays]
      ,[ostoys]
      ,[avustys]
      ,[sykys]
      ,[oma3k]
      ,[osto3k]
      ,[avust3k]
      ,[kev3k]
      ,[oma4k]
      ,[osto4k]
      ,[avust4k]
      ,[kev4k]
      ,[omamk]
      ,[ostomk]
      ,[avustmk]
      ,[kevmk]
      ,[omayk]
      ,[ostoyk]
      ,[avustyk]
      ,[kevyk]
      ,[pesis]
      ,[pesisjarjnim]
      ,[pesisjarj]
      ,[kesis]
      ,[kesisjarjnim]
      ,[kesisjarj]
      ,[perops]
      ,[peropsjarjnim]
      ,[peropsjarj]
      ,[apips]
      ,[apipsjarjnim]
      ,[apipsjarj]
      ,[luontipvm]
      ,[jmamun] = NULL
      ,[jmamuy] = NULL
      ,[jmamuyn] = NULL
      ,[jmamusisay] = NULL
      ,[jmamueo8] = NULL
      ,[jmamueo8n] = NULL
      ,[jmamueo4] = NULL
      ,[jmamueo4n] = NULL
FROM [TK_H9098_CSC]..[TK_2_18_sopv_12]
UNION ALL
SELECT [tilv]
      ,[jarjnim]
      ,[jarj]
      ,[tiedtype]
      ,[popy]
	  ,[popyn] = NULL
      ,[jmamu]
      ,[psisa]
      ,[jmamusisa]
      ,[pteho]
      ,[pertu]
      ,[pertuv]
      ,[pertum]
      ,[ptehoerop]
      ,[pviertu]
      ,[pviertuv]
      ,[pviertum]
      ,[pvimuut]
      ,[pviop]
      ,[pkuertu]
      ,[pkuertuv]
      ,[pkuertum]
      ,[pkumuut]
      ,[pkuop]
      ,[ppid5v]
      ,[pmuu5v]
      ,[pop5v]
      ,[apip1]
      ,[apip2]
      ,[apip39]
      ,[apipy]
      ,[oma3s]
      ,[osto3s]
      ,[avust3s]
      ,[syk3s]
      ,[oma4s]
      ,[osto4s]
      ,[avust4s]
      ,[syk4s]
      ,[omams]
      ,[ostoms]
      ,[avustms]
      ,[sykms]
      ,[omays]
      ,[ostoys]
      ,[avustys]
      ,[sykys]
      ,[oma3k]
      ,[osto3k]
      ,[avust3k]
      ,[kev3k]
      ,[oma4k]
      ,[osto4k]
      ,[avust4k]
      ,[kev4k]
      ,[omamk]
      ,[ostomk]
      ,[avustmk]
      ,[kevmk]
      ,[omayk]
      ,[ostoyk]
      ,[avustyk]
      ,[kevyk]
      ,[pesis]
      ,[pesisjarjnim]
      ,[pesisjarj]
      ,[kesis]
      ,[kesisjarjnim]
      ,[kesisjarj]
      ,[perops]
      ,[peropsjarjnim]
      ,[peropsjarj]
      ,[apips]
      ,[apipsjarjnim]
      ,[apipsjarj]
      ,[luontipvm]
      ,[jmamun] = NULL
      ,[jmamuy] = NULL
      ,[jmamuyn] = NULL
      ,[jmamusisay] = NULL
      ,[jmamueo8] = NULL
      ,[jmamueo8n] = NULL
      ,[jmamueo4] = NULL
      ,[jmamueo4n] = NULL
FROM [TK_H9098_CSC]..[TK_2_18_sopv_13]
UNION ALL
SELECT [tilv]
      ,[jarjnim]
      ,[jarj]
      ,[tiedtype]
      ,[popy]
	  ,[popyn] = NULL
      ,[jmamu]
      ,[psisa]
      ,[jmamusisa]
      ,[pteho]
      ,[pertu]
      ,[pertuv]
      ,[pertum]
      ,[ptehoerop]
      ,[pviertu]
      ,[pviertuv]
      ,[pviertum]
      ,[pvimuut]
      ,[pviop]
      ,[pkuertu]
      ,[pkuertuv]
      ,[pkuertum]
      ,[pkumuut]
      ,[pkuop]
      ,[ppid5v]
      ,[pmuu5v]
      ,[pop5v]
      ,[apip1]
      ,[apip2]
      ,[apip39]
      ,[apipy]
      ,[oma3s]
      ,[osto3s]
      ,[avust3s]
      ,[syk3s]
      ,[oma4s]
      ,[osto4s]
      ,[avust4s]
      ,[syk4s]
      ,[omams]
      ,[ostoms]
      ,[avustms]
      ,[sykms]
      ,[omays]
      ,[ostoys]
      ,[avustys]
      ,[sykys]
      ,[oma3k]
      ,[osto3k]
      ,[avust3k]
      ,[kev3k]
      ,[oma4k]
      ,[osto4k]
      ,[avust4k]
      ,[kev4k]
      ,[omamk]
      ,[ostomk]
      ,[avustmk]
      ,[kevmk]
      ,[omayk]
      ,[ostoyk]
      ,[avustyk]
      ,[kevyk]
      ,[pesis]
      ,[pesisjarjnim]
      ,[pesisjarj]
      ,[kesis]
      ,[kesisjarjnim]
      ,[kesisjarj]
      ,[perops]
      ,[peropsjarjnim]
      ,[peropsjarj]
      ,[apips]
      ,[apipsjarjnim]
      ,[apipsjarj]
      ,[luontipvm]
      ,[jmamun] = NULL
      ,[jmamuy] = NULL
      ,[jmamuyn] = NULL
      ,[jmamusisay] = NULL
      ,[jmamueo8] = NULL
      ,[jmamueo8n] = NULL
      ,[jmamueo4] = NULL
      ,[jmamueo4n] = NULL
FROM [TK_H9098_CSC]..[TK_2_18_sopv_14]
UNION ALL
SELECT [tilv]
      ,[jarjnim]
      ,[jarj]
      ,[tiedtype]
      ,[popy]
	  ,[popyn] = NULL
      ,[jmamu]
      ,[psisa]
      ,[jmamusisa]
      ,[pteho]
      ,[pertu]
      ,[pertuv]
      ,[pertum]
      ,[ptehoerop]
      ,[pviertu]
      ,[pviertuv]
      ,[pviertum]
      ,[pvimuut]
      ,[pviop]
      ,[pkuertu]
      ,[pkuertuv]
      ,[pkuertum]
      ,[pkumuut]
      ,[pkuop]
      ,[ppid5v]
      ,[pmuu5v]
      ,[pop5v]
      ,[apip1]
      ,[apip2]
      ,[apip39]
      ,[apipy]
      ,[oma3s]
      ,[osto3s]
      ,[avust3s]
      ,[syk3s]
      ,[oma4s]
      ,[osto4s]
      ,[avust4s]
      ,[syk4s]
      ,[omams]
      ,[ostoms]
      ,[avustms]
      ,[sykms]
      ,[omays]
      ,[ostoys]
      ,[avustys]
      ,[sykys]
      ,[oma3k]
      ,[osto3k]
      ,[avust3k]
      ,[kev3k]
      ,[oma4k]
      ,[osto4k]
      ,[avust4k]
      ,[kev4k]
      ,[omamk]
      ,[ostomk]
      ,[avustmk]
      ,[kevmk]
      ,[omayk]
      ,[ostoyk]
      ,[avustyk]
      ,[kevyk]
      ,[pesis]
      ,[pesisjarjnim]
      ,[pesisjarj]
      ,[kesis]
      ,[kesisjarjnim]
      ,[kesisjarj]
      ,[perops]
      ,[peropsjarjnim]
      ,[peropsjarj]
      ,[apips]
      ,[apipsjarjnim]
      ,[apipsjarj]
      ,[luontipvm]
      ,[jmamun] = NULL
      ,[jmamuy] = NULL
      ,[jmamuyn] = NULL
      ,[jmamusisay] = NULL
      ,[jmamueo8] = NULL
      ,[jmamueo8n] = NULL
      ,[jmamueo4] = NULL
      ,[jmamueo4n] = NULL
FROM [TK_H9098_CSC]..[TK_2_18_sopv_15]
UNION ALL
SELECT [tilv]
      ,[jarjnim]
      ,[jarj]
      ,[tiedtype]
      ,[popy]
	  ,[popyn]
      ,[jmamu]
      ,[psisa]
      ,[jmamusisa]
      ,[pteho]
      ,[pertu]
      ,[pertuv]
      ,[pertum]
      ,[ptehoerop]
      ,[pviertu]
      ,[pviertuv]
      ,[pviertum]
      ,[pvimuut]
      ,[pviop]
      ,[pkuertu]
      ,[pkuertuv]
      ,[pkuertum]
      ,[pkumuut]
      ,[pkuop]
      ,[ppid5v]
      ,[pmuu5v]
      ,[pop5v]
      ,[apip1]
      ,[apip2]
      ,[apip39]
      ,[apipy]
      ,[oma3s]
      ,[osto3s]
      ,[avust3s]
      ,[syk3s]
      ,[oma4s]
      ,[osto4s]
      ,[avust4s]
      ,[syk4s]
      ,[omams]
      ,[ostoms]
      ,[avustms]
      ,[sykms]
      ,[omays]
      ,[ostoys]
      ,[avustys]
      ,[sykys]
      ,[oma3k]
      ,[osto3k]
      ,[avust3k]
      ,[kev3k]
      ,[oma4k]
      ,[osto4k]
      ,[avust4k]
      ,[kev4k]
      ,[omamk]
      ,[ostomk]
      ,[avustmk]
      ,[kevmk]
      ,[omayk]
      ,[ostoyk]
      ,[avustyk]
      ,[kevyk]
      ,[pesis]
      ,[pesisjarjnim]
      ,[pesisjarj]
      ,[kesis]
      ,[kesisjarjnim]
      ,[kesisjarj]
      ,[perops]
      ,[peropsjarjnim]
      ,[peropsjarj]
      ,[apips]
      ,[apipsjarjnim]
      ,[apipsjarj]
      ,[luontipvm]
      ,[jmamun]
      ,[jmamuy]
      ,[jmamuyn]
      ,[jmamusisay]
      ,[jmamueo8]
      ,[jmamueo8n]
      ,[jmamueo4]
      ,[jmamueo4n]
FROM [TK_H9098_CSC]..[TK_2_18_sopv_16]
UNION ALL
SELECT [tilv]
      ,[jarjnim]
      ,[jarj]
      ,[tiedtype]
      ,[popy]
	  ,[popyn]
      ,[jmamu]
      ,[psisa]
      ,[jmamusisa]
      ,[pteho]
      ,[pertu]
      ,[pertuv]
      ,[pertum]
      ,[ptehoerop]
      ,[pviertu]
      ,[pviertuv]
      ,[pviertum]
      ,[pvimuut]
      ,[pviop]
      ,[pkuertu]
      ,[pkuertuv]
      ,[pkuertum]
      ,[pkumuut]
      ,[pkuop]
      ,[ppid5v]
      ,[pmuu5v]
      ,[pop5v]
      ,[apip1]
      ,[apip2]
      ,[apip39]
      ,[apipy]
      ,[oma3s]
      ,[osto3s]
      ,[avust3s]
      ,[syk3s]
      ,[oma4s]
      ,[osto4s]
      ,[avust4s]
      ,[syk4s]
      ,[omams]
      ,[ostoms]
      ,[avustms]
      ,[sykms]
      ,[omays]
      ,[ostoys]
      ,[avustys]
      ,[sykys]
      ,[oma3k]
      ,[osto3k]
      ,[avust3k]
      ,[kev3k]
      ,[oma4k]
      ,[osto4k]
      ,[avust4k]
      ,[kev4k]
      ,[omamk]
      ,[ostomk]
      ,[avustmk]
      ,[kevmk]
      ,[omayk]
      ,[ostoyk]
      ,[avustyk]
      ,[kevyk]
      ,[pesis]
      ,[pesisjarjnim]
      ,[pesisjarj]
      ,[kesis]
      ,[kesisjarjnim]
      ,[kesisjarj]
      ,[perops]
      ,[peropsjarjnim]
      ,[peropsjarj]
      ,[apips]
      ,[apipsjarjnim]
      ,[apipsjarj]
      ,[luontipvm]
      ,[jmamun] = NULL
      ,[jmamuy] = NULL
      ,[jmamuyn] = NULL
      ,[jmamusisay] = NULL
      ,[jmamueo8] = NULL
      ,[jmamueo8n] = NULL
      ,[jmamueo4] = NULL
      ,[jmamueo4n] = NULL
FROM [TK_H9098_CSC]..[TK_2_18_sopv_17]

UNION ALL
SELECT [tilv]
      ,[jarjnim]
      ,[jarj]
      ,[tiedtype]
      ,[popy]
	  ,[popyn]
      ,[jmamu] = NULL
      ,[psisa]
      ,[jmamusisa] = NULL
      ,[pteho]
      ,[pertu]
      ,[pertuv]
      ,[pertum]
      ,[ptehoerop]
      ,[pviertu]
      ,[pviertuv]
      ,[pviertum]
      ,[pvimuut]
      ,[pviop]
      ,[pkuertu]
      ,[pkuertuv]
      ,[pkuertum]
      ,[pkumuut]
      ,[pkuop]
      ,[ppid5v]
      ,[pmuu5v]
      ,[pop5v]
      ,[apip1]
      ,[apip2]
      ,[apip39]
      ,[apipy]
      ,[oma3s]
      ,[osto3s]
      ,[avust3s]
      ,[syk3s]
      ,[oma4s]
      ,[osto4s]
      ,[avust4s]
      ,[syk4s]
      ,[omams]
      ,[ostoms]
      ,[avustms]
      ,[sykms]
      ,[omays]
      ,[ostoys]
      ,[avustys]
      ,[sykys]
      ,[oma3k]
      ,[osto3k]
      ,[avust3k]
      ,[kev3k]
      ,[oma4k]
      ,[osto4k]
      ,[avust4k]
      ,[kev4k]
      ,[omamk]
      ,[ostomk]
      ,[avustmk]
      ,[kevmk]
      ,[omayk]
      ,[ostoyk]
      ,[avustyk]
      ,[kevyk]
      ,[pesis]
      ,[pesisjarjnim]
      ,[pesisjarj]
      ,[kesis]
      ,[kesisjarjnim]
      ,[kesisjarj]
      ,[perops]
      ,[peropsjarjnim]
      ,[peropsjarj]
      ,[apips]
      ,[apipsjarjnim]
      ,[apipsjarj]
      ,[luontipvm]
      ,[jmamun] = NULL
      ,[jmamuy] = NULL
      ,[jmamuyn] = NULL
      ,[jmamusisay] = NULL
      ,[jmamueo8] = NULL
      ,[jmamueo8n] = NULL
      ,[jmamueo4] = NULL
      ,[jmamueo4n] = NULL
FROM [TK_H9098_CSC]..[TK_2_18_sopv_18]




GO


USE [ANTERO]