USE [ANTERO]
IF EXISTS
	(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='sa' AND TABLE_NAME='sa_eter_erasmus')
BEGIN
	DROP TABLE [sa].[sa_eter_erasmus];
END

IF  NOT EXISTS
	(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='sa' AND TABLE_NAME='sa_eter_erasmus')
BEGIN

CREATE TABLE [sa].[sa_eter_erasmus](
	[_id] [varchar](24) NOT NULL,
	[ERA.CODE] [varchar](38) NULL,
	[ERA.INCOMING_STUDENTS_ISCED5.code] [varchar](2) NULL,
	[ERA.INCOMING_STUDENTS_ISCED5.v] [varchar](2) NULL,
	[ERA.INCOMING_STUDENTS_ISCED6.code] [varchar](2) NULL,
	[ERA.INCOMING_STUDENTS_ISCED6.v] [varchar](4) NULL,
	[ERA.INCOMING_STUDENTS_ISCED7.code] [varchar](2) NULL,
	[ERA.INCOMING_STUDENTS_ISCED7.v] [varchar](3) NULL,
	[ERA.INCOMING_STUDENTS_ISCED8.code] [varchar](2) NULL,
	[ERA.INCOMING_STUDENTS_ISCED8.v] [varchar](3) NULL,
	[ERA.INCOMING_STUDENTS_OTHER.code] [varchar](2) NULL,
	[ERA.INCOMING_STUDENTS_OTHER.v] [varchar](2) NULL,
	[ERA.INCOMING_STUDENTS_TOT.code] [varchar](2) NULL,
	[ERA.INCOMING_STUDENTS_TOT.v] [varchar](4) NULL,
	[ERA.OUTGOING_STUDENTS_ISCED5.code] [varchar](2) NULL,
	[ERA.OUTGOING_STUDENTS_ISCED5.v] [varchar](3) NULL,
	[ERA.OUTGOING_STUDENTS_ISCED6.code] [varchar](2) NULL,
	[ERA.OUTGOING_STUDENTS_ISCED6.v] [varchar](4) NULL,
	[ERA.OUTGOING_STUDENTS_ISCED7.code] [varchar](2) NULL,
	[ERA.OUTGOING_STUDENTS_ISCED7.v] [varchar](4) NULL,
	[ERA.OUTGOING_STUDENTS_ISCED8.code] [varchar](2) NULL,
	[ERA.OUTGOING_STUDENTS_ISCED8.v] [varchar](3) NULL,
	[ERA.OUTGOING_STUDENTS_OTHER.code] [varchar](2) NULL,
	[ERA.OUTGOING_STUDENTS_OTHER.v] [varchar](3) NULL,
	[ERA.OUTGOING_STUDENTS_TOT.code] [varchar](2) NULL,
	[ERA.OUTGOING_STUDENTS_TOT.v] [varchar](4) NULL,
	[ERA.INCOMING_STAFF.code] [varchar](2) NULL,
	[ERA.INCOMING_STAFF.v] [varchar](3) NULL,
	[ERA.OUTGOING_STAFF.code] [varchar](2) NULL,
	[ERA.OUTGOING_STAFF.v] [varchar](3) NULL,
	[ERA.FLAG] [varchar](2) NULL,
	[ERA.NOTES] [varchar](2) NULL,
	[ERA.CREDITMOBINCOMING.code] [varchar](2) NULL,
	[ERA.CREDITMOBINCOMING.v] [varchar](20) NULL,
	[ERA.FLAGCREDITMOBINCOMING] [varchar](5) NULL,
	[ERA.CREDITMOBOUTGOING.code] [varchar](2) NULL,
	[ERA.CREDITMOBOUTGOING.v] [varchar](20) NULL,
	[username] [varchar](100) NULL,
	[Source] [varchar](100) NULL,
	[Loadtime] [datetime] NULL,
 CONSTRAINT [PK__sa_eter_erasmus] PRIMARY KEY CLUSTERED
(
	[_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO

ALTER TABLE [sa].[sa_eter_erasmus] ADD  CONSTRAINT [DF__sa_eter_erasmus]  DEFAULT (suser_name()) FOR [username]
GO

USE ANTERO