USE ANTERO

IF  EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_oiva_jarjestysluvat')
BEGIN
	DROP TABLE [sa].[sa_oiva_jarjestysluvat]
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_oiva_maara')

BEGIN
  DROP TABLE [sa].[sa_oiva_maara]
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_oiva_maaraykset_pdi')

BEGIN
	DROP TABLE [sa].[sa_oiva_maaraykset_pdi]
END
