USE ANTERO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_yo_talous_1_tuloslaskelma'  
AND COLUMN_NAME ='LIIKEVAIHTO')
BEGIN
	ALTER TABLE [sa].[sa_suorat_yo_talous_1_tuloslaskelma]  ADD [LIIKEVAIHTO] bigint  NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_yo_talous_1_tuloslaskelma'
AND COLUMN_NAME ='MUUOKM')
BEGIN
	ALTER TABLE [sa].[sa_suorat_yo_talous_1_tuloslaskelma]  ADD [MUUOKM] bigint  NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_yo_talous_1_tuloslaskelma'
AND COLUMN_NAME ='MUUVALTIO')
BEGIN
	ALTER TABLE [sa].[sa_suorat_yo_talous_1_tuloslaskelma]  ADD [MUUVALTIO] bigint  NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_yo_talous_1_tuloslaskelma'
AND COLUMN_NAME ='ULKLIIKTOIM')
BEGIN
	ALTER TABLE [sa].[sa_suorat_yo_talous_1_tuloslaskelma]  ADD [ULKLIIKTOIM] bigint  NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_yo_talous_1_tuloslaskelma'
AND COLUMN_NAME ='MAKSUASETUS')
BEGIN
	ALTER TABLE [sa].[sa_suorat_yo_talous_1_tuloslaskelma]  ADD [MAKSUASETUS] bigint  NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_yo_talous_1_tuloslaskelma'
AND COLUMN_NAME ='LUKUKAUSIMAKSUT')
BEGIN
	ALTER TABLE [sa].[sa_suorat_yo_talous_1_tuloslaskelma]  ADD [LUKUKAUSIMAKSUT] bigint  NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_yo_talous_1_tuloslaskelma'
AND COLUMN_NAME ='PYSYVAISLUONTOINEN')
BEGIN
	ALTER TABLE [sa].[sa_suorat_yo_talous_1_tuloslaskelma]  ADD [PYSYVAISLUONTOINEN] bigint  NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_yo_talous_1_tuloslaskelma'
AND COLUMN_NAME ='MUUTMUUTTUOT')
BEGIN
	ALTER TABLE [sa].[sa_suorat_yo_talous_1_tuloslaskelma]  ADD [MUUTMUUTTUOT] bigint  NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_yo_talous_1_tuloslaskelma'
AND COLUMN_NAME ='MUUTKULUTYHT')
BEGIN
	ALTER TABLE [sa].[sa_suorat_yo_talous_1_tuloslaskelma]  ADD [MUUTKULUTYHT] bigint  NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_yo_talous_1_tuloslaskelma'
AND COLUMN_NAME ='KERLAHJKULU')
BEGIN
	ALTER TABLE [sa].[sa_suorat_yo_talous_1_tuloslaskelma]  ADD [KERLAHJKULU] bigint  NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_yo_talous_1_tuloslaskelma'
AND COLUMN_NAME ='MUUTTUOTOT_3')
BEGIN
	ALTER TABLE [sa].[sa_suorat_yo_talous_1_tuloslaskelma]  ADD [MUUTTUOTOT_3] bigint  NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_yo_talous_1_tuloslaskelma'
AND COLUMN_NAME ='MUUTKULUT')
BEGIN
	ALTER TABLE [sa].[sa_suorat_yo_talous_1_tuloslaskelma]  ADD [MUUTKULUT] bigint  NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_yo_talous_1_tuloslaskelma'
AND COLUMN_NAME ='KVARVONMUUTOS')
BEGIN
	ALTER TABLE [sa].[sa_suorat_yo_talous_1_tuloslaskelma]  ADD [KVARVONMUUTOS] bigint  NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_yo_talous_1_tuloslaskelma'
AND COLUMN_NAME ='VARSSIJTUOT')
BEGIN
	ALTER TABLE [sa].[sa_suorat_yo_talous_1_tuloslaskelma]  ADD [VARSSIJTUOT] bigint  NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_yo_talous_1_tuloslaskelma'
AND COLUMN_NAME ='TUOTOSUUKSISTAKONS')
BEGIN
	ALTER TABLE [sa].[sa_suorat_yo_talous_1_tuloslaskelma]  ADD [TUOTOSUUKSISTAKONS] bigint  NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_yo_talous_1_tuloslaskelma'
AND COLUMN_NAME ='TUOTOTOSUUKSISTAOMIST')
BEGIN
	ALTER TABLE [sa].[sa_suorat_yo_talous_1_tuloslaskelma]  ADD [TUOTOTOSUUKSISTAOMIST] bigint  NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_yo_talous_1_tuloslaskelma'
AND COLUMN_NAME ='TUOTOTMUISTA')
BEGIN
	ALTER TABLE [sa].[sa_suorat_yo_talous_1_tuloslaskelma]  ADD [TUOTOTMUISTA] bigint  NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_yo_talous_1_tuloslaskelma'
AND COLUMN_NAME ='MUUTKORKORAHTUOTOT')
BEGIN
	ALTER TABLE [sa].[sa_suorat_yo_talous_1_tuloslaskelma]  ADD [MUUTKORKORAHTUOTOT] bigint  NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_yo_talous_1_tuloslaskelma'
AND COLUMN_NAME ='ARVONALENTUMISETPAL')
BEGIN
	ALTER TABLE [sa].[sa_suorat_yo_talous_1_tuloslaskelma]  ADD [ARVONALENTUMISETPAL] bigint  NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_yo_talous_1_tuloslaskelma'
AND COLUMN_NAME ='ARVONALENTUMISETPYSSIJ')
BEGIN
	ALTER TABLE [sa].[sa_suorat_yo_talous_1_tuloslaskelma]  ADD [ARVONALENTUMISETPYSSIJ] bigint  NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_yo_talous_1_tuloslaskelma'
AND COLUMN_NAME ='ARVONALENTUMISETVAIHTUVIEN')
BEGIN
	ALTER TABLE [sa].[sa_suorat_yo_talous_1_tuloslaskelma]  ADD [ARVONALENTUMISETVAIHTUVIEN] bigint  NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_yo_talous_1_tuloslaskelma'
AND COLUMN_NAME ='KORKOKULUTRAHKULUT')
BEGIN
	ALTER TABLE [sa].[sa_suorat_yo_talous_1_tuloslaskelma]  ADD [KORKOKULUTRAHKULUT] bigint  NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_yo_talous_1_tuloslaskelma'
AND COLUMN_NAME ='KORKOKULUTRAHKULUTSAMA')
BEGIN
	ALTER TABLE [sa].[sa_suorat_yo_talous_1_tuloslaskelma]  ADD [KORKOKULUTRAHKULUTSAMA] bigint  NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_yo_talous_1_tuloslaskelma'
AND COLUMN_NAME ='RAHOITUSTUOTOT')
BEGIN
	ALTER TABLE [sa].[sa_suorat_yo_talous_1_tuloslaskelma]  ADD [RAHOITUSTUOTOT] bigint  NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_yo_talous_1_tuloslaskelma'
AND COLUMN_NAME ='VOITTOENTILP')
BEGIN
	ALTER TABLE [sa].[sa_suorat_yo_talous_1_tuloslaskelma]  ADD [VOITTOENTILP] bigint  NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_yo_talous_1_tuloslaskelma'
AND COLUMN_NAME ='SIIRTOSIDOTUSTA')
BEGIN
	ALTER TABLE [sa].[sa_suorat_yo_talous_1_tuloslaskelma]  ADD [SIIRTOSIDOTUSTA] bigint  NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_yo_talous_1_tuloslaskelma'
AND COLUMN_NAME ='SIIRTOSIDOTTUUN')
BEGIN
	ALTER TABLE [sa].[sa_suorat_yo_talous_1_tuloslaskelma]  ADD [SIIRTOSIDOTTUUN] bigint  NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_yo_talous_1_tuloslaskelma'
AND COLUMN_NAME ='SIIRTORAHASTOSTA')
BEGIN
	ALTER TABLE [sa].[sa_suorat_yo_talous_1_tuloslaskelma]  ADD [SIIRTORAHASTOSTA] bigint  NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_yo_talous_1_tuloslaskelma'
AND COLUMN_NAME ='SIIRTORAHASTOON')
BEGIN
	ALTER TABLE [sa].[sa_suorat_yo_talous_1_tuloslaskelma]  ADD [SIIRTORAHASTOON] bigint  NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_yo_talous_1_tuloslaskelma'
AND COLUMN_NAME ='TILAKUSTANNUKSET')
BEGIN
	ALTER TABLE [sa].[sa_suorat_yo_talous_1_tuloslaskelma]  ADD [TILAKUSTANNUKSET] bigint  NULL
END
