USE ANTERO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='dw' and TABLE_NAME='f_amk_talous'
AND COLUMN_NAME ='Konserni')
BEGIN
	ALTER TABLE [dw].[f_amk_talous]  ADD [Konserni] char(1)  NULL
END
