USE ANTERO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_amk_talous_1_tuloslaskelma'
AND COLUMN_NAME ='AVUSTUSTUOTOT')
BEGIN
	ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [AVUSTUSTUOTOT] int  NULL
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_amk_talous_1_tuloslaskelma'
AND COLUMN_NAME ='LIIKTUOTOT')
BEGIN
	ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [LIIKTUOTOT] int  NULL
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_amk_talous_1_tuloslaskelma'
AND COLUMN_NAME ='OSUUSTULOS')
BEGIN
	ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [OSUUSTULOS] int  NULL
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_amk_talous_1_tuloslaskelma'
AND COLUMN_NAME ='ULKLIIKTOIM')
BEGIN
	ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [ULKLIIKTOIM] int  NULL
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_amk_talous_1_tuloslaskelma'
AND COLUMN_NAME ='KVARVONMUUTOS')
BEGIN
	ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [KVARVONMUUTOS] int  NULL
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_amk_talous_1_tuloslaskelma'
AND COLUMN_NAME ='VARSSIJTUOT')
BEGIN
	ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [VARSSIJTUOT] int  NULL
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_amk_talous_1_tuloslaskelma'
AND COLUMN_NAME ='MUUTKORKORAHTUOTOT')
BEGIN
	ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [MUUTKORKORAHTUOTOT] int  NULL
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_amk_talous_1_tuloslaskelma'
AND COLUMN_NAME ='ARVONALENTUMISETPAL')
BEGIN
	ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [ARVONALENTUMISETPAL] int  NULL
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_amk_talous_1_tuloslaskelma'
AND COLUMN_NAME ='RAHOITUSTUOTOT')
BEGIN
	ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [RAHOITUSTUOTOT] int  NULL
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_amk_talous_1_tuloslaskelma'
AND COLUMN_NAME ='SIDOTUT')
BEGIN
	ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [SIDOTUT] int  NULL
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_amk_talous_1_tuloslaskelma'
AND COLUMN_NAME ='SIIRTOSIDOTUSTA')
BEGIN
	ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [SIIRTOSIDOTUSTA] int  NULL
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_amk_talous_1_tuloslaskelma'
AND COLUMN_NAME ='SIIRTOSIDOTTUUN')
BEGIN
	ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [SIIRTOSIDOTTUUN] int  NULL
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_amk_talous_1_tuloslaskelma'
AND COLUMN_NAME ='OMAKATTEISET')
BEGIN
	ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [OMAKATTEISET] int  NULL
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_amk_talous_1_tuloslaskelma'
AND COLUMN_NAME ='SIIRTORAHASTOSTA')
BEGIN
	ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [SIIRTORAHASTOSTA] int  NULL
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_amk_talous_1_tuloslaskelma'
AND COLUMN_NAME ='SIIRTORAHASTOON')
BEGIN
	ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [SIIRTORAHASTOON] int  NULL
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_amk_talous_1_tuloslaskelma'
AND COLUMN_NAME ='VAHEMMISTOOSUUDET')
BEGIN
	ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [VAHEMMISTOOSUUDET] int  NULL
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_amk_talous_1_tuloslaskelma'
AND COLUMN_NAME ='KORKVARSTOIMALV')
BEGIN
	ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [KORKVARSTOIMALV] int  NULL
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_amk_talous_1_tuloslaskelma'
AND COLUMN_NAME ='OKMKOMPENS')
BEGIN
	ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [OKMKOMPENS] int  NULL
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_amk_talous_1_tuloslaskelma'
AND COLUMN_NAME ='HARJOITTELUKOULUJENVM')
BEGIN
	ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [HARJOITTELUKOULUJENVM] int  NULL
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_amk_talous_1_tuloslaskelma'
AND COLUMN_NAME ='MUURAHKOMP')
BEGIN
	ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [MUURAHKOMP] int  NULL
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_amk_talous_1_tuloslaskelma'
AND COLUMN_NAME ='VMRAHHARJKOULU')
BEGIN
	ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [VMRAHHARJKOULU] int  NULL
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_amk_talous_1_tuloslaskelma'
AND COLUMN_NAME ='OKMRAHHARJKOULU')
BEGIN
	ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [OKMRAHHARJKOULU] int  NULL
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_amk_talous_1_tuloslaskelma'
AND COLUMN_NAME ='HARJKOULUKULUYHT')
BEGIN
	ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [HARJKOULUKULUYHT] int  NULL
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_amk_talous_1_tuloslaskelma'
AND COLUMN_NAME ='KONELAITE')
BEGIN
	ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [KONELAITE] int  NULL
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_amk_talous_1_tuloslaskelma'
AND COLUMN_NAME ='KERLAHJKOTITAL')
BEGIN
	ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [KERLAHJKOTITAL] int  NULL
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_amk_talous_1_tuloslaskelma'
AND COLUMN_NAME ='KERLAHJYRI')
BEGIN
	ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [KERLAHJYRI] int  NULL
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_amk_talous_1_tuloslaskelma'
AND COLUMN_NAME ='KERLAHJMUUT')
BEGIN
	ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [KERLAHJMUUT] int  NULL
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_amk_talous_1_tuloslaskelma'
AND COLUMN_NAME ='VARAINHANKINTA')
BEGIN
	ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [VARAINHANKINTA] int  NULL
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_amk_talous_1_tuloslaskelma'
AND COLUMN_NAME ='MUUVARAINHANKINTA')
BEGIN
	ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [MUUVARAINHANKINTA] int  NULL
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_amk_talous_1_tuloslaskelma'
AND COLUMN_NAME ='KERLAHJKULU')
BEGIN
	ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [KERLAHJKULU] int  NULL
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_amk_talous_1_tuloslaskelma'
AND COLUMN_NAME ='VARAINHANKINTAKUL')
BEGIN
	ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [VARAINHANKINTAKUL] int  NULL
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_amk_talous_1_tuloslaskelma'
AND COLUMN_NAME ='MUUTVARAINHANKINTAKUL')
BEGIN
	ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [MUUTVARAINHANKINTAKUL] int  NULL
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_amk_talous_1_tuloslaskelma'
AND COLUMN_NAME ='VARAINHANKINTATUOT')
BEGIN
	ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [VARAINHANKINTATUOT] int  NULL
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_amk_talous_1_tuloslaskelma'
AND COLUMN_NAME ='OSINKOTUOTOT')
BEGIN
	ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [OSINKOTUOTOT] int  NULL
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_amk_talous_1_tuloslaskelma'
AND COLUMN_NAME ='KORKOTUOTOT')
BEGIN
	ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [KORKOTUOTOT] int  NULL
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_amk_talous_1_tuloslaskelma'
AND COLUMN_NAME ='MYYNTITUOTOT')
BEGIN
	ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [MYYNTITUOTOT] int  NULL
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_amk_talous_1_tuloslaskelma'
AND COLUMN_NAME ='VUOKRATUOTOT')
BEGIN
	ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [VUOKRATUOTOT] int  NULL
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_amk_talous_1_tuloslaskelma'
AND COLUMN_NAME ='MUUTTUOTOT_3')
BEGIN
	ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [MUUTTUOTOT_3] int  NULL
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_amk_talous_1_tuloslaskelma'
AND COLUMN_NAME ='KORKOKULUT')
BEGIN
	ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [KORKOKULUT] int  NULL
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_amk_talous_1_tuloslaskelma'
AND COLUMN_NAME ='VUOKRAKULUT')
BEGIN
	ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [VUOKRAKULUT] int  NULL
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_amk_talous_1_tuloslaskelma'
AND COLUMN_NAME ='MYYNTITAPPIOT')
BEGIN
	ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [MYYNTITAPPIOT] int  NULL
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_amk_talous_1_tuloslaskelma'
AND COLUMN_NAME ='LUKUKAUSIMAKSUT')
BEGIN
	ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [LUKUKAUSIMAKSUT] int  NULL
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_amk_talous_1_tuloslaskelma'
AND COLUMN_NAME ='PYSYVAISLUONTOINEN')
BEGIN
	ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [PYSYVAISLUONTOINEN] int  NULL
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_amk_talous_1_tuloslaskelma'
AND COLUMN_NAME ='MUUTMUUTTUOT')
BEGIN
	ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [MUUTMUUTTUOT] int  NULL
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_amk_talous_1_tuloslaskelma'
AND COLUMN_NAME ='KULUTYHT')
BEGIN
	ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [KULUTYHT] int  NULL
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_amk_talous_1_tuloslaskelma'
AND COLUMN_NAME ='MUUTKULUTYHT')
BEGIN
	ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [MUUTKULUTYHT] int  NULL
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_amk_talous_1_tuloslaskelma'
AND COLUMN_NAME ='TILAKUSTANNUKSET')
BEGIN
	ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [TILAKUSTANNUKSET] int  NULL
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_amk_talous_1_tuloslaskelma'
AND COLUMN_NAME ='MUUTVHKULUT')
BEGIN
	ALTER TABLE [sa].[sa_suorat_amk_talous_1_tuloslaskelma]  ALTER COLUMN [MUUTVHKULUT] int  NULL
END
