USE [VipunenTK_DW]
GO

/****** Object:  Table [dbo].[_f_tutkinnon_suorittaneiden_myohempi_koulutus_4_8]    Script Date: 23.6.2022 13:08:14 ******/
DROP TABLE [dbo].[_f_tutkinnon_suorittaneiden_myohempi_koulutus_4_8]
GO

/****** Object:  Table [dbo].[_f_tutkinnon_suorittaneiden_myohempi_koulutus_4_8]    Script Date: 23.6.2022 13:08:14 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[_f_tutkinnon_suorittaneiden_myohempi_koulutus_4_8](
	[tilastovuosi] [nvarchar](4) NULL,
	[tilv_date] [date] NULL,
	[sukupuoli_koodi] [nvarchar](10) NULL,
	[aidinkieli_versio1_koodi] [nvarchar](2) NULL,
	[suorv] [varchar](4) NULL,
	[suorlk] [varchar](1) NULL,
	[suorituskausikoodi] [varchar](8) NULL,
	[koulutusluokitus_avain] [nvarchar](6) NULL,
	[alvv] [varchar](4) NULL,
	[allk] [varchar](1) NULL,
	[aloituskausikoodi] [varchar](8) NULL,
	[oppisopimuskoulutus_koodi] [nvarchar](2) NULL,
	[ammatillisen_koulutuksen_koulutuslaji_koodi] [nvarchar](2) NULL,
	[opetussuunnitelmaperusteinen_koulutus_nayttotutkintoon_valmistava_koulutus_koodi] [nvarchar](2) NULL,
	[ammatillinen_koulutus_ryhma] [nvarchar](10) NULL,
	[ammatillinen_koulutus_ryhma_avain] [nvarchar](10) NULL,
	[nuorten_aikuisten_koulutus_amm_koodi] [nvarchar](2) NULL,
	[ulkom] [nvarchar](2) NULL,
	[syntv] [varchar](4) NULL,
	[ika_avain] [nvarchar](10) NULL,
	[henkiloiden_lkm] [int] NULL,
	[lulkm] [int] NULL,
	[lukoulk] [varchar](6) NULL,
	[lusuorv] [varchar](4) NULL,
	[luaikoul] [varchar](1) NULL,
	[luulkom] [nvarchar](2) NULL,
	[lu_ika] [int] NULL,
	[lu_myohempi_tutkinto_suoritettu] [varchar](1) NOT NULL,
	[ammlkm] [int] NULL,
	[ammkoulk] [varchar](6) NULL,
	[ammsuorv] [varchar](4) NULL,
	[ammoppis] [varchar](1) NULL,
	[amm_sopimusjaksot] [varchar](1) NULL,
	[ammtutklaja] [varchar](1) NULL,
	[ammtutktav] [varchar](1) NULL,
	[ammulkom] [nvarchar](2) NULL,
	[amm_ika] [int] NULL,
	[amm_myohempi_tutkinto_suoritettu] [varchar](1) NOT NULL,
	[opistlkm] [int] NULL,
	[opistkoulk] [varchar](6) NULL,
	[opistsuorv] [varchar](4) NULL,
	[opistulkom] [nvarchar](2) NULL,
	[opist_ika] [int] NULL,
	[opist_myohempi_tutkinto_suoritettu] [varchar](1) NOT NULL,
	[ammkalkm] [int] NULL,
	[ammkakoulk] [varchar](6) NULL,
	[ammkasuorv] [varchar](4) NULL,
	[ammkaulkom] [nvarchar](2) NULL,
	[ammka_ika] [int] NULL,
	[ammka_myohempi_tutkinto_suoritettu] [varchar](1) NOT NULL,
	[amklkm] [int] NULL,
	[amkkoulk] [varchar](6) NULL,
	[amksuorv] [varchar](4) NULL,
	[amkaikoul] [varchar](1) NULL,
	[amkulkom] [nvarchar](2) NULL,
	[amk_ika] [int] NULL,
	[amk_myohempi_tutkinto_suoritettu] [varchar](1) NOT NULL,
	[akklkm] [int] NULL,
	[akkkoulk] [varchar](6) NULL,
	[akksuorv] [varchar](4) NULL,
	[akkulkom] [nvarchar](2) NULL,
	[akk_ika] [int] NULL,
	[akk_myohempi_tutkinto_suoritettu] [varchar](1) NOT NULL,
	[ylamklkm] [int] NULL,
	[ylamkkoulk] [varchar](6) NULL,
	[ylamksuorv] [varchar](4) NULL,
	[ylamkulkom] [nvarchar](2) NULL,
	[ylamk_ika] [int] NULL,
	[ylamk_myohempi_tutkinto_suoritettu] [varchar](1) NOT NULL,
	[ykklkm] [int] NULL,
	[ykkkoulk] [varchar](6) NULL,
	[ykksuorv] [varchar](4) NULL,
	[ykkulkom] [nvarchar](2) NULL,
	[ykk_ika] [int] NULL,
	[ykk_myohempi_tutkinto_suoritettu] [varchar](1) NOT NULL,
	[laakerlkm] [int] NULL,
	[laakerkoulk] [varchar](6) NULL,
	[laakersuorv] [varchar](4) NULL,
	[laakerulkom] [nvarchar](2) NULL,
	[laaker_ika] [int] NULL,
	[laaker_myohempi_tutkinto_suoritettu] [varchar](1) NOT NULL,
	[lislkm] [int] NULL,
	[liskoulk] [varchar](6) NULL,
	[lissuorv] [varchar](4) NULL,
	[lisulkom] [nvarchar](2) NULL,
	[lis_ika] [int] NULL,
	[lis_myohempi_tutkinto_suoritettu] [varchar](1) NOT NULL,
	[tohtlkm] [int] NULL,
	[tohtkoulk] [varchar](6) NULL,
	[tohtsuorv] [varchar](4) NULL,
	[tohtulkom] [nvarchar](2) NULL,
	[toht_ika] [int] NULL,
	[toht_myohempi_tutkinto_suoritettu] [varchar](1) NOT NULL,
	[tietolahde] [nvarchar](50) NULL,
	[rivinumero] [int] NULL,
	[tarkastelujakso_koodi] [nvarchar](20) NOT NULL,
	[tutkintojen_maara_amm_avain] [nvarchar](11) NULL,
	[tutkintojen_maara_amk_avain] [nvarchar](11) NULL,
	[tutkintojen_maara_akk_avain] [nvarchar](11) NULL,
	[tutkintojen_maara_ykk_avain] [nvarchar](11) NULL,
	[tutkinto_suoritettu_lu_avain] [varchar](9) NOT NULL,
	[tutkinto_suoritettu_amm_avain] [varchar](10) NOT NULL,
	[tutkinto_suoritettu_opisto_avain] [varchar](13) NOT NULL,
	[tutkinto_suoritettu_ammka_avain] [varchar](12) NOT NULL,
	[tutkinto_suoritettu_amk_avain] [varchar](10) NOT NULL,
	[tutkinto_suoritettu_akk_avain] [varchar](10) NOT NULL,
	[tutkinto_suoritettu_ylamk_avain] [varchar](11) NOT NULL,
	[tutkinto_suoritettu_ykk_avain] [varchar](10) NOT NULL,
	[tutkinto_suoritettu_laaker_avain] [varchar](13) NOT NULL,
	[tutkinto_suoritettu_lis_avain] [varchar](10) NOT NULL,
	[tutkinto_suoritettu_toht_avain] [varchar](11) NOT NULL,
	[yliopistotutkinto_myohempi_suoritettu] [varchar](1) NULL,
	[yo_jatkotutkinto_myohempi_suoritettu] [varchar](1) NULL,
	[opisto_tai_ammatillisen_korkea_asteen_tutkinto_myohempi_suoritettu] [varchar](1) NULL,
	[korkeakoulututkinto_myohempi_suoritettu] [varchar](1) NULL,
	[toisen_asteen_tutkinto_myohempi_suoritettu] [varchar](1) NULL,
	[ammatillisen_tutkinto_myohempi_suoritettu_ryhma1] [varchar](1) NOT NULL,
	[ammatillisen_tutkinto_myohempi_suoritettu_ryhma2] [varchar](1) NOT NULL,
	[ammatillisen_tutkinto_myohempi_suoritettu_ryhma3] [varchar](1) NOT NULL,
	[lu_sama_myohempi_koulutusala2002_avain] [varchar](34) NOT NULL,
	[amm_sama_myohempi_koulutusala2002_avain] [varchar](35) NOT NULL,
	[opist_sama_myohempi_koulutusala2002_avain] [varchar](37) NOT NULL,
	[ammka_sama_myohempi_koulutusala2002_avain] [varchar](37) NOT NULL,
	[akk_sama_myohempi_koulutusala2002_avain] [varchar](35) NOT NULL,
	[amk_sama_myohempi_koulutusala2002_avain] [varchar](35) NOT NULL,
	[ylamk_sama_myohempi_koulutusala2002_avain] [varchar](37) NOT NULL,
	[ykk_sama_myohempi_koulutusala2002_avain] [varchar](35) NOT NULL,
	[laaker_sama_myohempi_koulutusala2002_avain] [varchar](38) NOT NULL,
	[lis_sama_myohempi_koulutusala2002_avain] [varchar](35) NOT NULL,
	[toht_sama_myohempi_koulutusala2002_avain] [varchar](36) NOT NULL,
	[yliopistotutkinto_sama_myohempi_koulutusala2002_avain] [varchar](49) NOT NULL,
	[yo_jatkotutkinto_sama_myohempi_koulutusala2002_avain] [varchar](48) NOT NULL,
	[opisto_tai_ammatillisen_korkea_asteen_tutkinto_sama_myohempi_koulutusala2002_avain] [varchar](78) NOT NULL,
	[korkeakoulututkinto_sama_myohempi_koulutusala2002_avain] [varchar](51) NOT NULL,
	[toisen_asteen_tutkinto_sama_myohempi_koulutusala2002_avain] [varchar](54) NOT NULL,
	[lu_sama_myohempi_opintoala2002_avain] [varchar](32) NOT NULL,
	[amm_sama_myohempi_opintoala2002_avain] [varchar](33) NOT NULL,
	[opist_sama_myohempi_opintoala2002_avain] [varchar](35) NOT NULL,
	[ammka_sama_myohempi_opintoala2002_avain] [varchar](35) NOT NULL,
	[akk_sama_myohempi_opintoala2002_avain] [varchar](33) NOT NULL,
	[amk_sama_myohempi_opintoala2002_avain] [varchar](33) NOT NULL,
	[ylamk_sama_myohempi_opintoala2002_avain] [varchar](35) NOT NULL,
	[ykk_sama_myohempi_opintoala2002_avain] [varchar](33) NOT NULL,
	[laaker_sama_myohempi_opintoala2002_avain] [varchar](36) NOT NULL,
	[lis_sama_myohempi_opintoala2002_avain] [varchar](33) NOT NULL,
	[toht_sama_myohempi_opintoala2002_avain] [varchar](34) NOT NULL,
	[yliopistotutkinto_sama_myohempi_opintoala2002_avain] [varchar](47) NOT NULL,
	[yo_jatkotutkinto_sama_myohempi_opintoala2002_avain] [varchar](46) NOT NULL,
	[opisto_tai_ammatillisen_korkea_asteen_tutkinto_sama_myohempi_opintoala2002_avain] [varchar](76) NOT NULL,
	[korkeakoulututkinto_sama_myohempi_opintoala2002_avain] [varchar](49) NOT NULL,
	[toisen_asteen_tutkinto_sama_myohempi_opintoala2002_avain] [varchar](52) NOT NULL,
	[lu_sama_myohempi_opintoala1995_avain] [varchar](32) NOT NULL,
	[amm_sama_myohempi_opintoala1995_avain] [varchar](33) NOT NULL,
	[opist_sama_myohempi_opintoala1995_avain] [varchar](35) NOT NULL,
	[ammka_sama_myohempi_opintoala1995_avain] [varchar](35) NOT NULL,
	[akk_sama_myohempi_opintoala1995_avain] [varchar](33) NOT NULL,
	[amk_sama_myohempi_opintoala1995_avain] [varchar](33) NOT NULL,
	[ylamk_sama_myohempi_opintoala1995_avain] [varchar](35) NOT NULL,
	[ykk_sama_myohempi_opintoala1995_avain] [varchar](33) NOT NULL,
	[laaker_sama_myohempi_opintoala1995_avain] [varchar](36) NOT NULL,
	[lis_sama_myohempi_opintoala1995_avain] [varchar](33) NOT NULL,
	[toht_sama_myohempi_opintoala1995_avain] [varchar](34) NOT NULL,
	[yliopistotutkinto_sama_myohempi_opintoala1995_avain] [varchar](47) NOT NULL,
	[yo_jatkotutkinto_sama_myohempi_opintoala1995_avain] [varchar](46) NOT NULL,
	[opisto_tai_ammatillisen_korkea_asteen_tutkinto_sama_myohempi_opintoala1995_avain] [varchar](76) NOT NULL,
	[korkeakoulututkinto_sama_myohempi_opintoala1995_avain] [varchar](49) NOT NULL,
	[toisen_asteen_tutkinto_sama_myohempi_opintoala1995_avain] [varchar](52) NOT NULL,
	[lu_sama_myohempi_iscfibroad2013_avain] [varchar](33) NOT NULL,
	[amm_sama_myohempi_iscfibroad2013_avain] [varchar](34) NOT NULL,
	[opist_sama_myohempi_iscfibroad2013_avain] [varchar](36) NOT NULL,
	[ammka_sama_myohempi_iscfibroad2013_avain] [varchar](36) NOT NULL,
	[akk_sama_myohempi_iscfibroad2013_avain] [varchar](34) NOT NULL,
	[amk_sama_myohempi_iscfibroad2013_avain] [varchar](34) NOT NULL,
	[ylamk_sama_myohempi_iscfibroad2013_avain] [varchar](36) NOT NULL,
	[ykk_sama_myohempi_iscfibroad2013_avain] [varchar](34) NOT NULL,
	[laaker_sama_myohempi_iscfibroad2013_avain] [varchar](37) NOT NULL,
	[lis_sama_myohempi_iscfibroad2013_avain] [varchar](34) NOT NULL,
	[toht_sama_myohempi_iscfibroad2013_avain] [varchar](35) NOT NULL,
	[yliopistotutkinto_sama_myohempi_iscfibroad2013_avain] [varchar](48) NOT NULL,
	[yo_jatkotutkinto_sama_myohempi_iscfibroad2013_avain] [varchar](47) NOT NULL,
	[opisto_tai_ammatillisen_korkea_asteen_tutkinto_sama_myohempi_iscfibroad2013_avain] [varchar](77) NOT NULL,
	[korkeakoulututkinto_sama_myohempi_iscfibroad2013_avain] [varchar](50) NOT NULL,
	[toisen_asteen_tutkinto_sama_myohempi_iscfibroad2013_avain] [varchar](53) NOT NULL,
	[lu_sama_myohempi_iscfinarrow2013_avain] [varchar](34) NOT NULL,
	[amm_sama_myohempi_iscfinarrow2013_avain] [varchar](35) NOT NULL,
	[opist_sama_myohempi_iscfinarrow2013_avain] [varchar](37) NOT NULL,
	[ammka_sama_myohempi_iscfinarrow2013_avain] [varchar](37) NOT NULL,
	[akk_sama_myohempi_iscfinarrow2013_avain] [varchar](35) NOT NULL,
	[amk_sama_myohempi_iscfinarrow2013_avain] [varchar](35) NOT NULL,
	[ylamk_sama_myohempi_iscfinarrow2013_avain] [varchar](37) NOT NULL,
	[ykk_sama_myohempi_iscfinarrow2013_avain] [varchar](35) NOT NULL,
	[laaker_sama_myohempi_iscfinarrow2013_avain] [varchar](38) NOT NULL,
	[lis_sama_myohempi_iscfinarrow2013_avain] [varchar](35) NOT NULL,
	[toht_sama_myohempi_iscfinarrow2013_avain] [varchar](36) NOT NULL,
	[yliopistotutkinto_sama_myohempi_iscfinarrow2013_avain] [varchar](49) NOT NULL,
	[yo_jatkotutkinto_sama_myohempi_iscfinarrow2013_avain] [varchar](48) NOT NULL,
	[opisto_tai_ammatillisen_korkea_asteen_tutkinto_sama_myohempi_iscfinarrow2013_avain] [varchar](78) NOT NULL,
	[korkeakoulututkinto_sama_myohempi_iscfinarrow2013_avain] [varchar](51) NOT NULL,
	[toisen_asteen_tutkinto_sama_myohempi_iscfinarrow2013_avain] [varchar](54) NOT NULL
) ON [PRIMARY]

GO


