USE [VipunenTK_lisatiedot]
GO
/****** Object:  Table [dbo].[hakukohteen_tutkinnon_taso]    Script Date: 26.6.2017 17:40:38 ******/
DROP TABLE IF EXISTS [dbo].[hakukohteen_tutkinnon_taso]
GO
/****** Object:  Table [dbo].[hakukohteen_tutkinnon_taso]    Script Date: 26.6.2017 17:40:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[hakukohteen_tutkinnon_taso]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[hakukohteen_tutkinnon_taso](
	[id] [int] NOT NULL,
	[luotu] [date] NULL,
	[alkaa] [date] NULL,
	[paattyy] [date] NULL,
	[hakukohde_tutkinnon_taso_koodi] [nvarchar](10) NULL,
	[hakukohde_tutkinnon_taso] [nvarchar](100) NULL,
	[hakukohde_tutkinnon_taso_SV] [nvarchar](100) NULL,
	[hakukohde_tutkinnon_taso_EN] [nvarchar](100) NULL,
	[jarjestys_hakukohde_tutkinnon_taso] [nvarchar](10) NULL,
	[hakukohde_tutkinnon_taso_tarkennus_koodi] [nvarchar](10) NULL,
	[hakukohde_tutkinnon_taso_tarkennus] [nvarchar](100) NULL,
	[hakukohde_tutkinnon_taso_tarkennus_SV] [nvarchar](100) NULL,
	[hakukohde_tutkinnon_taso_tarkennus_EN] [nvarchar](100) NULL,
	[jarjestys_hakukohde_tutkinnon_taso_tarkennus] [nvarchar](10) NULL,
	[virhetilanne] [nchar](1) NULL,
	[poistettu] [nchar](1) NULL,
	[tietolahde] [nvarchar](50) NULL,
	[kommentti] [nvarchar](250) NULL
) ON [PRIMARY]
END
GO
INSERT [dbo].[hakukohteen_tutkinnon_taso] ([id], [luotu], [alkaa], [paattyy], [hakukohde_tutkinnon_taso_koodi], [hakukohde_tutkinnon_taso], [hakukohde_tutkinnon_taso_SV], [hakukohde_tutkinnon_taso_EN], [jarjestys_hakukohde_tutkinnon_taso], [hakukohde_tutkinnon_taso_tarkennus_koodi], [hakukohde_tutkinnon_taso_tarkennus], [hakukohde_tutkinnon_taso_tarkennus_SV], [hakukohde_tutkinnon_taso_tarkennus_EN], [jarjestys_hakukohde_tutkinnon_taso_tarkennus], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (-2, CAST(N'2014-09-08' AS Date), CAST(N'1900-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'-2', N'Virhetilanne', N'Feltillstånd', N'Error occurred', N'99', N'-2', N'Virhetilanne', N'Feltillstånd', N'Error occurred', N'99', N'K', N'0', N'Manuaalinen', N'CSC Jarmo')
GO
INSERT [dbo].[hakukohteen_tutkinnon_taso] ([id], [luotu], [alkaa], [paattyy], [hakukohde_tutkinnon_taso_koodi], [hakukohde_tutkinnon_taso], [hakukohde_tutkinnon_taso_SV], [hakukohde_tutkinnon_taso_EN], [jarjestys_hakukohde_tutkinnon_taso], [hakukohde_tutkinnon_taso_tarkennus_koodi], [hakukohde_tutkinnon_taso_tarkennus], [hakukohde_tutkinnon_taso_tarkennus_SV], [hakukohde_tutkinnon_taso_tarkennus_EN], [jarjestys_hakukohde_tutkinnon_taso_tarkennus], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (-1, CAST(N'2014-09-08' AS Date), CAST(N'1900-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'-1', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'-1', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'K', N'0', N'Manuaalinen', N'CSC Jarmo')
GO
INSERT [dbo].[hakukohteen_tutkinnon_taso] ([id], [luotu], [alkaa], [paattyy], [hakukohde_tutkinnon_taso_koodi], [hakukohde_tutkinnon_taso], [hakukohde_tutkinnon_taso_SV], [hakukohde_tutkinnon_taso_EN], [jarjestys_hakukohde_tutkinnon_taso], [hakukohde_tutkinnon_taso_tarkennus_koodi], [hakukohde_tutkinnon_taso_tarkennus], [hakukohde_tutkinnon_taso_tarkennus_SV], [hakukohde_tutkinnon_taso_tarkennus_EN], [jarjestys_hakukohde_tutkinnon_taso_tarkennus], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (1, CAST(N'2014-09-08' AS Date), CAST(N'1900-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'YO05', N'Alempi korkeakoulututkinto', N'Lägre högskoleexamen', N'Bachelor''s degree', N'11', N'YOTA1', N'II syklin haku', N'Ansökan i cykel II', N'II cycle application', N'32', N'E', N'0', N'Manuaalinen', N'OKM Jukka')
GO
INSERT [dbo].[hakukohteen_tutkinnon_taso] ([id], [luotu], [alkaa], [paattyy], [hakukohde_tutkinnon_taso_koodi], [hakukohde_tutkinnon_taso], [hakukohde_tutkinnon_taso_SV], [hakukohde_tutkinnon_taso_EN], [jarjestys_hakukohde_tutkinnon_taso], [hakukohde_tutkinnon_taso_tarkennus_koodi], [hakukohde_tutkinnon_taso_tarkennus], [hakukohde_tutkinnon_taso_tarkennus_SV], [hakukohde_tutkinnon_taso_tarkennus_EN], [jarjestys_hakukohde_tutkinnon_taso_tarkennus], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (2, CAST(N'2014-09-08' AS Date), CAST(N'1900-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'YO05', N'Alempi korkeakoulututkinto', N'Lägre högskoleexamen', N'Bachelor''s degree', N'11', N'YOTA2', N'I syklin haku', N'Ansökan i cykel I', N'I cycle application', N'31', N'E', N'0', N'Manuaalinen', N'OKM Jukka')
GO
INSERT [dbo].[hakukohteen_tutkinnon_taso] ([id], [luotu], [alkaa], [paattyy], [hakukohde_tutkinnon_taso_koodi], [hakukohde_tutkinnon_taso], [hakukohde_tutkinnon_taso_SV], [hakukohde_tutkinnon_taso_EN], [jarjestys_hakukohde_tutkinnon_taso], [hakukohde_tutkinnon_taso_tarkennus_koodi], [hakukohde_tutkinnon_taso_tarkennus], [hakukohde_tutkinnon_taso_tarkennus_SV], [hakukohde_tutkinnon_taso_tarkennus_EN], [jarjestys_hakukohde_tutkinnon_taso_tarkennus], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (3, CAST(N'2014-09-08' AS Date), CAST(N'1900-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'YO06', N'Ylempi korkeakoulututkinto', N'Högre högskoleexamen', N'Master''s degree', N'12', N'YOTA1', N'II syklin haku', N'Ansökan i cykel II', N'II cycle application', N'32', N'E', N'0', N'Manuaalinen', N'OKM Jukka')
GO
INSERT [dbo].[hakukohteen_tutkinnon_taso] ([id], [luotu], [alkaa], [paattyy], [hakukohde_tutkinnon_taso_koodi], [hakukohde_tutkinnon_taso], [hakukohde_tutkinnon_taso_SV], [hakukohde_tutkinnon_taso_EN], [jarjestys_hakukohde_tutkinnon_taso], [hakukohde_tutkinnon_taso_tarkennus_koodi], [hakukohde_tutkinnon_taso_tarkennus], [hakukohde_tutkinnon_taso_tarkennus_SV], [hakukohde_tutkinnon_taso_tarkennus_EN], [jarjestys_hakukohde_tutkinnon_taso_tarkennus], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (4, CAST(N'2014-09-08' AS Date), CAST(N'1900-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'YO06', N'Ylempi korkeakoulututkinto', N'Högre högskoleexamen', N'Master''s degree', N'12', N'YOTA2', N'I syklin haku', N'Ansökan i cykel I', N'I cycle application', N'31', N'E', N'0', N'Manuaalinen', N'OKM Jukka')
GO
INSERT [dbo].[hakukohteen_tutkinnon_taso] ([id], [luotu], [alkaa], [paattyy], [hakukohde_tutkinnon_taso_koodi], [hakukohde_tutkinnon_taso], [hakukohde_tutkinnon_taso_SV], [hakukohde_tutkinnon_taso_EN], [jarjestys_hakukohde_tutkinnon_taso], [hakukohde_tutkinnon_taso_tarkennus_koodi], [hakukohde_tutkinnon_taso_tarkennus], [hakukohde_tutkinnon_taso_tarkennus_SV], [hakukohde_tutkinnon_taso_tarkennus_EN], [jarjestys_hakukohde_tutkinnon_taso_tarkennus], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (5, CAST(N'2014-09-08' AS Date), CAST(N'1900-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'YO05', N'Alempi korkeakoulututkinto', N'Lägre högskoleexamen', N'Bachelor''s degree', N'11', N'-1', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'E', N'0', N'Manuaalinen', N'CSC Jarmo')
GO
INSERT [dbo].[hakukohteen_tutkinnon_taso] ([id], [luotu], [alkaa], [paattyy], [hakukohde_tutkinnon_taso_koodi], [hakukohde_tutkinnon_taso], [hakukohde_tutkinnon_taso_SV], [hakukohde_tutkinnon_taso_EN], [jarjestys_hakukohde_tutkinnon_taso], [hakukohde_tutkinnon_taso_tarkennus_koodi], [hakukohde_tutkinnon_taso_tarkennus], [hakukohde_tutkinnon_taso_tarkennus_SV], [hakukohde_tutkinnon_taso_tarkennus_EN], [jarjestys_hakukohde_tutkinnon_taso_tarkennus], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (6, CAST(N'2014-09-08' AS Date), CAST(N'1900-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'YO06', N'Ylempi korkeakoulututkinto', N'Högre högskoleexamen', N'Master''s degree', N'12', N'-1', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'E', N'0', N'Manuaalinen', N'CSC Jarmo')
GO
INSERT [dbo].[hakukohteen_tutkinnon_taso] ([id], [luotu], [alkaa], [paattyy], [hakukohde_tutkinnon_taso_koodi], [hakukohde_tutkinnon_taso], [hakukohde_tutkinnon_taso_SV], [hakukohde_tutkinnon_taso_EN], [jarjestys_hakukohde_tutkinnon_taso], [hakukohde_tutkinnon_taso_tarkennus_koodi], [hakukohde_tutkinnon_taso_tarkennus], [hakukohde_tutkinnon_taso_tarkennus_SV], [hakukohde_tutkinnon_taso_tarkennus_EN], [jarjestys_hakukohde_tutkinnon_taso_tarkennus], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (7, CAST(N'2014-09-08' AS Date), CAST(N'1900-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'-1', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'1', N'II syklin haku', N'Ansökan i cykel II', N'II cycle application', N'32', N'E', N'0', N'Manuaalinen', N'OKM Jukka')
GO
INSERT [dbo].[hakukohteen_tutkinnon_taso] ([id], [luotu], [alkaa], [paattyy], [hakukohde_tutkinnon_taso_koodi], [hakukohde_tutkinnon_taso], [hakukohde_tutkinnon_taso_SV], [hakukohde_tutkinnon_taso_EN], [jarjestys_hakukohde_tutkinnon_taso], [hakukohde_tutkinnon_taso_tarkennus_koodi], [hakukohde_tutkinnon_taso_tarkennus], [hakukohde_tutkinnon_taso_tarkennus_SV], [hakukohde_tutkinnon_taso_tarkennus_EN], [jarjestys_hakukohde_tutkinnon_taso_tarkennus], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (8, CAST(N'2014-09-08' AS Date), CAST(N'1900-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'-1', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'2', N'I syklin haku', N'Ansökan i cykel I', N'I cycle application', N'31', N'E', N'0', N'Manuaalinen', N'OKM Jukka')
GO
INSERT [dbo].[hakukohteen_tutkinnon_taso] ([id], [luotu], [alkaa], [paattyy], [hakukohde_tutkinnon_taso_koodi], [hakukohde_tutkinnon_taso], [hakukohde_tutkinnon_taso_SV], [hakukohde_tutkinnon_taso_EN], [jarjestys_hakukohde_tutkinnon_taso], [hakukohde_tutkinnon_taso_tarkennus_koodi], [hakukohde_tutkinnon_taso_tarkennus], [hakukohde_tutkinnon_taso_tarkennus_SV], [hakukohde_tutkinnon_taso_tarkennus_EN], [jarjestys_hakukohde_tutkinnon_taso_tarkennus], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (9, CAST(N'2014-09-17' AS Date), CAST(N'1900-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'AMK1', N'Amk-tutkinto', N'YH-examen', N'Polytechnic degree', N'21', N'AMKTA1', N'Amk-tutkintoon johtava nuorten koulutus', N'Utbildning för unga som leder till YH-examen', N'Youth education leading to a polytechnic degree', N'41', N'E', N'0', N'Manuaalinen', N'CSC Jarmo')
GO
INSERT [dbo].[hakukohteen_tutkinnon_taso] ([id], [luotu], [alkaa], [paattyy], [hakukohde_tutkinnon_taso_koodi], [hakukohde_tutkinnon_taso], [hakukohde_tutkinnon_taso_SV], [hakukohde_tutkinnon_taso_EN], [jarjestys_hakukohde_tutkinnon_taso], [hakukohde_tutkinnon_taso_tarkennus_koodi], [hakukohde_tutkinnon_taso_tarkennus], [hakukohde_tutkinnon_taso_tarkennus_SV], [hakukohde_tutkinnon_taso_tarkennus_EN], [jarjestys_hakukohde_tutkinnon_taso_tarkennus], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (10, CAST(N'2014-09-17' AS Date), CAST(N'1900-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'AMK2', N'Amk-tutkinto', N'YH-examen', N'Polytechnic degree', N'21', N'AMKTA2', N'Amk-tutkintoon johtava aikuiskoulutus', N'Vuxenutbildning som leder till en examen', N'Adult education leading to a polytechnic degree', N'42', N'E', N'0', N'Manuaalinen', N'CSC Jarmo')
GO
INSERT [dbo].[hakukohteen_tutkinnon_taso] ([id], [luotu], [alkaa], [paattyy], [hakukohde_tutkinnon_taso_koodi], [hakukohde_tutkinnon_taso], [hakukohde_tutkinnon_taso_SV], [hakukohde_tutkinnon_taso_EN], [jarjestys_hakukohde_tutkinnon_taso], [hakukohde_tutkinnon_taso_tarkennus_koodi], [hakukohde_tutkinnon_taso_tarkennus], [hakukohde_tutkinnon_taso_tarkennus_SV], [hakukohde_tutkinnon_taso_tarkennus_EN], [jarjestys_hakukohde_tutkinnon_taso_tarkennus], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (11, CAST(N'2014-09-17' AS Date), CAST(N'1900-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'AMK3', N'Ylempi amk-tutkinto', N'Högre YH-examen', N'Polytechnic Master''s degree', N'23', N'AMKTA3', N'Ylempään amk-tutkintoon johtava koulutus', N'Utbildning för högre YH-examen', N'Education leading to polytechnic Master''s degree', N'43', N'E', N'0', N'Manuaalinen', N'CSC Jarmo')
GO
INSERT [dbo].[hakukohteen_tutkinnon_taso] ([id], [luotu], [alkaa], [paattyy], [hakukohde_tutkinnon_taso_koodi], [hakukohde_tutkinnon_taso], [hakukohde_tutkinnon_taso_SV], [hakukohde_tutkinnon_taso_EN], [jarjestys_hakukohde_tutkinnon_taso], [hakukohde_tutkinnon_taso_tarkennus_koodi], [hakukohde_tutkinnon_taso_tarkennus], [hakukohde_tutkinnon_taso_tarkennus_SV], [hakukohde_tutkinnon_taso_tarkennus_EN], [jarjestys_hakukohde_tutkinnon_taso_tarkennus], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (-2, CAST(N'2014-09-08' AS Date), CAST(N'1900-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'-2', N'Virhetilanne', N'Feltillstånd', N'Error occurred', N'99', N'-2', N'Virhetilanne', N'Feltillstånd', N'Error occurred', N'99', N'K', N'0', N'Manuaalinen', N'CSC Jarmo')
GO
INSERT [dbo].[hakukohteen_tutkinnon_taso] ([id], [luotu], [alkaa], [paattyy], [hakukohde_tutkinnon_taso_koodi], [hakukohde_tutkinnon_taso], [hakukohde_tutkinnon_taso_SV], [hakukohde_tutkinnon_taso_EN], [jarjestys_hakukohde_tutkinnon_taso], [hakukohde_tutkinnon_taso_tarkennus_koodi], [hakukohde_tutkinnon_taso_tarkennus], [hakukohde_tutkinnon_taso_tarkennus_SV], [hakukohde_tutkinnon_taso_tarkennus_EN], [jarjestys_hakukohde_tutkinnon_taso_tarkennus], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (-1, CAST(N'2014-09-08' AS Date), CAST(N'1900-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'-1', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'-1', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'K', N'0', N'Manuaalinen', N'CSC Jarmo')
GO
INSERT [dbo].[hakukohteen_tutkinnon_taso] ([id], [luotu], [alkaa], [paattyy], [hakukohde_tutkinnon_taso_koodi], [hakukohde_tutkinnon_taso], [hakukohde_tutkinnon_taso_SV], [hakukohde_tutkinnon_taso_EN], [jarjestys_hakukohde_tutkinnon_taso], [hakukohde_tutkinnon_taso_tarkennus_koodi], [hakukohde_tutkinnon_taso_tarkennus], [hakukohde_tutkinnon_taso_tarkennus_SV], [hakukohde_tutkinnon_taso_tarkennus_EN], [jarjestys_hakukohde_tutkinnon_taso_tarkennus], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (1, CAST(N'2014-09-08' AS Date), CAST(N'1900-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'YO05', N'Alempi korkeakoulututkinto', N'Lägre högskoleexamen', N'Bachelor''s degree', N'11', N'YOTA1', N'II syklin haku', N'Ansökan i cykel II', N'II cycle application', N'32', N'E', N'0', N'Manuaalinen', N'OKM Jukka')
GO
INSERT [dbo].[hakukohteen_tutkinnon_taso] ([id], [luotu], [alkaa], [paattyy], [hakukohde_tutkinnon_taso_koodi], [hakukohde_tutkinnon_taso], [hakukohde_tutkinnon_taso_SV], [hakukohde_tutkinnon_taso_EN], [jarjestys_hakukohde_tutkinnon_taso], [hakukohde_tutkinnon_taso_tarkennus_koodi], [hakukohde_tutkinnon_taso_tarkennus], [hakukohde_tutkinnon_taso_tarkennus_SV], [hakukohde_tutkinnon_taso_tarkennus_EN], [jarjestys_hakukohde_tutkinnon_taso_tarkennus], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (2, CAST(N'2014-09-08' AS Date), CAST(N'1900-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'YO05', N'Alempi korkeakoulututkinto', N'Lägre högskoleexamen', N'Bachelor''s degree', N'11', N'YOTA2', N'I syklin haku', N'Ansökan i cykel I', N'I cycle application', N'31', N'E', N'0', N'Manuaalinen', N'OKM Jukka')
GO
INSERT [dbo].[hakukohteen_tutkinnon_taso] ([id], [luotu], [alkaa], [paattyy], [hakukohde_tutkinnon_taso_koodi], [hakukohde_tutkinnon_taso], [hakukohde_tutkinnon_taso_SV], [hakukohde_tutkinnon_taso_EN], [jarjestys_hakukohde_tutkinnon_taso], [hakukohde_tutkinnon_taso_tarkennus_koodi], [hakukohde_tutkinnon_taso_tarkennus], [hakukohde_tutkinnon_taso_tarkennus_SV], [hakukohde_tutkinnon_taso_tarkennus_EN], [jarjestys_hakukohde_tutkinnon_taso_tarkennus], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (3, CAST(N'2014-09-08' AS Date), CAST(N'1900-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'YO06', N'Ylempi korkeakoulututkinto', N'Högre högskoleexamen', N'Master''s degree', N'12', N'YOTA1', N'II syklin haku', N'Ansökan i cykel II', N'II cycle application', N'32', N'E', N'0', N'Manuaalinen', N'OKM Jukka')
GO
INSERT [dbo].[hakukohteen_tutkinnon_taso] ([id], [luotu], [alkaa], [paattyy], [hakukohde_tutkinnon_taso_koodi], [hakukohde_tutkinnon_taso], [hakukohde_tutkinnon_taso_SV], [hakukohde_tutkinnon_taso_EN], [jarjestys_hakukohde_tutkinnon_taso], [hakukohde_tutkinnon_taso_tarkennus_koodi], [hakukohde_tutkinnon_taso_tarkennus], [hakukohde_tutkinnon_taso_tarkennus_SV], [hakukohde_tutkinnon_taso_tarkennus_EN], [jarjestys_hakukohde_tutkinnon_taso_tarkennus], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (4, CAST(N'2014-09-08' AS Date), CAST(N'1900-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'YO06', N'Ylempi korkeakoulututkinto', N'Högre högskoleexamen', N'Master''s degree', N'12', N'YOTA2', N'I syklin haku', N'Ansökan i cykel I', N'I cycle application', N'31', N'E', N'0', N'Manuaalinen', N'OKM Jukka')
GO
INSERT [dbo].[hakukohteen_tutkinnon_taso] ([id], [luotu], [alkaa], [paattyy], [hakukohde_tutkinnon_taso_koodi], [hakukohde_tutkinnon_taso], [hakukohde_tutkinnon_taso_SV], [hakukohde_tutkinnon_taso_EN], [jarjestys_hakukohde_tutkinnon_taso], [hakukohde_tutkinnon_taso_tarkennus_koodi], [hakukohde_tutkinnon_taso_tarkennus], [hakukohde_tutkinnon_taso_tarkennus_SV], [hakukohde_tutkinnon_taso_tarkennus_EN], [jarjestys_hakukohde_tutkinnon_taso_tarkennus], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (5, CAST(N'2014-09-08' AS Date), CAST(N'1900-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'YO05', N'Alempi korkeakoulututkinto', N'Lägre högskoleexamen', N'Bachelor''s degree', N'11', N'-1', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'E', N'0', N'Manuaalinen', N'CSC Jarmo')
GO
INSERT [dbo].[hakukohteen_tutkinnon_taso] ([id], [luotu], [alkaa], [paattyy], [hakukohde_tutkinnon_taso_koodi], [hakukohde_tutkinnon_taso], [hakukohde_tutkinnon_taso_SV], [hakukohde_tutkinnon_taso_EN], [jarjestys_hakukohde_tutkinnon_taso], [hakukohde_tutkinnon_taso_tarkennus_koodi], [hakukohde_tutkinnon_taso_tarkennus], [hakukohde_tutkinnon_taso_tarkennus_SV], [hakukohde_tutkinnon_taso_tarkennus_EN], [jarjestys_hakukohde_tutkinnon_taso_tarkennus], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (6, CAST(N'2014-09-08' AS Date), CAST(N'1900-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'YO06', N'Ylempi korkeakoulututkinto', N'Högre högskoleexamen', N'Master''s degree', N'12', N'-1', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'E', N'0', N'Manuaalinen', N'CSC Jarmo')
GO
INSERT [dbo].[hakukohteen_tutkinnon_taso] ([id], [luotu], [alkaa], [paattyy], [hakukohde_tutkinnon_taso_koodi], [hakukohde_tutkinnon_taso], [hakukohde_tutkinnon_taso_SV], [hakukohde_tutkinnon_taso_EN], [jarjestys_hakukohde_tutkinnon_taso], [hakukohde_tutkinnon_taso_tarkennus_koodi], [hakukohde_tutkinnon_taso_tarkennus], [hakukohde_tutkinnon_taso_tarkennus_SV], [hakukohde_tutkinnon_taso_tarkennus_EN], [jarjestys_hakukohde_tutkinnon_taso_tarkennus], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (7, CAST(N'2014-09-08' AS Date), CAST(N'1900-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'-1', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'1', N'II syklin haku', N'Ansökan i cykel II', N'II cycle application', N'32', N'E', N'0', N'Manuaalinen', N'OKM Jukka')
GO
INSERT [dbo].[hakukohteen_tutkinnon_taso] ([id], [luotu], [alkaa], [paattyy], [hakukohde_tutkinnon_taso_koodi], [hakukohde_tutkinnon_taso], [hakukohde_tutkinnon_taso_SV], [hakukohde_tutkinnon_taso_EN], [jarjestys_hakukohde_tutkinnon_taso], [hakukohde_tutkinnon_taso_tarkennus_koodi], [hakukohde_tutkinnon_taso_tarkennus], [hakukohde_tutkinnon_taso_tarkennus_SV], [hakukohde_tutkinnon_taso_tarkennus_EN], [jarjestys_hakukohde_tutkinnon_taso_tarkennus], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (8, CAST(N'2014-09-08' AS Date), CAST(N'1900-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'-1', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'2', N'I syklin haku', N'Ansökan i cykel I', N'I cycle application', N'31', N'E', N'0', N'Manuaalinen', N'OKM Jukka')
GO
INSERT [dbo].[hakukohteen_tutkinnon_taso] ([id], [luotu], [alkaa], [paattyy], [hakukohde_tutkinnon_taso_koodi], [hakukohde_tutkinnon_taso], [hakukohde_tutkinnon_taso_SV], [hakukohde_tutkinnon_taso_EN], [jarjestys_hakukohde_tutkinnon_taso], [hakukohde_tutkinnon_taso_tarkennus_koodi], [hakukohde_tutkinnon_taso_tarkennus], [hakukohde_tutkinnon_taso_tarkennus_SV], [hakukohde_tutkinnon_taso_tarkennus_EN], [jarjestys_hakukohde_tutkinnon_taso_tarkennus], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (12, CAST(N'2017-06-26' AS Date), CAST(N'1900-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'AMK1', N'Amk-tutkinto', N'YH-examen', N'Polytechnic degree', N'21', N'-1', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'E', N'0', N'Manuaalinen', N'CSC Anssi')
GO
INSERT [dbo].[hakukohteen_tutkinnon_taso] ([id], [luotu], [alkaa], [paattyy], [hakukohde_tutkinnon_taso_koodi], [hakukohde_tutkinnon_taso], [hakukohde_tutkinnon_taso_SV], [hakukohde_tutkinnon_taso_EN], [jarjestys_hakukohde_tutkinnon_taso], [hakukohde_tutkinnon_taso_tarkennus_koodi], [hakukohde_tutkinnon_taso_tarkennus], [hakukohde_tutkinnon_taso_tarkennus_SV], [hakukohde_tutkinnon_taso_tarkennus_EN], [jarjestys_hakukohde_tutkinnon_taso_tarkennus], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (13, CAST(N'2017-06-26' AS Date), CAST(N'1900-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'AMK3', N'Ylempi amk-tutkinto', N'Högre YH-examen', N'Polytechnic Master''s degree', N'23', N'-1', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'E', N'0', N'Manuaalinen', N'CSC Anssi')
GO
INSERT [dbo].[hakukohteen_tutkinnon_taso] ([id], [luotu], [alkaa], [paattyy], [hakukohde_tutkinnon_taso_koodi], [hakukohde_tutkinnon_taso], [hakukohde_tutkinnon_taso_SV], [hakukohde_tutkinnon_taso_EN], [jarjestys_hakukohde_tutkinnon_taso], [hakukohde_tutkinnon_taso_tarkennus_koodi], [hakukohde_tutkinnon_taso_tarkennus], [hakukohde_tutkinnon_taso_tarkennus_SV], [hakukohde_tutkinnon_taso_tarkennus_EN], [jarjestys_hakukohde_tutkinnon_taso_tarkennus], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (9, CAST(N'2014-09-17' AS Date), CAST(N'1900-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'AMK1', N'Amk-tutkinto', N'YH-examen', N'Polytechnic degree', N'21', N'AMKTA1', N'Amk-tutkintoon johtava nuorten koulutus', N'Utbildning för unga som leder till YH-examen', N'Youth education leading to a polytechnic degree', N'41', N'E', N'0', N'Manuaalinen', N'CSC Jarmo')
GO
INSERT [dbo].[hakukohteen_tutkinnon_taso] ([id], [luotu], [alkaa], [paattyy], [hakukohde_tutkinnon_taso_koodi], [hakukohde_tutkinnon_taso], [hakukohde_tutkinnon_taso_SV], [hakukohde_tutkinnon_taso_EN], [jarjestys_hakukohde_tutkinnon_taso], [hakukohde_tutkinnon_taso_tarkennus_koodi], [hakukohde_tutkinnon_taso_tarkennus], [hakukohde_tutkinnon_taso_tarkennus_SV], [hakukohde_tutkinnon_taso_tarkennus_EN], [jarjestys_hakukohde_tutkinnon_taso_tarkennus], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (10, CAST(N'2014-09-17' AS Date), CAST(N'1900-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'AMK2', N'Amk-tutkinto', N'YH-examen', N'Polytechnic degree', N'21', N'AMKTA2', N'Amk-tutkintoon johtava aikuiskoulutus', N'Vuxenutbildning som leder till en examen', N'Adult education leading to a polytechnic degree', N'42', N'E', N'0', N'Manuaalinen', N'CSC Jarmo')
GO
INSERT [dbo].[hakukohteen_tutkinnon_taso] ([id], [luotu], [alkaa], [paattyy], [hakukohde_tutkinnon_taso_koodi], [hakukohde_tutkinnon_taso], [hakukohde_tutkinnon_taso_SV], [hakukohde_tutkinnon_taso_EN], [jarjestys_hakukohde_tutkinnon_taso], [hakukohde_tutkinnon_taso_tarkennus_koodi], [hakukohde_tutkinnon_taso_tarkennus], [hakukohde_tutkinnon_taso_tarkennus_SV], [hakukohde_tutkinnon_taso_tarkennus_EN], [jarjestys_hakukohde_tutkinnon_taso_tarkennus], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (11, CAST(N'2014-09-17' AS Date), CAST(N'1900-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'AMK3', N'Ylempi amk-tutkinto', N'Högre YH-examen', N'Polytechnic Master''s degree', N'23', N'AMKTA3', N'Ylempään amk-tutkintoon johtava koulutus', N'Utbildning för högre YH-examen', N'Education leading to polytechnic Master''s degree', N'43', N'E', N'0', N'Manuaalinen', N'CSC Jarmo')
GO

USE [ANTERO]

