USE [VipunenTK]
GO

/****** Object:  View [dbo].[v_f_tab_tutkinnon_suorittaneiden_myohempi_koulutus_yhteiset]    Script Date: 30.6.2023 18:41:29 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



DROP VIEW IF EXISTS [dbo].[v_f_tab_tutkinnon_suorittaneiden_myohempi_koulutus_4_8_yhteiset]
GO

CREATE VIEW [dbo].[v_f_tab_tutkinnon_suorittaneiden_myohempi_koulutus_4_8_yhteiset] AS

--luetaan taulu sellaisenaan pois lukien id-sarake, joka vain veisi kuutiossa tilaa
SELECT [henkiloiden_lkm]
      ,[lu_henkiloiden_lkm]
      ,[amm_henkiloiden_lkm]
      ,[opist_henkiloiden_lkm]
      ,[ammka_henkiloiden_lkm]
      ,[amk_henkiloiden_lkm]
      ,[akk_henkiloiden_lkm]
      ,[ylamklkm_henkiloiden_lkm]
      ,[ykk_henkiloiden_lkm]
      ,[laaker_henkiloiden_lkm]
      ,[lis_henkiloiden_lkm]
      ,[toht_henkiloiden_lkm]
      ,[myoh_yliop_lkm]
      ,[myoh_yo_jatko_lkm]
      ,[myoh_opisto_ammkork_lkm]
      ,[myoh_kork_lkm]
      ,[myoh_toinenaste_lkm]
      ,[myoh_ammryhma1_lkm]
      ,[myoh_ammryhma2_lkm]
      ,[myoh_ammryhma3_lkm]
      ,[Tilastovuosi]
      ,[Tarkastelujakso]
      ,[Äidinkieli]
      ,[Koulutusnimike]
      ,[Sukupuoli]
      ,[Tutkinnon suoritusvuosi]
      ,[Tutkinnon suorituslukukausi]
      ,[Aloitusvuosi]
      ,[Aloituslukukausi]
      ,[Syntymävuosi]
      ,[Yo-tutkinnon suoritusvuosi]
      ,[Amm. tutkinnon suoritusvuosi]
      ,[Opistoast. tutkinnon suoritusvuosi]
      ,[Amm. kork.asteen tutk. suoritusvuosi]
      ,[Amk-tutkinnon suoritusvuosi]
      ,[Alemman kk-tutk. suoritusvuosi]
      ,[Ylemmän amk-tutk. suoritusvuosi]
      ,[Ylemmän kk-tutk. suoritusvuosi]
      ,[Lääk. erikois.tutk. suoritusvuosi]
      ,[Lisensiaatin tutk. suoritusvuosi]
      ,[Tohtorin tutk. suorituvuosi]
      ,[Oppisopimuskoulutus]
      ,[Tutkintotyyppi]
      ,[Järjestämistapa]
      ,[Nuorten/aikuisten koulutus]
      ,[Ikä]
      ,[Ikäryhmä]
      ,[Yo-tutkinnon koulutusnimike]
      ,[Myöh. suoritettu yo-tutkinto]
      ,[Kulunut aika alkup. tutkinnosta (yo)]
      ,[Nuorten/aikuisten koulutus (yo)]
      ,[Amm. tutkinnon koulutusnimike]
      ,[Myöh. suoritettu amm. tutkinto]
      ,[Kulunut aika alkup. tutkinnosta (amm)]
      ,[Amm. tutkinnon tutkintotyyppi]
      ,[Amm. tutkinnon järjestämistapa]
      ,[Amm. tutkinto oppisopimuskoul.]
      ,[Amm. tutkinnon koulutus- ja oppisopimusjaksot]
      ,[Amm. tutkintojen määrä]
      ,[Amm. koulutuksen ryhmät]
      ,[Opistoast. tutkinnon koulutusnimike]
      ,[Myöh. suoritettu opistoast. tutkinto]
      ,[Kulunut aika alkup. tutkinnosta (opisto)]
      ,[Amm. kork.asteen tutk. koulutusnimike]
      ,[Myöh. suoritettu amm. kork.asteen tutkinto]
      ,[Kulunut aika alkup. tutkinnosta (ammka)]
      ,[Amk-tutkinnon koulutusnimike]
      ,[Myöh. suoritettu amk-tutkinto]
      ,[Kulunut aika alkup. tutkinnosta (amk)]
      ,[Amk-tutkintojen määrä]
      ,[Nuorten/aikuisten koulutus (amk)]
      ,[Alemman kk-tutk. koulutusnimike]
      ,[Myöh. suoritettu alempi kk-tutkinto]
      ,[Kulunut aika alkup. tutkinnosta (alempi kk)]
      ,[Alempien kk-tutkintojen määrä]
      ,[Ylemmän amk-tutk. koulutusnimike]
      ,[Myöh. suoritettu ylempi amk-tutkinto]
      ,[Kulunut aika alkup. tutkinnosta (ylempi amk)]
      ,[Ylemmän kk-tutk. koulutusnimike]
      ,[Myöh. suoritettu ylempi kk-tutkinto]
      ,[Kulunut aika alkup. tutkinnosta (ylempi kk)]
      ,[Ylempien kk-tutkintojen määrä]
      ,[Lääk. erikois.tutk. koulutusnimike]
      ,[Myöh. suoritettu lääk. erikois.tutk.]
      ,[Kulunut aika alkup. tutkinnosta (lääk. erik.)]
      ,[Lisensiaatin tutk. koulutusnimike]
      ,[Myöh. suoritettu lisensiaatin tutk.]
      ,[Kulunut aika alkup. tutkinnosta (lis.)]
      ,[Tohtorin tutk. koulutusnimike]
      ,[Myöh. suoritettu tohtorin tutk.]
      ,[Kulunut aika alkup. tutkinnosta (toht.)]
      ,[Myöh. suoritettu yliopistotutkinto]
      ,[Myöh. suoritettu yo-jatkotutkinto]
      ,[Myöh. suoritettu opistoast. tai amm. kork.ast. tutkinto]
      ,[Myöh. suoritettu korkeakoulututkinto]
      ,[Myöh. suoritettu toisen asteen tutkinto]
      ,[Myöh. suoritettu amm. tutkinto (ryhmä 1)]
      ,[Myöh. suoritettu amm. tutkinto (ryhmä 2)]
      ,[Myöh. suoritettu amm. tutkinto (ryhmä 3)]
      ,[Tutk. suor. ulkomailla]
      ,[Myöh. tutk. suor. ulkomailla (yo)]
      ,[Myöh. tutk. suor. ulkomailla (amm)]
      ,[Myöh. tutk. suor. ulkomailla (opisto)]
      ,[Myöh. tutk. suor. ulkomailla (ammka)]
      ,[Myöh. tutk. suor. ulkomailla (amk)]
      ,[Myöh. tutk. suor. ulkomailla (alempi kk)]
      ,[Myöh. tutk. suor. ulkomailla (ylempi amk)]
      ,[Myöh. tutk. suor. ulkomailla (ylempi kk)]
      ,[Myöh. tutk. suor. ulkomailla (lääk. erik.)]
      ,[Myöh. tutk. suor. ulkomailla (lis.)]
      ,[Myöh. tutk. suor. ulkomailla (toht.)]
      ,[Yo-tutkinto samalla koul.alalla 1]
      ,[Amm. tutk. samalla koul.alalla 1]
      ,[Opistoast. tutk. samalla koul.alalla 1]
      ,[Amm. ka. tutk. samalla koul.alalla 1]
      ,[Amk-tutkinto samalla koul.alalla 1]
      ,[Alempi kk-tutk. samalla koul.alalla 1]
      ,[Ylempi amk-tutk. samalla koul.alalla 1]
      ,[Ylempi kk-tutk. samalla koul.alalla 1]
      ,[Laak. erik.tutk. samalla koul.alalla 1]
      ,[Lis. tutkinto samalla koul.alalla 1]
      ,[Toht. tutkinto samalla koul.alalla 1]
      ,[Yliopistotutk. samalla koul.alalla 1]
      ,[Yo-jatkotutk. samalla koul.alalla 1]
      ,[Opisto/amm.ka. tutk. samalla koul.alalla 1]
      ,[Korkeak.tutk. samalla koul.alalla 1]
      ,[Toisen asteen tutk. samalla koul.alalla 1]
      ,[Yo-tutkinto samalla koul.alalla 2]
      ,[Amm. tutk. samalla koul.alalla 2]
      ,[Opistoast. tutk. samalla koul.alalla 2]
      ,[Amm. ka. tutk. samalla koul.alalla 2]
      ,[Amk-tutkinto samalla koul.alalla 2]
      ,[Alempi kk-tutk. samalla koul.alalla 2]
      ,[Ylempi amk-tutk. samalla koul.alalla 2]
      ,[Ylempi kk-tutk. samalla koul.alalla 2]
      ,[Laak. erik.tutk. samalla koul.alalla 2]
      ,[Lis. tutkinto samalla koul.alalla 2]
      ,[Toht. tutkinto samalla koul.alalla 2]
      ,[Yliopistotutk. samalla koul.alalla 2]
      ,[Yo-jatkotutk. samalla koul.alalla 2]
      ,[Opisto/amm.ka. tutk. samalla koul.alalla 2]
      ,[Korkeak.tutk. samalla koul.alalla 2]
      ,[Toisen asteen tutk. samalla koul.alalla 2]
      ,[jarj_tarkastelujakso]
      ,[jarj_aidinkieli]
      ,[jarj_koulnimike]
      ,[jarj_oppis]
      ,[jarj_tutktyyppi]
      ,[jarj_jarjtapa]
      ,[jarj_nuoretaikuisetamm]
      ,[jarj_ika]
      ,[jarj_ika5v]
      ,[jarj_lukio_koulnimike]
      ,[jarj_lukio_myohtutk]
      ,[jarj_lukio_kulunutaika]
      ,[jarj_lukio_nuoretaikuiset]
      ,[jarj_amm_koulnimike]
      ,[jarj_amm_myohtutk]
      ,[jarj_amm_kulunutaika]
      ,[jarj_amm_tutktyyppi]
      ,[jarj_amm_jarjtapa]
      ,[jarj_amm_oppis]
      ,[jarj_amm_sopimusjaksot]
      ,[jarj_amm_tutkmaara]
      ,[jarj_amm_ryhma]
      ,[jarj_opisto_koulnimike]
      ,[jarj_opisto_myohtutk]
      ,[jarj_opisto_kulunutaika]
      ,[jarj_amm_kork_aste_koulnimike]
      ,[jarj_amm_kork_aste_myohtutk]
      ,[jarj_amm_kork_aste_kulunutaika]
      ,[jarj_amk_koulnimike]
      ,[jarj_amk_myohtutk]
      ,[jarj_amk_kulunutaika]
      ,[jarj_amk_tutkmaara]
      ,[jarj_amk_nuoraik]
      ,[jarj_alempi_kk_koulnimike]
      ,[jarj_alempi_kk_myohtutk]
      ,[jarj_alempi_kk_kulunutaika]
      ,[jarj_alempi_kk_tutkmaara]
      ,[jarj_ylempi_amk_koulnimike]
      ,[jarj_ylempi_amk_myohtutk]
      ,[jarj_ylempi_amk_kulunutaika]
      ,[jarj_ylempi_kk_koulnimike]
      ,[jarj_ylempi_kk_myohtutk]
      ,[jarj_ylempi_kk_kulunutaika]
      ,[jarj_ylempi_kk_tutkmaara]
      ,[jarj_laak_erik_koulnimike]
      ,[jarj_laak_erik_myohtutk]
      ,[jarj_laak_erik_kulunutaika]
      ,[jarj_lis_koulnimike]
      ,[jarj_lis_myohtutk]
      ,[jarj_lis_kulunutaika]
      ,[jarj_toht_koulnimike]
      ,[jarj_toht_myohtutk]
      ,[jarj_toht_kulunutaika]
      ,[jarj_yliopisto_myohtutk]
      ,[jarj_yojatko_myohtutk]
      ,[jarj_opist_myohtutk]
      ,[jarj_korkeakoulu_myohtutk]
      ,[jarj_toinenaste_myohtutk]
      ,[jarj_ammryhma1_myohtutk]
      ,[jarj_ammryhma2_myohtutk]
      ,[jarj_ammryhma3_myohtutk]
      ,[jarj_ulkom]
      ,[jarj_luulkom]
      ,[jarj_ammulkom]
      ,[jarj_opistulkom]
      ,[jarj_ammkaulkom]
      ,[jarj_amkulkom]
      ,[jarj_akkulkom]
      ,[jarj_ylamkulkom]
      ,[jarj_ykkulkom]
      ,[jarj_laakerulkom]
      ,[jarj_lisulkom]
      ,[jarj_tohtulkom]
      ,[jarj_samaiscbroad_lu]
      ,[jarj_samaiscbroad_amm]
      ,[jarj_samaiscbroad_opisto]
      ,[jarj_samaiscbroad_ammka]
      ,[jarj_samaiscbroad_amk]
      ,[jarj_samaiscbroad_alempikk]
      ,[jarj_samaiscbroad_ylempiamk]
      ,[jarj_samaiscbroad_ylempikk]
      ,[jarj_samaiscbroad_laak]
      ,[jarj_samaiscbroad_lis]
      ,[jarj_samaiscbroad_toht]
      ,[jarj_samaiscbroad_yliopisto]
      ,[jarj_samaiscbroad_yojatko]
      ,[jarj_samaiscbroad_opistoammka]
      ,[jarj_samaiscbroad_korkeak]
      ,[jarj_samaiscbroad_toinenaste]
      ,[jarj_samaiscnarrow_lu]
      ,[jarj_samaiscnarrow_amm]
      ,[jarj_samaiscnarrow_opisto]
      ,[jarj_samaiscnarrow_ammka]
      ,[jarj_samaiscnarrow_amk]
      ,[jarj_samaiscnarrow_alempikk]
      ,[jarj_samaiscnarrow_ylempiamk]
      ,[jarj_samaiscnarrow_ylempikk]
      ,[jarj_samaiscnarrow_laak]
      ,[jarj_samaiscnarrow_lis]
      ,[jarj_samaiscnarrow_toht]
      ,[jarj_samaiscnarrow_yliopisto]
      ,[jarj_samaiscnarrow_yojatko]
      ,[jarj_samaiscnarrow_opistoammka]
      ,[jarj_samaiscnarrow_korkeak]
      ,[jarj_samaiscnarrow_toinenaste]
      ,[Koodit Koulutusnimike]
      ,[Koodit Yo-tutkinnon koulutusnimike]
      ,[Koodit Amm. tutkinnon koulutusnimike]
      ,[Koodit Opistoast. tutkinnon koulutusnimike]
      ,[Koodit Amm. kork.asteen tutk. koulutusnimike]
      ,[Koodit Amk-tutkinnon koulutusnimike]
      ,[Koodit Alemman kk-tutk. koulutusnimike]
      ,[Koodit Ylemmän amk-tutk. koulutusnimike]
      ,[Koodit Ylemmän kk-tutk. koulutusnimike]
      ,[Koodit Lääk. erikois.tutk. koulutusnimike]
      ,[Koodit Lisensiaatin tutk. koulutusnimike]
      ,[Koodit Tohtorin tutk. koulutusnimike]
      ,[rivinumero]
      ,[Koulutusaste, taso 1]
      ,[Koulutusaste, taso 2]
      ,[Koulutusala, taso 1]
      ,[Koulutusala, taso 2]
      ,[Koulutusala, taso 3]
      ,[OKM ohjauksen ala]
      ,[jarj_isced_koulast1]
      ,[jarj_isced_koulast2]
      ,[jarj_isced_koulala1]
      ,[jarj_isced_koulala2]
      ,[jarj_isced_koulala3]
      ,[jarj_isced_okmohjaus1]
      ,[Koodit Koulutusaste, taso 1]
      ,[Koodit Koulutusaste, taso 2]
      ,[Koodit Koulutusala, taso 1]
      ,[Koodit Koulutusala, taso 2]
      ,[Koodit Koulutusala, taso 3]
      ,[Koodit OKM ohjauksen ala]
      ,[Yo-tutkinnon koulutusala 3]
      ,[Amm. tutkinnon koulutusala 1]
      ,[Amm. tutkinnon koulutusala 2]
      ,[Amm. tutkinnon koulutusala 3]
      ,[Opistoast. tutkinnon koulutusala 1]
      ,[Opistoast. tutkinnon koulutusala 2]
      ,[Opistoast. tutkinnon koulutusala 3]
      ,[Amm. kork.asteen tutk. koulutusala 1]
      ,[Amm. kork.asteen tutk. koulutusala 2]
      ,[Amm. kork.asteen tutk. koulutusala 3]
      ,[Amk-tutkinnon koulutusala 1]
      ,[Amk-tutkinnon OKM ohjauksen ala]
      ,[Amk-tutkinnon koulutusala 2]
      ,[Amk-tutkinnon koulutusala 3]
      ,[Alemman kk-tutk. koulutusala 1]
      ,[Alemman kk-tutk. OKM ohjauksen ala]
      ,[Alemman kk-tutk. koulutusala 2]
      ,[Alemman kk-tutk. koulutusala 3]
      ,[Ylemmän amk-tutk. koulutusala 1]
      ,[Ylemmän amk-tutk. OKM ohjauksen ala]
      ,[Ylemmän amk-tutk. koulutusala 2]
      ,[Ylemmän amk-tutk. koulutusala 3]
      ,[Ylemmän kk-tutk. koulutusala 1]
      ,[Ylemmän kk-tutk. OKM ohjauksen ala]
      ,[Ylemmän kk-tutk. koulutusala 2]
      ,[Ylemmän kk-tutk. koulutusala 3]
      ,[Lääk. erikois.tutk. koulutusala 3]
      ,[Lisensiaatin tutk. koulutusala 1]
      ,[Lisensiaatin tutk. OKM ohjauksen ala]
      ,[Lisensiaatin tutk. koulutusala 2]
      ,[Lisensiaatin tutk. koulutusala 3]
      ,[Tohtorin tutk. koulutusala 1]
      ,[Tohtorin tutk. OKM ohjauksen ala]
      ,[Tohtorin tutk. koulutusala 2]
      ,[Tohtorin tutk. koulutusala 3]
      ,[jarj_lukio_iscfi2013]
      ,[jarj_amm_iscfibroad2013]
      ,[jarj_amm_iscfinarrow2013]
      ,[jarj_amm_iscfi2013]
      ,[jarj_opisto_iscfibroad2013]
      ,[jarj_opisto_iscfinarrow2013]
      ,[jarj_opisto_iscfi2013]
      ,[jarj_amm_kork_aste_iscfibroad2013]
      ,[jarj_amm_kork_aste_iscfinarrow2013]
      ,[jarj_amm_kork_aste_iscfi2013]
      ,[jarj_amk_iscfibroad2013]
      ,[jarj_amk_OKM_ohjauksen_ala]
      ,[jarj_amk_iscfinarrow2013]
      ,[jarj_amk_iscfi2013]
      ,[jarj_alempi_kk_iscfibroad2013]
      ,[jarj_alempi_kk_OKM_ohjauksen_ala]
      ,[jarj_alempi_kk_iscfinarrow2013]
      ,[jarj_alempi_kk_iscfi2013]
      ,[jarj_ylempi_amk_iscfibroad2013]
      ,[jarj_ylempi_amk_OKM_ohjauksen_ala]
      ,[jarj_ylempi_amk_iscfinarrow2013]
      ,[jarj_ylempi_amk_iscfi2013]
      ,[jarj_ylempi_kk_iscfibroad2013]
      ,[jarj_ylempi_kk_OKM_ohjauksen_ala]
      ,[jarj_ylempi_kk_iscfinarrow2013]
      ,[jarj_ylempi_kk_iscfi2013]
      ,[jarj_laak_erik_iscfi2013]
      ,[jarj_lis_iscfibroad2013]
      ,[jarj_lis_OKM_ohjauksen_ala]
      ,[jarj_lis_iscfinarrow2013]
      ,[jarj_lis_iscfi2013]
      ,[jarj_toht_iscfibroad2013]
      ,[jarj_toht_OKM_ohjauksen_ala]
      ,[jarj_toht_iscfinarrow2013]
      ,[jarj_toht_iscfi2013]
      ,[Koodit Yo-tutkinnon koulutusala 3]
      ,[Koodit Amm. tutkinnon koulutusala 1]
      ,[Koodit Amm. tutkinnon koulutusala 2]
      ,[Koodit Amm. tutkinnon koulutusala 3]
      ,[Koodit Opistoast. tutkinnon koulutusala 1]
      ,[Koodit Opistoast. tutkinnon koulutusala 2]
      ,[Koodit Opistoast. tutkinnon koulutusala 3]
      ,[Koodit Amm. kork.asteen tutk. koulutusala 1]
      ,[Koodit Amm. kork.asteen tutk. koulutusala 2]
      ,[Koodit Amm. kork.asteen tutk. koulutusala 3]
      ,[Koodit Amk-tutkinnon koulutusala 1]
      ,[Koodit Amk-tutkinnon OKM ohjauksen ala]
      ,[Koodit Amk-tutkinnon koulutusala 2]
      ,[Koodit Amk-tutkinnon koulutusala 3]
      ,[Koodit Alemman kk-tutk. koulutusala 1]
      ,[Koodit Alemman kk-tutk. OKM ohjauksen ala]
      ,[Koodit Alemman kk-tutk. koulutusala 2]
      ,[Koodit Alemman kk-tutk. koulutusala 3]
      ,[Koodit Ylemmän amk-tutk. koulutusala 1]
      ,[Koodit Ylemmän amk-tutk. OKM ohjauksen ala]
      ,[Koodit Ylemmän amk-tutk. koulutusala 2]
      ,[Koodit Ylemmän amk-tutk. koulutusala 3]
      ,[Koodit Ylemmän kk-tutk. koulutusala 1]
      ,[Koodit Ylemmän kk-tutk. OKM ohjauksen ala]
      ,[Koodit Ylemmän kk-tutk. koulutusala 2]
      ,[Koodit Ylemmän kk-tutk. koulutusala 3]
      ,[Koodit Lääk. erikois.tutk. koulutusala 3]
      ,[Koodit Lisensiaatin tutk. koulutusala 1]
      ,[Koodit Lisensiaatin tutk. OKM ohjauksen ala]
      ,[Koodit Lisensiaatin tutk. koulutusala 2]
      ,[Koodit Lisensiaatin tutk. koulutusala 3]
      ,[Koodit Tohtorin tutk. koulutusala 1]
      ,[Koodit Tohtorin tutk. OKM ohjauksen ala]
      ,[Koodit Tohtorin tutk. koulutusala 2]
      ,[Koodit Tohtorin tutk. koulutusala 3]
  FROM [VipunenTK].[dbo].[f_tab_tutkinnon_suorittaneiden_myohempi_koulutus_4_8_yhteiset]