USE [VipunenTK_DW]
GO

/****** Object:  Table [dbo].[_VipunenTK_f_tutkinnon_suorittaneiden_myohempi_koulutus_4_8]    Script Date: 10.7.2023 15:00:15 ******/
DROP TABLE [dbo].[_VipunenTK_f_tutkinnon_suorittaneiden_myohempi_koulutus_4_8]
GO

/****** Object:  Table [dbo].[_VipunenTK_f_tutkinnon_suorittaneiden_myohempi_koulutus_4_8]    Script Date: 10.7.2023 15:00:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[_VipunenTK_f_tutkinnon_suorittaneiden_myohempi_koulutus_4_8](
	[tilastovuosi] [int] NOT NULL,
	[tilv_date] [date] NULL,
	[tarkastelujakso_koodi] [nvarchar](20) NOT NULL,
	[tarkastelujakso_id] [int] NOT NULL,
	[sukupuoli_koodi] [nvarchar](10) NULL,
	[sukupuoli_id] [int] NOT NULL,
	[aidinkieli_versio1_koodi] [nvarchar](2) NULL,
	[aidinkieli_id] [int] NOT NULL,
	[suorv] [int] NOT NULL,
	[suorlk] [varchar](1) NULL,
	[suorituskausikoodi] [varchar](8) NULL,
	[suorituskausi_id] [nvarchar](10) NOT NULL,
	[koulutusluokitus_avain] [nvarchar](6) NULL,
	[koulutusluokitus_id] [int] NOT NULL,
	[alvv] [varchar](4) NULL,
	[allk] [varchar](1) NULL,
	[aloituskausikoodi] [varchar](8) NULL,
	[aloituskausi_id] [nvarchar](10) NOT NULL,
	[oppisopimuskoulutus_koodi] [nvarchar](2) NULL,
	[oppisopimuskoulutus_id] [int] NOT NULL,
	[ammatillisen_koulutuksen_koulutuslaji_koodi] [nvarchar](2) NULL,
	[ammatillisen_koulutuksen_koulutuslaji_id] [int] NOT NULL,
	[opetussuunnitelmaperusteinen_koulutus_nayttotutkintoon_valmistava_koulutus_koodi] [nvarchar](2) NULL,
	[opetussuunnitelmaperusteinen_koulutus_nayttotutkintoon_valmistava_koulutus_id] [int] NOT NULL,
	[nuorten_aikuisten_koulutus_amm_koodi] [nvarchar](2) NULL,
	[nuorten_aikuisten_koulutus_amm_id] [int] NOT NULL,
	[ulkom_id] [int] NOT NULL,
	[syntv] [varchar](4) NULL,
	[ika_avain] [nvarchar](10) NULL,
	[ika_id] [int] NOT NULL,
	[henkiloiden_lkm] [int] NULL,
	[lu_henkiloiden_lkm] [int] NULL,
	[lukoulk] [varchar](6) NULL,
	[lu_myohempi_koulutusluokitus_id] [int] NOT NULL,
	[lusuorv] [varchar](4) NULL,
	[luaikoul] [varchar](1) NULL,
	[lu_nuorten_aikuisten_koulutus_amm_id] [int] NOT NULL,
	[luulkom_id] [int] NOT NULL,
	[lu_ika] [int] NULL,
	[lu_ika_id] [int] NOT NULL,
	[lu_myohempi_tutkinto_suoritettu] [varchar](1) NOT NULL,
	[lu_myohempi_tutkinto_suoritettu_id] [int] NOT NULL,
	[ammlkm_id] [int] NOT NULL,
	[amm_henkiloiden_lkm] [int] NULL,
	[ammkoulk] [varchar](6) NULL,
	[amm_myohempi_koulutusluokitus_id] [int] NOT NULL,
	[ammsuorv] [varchar](4) NULL,
	[ammoppis] [varchar](1) NULL,
	[ammoppis_id] [int] NOT NULL,
	[amm_sopimusjaksot_id] [int] NOT NULL,
	[ammtutklaja] [varchar](1) NULL,
	[ammtutklaja_id] [int] NOT NULL,
	[ammtutktav] [varchar](1) NULL,
	[ammtutktav_id] [int] NOT NULL,
	[ammatillinen_koulutus_ryhma] [nvarchar](10) NULL,
	[ammatillinen_koulutus_ryhma_id] [int] NOT NULL,
	[ammulkom_id] [int] NOT NULL,
	[amm_ika] [int] NULL,
	[amm_ika_id] [int] NOT NULL,
	[amm_myohempi_tutkinto_suoritettu] [varchar](1) NOT NULL,
	[amm_myohempi_tutkinto_suoritettu_id] [int] NOT NULL,
	[opist_henkiloiden_lkm] [int] NULL,
	[opistkoulk] [varchar](6) NULL,
	[opist_myohempi_koulutusluokitus_id] [int] NOT NULL,
	[opistsuorv] [varchar](4) NULL,
	[opistulkom_id] [int] NOT NULL,
	[opist_ika] [int] NULL,
	[opist_ika_id] [int] NOT NULL,
	[opist_myohempi_tutkinto_suoritettu] [varchar](1) NOT NULL,
	[opist_myohempi_tutkinto_suoritettu_id] [int] NOT NULL,
	[ammka_henkiloiden_lkm] [int] NULL,
	[ammkakoulk] [varchar](6) NULL,
	[ammka_myohempi_koulutusluokitus_id] [int] NOT NULL,
	[ammkasuorv] [varchar](4) NULL,
	[ammkaulkom_id] [int] NOT NULL,
	[ammka_ika] [int] NULL,
	[ammka_ika_id] [int] NOT NULL,
	[ammka_myohempi_tutkinto_suoritettu] [varchar](1) NOT NULL,
	[ammka_myohempi_tutkinto_suoritettu_id] [int] NOT NULL,
	[amklkm_id] [int] NOT NULL,
	[amk_henkiloiden_lkm] [int] NULL,
	[amkkoulk] [varchar](6) NULL,
	[amk_myohempi_koulutusluokitus_id] [int] NOT NULL,
	[amksuorv] [varchar](4) NULL,
	[amkaikoul] [varchar](1) NULL,
	[amkaikoul_id] [int] NOT NULL,
	[amkulkom_id] [int] NOT NULL,
	[amk_ika] [int] NULL,
	[amk_ika_id] [int] NOT NULL,
	[amk_myohempi_tutkinto_suoritettu] [varchar](1) NOT NULL,
	[amk_myohempi_tutkinto_suoritettu_id] [int] NOT NULL,
	[akklkm_id] [int] NOT NULL,
	[akk_henkiloiden_lkm] [int] NULL,
	[akkkoulk] [varchar](6) NULL,
	[akk_myohempi_koulutusluokitus_id] [int] NOT NULL,
	[akksuorv] [varchar](4) NULL,
	[akkulkom_id] [int] NOT NULL,
	[akk_ika] [int] NULL,
	[akk_ika_id] [int] NOT NULL,
	[akk_myohempi_tutkinto_suoritettu] [varchar](1) NOT NULL,
	[akk_myohempi_tutkinto_suoritettu_id] [int] NOT NULL,
	[ylamklkm_henkiloiden_lkm] [int] NULL,
	[ylamkkoulk] [varchar](6) NULL,
	[ylamk_myohempi_koulutusluokitus_id] [int] NOT NULL,
	[ylamksuorv] [varchar](4) NULL,
	[ylamkulkom_id] [int] NOT NULL,
	[ylamk_ika] [int] NULL,
	[ylamk_ika_id] [int] NOT NULL,
	[ylamk_myohempi_tutkinto_suoritettu] [varchar](1) NOT NULL,
	[ylamk_myohempi_tutkinto_suoritettu_id] [int] NOT NULL,
	[ykklkm_id] [int] NOT NULL,
	[ykk_henkiloiden_lkm] [int] NULL,
	[ykkkoulk] [varchar](6) NULL,
	[ykk_myohempi_koulutusluokitus_id] [int] NOT NULL,
	[ykksuorv] [varchar](4) NULL,
	[ykkulkom_id] [int] NOT NULL,
	[ykk_ika] [int] NULL,
	[ykk_ika_id] [int] NOT NULL,
	[ykk_myohempi_tutkinto_suoritettu] [varchar](1) NOT NULL,
	[ykk_myohempi_tutkinto_suoritettu_id] [int] NOT NULL,
	[laaker_henkiloiden_lkm] [int] NULL,
	[laakerkoulk] [varchar](6) NULL,
	[laaker_myohempi_koulutusluokitus_id] [int] NOT NULL,
	[laakersuorv] [varchar](4) NULL,
	[laakerulkom_id] [int] NOT NULL,
	[laaker_ika] [int] NULL,
	[laaker_ika_id] [int] NOT NULL,
	[laaker_myohempi_tutkinto_suoritettu] [varchar](1) NOT NULL,
	[laaker_myohempi_tutkinto_suoritettu_id] [int] NOT NULL,
	[lis_henkiloiden_lkm] [int] NULL,
	[liskoulk] [varchar](6) NULL,
	[lis_myohempi_koulutusluokitus_id] [int] NOT NULL,
	[lissuorv] [varchar](4) NULL,
	[lisulkom_id] [int] NOT NULL,
	[lis_ika] [int] NULL,
	[lis_ika_id] [int] NOT NULL,
	[lis_myohempi_tutkinto_suoritettu] [varchar](1) NOT NULL,
	[lis_myohempi_tutkinto_suoritettu_id] [int] NOT NULL,
	[toht_henkiloiden_lkm] [int] NULL,
	[tohtkoulk] [varchar](6) NULL,
	[toht_myohempi_koulutusluokitus_id] [int] NOT NULL,
	[tohtsuorv] [varchar](4) NULL,
	[tohtulkom_id] [int] NOT NULL,
	[toht_ika] [int] NULL,
	[toht_ika_id] [int] NOT NULL,
	[toht_myohempi_tutkinto_suoritettu] [varchar](1) NOT NULL,
	[toht_myohempi_tutkinto_suoritettu_id] [int] NOT NULL,
	[yliopistotutkinto_myohempi_suoritettu_id] [int] NOT NULL,
	[yo_jatkotutkinto_myohempi_suoritettu_id] [int] NOT NULL,
	[opisto_tai_ammatillisen_korkea_asteen_tutkinto_myohempi_suoritettu_id] [int] NOT NULL,
	[korkeakoulututkinto_myohempi_suoritettu_id] [int] NOT NULL,
	[toisen_asteen_tutkinto_myohempi_suoritettu_id] [int] NOT NULL,
	[ammatillisen_tutkinto_myohempi_suoritettu_ryhma1_id] [int] NOT NULL,
	[ammatillisen_tutkinto_myohempi_suoritettu_ryhma2_id] [int] NOT NULL,
	[ammatillisen_tutkinto_myohempi_suoritettu_ryhma3_id] [int] NOT NULL,
	[myohemman_yliopistotutkinnon_suorittaneiden_lkm] [int] NULL,
	[myohemman_yo_jatkotutkinnon_suorittaneiden_lkm] [int] NULL,
	[myohemman_opisto_tai_ammatillisen_korkea_asteen_tutkinnon_suorittaneiden_lkm] [int] NULL,
	[myohemman_korkeakoulututkinnon_suorittaneiden_lkm] [int] NULL,
	[myohemman_toisen_asteen_tutkinnon_suorittaneiden_lkm] [int] NULL,
	[myohemman_ammatillisen_tutkinnon_ryhma1_suorittaneiden_lkm] [int] NULL,
	[myohemman_ammatillisen_tutkinnon_ryhma2_suorittaneiden_lkm] [int] NULL,
	[myohemman_ammatillisen_tutkinnon_ryhma3_suorittaneiden_lkm] [int] NULL,
	[lu_sama_myohempi_iscfibroad2013_avain] [varchar](33) NOT NULL,
	[amm_sama_myohempi_iscfibroad2013_avain] [varchar](34) NOT NULL,
	[opist_sama_myohempi_iscfibroad2013_avain] [varchar](36) NOT NULL,
	[ammka_sama_myohempi_iscfibroad2013_avain] [varchar](36) NOT NULL,
	[akk_sama_myohempi_iscfibroad2013_avain] [varchar](34) NOT NULL,
	[amk_sama_myohempi_iscfibroad2013_avain] [varchar](34) NOT NULL,
	[ylamk_sama_myohempi_iscfibroad2013_avain] [varchar](36) NOT NULL,
	[ykk_sama_myohempi_iscfibroad2013_avain] [varchar](34) NOT NULL,
	[laaker_sama_myohempi_iscfibroad2013_avain] [varchar](37) NOT NULL,
	[lis_sama_myohempi_iscfibroad2013_avain] [varchar](34) NOT NULL,
	[toht_sama_myohempi_iscfibroad2013_avain] [varchar](35) NOT NULL,
	[yliopistotutkinto_sama_myohempi_iscfibroad2013_avain] [varchar](48) NOT NULL,
	[yo_jatkotutkinto_sama_myohempi_iscfibroad2013_avain] [varchar](47) NOT NULL,
	[opisto_tai_ammatillisen_korkea_asteen_tutkinto_sama_myohempi_iscfibroad2013_avain] [varchar](77) NOT NULL,
	[korkeakoulututkinto_sama_myohempi_iscfibroad2013_avain] [varchar](50) NOT NULL,
	[toisen_asteen_tutkinto_sama_myohempi_iscfibroad2013_avain] [varchar](53) NOT NULL,
	[lu_sama_myohempi_iscfinarrow2013_avain] [varchar](34) NOT NULL,
	[amm_sama_myohempi_iscfinarrow2013_avain] [varchar](35) NOT NULL,
	[opist_sama_myohempi_iscfinarrow2013_avain] [varchar](37) NOT NULL,
	[ammka_sama_myohempi_iscfinarrow2013_avain] [varchar](37) NOT NULL,
	[akk_sama_myohempi_iscfinarrow2013_avain] [varchar](35) NOT NULL,
	[amk_sama_myohempi_iscfinarrow2013_avain] [varchar](35) NOT NULL,
	[ylamk_sama_myohempi_iscfinarrow2013_avain] [varchar](37) NOT NULL,
	[ykk_sama_myohempi_iscfinarrow2013_avain] [varchar](35) NOT NULL,
	[laaker_sama_myohempi_iscfinarrow2013_avain] [varchar](38) NOT NULL,
	[lis_sama_myohempi_iscfinarrow2013_avain] [varchar](35) NOT NULL,
	[toht_sama_myohempi_iscfinarrow2013_avain] [varchar](36) NOT NULL,
	[yliopistotutkinto_sama_myohempi_iscfinarrow2013_avain] [varchar](49) NOT NULL,
	[yo_jatkotutkinto_sama_myohempi_iscfinarrow2013_avain] [varchar](48) NOT NULL,
	[opisto_tai_ammatillisen_korkea_asteen_tutkinto_sama_myohempi_iscfinarrow2013_avain] [varchar](78) NOT NULL,
	[korkeakoulututkinto_sama_myohempi_iscfinarrow2013_avain] [varchar](51) NOT NULL,
	[toisen_asteen_tutkinto_sama_myohempi_iscfinarrow2013_avain] [varchar](54) NOT NULL,
	[tietolahde] [nvarchar](50) NULL,
	[rivinumero] [int] NULL
) ON [PRIMARY]

GO


