USE [ANTERO]
GO

/****** Object:  Table [dw].[f_eter_students]    Script Date: 25.8.2023 15:39:41 ******/
DROP TABLE [dw].[f_eter_students]
GO

/****** Object:  Table [dw].[f_eter_students]    Script Date: 25.8.2023 15:39:41 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dw].[f_eter_students](
	[ETER_ID] [varchar](255) NULL,
	[Lowest degree delivered] [varchar](255) NULL,
	[Flag Students ISCED 5 - gender] [varchar](255) NULL,
	[Students enrolled at ISCED 5 - men] [float] NULL,
	[Students enrolled at ISCED 5 - resident] [float] NULL,
	[Students enrolled at ISCED 5 - gender unclassified] [float] NULL,
	[Highest degree delivered] [varchar](255) NULL,
	[Students enrolled at ISCED 5 - Education] [float] NULL,
	[Flag Students ISCED 5 - citizenship] [varchar](255) NULL,
	[Students enrolled at ISCED 5 - foreigner] [float] NULL,
	[Students enrolled at ISCED 5 - Information and Communication Technologies] [float] NULL,
	[Students enrolled at ISCED 5 - national] [float] NULL,
	[Students enrolled at ISCED 5 - Generic programmes and qualifications] [float] NULL,
	[Students enrolled at ISCED 5-mobility unclassified] [float] NULL,
	[Students enrolled at ISCED 5-ISCED-FoE unclassified] [float] NULL,
	[Students enrolled at ISCED 5 - Natural sciences, mathematics and statistics] [float] NULL,
	[Students enrolled at ISCED 5 - mobile] [float] NULL,
	[Students enrolled at ISCED 5 - Social sciences, journalism and information] [float] NULL,
	[Flag Students ISCED 5 - part-time, full-time] [varchar](255) NULL,
	[Students enrolled at ISCED 5 - Services] [float] NULL,
	[Students enrolled at ISCED 5 - Arts and Humanities] [float] NULL,
	[Students enrolled at ISCED 5 - Agriculture, forestry, fisheries and veterinary] [float] NULL,
	[Students enrolled at ISCED 5 - over 29 years old] [float] NULL,
	[Students enrolled at ISCED 5 - Engineering, manufacturing and construction] [float] NULL,
	[Students enrolled at ISCED 5 - part-, full-time unclassified] [float] NULL,
	[Students enrolled at ISCED 5 - between 25 and 29 years old] [float] NULL,
	[Flag Students ISCED 5 - ISCED-FoE] [varchar](255) NULL,
	[Notes on students enrolled at ISCED 5] [varchar](max) NULL,
	[Students enrolled at ISCED 5 - part-time] [float] NULL,
	[Students enrolled at ISCED 5 - under 20 years old] [float] NULL,
	[Flag Total students ISCED 5] [varchar](255) NULL,
	[Students enrolled at ISCED 6 - national] [float] NULL,
	[Students enrolled at ISCED 6 - mobile] [float] NULL,
	[Students enrolled at ISCED 5 - Age goup unclassified] [float] NULL,
	[Flag Students ISCED 5 - Age group] [varchar](255) NULL,
	[Students enrolled at ISCED 6 - Arts and Humanities] [float] NULL,
	[Flag Students ISCED 6 - gender] [varchar](255) NULL,
	[Students enrolled at ISCED 6 - resident] [float] NULL,
	[Students enrolled at ISCED 6 - men] [float] NULL,
	[Students enrolled at ISCED 6 - women] [float] NULL,
	[Students enrolled at ISCED 6 - Engineering, manufacturing and construction] [float] NULL,
	[Students enrolled at ISCED 6 - Education] [float] NULL,
	[Students at ISCED 6-citizenship unclassified] [float] NULL,
	[Students enrolled at ISCED 6 - foreigner] [float] NULL,
	[Flag Students ISCED 6 - ISCED-FoE] [varchar](255) NULL,
	[Students enrolled at ISCED 6 - Information and Communication Technologies] [float] NULL,
	[Students at ISCED 6 - mobility unclassified] [float] NULL,
	[Flag Students ISCED 6 - mobility] [varchar](255) NULL,
	[Students enrolled at ISCED 6 - under 20 years old] [float] NULL,
	[Students at ISCED 6 - ISCED-FoE unclassified] [float] NULL,
	[Students enrolled at ISCED 6 - Social sciences, journalism and information] [float] NULL,
	[Students enrolled at ISCED 6 - Age goup unclassified] [float] NULL,
	[Students enrolled at ISCED 6 - Business, administration and law] [float] NULL,
	[Students enrolled at ISCED 7 - men] [float] NULL,
	[Flag Students ISCED 6 - part-time, full-time] [varchar](255) NULL,
	[Students enrolled at ISCED 6 - Health and welfare] [float] NULL,
	[Students enrolled at ISCED 6 - Agriculture, forestry, fisheries and veterinary] [float] NULL,
	[Students enrolled at ISCED 6 - over 29 years old] [float] NULL,
	[Students enrolled at ISCED 6 - full-time] [float] NULL,
	[Students enrolled at ISCED 7 - foreigner] [float] NULL,
	[Students enrolled at ISCED 5 - women] [float] NULL,
	[Students enrolled at ISCED 6 - part-time] [float] NULL,
	[Notes on students enrolled at ISCED 6] [varchar](max) NULL,
	[Students enrolled at ISCED 6 - between 22 and 24 years old] [float] NULL,
	[Students at ISCED 7 - mobility unclassified] [float] NULL,
	[Students enrolled at ISCED 7 - national] [float] NULL,
	[Total students enrolled at ISCED 6] [float] NULL,
	[Students enrolled at ISCED 7 - Social sciences, journalism and information] [float] NULL,
	[Students at ISCED 5-citizenship unclassified] [float] NULL,
	[Students enrolled at ISCED 7 - gender unclassified] [float] NULL,
	[Students enrolled at ISCED 7 - mobile] [float] NULL,
	[Students enrolled at ISCED 7 - Agriculture, forestry, fisheries and veterinary] [float] NULL,
	[Flag Students ISCED 5 - mobility] [varchar](255) NULL,
	[Students enrolled at ISCED 7 - Arts and Humanities] [float] NULL,
	[Students enrolled at ISCED 7 - part-time] [float] NULL,
	[Flag Students ISCED 6 - Age group] [varchar](255) NULL,
	[Students enrolled at ISCED 5 - Business, administration and law] [float] NULL,
	[Students enrolled at ISCED 7 - Engineering, manufacturing and construction] [float] NULL,
	[Flag Students ISCED 7 - citizenship] [varchar](255) NULL,
	[Students enrolled at ISCED 7 - Generic programmes and qualifications] [float] NULL,
	[Students enrolled at ISCED 7 - women] [float] NULL,
	[Flag Students ISCED 7 - ISCED-FoE] [varchar](255) NULL,
	[Flag Students ISCED 7 - Age group] [varchar](255) NULL,
	[Students enrolled at ISCED 5 - Health and welfare] [float] NULL,
	[Students enrolled at ISCED 7 - Natural sciences, mathematics and statistics] [float] NULL,
	[Students at ISCED 7-citizenship unclassified] [float] NULL,
	[Students enrolled at ISCED 7 - under 20 years old] [float] NULL,
	[Students enrolled ISCED 7 long degree - women] [float] NULL,
	[Students enrolled at ISCED 5 - full-time] [float] NULL,
	[Flag Students ISCED 7 - mobility] [varchar](255) NULL,
	[Students enrolled at ISCED 7 - Services] [float] NULL,
	[Students ISCED7 long degree-citiz. unclassified] [float] NULL,
	[Students enrolled at ISCED 7 - Age goup unclassified] [float] NULL,
	[Students enrolled at ISCED 7 - Business, administration and law] [float] NULL,
	[Students enrolled at ISCED 5 - between 22 and 24 years old] [float] NULL,
	[Students enrolled at ISCED 7 - part-, full-time unclassified] [float] NULL,
	[Total students enrolled at ISCED 5] [float] NULL,
	[Students enrolled at ISCED 7 - Health and welfare] [float] NULL,
	[Students enrolled ISCED 7 long degree - men] [float] NULL,
	[Students enrolled at ISCED 7 - between 25 and 29 years old] [float] NULL,
	[Students enrolled at ISCED 6 - gender unclassified] [float] NULL,
	[Flag Students ISCED 7 long degree - mobility] [varchar](255) NULL,
	[Students enrolled at ISCED 7 - full-time] [float] NULL,
	[Students enrolled ISCED 7 long degree - foreigner] [float] NULL,
	[Flag Total students ISCED 7] [varchar](255) NULL,
	[Students ISCED 7 long degree-mobility unclassified] [float] NULL,
	[Flag Students ISCED 6 - citizenship] [varchar](255) NULL,
	[Students enrolled ISCED 7 long degree - Business, administration and law] [float] NULL,
	[Students enrolled at ISCED 7 - between 22 and 24 years old] [float] NULL,
	[Flag Students ISCED 7 long degree - gender] [varchar](255) NULL,
	[Students enrolled ISCED 7 long degree - Social sciences, journalism and information] [float] NULL,
	[Students enrolled at ISCED 6 - Generic programmes and qualifications] [float] NULL,
	[Students enrolled ISCED 7 long degree - Health and welfare] [float] NULL,
	[Total students enrolled at ISCED 7] [float] NULL,
	[Students enrolled ISCED 7 long degree - resident] [float] NULL,
	[Students enrolled at ISCED 6 - Natural sciences, mathematics and statistics] [float] NULL,
	[Students enrolled at ISCED 7 long degree - full-time] [float] NULL,
	[Students enrolled ISCED 7 long degree - Agriculture, forestry, fisheries and veterinary] [float] NULL,
	[Students ISCED 7 long degree - gender unclassified] [float] NULL,
	[Students enrolled ISCED 7 long degree - Education] [float] NULL,
	[Students enrolled at ISCED 6 - Services] [float] NULL,
	[Students enrolled at ISCED 7 long degree - part-time] [float] NULL,
	[Students enrolled at ISCED 7 long degree - between 22 and 24 years old] [float] NULL,
	[Flag Students ISCED 7 long degree - citizenship] [varchar](255) NULL,
	[Students enrolled ISCED 7 long degree - Information and Communication Technologies] [float] NULL,
	[Total students enrolled ISCED 7 long degree] [float] NULL,
	[Students enrolled at ISCED 6 - part-, full-time unclassified] [float] NULL,
	[Students enrolled at ISCED 6 - between 25 and 29 years old] [float] NULL,
	[Students ISCED7 long degree - ISCED-FoE unclassified] [float] NULL,
	[Flag Students ISCED 7 long degree - Age group] [varchar](255) NULL,
	[Students enrolled at ISCED 5-7 - gender unclassified] [float] NULL,
	[Students enrolled ISCED 7 long degree - Generic programmes and qualifications] [float] NULL,
	[Flag Students ISCED 7 long degree - part-time, full-time] [varchar](255) NULL,
	[Flag Total students ISCED 6] [varchar](255) NULL,
	[Students enrolled at ISCED 5-7 - women] [float] NULL,
	[Flag students enrolled at ISCED 5-7 - citizenship] [varchar](255) NULL,
	[Students enrolled ISCED 7 long degree - Natural sciences, mathematics and statistics] [float] NULL,
	[Students enrolled at ISCED 7 long degree - over 29 years old] [float] NULL,
	[Flag Students ISCED 7 - gender] [varchar](255) NULL,
	[Students enrolled at ISCED 5-7 - Generic programmes and qualifications] [float] NULL,
	[Students enrolled at ISCED 5-7 - citizenship unclassified] [float] NULL,
	[Students enrolled ISCED 7 long degree - Services] [float] NULL,
	[Students enrolled at ISCED 7 - resident] [float] NULL,
	[Notes on students enrolled at ISCED 7 long degree] [varchar](max) NULL,
	[Flag students enrolled at ISCED 5-7 - mobility] [varchar](255) NULL,
	[Students enrolled at ISCED 5-7 - Natural sciences, mathematics and statistics] [float] NULL,
	[Students enrolled at ISCED 7 long degree - part-, full-time unclassified] [float] NULL,
	[Students enrolled at ISCED 7 - Education] [float] NULL,
	[Students enrolled at ISCED 5-7 - Services] [float] NULL,
	[Students enrolled at ISCED 5-7 - national] [float] NULL,
	[Students enrolled at ISCED 5-7 - Business, administration and law] [float] NULL,
	[Students enrolled at ISCED 7 long degree - between 25 and 29 years old] [float] NULL,
	[Students enrolled at ISCED 5-7 - Health and welfare] [float] NULL,
	[Students enrolled at ISCED 5-7 - part-, full-time unclassified] [float] NULL,
	[Students enrolled at ISCED 5-7 - full-time] [float] NULL,
	[Students enrolled at ISCED 7 - Information and Communication Technologies] [float] NULL,
	[Students enrolled at ISCED 5-7 - between 22 and 24 years old] [float] NULL,
	[Flag Total students ISCED 7 long degree] [varchar](255) NULL,
	[Total students enrolled ISCED 5-7] [float] NULL,
	[Students at ISCED 7 - ISCED-FoE unclassified] [float] NULL,
	[Students enrolled at ISCED 5-7 - between 25 and 29 years old] [float] NULL,
	[Flag students enrolled at ISCED 5-7 - gender] [varchar](255) NULL,
	[Flag Students ISCED 7 - part-time, full-time] [varchar](255) NULL,
	[Students enrolled at ISCED 5-7 - mobile] [float] NULL,
	[Flag Total students ISCED 5-7] [varchar](255) NULL,
	[Students enrolled at ISCED 5-7 - resident] [float] NULL,
	[Students enrolled at ISCED 7 - over 29 years old] [float] NULL,
	[Students enrolled at ISCED 5-7 - Arts and Humanities] [float] NULL,
	[Students enrolled at ISCED 5-7 - Education] [float] NULL,
	[Students enrolled at ISCED 5-7 - Engineering, manufacturing and construction] [float] NULL,
	[Notes on students enrolled at ISCED 7] [varchar](max) NULL,
	[Students enrolled ISCED 7 long degree - national] [float] NULL,
	[Flag students enrolled at ISCED 5-7 - ISCED-FoE] [varchar](255) NULL,
	[Students enrolled at ISCED 5-7 - Information and Communication Technologies] [float] NULL,
	[Students enrolled ISCED 7 long degree - mobile] [float] NULL,
	[Students enrolled at ISCED 5-7 - ISCED-FoE unclassified] [float] NULL,
	[Students enrolled at ISCED 5-7 - under 20 years old] [float] NULL,
	[Flag Students ISCED 5-7 - part-time, full-time] [varchar](255) NULL,
	[Students enrolled at ISCED 5-7 - Age goup unclassified] [float] NULL,
	[Students enrolled ISCED 7 long degree - Arts and Humanities] [float] NULL,
	[Distance education institution] [float] NULL,
	[Students enrolled ISCED 7 long degree - Engineering, manufacturing and construction] [float] NULL,
	[Students enrolled at ISCED 5-7 - over 29 years old] [float] NULL,
	[Flag Students ISCED 7 long degree - ISCED-FoE] [varchar](255) NULL,
	[Notes on total students enrolled ISCED 5-7] [varchar](max) NULL,
	[Students enrolled at ISCED 7 long degree - under 20 years old] [float] NULL,
	[Students enrolled at ISCED 7 long degree - Age goup unclassified] [float] NULL,
	[Students enrolled at ISCED 5-7 - men] [float] NULL,
	[Students enrolled at ISCED 5-7 - foreigner] [float] NULL,
	[Students enrolled at ISCED 5-7 - mobility unclassified] [float] NULL,
	[Students enrolled at ISCED 5-7 - Social sciences, journalism and information] [float] NULL,
	[Students enrolled at ISCED 5-7 - Agriculture, forestry, fisheries and veterinary] [float] NULL,
	[Students enrolled at ISCED 5-7 - part-time] [float] NULL,
	[Flag Students ISCED 5-7 - Age group] [varchar](255) NULL,
	[Notes on educational activities (Students)] [varchar](max) NULL,
	[username] [varchar](100) NULL,
	[source] [varchar](100) NULL,
	[loadtime] [datetime] NULL
) ON [PRIMARY]

GO

USE [ANTERO]