IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'dw.f_amk_talous_2_tase') AND type in (N'U'))
BEGIN
CREATE TABLE dw.f_amk_talous_2_tase(
  id int IDENTITY(1,1) NOT NULL,
  d_amk_id int NOT NULL,
  tilikausi int NOT NULL,
  aineistotyyppi varchar(20) NULL,
  kehmenot bigint NULL,
  aineetoi bigint NULL,
  liikear bigint NULL,
  muupmeno bigint NULL,
  ahennakk bigint NULL,
  maavesi bigint NULL,
  rakennus bigint NULL,
  koneet bigint NULL,
  muuainh bigint NULL,
  ennakesk bigint NULL,
  osuuskon bigint NULL,
  saamikon bigint NULL,
  osuusoyy bigint NULL,
  saamioyy bigint NULL,
  muutosak bigint NULL,
  muutsaam bigint NULL,
  okrvarat bigint NULL,
  aineet bigint NULL,
  keskener bigint NULL,
  valmiit bigint NULL,
  muuvom bigint NULL,
  voennakk bigint NULL,
  pmyyntis bigint NULL,
  pskonser bigint NULL,
  psoyyrit bigint NULL,
  plainas bigint NULL,
  plveros bigint NULL,
  pmuuts bigint NULL,
  psiirtos bigint NULL,
  lmyyntis bigint NULL,
  lskonser bigint NULL,
  lsoyyrit bigint NULL,
  llainas bigint NULL,
  llveros bigint NULL,
  lmuuts bigint NULL,
  lsiirtos bigint NULL,
  raposuus bigint NULL,
  raposakk bigint NULL,
  muuarvop bigint NULL,
  rahatps bigint NULL,
  vastaava bigint NULL,
  osakepaa bigint NULL,
  arvonkr bigint NULL,
  kayvanar bigint NULL,
  okarahas bigint NULL,
  msirahas bigint NULL,
  vaprahas bigint NULL,
  edtilvo bigint NULL,
  tkvoitto bigint NULL,
  opoyht bigint NULL,
  tpskerty bigint NULL,
  elakvara bigint NULL,
  verovara bigint NULL,
  mpakvara bigint NULL,
  ppaaomal bigint NULL,
  pjvelkal bigint NULL,
  pvvelkal bigint NULL,
  plrahala bigint NULL,
  pelakel bigint NULL,
  psaadute bigint NULL,
  postovel bigint NULL,
  prveksel bigint NULL,
  pvkonser bigint NULL,
  pvoyyrit bigint NULL,
  plverove bigint NULL,
  pmuutvel bigint NULL,
  psiirtov bigint NULL,
  lpaaomal bigint NULL,
  ljvelkal bigint NULL,
  lvvelkal bigint NULL,
  llrahala bigint NULL,
  lelakel bigint NULL,
  lsaadute bigint NULL,
  lostovel bigint NULL,
  lrveksel bigint NULL,
  lvkonser bigint NULL,
  lvoyyrit bigint NULL,
  llverove bigint NULL,
  lmuutvel bigint NULL,
  lsiirtov bigint NULL,
  vastatta bigint NULL,
  okrsijyh bigint NULL,
  okrrahas bigint NULL,
  okrosakk bigint NULL,
  okrmuuap bigint NULL,
  okrrjaps bigint NULL,
  okrmuutv bigint NULL,
  kompperusalvm bigint NULL,
  saadalvkomp bigint NULL,
  alvsaavel bigint NULL,
  loadtime datetime NOT NULL,
  source varchar(100) NOT NULL,
  username varchar(30) NOT NULL
)
END

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'dw.DF__f_amk_tal__loadt__2645B050') AND type = 'D')
BEGIN
ALTER TABLE dw.f_amk_talous_2_tase ADD  DEFAULT (getdate()) FOR loadtime
END

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'dw.DF__f_amk_tal__usern__2739D489') AND type = 'D')
BEGIN
ALTER TABLE dw.f_amk_talous_2_tase ADD  DEFAULT (suser_sname()) FOR username
END