USE [VipunenTK_lisatiedot]
GO
UPDATE [VipunenTK_lisatiedot].[dbo].[oef_toimiala] SET oef_toimiala_EN = '1 Agriculture and fishing activities', oef_toimiala_SV = '1 Jordbruk och fiskerihushållning ' WHERE oef_toimiala_koodi = '01'
UPDATE [VipunenTK_lisatiedot].[dbo].[oef_toimiala] SET oef_toimiala_EN = '2 Veterinary activities', oef_toimiala_SV = '2 Veterinärtjänster' WHERE oef_toimiala_koodi = '02'
UPDATE [VipunenTK_lisatiedot].[dbo].[oef_toimiala] SET oef_toimiala_EN = '3 Forestry', oef_toimiala_SV = '3 Skogsbruk' WHERE oef_toimiala_koodi = '03'
UPDATE [VipunenTK_lisatiedot].[dbo].[oef_toimiala] SET oef_toimiala_EN = '4 Manufacture of food products', oef_toimiala_SV = '4 Tillverkning av livsmedel ' WHERE oef_toimiala_koodi = '04'
UPDATE [VipunenTK_lisatiedot].[dbo].[oef_toimiala] SET oef_toimiala_EN = '5 Trade', oef_toimiala_SV = '5 Handel' WHERE oef_toimiala_koodi = '05'
UPDATE [VipunenTK_lisatiedot].[dbo].[oef_toimiala] SET oef_toimiala_EN = '6 Financial and insurance services', oef_toimiala_SV = '6 Finansierings- och försäkringstjänster ' WHERE oef_toimiala_koodi = '06'
UPDATE [VipunenTK_lisatiedot].[dbo].[oef_toimiala] SET oef_toimiala_EN = '7 Business and development services for business life', oef_toimiala_SV = '7 Tjänster för affärsverksamhet och utveckling för affärslivet ' WHERE oef_toimiala_koodi = '07'
UPDATE [VipunenTK_lisatiedot].[dbo].[oef_toimiala] SET oef_toimiala_EN = '8 Rental and support services for business life', oef_toimiala_SV = '8 Uthyrnings- och supporttjänster för affärslivet' WHERE oef_toimiala_koodi = '08'
UPDATE [VipunenTK_lisatiedot].[dbo].[oef_toimiala] SET oef_toimiala_EN = '9 Public administration', oef_toimiala_SV = '9 Offentlig förvaltning ' WHERE oef_toimiala_koodi = '09'
UPDATE [VipunenTK_lisatiedot].[dbo].[oef_toimiala] SET oef_toimiala_EN = '10 Activities of membership organisations', oef_toimiala_SV = '10 Organisationer' WHERE oef_toimiala_koodi = '10'
UPDATE [VipunenTK_lisatiedot].[dbo].[oef_toimiala] SET oef_toimiala_EN = '11 Communications and publishing activities', oef_toimiala_SV = '11 Kommunikation och förlagsverksamhet ' WHERE oef_toimiala_koodi = '11'
UPDATE [VipunenTK_lisatiedot].[dbo].[oef_toimiala] SET oef_toimiala_EN = '12 Education', oef_toimiala_SV = '12 Utbildning' WHERE oef_toimiala_koodi = '12'
UPDATE [VipunenTK_lisatiedot].[dbo].[oef_toimiala] SET oef_toimiala_EN = '13 Arts and entertainment activities', oef_toimiala_SV = '13 Kultur- och nöjesverksamhet ' WHERE oef_toimiala_koodi = '13'
UPDATE [VipunenTK_lisatiedot].[dbo].[oef_toimiala] SET oef_toimiala_EN = '14 Trade and repair of motor vehicles', oef_toimiala_SV = '14 Handel och reparation av motorfordon' WHERE oef_toimiala_koodi = '14'
UPDATE [VipunenTK_lisatiedot].[dbo].[oef_toimiala] SET oef_toimiala_EN = '15 Traffic', oef_toimiala_SV = '15 Trafik' WHERE oef_toimiala_koodi = '15'
UPDATE [VipunenTK_lisatiedot].[dbo].[oef_toimiala] SET oef_toimiala_EN = '16 Warehousing and postal activities', oef_toimiala_SV = '16 Lagring och postverksamhet ' WHERE oef_toimiala_koodi = '16'
UPDATE [VipunenTK_lisatiedot].[dbo].[oef_toimiala] SET oef_toimiala_EN = '17 Accommodation', oef_toimiala_SV = '17 Logi' WHERE oef_toimiala_koodi = '17'
UPDATE [VipunenTK_lisatiedot].[dbo].[oef_toimiala] SET oef_toimiala_EN = '18 Travel agency and tour operator activities', oef_toimiala_SV = '18 Resebyråers och reseanordnares verksamhet ' WHERE oef_toimiala_koodi = '18'
UPDATE [VipunenTK_lisatiedot].[dbo].[oef_toimiala] SET oef_toimiala_EN = '19 Food service activities', oef_toimiala_SV = '19 Förplägnadsverksamhet' WHERE oef_toimiala_koodi = '19'
UPDATE [VipunenTK_lisatiedot].[dbo].[oef_toimiala] SET oef_toimiala_EN = '20 Electricity, gas, steam and air conditioning supply', oef_toimiala_SV = '20 Försörjning av el, gas och värme' WHERE oef_toimiala_koodi = '20'
UPDATE [VipunenTK_lisatiedot].[dbo].[oef_toimiala] SET oef_toimiala_EN = '21 Water supply and waste management activities', oef_toimiala_SV = '21 Vattenförsörjning och avfallshantering' WHERE oef_toimiala_koodi = '21'
UPDATE [VipunenTK_lisatiedot].[dbo].[oef_toimiala] SET oef_toimiala_EN = '22 Construction and design of buildings ', oef_toimiala_SV = '22 Husbygge och planering ' WHERE oef_toimiala_koodi = '22'
UPDATE [VipunenTK_lisatiedot].[dbo].[oef_toimiala] SET oef_toimiala_EN = '23 Civil engineering ', oef_toimiala_SV = '23 Jord- och vattenbygge' WHERE oef_toimiala_koodi = '23'
UPDATE [VipunenTK_lisatiedot].[dbo].[oef_toimiala] SET oef_toimiala_EN = '24 Real estate activities ', oef_toimiala_SV = '24 Fastigshetbranschen' WHERE oef_toimiala_koodi = '24'
UPDATE [VipunenTK_lisatiedot].[dbo].[oef_toimiala] SET oef_toimiala_EN = '25 Health services', oef_toimiala_SV = '25 Hälsotjänster' WHERE oef_toimiala_koodi = '25'
UPDATE [VipunenTK_lisatiedot].[dbo].[oef_toimiala] SET oef_toimiala_EN = '26 Social services', oef_toimiala_SV = '26 Socialtjänster' WHERE oef_toimiala_koodi = '26'
UPDATE [VipunenTK_lisatiedot].[dbo].[oef_toimiala] SET oef_toimiala_EN = '26 Social services', oef_toimiala_SV = '26 Sosiaalipalvelut' WHERE oef_toimiala_koodi = '26'
UPDATE [VipunenTK_lisatiedot].[dbo].[oef_toimiala] SET oef_toimiala_EN = '27 Sports and recreational services', oef_toimiala_SV = '27 Sport- och rekreationstjänster' WHERE oef_toimiala_koodi = '27'
UPDATE [VipunenTK_lisatiedot].[dbo].[oef_toimiala] SET oef_toimiala_EN = '28 Personal service activities', oef_toimiala_SV = '28 Personliga tjänster' WHERE oef_toimiala_koodi = '28'
UPDATE [VipunenTK_lisatiedot].[dbo].[oef_toimiala] SET oef_toimiala_EN = '29 Mining of ores and refining of metals ', oef_toimiala_SV = '29 Malmbrytning och metallförädling' WHERE oef_toimiala_koodi = '29'
UPDATE [VipunenTK_lisatiedot].[dbo].[oef_toimiala] SET oef_toimiala_EN = '30 Manufacture of electrical and electronic equipment', oef_toimiala_SV = '30 Tillverkning av elapparater och elektroniska anordningar ' WHERE oef_toimiala_koodi = '30'
UPDATE [VipunenTK_lisatiedot].[dbo].[oef_toimiala] SET oef_toimiala_EN = '31 Manufacture of metal products, machinery and vehicles', oef_toimiala_SV = '31 Tillverkning av metallprodukter, maskiner och fordon ' WHERE oef_toimiala_koodi = '31'
UPDATE [VipunenTK_lisatiedot].[dbo].[oef_toimiala] SET oef_toimiala_EN = '32 Telecommunications', oef_toimiala_SV = '32 Telekommunikation' WHERE oef_toimiala_koodi = '32'
UPDATE [VipunenTK_lisatiedot].[dbo].[oef_toimiala] SET oef_toimiala_EN = '33 Software and data services', oef_toimiala_SV = '33 Programvaru- och informationstjänster ' WHERE oef_toimiala_koodi = '33'
UPDATE [VipunenTK_lisatiedot].[dbo].[oef_toimiala] SET oef_toimiala_EN = '34 Manufacture of clothes and textiles', oef_toimiala_SV = '34 Tillverkning av kläder och textili' WHERE oef_toimiala_koodi = '34'
UPDATE [VipunenTK_lisatiedot].[dbo].[oef_toimiala] SET oef_toimiala_EN = '35 Manufacture of paperboard, paper and sawn timber ', oef_toimiala_SV = '35 Tillverkning av papper och sågvara' WHERE oef_toimiala_koodi = '35'
UPDATE [VipunenTK_lisatiedot].[dbo].[oef_toimiala] SET oef_toimiala_EN = '36 Manufacture of chemical products ', oef_toimiala_SV = '36 Tillverkning av kemiska produkter ' WHERE oef_toimiala_koodi = '36'
UPDATE [VipunenTK_lisatiedot].[dbo].[oef_toimiala] SET oef_toimiala_EN = '37 Manufacture of furniture ', oef_toimiala_SV = '37 Tillverkning av möbler ' WHERE oef_toimiala_koodi = '37'
UPDATE [VipunenTK_lisatiedot].[dbo].[oef_toimiala] SET oef_toimiala_EN = '38 Other manufacturing', oef_toimiala_SV = '38 Annan tillverkning' WHERE oef_toimiala_koodi = '38'
UPDATE [VipunenTK_lisatiedot].[dbo].[oef_toimiala] SET oef_toimiala_EN = '39 Industry unknown', oef_toimiala_SV = '39 Okänd' WHERE oef_toimiala_koodi = '39'
GO
USE [ANTERO]