USE [ANTERO]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dw].[d_keskeyttaminen_opiskelijan_toiminta]') AND type in (N'U'))
DROP TABLE [dw].[d_keskeyttaminen_opiskelijan_toiminta]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dw].[d_keskeyttaminen_opiskelijan_toiminta](
	[id] [bigint] IDENTITY(0,1) NOT NULL,
	[keskeyttaminen_opiskelijan_toiminta_koodi] [varchar](100) NULL,
	[keskeyttaminen_opiskelijan_toiminta_fi] [varchar](100) NOT NULL,
	[keskeyttaminen_opiskelijan_toiminta_sv] [varchar](100) NOT NULL,
	[keskeyttaminen_opiskelijan_toiminta_en] [varchar](100) NOT NULL,
	[keskeyttaminen_opiskelijan_toiminta_taso1_fi] [varchar](100) NOT NULL,
	[keskeyttaminen_opiskelijan_toiminta_taso1_sv] [varchar](100) NOT NULL,
	[keskeyttaminen_opiskelijan_toiminta_taso1_en] [varchar](100) NOT NULL,
	[keskeyttaminen_opiskelijan_toiminta_taso0_fi] [varchar](100) NOT NULL,
	[keskeyttaminen_opiskelijan_toiminta_taso0_sv] [varchar](100) NOT NULL,
	[keskeyttaminen_opiskelijan_toiminta_taso0_en] [varchar](100) NOT NULL,
	[keskeyttaminen_opiskelijan_toiminta_jarjestys] [int] NOT NULL,
	[kuutioon_ammatillinen] [int] NULL,
	[kuutioon_lukio] [int] NULL,
	[loadtime] [datetime] NOT NULL,
	[source] [varchar](100) NOT NULL,
	[username] [varchar](30) NOT NULL,
	CONSTRAINT [PK__d_keskeyttaminen_opiskelijan_toiminta] PRIMARY KEY CLUSTERED 
	(
		[id] ASC
	)
	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) 
	ON [PRIMARY]
) 
ON [PRIMARY]
GO

SET IDENTITY_INSERT [dw].[d_keskeyttaminen_opiskelijan_toiminta] ON 
GO

INSERT [dw].[d_keskeyttaminen_opiskelijan_toiminta] ([id], [keskeyttaminen_opiskelijan_toiminta_koodi], [keskeyttaminen_opiskelijan_toiminta_fi], [keskeyttaminen_opiskelijan_toiminta_sv], [keskeyttaminen_opiskelijan_toiminta_en], [keskeyttaminen_opiskelijan_toiminta_taso1_fi], [keskeyttaminen_opiskelijan_toiminta_taso1_sv], [keskeyttaminen_opiskelijan_toiminta_taso1_en], [keskeyttaminen_opiskelijan_toiminta_taso0_fi], [keskeyttaminen_opiskelijan_toiminta_taso0_sv], [keskeyttaminen_opiskelijan_toiminta_taso0_en], [keskeyttaminen_opiskelijan_toiminta_jarjestys], [kuutioon_ammatillinen], [kuutioon_lukio], [loadtime], [source], [username]) VALUES (0, N'ei_eronnut', N'Ei eronnut', N'*SV*Ei eronnut', N'*EN*Ei eronnut', N'Ei eronnut', N'*SV*Ei eronnut', N'*EN*Ei eronnut', N'Ei eronnut', N'*SV*Ei eronnut', N'*EN*Ei eronnut', 0, 1, 1, CAST(N'2024-05-10T22:39:02.640' AS DateTime), N'manuaalinen', N'DWI\jsyrjala2')
GO
INSERT [dw].[d_keskeyttaminen_opiskelijan_toiminta] ([id], [keskeyttaminen_opiskelijan_toiminta_koodi], [keskeyttaminen_opiskelijan_toiminta_fi], [keskeyttaminen_opiskelijan_toiminta_sv], [keskeyttaminen_opiskelijan_toiminta_en], [keskeyttaminen_opiskelijan_toiminta_taso1_fi], [keskeyttaminen_opiskelijan_toiminta_taso1_sv], [keskeyttaminen_opiskelijan_toiminta_taso1_en], [keskeyttaminen_opiskelijan_toiminta_taso0_fi], [keskeyttaminen_opiskelijan_toiminta_taso0_sv], [keskeyttaminen_opiskelijan_toiminta_taso0_en], [keskeyttaminen_opiskelijan_toiminta_jarjestys], [kuutioon_ammatillinen], [kuutioon_lukio], [loadtime], [source], [username]) VALUES (1, N'jatkaa_aikuistenops', N'Jatkoi lukion aikuisten oppimäärässä', N'', N'', N'Jatkoi', N'', N'', N'Eronnut', N'*SV*Eronnut', N'*EN*Eronnut', 21, 0, 1, CAST(N'2024-05-10T22:44:17.860' AS DateTime), N'manuaalinen', N'DWI\jsyrjala2')
GO
INSERT [dw].[d_keskeyttaminen_opiskelijan_toiminta] ([id], [keskeyttaminen_opiskelijan_toiminta_koodi], [keskeyttaminen_opiskelijan_toiminta_fi], [keskeyttaminen_opiskelijan_toiminta_sv], [keskeyttaminen_opiskelijan_toiminta_en], [keskeyttaminen_opiskelijan_toiminta_taso1_fi], [keskeyttaminen_opiskelijan_toiminta_taso1_sv], [keskeyttaminen_opiskelijan_toiminta_taso1_en], [keskeyttaminen_opiskelijan_toiminta_taso0_fi], [keskeyttaminen_opiskelijan_toiminta_taso0_sv], [keskeyttaminen_opiskelijan_toiminta_taso0_en], [keskeyttaminen_opiskelijan_toiminta_jarjestys], [kuutioon_ammatillinen], [kuutioon_lukio], [loadtime], [source], [username]) VALUES (2, N'jatkaa_amm_valmentava', N'Jatkoi ammatillisen valmentavassa', N'', N'', N'Jatkoi', N'', N'', N'Eronnut', N'*SV*Eronnut', N'*EN*Eronnut', 32, 1, 1, CAST(N'2024-05-10T22:44:17.860' AS DateTime), N'manuaalinen', N'DWI\jsyrjala2')
GO
INSERT [dw].[d_keskeyttaminen_opiskelijan_toiminta] ([id], [keskeyttaminen_opiskelijan_toiminta_koodi], [keskeyttaminen_opiskelijan_toiminta_fi], [keskeyttaminen_opiskelijan_toiminta_sv], [keskeyttaminen_opiskelijan_toiminta_en], [keskeyttaminen_opiskelijan_toiminta_taso1_fi], [keskeyttaminen_opiskelijan_toiminta_taso1_sv], [keskeyttaminen_opiskelijan_toiminta_taso1_en], [keskeyttaminen_opiskelijan_toiminta_taso0_fi], [keskeyttaminen_opiskelijan_toiminta_taso0_sv], [keskeyttaminen_opiskelijan_toiminta_taso0_en], [keskeyttaminen_opiskelijan_toiminta_jarjestys], [kuutioon_ammatillinen], [kuutioon_lukio], [loadtime], [source], [username]) VALUES (3, N'jatkaa_ammatillinen', N'Jatkoi ammatillisessa koulutuksessa', N'', N'', N'Jatkoi', N'', N'', N'Eronnut', N'*SV*Eronnut', N'*EN*Eronnut', 36, 1, 1, CAST(N'2024-05-10T22:44:17.860' AS DateTime), N'manuaalinen', N'DWI\jsyrjala2')
GO
INSERT [dw].[d_keskeyttaminen_opiskelijan_toiminta] ([id], [keskeyttaminen_opiskelijan_toiminta_koodi], [keskeyttaminen_opiskelijan_toiminta_fi], [keskeyttaminen_opiskelijan_toiminta_sv], [keskeyttaminen_opiskelijan_toiminta_en], [keskeyttaminen_opiskelijan_toiminta_taso1_fi], [keskeyttaminen_opiskelijan_toiminta_taso1_sv], [keskeyttaminen_opiskelijan_toiminta_taso1_en], [keskeyttaminen_opiskelijan_toiminta_taso0_fi], [keskeyttaminen_opiskelijan_toiminta_taso0_sv], [keskeyttaminen_opiskelijan_toiminta_taso0_en], [keskeyttaminen_opiskelijan_toiminta_jarjestys], [kuutioon_ammatillinen], [kuutioon_lukio], [loadtime], [source], [username]) VALUES (4, N'jatkaa_kj', N'Jatkoi samalla koulutuksen järjestäjällä', N'', N'', N'Jatkoi', N'', N'', N'Eronnut', N'*SV*Eronnut', N'*EN*Eronnut', 41, 1, 1, CAST(N'2024-05-10T22:44:17.863' AS DateTime), N'manuaalinen', N'DWI\jsyrjala2')
GO
INSERT [dw].[d_keskeyttaminen_opiskelijan_toiminta] ([id], [keskeyttaminen_opiskelijan_toiminta_koodi], [keskeyttaminen_opiskelijan_toiminta_fi], [keskeyttaminen_opiskelijan_toiminta_sv], [keskeyttaminen_opiskelijan_toiminta_en], [keskeyttaminen_opiskelijan_toiminta_taso1_fi], [keskeyttaminen_opiskelijan_toiminta_taso1_sv], [keskeyttaminen_opiskelijan_toiminta_taso1_en], [keskeyttaminen_opiskelijan_toiminta_taso0_fi], [keskeyttaminen_opiskelijan_toiminta_taso0_sv], [keskeyttaminen_opiskelijan_toiminta_taso0_en], [keskeyttaminen_opiskelijan_toiminta_jarjestys], [kuutioon_ammatillinen], [kuutioon_lukio], [loadtime], [source], [username]) VALUES (5, N'jatkaa_kj_siirtyi_amm', N'Jatkoi samalla koulutuksen järjestäjällä (siirtyi ammatilliseen)', N'', N'', N'Jatkoi', N'', N'', N'Eronnut', N'*SV*Eronnut', N'*EN*Eronnut', 42, 0, 1, CAST(N'2024-05-10T22:44:17.863' AS DateTime), N'manuaalinen', N'DWI\jsyrjala2')
GO
INSERT [dw].[d_keskeyttaminen_opiskelijan_toiminta] ([id], [keskeyttaminen_opiskelijan_toiminta_koodi], [keskeyttaminen_opiskelijan_toiminta_fi], [keskeyttaminen_opiskelijan_toiminta_sv], [keskeyttaminen_opiskelijan_toiminta_en], [keskeyttaminen_opiskelijan_toiminta_taso1_fi], [keskeyttaminen_opiskelijan_toiminta_taso1_sv], [keskeyttaminen_opiskelijan_toiminta_taso1_en], [keskeyttaminen_opiskelijan_toiminta_taso0_fi], [keskeyttaminen_opiskelijan_toiminta_taso0_sv], [keskeyttaminen_opiskelijan_toiminta_taso0_en], [keskeyttaminen_opiskelijan_toiminta_jarjestys], [kuutioon_ammatillinen], [kuutioon_lukio], [loadtime], [source], [username]) VALUES (6, N'jatkaa_koulutusala_taso1_boo', N'Jatkoi samalla koulutusalalla, taso 1', N'', N'', N'Jatkoi', N'', N'', N'Eronnut', N'*SV*Eronnut', N'*EN*Eronnut', 14, 1, 0, CAST(N'2024-05-10T22:44:17.867' AS DateTime), N'manuaalinen', N'DWI\jsyrjala2')
GO
INSERT [dw].[d_keskeyttaminen_opiskelijan_toiminta] ([id], [keskeyttaminen_opiskelijan_toiminta_koodi], [keskeyttaminen_opiskelijan_toiminta_fi], [keskeyttaminen_opiskelijan_toiminta_sv], [keskeyttaminen_opiskelijan_toiminta_en], [keskeyttaminen_opiskelijan_toiminta_taso1_fi], [keskeyttaminen_opiskelijan_toiminta_taso1_sv], [keskeyttaminen_opiskelijan_toiminta_taso1_en], [keskeyttaminen_opiskelijan_toiminta_taso0_fi], [keskeyttaminen_opiskelijan_toiminta_taso0_sv], [keskeyttaminen_opiskelijan_toiminta_taso0_en], [keskeyttaminen_opiskelijan_toiminta_jarjestys], [kuutioon_ammatillinen], [kuutioon_lukio], [loadtime], [source], [username]) VALUES (7, N'jatkaa_koulutusala_taso2_boo', N'Jatkoi samalla koulutusalalla, taso 2', N'', N'', N'Jatkoi', N'', N'', N'Eronnut', N'*SV*Eronnut', N'*EN*Eronnut', 13, 1, 0, CAST(N'2024-05-10T22:44:17.867' AS DateTime), N'manuaalinen', N'DWI\jsyrjala2')
GO
INSERT [dw].[d_keskeyttaminen_opiskelijan_toiminta] ([id], [keskeyttaminen_opiskelijan_toiminta_koodi], [keskeyttaminen_opiskelijan_toiminta_fi], [keskeyttaminen_opiskelijan_toiminta_sv], [keskeyttaminen_opiskelijan_toiminta_en], [keskeyttaminen_opiskelijan_toiminta_taso1_fi], [keskeyttaminen_opiskelijan_toiminta_taso1_sv], [keskeyttaminen_opiskelijan_toiminta_taso1_en], [keskeyttaminen_opiskelijan_toiminta_taso0_fi], [keskeyttaminen_opiskelijan_toiminta_taso0_sv], [keskeyttaminen_opiskelijan_toiminta_taso0_en], [keskeyttaminen_opiskelijan_toiminta_jarjestys], [kuutioon_ammatillinen], [kuutioon_lukio], [loadtime], [source], [username]) VALUES (8, N'jatkaa_koulutusala_taso3_boo', N'Jatkoi samalla koulutusalalla, taso 3', N'', N'', N'Jatkoi', N'', N'', N'Eronnut', N'*SV*Eronnut', N'*EN*Eronnut', 12, 1, 0, CAST(N'2024-05-10T22:44:17.870' AS DateTime), N'manuaalinen', N'DWI\jsyrjala2')
GO
INSERT [dw].[d_keskeyttaminen_opiskelijan_toiminta] ([id], [keskeyttaminen_opiskelijan_toiminta_koodi], [keskeyttaminen_opiskelijan_toiminta_fi], [keskeyttaminen_opiskelijan_toiminta_sv], [keskeyttaminen_opiskelijan_toiminta_en], [keskeyttaminen_opiskelijan_toiminta_taso1_fi], [keskeyttaminen_opiskelijan_toiminta_taso1_sv], [keskeyttaminen_opiskelijan_toiminta_taso1_en], [keskeyttaminen_opiskelijan_toiminta_taso0_fi], [keskeyttaminen_opiskelijan_toiminta_taso0_sv], [keskeyttaminen_opiskelijan_toiminta_taso0_en], [keskeyttaminen_opiskelijan_toiminta_jarjestys], [kuutioon_ammatillinen], [kuutioon_lukio], [loadtime], [source], [username]) VALUES (9, N'jatkaa_lukio_valmentava', N'Jatkoi lukion valmentavassa', N'', N'', N'Jatkoi', N'', N'', N'Eronnut', N'*SV*Eronnut', N'*EN*Eronnut', 33, 1, 1, CAST(N'2024-05-10T22:44:17.870' AS DateTime), N'manuaalinen', N'DWI\jsyrjala2')
GO
INSERT [dw].[d_keskeyttaminen_opiskelijan_toiminta] ([id], [keskeyttaminen_opiskelijan_toiminta_koodi], [keskeyttaminen_opiskelijan_toiminta_fi], [keskeyttaminen_opiskelijan_toiminta_sv], [keskeyttaminen_opiskelijan_toiminta_en], [keskeyttaminen_opiskelijan_toiminta_taso1_fi], [keskeyttaminen_opiskelijan_toiminta_taso1_sv], [keskeyttaminen_opiskelijan_toiminta_taso1_en], [keskeyttaminen_opiskelijan_toiminta_taso0_fi], [keskeyttaminen_opiskelijan_toiminta_taso0_sv], [keskeyttaminen_opiskelijan_toiminta_taso0_en], [keskeyttaminen_opiskelijan_toiminta_jarjestys], [kuutioon_ammatillinen], [kuutioon_lukio], [loadtime], [source], [username]) VALUES (10, N'jatkaa_muu_ammatillinen', N'Jatkoi muussa ammatillisessa', N'', N'', N'Jatkoi', N'', N'', N'Eronnut', N'*SV*Eronnut', N'*EN*Eronnut', 31, 1, 1, CAST(N'2024-05-10T22:44:17.870' AS DateTime), N'manuaalinen', N'DWI\jsyrjala2')
GO
INSERT [dw].[d_keskeyttaminen_opiskelijan_toiminta] ([id], [keskeyttaminen_opiskelijan_toiminta_koodi], [keskeyttaminen_opiskelijan_toiminta_fi], [keskeyttaminen_opiskelijan_toiminta_sv], [keskeyttaminen_opiskelijan_toiminta_en], [keskeyttaminen_opiskelijan_toiminta_taso1_fi], [keskeyttaminen_opiskelijan_toiminta_taso1_sv], [keskeyttaminen_opiskelijan_toiminta_taso1_en], [keskeyttaminen_opiskelijan_toiminta_taso0_fi], [keskeyttaminen_opiskelijan_toiminta_taso0_sv], [keskeyttaminen_opiskelijan_toiminta_taso0_en], [keskeyttaminen_opiskelijan_toiminta_jarjestys], [kuutioon_ammatillinen], [kuutioon_lukio], [loadtime], [source], [username]) VALUES (11, N'jatkaa_nuortenops', N'Jatkoi lukion nuorten oppimäärässä', N'', N'', N'Jatkoi', N'', N'', N'Eronnut', N'*SV*Eronnut', N'*EN*Eronnut', 20, 0, 1, CAST(N'2024-05-10T22:44:17.873' AS DateTime), N'manuaalinen', N'DWI\jsyrjala2')
GO
INSERT [dw].[d_keskeyttaminen_opiskelijan_toiminta] ([id], [keskeyttaminen_opiskelijan_toiminta_koodi], [keskeyttaminen_opiskelijan_toiminta_fi], [keskeyttaminen_opiskelijan_toiminta_sv], [keskeyttaminen_opiskelijan_toiminta_en], [keskeyttaminen_opiskelijan_toiminta_taso1_fi], [keskeyttaminen_opiskelijan_toiminta_taso1_sv], [keskeyttaminen_opiskelijan_toiminta_taso1_en], [keskeyttaminen_opiskelijan_toiminta_taso0_fi], [keskeyttaminen_opiskelijan_toiminta_taso0_sv], [keskeyttaminen_opiskelijan_toiminta_taso0_en], [keskeyttaminen_opiskelijan_toiminta_jarjestys], [kuutioon_ammatillinen], [kuutioon_lukio], [loadtime], [source], [username]) VALUES (12, N'jatkaa_oppilaitos', N'Jatkoi samassa oppilaitoksessa', N'', N'', N'Jatkoi', N'', N'', N'Eronnut', N'*SV*Eronnut', N'*EN*Eronnut', 40, 1, 1, CAST(N'2024-05-10T22:44:17.873' AS DateTime), N'manuaalinen', N'DWI\jsyrjala2')
GO
INSERT [dw].[d_keskeyttaminen_opiskelijan_toiminta] ([id], [keskeyttaminen_opiskelijan_toiminta_koodi], [keskeyttaminen_opiskelijan_toiminta_fi], [keskeyttaminen_opiskelijan_toiminta_sv], [keskeyttaminen_opiskelijan_toiminta_en], [keskeyttaminen_opiskelijan_toiminta_taso1_fi], [keskeyttaminen_opiskelijan_toiminta_taso1_sv], [keskeyttaminen_opiskelijan_toiminta_taso1_en], [keskeyttaminen_opiskelijan_toiminta_taso0_fi], [keskeyttaminen_opiskelijan_toiminta_taso0_sv], [keskeyttaminen_opiskelijan_toiminta_taso0_en], [keskeyttaminen_opiskelijan_toiminta_jarjestys], [kuutioon_ammatillinen], [kuutioon_lukio], [loadtime], [source], [username]) VALUES (13, N'jatkaa_toinen_aste_boo', N'Jatkoi toisen asteen koulutuksessa', N'', N'', N'Jatkoi', N'', N'', N'Eronnut', N'*SV*Eronnut', N'*EN*Eronnut', 39, 1, 1, CAST(N'2024-05-10T22:44:17.873' AS DateTime), N'manuaalinen', N'DWI\jsyrjala2')
GO
INSERT [dw].[d_keskeyttaminen_opiskelijan_toiminta] ([id], [keskeyttaminen_opiskelijan_toiminta_koodi], [keskeyttaminen_opiskelijan_toiminta_fi], [keskeyttaminen_opiskelijan_toiminta_sv], [keskeyttaminen_opiskelijan_toiminta_en], [keskeyttaminen_opiskelijan_toiminta_taso1_fi], [keskeyttaminen_opiskelijan_toiminta_taso1_sv], [keskeyttaminen_opiskelijan_toiminta_taso1_en], [keskeyttaminen_opiskelijan_toiminta_taso0_fi], [keskeyttaminen_opiskelijan_toiminta_taso0_sv], [keskeyttaminen_opiskelijan_toiminta_taso0_en], [keskeyttaminen_opiskelijan_toiminta_jarjestys], [kuutioon_ammatillinen], [kuutioon_lukio], [loadtime], [source], [username]) VALUES (14, N'jatkaa_tutkinto_boo', N'Jatkoi samassa tutkinnossa', N'', N'', N'Jatkoi', N'', N'', N'Eronnut', N'*SV*Eronnut', N'*EN*Eronnut', 10, 1, 0, CAST(N'2024-05-10T22:44:17.877' AS DateTime), N'manuaalinen', N'DWI\jsyrjala2')
GO
INSERT [dw].[d_keskeyttaminen_opiskelijan_toiminta] ([id], [keskeyttaminen_opiskelijan_toiminta_koodi], [keskeyttaminen_opiskelijan_toiminta_fi], [keskeyttaminen_opiskelijan_toiminta_sv], [keskeyttaminen_opiskelijan_toiminta_en], [keskeyttaminen_opiskelijan_toiminta_taso1_fi], [keskeyttaminen_opiskelijan_toiminta_taso1_sv], [keskeyttaminen_opiskelijan_toiminta_taso1_en], [keskeyttaminen_opiskelijan_toiminta_taso0_fi], [keskeyttaminen_opiskelijan_toiminta_taso0_sv], [keskeyttaminen_opiskelijan_toiminta_taso0_en], [keskeyttaminen_opiskelijan_toiminta_jarjestys], [kuutioon_ammatillinen], [kuutioon_lukio], [loadtime], [source], [username]) VALUES (15, N'jatkaa_tutkintotyyppi', N'Jatkoi samassa tutkintotyypissä', N'', N'', N'Jatkoi', N'', N'', N'Eronnut', N'*SV*Eronnut', N'*EN*Eronnut', 11, 1, 0, CAST(N'2024-05-10T22:44:17.877' AS DateTime), N'manuaalinen', N'DWI\jsyrjala2')
GO
INSERT [dw].[d_keskeyttaminen_opiskelijan_toiminta] ([id], [keskeyttaminen_opiskelijan_toiminta_koodi], [keskeyttaminen_opiskelijan_toiminta_fi], [keskeyttaminen_opiskelijan_toiminta_sv], [keskeyttaminen_opiskelijan_toiminta_en], [keskeyttaminen_opiskelijan_toiminta_taso1_fi], [keskeyttaminen_opiskelijan_toiminta_taso1_sv], [keskeyttaminen_opiskelijan_toiminta_taso1_en], [keskeyttaminen_opiskelijan_toiminta_taso0_fi], [keskeyttaminen_opiskelijan_toiminta_taso0_sv], [keskeyttaminen_opiskelijan_toiminta_taso0_en], [keskeyttaminen_opiskelijan_toiminta_jarjestys], [kuutioon_ammatillinen], [kuutioon_lukio], [loadtime], [source], [username]) VALUES (16, N'jatkaa_valmentava', N'Jatkoi valmentavassa koulutuksessa', N'', N'', N'Jatkoi', N'', N'', N'Eronnut', N'*SV*Eronnut', N'*EN*Eronnut', 34, 1, 1, CAST(N'2024-05-10T22:44:17.877' AS DateTime), N'manuaalinen', N'DWI\jsyrjala2')
GO
INSERT [dw].[d_keskeyttaminen_opiskelijan_toiminta] ([id], [keskeyttaminen_opiskelijan_toiminta_koodi], [keskeyttaminen_opiskelijan_toiminta_fi], [keskeyttaminen_opiskelijan_toiminta_sv], [keskeyttaminen_opiskelijan_toiminta_en], [keskeyttaminen_opiskelijan_toiminta_taso1_fi], [keskeyttaminen_opiskelijan_toiminta_taso1_sv], [keskeyttaminen_opiskelijan_toiminta_taso1_en], [keskeyttaminen_opiskelijan_toiminta_taso0_fi], [keskeyttaminen_opiskelijan_toiminta_taso0_sv], [keskeyttaminen_opiskelijan_toiminta_taso0_en], [keskeyttaminen_opiskelijan_toiminta_jarjestys], [kuutioon_ammatillinen], [kuutioon_lukio], [loadtime], [source], [username]) VALUES (17, N'jatkaa_yleissivistava', N'Jatkoi yleissivistävässä koulutuksessa', N'', N'', N'Jatkoi', N'', N'', N'Eronnut', N'*SV*Eronnut', N'*EN*Eronnut', 38, 1, 1, CAST(N'2024-05-10T22:44:17.880' AS DateTime), N'manuaalinen', N'DWI\jsyrjala2')
GO
INSERT [dw].[d_keskeyttaminen_opiskelijan_toiminta] ([id], [keskeyttaminen_opiskelijan_toiminta_koodi], [keskeyttaminen_opiskelijan_toiminta_fi], [keskeyttaminen_opiskelijan_toiminta_sv], [keskeyttaminen_opiskelijan_toiminta_en], [keskeyttaminen_opiskelijan_toiminta_taso1_fi], [keskeyttaminen_opiskelijan_toiminta_taso1_sv], [keskeyttaminen_opiskelijan_toiminta_taso1_en], [keskeyttaminen_opiskelijan_toiminta_taso0_fi], [keskeyttaminen_opiskelijan_toiminta_taso0_sv], [keskeyttaminen_opiskelijan_toiminta_taso0_en], [keskeyttaminen_opiskelijan_toiminta_jarjestys], [kuutioon_ammatillinen], [kuutioon_lukio], [loadtime], [source], [username]) VALUES (18, N'keskeyttanyt_amm_koulutus', N'Keskeytti amm. koulutuksen', N'', N'', N'Keskeytti', N'', N'', N'Eronnut', N'*SV*Eronnut', N'*EN*Eronnut', 51, 1, 0, CAST(N'2024-05-10T22:44:17.880' AS DateTime), N'manuaalinen', N'DWI\jsyrjala2')
GO
INSERT [dw].[d_keskeyttaminen_opiskelijan_toiminta] ([id], [keskeyttaminen_opiskelijan_toiminta_koodi], [keskeyttaminen_opiskelijan_toiminta_fi], [keskeyttaminen_opiskelijan_toiminta_sv], [keskeyttaminen_opiskelijan_toiminta_en], [keskeyttaminen_opiskelijan_toiminta_taso1_fi], [keskeyttaminen_opiskelijan_toiminta_taso1_sv], [keskeyttaminen_opiskelijan_toiminta_taso1_en], [keskeyttaminen_opiskelijan_toiminta_taso0_fi], [keskeyttaminen_opiskelijan_toiminta_taso0_sv], [keskeyttaminen_opiskelijan_toiminta_taso0_en], [keskeyttaminen_opiskelijan_toiminta_jarjestys], [kuutioon_ammatillinen], [kuutioon_lukio], [loadtime], [source], [username]) VALUES (19, N'keskeyttanyt_amm_tutkintokoulutus', N'Keskeytti amm. tutkintokoulutuksen', N'', N'', N'Keskeytti', N'', N'', N'Eronnut', N'*SV*Eronnut', N'*EN*Eronnut', 50, 1, 0, CAST(N'2024-05-10T22:44:17.880' AS DateTime), N'manuaalinen', N'DWI\jsyrjala2')
GO
INSERT [dw].[d_keskeyttaminen_opiskelijan_toiminta] ([id], [keskeyttaminen_opiskelijan_toiminta_koodi], [keskeyttaminen_opiskelijan_toiminta_fi], [keskeyttaminen_opiskelijan_toiminta_sv], [keskeyttaminen_opiskelijan_toiminta_en], [keskeyttaminen_opiskelijan_toiminta_taso1_fi], [keskeyttaminen_opiskelijan_toiminta_taso1_sv], [keskeyttaminen_opiskelijan_toiminta_taso1_en], [keskeyttaminen_opiskelijan_toiminta_taso0_fi], [keskeyttaminen_opiskelijan_toiminta_taso0_sv], [keskeyttaminen_opiskelijan_toiminta_taso0_en], [keskeyttaminen_opiskelijan_toiminta_jarjestys], [kuutioon_ammatillinen], [kuutioon_lukio], [loadtime], [source], [username]) VALUES (20, N'keskeyttanyt_toinen_aste', N'Keskeytti toisen asteen', N'', N'', N'Keskeytti', N'', N'', N'Eronnut', N'*SV*Eronnut', N'*EN*Eronnut', 52, 1, 1, CAST(N'2024-05-10T22:44:17.880' AS DateTime), N'manuaalinen', N'DWI\jsyrjala2')
GO
INSERT [dw].[d_keskeyttaminen_opiskelijan_toiminta] ([id], [keskeyttaminen_opiskelijan_toiminta_koodi], [keskeyttaminen_opiskelijan_toiminta_fi], [keskeyttaminen_opiskelijan_toiminta_sv], [keskeyttaminen_opiskelijan_toiminta_en], [keskeyttaminen_opiskelijan_toiminta_taso1_fi], [keskeyttaminen_opiskelijan_toiminta_taso1_sv], [keskeyttaminen_opiskelijan_toiminta_taso1_en], [keskeyttaminen_opiskelijan_toiminta_taso0_fi], [keskeyttaminen_opiskelijan_toiminta_taso0_sv], [keskeyttaminen_opiskelijan_toiminta_taso0_en], [keskeyttaminen_opiskelijan_toiminta_jarjestys], [kuutioon_ammatillinen], [kuutioon_lukio], [loadtime], [source], [username]) VALUES (21, N'vaihtoi_amm_koulutusala_taso_1', N'Vaihtoi amm. koulutusalaa, taso 1', N'', N'', N'Vaihtoi', N'', N'', N'Eronnut', N'*SV*Eronnut', N'*EN*Eronnut', 64, 1, 0, CAST(N'2024-05-10T22:44:17.883' AS DateTime), N'manuaalinen', N'DWI\jsyrjala2')
GO
INSERT [dw].[d_keskeyttaminen_opiskelijan_toiminta] ([id], [keskeyttaminen_opiskelijan_toiminta_koodi], [keskeyttaminen_opiskelijan_toiminta_fi], [keskeyttaminen_opiskelijan_toiminta_sv], [keskeyttaminen_opiskelijan_toiminta_en], [keskeyttaminen_opiskelijan_toiminta_taso1_fi], [keskeyttaminen_opiskelijan_toiminta_taso1_sv], [keskeyttaminen_opiskelijan_toiminta_taso1_en], [keskeyttaminen_opiskelijan_toiminta_taso0_fi], [keskeyttaminen_opiskelijan_toiminta_taso0_sv], [keskeyttaminen_opiskelijan_toiminta_taso0_en], [keskeyttaminen_opiskelijan_toiminta_jarjestys], [kuutioon_ammatillinen], [kuutioon_lukio], [loadtime], [source], [username]) VALUES (22, N'vaihtoi_amm_koulutusala_taso_2', N'Vaihtoi amm. koulutusalaa, taso 2', N'', N'', N'Vaihtoi', N'', N'', N'Eronnut', N'*SV*Eronnut', N'*EN*Eronnut', 63, 1, 0, CAST(N'2024-05-10T22:44:17.883' AS DateTime), N'manuaalinen', N'DWI\jsyrjala2')
GO
INSERT [dw].[d_keskeyttaminen_opiskelijan_toiminta] ([id], [keskeyttaminen_opiskelijan_toiminta_koodi], [keskeyttaminen_opiskelijan_toiminta_fi], [keskeyttaminen_opiskelijan_toiminta_sv], [keskeyttaminen_opiskelijan_toiminta_en], [keskeyttaminen_opiskelijan_toiminta_taso1_fi], [keskeyttaminen_opiskelijan_toiminta_taso1_sv], [keskeyttaminen_opiskelijan_toiminta_taso1_en], [keskeyttaminen_opiskelijan_toiminta_taso0_fi], [keskeyttaminen_opiskelijan_toiminta_taso0_sv], [keskeyttaminen_opiskelijan_toiminta_taso0_en], [keskeyttaminen_opiskelijan_toiminta_jarjestys], [kuutioon_ammatillinen], [kuutioon_lukio], [loadtime], [source], [username]) VALUES (23, N'vaihtoi_amm_koulutusala_taso_3', N'Vaihtoi amm. koulutusalaa, taso 3', N'', N'', N'Vaihtoi', N'', N'', N'Eronnut', N'*SV*Eronnut', N'*EN*Eronnut', 62, 1, 0, CAST(N'2024-05-10T22:44:17.883' AS DateTime), N'manuaalinen', N'DWI\jsyrjala2')
GO
INSERT [dw].[d_keskeyttaminen_opiskelijan_toiminta] ([id], [keskeyttaminen_opiskelijan_toiminta_koodi], [keskeyttaminen_opiskelijan_toiminta_fi], [keskeyttaminen_opiskelijan_toiminta_sv], [keskeyttaminen_opiskelijan_toiminta_en], [keskeyttaminen_opiskelijan_toiminta_taso1_fi], [keskeyttaminen_opiskelijan_toiminta_taso1_sv], [keskeyttaminen_opiskelijan_toiminta_taso1_en], [keskeyttaminen_opiskelijan_toiminta_taso0_fi], [keskeyttaminen_opiskelijan_toiminta_taso0_sv], [keskeyttaminen_opiskelijan_toiminta_taso0_en], [keskeyttaminen_opiskelijan_toiminta_jarjestys], [kuutioon_ammatillinen], [kuutioon_lukio], [loadtime], [source], [username]) VALUES (24, N'vaihtoi_amm_tutkinto', N'Vaihtoi amm. tutkintoa', N'', N'', N'Vaihtoi', N'', N'', N'Eronnut', N'*SV*Eronnut', N'*EN*Eronnut', 60, 1, 0, CAST(N'2024-05-10T22:44:17.887' AS DateTime), N'manuaalinen', N'DWI\jsyrjala2')
GO
INSERT [dw].[d_keskeyttaminen_opiskelijan_toiminta] ([id], [keskeyttaminen_opiskelijan_toiminta_koodi], [keskeyttaminen_opiskelijan_toiminta_fi], [keskeyttaminen_opiskelijan_toiminta_sv], [keskeyttaminen_opiskelijan_toiminta_en], [keskeyttaminen_opiskelijan_toiminta_taso1_fi], [keskeyttaminen_opiskelijan_toiminta_taso1_sv], [keskeyttaminen_opiskelijan_toiminta_taso1_en], [keskeyttaminen_opiskelijan_toiminta_taso0_fi], [keskeyttaminen_opiskelijan_toiminta_taso0_sv], [keskeyttaminen_opiskelijan_toiminta_taso0_en], [keskeyttaminen_opiskelijan_toiminta_jarjestys], [kuutioon_ammatillinen], [kuutioon_lukio], [loadtime], [source], [username]) VALUES (25, N'vaihtoi_amm_tutkintotyyppi', N'Vaihtoi amm. tutkintotyyppiä', N'', N'', N'Vaihtoi', N'', N'', N'Eronnut', N'*SV*Eronnut', N'*EN*Eronnut', 61, 1, 0, CAST(N'2024-05-10T22:44:17.887' AS DateTime), N'manuaalinen', N'DWI\jsyrjala2')
GO
INSERT [dw].[d_keskeyttaminen_opiskelijan_toiminta] ([id], [keskeyttaminen_opiskelijan_toiminta_koodi], [keskeyttaminen_opiskelijan_toiminta_fi], [keskeyttaminen_opiskelijan_toiminta_sv], [keskeyttaminen_opiskelijan_toiminta_en], [keskeyttaminen_opiskelijan_toiminta_taso1_fi], [keskeyttaminen_opiskelijan_toiminta_taso1_sv], [keskeyttaminen_opiskelijan_toiminta_taso1_en], [keskeyttaminen_opiskelijan_toiminta_taso0_fi], [keskeyttaminen_opiskelijan_toiminta_taso0_sv], [keskeyttaminen_opiskelijan_toiminta_taso0_en], [keskeyttaminen_opiskelijan_toiminta_jarjestys], [kuutioon_ammatillinen], [kuutioon_lukio], [loadtime], [source], [username]) VALUES (26, N'vaihtoi_kj_eri_amm_tutkinto', N'Vaihtoi koulutuksen järjestäjää (eri amm. tutkinto)', N'', N'', N'Vaihtoi', N'', N'', N'Eronnut', N'*SV*Eronnut', N'*EN*Eronnut', 66, 1, 0, CAST(N'2024-05-10T22:44:17.890' AS DateTime), N'manuaalinen', N'DWI\jsyrjala2')
GO
INSERT [dw].[d_keskeyttaminen_opiskelijan_toiminta] ([id], [keskeyttaminen_opiskelijan_toiminta_koodi], [keskeyttaminen_opiskelijan_toiminta_fi], [keskeyttaminen_opiskelijan_toiminta_sv], [keskeyttaminen_opiskelijan_toiminta_en], [keskeyttaminen_opiskelijan_toiminta_taso1_fi], [keskeyttaminen_opiskelijan_toiminta_taso1_sv], [keskeyttaminen_opiskelijan_toiminta_taso1_en], [keskeyttaminen_opiskelijan_toiminta_taso0_fi], [keskeyttaminen_opiskelijan_toiminta_taso0_sv], [keskeyttaminen_opiskelijan_toiminta_taso0_en], [keskeyttaminen_opiskelijan_toiminta_jarjestys], [kuutioon_ammatillinen], [kuutioon_lukio], [loadtime], [source], [username]) VALUES (27, N'vaihtoi_kj_siirtyi_amm', N'Vaihtoi koulutuksen järjestäjää (siirtyi ammatilliseen)', N'', N'', N'Vaihtoi', N'', N'', N'Eronnut', N'*SV*Eronnut', N'*EN*Eronnut', 72, 0, 1, CAST(N'2024-05-10T22:44:17.890' AS DateTime), N'manuaalinen', N'DWI\jsyrjala2')
GO
INSERT [dw].[d_keskeyttaminen_opiskelijan_toiminta] ([id], [keskeyttaminen_opiskelijan_toiminta_koodi], [keskeyttaminen_opiskelijan_toiminta_fi], [keskeyttaminen_opiskelijan_toiminta_sv], [keskeyttaminen_opiskelijan_toiminta_en], [keskeyttaminen_opiskelijan_toiminta_taso1_fi], [keskeyttaminen_opiskelijan_toiminta_taso1_sv], [keskeyttaminen_opiskelijan_toiminta_taso1_en], [keskeyttaminen_opiskelijan_toiminta_taso0_fi], [keskeyttaminen_opiskelijan_toiminta_taso0_sv], [keskeyttaminen_opiskelijan_toiminta_taso0_en], [keskeyttaminen_opiskelijan_toiminta_jarjestys], [kuutioon_ammatillinen], [kuutioon_lukio], [loadtime], [source], [username]) VALUES (28, N'vaihtoi_kj_jatkaa_lukio', N'Vaihtoi koulutuksen järjestäjää (jatkoi lukiokoulutuksessa)', N'', N'', N'Vaihtoi', N'', N'', N'Eronnut', N'*SV*Eronnut', N'*EN*Eronnut', 74, 0, 1, CAST(N'2024-05-10T22:44:17.890' AS DateTime), N'manuaalinen', N'DWI\jsyrjala2')
GO
INSERT [dw].[d_keskeyttaminen_opiskelijan_toiminta] ([id], [keskeyttaminen_opiskelijan_toiminta_koodi], [keskeyttaminen_opiskelijan_toiminta_fi], [keskeyttaminen_opiskelijan_toiminta_sv], [keskeyttaminen_opiskelijan_toiminta_en], [keskeyttaminen_opiskelijan_toiminta_taso1_fi], [keskeyttaminen_opiskelijan_toiminta_taso1_sv], [keskeyttaminen_opiskelijan_toiminta_taso1_en], [keskeyttaminen_opiskelijan_toiminta_taso0_fi], [keskeyttaminen_opiskelijan_toiminta_taso0_sv], [keskeyttaminen_opiskelijan_toiminta_taso0_en], [keskeyttaminen_opiskelijan_toiminta_jarjestys], [kuutioon_ammatillinen], [kuutioon_lukio], [loadtime], [source], [username]) VALUES (29, N'vaihtoi_kj_sama_amm_tutkinto', N'Vaihtoi koulutuksen järjestäjää (sama tutkinto)', N'', N'', N'Vaihtoi', N'', N'', N'Eronnut', N'*SV*Eronnut', N'*EN*Eronnut', 65, 1, 0, CAST(N'2024-05-10T22:44:17.890' AS DateTime), N'manuaalinen', N'DWI\jsyrjala2')
GO
INSERT [dw].[d_keskeyttaminen_opiskelijan_toiminta] ([id], [keskeyttaminen_opiskelijan_toiminta_koodi], [keskeyttaminen_opiskelijan_toiminta_fi], [keskeyttaminen_opiskelijan_toiminta_sv], [keskeyttaminen_opiskelijan_toiminta_en], [keskeyttaminen_opiskelijan_toiminta_taso1_fi], [keskeyttaminen_opiskelijan_toiminta_taso1_sv], [keskeyttaminen_opiskelijan_toiminta_taso1_en], [keskeyttaminen_opiskelijan_toiminta_taso0_fi], [keskeyttaminen_opiskelijan_toiminta_taso0_sv], [keskeyttaminen_opiskelijan_toiminta_taso0_en], [keskeyttaminen_opiskelijan_toiminta_jarjestys], [kuutioon_ammatillinen], [kuutioon_lukio], [loadtime], [source], [username]) VALUES (30, N'vaihtoi_kj_sama_lukio_tutkinto', N'Vaihtoi koulutuksen järjestäjää (sama tutkinto)', N'', N'', N'Vaihtoi', N'', N'', N'Eronnut', N'*SV*Eronnut', N'*EN*Eronnut', 73, 0, 1, CAST(N'2024-05-10T22:44:17.890' AS DateTime), N'manuaalinen', N'DWI\jsyrjala2')
GO
INSERT [dw].[d_keskeyttaminen_opiskelijan_toiminta] ([id], [keskeyttaminen_opiskelijan_toiminta_koodi], [keskeyttaminen_opiskelijan_toiminta_fi], [keskeyttaminen_opiskelijan_toiminta_sv], [keskeyttaminen_opiskelijan_toiminta_en], [keskeyttaminen_opiskelijan_toiminta_taso1_fi], [keskeyttaminen_opiskelijan_toiminta_taso1_sv], [keskeyttaminen_opiskelijan_toiminta_taso1_en], [keskeyttaminen_opiskelijan_toiminta_taso0_fi], [keskeyttaminen_opiskelijan_toiminta_taso0_sv], [keskeyttaminen_opiskelijan_toiminta_taso0_en], [keskeyttaminen_opiskelijan_toiminta_jarjestys], [kuutioon_ammatillinen], [kuutioon_lukio], [loadtime], [source], [username]) VALUES (31, N'vaihtoi_lukio', N'Vaihtoi lukiota', N'', N'', N'Vaihtoi', N'', N'', N'Eronnut', N'*SV*Eronnut', N'*EN*Eronnut', 70, 0, 1, CAST(N'2024-05-10T22:44:17.893' AS DateTime), N'manuaalinen', N'DWI\jsyrjala2')
GO
INSERT [dw].[d_keskeyttaminen_opiskelijan_toiminta] ([id], [keskeyttaminen_opiskelijan_toiminta_koodi], [keskeyttaminen_opiskelijan_toiminta_fi], [keskeyttaminen_opiskelijan_toiminta_sv], [keskeyttaminen_opiskelijan_toiminta_en], [keskeyttaminen_opiskelijan_toiminta_taso1_fi], [keskeyttaminen_opiskelijan_toiminta_taso1_sv], [keskeyttaminen_opiskelijan_toiminta_taso1_en], [keskeyttaminen_opiskelijan_toiminta_taso0_fi], [keskeyttaminen_opiskelijan_toiminta_taso0_sv], [keskeyttaminen_opiskelijan_toiminta_taso0_en], [keskeyttaminen_opiskelijan_toiminta_jarjestys], [kuutioon_ammatillinen], [kuutioon_lukio], [loadtime], [source], [username]) VALUES (32, N'vaihtoi_lukio_sama_kj', N'Vaihtoi lukiota samalla koulutuksen järjestäjällä', N'', N'', N'Vaihtoi', N'', N'', N'Eronnut', N'*SV*Eronnut', N'*EN*Eronnut', 71, 0, 1, CAST(N'2024-05-10T22:44:17.893' AS DateTime), N'manuaalinen', N'DWI\jsyrjala2')
GO
INSERT [dw].[d_keskeyttaminen_opiskelijan_toiminta] ([id], [keskeyttaminen_opiskelijan_toiminta_koodi], [keskeyttaminen_opiskelijan_toiminta_fi], [keskeyttaminen_opiskelijan_toiminta_sv], [keskeyttaminen_opiskelijan_toiminta_en], [keskeyttaminen_opiskelijan_toiminta_taso1_fi], [keskeyttaminen_opiskelijan_toiminta_taso1_sv], [keskeyttaminen_opiskelijan_toiminta_taso1_en], [keskeyttaminen_opiskelijan_toiminta_taso0_fi], [keskeyttaminen_opiskelijan_toiminta_taso0_sv], [keskeyttaminen_opiskelijan_toiminta_taso0_en], [keskeyttaminen_opiskelijan_toiminta_jarjestys], [kuutioon_ammatillinen], [kuutioon_lukio], [loadtime], [source], [username]) VALUES (34, N'vaihtoi_tutkinto_siirtyi_amm', N'Vaihtoi tutkintoa (siirtyi ammatilliseen)', N'', N'', N'Vaihtoi', N'', N'', N'Eronnut', N'*SV*Eronnut', N'*EN*Eronnut', 75, 0, 1, CAST(N'2024-05-10T22:35:02.850' AS DateTime), N'manuaalinen', N'DWI\jsyrjala2')
GO

SET IDENTITY_INSERT [dw].[d_keskeyttaminen_opiskelijan_toiminta] OFF
GO

ALTER TABLE [dw].[d_keskeyttaminen_opiskelijan_toiminta] ADD  CONSTRAINT [DF__d_keskeyttaminen_opiskelijan_toiminta__loadtime]  DEFAULT (getdate()) FOR [loadtime]
GO
ALTER TABLE [dw].[d_keskeyttaminen_opiskelijan_toiminta] ADD  CONSTRAINT [DF__d_keskeyttaminen_opiskelijan_toiminta__username]  DEFAULT (suser_name()) FOR [username]
GO
