USE ANTERO
GO
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [KEHMENOT] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [AINEETOI] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [LIIKEAR] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [KLIIKEAR] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [MUUPMENO] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [AHENNAKK] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [MAAVESI] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [RAKENNUS] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [KONEET] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [MUUAINH] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [ENNAKESK] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [OSUUSKON] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [SAAMIKON] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [OSUUSOYY] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [SAAMIOYY] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [MUUTOSAK] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [MUUTSAAM] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [OKRVARAT] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [AINEET] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [KESKENER] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [VALMIIT] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [MUUVOM] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [VOENNAKK] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [PMYYNTIS] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [PSKONSER] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [PSOYYRIT] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [PLAINAS] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [PLVEROS] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [PMUUTS] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [PSIIRTOS] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [LMYYNTIS] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [LSKONSER] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [LSOYYRIT] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [LLAINAS] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [LLVEROS] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [LMUUTS] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [LSIIRTOS] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [RAPOSUUS] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [RAPOSAKK] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [MUUARVOP] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [RAHATPS] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [VASTAAVA] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [PERUSPO] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [ARVONKR] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [KAYVANAR] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [OKARAHAS] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [MSIRAHAS] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [VAPRAHAS] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [TOIMPO] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [EDJAAMA] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [TKJAAMA] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [OPOYHT] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [TAVAHEM] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [TPSKERTY] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [ELAKVARA] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [VEROVARA] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [MPAKVARA] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [KRESERVI] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [OKRVELAT] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [PPAAOMAL] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [PJVELKAL] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [PVVELKAL] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [PLRAHALA] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [PELAKEL] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [PSAADUTE] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [POSTOVEL] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [PRVEKSEL] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [PVKONSER] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [PVOYYRIT] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [PMUUTVEL] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [PSIIRTOV] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [PLVEROVE] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [LPAAOMAL] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [LJVELKAL] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [LVVELKAL] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [LLRAHALA] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [LELAKEL] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [LSAADUTE] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [LOSTOVEL] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [LRVEKSEL] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [LVKONSER] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [LVOYYRIT] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [LMUUTVEL] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [LSIIRTOV] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [LLVEROVE] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [VASTATTA] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [OKRSIJYH] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [OKRRAHAS] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [OKROSAKK] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [OKRMUUAP] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [OKRRJAPS] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [OKRMUUTV] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [PORAH] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [YKRAH] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [SIJVAPRAH] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [VARARAH] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [YJRAH] bigint NULL
ALTER TABLE [sa].[sa_suorat_yo_talous_2_tase] ALTER COLUMN [VEROPVARA] bigint NULL
