USE [VipunenTK]
GO

/****** Object:  Table [dbo].[f_TOAK_2_20_Lukio_amm_oppis_opisk_ian_ja_aik_koul_mukaan]    Script Date: 26.3.2025 9.49.52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

DROP TABLE [dbo].[f_TOAK_2_20_Lukio_amm_oppis_opisk_ian_ja_aik_koul_mukaan]

GO

CREATE TABLE [dbo].[f_TOAK_2_20_Lukio_amm_oppis_opisk_ian_ja_aik_koul_mukaan](
	[tilastovuosi] [nvarchar](4) NULL,
	[tilv_date] [date] NULL,
	[lahde_id] [int] NULL,
	[oppilaitoksen_oppilaitostyyppi_id] [int] NULL,
	[koulutusluokitus_id] [int] NULL,
	[koulutusluokitus_historia_id] [int] NULL,
	[nuorten_aikuisten_koulutus_id] [int] NULL,
	[opetussuunnitelmaperusteinen_koulutus_nayttotutkintoon_valmistava_koulutus_id] [int] NULL,
	[ammatillisen_koulutuksen_koulutuslaji_id] [int] NULL,
	[opetushallinnon_koulutus_id] [int] NULL,
	[koulutuksen_kunta_id] [int] NULL,
	[koulutuksen_kunta_historia_id] [int] NULL,
	[rahoituslahde_id] [int] NULL,
	[koulutuksen_tavoite_id] [int] NULL,
	[sukupuoli_id] [int] NULL,
	[aidinkieli_versio1_id] [int] NULL,
	[kirjoihintulovuosi_id] [nvarchar](10) NULL,
	[kirjoihintulolukukausi_id] [nvarchar](10) NULL,
	[opiskelijan_olo_syys_id] [int] NULL,
	[aikaisempi_ylsk_koulutus_id] [int] NULL,
	[aikaisempi_ammpk_tarkempi] [nvarchar](100) NULL,
	[ammpk_pohjakoulutuksen_tila] [nvarchar](150) NULL,
	[aikaisemman_ammpk_opintoala2002_id] [int] NULL,
	[aikaisemman_ammpk_koulutusala2002_id] [int] NULL,
	[aikaisemman_ammpk_koulutusaste2002_id] [int] NULL,
	[aikaisemman_ammpk_koulutusala_taso2_id] [int] NULL,
	[aikaisemman_ammpk_koulutusaste_taso2_id] [int] NULL,
	[aikaisemman_ammpk_suoritusvuosi_id] [nvarchar](10) NULL,
	[aikaisempi_ammpk_nayttotutkintona_tarkempi] [nvarchar](100) NULL,
	[aikaisempi_ammpk_oppisopimuskoulutuksena_tarkempi] [nvarchar](100) NULL,
	[aikaisempi_ammlisa_tarkempi] [nvarchar](100) NULL,
	[ammlisa_pohjakoulutuksen_tila] [nvarchar](150) NULL,
	[aikaisemman_ammlisa_opintoala2002_id] [int] NULL,
	[aikaisemman_ammlisa_koulutusala2002_id] [int] NULL,
	[aikaisemman_ammlisa_koulutusaste2002_id] [int] NULL,
	[aikaisemman_ammlisa_koulutusala_taso2_id] [int] NULL,
	[aikaisemman_ammlisa_koulutusaste_taso2_id] [int] NULL,
	[aikaisemman_ammlisa_suoritusvuosi_id] [nvarchar](10) NULL,
	[aikaisempi_ammlisa_oppisopimuskoulutuksena_tarkempi] [nvarchar](100) NULL,
	[aikaisempi_alempi_kk_tarkempi] [nvarchar](100) NULL,
	[alempi_kk_pohjakoulutuksen_tila] [nvarchar](150) NULL,
	[aikaisemman_alemman_kk_opintoala1995_id] [int] NULL,
	[aikaisemman_alemman_kk_koulutusala1995_id] [int] NULL,
	[aikaisemman_alemman_kk_opintoala2002_id] [int] NULL,
	[aikaisemman_alemman_kk_koulutusala2002_id] [int] NULL,
	[aikaisemman_alemman_kk_koulutusaste2002_id] [int] NULL,
	[aikaisemman_alemman_kk_koulutusala_taso2_id] [int] NULL,
	[aikaisemman_alemman_kk_koulutusaste_taso2_id] [int] NULL,
	[aikaisemman_alemman_kk_suoritusvuosi_id] [nvarchar](10) NULL,
	[aikaisempi_ylempi_kk_tarkempi] [nvarchar](100) NULL,
	[ylempi_kk_pohjakoulutuksen_tila] [nvarchar](150) NULL,
	[aikasemman_ylemman_kk_opintoala1995_id] [int] NULL,
	[aikasemman_ylemman_kk_koulutusala1995_id] [int] NULL,
	[aikasemman_ylemman_kk_opintoala2002_id] [int] NULL,
	[aikasemman_ylemman_kk_koulutusala2002_id] [int] NULL,
	[aikasemman_ylemman_kk_koulutusaste2002_id] [int] NULL,
	[aikasemman_ylemman_kk_koulutusala_taso2_id] [int] NULL,
	[aikasemman_ylemman_kk_koulutusaste_taso2_id] [int] NULL,
	[aikaisemman_ylemman_kk_suoritusvuosi_id] [nvarchar](10) NULL,
	[opiskelijan_asuinkunta_id] [int] NULL,
	[opiskelijan_asuinkunta_historia_id] [int] NULL,
	[lukumaara] [int] NULL,
	[rivinumero] [int] NULL,
	[ika1v_id] [int] NULL,
	[ika5v_id] [int] NULL,
	[ika_14_65_id] [int] NULL,
	[aikaisemmasta_koulutuksesta_ammpk_kulunut_aika_id] [int] NULL,
	[aikaisemmasta_koulutuksesta_ammlisa_kulunut_aika_id] [int] NULL,
	[aikaisemmasta_koulutuksesta_alempi_kk_kulunut_aika_id] [int] NULL,
	[aikaisemmasta_koulutuksesta_ylempi_kk_kulunut_aika_id] [int] NULL,
	[aiemman_tutkinnon_ammpk_opintoala_sama] [nvarchar](100) NULL,
	[aiemman_tutkinnon_ammpk_koulutusala_sama] [nvarchar](100) NULL,
	[aiemman_tutkinnon_ammpk_koulutusaste_sama] [nvarchar](100) NULL,
	[aiemman_tutkinnon_ammlisa_opintoala_sama] [nvarchar](100) NULL,
	[aiemman_tutkinnon_ammlisa_koulutusala_sama] [nvarchar](100) NULL,
	[aiemman_tutkinnon_ammlisa_koulutusaste_sama] [nvarchar](100) NULL,
	[aiemman_tutkinnon_alempi_kk_opintoala_sama] [nvarchar](100) NULL,
	[aiemman_tutkinnon_alempi_kk_koulutusala_sama] [nvarchar](100) NULL,
	[aiemman_tutkinnon_alempi_kk_koulutusaste_sama] [nvarchar](100) NULL,
	[aiemman_tutkinnon_ylempi_kk_opintoala_sama] [nvarchar](100) NULL,
	[aiemman_tutkinnon_ylempi_kk_koulutusala_sama] [nvarchar](100) NULL,
	[aiemman_tutkinnon_ylempi_kk_koulutusaste_sama] [nvarchar](100) NULL,
	[aikaisempi_korkein_tutkinto_id] [int] NULL,
	[aiemman_tutkinnon_opintoala2002_sama] [nvarchar](100) NULL,
	[aiemman_tutkinnon_koulutusaste2002_sama] [nvarchar](100) NULL,
	[aiemman_tutkinnon_koulutusala2002_sama] [nvarchar](100) NULL,
	[aiemman_tutkinnon_koulutusala_taso2_sama] [nvarchar](100) NULL,
	[aiemman_tutkinnon_koulutusaste_taso2_sama] [nvarchar](100) NULL,
	[nuorten_aikuisten_koulutus_amm_id] [int] NULL,
	[koulutuksen_jarjestamismuoto_id] [int] NULL,
	[aloittaneet] [int] NULL,
	[viimeisimman_koulutuksen_suorituvuosi_id] [nvarchar](10) NULL,
	[viimeisimmasta_koulutuksesta_kulunut_aika_id] [int] NULL,
	[hallinnonala2_id] [int] NULL
) ON [PRIMARY]
GO


