USE [ANTERO]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE OR ALTER VIEW [dw].[v_TK_K1_13b] AS 

--lopulta poiminnat (limittäin) rahoituskausittain, käydään tuolloin läpi mm. aikamuuttujat

SELECT
	[tilv]
    ,[aineisto]
    ,[ikar21]
    ,[aikielir1]
    ,[prioriteetti]
    ,[toteuma_tutk]
    ,[tyov]
    ,[jarj_opisk]
    ,[jarjnimi_opisk]
    ,[jarj_tutk]
    ,[jarjnimi_tutk]
    ,[jarjmaak]
    ,[jarjmaaknimi]
    ,[tutkmaak]
    ,[tutkmaaknimi]
    ,[kaste_t2]
    ,[kaste_t2ni]
    ,[iscfibroad2013]
    ,[kala_t1ni]
    ,[oppis]
    ,[alvv]
    ,[allk]
    ,[rahoituskausi]
    ,[rahoitus]
    ,[kustannusryhma]
    ,[kaste_t2_e]
    ,[kaste_t2ni_e]
    ,[suorv_e]
    ,[ptoim1r2e]
    ,[kaste_t2_evj]
    ,[kaste_t2ni_evj]
    ,[amase]
    ,[ptoim1r2_tilv_07]
    ,[amas_tilv_07]
    ,[ptoim1r2_tilv_08]
    ,[amas_tilv_08]
    ,[ptoim1r2_tilv_09]
    ,[amas_tilv_09]
    ,[ptoim1r2_tilv_10]
    ,[amas_tilv_10]
    ,[ptoim1r2_tilv_11]
    ,[amas_tilv_11]
    ,[ptoim1r2_tilv_12]
    ,[amas_tilv_12]
    ,[ptoim1r2_tilvseur_01]
    ,[amas_tilvseur_01]
    ,[ptoim1r2_tilvseur_02]
    ,[amas_tilvseur_02]
    ,[ptoim1r2_tilvseur_03]
    ,[amas_tilvseur_03]
    ,[ptoim1r2_tilvseur_04]
    ,[amas_tilvseur_04]
    ,[ptoim1r2_tilvseur_05]
    ,[amas_tilvseur_05]
    ,[ptoim1r2_tilvseur_06]
    ,[amas_tilvseur_06]
    ,[opisk_kk]
    ,[opisk_syys]
    ,[opisk_tammi]
    ,[lkm]
FROM [TK_H9098_CSC].[dbo].[TK_K1_13b_sopv_24_2023]

UNION ALL

SELECT 
	[tilv]
    ,[aineisto]
    ,[ikar21]
    ,[aikielir1]
    ,[prioriteetti]
    ,[toteuma_tutk]
    ,[tyov]
    ,[jarj_opisk]
    ,[jarjnimi_opisk]
    ,[jarj_tutk]
    ,[jarjnimi_tutk]
    ,[jarjmaak]
    ,[jarjmaaknimi]
    ,[tutkmaak]
    ,[tutkmaaknimi]
    ,[kaste_t2]
    ,[kaste_t2ni]
    ,[iscfibroad2013]
    ,[kala_t1ni]
    ,[oppis]
    ,[alvv]
    ,[allk]
    ,[rahoituskausi]
    ,[rahoitus]
    ,[kustannusryhma]
    ,[kaste_t2_e]
    ,[kaste_t2ni_e]
    ,[suorv_e]
    ,[ptoim1r2e]
    ,[kaste_t2_evj]
    ,[kaste_t2ni_evj]
    ,[amase]
    ,[ptoim1r2_tilv_07]
    ,[amas_tilv_07]
    ,[ptoim1r2_tilv_08]
    ,[amas_tilv_08]
    ,[ptoim1r2_tilv_09]
    ,[amas_tilv_09]
    ,[ptoim1r2_tilv_10]
    ,[amas_tilv_10]
    ,[ptoim1r2_tilv_11]
    ,[amas_tilv_11]
    ,[ptoim1r2_tilv_12]
    ,[amas_tilv_12]
    ,[ptoim1r2_tilvseur_01]
    ,[amas_tilvseur_01]
    ,[ptoim1r2_tilvseur_02]
    ,[amas_tilvseur_02]
    ,[ptoim1r2_tilvseur_03]
    ,[amas_tilvseur_03]
    ,[ptoim1r2_tilvseur_04]
    ,[amas_tilvseur_04]
    ,[ptoim1r2_tilvseur_05]
    ,[amas_tilvseur_05]
    ,[ptoim1r2_tilvseur_06]
    ,[amas_tilvseur_06]
    ,[opisk_kk]
    ,[opisk_syys]
    ,[opisk_tammi]
    ,[lkm]
FROM [TK_H9098_CSC].[dbo].[TK_K1_13b_sopv_24_2022]

UNION ALL

SELECT 
	[tilv]
    ,[aineisto]
    ,[ikar21]
    ,[aikielir1]
    ,[prioriteetti]
    ,[toteuma_tutk]
    ,[tyov]
    ,[jarj_opisk]
    ,[jarjnimi_opisk]
    ,[jarj_tutk]
    ,[jarjnimi_tutk]
    ,[jarjmaak]
    ,[jarjmaaknimi]
    ,[tutkmaak]
    ,[tutkmaaknimi]
    ,[kaste_t2]
    ,[kaste_t2ni]
    ,[iscfibroad2013]
    ,[kala_t1ni]
    ,[oppis]
    ,[alvv]
    ,[allk]
    ,[rahoituskausi]
    ,[rahoitus]
    ,[kustannusryhma]
    ,[kaste_t2_e]
    ,[kaste_t2ni_e]
    ,[suorv_e]
    ,[ptoim1r2e]
    ,[kaste_t2_evj]
    ,[kaste_t2ni_evj]
    ,[amase]
    ,[ptoim1r2_tilv_07]
    ,[amas_tilv_07]
    ,[ptoim1r2_tilv_08]
    ,[amas_tilv_08]
    ,[ptoim1r2_tilv_09]
    ,[amas_tilv_09]
    ,[ptoim1r2_tilv_10]
    ,[amas_tilv_10]
    ,[ptoim1r2_tilv_11]
    ,[amas_tilv_11]
    ,[ptoim1r2_tilv_12]
    ,[amas_tilv_12]
    ,[ptoim1r2_tilvseur_01]
    ,[amas_tilvseur_01]
    ,[ptoim1r2_tilvseur_02]
    ,[amas_tilvseur_02]
    ,[ptoim1r2_tilvseur_03]
    ,[amas_tilvseur_03]
    ,[ptoim1r2_tilvseur_04]
    ,[amas_tilvseur_04]
    ,[ptoim1r2_tilvseur_05]
    ,[amas_tilvseur_05]
    ,[ptoim1r2_tilvseur_06]
    ,[amas_tilvseur_06]
    ,[opisk_kk]
    ,[opisk_syys]
    ,[opisk_tammi]
    ,[lkm]
FROM [TK_H9098_CSC].[dbo].[TK_K1_13b_sopv_24_2021]
WHERE rahoituskausi != '01.07.2021 - 30.06.2022' --sis. aineistoon _2022

GO
