USE [ANTERO]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dw].[d_perusopetus_oppiaine_ja_oppimaara]') AND type in (N'U'))
DROP TABLE [dw].[d_perusopetus_oppiaine_ja_oppimaara]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dw].[d_perusopetus_oppiaine_ja_oppimaara](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[koodisto] [nvarchar](100) NOT NULL,
	[koodi] [nvarchar](100) NOT NULL,
	[nimi] [nvarchar](200) NULL,
	[nimi_sv] [nvarchar](200) NULL,
	[nimi_en] [nvarchar](200) NULL,
	[jarjestys] [nvarchar](10) NULL,
	[ryhma_koodi] [nvarchar](10) NOT NULL,
	[ryhma_nimi] [nvarchar](50) NULL,
	[ryhma_nimi_sv] [nvarchar](50) NULL,
	[ryhma_nimi_en] [nvarchar](50) NULL,
	[jarjestys_ryhma] [int] NULL,
	[ryhma2_koodi] [nvarchar](10) NOT NULL,
	[ryhma2_nimi] [nvarchar](50) NULL,
	[ryhma2_nimi_sv] [nvarchar](50) NULL,
	[ryhma2_nimi_en] [nvarchar](50) NULL,
	[jarjestys_ryhma2] [int] NULL,
 CONSTRAINT [PK__d_perusopetus_oppiaine_ja_oppimaara] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ON 
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (1, N'koskioppiaineetyleissivistava', N'AI', N'Äidinkieli ja kirjallisuus', N'Modersmålet och litteratur', N'Mother tongue and literature', N'1000', N'aid', N'Äidinkieli ja kirjallisuus', N'Modersmålet och litteratur', NULL, 0, N'aid', N'Äidinkieli ja kirjallisuus', N'Modersmålet och litteratur', NULL, 0)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (2, N'koskioppiaineetyleissivistava', N'AOM', N'Äidinkielenomainen kieli', N'Modersmålsinriktat språk', NULL, N'2130', N'kie', N'Kielet', N'Språk', NULL, 2, N'aom', N'Äidinkielenomainen kieli', N'Modersmålsinriktat språk', NULL, 0)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (3, N'oppiaineaidinkielijakirjallisuus', N'AI1', N'Suomen kieli ja kirjallisuus', N'Finska och litteratur', N'Finnish language and literature', N'1801', N'aid', N'Äidinkieli ja kirjallisuus', N'Modersmålet och litteratur', NULL, 0, N'aid', N'Äidinkieli ja kirjallisuus', N'Modersmålet och litteratur', NULL, 0)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (4, N'oppiaineaidinkielijakirjallisuus', N'AI2', N'Ruotsin kieli ja kirjallisuus', N'Svenska och litteratur', N'Swedish language and literature', N'1802', N'aid', N'Äidinkieli ja kirjallisuus', N'Modersmålet och litteratur', NULL, 0, N'aid', N'Äidinkieli ja kirjallisuus', N'Modersmålet och litteratur', NULL, 0)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (5, N'oppiaineaidinkielijakirjallisuus', N'AI3', N'Saamen kieli ja kirjallisuus', N'Samiska och litteratur', N'Saami language and literature', N'1803', N'aid', N'Äidinkieli ja kirjallisuus', N'Modersmålet och litteratur', NULL, 0, N'aid', N'Äidinkieli ja kirjallisuus', N'Modersmålet och litteratur', NULL, 0)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (6, N'oppiaineaidinkielijakirjallisuus', N'AI4', N'Romanikieli ja kirjallisuus', N'Romani och litteratur', N'Romani and literature', N'1804', N'aid', N'Äidinkieli ja kirjallisuus', N'Modersmålet och litteratur', NULL, 0, N'aid', N'Äidinkieli ja kirjallisuus', N'Modersmålet och litteratur', NULL, 0)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (7, N'oppiaineaidinkielijakirjallisuus', N'AI5', N'Viittomakieli ja kirjallisuus', N'Teckenspråk och litteratur', N'Sign language and literature', N'1805', N'aid', N'Äidinkieli ja kirjallisuus', N'Modersmålet och litteratur', NULL, 0, N'aid', N'Äidinkieli ja kirjallisuus', N'Modersmålet och litteratur', NULL, 0)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (8, N'oppiaineaidinkielijakirjallisuus', N'AI6', N'Muu oppilaan äidinkieli', N'Annat modersmål', N'Other mother tongue', N'1806', N'aid', N'Äidinkieli ja kirjallisuus', N'Modersmålet och litteratur', NULL, 0, N'aid', N'Äidinkieli ja kirjallisuus', N'Modersmålet och litteratur', NULL, 0)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (9, N'oppiaineaidinkielijakirjallisuus', N'AI7', N'Suomi toisena kielenä ja kirjallisuus', N'Finska som andraspråk och litteratur', N'Finnish as a second language and literature', N'1807', N'aid', N'Äidinkieli ja kirjallisuus', N'Modersmålet och litteratur', NULL, 0, N'aid', N'Äidinkieli ja kirjallisuus', N'Modersmålet och litteratur', NULL, 0)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (10, N'oppiaineaidinkielijakirjallisuus', N'AI8', N'Ruotsi toisena kielenä ja kirjallisuus', N'Svenska som andraspråk och litteratur', N'Swedish as a second language and literature', N'1808', N'aid', N'Äidinkieli ja kirjallisuus', N'Modersmålet och litteratur', NULL, 0, N'aid', N'Äidinkieli ja kirjallisuus', N'Modersmålet och litteratur', NULL, 0)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (11, N'oppiaineaidinkielijakirjallisuus', N'AI9', N'Suomi saamenkielisille', N'Finska för samisktalande', N'Finnish for Saami speakers', N'1809', N'aid', N'Äidinkieli ja kirjallisuus', N'Modersmålet och litteratur', NULL, 0, N'aid', N'Äidinkieli ja kirjallisuus', N'Modersmålet och litteratur', NULL, 0)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (12, N'oppiaineaidinkielijakirjallisuus', N'AI10', N'Ruotsi saamenkielisille', N'Svenska för samisktalande', N'Swedish for Saami speakers', N'1810', N'aid', N'Äidinkieli ja kirjallisuus', N'Modersmålet och litteratur', NULL, 0, N'aid', N'Äidinkieli ja kirjallisuus', N'Modersmålet och litteratur', NULL, 0)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (13, N'oppiaineaidinkielijakirjallisuus', N'AI11', N'Suomi viittomakielisille', N'Finska för teckenspråkiga', N'Finnish for sign language speakers', N'1811', N'aid', N'Äidinkieli ja kirjallisuus', N'Modersmålet och litteratur', NULL, 0, N'aid', N'Äidinkieli ja kirjallisuus', N'Modersmålet och litteratur', NULL, 0)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (14, N'oppiaineaidinkielijakirjallisuus', N'AI12', N'Ruotsi viittomakielisille', N'Svenska för teckenspråkiga', N'Swedish for sign language speakers', N'1812', N'aid', N'Äidinkieli ja kirjallisuus', N'Modersmålet och litteratur', NULL, 0, N'aid', N'Äidinkieli ja kirjallisuus', N'Modersmålet och litteratur', NULL, 0)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (15, N'oppiaineaidinkielijakirjallisuus', N'AIAI', N'Suomen kieli, äidinkielenomainen suomi', N'Finska, modersmålsinriktad finska', NULL, N'1815', N'aid', N'Äidinkieli ja kirjallisuus', N'Modersmålet och litteratur', NULL, 0, N'aid', N'Äidinkieli ja kirjallisuus', N'Modersmålet och litteratur', NULL, 0)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (16, N'koskioppiaineetyleissivistava', N'HI', N'Historia', N'Historia', N'History', N'6300', N'his', N'Historia, Yhteiskuntaoppi', N'Historia, Samhällslära', NULL, 5, N'his', N'Historia, Yhteiskuntaoppi', N'Historia, Samhällslära', NULL, 5)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (17, N'koskioppiaineetyleissivistava', N'YH', N'Yhteiskuntaoppi', N'Samhällslära', N'Social studies', N'6400', N'his', N'Historia, Yhteiskuntaoppi', N'Historia, Samhällslära', NULL, 5, N'his', N'Historia, Yhteiskuntaoppi', N'Historia, Samhällslära', NULL, 5)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (18, N'koskioppiaineetyleissivistava', N'A', N'A-kieli', N'A-språk', N'A-language', N'2000', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (19, N'koskioppiaineetyleissivistava', N'A1', N'A1-kieli', N'A1-språk', N'A1-language', N'2010', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (20, N'koskioppiaineetyleissivistava', N'A2', N'A2-kieli', N'A2-språk', N'A2-language', N'2020', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (21, N'koskioppiaineetyleissivistava', N'B1', N'B1-kieli', N'B1-språk', N'B1-language', N'2100', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (22, N'koskioppiaineetyleissivistava', N'B2', N'B2-kieli', N'B2-språk', N'B2-language', N'2110', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (23, N'koskioppiaineetyleissivistava', N'B3', N'B3-kieli', N'B3-språk', N'B3-language', N'2120', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (24, N'kielivalikoima', N'AR', N'arabia', N'arabiska', N'Arabic', N'3710', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (25, N'kielivalikoima', N'EN', N'englanti', N'engelska', N'English', N'3718', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (26, N'kielivalikoima', N'ES', N'espanja', N'spanska', N'Spanish', N'3719', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (27, N'kielivalikoima', N'HE', N'heprea', N'hebreiska', N'Hebrew', N'3725', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (28, N'kielivalikoima', N'IT', N'italia', N'italienska', N'Italian', N'3731', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (29, N'kielivalikoima', N'JA', N'japani', N'japanska', N'Japanese', N'3732', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (30, N'kielivalikoima', N'ZH', N'kiina', N'kinesiska', N'Chinese', N'3738', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (31, N'kielivalikoima', N'KO', N'korea', N'koreanska', N'Korean', N'3740', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (32, N'kielivalikoima', N'EL', N'kreikka', N'grekiska', N'Greek', N'3741', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (33, N'kielivalikoima', N'KU', N'kurdi', N'kurdiska', N'Kurdish', N'3743', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (34, N'kielivalikoima', N'LA', N'latina', N'latin', N'Latin', N'3745', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (35, N'kielivalikoima', N'LV', N'latvia', N'lettiska', N'Latvian', N'3746', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (36, N'kielivalikoima', N'LT', N'liettua', N'litauiska', N'Lithuanian', N'3747', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (37, N'kielivalikoima', N'NE', N'nepali', N'nepali', N'Nepali', N'3758', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (38, N'kielivalikoima', N'PT', N'portugali', N'portugisiska', N'Portuguese', N'3763', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (39, N'kielivalikoima', N'PL', N'puola', N'polska', N'Polish', N'3764', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (40, N'kielivalikoima', N'FR', N'ranska', N'franska', N'French', N'3765', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (41, N'kielivalikoima', N'SE', N'saame', N'samiska', N'Northern Sami', N'3769', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (42, N'kielivalikoima', N'DE', N'saksa', N'tyska', N'German', N'3770', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (43, N'kielivalikoima', N'TH', N'thai', N'thai', NULL, N'3784', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (44, N'kielivalikoima', N'TR', N'turkki', N'turkiska', N'Turkish', N'3787', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (45, N'kielivalikoima', N'UK', N'ukraina', N'ukrainska', N'Ukrainian', N'3789', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (46, N'kielivalikoima', N'HU', N'unkari', N'ungerska', N'Hungarian', N'3790', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (47, N'kielivalikoima', N'RU', N'venäjä', N'ryska', N'Russian', N'3792', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (48, N'kielivalikoima', N'VI', N'vietnam', N'vietnamesiska', N'Vietnamese', N'3793', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (49, N'kielivalikoima', N'VK', N'viittomakieli', N'teckenspråk', N'Sign language', N'3794', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (50, N'kielivalikoima', N'ET', N'viro', N'estniska', N'Estonian', N'3795', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (51, N'kielivalikoima', N'XX', N'muu kieli', N'övrigt språk', N'Other languages', N'3856', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (52, N'kielivalikoima', N'97', N'Ei suoritusta', N'Ej avlagd', NULL, N'3917', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (53, N'koskioppiaineetyleissivistava', N'MA', N'Matematiikka', N'Matematik', N'Mathematics', N'4000', N'mat', N'Matematiikka', N'Matematik', NULL, 3, N'mat', N'Matematiikka', N'Matematik', NULL, 3)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (54, N'koskioppiaineetyleissivistava', N'XX', N'Ei tiedossa', N'Okänd', N'Unknown', N'9900', N'muu', N'Muut opinnot', N'Övriga studier', NULL, 9, N'muu', N'Muut opinnot', N'Övriga studier', NULL, 9)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (55, N'koskioppiaineetyleissivistava', N'OP', N'Oppilaanohjaus', N'Elevhandledning', N'Guidance counselling', N'9711', N'muu', N'Muut opinnot', N'Övriga studier', NULL, 9, N'muu', N'Muut opinnot', N'Övriga studier', NULL, 9)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (56, N'koskioppiaineetyleissivistava', N'OPA', N'Oppilaanohjaus', N'Studiehandledning och handledning i arbetslivsfärdigheter', N'Guidance counselling and working life competence', N'9712', N'muu', N'Muut opinnot', N'Övriga studier', NULL, 9, N'muu', N'Muut opinnot', N'Övriga studier', NULL, 9)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (57, N'koskioppiaineetyleissivistava', N'MU', N'Musiikki', N'Musik', N'Music', N'7400', N'tai', N'Taide- ja taitoaineet', N'Konst- och färdighetsämnen', NULL, 7, N'tai', N'Taide- ja taitoaineet', N'Konst- och färdighetsämnen', NULL, 7)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (58, N'koskioppiaineetyleissivistava', N'KU', N'Kuvataide', N'Bildkonst', N'Visual arts', N'7500', N'tai', N'Taide- ja taitoaineet', N'Konst- och färdighetsämnen', NULL, 7, N'tai', N'Taide- ja taitoaineet', N'Konst- och färdighetsämnen', NULL, 7)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (59, N'koskioppiaineetyleissivistava', N'LI', N'Liikunta', N'Gymnastik', N'Physical education', N'7600', N'tai', N'Taide- ja taitoaineet', N'Konst- och färdighetsämnen', NULL, 7, N'tai', N'Taide- ja taitoaineet', N'Konst- och färdighetsämnen', NULL, 7)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (60, N'koskioppiaineetyleissivistava', N'KO', N'Kotitalous', N'Huslig ekonomi', N'Home economics', N'7700', N'tai', N'Taide- ja taitoaineet', N'Konst- och färdighetsämnen', NULL, 7, N'tai', N'Taide- ja taitoaineet', N'Konst- och färdighetsämnen', NULL, 7)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (61, N'koskioppiaineetyleissivistava', N'KS', N'Käsityö', N'Slöjd', N'Crafts', N'7800', N'tai', N'Taide- ja taitoaineet', N'Konst- och färdighetsämnen', NULL, 7, N'tai', N'Taide- ja taitoaineet', N'Konst- och färdighetsämnen', NULL, 7)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (62, N'kielivalikoima', N'SV', N'ruotsi', N'svenska', N'Swedish', N'3704', N'kie', N'Kielet', N'Språk', NULL, 2, N'toi', N'Toinen kotimainen kieli', N'Det andra inhemska språket', NULL, 1)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (63, N'kielivalikoima', N'FI', N'suomi', N'finska', N'Finnish', N'3701', N'kie', N'Kielet', N'Språk', NULL, 2, N'toi', N'Toinen kotimainen kieli', N'Det andra inhemska språket', NULL, 1)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (64, N'koskioppiaineetyleissivistava', N'KT', N'Uskonto', N'Religion', N'Religion/ethics', N'6501', N'usk', N'Uskonto, Elämänkatsomustieto', N'Religion, Livsåskådningskunskap', NULL, 6, N'usk', N'Uskonto, Elämänkatsomustieto', N'Religion, Livsåskådningskunskap', NULL, 6)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (65, N'koskioppiaineetyleissivistava', N'ET', N'Elämänkatsomustieto', N'Livsåskådningskunskap', N'Religion/ethics', N'6551', N'usk', N'Uskonto, Elämänkatsomustieto', N'Religion, Livsåskådningskunskap', NULL, 6, N'usk', N'Uskonto, Elämänkatsomustieto', N'Religion, Livsåskådningskunskap', NULL, 6)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (66, N'koskioppiaineetyleissivistava', N'FY', N'Fysiikka', N'Fysik', N'Physics', N'4400', N'ymp', N'Ympäristö- ja luonnontietoaineet', N'Miljö- och naturkunskapämnen', NULL, 4, N'ymp', N'Ympäristö- ja luonnontietoaineet', N'Miljö- och naturkunskapämnen', NULL, 4)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (67, N'koskioppiaineetyleissivistava', N'KE', N'Kemia', N'Kemi', N'Chemistry', N'4500', N'ymp', N'Ympäristö- ja luonnontietoaineet', N'Miljö- och naturkunskapämnen', NULL, 4, N'ymp', N'Ympäristö- ja luonnontietoaineet', N'Miljö- och naturkunskapämnen', NULL, 4)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (68, N'koskioppiaineetyleissivistava', N'BI', N'Biologia', N'Biologi', N'Biology', N'4600', N'ymp', N'Ympäristö- ja luonnontietoaineet', N'Miljö- och naturkunskapämnen', NULL, 4, N'ymp', N'Ympäristö- ja luonnontietoaineet', N'Miljö- och naturkunskapämnen', NULL, 4)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (69, N'koskioppiaineetyleissivistava', N'GE', N'Maantieto', N'Geografi', N'Geography', N'4700', N'ymp', N'Ympäristö- ja luonnontietoaineet', N'Miljö- och naturkunskapämnen', NULL, 4, N'ymp', N'Ympäristö- ja luonnontietoaineet', N'Miljö- och naturkunskapämnen', NULL, 4)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (70, N'koskioppiaineetyleissivistava', N'YL', N'Ympäristöoppi', N'Omgivningslära', N'Environmental studies', N'4800', N'ymp', N'Ympäristö- ja luonnontietoaineet', N'Miljö- och naturkunskapämnen', NULL, 4, N'ymp', N'Ympäristö- ja luonnontietoaineet', N'Miljö- och naturkunskapämnen', NULL, 4)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (71, N'koskioppiaineetyleissivistava', N'TE', N'Terveystieto', N'Hälsokunskap', N'Health education', N'4900', N'ymp', N'Ympäristö- ja luonnontietoaineet', N'Miljö- och naturkunskapämnen', NULL, 4, N'ymp', N'Ympäristö- ja luonnontietoaineet', N'Miljö- och naturkunskapämnen', NULL, 4)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (76, N'koskioppiaineetyleissivistava', N'KT/ET', N'Uskonto, Elämänkatsomustieto', N'Religion, Livsåskådningskunskap', NULL, N'6500', N'usk', N'Uskonto, Elämänkatsomustieto', N'Religion, Livsåskådningskunskap', NULL, 6, N'usk', N'Uskonto, Elämänkatsomustieto', N'Religion, Livsåskådningskunskap', NULL, 6)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (77, N'manuaalinen', N'OA', N'Oman äidinkielen opinnot', N'Studier i det egna modersmålet', NULL, N'8100', N'oma', N'Oman äidinkielen opinnot', N'Studier i det egna modersmålet', NULL, 8, N'oma', N'Oman äidinkielen opinnot', N'Studier i det egna modersmålet', NULL, 8)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (78, N'kielivalikoima', N'NO', N'norja', N'norska', N'Norwegian', N'3759', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (79, N'kielivalikoima', N'AF', N'afrikaans', N'afrikaans', N'afrikaans', N'3707', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (80, N'kielivalikoima', N'AM', N'amhara', N'amhariska', N'Amharic', N'3709', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (81, N'kielivalikoima', N'AZ', N'azeri', N'azerbajdzjanska', N'Azerbaijani', N'3712', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (82, N'kielivalikoima', N'BG', N'bulgaria', N'bulgariska', N'Bulgarian', N'3715', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (83, N'kielivalikoima', N'BN', N'bengali', N'bengali', N'Bengali, Bangla', N'3713', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (84, N'kielivalikoima', N'BS', N'bosnia', N'bosniska', N'Bosnian', N'3714', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (85, N'kielivalikoima', N'CA', N'katalaani', N'katalanska', N'Catalan', N'3736', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (86, N'kielivalikoima', N'CS', N'tšekki', N'tjeckiska', N'Czech', N'3786', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (87, N'kielivalikoima', N'DA', N'tanska', N'danska', N'Danish', N'3781', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (88, N'kielivalikoima', N'FA', N'persia, farsi', N'persiska', N'Persian, Farsi', N'3762', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (89, N'kielivalikoima', N'fil', N'filipino', N'filipino', NULL, N'3721', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (90, N'kielivalikoima', N'HI', N'hindi', N'hindi', N'Hindi', N'3726', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (91, N'kielivalikoima', N'HR', N'kroatia', N'kroatiska', N'Croatian', N'3742', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (92, N'kielivalikoima', N'HY', N'armenia', N'armeniska', N'Armenian', N'3711', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (93, N'kielivalikoima', N'ID', N'indonesia', N'indonesiska', N'Indonesian', N'3729', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (94, N'kielivalikoima', N'IS', N'islanti', N'isländska', N'Icelandic', N'3730', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (95, N'kielivalikoima', N'KA', N'georgia', N'georgiska', N'Georgian', N'3722', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (96, N'kielivalikoima', N'KM', N'keskikhmer', N'khmeriska, kambodjanska', N'Cambodian, Khmer', N'3737', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (97, N'kielivalikoima', N'MK', N'makedonia', N'makedonska', N'Macedonian', N'3749', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (98, N'kielivalikoima', N'MN', N'mongoli', N'mongoliska', N'Mongolian', N'3755', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (99, N'kielivalikoima', N'MS', N'malaiji', N'malajiska', N'Malay', N'3750', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (100, N'kielivalikoima', N'NL', N'hollanti', N'holländska', N'Dutch', N'3727', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (101, N'kielivalikoima', N'RI', N'romani', N'romani', N'Romani', N'3766', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (102, N'kielivalikoima', N'RO', N'romania', N'rumänska', N'Romanian', N'3767', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (103, N'kielivalikoima', N'SK', N'slovakki', N'slovakiska', N'Slovak', N'3774', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (104, N'kielivalikoima', N'SL', N'sloveeni', N'slovenska', N'Slovenian', N'3775', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (105, N'kielivalikoima', N'SQ', N'albania', N'albanska', N'Albanian', N'3708', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (106, N'kielivalikoima', N'SR', N'serbia', N'serbiska', N'Serbian', N'3771', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (107, N'kielivalikoima', N'SS', N'swazi', N'swazi', N'Siswati, Swazi, Swati', N'3778', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (108, N'kielivalikoima', N'ST', N'eteläsotho', N'sotho', N'Sesotho, Southern Sotho', N'3720', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (109, N'kielivalikoima', N'SW', N'suahili', N'swahili', N'Swahili, Kiswahili', N'3777', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (110, N'kielivalikoima', N'UR', N'urdu', N'urdu', N'Urdu', N'3791', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (111, N'kielivalikoima', N'XAI11', N'suomi viittomakielisille', N'finska för teckenspråkiga', N'Finnish for sign language users', N'3703', N'kie', N'Kielet', N'Språk', NULL, 2, N'toi', N'Toinen kotimainen kieli', N'Det andra inhemska språket', NULL, 1)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (112, N'kielivalikoima', N'XAI12', N'ruotsi viittomakielisille', N'svenska för teckenspråkiga', N'Swedish for sign language users', N'3706', N'kie', N'Kielet', N'Språk', NULL, 2, N'toi', N'Toinen kotimainen kieli', N'Det andra inhemska språket', NULL, 1)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (113, N'kielivalikoima', N'XAI7', N'suomi toisena kielenä', N'finska som andraspråk', N'Finnish as a second language', N'3702', N'kie', N'Kielet', N'Språk', NULL, 2, N'toi', N'Toinen kotimainen kieli', N'Det andra inhemska språket', NULL, 1)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (114, N'kielivalikoima', N'XAI8', N'ruotsi toisena kielenä', N'svenska som andraspråk', N'Swedish as a second language', N'3705', N'kie', N'Kielet', N'Språk', NULL, 2, N'toi', N'Toinen kotimainen kieli', N'Det andra inhemska språket', NULL, 1)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (115, N'kielivalikoima', N'KX', N'muu kieli', N'övrigt språk', N'Other languages', N'3856', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (116, N'kielivalikoima', N'CMN', N'mandariinikiina', N'mandarin', N'Mandarin Chinese', N'3752', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (117, N'kielivalikoima', N'YUE', N'kantoninkiina', N'kantonesiska', N'Yue Chinese', N'3735', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (118, N'kielivalikoima', N'PRS', N'Dari', N'Dari', N'Dari', N'3716', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (119, N'kielivalikoima', N'IG', N'igbo', N'ibo', N'Igbo', N'3728', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (120, N'kielivalikoima', N'YO', N'joruba', N'joruba', N'Yoruba', N'3733', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (121, N'kielivalikoima', N'SH', N'serbokroatia', N'serbokroatiska', N'Serbo-Croatian', N'3772', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (122, N'kielivalikoima', N'PS', N'paštu, myös: afgaani', N'pashto', N'Pashto, Pushto', N'3761', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (123, N'kielivalikoima', N'TT', N'tataari', N'tatariska', N'Tatar', N'3782', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (124, N'kielivalikoima', N'UG', N'uiguuri', N'uiguriska', N'Uighur', N'3788', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (125, N'kielivalikoima', N'TL', N'tagalog', N'tagalog', N'Tagalog', N'3779', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (126, N'kielivalikoima', N'TA', N'tamili', N'tamili', N'Tamil', N'3780', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (127, N'kielivalikoima', N'TI', N'tigrinja', N'tigrinja', N'Tigrinya', N'3785', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (128, N'kielivalikoima', N'RW', N'ruanda', N'kinyarwanda', N'Kinyarwanda, Rwanda', N'3768', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (129, N'kielivalikoima', N'SO', N'somali', N'somaliska', N'Somali', N'3776', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (130, N'kielivalikoima', N'SI', N'sinhala', N'singalesiska', N'Sinhala; Sinhalese; Singhalese', N'3773', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (131, N'kielivalikoima', N'KN', N'kannada', N'kannada', N'Kannada', N'3734', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (132, N'kielivalikoima', N'ML', N'malajalam', N'malayalam', N'Malayalam', N'3751', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (133, N'kielivalikoima', N'MR', N'marathi', N'marathi', N'Marathi', N'3754', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (134, N'kielivalikoima', N'PA', N'pandžabi', N'panjabi', N'Punjabi, Panjabi', N'3760', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (135, N'kielivalikoima', N'TE', N'telugu', N'telugu', N'Telegu', N'3783', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (136, N'kielivalikoima', N'KY', N'kirgiisi', N'kirgisiska', N'Kirghiz, Kyrgyz', N'3739', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (137, N'kielivalikoima', N'GU', N'gudžarati', N'gujarati', N'Gujarati', N'3723', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (138, N'kielivalikoima', N'WO', N'wolof', N'wolof', N'Wolof', N'3796', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (139, N'kielivalikoima', N'HA', N'hausa', N'hausa', N'Hausa', N'3724', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (140, N'kielivalikoima', N'LN', N'lingala', N'lingala', N'Lingala', N'3748', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (141, N'kielivalikoima', N'KMR', N'kurmandži', N'nordkurdiska', N'Kurmanji', N'3744', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] ([id], [koodisto], [koodi], [nimi], [nimi_sv], [nimi_en], [jarjestys], [ryhma_koodi], [ryhma_nimi], [ryhma_nimi_sv], [ryhma_nimi_en], [jarjestys_ryhma], [ryhma2_koodi], [ryhma2_nimi], [ryhma2_nimi_sv], [ryhma2_nimi_en], [jarjestys_ryhma2]) VALUES (142, N'kielivalikoima', N'MNK', N'mandinka ', N'mandinka', N'Mandinka', N'3753', N'kie', N'Kielet', N'Språk', NULL, 2, N'kie', N'Vieraat kielet', N'Främmande språk', NULL, 2)
GO
SET IDENTITY_INSERT [dw].[d_perusopetus_oppiaine_ja_oppimaara] OFF
GO
