USE [ANTERO]
GO
IF NOT EXISTS (select * from INFORMATION_SCHEMA.TABLES
    where TABLE_SCHEMA='sa' and TABLE_NAME='SA_SUORAT_AMK_TALOUS_4_tutkimusmenot'
    and COLUMN_NAME='KOTIKK')
BEGIN
ALTER TABLE [sa].[SA_SUORAT_AMK_TALOUS_4_tutkimusmenot] ADD KOTIKK BIGINT NULL;
END
