USE [ANTERO]
GO
IF  EXISTS (select * from INFORMATION_SCHEMA.TABLES
    where TABLE_SCHEMA='sa' and TABLE_NAME='SA_SUORAT_AMK_TALOUS_4_tutkimusmenot')
BEGIN
ALTER TABLE [sa].[SA_SUORAT_AMK_TALOUS_4_tutkimusmenot] ADD KOTIKK BIGINT, NULL;
END
