USE [VipunenTK_DW]
GO

/****** Object:  Table [dbo].[f_2_8_Korkeakouluopiskelijat_joinavaimet]    Script Date: 5.11.2025 10.25.48 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[f_2_8_Korkeakouluopiskelijat_joinavaimet]') AND type in (N'U'))
  DROP TABLE [dbo].[f_2_8_Korkeakouluopiskelijat_joinavaimet]
GO

CREATE TABLE [dbo].[f_2_8_Korkeakouluopiskelijat_joinavaimet](
	[tilastointivuosi] [nvarchar](4) NULL,
	[tilv_date] [date] NULL,
	[aineisto] [nvarchar](2) NULL,
	[lahde] [nvarchar](2) NULL,
	[oppilaitos] [nvarchar](5) NULL,
	[oppilaitos_sijaintikuntakoodi_join] [nvarchar](3) NULL,
	[oppilaitos_sijaintikuntakoodi_historia_join] [nvarchar](3) NULL,
	[koulutuksen_jarjestaja] [nvarchar](10) NULL,
	[koulutuksen_jarjestaja_sijaintikuntakoodi_join] [nvarchar](3) NULL,
	[koulutuksen_jarjestaja_sijaintikuntakoodi_historia_join] [nvarchar](3) NULL,
	[koulutusluokitus] [nvarchar](6) NULL,
	[koulutuksen_kunta] [nvarchar](3) NULL,
	[sukupuoli] [nvarchar](2) NULL,
	[aidinkieli_versio1x] [nvarchar](2) NULL,
	[syntymavuosi] [nvarchar](4) NULL,
	[syntymavuosi_join] [nvarchar](4) NULL,
	[kotikunta] [nvarchar](6) NULL,
	[kotikunta1x] [nvarchar](3) NULL,
	[kotikunta2x] [nvarchar](3) NULL,
	[kansalaisuus_versio2] [nvarchar](2) NULL,
	[kvopisk] [nvarchar](2) NULL,
	[suormaa] [nvarchar](2) NULL,
	[kirjoihintulovuosi] [nvarchar](10) NULL,
	[jarjestys_kirjoihintulovuosi] [int] NULL,
	[kirjoihintulovuosi_join] [nvarchar](10) NULL,
	[kirjoihintulokausi] [nvarchar](2) NULL,
	[kirjoihintulokausi_join] [nvarchar](6) NULL,
	[opiskelijan_olo_tamm] [nvarchar](2) NULL,
	[opiskelijan_olo_syys] [nvarchar](2) NULL,
	[rahoituslahde] [nvarchar](2) NULL,
	[opiskelijan_fte_tieto] [nvarchar](2) NULL,
	[kirjoihintulovuosi_korkeakoulusektori] [nvarchar](4) NULL,
	[kirjoihintulovuosi_korkeakoulusektori_join] [nvarchar](4) NULL,
	[kirjoihintulovuosi_korkeakoulusektori_lasnaoleva] [nvarchar](4) NULL,
	[kirjoihintulovuosi_korkeakoulusektori_lasnaoleva_join] [nvarchar](4) NULL,
	[kirjoihintulovuosi_sektori] [nvarchar](4) NULL,
	[kirjoihintulovuosi_sektori_join] [nvarchar](4) NULL,
	[kirjoihintulovuosi_sektori_lasnaoleva] [nvarchar](4) NULL,
	[kirjoihintulovuosi_sektori_lasnaoleva_join] [nvarchar](4) NULL,
	[kirjoihintulovuosi_korkeakoulu] [nvarchar](4) NULL,
	[kirjoihintulovuosi_korkeakoulu_join] [nvarchar](4) NULL,
	[kirjoihintulovuosi_korkeakoulu_lasnaoleva] [nvarchar](4) NULL,
	[kirjoihintulovuosi_korkeakoulu_lasnaoleva_join] [nvarchar](4) NULL,
	[kirjoihintulovuosi_opintoala] [nvarchar](4) NULL,
	[kirjoihintulovuosi_opintoala_join] [nvarchar](4) NULL,
	[kirjoihintulovuosi_opintoala_lasnaoleva] [nvarchar](4) NULL,
	[kirjoihintulovuosi_opintoala_lasnaoleva_join] [nvarchar](4) NULL,
	[lukumaara] [int] NULL,
	[lkm_op0] [int] NULL,
	[lkm_op1_14] [int] NULL,
	[lkm_op15_29] [int] NULL,
	[lkm_op30_44] [int] NULL,
	[lkm_op45_59] [int] NULL,
	[lkm_op60_74] [int] NULL,
	[lkm_op75_89] [int] NULL,
	[lkm_op90_104] [int] NULL,
	[lkm_op105_119] [int] NULL,
	[lkm_op120_] [int] NULL,
	[vahintaan_55_op_suorittanut] [nvarchar](2) NULL,
	[op_edellinen_syksy] [int] NULL,
	[op_edellinen_kevat] [int] NULL,
	[op_kertyma_edel_lkv_loppu] [int] NULL,
	[tutkinto_amk] [nvarchar](3) NULL,
	[koulutusohjelma_amk] [nvarchar](4) NULL,
	[suuntautumisvaihtoehto_amk] [nvarchar](5) NULL,
	[koulutustyyppi] [nvarchar](2) NULL,
	[koulutuksen_kieli] [nvarchar](2) NULL,
	[lkm_lasnalk] [int] NULL,
	[lkm_poissalk] [int] NULL,
	[op_suoritettavien_laajuus] [int] NULL,
	[kirjoihintulovuosi_tutkinto] [nvarchar](4) NULL,
	[kirjoihintulovuosi_tutkinto_join] [nvarchar](4) NULL,
	[kirjoihintulokausi_tutkinto] [nvarchar](2) NULL,
	[kirjoihintulokausi_tutkinto_join] [nvarchar](6) NULL,
	[ensisijainen_opintooikeus] [nvarchar](2) NULL,
	[tilauskoulutuksen_sijaintimaa] [nvarchar](2) NULL,
	[tutkinto_yo] [nvarchar](3) NULL,
	[koulutusohjelma_yo] [nvarchar](4) NULL,
	[paaaine_yo] [nvarchar](4) NULL,
	[yliopisto] [nvarchar](2) NULL,
	[tiedekunta_yo] [nvarchar](2) NULL,
	[uusi_vanha_opiskelija] [nvarchar](2) NULL,
	[tutkintooikeusvuosi] [nvarchar](4) NULL,
	[tutkintooikeusvuosi_join] [nvarchar](4) NULL,
	[opiskelumuoto] [nvarchar](2) NULL,
	[opettajankelpoisuus] [nvarchar](2) NULL,
	[avoinvayla] [nvarchar](2) NULL,
	[tietolahde] [nvarchar](55) NULL,
	[rivinumero] [int] NULL,
	[aineistotunnus] [nvarchar](8) NULL,
	[koulutussektori] [nvarchar](2) NULL,
	[ika_1v] [nvarchar](4) NULL,
	[aloittaneet] [int] NULL,
	[aloittaneet_kirjoihintulovuosi] [int] NULL,
	[aloittaneet_korkeakoulusektori] [int] NULL,
	[aloittaneet_korkeakoulusektori_lasnaoleva] [int] NULL,
	[aloittaneet_sektori] [int] NULL,
	[aloittaneet_sektori_lasnaoleva] [int] NULL,
	[aloittaneet_korkeakoulu] [int] NULL,
	[aloittaneet_korkeakoulu_lasnaoleva] [int] NULL,
	[aloittaneet_opintoala] [int] NULL,
	[aloittaneet_opintoala_lasnaoleva] [int] NULL,
	[opiskelijat] [int] NULL,
	[opiskelijat_lasna] [int] NULL,
	[opiskelijat_fte] [decimal](18, 1) NULL,
	[koulutuslaji_OKM_avain] [nvarchar](2) NULL,
	[koulutusryhma_avain] [varchar](2) NULL,
	[ikaryhma1_avain] [varchar](10) NULL,
	[ikaryhma2_avain] [varchar](10) NULL,
	[laak] [varchar](1) NULL,
	[ltop] [nvarchar](1) NULL
) ON [PRIMARY]
GO


