USE [VipunenTK_DW]
GO

/****** Object:  View [dbo].[_v_sa_K3_9_Tutk_suor_osuus_aloittaneista_toinen_aste_surrogaattiavaimet_nykytila_taulusta]    Script Date: 9.1.2026 13.38.12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO











ALTER View [dbo].[_v_sa_K3_9_Tutk_suor_osuus_aloittaneista_toinen_aste_surrogaattiavaimet_nykytila_taulusta] as

/****** Script for SelectTopNRows command from SSMS  ******/
--Select * from [okm].[okm_ktpo_tiedontuotanto_in].f --> 6588 rows
--Select * from [vipunen_ETL].[v_sa_K3_9_Tutk_suor_osuus_aloittaneista_toinen_aste_surrogaattiavaimet] --> 6588 rows

SELECT [tilv]
      ,[lahde]
      ,[sp]
      ,[syntv]
      ,[aikielir1]
      ,[alvv]
      ,[allk]
      ,[klaji]
      ,[ophal]
      ,[jarj]
      ,[kkun]
      ,[koulk]
      ,[pohjkoulk]
      ,[tietolahde]
      ,[rivinumero]
      ,[aineistorivinumero]

      ,[lkm]


--2009
      ,'lu_2009' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [lusuorv_2009] AND
      suorlk = [lusuorlk_2009] AND
      tutkmaak = [lututkmaak_2009] AND
      tutkjarj = [lututkjarj_2009] AND
      tutkkoulk = [lututkkoulk_2009]  )
      ,'ampt_2009' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [amptsuorv_2009] AND
      suorlk = [amptsuorlk_2009] AND
      tutkmaak = [ampttutkmaak_2009] AND
      tutkjarj = [ampttutkjarj_2009] AND
      tutkkoulk = [ampttutkkoulk_2009]  )
      ,'amlk_2009' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [amlksuorv_2009] AND
      suorlk = [amlksuorlk_2009] AND
      tutkmaak = [amlktutkmaak_2009] AND
      tutkjarj = [amlktutkjarj_2009] AND
      tutkkoulk = [amlktutkkoulk_2009]  )
      ,'muukk_2009' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [muukksuorv_2009] AND
      suorlk = [muukksuorlk_2009] AND
      tutkmaak = [muukktutkmaak_2009] AND
      tutkjarj = [muukktutkjarj_2009] AND
      tutkkoulk = [muukktutkkoulk_2009]  )
      ,'luopisk_2009' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [luopiskkoulk_2009] AND
      opiskjarj = [luopiskjarj_2009] AND
      kmaak = [lukmaak_2009]  )
      ,'amptopisk_2009' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [amptopiskkoulk_2009] AND
      opiskjarj = [amptopiskjarj_2009] AND
      kmaak = [amptkmaak_2009]  )
      ,'amlkopisk_2009' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [amlkopiskkoulk_2009] AND
      opiskjarj = [amlkopiskjarj_2009] AND
      kmaak = [amlkkmaak_2009]  )
      ,'muukkopisk_2009' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [muukkopiskkoulk_2009] AND
      opiskjarj = [muukkopiskjarj_2009] AND
      kmaak = [muukkkmaak_2009]  )
      ,'ptoim1r5_2009' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
      ptoim1r5 = [ptoim1r5_2009]  )
      --amas = [amas_2009]  ) )
--2010
      ,'lu_2010' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [lusuorv_2010] AND
      suorlk = [lusuorlk_2010] AND
      tutkmaak = [lututkmaak_2010] AND
      tutkjarj = [lututkjarj_2010] AND
      tutkkoulk = [lututkkoulk_2010]  )
      ,'ampt_2010' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [amptsuorv_2010] AND
      suorlk = [amptsuorlk_2010] AND
      tutkmaak = [ampttutkmaak_2010] AND
      tutkjarj = [ampttutkjarj_2010] AND
      tutkkoulk = [ampttutkkoulk_2010]  )
      ,'amlk_2010' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [amlksuorv_2010] AND
      suorlk = [amlksuorlk_2010] AND
      tutkmaak = [amlktutkmaak_2010] AND
      tutkjarj = [amlktutkjarj_2010] AND
      tutkkoulk = [amlktutkkoulk_2010]  )
      ,'muukk_2010' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [muukksuorv_2010] AND
      suorlk = [muukksuorlk_2010] AND
      tutkmaak = [muukktutkmaak_2010] AND
      tutkjarj = [muukktutkjarj_2010] AND
      tutkkoulk = [muukktutkkoulk_2010]  )
      ,'luopisk_2010' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [luopiskkoulk_2010] AND
      opiskjarj = [luopiskjarj_2010] AND
      kmaak = [lukmaak_2010]  )
      ,'amptopisk_2010' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [amptopiskkoulk_2010] AND
      opiskjarj = [amptopiskjarj_2010] AND
      kmaak = [amptkmaak_2010]  )
      ,'amlkopisk_2010' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [amlkopiskkoulk_2010] AND
      opiskjarj = [amlkopiskjarj_2010] AND
      kmaak = [amlkkmaak_2010]  )
      ,'muukkopisk_2010' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [muukkopiskkoulk_2010] AND
      opiskjarj = [muukkopiskjarj_2010] AND
      kmaak = [muukkkmaak_2010]  )
      ,'ptoim1r5_2010' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
      ptoim1r5 = [ptoim1r5_2010]  )
      --amas = [amas_2010]  ) )
--2011
      ,'lu_2011' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [lusuorv_2011] AND
      suorlk = [lusuorlk_2011] AND
      tutkmaak = [lututkmaak_2011] AND
      tutkjarj = [lututkjarj_2011] AND
      tutkkoulk = [lututkkoulk_2011]  )
      ,'ampt_2011' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [amptsuorv_2011] AND
      suorlk = [amptsuorlk_2011] AND
      tutkmaak = [ampttutkmaak_2011] AND
      tutkjarj = [ampttutkjarj_2011] AND
      tutkkoulk = [ampttutkkoulk_2011]  )
      ,'amlk_2011' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [amlksuorv_2011] AND
      suorlk = [amlksuorlk_2011] AND
      tutkmaak = [amlktutkmaak_2011] AND
      tutkjarj = [amlktutkjarj_2011] AND
      tutkkoulk = [amlktutkkoulk_2011]  )
      ,'muukk_2011' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [muukksuorv_2011] AND
      suorlk = [muukksuorlk_2011] AND
      tutkmaak = [muukktutkmaak_2011] AND
      tutkjarj = [muukktutkjarj_2011] AND
      tutkkoulk = [muukktutkkoulk_2011]  )
      ,'luopisk_2011' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [luopiskkoulk_2011] AND
      opiskjarj = [luopiskjarj_2011] AND
      kmaak = [lukmaak_2011]  )
      ,'amptopisk_2011' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [amptopiskkoulk_2011] AND
      opiskjarj = [amptopiskjarj_2011] AND
      kmaak = [amptkmaak_2011]  )
      ,'amlkopisk_2011' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [amlkopiskkoulk_2011] AND
      opiskjarj = [amlkopiskjarj_2011] AND
      kmaak = [amlkkmaak_2011]  )
      ,'muukkopisk_2011' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [muukkopiskkoulk_2011] AND
      opiskjarj = [muukkopiskjarj_2011] AND
      kmaak = [muukkkmaak_2011]  )
      ,'ptoim1r5_2011' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
      ptoim1r5 = [ptoim1r5_2011]  )
      --amas = [amas_2011]  ) )
--2012
      ,'lu_2012' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [lusuorv_2012] AND
      suorlk = [lusuorlk_2012] AND
      tutkmaak = [lututkmaak_2012] AND
      tutkjarj = [lututkjarj_2012] AND
      tutkkoulk = [lututkkoulk_2012]  )
      ,'ampt_2012' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [amptsuorv_2012] AND
      suorlk = [amptsuorlk_2012] AND
      tutkmaak = [ampttutkmaak_2012] AND
      tutkjarj = [ampttutkjarj_2012] AND
      tutkkoulk = [ampttutkkoulk_2012]  )
      ,'amlk_2012' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [amlksuorv_2012] AND
      suorlk = [amlksuorlk_2012] AND
      tutkmaak = [amlktutkmaak_2012] AND
      tutkjarj = [amlktutkjarj_2012] AND
      tutkkoulk = [amlktutkkoulk_2012]  )
      ,'muukk_2012' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [muukksuorv_2012] AND
      suorlk = [muukksuorlk_2012] AND
      tutkmaak = [muukktutkmaak_2012] AND
      tutkjarj = [muukktutkjarj_2012] AND
      tutkkoulk = [muukktutkkoulk_2012]  )
      ,'luopisk_2012' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [luopiskkoulk_2012] AND
      opiskjarj = [luopiskjarj_2012] AND
      kmaak = [lukmaak_2012]  )
      ,'amptopisk_2012' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [amptopiskkoulk_2012] AND
      opiskjarj = [amptopiskjarj_2012] AND
      kmaak = [amptkmaak_2012]  )
      ,'amlkopisk_2012' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [amlkopiskkoulk_2012] AND
      opiskjarj = [amlkopiskjarj_2012] AND
      kmaak = [amlkkmaak_2012]  )
      ,'muukkopisk_2012' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [muukkopiskkoulk_2012] AND
      opiskjarj = [muukkopiskjarj_2012] AND
      kmaak = [muukkkmaak_2012]  )
      ,'ptoim1r5_2012' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
      ptoim1r5 = [ptoim1r5_2012]  )
      --amas = [amas_2012]  ) )
--2013
      ,'lu_2013' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [lusuorv_2013] AND
      suorlk = [lusuorlk_2013] AND
      tutkmaak = [lututkmaak_2013] AND
      tutkjarj = [lututkjarj_2013] AND
      tutkkoulk = [lututkkoulk_2013]  )
      ,'ampt_2013' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [amptsuorv_2013] AND
      suorlk = [amptsuorlk_2013] AND
      tutkmaak = [ampttutkmaak_2013] AND
      tutkjarj = [ampttutkjarj_2013] AND
      tutkkoulk = [ampttutkkoulk_2013]  )
      ,'amlk_2013' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [amlksuorv_2013] AND
      suorlk = [amlksuorlk_2013] AND
      tutkmaak = [amlktutkmaak_2013] AND
      tutkjarj = [amlktutkjarj_2013] AND
      tutkkoulk = [amlktutkkoulk_2013]  )
      ,'muukk_2013' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [muukksuorv_2013] AND
      suorlk = [muukksuorlk_2013] AND
      tutkmaak = [muukktutkmaak_2013] AND
      tutkjarj = [muukktutkjarj_2013] AND
      tutkkoulk = [muukktutkkoulk_2013]  )
      ,'luopisk_2013' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [luopiskkoulk_2013] AND
      opiskjarj = [luopiskjarj_2013] AND
      kmaak = [lukmaak_2013]  )
      ,'amptopisk_2013' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [amptopiskkoulk_2013] AND
      opiskjarj = [amptopiskjarj_2013] AND
      kmaak = [amptkmaak_2013]  )
      ,'amlkopisk_2013' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [amlkopiskkoulk_2013] AND
      opiskjarj = [amlkopiskjarj_2013] AND
      kmaak = [amlkkmaak_2013]  )
      ,'muukkopisk_2013' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [muukkopiskkoulk_2013] AND
      opiskjarj = [muukkopiskjarj_2013] AND
      kmaak = [muukkkmaak_2013]  )
      ,'ptoim1r5_2013' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
      ptoim1r5 = [ptoim1r5_2013]  )
      --amas = [amas_2013]  ) )

--2014
      ,'lu_2014' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [lusuorv_2014] AND
      suorlk = [lusuorlk_2014] AND
      tutkmaak = [lututkmaak_2014] AND
      tutkjarj = [lututkjarj_2014] AND
      tutkkoulk = [lututkkoulk_2014]  )
      ,'ampt_2014' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [amptsuorv_2014] AND
      suorlk = [amptsuorlk_2014] AND
      tutkmaak = [ampttutkmaak_2014] AND
      tutkjarj = [ampttutkjarj_2014] AND
      tutkkoulk = [ampttutkkoulk_2014]  )
      ,'amlk_2014' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [amlksuorv_2014] AND
      suorlk = [amlksuorlk_2014] AND
      tutkmaak = [amlktutkmaak_2014] AND
      tutkjarj = [amlktutkjarj_2014] AND
      tutkkoulk = [amlktutkkoulk_2014]  )
      ,'muukk_2014' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [muukksuorv_2014] AND
      suorlk = [muukksuorlk_2014] AND
      tutkmaak = [muukktutkmaak_2014] AND
      tutkjarj = [muukktutkjarj_2014] AND
      tutkkoulk = [muukktutkkoulk_2014]  )
      ,'luopisk_2014' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [luopiskkoulk_2014] AND
      opiskjarj = [luopiskjarj_2014] AND
      kmaak = [lukmaak_2014]  )
      ,'amptopisk_2014' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [amptopiskkoulk_2014] AND
      opiskjarj = [amptopiskjarj_2014] AND
      kmaak = [amptkmaak_2014]  )
      ,'amlkopisk_2014' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [amlkopiskkoulk_2014] AND
      opiskjarj = [amlkopiskjarj_2014] AND
      kmaak = [amlkkmaak_2014]  )
      ,'muukkopisk_2014' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [muukkopiskkoulk_2014] AND
      opiskjarj = [muukkopiskjarj_2014] AND
      kmaak = [muukkkmaak_2014]  )
      ,'ptoim1r5_2014' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
      ptoim1r5 = [ptoim1r5_2014]  )
      --amas = [amas_2014]  ) )

--2015
      ,'lu_2015' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [lusuorv_2015] AND
      suorlk = [lusuorlk_2015] AND
      tutkmaak = [lututkmaak_2015] AND
      tutkjarj = [lututkjarj_2015] AND
      tutkkoulk = [lututkkoulk_2015]  )
      ,'ampt_2015' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [amptsuorv_2015] AND
      suorlk = [amptsuorlk_2015] AND
      tutkmaak = [ampttutkmaak_2015] AND
      tutkjarj = [ampttutkjarj_2015] AND
      tutkkoulk = [ampttutkkoulk_2015]  )
      ,'amlk_2015' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [amlksuorv_2015] AND
      suorlk = [amlksuorlk_2015] AND
      tutkmaak = [amlktutkmaak_2015] AND
      tutkjarj = [amlktutkjarj_2015] AND
      tutkkoulk = [amlktutkkoulk_2015]  )
      ,'muukk_2015' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [muukksuorv_2015] AND
      suorlk = [muukksuorlk_2015] AND
      tutkmaak = [muukktutkmaak_2015] AND
      tutkjarj = [muukktutkjarj_2015] AND
      tutkkoulk = [muukktutkkoulk_2015]  )
      ,'luopisk_2015' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [luopiskkoulk_2015] AND
      opiskjarj = [luopiskjarj_2015] AND
      kmaak = [lukmaak_2015]  )
      ,'amptopisk_2015' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [amptopiskkoulk_2015] AND
      opiskjarj = [amptopiskjarj_2015] AND
      kmaak = [amptkmaak_2015]  )
      ,'amlkopisk_2015' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [amlkopiskkoulk_2015] AND
      opiskjarj = [amlkopiskjarj_2015] AND
      kmaak = [amlkkmaak_2015]  )
      ,'muukkopisk_2015' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [muukkopiskkoulk_2015] AND
      opiskjarj = [muukkopiskjarj_2015] AND
      kmaak = [muukkkmaak_2015]  )
      ,'ptoim1r5_2015' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
      ptoim1r5 = [ptoim1r5_2015]  )
      --amas = [amas_2015]  ) )

--2016

      ,'lu_2016' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [lusuorv_2016] AND
      suorlk = [lusuorlk_2016] AND
      tutkmaak = [lututkmaak_2016] AND
      tutkjarj = [lututkjarj_2016] AND
      tutkkoulk = [lututkkoulk_2016]  )
      ,'ampt_2016' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [amptsuorv_2016] AND
      suorlk = [amptsuorlk_2016] AND
      tutkmaak = [ampttutkmaak_2016] AND
      tutkjarj = [ampttutkjarj_2016] AND
      tutkkoulk = [ampttutkkoulk_2016]  )
      ,'amlk_2016' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [amlksuorv_2016] AND
      suorlk = [amlksuorlk_2016] AND
      tutkmaak = [amlktutkmaak_2016] AND
      tutkjarj = [amlktutkjarj_2016] AND
      tutkkoulk = [amlktutkkoulk_2016]  )
      ,'muukk_2016' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [muukksuorv_2016] AND
      suorlk = [muukksuorlk_2016] AND
      tutkmaak = [muukktutkmaak_2016] AND
      tutkjarj = [muukktutkjarj_2016] AND
      tutkkoulk = [muukktutkkoulk_2016]  )
      ,'luopisk_2016' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [luopiskkoulk_2016] AND
      opiskjarj = [luopiskjarj_2016] AND
      kmaak = [lukmaak_2016]  )
      ,'amptopisk_2016' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [amptopiskkoulk_2016] AND
      opiskjarj = [amptopiskjarj_2016] AND
      kmaak = [amptkmaak_2016]  )
      ,'amlkopisk_2016' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [amlkopiskkoulk_2016] AND
      opiskjarj = [amlkopiskjarj_2016] AND
      kmaak = [amlkkmaak_2016]  )
      ,'muukkopisk_2016' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [muukkopiskkoulk_2016] AND
      opiskjarj = [muukkopiskjarj_2016] AND
      kmaak = [muukkkmaak_2016]  )
      ,'ptoim1r5_2016' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
      ptoim1r5 = [ptoim1r5_2016]  )
      --amas = [amas_2016]  ) )

--2017

      ,'lu_2017' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [lusuorv_2017] AND
      suorlk = [lusuorlk_2017] AND
      tutkmaak = [lututkmaak_2017] AND
      tutkjarj = [lututkjarj_2017] AND
      tutkkoulk = [lututkkoulk_2017]  )
      ,'ampt_2017' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [amptsuorv_2017] AND
      suorlk = [amptsuorlk_2017] AND
      tutkmaak = [ampttutkmaak_2017] AND
      tutkjarj = [ampttutkjarj_2017] AND
      tutkkoulk = [ampttutkkoulk_2017]  )
      ,'amlk_2017' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [amlksuorv_2017] AND
      suorlk = [amlksuorlk_2017] AND
      tutkmaak = [amlktutkmaak_2017] AND
      tutkjarj = [amlktutkjarj_2017] AND
      tutkkoulk = [amlktutkkoulk_2017]  )
      ,'muukk_2017' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [muukksuorv_2017] AND
      suorlk = [muukksuorlk_2017] AND
      tutkmaak = [muukktutkmaak_2017] AND
      tutkjarj = [muukktutkjarj_2017] AND
      tutkkoulk = [muukktutkkoulk_2017]  )
      ,'luopisk_2017' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [luopiskkoulk_2017] AND
      opiskjarj = [luopiskjarj_2017] AND
      kmaak = [lukmaak_2017]  )
      ,'amptopisk_2017' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [amptopiskkoulk_2017] AND
      opiskjarj = [amptopiskjarj_2017] AND
      kmaak = [amptkmaak_2017]  )
      ,'amlkopisk_2017' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [amlkopiskkoulk_2017] AND
      opiskjarj = [amlkopiskjarj_2017] AND
      kmaak = [amlkkmaak_2017]  )
      ,'muukkopisk_2017' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [muukkopiskkoulk_2017] AND
      opiskjarj = [muukkopiskjarj_2017] AND
      kmaak = [muukkkmaak_2017]  )
      ,'ptoim1r5_2017' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
      ptoim1r5 = [ptoim1r5_2017]  )
      --amas = [amas_2017]  ) )

--2018

      ,'lu_2018' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [lusuorv_2018] AND
      suorlk = [lusuorlk_2018] AND
      tutkmaak = [lututkmaak_2018] AND
      tutkjarj = [lututkjarj_2018] AND
      tutkkoulk = [lututkkoulk_2018]  )
      ,'ampt_2018' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [amptsuorv_2018] AND
      suorlk = [amptsuorlk_2018] AND
      tutkmaak = [ampttutkmaak_2018] AND
      tutkjarj = [ampttutkjarj_2018] AND
      tutkkoulk = [ampttutkkoulk_2018]  )
      ,'amlk_2018' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [amlksuorv_2018] AND
      suorlk = [amlksuorlk_2018] AND
      tutkmaak = [amlktutkmaak_2018] AND
      tutkjarj = [amlktutkjarj_2018] AND
      tutkkoulk = [amlktutkkoulk_2018]  )
      ,'muukk_2018' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [muukksuorv_2018] AND
      suorlk = [muukksuorlk_2018] AND
      tutkmaak = [muukktutkmaak_2018] AND
      tutkjarj = [muukktutkjarj_2018] AND
      tutkkoulk = [muukktutkkoulk_2018]  )
      ,'luopisk_2018' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [luopiskkoulk_2018] AND
      opiskjarj = [luopiskjarj_2018] AND
      kmaak = [lukmaak_2018]  )
      ,'amptopisk_2018' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [amptopiskkoulk_2018] AND
      opiskjarj = [amptopiskjarj_2018] AND
      kmaak = [amptkmaak_2018]  )
      ,'amlkopisk_2018' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [amlkopiskkoulk_2018] AND
      opiskjarj = [amlkopiskjarj_2018] AND
      kmaak = [amlkkmaak_2018]  )
      ,'muukkopisk_2018' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [muukkopiskkoulk_2018] AND
      opiskjarj = [muukkopiskjarj_2018] AND
      kmaak = [muukkkmaak_2018]  )
      ,'ptoim1r5_2018' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
      ptoim1r5 = [ptoim1r5_2018]  )
      --amas = [amas_2018]  ) )

--2019

      ,'lu_2019' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [lusuorv_2019] AND
      suorlk = [lusuorlk_2019] AND
      tutkmaak = [lututkmaak_2019] AND
      tutkjarj = [lututkjarj_2019] AND
      tutkkoulk = [lututkkoulk_2019]  )
      ,'ampt_2019' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [amptsuorv_2019] AND
      suorlk = [amptsuorlk_2019] AND
      tutkmaak = [ampttutkmaak_2019] AND
      tutkjarj = [ampttutkjarj_2019] AND
      tutkkoulk = [ampttutkkoulk_2019]  )
      ,'amlk_2019' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [amlksuorv_2019] AND
      suorlk = [amlksuorlk_2019] AND
      tutkmaak = [amlktutkmaak_2019] AND
      tutkjarj = [amlktutkjarj_2019] AND
      tutkkoulk = [amlktutkkoulk_2019]  )
      ,'muukk_2019' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [muukksuorv_2019] AND
      suorlk = [muukksuorlk_2019] AND
      tutkmaak = [muukktutkmaak_2019] AND
      tutkjarj = [muukktutkjarj_2019] AND
      tutkkoulk = [muukktutkkoulk_2019]  )
      ,'luopisk_2019' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [luopiskkoulk_2019] AND
      opiskjarj = [luopiskjarj_2019] AND
      kmaak = [lukmaak_2019]  )
      ,'amptopisk_2019' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [amptopiskkoulk_2019] AND
      opiskjarj = [amptopiskjarj_2019] AND
      kmaak = [amptkmaak_2019]  )
      ,'amlkopisk_2019' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [amlkopiskkoulk_2019] AND
      opiskjarj = [amlkopiskjarj_2019] AND
      kmaak = [amlkkmaak_2019]  )
      ,'muukkopisk_2019' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [muukkopiskkoulk_2019] AND
      opiskjarj = [muukkopiskjarj_2019] AND
      kmaak = [muukkkmaak_2019]  )
      ,'ptoim1r5_2019' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
      ptoim1r5 = [ptoim1r5_2019]  )
      --amas = [amas_2019]  ) )

--2020

      ,'lu_2020' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [lusuorv_2020] AND
      suorlk = [lusuorlk_2020] AND
      tutkmaak = [lututkmaak_2020] AND
      tutkjarj = [lututkjarj_2020] AND
      tutkkoulk = [lututkkoulk_2020]  )
      ,'ampt_2020' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [amptsuorv_2020] AND
      suorlk = [amptsuorlk_2020] AND
      tutkmaak = [ampttutkmaak_2020] AND
      tutkjarj = [ampttutkjarj_2020] AND
      tutkkoulk = [ampttutkkoulk_2020]  )
      ,'amlk_2020' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [amlksuorv_2020] AND
      suorlk = [amlksuorlk_2020] AND
      tutkmaak = [amlktutkmaak_2020] AND
      tutkjarj = [amlktutkjarj_2020] AND
      tutkkoulk = [amlktutkkoulk_2020]  )
      ,'muukk_2020' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [muukksuorv_2020] AND
      suorlk = [muukksuorlk_2020] AND
      tutkmaak = [muukktutkmaak_2020] AND
      tutkjarj = [muukktutkjarj_2020] AND
      tutkkoulk = [muukktutkkoulk_2020]  )
      ,'luopisk_2020' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [luopiskkoulk_2020] AND
      opiskjarj = [luopiskjarj_2020] AND
      kmaak = [lukmaak_2020]  )
      ,'amptopisk_2020' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [amptopiskkoulk_2020] AND
      opiskjarj = [amptopiskjarj_2020] AND
      kmaak = [amptkmaak_2020]  )
      ,'amlkopisk_2020' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [amlkopiskkoulk_2020] AND
      opiskjarj = [amlkopiskjarj_2020] AND
      kmaak = [amlkkmaak_2020]  )
      ,'muukkopisk_2020' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [muukkopiskkoulk_2020] AND
      opiskjarj = [muukkopiskjarj_2020] AND
      kmaak = [muukkkmaak_2020]  )
      ,'ptoim1r5_2020' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
      ptoim1r5 = [ptoim1r5_2020]  )
      --amas = [amas_2020]  ) )

--2021

      ,'lu_2021' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [lusuorv_2021] AND
      suorlk = [lusuorlk_2021] AND
      tutkmaak = [lututkmaak_2021] AND
      tutkjarj = [lututkjarj_2021] AND
      tutkkoulk = [lututkkoulk_2021]  )
      ,'ampt_2021' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [amptsuorv_2021] AND
      suorlk = [amptsuorlk_2021] AND
      tutkmaak = [ampttutkmaak_2021] AND
      tutkjarj = [ampttutkjarj_2021] AND
      tutkkoulk = [ampttutkkoulk_2021]  )
      ,'amlk_2021' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [amlksuorv_2021] AND
      suorlk = [amlksuorlk_2021] AND
      tutkmaak = [amlktutkmaak_2021] AND
      tutkjarj = [amlktutkjarj_2021] AND
      tutkkoulk = [amlktutkkoulk_2021]  )
      ,'muukk_2021' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [muukksuorv_2021] AND
      suorlk = [muukksuorlk_2021] AND
      tutkmaak = [muukktutkmaak_2021] AND
      tutkjarj = [muukktutkjarj_2021] AND
      tutkkoulk = [muukktutkkoulk_2021]  )
      ,'luopisk_2021' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [luopiskkoulk_2021] AND
      opiskjarj = [luopiskjarj_2021] AND
      kmaak = [lukmaak_2021]  )
      ,'amptopisk_2021' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [amptopiskkoulk_2021] AND
      opiskjarj = [amptopiskjarj_2021] AND
      kmaak = [amptkmaak_2021]  )
      ,'amlkopisk_2021' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [amlkopiskkoulk_2021] AND
      opiskjarj = [amlkopiskjarj_2021] AND
      kmaak = [amlkkmaak_2021]  )
      ,'muukkopisk_2021' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [muukkopiskkoulk_2021] AND
      opiskjarj = [muukkopiskjarj_2021] AND
      kmaak = [muukkkmaak_2021]  )
      ,'ptoim1r5_2021' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
      ptoim1r5 = [ptoim1r5_2021]  )
      --amas = [amas_2021]  ) )

--2022

      ,'lu_2022' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [lusuorv_2022] AND
      suorlk = [lusuorlk_2022] AND
      tutkmaak = [lututkmaak_2022] AND
      tutkjarj = [lututkjarj_2022] AND
      tutkkoulk = [lututkkoulk_2022]  )
      ,'ampt_2022' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [amptsuorv_2022] AND
      suorlk = [amptsuorlk_2022] AND
      tutkmaak = [ampttutkmaak_2022] AND
      tutkjarj = [ampttutkjarj_2022] AND
      tutkkoulk = [ampttutkkoulk_2022]  )
      ,'amlk_2022' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [amlksuorv_2022] AND
      suorlk = [amlksuorlk_2022] AND
      tutkmaak = [amlktutkmaak_2022] AND
      tutkjarj = [amlktutkjarj_2022] AND
      tutkkoulk = [amlktutkkoulk_2022]  )
      ,'muukk_2022' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [muukksuorv_2022] AND
      suorlk = [muukksuorlk_2022] AND
      tutkmaak = [muukktutkmaak_2022] AND
      tutkjarj = [muukktutkjarj_2022] AND
      tutkkoulk = [muukktutkkoulk_2022]  )
      ,'luopisk_2022' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [luopiskkoulk_2022] AND
      opiskjarj = [luopiskjarj_2022] AND
      kmaak = [lukmaak_2022]  )
      ,'amptopisk_2022' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [amptopiskkoulk_2022] AND
      opiskjarj = [amptopiskjarj_2022] AND
      kmaak = [amptkmaak_2022]  )
      ,'amlkopisk_2022' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [amlkopiskkoulk_2022] AND
      opiskjarj = [amlkopiskjarj_2022] AND
      kmaak = [amlkkmaak_2022]  )
      ,'muukkopisk_2022' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [muukkopiskkoulk_2022] AND
      opiskjarj = [muukkopiskjarj_2022] AND
      kmaak = [muukkkmaak_2022]  )
      ,'ptoim1r5_2022' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
      ptoim1r5 = [ptoim1r5_2022]  )
      --amas = [amas_2022]  ) )

-- 2023

      ,'lu_2023' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [lusuorv_2023] AND
      suorlk = [lusuorlk_2023] AND
      tutkmaak = [lututkmaak_2023] AND
      tutkjarj = [lututkjarj_2023] AND
      tutkkoulk = [lututkkoulk_2023]  )
      ,'ampt_2023' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [amptsuorv_2023] AND
      suorlk = [amptsuorlk_2023] AND
      tutkmaak = [ampttutkmaak_2023] AND
      tutkjarj = [ampttutkjarj_2023] AND
      tutkkoulk = [ampttutkkoulk_2023]  )
      ,'amlk_2023' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [amlksuorv_2023] AND
      suorlk = [amlksuorlk_2023] AND
      tutkmaak = [amlktutkmaak_2023] AND
      tutkjarj = [amlktutkjarj_2023] AND
      tutkkoulk = [amlktutkkoulk_2023]  )
      ,'muukk_2023' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [muukksuorv_2023] AND
      suorlk = [muukksuorlk_2023] AND
      tutkmaak = [muukktutkmaak_2023] AND
      tutkjarj = [muukktutkjarj_2023] AND
      tutkkoulk = [muukktutkkoulk_2023]  )
      ,'luopisk_2023' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [luopiskkoulk_2023] AND
      opiskjarj = [luopiskjarj_2023] AND
      kmaak = [lukmaak_2023]  )
      ,'amptopisk_2023' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [amptopiskkoulk_2023] AND
      opiskjarj = [amptopiskjarj_2023] AND
      kmaak = [amptkmaak_2023]  )
      ,'amlkopisk_2023' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [amlkopiskkoulk_2023] AND
      opiskjarj = [amlkopiskjarj_2023] AND
      kmaak = [amlkkmaak_2023]  )
      ,'muukkopisk_2023' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk = [muukkopiskkoulk_2023] AND
      opiskjarj = [muukkopiskjarj_2023] AND
      kmaak = [muukkkmaak_2023]  )
      ,'ptoim1r5_2023' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
      ptoim1r5 = [ptoim1r5_2023]  )
      --amas = [amas_2023]  ) )

--UUSI VUOSI
--Lisää uuden vuoden kentät tähän yläpuolelle. Käytä pohjana edellisen vuoden kenttiä. Poista alusta edellinen vuosi.

  FROM VipunenTK_DW.dbo.[_sa_K3_9_Tutk_suor_osuus_aloittaneista_toinen_aste_nykytila] f




GO


