USE [AnteroAPI]
GO

DROP TABLE IF EXISTS [dw].[api_amm_rahoitus_koonti]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dw].[api_amm_rahoitus_koonti](
	[defaultorder] [bigint] NULL,
	[koulutuksen_jarjestaja] [nvarchar](255) NULL,
	[hankintakoulutuksen_jarjestaja] [nvarchar](500) NULL,
	[oppilaitos] [nvarchar](500) NULL,
	[toimipiste] [nvarchar](500) NULL,
	[kokonaisuus] [varchar](32) NOT NULL,
	[varainhoitovuosi] [int] NULL,
	[rahoituskausi_pl_palautteet] [nvarchar](39) NULL,
	[rahoituskausi_palautteet] [nvarchar](50) NULL,
	[tilastokausi] [nvarchar](50) NULL,
	[tilastovuosi] [int] NULL,
	[tilastokuukausi] [int] NULL,
	[ika_maksuttomuusraja] [varchar](13) NOT NULL,
	[ikaryhma] [nvarchar](100) NULL,
	[sukupuoli] [nvarchar](100) NULL,
	[aidinkieli_ryhma] [nvarchar](100) NULL,
	[suorituksen_tyyppi] [varchar](255) NULL,
	[suorituskieli] [nvarchar](100) NULL,
	[tutkintotyyppi_rahoitus] [varchar](41) NULL,
	[kustannusryhma] [nvarchar](117) NULL,
	[rahoitusmuoto] [nvarchar](100) NULL,
	[majoitus] [varchar](100) NULL,
	[vaativa_erityinen_tuki] [varchar](27) NOT NULL,
	[luvaton_koulutus] [varchar](255) NULL,
	[luvaton_majoitus] [varchar](255) NULL,
	[luvaton_korotustekija] [varchar](255) NULL,
	[luvanmukainen_suorituskieli] [varchar](36) NOT NULL,
	[hyvaksytyt_hylatyt_opiskelijavuodet] [nvarchar](100) NULL,
	[huomioidaan_rahoituksessa_kylla_ei] [bit] NULL,
	[jarjestajarakenne_viimeisin_suoritepaatos_kylla_ei] [bit] NULL,
	[maksuttomuus_rahoitus_kylla_ei] [bit] NULL,
	[oppisopimuskoulutus_kylla_ei] [bit] NULL,
	[tyovoimakoulutus_kylla_ei] [bit] NULL,
	[vankilaopetus_kylla_ei] [bit] NULL,
	[hankintakoulutus_kylla_ei] [bit] NULL,
	[toiminnanohjauksen_kokeilu_kylla_ei] [bit] NULL,
	[koodit_koulutuksen_jarjestajan_pilke_alue_kokeilu] [nvarchar](1) NULL,
	[koodit_koulutuksen_jarjestaja] [varchar](20) NULL,
	[koodit_hankintakoulutuksen_jarjestaja] [varchar](20) NULL,
	[koodit_tutkinto] [int] NULL,
	[opiskelijavuodet_painottamaton_lkm] [decimal](30, 20) NULL,
	[enimmaismaaran_mukaiset_opiskelijavuodet_painottamaton_lkm] [decimal](38, 26) NULL,
	[rahoituksen_perusteena_olevat_opiskelijavuodet_painotettu_lahtotaso_lkm] [decimal](38, 26) NULL,
	[rahoituksen_perusteena_olevat_opiskelijavuodet_painotettu_kustannusryhma_tutkintotyyppi_lkm] [decimal](38, 26) NULL,
	[rahoituksen_perusteena_olevat_opiskelijavuodet_painotettu_korotus_erityistuki_lkm] [decimal](38, 26) NULL,
	[rahoituksen_perusteena_olevat_opiskelijavuodet_painotettu_korotus_majoitus_lkm] [decimal](38, 26) NULL,
	[rahoituksen_perusteena_olevat_opiskelijavuodet_painotettu_kustannusryhma_tutkintotyyppi_korotukset_lkm] [decimal](38, 24) NULL,
	[rahoituksen_perusteena_olevat_opiskelijavuodet_painotettu_lahtotaso_osuus] [decimal](30, 29) NULL,
	[rahoituksen_perusteena_olevat_opiskelijavuodet_painotettu_kustannusryhma_tutkintotyyppi_korotukset_osuus] [decimal](30, 29) NULL,
	[tutkinnot_painottamaton_lkm] [decimal](38, 20) NULL,
	[tutkinnot_painotettu_lkm] [decimal](30, 20) NULL,
	[tutkinnon_osien_osaamispisteet_lkm] [decimal](30, 20) NULL,
	[tutkinnon_osien_laskentaan_hyvaksytyt_osaamispisteet_lkm] [decimal](38, 26) NULL,
	[tutkinnot_painotettu_ja_tutkinnon_osien_laskentaan_hyvaksytyt_osaamispisteet_lkm] [decimal](38, 26) NULL,
	[tutkinnot_painotettu_ja_tutkinnon_osien_laskentaan_hyvaksytyt_osaamispisteet_osuus] [decimal](30, 29) NULL,
	[koulutuksen_suorittaneet_tyollistyneet_ei_tyollinen_ennen_koulutusta_lkm] [int] NULL,
	[koulutuksen_suorittaneet_jatkoopiskelijat_ei_tyollinen_ennen_koulutusta_lkm] [int] NULL,
	[koulutuksen_suorittaneet_tyollistyneet_ja_jatkoopiskelijat_ei_tyollinen_ennen_koulutusta_lkm] [int] NULL,
	[koulutuksen_suorittaneet_tyollistyneet_ja_jatkoopiskelijat_ei_tyollinen_ennen_koulutusta_osuus] [decimal](30, 29) NULL,
	[opiskelunsa_aloittaneiden_palautteen_pisteet_lkm] [decimal](30, 20) NULL,
	[opiskelunsa_aloittaneiden_palautteen_painotetut_pisteet_lkm] [decimal](30, 20) NULL,
	[opiskelunsa_aloittaneiden_palautteen_painotetut_pisteet_osuus] [decimal](30, 29) NULL,
	[opiskelunsa_paattaneiden_palautteen_pisteet_lkm] [decimal](30, 20) NULL,
	[opiskelunsa_paattaneiden_palautteen_painotetut_pisteet_lkm] [decimal](38, 17) NULL,
	[opiskelunsa_paattaneiden_palautteen_painotetut_pisteet_osuus] [decimal](30, 29) NULL,
	[tyopaikkaohjaajakyselyn_pisteet_lkm] [decimal](30, 20) NULL,
	[tyopaikkaohjaajakyselyn_painotetut_pisteet_lkm] [decimal](30, 20) NULL,
	[tyopaikkaohjaajakyselyn_painotetut_pisteet_osuus] [decimal](30, 29) NULL,
	[tyopaikkakyselyn_pisteet_lkm] [decimal](30, 20) NULL,
	[tyopaikkakyselyn_pisteet_osuus] [decimal](30, 29) NULL,
	[rahoitusosioiden_osuuksilla_painotettu_osuus] [decimal](38,37) NULL,
	[laskennallinen_rahoitus_ed_v_kiintea_osuus] [decimal](30, 29) NULL,
	[laskennallinen_rahoitus_kiintea_osuus] [decimal](30, 29) NULL
) ON [PRIMARY]
GO
