USE [ANTERO]
GO

/****** Object:  Table [dw].[f_haku_ja_valinta_hakeneet_korkea_aste]    Script Date: 4.2.2026 9.32.15 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dw].[f_haku_ja_valinta_hakeneet_korkea_aste]') AND type in (N'U'))
DROP TABLE [dw].[f_haku_ja_valinta_hakeneet_korkea_aste]
GO

/****** Object:  Table [dw].[f_haku_ja_valinta_hakeneet_korkea_aste]    Script Date: 4.2.2026 9.32.15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dw].[f_haku_ja_valinta_hakeneet_korkea_aste](
	[koulutuksen_alkamisvuosi] [int] NULL,
	[master_oid] [varchar](100) NULL,
	[hakemus_oid] [varchar](100) NULL,
	[sa_haku_ja_valinta_vuosikello_korkea_aste_id] [int] NULL,
	[d_kausi_koulutuksen_alkamiskausi_id] [int] NULL,
	[d_sukupuoli_id] [int] NULL,
	[d_kieli_aidinkieli_id] [bigint] NULL,
	[d_ika_id] [bigint] NULL,
	[d_maatjavaltiot2_kansalaisuus_id] [int] NULL,
	[d_alueluokitus_kotikunta_id] [int] NULL,
	[d_organisaatioluokitus_koulutustoimija_id] [bigint] NULL,
	[d_organisaatioluokitus_oppilaitos_id] [bigint] NULL,
	[d_organisaatioluokitus_toimipiste_id] [bigint] NULL,
	[d_haku_id] [int] NULL,
	[d_hakukohde_id] [int] NULL,
	[d_koulutusluokitus_id] [int] NULL,
	[d_haku_amk_yo_id] [int] NULL,
	[d_tutkinnon_aloitussykli_kk_id] [int] NULL,
	[d_tutkinnon_taso_kk_id] [int] NULL,
	[d_kytkin_pohjakoulutus_am_id] [int] NULL,
	[d_kytkin_pohjakoulutus_amp_id] [int] NULL,
	[d_kytkin_pohjakoulutus_amt_id] [int] NULL,
	[d_kytkin_pohjakoulutus_amv_id] [int] NULL,
	[d_kytkin_pohjakoulutus_avoin_id] [int] NULL,
	[d_kytkin_pohjakoulutus_kk_id] [int] NULL,
	[d_kytkin_pohjakoulutus_kk_ulk_id] [int] NULL,
	[d_kytkin_pohjakoulutus_lk_id] [int] NULL,
	[d_kytkin_pohjakoulutus_ulk_id] [int] NULL,
	[d_kytkin_pohjakoulutus_yo_id] [int] NULL,
	[d_kytkin_pohjakoulutus_yo_ammatillinen_id] [int] NULL,
	[d_kytkin_pohjakoulutus_yo_kansainvalinen_suomessa_id] [int] NULL,
	[d_kytkin_pohjakoulutus_yo_ulkomainen_id] [int] NULL,
	[d_kytkin_pohjakoulutus_muu_id] [int] NULL,
	[toisen_asteen_koulutuksen_suoritusvuosi] [int] NULL,
	[d_pohjakoulutus_id] [int] NULL,
	[pohjakoulutuksen_paattovuosi] [int] NULL,
	[d_kytkin_pohjakoulutus_ulkomaat_id] [int] NULL,
	[pohjakoulutus_suomessa_priorisoitu] [int] NULL,
	[d_kalenteri_ylioppilastutkinnon_suorituspaivamaara_id] [bigint] NULL,
	[d_oppilaitoksenopetuskieli_koulutuksen_kieli_id] [int] NULL,
	[d_valintatapajonon_tyyppi_id] [int] NULL,
	[d_alueluokitus_hakukohde_id] [int] NULL,
	[d_valintatapajono_id] [int] NULL,
	[d_organisaatioluokitus_hakukohde1_id] [bigint] NULL,
	[d_koulutusluokitus_hakukohde1_id] [int] NULL,
	[d_tutkinnon_aloitussykli_kk_hakukohde1_id] [int] NULL,
	[d_hakukohde_hakukohde1_id] [int] NULL,
	[d_organisaatioluokitus_hakukohde2_id] [bigint] NULL,
	[d_koulutusluokitus_hakukohde2_id] [int] NULL,
	[d_tutkinnon_aloitussykli_kk_hakukohde2_id] [int] NULL,
	[d_hakukohde_hakukohde2_id] [int] NULL,
	[d_organisaatioluokitus_hakukohde3_id] [bigint] NULL,
	[d_koulutusluokitus_hakukohde3_id] [int] NULL,
	[d_tutkinnon_aloitussykli_kk_hakukohde3_id] [int] NULL,
	[d_hakukohde_hakukohde3_id] [int] NULL,
	[d_organisaatioluokitus_hakukohde4_id] [bigint] NULL,
	[d_koulutusluokitus_hakukohde4_id] [int] NULL,
	[d_tutkinnon_aloitussykli_kk_hakukohde4_id] [int] NULL,
	[d_hakukohde_hakukohde4_id] [int] NULL,
	[d_organisaatioluokitus_hakukohde5_id] [bigint] NULL,
	[d_koulutusluokitus_hakukohde5_id] [int] NULL,
	[d_tutkinnon_aloitussykli_kk_hakukohde5_id] [int] NULL,
	[d_hakukohde_hakukohde5_id] [int] NULL,
	[d_organisaatioluokitus_hakukohde6_id] [bigint] NULL,
	[d_koulutusluokitus_hakukohde6_id] [int] NULL,
	[d_tutkinnon_aloitussykli_kk_hakukohde6_id] [int] NULL,
	[d_hakukohde_hakukohde6_id] [int] NULL,
	[hakutoive] [int] NULL,
	[valittu] [int] NULL,
	[vastaanottanut_paikan] [int] NULL,
	[ilmoittautunut] [int] NULL,
	[ensikertalainen] [int] NULL,
	[valittu_ensisijaiseen_kohteeseen] [int] NULL,
	[valittu_ensisijaisen_kohteen_koulutusalalle] [int] NULL,
	[ei_vastaanottoa_kaudella] [int] NULL,
	[aidosti_ensikertainen] [int] NULL,
	[ensikertaisuuden_lahde] [int] NULL,
	[pk_rnk] [bigint] NULL,
	[kansainvalinen_opiskelija] [int] NULL,
	[uusi_ylioppilas] [int] NULL,
	[aloittanut_opinnot_toisen_asteen_koulutuksen_suoritusvuonna] [int] NULL,
	[aloittanut_opinnot_ilmoittamansa_pohjakoulutuksen_suoritusvuonna] [int] NULL,
	[laajuus] [decimal](18, 0) NULL,
	[valitut_indikaattori] [date] NULL,
	[vastaanottaneet_indikaattori] [date] NULL,
	[pisteet] [float] NULL,
	[alpa] [int] NULL,
	[pisteraja] [float] NULL,
	[hakemus_luotu] [datetime] NULL,
	[source] [varchar] (100) NULL,
	[username] [varchar] (100) NULL,
	[loadtime] [date] NULL
) ON [PRIMARY]