USE [VipunenTK_DW]



GO

DROP TABLE VipunenTK_DW.dbo.[_sa_K3_9_Tutk_suor_osuus_aloittaneista_toinen_aste_nykytila]

Select top 0 * into VipunenTK_DW.dbo.[_sa_K3_9_Tutk_suor_osuus_aloittaneista_toinen_aste_nykytila] from VipunenTK_SA.dbo.[v_sa_K3_9_Tutk_suor_osuus_aloittaneista_toinen_aste_nykytila]

DROP TABLE VipunenTK_DW.dbo.[_sa_K3_10_Tutk_suor_osuus_aloittaneista_korkeakoulut_nykytila]

Select top 0 * into VipunenTK_DW.dbo.[_sa_K3_10_Tutk_suor_osuus_aloittaneista_korkeakoulut_nykytila] from VipunenTK_SA.dbo.[v_sa_K3_10_Tutk_suor_osuus_aloittaneista_korkeakoulut_nykytila]

DROP TABLE VipunenTK_DW.dbo._sa_K3_9_Tutk_suor_osuus_aloittaneista_toinen_aste_surrogaattiavaimet

Select top 0 * into dbo._sa_K3_9_Tutk_suor_osuus_aloittaneista_toinen_aste_surrogaattiavaimet from _v_sa_K3_9_Tutk_suor_osuus_aloittaneista_toinen_aste_surrogaattiavaimet_nykytila_taulusta

DROP TABLE VipunenTK_DW.dbo._sa_K3_10_Tutk_suor_osuus_aloittaneista_korkeakoulut_surrogaattiavaimet

Select top 0 * into dbo._sa_K3_10_Tutk_suor_osuus_aloittaneista_korkeakoulut_surrogaattiavaimet from _v_sa_K3_10_Tutk_suor_osuus_aloittaneista_korkeakoulut_surrogaattiavaimet_nykytila_taulusta

GO



USE [ANTERO]