USE [Antero]
GO 
IF NOT EXISTS (select * from INFORMATION_SCHEMA.TABLES where TABLE_SCHEMA='dw' and TABLE_NAME='f_amos_rajapinta_rahoitus_kriteerit_new') 
BEGIN
CREATE TABLE [dw].[f_amos_rajapinta_rahoitus_kriteerit_new](
 [ytunnus] [nvarchar](12) NULL,
 [ta_ensikertainen_suoritepaatos] [float] NULL,
 [ta_lisasuoritepaatos] [float] NULL,
 [ta_paatokset_yhteensa] [float] NULL,
 [ltae_mukaiset_paatokset] [float] NULL,
 [ltae2_mukaiset_paatokset] [float] NULL,
 [ltae_mukaiset_paatokset_yhteensa] [float] NULL,
 [paatokset_yhteensa] [float] NULL,
 [sp_lisays_kohdentamaton_jarj_esitys] [float] NULL,
 [sp_lisays_kohdentamaton_okm_paatos] [float] NULL,
 [sp_lisays_kohdentamaton_tyovkoul_jarj_esitys] [float] NULL,
 [sp_lisays_kohdentamaton_tyovkoul_okm_paatos] [float] NULL,
 [sp_lisays_kohdennettu_krit1_jarj_esitys] [float] NULL,
 [sp_lisays_kohdennettu_krit1_okm_paatos] [float] NULL,
 [sp_lisays_kohdennettu_tyovkoul_krit1_jarj_esitys] [float] NULL,
 [sp_lisays_kohdennettu_tyovkoul_krit1_okm_paatos] [float] NULL,
 [sp_lisays_kohdennettu_krit2_jarj_esitys] [float] NULL,
 [sp_lisays_kohdennettu_krit2_okm_paatos] [float] NULL,
 [sp_lisays_kohdennettu_tyovkoul_krit2_jarj_esitys] [float] NULL,
 [sp_lisays_kohdennettu_tyovkoul_krit2_okm_paatos] [float] NULL,
 [sp_lisays_kohdennettu_krit3_jarj_esitys] [float] NULL,
 [sp_lisays_kohdennettu_krit3_okm_paatos] [float] NULL,
 [sp_lisays_kohdennettu_tyovkoul_krit3_jarj_esitys] [float] NULL,
 [sp_lisays_kohdennettu_tyovkoul_krit3_okm_paatos] [float] NULL,
 [sp_lisays_kohdennettu_krit4_jarj_esitys] [float] NULL,
 [sp_lisays_kohdennettu_krit4_okm_paatos] [float] NULL,
 [sp_lisays_kohdennettu_tyovkoul_krit4_jarj_esitys] [float] NULL,
 [sp_lisays_kohdennettu_tyovkoul_krit4_okm_paatos] [float] NULL,
 [ta_ensikertainen_suoritepaatos_harkv_korotus] [float] NULL,
 [ta_lisasuoritepaatos_harkv_korotus] [float] NULL,
 [harkv_korotus_syy1_hakemus] [float] NULL,
 [harkv_korotus_syy1_paatos] [float] NULL,
 [harkv_korotus_syy2_hakemus] [float] NULL,
 [harkv_korotus_syy2_paatos] [float] NULL,
 [harkv_korotus_syy3_hakemus] [float] NULL,
 [harkv_korotus_syy3_paatos] [float] NULL,
 [harkv_korotus_syy4_hakemus] [float] NULL,
 [harkv_korotus_syy4_paatos] [float] NULL,
 [vos_ta_mukainen] [float] NULL,
 [vos_ta_mukainen_sis_alv] [float] NULL,
 [vos_ta_ja_ltae_mukainen] [float] NULL,
 [vos_ta_ja_ltae_mukainen_sis_alv] [float] NULL,
 [vos_ta_ja_ltae_mukainen_vertailu] [float] NULL,
 [vos_ta_ja_ltae_mukainen_vertailu_sis_alv] [float] NULL,
 [ensikertainen_sp_suoritusrahoitus] [float] NULL,
 [ensikertainen_sp_tyovoimakoulutus] [float] NULL,
 [ltae_mukaiset_paatokset_ed_vuosi] [float] NULL,
 [ltae2_mukaiset_paatokset_ed_vuosi] [float] NULL,
 [jarj_luvan_opiskelijavuodet] [float] NULL,
 [profiilikerroin_korjattu] [float] NULL
)
END

