USE [VipunenTK_lisatiedot]
GO
/****** Object:  Table [dbo].[tutkimuksen_rahoituslahde]    Script Date: 31.1.2019 16:15:34 ******/
DROP TABLE [dbo].[tutkimuksen_rahoituslahde]
GO
/****** Object:  Table [dbo].[tutkimuksen_rahoituslahde]    Script Date: 31.1.2019 16:15:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tutkimuksen_rahoituslahde](
	[id] [int] NOT NULL,
	[luotu] [date] NULL,
	[rahoituslahde_avain] [nvarchar](10) NULL,
	[rahoituslahdetarkennus] [nvarchar](50) NULL,
	[rahoituslahdetarkennus_SV] [nvarchar](100) NULL,
	[rahoituslahdetarkennus_EN] [nvarchar](100) NULL,
	[jarjestys_rahoituslahdetarkennus] [nvarchar](50) NULL,
	[rahoituslahde] [nvarchar](50) NULL,
	[rahoituslahde_SV] [nvarchar](100) NULL,
	[rahoituslahde_EN] [nvarchar](100) NULL,
	[jarjestys_rahoituslahde] [nvarchar](50) NULL,
	[ulkopuolisen_rahoituksen_kansainvalisyys] [nvarchar](50) NULL,
	[ulkopuolisen_rahoituksen_kansainvalisyys_SV] [nvarchar](100) NULL,
	[ulkopuolisen_rahoituksen_kansainvalisyys_EN] [nvarchar](100) NULL,
	[jarjestys_ulkopuolisen_rahoituksen_kansainvalisyys] [nvarchar](50) NULL,
	[rahoituslahteen_tyyppi] [nvarchar](50) NULL,
	[rahoituslahteen_tyyppi_SV] [nvarchar](100) NULL,
	[rahoituslahteen_tyyppi_EN] [nvarchar](100) NULL,
	[jarjestys_rahoituslahteen_tyyppi] [nvarchar](50) NULL,
	[rahoituksen_laatu] [nvarchar](50) NULL,
	[rahoituksen_laatu_SV] [nvarchar](100) NULL,
	[rahoituksen_laatu_EN] [nvarchar](100) NULL,
	[jarjestys_rahoituksen_laatu] [nvarchar](50) NULL,
	[virhetilanne] [nchar](1) NULL,
	[poistettu] [nchar](1) NULL,
	[tietolahde] [nvarchar](50) NULL,
	[kommentti] [nvarchar](250) NULL
) ON [PRIMARY]

GO
INSERT [dbo].[tutkimuksen_rahoituslahde] ([id], [luotu], [rahoituslahde_avain], [rahoituslahdetarkennus], [rahoituslahdetarkennus_SV], [rahoituslahdetarkennus_EN], [jarjestys_rahoituslahdetarkennus], [rahoituslahde], [rahoituslahde_SV], [rahoituslahde_EN], [jarjestys_rahoituslahde], [ulkopuolisen_rahoituksen_kansainvalisyys], [ulkopuolisen_rahoituksen_kansainvalisyys_SV], [ulkopuolisen_rahoituksen_kansainvalisyys_EN], [jarjestys_ulkopuolisen_rahoituksen_kansainvalisyys], [rahoituslahteen_tyyppi], [rahoituslahteen_tyyppi_SV], [rahoituslahteen_tyyppi_EN], [jarjestys_rahoituslahteen_tyyppi], [rahoituksen_laatu], [rahoituksen_laatu_SV], [rahoituksen_laatu_EN], [jarjestys_rahoituksen_laatu], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (-1, CAST(N'2015-02-25' AS Date), N'-1', N'Tuntematon', N'Information saknas', N'Missing data', N'998', N'Tuntematon', N'Information saknas', N'Missing data', N'998', N'Tuntematon', N'Information saknas', N'Missing data', N'998', N'Tuntematon', N'Information saknas', N'Missing data', N'998', N'Tuntematon', N'Information saknas', N'Missing data', N'998', N'K', N'0', N'Työpaja 11.2.2015', N'CSC Jarmo')
GO
INSERT [dbo].[tutkimuksen_rahoituslahde] ([id], [luotu], [rahoituslahde_avain], [rahoituslahdetarkennus], [rahoituslahdetarkennus_SV], [rahoituslahdetarkennus_EN], [jarjestys_rahoituslahdetarkennus], [rahoituslahde], [rahoituslahde_SV], [rahoituslahde_EN], [jarjestys_rahoituslahde], [ulkopuolisen_rahoituksen_kansainvalisyys], [ulkopuolisen_rahoituksen_kansainvalisyys_SV], [ulkopuolisen_rahoituksen_kansainvalisyys_EN], [jarjestys_ulkopuolisen_rahoituksen_kansainvalisyys], [rahoituslahteen_tyyppi], [rahoituslahteen_tyyppi_SV], [rahoituslahteen_tyyppi_EN], [jarjestys_rahoituslahteen_tyyppi], [rahoituksen_laatu], [rahoituksen_laatu_SV], [rahoituksen_laatu_EN], [jarjestys_rahoituksen_laatu], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (-2, CAST(N'2015-02-25' AS Date), N'-2', N'Virhetilanne', N'Feltillstånd', N'Error occurred', N'999', N'Virhetilanne', N'Feltillstånd', N'Error occurred', N'999', N'Virhetilanne', N'Feltillstånd', N'Error occurred', N'999', N'Virhetilanne', N'Feltillstånd', N'Error occurred', N'999', N'Virhetilanne', N'Feltillstånd', N'Error occurred', N'999', N'K', N'0', N'Työpaja 11.2.2015', N'CSC Jarmo')
GO
INSERT [dbo].[tutkimuksen_rahoituslahde] ([id], [luotu], [rahoituslahde_avain], [rahoituslahdetarkennus], [rahoituslahdetarkennus_SV], [rahoituslahdetarkennus_EN], [jarjestys_rahoituslahdetarkennus], [rahoituslahde], [rahoituslahde_SV], [rahoituslahde_EN], [jarjestys_rahoituslahde], [ulkopuolisen_rahoituksen_kansainvalisyys], [ulkopuolisen_rahoituksen_kansainvalisyys_SV], [ulkopuolisen_rahoituksen_kansainvalisyys_EN], [jarjestys_ulkopuolisen_rahoituksen_kansainvalisyys], [rahoituslahteen_tyyppi], [rahoituslahteen_tyyppi_SV], [rahoituslahteen_tyyppi_EN], [jarjestys_rahoituslahteen_tyyppi], [rahoituksen_laatu], [rahoituksen_laatu_SV], [rahoituksen_laatu_EN], [jarjestys_rahoituksen_laatu], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (1, CAST(N'2015-02-25' AS Date), N'OKM_PERUS', N'OKM perusrahoitus', N'UKM basfinansiering', N'Ministry of Education and Culture basic funding', N'100', N'OKM perusrahoitus', N'UKM basfinansiering', N'Ministry of Education and Culture basic funding', N'100', N'budjettirahoitus', N'budgetfinansiering', N'budgeted financing', N'100', N'budjettirahoitus', N'budgetfinansiering', N'budgeted financing', N'100', N'budjettirahoitus', N'budgetfinansiering', N'budgeted financing', N'100', N'E', N'0', N'Työpaja 11.2.2015', N'CSC Jarmo')
GO
INSERT [dbo].[tutkimuksen_rahoituslahde] ([id], [luotu], [rahoituslahde_avain], [rahoituslahdetarkennus], [rahoituslahdetarkennus_SV], [rahoituslahdetarkennus_EN], [jarjestys_rahoituslahdetarkennus], [rahoituslahde], [rahoituslahde_SV], [rahoituslahde_EN], [jarjestys_rahoituslahde], [ulkopuolisen_rahoituksen_kansainvalisyys], [ulkopuolisen_rahoituksen_kansainvalisyys_SV], [ulkopuolisen_rahoituksen_kansainvalisyys_EN], [jarjestys_ulkopuolisen_rahoituksen_kansainvalisyys], [rahoituslahteen_tyyppi], [rahoituslahteen_tyyppi_SV], [rahoituslahteen_tyyppi_EN], [jarjestys_rahoituslahteen_tyyppi], [rahoituksen_laatu], [rahoituksen_laatu_SV], [rahoituksen_laatu_EN], [jarjestys_rahoituksen_laatu], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (2, CAST(N'2015-02-25' AS Date), N'AKATEMIA', N'Suomen Akatemia', N'Finlands Akademi', N'Academy of Finland', N'110', N'Suomen Akatemia', N'Finlands Akademi', N'Academy of Finland', N'110', N'kotimainen', N'inhemsk', N'national', N'200', N'ulkopuolinen rahoitus', N'extern finansiering', N'external financing', N'200', N'muu kilpailtu tutkimusrahoitus', N'annan konkurrensutsatt forskarfinansiering', N'other research funding subject to tendering', N'300', N'E', N'0', N'Työpaja 11.2.2015', N'CSC Jarmo')
GO
INSERT [dbo].[tutkimuksen_rahoituslahde] ([id], [luotu], [rahoituslahde_avain], [rahoituslahdetarkennus], [rahoituslahdetarkennus_SV], [rahoituslahdetarkennus_EN], [jarjestys_rahoituslahdetarkennus], [rahoituslahde], [rahoituslahde_SV], [rahoituslahde_EN], [jarjestys_rahoituslahde], [ulkopuolisen_rahoituksen_kansainvalisyys], [ulkopuolisen_rahoituksen_kansainvalisyys_SV], [ulkopuolisen_rahoituksen_kansainvalisyys_EN], [jarjestys_ulkopuolisen_rahoituksen_kansainvalisyys], [rahoituslahteen_tyyppi], [rahoituslahteen_tyyppi_SV], [rahoituslahteen_tyyppi_EN], [jarjestys_rahoituslahteen_tyyppi], [rahoituksen_laatu], [rahoituksen_laatu_SV], [rahoituksen_laatu_EN], [jarjestys_rahoituksen_laatu], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (3, CAST(N'2015-02-25' AS Date), N'OKM_MUU', N'Muu OKM', N'Annan UKM', N'Other MEC', N'120', N'Ministeriöt', N'Ministerier', N'Ministries', N'120', N'kotimainen', N'inhemsk', N'national', N'200', N'ulkopuolinen rahoitus', N'extern finansiering', N'external financing', N'200', N'muu tutkimusrahoitus', N'annan forskarfinansiering', N'other research funding', N'200', N'E', N'0', N'Työpaja 11.2.2015', N'CSC Jarmo')
GO
INSERT [dbo].[tutkimuksen_rahoituslahde] ([id], [luotu], [rahoituslahde_avain], [rahoituslahdetarkennus], [rahoituslahdetarkennus_SV], [rahoituslahdetarkennus_EN], [jarjestys_rahoituslahdetarkennus], [rahoituslahde], [rahoituslahde_SV], [rahoituslahde_EN], [jarjestys_rahoituslahde], [ulkopuolisen_rahoituksen_kansainvalisyys], [ulkopuolisen_rahoituksen_kansainvalisyys_SV], [ulkopuolisen_rahoituksen_kansainvalisyys_EN], [jarjestys_ulkopuolisen_rahoituksen_kansainvalisyys], [rahoituslahteen_tyyppi], [rahoituslahteen_tyyppi_SV], [rahoituslahteen_tyyppi_EN], [jarjestys_rahoituslahteen_tyyppi], [rahoituksen_laatu], [rahoituksen_laatu_SV], [rahoituksen_laatu_EN], [jarjestys_rahoituksen_laatu], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (4, CAST(N'2015-02-25' AS Date), N'TEKES', N'Business Finland', N'Business Finland', N'Business Finland', N'115', N'Business Finland', N'Business Finland', N'Business Finland', N'115', N'kotimainen', N'inhemsk', N'national', N'200', N'ulkopuolinen rahoitus', N'extern finansiering', N'external financing', N'200', N'muu kilpailtu tutkimusrahoitus', N'annan konkurrensutsatt forskarfinansiering', N'other research funding subject to tendering', N'300', N'E', N'0', N'Työpaja 11.2.2015', N'CSC Jarmo')
GO
INSERT [dbo].[tutkimuksen_rahoituslahde] ([id], [luotu], [rahoituslahde_avain], [rahoituslahdetarkennus], [rahoituslahdetarkennus_SV], [rahoituslahdetarkennus_EN], [jarjestys_rahoituslahdetarkennus], [rahoituslahde], [rahoituslahde_SV], [rahoituslahde_EN], [jarjestys_rahoituslahde], [ulkopuolisen_rahoituksen_kansainvalisyys], [ulkopuolisen_rahoituksen_kansainvalisyys_SV], [ulkopuolisen_rahoituksen_kansainvalisyys_EN], [jarjestys_ulkopuolisen_rahoituksen_kansainvalisyys], [rahoituslahteen_tyyppi], [rahoituslahteen_tyyppi_SV], [rahoituslahteen_tyyppi_EN], [jarjestys_rahoituslahteen_tyyppi], [rahoituksen_laatu], [rahoituksen_laatu_SV], [rahoituksen_laatu_EN], [jarjestys_rahoituksen_laatu], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (5, CAST(N'2015-02-25' AS Date), N'TEM_MUU', N'Muu TEM', N'Annan ANM', N'Other MEE', N'140', N'Ministeriöt', N'Ministerier', N'Ministries', N'120', N'kotimainen', N'inhemsk', N'national', N'200', N'ulkopuolinen rahoitus', N'extern finansiering', N'external financing', N'200', N'muu tutkimusrahoitus', N'annan forskarfinansiering', N'other research funding', N'200', N'E', N'0', N'Työpaja 11.2.2015', N'CSC Jarmo')
GO
INSERT [dbo].[tutkimuksen_rahoituslahde] ([id], [luotu], [rahoituslahde_avain], [rahoituslahdetarkennus], [rahoituslahdetarkennus_SV], [rahoituslahdetarkennus_EN], [jarjestys_rahoituslahdetarkennus], [rahoituslahde], [rahoituslahde_SV], [rahoituslahde_EN], [jarjestys_rahoituslahde], [ulkopuolisen_rahoituksen_kansainvalisyys], [ulkopuolisen_rahoituksen_kansainvalisyys_SV], [ulkopuolisen_rahoituksen_kansainvalisyys_EN], [jarjestys_ulkopuolisen_rahoituksen_kansainvalisyys], [rahoituslahteen_tyyppi], [rahoituslahteen_tyyppi_SV], [rahoituslahteen_tyyppi_EN], [jarjestys_rahoituslahteen_tyyppi], [rahoituksen_laatu], [rahoituksen_laatu_SV], [rahoituksen_laatu_EN], [jarjestys_rahoituksen_laatu], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (6, CAST(N'2015-02-25' AS Date), N'UM', N'UM', N'UM', N'MFA', N'150', N'Ministeriöt', N'Ministerier', N'Ministries', N'120', N'kotimainen', N'inhemsk', N'national', N'200', N'ulkopuolinen rahoitus', N'extern finansiering', N'external financing', N'200', N'muu tutkimusrahoitus', N'annan forskarfinansiering', N'other research funding', N'200', N'E', N'0', N'Työpaja 11.2.2015', N'CSC Jarmo')
GO
INSERT [dbo].[tutkimuksen_rahoituslahde] ([id], [luotu], [rahoituslahde_avain], [rahoituslahdetarkennus], [rahoituslahdetarkennus_SV], [rahoituslahdetarkennus_EN], [jarjestys_rahoituslahdetarkennus], [rahoituslahde], [rahoituslahde_SV], [rahoituslahde_EN], [jarjestys_rahoituslahde], [ulkopuolisen_rahoituksen_kansainvalisyys], [ulkopuolisen_rahoituksen_kansainvalisyys_SV], [ulkopuolisen_rahoituksen_kansainvalisyys_EN], [jarjestys_ulkopuolisen_rahoituksen_kansainvalisyys], [rahoituslahteen_tyyppi], [rahoituslahteen_tyyppi_SV], [rahoituslahteen_tyyppi_EN], [jarjestys_rahoituslahteen_tyyppi], [rahoituksen_laatu], [rahoituksen_laatu_SV], [rahoituksen_laatu_EN], [jarjestys_rahoituksen_laatu], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (7, CAST(N'2015-02-25' AS Date), N'OM ', N'OM ', N'JM ', N'MJ ', N'160', N'Ministeriöt', N'Ministerier', N'Ministries', N'120', N'kotimainen', N'inhemsk', N'national', N'200', N'ulkopuolinen rahoitus', N'extern finansiering', N'external financing', N'200', N'muu tutkimusrahoitus', N'annan forskarfinansiering', N'other research funding', N'200', N'E', N'0', N'Työpaja 11.2.2015', N'CSC Jarmo')
GO
INSERT [dbo].[tutkimuksen_rahoituslahde] ([id], [luotu], [rahoituslahde_avain], [rahoituslahdetarkennus], [rahoituslahdetarkennus_SV], [rahoituslahdetarkennus_EN], [jarjestys_rahoituslahdetarkennus], [rahoituslahde], [rahoituslahde_SV], [rahoituslahde_EN], [jarjestys_rahoituslahde], [ulkopuolisen_rahoituksen_kansainvalisyys], [ulkopuolisen_rahoituksen_kansainvalisyys_SV], [ulkopuolisen_rahoituksen_kansainvalisyys_EN], [jarjestys_ulkopuolisen_rahoituksen_kansainvalisyys], [rahoituslahteen_tyyppi], [rahoituslahteen_tyyppi_SV], [rahoituslahteen_tyyppi_EN], [jarjestys_rahoituslahteen_tyyppi], [rahoituksen_laatu], [rahoituksen_laatu_SV], [rahoituksen_laatu_EN], [jarjestys_rahoituksen_laatu], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (8, CAST(N'2015-02-25' AS Date), N'SM', N'SM', N'IM', N'MI', N'170', N'Ministeriöt', N'Ministerier', N'Ministries', N'120', N'kotimainen', N'inhemsk', N'national', N'200', N'ulkopuolinen rahoitus', N'extern finansiering', N'external financing', N'200', N'muu tutkimusrahoitus', N'annan forskarfinansiering', N'other research funding', N'200', N'E', N'0', N'Työpaja 11.2.2015', N'CSC Jarmo')
GO
INSERT [dbo].[tutkimuksen_rahoituslahde] ([id], [luotu], [rahoituslahde_avain], [rahoituslahdetarkennus], [rahoituslahdetarkennus_SV], [rahoituslahdetarkennus_EN], [jarjestys_rahoituslahdetarkennus], [rahoituslahde], [rahoituslahde_SV], [rahoituslahde_EN], [jarjestys_rahoituslahde], [ulkopuolisen_rahoituksen_kansainvalisyys], [ulkopuolisen_rahoituksen_kansainvalisyys_SV], [ulkopuolisen_rahoituksen_kansainvalisyys_EN], [jarjestys_ulkopuolisen_rahoituksen_kansainvalisyys], [rahoituslahteen_tyyppi], [rahoituslahteen_tyyppi_SV], [rahoituslahteen_tyyppi_EN], [jarjestys_rahoituslahteen_tyyppi], [rahoituksen_laatu], [rahoituksen_laatu_SV], [rahoituksen_laatu_EN], [jarjestys_rahoituksen_laatu], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (9, CAST(N'2015-02-25' AS Date), N'PM', N'PM', N'FSM', N'MD', N'180', N'Ministeriöt', N'Ministerier', N'Ministries', N'120', N'kotimainen', N'inhemsk', N'national', N'200', N'ulkopuolinen rahoitus', N'extern finansiering', N'external financing', N'200', N'muu tutkimusrahoitus', N'annan forskarfinansiering', N'other research funding', N'200', N'E', N'0', N'Työpaja 11.2.2015', N'CSC Jarmo')
GO
INSERT [dbo].[tutkimuksen_rahoituslahde] ([id], [luotu], [rahoituslahde_avain], [rahoituslahdetarkennus], [rahoituslahdetarkennus_SV], [rahoituslahdetarkennus_EN], [jarjestys_rahoituslahdetarkennus], [rahoituslahde], [rahoituslahde_SV], [rahoituslahde_EN], [jarjestys_rahoituslahde], [ulkopuolisen_rahoituksen_kansainvalisyys], [ulkopuolisen_rahoituksen_kansainvalisyys_SV], [ulkopuolisen_rahoituksen_kansainvalisyys_EN], [jarjestys_ulkopuolisen_rahoituksen_kansainvalisyys], [rahoituslahteen_tyyppi], [rahoituslahteen_tyyppi_SV], [rahoituslahteen_tyyppi_EN], [jarjestys_rahoituslahteen_tyyppi], [rahoituksen_laatu], [rahoituksen_laatu_SV], [rahoituksen_laatu_EN], [jarjestys_rahoituksen_laatu], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (10, CAST(N'2015-02-25' AS Date), N'VM', N'VM', N'FM', N'MF', N'190', N'Ministeriöt', N'Ministerier', N'Ministries', N'120', N'kotimainen', N'inhemsk', N'national', N'200', N'ulkopuolinen rahoitus', N'extern finansiering', N'external financing', N'200', N'muu tutkimusrahoitus', N'annan forskarfinansiering', N'other research funding', N'200', N'E', N'0', N'Työpaja 11.2.2015', N'CSC Jarmo')
GO
INSERT [dbo].[tutkimuksen_rahoituslahde] ([id], [luotu], [rahoituslahde_avain], [rahoituslahdetarkennus], [rahoituslahdetarkennus_SV], [rahoituslahdetarkennus_EN], [jarjestys_rahoituslahdetarkennus], [rahoituslahde], [rahoituslahde_SV], [rahoituslahde_EN], [jarjestys_rahoituslahde], [ulkopuolisen_rahoituksen_kansainvalisyys], [ulkopuolisen_rahoituksen_kansainvalisyys_SV], [ulkopuolisen_rahoituksen_kansainvalisyys_EN], [jarjestys_ulkopuolisen_rahoituksen_kansainvalisyys], [rahoituslahteen_tyyppi], [rahoituslahteen_tyyppi_SV], [rahoituslahteen_tyyppi_EN], [jarjestys_rahoituslahteen_tyyppi], [rahoituksen_laatu], [rahoituksen_laatu_SV], [rahoituksen_laatu_EN], [jarjestys_rahoituksen_laatu], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (11, CAST(N'2015-02-25' AS Date), N'MMM', N'MMM', N'JSM', N'MAF', N'200', N'Ministeriöt', N'Ministerier', N'Ministries', N'120', N'kotimainen', N'inhemsk', N'national', N'200', N'ulkopuolinen rahoitus', N'extern finansiering', N'external financing', N'200', N'muu tutkimusrahoitus', N'annan forskarfinansiering', N'other research funding', N'200', N'E', N'0', N'Työpaja 11.2.2015', N'CSC Jarmo')
GO
INSERT [dbo].[tutkimuksen_rahoituslahde] ([id], [luotu], [rahoituslahde_avain], [rahoituslahdetarkennus], [rahoituslahdetarkennus_SV], [rahoituslahdetarkennus_EN], [jarjestys_rahoituslahdetarkennus], [rahoituslahde], [rahoituslahde_SV], [rahoituslahde_EN], [jarjestys_rahoituslahde], [ulkopuolisen_rahoituksen_kansainvalisyys], [ulkopuolisen_rahoituksen_kansainvalisyys_SV], [ulkopuolisen_rahoituksen_kansainvalisyys_EN], [jarjestys_ulkopuolisen_rahoituksen_kansainvalisyys], [rahoituslahteen_tyyppi], [rahoituslahteen_tyyppi_SV], [rahoituslahteen_tyyppi_EN], [jarjestys_rahoituslahteen_tyyppi], [rahoituksen_laatu], [rahoituksen_laatu_SV], [rahoituksen_laatu_EN], [jarjestys_rahoituksen_laatu], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (12, CAST(N'2015-02-25' AS Date), N'LVM', N'LVM', N'KM', N'MTC', N'210', N'Ministeriöt', N'Ministerier', N'Ministries', N'120', N'kotimainen', N'inhemsk', N'national', N'200', N'ulkopuolinen rahoitus', N'extern finansiering', N'external financing', N'200', N'muu tutkimusrahoitus', N'annan forskarfinansiering', N'other research funding', N'200', N'E', N'0', N'Työpaja 11.2.2015', N'CSC Jarmo')
GO
INSERT [dbo].[tutkimuksen_rahoituslahde] ([id], [luotu], [rahoituslahde_avain], [rahoituslahdetarkennus], [rahoituslahdetarkennus_SV], [rahoituslahdetarkennus_EN], [jarjestys_rahoituslahdetarkennus], [rahoituslahde], [rahoituslahde_SV], [rahoituslahde_EN], [jarjestys_rahoituslahde], [ulkopuolisen_rahoituksen_kansainvalisyys], [ulkopuolisen_rahoituksen_kansainvalisyys_SV], [ulkopuolisen_rahoituksen_kansainvalisyys_EN], [jarjestys_ulkopuolisen_rahoituksen_kansainvalisyys], [rahoituslahteen_tyyppi], [rahoituslahteen_tyyppi_SV], [rahoituslahteen_tyyppi_EN], [jarjestys_rahoituslahteen_tyyppi], [rahoituksen_laatu], [rahoituksen_laatu_SV], [rahoituksen_laatu_EN], [jarjestys_rahoituksen_laatu], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (13, CAST(N'2015-02-25' AS Date), N'STM', N'STM', N'SHM', N'MSAH', N'220', N'Ministeriöt', N'Ministerier', N'Ministries', N'120', N'kotimainen', N'inhemsk', N'national', N'200', N'ulkopuolinen rahoitus', N'extern finansiering', N'external financing', N'200', N'muu tutkimusrahoitus', N'annan forskarfinansiering', N'other research funding', N'200', N'E', N'0', N'Työpaja 11.2.2015', N'CSC Jarmo')
GO
INSERT [dbo].[tutkimuksen_rahoituslahde] ([id], [luotu], [rahoituslahde_avain], [rahoituslahdetarkennus], [rahoituslahdetarkennus_SV], [rahoituslahdetarkennus_EN], [jarjestys_rahoituslahdetarkennus], [rahoituslahde], [rahoituslahde_SV], [rahoituslahde_EN], [jarjestys_rahoituslahde], [ulkopuolisen_rahoituksen_kansainvalisyys], [ulkopuolisen_rahoituksen_kansainvalisyys_SV], [ulkopuolisen_rahoituksen_kansainvalisyys_EN], [jarjestys_ulkopuolisen_rahoituksen_kansainvalisyys], [rahoituslahteen_tyyppi], [rahoituslahteen_tyyppi_SV], [rahoituslahteen_tyyppi_EN], [jarjestys_rahoituslahteen_tyyppi], [rahoituksen_laatu], [rahoituksen_laatu_SV], [rahoituksen_laatu_EN], [jarjestys_rahoituksen_laatu], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (14, CAST(N'2015-02-25' AS Date), N'YM', N'YM', N'MM', N'ME', N'230', N'Ministeriöt', N'Ministerier', N'Ministries', N'120', N'kotimainen', N'inhemsk', N'national', N'200', N'ulkopuolinen rahoitus', N'extern finansiering', N'external financing', N'200', N'muu tutkimusrahoitus', N'annan forskarfinansiering', N'other research funding', N'200', N'E', N'0', N'Työpaja 11.2.2015', N'CSC Jarmo')
GO
INSERT [dbo].[tutkimuksen_rahoituslahde] ([id], [luotu], [rahoituslahde_avain], [rahoituslahdetarkennus], [rahoituslahdetarkennus_SV], [rahoituslahdetarkennus_EN], [jarjestys_rahoituslahdetarkennus], [rahoituslahde], [rahoituslahde_SV], [rahoituslahde_EN], [jarjestys_rahoituslahde], [ulkopuolisen_rahoituksen_kansainvalisyys], [ulkopuolisen_rahoituksen_kansainvalisyys_SV], [ulkopuolisen_rahoituksen_kansainvalisyys_EN], [jarjestys_ulkopuolisen_rahoituksen_kansainvalisyys], [rahoituslahteen_tyyppi], [rahoituslahteen_tyyppi_SV], [rahoituslahteen_tyyppi_EN], [jarjestys_rahoituslahteen_tyyppi], [rahoituksen_laatu], [rahoituksen_laatu_SV], [rahoituksen_laatu_EN], [jarjestys_rahoituksen_laatu], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (15, CAST(N'2015-04-16' AS Date), N'VN', N'VN', N'SR', N'FG', N'231', N'Ministeriöt', N'Ministerier', N'Ministries', N'120', N'kotimainen', N'inhemsk', N'national', N'200', N'ulkopuolinen rahoitus', N'extern finansiering', N'external financing', N'200', N'muu tutkimusrahoitus', N'annan forskarfinansiering', N'other research funding', N'200', N'E', N'0', N'Työpaja 11.2.2015', N'CSC Jarmo')
GO
INSERT [dbo].[tutkimuksen_rahoituslahde] ([id], [luotu], [rahoituslahde_avain], [rahoituslahdetarkennus], [rahoituslahdetarkennus_SV], [rahoituslahdetarkennus_EN], [jarjestys_rahoituslahdetarkennus], [rahoituslahde], [rahoituslahde_SV], [rahoituslahde_EN], [jarjestys_rahoituslahde], [ulkopuolisen_rahoituksen_kansainvalisyys], [ulkopuolisen_rahoituksen_kansainvalisyys_SV], [ulkopuolisen_rahoituksen_kansainvalisyys_EN], [jarjestys_ulkopuolisen_rahoituksen_kansainvalisyys], [rahoituslahteen_tyyppi], [rahoituslahteen_tyyppi_SV], [rahoituslahteen_tyyppi_EN], [jarjestys_rahoituslahteen_tyyppi], [rahoituksen_laatu], [rahoituksen_laatu_SV], [rahoituksen_laatu_EN], [jarjestys_rahoituksen_laatu], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (16, CAST(N'2015-02-25' AS Date), N'KUNNAT', N'Kunnat', N'Kommunerna', N'Municipalities', N'240', N'Kunnat', N'Kommunerna', N'Municipalities', N'240', N'kotimainen', N'inhemsk', N'national', N'200', N'ulkopuolinen rahoitus', N'extern finansiering', N'external financing', N'200', N'muu tutkimusrahoitus', N'annan forskarfinansiering', N'other research funding', N'200', N'E', N'0', N'Työpaja 11.2.2015', N'CSC Jarmo')
GO
INSERT [dbo].[tutkimuksen_rahoituslahde] ([id], [luotu], [rahoituslahde_avain], [rahoituslahdetarkennus], [rahoituslahdetarkennus_SV], [rahoituslahdetarkennus_EN], [jarjestys_rahoituslahdetarkennus], [rahoituslahde], [rahoituslahde_SV], [rahoituslahde_EN], [jarjestys_rahoituslahde], [ulkopuolisen_rahoituksen_kansainvalisyys], [ulkopuolisen_rahoituksen_kansainvalisyys_SV], [ulkopuolisen_rahoituksen_kansainvalisyys_EN], [jarjestys_ulkopuolisen_rahoituksen_kansainvalisyys], [rahoituslahteen_tyyppi], [rahoituslahteen_tyyppi_SV], [rahoituslahteen_tyyppi_EN], [jarjestys_rahoituslahteen_tyyppi], [rahoituksen_laatu], [rahoituksen_laatu_SV], [rahoituksen_laatu_EN], [jarjestys_rahoituksen_laatu], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (17, CAST(N'2015-02-25' AS Date), N'JULK_MUU', N'Muu julkinen rahoitus', N'Annan offentlig finansiering', N'Other public financing', N'250', N'Muu julkinen rahoitus', N'Annan offentlig finansiering', N'Other public financing', N'250', N'kotimainen', N'inhemsk', N'national', N'200', N'ulkopuolinen rahoitus', N'extern finansiering', N'external financing', N'200', N'muu tutkimusrahoitus', N'annan forskarfinansiering', N'other research funding', N'200', N'E', N'0', N'Työpaja 11.2.2015', N'CSC Jarmo')
GO
INSERT [dbo].[tutkimuksen_rahoituslahde] ([id], [luotu], [rahoituslahde_avain], [rahoituslahdetarkennus], [rahoituslahdetarkennus_SV], [rahoituslahdetarkennus_EN], [jarjestys_rahoituslahdetarkennus], [rahoituslahde], [rahoituslahde_SV], [rahoituslahde_EN], [jarjestys_rahoituslahde], [ulkopuolisen_rahoituksen_kansainvalisyys], [ulkopuolisen_rahoituksen_kansainvalisyys_SV], [ulkopuolisen_rahoituksen_kansainvalisyys_EN], [jarjestys_ulkopuolisen_rahoituksen_kansainvalisyys], [rahoituslahteen_tyyppi], [rahoituslahteen_tyyppi_SV], [rahoituslahteen_tyyppi_EN], [jarjestys_rahoituslahteen_tyyppi], [rahoituksen_laatu], [rahoituksen_laatu_SV], [rahoituksen_laatu_EN], [jarjestys_rahoituksen_laatu], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (18, CAST(N'2015-02-25' AS Date), N'RAHASTO_K', N'Kotimaiset rahastot ja säätiöt', N'Inhemska fonder och stiftelser', N'Finnish trusts and foundations', N'260', N'Kotimaiset rahastot ja säätiöt', N'Inhemska fonder och stiftelser', N'Finnish trusts and foundations', N'260', N'kotimainen', N'inhemsk', N'national', N'200', N'ulkopuolinen rahoitus', N'extern finansiering', N'external financing', N'200', N'muu tutkimusrahoitus', N'annan forskarfinansiering', N'other research funding', N'200', N'E', N'0', N'Työpaja 11.2.2015', N'CSC Jarmo')
GO
INSERT [dbo].[tutkimuksen_rahoituslahde] ([id], [luotu], [rahoituslahde_avain], [rahoituslahdetarkennus], [rahoituslahdetarkennus_SV], [rahoituslahdetarkennus_EN], [jarjestys_rahoituslahdetarkennus], [rahoituslahde], [rahoituslahde_SV], [rahoituslahde_EN], [jarjestys_rahoituslahde], [ulkopuolisen_rahoituksen_kansainvalisyys], [ulkopuolisen_rahoituksen_kansainvalisyys_SV], [ulkopuolisen_rahoituksen_kansainvalisyys_EN], [jarjestys_ulkopuolisen_rahoituksen_kansainvalisyys], [rahoituslahteen_tyyppi], [rahoituslahteen_tyyppi_SV], [rahoituslahteen_tyyppi_EN], [jarjestys_rahoituslahteen_tyyppi], [rahoituksen_laatu], [rahoituksen_laatu_SV], [rahoituksen_laatu_EN], [jarjestys_rahoituksen_laatu], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (19, CAST(N'2015-02-25' AS Date), N'YRITYS_K', N'Kotimaiset yritykset', N'Inhemska företag', N'Finnish companies', N'270', N'Kotimaiset yritykset', N'Inhemska företag', N'Finnish companies', N'270', N'kotimainen', N'inhemsk', N'national', N'200', N'ulkopuolinen rahoitus', N'extern finansiering', N'external financing', N'200', N'muu kilpailtu tutkimusrahoitus', N'annan konkurrensutsatt forskarfinansiering', N'other research funding subject to tendering', N'300', N'E', N'0', N'Työpaja 11.2.2015', N'CSC Jarmo')
GO
INSERT [dbo].[tutkimuksen_rahoituslahde] ([id], [luotu], [rahoituslahde_avain], [rahoituslahdetarkennus], [rahoituslahdetarkennus_SV], [rahoituslahdetarkennus_EN], [jarjestys_rahoituslahdetarkennus], [rahoituslahde], [rahoituslahde_SV], [rahoituslahde_EN], [jarjestys_rahoituslahde], [ulkopuolisen_rahoituksen_kansainvalisyys], [ulkopuolisen_rahoituksen_kansainvalisyys_SV], [ulkopuolisen_rahoituksen_kansainvalisyys_EN], [jarjestys_ulkopuolisen_rahoituksen_kansainvalisyys], [rahoituslahteen_tyyppi], [rahoituslahteen_tyyppi_SV], [rahoituslahteen_tyyppi_EN], [jarjestys_rahoituslahteen_tyyppi], [rahoituksen_laatu], [rahoituksen_laatu_SV], [rahoituksen_laatu_EN], [jarjestys_rahoituksen_laatu], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (20, CAST(N'2015-02-25' AS Date), N'YRITYS_U', N'Ulkomaiset yritykset', N'Utländska företag', N'Foreign companies', N'280', N'Ulkomaiset yritykset', N'Utländska företag', N'Foreign companies', N'280', N'ulkomainen', N'utländsk', N'abroad', N'300', N'ulkopuolinen rahoitus', N'extern finansiering', N'external financing', N'200', N'muu kilpailtu tutkimusrahoitus', N'annan konkurrensutsatt forskarfinansiering', N'other research funding subject to tendering', N'300', N'E', N'0', N'Työpaja 11.2.2015', N'CSC Jarmo')
GO
INSERT [dbo].[tutkimuksen_rahoituslahde] ([id], [luotu], [rahoituslahde_avain], [rahoituslahdetarkennus], [rahoituslahdetarkennus_SV], [rahoituslahdetarkennus_EN], [jarjestys_rahoituslahdetarkennus], [rahoituslahde], [rahoituslahde_SV], [rahoituslahde_EN], [jarjestys_rahoituslahde], [ulkopuolisen_rahoituksen_kansainvalisyys], [ulkopuolisen_rahoituksen_kansainvalisyys_SV], [ulkopuolisen_rahoituksen_kansainvalisyys_EN], [jarjestys_ulkopuolisen_rahoituksen_kansainvalisyys], [rahoituslahteen_tyyppi], [rahoituslahteen_tyyppi_SV], [rahoituslahteen_tyyppi_EN], [jarjestys_rahoituslahteen_tyyppi], [rahoituksen_laatu], [rahoituksen_laatu_SV], [rahoituksen_laatu_EN], [jarjestys_rahoituksen_laatu], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (21, CAST(N'2015-02-25' AS Date), N'EU_PUITE', N'EU-puiteohjelmarahoitus', N'EU-ramprogramfinansiering', N'EU framework programme funding', N'292', N'EU-puiteohjelmarahoitus', N'EU-ramprogramfinansiering', N'EU framework programme funding', N'292', N'ulkomainen', N'utländsk', N'abroad', N'300', N'ulkopuolinen rahoitus', N'extern finansiering', N'external financing', N'200', N'kansainvälinen kilpailtu tutkimusrahoitus', N' internationell konkurrensutsatt forskarfinansiering', N'other international research funding subject to tendering', N'400', N'E', N'0', N'Työpaja 11.2.2015', N'CSC Jarmo')
GO
INSERT [dbo].[tutkimuksen_rahoituslahde] ([id], [luotu], [rahoituslahde_avain], [rahoituslahdetarkennus], [rahoituslahdetarkennus_SV], [rahoituslahdetarkennus_EN], [jarjestys_rahoituslahdetarkennus], [rahoituslahde], [rahoituslahde_SV], [rahoituslahde_EN], [jarjestys_rahoituslahde], [ulkopuolisen_rahoituksen_kansainvalisyys], [ulkopuolisen_rahoituksen_kansainvalisyys_SV], [ulkopuolisen_rahoituksen_kansainvalisyys_EN], [jarjestys_ulkopuolisen_rahoituksen_kansainvalisyys], [rahoituslahteen_tyyppi], [rahoituslahteen_tyyppi_SV], [rahoituslahteen_tyyppi_EN], [jarjestys_rahoituslahteen_tyyppi], [rahoituksen_laatu], [rahoituksen_laatu_SV], [rahoituksen_laatu_EN], [jarjestys_rahoituksen_laatu], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (22, CAST(N'2015-02-25' AS Date), N'EU_ALUE', N'Aluekehitysrahoitus', N'Finansiering för regional utveckling', N'ERDF, ESF and other EU financing', N'294', N'EAKR-, ESR- ja muu EU-rahoitus', N'ERUF-, ESF- och annan EU-finansiering', N'ERDF, ESF and other EU financing', N'294', N'ulkomainen', N'utländsk', N'abroad', N'300', N'ulkopuolinen rahoitus', N'extern finansiering', N'external financing', N'200', N'muu tutkimusrahoitus', N'annan forskarfinansiering', N'other research funding', N'200', N'E', N'0', N'Työpaja 11.2.2015', N'CSC Jarmo')
GO
INSERT [dbo].[tutkimuksen_rahoituslahde] ([id], [luotu], [rahoituslahde_avain], [rahoituslahdetarkennus], [rahoituslahdetarkennus_SV], [rahoituslahdetarkennus_EN], [jarjestys_rahoituslahdetarkennus], [rahoituslahde], [rahoituslahde_SV], [rahoituslahde_EN], [jarjestys_rahoituslahde], [ulkopuolisen_rahoituksen_kansainvalisyys], [ulkopuolisen_rahoituksen_kansainvalisyys_SV], [ulkopuolisen_rahoituksen_kansainvalisyys_EN], [jarjestys_ulkopuolisen_rahoituksen_kansainvalisyys], [rahoituslahteen_tyyppi], [rahoituslahteen_tyyppi_SV], [rahoituslahteen_tyyppi_EN], [jarjestys_rahoituslahteen_tyyppi], [rahoituksen_laatu], [rahoituksen_laatu_SV], [rahoituksen_laatu_EN], [jarjestys_rahoituksen_laatu], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (23, CAST(N'2015-02-25' AS Date), N'EU_SOS', N'Sosiaalirahasto', N'Socialfonden', N'ERDF, ESF and other EU financing', N'296', N'EAKR-, ESR- ja muu EU-rahoitus', N'ERUF-, ESF- och annan EU-finansiering', N'ERDF, ESF and other EU financing', N'294', N'ulkomainen', N'utländsk', N'abroad', N'300', N'ulkopuolinen rahoitus', N'extern finansiering', N'external financing', N'200', N'muu tutkimusrahoitus', N'annan forskarfinansiering', N'other research funding', N'200', N'E', N'0', N'Työpaja 11.2.2015', N'CSC Jarmo')
GO
INSERT [dbo].[tutkimuksen_rahoituslahde] ([id], [luotu], [rahoituslahde_avain], [rahoituslahdetarkennus], [rahoituslahdetarkennus_SV], [rahoituslahdetarkennus_EN], [jarjestys_rahoituslahdetarkennus], [rahoituslahde], [rahoituslahde_SV], [rahoituslahde_EN], [jarjestys_rahoituslahde], [ulkopuolisen_rahoituksen_kansainvalisyys], [ulkopuolisen_rahoituksen_kansainvalisyys_SV], [ulkopuolisen_rahoituksen_kansainvalisyys_EN], [jarjestys_ulkopuolisen_rahoituksen_kansainvalisyys], [rahoituslahteen_tyyppi], [rahoituslahteen_tyyppi_SV], [rahoituslahteen_tyyppi_EN], [jarjestys_rahoituslahteen_tyyppi], [rahoituksen_laatu], [rahoituksen_laatu_SV], [rahoituksen_laatu_EN], [jarjestys_rahoituksen_laatu], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (24, CAST(N'2015-02-25' AS Date), N'EU_MUU', N'Muu EU', N'Annan EU', N'ERDF, ESF and other EU financing', N'298', N'EAKR-, ESR- ja muu EU-rahoitus', N'ERUF-, ESF- och annan EU-finansiering', N'ERDF, ESF and other EU financing', N'294', N'ulkomainen', N'utländsk', N'abroad', N'300', N'ulkopuolinen rahoitus', N'extern finansiering', N'external financing', N'200', N'muu tutkimusrahoitus', N'annan forskarfinansiering', N'other research funding', N'200', N'E', N'0', N'Työpaja 11.2.2015', N'CSC Jarmo')
GO
INSERT [dbo].[tutkimuksen_rahoituslahde] ([id], [luotu], [rahoituslahde_avain], [rahoituslahdetarkennus], [rahoituslahdetarkennus_SV], [rahoituslahdetarkennus_EN], [jarjestys_rahoituslahdetarkennus], [rahoituslahde], [rahoituslahde_SV], [rahoituslahde_EN], [jarjestys_rahoituslahde], [ulkopuolisen_rahoituksen_kansainvalisyys], [ulkopuolisen_rahoituksen_kansainvalisyys_SV], [ulkopuolisen_rahoituksen_kansainvalisyys_EN], [jarjestys_ulkopuolisen_rahoituksen_kansainvalisyys], [rahoituslahteen_tyyppi], [rahoituslahteen_tyyppi_SV], [rahoituslahteen_tyyppi_EN], [jarjestys_rahoituslahteen_tyyppi], [rahoituksen_laatu], [rahoituksen_laatu_SV], [rahoituksen_laatu_EN], [jarjestys_rahoituksen_laatu], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (25, CAST(N'2015-04-16' AS Date), N'EU', N'EU yhteensä', N'EU totalt', N'EU total', N'290', N'EU yhteensä', N'EU totalt', N'EU total', N'290', N'ulkomainen', N'utländsk', N'abroad', N'300', N'ulkopuolinen rahoitus', N'extern finansiering', N'external financing', N'200', N'muu tutkimusrahoitus', N'annan forskarfinansiering', N'other research funding', N'200', N'E', N'0', N'Työpaja 11.2.2015', N'CSC Jarmo')
GO
INSERT [dbo].[tutkimuksen_rahoituslahde] ([id], [luotu], [rahoituslahde_avain], [rahoituslahdetarkennus], [rahoituslahdetarkennus_SV], [rahoituslahdetarkennus_EN], [jarjestys_rahoituslahdetarkennus], [rahoituslahde], [rahoituslahde_SV], [rahoituslahde_EN], [jarjestys_rahoituslahde], [ulkopuolisen_rahoituksen_kansainvalisyys], [ulkopuolisen_rahoituksen_kansainvalisyys_SV], [ulkopuolisen_rahoituksen_kansainvalisyys_EN], [jarjestys_ulkopuolisen_rahoituksen_kansainvalisyys], [rahoituslahteen_tyyppi], [rahoituslahteen_tyyppi_SV], [rahoituslahteen_tyyppi_EN], [jarjestys_rahoituslahteen_tyyppi], [rahoituksen_laatu], [rahoituksen_laatu_SV], [rahoituksen_laatu_EN], [jarjestys_rahoituksen_laatu], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (26, CAST(N'2015-02-25' AS Date), N'RAHASTO_U', N'Ulkomaiset rahastot ja säätiöt', N'Utländska fonder och stiftelser', N'Foreign trusts and foundations', N'300', N'Ulkomaiset rahastot ja säätiöt', N'Utländska fonder och stiftelser', N'Foreign trusts and foundations', N'300', N'ulkomainen', N'utländsk', N'abroad', N'300', N'ulkopuolinen rahoitus', N'extern finansiering', N'external financing', N'200', N'kansainvälinen kilpailtu tutkimusrahoitus', N' internationell konkurrensutsatt forskarfinansiering', N'other international research funding subject to tendering', N'400', N'E', N'0', N'Työpaja 11.2.2015', N'CSC Jarmo')
GO
INSERT [dbo].[tutkimuksen_rahoituslahde] ([id], [luotu], [rahoituslahde_avain], [rahoituslahdetarkennus], [rahoituslahdetarkennus_SV], [rahoituslahdetarkennus_EN], [jarjestys_rahoituslahdetarkennus], [rahoituslahde], [rahoituslahde_SV], [rahoituslahde_EN], [jarjestys_rahoituslahde], [ulkopuolisen_rahoituksen_kansainvalisyys], [ulkopuolisen_rahoituksen_kansainvalisyys_SV], [ulkopuolisen_rahoituksen_kansainvalisyys_EN], [jarjestys_ulkopuolisen_rahoituksen_kansainvalisyys], [rahoituslahteen_tyyppi], [rahoituslahteen_tyyppi_SV], [rahoituslahteen_tyyppi_EN], [jarjestys_rahoituslahteen_tyyppi], [rahoituksen_laatu], [rahoituksen_laatu_SV], [rahoituksen_laatu_EN], [jarjestys_rahoituksen_laatu], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (27, CAST(N'2015-02-25' AS Date), N'JARJESTO_U', N'Kansainväliset järjestöt', N'Internationella organisationer', N'International organisations', N'310', N'Kansainväliset järjestöt', N'Internationella organisationer', N'International organisations', N'310', N'ulkomainen', N'utländsk', N'abroad', N'300', N'ulkopuolinen rahoitus', N'extern finansiering', N'external financing', N'200', N'kansainvälinen kilpailtu tutkimusrahoitus', N' internationell konkurrensutsatt forskarfinansiering', N'other international research funding subject to tendering', N'400', N'E', N'0', N'Työpaja 11.2.2015', N'CSC Jarmo')
GO
INSERT [dbo].[tutkimuksen_rahoituslahde] ([id], [luotu], [rahoituslahde_avain], [rahoituslahdetarkennus], [rahoituslahdetarkennus_SV], [rahoituslahdetarkennus_EN], [jarjestys_rahoituslahdetarkennus], [rahoituslahde], [rahoituslahde_SV], [rahoituslahde_EN], [jarjestys_rahoituslahde], [ulkopuolisen_rahoituksen_kansainvalisyys], [ulkopuolisen_rahoituksen_kansainvalisyys_SV], [ulkopuolisen_rahoituksen_kansainvalisyys_EN], [jarjestys_ulkopuolisen_rahoituksen_kansainvalisyys], [rahoituslahteen_tyyppi], [rahoituslahteen_tyyppi_SV], [rahoituslahteen_tyyppi_EN], [jarjestys_rahoituslahteen_tyyppi], [rahoituksen_laatu], [rahoituksen_laatu_SV], [rahoituksen_laatu_EN], [jarjestys_rahoituksen_laatu], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (28, CAST(N'2015-02-25' AS Date), N'MUU_U', N'Muu ulkomainen rahoitus', N'Annan utländsk finansiering', N'Other foreign financing', N'320', N'Muu ulkomainen rahoitus', N'Annan utländsk finansiering', N'Other foreign financing', N'320', N'ulkomainen', N'utländsk', N'abroad', N'300', N'ulkopuolinen rahoitus', N'extern finansiering', N'external financing', N'200', N'kansainvälinen kilpailtu tutkimusrahoitus', N' internationell konkurrensutsatt forskarfinansiering', N'other international research funding subject to tendering', N'400', N'E', N'0', N'Työpaja 11.2.2015', N'CSC Jarmo')
GO
INSERT [dbo].[tutkimuksen_rahoituslahde] ([id], [luotu], [rahoituslahde_avain], [rahoituslahdetarkennus], [rahoituslahdetarkennus_SV], [rahoituslahdetarkennus_EN], [jarjestys_rahoituslahdetarkennus], [rahoituslahde], [rahoituslahde_SV], [rahoituslahde_EN], [jarjestys_rahoituslahde], [ulkopuolisen_rahoituksen_kansainvalisyys], [ulkopuolisen_rahoituksen_kansainvalisyys_SV], [ulkopuolisen_rahoituksen_kansainvalisyys_EN], [jarjestys_ulkopuolisen_rahoituksen_kansainvalisyys], [rahoituslahteen_tyyppi], [rahoituslahteen_tyyppi_SV], [rahoituslahteen_tyyppi_EN], [jarjestys_rahoituslahteen_tyyppi], [rahoituksen_laatu], [rahoituksen_laatu_SV], [rahoituksen_laatu_EN], [jarjestys_rahoituksen_laatu], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (29, CAST(N'2015-02-25' AS Date), N'KOULU', N'Korkeakoulun omat varat', N'Högskolans egna medel', N'Self-financing of the institution of higher education', N'330', N'Korkeakoulun omat varat', N'Högskolans egna medel', N'Self-financing of the institution of higher education', N'330', N'korkeakoulun omat varat', N'högskolans egna medel', N'own funds of the institution of higher education', N'400', N'korkeakoulun omat varat', N'högskolans egna medel', N'own funds of the institution of higher education', N'300', N'korkeakoulun omat varat', N'högskolans egna medel', N'own funds of the institution of higher education', N'500', N'E', N'0', N'Työpaja 27.8.2015', N'CSC Jarmo')
GO
INSERT [dbo].[tutkimuksen_rahoituslahde] ([id], [luotu], [rahoituslahde_avain], [rahoituslahdetarkennus], [rahoituslahdetarkennus_SV], [rahoituslahdetarkennus_EN], [jarjestys_rahoituslahdetarkennus], [rahoituslahde], [rahoituslahde_SV], [rahoituslahde_EN], [jarjestys_rahoituslahde], [ulkopuolisen_rahoituksen_kansainvalisyys], [ulkopuolisen_rahoituksen_kansainvalisyys_SV], [ulkopuolisen_rahoituksen_kansainvalisyys_EN], [jarjestys_ulkopuolisen_rahoituksen_kansainvalisyys], [rahoituslahteen_tyyppi], [rahoituslahteen_tyyppi_SV], [rahoituslahteen_tyyppi_EN], [jarjestys_rahoituslahteen_tyyppi], [rahoituksen_laatu], [rahoituksen_laatu_SV], [rahoituksen_laatu_EN], [jarjestys_rahoituksen_laatu], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (30, CAST(N'2015-08-27' AS Date), N'ORAHAS', N'Oma rahoitus', N'Egen finansiering', N'Self-financing', N'331', N'Oma rahoitus', N'Egen finansiering', N'Self-financing', N'331', N'oma rahoitus', N'egen finansiering', N'self-financing', N'410', N'oma rahoitus', N'egen finansiering', N'self-financing', N'310', N'oma rahoitus', N'egen finansiering', N'self-financing', N'510', N'E', N'0', N'Työpaja 27.8.2015', N'CSC Jarmo')
GO
INSERT [dbo].[tutkimuksen_rahoituslahde] ([id], [luotu], [rahoituslahde_avain], [rahoituslahdetarkennus], [rahoituslahdetarkennus_SV], [rahoituslahdetarkennus_EN], [jarjestys_rahoituslahdetarkennus], [rahoituslahde], [rahoituslahde_SV], [rahoituslahde_EN], [jarjestys_rahoituslahde], [ulkopuolisen_rahoituksen_kansainvalisyys], [ulkopuolisen_rahoituksen_kansainvalisyys_SV], [ulkopuolisen_rahoituksen_kansainvalisyys_EN], [jarjestys_ulkopuolisen_rahoituksen_kansainvalisyys], [rahoituslahteen_tyyppi], [rahoituslahteen_tyyppi_SV], [rahoituslahteen_tyyppi_EN], [jarjestys_rahoituslahteen_tyyppi], [rahoituksen_laatu], [rahoituksen_laatu_SV], [rahoituksen_laatu_EN], [jarjestys_rahoituksen_laatu], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (31, CAST(N'2015-04-27' AS Date), N'GRAD', N'Tutkijankoulutusohjelmat', N'Forskarutbildningsprogram', N'Postgraduate programmes', N'117', N'Tutkijankoulutusohjelmat', N'Forskarutbildningsprogram', N'Postgraduate programmes', N'117', N'kotimainen', N'inhemsk', N'national', N'200', N'ulkopuolinen rahoitus', N'extern finansiering', N'external financing', N'200', N'muu kilpailtu tutkimusrahoitus', N'annan konkurrensutsatt forskarfinansiering', N'other research funding subject to tendering', N'300', N'E', N'0', N'Työpaja 27.4.2015', N'CSC Jarmo')
GO
INSERT [dbo].[tutkimuksen_rahoituslahde] ([id], [luotu], [rahoituslahde_avain], [rahoituslahdetarkennus], [rahoituslahdetarkennus_SV], [rahoituslahdetarkennus_EN], [jarjestys_rahoituslahdetarkennus], [rahoituslahde], [rahoituslahde_SV], [rahoituslahde_EN], [jarjestys_rahoituslahde], [ulkopuolisen_rahoituksen_kansainvalisyys], [ulkopuolisen_rahoituksen_kansainvalisyys_SV], [ulkopuolisen_rahoituksen_kansainvalisyys_EN], [jarjestys_ulkopuolisen_rahoituksen_kansainvalisyys], [rahoituslahteen_tyyppi], [rahoituslahteen_tyyppi_SV], [rahoituslahteen_tyyppi_EN], [jarjestys_rahoituslahteen_tyyppi], [rahoituksen_laatu], [rahoituksen_laatu_SV], [rahoituksen_laatu_EN], [jarjestys_rahoituksen_laatu], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (32, CAST(N'2017-09-28' AS Date), N'RKORK', N'Kotimaiset korkeakoulut', N'Inhemska högskolor', N'Finnish higher education institution', N'265', N'Kotimaiset korkeakoulut', N'Inhemska högskolor', N'Finnish higher education institution', N'265', N'kotimainen', N'inhemsk', N'national', N'200', N'ulkopuolinen rahoitus', N'extern finansiering', N'external financing', N'200', N'muu tutkimusrahoitus', N'annan forskarfinansiering', N'other research funding', N'200', N'E', N'0', N'Pekka 11.9.2017', N'CSC Anssi')
GO
USE [ANTERO]