USE [VipunenTK_lisatiedot]
GO
ALTER TABLE [dbo].[koulutuslaji3] DROP CONSTRAINT IF EXISTS [DF__koulutusl__tieto__345F90D4]
GO
ALTER TABLE [dbo].[koulutuslaji2] DROP CONSTRAINT IF EXISTS [DF__koulutusl__tieto__336B6C9B]
GO
ALTER TABLE [dbo].[koulutuslaji_okm] DROP CONSTRAINT IF EXISTS [DF__koulutuslaji_okm__tietolahde]
GO
ALTER TABLE [dbo].[koulutuslaji] DROP CONSTRAINT IF EXISTS [DF__koulutuslaji__tietolahde]
GO
ALTER TABLE [dbo].[koulutuslaji] DROP CONSTRAINT IF EXISTS [DF__koulutuslaji__paattyy]
GO
ALTER TABLE [dbo].[koulutuslaji] DROP CONSTRAINT IF EXISTS [DF__koulutuslaji__alkaa]
GO
ALTER TABLE [dbo].[koulutuslaji3] DROP CONSTRAINT IF EXISTS [DF__koulutusl__tieto__068DD92C]
GO
ALTER TABLE [dbo].[koulutuslaji2] DROP CONSTRAINT IF EXISTS [DF__koulutusl__tieto__0599B4F3]
GO
/****** Object:  Table [dbo].[koulutuslaji3]    Script Date: 16.1.2020 16:36:38 ******/
DROP TABLE [dbo].[koulutuslaji3]
GO
/****** Object:  Table [dbo].[koulutuslaji2]    Script Date: 16.1.2020 16:36:38 ******/
DROP TABLE [dbo].[koulutuslaji2]
GO
/****** Object:  Table [dbo].[koulutuslaji_okm]    Script Date: 16.1.2020 16:36:38 ******/
DROP TABLE [dbo].[koulutuslaji_okm]
GO
/****** Object:  Table [dbo].[koulutuslaji]    Script Date: 16.1.2020 16:36:38 ******/
DROP TABLE [dbo].[koulutuslaji]
GO
/****** Object:  Table [dbo].[koulutuslaji]    Script Date: 16.1.2020 16:36:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[koulutuslaji](
	[id] [int] NOT NULL,
	[luotu] [date] NULL,
	[alkaa] [date] NULL,
	[paattyy] [date] NULL,
	[koulutuslaji_koodi] [nvarchar](10) NULL,
	[koulutuslaji] [nvarchar](150) NULL,
	[koulutuslaji_SV] [nvarchar](150) NULL,
	[koulutuslaji_EN] [nvarchar](150) NULL,
	[jarjestys] [nvarchar](50) NULL,
	[virhetilanne] [nchar](1) NULL,
	[poistettu] [nchar](1) NULL,
	[tietolahde] [nvarchar](50) NULL,
	[kommentti] [nvarchar](250) NULL
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[koulutuslaji_okm]    Script Date: 16.1.2020 16:36:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[koulutuslaji_okm](
	[id] [int] NOT NULL,
	[luotu] [date] NULL,
	[koulutuslaji_okm_avain] [nvarchar](10) NULL,
	[koulutuslaji_okm] [nvarchar](100) NULL,
	[koulutuslaji_okm_SV] [nvarchar](100) NULL,
	[koulutuslaji_okm_EN] [nvarchar](100) NULL,
	[koulutuslaji_okm2] [nvarchar](100) NULL,
	[koulutuslaji_okm2_SV] [nvarchar](100) NULL,
	[koulutuslaji_okm2_EN] [nvarchar](100) NULL,
	[jarjestys] [nvarchar](50) NULL,
	[jarjestys2] [nvarchar](50) NULL,
	[virhetilanne] [nchar](1) NULL,
	[poistettu] [nchar](1) NULL,
	[tietolahde] [nvarchar](50) NULL,
	[kommentti] [nvarchar](250) NULL
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[koulutuslaji2]    Script Date: 16.1.2020 16:36:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[koulutuslaji2](
	[id] [int] NOT NULL,
	[luotu] [date] NULL,
	[koulutuslaji2_koodi] [nvarchar](10) NULL,
	[koulutuslaji2] [nvarchar](250) NULL,
	[koulutuslaji2_SV] [nvarchar](250) NULL,
	[koulutuslaji2_EN] [nvarchar](250) NULL,
	[jarjestys_koulutuslaji2] [nvarchar](50) NULL,
	[jarjestamistapa] [nvarchar](250) NULL,
	[jarjestamistapa_SV] [nvarchar](250) NULL,
	[jarjestamistapa_EN] [nvarchar](250) NULL,
	[jarjestys_jarjestamistapa] [nvarchar](50) NULL,
	[jarjestamismuoto] [nvarchar](250) NULL,
	[jarjestamismuoto_SV] [nvarchar](250) NULL,
	[jarjestamismuoto_EN] [nvarchar](250) NULL,
	[jarjestys_jarjestamismuoto] [nvarchar](50) NULL,
	[tutkintotyyppi] [nvarchar](250) NULL,
	[tutkintotyyppi_SV] [nvarchar](250) NULL,
	[tutkintotyyppi_EN] [nvarchar](250) NULL,
	[jarjestys_tutkintotyyppi] [nvarchar](50) NULL,
	[virhetilanne] [nchar](1) NULL,
	[poistettu] [nchar](1) NULL,
	[tietolahde] [nvarchar](50) NULL,
	[kommentti] [nvarchar](250) NULL
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[koulutuslaji3]    Script Date: 16.1.2020 16:36:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[koulutuslaji3](
	[id] [int] NOT NULL,
	[luotu] [date] NULL,
	[koulutuslaji3_koodi] [nvarchar](10) NULL,
	[koulutuslaji3] [nvarchar](250) NULL,
	[koulutuslaji3_SV] [nvarchar](250) NULL,
	[koulutuslaji3_EN] [nvarchar](250) NULL,
	[jarjestys_koulutuslaji3] [nvarchar](50) NULL,
	[jarjestamistapa] [nvarchar](250) NULL,
	[jarjestamistapa_SV] [nvarchar](250) NULL,
	[jarjestamistapa_EN] [nvarchar](250) NULL,
	[jarjestys_jarjestamistapa] [nvarchar](50) NULL,
	[jarjestamismuoto] [nvarchar](250) NULL,
	[jarjestamismuoto_SV] [nvarchar](250) NULL,
	[jarjestamismuoto_EN] [nvarchar](250) NULL,
	[jarjestys_jarjestamismuoto] [nvarchar](50) NULL,
	[tutkintotyyppi] [nvarchar](250) NULL,
	[tutkintotyyppi_SV] [nvarchar](250) NULL,
	[tutkintotyyppi_EN] [nvarchar](250) NULL,
	[jarjestys_tutkintotyyppi] [nvarchar](50) NULL,
	[virhetilanne] [nchar](1) NULL,
	[poistettu] [nchar](1) NULL,
	[tietolahde] [nvarchar](50) NULL,
	[kommentti] [nvarchar](250) NULL
) ON [PRIMARY]

GO
INSERT [dbo].[koulutuslaji] ([id], [luotu], [alkaa], [paattyy], [koulutuslaji_koodi], [koulutuslaji], [koulutuslaji_SV], [koulutuslaji_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (-2, CAST(N'2014-02-03' AS Date), CAST(N'1900-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'-2', N'Virhetilanne', N'Feltillstånd', N'Error occurred', N'99999', N'K', N'0', N'Manuaalinen', N'CSC Lauri')
GO
INSERT [dbo].[koulutuslaji] ([id], [luotu], [alkaa], [paattyy], [koulutuslaji_koodi], [koulutuslaji], [koulutuslaji_SV], [koulutuslaji_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (-1, CAST(N'2014-02-03' AS Date), CAST(N'1900-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'-1', N'Tuntematon', N'Information saknas', N'Missing data', N'99998', N'K', N'0', N'Manuaalinen', N'CSC Lauri')
GO
INSERT [dbo].[koulutuslaji] ([id], [luotu], [alkaa], [paattyy], [koulutuslaji_koodi], [koulutuslaji], [koulutuslaji_SV], [koulutuslaji_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (190, CAST(N'2014-02-03' AS Date), CAST(N'1900-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'21', N'Lukiokoulutus, nuorten OPS (oppilaitoksen määrittelemä tieto)', N'Gymnasieutbildning, LP för unga (uppgift som läroanstalten fastställt)', N'Upper secondary general education, curriculum for young people (data provided by the educational institution)', N'21', N'E', N'0', N'Tilastokeskus', N'CSC Lauri')
GO
INSERT [dbo].[koulutuslaji] ([id], [luotu], [alkaa], [paattyy], [koulutuslaji_koodi], [koulutuslaji], [koulutuslaji_SV], [koulutuslaji_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (191, CAST(N'2014-02-03' AS Date), CAST(N'1900-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'22', N'Lukiokoulutus, aikuisten OPS (oppilaitoksen määrittelemä tieto)', N'Gymnasieutbildning, LP för vuxna (uppgift som läroanstalten fastställt)', N'Upper secondary general education, curriculum for adults (data provided by the educational institution)', N'22', N'E', N'0', N'Tilastokeskus', N'CSC Lauri')
GO
INSERT [dbo].[koulutuslaji] ([id], [luotu], [alkaa], [paattyy], [koulutuslaji_koodi], [koulutuslaji], [koulutuslaji_SV], [koulutuslaji_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (192, CAST(N'2014-02-03' AS Date), CAST(N'1900-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'31', N'OPS-perusteinen ammatillinen peruskoulutus (ei oppisopimuskoulutus)', N'LP-baserad grundläggande yrkesutbildning (ej läroavtalsutbildning)', N'Curriculum-based vocational upper secondary education and training (not apprenticeship training)', N'310', N'E', N'0', N'Tilastokeskus', N'CSC Lauri')
GO
INSERT [dbo].[koulutuslaji] ([id], [luotu], [alkaa], [paattyy], [koulutuslaji_koodi], [koulutuslaji], [koulutuslaji_SV], [koulutuslaji_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (193, CAST(N'2014-02-03' AS Date), CAST(N'1900-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'32', N'Näyttötutkintoon valmistava koulutus: perustutkinnot (ei oppisop. koul.)', N'Förberedande utbildning för fristående examen: grundexamina (ej läroavtalsutb.)', N'Preparatory training for competence-based qualifications: vocational upper secondary qualifications (not apprenticeship training)', N'320', N'E', N'0', N'Tilastokeskus', N'CSC Lauri')
GO
INSERT [dbo].[koulutuslaji] ([id], [luotu], [alkaa], [paattyy], [koulutuslaji_koodi], [koulutuslaji], [koulutuslaji_SV], [koulutuslaji_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (194, CAST(N'2014-02-03' AS Date), CAST(N'1900-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'33', N'Näyttötutkintoon valmistava koulutus: ammattitutkinnot (ei oppisop.koul.)', N'Förberedande utbildning för fristående examen: yrkesexamina (ej läroavtalsutb.)', N'Preparatory training for competence-based qualifications: further vocational qualifications (not apprenticeship training)', N'330', N'E', N'0', N'Tilastokeskus', N'CSC Lauri')
GO
INSERT [dbo].[koulutuslaji] ([id], [luotu], [alkaa], [paattyy], [koulutuslaji_koodi], [koulutuslaji], [koulutuslaji_SV], [koulutuslaji_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (195, CAST(N'2014-02-03' AS Date), CAST(N'1900-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'34', N'Näyttötutkintoon valmistava koulutus: erikoisammattitutkinnot (ei oppisop.k.)', N'Förberedande utbildning för fristående examen: specialyrkesexamina (ej läroavtalsutb.)', N'Preparatory training for competence-based qualifications: specialist vocational qualifications (not apprenticeship training)', N'340', N'E', N'0', N'Tilastokeskus', N'CSC Lauri')
GO
INSERT [dbo].[koulutuslaji] ([id], [luotu], [alkaa], [paattyy], [koulutuslaji_koodi], [koulutuslaji], [koulutuslaji_SV], [koulutuslaji_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (196, CAST(N'2014-02-03' AS Date), CAST(N'1900-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'35', N'OPS-perusteinen ammatillinen peruskoulutus (oppisopimuskoulutus)', N'LP-baserad grundläggande yrkesutbildning (läroavtalsutbildning)', N'Curriculum-based vocational upper secondary education and training (apprenticeship training)', N'350', N'E', N'0', N'Tilastokeskus', N'CSC Lauri')
GO
INSERT [dbo].[koulutuslaji] ([id], [luotu], [alkaa], [paattyy], [koulutuslaji_koodi], [koulutuslaji], [koulutuslaji_SV], [koulutuslaji_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (197, CAST(N'2014-02-03' AS Date), CAST(N'1900-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'36', N'Näyttötutkintoon valmistava koulutus: perustutkinnot (oppisopimuskoulutus)', N'Förberedande utbildning för fristående examen: grundexamina (läroavtalsutbildning)', N'Preparatory training for competence-based qualifications: vocational qualifications (apprenticeship training)', N'360', N'E', N'0', N'Tilastokeskus', N'CSC Lauri')
GO
INSERT [dbo].[koulutuslaji] ([id], [luotu], [alkaa], [paattyy], [koulutuslaji_koodi], [koulutuslaji], [koulutuslaji_SV], [koulutuslaji_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (198, CAST(N'2014-02-03' AS Date), CAST(N'1900-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'37', N'Näyttötutkintoon valmistava koulutus: ammattitutkinnot (oppisopimuskoulutus)', N'Förberedande utbildning för fristående examen: yrkesexamina (läroavtalsutbildning)', N'Preparatory training for competence-based qualifications: further vocational qualifications (apprenticeship training)', N'370', N'E', N'0', N'Tilastokeskus', N'CSC Lauri')
GO
INSERT [dbo].[koulutuslaji] ([id], [luotu], [alkaa], [paattyy], [koulutuslaji_koodi], [koulutuslaji], [koulutuslaji_SV], [koulutuslaji_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (199, CAST(N'2014-02-03' AS Date), CAST(N'1900-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'38', N'Näyttötutkintoon valmistava koulutus: erikoisammattitutkinnot (oppisop.koul.)', N'Förberedande utbildning för fristående examen: specialyrkesexamina (läroavtalsutb.)', N'Preparatory training for competence-based qualifications: specialist vocational qualifications (apprenticeship training)', N'380', N'E', N'0', N'Tilastokeskus', N'CSC Lauri')
GO
INSERT [dbo].[koulutuslaji] ([id], [luotu], [alkaa], [paattyy], [koulutuslaji_koodi], [koulutuslaji], [koulutuslaji_SV], [koulutuslaji_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (200, CAST(N'2014-02-03' AS Date), CAST(N'1900-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'41', N'Ammattikorkeakoulututkinto, päivätoteutus', N'Yrkeshögskoleexamen, dagstudier', N'UAS degree, daytime studies', N'410', N'E', N'0', N'Tilastokeskus', N'CSC Lauri')
GO
INSERT [dbo].[koulutuslaji] ([id], [luotu], [alkaa], [paattyy], [koulutuslaji_koodi], [koulutuslaji], [koulutuslaji_SV], [koulutuslaji_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (201, CAST(N'2014-02-03' AS Date), CAST(N'1900-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'42', N'Ammattikorkeakoulututkinto, monimuotototeutus', N'Yrkeshögskoleexamen, flerformsstudier', N'UAS degree, multiform studies', N'420', N'E', N'0', N'Tilastokeskus', N'CSC Lauri')
GO
INSERT [dbo].[koulutuslaji] ([id], [luotu], [alkaa], [paattyy], [koulutuslaji_koodi], [koulutuslaji], [koulutuslaji_SV], [koulutuslaji_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (202, CAST(N'2014-02-03' AS Date), CAST(N'1900-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'46', N'Ylempään AMK-tutkintoon tähtäävä koulutus', N'Utbildning för högre YH-examen', N'Education leading to a UAS Master''s degree', N'460', N'E', N'0', N'Tilastokeskus', N'CSC Lauri')
GO
INSERT [dbo].[koulutuslaji] ([id], [luotu], [alkaa], [paattyy], [koulutuslaji_koodi], [koulutuslaji], [koulutuslaji_SV], [koulutuslaji_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (203, CAST(N'2014-02-03' AS Date), CAST(N'1900-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'51', N'Alempaan ja ylempään korkeakoulututkintoon tähtäävä koulutus', N'Utbildning för lägre och högre högskoleexamen', N'Education leading to a Bachelor''s and Master’s degree', N'510', N'E', N'0', N'Tilastokeskus', N'CSC Lauri')
GO
INSERT [dbo].[koulutuslaji] ([id], [luotu], [alkaa], [paattyy], [koulutuslaji_koodi], [koulutuslaji], [koulutuslaji_SV], [koulutuslaji_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (204, CAST(N'2014-02-03' AS Date), CAST(N'1900-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'52', N'Lisensiaatinkoulutus, tohtorinkoulutus ja lääkärien erik.koul.', N'Licentiatutbildning, doktorsutbildning och specialiseringsutb. för läkare', N'Licentiate education, postgraduate education and specialist degrees in medicine', N'520', N'E', N'0', N'Tilastokeskus', N'CSC Lauri')
GO
INSERT [dbo].[koulutuslaji] ([id], [luotu], [alkaa], [paattyy], [koulutuslaji_koodi], [koulutuslaji], [koulutuslaji_SV], [koulutuslaji_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (205, CAST(N'2020-01-16' AS Date), CAST(N'1900-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'61', N'Ammatilliset perustutkinnot (ei oppisopimuskoulutus)', N'Yrkesinriktade grundexamina (ej läroavtalsutbildning)', N'Vocational qualifications (not apprenticeship training)', N'301', N'E', N'0', N'Tilastokeskus', N'CSC Juha')
GO
INSERT [dbo].[koulutuslaji] ([id], [luotu], [alkaa], [paattyy], [koulutuslaji_koodi], [koulutuslaji], [koulutuslaji_SV], [koulutuslaji_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (206, CAST(N'2020-01-16' AS Date), CAST(N'1900-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'62', N'Ammattitutkinnot (ei oppisopimuskoulutus)', N'Yrkesexamina (ej läroavtalsutbildning)', N'Further vocational qualifications (not apprenticeship training)', N'302', N'E', N'0', N'Tilastokeskus', N'CSC Juha')
GO
INSERT [dbo].[koulutuslaji] ([id], [luotu], [alkaa], [paattyy], [koulutuslaji_koodi], [koulutuslaji], [koulutuslaji_SV], [koulutuslaji_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (207, CAST(N'2020-01-16' AS Date), CAST(N'1900-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'63', N'Erikoisammattitutkinnot (ei oppisopimuskoulutus)', N'Specialyrkesexamina (ej läroavtalsutbildning)', N'Specialist vocational qualifications (not apprenticeship training)', N'303', N'E', N'0', N'Tilastokeskus', N'CSC Juha')
GO
INSERT [dbo].[koulutuslaji] ([id], [luotu], [alkaa], [paattyy], [koulutuslaji_koodi], [koulutuslaji], [koulutuslaji_SV], [koulutuslaji_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (208, CAST(N'2020-01-16' AS Date), CAST(N'1900-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'64', N'Ammatilliset perustutkinnot (oppisopimuskoulutus)', N'Yrkesinriktade grundexamina (läroavtalsutbildning)', N'Vocational qualifications (apprenticeship training)', N'344', N'E', N'0', N'Tilastokeskus', N'CSC Juha')
GO
INSERT [dbo].[koulutuslaji] ([id], [luotu], [alkaa], [paattyy], [koulutuslaji_koodi], [koulutuslaji], [koulutuslaji_SV], [koulutuslaji_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (209, CAST(N'2020-01-16' AS Date), CAST(N'1900-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'65', N'Ammattitutkinnot (oppisopimuskoulutus)', N'Yrkesexamina (läroavtalsutbildning)', N'Further vocational qualifications (apprenticeship training)', N'345', N'E', N'0', N'Tilastokeskus', N'CSC Juha')
GO
INSERT [dbo].[koulutuslaji] ([id], [luotu], [alkaa], [paattyy], [koulutuslaji_koodi], [koulutuslaji], [koulutuslaji_SV], [koulutuslaji_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (210, CAST(N'2020-01-16' AS Date), CAST(N'1900-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'66', N'Erikoisammattitutkinnot (oppisopimuskoulutus)', N'Specialyrkesexamina (läroavtalsutbildning)', N'Specialist vocational qualifications (apprenticeship training)', N'346', N'E', N'0', N'Tilastokeskus', N'CSC Juha')
GO
INSERT [dbo].[koulutuslaji_okm] ([id], [luotu], [koulutuslaji_okm_avain], [koulutuslaji_okm], [koulutuslaji_okm_SV], [koulutuslaji_okm_EN], [koulutuslaji_okm2], [koulutuslaji_okm2_SV], [koulutuslaji_okm2_EN], [jarjestys], [jarjestys2], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (-2, CAST(N'2015-05-13' AS Date), N'-2', N'Virhetilanne', N'Feltillstånd', N'Error occurred', N'Virhetilanne', N'Feltillstånd', N'Error occurred', N'99', N'99', N'K', N'0', N'CSC', N'CSC Lasse')
GO
INSERT [dbo].[koulutuslaji_okm] ([id], [luotu], [koulutuslaji_okm_avain], [koulutuslaji_okm], [koulutuslaji_okm_SV], [koulutuslaji_okm_EN], [koulutuslaji_okm2], [koulutuslaji_okm2_SV], [koulutuslaji_okm2_EN], [jarjestys], [jarjestys2], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (-1, CAST(N'2015-05-13' AS Date), N'-1', N'Tuntematon', N'Information saknas', N'Missing data', N'Tuntematon', N'Information saknas', N'Missing data', N'98', N'98', N'K', N'0', N'CSC', N'CSC Lasse')
GO
INSERT [dbo].[koulutuslaji_okm] ([id], [luotu], [koulutuslaji_okm_avain], [koulutuslaji_okm], [koulutuslaji_okm_SV], [koulutuslaji_okm_EN], [koulutuslaji_okm2], [koulutuslaji_okm2_SV], [koulutuslaji_okm2_EN], [jarjestys], [jarjestys2], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (1, CAST(N'2015-05-13' AS Date), N'1', N'Esiopetus', N'Förskoleundervisning', N'Pre-primary education', N'Esiopetus', N'Förskoleundervisning', N'Pre-primary education', N'01', N'01', N'K', N'0', N'CSC', N'CSC Lasse')
GO
INSERT [dbo].[koulutuslaji_okm] ([id], [luotu], [koulutuslaji_okm_avain], [koulutuslaji_okm], [koulutuslaji_okm_SV], [koulutuslaji_okm_EN], [koulutuslaji_okm2], [koulutuslaji_okm2_SV], [koulutuslaji_okm2_EN], [jarjestys], [jarjestys2], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (2, CAST(N'2015-05-13' AS Date), N'2', N'Perusopetus', N'Grundläggande utbildning', N'Basic education', N'Perusopetus', N'Grundläggande utbildning', N'Basic education', N'02', N'02', N'K', N'0', N'CSC', N'CSC Lasse')
GO
INSERT [dbo].[koulutuslaji_okm] ([id], [luotu], [koulutuslaji_okm_avain], [koulutuslaji_okm], [koulutuslaji_okm_SV], [koulutuslaji_okm_EN], [koulutuslaji_okm2], [koulutuslaji_okm2_SV], [koulutuslaji_okm2_EN], [jarjestys], [jarjestys2], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (3, CAST(N'2015-05-13' AS Date), N'3', N'Lukiokoulutus (nuorten opetussuunnitelma)', N'Gymnasieutbildning (läroplan för unga)', N'General upper secondary education (curriculum for young people)', N'Lukiokoulutus (nuorten opetussuunnitelma)', N'Gymnasieutbildning (läroplan för unga)', N'General upper secondary education (curriculum for young people)', N'03', N'03', N'K', N'0', N'CSC', N'CSC Lasse')
GO
INSERT [dbo].[koulutuslaji_okm] ([id], [luotu], [koulutuslaji_okm_avain], [koulutuslaji_okm], [koulutuslaji_okm_SV], [koulutuslaji_okm_EN], [koulutuslaji_okm2], [koulutuslaji_okm2_SV], [koulutuslaji_okm2_EN], [jarjestys], [jarjestys2], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (4, CAST(N'2015-05-13' AS Date), N'4', N'Lukiokoulutus (aikuisten opetussuunnitelma)', N'Gymnasieutbildning (läroplan för vuxna)', N'General upper secondary general education (curriculum for adults)', N'Lukiokoulutus (aikuisten opetussuunnitelma)', N'Gymnasieutbildning (läroplan för vuxna)', N'General upper secondary general education (curriculum for adults)', N'04', N'04', N'K', N'0', N'CSC', N'CSC Lasse')
GO
INSERT [dbo].[koulutuslaji_okm] ([id], [luotu], [koulutuslaji_okm_avain], [koulutuslaji_okm], [koulutuslaji_okm_SV], [koulutuslaji_okm_EN], [koulutuslaji_okm2], [koulutuslaji_okm2_SV], [koulutuslaji_okm2_EN], [jarjestys], [jarjestys2], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (5, CAST(N'2015-05-13' AS Date), N'5', N'Ammatillinen perustutkinto (oppilaitosmuotoinen, opetussuunnitelmaperusteinen)', N'Grundläggande yrkesexamen (i läroanstaltsform, läroplansbaserad)', N'Vocational upper secondary qualification (institution-based, curriculum-based)', N'Ammatillinen perustutkinto (oppilaitosmuotoinen, opetussuunnitelmaperusteinen)', N'Grundläggande yrkesexamen (i läroanstaltsform, läroplansbaserad)', N'Vocational upper secondary qualification (institution-based, curriculum-based)', N'13', N'13', N'K', N'0', N'CSC', N'CSC Lasse')
GO
INSERT [dbo].[koulutuslaji_okm] ([id], [luotu], [koulutuslaji_okm_avain], [koulutuslaji_okm], [koulutuslaji_okm_SV], [koulutuslaji_okm_EN], [koulutuslaji_okm2], [koulutuslaji_okm2_SV], [koulutuslaji_okm2_EN], [jarjestys], [jarjestys2], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (6, CAST(N'2015-05-13' AS Date), N'6', N'Ammatillinen perustutkinto (oppilaitosmuotoinen, näyttötutkinto)', N'Grundläggande yrkesexamen (i läroanstaltsform, fristående examen)', N'Vocational upper secondary qualification (institution-based, competence-based)', N'Ammatillinen perustutkinto (oppilaitosmuotoinen, näyttötutkinto)', N'Grundläggande yrkesexamen (i läroanstaltsform, fristående examen)', N'Vocational upper secondary qualification (institution-based, competence-based)', N'14', N'14', N'K', N'0', N'CSC', N'CSC Lasse')
GO
INSERT [dbo].[koulutuslaji_okm] ([id], [luotu], [koulutuslaji_okm_avain], [koulutuslaji_okm], [koulutuslaji_okm_SV], [koulutuslaji_okm_EN], [koulutuslaji_okm2], [koulutuslaji_okm2_SV], [koulutuslaji_okm2_EN], [jarjestys], [jarjestys2], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (7, CAST(N'2015-05-13' AS Date), N'7', N'Ammattitutkinto (oppilaitosmuotoinen)', N'Yrkesexamen (i läroanstaltsform)', N'Further vocational qualification (institution-based)', N'Ammattitutkinto (oppilaitosmuotoinen)', N'Yrkesexamen (i läroanstaltsform)', N'Further vocational qualification (institution-based)', N'15', N'15', N'K', N'0', N'CSC', N'CSC Lasse')
GO
INSERT [dbo].[koulutuslaji_okm] ([id], [luotu], [koulutuslaji_okm_avain], [koulutuslaji_okm], [koulutuslaji_okm_SV], [koulutuslaji_okm_EN], [koulutuslaji_okm2], [koulutuslaji_okm2_SV], [koulutuslaji_okm2_EN], [jarjestys], [jarjestys2], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (8, CAST(N'2015-05-13' AS Date), N'8', N'Erikoisammattitutkinto  (oppilaitosmuotoinen)', N'Specialyrkesexamen (i läroanstaltsform)', N'Specialist vocational qualification (institution-based)', N'Erikoisammattitutkinto  (oppilaitosmuotoinen)', N'Specialyrkesexamen (i läroanstaltsform)', N'Specialist vocational qualification (institution-based)', N'16', N'16', N'K', N'0', N'CSC', N'CSC Lasse')
GO
INSERT [dbo].[koulutuslaji_okm] ([id], [luotu], [koulutuslaji_okm_avain], [koulutuslaji_okm], [koulutuslaji_okm_SV], [koulutuslaji_okm_EN], [koulutuslaji_okm2], [koulutuslaji_okm2_SV], [koulutuslaji_okm2_EN], [jarjestys], [jarjestys2], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (9, CAST(N'2015-05-13' AS Date), N'9', N'Ammatillinen perustutkinto (oppisopimuskoulutus, opetussuunnitelmaperusteinen)', N'Grundläggande yrkesexamen (läroavtalsutbildning, läroplansbaserad)', N'Vocational upper secondary qualification (apprenticeship training, curriculum-based)', N'Ammatillinen perustutkinto (oppisopimuskoulutus, opetussuunnitelmaperusteinen)', N'Grundläggande yrkesexamen (läroavtalsutbildning, läroplansbaserad)', N'Vocational upper secondary qualification (apprenticeship training, curriculum-based)', N'18', N'18', N'K', N'0', N'CSC', N'CSC Lasse')
GO
INSERT [dbo].[koulutuslaji_okm] ([id], [luotu], [koulutuslaji_okm_avain], [koulutuslaji_okm], [koulutuslaji_okm_SV], [koulutuslaji_okm_EN], [koulutuslaji_okm2], [koulutuslaji_okm2_SV], [koulutuslaji_okm2_EN], [jarjestys], [jarjestys2], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (10, CAST(N'2015-05-13' AS Date), N'10', N'Ammatillinen perustutkinto (oppisopimuskoulutus, näyttötutkinto)', N'Grundläggande yrkesexamen (läroavtalsutbildning, fristående examen)', N'Vocational upper secondary qualification (apprenticeship training, competence-based)', N'Ammatillinen perustutkinto (oppisopimuskoulutus, näyttötutkinto)', N'Grundläggande yrkesexamen (läroavtalsutbildning, fristående examen)', N'Vocational upper secondary qualification (apprenticeship training, competence-based)', N'19', N'19', N'K', N'0', N'CSC', N'CSC Lasse')
GO
INSERT [dbo].[koulutuslaji_okm] ([id], [luotu], [koulutuslaji_okm_avain], [koulutuslaji_okm], [koulutuslaji_okm_SV], [koulutuslaji_okm_EN], [koulutuslaji_okm2], [koulutuslaji_okm2_SV], [koulutuslaji_okm2_EN], [jarjestys], [jarjestys2], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (11, CAST(N'2015-05-13' AS Date), N'11', N'Ammattitutkinto (oppisopimuskoulutus)', N'Yrkesexamen (läroavtalsutbildning)', N'Further vocational qualification (apprenticeship training)', N'Ammattitutkinto (oppisopimuskoulutus)', N'Yrkesexamen (läroavtalsutbildning)', N'Further vocational qualification (apprenticeship training)', N'20', N'20', N'K', N'0', N'CSC', N'CSC Lasse')
GO
INSERT [dbo].[koulutuslaji_okm] ([id], [luotu], [koulutuslaji_okm_avain], [koulutuslaji_okm], [koulutuslaji_okm_SV], [koulutuslaji_okm_EN], [koulutuslaji_okm2], [koulutuslaji_okm2_SV], [koulutuslaji_okm2_EN], [jarjestys], [jarjestys2], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (12, CAST(N'2015-05-13' AS Date), N'12', N'Erikoisammattitutkinto (oppisopimuskoulutus)', N'Specialyrkesexamen (läroavtalsutbildning)', N'Specialist vocational qualification (apprenticeship training)', N'Erikoisammattitutkinto (oppisopimuskoulutus)', N'Specialyrkesexamen (läroavtalsutbildning)', N'Specialist vocational qualification (apprenticeship training)', N'21', N'21', N'K', N'0', N'CSC', N'CSC Lasse')
GO
INSERT [dbo].[koulutuslaji_okm] ([id], [luotu], [koulutuslaji_okm_avain], [koulutuslaji_okm], [koulutuslaji_okm_SV], [koulutuslaji_okm_EN], [koulutuslaji_okm2], [koulutuslaji_okm2_SV], [koulutuslaji_okm2_EN], [jarjestys], [jarjestys2], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (13, CAST(N'2015-05-13' AS Date), N'13', N'Ammattikorkeakoulututkinto (päivätoteutus)', N'Yrkeshögskoleexamen (dagstudier)', N'UAS degree (daytime studies)', N'Ammattikorkeakoulututkinto', N'Yrkeshögskoleexamen', N'UAS degree', N'22', N'22', N'K', N'0', N'CSC', N'CSC Lasse')
GO
INSERT [dbo].[koulutuslaji_okm] ([id], [luotu], [koulutuslaji_okm_avain], [koulutuslaji_okm], [koulutuslaji_okm_SV], [koulutuslaji_okm_EN], [koulutuslaji_okm2], [koulutuslaji_okm2_SV], [koulutuslaji_okm2_EN], [jarjestys], [jarjestys2], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (14, CAST(N'2015-05-13' AS Date), N'14', N'Ammattikorkeakoulututkinto (monimuotototeutus)', N'Yrkeshögskoleexamen (flerformsstudier)', N'UAS degree (multiform studies)', N'Ammattikorkeakoulututkinto', N'Yrkeshögskoleexamen', N'UAS degree', N'23', N'22', N'K', N'0', N'CSC', N'CSC Lasse')
GO
INSERT [dbo].[koulutuslaji_okm] ([id], [luotu], [koulutuslaji_okm_avain], [koulutuslaji_okm], [koulutuslaji_okm_SV], [koulutuslaji_okm_EN], [koulutuslaji_okm2], [koulutuslaji_okm2_SV], [koulutuslaji_okm2_EN], [jarjestys], [jarjestys2], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (15, CAST(N'2015-05-13' AS Date), N'15', N'Ylempi ammattikorkeakoulututkinto  ', N'Högre yrkeshögskoleexamen  ', N'UAS Master''s degree  ', N'Ylempi ammattikorkeakoulututkinto  ', N'Högre yrkeshögskoleexamen  ', N'UAS Master''s degree  ', N'24', N'24', N'K', N'0', N'CSC', N'CSC Lasse')
GO
INSERT [dbo].[koulutuslaji_okm] ([id], [luotu], [koulutuslaji_okm_avain], [koulutuslaji_okm], [koulutuslaji_okm_SV], [koulutuslaji_okm_EN], [koulutuslaji_okm2], [koulutuslaji_okm2_SV], [koulutuslaji_okm2_EN], [jarjestys], [jarjestys2], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (16, CAST(N'2015-05-13' AS Date), N'16', N'Alempi korkeakoulututkinto  ', N'Lägre högskoleexamen  ', N'Bachelor''s degree  ', N'Alempi korkeakoulututkinto  ', N'Lägre högskoleexamen  ', N'Bachelor''s degree  ', N'25', N'25', N'K', N'0', N'CSC', N'CSC Lasse')
GO
INSERT [dbo].[koulutuslaji_okm] ([id], [luotu], [koulutuslaji_okm_avain], [koulutuslaji_okm], [koulutuslaji_okm_SV], [koulutuslaji_okm_EN], [koulutuslaji_okm2], [koulutuslaji_okm2_SV], [koulutuslaji_okm2_EN], [jarjestys], [jarjestys2], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (17, CAST(N'2015-05-13' AS Date), N'17', N'Ylempi korkeakoulututkinto  ', N'Högre högskoleexamen  ', N'Master''s degree  ', N'Ylempi korkeakoulututkinto  ', N'Högre högskoleexamen  ', N'Master''s degree  ', N'26', N'26', N'K', N'0', N'CSC', N'CSC Lasse')
GO
INSERT [dbo].[koulutuslaji_okm] ([id], [luotu], [koulutuslaji_okm_avain], [koulutuslaji_okm], [koulutuslaji_okm_SV], [koulutuslaji_okm_EN], [koulutuslaji_okm2], [koulutuslaji_okm2_SV], [koulutuslaji_okm2_EN], [jarjestys], [jarjestys2], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (18, CAST(N'2015-05-13' AS Date), N'18', N'Lääkärien erikoistumiskoulutus', N'Läkarnas specialiseringsutbildning', N'Specialist degree in medicine', N'Lääkärien erikoistumiskoulutus', N'Läkarnas specialiseringsutbildning', N'Specialist degree in medicine', N'27', N'27', N'K', N'0', N'CSC', N'CSC Lasse')
GO
INSERT [dbo].[koulutuslaji_okm] ([id], [luotu], [koulutuslaji_okm_avain], [koulutuslaji_okm], [koulutuslaji_okm_SV], [koulutuslaji_okm_EN], [koulutuslaji_okm2], [koulutuslaji_okm2_SV], [koulutuslaji_okm2_EN], [jarjestys], [jarjestys2], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (19, CAST(N'2015-05-13' AS Date), N'19', N'Lisensiaatintutkinto', N'Licentiatexamen', N'Licentiate degree', N'Lisensiaatintutkinto', N'Licentiatexamen', N'Licentiate degree', N'28', N'28', N'K', N'0', N'CSC', N'CSC Lasse')
GO
INSERT [dbo].[koulutuslaji_okm] ([id], [luotu], [koulutuslaji_okm_avain], [koulutuslaji_okm], [koulutuslaji_okm_SV], [koulutuslaji_okm_EN], [koulutuslaji_okm2], [koulutuslaji_okm2_SV], [koulutuslaji_okm2_EN], [jarjestys], [jarjestys2], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (20, CAST(N'2015-05-13' AS Date), N'20', N'Tohtorintutkinto', N'Doktorsexamen', N'Doctoral degree', N'Tohtorintutkinto', N'Doktorsexamen', N'Doctoral degree', N'29', N'29', N'K', N'0', N'CSC', N'CSC Lasse')
GO
INSERT [dbo].[koulutuslaji_okm] ([id], [luotu], [koulutuslaji_okm_avain], [koulutuslaji_okm], [koulutuslaji_okm_SV], [koulutuslaji_okm_EN], [koulutuslaji_okm2], [koulutuslaji_okm2_SV], [koulutuslaji_okm2_EN], [jarjestys], [jarjestys2], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (21, CAST(N'2020-01-16' AS Date), N'61', N'Ammatillinen perustutkinto (oppilaitosmuotoinen)', N'Grundläggande yrkesexamen (i läroanstaltsform)', N'Vocational upper secondary qualification (institution-based)', N'Ammatillinen perustutkinto (oppilaitosmuotoinen)', N'Grundläggande yrkesexamen (i läroanstaltsform)', N'Vocational upper secondary qualification (institution-based)', N'10', N'10', N'K', N'0', N'CSC', N'CSC Juha')
GO
INSERT [dbo].[koulutuslaji_okm] ([id], [luotu], [koulutuslaji_okm_avain], [koulutuslaji_okm], [koulutuslaji_okm_SV], [koulutuslaji_okm_EN], [koulutuslaji_okm2], [koulutuslaji_okm2_SV], [koulutuslaji_okm2_EN], [jarjestys], [jarjestys2], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (22, CAST(N'2020-01-16' AS Date), N'64', N'Ammatillinen perustutkinto (oppisopimuskoulutus)', N'Grundläggande yrkesexamen (läroavtalsutbildning)', N'Vocational upper secondary qualification (apprenticeship training)', N'Ammatillinen perustutkinto (oppisopimuskoulutus)', N'Grundläggande yrkesexamen (läroavtalsutbildning)', N'Vocational upper secondary qualification (apprenticeship training)', N'17', N'17', N'K', N'0', N'CSC', N'CSC Juha')
GO
INSERT [dbo].[koulutuslaji2] ([id], [luotu], [koulutuslaji2_koodi], [koulutuslaji2], [koulutuslaji2_SV], [koulutuslaji2_EN], [jarjestys_koulutuslaji2], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (-2, CAST(N'2013-06-10' AS Date), N'-2', N'Virhetilanne', N'Feltillstånd', N'Error occurred', N'999', N'Virhetilanne', N'Feltillstånd', N'Error occurred', N'99', N'Virhetilanne', N'Feltillstånd', N'Error occurred', N'99', N'Virhetilanne', N'Feltillstånd', N'Error occurred', N'99', N'K', N'0', N'Manuaalinen', N'')
GO
INSERT [dbo].[koulutuslaji2] ([id], [luotu], [koulutuslaji2_koodi], [koulutuslaji2], [koulutuslaji2_SV], [koulutuslaji2_EN], [jarjestys_koulutuslaji2], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (-1, CAST(N'2013-06-10' AS Date), N'-1', N'Tuntematon', N'Okänd', N'Unknown', N'998', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'K', N'0', N'Manuaalinen', N'')
GO
INSERT [dbo].[koulutuslaji2] ([id], [luotu], [koulutuslaji2_koodi], [koulutuslaji2], [koulutuslaji2_SV], [koulutuslaji2_EN], [jarjestys_koulutuslaji2], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (1, CAST(N'2013-06-10' AS Date), N'21', N'Lukiokoulutus, nuorten OPS', N'Gymnasieutbildning, LP för unga', N'General upper secondary education, curriculum for young people', N'210', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'E', N'0', N'Manuaalinen', N'')
GO
INSERT [dbo].[koulutuslaji2] ([id], [luotu], [koulutuslaji2_koodi], [koulutuslaji2], [koulutuslaji2_SV], [koulutuslaji2_EN], [jarjestys_koulutuslaji2], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (2, CAST(N'2013-06-10' AS Date), N'22', N'Lukiokoulutus, aikuisten OPS', N'Gymnasieutbildning, LP för vuxna', N'General upper secondary education, curriculum for adults', N'220', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'E', N'0', N'Manuaalinen', N'')
GO
INSERT [dbo].[koulutuslaji2] ([id], [luotu], [koulutuslaji2_koodi], [koulutuslaji2], [koulutuslaji2_SV], [koulutuslaji2_EN], [jarjestys_koulutuslaji2], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (3, CAST(N'2013-06-10' AS Date), N'31', N'OPS-perusteinen ammatillinen peruskoulutus (ei oppisopimuskoulutus)', N'LP-baserad grundläggande yrkesutbildning (ej läroavtalsutbildning)', N'Curriculum-based vocational upper secondary education and training (not apprenticeship training)', N'310', N'opetussuunnitelmaperusteinen koulutus/tutkinto', N'läroplansbaserad utbildning/examen', N'curriculum-based education/qualification', N'1', N'Oppilaitosmuotoinen koulutus', N'Institututbildning', N'Institute-based education', N'1', N'ammatillinen peruskoulutus', N'grundläggande yrkesutbildning', N'vocational upper secondary education and training', N'1', N'E', N'0', N'Manuaalinen', N'')
GO
INSERT [dbo].[koulutuslaji2] ([id], [luotu], [koulutuslaji2_koodi], [koulutuslaji2], [koulutuslaji2_SV], [koulutuslaji2_EN], [jarjestys_koulutuslaji2], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (4, CAST(N'2013-06-10' AS Date), N'32', N'Näyttötutkintoon valmistava koulutus: perustutkinnot (ei oppisop. koul.)', N'Förberedande utbildning för fristående examen: grundexamina (ej läroavtalsutb.)', N'Preparatory training for competence-based qualifications: vocational upper secondary qualifications (not apprenticeship training)', N'320', N'näyttötutkintoon valmistava koulutus/tutkinto', N'Förberedande utbildning för fristående examen/examen', N'preparatory training/qualification for competence-based qualifications', N'2', N'Oppilaitosmuotoinen koulutus', N'Institututbildning', N'Institute-based education', N'1', N'ammatillinen peruskoulutus', N'grundläggande yrkesutbildning', N'vocational upper secondary education and training', N'1', N'E', N'0', N'Manuaalinen', N'')
GO
INSERT [dbo].[koulutuslaji2] ([id], [luotu], [koulutuslaji2_koodi], [koulutuslaji2], [koulutuslaji2_SV], [koulutuslaji2_EN], [jarjestys_koulutuslaji2], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (5, CAST(N'2013-06-10' AS Date), N'33', N'Näyttötutkintoon valmistava koulutus: ammattitutkinnot (ei oppisop.koul.)', N'Förberedande utbildning för fristående examen: yrkesexamina (ej läroavtalsutb.)', N'Preparatory training for competence-based qualifications: further vocational qualifications (not apprenticeship training)', N'330', N'näyttötutkintoon valmistava koulutus/tutkinto', N'Förberedande utbildning för fristående examen/examen', N'preparatory training/qualification for competence-based qualifications', N'2', N'Oppilaitosmuotoinen koulutus', N'Institututbildning', N'Institute-based education', N'1', N'ammattitutkinto', N'yrkesexamen', N'further vocational qualification', N'2', N'E', N'0', N'Manuaalinen', N'')
GO
INSERT [dbo].[koulutuslaji2] ([id], [luotu], [koulutuslaji2_koodi], [koulutuslaji2], [koulutuslaji2_SV], [koulutuslaji2_EN], [jarjestys_koulutuslaji2], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (6, CAST(N'2013-06-10' AS Date), N'34', N'Näyttötutkintoon valmistava koulutus: erikoisammattitutkinnot (ei oppisop.k.)', N'Förberedande utbildning för fristående examen: specialyrkesexamina (ej läroavtalsutb.)', N'Preparatory training for competence-based qualifications: specialist vocational qualifications (not apprenticeship training)', N'340', N'näyttötutkintoon valmistava koulutus/tutkinto', N'Förberedande utbildning för fristående examen/examen', N'preparatory training/qualification for competence-based qualifications', N'2', N'Oppilaitosmuotoinen koulutus', N'Institututbildning', N'Institute-based education', N'1', N'erikoisammattitutkinto', N'specialyrkesexamen', N'specialist vocational qualification', N'3', N'E', N'0', N'Manuaalinen', N'')
GO
INSERT [dbo].[koulutuslaji2] ([id], [luotu], [koulutuslaji2_koodi], [koulutuslaji2], [koulutuslaji2_SV], [koulutuslaji2_EN], [jarjestys_koulutuslaji2], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (7, CAST(N'2013-06-10' AS Date), N'35', N'OPS-perusteinen ammatillinen peruskoulutus (oppisopimuskoulutus)', N'LP-baserad grundläggande yrkesutbildning (läroavtalsutbildning)', N'Curriculum-based vocational upper secondary education and training (apprenticeship training)', N'350', N'opetussuunnitelmaperusteinen koulutus/tutkinto', N'läroplansbaserad utbildning/examen', N'curriculum-based education/qualification', N'1', N'Oppisopimuskoulutus', N'Läroavtalsutbildning', N'Apprenticeship training', N'2', N'ammatillinen peruskoulutus', N'grundläggande yrkesutbildning', N'vocational upper secondary education and training', N'1', N'E', N'0', N'Manuaalinen', N'')
GO
INSERT [dbo].[koulutuslaji2] ([id], [luotu], [koulutuslaji2_koodi], [koulutuslaji2], [koulutuslaji2_SV], [koulutuslaji2_EN], [jarjestys_koulutuslaji2], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (8, CAST(N'2013-06-10' AS Date), N'36', N'Näyttötutkintoon valmistava koulutus: perustutkinnot (oppisopimuskoulutus)', N'Förberedande utbildning för fristående examen: grundexamina (läroavtalsutb.)', N'Preparatory training for competence-based qualifications: vocational upper secondary qualifications (apprenticeship training)', N'360', N'näyttötutkintoon valmistava koulutus/tutkinto', N'Förberedande utbildning för fristående examen/examen', N'preparatory training/qualification for competence-based qualifications', N'2', N'Oppisopimuskoulutus', N'Läroavtalsutbildning', N'Apprenticeship training', N'2', N'ammatillinen peruskoulutus', N'grundläggande yrkesutbildning', N'vocational upper secondary education and training', N'1', N'E', N'0', N'Manuaalinen', N'')
GO
INSERT [dbo].[koulutuslaji2] ([id], [luotu], [koulutuslaji2_koodi], [koulutuslaji2], [koulutuslaji2_SV], [koulutuslaji2_EN], [jarjestys_koulutuslaji2], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (9, CAST(N'2013-06-10' AS Date), N'37', N'Näyttötutkintoon valmistava koulutus: ammattitutkinnot (oppisopimuskoulutus)', N'Förberedande utbildning för fristående examen: yrkesexamina (läroavtalsutb.)', N'Preparatory training for competence-based qualifications: further vocational qualifications (apprenticeship training)', N'370', N'näyttötutkintoon valmistava koulutus/tutkinto', N'Förberedande utbildning för fristående examen/examen', N'preparatory training/qualification for competence-based qualifications', N'2', N'Oppisopimuskoulutus', N'Läroavtalsutbildning', N'Apprenticeship training', N'2', N'ammattitutkinto', N'yrkesexamen', N'further vocational qualification', N'2', N'E', N'0', N'Manuaalinen', N'')
GO
INSERT [dbo].[koulutuslaji2] ([id], [luotu], [koulutuslaji2_koodi], [koulutuslaji2], [koulutuslaji2_SV], [koulutuslaji2_EN], [jarjestys_koulutuslaji2], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (10, CAST(N'2013-06-10' AS Date), N'38', N'Näyttötutkintoon valmistava koulutus: erikoisammattitutkinnot (oppisop.koul.)', N'Förberedande utbildning för fristående examen: specialyrkesexamina (läroavtalsutb.)', N'Preparatory training for competence-based qualifications: specialist vocational qualifications (apprenticeship training)', N'380', N'näyttötutkintoon valmistava koulutus/tutkinto', N'Förberedande utbildning för fristående examen/examen', N'preparatory training/qualification for competence-based qualifications', N'2', N'Oppisopimuskoulutus', N'Läroavtalsutbildning', N'Apprenticeship training', N'2', N'erikoisammattitutkinto', N'specialyrkesexamen', N'specialist vocational qualification', N'3', N'E', N'0', N'Manuaalinen', N'')
GO
INSERT [dbo].[koulutuslaji2] ([id], [luotu], [koulutuslaji2_koodi], [koulutuslaji2], [koulutuslaji2_SV], [koulutuslaji2_EN], [jarjestys_koulutuslaji2], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (11, CAST(N'2013-06-10' AS Date), N'41', N'Ammattikorkeakoulututkinto, päivätoteutus', N'Yrkeshögskoleexamen, dagstudier', N'Polytechnic degree, daytime studies', N'410', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'E', N'0', N'Manuaalinen', N'')
GO
INSERT [dbo].[koulutuslaji2] ([id], [luotu], [koulutuslaji2_koodi], [koulutuslaji2], [koulutuslaji2_SV], [koulutuslaji2_EN], [jarjestys_koulutuslaji2], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (12, CAST(N'2013-06-10' AS Date), N'42', N'Ammattikorkeakoulututkinto, monimuotototeutus', N'Yrkeshögskoleexamen, flerformsstudier', N'Polytechnic degree, multiform studies', N'420', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'E', N'0', N'Manuaalinen', N'')
GO
INSERT [dbo].[koulutuslaji2] ([id], [luotu], [koulutuslaji2_koodi], [koulutuslaji2], [koulutuslaji2_SV], [koulutuslaji2_EN], [jarjestys_koulutuslaji2], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (13, CAST(N'2013-06-10' AS Date), N'46', N'Ylempään AMK-tutkintoon tähtäävä koulutus', N'Utbildning för högre YH-examen', N'Education leading to UAS Master''s degree', N'460', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'E', N'0', N'Manuaalinen', N'')
GO
INSERT [dbo].[koulutuslaji2] ([id], [luotu], [koulutuslaji2_koodi], [koulutuslaji2], [koulutuslaji2_SV], [koulutuslaji2_EN], [jarjestys_koulutuslaji2], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (14, CAST(N'2013-06-10' AS Date), N'51a', N'Alempaan korkeakoulututkintoon tähtäävä koulutus', N'Utbildning för lägre högskoleexamen', N'Education leading to Bachelor''s degree', N'511', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'E', N'0', N'Manuaalinen', N'')
GO
INSERT [dbo].[koulutuslaji2] ([id], [luotu], [koulutuslaji2_koodi], [koulutuslaji2], [koulutuslaji2_SV], [koulutuslaji2_EN], [jarjestys_koulutuslaji2], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (15, CAST(N'2013-06-10' AS Date), N'51b', N'Ylempään korkeakoulututkintoon tähtäävä koulutus', N'Utbildning för högre högskoleexamen', N'Education leading to Master''s degree', N'512', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'E', N'0', N'Manuaalinen', N'')
GO
INSERT [dbo].[koulutuslaji2] ([id], [luotu], [koulutuslaji2_koodi], [koulutuslaji2], [koulutuslaji2_SV], [koulutuslaji2_EN], [jarjestys_koulutuslaji2], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (16, CAST(N'2013-06-10' AS Date), N'52', N'Lisensiaatinkoulutus, tohtorinkoulutus ja lääkärien erik.koul.', N'Licentiatutbildning, doktorsutbildning och specialiseringsutb. för läkare', N'Licentiate education, postgraduate education and specialist degrees in medicine', N'520', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'E', N'0', N'Manuaalinen', N'')
GO
INSERT [dbo].[koulutuslaji2] ([id], [luotu], [koulutuslaji2_koodi], [koulutuslaji2], [koulutuslaji2_SV], [koulutuslaji2_EN], [jarjestys_koulutuslaji2], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (17, CAST(N'2020-01-16' AS Date), N'61', N'Ammatilliset perustutkinnot (ei oppisopimuskoulutus)', N'Yrkesinriktade grundexamina (ej läroavtalsutbildning)', N'Vocational qualifications (not apprenticeship training)', N'301', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Oppilaitosmuotoinen koulutus', N'Institututbildning', N'Institute-based education', N'1', N'ammatillinen peruskoulutus', N'grundläggande yrkesutbildning', N'vocational upper secondary education and training', N'1', N'E', N'0', N'Manuaalinen', N'')
GO
INSERT [dbo].[koulutuslaji2] ([id], [luotu], [koulutuslaji2_koodi], [koulutuslaji2], [koulutuslaji2_SV], [koulutuslaji2_EN], [jarjestys_koulutuslaji2], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (18, CAST(N'2020-01-16' AS Date), N'62', N'Ammattitutkinnot (ei oppisopimuskoulutus)', N'Yrkesexamina (ej läroavtalsutbildning)', N'Further vocational qualifications (not apprenticeship training)', N'302', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Oppilaitosmuotoinen koulutus', N'Institututbildning', N'Institute-based education', N'1', N'ammattitutkinto', N'yrkesexamen', N'further vocational qualification', N'2', N'E', N'0', N'Manuaalinen', N'')
GO
INSERT [dbo].[koulutuslaji2] ([id], [luotu], [koulutuslaji2_koodi], [koulutuslaji2], [koulutuslaji2_SV], [koulutuslaji2_EN], [jarjestys_koulutuslaji2], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (19, CAST(N'2020-01-16' AS Date), N'63', N'Erikoisammattitutkinnot (ei oppisopimuskoulutus)', N'Specialyrkesexamina (ej läroavtalsutbildning)', N'Specialist vocational qualifications (not apprenticeship training)', N'303', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Oppilaitosmuotoinen koulutus', N'Institututbildning', N'Institute-based education', N'1', N'erikoisammattitutkinto', N'specialyrkesexamen', N'specialist vocational qualification', N'3', N'E', N'0', N'Manuaalinen', N'')
GO
INSERT [dbo].[koulutuslaji2] ([id], [luotu], [koulutuslaji2_koodi], [koulutuslaji2], [koulutuslaji2_SV], [koulutuslaji2_EN], [jarjestys_koulutuslaji2], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (20, CAST(N'2020-01-16' AS Date), N'64', N'Ammatilliset perustutkinnot (oppisopimuskoulutus)', N'Yrkesinriktade grundexamina (läroavtalsutbildning)', N'Vocational qualifications (apprenticeship training)', N'344', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Oppisopimuskoulutus', N'Läroavtalsutbildning', N'Apprenticeship training', N'2', N'ammatillinen peruskoulutus', N'grundläggande yrkesutbildning', N'vocational upper secondary education and training', N'1', N'E', N'0', N'Manuaalinen', N'')
GO
INSERT [dbo].[koulutuslaji2] ([id], [luotu], [koulutuslaji2_koodi], [koulutuslaji2], [koulutuslaji2_SV], [koulutuslaji2_EN], [jarjestys_koulutuslaji2], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (21, CAST(N'2020-01-16' AS Date), N'65', N'Ammattitutkinnot (oppisopimuskoulutus)', N'Yrkesexamina (läroavtalsutbildning)', N'Further vocational qualifications (apprenticeship training)', N'345', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Oppisopimuskoulutus', N'Läroavtalsutbildning', N'Apprenticeship training', N'2', N'ammattitutkinto', N'yrkesexamen', N'further vocational qualification', N'2', N'E', N'0', N'Manuaalinen', N'')
GO
INSERT [dbo].[koulutuslaji2] ([id], [luotu], [koulutuslaji2_koodi], [koulutuslaji2], [koulutuslaji2_SV], [koulutuslaji2_EN], [jarjestys_koulutuslaji2], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (22, CAST(N'2020-01-16' AS Date), N'66', N'Erikoisammattitutkinnot (oppisopimuskoulutus)', N'Specialyrkesexamina (läroavtalsutbildning)', N'Specialist vocational qualifications (apprenticeship training)', N'346', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Oppisopimuskoulutus', N'Läroavtalsutbildning', N'Apprenticeship training', N'2', N'erikoisammattitutkinto', N'specialyrkesexamen', N'specialist vocational qualification', N'3', N'E', N'0', N'Manuaalinen', N'')
GO
INSERT [dbo].[koulutuslaji3] ([id], [luotu], [koulutuslaji3_koodi], [koulutuslaji3], [koulutuslaji3_SV], [koulutuslaji3_EN], [jarjestys_koulutuslaji3], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (-2, CAST(N'2015-05-28' AS Date), N'-2', N'Virhetilanne', N'Feltillstånd', N'Error occurred', N'999', N'Virhetilanne', N'Feltillstånd', N'Error occurred', N'99', N'Virhetilanne', N'Feltillstånd', N'Error occurred', N'99', N'Virhetilanne', N'Feltillstånd', N'Error occurred', N'99', N'K', N'0', N'Manuaalinen', N'')
GO
INSERT [dbo].[koulutuslaji3] ([id], [luotu], [koulutuslaji3_koodi], [koulutuslaji3], [koulutuslaji3_SV], [koulutuslaji3_EN], [jarjestys_koulutuslaji3], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (-1, CAST(N'2015-05-28' AS Date), N'-1', N'Tuntematon', N'Okänd', N'Unknown', N'998', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'K', N'0', N'Manuaalinen', N'')
GO
INSERT [dbo].[koulutuslaji3] ([id], [luotu], [koulutuslaji3_koodi], [koulutuslaji3], [koulutuslaji3_SV], [koulutuslaji3_EN], [jarjestys_koulutuslaji3], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (1, CAST(N'2015-05-28' AS Date), N'21', N'Lukiokoulutus, nuorten OPS', N'Gymnasieutbildning, ungdomar LP-baserad', N'General upper secondary education, curriculum for young people', N'210', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'E', N'0', N'Manuaalinen', N'Järjestämistapa-, muoto ja tutkintotyyppi kopioitu koulutuslaji2:sta')
GO
INSERT [dbo].[koulutuslaji3] ([id], [luotu], [koulutuslaji3_koodi], [koulutuslaji3], [koulutuslaji3_SV], [koulutuslaji3_EN], [jarjestys_koulutuslaji3], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (2, CAST(N'2015-05-28' AS Date), N'22', N'Lukiokoulutus, aikuisten OPS', N'Gymnasieutbildning, vuxna LP-baserad', N'General upper secondary education, curriculum for adults', N'220', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'E', N'0', N'Manuaalinen', N'Järjestämistapa-, muoto ja tutkintotyyppi kopioitu koulutuslaji2:sta')
GO
INSERT [dbo].[koulutuslaji3] ([id], [luotu], [koulutuslaji3_koodi], [koulutuslaji3], [koulutuslaji3_SV], [koulutuslaji3_EN], [jarjestys_koulutuslaji3], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (3, CAST(N'2015-05-28' AS Date), N'31', N'OPS-perusteinen ammatillinen peruskoulutus (ei oppisop.koul.)', N'LP-baserad grundläggande yrkesutbildning (ej läroavtalsutbildning)', N'Curriculum-based vocational upper secondary education and training (not apprenticeship training)', N'310', N'opetussuunnitelmaperusteinen koulutus/tutkinto', N'läroplansbaserad utbildning/examen', N'curriculum-based education/qualification', N'01', N'Oppilaitosmuotoinen koulutus', N'Institututbildning', N'Institute-based education', N'01', N'ammatillinen peruskoulutus', N'grundläggande yrkesutbildning', N'vocational upper secondary education and training', N'01', N'E', N'0', N'Manuaalinen', N'Järjestämistapa-, muoto ja tutkintotyyppi kopioitu koulutuslaji2:sta')
GO
INSERT [dbo].[koulutuslaji3] ([id], [luotu], [koulutuslaji3_koodi], [koulutuslaji3], [koulutuslaji3_SV], [koulutuslaji3_EN], [jarjestys_koulutuslaji3], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (4, CAST(N'2015-05-28' AS Date), N'32', N'Näyttötutkintoon valmistava koulutus: perustutkinnot (ei oppisop. koul.)', N'Förberedande utbildning för fristående examen: grundexamina (ej läroavtalsutb.)', N'Preparatory training for competence-based qualifications: vocational upper secondary qualifications (not apprenticeship training)', N'320', N'näyttötutkintoon valmistava koulutus/tutkinto', N'Förberedande utbildning för fristående examen/examen', N'preparatory training/qualification for competence-based qualifications', N'02', N'Oppilaitosmuotoinen koulutus', N'Institututbildning', N'Institute-based education', N'01', N'ammatillinen peruskoulutus', N'grundläggande yrkesutbildning', N'vocational upper secondary education and training', N'01', N'E', N'0', N'Manuaalinen', N'Järjestämistapa-, muoto ja tutkintotyyppi kopioitu koulutuslaji2:sta')
GO
INSERT [dbo].[koulutuslaji3] ([id], [luotu], [koulutuslaji3_koodi], [koulutuslaji3], [koulutuslaji3_SV], [koulutuslaji3_EN], [jarjestys_koulutuslaji3], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (5, CAST(N'2015-05-28' AS Date), N'33', N'Näyttötutkintoon valmistava koulutus: ammattitutkinnot (ei oppisop.koul.)', N'Förberedande utbildning för fristående examen: yrkesexamina (ej läroavtalsutb.)', N'Preparatory training for competence-based qualifications: further vocational qualifications (not apprenticeship training)', N'330', N'näyttötutkintoon valmistava koulutus/tutkinto', N'Förberedande utbildning för fristående examen/examen', N'preparatory training/qualification for competence-based qualifications', N'02', N'Oppilaitosmuotoinen koulutus', N'Institututbildning', N'Institute-based education', N'01', N'ammattitutkinto', N'yrkesexamen', N'further vocational qualification', N'02', N'E', N'0', N'Manuaalinen', N'Järjestämistapa-, muoto ja tutkintotyyppi kopioitu koulutuslaji2:sta')
GO
INSERT [dbo].[koulutuslaji3] ([id], [luotu], [koulutuslaji3_koodi], [koulutuslaji3], [koulutuslaji3_SV], [koulutuslaji3_EN], [jarjestys_koulutuslaji3], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (6, CAST(N'2015-05-28' AS Date), N'34', N'Näyttötutkintoon valmistava koulutus: erikoisammattitutk. (ei oppisop.koul.)', N'Förberedande utbildning för fristående examen: specialyrkesexamina (ej läroavtalsutb.)', N'Preparatory training for competence-based qualifications: specialist vocational qualifications (not apprenticeship training) ', N'340', N'näyttötutkintoon valmistava koulutus/tutkinto', N'Förberedande utbildning för fristående examen/examen', N'preparatory training/qualification for competence-based qualifications', N'02', N'Oppilaitosmuotoinen koulutus', N'Institututbildning', N'Institute-based education', N'01', N'erikoisammattitutkinto', N'specialyrkesexamen', N'specialist vocational qualification', N'03', N'E', N'0', N'Manuaalinen', N'Järjestämistapa-, muoto ja tutkintotyyppi kopioitu koulutuslaji2:sta')
GO
INSERT [dbo].[koulutuslaji3] ([id], [luotu], [koulutuslaji3_koodi], [koulutuslaji3], [koulutuslaji3_SV], [koulutuslaji3_EN], [jarjestys_koulutuslaji3], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (7, CAST(N'2015-05-28' AS Date), N'35', N'Oppisopimuskoulutus', N'Läroavtalsutbildning', N'Apprenticeship training', N'350', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Oppisopimuskoulutus', N'Läroavtalsutbildning', N'Apprenticeship training', N'02', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'E', N'0', N'Manuaalinen', N'Järjestämistapa-, muoto ja tutkintotyyppi kopioitu koulutuslaji2:sta')
GO
INSERT [dbo].[koulutuslaji3] ([id], [luotu], [koulutuslaji3_koodi], [koulutuslaji3], [koulutuslaji3_SV], [koulutuslaji3_EN], [jarjestys_koulutuslaji3], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (11, CAST(N'2015-05-28' AS Date), N'41', N'AMK-tutkinto, päivätoteutus', N'YH-examen, dagstudier', N'UAS degree, daytime studies', N'410', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'E', N'0', N'Manuaalinen', N'Järjestämistapa-, muoto ja tutkintotyyppi kopioitu koulutuslaji2:sta')
GO
INSERT [dbo].[koulutuslaji3] ([id], [luotu], [koulutuslaji3_koodi], [koulutuslaji3], [koulutuslaji3_SV], [koulutuslaji3_EN], [jarjestys_koulutuslaji3], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (12, CAST(N'2015-05-28' AS Date), N'42', N'AMK-tutkinto, monimuotototeutus', N'YH-examen, flerformsstudier', N'UAS degree, multiform studies', N'420', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'E', N'0', N'Manuaalinen', N'Järjestämistapa-, muoto ja tutkintotyyppi kopioitu koulutuslaji2:sta')
GO
INSERT [dbo].[koulutuslaji3] ([id], [luotu], [koulutuslaji3_koodi], [koulutuslaji3], [koulutuslaji3_SV], [koulutuslaji3_EN], [jarjestys_koulutuslaji3], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (13, CAST(N'2015-05-28' AS Date), N'46', N'Ylempi AMK-tutkintokoulutus', N'Utbildning för högre YH-examen', N'UAS Master''s degree education', N'460', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'E', N'0', N'Manuaalinen', N'Järjestämistapa-, muoto ja tutkintotyyppi kopioitu koulutuslaji2:sta')
GO
INSERT [dbo].[koulutuslaji3] ([id], [luotu], [koulutuslaji3_koodi], [koulutuslaji3], [koulutuslaji3_SV], [koulutuslaji3_EN], [jarjestys_koulutuslaji3], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (14, CAST(N'2015-05-28' AS Date), N'51', N'Alemmat ja ylemmät korkeakoulututkinnot', N'Lägre och högre yrkeshögskoleexamina', N'Bachelor''s and Master''s degrees', N'510', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'E', N'0', N'Manuaalinen', N'Järjestämistapa-, muoto ja tutkintotyyppi kopioitu koulutuslaji2:sta')
GO
INSERT [dbo].[koulutuslaji3] ([id], [luotu], [koulutuslaji3_koodi], [koulutuslaji3], [koulutuslaji3_SV], [koulutuslaji3_EN], [jarjestys_koulutuslaji3], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (16, CAST(N'2015-05-28' AS Date), N'52', N'Lisensiaatin-, tohtorin- ja lääkärien erikoistumiskoulutus', N'Licentiat- och doktorsutbildning, specialiseringsutbildning för läkare', N'Licentiate and doctoral education and specialist degree in medicine', N'520', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'E', N'0', N'Manuaalinen', N'Järjestämistapa-, muoto ja tutkintotyyppi kopioitu koulutuslaji2:sta')
GO
INSERT [dbo].[koulutuslaji3] ([id], [luotu], [koulutuslaji3_koodi], [koulutuslaji3], [koulutuslaji3_SV], [koulutuslaji3_EN], [jarjestys_koulutuslaji3], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (21, CAST(N'2020-01-16' AS Date), N'61', N'Ammatilliset perustutkinnot (ei oppisopimuskoulutus)', N'Yrkesinriktade grundexamina (ej läroavtalsutbildning)', N'Vocational qualifications (not apprenticeship training)', N'301', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Oppilaitosmuotoinen koulutus', N'Institututbildning', N'Institute-based education', N'01', N'ammatillinen peruskoulutus', N'grundläggande yrkesutbildning', N'vocational upper secondary education and training', N'01', N'E', N'0', N'Manuaalinen', N'')
GO
INSERT [dbo].[koulutuslaji3] ([id], [luotu], [koulutuslaji3_koodi], [koulutuslaji3], [koulutuslaji3_SV], [koulutuslaji3_EN], [jarjestys_koulutuslaji3], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (22, CAST(N'2020-01-16' AS Date), N'62', N'Ammattitutkinnot (ei oppisopimuskoulutus)', N'Yrkesexamina (ej läroavtalsutbildning)', N'Further vocational qualifications (not apprenticeship training)', N'302', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Oppilaitosmuotoinen koulutus', N'Institututbildning', N'Institute-based education', N'01', N'ammattitutkinto', N'yrkesexamen', N'further vocational qualification', N'02', N'E', N'0', N'Manuaalinen', N'')
GO
INSERT [dbo].[koulutuslaji3] ([id], [luotu], [koulutuslaji3_koodi], [koulutuslaji3], [koulutuslaji3_SV], [koulutuslaji3_EN], [jarjestys_koulutuslaji3], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (23, CAST(N'2020-01-16' AS Date), N'63', N'Erikoisammattitutkinnot (ei oppisopimuskoulutus)', N'Specialyrkesexamina (ej läroavtalsutbildning)', N'Specialist vocational qualifications (not apprenticeship training)', N'303', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Oppilaitosmuotoinen koulutus', N'Institututbildning', N'Institute-based education', N'01', N'erikoisammattitutkinto', N'specialyrkesexamen', N'specialist vocational qualification', N'03', N'E', N'0', N'Manuaalinen', N'')
GO
INSERT [dbo].[koulutuslaji3] ([id], [luotu], [koulutuslaji3_koodi], [koulutuslaji3], [koulutuslaji3_SV], [koulutuslaji3_EN], [jarjestys_koulutuslaji3], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (27, CAST(N'2020-01-16' AS Date), N'67', N'Oppisopimuskoulutus', N'Läroavtalsutbildning', N'Apprenticeship training', N'347', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Oppisopimuskoulutus', N'Läroavtalsutbildning', N'Apprenticeship training', N'02', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'E', N'0', N'Manuaalinen', N'')
GO
ALTER TABLE [dbo].[koulutuslaji] ADD  CONSTRAINT [DF__koulutuslaji__alkaa]  DEFAULT ('1900-01-01') FOR [alkaa]
GO
ALTER TABLE [dbo].[koulutuslaji] ADD  CONSTRAINT [DF__koulutuslaji__paattyy]  DEFAULT ('9999-01-01') FOR [paattyy]
GO
ALTER TABLE [dbo].[koulutuslaji] ADD  CONSTRAINT [DF__koulutuslaji__tietolahde]  DEFAULT ('Tilastokeskus') FOR [tietolahde]
GO
ALTER TABLE [dbo].[koulutuslaji_okm] ADD  CONSTRAINT [DF__koulutuslaji_okm__tietolahde]  DEFAULT ('Tilastokeskus') FOR [tietolahde]
GO
ALTER TABLE [dbo].[koulutuslaji2] ADD  DEFAULT ('Tilastokeskus') FOR [tietolahde]
GO
ALTER TABLE [dbo].[koulutuslaji3] ADD  DEFAULT ('Tilastokeskus') FOR [tietolahde]
GO
USE [ANTERO]