USE [VipunenTK_lisatiedot]
GO
/****** Object:  Table [dbo].[opettajat_aine_amm]    Script Date: 12.2.2020 21:09:00 ******/
DROP TABLE [dbo].[opettajat_aine_amm]
GO
/****** Object:  Table [dbo].[opettajat_aine_amm]    Script Date: 12.2.2020 21:09:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[opettajat_aine_amm](
	[id] [int] NOT NULL,
	[luotu] [date] NULL,
	[aine_koodi] [nvarchar](3) NULL,
	[aine] [nvarchar](255) NULL,
	[aine_SV] [nvarchar](255) NULL,
	[aine_EN] [nvarchar](255) NULL,
	[jarjestys] [nvarchar](50) NULL,
	[virhetilanne] [nchar](10) NULL,
	[poistettu] [nchar](1) NULL,
	[tietolahde] [nvarchar](50) NULL,
	[kommentti] [nvarchar](250) NULL,
	[alkaa] [date] NULL,
	[paattyy] [date] NULL
) ON [PRIMARY]

GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (-1, CAST(N'2015-06-08' AS Date), N'-1', N'Tuntematon', N'Information saknas', N'Missing data', N'9980', N'K         ', N' ', N'Manuaalinen', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (-2, CAST(N'2015-06-08' AS Date), N'-2', N'Virhetilanne', N'Feltillstånd', N'Error occurred', N'9990', N'K         ', N' ', N'Manuaalinen', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (83, CAST(N'2017-02-09' AS Date), N'000', N'ei opetusta (rehtorit) tai ei muiden aineiden opetusta', N'*SV*Ei opetusta (rehtorit) tai ei muiden aineiden opetusta', N'*EN*Ei opetusta (rehtorit) tai ei muiden aineiden opetusta', N'1000', N'E         ', N' ', N'Manuaalinen', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (84, CAST(N'2015-06-08' AS Date), N'006', N'äidinkieli, suomi ', N'modersmål, finska ', N'mother tongue, Finnish ', N'1010', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (85, CAST(N'2015-06-08' AS Date), N'007', N'äidinkieli, ruotsi  ', N'modersmål, svenska  ', N'mother tongue, Swedish  ', N'1020', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (86, CAST(N'2015-06-08' AS Date), N'008', N'äidinkieli, saame  ', N'modersmål, samiska  ', N'mother tongue, Sámi  ', N'1030', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (87, CAST(N'2015-06-08' AS Date), N'009', N'äidinkieli, viittomakieli  ', N'modersmål, teckenspråk  ', N'mother tongue, sign language  ', N'1040', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (88, CAST(N'2015-06-08' AS Date), N'010', N'äidinkieli, muu opiskelijan äidinkieli ', N'modersmål, annat modersmål ', N'mother tongue, other mother tongue ', N'1050', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (89, CAST(N'2015-06-08' AS Date), N'011', N'äidinkieli, suomi toisena kielenä ', N'modersmål, finska som andra språk ', N'mother tongue, Finnish as a second language ', N'1060', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (90, CAST(N'2015-06-08' AS Date), N'012', N'äidinkieli, ruotsi toisena kielenä  ', N'modersmål, svenska som andra språk  ', N'mother tongue, Swedish as a second language  ', N'1070', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (91, CAST(N'2015-06-08' AS Date), N'013', N'matematiikka', N'matematik', N'mathematics', N'1080', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (92, CAST(N'2015-06-08' AS Date), N'014', N'tietotekniikka', N'IT', N'information technology', N'1090', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (93, CAST(N'2015-06-08' AS Date), N'015', N'fysiikka ja kemia', N'fysik och kemi', N'physics and chemistry', N'1100', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (94, CAST(N'2015-06-08' AS Date), N'016', N'ympäristötieto', N'miljökunskap', N'environmental education', N'1110', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (95, CAST(N'2015-06-08' AS Date), N'017', N'yhteiskunta- ja työelämätieto', N'samhälls- och arbetslivskunskap', N'citizenship and working life', N'1120', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (96, CAST(N'2015-06-08' AS Date), N'018', N'toinen kotimainen kieli (suomi)', N'andra inhemska språket (finska)', N'second national language (Finnish)', N'1130', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (97, CAST(N'2015-06-08' AS Date), N'019', N'toinen kotimainen kieli (ruotsi)', N'andra inhemska språket (svenska)', N'second national language (Swedish)', N'1140', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (98, CAST(N'2015-06-08' AS Date), N'020', N'englanti', N'engelska', N'english', N'1150', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (99, CAST(N'2015-06-08' AS Date), N'021', N'ranska', N'franska', N'french', N'1160', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (100, CAST(N'2015-06-08' AS Date), N'022', N'saksa', N'tyska', N'german', N'1170', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (101, CAST(N'2015-06-08' AS Date), N'023', N'venäjä', N'ryska', N'russian', N'1180', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (102, CAST(N'2015-06-08' AS Date), N'024', N'muu kieli', N'annat språk', N'other language', N'1190', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (103, CAST(N'2015-06-08' AS Date), N'025', N'yritystoiminnan perusteet', N'grunder i företagsverksamhet', N'basics of entrepreneurship', N'1200', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (104, CAST(N'2015-06-08' AS Date), N'026', N'psykologia', N'psykologi', N'psychology', N'1210', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (105, CAST(N'2015-06-08' AS Date), N'027', N'liikunta', N'gymnastik och idrott', N'physical education', N'1220', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (106, CAST(N'2015-06-08' AS Date), N'028', N'terveystieto', N'hälsokunskap', N'health education', N'1230', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (107, CAST(N'2015-06-08' AS Date), N'029', N'taide- ja kulttuuri', N'konst och kultur', N'arts and culture', N'1240', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (108, CAST(N'2015-06-08' AS Date), N'030', N'etiikka', N'etik', N'ethics', N'1250', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (109, CAST(N'2015-06-08' AS Date), N'031', N'vieraat kulttuurit', N'främmande kulturer', N'foreign cultures', N'1260', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (110, CAST(N'2015-06-08' AS Date), N'101', N'vapaa-aika- ja nuorisotyö', N'fritid och ungdomsarbete', N'leisure activities and youth work', N'1270', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (111, CAST(N'2015-06-08' AS Date), N'102', N'kielitieteet', N'språkvetenskaper', N'languages', N'1280', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (112, CAST(N'2015-06-08' AS Date), N'106', N'opetus- ja kasvatustyö', N'undervisnings- och fostringsarbete', N'teaching and education', N'1290', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (113, CAST(N'2015-06-08' AS Date), N'199', N'muu humanistisen ja kasvatusalan koulutus', N'annan humanistisk och pedagogisk utbildning', N'other education in humanities and education', N'1300', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (114, CAST(N'2015-06-08' AS Date), N'201', N'käsi- ja taideteollisuus', N'hantverks- och konstindustri', N'crafts and design', N'1310', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (115, CAST(N'2015-06-08' AS Date), N'202', N'viestintä ja informaatiotieteet', N'kommunikation och informationsvetenskaper', N'information and communication', N'1320', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (116, CAST(N'2017-02-09' AS Date), N'203', N'Kulttuuriala: Ympäristön suunnittelu ja rakentaminen', N'*SV*Kulttuuriala: Ympäristön suunnittelu ja rakentaminen', N'*EN*Kulttuuriala: Ympäristön suunnittelu ja rakentaminen', N'1330', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (117, CAST(N'2015-06-08' AS Date), N'204', N'teatteri ja tanssi', N'teater och dans', N'theatre and dance', N'1340', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (118, CAST(N'2015-06-08' AS Date), N'205', N'musiikki', N'musik', N'music', N'1350', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (119, CAST(N'2015-06-08' AS Date), N'206', N'kuvataide', N'bildkonst', N'visual arts', N'1360', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (120, CAST(N'2015-06-08' AS Date), N'299', N'muu kulttuurialan koulutus', N'annan kulturutbildning', N'other education in culture', N'1370', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (121, CAST(N'2015-06-08' AS Date), N'301', N'liiketalous ja kauppa', N'företagsekonomi och handel', N'business and commerce', N'1380', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (122, CAST(N'2015-06-08' AS Date), N'303', N'hallinto ', N'administration ', N'administration ', N'1390', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (123, CAST(N'2015-06-08' AS Date), N'399', N'muu yhteiskuntatieteiden, liiketalouden ja hallinnon alan koulutus', N'andra samhällsvetenskaper, företagsekonomi och administration', N'other social sciences, business and administration', N'1400', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (124, CAST(N'2015-06-08' AS Date), N'402', N'tietojenkäsittely   ', N'databehandling   ', N'computing and software   ', N'1410', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (125, CAST(N'2015-06-08' AS Date), N'499', N'muu luonnontieteiden alan koulutus', N'annan naturvetenskaplig utbildning', N'other education in natural sciences', N'1420', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (126, CAST(N'2015-06-08' AS Date), N'501', N'arkkitehtuuri ja rakentaminen', N'arkitektur och byggande', N'architecture and construction', N'1430', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (127, CAST(N'2015-06-08' AS Date), N'502', N'kone-, metalli- ja energiatekniikka', N'maskin-, metall- och energiteknik', N'mechanical, metal and energy engineering', N'1440', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (128, CAST(N'2015-06-08' AS Date), N'503', N'sähkö- ja automaatiotekniikka', N'el- och automationsteknik', N'electrical and automation engineering', N'1450', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (129, CAST(N'2015-06-08' AS Date), N'504', N'tieto- ja tietoliikennetekniikka', N'informations- och datakommunikationsteknik', N'information and telecommunications technology', N'1460', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (130, CAST(N'2015-06-08' AS Date), N'505', N'graafinen ja viestintätekniikka', N'grafisk teknik och kommunikationsteknik', N'graphics and communications technology', N'1470', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (131, CAST(N'2015-06-08' AS Date), N'506', N'elintarvikeala ja biotekniikka', N'livsmedelsbranschen och bioteknik', N'food sciences, food industry and biotechnology', N'1480', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (132, CAST(N'2015-06-08' AS Date), N'507', N'prosessi-, kemian- ja materiaalitekniikka', N'process- kemi- och materialteknik', N'process, chemical and materials engineering', N'1490', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (133, CAST(N'2015-06-08' AS Date), N'508', N'tekstiili- ja vaatetustekniikka', N'textil- och beklädnadsteknik', N'textiles and clothing technology', N'1500', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (134, CAST(N'2015-06-08' AS Date), N'509', N'ajoneuvo- ja kuljetustekniikka', N'fordons- och transportteknik', N'automotive and transport engineering', N'1510', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (135, CAST(N'2015-06-08' AS Date), N'510', N'tuotantotalous', N'produktionsekonomi', N'industrial management', N'1520', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (136, CAST(N'2015-06-08' AS Date), N'599', N'muu tekniikan ja liikenteen alan koulutus', N'annan teknik- och trafikutbildning', N'other education in technology, communications and transport', N'1530', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (137, CAST(N'2015-06-08' AS Date), N'601', N'maatilatalous', N'lantbruksnäring', N'agriculture', N'1540', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (138, CAST(N'2015-06-08' AS Date), N'602', N'puutarhatalous', N'trädgårdsnäring', N'horticulture', N'1550', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (139, CAST(N'2015-06-08' AS Date), N'603', N'kalatalous', N'fiskeri', N'fishery', N'1560', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (140, CAST(N'2015-06-08' AS Date), N'604', N'metsätalous', N'skogsbruk', N'forestry', N'1570', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (141, CAST(N'2015-06-08' AS Date), N'605', N'luonto- ja ympäristöala', N'natur- och miljöbranschen', N'nature and the environment', N'1580', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (142, CAST(N'2015-06-08' AS Date), N'699', N'muu luonnonvara- ja ympäristöalan koulutus', N'annan utbildning inom naturresurs- och miljöområdet', N'other education in natural resources and the environment', N'1590', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (143, CAST(N'2015-06-08' AS Date), N'701', N'sosiaaliala', N'socialbranschen', N'social services', N'1600', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (144, CAST(N'2015-06-08' AS Date), N'702', N'terveysala', N'hälso- och sjukvårdsbranschen', N'health care', N'1610', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (145, CAST(N'2015-06-08' AS Date), N'703', N'sosiaali- ja terveysala (alojen yhteiset ohjelmat)', N'social- och hälsovårdsbranschen (gemensamma program för branscherna)', N'health care and social services (shared programmes)', N'1620', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (146, CAST(N'2015-06-08' AS Date), N'704', N'hammaslääketiede ja muu hammashuolto', N'odontologi och annan tandvård', N'dentistry and other dental services', N'1630', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (147, CAST(N'2015-06-08' AS Date), N'705', N'kuntoutus ja liikunta', N'rehabilitering, gymnastik och idrott', N'rehabilitation and sports', N'1640', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (148, CAST(N'2015-06-08' AS Date), N'706', N'tekniset terveyspalvelut', N'tekniska hälso- och sjukvårdstjänster', N'technical health services', N'1650', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (149, CAST(N'2015-06-08' AS Date), N'710', N'kauneudenhoitoala', N'skönhetsvård', N'beauty care', N'1660', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (150, CAST(N'2015-06-08' AS Date), N'799', N'muu sosiaali- ja terveys- ja liikunta-alan koulutus', N'annan utbildning inom social- och hälsovårdsområdet samt gymnastik och idrott', N'other education in social services, health and sports', N'1670', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (151, CAST(N'2015-06-08' AS Date), N'801', N'matkailuala', N'turism', N'tourism', N'1680', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (152, CAST(N'2015-06-08' AS Date), N'802', N'majoitus- ja ravitsemisala', N'inkvarterings- och restaurangbranschen', N'hotel and catering', N'1690', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (153, CAST(N'2015-06-08' AS Date), N'804', N'kotitalous- ja kuluttajapalvelut', N'hushålls- och konsumenttjänster', N'domestic and consumer services', N'1700', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (154, CAST(N'2015-06-08' AS Date), N'899', N'muu matkailu-, ravitsemis- ja talousalan koulutus', N'annan utbildning inom turist-, kosthålls- och ekonomiområdet', N'other education in tourism, catering and domestic services', N'1710', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (155, CAST(N'2015-06-08' AS Date), N'901', N'lukio-opetus', N'gymnasieundervisning', N'general upper secondary school', N'1720', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (156, CAST(N'2015-06-08' AS Date), N'932', N'aikuisten maahanmuuttajien kotoutumiskoulutus', N'integrationsutbildning för vuxna invandrare', N'integration training for adult immigrants', N'1730', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (157, CAST(N'2015-06-08' AS Date), N'933', N'luku- ja kirjoitustaidottomien maahanmuuttajien koulutus', N'utbildning för läs- och skrivokunniga invandrare', N'education for illiterate immigrants', N'1740', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (158, CAST(N'2015-06-08' AS Date), N'999', N'muu opetus', N'annan undervisning', N'other education', N'1750', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Anssi', CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (2, CAST(N'2020-02-12' AS Date), N'2', N'Viestintä ja vuorovaikutus äidinkielellä, ruotsi', N'Kommunikation och interaktion på modersmålet, svenska', N'Communication and interaction in mother tongue, Swedish', N'2020', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (3, CAST(N'2020-02-12' AS Date), N'3', N'Viestintä ja vuorovaikutus äidinkielellä, saame', N'Kommunikation och interaktion på modersmålet, samiska', N'Communication and interaction in mother tongue, Sámi', N'2030', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (4, CAST(N'2020-02-12' AS Date), N'4', N'Viestintä ja vuorovaikutus äidinkielellä, viittomakieli', N'Kommunikation och interaktion på modersmålet, teckenspråk', N'Communication and interaction in mother tongue, sign language', N'2040', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (5, CAST(N'2020-02-12' AS Date), N'5', N'Viestintä ja vuorovaikutus äidinkielellä, romani', N'Kommunikation och interaktion på modersmålet, romerska', N'Communication and interaction in mother tongue, the Roma language', N'2050', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (1, CAST(N'2020-02-12' AS Date), N'1', N'Viestintä ja vuorovaikutus äidinkielellä, suomi', N'Kommunikation och interaktion på modersmålet, finska', N'Communication and interaction in mother tongue, Finnish', N'2010', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (6, CAST(N'2020-02-12' AS Date), N'6', N'Viestintä ja vuorovaikutus äidinkielellä, muu opiskelijan äidinkieli', N'Kommunikation och interaktion på modersmålet, annat modersmål', N'Communication and interaction in mother tongue, other mother tongue', N'2060', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (7, CAST(N'2020-02-12' AS Date), N'7', N'Viestintä ja vuorovaikutus äidinkielellä, suomi viittomakielisille', N'Kommunikation och interaktion på modersmålet, finska för teckenspråkiga', N'Communication and interaction in mother tongue, Finnish for sign language users', N'2070', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (8, CAST(N'2020-02-12' AS Date), N'8', N'Viestintä ja vuorovaikutus äidinkielellä, suomi toisena kielenä', N'Kommunikation och interaktion på modersmålet, finska som andraspråk', N'Communication and interaction in mother tongue, Finnish as a second language', N'2080', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (9, CAST(N'2020-02-12' AS Date), N'9', N'Viestintä ja vuorovaikutus äidinkielellä, ruotsi toisena kielenä', N'Kommunikation och interaktion på modersmålet, svenska som andraspråk', N'Communication and interaction in mother tongue, Swedish as a second language', N'2090', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (10, CAST(N'2020-02-12' AS Date), N'10', N'Viestintä ja vuorovaikutus toisella kotimaisella kielellä, ruotsi', N'Kommunikation och interaktion på det andra inhemska språket, svenska', N'Communication and interaction in the second national language, Swedish', N'2100', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (11, CAST(N'2020-02-12' AS Date), N'11', N'Viestintä ja vuorovaikutus toisella kotimaisella kielellä, suomi', N'Kommunikation och interaktion på det andra inhemska språket, finska', N'Communication and interaction in the second national language, Finnish', N'2110', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (12, CAST(N'2020-02-12' AS Date), N'12', N'Viestintä ja vuorovaikutus vieraalla kielellä', N'Kommunikation och interaktion på ett främmande språk', N'Communication and interaction in a foreign language', N'2120', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (13, CAST(N'2020-02-12' AS Date), N'13', N'Toiminta digitaalisessa ympäristössä', N'Verksamhet i den digitala miljön', N'Operating in a digital environment', N'2130', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (14, CAST(N'2020-02-12' AS Date), N'14', N'Taide ja luova ilmaisu', N'Konst och kreativt uttryck', N'Art and creative expression', N'2140', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (15, CAST(N'2020-02-12' AS Date), N'15', N'Matematiikka ja matematiikan soveltaminen', N'Matematik och tillämpad matematik', N'Mathematics and application of mathematics', N'2150', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (16, CAST(N'2020-02-12' AS Date), N'16', N'Fysikaaliset ja kemialliset ilmiöt ja niiden soveltaminen', N'Fysikaliska och kemiska fenomen och tillämpning av dem', N'Physical and chemical phenomena and their application', N'2160', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (17, CAST(N'2020-02-12' AS Date), N'17', N'Yhteiskunnassa ja kansalaisena toimiminen', N'Att verka i samhället och som medborgare', N'Operating as a member of society and a citizen', N'2170', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (18, CAST(N'2020-02-12' AS Date), N'18', N'Työelämässä toimiminen', N'Att verka i arbetslivet', N'Operating in the world of work', N'2180', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (19, CAST(N'2020-02-12' AS Date), N'19', N'Opiskelu- ja urasuunnitteluvalmiudet', N'Färdigheter i studie- och karriärplanering', N'Study and career planning capabilities', N'2190', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (20, CAST(N'2020-02-12' AS Date), N'20', N'Yrittäjyys ja yrittäjämäinen toiminta', N'Företagsamhet och företagarinriktad verksamhet', N'Entrepreneurship and entrepreneurial activities', N'2200', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (21, CAST(N'2020-02-12' AS Date), N'21', N'Työkyvyn ja hyvinvoinnin ylläpitäminen', N'Upprätthållande av arbetsförmågan och välbefinnandet', N'Maintaining ability to work and wellbeing at work', N'2210', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (22, CAST(N'2020-02-12' AS Date), N'22', N'Kestävän kehityksen edistäminen', N'Främjande av hållbar utveckling', N'Promotion of sustainable development', N'2220', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (23, CAST(N'2020-02-12' AS Date), N'23', N'Ajoneuvo- ja kuljetustekniikka', N'Fordons- och transportteknik', N'Automotive and transport engineering', N'2230', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (24, CAST(N'2020-02-12' AS Date), N'24', N'Kielitieteet', N'Språkvetenskaper', N'Languages', N'2240', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (25, CAST(N'2020-02-12' AS Date), N'25', N'Käsi- ja taideteollisuus', N'Hantverk och konstindustri', N'Crafts and design', N'2250', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (26, CAST(N'2020-02-12' AS Date), N'26', N'Viestintä ja informaatiotieteet', N'Mediekultur och informationsvetenskaper', N'Information and communication', N'2260', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (27, CAST(N'2020-02-12' AS Date), N'27', N'Teatteri ja tanssi', N'Teater och dans', N'Theatre and dance', N'2270', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (28, CAST(N'2020-02-12' AS Date), N'28', N'Musiikki', N'Musik', N'Music', N'2280', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (29, CAST(N'2020-02-12' AS Date), N'29', N'Graafinen ja viestintätekniikka', N'Grafisk teknik och medieteknik', N'Graphics and communications technology', N'2290', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (30, CAST(N'2020-02-12' AS Date), N'30', N'Prosessi-, kemian- ja materiaalitekniikka', N'Process-, kemi- och materialteknik', N'Process, chemical and materials engineering', N'2300', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (31, CAST(N'2020-02-12' AS Date), N'31', N'Muu tekniikan ja liikenteen alan koulutus', N'Övrig utbildning inom teknik och kommunikation', N'Other education in technology, communications and transport', N'2310', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (32, CAST(N'2020-02-12' AS Date), N'32', N'Sosiaali- ja terveysala (alojen yhteiset ohjelmat)', N'Social- och hälsoområdet (gemensamma program)', N'Health care and social services', N'2320', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (33, CAST(N'2020-02-12' AS Date), N'33', N'Viestintä ja informaatiotieteet', N'Mediekultur och informationsvetenskaper', N'Information and communication', N'2330', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (62, CAST(N'2020-02-12' AS Date), N'62', N'Muu humanistisen ja kasvatusalan koulutus', N'Övrig utbildning inom det humanistiska och pedagogiska området', N'Other education in humanities and education', N'2620', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (34, CAST(N'2020-02-12' AS Date), N'34', N'Liiketalous ja kauppa', N'Företagsekonomi och handel', N'Business and commerce', N'2340', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (35, CAST(N'2020-02-12' AS Date), N'35', N'Liiketalous ja kauppa', N'Företagsekonomi och handel', N'Business and commerce', N'2350', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (36, CAST(N'2020-02-12' AS Date), N'36', N'Kone-, metalli- ja energiatekniikka', N'Maskin-, metall- och energiteknik', N'Mechanical, metal and energy engineering', N'2360', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (37, CAST(N'2020-02-12' AS Date), N'37', N'Ajoneuvo- ja kuljetustekniikka', N'Fordons- och transportteknik', N'Automotive and transport engineering', N'2370', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (38, CAST(N'2020-02-12' AS Date), N'38', N'Muu tekniikan ja liikenteen alan koulutus', N'Övrig utbildning inom teknik och kommunikation', N'Other education in technology, communications and transport', N'2380', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (39, CAST(N'2020-02-12' AS Date), N'39', N'Majoitus- ja ravitsemisala', N'Inkvarterings- och kosthållsbranschen', N'Hotel and catering', N'2390', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (40, CAST(N'2020-02-12' AS Date), N'40', N'Luonto- ja ympäristöala', N'Natur- och miljöområdet', N'Nature and the environment', N'2400', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (41, CAST(N'2020-02-12' AS Date), N'41', N'Tietojenkäsittely', N'Databehandling', N'Computing and software', N'2410', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (42, CAST(N'2020-02-12' AS Date), N'42', N'Tieto- ja tietoliikennetekniikka', N'Informations- och kommunikationsteknik', N'Information and telecommunications technology', N'2420', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (43, CAST(N'2020-02-12' AS Date), N'43', N'Käsi- ja taideteollisuus', N'Hantverk och konstindustri', N'Crafts and design', N'2430', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (44, CAST(N'2020-02-12' AS Date), N'44', N'Arkkitehtuuri ja rakentaminen', N'Arkitektur och byggande', N'Architecture and construction', N'2440', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (45, CAST(N'2020-02-12' AS Date), N'45', N'Kone-, metalli- ja energiatekniikka', N'Maskin-, metall- och energiteknik', N'Mechanical, metal and energy engineering', N'2450', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (46, CAST(N'2020-02-12' AS Date), N'46', N'Sähkö- ja automaatiotekniikka', N'El- och automationsteknik', N'Electrical and automation engineering', N'2460', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (47, CAST(N'2020-02-12' AS Date), N'47', N'Elintarvikeala ja biotekniikka', N'Livsmedelsbranschen och bioteknik', N'Food sciences, food industry and biotechnology', N'2470', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (48, CAST(N'2020-02-12' AS Date), N'48', N'Prosessi-, kemian- ja materiaalitekniikka', N'Process-, kemi- och materialteknik', N'Process, chemical and materials engineering', N'2480', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (49, CAST(N'2020-02-12' AS Date), N'49', N'Tekstiili- ja vaatetustekniikka', N'Textil- och beklädnadsteknik', N'Textiles and clothing technology', N'2490', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (50, CAST(N'2020-02-12' AS Date), N'50', N'Ajoneuvo- ja kuljetustekniikka', N'Fordons- och transportteknik', N'Automotive and transport engineering', N'2500', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (51, CAST(N'2020-02-12' AS Date), N'51', N'Muu tekniikan ja liikenteen alan koulutus', N'Övrig utbildning inom teknik och kommunikation', N'Other education in technology, communications and transport', N'2510', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (52, CAST(N'2020-02-12' AS Date), N'52', N'Maatilatalous', N'Lantbruk', N'Agriculture', N'2520', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (53, CAST(N'2020-02-12' AS Date), N'53', N'Puutarhatalous', N'Trädgårdsskötsel', N'Horticulture', N'2530', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (54, CAST(N'2020-02-12' AS Date), N'54', N'Maatilatalous', N'Lantbruk', N'Agriculture', N'2540', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (55, CAST(N'2020-02-12' AS Date), N'55', N'Puutarhatalous', N'Trädgårdsskötsel', N'Horticulture', N'2550', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (56, CAST(N'2020-02-12' AS Date), N'56', N'Kalatalous', N'Fiskeri', N'Fishery', N'2560', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (57, CAST(N'2020-02-12' AS Date), N'57', N'Metsätalous', N'Skogsbruk', N'Forestry', N'2570', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (58, CAST(N'2020-02-12' AS Date), N'58', N'Luonto- ja ympäristöala', N'Natur- och miljöområdet', N'Nature and the environment', N'2580', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (59, CAST(N'2020-02-12' AS Date), N'59', N'Muu luonnonvara- ja ympäristöalan koulutus', N'Övrig utbildning inom naturbruk och miljöområdet', N'Other education in natural resources and the environment', N'2590', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (61, CAST(N'2020-02-12' AS Date), N'61', N'Opetus- ja kasvatustyö', N'Undervisning och fostran', N'Teaching and education', N'2610', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (60, CAST(N'2020-02-12' AS Date), N'60', N'Vapaa-aika ja nuorisotyö', N'Fritidsverksamhet och ungdomsarbete', N'Leisure activities and youth work', N'2600', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (63, CAST(N'2020-02-12' AS Date), N'63', N'Sosiaaliala', N'Socialområdet', N'Social services', N'2630', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (64, CAST(N'2020-02-12' AS Date), N'64', N'Terveysala', N'Hälsoområdet', N'Health care', N'2640', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (65, CAST(N'2020-02-12' AS Date), N'65', N'Sosiaali- ja terveysala (alojen yhteiset ohjelmat)', N'Social- och hälsoområdet (gemensamma program)', N'Health care and social services', N'2650', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (66, CAST(N'2020-02-12' AS Date), N'66', N'Hammaslääketiede ja muu hammashuolto', N'Odontologi och annan tandvård', N'Dentistry and other dental services', N'2660', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (67, CAST(N'2020-02-12' AS Date), N'67', N'Kuntoutus ja liikunta', N'Rehabilitering och idrott', N'Rehabilitation and sports', N'2670', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (68, CAST(N'2020-02-12' AS Date), N'68', N'Tekniset terveyspalvelut', N'Teknisk hälsoservice', N'Technical health services', N'2680', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (69, CAST(N'2020-02-12' AS Date), N'69', N'Farmasia ja muu lääkehuolto', N'Farmaci och annan läkemedelsförsörjning', N'Pharmacy and other pharmacological services', N'2690', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (70, CAST(N'2020-02-12' AS Date), N'70', N'Muu humanistisen ja kasvatusalan koulutus', N'Övrig utbildning inom det humanistiska och pedagogiska området', N'Other education in humanities and education', N'2700', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (71, CAST(N'2020-02-12' AS Date), N'71', N'Liiketalous ja kauppa', N'Företagsekonomi och handel', N'Business and commerce', N'2710', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (72, CAST(N'2020-02-12' AS Date), N'72', N'Tekstiili- ja vaatetustekniikka', N'Textil- och beklädnadsteknik', N'Textiles and clothing technology', N'2720', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (73, CAST(N'2020-02-12' AS Date), N'73', N'Ajoneuvo- ja kuljetustekniikka', N'Fordons- och transportteknik', N'Automotive and transport engineering', N'2730', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (74, CAST(N'2020-02-12' AS Date), N'74', N'Muu tekniikan ja liikenteen alan koulutus', N'Övrig utbildning inom teknik och kommunikation', N'Other education in technology, communications and transport', N'2740', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (75, CAST(N'2020-02-12' AS Date), N'75', N'Kuntoutus ja liikunta', N'Rehabilitering och idrott', N'Rehabilitation and sports', N'2750', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (76, CAST(N'2020-02-12' AS Date), N'76', N'Kauneudenhoitoala', N'Skönhetsområdet', N'Beauty care', N'2760', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (77, CAST(N'2020-02-12' AS Date), N'77', N'Matkailuala', N'Turism', N'Tourism', N'2770', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (78, CAST(N'2020-02-12' AS Date), N'78', N'Majoitus- ja ravitsemisala', N'Inkvarterings- och kosthållsbranschen', N'Hotel and catering', N'2780', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (79, CAST(N'2020-02-12' AS Date), N'79', N'Kotitalous- ja kuluttajapalvelut', N'Huslig ekonomi och konsumentservice', N'Domestic and consumer services', N'2790', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (80, CAST(N'2020-02-12' AS Date), N'80', N'Puhdistuspalvelut', N'Rengöringsservice', N'Cleaning services', N'2800', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (81, CAST(N'2020-02-12' AS Date), N'81', N'Lukio-opetus', N'Gymnasieundervisning', N'General upper secondary school education', N'2810', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO
INSERT [dbo].[opettajat_aine_amm] ([id], [luotu], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [kommentti], [alkaa], [paattyy]) VALUES (82, CAST(N'2020-02-12' AS Date), N'82', N'Muu opetus', N'Annan undervisning', N'Other education', N'2820', N'E         ', N' ', N'Tilastokeskus 7-aineistot', N'CSC Juha', CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date))
GO

USE [ANTERO]
