USE [VipunenTK_lisatiedot]
GO
/****** Object:  Table [dbo].[opettajat_aine_vst]    Script Date: 6.2.2020 14:58:47 ******/
DROP TABLE [dbo].[opettajat_aine_vst]
GO
/****** Object:  Table [dbo].[opettajat_aine_vst]    Script Date: 6.2.2020 14:58:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[opettajat_aine_vst](
	[id] [int] NOT NULL,
	[alkaa] [date] NULL,
	[paattyy] [date] NULL,
	[aine_koodi] [nvarchar](3) NULL,
	[aine] [nvarchar](255) NULL,
	[aine_SV] [nvarchar](255) NULL,
	[aine_EN] [nvarchar](255) NULL,
	[jarjestys] [nvarchar](50) NULL,
	[virhetilanne] [nchar](10) NULL,
	[poistettu] [nchar](1) NULL,
	[tietolahde] [nvarchar](50) NULL,
	[luotu] [date] NULL,
	[kommentti] [nvarchar](250) NULL
) ON [PRIMARY]

GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (-1, CAST(N'2010-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'-1', N'Tuntematon', N'Information saknas', N'Missing data', N'1980', N'K         ', N' ', N'Manuaalinen', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (-2, CAST(N'2010-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'-2', N'Virhetilanne', N'Feltillstånd', N'Error occurred', N'1990', N'K         ', N' ', N'Manuaalinen', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (1, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'1', N'Äidinkieli, suomi  toisena kielenä', N'Modersmål, finska som andra språk', N'Mother tongue, Finnish as a second language', N'1000', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (2, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'2', N'Äidinkieli, ruotsi  toisena kielenä', N'Modersmål, svenska som andra språk', N'Mother tongue, Swedish as a second language', N'1010', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (3, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'3', N'Suomalainen yhteiskunta- ja työelämätieto  ', N'Finländsk samhälls- och arbetslivskunskap', N'Finnish society and working life  ', N'1020', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (4, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'4', N'Muu maahanmuuttajille tarkoitettu opetus ', N'Annan undervisning avsedd för invandrare ', N'Other education intended for migrants ', N'1030', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (5, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'5', N'Luku- ja kirjoitustaidon opetus, suomi', N'Undervisning i läs- och skrivkunnighet, finska', N'Literacy education, Finnish', N'1035', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (6, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'6', N'Luku- ja kirjoitustaidon opetus, ruotsi', N'Undervisning i läs- och skrivkunnighet, svenska', N'Literacy education, Swedish', N'1036', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (7, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'7', N'Vapaa-aika ja nuorisotyö', N'Fritid och ungdomsarbete', N'Leisure time and youth work', N'1040', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (8, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'8', N'Kielitieteet', N'Språkvetenskaper', N'Languages', N'1050', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (9, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'9', N'Historia ja arkeologia', N'Historia och arkeologi', N'History and archaeology', N'1060', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (10, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'10', N'Filosofia', N'Filosofi', N'Philosophy', N'1070', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (11, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'11', N'Kasvatustieteet ja psykologia ', N'Pedagogik och psykologi ', N'Educational sciences and psychology ', N'1080', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (12, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'12', N'Opetus- ja kasvatustyö', N'Undervisnings- och fostringsarbete', N'Teaching and education', N'1090', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (13, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'13', N'Teologia', N'Teologi', N'Theology', N'1100', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (14, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'14', N'Muu humanistisen ja kasvatusalan koulutus', N'Annan humanistisk och pedagogisk utbildning', N'Other education in humanities and education', N'1110', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (15, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'15', N'Käsi- ja taideteollisuus', N'Hantverks- och konstindustri', N'Crafts and design', N'1120', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (16, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'16', N'Viestintä- ja informaatiotieteet', N'Kommunikations- och informationsvetenskaper', N'Information and communication', N'1130', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (17, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'17', N'Kirjallisuus', N'Litteratur', N'Literature', N'1140', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (18, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'18', N'Teatteri ja tanssi', N'Teater och dans', N'Theatre and dance', N'1150', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (19, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'19', N'Musiikki', N'Musik', N'Music', N'1160', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (20, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'20', N'Kuvataide', N'Bildkonst', N'Visual arts', N'1170', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (21, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'21', N'Kulttuurin ja taiteiden tutkimus', N'Kultur- och konstforskning', N'Cultural and arts research', N'1180', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (22, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'22', N'Muu kulttuurialan koulutus', N'Annan kulturutbildning', N'Other education in culture', N'1190', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (23, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'23', N'Liiketalous ja kauppa', N'Företagsekonomi och handel', N'Business and commerce', N'1200', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (24, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'24', N'Kansantalous', N'Nationalekonomi', N'Economics', N'1210', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (25, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'25', N'Hallinto', N'Förvaltning', N'Administration', N'1220', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (26, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'26', N'Tilastotiede', N'Statistikvetenskap', N'Statistics', N'1230', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (27, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'27', N'Sosiaalitieteet', N'Socialvetenskaper', N'Social sciences', N'1240', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (28, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'28', N'Politiikkatieteet', N'Politikvetenskaper', N'Political sciences', N'1250', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (29, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'29', N'Oikeustiede', N'Juridik', N'Law', N'1260', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (31, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'31', N'Matematiikka', N'Matematik', N'Mathematics', N'1280', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (30, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'30', N'Muu yhteiskuntatieteiden, liiketalouden ja hallinnon alan koulutus ', N'Annan utbildning inom samhällsvetenskap, företagsekonomi och förvaltning ', N'Other education in social sciences, business and administration ', N'1270', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (32, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'32', N'Tietojenkäsittely', N'Databehandling', N'Computing and software', N'1290', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (33, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'33', N'Geo-, avaruus-, ja tähtitieteet', N'Geo- och rymdvetenskap, astronomi', N'Earth and space sciences and astronomy', N'1300', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (35, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'35', N'Kemia', N'Kemi', N'Chemistry', N'1320', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (36, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'36', N'Biologia', N'Biologi', N'Biology', N'1330', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (37, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'37', N'Maantiede', N'Geografi', N'Geography', N'1340', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (38, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'38', N'Muu luonnontieteiden alan koulutus', N'Annan naturvetenskaplig utbildning', N'Other education in natural sciences', N'1350', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (39, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'39', N'Arkkitehtuuri ja rakentaminen', N'Arkitektur och byggande', N'Architecture and construction', N'1360', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (40, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'40', N'Kone-metalli-ja energiatekniikka', N'Maskin-, metall- och energiteknik', N'Mechanical, metal and energy engineering', N'1370', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (41, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'41', N'Sähkö-ja automaatiotekniikka', N'El- och automationsteknik', N'Electrical and automation engineering', N'1380', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (42, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'42', N'Tieto-ja tietoliikennetekniikka', N'Data- och datakommunikationsteknik', N'Information and telecommunications technology', N'1390', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (43, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'43', N'Graafinen viestintätekniikka', N'Grafisk kommunikationsteknik', N'Graphics and communications technology', N'1400', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (44, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'44', N'Elintarvikeala ja biotekniikka', N'Livsmedelsbranschen och bioteknik', N'Food sciences, food industry and biotechnology', N'1410', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (45, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'45', N'Prosessi-, kemian- ja materiaalitekniikka', N'Process- och materialteknik kemisk teknik', N'Process, chemical and materials engineering', N'1420', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (46, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'46', N'Tekstiili-ja vaatetustekniikka', N'Textil- och beklädnadsteknik', N'Textiles and clothing technology', N'1430', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (47, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'47', N'Ajoneuvo-ja kuljetustekniikka', N'Fordons- och transportteknik', N'Automotive and transport engineering', N'1440', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (48, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'48', N'Tuotantotalous', N'Produktionsteknik', N'Industrial management', N'1450', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (49, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'49', N'Muu tekniikan ja liikenteen alan koulutus ', N'Annan utbildning inom teknik och trafik ', N'Other education in technology, communications and transport ', N'1460', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (50, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'50', N'Maatilatalous', N'Jordbruk', N'Agriculture', N'1470', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (51, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'51', N'Puutarhatalous', N'Trädgårdsekonomi', N'Horticulture', N'1480', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (52, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'52', N'Kalatalous', N'Fiske', N'Fishery', N'1490', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (53, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'53', N'Metsätalous', N'Skogsbruk', N'Forestry', N'1500', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (54, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'54', N'Luonto-ja ympäristöala', N'Natur- och miljöbranschen', N'Nature and the environment', N'1510', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (56, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'56', N'Sosiaaliala', N'Socialbranschen', N'Social services', N'1530', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (57, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'57', N'Terveysala', N'Hälso- och sjukvårdsbranschen', N'Health care', N'1540', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (59, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'59', N'Hammaslääketiede ja muu hammashuolto', N'odontologi och annan tandvård', N'Dentistry and other dental services', N'1560', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (60, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'60', N'Kuntoutus ja liikunta', N'Rehabilitering, gymnastik och idrott', N'Rehabilitation and sports', N'1570', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (34, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'34', N'Fysiikka', N'Fysik', N'Physics', N'1310', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (55, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'55', N'Muu luonnonvara- ja ympäristöalan koulutus', N'Annan naturresurs- och miljöutbildning', N'Other education in natural resources and the environment', N'1520', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (58, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'58', N'Sosiaali-ja terveysala (alojen yhteiset ohjelmat)', N'Social- och hälsovårdsbranschen (gemensamma program för branscherna)', N'Health care and social services (shared programmes)', N'1550', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (61, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'61', N'Tekniset terveyspalvelut', N'Tekniska hälsovårdstjänster', N'Technical health services', N'1580', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (62, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'62', N'Farmasia ja muu lääkehuolto', N'Farmaci och annan läkemedelsförsörjning', N'Pharmacy and other pharmacological services', N'1590', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (63, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'63', N'Lääketiede', N'Medicin', N'Medicine', N'1600', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (64, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'64', N'Eläinlääketiede', N'Veterinärmedicin', N'Veterinary medicine', N'1610', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (65, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'65', N'Kauneudenhoitoala', N'Skönhetsvård', N'Beauty care', N'1620', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (66, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'66', N'Muu sosiaali-, terveys- ja liikunta-alan koulutus', N'Annan utbildning inom social- och hälsovård, gymnastik och idrott', N'Other education in social services, health and sports', N'1630', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (67, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'67', N'Matkailuala', N'Turism', N'Tourism', N'1640', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (68, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'68', N'Majoitus-ja ravitsemisala', N'Hotell- och restaurangbranschen', N'Hotel and catering', N'1650', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (69, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'69', N'Kotitalous-ja kuluttajapalvelut', N'Hushålls- och konsumenttjänster', N'Domestic and consumer services', N'1660', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (70, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'70', N'Puhdistuspalvelut', N'Renhållningstjänster', N'Cleaning services', N'1670', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (71, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'71', N'Muu matkailu-, ravitsemis- ja talousalan koulutus', N'Annan turism-, restaurang- och huhållsutbildning', N'Other education in tourism, catering and domestic services', N'1680', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (72, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'72', N'Sotilas-ja rajavartioala', N'Militär- och gränsbevakningsbranschen', N'Military and border guard', N'1690', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (73, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'73', N'Palo-ja pelastusala', N'Brand- och räddningsbranschen', N'Fire and rescue services', N'1700', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (74, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'74', N'Poliisiala', N'Polisbranschen', N'Police services', N'1710', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (75, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'75', N'Vankeinhoito', N'Fångvård', N'Correctional services', N'1720', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (76, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'76', N'Muu opetusministeriön hallinnonalan ulkopuolella järjestettävä koulutus', N'Annan utbildning som ordnas utanför undervisningsministeriets förvaltningsområde', N'Other education outside the Ministry of Education sector', N'1730', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (77, CAST(N'2019-01-01' AS Date), CAST(N'9999-01-01' AS Date), N'77', N'Muu opetusministeriön hallinnonalalla järjestettävä koulutus', N'Annan utbildning som ordnas inom undervisningsministeriets förvaltningsområde', N'Other education in the Ministry of Education sector', N'1731', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2020-02-06' AS Date), N'CSC Juha')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (78, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'001', N'Äidinkieli, suomi  toisena kielenä', N'Modersmål, finska som andra språk', N'Mother tongue, Finnish as a second language', N'1000', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (79, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'002', N'Äidinkieli, ruotsi  toisena kielenä', N'Modersmål, svenska som andra språk', N'Mother tongue, Swedish as a second language', N'1010', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (80, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'003', N'Suomalainen yhteiskunta- ja työelämätieto  ', N'Finländsk samhälls- och arbetslivskunskap', N'Finnish society and working life  ', N'1020', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (81, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'099', N'Muu maahanmuuttajille tarkoitettu opetus ', N'Annan undervisning avsedd för invandrare ', N'Other education intended for migrants ', N'1030', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (82, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'101', N'Vapaa-aika ja nuorisotyö', N'Fritid och ungdomsarbete', N'Leisure time and youth work', N'1040', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (83, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'102', N'Kielitieteet', N'Språkvetenskaper', N'Languages', N'1050', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (84, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'103', N'Historia ja arkeologia', N'Historia och arkeologi', N'History and archaeology', N'1060', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (85, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'104', N'Filosofia', N'Filosofi', N'Philosophy', N'1070', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (86, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'105', N'Kasvatustieteet ja psykologia ', N'Pedagogik och psykologi ', N'Educational sciences and psychology ', N'1080', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (87, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'106', N'Opetus- ja kasvatustyö', N'Undervisnings- och fostringsarbete', N'Teaching and education', N'1090', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (88, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'107', N'Teologia', N'Teologi', N'Theology', N'1100', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (89, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'199', N'Muu humanistisen ja kasvatusalan koulutus', N'Annan humanistisk och pedagogisk utbildning', N'Other education in humanities and education', N'1110', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (90, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'202', N'Käsi- ja taideteollisuus', N'Hantverks- och konstindustri', N'Crafts and design', N'1120', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (91, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'203', N'Viestintä- ja informaatiotieteet', N'Kommunikations- och informationsvetenskaper', N'Information and communication', N'1130', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (92, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'204', N'Kirjallisuus', N'Litteratur', N'Literature', N'1140', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (93, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'205', N'Teatteri ja tanssi', N'Teater och dans', N'Theatre and dance', N'1150', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (94, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'206', N'Musiikki', N'Musik', N'Music', N'1160', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (95, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'207', N'Kuvataide', N'Bildkonst', N'Visual arts', N'1170', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (96, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'208', N'Kulttuurin ja taiteiden tutkimus', N'Kultur- och konstforskning', N'Cultural and arts research', N'1180', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (97, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'299', N'Muu kulttuurialan koulutus', N'Annan kulturutbildning', N'Other education in culture', N'1190', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (98, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'301', N'Liiketalous ja kauppa', N'Företagsekonomi och handel', N'Business and commerce', N'1200', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (99, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'302', N'Kansantalous', N'Nationalekonomi', N'Economics', N'1210', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (100, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'303', N'Hallinto', N'Förvaltning', N'Administration', N'1220', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (101, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'304', N'Tilastotiede', N'Statistikvetenskap', N'Statistics', N'1230', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (102, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'305', N'Sosiaalitieteet', N'Socialvetenskaper', N'Social sciences', N'1240', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (103, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'306', N'Politiikkatieteet', N'Politikvetenskaper', N'Political sciences', N'1250', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (104, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'307', N'Oikeustiede', N'Juridik', N'Law', N'1260', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (106, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'401', N'Matematiikka', N'Matematik', N'Mathematics', N'1280', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (105, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'399', N'Muu yhteiskuntatieteiden, liiketalouden ja hallinnon alan koulutus ', N'Annan utbildning inom samhällsvetenskap, företagsekonomi och förvaltning ', N'Other education in social sciences, business and administration ', N'1270', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (107, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'402', N'Tietojenkäsittely', N'Databehandling', N'Computing and software', N'1290', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (108, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'403', N'Geo-, avaruus-, ja tähtitieteet', N'Geo- och rymdvetenskap, astronomi', N'Earth and space sciences and astronomy', N'1300', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (110, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'405', N'Kemia', N'Kemi', N'Chemistry', N'1320', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (111, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'406', N'Biologia', N'Biologi', N'Biology', N'1330', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (112, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'407', N'Maantiede', N'Geografi', N'Geography', N'1340', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (113, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'499', N'Muu luonnontieteiden alan koulutus', N'Annan naturvetenskaplig utbildning', N'Other education in natural sciences', N'1350', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (114, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'501', N'Arkkitehtuuri ja rakentaminen', N'Arkitektur och byggande', N'Architecture and construction', N'1360', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (115, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'502', N'Kone-metalli-ja energiatekniikka', N'Maskin-, metall- och energiteknik', N'Mechanical, metal and energy engineering', N'1370', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (116, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'503', N'Sähkö-ja automaatiotekniikka', N'El- och automationsteknik', N'Electrical and automation engineering', N'1380', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (117, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'504', N'Tieto-ja tietoliikennetekniikka', N'Data- och datakommunikationsteknik', N'Information and telecommunications technology', N'1390', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (118, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'505', N'Graafinen viestintätekniikka', N'Grafisk kommunikationsteknik', N'Graphics and communications technology', N'1400', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (119, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'506', N'Elintarvikeala ja biotekniikka', N'Livsmedelsbranschen och bioteknik', N'Food sciences, food industry and biotechnology', N'1410', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (120, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'507', N'Prosessi-, kemian- ja materiaalitekniikka', N'Process- och materialteknik kemisk teknik', N'Process, chemical and materials engineering', N'1420', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (121, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'508', N'Tekstiili-ja vaatetustekniikka', N'Textil- och beklädnadsteknik', N'Textiles and clothing technology', N'1430', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (122, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'509', N'Ajoneuvo-ja kuljetustekniikka', N'Fordons- och transportteknik', N'Automotive and transport engineering', N'1440', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (123, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'510', N'Tuotantotalous', N'Produktionsteknik', N'Industrial management', N'1450', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (124, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'599', N'Muu tekniikan ja liikenteen alan koulutus ', N'Annan utbildning inom teknik och trafik ', N'Other education in technology, communications and transport ', N'1460', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (125, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'601', N'Maatilatalous', N'Jordbruk', N'Agriculture', N'1470', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (126, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'602', N'Puutarhatalous', N'Trädgårdsekonomi', N'Horticulture', N'1480', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (127, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'603', N'Kalatalous', N'Fiske', N'Fishery', N'1490', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (128, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'604', N'Metsätalous', N'Skogsbruk', N'Forestry', N'1500', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (129, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'605', N'Luonto-ja ympäristöala', N'Natur- och miljöbranschen', N'Nature and the environment', N'1510', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (131, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'701', N'Sosiaaliala', N'Socialbranschen', N'Social services', N'1530', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (132, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'702', N'Terveysala', N'Hälso- och sjukvårdsbranschen', N'Health care', N'1540', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (134, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'704', N'Hammaslääketiede ja muu hammashuolto', N'odontologi och annan tandvård', N'Dentistry and other dental services', N'1560', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (135, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'705', N'Kuntoutus ja liikunta', N'Rehabilitering, gymnastik och idrott', N'Rehabilitation and sports', N'1570', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (109, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'404', N'Fysiikka', N'Fysik', N'Physics', N'1310', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (130, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'699', N'Muu luonnonvara- ja ympäristöalan koulutus', N'Annan naturresurs- och miljöutbildning', N'Other education in natural resources and the environment', N'1520', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (133, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'703', N'Sosiaali-ja terveysala (alojen yhteiset ohjelmat)', N'Social- och hälsovårdsbranschen (gemensamma program för branscherna)', N'Health care and social services (shared programmes)', N'1550', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (136, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'706', N'Tekniset terveyspalvelut', N'Tekniska hälsovårdstjänster', N'Technical health services', N'1580', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (137, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'707', N'Farmasia ja muu lääkehuolto', N'Farmaci och annan läkemedelsförsörjning', N'Pharmacy and other pharmacological services', N'1590', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (138, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'708', N'Lääketiede', N'Medicin', N'Medicine', N'1600', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (139, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'709', N'Eläinlääketiede', N'Veterinärmedicin', N'Veterinary medicine', N'1610', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (140, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'710', N'Kauneudenhoitoala', N'Skönhetsvård', N'Beauty care', N'1620', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (141, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'799', N'Muu sosiaali-, terveys- ja liikunta-alan koulutus', N'Annan utbildning inom social- och hälsovård, gymnastik och idrott', N'Other education in social services, health and sports', N'1630', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (142, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'801', N'Matkailuala', N'Turism', N'Tourism', N'1640', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (143, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'802', N'Majoitus-ja ravitsemisala', N'Hotell- och restaurangbranschen', N'Hotel and catering', N'1650', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (144, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'803', N'Kotitalous-ja kuluttajapalvelut', N'Hushålls- och konsumenttjänster', N'Domestic and consumer services', N'1660', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (145, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'804', N'Puhdistuspalvelut', N'Renhållningstjänster', N'Cleaning services', N'1670', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (146, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'899', N'Muu matkailu-, ravitsemis- ja talousalan koulutus', N'Annan turism-, restaurang- och huhållsutbildning', N'Other education in tourism, catering and domestic services', N'1680', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (147, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'901', N'Sotilas-ja rajavartioala', N'Militär- och gränsbevakningsbranschen', N'Military and border guard', N'1690', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (148, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'902', N'Palo-ja pelastusala', N'Brand- och räddningsbranschen', N'Fire and rescue services', N'1700', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (149, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'903', N'Poliisiala', N'Polisbranschen', N'Police services', N'1710', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (150, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'904', N'Vankeinhoito', N'Fångvård', N'Correctional services', N'1720', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (151, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'989', N'Muu opetusministeriön hallinnonalan ulkopuolella järjestettävä koulutus', N'Annan utbildning som ordnas utanför undervisningsministeriets förvaltningsområde', N'Other education outside the Ministry of Education sector', N'1730', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
INSERT [dbo].[opettajat_aine_vst] ([id], [alkaa], [paattyy], [aine_koodi], [aine], [aine_SV], [aine_EN], [jarjestys], [virhetilanne], [poistettu], [tietolahde], [luotu], [kommentti]) VALUES (152, CAST(N'2010-01-01' AS Date), CAST(N'2018-12-31' AS Date), N'999', N'Muu opetusministeriön hallinnonalalla järjestettävä koulutus', N'Annan utbildning som ordnas inom undervisningsministeriets förvaltningsområde', N'Other education in the Ministry of Education sector', N'1731', N'E         ', N' ', N'Tilastokeskus 7-aineistot', CAST(N'2015-09-18' AS Date), N'CSC Anssi')
GO
USE [ANTERO]