IF NOT EXISTS (select * from INFORMATION_SCHEMA.TABLES where TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_yo_talous_1_tuloslaskelma') BEGIN


CREATE TABLE [sa].[sa_suorat_yo_talous_1_tuloslaskelma](
	[AKATEMIA] [text] NULL,
	[ARVALPAL] [int] NULL,
	[ARVONAL] [int] NULL,
	[AVUSTUST] [int] NULL,
	[ELAKEK] [int] NULL,
	[Emo_konserni] [varchar](255) NULL,
	[EUMUUT] [int] NULL,
	[EUSUORA] [int] NULL,
	[EUYRITYS] [int] NULL,
	[HLOKULUY] [int] NULL,
	[KERAKULU] [int] NULL,
	[KERATULO] [int] NULL,
	[KONEVUOK] [int] NULL,
	[KORKOK] [int] NULL,
	[KORKOT] [int] NULL,
	[KOTILAHJ] [int] NULL,
	[KOTITALT] [int] NULL,
	[KRAHALT] [int] NULL,
	[KUNNAT] [int] NULL,
	[KYRITYST] [int] NULL,
	[LAHJKULU] [int] NULL,
	[LAHJTULO] [int] NULL,
	[MTAPPIO] [int] NULL,
	[MUUJULKH] [int] NULL,
	[MUULAHJ] [int] NULL,
	[MUUSIVUK] [int] NULL,
	[MUUTILAK] [int] NULL,
	[MVOITTO] [int] NULL,
	[OSA] [text] NULL,
	[OSINKOT] [int] NULL,
	[PALKKAK] [int] NULL,
	[PALVOSTO] [int] NULL,
	[POISTOT] [int] NULL,
	[SRJAAMA] [int] NULL,
	[SRLIIKEK] [int] NULL,
	[SRLIIKET] [int] NULL,
	[SRMUUK] [int] NULL,
	[SRMUUTUL] [int] NULL,
	[SROSUUS] [int] NULL,
	[SRVAHEM] [int] NULL,
	[TAVAOSTO] [int] NULL,
	[TEKES] [int] NULL,
	[TILIK] [varchar](255) NULL,
	[ULKMUU] [int] NULL,
	[ULKYRITY] [int] NULL,
	[VALTIO] [int] NULL,
	[VASTIKEK] [int] NULL,
	[VHJAAMA] [int] NULL,
	[VHLIIKEK] [int] NULL,
	[VHLIIKET] [int] NULL,
	[VHMUUK] [int] NULL,
	[VHMUUTUL] [int] NULL,
	[VHOSUUST] [int] NULL,
	[VHVAHEM] [int] NULL,
	[VTJAAMA] [int] NULL,
	[VTKULUTY] [int] NULL,
	[VTLIIKEK] [int] NULL,
	[VTLIIKET] [int] NULL,
	[VTMUUK] [int] NULL,
	[VTMUUTUL] [int] NULL,
	[VTOSUUST] [int] NULL,
	[VTVAHEM] [int] NULL,
	[VUOKRAK] [int] NULL,
	[VUOKRAT] [int] NULL,
	[VYHTEISO] [int] NULL,
	[YLIOP] [varchar](255) NULL,
	[YLIOP_koodi] [varchar](255) NULL,
	[YRITLAHJ] [text] NULL,
	[SATTUOTO] [int] NULL,
	[SATKULUT] [int] NULL,
	[YOLAKI49] [int] NULL,
	[MUUYAVUS] [int] NULL,
	[OMAKRAHM] [int] NULL,
	[TILIKTUL] [int] NULL,
	[POISTOEM] [int] NULL,
	[SIDOTTRM] [int] NULL,
	[TULOVERO] [int] NULL,
	[TILIKJAAM] [int] NULL,
	[YVARULKOT] [int] NULL,
	[MVARULKOT] [int] NULL,
	[ALV] [int] NULL,
	[OKMALV] [int] NULL,
	[VMALV] [int] NULL,
	[MUUALV] [int] NULL,
	[VMHAR] [int] NULL,
	[OKMHAR] [int] NULL,
	[HARLIIK] [int] NULL,
	[APTEMKA] [int] NULL,
	[APTEVER] [int] NULL,
	[Aineistotyyppi_osa_1] [varchar](1) NULL,
	[IMP_CREATED_DATE] [datetime] NULL,
	[IMP_UPDATED_DATE] [datetime] NULL,
	[IMP_CREATED_BY] [varchar](100) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

END


IF NOT EXISTS (select * from INFORMATION_SCHEMA.TABLES where TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_yo_talous_2_tase') BEGIN


CREATE TABLE [sa].[sa_suorat_yo_talous_2_tase](
	[Emo_konserni] [varchar](255) NULL,
	[OSA] [text] NULL,
	[TILIK] [varchar](255) NULL,
	[YLIOP] [varchar](255) NULL,
	[YLIOP_koodi] [varchar](255) NULL,
	[KEHMENOT] [int] NULL,
	[AINEETOI] [int] NULL,
	[LIIKEAR] [int] NULL,
	[KLIIKEAR] [int] NULL,
	[MUUPMENO] [int] NULL,
	[AHENNAKK] [int] NULL,
	[MAAVESI] [int] NULL,
	[RAKENNUS] [int] NULL,
	[KONEET] [int] NULL,
	[MUUAINH] [int] NULL,
	[ENNAKESK] [int] NULL,
	[OSUUSKON] [int] NULL,
	[SAAMIKON] [int] NULL,
	[OSUUSOYY] [int] NULL,
	[SAAMIOYY] [int] NULL,
	[MUUTOSAK] [int] NULL,
	[MUUTSAAM] [int] NULL,
	[OKRVARAT] [int] NULL,
	[AINEET] [int] NULL,
	[KESKENER] [int] NULL,
	[VALMIIT] [int] NULL,
	[MUUVOM] [int] NULL,
	[VOENNAKK] [int] NULL,
	[PMYYNTIS] [int] NULL,
	[PSKONSER] [int] NULL,
	[PSOYYRIT] [int] NULL,
	[PLAINAS] [int] NULL,
	[PLVEROS] [int] NULL,
	[PMUUTS] [int] NULL,
	[PSIIRTOS] [int] NULL,
	[LMYYNTIS] [int] NULL,
	[LSKONSER] [int] NULL,
	[LSOYYRIT] [int] NULL,
	[LLAINAS] [int] NULL,
	[LLVEROS] [int] NULL,
	[LMUUTS] [int] NULL,
	[LSIIRTOS] [int] NULL,
	[RAPOSUUS] [int] NULL,
	[RAPOSAKK] [int] NULL,
	[MUUARVOP] [int] NULL,
	[RAHATPS] [int] NULL,
	[VASTAAVA] [int] NULL,
	[PERUSPO] [int] NULL,
	[ARVONKR] [int] NULL,
	[KAYVANAR] [int] NULL,
	[OKARAHAS] [int] NULL,
	[MSIRAHAS] [int] NULL,
	[VAPRAHAS] [int] NULL,
	[TOIMPO] [int] NULL,
	[EDJAAMA] [int] NULL,
	[TKJAAMA] [int] NULL,
	[OPOYHT] [int] NULL,
	[TAVAHEM] [int] NULL,
	[TPSKERTY] [int] NULL,
	[ELAKVARA] [int] NULL,
	[VEROVARA] [int] NULL,
	[MPAKVARA] [int] NULL,
	[KRESERVI] [int] NULL,
	[OKRVELAT] [int] NULL,
	[PPAAOMAL] [int] NULL,
	[PJVELKAL] [int] NULL,
	[PVVELKAL] [int] NULL,
	[PLRAHALA] [int] NULL,
	[PELAKEL] [int] NULL,
	[PSAADUTE] [int] NULL,
	[POSTOVEL] [int] NULL,
	[PRVEKSEL] [int] NULL,
	[PVKONSER] [int] NULL,
	[PVOYYRIT] [int] NULL,
	[PMUUTVEL] [int] NULL,
	[PSIIRTOV] [int] NULL,
	[PLVEROVE] [int] NULL,
	[LPAAOMAL] [int] NULL,
	[LJVELKAL] [int] NULL,
	[LVVELKAL] [int] NULL,
	[LLRAHALA] [int] NULL,
	[LELAKEL] [int] NULL,
	[LSAADUTE] [int] NULL,
	[LOSTOVEL] [int] NULL,
	[LRVEKSEL] [int] NULL,
	[LVKONSER] [int] NULL,
	[LVOYYRIT] [int] NULL,
	[LMUUTVEL] [int] NULL,
	[LSIIRTOV] [int] NULL,
	[LLVEROVE] [int] NULL,
	[VASTATTA] [int] NULL,
	[OKRSIJYH] [int] NULL,
	[OKRRAHAS] [int] NULL,
	[OKROSAKK] [int] NULL,
	[OKRMUUAP] [int] NULL,
	[OKRRJAPS] [int] NULL,
	[OKRMUUTV] [int] NULL,
	[Aineistotyyppi_osa_1] [varchar](1) NULL,
	[IMP_CREATED_DATE] [datetime] NULL,
	[IMP_UPDATED_DATE] [datetime] NULL,
	[IMP_CREATED_BY] [varchar](100) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

END

IF NOT EXISTS (select * from INFORMATION_SCHEMA.TABLES where TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_yo_talous_3_tuloslaskelman_toiminnot') BEGIN


CREATE TABLE [sa].[sa_suorat_yo_talous_3_tuloslaskelman_toiminnot](
	[YLIOP] [varchar](255) NULL,
	[TILIK] [varchar](255) NULL,
	[TOIMINTO] [varchar](255) NULL,
	[TUOTOT] [int] NULL,
	[TTAVUSTU] [int] NULL,
	[LIIKETUO] [int] NULL,
	[MUUTTUOT] [int] NULL,
	[KULUTYHT] [int] NULL,
	[HLOKULUT] [int] NULL,
	[TTPOISTO] [int] NULL,
	[MUUTKULU] [int] NULL,
	[OSUUSYKU] [int] NULL,
	[YLIOP_koodi] [varchar](255) NULL,
	[IMP_CREATED_DATE] [datetime] NULL,
	[IMP_UPDATED_DATE] [datetime] NULL,
	[IMP_CREATED_BY] [varchar](100) NULL
) ON [PRIMARY]

END

IF NOT EXISTS (select * from INFORMATION_SCHEMA.TABLES where TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_yo_talous_4_tutkimusmenot') BEGIN


CREATE TABLE [sa].[sa_suorat_yo_talous_4_tutkimusmenot](
	[YLIOP] [varchar](255) NULL,
	[TILIK] [varchar](255) NULL,
	[YLIOP_koodi] [varchar](255) NULL,
	[OPM95OPA] [varchar](255) NULL,
	[TUTMENOT] [int] NULL,
	[OMATR] [int] NULL,
	[ULKOPTR] [int] NULL,
	[AKATEMIA] [int] NULL,
	[MUUOKM] [int] NULL,
	[TEKES] [int] NULL,
	[MUUTEM] [int] NULL,
	[ULKOMIN] [int] NULL,
	[OIKMIN] [int] NULL,
	[SISÄMIN] [int] NULL,
	[PUOLMIN] [int] NULL,
	[VALTVMIN] [int] NULL,
	[MMM] [int] NULL,
	[LVM] [int] NULL,
	[STM] [int] NULL,
	[YMPMIN] [int] NULL,
	[KUNNAT] [int] NULL,
	[MUUJULKR] [int] NULL,
	[KOTIRAHA] [int] NULL,
	[KOTIYRIT] [int] NULL,
	[ULKOYRIT] [int] NULL,
	[EUPUITER] [int] NULL,
	[EAKR] [int] NULL,
	[ESR] [int] NULL,
	[MUUEUR] [int] NULL,
	[ULKORAHA] [int] NULL,
	[KVJARJ] [int] NULL,
	[ULKOMUUR] [int] NULL,
	[OPM95OPA_koodi] [varchar](255) NULL,
	[IMP_CREATED_DATE] [datetime] NULL,
	[IMP_UPDATED_DATE] [datetime] NULL,
	[IMP_CREATED_BY] [varchar](100) NULL
) ON [PRIMARY]

END

IF NOT EXISTS (select * from INFORMATION_SCHEMA.TABLES where TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_yo_talous_5_kustannustiedot') BEGIN


CREATE TABLE [sa].[sa_suorat_yo_talous_5_kustannustiedot](
	[PTUTKOUL] [int] NULL,
	[YLIOP] [varchar](255) NULL,
	[TILIK] [varchar](255) NULL,
	[YLIOP_koodi] [varchar](255) NULL,
	[OPM95OPA] [varchar](255) NULL,
	[VTKUSTY] [int] NULL,
	[KOULUTUS] [int] NULL,
	[PTUTOSAT] [int] NULL,
	[MUUKOUL] [int] NULL,
	[TUTKIMUS] [int] NULL,
	[JTUTKKOU] [int] NULL,
	[TIETTUTK] [int] NULL,
	[TAITTOIM] [int] NULL,
	[MUUYHTEI] [int] NULL,
	[JULOIKSU] [int] NULL,
	[YLEISTOI] [int] NULL,
	[HARJKOUL] [int] NULL,
	[OPETUSY] [int] NULL,
	[ESIOPE] [int] NULL,
	[PERUSOPE] [int] NULL,
	[LUKIOOPE] [int] NULL,
	[OPEKOULY] [int] NULL,
	[HARJHKOU] [int] NULL,
	[HARJULKO] [int] NULL,
	[OPEKEHIT] [int] NULL,
	[KIRJYHT] [int] NULL,
	[YLAKIYHT] [int] NULL,
	[KULTPER] [int] NULL,
	[KANPAKIR] [int] NULL,
	[YOTOTTEH] [int] NULL,
	[OPM95OPA_koodi] [varchar](255) NULL,
	[IMP_CREATED_DATE] [datetime] NULL,
	[IMP_UPDATED_DATE] [datetime] NULL,
	[IMP_CREATED_BY] [varchar](100) NULL
) ON [PRIMARY]

END

IF NOT EXISTS (select * from INFORMATION_SCHEMA.TABLES where TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_yo_talous_6_liiketoiminnan_tuloslaskelma') BEGIN


CREATE TABLE [sa].[sa_suorat_yo_talous_6_liiketoiminnan_tuloslaskelma](
	[YLIOP] [varchar](255) NULL,
	[TILIK] [varchar](255) NULL,
	[LIIKEVAIHTO] [int] NULL,
	[VARASTOJEN_LISAYS_TAI_VAHENNYS] [int] NULL,
	[VALMISTUS_OMAAN_KAYTTOON] [int] NULL,
	[LIIKETOIMINNAN_MUUT_TUOTOT] [int] NULL,
	[MATERIAALIT_JA_PALVELUT] [int] NULL,
	[AINEET_TARVIKKEET_JA_TAVARAT] [int] NULL,
	[OSTOT_TILIKAUDEN_AIKANA] [int] NULL,
	[TUOTTEET_VARASTOJEN_LISAYS_TAI_VAHENNYS] [int] NULL,
	[ULKOPUOLISET_PALVELUT] [int] NULL,
	[HENKILOSTOKULUT] [int] NULL,
	[PALKAT_JA_PALKKIOT] [int] NULL,
	[HENKILOSTOSIVUKULUT] [int] NULL,
	[ELAKEKULUT] [int] NULL,
	[MUUT_HENKILOSTOSIVUKULUT] [int] NULL,
	[POISTOT_JA_ARVONALENNUKSET] [int] NULL,
	[SUUNNITELMAN_MUKAISET_POISTOT] [int] NULL,
	[SIJOITUKSET_ARVONALENTUMISET_PYSYVAT_VASTAAVAT] [int] NULL,
	[SIJOITUKSET_ARVONALENTUMISET_VAIHTUVAT_VASTAAVAT] [int] NULL,
	[LIIKETOIMINNAN_MUUT_KULUT] [int] NULL,
	[LIIKEVOITTO] [int] NULL,
	[YLIOP_koodi] [varchar](255) NULL,
	[OSA] [text] NULL,
	[RAHOITUSTUOTOT_JA_KULUT] [int] NULL,
	[TUOTOT_OSUUKSISTA_KONSERNI] [int] NULL,
	[TUOTOT_OSUUKSISTA_OMISTUSYHTEISTYOYRITYKSISSA] [int] NULL,
	[TUOTOT_MUISTA] [int] NULL,
	[TUOTOT_SAMA_KONSERNI] [int] NULL,
	[TUOTOT_MUILTA] [int] NULL,
	[MUUT_KORKOTUOTOT] [int] NULL,
	[MUUT_KORKOTUOTOT_SAMA_KONSERNI] [int] NULL,
	[MUUT_KORKOTUOTOT_MUILTA] [int] NULL,
	[ARVONALENTUMISET_PYSYVAT_VASTAAVAT] [int] NULL,
	[ARVONALENTUMISET_VAIHTUVAT_VASTAAVAT] [int] NULL,
	[KORKOKULUT_JA_MUUT_RAHOITUSKULUT] [int] NULL,
	[KORKOKULUT_SAMA_KONSERNI] [int] NULL,
	[KORKOKULUT_MUILLE] [int] NULL,
	[VOITTO_ENNEN_SATUNNAISIA_ERIA] [int] NULL,
	[SATUNNAISET_ERAT] [int] NULL,
	[SATUNNAISET_TUOTOT] [int] NULL,
	[SATUNNAISET_KULUT] [int] NULL,
	[VOITOT_ENNEN_TILINPAATOSSIIRTOJA] [int] NULL,
	[TILINPAATOSSIIRROT] [int] NULL,
	[POISTOERON_LISAYS] [int] NULL,
	[VAPAAEHTOISTEN_VARAUSTEN_LISAYS] [int] NULL,
	[TULOVEROT] [int] NULL,
	[MUUT_VALITTOMAT_VEROT] [int] NULL,
	[TILKAUDEN_VOITTO] [int] NULL,
	[Aineistotyyppi] [varchar](1) NULL,
	[IMP_CREATED_DATE] [datetime] NULL,
	[IMP_UPDATED_DATE] [datetime] NULL,
	[IMP_CREATED_BY] [varchar](100) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

END

