USE [VipunenTK_lisatiedot]
GO
/****** Object:  Table [dbo].[koulutuslaji3]    Script Date: 7.1.2021 21:45:07 ******/
DROP TABLE [dbo].[koulutuslaji3]
GO
/****** Object:  Table [dbo].[koulutuslaji3]    Script Date: 7.1.2021 21:45:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[koulutuslaji3](
	[id] [int] NOT NULL,
	[luotu] [date] NULL,
	[koulutuslaji3_koodi] [nvarchar](10) NULL,
	[koulutuslaji3] [nvarchar](250) NULL,
	[koulutuslaji3_SV] [nvarchar](250) NULL,
	[koulutuslaji3_EN] [nvarchar](250) NULL,
	[jarjestys_koulutuslaji3] [nvarchar](50) NULL,
	[koulutuslaji4] [nvarchar](250) NULL,
	[koulutuslaji4_SV] [nvarchar](250) NULL,
	[koulutuslaji4_EN] [nvarchar](250) NULL,
	[jarjestys_koulutuslaji4] [nvarchar](50) NULL,
	[jarjestamistapa] [nvarchar](250) NULL,
	[jarjestamistapa_SV] [nvarchar](250) NULL,
	[jarjestamistapa_EN] [nvarchar](250) NULL,
	[jarjestys_jarjestamistapa] [nvarchar](50) NULL,
	[jarjestamismuoto] [nvarchar](250) NULL,
	[jarjestamismuoto_SV] [nvarchar](250) NULL,
	[jarjestamismuoto_EN] [nvarchar](250) NULL,
	[jarjestys_jarjestamismuoto] [nvarchar](50) NULL,
	[tutkintotyyppi] [nvarchar](250) NULL,
	[tutkintotyyppi_SV] [nvarchar](250) NULL,
	[tutkintotyyppi_EN] [nvarchar](250) NULL,
	[jarjestys_tutkintotyyppi] [nvarchar](50) NULL,
	[virhetilanne] [nchar](1) NULL,
	[poistettu] [nchar](1) NULL,
	[tietolahde] [nvarchar](50) NULL,
	[kommentti] [nvarchar](250) NULL
) ON [PRIMARY]

GO
INSERT [dbo].[koulutuslaji3] ([id], [luotu], [koulutuslaji3_koodi], [koulutuslaji3], [koulutuslaji3_SV], [koulutuslaji3_EN], [jarjestys_koulutuslaji3], [koulutuslaji4], [koulutuslaji4_SV], [koulutuslaji4_EN], [jarjestys_koulutuslaji4], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (-2, CAST(N'2015-05-28' AS Date), N'-2', N'Virhetilanne', N'Feltillstånd', N'Error occurred', N'999', N'Virhetilanne', N'Feltillstånd', N'Error occurred', N'999', N'Virhetilanne', N'Feltillstånd', N'Error occurred', N'99', N'Virhetilanne', N'Feltillstånd', N'Error occurred', N'99', N'Virhetilanne', N'Feltillstånd', N'Error occurred', N'99', N'K', N'0', N'Manuaalinen', N'')
GO
INSERT [dbo].[koulutuslaji3] ([id], [luotu], [koulutuslaji3_koodi], [koulutuslaji3], [koulutuslaji3_SV], [koulutuslaji3_EN], [jarjestys_koulutuslaji3], [koulutuslaji4], [koulutuslaji4_SV], [koulutuslaji4_EN], [jarjestys_koulutuslaji4], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (-1, CAST(N'2015-05-28' AS Date), N'-1', N'Tuntematon', N'Okänd', N'Unknown', N'998', N'Tuntematon', N'Okänd', N'Unknown', N'998', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'K', N'0', N'Manuaalinen', N'')
GO
INSERT [dbo].[koulutuslaji3] ([id], [luotu], [koulutuslaji3_koodi], [koulutuslaji3], [koulutuslaji3_SV], [koulutuslaji3_EN], [jarjestys_koulutuslaji3], [koulutuslaji4], [koulutuslaji4_SV], [koulutuslaji4_EN], [jarjestys_koulutuslaji4], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (1, CAST(N'2015-05-28' AS Date), N'21', N'Lukiokoulutus, nuorten OPS (oppilaitoksen määrittelemä tieto)', N'Gymnasieutbildning, ungdomar LP-baserad (uppgift som läroanstalten fastställt)', N'General upper secondary education, curriculum for young people (data provided by the educational institution)', N'210', N'Lukiokoulutus, nuorten OPS (oppilaitoksen määrittelemä tieto)', N'Gymnasieutbildning, ungdomar LP-baserad (uppgift som läroanstalten fastställt)', N'General upper secondary education, curriculum for young people (data provided by the educational institution)', N'210', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'E', N'0', N'Manuaalinen', N'Järjestämistapa-, muoto ja tutkintotyyppi kopioitu koulutuslaji2:sta')
GO
INSERT [dbo].[koulutuslaji3] ([id], [luotu], [koulutuslaji3_koodi], [koulutuslaji3], [koulutuslaji3_SV], [koulutuslaji3_EN], [jarjestys_koulutuslaji3], [koulutuslaji4], [koulutuslaji4_SV], [koulutuslaji4_EN], [jarjestys_koulutuslaji4], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (2, CAST(N'2015-05-28' AS Date), N'22', N'Lukiokoulutus, aikuisten OPS (oppilaitoksen määrittelemä tieto)', N'Gymnasieutbildning, vuxna LP-baserad (uppgift som läroanstalten fastställt)', N'General upper secondary education, curriculum for adults (data provided by the educational institution)', N'220', N'Lukiokoulutus, aikuisten OPS (oppilaitoksen määrittelemä tieto)', N'Gymnasieutbildning, vuxna LP-baserad (uppgift som läroanstalten fastställt)', N'General upper secondary education, curriculum for adults (data provided by the educational institution)', N'220', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'E', N'0', N'Manuaalinen', N'Järjestämistapa-, muoto ja tutkintotyyppi kopioitu koulutuslaji2:sta')
GO
INSERT [dbo].[koulutuslaji3] ([id], [luotu], [koulutuslaji3_koodi], [koulutuslaji3], [koulutuslaji3_SV], [koulutuslaji3_EN], [jarjestys_koulutuslaji3], [koulutuslaji4], [koulutuslaji4_SV], [koulutuslaji4_EN], [jarjestys_koulutuslaji4], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (3, CAST(N'2015-05-28' AS Date), N'31', N'Ammatilliset perustutkinnot (ei oppisopimuskoulutus)', N'Yrkesinriktade grundexamina (ej läroavtalsutbildning)', N'Initial vocational qualifications (not apprenticeship training)', N'310', N'Ammatilliset perustutkinnot (ei oppisopimuskoulutus)', N'Yrkesinriktade grundexamina (ej läroavtalsutbildning)', N'Initial vocational qualifications (not apprenticeship training)', N'320', N'opetussuunnitelmaperusteinen koulutus/tutkinto', N'läroplansbaserad utbildning/examen', N'curriculum-based education/qualification', N'01', N'Ei oppisopimuskoulutus', N'Ej läroavtalsutbildning', N'Not apprenticeship training', N'01', N'ammatillinen peruskoulutus', N'grundläggande yrkesutbildning', N'vocational upper secondary education and training', N'01', N'E', N'0', N'Manuaalinen', N'Järjestämistapa-, muoto ja tutkintotyyppi kopioitu koulutuslaji2:sta')
GO
INSERT [dbo].[koulutuslaji3] ([id], [luotu], [koulutuslaji3_koodi], [koulutuslaji3], [koulutuslaji3_SV], [koulutuslaji3_EN], [jarjestys_koulutuslaji3], [koulutuslaji4], [koulutuslaji4_SV], [koulutuslaji4_EN], [jarjestys_koulutuslaji4], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (4, CAST(N'2015-05-28' AS Date), N'32', N'Ammatilliset perustutkinnot (ei oppisopimuskoulutus)', N'Yrkesinriktade grundexamina (ej läroavtalsutbildning)', N'Initial vocational qualifications (not apprenticeship training)', N'310', N'Ammatilliset perustutkinnot (ei oppisopimuskoulutus)', N'Yrkesinriktade grundexamina (ej läroavtalsutbildning)', N'Initial vocational qualifications (not apprenticeship training)', N'320', N'näyttötutkintoon valmistava koulutus/tutkinto', N'Förberedande utbildning för fristående examen/examen', N'preparatory training/qualification for competence-based qualifications', N'02', N'Ei oppisopimuskoulutus', N'Ej läroavtalsutbildning', N'Not apprenticeship training', N'01', N'ammatillinen peruskoulutus', N'grundläggande yrkesutbildning', N'vocational upper secondary education and training', N'01', N'E', N'0', N'Manuaalinen', N'Järjestämistapa-, muoto ja tutkintotyyppi kopioitu koulutuslaji2:sta')
GO
INSERT [dbo].[koulutuslaji3] ([id], [luotu], [koulutuslaji3_koodi], [koulutuslaji3], [koulutuslaji3_SV], [koulutuslaji3_EN], [jarjestys_koulutuslaji3], [koulutuslaji4], [koulutuslaji4_SV], [koulutuslaji4_EN], [jarjestys_koulutuslaji4], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (5, CAST(N'2015-05-28' AS Date), N'33', N'Ammattitutkinnot (ei oppisopimuskoulutus)', N'Yrkesexamina (ej läroavtalsutbildning)', N'Further vocational qualifications (not apprenticeship training)', N'330', N'Ammattitutkinnot (ei oppisopimuskoulutus)', N'Yrkesexamina (ej läroavtalsutbildning)', N'Further vocational qualifications (not apprenticeship training)', N'330', N'näyttötutkintoon valmistava koulutus/tutkinto', N'Förberedande utbildning för fristående examen/examen', N'preparatory training/qualification for competence-based qualifications', N'02', N'Ei oppisopimuskoulutus', N'Ej läroavtalsutbildning', N'Not apprenticeship training', N'01', N'ammattitutkinto', N'yrkesexamen', N'further vocational qualification', N'02', N'E', N'0', N'Manuaalinen', N'Järjestämistapa-, muoto ja tutkintotyyppi kopioitu koulutuslaji2:sta')
GO
INSERT [dbo].[koulutuslaji3] ([id], [luotu], [koulutuslaji3_koodi], [koulutuslaji3], [koulutuslaji3_SV], [koulutuslaji3_EN], [jarjestys_koulutuslaji3], [koulutuslaji4], [koulutuslaji4_SV], [koulutuslaji4_EN], [jarjestys_koulutuslaji4], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (6, CAST(N'2015-05-28' AS Date), N'34', N'Erikoisammattitutkinnot (ei oppisopimuskoulutus)', N'Specialyrkesexamina (ej läroavtalsutbildning)', N'Specialist vocational qualifications (not apprenticeship training)', N'340', N'Erikoisammattitutkinnot (ei oppisopimuskoulutus)', N'Specialyrkesexamina (ej läroavtalsutbildning)', N'Specialist vocational qualifications (not apprenticeship training)', N'340', N'näyttötutkintoon valmistava koulutus/tutkinto', N'Förberedande utbildning för fristående examen/examen', N'preparatory training/qualification for competence-based qualifications', N'02', N'Ei oppisopimuskoulutus', N'Ej läroavtalsutbildning', N'Not apprenticeship training', N'01', N'erikoisammattitutkinto', N'specialyrkesexamen', N'specialist vocational qualification', N'03', N'E', N'0', N'Manuaalinen', N'Järjestämistapa-, muoto ja tutkintotyyppi kopioitu koulutuslaji2:sta')
GO
INSERT [dbo].[koulutuslaji3] ([id], [luotu], [koulutuslaji3_koodi], [koulutuslaji3], [koulutuslaji3_SV], [koulutuslaji3_EN], [jarjestys_koulutuslaji3], [koulutuslaji4], [koulutuslaji4_SV], [koulutuslaji4_EN], [jarjestys_koulutuslaji4], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (18, CAST(N'2020-01-07' AS Date), N'72', N'Ammattitutkinnot (ei oppisopimuskoulutus)', N'Yrkesexamina (ej läroavtalsutbildning)', N'Further vocational qualifications (not apprenticeship training)', N'330', N'Ammattitutkinnot (ei sisällä koulutussopimus- eikä oppisopimusjaksoja)', N'Yrkesexamen (omfattar inte utbildningsavtals- eller läroavtalsperioder)', N'Further vocational qualifications (training agreement or apprenticeship training periods not included)', N'302', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Ei oppisopimuskoulutus', N'Ej läroavtalsutbildning', N'Not apprenticeship training', N'01', N'ammattitutkinto', N'yrkesexamen', N'further vocational qualification', N'02', N'E', N'0', N'Tilastokeskus', N'')
GO
INSERT [dbo].[koulutuslaji3] ([id], [luotu], [koulutuslaji3_koodi], [koulutuslaji3], [koulutuslaji3_SV], [koulutuslaji3_EN], [jarjestys_koulutuslaji3], [koulutuslaji4], [koulutuslaji4_SV], [koulutuslaji4_EN], [jarjestys_koulutuslaji4], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (19, CAST(N'2020-01-07' AS Date), N'73', N'Erikoisammattitutkinnot (ei oppisopimuskoulutus)', N'Specialyrkesexamina (ej läroavtalsutbildning)', N'Specialist vocational qualifications (not apprenticeship training)', N'340', N'Erikoisammattitutkinnot (ei sisällä koulutussopimus- eikä oppisopimusjaksoja)', N'Specialyrkesexamen (omfattar inte utbildningsavtals- eller läroavtalsperioder)', N'Specialist vocational qualifications (training agreement or apprenticeship training periods not included)', N'303', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Ei oppisopimuskoulutus', N'Ej läroavtalsutbildning', N'Not apprenticeship training', N'01', N'erikoisammattitutkinto', N'specialyrkesexamen', N'specialist vocational qualification', N'03', N'E', N'0', N'Tilastokeskus', N'')
GO
INSERT [dbo].[koulutuslaji3] ([id], [luotu], [koulutuslaji3_koodi], [koulutuslaji3], [koulutuslaji3_SV], [koulutuslaji3_EN], [jarjestys_koulutuslaji3], [koulutuslaji4], [koulutuslaji4_SV], [koulutuslaji4_EN], [jarjestys_koulutuslaji4], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (20, CAST(N'2020-01-07' AS Date), N'74', N'Oppisopimuskoulutus', N'Läroavtalsutbildning', N'Apprenticeship training', N'350', N'Ammatilliset perustutkinnot (sisältää sekä koulutus- että oppisopimusjaksoja)', N'Grundläggande yrkesutbildning (omfattar både utbildningsavtals- och läroavtalsperioder)', N'Initial vocational qualifications (training agreement and apprenticeship training periods included)', N'310', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Oppisopimuskoulutus', N'Läroavtalsutbildning', N'Apprenticeship training', N'02', N'ammatillinen peruskoulutus', N'grundläggande yrkesutbildning', N'vocational upper secondary education and training', N'01', N'E', N'0', N'Tilastokeskus', N'')
GO
INSERT [dbo].[koulutuslaji3] ([id], [luotu], [koulutuslaji3_koodi], [koulutuslaji3], [koulutuslaji3_SV], [koulutuslaji3_EN], [jarjestys_koulutuslaji3], [koulutuslaji4], [koulutuslaji4_SV], [koulutuslaji4_EN], [jarjestys_koulutuslaji4], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (21, CAST(N'2020-01-07' AS Date), N'75', N'Oppisopimuskoulutus', N'Läroavtalsutbildning', N'Apprenticeship training', N'350', N'Ammattitutkinnot (sisältää sekä koulutus- että oppisopimusjaksoja)', N'Yrkesexamen (omfattar både utbildningsavtals- och läroavtalsperioder)', N'Further vocational qualifications (training agreement and apprenticeship training periods included)', N'311', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Oppisopimuskoulutus', N'Läroavtalsutbildning', N'Apprenticeship training', N'02', N'ammattitutkinto', N'yrkesexamen', N'further vocational qualification', N'02', N'E', N'0', N'Tilastokeskus', N'')
GO
INSERT [dbo].[koulutuslaji3] ([id], [luotu], [koulutuslaji3_koodi], [koulutuslaji3], [koulutuslaji3_SV], [koulutuslaji3_EN], [jarjestys_koulutuslaji3], [koulutuslaji4], [koulutuslaji4_SV], [koulutuslaji4_EN], [jarjestys_koulutuslaji4], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (22, CAST(N'2020-01-07' AS Date), N'76', N'Oppisopimuskoulutus', N'Läroavtalsutbildning', N'Apprenticeship training', N'350', N'Erikoisammattitutkinnot (sisältää sekä koulutus- että oppisopimusjaksoja)', N'Specialyrkesexamen (omfattar både utbildningsavtals- och läroavtalsperioder)', N'Specialist vocational qualifications (training agreement and apprenticeship training periods included)', N'312', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Oppisopimuskoulutus', N'Läroavtalsutbildning', N'Apprenticeship training', N'02', N'erikoisammattitutkinto', N'specialyrkesexamen', N'specialist vocational qualification', N'03', N'E', N'0', N'Tilastokeskus', N'')
GO
INSERT [dbo].[koulutuslaji3] ([id], [luotu], [koulutuslaji3_koodi], [koulutuslaji3], [koulutuslaji3_SV], [koulutuslaji3_EN], [jarjestys_koulutuslaji3], [koulutuslaji4], [koulutuslaji4_SV], [koulutuslaji4_EN], [jarjestys_koulutuslaji4], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (23, CAST(N'2020-01-07' AS Date), N'77', N'Ammatilliset perustutkinnot (ei oppisopimuskoulutus)', N'Yrkesinriktade grundexamina (ej läroavtalsutbildning)', N'Initial vocational qualifications (not apprenticeship training)', N'310', N'Ammatilliset perustutkinnot (sisältää koulutussopimusjaksoja)', N'Grundläggande yrkesutbildning (omfattar utbildningsavtalsperioder)', N'Initial vocational qualifications (training agreement periods included)', N'307', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Ei oppisopimuskoulutus', N'Ej läroavtalsutbildning', N'Not apprenticeship training', N'01', N'ammatillinen peruskoulutus', N'grundläggande yrkesutbildning', N'vocational upper secondary education and training', N'01', N'E', N'0', N'Tilastokeskus', N'')
GO
INSERT [dbo].[koulutuslaji3] ([id], [luotu], [koulutuslaji3_koodi], [koulutuslaji3], [koulutuslaji3_SV], [koulutuslaji3_EN], [jarjestys_koulutuslaji3], [koulutuslaji4], [koulutuslaji4_SV], [koulutuslaji4_EN], [jarjestys_koulutuslaji4], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (24, CAST(N'2020-01-07' AS Date), N'78', N'Ammattitutkinnot (ei oppisopimuskoulutus)', N'Yrkesexamina (ej läroavtalsutbildning)', N'Further vocational qualifications (not apprenticeship training)', N'330', N'Ammattitutkinnot (sisältää koulutussopimusjaksoja)', N'Yrkesexamen (omfattar utbildningsavtalsperioder)', N'Further vocational qualifications (training agreement periods included)', N'308', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Ei oppisopimuskoulutus', N'Ej läroavtalsutbildning', N'Not apprenticeship training', N'01', N'ammattitutkinto', N'yrkesexamen', N'further vocational qualification', N'02', N'E', N'0', N'Tilastokeskus', N'')
GO
INSERT [dbo].[koulutuslaji3] ([id], [luotu], [koulutuslaji3_koodi], [koulutuslaji3], [koulutuslaji3_SV], [koulutuslaji3_EN], [jarjestys_koulutuslaji3], [koulutuslaji4], [koulutuslaji4_SV], [koulutuslaji4_EN], [jarjestys_koulutuslaji4], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (25, CAST(N'2020-01-07' AS Date), N'79', N'Erikoisammattitutkinnot (ei oppisopimuskoulutus)', N'Specialyrkesexamina (ej läroavtalsutbildning)', N'Specialist vocational qualifications (not apprenticeship training)', N'340', N'Erikoisammattitutkinnot (sisältää koulutussopimusjaksoja)', N'Specialyrkesexamen (omfattar utbildningsavtalsperioder)', N'Specialist vocational qualifications (training agreement periods included)', N'309', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Ei oppisopimuskoulutus', N'Ej läroavtalsutbildning', N'Not apprenticeship training', N'01', N'erikoisammattitutkinto', N'specialyrkesexamen', N'specialist vocational qualification', N'03', N'E', N'0', N'Tilastokeskus', N'')
GO
INSERT [dbo].[koulutuslaji3] ([id], [luotu], [koulutuslaji3_koodi], [koulutuslaji3], [koulutuslaji3_SV], [koulutuslaji3_EN], [jarjestys_koulutuslaji3], [koulutuslaji4], [koulutuslaji4_SV], [koulutuslaji4_EN], [jarjestys_koulutuslaji4], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (26, CAST(N'2020-01-07' AS Date), N'80', N'Oppisopimuskoulutus', N'Läroavtalsutbildning', N'Apprenticeship training', N'350', N'Ammatilliset perustutkinnot (sisältää oppisopimusjaksoja)', N'Grundläggande yrkesutbildning (omfattar läroavtalsperioder)', N'Initial vocational qualifications (apprenticeship training periods included)', N'304', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Oppisopimuskoulutus', N'Läroavtalsutbildning', N'Apprenticeship training', N'02', N'ammatillinen peruskoulutus', N'grundläggande yrkesutbildning', N'vocational upper secondary education and training', N'01', N'E', N'0', N'Tilastokeskus', N'')
GO
INSERT [dbo].[koulutuslaji3] ([id], [luotu], [koulutuslaji3_koodi], [koulutuslaji3], [koulutuslaji3_SV], [koulutuslaji3_EN], [jarjestys_koulutuslaji3], [koulutuslaji4], [koulutuslaji4_SV], [koulutuslaji4_EN], [jarjestys_koulutuslaji4], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (7, CAST(N'2015-05-28' AS Date), N'35', N'Oppisopimuskoulutus', N'Läroavtalsutbildning', N'Apprenticeship training', N'350', N'Oppisopimuskoulutus', N'Läroavtalsutbildning', N'Apprenticeship training', N'350', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Oppisopimuskoulutus', N'Läroavtalsutbildning', N'Apprenticeship training', N'02', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'E', N'0', N'Manuaalinen', N'Järjestämistapa-, muoto ja tutkintotyyppi kopioitu koulutuslaji2:sta')
GO
INSERT [dbo].[koulutuslaji3] ([id], [luotu], [koulutuslaji3_koodi], [koulutuslaji3], [koulutuslaji3_SV], [koulutuslaji3_EN], [jarjestys_koulutuslaji3], [koulutuslaji4], [koulutuslaji4_SV], [koulutuslaji4_EN], [jarjestys_koulutuslaji4], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (8, CAST(N'2015-05-28' AS Date), N'41', N'AMK-tutkinto, päivätoteutus', N'YH-examen, dagstudier', N'UAS degree, daytime studies', N'410', N'AMK-tutkinto, päivätoteutus', N'YH-examen, dagstudier', N'UAS degree, daytime studies', N'410', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'E', N'0', N'Manuaalinen', N'Järjestämistapa-, muoto ja tutkintotyyppi kopioitu koulutuslaji2:sta')
GO
INSERT [dbo].[koulutuslaji3] ([id], [luotu], [koulutuslaji3_koodi], [koulutuslaji3], [koulutuslaji3_SV], [koulutuslaji3_EN], [jarjestys_koulutuslaji3], [koulutuslaji4], [koulutuslaji4_SV], [koulutuslaji4_EN], [jarjestys_koulutuslaji4], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (9, CAST(N'2015-05-28' AS Date), N'42', N'AMK-tutkinto, monimuotototeutus', N'YH-examen, flerformsstudier', N'UAS degree, multiform studies', N'420', N'AMK-tutkinto, monimuotototeutus', N'YH-examen, flerformsstudier', N'UAS degree, multiform studies', N'420', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'E', N'0', N'Manuaalinen', N'Järjestämistapa-, muoto ja tutkintotyyppi kopioitu koulutuslaji2:sta')
GO
INSERT [dbo].[koulutuslaji3] ([id], [luotu], [koulutuslaji3_koodi], [koulutuslaji3], [koulutuslaji3_SV], [koulutuslaji3_EN], [jarjestys_koulutuslaji3], [koulutuslaji4], [koulutuslaji4_SV], [koulutuslaji4_EN], [jarjestys_koulutuslaji4], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (10, CAST(N'2015-05-28' AS Date), N'46', N'Ylempi AMK-tutkintokoulutus', N'Utbildning för högre YH-examen', N'UAS Master''s degree education', N'460', N'Ylempi AMK-tutkintokoulutus', N'Utbildning för högre YH-examen', N'UAS Master''s degree education', N'460', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'E', N'0', N'Manuaalinen', N'Järjestämistapa-, muoto ja tutkintotyyppi kopioitu koulutuslaji2:sta')
GO
INSERT [dbo].[koulutuslaji3] ([id], [luotu], [koulutuslaji3_koodi], [koulutuslaji3], [koulutuslaji3_SV], [koulutuslaji3_EN], [jarjestys_koulutuslaji3], [koulutuslaji4], [koulutuslaji4_SV], [koulutuslaji4_EN], [jarjestys_koulutuslaji4], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (11, CAST(N'2015-05-28' AS Date), N'51', N'Alemmat ja ylemmät korkeakoulututkinnot', N'Lägre och högre yrkeshögskoleexamina', N'Bachelor''s and Master''s degrees', N'510', N'Alemmat ja ylemmät korkeakoulututkinnot', N'Lägre och högre yrkeshögskoleexamina', N'Bachelor''s and Master''s degrees', N'510', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'E', N'0', N'Manuaalinen', N'Järjestämistapa-, muoto ja tutkintotyyppi kopioitu koulutuslaji2:sta')
GO
INSERT [dbo].[koulutuslaji3] ([id], [luotu], [koulutuslaji3_koodi], [koulutuslaji3], [koulutuslaji3_SV], [koulutuslaji3_EN], [jarjestys_koulutuslaji3], [koulutuslaji4], [koulutuslaji4_SV], [koulutuslaji4_EN], [jarjestys_koulutuslaji4], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (12, CAST(N'2015-05-28' AS Date), N'52', N'Lisensiaatin-, tohtorin- ja lääkärien erikoistumiskoulutus', N'Licentiat- och doktorsutbildning, specialiseringsutbildning för läkare', N'Licentiate and doctoral education and specialist degree in medicine', N'520', N'Lisensiaatin-, tohtorin- ja lääkärien erikoistumiskoulutus', N'Licentiat- och doktorsutbildning, specialiseringsutbildning för läkare', N'Licentiate and doctoral education and specialist degree in medicine', N'520', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'E', N'0', N'Manuaalinen', N'Järjestämistapa-, muoto ja tutkintotyyppi kopioitu koulutuslaji2:sta')
GO
INSERT [dbo].[koulutuslaji3] ([id], [luotu], [koulutuslaji3_koodi], [koulutuslaji3], [koulutuslaji3_SV], [koulutuslaji3_EN], [jarjestys_koulutuslaji3], [koulutuslaji4], [koulutuslaji4_SV], [koulutuslaji4_EN], [jarjestys_koulutuslaji4], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (13, CAST(N'2020-01-16' AS Date), N'61', N'Ammatilliset perustutkinnot (ei oppisopimuskoulutus)', N'Yrkesinriktade grundexamina (ej läroavtalsutbildning)', N'Initial vocational qualifications (not apprenticeship training)', N'310', N'Ammatilliset perustutkinnot (ei oppisopimuskoulutus)', N'Yrkesinriktade grundexamina (ej läroavtalsutbildning)', N'Initial vocational qualifications (not apprenticeship training)', N'320', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Ei oppisopimuskoulutus', N'Ej läroavtalsutbildning', N'Not apprenticeship training', N'01', N'ammatillinen peruskoulutus', N'grundläggande yrkesutbildning', N'vocational upper secondary education and training', N'01', N'E', N'0', N'Manuaalinen', N'')
GO
INSERT [dbo].[koulutuslaji3] ([id], [luotu], [koulutuslaji3_koodi], [koulutuslaji3], [koulutuslaji3_SV], [koulutuslaji3_EN], [jarjestys_koulutuslaji3], [koulutuslaji4], [koulutuslaji4_SV], [koulutuslaji4_EN], [jarjestys_koulutuslaji4], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (14, CAST(N'2020-01-16' AS Date), N'62', N'Ammattitutkinnot (ei oppisopimuskoulutus)', N'Yrkesexamina (ej läroavtalsutbildning)', N'Further vocational qualifications (not apprenticeship training)', N'330', N'Ammattitutkinnot (ei oppisopimuskoulutus)', N'Yrkesexamina (ej läroavtalsutbildning)', N'Further vocational qualifications (not apprenticeship training)', N'330', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Ei oppisopimuskoulutus', N'Ej läroavtalsutbildning', N'Not apprenticeship training', N'01', N'ammattitutkinto', N'yrkesexamen', N'further vocational qualification', N'02', N'E', N'0', N'Manuaalinen', N'')
GO
INSERT [dbo].[koulutuslaji3] ([id], [luotu], [koulutuslaji3_koodi], [koulutuslaji3], [koulutuslaji3_SV], [koulutuslaji3_EN], [jarjestys_koulutuslaji3], [koulutuslaji4], [koulutuslaji4_SV], [koulutuslaji4_EN], [jarjestys_koulutuslaji4], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (15, CAST(N'2020-01-16' AS Date), N'63', N'Erikoisammattitutkinnot (ei oppisopimuskoulutus)', N'Specialyrkesexamina (ej läroavtalsutbildning)', N'Specialist vocational qualifications (not apprenticeship training)', N'340', N'Erikoisammattitutkinnot (ei oppisopimuskoulutus)', N'Specialyrkesexamina (ej läroavtalsutbildning)', N'Specialist vocational qualifications (not apprenticeship training)', N'340', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Ei oppisopimuskoulutus', N'Ej läroavtalsutbildning', N'Not apprenticeship training', N'01', N'erikoisammattitutkinto', N'specialyrkesexamen', N'specialist vocational qualification', N'03', N'E', N'0', N'Manuaalinen', N'')
GO
INSERT [dbo].[koulutuslaji3] ([id], [luotu], [koulutuslaji3_koodi], [koulutuslaji3], [koulutuslaji3_SV], [koulutuslaji3_EN], [jarjestys_koulutuslaji3], [koulutuslaji4], [koulutuslaji4_SV], [koulutuslaji4_EN], [jarjestys_koulutuslaji4], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (16, CAST(N'2020-01-16' AS Date), N'67', N'Oppisopimuskoulutus', N'Läroavtalsutbildning', N'Apprenticeship training', N'350', N'Oppisopimuskoulutus', N'Läroavtalsutbildning', N'Apprenticeship training', N'350', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Oppisopimuskoulutus', N'Läroavtalsutbildning', N'Apprenticeship training', N'02', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'E', N'0', N'Manuaalinen', N'')
GO
INSERT [dbo].[koulutuslaji3] ([id], [luotu], [koulutuslaji3_koodi], [koulutuslaji3], [koulutuslaji3_SV], [koulutuslaji3_EN], [jarjestys_koulutuslaji3], [koulutuslaji4], [koulutuslaji4_SV], [koulutuslaji4_EN], [jarjestys_koulutuslaji4], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (17, CAST(N'2020-01-07' AS Date), N'71', N'Ammatilliset perustutkinnot (ei oppisopimuskoulutus)', N'Yrkesinriktade grundexamina (ej läroavtalsutbildning)', N'Initial vocational qualifications (not apprenticeship training)', N'310', N'Ammatilliset perustutkinnot (ei sisällä koulutussopimus- eikä oppisopimusjaksoja)', N'Grundläggande yrkesutbildning (omfattar inte utbildningsavtals- eller läroavtalsperioder)', N'Initial vocational qualifications (training agreement or apprenticeship training periods not included)', N'301', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Ei oppisopimuskoulutus', N'Ej läroavtalsutbildning', N'Not apprenticeship training', N'01', N'ammatillinen peruskoulutus', N'grundläggande yrkesutbildning', N'vocational upper secondary education and training', N'01', N'E', N'0', N'Tilastokeskus', N'')
GO
INSERT [dbo].[koulutuslaji3] ([id], [luotu], [koulutuslaji3_koodi], [koulutuslaji3], [koulutuslaji3_SV], [koulutuslaji3_EN], [jarjestys_koulutuslaji3], [koulutuslaji4], [koulutuslaji4_SV], [koulutuslaji4_EN], [jarjestys_koulutuslaji4], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (27, CAST(N'2020-01-07' AS Date), N'81', N'Oppisopimuskoulutus', N'Läroavtalsutbildning', N'Apprenticeship training', N'350', N'Ammattitutkinnot (sisältää oppisopimusjaksoja)', N'Yrkesexamen (omfattar läroavtalsperioder)', N'Further vocational qualifications (apprenticeship training periods included)', N'305', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Oppisopimuskoulutus', N'Läroavtalsutbildning', N'Apprenticeship training', N'02', N'ammattitutkinto', N'yrkesexamen', N'further vocational qualification', N'02', N'E', N'0', N'Tilastokeskus', N'')
GO
INSERT [dbo].[koulutuslaji3] ([id], [luotu], [koulutuslaji3_koodi], [koulutuslaji3], [koulutuslaji3_SV], [koulutuslaji3_EN], [jarjestys_koulutuslaji3], [koulutuslaji4], [koulutuslaji4_SV], [koulutuslaji4_EN], [jarjestys_koulutuslaji4], [jarjestamistapa], [jarjestamistapa_SV], [jarjestamistapa_EN], [jarjestys_jarjestamistapa], [jarjestamismuoto], [jarjestamismuoto_SV], [jarjestamismuoto_EN], [jarjestys_jarjestamismuoto], [tutkintotyyppi], [tutkintotyyppi_SV], [tutkintotyyppi_EN], [jarjestys_tutkintotyyppi], [virhetilanne], [poistettu], [tietolahde], [kommentti]) VALUES (28, CAST(N'2020-01-07' AS Date), N'82', N'Oppisopimuskoulutus', N'Läroavtalsutbildning', N'Apprenticeship training', N'350', N'Erikoisammattitutkinnot (sisältää oppisopimusjaksoja)', N'Specialyrkesexamen (omfattar läroavtalsperioder)', N'Specialist vocational qualifications (apprenticeship training periods included)', N'306', N'Tuntematon', N'Okänd', N'Unknown', N'98', N'Oppisopimuskoulutus', N'Läroavtalsutbildning', N'Apprenticeship training', N'02', N'erikoisammattitutkinto', N'specialyrkesexamen', N'specialist vocational qualification', N'03', N'E', N'0', N'Tilastokeskus', N'')
GO
