USE [VipunenTK_DW]
GO

/****** Object:  View [dbo].[v_alueluokitus_nykytila]    Script Date: 9.9.2021 12:28:22 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


/* Korvattu is not null -> <> '', jotta erityisesti liitoskuntakoodit eivät "tyhjene", ja ohjattu aidosti liittämättömien koodi nulliksi -Juha 9.9.2021 */
/* Ajettu replace liitoskunta_koodi -> kunta_koodi kaikkiin sarakkeisiin [kunta]-[tietolahde] -Anssi 14.12.2017 */

ALTER VIEW [dbo].[v_alueluokitus_nykytila] AS
/*
-- HUOM [VipunenTK].[dbo].[d_alueluokitus_historia] pitää olla olemassa
Drop table VipunenTK.dbo.d_alueluokitus_nykytila
Select * into VipunenTK.dbo.d_alueluokitus_nykytila from VipunenTK_DW.dbo.v_alueluokitus_nykytila
Truncate table VipunenTK.dbo.d_alueluokitus_nykytila
Insert into VipunenTK.dbo.d_alueluokitus_nykytila
  Select * from VipunenTK_DW.dbo.v_alueluokitus_nykytila
*/

SELECT al.id
      ,al.alueluokitus_avain
      ,al.kunta_koodi
      --,[viimeisin_tilv]
      ,[liitoskunta_koodi] = Case when al_uusi_6.liitoskunta_koodi <> '' then al_uusi_6.liitoskunta_koodi when al_uusi_5.liitoskunta_koodi <> '' then al_uusi_5.liitoskunta_koodi when al_uusi_4.liitoskunta_koodi <> '' then al_uusi_4.liitoskunta_koodi when al_uusi_3.liitoskunta_koodi <> '' then al_uusi_3.liitoskunta_koodi when al_uusi_2.liitoskunta_koodi <> '' then al_uusi_2.liitoskunta_koodi when al_uusi.liitoskunta_koodi <> '' then al_uusi.liitoskunta_koodi else nullif(coalesce(al.liitoskunta_koodi,''),'') end
      ,[kunta] = Case when al_uusi_6.kunta_koodi <> '' then al_uusi_6.kunta when al_uusi_5.kunta_koodi <> '' then al_uusi_5.kunta when al_uusi_4.kunta_koodi <> '' then al_uusi_4.kunta when al_uusi_3.kunta_koodi <> '' then al_uusi_3.kunta when al_uusi_2.kunta_koodi <> '' then al_uusi_2.kunta when al_uusi.kunta_koodi <> '' then al_uusi.kunta else al.kunta end 
      ,[kunta_SV] = Case when al_uusi_6.kunta_koodi <> '' then al_uusi_6.kunta_SV when al_uusi_5.kunta_koodi <> '' then al_uusi_5.kunta_SV when al_uusi_4.kunta_koodi <> '' then al_uusi_4.kunta_SV when al_uusi_3.kunta_koodi <> '' then al_uusi_3.kunta_SV when al_uusi_2.kunta_koodi <> '' then al_uusi_2.kunta_SV when al_uusi.kunta_koodi <> '' then al_uusi.kunta_SV else al.kunta_SV end
      ,[kunta_EN] = Case when al_uusi_6.kunta_koodi <> '' then al_uusi_6.kunta_EN when al_uusi_5.kunta_koodi <> '' then al_uusi_5.kunta_EN when al_uusi_4.kunta_koodi <> '' then al_uusi_4.kunta_EN when al_uusi_3.kunta_koodi <> '' then al_uusi_3.kunta_EN when al_uusi_2.kunta_koodi <> '' then al_uusi_2.kunta_EN when al_uusi.kunta_koodi <> '' then al_uusi.kunta_EN else al.kunta_EN end
      ,[maakunta_koodi] = Case when al_uusi_6.kunta_koodi <> '' then al_uusi_6.maakunta_koodi when al_uusi_5.kunta_koodi <> '' then al_uusi_5.maakunta_koodi when al_uusi_4.kunta_koodi <> '' then al_uusi_4.maakunta_koodi when al_uusi_3.kunta_koodi <> '' then al_uusi_3.maakunta_koodi when al_uusi_2.kunta_koodi <> '' then al_uusi_2.maakunta_koodi when al_uusi.kunta_koodi <> '' then al_uusi.maakunta_koodi else al.maakunta_koodi end
      ,[maakunta] = Case when al_uusi_6.kunta_koodi <> '' then al_uusi_6.maakunta when al_uusi_5.kunta_koodi <> '' then al_uusi_5.maakunta when al_uusi_4.kunta_koodi <> '' then al_uusi_4.maakunta when al_uusi_3.kunta_koodi <> '' then al_uusi_3.maakunta when al_uusi_2.kunta_koodi <> '' then al_uusi_2.maakunta when al_uusi.kunta_koodi <> '' then al_uusi.maakunta else al.maakunta end
      ,[maakunta_SV] = Case when al_uusi_6.kunta_koodi <> '' then al_uusi_6.maakunta_SV when al_uusi_5.kunta_koodi <> '' then al_uusi_5.maakunta_SV when al_uusi_4.kunta_koodi <> '' then al_uusi_4.maakunta_SV when al_uusi_3.kunta_koodi <> '' then al_uusi_3.maakunta_SV when al_uusi_2.kunta_koodi <> '' then al_uusi_2.maakunta_SV when al_uusi.kunta_koodi <> '' then al_uusi.maakunta_SV else al.maakunta_SV end
      ,[maakunta_EN] = Case when al_uusi_6.kunta_koodi <> '' then al_uusi_6.maakunta_EN when al_uusi_5.kunta_koodi <> '' then al_uusi_5.maakunta_EN when al_uusi_4.kunta_koodi <> '' then al_uusi_4.maakunta_EN when al_uusi_3.kunta_koodi <> '' then al_uusi_3.maakunta_EN when al_uusi_2.kunta_koodi <> '' then al_uusi_2.maakunta_EN when al_uusi.kunta_koodi <> '' then al_uusi.maakunta_EN else al.maakunta_EN end
      ,[avi_koodi] = Case when al_uusi_6.kunta_koodi <> '' then al_uusi_6.avi_koodi when al_uusi_5.kunta_koodi <> '' then al_uusi_5.avi_koodi when al_uusi_4.kunta_koodi <> '' then al_uusi_4.avi_koodi when al_uusi_3.kunta_koodi <> '' then al_uusi_3.avi_koodi when al_uusi_2.kunta_koodi <> '' then al_uusi_2.avi_koodi when al_uusi.kunta_koodi <> '' then al_uusi.avi_koodi else al.avi_koodi end
      ,[avi] = Case when al_uusi_6.kunta_koodi <> '' then al_uusi_6.avi when al_uusi_5.kunta_koodi <> '' then al_uusi_5.avi when al_uusi_4.kunta_koodi <> '' then al_uusi_4.avi when al_uusi_3.kunta_koodi <> '' then al_uusi_3.avi when al_uusi_2.kunta_koodi <> '' then al_uusi_2.avi when al_uusi.kunta_koodi <> '' then al_uusi.avi else al.avi end
      ,[avi_SV] = Case when al_uusi_6.kunta_koodi <> '' then al_uusi_6.avi_SV when al_uusi_5.kunta_koodi <> '' then al_uusi_5.avi_SV when al_uusi_4.kunta_koodi <> '' then al_uusi_4.avi_SV when al_uusi_3.kunta_koodi <> '' then al_uusi_3.avi_SV when al_uusi_2.kunta_koodi <> '' then al_uusi_2.avi_SV when al_uusi.kunta_koodi <> '' then al_uusi.avi_SV else al.avi_SV end
      ,[avi_EN] = Case when al_uusi_6.kunta_koodi <> '' then al_uusi_6.avi_EN when al_uusi_5.kunta_koodi <> '' then al_uusi_5.avi_EN when al_uusi_4.kunta_koodi <> '' then al_uusi_4.avi_EN when al_uusi_3.kunta_koodi <> '' then al_uusi_3.avi_EN when al_uusi_2.kunta_koodi <> '' then al_uusi_2.avi_EN when al_uusi.kunta_koodi <> '' then al_uusi.avi_EN else al.avi_EN end
      ,[ely_koodi] = Case when al_uusi_6.kunta_koodi <> '' then al_uusi_6.ely_koodi when al_uusi_5.kunta_koodi <> '' then al_uusi_5.ely_koodi when al_uusi_4.kunta_koodi <> '' then al_uusi_4.ely_koodi when al_uusi_3.kunta_koodi <> '' then al_uusi_3.ely_koodi when al_uusi_2.kunta_koodi <> '' then al_uusi_2.ely_koodi when al_uusi.kunta_koodi <> '' then al_uusi.ely_koodi else al.ely_koodi end
      ,[ely] = Case when al_uusi_6.kunta_koodi <> '' then al_uusi_6.ely when al_uusi_5.kunta_koodi <> '' then al_uusi_5.ely when al_uusi_4.kunta_koodi <> '' then al_uusi_4.ely when al_uusi_3.kunta_koodi <> '' then al_uusi_3.ely when al_uusi_2.kunta_koodi <> '' then al_uusi_2.ely when al_uusi.kunta_koodi <> '' then al_uusi.ely else al.ely end
      ,[ely_SV] = Case when al_uusi_6.kunta_koodi <> '' then al_uusi_6.ely_SV when al_uusi_5.kunta_koodi <> '' then al_uusi_5.ely_SV when al_uusi_4.kunta_koodi <> '' then al_uusi_4.ely_SV when al_uusi_3.kunta_koodi <> '' then al_uusi_3.ely_SV when al_uusi_2.kunta_koodi <> '' then al_uusi_2.ely_SV when al_uusi.kunta_koodi <> '' then al_uusi.ely_SV else al.ely_SV end
      ,[ely_EN] = Case when al_uusi_6.kunta_koodi <> '' then al_uusi_6.ely_EN when al_uusi_5.kunta_koodi <> '' then al_uusi_5.ely_EN when al_uusi_4.kunta_koodi <> '' then al_uusi_4.ely_EN when al_uusi_3.kunta_koodi <> '' then al_uusi_3.ely_EN when al_uusi_2.kunta_koodi <> '' then al_uusi_2.ely_EN when al_uusi.kunta_koodi <> '' then al_uusi.ely_EN else al.ely_EN end
      ,[seutukunta_koodi] = Case when al_uusi_6.kunta_koodi <> '' then al_uusi_6.seutukunta_koodi when al_uusi_5.kunta_koodi <> '' then al_uusi_5.seutukunta_koodi when al_uusi_4.kunta_koodi <> '' then al_uusi_4.seutukunta_koodi when al_uusi_3.kunta_koodi <> '' then al_uusi_3.seutukunta_koodi when al_uusi_2.kunta_koodi <> '' then al_uusi_2.seutukunta_koodi when al_uusi.kunta_koodi <> '' then al_uusi.seutukunta_koodi else al.seutukunta_koodi end
      ,[seutukunta] = Case when al_uusi_6.kunta_koodi <> '' then al_uusi_6.seutukunta when al_uusi_5.kunta_koodi <> '' then al_uusi_5.seutukunta when al_uusi_4.kunta_koodi <> '' then al_uusi_4.seutukunta when al_uusi_3.kunta_koodi <> '' then al_uusi_3.seutukunta when al_uusi_2.kunta_koodi <> '' then al_uusi_2.seutukunta when al_uusi.kunta_koodi <> '' then al_uusi.seutukunta else al.seutukunta end
      ,[seutukunta_SV] = Case when al_uusi_6.kunta_koodi <> '' then al_uusi_6.seutukunta_SV when al_uusi_5.kunta_koodi <> '' then al_uusi_5.seutukunta_SV when al_uusi_4.kunta_koodi <> '' then al_uusi_4.seutukunta_SV when al_uusi_3.kunta_koodi <> '' then al_uusi_3.seutukunta_SV when al_uusi_2.kunta_koodi <> '' then al_uusi_2.seutukunta_SV when al_uusi.kunta_koodi <> '' then al_uusi.seutukunta_SV else al.seutukunta_SV end
      ,[seutukunta_EN] = Case when al_uusi_6.kunta_koodi <> '' then al_uusi_6.seutukunta_EN when al_uusi_5.kunta_koodi <> '' then al_uusi_5.seutukunta_EN when al_uusi_4.kunta_koodi <> '' then al_uusi_4.seutukunta_EN when al_uusi_3.kunta_koodi <> '' then al_uusi_3.seutukunta_EN when al_uusi_2.kunta_koodi <> '' then al_uusi_2.seutukunta_EN when al_uusi.kunta_koodi <> '' then al_uusi.seutukunta_EN else al.seutukunta_EN end
      ,[suuralue_koodi] = Case when al_uusi_6.kunta_koodi <> '' then al_uusi_6.suuralue_koodi when al_uusi_5.kunta_koodi <> '' then al_uusi_5.suuralue_koodi when al_uusi_4.kunta_koodi <> '' then al_uusi_4.suuralue_koodi when al_uusi_3.kunta_koodi <> '' then al_uusi_3.suuralue_koodi when al_uusi_2.kunta_koodi <> '' then al_uusi_2.suuralue_koodi when al_uusi.kunta_koodi <> '' then al_uusi.suuralue_koodi else al.suuralue_koodi end
      ,[suuralue] = Case when al_uusi_6.kunta_koodi <> '' then al_uusi_6.suuralue when al_uusi_5.kunta_koodi <> '' then al_uusi_5.suuralue when al_uusi_4.kunta_koodi <> '' then al_uusi_4.suuralue when al_uusi_3.kunta_koodi <> '' then al_uusi_3.suuralue when al_uusi_2.kunta_koodi <> '' then al_uusi_2.suuralue when al_uusi.kunta_koodi <> '' then al_uusi.suuralue else al.suuralue end
      ,[suuralue_SV] = Case when al_uusi_6.kunta_koodi <> '' then al_uusi_6.suuralue_SV when al_uusi_5.kunta_koodi <> '' then al_uusi_5.suuralue_SV when al_uusi_4.kunta_koodi <> '' then al_uusi_4.suuralue_SV when al_uusi_3.kunta_koodi <> '' then al_uusi_3.suuralue_SV when al_uusi_2.kunta_koodi <> '' then al_uusi_2.suuralue_SV when al_uusi.kunta_koodi <> '' then al_uusi.suuralue_SV else al.suuralue_SV end
      ,[suuralue_EN] = Case when al_uusi_6.kunta_koodi <> '' then al_uusi_6.suuralue_EN when al_uusi_5.kunta_koodi <> '' then al_uusi_5.suuralue_EN when al_uusi_4.kunta_koodi <> '' then al_uusi_4.suuralue_EN when al_uusi_3.kunta_koodi <> '' then al_uusi_3.suuralue_EN when al_uusi_2.kunta_koodi <> '' then al_uusi_2.suuralue_EN when al_uusi.kunta_koodi <> '' then al_uusi.suuralue_EN else al.suuralue_EN end
      ,[kuntaryhma_koodi] = Case when al_uusi_6.kunta_koodi <> '' then al_uusi_6.kuntaryhma_koodi when al_uusi_5.kunta_koodi <> '' then al_uusi_5.kuntaryhma_koodi when al_uusi_4.kunta_koodi <> '' then al_uusi_4.kuntaryhma_koodi when al_uusi_3.kunta_koodi <> '' then al_uusi_3.kuntaryhma_koodi when al_uusi_2.kunta_koodi <> '' then al_uusi_2.kuntaryhma_koodi when al_uusi.kunta_koodi <> '' then al_uusi.kuntaryhma_koodi else al.kuntaryhma_koodi end
      ,[kuntaryhma] = Case when al_uusi_6.kunta_koodi <> '' then al_uusi_6.kuntaryhma when al_uusi_5.kunta_koodi <> '' then al_uusi_5.kuntaryhma when al_uusi_4.kunta_koodi <> '' then al_uusi_4.kuntaryhma when al_uusi_3.kunta_koodi <> '' then al_uusi_3.kuntaryhma when al_uusi_2.kunta_koodi <> '' then al_uusi_2.kuntaryhma when al_uusi.kunta_koodi <> '' then al_uusi.kuntaryhma else al.kuntaryhma end
      ,[kuntaryhma_SV] = Case when al_uusi_6.kunta_koodi <> '' then al_uusi_6.kuntaryhma_SV when al_uusi_5.kunta_koodi <> '' then al_uusi_5.kuntaryhma_SV when al_uusi_4.kunta_koodi <> '' then al_uusi_4.kuntaryhma_SV when al_uusi_3.kunta_koodi <> '' then al_uusi_3.kuntaryhma_SV when al_uusi_2.kunta_koodi <> '' then al_uusi_2.kuntaryhma_SV when al_uusi.kunta_koodi <> '' then al_uusi.kuntaryhma_SV else al.kuntaryhma_SV end
      ,[kuntaryhma_EN] = Case when al_uusi_6.kunta_koodi <> '' then al_uusi_6.kuntaryhma_EN when al_uusi_5.kunta_koodi <> '' then al_uusi_5.kuntaryhma_EN when al_uusi_4.kunta_koodi <> '' then al_uusi_4.kuntaryhma_EN when al_uusi_3.kunta_koodi <> '' then al_uusi_3.kuntaryhma_EN when al_uusi_2.kunta_koodi <> '' then al_uusi_2.kuntaryhma_EN when al_uusi.kunta_koodi <> '' then al_uusi.kuntaryhma_EN else al.kuntaryhma_EN end
      ,[laani_koodi] = Case when al_uusi_6.kunta_koodi <> '' then al_uusi_6.laani_koodi when al_uusi_5.kunta_koodi <> '' then al_uusi_5.laani_koodi when al_uusi_4.kunta_koodi <> '' then al_uusi_4.laani_koodi when al_uusi_3.kunta_koodi <> '' then al_uusi_3.laani_koodi when al_uusi_2.kunta_koodi <> '' then al_uusi_2.laani_koodi when al_uusi.kunta_koodi <> '' then al_uusi.laani_koodi else al.laani_koodi end
      ,[laani] = Case when al_uusi_6.kunta_koodi <> '' then al_uusi_6.laani when al_uusi_5.kunta_koodi <> '' then al_uusi_5.laani when al_uusi_4.kunta_koodi <> '' then al_uusi_4.laani when al_uusi_3.kunta_koodi <> '' then al_uusi_3.laani when al_uusi_2.kunta_koodi <> '' then al_uusi_2.laani when al_uusi.kunta_koodi <> '' then al_uusi.laani else al.laani end
      ,[laani_SV] = Case when al_uusi_6.kunta_koodi <> '' then al_uusi_6.laani_SV when al_uusi_5.kunta_koodi <> '' then al_uusi_5.laani_SV when al_uusi_4.kunta_koodi <> '' then al_uusi_4.laani_SV when al_uusi_3.kunta_koodi <> '' then al_uusi_3.laani_SV when al_uusi_2.kunta_koodi <> '' then al_uusi_2.laani_SV when al_uusi.kunta_koodi <> '' then al_uusi.laani_SV else al.laani_SV end
      ,[laani_EN] = Case when al_uusi_6.kunta_koodi <> '' then al_uusi_6.laani_EN when al_uusi_5.kunta_koodi <> '' then al_uusi_5.laani_EN when al_uusi_4.kunta_koodi <> '' then al_uusi_4.laani_EN when al_uusi_3.kunta_koodi <> '' then al_uusi_3.laani_EN when al_uusi_2.kunta_koodi <> '' then al_uusi_2.laani_EN when al_uusi.kunta_koodi <> '' then al_uusi.laani_EN else al.laani_EN end
      ,[tyovoima_elinkeinokeskus_koodi] = Case when al_uusi_6.kunta_koodi <> '' then al_uusi_6.tyovoima_elinkeinokeskus_koodi when al_uusi_5.kunta_koodi <> '' then al_uusi_5.tyovoima_elinkeinokeskus_koodi when al_uusi_4.kunta_koodi <> '' then al_uusi_4.tyovoima_elinkeinokeskus_koodi when al_uusi_3.kunta_koodi <> '' then al_uusi_3.tyovoima_elinkeinokeskus_koodi when al_uusi_2.kunta_koodi <> '' then al_uusi_2.tyovoima_elinkeinokeskus_koodi when al_uusi.kunta_koodi <> '' then al_uusi.tyovoima_elinkeinokeskus_koodi else al.tyovoima_elinkeinokeskus_koodi end
      ,[tyovoima_elinkeinokeskus] = Case when al_uusi_6.kunta_koodi <> '' then al_uusi_6.tyovoima_elinkeinokeskus when al_uusi_5.kunta_koodi <> '' then al_uusi_5.tyovoima_elinkeinokeskus when al_uusi_4.kunta_koodi <> '' then al_uusi_4.tyovoima_elinkeinokeskus when al_uusi_3.kunta_koodi <> '' then al_uusi_3.tyovoima_elinkeinokeskus when al_uusi_2.kunta_koodi <> '' then al_uusi_2.tyovoima_elinkeinokeskus when al_uusi.kunta_koodi <> '' then al_uusi.tyovoima_elinkeinokeskus else al.tyovoima_elinkeinokeskus end
      ,[tyovoima_elinkeinokeskus_SV] = Case when al_uusi_6.kunta_koodi <> '' then al_uusi_6.tyovoima_elinkeinokeskus_SV when al_uusi_5.kunta_koodi <> '' then al_uusi_5.tyovoima_elinkeinokeskus_SV when al_uusi_4.kunta_koodi <> '' then al_uusi_4.tyovoima_elinkeinokeskus_SV when al_uusi_3.kunta_koodi <> '' then al_uusi_3.tyovoima_elinkeinokeskus_SV when al_uusi_2.kunta_koodi <> '' then al_uusi_2.tyovoima_elinkeinokeskus_SV when al_uusi.kunta_koodi <> '' then al_uusi.tyovoima_elinkeinokeskus_SV else al.tyovoima_elinkeinokeskus_SV end
      ,[tyovoima_elinkeinokeskus_EN] = Case when al_uusi_6.kunta_koodi <> '' then al_uusi_6.tyovoima_elinkeinokeskus_EN when al_uusi_5.kunta_koodi <> '' then al_uusi_5.tyovoima_elinkeinokeskus_EN when al_uusi_4.kunta_koodi <> '' then al_uusi_4.tyovoima_elinkeinokeskus_EN when al_uusi_3.kunta_koodi <> '' then al_uusi_3.tyovoima_elinkeinokeskus_EN when al_uusi_2.kunta_koodi <> '' then al_uusi_2.tyovoima_elinkeinokeskus_EN when al_uusi.kunta_koodi <> '' then al_uusi.tyovoima_elinkeinokeskus_EN else al.tyovoima_elinkeinokeskus_EN end
      ,[kielisuhde_koodi] = Case when al_uusi_6.kunta_koodi <> '' then al_uusi_6.kielisuhde_koodi when al_uusi_5.kunta_koodi <> '' then al_uusi_5.kielisuhde_koodi when al_uusi_4.kunta_koodi <> '' then al_uusi_4.kielisuhde_koodi when al_uusi_3.kunta_koodi <> '' then al_uusi_3.kielisuhde_koodi when al_uusi_2.kunta_koodi <> '' then al_uusi_2.kielisuhde_koodi when al_uusi.kunta_koodi <> '' then al_uusi.kielisuhde_koodi else al.kielisuhde_koodi end
      ,[kielisuhde] = Case when al_uusi_6.kunta_koodi <> '' then al_uusi_6.kielisuhde when al_uusi_5.kunta_koodi <> '' then al_uusi_5.kielisuhde when al_uusi_4.kunta_koodi <> '' then al_uusi_4.kielisuhde when al_uusi_3.kunta_koodi <> '' then al_uusi_3.kielisuhde when al_uusi_2.kunta_koodi <> '' then al_uusi_2.kielisuhde when al_uusi.kunta_koodi <> '' then al_uusi.kielisuhde else al.kielisuhde end
      ,[kielisuhde_SV] = Case when al_uusi_6.kunta_koodi <> '' then al_uusi_6.kielisuhde_SV when al_uusi_5.kunta_koodi <> '' then al_uusi_5.kielisuhde_SV when al_uusi_4.kunta_koodi <> '' then al_uusi_4.kielisuhde_SV when al_uusi_3.kunta_koodi <> '' then al_uusi_3.kielisuhde_SV when al_uusi_2.kunta_koodi <> '' then al_uusi_2.kielisuhde_SV when al_uusi.kunta_koodi <> '' then al_uusi.kielisuhde_SV else al.kielisuhde_SV end
      ,[kielisuhde_EN] = Case when al_uusi_6.kunta_koodi <> '' then al_uusi_6.kielisuhde_EN when al_uusi_5.kunta_koodi <> '' then al_uusi_5.kielisuhde_EN when al_uusi_4.kunta_koodi <> '' then al_uusi_4.kielisuhde_EN when al_uusi_3.kunta_koodi <> '' then al_uusi_3.kielisuhde_EN when al_uusi_2.kunta_koodi <> '' then al_uusi_2.kielisuhde_EN when al_uusi.kunta_koodi <> '' then al_uusi.kielisuhde_EN else al.kielisuhde_EN end
      ,[mannersuomi_ahvenanmaa_koodi] = Case when al_uusi_6.kunta_koodi <> '' then al_uusi_6.mannersuomi_ahvenanmaa_koodi when al_uusi_5.kunta_koodi <> '' then al_uusi_5.mannersuomi_ahvenanmaa_koodi when al_uusi_4.kunta_koodi <> '' then al_uusi_4.mannersuomi_ahvenanmaa_koodi when al_uusi_3.kunta_koodi <> '' then al_uusi_3.mannersuomi_ahvenanmaa_koodi when al_uusi_2.kunta_koodi <> '' then al_uusi_2.mannersuomi_ahvenanmaa_koodi when al_uusi.kunta_koodi <> '' then al_uusi.mannersuomi_ahvenanmaa_koodi else al.mannersuomi_ahvenanmaa_koodi end
      ,[mannersuomi_ahvenanmaa] = Case when al_uusi_6.kunta_koodi <> '' then al_uusi_6.mannersuomi_ahvenanmaa when al_uusi_5.kunta_koodi <> '' then al_uusi_5.mannersuomi_ahvenanmaa when al_uusi_4.kunta_koodi <> '' then al_uusi_4.mannersuomi_ahvenanmaa when al_uusi_3.kunta_koodi <> '' then al_uusi_3.mannersuomi_ahvenanmaa when al_uusi_2.kunta_koodi <> '' then al_uusi_2.mannersuomi_ahvenanmaa when al_uusi.kunta_koodi <> '' then al_uusi.mannersuomi_ahvenanmaa else al.mannersuomi_ahvenanmaa end
      ,[mannersuomi_ahvenanmaa_SV] = Case when al_uusi_6.kunta_koodi <> '' then al_uusi_6.mannersuomi_ahvenanmaa_SV when al_uusi_5.kunta_koodi <> '' then al_uusi_5.mannersuomi_ahvenanmaa_SV when al_uusi_4.kunta_koodi <> '' then al_uusi_4.mannersuomi_ahvenanmaa_SV when al_uusi_3.kunta_koodi <> '' then al_uusi_3.mannersuomi_ahvenanmaa_SV when al_uusi_2.kunta_koodi <> '' then al_uusi_2.mannersuomi_ahvenanmaa_SV when al_uusi.kunta_koodi <> '' then al_uusi.mannersuomi_ahvenanmaa_SV else al.mannersuomi_ahvenanmaa_SV end
      ,[mannersuomi_ahvenanmaa_EN] = Case when al_uusi_6.kunta_koodi <> '' then al_uusi_6.mannersuomi_ahvenanmaa_EN when al_uusi_5.kunta_koodi <> '' then al_uusi_5.mannersuomi_ahvenanmaa_EN when al_uusi_4.kunta_koodi <> '' then al_uusi_4.mannersuomi_ahvenanmaa_EN when al_uusi_3.kunta_koodi <> '' then al_uusi_3.mannersuomi_ahvenanmaa_EN when al_uusi_2.kunta_koodi <> '' then al_uusi_2.mannersuomi_ahvenanmaa_EN when al_uusi.kunta_koodi <> '' then al_uusi.mannersuomi_ahvenanmaa_EN else al.mannersuomi_ahvenanmaa_EN end
      ,[SCD_alkaa] = Case when al_uusi_6.kunta_koodi <> '' then al_uusi_6.SCD_alkaa when al_uusi_5.kunta_koodi <> '' then al_uusi_5.SCD_alkaa when al_uusi_4.kunta_koodi <> '' then al_uusi_4.SCD_alkaa when al_uusi_3.kunta_koodi <> '' then al_uusi_3.SCD_alkaa when al_uusi_2.kunta_koodi <> '' then al_uusi_2.SCD_alkaa when al_uusi.kunta_koodi <> '' then al_uusi.SCD_alkaa else al.SCD_alkaa end
      ,[SCD_paattyy] = Case when al_uusi_6.kunta_koodi <> '' then al_uusi_6.SCD_paattyy when al_uusi_5.kunta_koodi <> '' then al_uusi_5.SCD_paattyy when al_uusi_4.kunta_koodi <> '' then al_uusi_4.SCD_paattyy when al_uusi_3.kunta_koodi <> '' then al_uusi_3.SCD_paattyy when al_uusi_2.kunta_koodi <> '' then al_uusi_2.SCD_paattyy when al_uusi.kunta_koodi <> '' then al_uusi.SCD_paattyy else al.SCD_paattyy end
      ,[jarjestys] = Case when al_uusi_6.kunta_koodi <> '' then al_uusi_6.jarjestys when al_uusi_5.kunta_koodi <> '' then al_uusi_5.jarjestys when al_uusi_4.kunta_koodi <> '' then al_uusi_4.jarjestys when al_uusi_3.kunta_koodi <> '' then al_uusi_3.jarjestys when al_uusi_2.kunta_koodi <> '' then al_uusi_2.jarjestys when al_uusi.kunta_koodi <> '' then al_uusi.jarjestys else al.jarjestys end
      ,[jarjestys_maakunta] = Case when al_uusi_6.kunta_koodi <> '' then al_uusi_6.jarjestys_maakunta when al_uusi_5.kunta_koodi <> '' then al_uusi_5.jarjestys_maakunta when al_uusi_4.kunta_koodi <> '' then al_uusi_4.jarjestys_maakunta when al_uusi_3.kunta_koodi <> '' then al_uusi_3.jarjestys_maakunta when al_uusi_2.kunta_koodi <> '' then al_uusi_2.jarjestys_maakunta when al_uusi.kunta_koodi <> '' then al_uusi.jarjestys_maakunta else al.jarjestys_maakunta end
      ,[jarjestys_avi] = Case when al_uusi_6.kunta_koodi <> '' then al_uusi_6.jarjestys_avi when al_uusi_5.kunta_koodi <> '' then al_uusi_5.jarjestys_avi when al_uusi_4.kunta_koodi <> '' then al_uusi_4.jarjestys_avi when al_uusi_3.kunta_koodi <> '' then al_uusi_3.jarjestys_avi when al_uusi_2.kunta_koodi <> '' then al_uusi_2.jarjestys_avi when al_uusi.kunta_koodi <> '' then al_uusi.jarjestys_avi else al.jarjestys_avi end
      ,[jarjestys_ely] = Case when al_uusi_6.kunta_koodi <> '' then al_uusi_6.jarjestys_ely when al_uusi_5.kunta_koodi <> '' then al_uusi_5.jarjestys_ely when al_uusi_4.kunta_koodi <> '' then al_uusi_4.jarjestys_ely when al_uusi_3.kunta_koodi <> '' then al_uusi_3.jarjestys_ely when al_uusi_2.kunta_koodi <> '' then al_uusi_2.jarjestys_ely when al_uusi.kunta_koodi <> '' then al_uusi.jarjestys_ely else al.jarjestys_ely end
      ,[jarjestys_seutukunta] = Case when al_uusi_6.kunta_koodi <> '' then al_uusi_6.jarjestys_seutukunta when al_uusi_5.kunta_koodi <> '' then al_uusi_5.jarjestys_seutukunta when al_uusi_4.kunta_koodi <> '' then al_uusi_4.jarjestys_seutukunta when al_uusi_3.kunta_koodi <> '' then al_uusi_3.jarjestys_seutukunta when al_uusi_2.kunta_koodi <> '' then al_uusi_2.jarjestys_seutukunta when al_uusi.kunta_koodi <> '' then al_uusi.jarjestys_seutukunta else al.jarjestys_seutukunta end
      ,[jarjestys_suuralue] = Case when al_uusi_6.kunta_koodi <> '' then al_uusi_6.jarjestys_suuralue when al_uusi_5.kunta_koodi <> '' then al_uusi_5.jarjestys_suuralue when al_uusi_4.kunta_koodi <> '' then al_uusi_4.jarjestys_suuralue when al_uusi_3.kunta_koodi <> '' then al_uusi_3.jarjestys_suuralue when al_uusi_2.kunta_koodi <> '' then al_uusi_2.jarjestys_suuralue when al_uusi.kunta_koodi <> '' then al_uusi.jarjestys_suuralue else al.jarjestys_suuralue end
      ,[jarjestys_kuntaryhma] = Case when al_uusi_6.kunta_koodi <> '' then al_uusi_6.jarjestys_kuntaryhma when al_uusi_5.kunta_koodi <> '' then al_uusi_5.jarjestys_kuntaryhma when al_uusi_4.kunta_koodi <> '' then al_uusi_4.jarjestys_kuntaryhma when al_uusi_3.kunta_koodi <> '' then al_uusi_3.jarjestys_kuntaryhma when al_uusi_2.kunta_koodi <> '' then al_uusi_2.jarjestys_kuntaryhma when al_uusi.kunta_koodi <> '' then al_uusi.jarjestys_kuntaryhma else al.jarjestys_kuntaryhma end
      ,[jarjestys_laani] = Case when al_uusi_6.kunta_koodi <> '' then al_uusi_6.jarjestys_laani when al_uusi_5.kunta_koodi <> '' then al_uusi_5.jarjestys_laani when al_uusi_4.kunta_koodi <> '' then al_uusi_4.jarjestys_laani when al_uusi_3.kunta_koodi <> '' then al_uusi_3.jarjestys_laani when al_uusi_2.kunta_koodi <> '' then al_uusi_2.jarjestys_laani when al_uusi.kunta_koodi <> '' then al_uusi.jarjestys_laani else al.jarjestys_laani end
      ,[jarjestys_tyovoima_elinkeinokeskus] = Case when al_uusi_6.kunta_koodi <> '' then al_uusi_6.jarjestys_tyovoima_elinkeinokeskus when al_uusi_5.kunta_koodi <> '' then al_uusi_5.jarjestys_tyovoima_elinkeinokeskus when al_uusi_4.kunta_koodi <> '' then al_uusi_4.jarjestys_tyovoima_elinkeinokeskus when al_uusi_3.kunta_koodi <> '' then al_uusi_3.jarjestys_tyovoima_elinkeinokeskus when al_uusi_2.kunta_koodi <> '' then al_uusi_2.jarjestys_tyovoima_elinkeinokeskus when al_uusi.kunta_koodi <> '' then al_uusi.jarjestys_tyovoima_elinkeinokeskus else al.jarjestys_tyovoima_elinkeinokeskus end
      ,[jarjestys_kielisuhde] = Case when al_uusi_6.kunta_koodi <> '' then al_uusi_6.jarjestys_kielisuhde when al_uusi_5.kunta_koodi <> '' then al_uusi_5.jarjestys_kielisuhde when al_uusi_4.kunta_koodi <> '' then al_uusi_4.jarjestys_kielisuhde when al_uusi_3.kunta_koodi <> '' then al_uusi_3.jarjestys_kielisuhde when al_uusi_2.kunta_koodi <> '' then al_uusi_2.jarjestys_kielisuhde when al_uusi.kunta_koodi <> '' then al_uusi.jarjestys_kielisuhde else al.jarjestys_kielisuhde end
      ,[jarjestys_mannersuomi_ahvenanmaa] = Case when al_uusi_6.kunta_koodi <> '' then al_uusi_6.jarjestys_mannersuomi_ahvenanmaa when al_uusi_5.kunta_koodi <> '' then al_uusi_5.jarjestys_mannersuomi_ahvenanmaa when al_uusi_4.kunta_koodi <> '' then al_uusi_4.jarjestys_mannersuomi_ahvenanmaa when al_uusi_3.kunta_koodi <> '' then al_uusi_3.jarjestys_mannersuomi_ahvenanmaa when al_uusi_2.kunta_koodi <> '' then al_uusi_2.jarjestys_mannersuomi_ahvenanmaa when al_uusi.kunta_koodi <> '' then al_uusi.jarjestys_mannersuomi_ahvenanmaa else al.jarjestys_mannersuomi_ahvenanmaa end
      ,[virhetilanne] = Case when al_uusi_6.kunta_koodi <> '' then al_uusi_6.virhetilanne when al_uusi_5.kunta_koodi <> '' then al_uusi_5.virhetilanne when al_uusi_4.kunta_koodi <> '' then al_uusi_4.virhetilanne when al_uusi_3.kunta_koodi <> '' then al_uusi_3.virhetilanne when al_uusi_2.kunta_koodi <> '' then al_uusi_2.virhetilanne when al_uusi.kunta_koodi <> '' then al_uusi.virhetilanne else al.virhetilanne end
      ,[tietolahde] = Case when al_uusi_6.kunta_koodi <> '' then al_uusi_6.tietolahde when al_uusi_5.kunta_koodi <> '' then al_uusi_5.tietolahde when al_uusi_4.kunta_koodi <> '' then al_uusi_4.tietolahde when al_uusi_3.kunta_koodi <> '' then al_uusi_3.tietolahde when al_uusi_2.kunta_koodi <> '' then al_uusi_2.tietolahde when al_uusi.kunta_koodi <> '' then al_uusi.tietolahde else al.tietolahde end
  FROM [VipunenTK_DW].[dbo].[v_alueluokitus_nykytila_koodiaeikorvattu] al


  left join [VipunenTK_DW].[dbo].[v_alueluokitus_nykytila_koodiaeikorvattu] al_uusi
	on al.liitoskunta_koodi = al_uusi.alueluokitus_avain
  left join [VipunenTK_DW].[dbo].[v_alueluokitus_nykytila_koodiaeikorvattu] al_uusi_2
	on al_uusi.liitoskunta_koodi = al_uusi_2.alueluokitus_avain
  left join [VipunenTK_DW].[dbo].[v_alueluokitus_nykytila_koodiaeikorvattu] al_uusi_3
	on al_uusi_2.liitoskunta_koodi = al_uusi_3.alueluokitus_avain
  left join [VipunenTK_DW].[dbo].[v_alueluokitus_nykytila_koodiaeikorvattu] al_uusi_4
	on al_uusi_3.liitoskunta_koodi = al_uusi_4.alueluokitus_avain
  left join [VipunenTK_DW].[dbo].[v_alueluokitus_nykytila_koodiaeikorvattu] al_uusi_5
	on al_uusi_4.liitoskunta_koodi = al_uusi_5.alueluokitus_avain
  left join [VipunenTK_DW].[dbo].[v_alueluokitus_nykytila_koodiaeikorvattu] al_uusi_6
	on al_uusi_5.liitoskunta_koodi = al_uusi_6.alueluokitus_avain




GO


