USE [VipunenTK_DW]
GO

/****** Object:  View [dbo].[_v_sa_K3_10_Tutk_suor_osuus_aloittaneista_korkeakoulut_surrogaattiavaimet_nykytila_taulusta]    Script Date: 9.9.2021 19:04:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




--amas, olosyys ja olotamm kommentoitu latauksesta ja liitoksista, koska eivät käytössä / CSC Juha 17.9.2021

ALTER View [dbo].[_v_sa_K3_10_Tutk_suor_osuus_aloittaneista_korkeakoulut_surrogaattiavaimet_nykytila_taulusta] as

/****** Script for SelectTopNRows command from SSMS  ******/
--Select * from [okm].[okm_ktpo_tiedontuotanto_in].f --> 6588 rows
--Select * from [vipunen_ETL].[v_sa_K3_9_Tutk_suor_osuus_aloittaneista_toinen_aste_surrogaattiavaimet] --> 6588 rows

SELECT [tilv]
      ,[lahde]
      ,[sp]
      ,[syntv]
      ,[aikielir1]
      ,[alvv]
      ,[allk]
      ,[alvv_kk]
      ,[allk_kk]
      ,[ololk]
      ,[klaji]
      --,[ophal]
      ,f.[jarj]
      ,[kkun]
      ,[koulk]
      ,[pohjkoulk]
      ,[rahlahde]
      ,f.[tietolahde]
      ,f.[rivinumero]
      ,f.[aineistorivinumero]

      ,f.[lkm]

      ,'amk_2000' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [amksuorv_2000] AND
      suorlk = [amksuorlk_2000] AND
      tutkmaak = [amktutkkmaak_2000] AND
      tutkjarj = [amktutkjarj_2000] AND
      tutkkoulk = [amktutkkoulk_2000]  )
      ,'ylamk_2000' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [ylamksuorv_2000] AND
      suorlk = [ylamksuorlk_2000] AND
      tutkmaak = [ylamktutkkmaak_2000] AND
      tutkjarj = [ylamktutkjarj_2000] AND
      tutkkoulk = [ylamktutkkoulk_2000]  )
      ,'alkk_2000' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [alkksuorv_2000] AND
      suorlk = [alkksuorlk_2000] AND
      tutkmaak = [alkktutkkmaak_2000] AND
      tutkjarj = [alkktutkjarj_2000] AND
      tutkkoulk = [alkktutkkoulk_2000]  )
      ,'ylkk_2000' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [ylkksuorv_2000] AND
      suorlk = [ylkksuorlk_2000] AND
      tutkmaak = [ylkktutkkmaak_2000] AND
      tutkjarj = [ylkktutkjarj_2000] AND
      tutkkoulk = [ylkktutkkoulk_2000]  )
      ,'tk_2000' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [tksuorv_2000] AND
      suorlk = [tksuorlk_2000] AND
      tutkmaak = [tktutkkmaak_2000] AND
      tutkjarj = [tktutkjarj_2000] AND
      tutkkoulk = [tktutkkoulk_2000]  )
      ,'muuta_2000' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [muutasuorv_2000] AND
      suorlk = [muutasuorlk_2000] AND
      tutkmaak = [muutatutkkmaak_2000] AND
      tutkjarj = [muutatutkjarj_2000] AND
      tutkkoulk = [muutatutkkoulk_2000]  )
      ,'amk_2001' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [amksuorv_2001] AND
      suorlk = [amksuorlk_2001] AND
      tutkmaak = [amktutkkmaak_2001] AND
      tutkjarj = [amktutkjarj_2001] AND
      tutkkoulk = [amktutkkoulk_2001]  )
      ,'ylamk_2001' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [ylamksuorv_2001] AND
      suorlk = [ylamksuorlk_2001] AND
      tutkmaak = [ylamktutkkmaak_2001] AND
      tutkjarj = [ylamktutkjarj_2001] AND
      tutkkoulk = [ylamktutkkoulk_2001]  )
      ,'alkk_2001' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [alkksuorv_2001] AND
      suorlk = [alkksuorlk_2001] AND
      tutkmaak = [alkktutkkmaak_2001] AND
      tutkjarj = [alkktutkjarj_2001] AND
      tutkkoulk = [alkktutkkoulk_2001]  )
      ,'ylkk_2001' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [ylkksuorv_2001] AND
      suorlk = [ylkksuorlk_2001] AND
      tutkmaak = [ylkktutkkmaak_2001] AND
      tutkjarj = [ylkktutkjarj_2001] AND
      tutkkoulk = [ylkktutkkoulk_2001]  )
      ,'tk_2001' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [tksuorv_2001] AND
      suorlk = [tksuorlk_2001] AND
      tutkmaak = [tktutkkmaak_2001] AND
      tutkjarj = [tktutkjarj_2001] AND
      tutkkoulk = [tktutkkoulk_2001]  )
      ,'muuta_2001' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [muutasuorv_2001] AND
      suorlk = [muutasuorlk_2001] AND
      tutkmaak = [muutatutkkmaak_2001] AND
      tutkjarj = [muutatutkjarj_2001] AND
      tutkkoulk = [muutatutkkoulk_2001]  )
      ,'amk_2002' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [amksuorv_2002] AND
      suorlk = [amksuorlk_2002] AND
      tutkmaak = [amktutkkmaak_2002] AND
      tutkjarj = [amktutkjarj_2002] AND
      tutkkoulk = [amktutkkoulk_2002]  )
      ,'ylamk_2002' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [ylamksuorv_2002] AND
      suorlk = [ylamksuorlk_2002] AND
      tutkmaak = [ylamktutkkmaak_2002] AND
      tutkjarj = [ylamktutkjarj_2002] AND
      tutkkoulk = [ylamktutkkoulk_2002]  )
      ,'alkk_2002' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [alkksuorv_2002] AND
      suorlk = [alkksuorlk_2002] AND
      tutkmaak = [alkktutkkmaak_2002] AND
      tutkjarj = [alkktutkjarj_2002] AND
      tutkkoulk = [alkktutkkoulk_2002]  )
      ,'ylkk_2002' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [ylkksuorv_2002] AND
      suorlk = [ylkksuorlk_2002] AND
      tutkmaak = [ylkktutkkmaak_2002] AND
      tutkjarj = [ylkktutkjarj_2002] AND
      tutkkoulk = [ylkktutkkoulk_2002]  )
      ,'tk_2002' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [tksuorv_2002] AND
      suorlk = [tksuorlk_2002] AND
      tutkmaak = [tktutkkmaak_2002] AND
      tutkjarj = [tktutkjarj_2002] AND
      tutkkoulk = [tktutkkoulk_2002]  )
      ,'muuta_2002' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [muutasuorv_2002] AND
      suorlk = [muutasuorlk_2002] AND
      tutkmaak = [muutatutkkmaak_2002] AND
      tutkjarj = [muutatutkjarj_2002] AND
      tutkkoulk = [muutatutkkoulk_2002]  )
      ,'amk_2003' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [amksuorv_2003] AND
      suorlk = [amksuorlk_2003] AND
      tutkmaak = [amktutkkmaak_2003] AND
      tutkjarj = [amktutkjarj_2003] AND
      tutkkoulk = [amktutkkoulk_2003]  )
      ,'ylamk_2003' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [ylamksuorv_2003] AND
      suorlk = [ylamksuorlk_2003] AND
      tutkmaak = [ylamktutkkmaak_2003] AND
      tutkjarj = [ylamktutkjarj_2003] AND
      tutkkoulk = [ylamktutkkoulk_2003]  )
      ,'alkk_2003' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [alkksuorv_2003] AND
      suorlk = [alkksuorlk_2003] AND
      tutkmaak = [alkktutkkmaak_2003] AND
      tutkjarj = [alkktutkjarj_2003] AND
      tutkkoulk = [alkktutkkoulk_2003]  )
      ,'ylkk_2003' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [ylkksuorv_2003] AND
      suorlk = [ylkksuorlk_2003] AND
      tutkmaak = [ylkktutkkmaak_2003] AND
      tutkjarj = [ylkktutkjarj_2003] AND
      tutkkoulk = [ylkktutkkoulk_2003]  )
      ,'tk_2003' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [tksuorv_2003] AND
      suorlk = [tksuorlk_2003] AND
      tutkmaak = [tktutkkmaak_2003] AND
      tutkjarj = [tktutkjarj_2003] AND
      tutkkoulk = [tktutkkoulk_2003]  )
      ,'muuta_2003' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [muutasuorv_2003] AND
      suorlk = [muutasuorlk_2003] AND
      tutkmaak = [muutatutkkmaak_2003] AND
      tutkjarj = [muutatutkjarj_2003] AND
      tutkkoulk = [muutatutkkoulk_2003]  )
      ,'amk_2004' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [amksuorv_2004] AND
      suorlk = [amksuorlk_2004] AND
      tutkmaak = [amktutkkmaak_2004] AND
      tutkjarj = [amktutkjarj_2004] AND
      tutkkoulk = [amktutkkoulk_2004]  )
      ,'ylamk_2004' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [ylamksuorv_2004] AND
      suorlk = [ylamksuorlk_2004] AND
      tutkmaak = [ylamktutkkmaak_2004] AND
      tutkjarj = [ylamktutkjarj_2004] AND
      tutkkoulk = [ylamktutkkoulk_2004]  )
      ,'alkk_2004' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [alkksuorv_2004] AND
      suorlk = [alkksuorlk_2004] AND
      tutkmaak = [alkktutkkmaak_2004] AND
      tutkjarj = [alkktutkjarj_2004] AND
      tutkkoulk = [alkktutkkoulk_2004]  )
      ,'ylkk_2004' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [ylkksuorv_2004] AND
      suorlk = [ylkksuorlk_2004] AND
      tutkmaak = [ylkktutkkmaak_2004] AND
      tutkjarj = [ylkktutkjarj_2004] AND
      tutkkoulk = [ylkktutkkoulk_2004]  )
      ,'tk_2004' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [tksuorv_2004] AND
      suorlk = [tksuorlk_2004] AND
      tutkmaak = [tktutkkmaak_2004] AND
      tutkjarj = [tktutkjarj_2004] AND
      tutkkoulk = [tktutkkoulk_2004]  )
      ,'muuta_2004' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [muutasuorv_2004] AND
      suorlk = [muutasuorlk_2004] AND
      tutkmaak = [muutatutkkmaak_2004] AND
      tutkjarj = [muutatutkjarj_2004] AND
      tutkkoulk = [muutatutkkoulk_2004]  )
      ,'amk_2005' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [amksuorv_2005] AND
      suorlk = [amksuorlk_2005] AND
      tutkmaak = [amktutkkmaak_2005] AND
      tutkjarj = [amktutkjarj_2005] AND
      tutkkoulk = [amktutkkoulk_2005]  )
      ,'ylamk_2005' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [ylamksuorv_2005] AND
      suorlk = [ylamksuorlk_2005] AND
      tutkmaak = [ylamktutkkmaak_2005] AND
      tutkjarj = [ylamktutkjarj_2005] AND
      tutkkoulk = [ylamktutkkoulk_2005]  )
      ,'alkk_2005' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [alkksuorv_2005] AND
      suorlk = [alkksuorlk_2005] AND
      tutkmaak = [alkktutkkmaak_2005] AND
      tutkjarj = [alkktutkjarj_2005] AND
      tutkkoulk = [alkktutkkoulk_2005]  )
      ,'ylkk_2005' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [ylkksuorv_2005] AND
      suorlk = [ylkksuorlk_2005] AND
      tutkmaak = [ylkktutkkmaak_2005] AND
      tutkjarj = [ylkktutkjarj_2005] AND
      tutkkoulk = [ylkktutkkoulk_2005]  )
      ,'tk_2005' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [tksuorv_2005] AND
      suorlk = [tksuorlk_2005] AND
      tutkmaak = [tktutkkmaak_2005] AND
      tutkjarj = [tktutkjarj_2005] AND
      tutkkoulk = [tktutkkoulk_2005]  )
      ,'muuta_2005' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [muutasuorv_2005] AND
      suorlk = [muutasuorlk_2005] AND
      tutkmaak = [muutatutkkmaak_2005] AND
      tutkjarj = [muutatutkjarj_2005] AND
      tutkkoulk = [muutatutkkoulk_2005]  )
      ,'amk_2006' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [amksuorv_2006] AND
      suorlk = [amksuorlk_2006] AND
      tutkmaak = [amktutkkmaak_2006] AND
      tutkjarj = [amktutkjarj_2006] AND
      tutkkoulk = [amktutkkoulk_2006]  )
      ,'ylamk_2006' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [ylamksuorv_2006] AND
      suorlk = [ylamksuorlk_2006] AND
      tutkmaak = [ylamktutkkmaak_2006] AND
      tutkjarj = [ylamktutkjarj_2006] AND
      tutkkoulk = [ylamktutkkoulk_2006]  )
      ,'alkk_2006' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [alkksuorv_2006] AND
      suorlk = [alkksuorlk_2006] AND
      tutkmaak = [alkktutkkmaak_2006] AND
      tutkjarj = [alkktutkjarj_2006] AND
      tutkkoulk = [alkktutkkoulk_2006]  )
      ,'ylkk_2006' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [ylkksuorv_2006] AND
      suorlk = [ylkksuorlk_2006] AND
      tutkmaak = [ylkktutkkmaak_2006] AND
      tutkjarj = [ylkktutkjarj_2006] AND
      tutkkoulk = [ylkktutkkoulk_2006]  )
      ,'tk_2006' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [tksuorv_2006] AND
      suorlk = [tksuorlk_2006] AND
      tutkmaak = [tktutkkmaak_2006] AND
      tutkjarj = [tktutkjarj_2006] AND
      tutkkoulk = [tktutkkoulk_2006]  )
      ,'muuta_2006' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [muutasuorv_2006] AND
      suorlk = [muutasuorlk_2006] AND
      tutkmaak = [muutatutkkmaak_2006] AND
      tutkjarj = [muutatutkjarj_2006] AND
      tutkkoulk = [muutatutkkoulk_2006]  )
      ,'amk_2007' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [amksuorv_2007] AND
      suorlk = [amksuorlk_2007] AND
      tutkmaak = [amktutkkmaak_2007] AND
      tutkjarj = [amktutkjarj_2007] AND
      tutkkoulk = [amktutkkoulk_2007]  )
      ,'ylamk_2007' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [ylamksuorv_2007] AND
      suorlk = [ylamksuorlk_2007] AND
      tutkmaak = [ylamktutkkmaak_2007] AND
      tutkjarj = [ylamktutkjarj_2007] AND
      tutkkoulk = [ylamktutkkoulk_2007]  )
      ,'alkk_2007' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [alkksuorv_2007] AND
      suorlk = [alkksuorlk_2007] AND
      tutkmaak = [alkktutkkmaak_2007] AND
      tutkjarj = [alkktutkjarj_2007] AND
      tutkkoulk = [alkktutkkoulk_2007]  )
      ,'ylkk_2007' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [ylkksuorv_2007] AND
      suorlk = [ylkksuorlk_2007] AND
      tutkmaak = [ylkktutkkmaak_2007] AND
      tutkjarj = [ylkktutkjarj_2007] AND
      tutkkoulk = [ylkktutkkoulk_2007]  )
      ,'tk_2007' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [tksuorv_2007] AND
      suorlk = [tksuorlk_2007] AND
      tutkmaak = [tktutkkmaak_2007] AND
      tutkjarj = [tktutkjarj_2007] AND
      tutkkoulk = [tktutkkoulk_2007]  )
      ,'muuta_2007' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [muutasuorv_2007] AND
      suorlk = [muutasuorlk_2007] AND
      tutkmaak = [muutatutkkmaak_2007] AND
      tutkjarj = [muutatutkjarj_2007] AND
      tutkkoulk = [muutatutkkoulk_2007]  )
      ,'amk_2008' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [amksuorv_2008] AND
      suorlk = [amksuorlk_2008] AND
      tutkmaak = [amktutkkmaak_2008] AND
      tutkjarj = [amktutkjarj_2008] AND
      tutkkoulk = [amktutkkoulk_2008]  )
      ,'ylamk_2008' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [ylamksuorv_2008] AND
      suorlk = [ylamksuorlk_2008] AND
      tutkmaak = [ylamktutkkmaak_2008] AND
      tutkjarj = [ylamktutkjarj_2008] AND
      tutkkoulk = [ylamktutkkoulk_2008]  )
      ,'alkk_2008' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [alkksuorv_2008] AND
      suorlk = [alkksuorlk_2008] AND
      tutkmaak = [alkktutkkmaak_2008] AND
      tutkjarj = [alkktutkjarj_2008] AND
      tutkkoulk = [alkktutkkoulk_2008]  )
      ,'ylkk_2008' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [ylkksuorv_2008] AND
      suorlk = [ylkksuorlk_2008] AND
      tutkmaak = [ylkktutkkmaak_2008] AND
      tutkjarj = [ylkktutkjarj_2008] AND
      tutkkoulk = [ylkktutkkoulk_2008]  )
      ,'tk_2008' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [tksuorv_2008] AND
      suorlk = [tksuorlk_2008] AND
      tutkmaak = [tktutkkmaak_2008] AND
      tutkjarj = [tktutkjarj_2008] AND
      tutkkoulk = [tktutkkoulk_2008]  )
      ,'muuta_2008' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [muutasuorv_2008] AND
      suorlk = [muutasuorlk_2008] AND
      tutkmaak = [muutatutkkmaak_2008] AND
      tutkjarj = [muutatutkjarj_2008] AND
      tutkkoulk = [muutatutkkoulk_2008]  )
      
      ,'amkopisk_2000' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [amkopiskkoulk_2000] AND
      opiskjarj_2 = [amkopiskjarj_2000] AND
      kmaak_2 = [amkkmaak_2000] --AND
      --olotamm_2 = [amkolotamm_2000] AND
      --olosyys_2 = [amkolosyys_2000]  
      )
      ,'ylamkopisk_2000' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [ylamkopiskkoulk_2000] AND
      opiskjarj_2 = [ylamkopiskjarj_2000] AND
      kmaak_2 = [ylamkkmaak_2000] --AND
      --olotamm_2 = [ylamkolotamm_2000] AND
      --olosyys_2 = [ylamkolosyys_2000]  
      )
      ,'alkkopisk_2000' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [alkkopiskkoulk_2000] AND
      opiskjarj_2 = [alkkopiskjarj_2000] AND
      kmaak_2 = [alkkkmaak_2000] --AND
      --olotamm_2 = [alkkolotamm_2000] AND
      --olosyys_2 = [alkkolosyys_2000]  
      )
      ,'ylkkopisk_2000' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [ylkkopiskkoulk_2000] AND
      opiskjarj_2 = [ylkkopiskjarj_2000] AND
      kmaak_2 = [ylkkkmaak_2000] --AND
      --olotamm_2 = [ylkkolotamm_2000] AND
      --olosyys_2 = [ylkkolosyys_2000]  
      )
      ,'tkopisk_2000' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [tkopiskkoulk_2000] AND
      opiskjarj_2 = [tkopiskjarj_2000] AND
      kmaak_2 = [tkkmaak_2000] --AND
      --olotamm_2 = [tkolotamm_2000] AND
      --olosyys_2 = [tkolosyys_2000]  
      )
      ,'muutaopisk_2000' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [muutaopiskkoulk_2000] AND
      opiskjarj_2 = [muutaopiskjarj_2000] AND
      kmaak_2 = [muutakmaak_2000] --AND
      --olotamm_2 = [muutaolotamm_2000] AND
      --olosyys_2 = [muutaolosyys_2000]  
      )
      ,'amkopisk_2001' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [amkopiskkoulk_2001] AND
      opiskjarj_2 = [amkopiskjarj_2001] AND
      kmaak_2 = [amkkmaak_2001] --AND
      --olotamm_2 = [amkolotamm_2001] AND
      --olosyys_2 = [amkolosyys_2001]  
      )
      ,'ylamkopisk_2001' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [ylamkopiskkoulk_2001] AND
      opiskjarj_2 = [ylamkopiskjarj_2001] AND
      kmaak_2 = [ylamkkmaak_2001] --AND
      --olotamm_2 = [ylamkolotamm_2001] AND
      --olosyys_2 = [ylamkolosyys_2001]  
      )
      ,'alkkopisk_2001' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [alkkopiskkoulk_2001] AND
      opiskjarj_2 = [alkkopiskjarj_2001] AND
      kmaak_2 = [alkkkmaak_2001] --AND
      --olotamm_2 = [alkkolotamm_2001] AND
      --olosyys_2 = [alkkolosyys_2001]  
      )
      ,'ylkkopisk_2001' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [ylkkopiskkoulk_2001] AND
      opiskjarj_2 = [ylkkopiskjarj_2001] AND
      kmaak_2 = [ylkkkmaak_2001] --AND
      --olotamm_2 = [ylkkolotamm_2001] AND
      --olosyys_2 = [ylkkolosyys_2001]  
      )
      ,'tkopisk_2001' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [tkopiskkoulk_2001] AND
      opiskjarj_2 = [tkopiskjarj_2001] AND
      kmaak_2 = [tkkmaak_2001] --AND
      --olotamm_2 = [tkolotamm_2001] AND
      --olosyys_2 = [tkolosyys_2001]  
      )
      ,'muutaopisk_2001' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [muutaopiskkoulk_2001] AND
      opiskjarj_2 = [muutaopiskjarj_2001] AND
      kmaak_2 = [muutakmaak_2001] --AND
      --olotamm_2 = [muutaolotamm_2001] AND
      --olosyys_2 = [muutaolosyys_2001]  
      )
      ,'amkopisk_2002' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [amkopiskkoulk_2002] AND
      opiskjarj_2 = [amkopiskjarj_2002] AND
      kmaak_2 = [amkkmaak_2002] --AND
      --olotamm_2 = [amkolotamm_2002] AND
      --olosyys_2 = [amkolosyys_2002]  
      )
      ,'ylamkopisk_2002' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [ylamkopiskkoulk_2002] AND
      opiskjarj_2 = [ylamkopiskjarj_2002] AND
      kmaak_2 = [ylamkkmaak_2002] --AND
      --olotamm_2 = [ylamkolotamm_2002] AND
      --olosyys_2 = [ylamkolosyys_2002]  
      )
      ,'alkkopisk_2002' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [alkkopiskkoulk_2002] AND
      opiskjarj_2 = [alkkopiskjarj_2002] AND
      kmaak_2 = [alkkkmaak_2002] --AND
      --olotamm_2 = [alkkolotamm_2002] AND
      --olosyys_2 = [alkkolosyys_2002]  
      )
      ,'ylkkopisk_2002' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [ylkkopiskkoulk_2002] AND
      opiskjarj_2 = [ylkkopiskjarj_2002] AND
      kmaak_2 = [ylkkkmaak_2002] --AND
      --olotamm_2 = [ylkkolotamm_2002] AND
      --olosyys_2 = [ylkkolosyys_2002]  
      )
      ,'tkopisk_2002' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [tkopiskkoulk_2002] AND
      opiskjarj_2 = [tkopiskjarj_2002] AND
      kmaak_2 = [tkkmaak_2002] --AND
      --olotamm_2 = [tkolotamm_2002] AND
      --olosyys_2 = [tkolosyys_2002]  
      )
      ,'muutaopisk_2002' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [muutaopiskkoulk_2002] AND
      opiskjarj_2 = [muutaopiskjarj_2002] AND
      kmaak_2 = [muutakmaak_2002] --AND
      --olotamm_2 = [muutaolotamm_2002] AND
      --olosyys_2 = [muutaolosyys_2002]  
      )
      ,'amkopisk_2003' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [amkopiskkoulk_2003] AND
      opiskjarj_2 = [amkopiskjarj_2003] AND
      kmaak_2 = [amkkmaak_2003] --AND
      --olotamm_2 = [amkolotamm_2003] AND
      --olosyys_2 = [amkolosyys_2003]  
      )
      ,'ylamkopisk_2003' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [ylamkopiskkoulk_2003] AND
      opiskjarj_2 = [ylamkopiskjarj_2003] AND
      kmaak_2 = [ylamkkmaak_2003] --AND
      --olotamm_2 = [ylamkolotamm_2003] AND
      --olosyys_2 = [ylamkolosyys_2003]  
      )
      ,'alkkopisk_2003' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [alkkopiskkoulk_2003] AND
      opiskjarj_2 = [alkkopiskjarj_2003] AND
      kmaak_2 = [alkkkmaak_2003] --AND
      --olotamm_2 = [alkkolotamm_2003] AND
      --olosyys_2 = [alkkolosyys_2003]  
      )
      ,'ylkkopisk_2003' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [ylkkopiskkoulk_2003] AND
      opiskjarj_2 = [ylkkopiskjarj_2003] AND
      kmaak_2 = [ylkkkmaak_2003] --AND
      --olotamm_2 = [ylkkolotamm_2003] AND
      --olosyys_2 = [ylkkolosyys_2003]  
      )
      ,'tkopisk_2003' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [tkopiskkoulk_2003] AND
      opiskjarj_2 = [tkopiskjarj_2003] AND
      kmaak_2 = [tkkmaak_2003] --AND
      --olotamm_2 = [tkolotamm_2003] AND
      --olosyys_2 = [tkolosyys_2003]  
      )
      ,'muutaopisk_2003' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [muutaopiskkoulk_2003] AND
      opiskjarj_2 = [muutaopiskjarj_2003] AND
      kmaak_2 = [muutakmaak_2003] --AND
      --olotamm_2 = [muutaolotamm_2003] AND
      --olosyys_2 = [muutaolosyys_2003]  
      )
      ,'amkopisk_2004' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [amkopiskkoulk_2004] AND
      opiskjarj_2 = [amkopiskjarj_2004] AND
      kmaak_2 = [amkkmaak_2004] --AND
      --olotamm_2 = [amkolotamm_2004] AND
      --olosyys_2 = [amkolosyys_2004]  
      )
      ,'ylamkopisk_2004' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [ylamkopiskkoulk_2004] AND
      opiskjarj_2 = [ylamkopiskjarj_2004] AND
      kmaak_2 = [ylamkkmaak_2004] --AND
      --olotamm_2 = [ylamkolotamm_2004] AND
      --olosyys_2 = [ylamkolosyys_2004]  
      )
      ,'alkkopisk_2004' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [alkkopiskkoulk_2004] AND
      opiskjarj_2 = [alkkopiskjarj_2004] AND
      kmaak_2 = [alkkkmaak_2004] --AND
      --olotamm_2 = [alkkolotamm_2004] AND
      --olosyys_2 = [alkkolosyys_2004]  
      )
      ,'ylkkopisk_2004' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [ylkkopiskkoulk_2004] AND
      opiskjarj_2 = [ylkkopiskjarj_2004] AND
      kmaak_2 = [ylkkkmaak_2004] --AND
      --olotamm_2 = [ylkkolotamm_2004] AND
      --olosyys_2 = [ylkkolosyys_2004]  
      )
      ,'tkopisk_2004' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [tkopiskkoulk_2004] AND
      opiskjarj_2 = [tkopiskjarj_2004] AND
      kmaak_2 = [tkkmaak_2004] --AND
      --olotamm_2 = [tkolotamm_2004] AND
      --olosyys_2 = [tkolosyys_2004]  
      )
      ,'muutaopisk_2004' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [muutaopiskkoulk_2004] AND
      opiskjarj_2 = [muutaopiskjarj_2004] AND
      kmaak_2 = [muutakmaak_2004] --AND
      --olotamm_2 = [muutaolotamm_2004] AND
      --olosyys_2 = [muutaolosyys_2004]  
      )
      ,'amkopisk_2005' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [amkopiskkoulk_2005] AND
      opiskjarj_2 = [amkopiskjarj_2005] AND
      kmaak_2 = [amkkmaak_2005] --AND
      --olotamm_2 = [amkolotamm_2005] AND
      --olosyys_2 = [amkolosyys_2005]  
      )
      ,'ylamkopisk_2005' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [ylamkopiskkoulk_2005] AND
      opiskjarj_2 = [ylamkopiskjarj_2005] AND
      kmaak_2 = [ylamkkmaak_2005] --AND
      --olotamm_2 = [ylamkolotamm_2005] AND
      --olosyys_2 = [ylamkolosyys_2005]  
      )
      ,'alkkopisk_2005' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [alkkopiskkoulk_2005] AND
      opiskjarj_2 = [alkkopiskjarj_2005] AND
      kmaak_2 = [alkkkmaak_2005] --AND
      --olotamm_2 = [alkkolotamm_2005] AND
      --olosyys_2 = [alkkolosyys_2005]  
      )
      ,'ylkkopisk_2005' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [ylkkopiskkoulk_2005] AND
      opiskjarj_2 = [ylkkopiskjarj_2005] AND
      kmaak_2 = [ylkkkmaak_2005] --AND
      --olotamm_2 = [ylkkolotamm_2005] AND
      --olosyys_2 = [ylkkolosyys_2005]  
      )
      ,'tkopisk_2005' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [tkopiskkoulk_2005] AND
      opiskjarj_2 = [tkopiskjarj_2005] AND
      kmaak_2 = [tkkmaak_2005] --AND
      --olotamm_2 = [tkolotamm_2005] AND
      --olosyys_2 = [tkolosyys_2005]  
      )
      ,'muutaopisk_2005' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [muutaopiskkoulk_2005] AND
      opiskjarj_2 = [muutaopiskjarj_2005] AND
      kmaak_2 = [muutakmaak_2005] --AND
      --olotamm_2 = [muutaolotamm_2005] AND
      --olosyys_2 = [muutaolosyys_2005]  
      )
      ,'amkopisk_2006' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [amkopiskkoulk_2006] AND
      opiskjarj_2 = [amkopiskjarj_2006] AND
      kmaak_2 = [amkkmaak_2006] --AND
      --olotamm_2 = [amkolotamm_2006] AND
      --olosyys_2 = [amkolosyys_2006]  
      )
      ,'ylamkopisk_2006' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [ylamkopiskkoulk_2006] AND
      opiskjarj_2 = [ylamkopiskjarj_2006] AND
      kmaak_2 = [ylamkkmaak_2006] --AND
      --olotamm_2 = [ylamkolotamm_2006] AND
      --olosyys_2 = [ylamkolosyys_2006]  
      )
      ,'alkkopisk_2006' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [alkkopiskkoulk_2006] AND
      opiskjarj_2 = [alkkopiskjarj_2006] AND
      kmaak_2 = [alkkkmaak_2006] --AND
      --olotamm_2 = [alkkolotamm_2006] AND
      --olosyys_2 = [alkkolosyys_2006]  
      )
      ,'ylkkopisk_2006' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [ylkkopiskkoulk_2006] AND
      opiskjarj_2 = [ylkkopiskjarj_2006] AND
      kmaak_2 = [ylkkkmaak_2006] --AND
      --olotamm_2 = [ylkkolotamm_2006] AND
      --olosyys_2 = [ylkkolosyys_2006]  
      )
      ,'tkopisk_2006' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [tkopiskkoulk_2006] AND
      opiskjarj_2 = [tkopiskjarj_2006] AND
      kmaak_2 = [tkkmaak_2006] --AND
      --olotamm_2 = [tkolotamm_2006] AND
      --olosyys_2 = [tkolosyys_2006]  
      )
      ,'muutaopisk_2006' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [muutaopiskkoulk_2006] AND
      opiskjarj_2 = [muutaopiskjarj_2006] AND
      kmaak_2 = [muutakmaak_2006] --AND
      --olotamm_2 = [muutaolotamm_2006] AND
      --olosyys_2 = [muutaolosyys_2006]  
      )
      ,'amkopisk_2007' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [amkopiskkoulk_2007] AND
      opiskjarj_2 = [amkopiskjarj_2007] AND
      kmaak_2 = [amkkmaak_2007] --AND
      --olotamm_2 = [amkolotamm_2007] AND
      --olosyys_2 = [amkolosyys_2007]  
      )
      ,'ylamkopisk_2007' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [ylamkopiskkoulk_2007] AND
      opiskjarj_2 = [ylamkopiskjarj_2007] AND
      kmaak_2 = [ylamkkmaak_2007] --AND
      --olotamm_2 = [ylamkolotamm_2007] AND
      --olosyys_2 = [ylamkolosyys_2007]  
      )
      ,'alkkopisk_2007' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [alkkopiskkoulk_2007] AND
      opiskjarj_2 = [alkkopiskjarj_2007] AND
      kmaak_2 = [alkkkmaak_2007] --AND
      --olotamm_2 = [alkkolotamm_2007] AND
      --olosyys_2 = [alkkolosyys_2007]  
      )
      ,'ylkkopisk_2007' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [ylkkopiskkoulk_2007] AND
      opiskjarj_2 = [ylkkopiskjarj_2007] AND
      kmaak_2 = [ylkkkmaak_2007] --AND
      --olotamm_2 = [ylkkolotamm_2007] AND
      --olosyys_2 = [ylkkolosyys_2007]  
      )
      ,'tkopisk_2007' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [tkopiskkoulk_2007] AND
      opiskjarj_2 = [tkopiskjarj_2007] AND
      kmaak_2 = [tkkmaak_2007] --AND
      --olotamm_2 = [tkolotamm_2007] AND
      --olosyys_2 = [tkolosyys_2007]  
      )
      ,'muutaopisk_2007' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [muutaopiskkoulk_2007] AND
      opiskjarj_2 = [muutaopiskjarj_2007] AND
      kmaak_2 = [muutakmaak_2007] --AND
      --olotamm_2 = [muutaolotamm_2007] AND
      --olosyys_2 = [muutaolosyys_2007]  
      )
      ,'amkopisk_2008' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [amkopiskkoulk_2008] AND
      opiskjarj_2 = [amkopiskjarj_2008] AND
      kmaak_2 = [amkkmaak_2008] --AND
      --olotamm_2 = [amkolotamm_2008] AND
      --olosyys_2 = [amkolosyys_2008]  
      )
      ,'ylamkopisk_2008' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [ylamkopiskkoulk_2008] AND
      opiskjarj_2 = [ylamkopiskjarj_2008] AND
      kmaak_2 = [ylamkkmaak_2008] --AND
      --olotamm_2 = [ylamkolotamm_2008] AND
      --olosyys_2 = [ylamkolosyys_2008]  
      )
      ,'alkkopisk_2008' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [alkkopiskkoulk_2008] AND
      opiskjarj_2 = [alkkopiskjarj_2008] AND
      kmaak_2 = [alkkkmaak_2008] --AND
      --olotamm_2 = [alkkolotamm_2008] AND
      --olosyys_2 = [alkkolosyys_2008]  
      )
      ,'ylkkopisk_2008' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [ylkkopiskkoulk_2008] AND
      opiskjarj_2 = [ylkkopiskjarj_2008] AND
      kmaak_2 = [ylkkkmaak_2008] --AND
      --olotamm_2 = [ylkkolotamm_2008] AND
      --olosyys_2 = [ylkkolosyys_2008]  
      )
      ,'tkopisk_2008' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [tkopiskkoulk_2008] AND
      opiskjarj_2 = [tkopiskjarj_2008] AND
      kmaak_2 = [tkkmaak_2008] --AND
      --olotamm_2 = [tkolotamm_2008] AND
      --olosyys_2 = [tkolosyys_2008]  
      )
      ,'muutaopisk_2008' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [muutaopiskkoulk_2008] AND
      opiskjarj_2 = [muutaopiskjarj_2008] AND
      kmaak_2 = [muutakmaak_2008] --AND
      --olotamm_2 = [muutaolotamm_2008] AND
      --olosyys_2 = [muutaolosyys_2008]  
      )

      ,'ptoim1r5_2000' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
      ptoim1r5 = [ptoim1r5_2000]  )
      --amas = [amas_2000]  )
      ,'ptoim1r5_2001' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
      ptoim1r5 = [ptoim1r5_2001]  )
      --amas = [amas_2001]  )
      ,'ptoim1r5_2002' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
      ptoim1r5 = [ptoim1r5_2002]  )
      --amas = [amas_2002]  )
      ,'ptoim1r5_2003' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
      ptoim1r5 = [ptoim1r5_2003]  )
      --amas = [amas_2003]  )
      ,'ptoim1r5_2004' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
      ptoim1r5 = [ptoim1r5_2004]  )
      --amas = [amas_2004]  )
      ,'ptoim1r5_2005' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
      ptoim1r5 = [ptoim1r5_2005]  )
      --amas = [amas_2005]  )
      ,'ptoim1r5_2006' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
      ptoim1r5 = [ptoim1r5_2006]  )
      --amas = [amas_2006]  )
      ,'ptoim1r5_2007' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
      ptoim1r5 = [ptoim1r5_2007]  )
      --amas = [amas_2007]  )
      ,'ptoim1r5_2008' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
      ptoim1r5 = [ptoim1r5_2008]  )
      --amas = [amas_2008]  )
--2009
      ,'amk_2009' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [amksuorv_2009] AND
      suorlk = [amksuorlk_2009] AND
      tutkmaak = [amktutkkmaak_2009] AND
      tutkjarj = [amktutkjarj_2009] AND
      tutkkoulk = [amktutkkoulk_2009]  )
      ,'ylamk_2009' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [ylamksuorv_2009] AND
      suorlk = [ylamksuorlk_2009] AND
      tutkmaak = [ylamktutkkmaak_2009] AND
      tutkjarj = [ylamktutkjarj_2009] AND
      tutkkoulk = [ylamktutkkoulk_2009]  )
      ,'alkk_2009' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [alkksuorv_2009] AND
      suorlk = [alkksuorlk_2009] AND
      tutkmaak = [alkktutkkmaak_2009] AND
      tutkjarj = [alkktutkjarj_2009] AND
      tutkkoulk = [alkktutkkoulk_2009]  )
      ,'ylkk_2009' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [ylkksuorv_2009] AND
      suorlk = [ylkksuorlk_2009] AND
      tutkmaak = [ylkktutkkmaak_2009] AND
      tutkjarj = [ylkktutkjarj_2009] AND
      tutkkoulk = [ylkktutkkoulk_2009]  )
      ,'tk_2009' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [tksuorv_2009] AND
      suorlk = [tksuorlk_2009] AND
      tutkmaak = [tktutkkmaak_2009] AND
      tutkjarj = [tktutkjarj_2009] AND
      tutkkoulk = [tktutkkoulk_2009]  )
      ,'muuta_2009' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [muutasuorv_2009] AND
      suorlk = [muutasuorlk_2009] AND
      tutkmaak = [muutatutkkmaak_2009] AND
      tutkjarj = [muutatutkjarj_2009] AND
      tutkkoulk = [muutatutkkoulk_2009]  )
      ,'amkopisk_2009' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [amkopiskkoulk_2009] AND
      opiskjarj_2 = [amkopiskjarj_2009] AND
      kmaak_2 = [amkkmaak_2009] --AND
      --olotamm_2 = [amkolotamm_2009] AND
      --olosyys_2 = [amkolosyys_2009]  
      )
      ,'ylamkopisk_2009' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [ylamkopiskkoulk_2009] AND
      opiskjarj_2 = [ylamkopiskjarj_2009] AND
      kmaak_2 = [ylamkkmaak_2009] --AND
      --olotamm_2 = [ylamkolotamm_2009] AND
      --olosyys_2 = [ylamkolosyys_2009]  
      )
      ,'alkkopisk_2009' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [alkkopiskkoulk_2009] AND
      opiskjarj_2 = [alkkopiskjarj_2009] AND
      kmaak_2 = [alkkkmaak_2009] --AND
      --olotamm_2 = [alkkolotamm_2009] AND
      --olosyys_2 = [alkkolosyys_2009]  
      )
      ,'ylkkopisk_2009' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [ylkkopiskkoulk_2009] AND
      opiskjarj_2 = [ylkkopiskjarj_2009] AND
      kmaak_2 = [ylkkkmaak_2009] --AND
      --olotamm_2 = [ylkkolotamm_2009] AND
      --olosyys_2 = [ylkkolosyys_2009]  
      )
      ,'tkopisk_2009' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [tkopiskkoulk_2009] AND
      opiskjarj_2 = [tkopiskjarj_2009] AND
      kmaak_2 = [tkkmaak_2009] --AND
      --olotamm_2 = [tkolotamm_2009] AND
      --olosyys_2 = [tkolosyys_2009]  
      )
      ,'muutaopisk_2009' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [muutaopiskkoulk_2009] AND
      opiskjarj_2 = [muutaopiskjarj_2009] AND
      kmaak_2 = [muutakmaak_2009] --AND
      --olotamm_2 = [muutaolotamm_2009] AND
      --olosyys_2 = [muutaolosyys_2009]  
      )
      ,'ptoim1r5_2009' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
      ptoim1r5 = [ptoim1r5_2009]  )
      --amas = [amas_2009]  )
--2010
      ,'amk_2010' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [amksuorv_2010] AND
      suorlk = [amksuorlk_2010] AND
      tutkmaak = [amktutkkmaak_2010] AND
      tutkjarj = [amktutkjarj_2010] AND
      tutkkoulk = [amktutkkoulk_2010]  )
      ,'ylamk_2010' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [ylamksuorv_2010] AND
      suorlk = [ylamksuorlk_2010] AND
      tutkmaak = [ylamktutkkmaak_2010] AND
      tutkjarj = [ylamktutkjarj_2010] AND
      tutkkoulk = [ylamktutkkoulk_2010]  )
      ,'alkk_2010' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [alkksuorv_2010] AND
      suorlk = [alkksuorlk_2010] AND
      tutkmaak = [alkktutkkmaak_2010] AND
      tutkjarj = [alkktutkjarj_2010] AND
      tutkkoulk = [alkktutkkoulk_2010]  )
      ,'ylkk_2010' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [ylkksuorv_2010] AND
      suorlk = [ylkksuorlk_2010] AND
      tutkmaak = [ylkktutkkmaak_2010] AND
      tutkjarj = [ylkktutkjarj_2010] AND
      tutkkoulk = [ylkktutkkoulk_2010]  )
      ,'tk_2010' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [tksuorv_2010] AND
      suorlk = [tksuorlk_2010] AND
      tutkmaak = [tktutkkmaak_2010] AND
      tutkjarj = [tktutkjarj_2010] AND
      tutkkoulk = [tktutkkoulk_2010]  )
      ,'muuta_2010' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [muutasuorv_2010] AND
      suorlk = [muutasuorlk_2010] AND
      tutkmaak = [muutatutkkmaak_2010] AND
      tutkjarj = [muutatutkjarj_2010] AND
      tutkkoulk = [muutatutkkoulk_2010]  )
      ,'amkopisk_2010' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [amkopiskkoulk_2010] AND
      opiskjarj_2 = [amkopiskjarj_2010] AND
      kmaak_2 = [amkkmaak_2010] --AND
      --olotamm_2 = [amkolotamm_2010] AND
      --olosyys_2 = [amkolosyys_2010]  
      )
      ,'ylamkopisk_2010' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [ylamkopiskkoulk_2010] AND
      opiskjarj_2 = [ylamkopiskjarj_2010] AND
      kmaak_2 = [ylamkkmaak_2010] --AND
      --olotamm_2 = [ylamkolotamm_2010] AND
      --olosyys_2 = [ylamkolosyys_2010]  
      )
      ,'alkkopisk_2010' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [alkkopiskkoulk_2010] AND
      opiskjarj_2 = [alkkopiskjarj_2010] AND
      kmaak_2 = [alkkkmaak_2010] --AND
      --olotamm_2 = [alkkolotamm_2010] AND
      --olosyys_2 = [alkkolosyys_2010]  
      )
      ,'ylkkopisk_2010' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [ylkkopiskkoulk_2010] AND
      opiskjarj_2 = [ylkkopiskjarj_2010] AND
      kmaak_2 = [ylkkkmaak_2010] --AND
      --olotamm_2 = [ylkkolotamm_2010] AND
      --olosyys_2 = [ylkkolosyys_2010]  
      )
      ,'tkopisk_2010' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [tkopiskkoulk_2010] AND
      opiskjarj_2 = [tkopiskjarj_2010] AND
      kmaak_2 = [tkkmaak_2010] --AND
      --olotamm_2 = [tkolotamm_2010] AND
      --olosyys_2 = [tkolosyys_2010]  
      )
      ,'muutaopisk_2010' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [muutaopiskkoulk_2010] AND
      opiskjarj_2 = [muutaopiskjarj_2010] AND
      kmaak_2 = [muutakmaak_2010] --AND
      --olotamm_2 = [muutaolotamm_2010] AND
      --olosyys_2 = [muutaolosyys_2010]  
      )
      ,'ptoim1r5_2010' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
      ptoim1r5 = [ptoim1r5_2010]  )
      --amas = [amas_2010]  )
--2011
      ,'amk_2011' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [amksuorv_2011] AND
      suorlk = [amksuorlk_2011] AND
      tutkmaak = [amktutkkmaak_2011] AND
      tutkjarj = [amktutkjarj_2011] AND
      tutkkoulk = [amktutkkoulk_2011]  )
      ,'ylamk_2011' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [ylamksuorv_2011] AND
      suorlk = [ylamksuorlk_2011] AND
      tutkmaak = [ylamktutkkmaak_2011] AND
      tutkjarj = [ylamktutkjarj_2011] AND
      tutkkoulk = [ylamktutkkoulk_2011]  )
      ,'alkk_2011' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [alkksuorv_2011] AND
      suorlk = [alkksuorlk_2011] AND
      tutkmaak = [alkktutkkmaak_2011] AND
      tutkjarj = [alkktutkjarj_2011] AND
      tutkkoulk = [alkktutkkoulk_2011]  )
      ,'ylkk_2011' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [ylkksuorv_2011] AND
      suorlk = [ylkksuorlk_2011] AND
      tutkmaak = [ylkktutkkmaak_2011] AND
      tutkjarj = [ylkktutkjarj_2011] AND
      tutkkoulk = [ylkktutkkoulk_2011]  )
      ,'tk_2011' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [tksuorv_2011] AND
      suorlk = [tksuorlk_2011] AND
      tutkmaak = [tktutkkmaak_2011] AND
      tutkjarj = [tktutkjarj_2011] AND
      tutkkoulk = [tktutkkoulk_2011]  )
      ,'muuta_2011' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [muutasuorv_2011] AND
      suorlk = [muutasuorlk_2011] AND
      tutkmaak = [muutatutkkmaak_2011] AND
      tutkjarj = [muutatutkjarj_2011] AND
      tutkkoulk = [muutatutkkoulk_2011]  )
      ,'amkopisk_2011' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [amkopiskkoulk_2011] AND
      opiskjarj_2 = [amkopiskjarj_2011] AND
      kmaak_2 = [amkkmaak_2011] --AND
      --olotamm_2 = [amkolotamm_2011] AND
      --olosyys_2 = [amkolosyys_2011]  
      )
      ,'ylamkopisk_2011' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [ylamkopiskkoulk_2011] AND
      opiskjarj_2 = [ylamkopiskjarj_2011] AND
      kmaak_2 = [ylamkkmaak_2011] --AND
      --olotamm_2 = [ylamkolotamm_2011] AND
      --olosyys_2 = [ylamkolosyys_2011]  
      )
      ,'alkkopisk_2011' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [alkkopiskkoulk_2011] AND
      opiskjarj_2 = [alkkopiskjarj_2011] AND
      kmaak_2 = [alkkkmaak_2011] --AND
      --olotamm_2 = [alkkolotamm_2011] AND
      --olosyys_2 = [alkkolosyys_2011]  
      )
      ,'ylkkopisk_2011' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [ylkkopiskkoulk_2011] AND
      opiskjarj_2 = [ylkkopiskjarj_2011] AND
      kmaak_2 = [ylkkkmaak_2011] --AND
      --olotamm_2 = [ylkkolotamm_2011] AND
      --olosyys_2 = [ylkkolosyys_2011]  
      )
      ,'tkopisk_2011' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [tkopiskkoulk_2011] AND
      opiskjarj_2 = [tkopiskjarj_2011] AND
      kmaak_2 = [tkkmaak_2011] --AND
      --olotamm_2 = [tkolotamm_2011] AND
      --olosyys_2 = [tkolosyys_2011]  
      )
      ,'muutaopisk_2011' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [muutaopiskkoulk_2011] AND
      opiskjarj_2 = [muutaopiskjarj_2011] AND
      kmaak_2 = [muutakmaak_2011] --AND
      --olotamm_2 = [muutaolotamm_2011] AND
      --olosyys_2 = [muutaolosyys_2011]  
      )
      ,'ptoim1r5_2011' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
      ptoim1r5 = [ptoim1r5_2011]  )
      --amas = [amas_2011]  )
--2012
      ,'amk_2012' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [amksuorv_2012] AND
      suorlk = [amksuorlk_2012] AND
      tutkmaak = [amktutkkmaak_2012] AND
      tutkjarj = [amktutkjarj_2012] AND
      tutkkoulk = [amktutkkoulk_2012]  )
      ,'ylamk_2012' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [ylamksuorv_2012] AND
      suorlk = [ylamksuorlk_2012] AND
      tutkmaak = [ylamktutkkmaak_2012] AND
      tutkjarj = [ylamktutkjarj_2012] AND
      tutkkoulk = [ylamktutkkoulk_2012]  )
      ,'alkk_2012' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [alkksuorv_2012] AND
      suorlk = [alkksuorlk_2012] AND
      tutkmaak = [alkktutkkmaak_2012] AND
      tutkjarj = [alkktutkjarj_2012] AND
      tutkkoulk = [alkktutkkoulk_2012]  )
      ,'ylkk_2012' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [ylkksuorv_2012] AND
      suorlk = [ylkksuorlk_2012] AND
      tutkmaak = [ylkktutkkmaak_2012] AND
      tutkjarj = [ylkktutkjarj_2012] AND
      tutkkoulk = [ylkktutkkoulk_2012]  )
      ,'tk_2012' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [tksuorv_2012] AND
      suorlk = [tksuorlk_2012] AND
      tutkmaak = [tktutkkmaak_2012] AND
      tutkjarj = [tktutkjarj_2012] AND
      tutkkoulk = [tktutkkoulk_2012]  )
      ,'muuta_2012' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [muutasuorv_2012] AND
      suorlk = [muutasuorlk_2012] AND
      tutkmaak = [muutatutkkmaak_2012] AND
      tutkjarj = [muutatutkjarj_2012] AND
      tutkkoulk = [muutatutkkoulk_2012]  )
      ,'amkopisk_2012' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [amkopiskkoulk_2012] AND
      opiskjarj_2 = [amkopiskjarj_2012] AND
      kmaak_2 = [amkkmaak_2012] --AND
      --olotamm_2 = [amkolotamm_2012] AND
      --olosyys_2 = [amkolosyys_2012]  
      )
      ,'ylamkopisk_2012' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [ylamkopiskkoulk_2012] AND
      opiskjarj_2 = [ylamkopiskjarj_2012] AND
      kmaak_2 = [ylamkkmaak_2012] --AND
      --olotamm_2 = [ylamkolotamm_2012] AND
      --olosyys_2 = [ylamkolosyys_2012]  
      )
      ,'alkkopisk_2012' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [alkkopiskkoulk_2012] AND
      opiskjarj_2 = [alkkopiskjarj_2012] AND
      kmaak_2 = [alkkkmaak_2012] --AND
      --olotamm_2 = [alkkolotamm_2012] AND
      --olosyys_2 = [alkkolosyys_2012]  
      )
      ,'ylkkopisk_2012' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [ylkkopiskkoulk_2012] AND
      opiskjarj_2 = [ylkkopiskjarj_2012] AND
      kmaak_2 = [ylkkkmaak_2012] --AND
      --olotamm_2 = [ylkkolotamm_2012] AND
      --olosyys_2 = [ylkkolosyys_2012]  
      )
      ,'tkopisk_2012' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [tkopiskkoulk_2012] AND
      opiskjarj_2 = [tkopiskjarj_2012] AND
      kmaak_2 = [tkkmaak_2012] --AND
      --olotamm_2 = [tkolotamm_2012] AND
      --olosyys_2 = [tkolosyys_2012]  
      )
      ,'muutaopisk_2012' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [muutaopiskkoulk_2012] AND
      opiskjarj_2 = [muutaopiskjarj_2012] AND
      kmaak_2 = [muutakmaak_2012] --AND
      --olotamm_2 = [muutaolotamm_2012] AND
      --olosyys_2 = [muutaolosyys_2012]  
      )
      ,'ptoim1r5_2012' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
      ptoim1r5 = [ptoim1r5_2012]  )
      --amas = [amas_2012]  )
--2013
      ,'amk_2013' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [amksuorv_2013] AND
      suorlk = [amksuorlk_2013] AND
      tutkmaak = [amktutkkmaak_2013] AND
      tutkjarj = [amktutkjarj_2013] AND
      tutkkoulk = [amktutkkoulk_2013]  )
      ,'ylamk_2013' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [ylamksuorv_2013] AND
      suorlk = [ylamksuorlk_2013] AND
      tutkmaak = [ylamktutkkmaak_2013] AND
      tutkjarj = [ylamktutkjarj_2013] AND
      tutkkoulk = [ylamktutkkoulk_2013]  )
      ,'alkk_2013' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [alkksuorv_2013] AND
      suorlk = [alkksuorlk_2013] AND
      tutkmaak = [alkktutkkmaak_2013] AND
      tutkjarj = [alkktutkjarj_2013] AND
      tutkkoulk = [alkktutkkoulk_2013]  )
      ,'ylkk_2013' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [ylkksuorv_2013] AND
      suorlk = [ylkksuorlk_2013] AND
      tutkmaak = [ylkktutkkmaak_2013] AND
      tutkjarj = [ylkktutkjarj_2013] AND
      tutkkoulk = [ylkktutkkoulk_2013]  )
      ,'tk_2013' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [tksuorv_2013] AND
      suorlk = [tksuorlk_2013] AND
      tutkmaak = [tktutkkmaak_2013] AND
      tutkjarj = [tktutkjarj_2013] AND
      tutkkoulk = [tktutkkoulk_2013]  )
      ,'muuta_2013' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [muutasuorv_2013] AND
      suorlk = [muutasuorlk_2013] AND
      tutkmaak = [muutatutkkmaak_2013] AND
      tutkjarj = [muutatutkjarj_2013] AND
      tutkkoulk = [muutatutkkoulk_2013]  )
      ,'amkopisk_2013' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [amkopiskkoulk_2013] AND
      opiskjarj_2 = [amkopiskjarj_2013] AND
      kmaak_2 = [amkkmaak_2013] --AND
      --olotamm_2 = [amkolotamm_2013] AND
      --olosyys_2 = [amkolosyys_2013]  
      )
      ,'ylamkopisk_2013' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [ylamkopiskkoulk_2013] AND
      opiskjarj_2 = [ylamkopiskjarj_2013] AND
      kmaak_2 = [ylamkkmaak_2013] --AND
      --olotamm_2 = [ylamkolotamm_2013] AND
      --olosyys_2 = [ylamkolosyys_2013]  
      )
      ,'alkkopisk_2013' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [alkkopiskkoulk_2013] AND
      opiskjarj_2 = [alkkopiskjarj_2013] AND
      kmaak_2 = [alkkkmaak_2013] --AND
      --olotamm_2 = [alkkolotamm_2013] AND
      --olosyys_2 = [alkkolosyys_2013]  
      )
      ,'ylkkopisk_2013' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [ylkkopiskkoulk_2013] AND
      opiskjarj_2 = [ylkkopiskjarj_2013] AND
      kmaak_2 = [ylkkkmaak_2013] --AND
      --olotamm_2 = [ylkkolotamm_2013] AND
      --olosyys_2 = [ylkkolosyys_2013]  
      )
      ,'tkopisk_2013' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [tkopiskkoulk_2013] AND
      opiskjarj_2 = [tkopiskjarj_2013] AND
      kmaak_2 = [tkkmaak_2013] --AND
      --olotamm_2 = [tkolotamm_2013] AND
      --olosyys_2 = [tkolosyys_2013]  
      )
      ,'muutaopisk_2013' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [muutaopiskkoulk_2013] AND
      opiskjarj_2 = [muutaopiskjarj_2013] AND
      kmaak_2 = [muutakmaak_2013] --AND
      --olotamm_2 = [muutaolotamm_2013] AND
      --olosyys_2 = [muutaolosyys_2013]  
      )
      ,'ptoim1r5_2013' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
      ptoim1r5 = [ptoim1r5_2013]  )
      --amas = [amas_2013]  )

-- 2014

      ,'amk_2014' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [amksuorv_2014] AND
      suorlk = [amksuorlk_2014] AND
      tutkmaak = [amktutkkmaak_2014] AND
      tutkjarj = [amktutkjarj_2014] AND
      tutkkoulk = [amktutkkoulk_2014]  )
      ,'ylamk_2014' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [ylamksuorv_2014] AND
      suorlk = [ylamksuorlk_2014] AND
      tutkmaak = [ylamktutkkmaak_2014] AND
      tutkjarj = [ylamktutkjarj_2014] AND
      tutkkoulk = [ylamktutkkoulk_2014]  )
      ,'alkk_2014' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [alkksuorv_2014] AND
      suorlk = [alkksuorlk_2014] AND
      tutkmaak = [alkktutkkmaak_2014] AND
      tutkjarj = [alkktutkjarj_2014] AND
      tutkkoulk = [alkktutkkoulk_2014]  )
      ,'ylkk_2014' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [ylkksuorv_2014] AND
      suorlk = [ylkksuorlk_2014] AND
      tutkmaak = [ylkktutkkmaak_2014] AND
      tutkjarj = [ylkktutkjarj_2014] AND
      tutkkoulk = [ylkktutkkoulk_2014]  )
      ,'tk_2014' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [tksuorv_2014] AND
      suorlk = [tksuorlk_2014] AND
      tutkmaak = [tktutkkmaak_2014] AND
      tutkjarj = [tktutkjarj_2014] AND
      tutkkoulk = [tktutkkoulk_2014]  )
      ,'muuta_2014' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [muutasuorv_2014] AND
      suorlk = [muutasuorlk_2014] AND
      tutkmaak = [muutatutkkmaak_2014] AND
      tutkjarj = [muutatutkjarj_2014] AND
      tutkkoulk = [muutatutkkoulk_2014]  )
      ,'amkopisk_2014' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [amkopiskkoulk_2014] AND
      opiskjarj_2 = [amkopiskjarj_2014] AND
      kmaak_2 = [amkkmaak_2014] --AND
      --olotamm_2 = [amkolotamm_2014] AND
      --olosyys_2 = [amkolosyys_2014]  
      )
      ,'ylamkopisk_2014' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [ylamkopiskkoulk_2014] AND
      opiskjarj_2 = [ylamkopiskjarj_2014] AND
      kmaak_2 = [ylamkkmaak_2014] --AND
      --olotamm_2 = [ylamkolotamm_2014] AND
      --olosyys_2 = [ylamkolosyys_2014]  
      )
      ,'alkkopisk_2014' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [alkkopiskkoulk_2014] AND
      opiskjarj_2 = [alkkopiskjarj_2014] AND
      kmaak_2 = [alkkkmaak_2014] --AND
      --olotamm_2 = [alkkolotamm_2014] AND
      --olosyys_2 = [alkkolosyys_2014]  
      )
      ,'ylkkopisk_2014' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [ylkkopiskkoulk_2014] AND
      opiskjarj_2 = [ylkkopiskjarj_2014] AND
      kmaak_2 = [ylkkkmaak_2014] --AND
      --olotamm_2 = [ylkkolotamm_2014] AND
      --olosyys_2 = [ylkkolosyys_2014]  
      )
      ,'tkopisk_2014' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [tkopiskkoulk_2014] AND
      opiskjarj_2 = [tkopiskjarj_2014] AND
      kmaak_2 = [tkkmaak_2014] --AND
      --olotamm_2 = [tkolotamm_2014] AND
      --olosyys_2 = [tkolosyys_2014]  
      )
      ,'muutaopisk_2014' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [muutaopiskkoulk_2014] AND
      opiskjarj_2 = [muutaopiskjarj_2014] AND
      kmaak_2 = [muutakmaak_2014] --AND
      --olotamm_2 = [muutaolotamm_2014] AND
      --olosyys_2 = [muutaolosyys_2014]  
      )
      ,'ptoim1r5_2014' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
      ptoim1r5 = [ptoim1r5_2014]  )
      --amas = [amas_2014]  )

-- 2015

      ,'amk_2015' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [amksuorv_2015] AND
      suorlk = [amksuorlk_2015] AND
      tutkmaak = [amktutkkmaak_2015] AND
      tutkjarj = [amktutkjarj_2015] AND
      tutkkoulk = [amktutkkoulk_2015]  )
      ,'ylamk_2015' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [ylamksuorv_2015] AND
      suorlk = [ylamksuorlk_2015] AND
      tutkmaak = [ylamktutkkmaak_2015] AND
      tutkjarj = [ylamktutkjarj_2015] AND
      tutkkoulk = [ylamktutkkoulk_2015]  )
      ,'alkk_2015' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [alkksuorv_2015] AND
      suorlk = [alkksuorlk_2015] AND
      tutkmaak = [alkktutkkmaak_2015] AND
      tutkjarj = [alkktutkjarj_2015] AND
      tutkkoulk = [alkktutkkoulk_2015]  )
      ,'ylkk_2015' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [ylkksuorv_2015] AND
      suorlk = [ylkksuorlk_2015] AND
      tutkmaak = [ylkktutkkmaak_2015] AND
      tutkjarj = [ylkktutkjarj_2015] AND
      tutkkoulk = [ylkktutkkoulk_2015]  )
      ,'tk_2015' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [tksuorv_2015] AND
      suorlk = [tksuorlk_2015] AND
      tutkmaak = [tktutkkmaak_2015] AND
      tutkjarj = [tktutkjarj_2015] AND
      tutkkoulk = [tktutkkoulk_2015]  )
      ,'muuta_2015' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [muutasuorv_2015] AND
      suorlk = [muutasuorlk_2015] AND
      tutkmaak = [muutatutkkmaak_2015] AND
      tutkjarj = [muutatutkjarj_2015] AND
      tutkkoulk = [muutatutkkoulk_2015]  )
      ,'amkopisk_2015' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [amkopiskkoulk_2015] AND
      opiskjarj_2 = [amkopiskjarj_2015] AND
      kmaak_2 = [amkkmaak_2015] --AND
      --olotamm_2 = [amkolotamm_2015] AND
      --olosyys_2 = [amkolosyys_2015]  
      )
      ,'ylamkopisk_2015' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [ylamkopiskkoulk_2015] AND
      opiskjarj_2 = [ylamkopiskjarj_2015] AND
      kmaak_2 = [ylamkkmaak_2015] --AND
      --olotamm_2 = [ylamkolotamm_2015] AND
      --olosyys_2 = [ylamkolosyys_2015]  
      )
      ,'alkkopisk_2015' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [alkkopiskkoulk_2015] AND
      opiskjarj_2 = [alkkopiskjarj_2015] AND
      kmaak_2 = [alkkkmaak_2015] --AND
      --olotamm_2 = [alkkolotamm_2015] AND
      --olosyys_2 = [alkkolosyys_2015]  
      )
      ,'ylkkopisk_2015' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [ylkkopiskkoulk_2015] AND
      opiskjarj_2 = [ylkkopiskjarj_2015] AND
      kmaak_2 = [ylkkkmaak_2015] --AND
      --olotamm_2 = [ylkkolotamm_2015] AND
      --olosyys_2 = [ylkkolosyys_2015]  
      )
      ,'tkopisk_2015' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [tkopiskkoulk_2015] AND
      opiskjarj_2 = [tkopiskjarj_2015] AND
      kmaak_2 = [tkkmaak_2015] --AND
      --olotamm_2 = [tkolotamm_2015] AND
      --olosyys_2 = [tkolosyys_2015]  
      )
      ,'muutaopisk_2015' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [muutaopiskkoulk_2015] AND
      opiskjarj_2 = [muutaopiskjarj_2015] AND
      kmaak_2 = [muutakmaak_2015] --AND
      --olotamm_2 = [muutaolotamm_2015] AND
      --olosyys_2 = [muutaolosyys_2015]  
      )
      ,'ptoim1r5_2015' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
      ptoim1r5 = [ptoim1r5_2015]  )
      --amas = [amas_2015]  )

-- 2016

      ,'amk_2016' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [amksuorv_2016] AND
      suorlk = [amksuorlk_2016] AND
      tutkmaak = [amktutkkmaak_2016] AND
      tutkjarj = [amktutkjarj_2016] AND
      tutkkoulk = [amktutkkoulk_2016]  )
      ,'ylamk_2016' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [ylamksuorv_2016] AND
      suorlk = [ylamksuorlk_2016] AND
      tutkmaak = [ylamktutkkmaak_2016] AND
      tutkjarj = [ylamktutkjarj_2016] AND
      tutkkoulk = [ylamktutkkoulk_2016]  )
      ,'alkk_2016' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [alkksuorv_2016] AND
      suorlk = [alkksuorlk_2016] AND
      tutkmaak = [alkktutkkmaak_2016] AND
      tutkjarj = [alkktutkjarj_2016] AND
      tutkkoulk = [alkktutkkoulk_2016]  )
      ,'ylkk_2016' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [ylkksuorv_2016] AND
      suorlk = [ylkksuorlk_2016] AND
      tutkmaak = [ylkktutkkmaak_2016] AND
      tutkjarj = [ylkktutkjarj_2016] AND
      tutkkoulk = [ylkktutkkoulk_2016]  )
      ,'tk_2016' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [tksuorv_2016] AND
      suorlk = [tksuorlk_2016] AND
      tutkmaak = [tktutkkmaak_2016] AND
      tutkjarj = [tktutkjarj_2016] AND
      tutkkoulk = [tktutkkoulk_2016]  )
      ,'muuta_2016' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [muutasuorv_2016] AND
      suorlk = [muutasuorlk_2016] AND
      tutkmaak = [muutatutkkmaak_2016] AND
      tutkjarj = [muutatutkjarj_2016] AND
      tutkkoulk = [muutatutkkoulk_2016]  )
      ,'amkopisk_2016' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [amkopiskkoulk_2016] AND
      opiskjarj_2 = [amkopiskjarj_2016] AND
      kmaak_2 = [amkkmaak_2016] --AND
      --olotamm_2 = [amkolotamm_2016] AND
      --olosyys_2 = [amkolosyys_2016]  
      )
      ,'ylamkopisk_2016' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [ylamkopiskkoulk_2016] AND
      opiskjarj_2 = [ylamkopiskjarj_2016] AND
      kmaak_2 = [ylamkkmaak_2016] --AND
      --olotamm_2 = [ylamkolotamm_2016] AND
      --olosyys_2 = [ylamkolosyys_2016]  
      )
      ,'alkkopisk_2016' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [alkkopiskkoulk_2016] AND
      opiskjarj_2 = [alkkopiskjarj_2016] AND
      kmaak_2 = [alkkkmaak_2016] --AND
      --olotamm_2 = [alkkolotamm_2016] AND
      --olosyys_2 = [alkkolosyys_2016]  
      )
      ,'ylkkopisk_2016' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [ylkkopiskkoulk_2016] AND
      opiskjarj_2 = [ylkkopiskjarj_2016] AND
      kmaak_2 = [ylkkkmaak_2016] --AND
      --olotamm_2 = [ylkkolotamm_2016] AND
      --olosyys_2 = [ylkkolosyys_2016]  
      )
      ,'tkopisk_2016' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [tkopiskkoulk_2016] AND
      opiskjarj_2 = [tkopiskjarj_2016] AND
      kmaak_2 = [tkkmaak_2016] --AND
      --olotamm_2 = [tkolotamm_2016] AND
      --olosyys_2 = [tkolosyys_2016]  
      )
      ,'muutaopisk_2016' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [muutaopiskkoulk_2016] AND
      opiskjarj_2 = [muutaopiskjarj_2016] AND
      kmaak_2 = [muutakmaak_2016] --AND
      --olotamm_2 = [muutaolotamm_2016] AND
      --olosyys_2 = [muutaolosyys_2016]  
      )
      ,'ptoim1r5_2016' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
      ptoim1r5 = [ptoim1r5_2016]  )
      --amas = [amas_2016]  )

-- 2017

      ,'amk_2017' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [amksuorv_2017] AND
      suorlk = [amksuorlk_2017] AND
      tutkmaak = [amktutkkmaak_2017] AND
      tutkjarj = [amktutkjarj_2017] AND
      tutkkoulk = [amktutkkoulk_2017]  )
      ,'ylamk_2017' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [ylamksuorv_2017] AND
      suorlk = [ylamksuorlk_2017] AND
      tutkmaak = [ylamktutkkmaak_2017] AND
      tutkjarj = [ylamktutkjarj_2017] AND
      tutkkoulk = [ylamktutkkoulk_2017]  )
      ,'alkk_2017' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [alkksuorv_2017] AND
      suorlk = [alkksuorlk_2017] AND
      tutkmaak = [alkktutkkmaak_2017] AND
      tutkjarj = [alkktutkjarj_2017] AND
      tutkkoulk = [alkktutkkoulk_2017]  )
      ,'ylkk_2017' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [ylkksuorv_2017] AND
      suorlk = [ylkksuorlk_2017] AND
      tutkmaak = [ylkktutkkmaak_2017] AND
      tutkjarj = [ylkktutkjarj_2017] AND
      tutkkoulk = [ylkktutkkoulk_2017]  )
      ,'tk_2017' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [tksuorv_2017] AND
      suorlk = [tksuorlk_2017] AND
      tutkmaak = [tktutkkmaak_2017] AND
      tutkjarj = [tktutkjarj_2017] AND
      tutkkoulk = [tktutkkoulk_2017]  )
      ,'muuta_2017' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [muutasuorv_2017] AND
      suorlk = [muutasuorlk_2017] AND
      tutkmaak = [muutatutkkmaak_2017] AND
      tutkjarj = [muutatutkjarj_2017] AND
      tutkkoulk = [muutatutkkoulk_2017]  )
      ,'amkopisk_2017' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [amkopiskkoulk_2017] AND
      opiskjarj_2 = [amkopiskjarj_2017] AND
      kmaak_2 = [amkkmaak_2017] --AND
      --olotamm_2 = [amkolotamm_2017] AND
      --olosyys_2 = [amkolosyys_2017]  
      )
      ,'ylamkopisk_2017' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [ylamkopiskkoulk_2017] AND
      opiskjarj_2 = [ylamkopiskjarj_2017] AND
      kmaak_2 = [ylamkkmaak_2017] --AND
      --olotamm_2 = [ylamkolotamm_2017] AND
      --olosyys_2 = [ylamkolosyys_2017]  
      )
      ,'alkkopisk_2017' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [alkkopiskkoulk_2017] AND
      opiskjarj_2 = [alkkopiskjarj_2017] AND
      kmaak_2 = [alkkkmaak_2017] --AND
      --olotamm_2 = [alkkolotamm_2017] AND
      --olosyys_2 = [alkkolosyys_2017]  
      )
      ,'ylkkopisk_2017' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [ylkkopiskkoulk_2017] AND
      opiskjarj_2 = [ylkkopiskjarj_2017] AND
      kmaak_2 = [ylkkkmaak_2017] --AND
      --olotamm_2 = [ylkkolotamm_2017] AND
      --olosyys_2 = [ylkkolosyys_2017]  
      )
      ,'tkopisk_2017' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [tkopiskkoulk_2017] AND
      opiskjarj_2 = [tkopiskjarj_2017] AND
      kmaak_2 = [tkkmaak_2017] --AND
      --olotamm_2 = [tkolotamm_2017] AND
      --olosyys_2 = [tkolosyys_2017]  
      )
      ,'muutaopisk_2017' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [muutaopiskkoulk_2017] AND
      opiskjarj_2 = [muutaopiskjarj_2017] AND
      kmaak_2 = [muutakmaak_2017] --AND
      --olotamm_2 = [muutaolotamm_2017] AND
      --olosyys_2 = [muutaolosyys_2017]  
      )
      ,'ptoim1r5_2017' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
      ptoim1r5 = [ptoim1r5_2017]  )
      --amas = [amas_2017]  )

-- 2018

      ,'amk_2018' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [amksuorv_2018] AND
      suorlk = [amksuorlk_2018] AND
      tutkmaak = [amktutkkmaak_2018] AND
      tutkjarj = [amktutkjarj_2018] AND
      tutkkoulk = [amktutkkoulk_2018]  )
      ,'ylamk_2018' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [ylamksuorv_2018] AND
      suorlk = [ylamksuorlk_2018] AND
      tutkmaak = [ylamktutkkmaak_2018] AND
      tutkjarj = [ylamktutkjarj_2018] AND
      tutkkoulk = [ylamktutkkoulk_2018]  )
      ,'alkk_2018' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [alkksuorv_2018] AND
      suorlk = [alkksuorlk_2018] AND
      tutkmaak = [alkktutkkmaak_2018] AND
      tutkjarj = [alkktutkjarj_2018] AND
      tutkkoulk = [alkktutkkoulk_2018]  )
      ,'ylkk_2018' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [ylkksuorv_2018] AND
      suorlk = [ylkksuorlk_2018] AND
      tutkmaak = [ylkktutkkmaak_2018] AND
      tutkjarj = [ylkktutkjarj_2018] AND
      tutkkoulk = [ylkktutkkoulk_2018]  )
      ,'tk_2018' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [tksuorv_2018] AND
      suorlk = [tksuorlk_2018] AND
      tutkmaak = [tktutkkmaak_2018] AND
      tutkjarj = [tktutkjarj_2018] AND
      tutkkoulk = [tktutkkoulk_2018]  )
      ,'muuta_2018' = (select id from [_aloittaneiden_lapaisy_avaimet] where  
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      suorv = [muutasuorv_2018] AND
      suorlk = [muutasuorlk_2018] AND
      tutkmaak = [muutatutkkmaak_2018] AND
      tutkjarj = [muutatutkjarj_2018] AND
      tutkkoulk = [muutatutkkoulk_2018]  )
      ,'amkopisk_2018' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [amkopiskkoulk_2018] AND
      opiskjarj_2 = [amkopiskjarj_2018] AND
      kmaak_2 = [amkkmaak_2018] --AND
      --olotamm_2 = [amkolotamm_2018] AND
      --olosyys_2 = [amkolosyys_2018]  
      )
      ,'ylamkopisk_2018' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [ylamkopiskkoulk_2018] AND
      opiskjarj_2 = [ylamkopiskjarj_2018] AND
      kmaak_2 = [ylamkkmaak_2018] --AND
      --olotamm_2 = [ylamkolotamm_2018] AND
      --olosyys_2 = [ylamkolosyys_2018]  
      )
      ,'alkkopisk_2018' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [alkkopiskkoulk_2018] AND
      opiskjarj_2 = [alkkopiskjarj_2018] AND
      kmaak_2 = [alkkkmaak_2018] --AND
      --olotamm_2 = [alkkolotamm_2018] AND
      --olosyys_2 = [alkkolosyys_2018]  
      )
      ,'ylkkopisk_2018' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [ylkkopiskkoulk_2018] AND
      opiskjarj_2 = [ylkkopiskjarj_2018] AND
      kmaak_2 = [ylkkkmaak_2018] --AND
      --olotamm_2 = [ylkkolotamm_2018] AND
      --olosyys_2 = [ylkkolosyys_2018]  
      )
      ,'tkopisk_2018' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [tkopiskkoulk_2018] AND
      opiskjarj_2 = [tkopiskjarj_2018] AND
      kmaak_2 = [tkkmaak_2018] --AND
      --olotamm_2 = [tkolotamm_2018] AND
      --olosyys_2 = [tkolosyys_2018]  
      )
      ,'muutaopisk_2018' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
	  [_aloittaneiden_lapaisy_avaimet].tilv = f.tilv AND
	  [_aloittaneiden_lapaisy_avaimet].lahde = f.lahde AND
      opiskkoulk_2 = [muutaopiskkoulk_2018] AND
      opiskjarj_2 = [muutaopiskjarj_2018] AND
      kmaak_2 = [muutakmaak_2018] --AND
      --olotamm_2 = [muutaolotamm_2018] AND
      --olosyys_2 = [muutaolosyys_2018]  
      )
      ,'ptoim1r5_2018' = (select id from [_aloittaneiden_lapaisy_avaimet] where    
      ptoim1r5 = [ptoim1r5_2018]  )
      --amas = [amas_2018]  )
	  	  
--UUSI VUOSI
--Lisää uuden vuoden kentät tähän yläpuolelle. Käytä pohjana edellisen vuoden kenttiä.

  FROM VipunenTK_DW.dbo.[_sa_K3_10_Tutk_suor_osuus_aloittaneista_korkeakoulut_nykytila_1] f
  INNER JOIN VipunenTK_DW.dbo.[_sa_K3_10_Tutk_suor_osuus_aloittaneista_korkeakoulut_nykytila_2] f2 on f2.rivinro = f.rivinro







GO


