use VipunenTK_DW
go

DROP TABLE VipunenTK_DW.dbo.[_sa_K3_10_Tutk_suor_osuus_aloittaneista_korkeakoulut_nykytila_1]

Select top 0 * into VipunenTK_DW.dbo.[_sa_K3_10_Tutk_suor_osuus_aloittaneista_korkeakoulut_nykytila_1] from VipunenTK_SA.dbo.[v_sa_K3_10_Tutk_suor_osuus_aloittaneista_korkeakoulut_nykytila_1]

DROP TABLE VipunenTK_DW.dbo.[_sa_K3_10_Tutk_suor_osuus_aloittaneista_korkeakoulut_nykytila_2]

Select top 0 * into VipunenTK_DW.dbo.[_sa_K3_10_Tutk_suor_osuus_aloittaneista_korkeakoulut_nykytila_2] from VipunenTK_SA.dbo.[v_sa_K3_10_Tutk_suor_osuus_aloittaneista_korkeakoulut_nykytila_2]
