
use antero

insert into antero.sa.[sa_virta_otp_viisviis_2021]
(
[edellinenSyysolo]
      ,[hetu]
      ,[ika]
      ,[kevat]
      ,[loAloituspvm]
      ,[olok]
      ,[olos]
      ,[ooAloituspvm]
      ,[opSummaKunOtePankista]
      ,[opiskelijaavain]
      ,[opiskeluoikeusavain]
      ,[opiskeluoikeusid]
      ,[oppilaitos]
      ,[oppilaitostunnus]
      ,[pankkiKumuEnnen55]
      ,[pankkiSaldo55]
      ,[regDatum]
      ,[sukupuoli]
      ,[summa]
      ,[suorittanut27]
      ,[suorittanut55ilmanPankkia]
      ,[suorittanut55pankinAvulla]
      ,[syys]
      ,[tkoodi]
      ,[uusiOpisk]
      ,[uusiOpiskKevat]
      ,[uuttaPankkiin]
      ,[vuosi]
)

select 
[edellinenSyysolo]
      ,[hetu]
      ,[ika]
      ,[kevat]
      ,[loAloituspvm]
      ,[olok]
      ,[olos]
      ,[ooAloituspvm]
      ,[opSummaKunOtePankista]
      ,[opiskelijaavain]
      ,[opiskeluoikeusavain]
      ,[opiskeluoikeusid]
      ,[oppilaitos]
      ,[oppilaitostunnus]
      ,[pankkiKumuEnnen55]
      ,[pankkiSaldo55]
      ,[regDatum]
      ,[sukupuoli]
      ,[summa]
      ,[suorittanut27]
      ,[suorittanut55ilmanPankkia]
      ,[suorittanut55pankinAvulla]
      ,[syys]
      ,[tkoodi]
      ,[uusiOpisk]
      ,[uusiOpiskKevat]
      ,[uuttaPankkiin]
      ,[vuosi]
	  from antero.sa.sa_virta_otp_viisviis

	  
	  go
	  use antero
	  