USE [VipunenTK_DW]
GO

/****** Object:  Table [dbo].[f_K_3_11_Keskeyttaneet]    Script Date: 23.11.2021 13:59:09 ******/
DROP TABLE [dbo].[f_K_3_11_Keskeyttaneet]
GO

/****** Object:  Table [dbo].[f_K_3_11_Keskeyttaneet]    Script Date: 23.11.2021 13:59:09 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[f_K_3_11_Keskeyttaneet](
	[tilastovuosi] [nvarchar](6) NULL,
	[tilv_date] [date] NULL,
	[aineisto] [nvarchar](1) NULL,
	[lahde] [nvarchar](2) NULL,
	[sukupuoli] [nvarchar](1) NULL,
	[aidinkieli_versio1x] [nvarchar](2) NULL,
	[ika_1v] [nvarchar](10) NULL,
	[ika_5v] [nvarchar](10) NULL,
	[kotikunta] [nvarchar](3) NULL,
	[kansalaisuus_versio1] [nvarchar](1) NULL,
	[eumaa] [nvarchar](1) NULL,
	[etamaa] [nvarchar](1) NULL,
	[pohjoismaa] [nvarchar](1) NULL,
	[kirjoihintulovuosi] [nvarchar](4) NULL,
	[kirjoihintulolukukausi] [nvarchar](6) NULL,
	[opiskelijan_olo_lk] [nvarchar](4) NULL,
	[oppilaitoksen_taustatiedot] [nvarchar](5) NULL,
	[koulutusluokitus] [nvarchar](6) NULL,
	[koulutuksen_kieli_versio1] [nvarchar](2) NULL,
	[koulutuksen_kunta] [nvarchar](3) NULL,
	[opetushallinnon_koulutus] [nvarchar](1) NULL,
	[hallinnonala2] [nvarchar](2) NULL,
	[koulutustyyppi] [nvarchar](1) NULL,
	[tutkinnon_suorittamismaakunta] [nvarchar](2) NULL,
	[tutkinnon_jarjestaja] [nvarchar](10) NULL,
	[tutkinnon_suorittamisoppilaitos] [nvarchar](5) NULL,
	[tutkinnon_koulutusluokitus] [nvarchar](6) NULL,
	[tutkinnon_koulutustyyppi] [nvarchar](1) NULL,
	[seuraavan_vuoden_maakunta] [nvarchar](2) NULL,
	[seuraavan_vuoden_jarjestaja] [nvarchar](10) NULL,
	[seuraavan_vuoden_oppilaitos] [nvarchar](5) NULL,
	[seuraavan_vuoden_koulutusluokitus] [nvarchar](6) NULL,
	[seuraavan_vuoden_koulutustyyppi] [nvarchar](1) NULL,
	[pääasiallinen_toiminta_versio2] [nvarchar](2) NULL,
	[ammattiasema] [nvarchar](1) NULL,
	[opiskelijat] [int] NULL,
	--uudet
	[1a_opiskelijoiden_opintojen_kulku_kaste_t2_mukaan] [nvarchar](2) NULL,
	[1b_opiskelijoiden_opintojen_kulku_kaste_t2_mukaan] [nvarchar](2) NULL,
	[1c_tutkinto_alkuperaisella_kaste_t2ella] [nvarchar](2) NULL,
	[1d_tutkinto_muulla_kaste_t2ella] [nvarchar](2) NULL,
	[1e_jatkaa_opiskelua_alkuperaisella_kaste_t2ella] [nvarchar](2) NULL,
	[1f_jatkaa_opiskelua_muulla_kaste_t2ella] [nvarchar](2) NULL,
	[2a_opiskelijoiden_opintojen_kulku_kala_t1_mukaan] [nvarchar](2) NULL,
	[2b_opiskelijoiden_opintojen_kulku_kala_t1_mukaan] [nvarchar](2) NULL,
	[2bb_opiskelijoiden_opintojen_kulku_kala_t1_mukaan] [nvarchar](2) NULL,
	[2c_tutkinto_alkuperaisella_kala_t1lla] [nvarchar](2) NULL,
	[2d_tutkinto_muulla_kala_t1lla] [nvarchar](2) NULL,
	[2e_jatkaa_opiskelua_alkuperaisella_kala_t1lla] [nvarchar](2) NULL,
	[2f_jatkaa_opiskelua_muulla_kala_t1lla] [nvarchar](2) NULL,
	[2a_opiskelijoiden_opintojen_kulku_kala_t2_mukaan] [nvarchar](2) NULL,
	[2b_opiskelijoiden_opintojen_kulku_kala_t2_mukaan] [nvarchar](2) NULL,
	[2bb_opiskelijoiden_opintojen_kulku_kala_t2_mukaan] [nvarchar](2) NULL,
	[2c_tutkinto_alkuperaisella_kala_t2lla] [nvarchar](2) NULL,
	[2d_tutkinto_muulla_kala_t2lla] [nvarchar](2) NULL,
	[2e_jatkaa_opiskelua_alkuperaisella_kala_t2lla] [nvarchar](2) NULL,
	[2f_jatkaa_opiskelua_muulla_kala_t2lla] [nvarchar](2) NULL,
	[2a_opiskelijoiden_opintojen_kulku_kala_t3_mukaan] [nvarchar](2) NULL,
	[2b_opiskelijoiden_opintojen_kulku_kala_t3_mukaan] [nvarchar](2) NULL,
	[2bb_opiskelijoiden_opintojen_kulku_kala_t3_mukaan] [nvarchar](2) NULL,
	[2c_tutkinto_alkuperaisella_kala_t3lla] [nvarchar](2) NULL,
	[2d_tutkinto_muulla_kala_t3lla] [nvarchar](2) NULL,
	[2e_jatkaa_opiskelua_alkuperaisella_kala_t3lla] [nvarchar](2) NULL,
	[2f_jatkaa_opiskelua_muulla_kala_t3lla] [nvarchar](2) NULL,
	[4bb_opiskelijoiden_opintojen_kulku_jarj_ja_kaste_t2_mukaan] [nvarchar](2) NULL,
	--vanhat; 5bb ja 7:t päivitetty
	[1a_opiskelijoiden_opintojen_kulku_koulutusaste_2002_mukaan] [nvarchar](2) NULL,
	[1b_opiskelijoiden_opintojen_kulku_koulutusaste_2002_mukaan] [nvarchar](2) NULL,
	[1c_tutkinto_alkuperaisella_koulutusasteella_2002] [nvarchar](2) NULL,
	[1d_tutkinto_muulla_koulutusasteella_2002] [nvarchar](2) NULL,
	[1e_jatkaa_opiskelua_alkuperaisella_koulutusasteella_2002] [nvarchar](2) NULL,
	[1f_jatkaa_opiskelua_muulla_koulutusasteella_2002] [nvarchar](2) NULL,
	[2a_opiskelijoiden_opintojen_kulku_koulutusala_2002_mukaan] [nvarchar](2) NULL,
	[2b_opiskelijoiden_opintojen_kulku_koulutusala_2002_mukaan] [nvarchar](2) NULL,
	[2bb_opiskelijoiden_opintojen_kulku_koulutusala_2002_mukaan] [nvarchar](2) NULL,
	[2c_tutkinto_alkuperaisella_koulutusalalla_2002] [nvarchar](2) NULL,
	[2d_tutkinto_muulla_koulutusalalla_2002] [nvarchar](2) NULL,
	[2e_jatkaa_opiskelua_alkuperaisella_koulutusalalla_2002] [nvarchar](2) NULL,
	[2f_jatkaa_opiskelua_muulla_koulutusalalla_2002] [nvarchar](2) NULL,
	[3a_opiskelijoiden_opintojen_kulku_opintoala_2002_mukaan] [nvarchar](2) NULL,
	[3b_opiskelijoiden_opintojen_kulku_opintoala_2002_mukaan] [nvarchar](2) NULL,
	[3bb_opiskelijoiden_opintojen_kulku_opintoala_2002_mukaan] [nvarchar](2) NULL,
	[3c_tutkinto_alkuperaisella_opintoalalla_2002] [nvarchar](2) NULL,
	[3d_tutkinto_muulla_opintoalalla_2002] [nvarchar](2) NULL,
	[3e_jatkaa_opiskelua_alkuperaisella_opintoalalla_2002] [nvarchar](2) NULL,
	[3f_jatkaa_opiskelua_muulla_opintoalalla_2002] [nvarchar](2) NULL,
	[4a_opiskelijoiden_opintojen_kulku_koul_jarjestajan_mukaan] [nvarchar](2) NULL,
	[4b_opiskelijoiden_opintojen_kulku_koul_jarjestajan_mukaan] [nvarchar](2) NULL,
	[4bb_opiskelijoiden_opintojen_kulku_koul_jarjestajan_mukaan] [nvarchar](2) NULL,
	[4c_tutkinto_alkuperaisella_koulutuksen_jarjestajalla] [nvarchar](2) NULL,
	[4d_tutkinto_muulla_koulutuksen_jarjestajalla] [nvarchar](2) NULL,
	[4e_jatkaa_opiskelua_alkuperaisella_koulutuksen_jarjestajalla] [nvarchar](2) NULL,
	[4f_jatkaa_opiskelua_muulla_koulutuksen_jarjestajalla] [nvarchar](2) NULL,
	[5a_opiskelijoiden_opintojen_kulku_oppilaitoksen_mukaan] [nvarchar](2) NULL,
	[5b_opiskelijoiden_opintojen_kulku_oppilaitoksen_mukaan] [nvarchar](2) NULL,
	[5bb_opiskelijoiden_opintojen_kulku_oppilaitoksen_mukaan] [nvarchar](2) NULL,
	[5c_tutkinto_alkuperaisessa_oppilaitoksessa] [nvarchar](2) NULL,
	[5d_tutkinto_muussa_oppilaitoksessa] [nvarchar](2) NULL,
	[5e_jatkaa_opiskelua_alkuperaisessa_oppilaitoksessa] [nvarchar](2) NULL,
	[5f_jatkaa_opiskelua_muussa_oppilaitoksessa] [nvarchar](2) NULL,
	[6a_opiskelijoiden_opintojen_kulku_maakunnan_mukaan] [nvarchar](2) NULL,
	[6b_opiskelijoiden_opintojen_kulku_maakunnan_mukaan] [nvarchar](2) NULL,
	[6c_tutkinto_alkuperaisessa_maakunnassa] [nvarchar](2) NULL,
	[6d_tutkinto_muussa_maakunnassa] [nvarchar](2) NULL,
	[6e_jatkaa_opiskelua_alkuperaisessa_maakunnassa] [nvarchar](2) NULL,
	[6f_jatkaa_opiskelua_muussa_maakunnassa] [nvarchar](2) NULL,
	[7a_opiskelijoiden_opintojen_kulku_koulutussektorin_mukaan] [nvarchar](2) NULL,
	[7b_opiskelijoiden_opintojen_kulku_koulutussektorin_mukaan] [nvarchar](2) NULL,
	[7c_tutkinto_alkuperaisella_koulutussektorilla] [nvarchar](2) NULL,
	[7d_tutkinto_muulla_koulutussektorilla] [nvarchar](2) NULL,
	[7e_jatkaa_opiskelua_alkuperaisella_koulutussektorilla] [nvarchar](2) NULL,
	[7f_jatkaa_opiskelua_muulla_koulutussektorilla] [nvarchar](2) NULL
) ON [PRIMARY]

GO


