USE [VipunenTK]
GO

/****** Object:  Table [dbo].[f_tab_tutkinnon_suorittaneiden_aiempi_koulutus_4_7_yhteiset]    Script Date: 3.12.2021 23:17:25 ******/
DROP TABLE [dbo].[f_tab_tutkinnon_suorittaneiden_aiempi_koulutus_4_7_yhteiset]
GO

/****** Object:  Table [dbo].[f_tab_tutkinnon_suorittaneiden_aiempi_koulutus_4_7_yhteiset]    Script Date: 3.12.2021 23:17:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[f_tab_tutkinnon_suorittaneiden_aiempi_koulutus_4_7_yhteiset](
	[henkiloiden_lkm] [int] NULL,
	[lu_henkiloiden_lkm] [int] NULL,
	[amm_henkiloiden_lkm] [int] NULL,
	[opist_henkiloiden_lkm] [int] NULL,
	[ammka_henkiloiden_lkm] [int] NULL,
	[amk_henkiloiden_lkm] [int] NULL,
	[akk_henkiloiden_lkm] [int] NULL,
	[ylamklkm_henkiloiden_lkm] [int] NULL,
	[ykk_henkiloiden_lkm] [int] NULL,
	[laaker_henkiloiden_lkm] [int] NULL,
	[lis_henkiloiden_lkm] [int] NULL,
	[toht_henkiloiden_lkm] [int] NULL,
	[ai_yliop_lkm] [int] NULL,
	[ai_yo_jatko_lkm] [int] NULL,
	[ai_opisto_ammkork_lkm] [int] NULL,
	[ai_kork_lkm] [int] NULL,
	[ai_toinenaste_lkm] [int] NULL,
	[ai_ammryhma1_lkm] [int] NULL,
	[ai_ammryhma2_lkm] [int] NULL,
	[ai_ammryhma3_lkm] [int] NULL,
	[Ei_aiempaa_perusasteen_jalkeista_tutkintoa_lkm] [int] NULL,
	[Tilastovuosi] [nvarchar](4) NULL,
	[Tarkastelujakso] [nvarchar](100) NULL,
	[Äidinkieli] [nvarchar](50) NULL,
	[Koulutusaste] [nvarchar](255) NOT NULL,
	[Koulutusala (02 luokitus)] [nvarchar](255) NOT NULL,
	[Koulutusala (95 luokitus)] [nvarchar](255) NOT NULL,
	[Opintoala] [nvarchar](255) NOT NULL,
	[Koulutusnimike] [nvarchar](255) NOT NULL,
	[Sukupuoli] [nvarchar](250) NULL,
	[Tutkinnon suoritusvuosi] [varchar](4) NOT NULL,
	[Tutkinnon suorituslukukausi] [nvarchar](20) NULL,
	[Aloitusvuosi] [varchar](4) NOT NULL,
	[Aloituslukukausi] [nvarchar](20) NULL,
	[Syntymävuosi] [varchar](4) NULL,
	[Yo-tutkinnon suoritusvuosi] [varchar](4) NOT NULL,
	[Amm. tutkinnon suoritusvuosi] [varchar](4) NOT NULL,
	[Opistoast. tutkinnon suoritusvuosi] [varchar](4) NOT NULL,
	[Amm. kork.asteen tutk. suoritusvuosi] [varchar](4) NOT NULL,
	[Amk-tutkinnon suoritusvuosi] [varchar](4) NOT NULL,
	[Alemman kk-tutk. suoritusvuosi] [varchar](4) NOT NULL,
	[Ylemmän amk-tutk. suoritusvuosi] [varchar](4) NOT NULL,
	[Ylemmän kk-tutk. suoritusvuosi] [varchar](4) NOT NULL,
	[Lääk. erikois.tutk. suoritusvuosi] [varchar](4) NOT NULL,
	[Lisensiaatin tutk. suoritusvuosi] [varchar](4) NOT NULL,
	[Tohtorin tutk. suorituvuosi] [varchar](4) NOT NULL,
	[Oppisopimuskoulutus] [nvarchar](50) NULL,
	[Koulutus- ja oppisopimusjaksot] [nvarchar](250) NULL,
	[Tutkintotyyppi] [nvarchar](50) NULL,
	[Järjestämistapa] [nvarchar](50) NULL,
	[Nuorten/aikuisten koulutus] [nvarchar](50) NULL,
	[Ikä] [nvarchar](50) NULL,
	[Ikäryhmä] [nvarchar](50) NULL,
	[Yo-tutkinnon koulutusnimike] [nvarchar](255) NOT NULL,
	[Aik. suoritettu yo-tutkinto] [nvarchar](100) NULL,
	[Yo-tutkinnosta kulunut aika] [nvarchar](100) NULL,
	[Nuorten/aikuisten koulutus (yo)] [nvarchar](50) NULL,
	[Amm. tutkinnon koulutusala] [nvarchar](255) NOT NULL,
	[Amm. tutkinnon opintoala] [nvarchar](255) NOT NULL,
	[Amm. tutkinnon koulutusnimike] [nvarchar](255) NOT NULL,
	[Aik. suoritettu amm. tutkinto] [nvarchar](100) NULL,
	[Amm. tutkinnosta kulunut aika] [nvarchar](100) NULL,
	[Amm. tutkinnon tutkintotyyppi] [nvarchar](50) NULL,
	[Amm. tutkinnon järjestämistapa] [nvarchar](50) NULL,
	[Amm. tutkinto oppisopimuskoul.] [nvarchar](50) NULL,
	[Amm. tutkinnon koulutus- ja oppisopimusjaksot] [nvarchar](250) NULL,
	[Amm. tutkintojen määrä] [nvarchar](100) NULL,
	[Amm. koulutuksen ryhmät] [nvarchar](100) NULL,
	[Opistoast. tutkinnon koulutusala] [nvarchar](255) NOT NULL,
	[Opistoast. tutkinnon opintoala] [nvarchar](255) NOT NULL,
	[Opistoast. tutkinnon koulutusnimike] [nvarchar](255) NOT NULL,
	[Aik. suoritettu opistoast. tutkinto] [nvarchar](100) NULL,
	[Opistoast. tutkinnosta kulunut aika] [nvarchar](100) NULL,
	[Amm. kork.asteen tutk. koulutusala] [nvarchar](255) NOT NULL,
	[Amm. kork.asteen tutk. opintoala] [nvarchar](255) NOT NULL,
	[Amm. kork.asteen tutk. koulutusnimike] [nvarchar](255) NOT NULL,
	[Aik. suoritettu amm. kork.asteen tutkinto] [nvarchar](100) NULL,
	[Amm. kork.asteen tutk. kulunut aika] [nvarchar](100) NULL,
	[Amk-tutkinnon koulutusala] [nvarchar](255) NOT NULL,
	[Amk-tutkinnon opintoala] [nvarchar](255) NOT NULL,
	[Amk-tutkinnon koulutusnimike] [nvarchar](255) NOT NULL,
	[Aik. suoritettu amk-tutkinto] [nvarchar](100) NULL,
	[Amk-tutkinnosta kulunut aika] [nvarchar](100) NULL,
	[Amk-tutkintojen määrä] [nvarchar](100) NULL,
	[Nuorten/aikuisten koulutus (amk)] [nvarchar](250) NULL,
	[Alemman kk-tutk. koulutusala (02)] [nvarchar](255) NOT NULL,
	[Alemman kk-tutk. koulutusala (95)] [nvarchar](255) NOT NULL,
	[Alemman kk-tutk. opintoala] [nvarchar](255) NOT NULL,
	[Alemman kk-tutk. koulutusnimike] [nvarchar](255) NOT NULL,
	[Aik. suoritettu alempi kk-tutkinto] [nvarchar](100) NULL,
	[Alemmasta kk-tutk. kulunut aika] [nvarchar](100) NULL,
	[Alempien kk-tutkintojen määrä] [nvarchar](100) NULL,
	[Ylemmän amk-tutk. koulutusala] [nvarchar](255) NOT NULL,
	[Ylemmän amk-tutk. opintoala] [nvarchar](255) NOT NULL,
	[Ylemmän amk-tutk. koulutusnimike] [nvarchar](255) NOT NULL,
	[Aik. suoritettu ylempi amk-tutkinto] [nvarchar](100) NULL,
	[Ylemmästä amk-tutk. kulunut aika] [nvarchar](100) NULL,
	[Ylemmän kk-tutk. koulutusala (02)] [nvarchar](255) NOT NULL,
	[Ylemmän kk-tutk. koulutusala (95)] [nvarchar](255) NOT NULL,
	[Ylemmän kk-tutk. opintoala] [nvarchar](255) NOT NULL,
	[Ylemmän kk-tutk. koulutusnimike] [nvarchar](255) NOT NULL,
	[Aik. suoritettu ylempi kk-tutkinto] [nvarchar](100) NULL,
	[Ylemmästä kk-tutk. kulunut aika] [nvarchar](100) NULL,
	[Ylempien kk-tutkintojen määrä] [nvarchar](100) NULL,
	[Lääk. erikois.tutk. koulutusnimike] [nvarchar](255) NOT NULL,
	[Aik. suoritettu lääk. erikois.tutk.] [nvarchar](100) NULL,
	[Lääk. erikois.tutk. kulunut aika] [nvarchar](100) NULL,
	[Lisensiaatin tutk. koulutusala (02)] [nvarchar](255) NOT NULL,
	[Lisensiaatin tutk. koulutusala (95)] [nvarchar](255) NOT NULL,
	[Lisensiaatin tutk. opintoala] [nvarchar](255) NOT NULL,
	[Lisensiaatin tutk. koulutusnimike] [nvarchar](255) NOT NULL,
	[Aik. suoritettu lisensiaatin tutk.] [nvarchar](100) NULL,
	[Lisensiaatin tutk. kulunut aika] [nvarchar](100) NULL,
	[Tohtorin tutk. koulutusala (02)] [nvarchar](255) NOT NULL,
	[Tohtorin tutk. koulutusala (95)] [nvarchar](255) NOT NULL,
	[Tohtorin tutk. opintoala] [nvarchar](255) NOT NULL,
	[Tohtorin tutk. koulutusnimike] [nvarchar](255) NOT NULL,
	[Aik. suoritettu tohtorin tutk.] [nvarchar](100) NULL,
	[Tohtorin tutk. kulunut aika] [nvarchar](100) NULL,
	[Aik. suoritettu yliopistotutkinto] [nvarchar](100) NULL,
	[Aik. suoritettu yo-jatkotutkinto] [nvarchar](100) NULL,
	[Aik. suoritettu opistoast. tai amm. kork.ast. tutkinto] [nvarchar](100) NULL,
	[Aik. suoritettu korkeakoulututkinto] [nvarchar](100) NULL,
	[Aik. suoritettu toisen asteen tutkinto] [nvarchar](100) NULL,
	[Aik. suoritettu amm. tutkinto (ryhmä 1)] [nvarchar](100) NULL,
	[Aik. suoritettu amm. tutkinto (ryhmä 2)] [nvarchar](100) NULL,
	[Aik. suoritettu amm. tutkinto (ryhmä 3)] [nvarchar](100) NULL,
	[Yo-tutkinto samalla koul.alalla (02)] [nvarchar](100) NULL,
	[Amm. tutk. samalla koul.alalla (02)] [nvarchar](100) NULL,
	[Opistoast. tutk. samalla koul.alalla (02)] [nvarchar](100) NULL,
	[Amm. ka. tutk. samalla koul.alalla (02)] [nvarchar](100) NULL,
	[Amk-tutkinto samalla koul.alalla (02)] [nvarchar](100) NULL,
	[Alempi kk-tutk. samalla koul.alalla (02)] [nvarchar](100) NULL,
	[Ylempi amk-tutk. samalla koul.alalla (02)] [nvarchar](100) NULL,
	[Ylempi kk-tutk. samalla koul.alalla (02)] [nvarchar](100) NULL,
	[Laak. erik.tutk. samalla koul.alalla (02)] [nvarchar](100) NULL,
	[Lis. tutkinto samalla koul.alalla (02)] [nvarchar](100) NULL,
	[Toht. tutkinto samalla koul.alalla (02)] [nvarchar](100) NULL,
	[Yliopistotutk. samalla koul.alalla (02)] [nvarchar](100) NULL,
	[Yo-jatkotutk. samalla koul.alalla (02)] [nvarchar](100) NULL,
	[Opisto/amm.ka. tutk. samalla koul.alalla (02)] [nvarchar](100) NULL,
	[Korkeak.tutk. samalla koul.alalla (02)] [nvarchar](100) NULL,
	[Toisen asteen tutk. samalla koul.alalla (02)] [nvarchar](100) NULL,
	[Yo-tutkinto samalla op.alalla] [nvarchar](100) NULL,
	[Amm. tutk. samalla op.alalla] [nvarchar](100) NULL,
	[Opistoast. tutk. samalla op.alalla] [nvarchar](100) NULL,
	[Amm. ka. tutk. samalla op.alalla] [nvarchar](100) NULL,
	[Amk-tutkinto samalla op.alalla] [nvarchar](100) NULL,
	[Alempi kk-tutk. samalla op.alalla] [nvarchar](100) NULL,
	[Ylempi amk-tutk. samalla op.alalla] [nvarchar](100) NULL,
	[Ylempi kk-tutk. samalla op.alalla] [nvarchar](100) NULL,
	[Laak. erik.tutk. samalla op.alalla] [nvarchar](100) NULL,
	[Lis. tutkinto samalla op.alalla] [nvarchar](100) NULL,
	[Toht. tutkinto samalla op.alalla] [nvarchar](100) NULL,
	[Yliopistotutk. samalla op.alalla] [nvarchar](100) NULL,
	[Yo-jatkotutk. samalla op.alalla] [nvarchar](100) NULL,
	[Opisto/amm.ka. tutk. samalla op.alalla] [nvarchar](100) NULL,
	[Korkeak.tutk. samalla op.alalla] [nvarchar](100) NULL,
	[Toisen asteen tutk. samalla op.alalla] [nvarchar](100) NULL,
	[Yo-tutkinto samalla koul.alalla (95)] [nvarchar](100) NULL,
	[Amm. tutk. samalla koul.alalla (95)] [nvarchar](100) NULL,
	[Opistoast. tutk. samalla koul.alalla (95)] [nvarchar](100) NULL,
	[Amm. ka. tutk. samalla koul.alalla (95)] [nvarchar](100) NULL,
	[Amk-tutkinto samalla koul.alalla (95)] [nvarchar](100) NULL,
	[Alempi kk-tutk. samalla koul.alalla (95)] [nvarchar](100) NULL,
	[Ylempi amk-tutk. samalla koul.alalla (95)] [nvarchar](100) NULL,
	[Ylempi kk-tutk. samalla koul.alalla (95)] [nvarchar](100) NULL,
	[Laak. erik.tutk. samalla koul.alalla (95)] [nvarchar](100) NULL,
	[Lis. tutkinto samalla koul.alalla (95)] [nvarchar](100) NULL,
	[Toht. tutkinto samalla koul.alalla (95)] [nvarchar](100) NULL,
	[Yliopistotutk. samalla koul.alalla (95)] [nvarchar](100) NULL,
	[Yo-jatkotutk. samalla koul.alalla (95)] [nvarchar](100) NULL,
	[Opisto/amm.ka. tutk. samalla koul.alalla (95)] [nvarchar](100) NULL,
	[Korkeak.tutk. samalla koul.alalla (95)] [nvarchar](100) NULL,
	[Toisen asteen tutk. samalla koul.alalla (95)] [nvarchar](100) NULL,
	[Yo-tutkinto samalla koul.alalla 1] [nvarchar](100) NULL,
	[Amm. tutk. samalla koul.alalla 1] [nvarchar](100) NULL,
	[Opistoast. tutk. samalla koul.alalla 1] [nvarchar](100) NULL,
	[Amm. ka. tutk. samalla koul.alalla 1] [nvarchar](100) NULL,
	[Amk-tutkinto samalla koul.alalla 1] [nvarchar](100) NULL,
	[Alempi kk-tutk. samalla koul.alalla 1] [nvarchar](100) NULL,
	[Ylempi amk-tutk. samalla koul.alalla 1] [nvarchar](100) NULL,
	[Ylempi kk-tutk. samalla koul.alalla 1] [nvarchar](100) NULL,
	[Laak. erik.tutk. samalla koul.alalla 1] [nvarchar](100) NULL,
	[Lis. tutkinto samalla koul.alalla 1] [nvarchar](100) NULL,
	[Toht. tutkinto samalla koul.alalla 1] [nvarchar](100) NULL,
	[Yliopistotutk. samalla koul.alalla 1] [nvarchar](100) NULL,
	[Yo-jatkotutk. samalla koul.alalla 1] [nvarchar](100) NULL,
	[Opisto/amm.ka. tutk. samalla koul.alalla 1] [nvarchar](100) NULL,
	[Korkeak.tutk. samalla koul.alalla 1] [nvarchar](100) NULL,
	[Toisen asteen tutk. samalla koul.alalla 1] [nvarchar](100) NULL,
	[Yo-tutkinto samalla koul.alalla 2] [nvarchar](100) NULL,
	[Amm. tutk. samalla koul.alalla 2] [nvarchar](100) NULL,
	[Opistoast. tutk. samalla koul.alalla 2] [nvarchar](100) NULL,
	[Amm. ka. tutk. samalla koul.alalla 2] [nvarchar](100) NULL,
	[Amk-tutkinto samalla koul.alalla 2] [nvarchar](100) NULL,
	[Alempi kk-tutk. samalla koul.alalla 2] [nvarchar](100) NULL,
	[Ylempi amk-tutk. samalla koul.alalla 2] [nvarchar](100) NULL,
	[Ylempi kk-tutk. samalla koul.alalla 2] [nvarchar](100) NULL,
	[Laak. erik.tutk. samalla koul.alalla 2] [nvarchar](100) NULL,
	[Lis. tutkinto samalla koul.alalla 2] [nvarchar](100) NULL,
	[Toht. tutkinto samalla koul.alalla 2] [nvarchar](100) NULL,
	[Yliopistotutk. samalla koul.alalla 2] [nvarchar](100) NULL,
	[Yo-jatkotutk. samalla koul.alalla 2] [nvarchar](100) NULL,
	[Opisto/amm.ka. tutk. samalla koul.alalla 2] [nvarchar](100) NULL,
	[Korkeak.tutk. samalla koul.alalla 2] [nvarchar](100) NULL,
	[Toisen asteen tutk. samalla koul.alalla 2] [nvarchar](100) NULL,
	[jarj_tarkastelujakso] [nvarchar](100) NULL,
	[jarj_aidinkieli] [nvarchar](50) NULL,
	[jarjestys_koulutusaste2002] [nvarchar](10) NULL,
	[jarjestys_koulutusala2002] [nvarchar](10) NULL,
	[jarjestys_opintoala1995] [nvarchar](10) NULL,
	[jarjestys_opintoala2002] [nvarchar](10) NULL,
	[jarj_koulnimike] [nvarchar](10) NULL,
	[jarj_oppis] [nvarchar](50) NULL,
	[jarj_sopimusjaksot] [int] NULL,
	[jarj_tutktyyppi] [nvarchar](50) NULL,
	[jarj_jarjtapa] [nvarchar](50) NULL,
	[jarj_nuoretaikuisetamm] [nvarchar](50) NULL,
	[jarj_ika] [nvarchar](50) NULL,
	[jarj_ika5v] [nvarchar](50) NULL,
	[jarj_lukio_koulnimike] [nvarchar](10) NULL,
	[jarj_lukio_aiktutk] [nvarchar](50) NULL,
	[jarj_lukio_kulunutaika] [nvarchar](100) NULL,
	[jarj_lukio_nuoretaikuiset] [nvarchar](50) NULL,
	[jarj_amm_koulala] [nvarchar](10) NULL,
	[jarj_amm_opala] [nvarchar](10) NULL,
	[jarj_amm_koulnimike] [nvarchar](10) NULL,
	[jarj_amm_aiktutk] [nvarchar](50) NULL,
	[jarj_amm_kulunutaika] [nvarchar](100) NULL,
	[jarj_amm_tutktyyppi] [nvarchar](50) NULL,
	[jarj_amm_jarjtapa] [nvarchar](50) NULL,
	[jarj_amm_oppis] [nvarchar](50) NULL,
	[jarj_amm_sopimusjaksot] [int] NULL,
	[jarj_amm_tutkmaara] [nvarchar](50) NULL,
	[jarj_amm_ryhma] [nvarchar](50) NULL,
	[jarj_opisto_koulala] [nvarchar](10) NULL,
	[jarj_opisto_opala] [nvarchar](10) NULL,
	[jarj_opisto_koulnimike] [nvarchar](10) NULL,
	[jarj_opisto_aiktutk] [nvarchar](50) NULL,
	[jarj_opisto_kulunutaika] [nvarchar](100) NULL,
	[jarj_amm_kork_aste_koulala] [nvarchar](10) NULL,
	[jarj_amm_kork_aste_opala] [nvarchar](10) NULL,
	[jarj_amm_kork_aste_koulnimike] [nvarchar](10) NULL,
	[jarj_amm_kork_aste_aiktutk] [nvarchar](50) NULL,
	[jarj_amm_kork_aste_kulunutaika] [nvarchar](100) NULL,
	[jarj_amk_koulala] [nvarchar](10) NULL,
	[jarj_amk_opala] [nvarchar](10) NULL,
	[jarj_amk_koulnimike] [nvarchar](10) NULL,
	[jarj_amk_aiktutk] [nvarchar](50) NULL,
	[jarj_amk_kulunutaika] [nvarchar](100) NULL,
	[jarj_amk_tutkmaara] [nvarchar](50) NULL,
	[jarj_amk_nuoraik] [nvarchar](50) NULL,
	[jarj_alempi_kk_koulala02] [nvarchar](10) NULL,
	[jarj_alempi_kk_koulala95] [nvarchar](10) NULL,
	[jarj_alempi_kk_opala] [nvarchar](10) NULL,
	[jarj_alempi_kk_koulnimike] [nvarchar](10) NULL,
	[jarj_alempi_kk_aiktutk] [nvarchar](50) NULL,
	[jarj_alempi_kk_kulunutaika] [nvarchar](100) NULL,
	[jarj_alempi_kk_tutkmaara] [nvarchar](50) NULL,
	[jarj_ylempi_amk_koulala] [nvarchar](10) NULL,
	[jarj_ylempi_amk_opala] [nvarchar](10) NULL,
	[jarj_ylempi_amk_koulnimike] [nvarchar](10) NULL,
	[jarj_ylempi_amk_aiktutk] [nvarchar](50) NULL,
	[jarj_ylempi_amk_kulunutaika] [nvarchar](100) NULL,
	[jarj_ylempi_kk_koulala02] [nvarchar](10) NULL,
	[jarj_ylempi_kk_koulala95] [nvarchar](10) NULL,
	[jarj_ylempi_kk_opala] [nvarchar](10) NULL,
	[jarj_ylempi_kk_koulnimike] [nvarchar](10) NULL,
	[jarj_ylempi_kk_aiktutk] [nvarchar](50) NULL,
	[jarj_ylempi_kk_kulunutaika] [nvarchar](100) NULL,
	[jarj_ylempi_kk_tutkmaara] [nvarchar](50) NULL,
	[jarj_laak_erik_koulnimike] [nvarchar](10) NULL,
	[jarj_laak_erik_aiktutk] [nvarchar](50) NULL,
	[jarj_laak_erik_kulunutaika] [nvarchar](100) NULL,
	[jarj_lis_koulala02] [nvarchar](10) NULL,
	[jarj_lis_koulala95] [nvarchar](10) NULL,
	[jarj_lis_opala] [nvarchar](10) NULL,
	[jarj_lis_koulnimike] [nvarchar](10) NULL,
	[jarj_lis_aiktutk] [nvarchar](50) NULL,
	[jarj_lis_kulunutaika] [nvarchar](100) NULL,
	[jarj_toht_koulala02] [nvarchar](10) NULL,
	[jarj_toht_koulala95] [nvarchar](10) NULL,
	[jarj_toht_opala] [nvarchar](10) NULL,
	[jarj_toht_koulnimike] [nvarchar](10) NULL,
	[jarj_toht_aiktutk] [nvarchar](50) NULL,
	[jarj_toht_kulunutaika] [nvarchar](100) NULL,
	[jarj_yliopisto_aiktutk] [nvarchar](50) NULL,
	[jarj_yojatko_aiktutk] [nvarchar](50) NULL,
	[jarj_opist_aiktutk] [nvarchar](50) NULL,
	[jarj_korkeakoulu_aiktutk] [nvarchar](50) NULL,
	[jarj_toinenaste_aiktutk] [nvarchar](50) NULL,
	[jarj_ammryhma1_aiktutk] [nvarchar](50) NULL,
	[jarj_ammryhma2_aiktutk] [nvarchar](50) NULL,
	[jarj_ammryhma3_aiktutk] [nvarchar](50) NULL,
	[jarj_samakoulutusala02_opisto] [nvarchar](10) NULL,
	[jarj_samakoulutusala02_ammka] [nvarchar](10) NULL,
	[jarj_samakoulutusala02_amk] [nvarchar](10) NULL,
	[jarj_samakoulutusala02_alempikk] [nvarchar](10) NULL,
	[jarj_samakoulutusala02_ylempiamk] [nvarchar](10) NULL,
	[jarj_samakoulutusala02_ylempikk] [nvarchar](10) NULL,
	[jarj_samakoulutusala02_laak] [nvarchar](10) NULL,
	[jarj_samakoulutusala02_lis] [nvarchar](10) NULL,
	[jarj_samakoulutusala02_toht] [nvarchar](10) NULL,
	[jarj_samakoulutusala02_yliopisto] [nvarchar](10) NULL,
	[jarj_samakoulutusala02_yojatko] [nvarchar](10) NULL,
	[jarj_samakoulutusala02_opistoammka] [nvarchar](10) NULL,
	[jarj_samakoulutusala02_korkeak] [nvarchar](10) NULL,
	[jarj_samakoulutusala02_toinenaste] [nvarchar](10) NULL,
	[jarj_samaopintoala02_lu] [nvarchar](10) NULL,
	[jarj_samaopintoala02_amm] [nvarchar](10) NULL,
	[jarj_samaopintoala02_opisto] [nvarchar](10) NULL,
	[jarj_samaopintoala02_ammka] [nvarchar](10) NULL,
	[jarj_samaopintoala02_amk] [nvarchar](10) NULL,
	[jarj_samaopintoala02_alempikk] [nvarchar](10) NULL,
	[jarj_samaopintoala02_ylempiamk] [nvarchar](10) NULL,
	[jarj_samaopintoala02_ylempikk] [nvarchar](10) NULL,
	[jarj_samaopintoala02_laak] [nvarchar](10) NULL,
	[jarj_samaopintoala02_lis] [nvarchar](10) NULL,
	[jarj_samaopintoala02_toht] [nvarchar](10) NULL,
	[jarj_samaopintoala02_yliopisto] [nvarchar](10) NULL,
	[jarj_samaopintoala02_yojatko] [nvarchar](10) NULL,
	[jarj_samaopintoala02_opistoammka] [nvarchar](10) NULL,
	[jarj_samaopintoala02_korkeak] [nvarchar](10) NULL,
	[jarj_samaopintoala02_toinenaste] [nvarchar](10) NULL,
	[jarj_samakoulutusala95_lu] [nvarchar](10) NULL,
	[jarj_samakoulutusala95_amm] [nvarchar](10) NULL,
	[jarj_samakoulutusala95_opisto] [nvarchar](10) NULL,
	[jarj_samakoulutusala95_ammka] [nvarchar](10) NULL,
	[jarj_samakoulutusala95_amk] [nvarchar](10) NULL,
	[jarj_samakoulutusala95_alempikk] [nvarchar](10) NULL,
	[jarj_samakoulutusala95_ylempiamk] [nvarchar](10) NULL,
	[jarj_samakoulutusala95_ylempikk] [nvarchar](10) NULL,
	[jarj_samakoulutusala95_laak] [nvarchar](10) NULL,
	[jarj_samakoulutusala95_lis] [nvarchar](10) NULL,
	[jarj_samakoulutusala95_toht] [nvarchar](10) NULL,
	[jarj_samakoulutusala95_yliopisto] [nvarchar](10) NULL,
	[jarj_samakoulutusala95_yojatko] [nvarchar](10) NULL,
	[jarj_samakoulutusala95_opistoammka] [nvarchar](10) NULL,
	[jarj_samakoulutusala95_korkeak] [nvarchar](10) NULL,
	[jarj_samakoulutusala95_toinenaste] [nvarchar](10) NULL,
	[jarj_samaiscbroad_lu] [nvarchar](10) NULL,
	[jarj_samaiscbroad_amm] [nvarchar](10) NULL,
	[jarj_samaiscbroad_opisto] [nvarchar](10) NULL,
	[jarj_samaiscbroad_ammka] [nvarchar](10) NULL,
	[jarj_samaiscbroad_amk] [nvarchar](10) NULL,
	[jarj_samaiscbroad_alempikk] [nvarchar](10) NULL,
	[jarj_samaiscbroad_ylempiamk] [nvarchar](10) NULL,
	[jarj_samaiscbroad_ylempikk] [nvarchar](10) NULL,
	[jarj_samaiscbroad_laak] [nvarchar](10) NULL,
	[jarj_samaiscbroad_lis] [nvarchar](10) NULL,
	[jarj_samaiscbroad_toht] [nvarchar](10) NULL,
	[jarj_samaiscbroad_yliopisto] [nvarchar](10) NULL,
	[jarj_samaiscbroad_yojatko] [nvarchar](10) NULL,
	[jarj_samaiscbroad_opistoammka] [nvarchar](10) NULL,
	[jarj_samaiscbroad_korkeak] [nvarchar](10) NULL,
	[jarj_samaiscbroad_toinenaste] [nvarchar](10) NULL,
	[jarj_samaiscnarrow_lu] [nvarchar](10) NULL,
	[jarj_samaiscnarrow_amm] [nvarchar](10) NULL,
	[jarj_samaiscnarrow_opisto] [nvarchar](10) NULL,
	[jarj_samaiscnarrow_ammka] [nvarchar](10) NULL,
	[jarj_samaiscnarrow_amk] [nvarchar](10) NULL,
	[jarj_samaiscnarrow_alempikk] [nvarchar](10) NULL,
	[jarj_samaiscnarrow_ylempiamk] [nvarchar](10) NULL,
	[jarj_samaiscnarrow_ylempikk] [nvarchar](10) NULL,
	[jarj_samaiscnarrow_laak] [nvarchar](10) NULL,
	[jarj_samaiscnarrow_lis] [nvarchar](10) NULL,
	[jarj_samaiscnarrow_toht] [nvarchar](10) NULL,
	[jarj_samaiscnarrow_yliopisto] [nvarchar](10) NULL,
	[jarj_samaiscnarrow_yojatko] [nvarchar](10) NULL,
	[jarj_samaiscnarrow_opistoammka] [nvarchar](10) NULL,
	[jarj_samaiscnarrow_korkeak] [nvarchar](10) NULL,
	[jarj_samaiscnarrow_toinenaste] [nvarchar](10) NULL,
	[Koodit Koulutusnimike] [nvarchar](6) NOT NULL,
	[Koodit Koulutusaste] [nvarchar](2) NOT NULL,
	[Koodit Koulutusala 02] [nvarchar](2) NOT NULL,
	[Koodit Koulutusala 95] [nvarchar](3) NOT NULL,
	[Koodit Opintoala] [nvarchar](3) NOT NULL,
	[Koodit Yo-tutkinnon koulutusnimike] [nvarchar](6) NOT NULL,
	[Koodit Amm. tutkinnon koulutusala] [nvarchar](2) NOT NULL,
	[Koodit Amm. tutkinnon opintoala] [nvarchar](3) NOT NULL,
	[Koodit Amm. tutkinnon koulutusnimike] [nvarchar](6) NOT NULL,
	[Koodit Opistoast. tutkinnon koulutusala] [nvarchar](2) NOT NULL,
	[Koodit Opistoast. tutkinnon opintoala] [nvarchar](3) NOT NULL,
	[Koodit Opistoast. tutkinnon koulutusnimike] [nvarchar](6) NOT NULL,
	[Koodit Amm. kork.asteen tutk. koulutusala] [nvarchar](2) NOT NULL,
	[Koodit Amm. kork.asteen tutk. opintoala] [nvarchar](3) NOT NULL,
	[Koodit Amm. kork.asteen tutk. koulutusnimike] [nvarchar](6) NOT NULL,
	[Koodit Amk-tutkinnon koulutusala] [nvarchar](2) NOT NULL,
	[Koodit Amk-tutkinnon opintoala] [nvarchar](3) NOT NULL,
	[Koodit Amk-tutkinnon koulutusnimike] [nvarchar](6) NOT NULL,
	[Koodit Alemman kk-tutk. koulutusala 02] [nvarchar](2) NOT NULL,
	[Koodit Alemman kk-tutk. koulutusala 95] [nvarchar](3) NOT NULL,
	[Koodit Alemman kk-tutk. opintoala] [nvarchar](3) NOT NULL,
	[Koodit Alemman kk-tutk. koulutusnimike] [nvarchar](6) NOT NULL,
	[Koodit Ylemmän amk-tutk. koulutusala] [nvarchar](2) NOT NULL,
	[Koodit Ylemmän amk-tutk. opintoala] [nvarchar](3) NOT NULL,
	[Koodit Ylemmän amk-tutk. koulutusnimike] [nvarchar](6) NOT NULL,
	[Koodit Ylemmän kk-tutk. koulutusala 02] [nvarchar](2) NOT NULL,
	[Koodit Ylemmän kk-tutk. koulutusala 95] [nvarchar](3) NOT NULL,
	[Koodit Ylemmän kk-tutk. opintoala] [nvarchar](3) NOT NULL,
	[Koodit Ylemmän kk-tutk. koulutusnimike] [nvarchar](6) NOT NULL,
	[Koodit Lääk. erikois.tutk. koulutusnimike] [nvarchar](6) NOT NULL,
	[Koodit Lisensiaatin tutk. koulutusala 02] [nvarchar](2) NOT NULL,
	[Koodit Lisensiaatin tutk. koulutusala 95] [nvarchar](3) NOT NULL,
	[Koodit Lisensiaatin tutk. opintoala] [nvarchar](3) NOT NULL,
	[Koodit Lisensiaatin tutk. koulutusnimike] [nvarchar](6) NOT NULL,
	[Koodit Tohtorin tutk. koulutusala 02] [nvarchar](2) NOT NULL,
	[Koodit Tohtorin tutk. koulutusala 95] [nvarchar](3) NOT NULL,
	[Koodit Tohtorin tutk. opintoala] [nvarchar](3) NOT NULL,
	[Koodit Tohtorin tutk. koulutusnimike] [nvarchar](6) NOT NULL,
	[rivinumero] [int] NULL,
	[Koulutusaste, taso 1] [nvarchar](255) NOT NULL,
	[Koulutusaste, taso 2] [nvarchar](255) NOT NULL,
	[Koulutusala, taso 1] [nvarchar](255) NOT NULL,
	[Koulutusala, taso 2] [nvarchar](255) NOT NULL,
	[Koulutusala, taso 3] [nvarchar](255) NOT NULL,
	[OKM ohjauksen ala] [nvarchar](255) NOT NULL,
	[jarj_isced_koulast1] [nvarchar](10) NULL,
	[jarj_isced_koulast2] [nvarchar](10) NULL,
	[jarj_isced_koulala1] [nvarchar](10) NULL,
	[jarj_isced_koulala2] [nvarchar](10) NULL,
	[jarj_isced_koulala3] [nvarchar](10) NULL,
	[jarj_isced_okmohjaus1] [nvarchar](10) NULL,
	[Koodit Koulutusaste, taso 1] [nvarchar](10) NOT NULL,
	[Koodit Koulutusaste, taso 2] [nvarchar](10) NOT NULL,
	[Koodit Koulutusala, taso 1] [nvarchar](10) NOT NULL,
	[Koodit Koulutusala, taso 2] [nvarchar](10) NOT NULL,
	[Koodit Koulutusala, taso 3] [nvarchar](10) NOT NULL,
	[Koodit OKM ohjauksen ala] [nvarchar](10) NOT NULL,
	[Yo-tutkinnon koulutusala 3] [nvarchar](255) NOT NULL,
	[Amm. tutkinnon koulutusala 1] [nvarchar](255) NOT NULL,
	[Amm. tutkinnon koulutusala 2] [nvarchar](255) NOT NULL,
	[Amm. tutkinnon koulutusala 3] [nvarchar](255) NOT NULL,
	[Opistoast. tutkinnon koulutusala 1] [nvarchar](255) NOT NULL,
	[Opistoast. tutkinnon koulutusala 2] [nvarchar](255) NOT NULL,
	[Opistoast. tutkinnon koulutusala 3] [nvarchar](255) NOT NULL,
	[Amm. kork.asteen tutk. koulutusala 1] [nvarchar](255) NOT NULL,
	[Amm. kork.asteen tutk. koulutusala 2] [nvarchar](255) NOT NULL,
	[Amm. kork.asteen tutk. koulutusala 3] [nvarchar](255) NOT NULL,
	[Amk-tutkinnon koulutusala 1] [nvarchar](255) NOT NULL,
	[Amk-tutkinnon OKM ohjauksen ala] [nvarchar](255) NOT NULL,
	[Amk-tutkinnon koulutusala 2] [nvarchar](255) NOT NULL,
	[Amk-tutkinnon koulutusala 3] [nvarchar](255) NOT NULL,
	[Alemman kk-tutk. koulutusala 1] [nvarchar](255) NOT NULL,
	[Alemman kk-tutk. OKM ohjauksen ala] [nvarchar](255) NOT NULL,
	[Alemman kk-tutk. koulutusala 2] [nvarchar](255) NOT NULL,
	[Alemman kk-tutk. koulutusala 3] [nvarchar](255) NOT NULL,
	[Ylemmän amk-tutk. koulutusala 1] [nvarchar](255) NOT NULL,
	[Ylemmän amk-tutk. OKM ohjauksen ala] [nvarchar](255) NOT NULL,
	[Ylemmän amk-tutk. koulutusala 2] [nvarchar](255) NOT NULL,
	[Ylemmän amk-tutk. koulutusala 3] [nvarchar](255) NOT NULL,
	[Ylemmän kk-tutk. koulutusala 1] [nvarchar](255) NOT NULL,
	[Ylemmän kk-tutk. OKM ohjauksen ala] [nvarchar](255) NOT NULL,
	[Ylemmän kk-tutk. koulutusala 2] [nvarchar](255) NOT NULL,
	[Ylemmän kk-tutk. koulutusala 3] [nvarchar](255) NOT NULL,
	[Lääk. erikois.tutk. koulutusala 3] [nvarchar](255) NOT NULL,
	[Lisensiaatin tutk. koulutusala 1] [nvarchar](255) NOT NULL,
	[Lisensiaatin tutk. OKM ohjauksen ala] [nvarchar](255) NOT NULL,
	[Lisensiaatin tutk. koulutusala 2] [nvarchar](255) NOT NULL,
	[Lisensiaatin tutk. koulutusala 3] [nvarchar](255) NOT NULL,
	[Tohtorin tutk. koulutusala 1] [nvarchar](255) NOT NULL,
	[Tohtorin tutk. OKM ohjauksen ala] [nvarchar](255) NOT NULL,
	[Tohtorin tutk. koulutusala 2] [nvarchar](255) NOT NULL,
	[Tohtorin tutk. koulutusala 3] [nvarchar](255) NOT NULL,
	[jarj_lukio_iscfi2013] [nvarchar](10) NULL,
	[jarj_amm_iscfibroad2013] [nvarchar](10) NULL,
	[jarj_amm_iscfinarrow2013] [nvarchar](10) NULL,
	[jarj_amm_iscfi2013] [nvarchar](10) NULL,
	[jarj_opisto_iscfibroad2013] [nvarchar](10) NULL,
	[jarj_opisto_iscfinarrow2013] [nvarchar](10) NULL,
	[jarj_opisto_iscfi2013] [nvarchar](10) NULL,
	[jarj_amm_kork_aste_iscfibroad2013] [nvarchar](10) NULL,
	[jarj_amm_kork_aste_iscfinarrow2013] [nvarchar](10) NULL,
	[jarj_amm_kork_aste_iscfi2013] [nvarchar](10) NULL,
	[jarj_amk_iscfibroad2013] [nvarchar](10) NULL,
	[jarj_amk_OKM_ohjauksen_ala] [nvarchar](10) NULL,
	[jarj_amk_iscfinarrow2013] [nvarchar](10) NULL,
	[jarj_amk_iscfi2013] [nvarchar](10) NULL,
	[jarj_alempi_kk_iscfibroad2013] [nvarchar](10) NULL,
	[jarj_alempi_kk_OKM_ohjauksen_ala] [nvarchar](10) NULL,
	[jarj_alempi_kk_iscfinarrow2013] [nvarchar](10) NULL,
	[jarj_alempi_kk_iscfi2013] [nvarchar](10) NULL,
	[jarj_ylempi_amk_iscfibroad2013] [nvarchar](10) NULL,
	[jarj_ylempi_amk_OKM_ohjauksen_ala] [nvarchar](10) NULL,
	[jarj_ylempi_amk_iscfinarrow2013] [nvarchar](10) NULL,
	[jarj_ylempi_amk_iscfi2013] [nvarchar](10) NULL,
	[jarj_ylempi_kk_iscfibroad2013] [nvarchar](10) NULL,
	[jarj_ylempi_kk_OKM_ohjauksen_ala] [nvarchar](10) NULL,
	[jarj_ylempi_kk_iscfinarrow2013] [nvarchar](10) NULL,
	[jarj_ylempi_kk_iscfi2013] [nvarchar](10) NULL,
	[jarj_laak_erik_iscfi2013] [nvarchar](10) NULL,
	[jarj_lis_iscfibroad2013] [nvarchar](10) NULL,
	[jarj_lis_OKM_ohjauksen_ala] [nvarchar](10) NULL,
	[jarj_lis_iscfinarrow2013] [nvarchar](10) NULL,
	[jarj_lis_iscfi2013] [nvarchar](10) NULL,
	[jarj_toht_iscfibroad2013] [nvarchar](10) NULL,
	[jarj_toht_OKM_ohjauksen_ala] [nvarchar](10) NULL,
	[jarj_toht_iscfinarrow2013] [nvarchar](10) NULL,
	[jarj_toht_iscfi2013] [nvarchar](10) NULL,
	[Koodit Yo-tutkinnon koulutusala 3] [nvarchar](10) NOT NULL,
	[Koodit Amm. tutkinnon koulutusala 1] [nvarchar](10) NOT NULL,
	[Koodit Amm. tutkinnon koulutusala 2] [nvarchar](10) NOT NULL,
	[Koodit Amm. tutkinnon koulutusala 3] [nvarchar](10) NOT NULL,
	[Koodit Opistoast. tutkinnon koulutusala 1] [nvarchar](10) NOT NULL,
	[Koodit Opistoast. tutkinnon koulutusala 2] [nvarchar](10) NOT NULL,
	[Koodit Opistoast. tutkinnon koulutusala 3] [nvarchar](10) NOT NULL,
	[Koodit Amm. kork.asteen tutk. koulutusala 1] [nvarchar](10) NOT NULL,
	[Koodit Amm. kork.asteen tutk. koulutusala 2] [nvarchar](10) NOT NULL,
	[Koodit Amm. kork.asteen tutk. koulutusala 3] [nvarchar](10) NOT NULL,
	[Koodit Amk-tutkinnon koulutusala 1] [nvarchar](10) NOT NULL,
	[Koodit Amk-tutkinnon OKM ohjauksen ala] [nvarchar](10) NOT NULL,
	[Koodit Amk-tutkinnon koulutusala 2] [nvarchar](10) NOT NULL,
	[Koodit Amk-tutkinnon koulutusala 3] [nvarchar](10) NOT NULL,
	[Koodit Alemman kk-tutk. koulutusala 1] [nvarchar](10) NOT NULL,
	[Koodit Alemman kk-tutk. OKM ohjauksen ala] [nvarchar](10) NOT NULL,
	[Koodit Alemman kk-tutk. koulutusala 2] [nvarchar](10) NOT NULL,
	[Koodit Alemman kk-tutk. koulutusala 3] [nvarchar](10) NOT NULL,
	[Koodit Ylemmän amk-tutk. koulutusala 1] [nvarchar](10) NOT NULL,
	[Koodit Ylemmän amk-tutk. OKM ohjauksen ala] [nvarchar](10) NOT NULL,
	[Koodit Ylemmän amk-tutk. koulutusala 2] [nvarchar](10) NOT NULL,
	[Koodit Ylemmän amk-tutk. koulutusala 3] [nvarchar](10) NOT NULL,
	[Koodit Ylemmän kk-tutk. koulutusala 1] [nvarchar](10) NOT NULL,
	[Koodit Ylemmän kk-tutk. OKM ohjauksen ala] [nvarchar](10) NOT NULL,
	[Koodit Ylemmän kk-tutk. koulutusala 2] [nvarchar](10) NOT NULL,
	[Koodit Ylemmän kk-tutk. koulutusala 3] [nvarchar](10) NOT NULL,
	[Koodit Lääk. erikois.tutk. koulutusala 3] [nvarchar](10) NOT NULL,
	[Koodit Lisensiaatin tutk. koulutusala 1] [nvarchar](10) NOT NULL,
	[Koodit Lisensiaatin tutk. OKM ohjauksen ala] [nvarchar](10) NOT NULL,
	[Koodit Lisensiaatin tutk. koulutusala 2] [nvarchar](10) NOT NULL,
	[Koodit Lisensiaatin tutk. koulutusala 3] [nvarchar](10) NOT NULL,
	[Koodit Tohtorin tutk. koulutusala 1] [nvarchar](10) NOT NULL,
	[Koodit Tohtorin tutk. OKM ohjauksen ala] [nvarchar](10) NOT NULL,
	[Koodit Tohtorin tutk. koulutusala 2] [nvarchar](10) NOT NULL,
	[Koodit Tohtorin tutk. koulutusala 3] [nvarchar](10) NOT NULL
) ON [PRIMARY]

GO


