USE [ANTERO]
GO

/****** Object:  StoredProcedure [dw].[p_lataa_f_eter_revenue]    Script Date: 27.4.2022 11:09:08 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER PROCEDURE [dw].[p_lataa_f_eter_revenue] AS

TRUNCATE TABLE dw.f_eter_revenue

INSERT INTO ANTERO.dw.f_eter_revenue (
	   [ETER_ID]
      ,[Basic government allocation (NC)]
      ,[Basic government allocation (PPP)]
      ,[Basic government allocation (EURO)]
      ,[Other core budget (EURO)]
      ,[Other core budget (NC)]
      ,[Other core budget (PPP)]
      ,[Total core budget (PPP)]
      ,[Total core budget (EURO)]
      ,[Total core budget (NC)]
      ,[Flag Public third party funding]
      ,[Flag other core budget]
      ,[Public third party funding (NC)]
      ,[Public third party funding (PPP)]
      ,[Public third party funding (EURO)]
      ,[Flag Total core budget]
      ,[Third party funding from abroad (NC)]
      ,[Third party funding from abroad (PPP)]
      ,[Third party funding from abroad (EURO)]
      ,[Third party funding undivided (EURO)]
      ,[Third party funding undivided (NC)]
      ,[Third party funding undivided (PPP)]
      ,[Flag Private third party funding]
      ,[Private third party funding (NC)]
      ,[Private third party funding (EURO)]
      ,[Private third party funding (PPP)]
      ,[Total third party funding (PPP)]
      ,[Total third party funding (EURO)]
      ,[Total third party funding (NC)]
      ,[Student fees funding (PPP)]
      ,[Student fees funding (EURO)]
      ,[Student fees funding (NC)]
      ,[Flag Third party funding undivided]
      ,[Flag Revenue unclassified]
      ,[Tuition fees]
      ,[Flag Total third party funding]
      ,[Revenue unclassified (NC)]
      ,[Revenue unclassified (PPP)]
      ,[Revenue unclassified (EURO)]
      ,[Non-recurring revenues (NC)]
      ,[Non-recurring revenues (PPP)]
      ,[Non-recurring revenues (EURO)]
      ,[Flag Student fees funding]
      ,[Total Current revenues (EURO)]
      ,[Total Current revenues (NC)]
      ,[Total Current revenues (PPP)]
      ,[Flag Total current revenues]
      ,[Notes on revenues]
      ,[Flag Basic government allocationt]
      ,[Flag Third party funding abroad]
      ,[Flag Non-recurring revenues]
      ,[username]
      ,[source]
      ,[loadtime])
SELECT
	   [ETER_ID]
      ,[Basic government allocation (NC)]
      ,[Basic government allocation (PPP)]
      ,[Basic government allocation (EURO)]
      ,[Other core budget (EURO)]
      ,[Other core budget (NC)]
      ,[Other core budget (PPP)]
      ,[Total core budget (PPP)]
      ,[Total core budget (EURO)]
      ,[Total core budget (NC)]
      ,[Flag Public third party funding]
      ,[Flag other core budget]
      ,[Public third party funding (NC)]
      ,[Public third party funding (PPP)]
      ,[Public third party funding (EURO)]
      ,[Flag Total core budget]
      ,[Third party funding from abroad (NC)]
      ,[Third party funding from abroad (PPP)]
      ,[Third party funding from abroad (EURO)]
      ,[Third party funding undivided (EURO)]
      ,[Third party funding undivided (NC)]
      ,[Third party funding undivided (PPP)]
      ,[Flag Private third party funding]
      ,[Private third party funding (NC)]
      ,[Private third party funding (EURO)]
      ,[Private third party funding (PPP)]
      ,[Total third party funding (PPP)]
      ,[Total third party funding (EURO)]
      ,[Total third party funding (NC)]
      ,[Student fees funding (PPP)]
      ,[Student fees funding (EURO)]
      ,[Student fees funding (NC)]
      ,[Flag Third party funding undivided]
      ,[Flag Revenue unclassified]
      ,[Tuition fees]
      ,[Flag Total third party funding]
      ,[Revenue unclassified (NC)]
      ,[Revenue unclassified (PPP)]
      ,[Revenue unclassified (EURO)]
      ,[Non-recurring revenues (NC)]
      ,[Non-recurring revenues (PPP)]
      ,[Non-recurring revenues (EURO)]
      ,[Flag Student fees funding]
      ,[Total Current revenues (EURO)]
      ,[Total Current revenues (NC)]
      ,[Total Current revenues (PPP)]
      ,[Flag Total current revenues]
      ,[Notes on revenues]
      ,[Flag Basic government allocationt]
      ,[Flag Third party funding abroad]
      ,[Flag Non-recurring revenues]
	  ,SUSER_NAME()
	  ,'ETL: p_lataa_f_eter_revenue' 
	  ,getdate()
FROM [ANTERO].[sa].[sa_eter_revenue]

GO

USE [ANTERO]