IF EXISTS (select * from INFORMATION_SCHEMA.TABLES where TABLE_SCHEMA='sa' and TABLE_NAME='sa_suorat_hist_amk3_julkaisut_a_e') BEGIN

DROP TABLE sa.sa_suorat_hist_amk3_julkaisut_a_e;

CREATE TABLE [sa].[sa_suorat_hist_amk3_julkaisut_a_e](
	[AMK_TUNNUS] [varchar](5) NULL,
	[KOULUTUSALA_KOODI] [varchar](5) NULL,
	[VUOSI] [int] NULL,
	[TIETEENALA_KOODI_10] [varchar](4) NULL,
	[PAATIETEENALA_KOODI_10] [varchar](2) NULL,
	[TIETEENALA_KOODI_07] [varchar](4) NULL,
	[PAATIETEENALA_KOODI_07] [varchar](2) NULL,
	[JULKAISUTYYPPI_KOODI] [varchar](3) NULL,
	[KANSAINVALISYYS_KOODI] [int] NULL,
	[OPEN_ACCESS_KOODI] [int] NULL,
	[JULKAISUN_PAALUOKKA_KOODI] [varchar](2) NULL,
	[JUFO_KOODI] [varchar](2) NULL,
	[KV_YHTEISJULKAISU_KOODI] [int] NULL,
	[EVO_KOODI] [int] NULL,
	[YLIOPISTOLLINEN_SAIRAANHOITOPIIRI_YHTEISJULKAISU_KOODI] [varchar](2) NULL,
	[VALTION_SEKTORITUTKIMUSLAITOS_YHTEISJULKAISU_KOODI] [varchar](2) NULL,
	[MUU_KOTIMAINEN_TUTKIMUSORGANISAATIO_YHTEISJULKAISU_KOODI] [varchar](2) NULL,
	[JULKAISUJEN_LKM] [int] NULL,
	[IMP_CREATED_BY] [varchar](100) NULL,
	[IMP_CREATED_DATE] [datetime] NULL
) ;

END