USE ANTERO
GO

IF NOT EXISTS (
  SELECT * FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = 'sa' AND TABLE_NAME = 'sa_kouta_haku' AND COLUMN_NAME = 'source')
BEGIN
     ALTER TABLE [sa].[sa_kouta_haku] ALTER COLUMN	[source] [varchar](255) NULL;
END
