USE [ANTERO]
GO

/****** Object:  View [dw].[v_eter]    Script Date: 28.8.2023 11:29:23 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER   view [dw].[v_eter] AS

SELECT

	-- Basic info
	f1.ETER_ID,
	f1.[Reference year] as 'Year',
	f1.[Foundation year],
	f1.[ETER ID] as 'Organisation id',
	coalesce([English Institution Name], f1.[Institution Name]) as 'Higher education institution',
	coalesce(d2.Value, 'Missing data') as 'Institution category',
	coalesce(f1.[Institution Category - English], 'Missing data') as 'Institution category - English',
	coalesce(d3.Value, 'Missing data') as 'Institution type',
	coalesce(d4.Value, 'Missing data') as 'Highest degree delivered',
	coalesce(d5.Value, 'Missing data') as 'Lowest degree delivered',
	coalesce(d6.Value, 'Missing data') as 'Distance education institution',
	coalesce(d7.Value, 'Missing data') as 'Tuition fees',

	f1.[Country Code],
	CASE 
		WHEN f1.[Country Code] = 'GR' THEN 'Greece'
		WHEN f1.[Country Code] = 'VA' THEN 'Vatican City'
		WHEN f1.[Country Code] = 'XK' THEN 'Kosovo'
		WHEN f1.[Country Code] = 'AD' THEN 'Andorra'
		WHEN f1.[Country Code] = 'DE' THEN 'Germany'
		WHEN f1.[Country Code] = 'LU' THEN 'Luxembourg'
		WHEN f1.[Country Code] = 'MT' THEN 'Malta'
		WHEN f1.[Country Code] = 'LI' THEN 'Liechtenstein'
		ELSE d1.[GEO_LABEL] 
	END as Country,
	coalesce(f4.[Name of the city], 'Missing data') as City,

	-- Erasmus
	f2.[Erasmus incoming students - ISCED 7],
	f2.[Erasmus outgoing students - ISCED 6],
	f2.[Erasmus incoming staff],
	f2.[Erasmus incoming students - ISCED 8],
	f2.[Erasmus outgoing students - ISCED 7],
	f2.[Erasmus outgoing staff],
	f2.[Erasmus incoming students - ISCED 6],
	f2.[Erasmus incoming students (other)],
	f2.[Erasmus outgoing students - ISCED 5],
	f2.[Erasmus outgoing students - ISCED 8],
	f2.[Erasmus total outgoing students],
	f2.[Erasmus incoming students - ISCED 5],
	f2.[Erasmus total incoming students],
	f2.[Erasmus outgoing students (other)],

	-- Expenditure
	f3.[Personnel expenditure (EURO)],
	f3.[Non-personnel expenditure (EURO)],
	f3.[Total Current expenditure (EURO)],
	f3.[Expenditure unclassified (EURO)],
	f3.[Capital expenditure (EURO)]

	-- Graduates

	,f5.[Graduates at ISCED 5 - men]
	,f5.[Graduates at ISCED 5 - foreigner]
	,f5.[Graduates at ISCED 5 - women]
	,f5.[Graduates at ISCED 5 - mobility unclassified]
	,f5.[Graduates at ISCED 5 - citizenship unclassified]
	,f5.[Graduates at ISCED 5 - Social sciences, journalism and information]
	,f5.[Graduates at ISCED 5 - Agriculture, forestry, fisheries and veterinary]
	,f5.[Graduates at ISCED 5 - Business, administration and law]
	,f5.[Graduates at ISCED 5 - under 20 years old]
	,f5.[Graduates at ISCED 5 - Health and welfare]
	,f5.[Graduates at ISCED 5 - Age goup unclassified]
	,f5.[Graduates at ISCED 6 - men]
	,f5.[Graduates at ISCED 5 - resident]
	,f5.[Graduates at ISCED 6 - foreigner]
	,f5.[Graduates at ISCED 5 - Education]
	,f5.[Graduates at ISCED 6 - women]
	,f5.[Graduates at ISCED 6 - mobility unclassified]
	,f5.[Graduates at ISCED 5 - gender unclassified]
	,f5.[Graduates at ISCED 5 - Information and Communication Technologies]
	,f5.[Graduates at ISCED 5 - ISCED-FoE unclassified]
	,f5.[Graduates at ISCED 6 - Social sciences, journalism and information]
	,f5.[Graduates at ISCED 5 - between 25 and 29 years old]
	,f5.[Graduates at ISCED 6 - Agriculture, forestry, fisheries and veterinary]
	,f5.[Graduates at ISCED 6 - citizenship unclassified]
	,f5.[Graduates at ISCED 6 - under 20 years old]
	,f5.[Graduates at ISCED 6 - Business, administration and law]
	,f5.[Graduates at ISCED 6 - Age goup unclassified]
	,f5.[Graduates at ISCED 5 - Generic programmes and qualifications]
	,f5.[Graduates at ISCED 5 - Natural sciences, mathematics and statistics]
	,f5.[Graduates at ISCED 6 - Health and welfare]
	,f5.[Graduates at ISCED 7 - men]
	,f5.[Graduates at ISCED 6 - resident]
	,f5.[Graduates at ISCED 5 - Services]
	,f5.[Graduates at ISCED 7 - foreigner]
	,f5.[Graduates at ISCED 5 - between 22 and 24 years old]
	,f5.[Graduates at ISCED 6 - Education]
	,f5.[Total graduates at ISCED 5]
	,f5.[Graduates at ISCED 6 - Information and Communication Technologies]
	,f5.[Graduates at ISCED 6 - ISCED-FoE unclassified]
	,f5.[Graduates at ISCED 6 - between 25 and 29 years old]
	,f5.[Graduates at ISCED 7 - mobility unclassified]
	,f5.[Graduates at ISCED 7 - Social sciences, journalism and information]
	,f5.[Graduates at ISCED 6 - gender unclassified]
	,f5.[Graduates at ISCED 7 - women]
	,f5.[Graduates at ISCED 7 - citizenship unclassified]
	,f5.[Graduates at ISCED 6 - Generic programmes and qualifications]
	,f5.[Graduates at ISCED 7 - resident]
	,f5.[Graduates at ISCED 7 - Agriculture, forestry, fisheries and veterinary]
	,f5.[Graduates at ISCED 6 - Natural sciences, mathematics and statistics]
	,f5.[Graduates at ISCED 6 - Services]
	,f5.[Graduates at ISCED 7 - Education]
	,f5.[Graduates at ISCED 6 - between 22 and 24 years old]
	,f5.[Graduates at ISCED 7 - under 20 years old]
	,f5.[Graduates at ISCED 7 - Information and Communication Technologies]
	,f5.[Total graduates at ISCED 6]
	,f5.[Graduates at ISCED 7 - gender unclassified]
	,f5.[Graduates at ISCED 7 - Business, administration and law]
	,f5.[Graduates at ISCED 7 - Age goup unclassified]
	,f5.[Graduates at ISCED 5 - national]
	,f5.[Graduates at ISCED 7 long degree - men]
	,f5.[Graduates at ISCED 7 - ISCED-FoE unclassified]
	,f5.[Graduates at ISCED 7 - Generic programmes and qualifications]
	,f5.[Graduates at ISCED 7 - between 25 and 29 years old]
	,f5.[Graduates at ISCED 7 - Natural sciences, mathematics and statistics]
	,f5.[Graduates at ISCED 7 - Health and welfare]
	,f5.[Graduates at ISCED 7 - Services]
	,f5.[Graduates at ISCED 5 - mobile]
	,f5.[Graduates at ISCED 7 long degree - foreigner]
	,f5.[Graduates at ISCED 7 - between 22 and 24 years old]
	,f5.[Graduates at ISCED 5 - Arts and Humanities]
	,f5.[Total graduates at ISCED 7]
	,f5.[Graduates at ISCED 5 - Engineering, manufacturing and construction]
	,f5.[Graduates ISCED7 long degree-mobility unclassified]
	,f5.[Graduates ISCED 7 long degree-gender unclassified]
	,f5.[Graduates at ISCED 7 long degree - Social sciences, journalism and information]
	,f5.[Graduates at ISCED 7 long degree - Generic programmes and qualifications]
	,f5.[Graduates at ISCED 7 long degree - Agriculture, forestry, fisheries and veterinary]
	,f5.[Graduates at ISCED 7 long degree - women]
	,f5.[Graduates at ISCED 7 long degree - Natural sciences, mathematics and statistics]
	,f5.[Graduates at ISCED 7 long degree - resident]
	,f5.[Graduates at ISCED 7 long degree - Services]
	,f5.[Graduates ISCED 7 long degree-citiz. unclassified]
	,f5.[Graduates at ISCED 7 long degree - under 20 years old]
	,f5.[Graduates at ISCED 5 - over 29 years old]
	,f5.[Graduates at ISCED 7 long degree - Education]
	,f5.[Graduates at ISCED 7 long degree - Age goup unclassified]
	,f5.[Graduates at ISCED 7 long degree - between 22 and 24 years old]
	,f5.[Graduates at ISCED 5-7 - men]
	,f5.[Total graduates at ISCED 7 long degree]
	,f5.[Graduates at ISCED 7 long degree - Business, administration and law]
	,f5.[Graduates at ISCED 5-7 - foreigner]
	,f5.[Graduates at ISCED 6 - national]
	,f5.[Graduates at ISCED 5-7 - gender unclassified]
	,f5.[Graduates at ISCED 7 long degree - Health and welfare]
	,f5.[Graduates at ISCED 6 - mobile]
	,f5.[Graduates at ISCED 7 long degree - Information and Communication Technologies]
	,f5.[Graduates at ISCED 5-7 - mobility unclassified]
	,f5.[Graduates at ISCED 5-7 - Generic programmes and qualifications]
	,f5.[Graduates at ISCED 5-7 - Natural sciences, mathematics and statistics]
	,f5.[Graduates ISCED7 long degree-ISCED-FoE unclassified]
	,f5.[Graduates at ISCED 5-7 - Services]
	,f5.[Graduates at ISCED 7 long degree - between 25 and 29 years old]
	,f5.[Graduates at ISCED 5-7 - between 22 and 24 years old]
	,f5.[Graduates at ISCED 5-7 - Social sciences, journalism and information]
	,f5.[Graduates at ISCED 6 - Arts and Humanities]
	,f5.[Total graduates ISCED 5-7]
	,f5.[Graduates at ISCED 5-7 - women]
	,f5.[Graduates at ISCED 6 - Engineering, manufacturing and construction]
	,f5.[Graduates at ISCED 5-7 - resident]
	,f5.[Graduates at ISCED 5-7 - Agriculture, forestry, fisheries and veterinary]
	,f5.[Graduates at ISCED 5-7 - Education]
	,f5.[Graduates at ISCED 5-7 - under 20 years old]
	,f5.[Graduates at ISCED 5-7 - Information and Communication Technologies]
	,f5.[Graduates at ISCED 5-7 - citizenship unclassified]
	,f5.[Graduates at ISCED 6 - over 29 years old]
	,f5.[Graduates at ISCED 5-7 - Business, administration and law]
	,f5.[Graduates at ISCED 5-7 - Age goup unclassified]
	,f5.[Graduates at ISCED 5-7 - ISCED-FoE unclassified]
	,f5.[Graduates at ISCED 5-7 - Health and welfare]
	,f5.[Graduates at ISCED 7 - national]
	,f5.[Graduates at ISCED 5-7 - between 25 and 29 years old]
	,f5.[Graduates at ISCED 7 - mobile]
	,f5.[Graduates at ISCED 7 - Arts and Humanities]
	,f5.[Graduates at ISCED 7 - Engineering, manufacturing and construction]
	,f5.[Graduates at ISCED 7 - over 29 years old]
	,f5.[Graduates at ISCED 7 long degree - national]
	,f5.[Graduates at ISCED 7 long degree - mobile]
	,f5.[Graduates at ISCED 7 long degree - Arts and Humanities]
	,f5.[Graduates at ISCED 7 long degree - Engineering, manufacturing and construction]
	,f5.[Graduates at ISCED 7 long degree - over 29 years old]
	,f5.[Graduates at ISCED 5-7 - national]
	,f5.[Graduates at ISCED 5-7 - mobile]
	,f5.[Graduates at ISCED 5-7 - Arts and Humanities]
	,f5.[Graduates at ISCED 5-7 - Engineering, manufacturing and construction]
	,f5.[Graduates at ISCED 5-7 - over 29 years old]

	-- Research
	,f6.[Students enrolled at ISCED 8 - men]
	,f6.[Students enrolled at ISCED 8 - foreigner]
	,f6.[Students enrolled ISCED 8-mobility unclassified]
	,f6.[Students enrolled at ISCED 8 - Social sciences, journalism and information]
	,f6.[Students enrolled at ISCED 8 - Agriculture, forestry, fisheries and veterinary]
	,f6.[Students enrolled at ISCED 8 - part-time]
	,f6.[Research active institution]
	,f6.[Students enrolled at ISCED 8 - national]
	,f6.[Students enrolled at ISCED 8 - resident]
	,f6.[Graduates at ISCED 8 - women]
	,f6.[Students enrolled at ISCED 8 - women]
	,f6.[Graduates at ISCED 8 - citizenship unclassified]
	,f6.[Students enrolled at ISCED 8 - Education]
	,f6.[Students enrolled ISCED 8-citizenship unclassified]
	,f6.[Graduates at ISCED 8 - Business, administration and law]
	,f6.[Students enrolled at ISCED 8 - mobile]
	,f6.[Graduates at ISCED 8 - Health and welfare]
	,f6.[Students enrolled at ISCED 8 - Arts and Humanities]
	,f6.[Students enrolled at ISCED 8 - Engineering, manufacturing and construction]
	,f6.[Students enrolled at ISCED 8 - Information and Communication Technologies]
	,f6.[Students enrolled at ISCED 8 - under 20 years old]
	,f6.[Students enrolled at ISCED 8 - Business, administration and law]
	,f6.[Students enrolled ISCED 8 - ISCED-FoE unclassified]
	,f6.[Students enrolled at ISCED 8 - Age goup unclassified]
	,f6.[R&D Expenditure (EURO)]
	,f6.[Graduates at ISCED 8 - men]
	,f6.[Graduates at ISCED 8 - foreigner]
	,f6.[Graduates at ISCED 8 - mobility unclassified]
	,f6.[Graduates at ISCED 8 - Social sciences, journalism and information]
	,f6.[Graduates at ISCED 8 - Agriculture, forestry, fisheries and veterinary]
	,f6.[Students enrolled at ISCED 8 - Health and welfare]
	,f6.[Students enrolled at ISCED 8 - over 29 years old]
	,f6.[Graduates at ISCED 8 - under 20 years old]
	,f6.[Graduates at ISCED 8 - Age goup unclassified]
	,f6.[Included in official R&D statistics]
	,f6.[Students enrolled at ISCED 8 - full-time]
	,f6.[Notes on students enrolled at ISCED 8]
	,f6.[Students enrolled at ISCED 8 - between 22 and 24 years old]
	,f6.[Graduates at ISCED 8 - national]
	,f6.[Total students enrolled at ISCED 8]
	,f6.[Graduates at ISCED 8 - mobile]
	,f6.[Graduates at ISCED 8 - gender unclassified]
	,f6.[Graduates at ISCED 8 - Arts and Humanities]
	,f6.[Graduates at ISCED 8 - Engineering, manufacturing and construction]
	,f6.[Graduates at ISCED 8 - Generic programmes and qualifications]
	,f6.[Graduates at ISCED 8 - Natural sciences, mathematics and statistics]
	,f6.[Graduates at ISCED 8 - over 29 years old]
	,f6.[Graduates at ISCED 8 - Services]
	,f6.[Graduates at ISCED 8 - between 22 and 24 years old]
	,f6.[Total graduates at ISCED 8]
	,f6.[Students enrolled ISCED 8 - gender unclassified]
	,f6.[Students enrolled at ISCED 8 - Generic programmes and qualifications]
	,f6.[Students enrolled at ISCED 8 - Natural sciences, mathematics and statistics]
	,f6.[Students enrolled at ISCED 8 - Services]
	,f6.[Students enrolled at ISCED 8 - part-, full-time unclassified]
	,f6.[Students enrolled at ISCED 8 - between 25 and 29 years old]
	,f6.[Graduates at ISCED 8 - resident]
	,f6.[Graduates at ISCED 8 - Education]
	,f6.[Graduates at ISCED 8 - Information and Communication Technologies]
	,f6.[Graduates at ISCED 8 - ISCED-FoE unclassified]
	,f6.[Graduates at ISCED 8 - between 25 and 29 years old]
	,f6.[EU-FP Staff mobility]
	,f6.[EU-FP Researchers mobility]
	,f6.[EU-FP Research training cooperation]

	-- Revenue
	,f7.[Basic government allocation (EURO)]
	,f7.[Other core budget (EURO)]
	,f7.[Total core budget (EURO)]
	,f7.[Public third party funding (EURO)]
	,f7.[Third party funding from abroad (EURO)]
	,f7.[Third party funding undivided (EURO)]
	,f7.[Private third party funding (EURO)]
	,f7.[Total third party funding (EURO)]
	,f7.[Student fees funding (EURO)]
	,f7.[Revenue unclassified (EURO)]
	,f7.[Non-recurring revenues (EURO)]
	,f7.[Total Current revenues (EURO)]
	,f7.[Total Current revenues (NC)]
	,f7.[Total Current revenues (PPP)]

	-- Staff
	,f8.[Total academic personnel (FTE)]
	,f8.[Academic personnel - Generic programmes and qualifications (HC)]
	,f8.[Academic personnel - men (HC)]
	,f8.[Academic personnel - gender unclassified (HC)]
	,f8.[Academic personnel - Natural sciences, mathematics and statistics (HC)]
	,f8.[Academic personnel - foreigner (HC)]
	,f8.[Academic personnel - national (HC)]
	,f8.[Academic personnel - Arts and Humanities (HC)]
	,f8.[Academic personnel - Business, administration and law (HC)]
	,f8.[Academic personnel - Services (HC)]
	,f8.[Academic personnel - Education (HC)]
	,f8.[Academic personnel - Engineering, manufacturing and construction (HC)]
	,f8.[Academic personnel - Health and welfare (HC)]
	,f8.[Number of full professors - men]
	,f8.[Academic personnel - Information and Communication Technologies (HC)]
	,f8.[Number of research and teaching assistants (FTE)]
	,f8.[Number of full professors - unclassified]
	,f8.[Academic personnel - ISCED-FoE unclassified]
	,f8.[Number of support and administrative personnel (FTE)]
	,f8.[Number of research and teaching assistants (HC)]
	,f8.[Number of full professors - women]
	,f8.[Total personnel (FTE)]
	,f8.[Number of support and administrative personnel (HC)]
	,f8.[Notes on support and administrative personnel]
	,f8.[Total personnel (HC)]
	,f8.[Academic personnel - women (HC)]
	,f8.[Academic personnel - citizenship unclassified]
	,f8.[Academic personnel - Social sciences, journalism and information (HC)]
	,f8.[Academic personnel - Agriculture, forestry, fisheries and veterinary (HC)]
	,f8.[Total academic personnel (HC)]
	,f8.[Total number of full professors]

	-- Students
	,f9.[Students enrolled at ISCED 5 - men]
	,f9.[Students enrolled at ISCED 5 - resident]
	,f9.[Students enrolled at ISCED 5 - gender unclassified]
	,f9.[Students enrolled at ISCED 5 - Education]
	,f9.[Students enrolled at ISCED 5 - foreigner]
	,f9.[Students enrolled at ISCED 5 - Information and Communication Technologies]
	,f9.[Students enrolled at ISCED 5 - national]
	,f9.[Students enrolled at ISCED 5 - Generic programmes and qualifications]
	,f9.[Students enrolled at ISCED 5-mobility unclassified]
	,f9.[Students enrolled at ISCED 5-ISCED-FoE unclassified]
	,f9.[Students enrolled at ISCED 5 - Natural sciences, mathematics and statistics]
	,f9.[Students enrolled at ISCED 5 - mobile]
	,f9.[Students enrolled at ISCED 5 - Social sciences, journalism and information]
	,f9.[Students enrolled at ISCED 5 - Services]
	,f9.[Students enrolled at ISCED 5 - Arts and Humanities]
	,f9.[Students enrolled at ISCED 5 - Agriculture, forestry, fisheries and veterinary]
	,f9.[Students enrolled at ISCED 5 - over 29 years old]
	,f9.[Students enrolled at ISCED 5 - Engineering, manufacturing and construction]
	,f9.[Students enrolled at ISCED 5 - part-, full-time unclassified]
	,f9.[Students enrolled at ISCED 5 - between 25 and 29 years old]
	,f9.[Students enrolled at ISCED 5 - part-time]
	,f9.[Students enrolled at ISCED 5 - under 20 years old]
	,f9.[Students enrolled at ISCED 6 - national]
	,f9.[Students enrolled at ISCED 6 - mobile]
	,f9.[Students enrolled at ISCED 5 - Age goup unclassified]
	,f9.[Students enrolled at ISCED 6 - Arts and Humanities]
	,f9.[Students enrolled at ISCED 6 - resident]
	,f9.[Students enrolled at ISCED 6 - men]
	,f9.[Students enrolled at ISCED 6 - women]
	,f9.[Students enrolled at ISCED 6 - Engineering, manufacturing and construction]
	,f9.[Students enrolled at ISCED 6 - Education]
	,f9.[Students at ISCED 6-citizenship unclassified]
	,f9.[Students enrolled at ISCED 6 - foreigner]
	,f9.[Students enrolled at ISCED 6 - Information and Communication Technologies]
	,f9.[Students at ISCED 6 - mobility unclassified]
	,f9.[Students enrolled at ISCED 6 - under 20 years old]
	,f9.[Students at ISCED 6 - ISCED-FoE unclassified]
	,f9.[Students enrolled at ISCED 6 - Social sciences, journalism and information]
	,f9.[Students enrolled at ISCED 6 - Age goup unclassified]
	,f9.[Students enrolled at ISCED 6 - Business, administration and law]
	,f9.[Students enrolled at ISCED 7 - men]
	,f9.[Students enrolled at ISCED 6 - Health and welfare]
	,f9.[Students enrolled at ISCED 6 - Agriculture, forestry, fisheries and veterinary]
	,f9.[Students enrolled at ISCED 6 - over 29 years old]
	,f9.[Students enrolled at ISCED 6 - full-time]
	,f9.[Students enrolled at ISCED 7 - foreigner]
	,f9.[Students enrolled at ISCED 5 - women]
	,f9.[Students enrolled at ISCED 6 - part-time]
	,f9.[Students enrolled at ISCED 6 - between 22 and 24 years old]
	,f9.[Students at ISCED 7 - mobility unclassified]
	,f9.[Students enrolled at ISCED 7 - national]
	,f9.[Total students enrolled at ISCED 6]
	,f9.[Students enrolled at ISCED 7 - Social sciences, journalism and information]
	,f9.[Students at ISCED 5-citizenship unclassified]
	,f9.[Students enrolled at ISCED 7 - gender unclassified]
	,f9.[Students enrolled at ISCED 7 - mobile]
	,f9.[Students enrolled at ISCED 7 - Agriculture, forestry, fisheries and veterinary]
	,f9.[Students enrolled at ISCED 7 - Arts and Humanities]
	,f9.[Students enrolled at ISCED 7 - part-time]
	,f9.[Students enrolled at ISCED 5 - Business, administration and law]
	,f9.[Students enrolled at ISCED 7 - Engineering, manufacturing and construction]
	,f9.[Students enrolled at ISCED 7 - Generic programmes and qualifications]
	,f9.[Students enrolled at ISCED 7 - women]
	,f9.[Students enrolled at ISCED 5 - Health and welfare]
	,f9.[Students enrolled at ISCED 7 - Natural sciences, mathematics and statistics]
	,f9.[Students at ISCED 7-citizenship unclassified]
	,f9.[Students enrolled at ISCED 7 - under 20 years old]
	,f9.[Students enrolled ISCED 7 long degree - women]
	,f9.[Students enrolled at ISCED 5 - full-time]
	,f9.[Students enrolled at ISCED 7 - Services]
	,f9.[Students ISCED7 long degree-citiz. unclassified]
	,f9.[Students enrolled at ISCED 7 - Age goup unclassified]
	,f9.[Students enrolled at ISCED 7 - Business, administration and law]
	,f9.[Students enrolled at ISCED 5 - between 22 and 24 years old]
	,f9.[Students enrolled at ISCED 7 - part-, full-time unclassified]
	,f9.[Total students enrolled at ISCED 5]
	,f9.[Students enrolled at ISCED 7 - Health and welfare]
	,f9.[Students enrolled ISCED 7 long degree - men]
	,f9.[Students enrolled at ISCED 7 - between 25 and 29 years old]
	,f9.[Students enrolled at ISCED 6 - gender unclassified]
	,f9.[Students enrolled at ISCED 7 - full-time]
	,f9.[Students enrolled ISCED 7 long degree - foreigner]
	,f9.[Students ISCED 7 long degree-mobility unclassified]
	,f9.[Students enrolled ISCED 7 long degree - Business, administration and law]
	,f9.[Students enrolled at ISCED 7 - between 22 and 24 years old]
	,f9.[Students enrolled ISCED 7 long degree - Social sciences, journalism and information]
	,f9.[Students enrolled at ISCED 6 - Generic programmes and qualifications]
	,f9.[Students enrolled ISCED 7 long degree - Health and welfare]
	,f9.[Total students enrolled at ISCED 7]
	,f9.[Students enrolled ISCED 7 long degree - resident]
	,f9.[Students enrolled at ISCED 6 - Natural sciences, mathematics and statistics]
	,f9.[Students enrolled at ISCED 7 long degree - full-time]
	,f9.[Students enrolled ISCED 7 long degree - Agriculture, forestry, fisheries and veterinary]
	,f9.[Students ISCED 7 long degree - gender unclassified]
	,f9.[Students enrolled ISCED 7 long degree - Education]
	,f9.[Students enrolled at ISCED 6 - Services]
	,f9.[Students enrolled at ISCED 7 long degree - part-time]
	,f9.[Students enrolled at ISCED 7 long degree - between 22 and 24 years old]
	,f9.[Students enrolled ISCED 7 long degree - Information and Communication Technologies]
	,f9.[Total students enrolled ISCED 7 long degree]
	,f9.[Students enrolled at ISCED 6 - part-, full-time unclassified]
	,f9.[Students enrolled at ISCED 6 - between 25 and 29 years old]
	,f9.[Students ISCED7 long degree - ISCED-FoE unclassified]
	,f9.[Students enrolled at ISCED 5-7 - gender unclassified]
	,f9.[Students enrolled ISCED 7 long degree - Generic programmes and qualifications]
	,f9.[Students enrolled at ISCED 5-7 - women]
	,f9.[Students enrolled ISCED 7 long degree - Natural sciences, mathematics and statistics]
	,f9.[Students enrolled at ISCED 7 long degree - over 29 years old]
	,f9.[Students enrolled at ISCED 5-7 - Generic programmes and qualifications]
	,f9.[Students enrolled at ISCED 5-7 - citizenship unclassified]
	,f9.[Students enrolled ISCED 7 long degree - Services]
	,f9.[Students enrolled at ISCED 7 - resident]
	,f9.[Students enrolled at ISCED 5-7 - Natural sciences, mathematics and statistics]
	,f9.[Students enrolled at ISCED 7 long degree - part-, full-time unclassified]
	,f9.[Students enrolled at ISCED 7 - Education]
	,f9.[Students enrolled at ISCED 5-7 - Services]
	,f9.[Students enrolled at ISCED 5-7 - national]
	,f9.[Students enrolled at ISCED 5-7 - Business, administration and law]
	,f9.[Students enrolled at ISCED 7 long degree - between 25 and 29 years old]
	,f9.[Students enrolled at ISCED 5-7 - Health and welfare]
	,f9.[Students enrolled at ISCED 5-7 - part-, full-time unclassified]
	,f9.[Students enrolled at ISCED 5-7 - full-time]
	,f9.[Students enrolled at ISCED 7 - Information and Communication Technologies]
	,f9.[Students enrolled at ISCED 5-7 - between 22 and 24 years old]
	,f9.[Total students enrolled ISCED 5-7]
	,f9.[Students at ISCED 7 - ISCED-FoE unclassified]
	,f9.[Students enrolled at ISCED 5-7 - between 25 and 29 years old]
	,f9.[Students enrolled at ISCED 5-7 - mobile]
	,f9.[Students enrolled at ISCED 5-7 - resident]
	,f9.[Students enrolled at ISCED 7 - over 29 years old]
	,f9.[Students enrolled at ISCED 5-7 - Arts and Humanities]
	,f9.[Students enrolled at ISCED 5-7 - Education]
	,f9.[Students enrolled at ISCED 5-7 - Engineering, manufacturing and construction]
	,f9.[Students enrolled ISCED 7 long degree - national]
	,f9.[Students enrolled at ISCED 5-7 - Information and Communication Technologies]
	,f9.[Students enrolled ISCED 7 long degree - mobile]
	,f9.[Students enrolled at ISCED 5-7 - ISCED-FoE unclassified]
	,f9.[Students enrolled at ISCED 5-7 - under 20 years old]
	,f9.[Students enrolled at ISCED 5-7 - Age goup unclassified]
	,f9.[Students enrolled ISCED 7 long degree - Arts and Humanities]
	,f9.[Students enrolled ISCED 7 long degree - Engineering, manufacturing and construction]
	,f9.[Students enrolled at ISCED 5-7 - over 29 years old]
	,f9.[Students enrolled at ISCED 7 long degree - under 20 years old]
	,f9.[Students enrolled at ISCED 7 long degree - Age goup unclassified]
	,f9.[Students enrolled at ISCED 5-7 - men]
	,f9.[Students enrolled at ISCED 5-7 - foreigner]
	,f9.[Students enrolled at ISCED 5-7 - mobility unclassified]
	,f9.[Students enrolled at ISCED 5-7 - Social sciences, journalism and information]
	,f9.[Students enrolled at ISCED 5-7 - Agriculture, forestry, fisheries and veterinary]
	,f9.[Students enrolled at ISCED 5-7 - part-time]

	-- Indicators
	,f10.[Share of women academic staff]
	,coalesce(f10.[Share of women full professors], CASE WHEN f8.[Number of full professors - women] = 0 THEN 0 ELSE f8.[Number of full professors - women] / f8.[Total number of full professors] END) as 'Share of women full professors'
	,f10.[Share of foreigners students ISCED 6]
	,f10.[Share of foreigners students ISCED 7]
	,[Share of foreigners PhD students]
	,[Share of foreigners academic staff]

FROM [ANTERO].[dw].[f_eter_basic_info] f1

LEFT JOIN [ANTERO].[dw].[f_eter_erasmus] f2 on f1.ETER_ID = f2.ETER_ID
LEFT JOIN [ANTERO].[dw].[f_eter_expenditure] f3 on f1.ETER_ID = f3.ETER_ID
LEFT JOIN [ANTERO].[dw].[f_eter_geographic] f4 on f1.ETER_ID = f4.ETER_ID
LEFT JOIN [ANTERO].[dw].[f_eter_graduates] f5 on f1.ETER_ID = f5.ETER_ID
LEFT JOIN [ANTERO].[dw].[f_eter_research] f6 on f1.ETER_ID = f6.ETER_ID
LEFT JOIN [ANTERO].[dw].[f_eter_revenue] f7 on f1.ETER_ID = f7.ETER_ID
LEFT JOIN [ANTERO].[dw].[f_eter_staff] f8 on f1.ETER_ID = f8.ETER_ID
LEFT JOIN [ANTERO].[dw].[f_eter_students] f9 on f1.ETER_ID = f9.ETER_ID
LEFT JOIN [ANTERO].[dw].[f_eter_indicators] f10 on f1.ETER_ID = f10.ETER_ID
LEFT JOIN (SELECT DISTINCT [GEO], [GEO_LABEL] FROM [ANTERO].[dw].[f_eter_eurostat]) d1 on f1.[Country Code] = d1.[GEO]
LEFT JOIN [ANTERO].[dw].[f_eter_allfields_codes] d2 on d2.Name = 'Institution Category standardized' and d2.Code = f1.[Institution Category standardized]
LEFT JOIN [ANTERO].[dw].[f_eter_allfields_codes] d3 on d3.Name = 'Legal status' and d3.Code = f1.[Legal status]
LEFT JOIN [ANTERO].[dw].[f_eter_allfields_codes] d4 on d4.Name = 'Highest degree delivered' and d4.Code = f9.[Highest degree delivered]
LEFT JOIN [ANTERO].[dw].[f_eter_allfields_codes] d5 on d5.Name = 'Highest degree delivered' and d5.Code = f9.[Lowest degree delivered]
LEFT JOIN [ANTERO].[dw].[f_eter_allfields_codes] d6 on d6.Name = 'Distance education institution' and d6.Code = f9.[Distance education institution]
LEFT JOIN [ANTERO].[dw].[f_eter_allfields_codes] d7 on d7.Name = 'Tuition fees' and d7.Code = f7.[Tuition fees]

GO

USE [ANTERO]