USE [VipunenTK_DW]
GO

/****** Object:  Table [dbo].[_f_koulutukseen_sijoittuneet_6v_tarkastelu]    Script Date: 1.2.2024 12:23:27 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

DROP TABLE [dbo].[_f_koulutukseen_sijoittuneet_6v_tarkastelu]

GO

CREATE TABLE [dbo].[_f_koulutukseen_sijoittuneet_6v_tarkastelu](
	[aineistorivinumero] [int] NOT NULL,
	[tarkastelujakso] [nvarchar](20) NOT NULL,
	[tilv] [nvarchar](4) NOT NULL,
	[tilv_date] [date] NULL,
	[tutkryh] [nvarchar](10) NOT NULL,
	[suorv] [nvarchar](4) NOT NULL,
	[suorlk] [nvarchar](6) NOT NULL,
	[sp] [int] NOT NULL,
	[syntv] [nvarchar](8) NOT NULL,
	[aikielir1] [nvarchar](2) NOT NULL,
	[tutkkaskun] [nvarchar](3) NOT NULL,
	[kansalr1] [int] NOT NULL,
	[pohjmaa] [int] NOT NULL,
	[eumaa] [nvarchar](2) NOT NULL,
	[etamaa] [nvarchar](2) NOT NULL,
	[tunn] [nvarchar](10) NOT NULL,
	[jarj] [nvarchar](10) NOT NULL,
	[kkielir1] [nvarchar](4) NOT NULL,
	[tutklaja] [int] NOT NULL,
	[tutktav] [int] NOT NULL,
	[aikoul] [int] NOT NULL,
	[tutkmaak] [nvarchar](2) NOT NULL,
	[koulutus] [nvarchar](6) NULL,
	[oppilaitos] [nvarchar](10) NULL,
	[koulutuksen_jarjestaja] [nvarchar](10) NULL,
	[koulutuksen_maakunta] [nvarchar](2) NULL,
	[monihaku] [int] NOT NULL,
	[paaasiallinen_toiminta] [int] NULL,
	[ammattiasema] [int] NULL,
	[lkm] [int] NOT NULL,
	[pohjkoulk] [nvarchar](6) NOT NULL,
	[tietolahde] [varchar](255) NOT NULL,
	[aineisto] [nvarchar](8) NOT NULL,
	[lukiokoulutuksessa] [int] NOT NULL,
	[ammatillisessa_koulutuksessa] [int] NOT NULL,
	[ammattikorkeakoulutuksessa] [int] NOT NULL,
	[yliopistokoulutuksessa] [int] NOT NULL,
	[lukiokoulutuksessa_ja_ammatillisessa_koulutuksessa] [int] NOT NULL,
	[toisen_asteen_ammatillisessa_koulutuksessa_ja_korkeakoulutuksessa] [int] NOT NULL,
	[ammattikorkeakoulutuksessa_ja_yliopistokoulutuksessa] [int] NOT NULL,
	[koulutuksen_paattaneiden_toiminta] [int] NOT NULL,
	[rivinumero] [int] NOT NULL,
	[ika_1v] [nvarchar](10) NOT NULL,
	[ika_5v] [nvarchar](10) NOT NULL,
	[ika_1v_suorv] [nvarchar](10) NULL,
	[opisk_lu] [varchar](2) NULL,
	[opisk_amm_pk] [varchar](2) NULL,
	[opisk_amm_at] [varchar](2) NULL,
	[opisk_amm_eat] [varchar](2) NULL,
	[opisk_amm] [varchar](2) NULL,
	[opisk_amk] [varchar](2) NULL,
	[opisk_yo] [varchar](2) NULL,
	[opisk_amk_koulala1] [varchar](2) NULL,
	[opisk_amk_koulala2] [varchar](2) NULL,
	[opisk_amk_koulala3] [varchar](2) NULL,
	[opisk_amk_koulala4] [varchar](2) NULL,
	[opisk_amk_koulala5] [varchar](2) NULL,
	[opisk_amk_koulala6] [varchar](2) NULL,
	[opisk_amk_koulala7] [varchar](2) NULL,
	[opisk_amk_koulala8] [varchar](2) NULL,
	[opisk_amk_koulala9] [varchar](2) NULL,
	[opisk_amk_koulala10] [varchar](2) NULL,
	[opisk_yo_koulala1] [varchar](2) NULL,
	[opisk_yo_koulala2] [varchar](2) NULL,
	[opisk_yo_koulala3] [varchar](2) NULL,
	[opisk_yo_koulala4] [varchar](2) NULL,
	[opisk_yo_koulala5] [varchar](2) NULL,
	[opisk_yo_koulala6] [varchar](2) NULL,
	[opisk_yo_koulala7] [varchar](2) NULL,
	[opisk_yo_koulala8] [varchar](2) NULL,
	[opisk_yo_koulala9] [varchar](2) NULL,
	[opisk_yo_koulala10] [varchar](2) NULL,
	[opisk_vah2_koulala] [varchar](2) NULL,
	[haku_amm] [varchar](2) NULL,
	[haku_amk] [varchar](2) NULL,
	[haku_yo] [varchar](2) NULL,
	[eihaku_kk_eiopisk] [int] NULL,
	[eihaku_kk_eiopisk_kk_opisk_ta] [int] NULL,
	[eihaku_kk_eiopisk_kk_opisk_lu] [int] NULL,
	[eihaku_kk_eiopisk_kk_opisk_pk] [int] NULL,
	[eihaku_kk_eiopisk_kk_opisk_at] [int] NULL,
	[eihaku_kk_eiopisk_kk_opisk_eat] [int] NULL,
	[haku_kk_eiopisk_kk] [int] NULL,
	[haku_kk_eiopisk_kk_eiopisk_ta] [int] NULL,
	[haku_kk_eiopisk_kk_opisk_ta] [int] NULL,
	[haku_amk_eiopisk_kk] [int] NULL,
	[haku_yo_eiopisk_kk] [int] NULL,
	[haku_amkyo_eiopisk_kk] [int] NULL,
	[opisk_kk] [int] NULL,
	[opisk_kk_eiopisk_ta] [int] NULL,
	[opisk_kk_opisk_ta] [int] NULL,
	[opisk_vain_amk] [int] NULL,
	[opisk_vain_yo] [int] NULL,
	[opisk_amkyo] [int] NULL,
	[tj0_koul_luokitus_id] [int] NULL
) ON [PRIMARY]

GO


