{
  "name": "SemanticModel",
  "compatibilityLevel": 1200,
  "model": {
    "culture": "fi-FI",
    "dataSources": [
      {
        "name": "SqlServer dwitvipuarch22 ANTERO_master",
        "connectionString": "Provider=SQLOLEDB.1;Data Source=dwitvipuarch22;Initial Catalog=ANTERO_master;Integrated Security=SSPI;Persist Security Info=false",
        "impersonationMode": "impersonateServiceAccount",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "Sarakeleveys",
        "isHidden": true,
        "columns": [
          {
            "name": "Sarakeleveys",
            "dataType": "string",
            "sourceColumn": "Sarakeleveys",
            "sourceProviderType": "Char"
          },
          {
            "name": "leveys",
            "dataType": "string",
            "sourceColumn": "leveys",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Sarakeleveys",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dw].[Sarakeleveys].* FROM [dw].[Sarakeleveys] ",
              "dataSource": "SqlServer dwitvipuarch22 ANTERO_master"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dw].[Sarakeleveys].* FROM [dw].[Sarakeleveys] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Sarakeleveys"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dw"
          }
        ]
      },
      {
        "name": "Muuttujat",
        "columns": [
          {
            "name": "rahoituskausi",
            "dataType": "string",
            "sourceColumn": "rahoituskausi",
            "sourceProviderType": "WChar"
          },
          {
            "name": "kysely_fi",
            "dataType": "string",
            "sourceColumn": "kysely_fi",
            "sourceProviderType": "WChar"
          },
          {
            "name": "koulutuksen_jarjestaja_fi",
            "dataType": "string",
            "sourceColumn": "koulutuksen_jarjestaja_fi",
            "sourceProviderType": "WChar"
          },
          {
            "name": "koulutuksen_jarjestajan_kunta_fi",
            "dataType": "string",
            "sourceColumn": "koulutuksen_jarjestajan_kunta_fi",
            "sourceProviderType": "WChar"
          },
          {
            "name": "koulutuksen_jarjestajan_maakunta_fi",
            "dataType": "string",
            "sourceColumn": "koulutuksen_jarjestajan_maakunta_fi",
            "sortByColumn": "jarjestys_koulutuksen_jarjestajan_maakunta",
            "sourceProviderType": "WChar"
          },
          {
            "name": "koulutuksen_jarjestajan_hyvinvointialue_fi",
            "dataType": "string",
            "sourceColumn": "koulutuksen_jarjestajan_hyvinvointialue_fi",
            "sortByColumn": "jarjestys_koulutuksen_jarjestajan_hyvinvointialue",
            "sourceProviderType": "WChar"
          },
          {
            "name": "koulutuksen_jarjestajan_avi_fi",
            "dataType": "string",
            "sourceColumn": "koulutuksen_jarjestajan_avi_fi",
            "sortByColumn": "jarjestys_koulutuksen_jarjestajan_avi",
            "sourceProviderType": "WChar"
          },
          {
            "name": "koulutuksen_jarjestajan_ely_fi",
            "dataType": "string",
            "sourceColumn": "koulutuksen_jarjestajan_ely_fi",
            "sortByColumn": "jarjestys_koulutuksen_jarjestajan_ely",
            "sourceProviderType": "WChar"
          },
          {
            "name": "koulutuksen_jarjestajan_opetuskieli_fi",
            "dataType": "string",
            "sourceColumn": "koulutuksen_jarjestajan_opetuskieli_fi",
            "sortByColumn": "jarjestys_koulutuksen_jarjestajan_opetuskieli",
            "sourceProviderType": "Char"
          },
          {
            "name": "Koul. järjestäjän PILKE-alue (kokeilu)",
            "dataType": "string",
            "sourceColumn": "Koul. järjestäjän PILKE-alue (kokeilu)",
            "sortByColumn": "jarjestys Koul. järjestäjän PILKE-alue (kokeilu)",
            "sourceProviderType": "WChar",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "jarjestys Koul. järjestäjän PILKE-alue (kokeilu)",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarjestys Koul. järjestäjän PILKE-alue (kokeilu)",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Toiminnanohjauksen kokeilu",
            "dataType": "string",
            "sourceColumn": "Toiminnanohjauksen kokeilu",
            "sortByColumn": "jarjestys Toiminnanohjauksen kokeilu",
            "sourceProviderType": "WChar",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "jarjestys Toiminnanohjauksen kokeilu",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jarjestys Toiminnanohjauksen kokeilu",
            "sourceProviderType": "Integer"
          },
          {
            "name": "koodit_koulutuksen_jarjestaja",
            "dataType": "string",
            "sourceColumn": "koodit_koulutuksen_jarjestaja",
            "sourceProviderType": "Char"
          },
          {
            "name": "jarjestys_koulutuksen_jarjestajan_maakunta",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarjestys_koulutuksen_jarjestajan_maakunta",
            "sourceProviderType": "Char"
          },
          {
            "name": "jarjestys_koulutuksen_jarjestajan_hyvinvointialue",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarjestys_koulutuksen_jarjestajan_hyvinvointialue",
            "sourceProviderType": "Char"
          },
          {
            "name": "jarjestys_koulutuksen_jarjestajan_avi",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarjestys_koulutuksen_jarjestajan_avi",
            "sourceProviderType": "Char"
          },
          {
            "name": "jarjestys_koulutuksen_jarjestajan_ely",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarjestys_koulutuksen_jarjestajan_ely",
            "sourceProviderType": "Char"
          },
          {
            "name": "jarjestys_koulutuksen_jarjestajan_opetuskieli",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "jarjestys_koulutuksen_jarjestajan_opetuskieli",
            "sourceProviderType": "Char"
          },
          {
            "name": "apusarake_kohteet",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "apusarake_kohteet",
            "sourceProviderType": "Double"
          },
          {
            "name": "apusarake_vastanneet",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "apusarake_vastanneet",
            "sourceProviderType": "Double"
          },
          {
            "name": "apusarake_vastausosuus",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "apusarake_vastausosuus",
            "sourceProviderType": "Double"
          },
          {
            "name": "apusarake_katokorjauskerroin",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "apusarake_katokorjauskerroin",
            "sourceProviderType": "Double"
          },
          {
            "name": "apusarake_keskiarvo",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "apusarake_keskiarvo",
            "sourceProviderType": "Double"
          },
          {
            "name": "apusarake_pisteet",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "apusarake_pisteet",
            "sourceProviderType": "Double"
          },
          {
            "name": "apusarake_painotetut_pisteet",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "apusarake_painotetut_pisteet",
            "sourceProviderType": "Double"
          }
        ],
        "partitions": [
          {
            "name": "Muuttujat",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dw].[v_amos_tyoelamapalaute].* FROM [dw].[v_amos_tyoelamapalaute] ",
              "dataSource": "SqlServer dwitvipuarch22 ANTERO_master"
            }
          }
        ],
        "measures": [
          {
            "name": "Kyselyn kohteet (Rahoitus)",
            "expression": [
              "",
              "var lkm = SUM(Muuttujat[apusarake_kohteet])",
              "return IF(lkm=0, BLANK(), lkm)"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Vastanneet (Rahoitus)",
            "expression": [
              "",
              "var lkm = SUM(Muuttujat[apusarake_vastanneet])",
              "return IF(lkm=0, BLANK(), lkm)"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Vastausosuus (Rahoitus)",
            "expression": "DIVIDE([Vastanneet (Rahoitus)], [Kyselyn kohteet (Rahoitus)])",
            "formatString": "0 %;-0 %;0 %"
          },
          {
            "name": "Katokorjauskerroin (Rahoitus)",
            "expression": [
              "",
              "var ehto = HASONEVALUE(Muuttujat[rahoituskausi]) && ISFILTERED(Muuttujat[rahoituskausi])",
              "var ehto_2025 = SELECTEDVALUE(Muuttujat[rahoituskausi]) in {\"01.07.2023 - 30.06.2024\", \"01.07.2022 - 30.06.2023\", \"01.07.2021 - 30.06.2022\"}",
              "var osuus = [Vastausosuus (Rahoitus)]",
              "var kk_2026 = IF(ISBLANK(osuus)",
              "\t, BLANK()",
              "\t, IF(osuus >= 0.6",
              "\t\t, 1/osuus",
              "\t\t, 1/0.6 + 2 * (0.6 - osuus)",
              "\t)",
              ")",
              "var kk_2025 = IF(ISBLANK(osuus)",
              "\t, BLANK()",
              "\t, IF(osuus >= 0.7",
              "\t\t, 1/osuus",
              "\t\t, IF(osuus <= 0.2",
              "\t\t\t, 857/350",
              "\t\t\t, 1/0.7 + 2.04 * (0.7 - osuus)",
              "\t\t)",
              "\t)",
              ")",
              "return IF(ehto, IF(ehto_2025, kk_2025, kk_2026), BLANK())"
            ],
            "formatString": "0.00"
          },
          {
            "name": "Pisteet (Rahoitus)",
            "expression": [
              "",
              "var lkm = SUM([apusarake_pisteet])",
              "return IF(lkm=0, BLANK(), lkm)"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Keskiarvo (Rahoitus)",
            "expression": [
              "",
              "DIVIDE(DIVIDE([Pisteet (Rahoitus)], [Vastanneet (Rahoitus)]), [kysymysten_lkm])"
            ],
            "formatString": "0.0"
          },
          {
            "name": "kysymysten_lkm",
            "expression": [
              "",
              "var ehto = HASONEVALUE(Muuttujat[kysely_fi])",
              "var ehto_tpok = VALUES(Muuttujat[kysely_fi])=\"Työelämäpalaute: työpaikkaohjaajan kysely\"",
              "var ehto_tpk  = VALUES(Muuttujat[kysely_fi])=\"Työelämäpalaute: työpaikkakysely\"",
              "return IF(ehto, IF(ehto_tpok, 8, IF(ehto_tpk, 9, BLANK())), BLANK())",
              ""
            ],
            "formatString": "0",
            "isHidden": true
          },
          {
            "name": "Painotetut pisteet (Rahoitus)",
            "expression": [
              "",
              "var taulu = ",
              "ADDCOLUMNS(",
              "\tSUMMARIZE(Muuttujat",
              "\t\t, Muuttujat[kysely_fi]",
              "\t\t, Muuttujat[rahoituskausi]",
              "\t\t, Muuttujat[koodit_koulutuksen_jarjestaja]",
              "\t)",
              "\t, \"painotetut\"",
              "\t, [Katokorjauskerroin (Rahoitus)] * [Pisteet (Rahoitus)]",
              ")",
              "var lkm = SUMX(taulu, [painotetut])",
              "return IF(lkm=0, BLANK(), lkm)"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Pisteet % (Rahoitus)",
            "expression": [
              "",
              "var osa = [Pisteet (Rahoitus)]",
              "var kaikki = ",
              "CALCULATE(",
              "\t[Pisteet (Rahoitus)]",
              "\t, ALLEXCEPT(Muuttujat",
              "\t\t, Muuttujat[kysely_fi]",
              "\t\t, Muuttujat[rahoituskausi]",
              "\t)",
              ")",
              "return DIVIDE(osa, kaikki)"
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %"
          },
          {
            "name": "Painotetut pisteet % (Rahoitus)",
            "expression": [
              "",
              "var osa = [Painotetut pisteet (Rahoitus)]",
              "var kaikki = ",
              "CALCULATE(",
              "\t[Painotetut pisteet (Rahoitus)]",
              "\t, ALLEXCEPT(Muuttujat",
              "\t\t, Muuttujat[kysely_fi]",
              "\t\t, Muuttujat[rahoituskausi]",
              "\t)",
              ")",
              "return DIVIDE(osa, kaikki)"
            ],
            "formatString": "0.00 %;-0.00 %;0.00 %"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dw].[v_amos_tyoelamapalaute].* FROM [dw].[v_amos_tyoelamapalaute] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "v_amos_tyoelamapalaute"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dw"
          }
        ]
      }
    ],
    "cultures": [
      {
        "name": "fi-FI",
        "translations": {
          "model": {
            "name": "Model",
            "tables": [
              {
                "name": "Muuttujat",
                "translatedCaption": "Muuttujat",
                "columns": [
                  {
                    "name": "rahoituskausi",
                    "translatedCaption": "Rahoituskausi",
                    "translatedDisplayFolder": "Aikamuuttujat"
                  },
                  {
                    "name": "kysely_fi",
                    "translatedCaption": "Kysely",
                    "translatedDisplayFolder": "Kyselymuuttujat"
                  },
                  {
                    "name": "koulutuksen_jarjestaja_fi",
                    "translatedCaption": "Koulutuksen järjestäjä",
                    "translatedDisplayFolder": "Organisaatiomuuttujat"
                  },
                  {
                    "name": "koulutuksen_jarjestajan_kunta_fi",
                    "translatedCaption": "Koulutuksen järjestäjän kunta",
                    "translatedDisplayFolder": "Organisaatiomuuttujat"
                  },
                  {
                    "name": "koulutuksen_jarjestajan_maakunta_fi",
                    "translatedCaption": "Koulutuksen järjestäjän maakunta",
                    "translatedDisplayFolder": "Organisaatiomuuttujat"
                  },
                  {
                    "name": "koulutuksen_jarjestajan_hyvinvointialue_fi",
                    "translatedCaption": "Koulutuksen järjestäjän hyvinvointialue",
                    "translatedDisplayFolder": "Organisaatiomuuttujat"
                  },
                  {
                    "name": "koulutuksen_jarjestajan_avi_fi",
                    "translatedCaption": "Koulutuksen järjestäjän AVI",
                    "translatedDisplayFolder": "Organisaatiomuuttujat"
                  },
                  {
                    "name": "koulutuksen_jarjestajan_ely_fi",
                    "translatedCaption": "Koulutuksen järjestäjän ELY",
                    "translatedDisplayFolder": "Organisaatiomuuttujat"
                  },
                  {
                    "name": "koulutuksen_jarjestajan_opetuskieli_fi",
                    "translatedCaption": "Koulutuksen järjestäjän opetuskieli",
                    "translatedDisplayFolder": "Organisaatiomuuttujat"
                  },
                  {
                    "name": "koodit_koulutuksen_jarjestaja",
                    "translatedCaption": "Koodit Koulutuksen järjestäjä",
                    "translatedDisplayFolder": "Koodimuuttujat"
                  },
                  {
                    "name": "jarjestys_koulutuksen_jarjestajan_maakunta",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Koodimuuttujat"
                  },
                  {
                    "name": "jarjestys_koulutuksen_jarjestajan_hyvinvointialue",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Koodimuuttujat"
                  },
                  {
                    "name": "jarjestys_koulutuksen_jarjestajan_avi",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Koodimuuttujat"
                  },
                  {
                    "name": "jarjestys_koulutuksen_jarjestajan_ely",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Koodimuuttujat"
                  },
                  {
                    "name": "jarjestys_koulutuksen_jarjestajan_opetuskieli",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Koodimuuttujat"
                  },
                  {
                    "name": "apusarake_kohteet",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Koodimuuttujat"
                  },
                  {
                    "name": "apusarake_vastanneet",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Koodimuuttujat"
                  },
                  {
                    "name": "apusarake_vastausosuus",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Koodimuuttujat"
                  },
                  {
                    "name": "apusarake_katokorjauskerroin",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Koodimuuttujat"
                  },
                  {
                    "name": "apusarake_keskiarvo",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Koodimuuttujat"
                  },
                  {
                    "name": "apusarake_pisteet",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Koodimuuttujat"
                  },
                  {
                    "name": "apusarake_painotetut_pisteet",
                    "translatedCaption": ".",
                    "translatedDisplayFolder": "Koodimuuttujat"
                  }
                ]
              }
            ]
          }
        }
      }
    ],
    "perspectives": [
      {
        "name": "rahoitus_tyopaikkaohjaajakysely_fi",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Koul. järjestäjän PILKE-alue (kokeilu)"
              },
              {
                "name": "Toiminnanohjauksen kokeilu"
              },
              {
                "name": "koulutuksen_jarjestaja_fi"
              },
              {
                "name": "koulutuksen_jarjestajan_avi_fi"
              },
              {
                "name": "koulutuksen_jarjestajan_ely_fi"
              },
              {
                "name": "koulutuksen_jarjestajan_kunta_fi"
              },
              {
                "name": "koulutuksen_jarjestajan_maakunta_fi"
              },
              {
                "name": "rahoituskausi"
              },
              {
                "name": "koodit_koulutuksen_jarjestaja"
              }
            ],
            "measures": [
              {
                "name": "Katokorjauskerroin (Rahoitus)"
              },
              {
                "name": "Keskiarvo (Rahoitus)"
              },
              {
                "name": "Kyselyn kohteet (Rahoitus)"
              },
              {
                "name": "Painotetut pisteet (Rahoitus)"
              },
              {
                "name": "Painotetut pisteet % (Rahoitus)"
              },
              {
                "name": "Pisteet (Rahoitus)"
              },
              {
                "name": "Vastanneet (Rahoitus)"
              },
              {
                "name": "Vastausosuus (Rahoitus)"
              }
            ]
          }
        ]
      },
      {
        "name": "rahoitus_tyopaikkakysely_fi",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "koulutuksen_jarjestaja_fi"
              },
              {
                "name": "koulutuksen_jarjestajan_avi_fi"
              },
              {
                "name": "koulutuksen_jarjestajan_ely_fi"
              },
              {
                "name": "koulutuksen_jarjestajan_kunta_fi"
              },
              {
                "name": "koulutuksen_jarjestajan_maakunta_fi"
              },
              {
                "name": "rahoituskausi"
              },
              {
                "name": "koodit_koulutuksen_jarjestaja"
              }
            ],
            "measures": [
              {
                "name": "Keskiarvo (Rahoitus)"
              },
              {
                "name": "Kyselyn kohteet (Rahoitus)"
              },
              {
                "name": "Pisteet (Rahoitus)"
              },
              {
                "name": "Pisteet % (Rahoitus)"
              },
              {
                "name": "Vastanneet (Rahoitus)"
              },
              {
                "name": "Vastausosuus (Rahoitus)"
              }
            ]
          }
        ]
      }
    ],
    "roles": [
      {
        "name": "Luku",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "DWI\\P_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1733"
          },
          {
            "memberName": "DWI\\T_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1732"
          },
          {
            "memberName": "DWI\\Z_DWIPVIPURD_Allow_F_Drive",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-5333"
          },
          {
            "memberName": "DWI\\Z_DWIVIPURD_Allow_E_Drive",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-5359"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "400"
      }
    ]
  },
  "id": "SemanticModel"
}