{
  "name": "SemanticModel",
  "id": "SemanticModel",
  "compatibilityLevel": 1200,
  "model": {
    "culture": "fi-FI",
    "dataSources": [
      {
        "name": "SqlServer DWITESTVIPUSQL VipunenTK",
        "connectionString": "Provider=SQLOLEDB.1;Data Source=dwitvipusql22;Initial Catalog=VipunenTK;Integrated Security=SSPI;Persist Security Info=false",
        "impersonationMode": "impersonateAccount",
        "account": "DWI\\T_VIPUTK_KUUTIO",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "Muuttujat",
        "columns": [
          {
            "name": "Tilastovuosi",
            "dataType": "string",
            "sourceColumn": "Tilastovuosi",
            "displayFolder": "Aikamuuttujat"
          },
          {
            "name": "Oppilaitoksen opetuskieli",
            "dataType": "string",
            "sourceColumn": "Oppilaitoksen opetuskieli",
            "sortByColumn": "opetuskieli järjestys",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Tehtävätyyppi",
            "dataType": "string",
            "sourceColumn": "Tehtavätyyppi perusopetuksessa",
            "sortByColumn": "Tehtavätyyppi perusopetuksessa järjestys",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Osallistuminen tutkintotavoitteeseen koulutukseen työajalla",
            "dataType": "int64",
            "sourceColumn": "Osallistuminen tutkintotavoitteeseen koulutukseen työajalla",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Osallistuminen tutkintotavoitteeseen omalla ajalla",
            "dataType": "int64",
            "sourceColumn": "Osallistuminen tutkintotavoitteeseen omalla ajalla",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Osallistuminen kelpoisuuden tai pätevyyden tuottavaan koulutukseen työajalla",
            "dataType": "int64",
            "sourceColumn": "Osallistuminen kelpoisuuden tai pätevyyden tuottavaan koulutukseen työajalla",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Osallistuminen kelpoisuuden tai pätevyyden tuottavaan koulutukseen omalla ajalla",
            "dataType": "int64",
            "sourceColumn": "Osallistuminen kelpoisuuden tai pätevyyden tuottavaan koulutukseen omalla ajalla",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Osallistuminen työantajan järjestämään henkilöstökoulutukseen työajalla",
            "dataType": "int64",
            "sourceColumn": "Osallistuminen työantajan järjestämään henkilöstökoulutukseen työajalla",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Osallistuminen työantajan järjestämään henkilöstökoulutukseen omalla ajalla",
            "dataType": "int64",
            "sourceColumn": "Osallistuminen työantajan järjestämään henkilöstökoulutukseen omalla ajalla",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Osallistuminen muuhun toimintaan työajalla",
            "dataType": "int64",
            "sourceColumn": "Osallistuminen muuhun toimintaan työajalla",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Osallistuminen muuhun toimintaan omalla ajalla",
            "dataType": "int64",
            "sourceColumn": "Osallistuminen muuhun toimintaan omalla ajalla",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Osallistuminen kotimaiseen tai kansainväliseen asiantuntijavaihtoon työajalla",
            "dataType": "int64",
            "sourceColumn": "Osallistuminen kotimaiseen tai kansainväliseen asiantuntijavaihtoon työajalla",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Osallistuminen kotimaiseen tai kansainväliseen asiantuntijavaihtoon omalla ajalla",
            "dataType": "int64",
            "sourceColumn": "Osallistuminen kotimaiseen tai kansainväliseen asiantuntijavaihtoon omalla ajalla",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Sukupuoli",
            "dataType": "string",
            "sourceColumn": "Sukupuoli",
            "sortByColumn": "Sukupuoli järjestys",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Oppilaitoksen maakunta",
            "dataType": "string",
            "sourceColumn": "Oppilaitoksen maakunta",
            "sortByColumn": "Oppilaitoksen maakunta järjestys",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "opetuskieli järjestys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "opetuskieli järjestys"
          },
          {
            "name": "Tehtavätyyppi perusopetuksessa järjestys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Tehtavätyyppi perusopetuksessa järjestys"
          },
          {
            "name": "Sukupuoli järjestys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Sukupuoli järjestys"
          },
          {
            "name": "Oppilaitoksen maakunta järjestys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Oppilaitoksen maakunta järjestys"
          },
          {
            "name": "Ikä järjestys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Ikä järjestys"
          },
          {
            "name": "Täydennyskoulutus tai asiantuntijavaihto",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Täydennyskoulutus tai asiantuntijavaihto"
          },
          {
            "name": "Statistikår",
            "dataType": "string",
            "sourceColumn": "Statistikår",
            "displayFolder": "Tidsvariabler"
          },
          {
            "name": "Läroanstaltens undervisningsspråk",
            "dataType": "string",
            "sourceColumn": "Läroanstaltens undervisningsspråk",
            "displayFolder": "Organisationsvariabler"
          },
          {
            "name": "Kön",
            "dataType": "string",
            "sourceColumn": "Kön",
            "displayFolder": "Personvariabler"
          },
          {
            "name": "Läroanstaltens landskap",
            "dataType": "string",
            "sourceColumn": "Läroanstaltens landskap",
            "sortByColumn": "Oppilaitoksen maakunta järjestys",
            "displayFolder": "Organisationsvariabler"
          },
          {
            "name": "Statistical year",
            "dataType": "string",
            "sourceColumn": "Statistical year",
            "displayFolder": "Time variables"
          },
          {
            "name": "Language of the institution",
            "dataType": "string",
            "sourceColumn": "Language of the institution",
            "displayFolder": "Organisation variables"
          },
          {
            "name": "Gender",
            "dataType": "string",
            "sourceColumn": "Gender",
            "displayFolder": "Person variables"
          },
          {
            "name": "Region of the institution",
            "dataType": "string",
            "sourceColumn": "Region of the institution",
            "sortByColumn": "Oppilaitoksen maakunta järjestys",
            "displayFolder": "Organisation variables"
          },
          {
            "name": "Age group",
            "dataType": "string",
            "sourceColumn": "Age group",
            "sortByColumn": "Ikä järjestys",
            "displayFolder": "Person variables"
          },
          {
            "name": "Koodit Oppil maakunta",
            "dataType": "string",
            "sourceColumn": "Koodit Oppil. maakunta",
            "displayFolder": "Koodimuuttujat"
          },
          {
            "name": "Ikäryhmä",
            "dataType": "string",
            "sourceColumn": "Ikäryhmä",
            "sortByColumn": "Ikä järjestys",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Åldersgrupp",
            "dataType": "string",
            "sourceColumn": "Åldersgrupp",
            "sortByColumn": "Ikä järjestys",
            "displayFolder": "Personvariabler"
          },
          {
            "name": "Type of task",
            "dataType": "string",
            "sourceColumn": "Type of task",
            "sortByColumn": "Tehtavätyyppi perusopetuksessa järjestys",
            "displayFolder": "Person variables"
          },
          {
            "name": "Uppgiftstyp",
            "dataType": "string",
            "sourceColumn": "Uppgiftstyp",
            "sortByColumn": "Tehtavätyyppi perusopetuksessa järjestys",
            "displayFolder": "Personvariabler"
          },
          {
            "name": "Kouluttautunut mentoriksi",
            "dataType": "string",
            "sourceColumn": "Kouluttautunut mentoriksi",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Toiminut mentorina",
            "dataType": "string",
            "sourceColumn": "Toiminut mentorina",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Ollut mentoroitavana",
            "dataType": "string",
            "sourceColumn": "Ollut mentoroitavana",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Kouluttautunut työnohjaajaksi",
            "dataType": "string",
            "sourceColumn": "Kouluttautunut työnohjaajaksi",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Toiminut työnohjaajana",
            "dataType": "string",
            "sourceColumn": "Toiminut työnohjaajana",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Ollut työnohjauksessa",
            "dataType": "string",
            "sourceColumn": "Ollut työnohjauksessa",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Koulutus- ja kehittämissuunnitelma",
            "dataType": "string",
            "sourceColumn": "Koulutus- ja kehittämissuunnitelma",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Opettajan tunnit",
            "dataType": "int64",
            "sourceColumn": "Opettajan tunnit",
            "displayFolder": "Henkilömuuttujat"
          }
        ],
        "partitions": [
          {
            "name": "f_Opettajat_perusopetus_osallistuminen_taydennyskoulutukseen",
            "source": {
              "query": "SELECT [dbo].[v_f_tab_opettajat_7_3].* FROM [dbo].[v_f_tab_opettajat_7_3]",
              "dataSource": "SqlServer DWITESTVIPUSQL VipunenTK"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": "&lt;?xml version=\"1.0\" encoding=\"UTF-16\"?&gt;&lt;Gemini xmlns=\"TableWidgetSerialization\"&gt;&lt;AnnotationContent&gt;&lt;![CDATA[&lt;?xml version=\"1.0\"?&gt;\n&lt;TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\"&gt;\n  &lt;ColumnSuggestedType /&gt;\n  &lt;ColumnFormat /&gt;\n  &lt;ColumnAccuracy /&gt;\n  &lt;ColumnCurrencySymbol /&gt;\n  &lt;ColumnPositivePattern /&gt;\n  &lt;ColumnNegativePattern /&gt;\n  &lt;ColumnWidths&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Tilastovuosi&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;86&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Oppilaitoksen opetuskieli&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;147&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Tehtavätyyppi perusopetuksessa&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;190&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Uppgiftstyp&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;86&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Läroanstaltens undervisningsspråk&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;196&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Statistikår&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;78&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Osallistuminen tutkintotavoitteeseen koulutukseen työajalla&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;315&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Osallistuminen tutkintotavoitteeseen omalla ajalla&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;266&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Osallistuminen kelpoisuuden tai pätevyyden tuottavaan koulutukseen työajalla&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;406&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Osallistuminen kelpoisuuden tai pätevyyden tuottavaan koulutukseen omalla ajalla&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;423&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Osallistuminen työantajan järjestämään henkilöstökoulutukseen työajalla&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;378&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Osallistuminen työantajan järjestämään henkilöstökoulutukseen omalla ajalla&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;395&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Osallistuminen muuhun toimintaan työajalla&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;236&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Osallistuminen muuhun toimintaan omalla ajalla&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;253&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Osallistuminen kotimaiseen tai kansainväliseen asiantuntijavaihtoon työajalla&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;395&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Osallistuminen kotimaiseen tai kansainväliseen asiantuntijavaihtoon omalla ajalla&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;412&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Sukupuoli&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;75&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Oppilaitoksen maakunta&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;144&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Type of task&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;90&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;opetuskieli järjestys&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;125&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Tehtavätyyppi perusopetuksessa järjestys&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;235&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Sukupuoli järjestys&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;120&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Oppilaitoksen maakunta järjestys&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;189&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Ikä järjestys&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;90&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Täydennyskoulutus tai asiantuntijavaihto&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;227&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Kön&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;48&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Läroanstaltens landskap&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;146&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Åldersgrupp&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;88&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Statistical year&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;101&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Language of the institution&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;159&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Ikäryhmä&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;75&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Gender&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;65&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Region of the institution&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;145&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Age group&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;80&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koodit Oppil. maakunta&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;141&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Kouluttautunut mentoriksi&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;153&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Toiminut mentorina&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;121&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Ollut mentoroitavana&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;131&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Kouluttautunut työnohjaajaksi&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;175&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Toiminut työnohjaajana&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;143&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Ollut työnohjauksessa&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;136&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koulutus- ja kehittämissuunnitelma&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;195&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Opettajan tunnit&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;136&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n  &lt;/ColumnWidths&gt;\n  &lt;ColumnDisplayIndex&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Tilastovuosi&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;0&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Oppilaitoksen opetuskieli&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;1&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Tehtavätyyppi perusopetuksessa&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;2&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Uppgiftstyp&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;34&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Läroanstaltens undervisningsspråk&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;22&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Statistikår&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;21&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Osallistuminen tutkintotavoitteeseen koulutukseen työajalla&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;3&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Osallistuminen tutkintotavoitteeseen omalla ajalla&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;4&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Osallistuminen kelpoisuuden tai pätevyyden tuottavaan koulutukseen työajalla&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;5&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Osallistuminen kelpoisuuden tai pätevyyden tuottavaan koulutukseen omalla ajalla&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;6&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Osallistuminen työantajan järjestämään henkilöstökoulutukseen työajalla&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;7&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Osallistuminen työantajan järjestämään henkilöstökoulutukseen omalla ajalla&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;8&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Osallistuminen muuhun toimintaan työajalla&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;9&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Osallistuminen muuhun toimintaan omalla ajalla&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;10&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Osallistuminen kotimaiseen tai kansainväliseen asiantuntijavaihtoon työajalla&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;11&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Osallistuminen kotimaiseen tai kansainväliseen asiantuntijavaihtoon omalla ajalla&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;12&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Sukupuoli&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;13&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Oppilaitoksen maakunta&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;14&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Type of task&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;33&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;opetuskieli järjestys&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;15&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Tehtavätyyppi perusopetuksessa järjestys&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;16&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Sukupuoli järjestys&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;17&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Oppilaitoksen maakunta järjestys&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;18&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Ikä järjestys&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;19&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Täydennyskoulutus tai asiantuntijavaihto&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;20&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Kön&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;23&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Läroanstaltens landskap&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;24&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Åldersgrupp&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;32&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Statistical year&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;25&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Language of the institution&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;26&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Ikäryhmä&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;31&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Gender&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;27&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Region of the institution&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;28&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Age group&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;29&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koodit Oppil. maakunta&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;30&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Kouluttautunut mentoriksi&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;35&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Toiminut mentorina&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;36&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Ollut mentoroitavana&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;37&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Kouluttautunut työnohjaajaksi&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;38&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Toiminut työnohjaajana&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;39&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Ollut työnohjauksessa&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;40&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koulutus- ja kehittämissuunnitelma&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;41&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Opettajan tunnit&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;int&gt;42&lt;/int&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n  &lt;/ColumnDisplayIndex&gt;\n  &lt;ColumnFrozen /&gt;\n  &lt;ColumnChecked&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Tilastovuosi&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Oppilaitoksen opetuskieli&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Tehtavätyyppi perusopetuksessa&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Uppgiftstyp&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Läroanstaltens undervisningsspråk&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Statistikår&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Osallistuminen tutkintotavoitteeseen koulutukseen työajalla&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Osallistuminen tutkintotavoitteeseen omalla ajalla&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Osallistuminen kelpoisuuden tai pätevyyden tuottavaan koulutukseen työajalla&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Osallistuminen kelpoisuuden tai pätevyyden tuottavaan koulutukseen omalla ajalla&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Osallistuminen työantajan järjestämään henkilöstökoulutukseen työajalla&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Osallistuminen työantajan järjestämään henkilöstökoulutukseen omalla ajalla&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Osallistuminen muuhun toimintaan työajalla&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Osallistuminen muuhun toimintaan omalla ajalla&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Osallistuminen kotimaiseen tai kansainväliseen asiantuntijavaihtoon työajalla&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Osallistuminen kotimaiseen tai kansainväliseen asiantuntijavaihtoon omalla ajalla&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Sukupuoli&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Oppilaitoksen maakunta&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Type of task&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;opetuskieli järjestys&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Tehtavätyyppi perusopetuksessa järjestys&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Sukupuoli järjestys&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Oppilaitoksen maakunta järjestys&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Ikä järjestys&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Täydennyskoulutus tai asiantuntijavaihto&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Kön&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Läroanstaltens landskap&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Åldersgrupp&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Statistical year&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Language of the institution&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Ikäryhmä&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Gender&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Region of the institution&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Age group&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koodit Oppil. maakunta&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Kouluttautunut mentoriksi&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Toiminut mentorina&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Ollut mentoroitavana&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Kouluttautunut työnohjaajaksi&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Toiminut työnohjaajana&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Ollut työnohjauksessa&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Koulutus- ja kehittämissuunnitelma&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n    &lt;item&gt;\n      &lt;key&gt;\n        &lt;string&gt;Opettajan tunnit&lt;/string&gt;\n      &lt;/key&gt;\n      &lt;value&gt;\n        &lt;boolean&gt;true&lt;/boolean&gt;\n      &lt;/value&gt;\n    &lt;/item&gt;\n  &lt;/ColumnChecked&gt;\n  &lt;ColumnFilter /&gt;\n  &lt;SelectionFilter /&gt;\n  &lt;FilterParameters /&gt;\n  &lt;IsSortDescending&gt;false&lt;/IsSortDescending&gt;\n&lt;/TableWidgetGridSerialization&gt;]]&gt;&lt;/AnnotationContent&gt;&lt;/Gemini&gt;"
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Opettajien lukumäärä (tiedonkeruussa)",
            "expression": "COUNTROWS(Muuttujat)",
            "formatString": "#,0"
          },
          {
            "name": "Osallistunut täydennyskoulutukseen tai asiantuntijavaihtoon",
            "expression": "sum(Muuttujat[Täydennyskoulutus tai asiantuntijavaihto])",
            "formatString": "#,0"
          },
          {
            "name": "Ei osallistunut täydennyskoulutukseen tai asiantuntijavaihtoon",
            "expression": "[Opettajien lukumäärä (tiedonkeruussa)]-[Osallistunut täydennyskoulutukseen tai asiantuntijavaihtoon]",
            "formatString": "#,0"
          },
          {
            "name": "Osallistuneiden osuus vastanneista",
            "expression": "[Osallistunut täydennyskoulutukseen tai asiantuntijavaihtoon]/([Opettajien lukumäärä (tiedonkeruussa)])",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Tutkintotavoitteinen koulutus (htpv)",
            "expression": "sum(Muuttujat[Osallistuminen tutkintotavoitteeseen omalla ajalla])+sum(Muuttujat[Osallistuminen tutkintotavoitteeseen koulutukseen työajalla])",
            "formatString": "#,0"
          },
          {
            "name": "Kelpoisuuden tuottava koulutus (htpv)",
            "expression": "sum(Muuttujat[Osallistuminen kelpoisuuden tai pätevyyden tuottavaan koulutukseen omalla ajalla])+sum(Muuttujat[Osallistuminen kelpoisuuden tai pätevyyden tuottavaan koulutukseen työajalla])",
            "formatString": "#,0"
          },
          {
            "name": "Henkilöstökoulutus (htpv)",
            "expression": "sum(Muuttujat[Osallistuminen työantajan järjestämään henkilöstökoulutukseen omalla ajalla])+sum(Muuttujat[Osallistuminen työantajan järjestämään henkilöstökoulutukseen työajalla])",
            "formatString": "#,0"
          },
          {
            "name": "Muu täydennyskoulutus (htpv)",
            "expression": "sum(Muuttujat[Osallistuminen muuhun toimintaan omalla ajalla])+sum(Muuttujat[Osallistuminen muuhun toimintaan työajalla])",
            "formatString": "#,0"
          },
          {
            "name": "Asiantuntijavaihto (htpv)",
            "expression": "sum(Muuttujat[Osallistuminen kotimaiseen tai kansainväliseen asiantuntijavaihtoon omalla ajalla])+sum(Muuttujat[Osallistuminen kotimaiseen tai kansainväliseen asiantuntijavaihtoon työajalla])",
            "formatString": "#,0"
          },
          {
            "name": "Tutkintotavoitteinen koulutus (%)",
            "expression": "[Tutkintotavoitteinen koulutus (htpv)]/([Asiantuntijavaihto (htpv)]+[Henkilöstökoulutus (htpv)]+[Kelpoisuuden tuottava koulutus (htpv)]+[Muu täydennyskoulutus (htpv)]+[Tutkintotavoitteinen koulutus (htpv)])",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Kelpoisuuden tuottava koulutus (%)",
            "expression": "[Kelpoisuuden tuottava koulutus (htpv)]/([Asiantuntijavaihto (htpv)]+[Henkilöstökoulutus (htpv)]+[Kelpoisuuden tuottava koulutus (htpv)]+[Muu täydennyskoulutus (htpv)]+[Tutkintotavoitteinen koulutus (htpv)])",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Henkilöstökoulutus (%)",
            "expression": "[Henkilöstökoulutus (htpv)]/([Asiantuntijavaihto (htpv)]+[Henkilöstökoulutus (htpv)]+[Kelpoisuuden tuottava koulutus (htpv)]+[Muu täydennyskoulutus (htpv)]+[Tutkintotavoitteinen koulutus (htpv)])",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Muu täydennyskoulutus (%)",
            "expression": "[Muu täydennyskoulutus (htpv)]/([Asiantuntijavaihto (htpv)]+[Henkilöstökoulutus (htpv)]+[Kelpoisuuden tuottava koulutus (htpv)]+[Muu täydennyskoulutus (htpv)]+[Tutkintotavoitteinen koulutus (htpv)])",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Asiantuntijavaihto (%)",
            "expression": "[Asiantuntijavaihto (htpv)]/([Asiantuntijavaihto (htpv)]+[Henkilöstökoulutus (htpv)]+[Kelpoisuuden tuottava koulutus (htpv)]+[Muu täydennyskoulutus (htpv)]+[Tutkintotavoitteinen koulutus (htpv)])",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Antal lärare (i datainsamling)",
            "expression": "COUNTROWS(Muuttujat)",
            "formatString": "#,0"
          },
          {
            "name": "Number of teachers (in data collection)",
            "expression": "COUNTROWS(Muuttujat)",
            "formatString": "#,0"
          },
          {
            "name": "Participated in continuing ed. or expert exchange program",
            "expression": "sum(Muuttujat[Täydennyskoulutus tai asiantuntijavaihto])",
            "formatString": "#,0"
          },
          {
            "name": "Education that leads to a degree (md)",
            "expression": "sum(Muuttujat[Osallistuminen tutkintotavoitteeseen omalla ajalla])+sum(Muuttujat[Osallistuminen tutkintotavoitteeseen koulutukseen työajalla])",
            "formatString": "#,0"
          },
          {
            "name": "Education that leads to a degree (%)",
            "expression": "[Tutkintotavoitteinen koulutus (htpv)]/([Asiantuntijavaihto (htpv)]+[Henkilöstökoulutus (htpv)]+[Kelpoisuuden tuottava koulutus (htpv)]+[Muu täydennyskoulutus (htpv)]+[Tutkintotavoitteinen koulutus (htpv)])",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Education that leads to a qualification (md)",
            "expression": "sum(Muuttujat[Osallistuminen kelpoisuuden tai pätevyyden tuottavaan koulutukseen omalla ajalla])+sum(Muuttujat[Osallistuminen kelpoisuuden tai pätevyyden tuottavaan koulutukseen työajalla])",
            "formatString": "#,0"
          },
          {
            "name": "Education that leads to a qualification (%)",
            "expression": "[Kelpoisuuden tuottava koulutus (htpv)]/([Asiantuntijavaihto (htpv)]+[Henkilöstökoulutus (htpv)]+[Kelpoisuuden tuottava koulutus (htpv)]+[Muu täydennyskoulutus (htpv)]+[Tutkintotavoitteinen koulutus (htpv)])",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Staff training (md)",
            "expression": "sum(Muuttujat[Osallistuminen työantajan järjestämään henkilöstökoulutukseen omalla ajalla])+sum(Muuttujat[Osallistuminen työantajan järjestämään henkilöstökoulutukseen työajalla])",
            "formatString": "#,0"
          },
          {
            "name": "Staff training (%)",
            "expression": "[Henkilöstökoulutus (htpv)]/([Asiantuntijavaihto (htpv)]+[Henkilöstökoulutus (htpv)]+[Kelpoisuuden tuottava koulutus (htpv)]+[Muu täydennyskoulutus (htpv)]+[Tutkintotavoitteinen koulutus (htpv)])",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Expert exchange program (md)",
            "expression": "sum(Muuttujat[Osallistuminen kotimaiseen tai kansainväliseen asiantuntijavaihtoon omalla ajalla])+sum(Muuttujat[Osallistuminen kotimaiseen tai kansainväliseen asiantuntijavaihtoon työajalla])",
            "formatString": "#,0"
          },
          {
            "name": "Expert exchange program (%)",
            "expression": "[Asiantuntijavaihto (htpv)]/([Asiantuntijavaihto (htpv)]+[Henkilöstökoulutus (htpv)]+[Kelpoisuuden tuottava koulutus (htpv)]+[Muu täydennyskoulutus (htpv)]+[Tutkintotavoitteinen koulutus (htpv)])",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Other continuing education (md)",
            "expression": "sum(Muuttujat[Osallistuminen muuhun toimintaan omalla ajalla])+sum(Muuttujat[Osallistuminen muuhun toimintaan työajalla])",
            "formatString": "#,0"
          },
          {
            "name": "Other continuing education (%)",
            "expression": "[Muu täydennyskoulutus (htpv)]/([Asiantuntijavaihto (htpv)]+[Henkilöstökoulutus (htpv)]+[Kelpoisuuden tuottava koulutus (htpv)]+[Muu täydennyskoulutus (htpv)]+[Tutkintotavoitteinen koulutus (htpv)])",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Deltagit i kompletterande utbildning eller expertutbyte",
            "expression": "sum(Muuttujat[Täydennyskoulutus tai asiantuntijavaihto])",
            "formatString": "#,0"
          },
          {
            "name": "Andel som deltagit",
            "expression": "[Osallistunut täydennyskoulutukseen tai asiantuntijavaihtoon]/([Opettajien lukumäärä (tiedonkeruussa)])",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Percentage of participants",
            "expression": "[Osallistunut täydennyskoulutukseen tai asiantuntijavaihtoon]/([Opettajien lukumäärä (tiedonkeruussa)])",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Examensinriktad utbildning (dv)",
            "expression": "sum(Muuttujat[Osallistuminen tutkintotavoitteeseen omalla ajalla])+sum(Muuttujat[Osallistuminen tutkintotavoitteeseen koulutukseen työajalla])",
            "formatString": "#,0"
          },
          {
            "name": "Examensinriktad utbildning (%)",
            "expression": "[Tutkintotavoitteinen koulutus (htpv)]/([Asiantuntijavaihto (htpv)]+[Henkilöstökoulutus (htpv)]+[Kelpoisuuden tuottava koulutus (htpv)]+[Muu täydennyskoulutus (htpv)]+[Tutkintotavoitteinen koulutus (htpv)])",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Utbildning som ger behörighet (dv)",
            "expression": "sum(Muuttujat[Osallistuminen kelpoisuuden tai pätevyyden tuottavaan koulutukseen omalla ajalla])+sum(Muuttujat[Osallistuminen kelpoisuuden tai pätevyyden tuottavaan koulutukseen työajalla])",
            "formatString": "#,0"
          },
          {
            "name": "Utbildning som ger behörighet (%)",
            "expression": "[Kelpoisuuden tuottava koulutus (htpv)]/([Asiantuntijavaihto (htpv)]+[Henkilöstökoulutus (htpv)]+[Kelpoisuuden tuottava koulutus (htpv)]+[Muu täydennyskoulutus (htpv)]+[Tutkintotavoitteinen koulutus (htpv)])",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Personalutbildning (dv)",
            "expression": "sum(Muuttujat[Osallistuminen työantajan järjestämään henkilöstökoulutukseen omalla ajalla])+sum(Muuttujat[Osallistuminen työantajan järjestämään henkilöstökoulutukseen työajalla])",
            "formatString": "#,0"
          },
          {
            "name": "Personalutbildning (%)",
            "expression": "[Henkilöstökoulutus (htpv)]/([Asiantuntijavaihto (htpv)]+[Henkilöstökoulutus (htpv)]+[Kelpoisuuden tuottava koulutus (htpv)]+[Muu täydennyskoulutus (htpv)]+[Tutkintotavoitteinen koulutus (htpv)])",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Annan kompletterande utbildning (dv)",
            "expression": "sum(Muuttujat[Osallistuminen muuhun toimintaan omalla ajalla])+sum(Muuttujat[Osallistuminen muuhun toimintaan työajalla])",
            "formatString": "#,0"
          },
          {
            "name": "Annan kompletterande utbildning (%)",
            "expression": "[Muu täydennyskoulutus (htpv)]/([Asiantuntijavaihto (htpv)]+[Henkilöstökoulutus (htpv)]+[Kelpoisuuden tuottava koulutus (htpv)]+[Muu täydennyskoulutus (htpv)]+[Tutkintotavoitteinen koulutus (htpv)])",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Expertutbyte (dv)",
            "expression": "sum(Muuttujat[Osallistuminen kotimaiseen tai kansainväliseen asiantuntijavaihtoon omalla ajalla])+sum(Muuttujat[Osallistuminen kotimaiseen tai kansainväliseen asiantuntijavaihtoon työajalla])",
            "formatString": "#,0"
          },
          {
            "name": "Expertutbyte (%)",
            "expression": "[Asiantuntijavaihto (htpv)]/([Asiantuntijavaihto (htpv)]+[Henkilöstökoulutus (htpv)]+[Kelpoisuuden tuottava koulutus (htpv)]+[Muu täydennyskoulutus (htpv)]+[Tutkintotavoitteinen koulutus (htpv)])",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Opettajien viikkotuntien keskiarvo",
            "expression": "CALCULATE(AVERAGE(Muuttujat[Opettajan tunnit]),FILTER(Muuttujat,[Opettajan tunnit]<>0))",
            "formatString": "0.0"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "v_f_tab_opettajat_7_3"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[v_f_tab_opettajat_7_3].* FROM [dbo].[v_f_tab_opettajat_7_3] "
          }
        ]
      },
      {
        "name": "Sarakeleveys",
        "isHidden": true,
        "columns": [
          {
            "name": "Sarakeleveys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Sarakeleveys"
          },
          {
            "name": "leveys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "leveys"
          }
        ],
        "partitions": [
          {
            "name": "Sarakeleveys",
            "source": {
              "query": "SELECT [dbo].[Sarakeleveys].* \t\tFROM [dbo].[Sarakeleveys]",
              "dataSource": "SqlServer DWITESTVIPUSQL VipunenTK"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization"
              },
              {
                "name": "TableWidgetSerialization"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Sarakeleveys"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "      SELECT [dbo].[Sarakeleveys].*   FROM [dbo].[Sarakeleveys] "
          }
        ]
      }
    ],
    "cultures": [
      {
        "name": "en-US",
        "translations": {
          "model": {
            "name": "Model",
            "tables": [
              {
                "name": "Muuttujat",
                "translatedCaption": "Variables",
                "columns": [
                  {
                    "name": "Koodit Oppil maakunta",
                    "translatedCaption": "Codes Region of the institution",
                    "translatedDisplayFolder": "Code variables"
                  }
                ]
              }
            ]
          }
        }
      },
      {
        "name": "sv-SE",
        "translations": {
          "model": {
            "name": "Model",
            "tables": [
              {
                "name": "Muuttujat",
                "translatedCaption": "Variabler",
                "columns": [
                  {
                    "name": "Koodit Oppil maakunta",
                    "translatedCaption": "Kod Läroanstaltens landskap",
                    "translatedDisplayFolder": "Kodvariabler"
                  }
                ]
              }
            ]
          }
        }
      }
    ],
    "perspectives": [
      {
        "name": "Perus",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Oppilaitoksen maakunta"
              },
              {
                "name": "Ikäryhmä"
              },
              {
                "name": "Kouluttautunut mentoriksi"
              },
              {
                "name": "Toiminut mentorina"
              },
              {
                "name": "Tehtävätyyppi"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Koulutus- ja kehittämissuunnitelma"
              },
              {
                "name": "Oppilaitoksen opetuskieli"
              },
              {
                "name": "Sukupuoli"
              },
              {
                "name": "Ollut mentoroitavana"
              }
            ],
            "measures": [
              {
                "name": "Opettajien lukumäärä (tiedonkeruussa)"
              },
              {
                "name": "Osallistuneiden osuus vastanneista"
              },
              {
                "name": "Osallistunut täydennyskoulutukseen tai asiantuntijavaihtoon"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Aika",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Oppilaitoksen maakunta"
              },
              {
                "name": "Ikäryhmä"
              },
              {
                "name": "Tehtävätyyppi"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Oppilaitoksen opetuskieli"
              },
              {
                "name": "Sukupuoli"
              }
            ],
            "measures": [
              {
                "name": "Asiantuntijavaihto (htpv)"
              },
              {
                "name": "Henkilöstökoulutus (htpv)"
              },
              {
                "name": "Tutkintotavoitteinen koulutus (htpv)"
              },
              {
                "name": "Tutkintotavoitteinen koulutus (%)"
              },
              {
                "name": "Muu täydennyskoulutus (htpv)"
              },
              {
                "name": "Asiantuntijavaihto (%)"
              },
              {
                "name": "Henkilöstökoulutus (%)"
              },
              {
                "name": "Kelpoisuuden tuottava koulutus (htpv)"
              },
              {
                "name": "Muu täydennyskoulutus (%)"
              },
              {
                "name": "Kelpoisuuden tuottava koulutus (%)"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "PerusSV",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Läroanstaltens landskap"
              },
              {
                "name": "Läroanstaltens undervisningsspråk"
              },
              {
                "name": "Uppgiftstyp"
              },
              {
                "name": "Statistikår"
              },
              {
                "name": "Kön"
              },
              {
                "name": "Åldersgrupp"
              }
            ],
            "measures": [
              {
                "name": "Andel som deltagit"
              },
              {
                "name": "Antal lärare (i datainsamling)"
              },
              {
                "name": "Deltagit i kompletterande utbildning eller expertutbyte"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "PerusEN",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Region of the institution"
              },
              {
                "name": "Age group"
              },
              {
                "name": "Type of task"
              },
              {
                "name": "Statistical year"
              },
              {
                "name": "Gender"
              },
              {
                "name": "Language of the institution"
              }
            ],
            "measures": [
              {
                "name": "Participated in continuing ed. or expert exchange program"
              },
              {
                "name": "Number of teachers (in data collection)"
              },
              {
                "name": "Percentage of participants"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "AikaSV",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Läroanstaltens landskap"
              },
              {
                "name": "Läroanstaltens undervisningsspråk"
              },
              {
                "name": "Uppgiftstyp"
              },
              {
                "name": "Statistikår"
              },
              {
                "name": "Kön"
              },
              {
                "name": "Åldersgrupp"
              }
            ],
            "measures": [
              {
                "name": "Annan kompletterande utbildning (%)"
              },
              {
                "name": "Personalutbildning (dv)"
              },
              {
                "name": "Utbildning som ger behörighet (%)"
              },
              {
                "name": "Utbildning som ger behörighet (dv)"
              },
              {
                "name": "Annan kompletterande utbildning (dv)"
              },
              {
                "name": "Examensinriktad utbildning (%)"
              },
              {
                "name": "Examensinriktad utbildning (dv)"
              },
              {
                "name": "Expertutbyte (%)"
              },
              {
                "name": "Expertutbyte (dv)"
              },
              {
                "name": "Personalutbildning (%)"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "AikaEN",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Region of the institution"
              },
              {
                "name": "Age group"
              },
              {
                "name": "Type of task"
              },
              {
                "name": "Statistical year"
              },
              {
                "name": "Gender"
              },
              {
                "name": "Language of the institution"
              }
            ],
            "measures": [
              {
                "name": "Education that leads to a degree (%)"
              },
              {
                "name": "Education that leads to a degree (md)"
              },
              {
                "name": "Education that leads to a qualification (md)"
              },
              {
                "name": "Expert exchange program (%)"
              },
              {
                "name": "Staff training (md)"
              },
              {
                "name": "Expert exchange program (md)"
              },
              {
                "name": "Other continuing education (%)"
              },
              {
                "name": "Other continuing education (md)"
              },
              {
                "name": "Education that leads to a qualification (%)"
              },
              {
                "name": "Staff training (%)"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      }
    ],
    "roles": [
      {
        "name": "Testi",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "DWI\\T_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1732"
          },
          {
            "memberName": "dwi\\Z_DWIPVIPURD_Allow_F_Drive",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-5333"
          },
          {
            "memberName": "DWI\\Z_P_Antero_Read_TAB",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-4156"
          },
          {
            "memberName": "DWI\\Z_T_Antero_Read_TAB",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-4155"
          }
        ]
      },
      {
        "name": "Tuotanto",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "DWI\\P_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1733"
          },
          {
            "memberName": "DWI\\Z_P_Antero_Read_TAB",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-4156"
          },
          {
            "memberName": "DWI\\Z_T_Antero_Read_TAB",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-4155"
          }
        ]
      }
    ]
  }
}
