{
  "name": "SemanticModel",
  "compatibilityLevel": 1200,
  "model": {
    "culture": "fi-FI",
    "dataSources": [
      {
        "name": "SqlServer dwitvipusql22 ANTERO",
        "connectionString": "Provider=SQLOLEDB.1;Data Source=dwitvipusql22;Initial Catalog=ANTERO;Integrated Security=SSPI;Persist Security Info=false",
        "impersonationMode": "impersonateServiceAccount",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "Sarakeleveys",
        "columns": [
          {
            "name": "Sarakeleveys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Sarakeleveys",
            "sourceProviderType": "Char"
          },
          {
            "name": "leveys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "leveys",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Sarakeleveys",
            "dataView": "full",
            "source": {
              "query": " SELECT [dw].[Sarakeleveys].* FROM [dw].[Sarakeleveys] ",
              "dataSource": "SqlServer dwitvipusql22 ANTERO"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dw].[Sarakeleveys].* FROM [dw].[Sarakeleveys] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Sarakeleveys"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dw"
          }
        ]
      },
      {
        "name": "Muuttujat",
        "columns": [
          {
            "name": "Sukupuoli",
            "dataType": "string",
            "sourceColumn": "Sukupuoli",
            "sourceProviderType": "WChar",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Sektori (hakukohde)",
            "dataType": "string",
            "sourceColumn": "Sektori (hakukohde)",
            "sourceProviderType": "WChar",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "yo",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "yo",
            "sourceProviderType": "Integer"
          },
          {
            "name": "ensisijainen_hakija",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ensisijainen_hakija",
            "sourceProviderType": "Integer"
          },
          {
            "name": "valittu",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "valittu",
            "sourceProviderType": "Integer"
          },
          {
            "name": "vastaanottanut",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "vastaanottanut",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Suoritusvuosi (ylioppilastutkinto)",
            "dataType": "string",
            "sourceColumn": "Suoritusvuosi (ylioppilastutkinto)",
            "displayFolder": "Aikamuuttujat"
          },
          {
            "name": "Suorituskausi (ylioppilastutkinto)",
            "dataType": "string",
            "sourceColumn": "Suorituskausi (ylioppilastutkinto)",
            "displayFolder": "Aikamuuttujat"
          },
          {
            "name": "henkilo_oid",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "henkilo_oid"
          },
          {
            "name": "Välitön siirtyminen",
            "dataType": "string",
            "sourceColumn": "Välitön siirtyminen",
            "displayFolder": "Hakumuuttujat"
          }
        ],
        "partitions": [
          {
            "name": "v_haku_ja_valinta_kk_ytl",
            "dataView": "full",
            "source": {
              "query": " \t\t\t\tSELECT [dw].[v_haku_ja_valinta_kk_ytl].*   FROM [dw].[v_haku_ja_valinta_kk_ytl] ",
              "dataSource": "SqlServer dwitvipusql22 ANTERO"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Suoritusvuosi (ylioppilastutkinto)</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>271</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Suorituskausi (ylioppilastutkinto)</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>270</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Sukupuoli</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>109</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Sektori (hakukohde)</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>182</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>yo</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>56</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ensisijainen_hakija</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>172</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>henkilo_oid</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>121</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>valittu</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>82</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>vastaanottanut</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>142</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Välitön siirtyminen</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>171</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Suoritusvuosi (ylioppilastutkinto)</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Suorituskausi (ylioppilastutkinto)</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Sukupuoli</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Sektori (hakukohde)</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>yo</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ensisijainen_hakija</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>5</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>henkilo_oid</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>8</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>valittu</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>6</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>vastaanottanut</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>7</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Välitön siirtyminen</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>9</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Suoritusvuosi (ylioppilastutkinto)</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Suorituskausi (ylioppilastutkinto)</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>henkilo_oid</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Välitön siirtyminen</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Ylioppilaat",
            "expression": [
              "",
              "var taulu = ADDCOLUMNS(SUMMARIZE(Muuttujat,[Suoritusvuosi (ylioppilastutkinto)],[Suorituskausi (ylioppilastutkinto)],[Sukupuoli]),\"lkm\",CALCULATE(AVERAGE([yo])))",
              "var lkm =  ROUND(SUMX(taulu,[lkm]), 0)",
              "return IF(lkm = 0, BLANK(), IF(lkm < 5, \"1-4\", MROUND(lkm, 3)))"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Välittömästi lukiosta korkeakouluihin jatkavien osuus, ensisijaiset hakijat",
            "expression": [
              "",
              "var lkm1 = CALCULATE(DISTINCTCOUNT(Muuttujat[henkilo_oid]),Muuttujat[ensisijainen_hakija]=1)",
              "var osa = IF(lkm1 = 0, BLANK(), IF(lkm1 < 5, \"1-4\", MROUND(lkm1, 3)))",
              "var kaikki = [Ylioppilaat]",
              "return IF(osa = BLANK(), BLANK(),",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, 0,",
              "CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))",
              ""
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Välittömästi lukiosta korkeakouluihin jatkavien osuus, hakijat",
            "expression": [
              "",
              "var lkm1 = CALCULATE(DISTINCTCOUNT(Muuttujat[henkilo_oid]))",
              "var osa = IF(lkm1 = 0, BLANK(), IF(lkm1 < 5, \"1-4\", MROUND(lkm1, 3)))",
              "var kaikki = [Ylioppilaat]",
              "return IF(osa = BLANK(), BLANK(),",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, 0,",
              "CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))",
              ""
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Välittömästi lukiosta korkeakouluihin jatkavien osuus, valitut",
            "expression": [
              "",
              "var lkm1 = CALCULATE(DISTINCTCOUNT(Muuttujat[henkilo_oid]),Muuttujat[valittu]=1)",
              "var osa = IF(lkm1 = 0, BLANK(), IF(lkm1 < 5, \"1-4\", MROUND(lkm1, 3)))",
              "var kaikki = [Ylioppilaat]",
              "return IF(osa = BLANK(), BLANK(),",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, 0,",
              "CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Välittömästi lukiosta korkeakouluihin jatkavien osuus, paikan vastaanottaneet",
            "expression": [
              "",
              "var lkm1 = CALCULATE(DISTINCTCOUNT(Muuttujat[henkilo_oid]),Muuttujat[vastaanottanut]=1)",
              "var osa = IF(lkm1 = 0, BLANK(), IF(lkm1 < 5, \"1-4\", MROUND(lkm1, 3)))",
              "var kaikki = [Ylioppilaat]",
              "return IF(osa = BLANK(), BLANK(),",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, 0,",
              "CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Ylioppilaat_s",
            "expression": [
              "",
              "var taulu = ADDCOLUMNS(SUMMARIZE(Muuttujat,[Suoritusvuosi (ylioppilastutkinto)],[Suorituskausi (ylioppilastutkinto)],[Sukupuoli]),\"lkm\",CALCULATE(AVERAGE([yo])))",
              "return SUMX(taulu,[lkm])"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Välittömästi lukiosta korkeakouluihin jatkavien osuus, ensisijaiset hakijat_s",
            "expression": [
              "",
              "DIVIDE(CALCULATE(DISTINCTCOUNT(Muuttujat[henkilo_oid]),Muuttujat[ensisijainen_hakija]=1),[Ylioppilaat_s])"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Välittömästi lukiosta korkeakouluihin jatkavien osuus, hakijat_s",
            "expression": [
              "",
              "DIVIDE(CALCULATE(DISTINCTCOUNT(Muuttujat[henkilo_oid])),[Ylioppilaat_s])"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Välittömästi lukiosta korkeakouluihin jatkavien osuus, valitut_s",
            "expression": [
              "",
              "DIVIDE(CALCULATE(DISTINCTCOUNT(Muuttujat[henkilo_oid]),Muuttujat[valittu]=1),[Ylioppilaat_s])"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Välittömästi lukiosta korkeakouluihin jatkavien osuus, paikan vastaanottaneet_s",
            "expression": [
              "",
              "DIVIDE(CALCULATE(DISTINCTCOUNT(Muuttujat[henkilo_oid]),Muuttujat[vastaanottanut]=1),[Ylioppilaat_s])"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " \t\t\t\tSELECT [dw].[v_haku_ja_valinta_kk_ytl].*   FROM [dw].[v_haku_ja_valinta_kk_ytl] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "v_haku_ja_valinta_kk_ytl"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dw"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Suoritusvuosi (ylioppilastutkinto)</string>",
              "      </key>",
              "      <value>",
              "        <int>271</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Suorituskausi (ylioppilastutkinto)</string>",
              "      </key>",
              "      <value>",
              "        <int>270</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Sukupuoli</string>",
              "      </key>",
              "      <value>",
              "        <int>109</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Sektori (hakukohde)</string>",
              "      </key>",
              "      <value>",
              "        <int>182</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>yo</string>",
              "      </key>",
              "      <value>",
              "        <int>56</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ensisijainen_hakija</string>",
              "      </key>",
              "      <value>",
              "        <int>172</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>henkilo_oid</string>",
              "      </key>",
              "      <value>",
              "        <int>121</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>valittu</string>",
              "      </key>",
              "      <value>",
              "        <int>82</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>vastaanottanut</string>",
              "      </key>",
              "      <value>",
              "        <int>142</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Välitön siirtyminen</string>",
              "      </key>",
              "      <value>",
              "        <int>171</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Suoritusvuosi (ylioppilastutkinto)</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Suorituskausi (ylioppilastutkinto)</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Sukupuoli</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Sektori (hakukohde)</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>yo</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ensisijainen_hakija</string>",
              "      </key>",
              "      <value>",
              "        <int>5</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>henkilo_oid</string>",
              "      </key>",
              "      <value>",
              "        <int>8</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>valittu</string>",
              "      </key>",
              "      <value>",
              "        <int>6</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>vastaanottanut</string>",
              "      </key>",
              "      <value>",
              "        <int>7</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Välitön siirtyminen</string>",
              "      </key>",
              "      <value>",
              "        <int>9</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Suoritusvuosi (ylioppilastutkinto)</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Suorituskausi (ylioppilastutkinto)</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>henkilo_oid</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Välitön siirtyminen</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      }
    ],
    "perspectives": [
      {
        "name": "Perus",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Sektori (hakukohde)"
              },
              {
                "name": "Sukupuoli"
              },
              {
                "name": "Suorituskausi (ylioppilastutkinto)"
              },
              {
                "name": "Suoritusvuosi (ylioppilastutkinto)"
              },
              {
                "name": "Välitön siirtyminen"
              }
            ],
            "measures": [
              {
                "name": "Välittömästi lukiosta korkeakouluihin jatkavien osuus, ensisijaiset hakijat"
              },
              {
                "name": "Välittömästi lukiosta korkeakouluihin jatkavien osuus, hakijat"
              },
              {
                "name": "Välittömästi lukiosta korkeakouluihin jatkavien osuus, paikan vastaanottaneet"
              },
              {
                "name": "Välittömästi lukiosta korkeakouluihin jatkavien osuus, valitut"
              },
              {
                "name": "Ylioppilaat"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      }
    ],
    "roles": [
      {
        "name": "Luku",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "DWI\\T_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1732"
          },
          {
            "memberName": "DWI\\P_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1733"
          },
          {
            "memberName": "NT AUTHORITY\\IUSR",
            "memberId": "S-1-5-17"
          },
		  {
			"memberName": "DWI\\Z_P_OPH_materials_Full_Read_No_TK_TAB",
			"memberId": "S-1-5-21-2196741920-3238685902-2581541251-5670"
		  }
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "400"
      }
    ]
  },
  "id": "SemanticModel"
}