mkdir "D:\paketit\OKM\ETL\"
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_2.20_Lukio_amm_oppis_opisk_ian_ja_aik_koul_mukaan_12.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_2.21_Lukiokoul_ja_toisen_asteen_amm_perusk_opisk_ja_tutksuor_12.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_2.7_Amm_erityisopetus_tutk_ja_opisk_jarjestajittain_12.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_2_1_Peruskoulutiedosto_11.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_2_10_Korkeakouluopiskelijoiden_aik_koulutus_11.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_2_10_Korkeakouluopiskelijoiden_aik_koulutus_12.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_2_11_Oppilaitosten_tutkintoon_johtamaton_11.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_2_11_Oppilaitosten_tutkintoon_johtamaton_12.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_2_12_Yliopistoissa_pedag_opinnot_suorittaneet_11.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_2_12_Yliopistoissa_pedag_opinnot_suorittaneet_12.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_2_13_Tutk_joht_koul_opisk_kansal_mukaan_11.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_2_13_Tutk_joht_koul_opisk_kansal_mukaan_12.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_2_14_Tutk_joht_koul_opisk_synt_maan_mukaan_11.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_2_14_Tutk_joht_koul_opisk_synt_maan_mukaan_12.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_2_15_Tutk_joht_koul_opisk_aidink_mukaan_11.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_2_15_Tutk_joht_koul_opisk_aidink_mukaan_12.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_2_16_Oppilaitokset_ja_opiskelijat_syksylla_11.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_2_2_Peruskoulun_erityisopetus_11.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_2_23_Opisk_ja_tutksuor_vanh_aseman_muk_12.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_2_3a_Lukio-_ja_amm_koulutuksen_opiskelijat_11.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_2_3a_Lukio-_ja_amm_koulutuksen_opiskelijat_12.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_2_3b_Lukio-_ja_amm_koulutuksen_opiskelijat_11.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_2_3b_Lukio-_ja_amm_koulutuksen_opiskelijat_12.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_2_3c_Lukio-_ja_amm_koulutuksen_opiskelijat_11.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_2_3c_Lukio-_ja_amm_koulutuksen_opiskelijat_12.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_2_3d_Lukio-_ja_amm_koulutuksen_opiskelijat_11.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_2_3d_Lukio-_ja_amm_koulutuksen_opiskelijat_12.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_2_4a_Amm_ koulutuksen_tutkinnot_11.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_2_4a_Amm_ koulutuksen_tutkinnot_12.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_2_4b_Amm_ koulutuksen_tutkinnot_11.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_2_4b_Amm_ koulutuksen_tutkinnot_12.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_2_4c_Amm_koulutuksen_tutkinnot_11.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_2_4c_Amm_koulutuksen_tutkinnot_12.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_2_4d_Amm_koulutuksen_tutkinnot_12.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_2_5_Lukiokoulutuksen_ainevalinnat_11.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_2_5_Lukiokoulutuksen_ainevalinnat_12.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_2_6_Amm_koul_erityisopetus_opisk_tutk_11.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_2_8a_Korkeakoulut_opiskelijat_11.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_2_8b_Korkeakoulut_opiskelijat_11.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_2_8b_Korkeakoulut_opiskelijat_12.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_2_8c_Korkeakoulut_opiskelijat_11.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_2_8c_Korkeakoulut_opiskelijat_12.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_2_8d_Korkeakoulut_opiskelijat_12.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_2_9a_Korkeakoulut_tutkinnot_11.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_2_9a_Korkeakoulut_tutkinnot_12.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_2_9b_Korkeakoulut_tutkinnot_11.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_2_9b_Korkeakoulut_tutkinnot_12.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_2_9c_Korkeakoulut_tutkinnot_11.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_2_9c_Korkeakoulut_tutkinnot_12.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_3_14_Lukio_ja_amm_opisk_mediaani_iat_12.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_3_15_Lukio_ja_amm_tutk_mediaani_iat_12.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_3_1a_Oppis_ptoim_tyollistyminen_ja_koul_kesto_11.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_3_1a_Oppis_ptoim_tyollistyminen_ja_koul_kesto_12.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_3_1b_Oppis_ptoim_tyollistyminen_ja_koul_kesto_11.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_3_1b_Oppis_ptoim_tyollistyminen_ja_koul_kesto_12.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_3_2_Oppis_ja_jatko-opinnot_11.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_3_2_Oppis_ja_jatko-opinnot_12.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_3_3_amkopisk_ja_tutksuor_opisteseuranta_11.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_3_3_Amkopisk_ja_tutksuor_opisteseuranta_11_11.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_3_3_amkopisk_ja_tutksuor_opisteseuranta_12.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_3_4_Kk_tutk_suor_mediaani_iat_ja_tutk_mediaani_ajat_11.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_3_4_Kk_tutk_suor_mediaani_iat_ja_tutk_mediaani_ajat_12.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_3_7_Tutk_suor_osuus_poistumasta_erityisopisk_11.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_3_7_Tutk_suor_osuus_poistumasta_erityisopisk_12.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_3_8_Tutk_suor_osuus_aloittaneista_erityisopisk_11.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_3_8_Tutk_suor_osuus_aloittaneista_erityisopisk_12.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_4_1_Lisaopetuksesta_sijoittuminen_11.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_4_1_Lisaopetuksesta_sijoittuminen_12.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_4_10_Vaestorakenne_aidink_muk_maakunnittain_11.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_4_10_Vaestorakenne_aidink_muk_maakunnittain_12.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_4_11_Vaeston_maassamuutto_asuinmaak_ja_tutkinnon_muk_11.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_4_12a_Tyottomat_11.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_4_12a_Tyottomat_12.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_4_12b_Tyottomat_11.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_4_12b_Tyottomat_12.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_4_2a_Vaeston_koulutusrakenne_ja_ptoim_11.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_4_2a_Vaeston_koulutusrakenne_ja_ptoim_12.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_4_2b_Vaeston_koulutusrakenne_ja_ptoim_11.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_4_2b_Vaeston_koulutusrakenne_ja_ptoim_12.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_4_2c_Vaeston_koulutusrakenne_ja_ptoim_12.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_4_3_Tutkinnon_suorittaneiden_paaasiallinen_toiminta_11.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_4_3_Tutkinnon_suorittaneiden_paaasiallinen_toiminta_12.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_4_4_Ulkom_tutk_ suor_paaasiallinen_toiminta_11.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_4_4_Ulkom_tutk_ suor_paaasiallinen_toiminta_12.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_4_7_Tutkinnot_ja_aikaisemmat_tukinnot_11.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_4_8_Tutkinnot_ja_myohemmat_tutkinnot_11.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_4_9_Vaestorakenne_kunnittain.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_ajopaketti.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_K2_17a_Ulkomaalaistaustaiset_opisk_ja_tutk_11.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_K2_17b_Ulkomaalaistaustaiset_opisk_ja_tutk_11.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_K3_10_Tutk_suor_osuus_aloittaneista_korkeakoulut_11.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_K3_10_Tutk_suor_osuus_aloittaneista_korkeakoulut_12.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_K3_11a_Tutk_suor_osuus_poistumasta_11.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_K3_11b_Tutk_suor_osuus_poistumasta_11.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_K3_12_Perusk_paattaneet_amm_tutk_suorittaneet_11.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_K3_12_Perusk_paattaneet_amm_tutk_suorittaneet_12.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_K3_13_Perusk_paattaneet_amm_tutk_suorittaneet_11.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_K3_13_Perusk_paattaneet_amm_tutk_suorittaneet_12.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_K3_9_Tutk_suor_osuus_aloittaneista_toinen_aste_11.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_K3_9_Tutk_suor_osuus_aloittaneista_toinen_aste_12.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_R4_16_Tyossakayvat_ammateittain_11.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_R4_19_Tyollisten_ammattisiirtymat.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_R4_5_Tyovoimatutk_tyolliset_11.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_R4_5_Tyovoimatutk_tyolliset_12.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_R4_6a_Tyovoimatutk_tyolliset_ja_tyottomat_11.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_R4_6a_Tyovoimatutk_tyolliset_ja_tyottomat_12.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_R4_6b_Tyovoimatutk_tyolliset_ja_tyottomat_11_11.dtsx" "D:\paketit\OKM\ETL\" /Y /R
xcopy "C:\Users\jarniemi\Documents\Visual Studio 2008\Projects\Vipunen-TK\Vipunen-TK_SSIS\sa_R4_6b_Tyovoimatutk_tyolliset_ja_tyottomat_12.dtsx" "D:\paketit\OKM\ETL\" /Y /R
