{
  "name": "SemanticModel",
  "compatibilityLevel": 1200,
  "model": {
    "culture": "fi-FI",
    "dataSources": [
      {
        "name": "SqlServer dwitestvipusql VipunenTK",
        "connectionString": "Provider=SQLNCLI11;Data Source=dwitvipusql16;Initial Catalog=VipunenTK;Integrated Security=SSPI;Persist Security Info=false",
        "impersonationMode": "impersonateAccount",
        "account": "dwi\\t_viputk_kuutio",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "Sarakeleveys",
        "isHidden": true,
        "columns": [
          {
            "name": "Sarakeleveys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Sarakeleveys"
          },
          {
            "name": "leveys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "leveys"
          }
        ],
        "partitions": [
          {
            "name": "Sarakeleveys",
            "source": {
              "query": "SELECT [dbo].[Sarakeleveys].* \t\tFROM [dbo].[Sarakeleveys]",
              "dataSource": "SqlServer dwitestvipusql VipunenTK"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization"
              },
              {
                "name": "TableWidgetSerialization"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Sarakeleveys"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "      SELECT [dbo].[Sarakeleveys].*   FROM [dbo].[Sarakeleveys] "
          }
        ]
      },
      {
        "name": "Muuttujat",
        "columns": [
          {
            "name": "Tilastovuosi",
            "dataType": "string",
            "sourceColumn": "Tilastovuosi",
            "displayFolder": "Aikamuuttujat"
          },
          {
            "name": "Oppilaitos",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Oppilaitos"
          },
          {
            "name": "Opetuksen järjestäjä",
            "dataType": "string",
            "sourceColumn": "Opetuksen järjestäjä",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Oppilaitostyypi",
            "dataType": "string",
            "sourceColumn": "Oppilaitostyypi",
            "sortByColumn": "Oppilaitostyypi jarjestys",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Oppilaitoksen omistajatyyppi",
            "dataType": "string",
            "sourceColumn": "Oppilaitoksen omistajatyyppi",
            "sortByColumn": "Oppilaitoksen omistajatyyppi jarjestys",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Oppilaitoksen opetuskieli",
            "dataType": "string",
            "sourceColumn": "Oppilaitoksen opetuskieli",
            "sortByColumn": "Oppilaitoksen opetuskieli jarjestys",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Oppilaitoksen kunta",
            "dataType": "string",
            "sourceColumn": "Oppilaitoksen kunta",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Oppilaitoksen maakunta",
            "dataType": "string",
            "sourceColumn": "Oppilaitoksen maakunta",
            "sortByColumn": "Oppilaitoksen maakunta jarjestys",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Vuosiluokka",
            "dataType": "string",
            "sourceColumn": "Vuosiluokka",
            "sortByColumn": "Vuosiluokka jarjestys",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Erityisen tuen päätös",
            "dataType": "string",
            "sourceColumn": "Erityisen tuen päätös",
            "sortByColumn": "Erityisen tuen päätös jarjestys",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Oppimäärän yksilöllistäminen",
            "dataType": "string",
            "sourceColumn": "Oppimäärän yksilöllistäminen",
            "sortByColumn": "Oppimäärän yksilöllistäminen jarjestys",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Pidennetty oppivelvollisuus",
            "dataType": "string",
            "sourceColumn": "Pidennetty oppivelvollisuus",
            "sortByColumn": "Pidennetty oppivelvollisuus jarjestys",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Joustava perusopetus",
            "dataType": "string",
            "sourceColumn": "Joustava perusopetus",
            "sortByColumn": "Joustava perusopetus jarjestys",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Kuljetusetuus",
            "dataType": "string",
            "sourceColumn": "Kuljetusetuus",
            "sortByColumn": "Kuljetusetuus jarjestys",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Majoitusetuus",
            "dataType": "string",
            "sourceColumn": "Majoitusetuus",
            "sortByColumn": "Majoitusetuus jarjestys",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Erityinen tuki",
            "dataType": "string",
            "sourceColumn": "Tehostettu tuki",
            "sortByColumn": "Tehostettu tuki jarjestys",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Tukimuoto",
            "dataType": "string",
            "sourceColumn": "Tukimuoto",
            "sortByColumn": "Tukimuoto jarjestys",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Vieraskielisyys",
            "dataType": "string",
            "sourceColumn": "Vieraskielisyys",
            "sortByColumn": "Vieraskielisyys jarjestys",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "Sukupuoli",
            "dataType": "string",
            "sourceColumn": "Sukupuoli",
            "sortByColumn": "Sukupuoli jarjestys",
            "displayFolder": "Henkilömuuttujat"
          },
          {
            "name": "lkm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "lkm"
          },
          {
            "name": "Faktataulu",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Faktataulu"
          },
          {
            "name": "Oppilaitostyypi jarjestys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Oppilaitostyypi jarjestys"
          },
          {
            "name": "Oppilaitoksen omistajatyyppi jarjestys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Oppilaitoksen omistajatyyppi jarjestys"
          },
          {
            "name": "Oppilaitoksen opetuskieli jarjestys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Oppilaitoksen opetuskieli jarjestys"
          },
          {
            "name": "Oppilaitoksen kunta jarjestys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Oppilaitoksen kunta jarjestys"
          },
          {
            "name": "Oppilaitoksen maakunta jarjestys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Oppilaitoksen maakunta jarjestys"
          },
          {
            "name": "Vuosiluokka jarjestys",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Vuosiluokka jarjestys",
            "formatString": "#,0"
          },
          {
            "name": "Erityisen tuen päätös jarjestys",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Erityisen tuen päätös jarjestys"
          },
          {
            "name": "Oppimäärän yksilöllistäminen jarjestys",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Oppimäärän yksilöllistäminen jarjestys"
          },
          {
            "name": "Pidennetty oppivelvollisuus jarjestys",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Pidennetty oppivelvollisuus jarjestys"
          },
          {
            "name": "Joustava perusopetus jarjestys",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Joustava perusopetus jarjestys"
          },
          {
            "name": "Kuljetusetuus jarjestys",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Kuljetusetuus jarjestys"
          },
          {
            "name": "Majoitusetuus jarjestys",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Majoitusetuus jarjestys"
          },
          {
            "name": "Tehostettu tuki jarjestys",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Tehostettu tuki jarjestys"
          },
          {
            "name": "Tukimuoto jarjestys",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Tukimuoto jarjestys"
          },
          {
            "name": "Vieraskielisyys jarjestys",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Vieraskielisyys jarjestys"
          },
          {
            "name": "Sukupuoli jarjestys",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Sukupuoli jarjestys"
          },
          {
            "name": "Opetuksen toteutuspaikka",
            "dataType": "string",
            "sourceColumn": "Opetuksen toteutuspaikka",
            "sortByColumn": "Opetuksen toteutuspaikka jarjestys",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Opetuksen toteutuspaikka jarjestys",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Opetuksen toteutuspaikka jarjestys"
          },
          {
            "type": "calculated",
            "name": "Erityinen tuki2",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "[Erityinen tuki]"
          },
          {
            "name": "Statistikår",
            "dataType": "string",
            "sourceColumn": "Statistikår",
            "displayFolder": "Tidsvariabler"
          },
          {
            "name": "Läroanstalt",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Läroanstalt"
          },
          {
            "name": "Undervisningsanordnare",
            "dataType": "string",
            "sourceColumn": "Utbildningsanordnare",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Läroanstaltstyp",
            "dataType": "string",
            "sourceColumn": "Läroanstaltstyp",
            "sortByColumn": "Oppilaitostyypi jarjestys",
            "displayFolder": "Organisationsvariabler"
          },
          {
            "name": "Läroanstaltens ägartyp",
            "dataType": "string",
            "sourceColumn": "Läroanstaltens ägartyp",
            "sortByColumn": "Oppilaitoksen omistajatyyppi jarjestys",
            "displayFolder": "Organisationsvariabler"
          },
          {
            "name": "Läroanstaltens undervisningsspråk",
            "dataType": "string",
            "sourceColumn": "Läroanstaltens undervisningsspråk",
            "sortByColumn": "Oppilaitoksen opetuskieli jarjestys",
            "displayFolder": "Organisationsvariabler"
          },
          {
            "name": "Läroanstaltens kommun",
            "dataType": "string",
            "sourceColumn": "Läroanstaltens kommun",
            "displayFolder": "Organisationsvariabler"
          },
          {
            "name": "Läroanstaltens landskap",
            "dataType": "string",
            "sourceColumn": "Läroanstaltens landskap",
            "sortByColumn": "Oppilaitoksen maakunta jarjestys",
            "displayFolder": "Organisationsvariabler"
          },
          {
            "name": "Årskurs",
            "dataType": "string",
            "sourceColumn": "Åldersklass",
            "sortByColumn": "Vuosiluokka jarjestys",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Beslut om särskilt stöd",
            "dataType": "string",
            "sourceColumn": "Beslut om särskilt stöd",
            "sortByColumn": "Erityisen tuen päätös jarjestys",
            "displayFolder": "Personvariabler"
          },
          {
            "name": "Undervisningens plats",
            "dataType": "string",
            "sourceColumn": "Undervisning plats",
            "sortByColumn": "Opetuksen toteutuspaikka jarjestys",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Individualiserad lärokurs",
            "dataType": "string",
            "sourceColumn": "Individualiserad lärokurs",
            "sortByColumn": "Oppimäärän yksilöllistäminen jarjestys",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Förlängd läroplikt",
            "dataType": "string",
            "sourceColumn": "Förlängd läroplikt",
            "sortByColumn": "Pidennetty oppivelvollisuus jarjestys",
            "displayFolder": "Personvariabler"
          },
          {
            "name": "Flexibel grundläggande utbildning",
            "dataType": "string",
            "sourceColumn": "Flexibel grundläggande utbildning",
            "sortByColumn": "Joustava perusopetus jarjestys",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Skolskjuts förmån",
            "dataType": "string",
            "sourceColumn": "Skolskjuts, förmån",
            "displayFolder": "Personvariabler"
          },
          {
            "name": "Inkvarteringsförmån",
            "dataType": "string",
            "sourceColumn": "Inkvarteringsförmån",
            "displayFolder": "Personvariabler"
          },
          {
            "name": "Särskilt stöd",
            "dataType": "string",
            "sourceColumn": "Intensifierat stöd",
            "sortByColumn": "Tehostettu tuki jarjestys",
            "displayFolder": "Personvariabler"
          },
          {
            "name": "Form av stöd",
            "dataType": "string",
            "sourceColumn": "Form av stöd",
            "sortByColumn": "Tukimuoto jarjestys",
            "displayFolder": "Utbildningsvariabler"
          },
          {
            "name": "Främmande modersmål",
            "dataType": "string",
            "sourceColumn": "Främmande modersmål",
            "sortByColumn": "Vieraskielisyys jarjestys",
            "displayFolder": "Personvariabler"
          },
          {
            "name": "Kön",
            "dataType": "string",
            "sourceColumn": "Kön",
            "sortByColumn": "Sukupuoli jarjestys",
            "displayFolder": "Personvariabler"
          },
          {
            "name": "Statistical year",
            "dataType": "string",
            "sourceColumn": "Statistical year",
            "displayFolder": "Time variables"
          },
          {
            "name": "Educational institution",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Educational institution"
          },
          {
            "name": "Education provider",
            "dataType": "string",
            "sourceColumn": "Education provider",
            "displayFolder": "Organisation variables"
          },
          {
            "name": "Type of institution",
            "dataType": "string",
            "sourceColumn": "Type of institution",
            "sortByColumn": "Oppilaitostyypi jarjestys",
            "displayFolder": "Organisation variables"
          },
          {
            "name": "Type of institution owner",
            "dataType": "string",
            "sourceColumn": "Type of institution owner",
            "sortByColumn": "Oppilaitoksen omistajatyyppi jarjestys",
            "displayFolder": "Organisation variables"
          },
          {
            "name": "Language of the institution",
            "dataType": "string",
            "sourceColumn": "Language of the institution",
            "sortByColumn": "Oppilaitoksen opetuskieli jarjestys",
            "displayFolder": "Organisation variables"
          },
          {
            "name": "Municipality of the institution",
            "dataType": "string",
            "sourceColumn": "Municipality of the institution",
            "displayFolder": "Organisation variables"
          },
          {
            "name": "Region of the institution",
            "dataType": "string",
            "sourceColumn": "Region of the institution",
            "sortByColumn": "Oppilaitoksen maakunta jarjestys",
            "displayFolder": "Organisation variables"
          },
          {
            "name": "Year class",
            "dataType": "string",
            "sourceColumn": "Year class",
            "sortByColumn": "Vuosiluokka jarjestys",
            "displayFolder": "Education variables"
          },
          {
            "name": "Resolution on special support",
            "dataType": "string",
            "sourceColumn": "Resolution on special support",
            "sortByColumn": "Erityisen tuen päätös jarjestys",
            "displayFolder": "Person variables"
          },
          {
            "name": "Teaching location",
            "dataType": "string",
            "sourceColumn": "Teaching location",
            "sortByColumn": "Opetuksen toteutuspaikka jarjestys",
            "displayFolder": "Education variables"
          },
          {
            "name": "Individualization of curriculum",
            "dataType": "string",
            "sourceColumn": "Individualization of curriculum",
            "sortByColumn": "Oppimäärän yksilöllistäminen jarjestys",
            "displayFolder": "Education variables"
          },
          {
            "name": "Extended compulsory ed.",
            "dataType": "string",
            "sourceColumn": "Extended compulsory ed.",
            "sortByColumn": "Pidennetty oppivelvollisuus jarjestys",
            "displayFolder": "Person variables"
          },
          {
            "name": "Flexible basic education",
            "dataType": "string",
            "sourceColumn": "Flexible basic education",
            "sortByColumn": "Joustava perusopetus jarjestys",
            "displayFolder": "Education variables"
          },
          {
            "name": "Transport benefit",
            "dataType": "string",
            "sourceColumn": "Transport benefit",
            "displayFolder": "Person variables"
          },
          {
            "name": "Accommodation benefit",
            "dataType": "string",
            "sourceColumn": "Accommodation benefit",
            "displayFolder": "Person variables"
          },
          {
            "name": "Special support",
            "dataType": "string",
            "sourceColumn": "Intensified support",
            "sortByColumn": "Tehostettu tuki jarjestys",
            "displayFolder": "Person variables"
          },
          {
            "name": "Form of support",
            "dataType": "string",
            "sourceColumn": "Form of support",
            "sortByColumn": "Tukimuoto jarjestys",
            "displayFolder": "Education variables"
          },
          {
            "name": "Foreign language",
            "dataType": "string",
            "sourceColumn": "Foreign language",
            "sortByColumn": "Vieraskielisyys jarjestys",
            "displayFolder": "Person variables"
          },
          {
            "name": "Gender",
            "dataType": "string",
            "sourceColumn": "Gender",
            "sortByColumn": "Sukupuoli jarjestys",
            "displayFolder": "Person variables"
          }
        ],
        "partitions": [
          {
            "name": "v_f_tab_perusopetuksen_erityisopetus",
            "source": {
              "query": "SELECT [dbo].[v_f_tab_perusopetuksen_erityisopetus].* \t\tFROM [dbo].[v_f_tab_perusopetuksen_erityisopetus]",
              "dataSource": "SqlServer dwitestvipusql VipunenTK"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "&lt;?xml version=\"1.0\" encoding=\"UTF-16\"?&gt;&lt;Gemini xmlns=\"TableWidgetSerialization\"&gt;&lt;AnnotationContent&gt;&lt;![CDATA[&lt;?xml version=\"1.0\"?&gt;",
                  "&lt;TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\"&gt;",
                  "  &lt;ColumnSuggestedType /&gt;",
                  "  &lt;ColumnFormat /&gt;",
                  "  &lt;ColumnAccuracy /&gt;",
                  "  &lt;ColumnCurrencySymbol /&gt;",
                  "  &lt;ColumnPositivePattern /&gt;",
                  "  &lt;ColumnNegativePattern /&gt;",
                  "  &lt;ColumnWidths&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Tilastovuosi&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;86&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Oppilaitos&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;186&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Opetuksen järjestäjä&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;131&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Oppilaitostyypi&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;101&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Oppilaitoksen omistajatyyppi&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;167&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Oppilaitoksen opetuskieli&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;147&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Oppilaitoksen kunta&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;124&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Oppilaitoksen maakunta&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;144&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Vuosiluokka&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;85&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Erityisen tuen päätös&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;132&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Opetuksen toteutuspaikka&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;156&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Oppimäärän yksilöllistäminen&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;166&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Pidennetty oppivelvollisuus&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;159&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Joustava perusopetus&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;137&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Kuljetusetuus&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;95&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Majoitusetuus&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;97&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Tehostettu tuki&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;103&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Tukimuoto&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;79&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Vieraskielisyys&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;98&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Sukupuoli&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;75&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;lkm&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;45&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Faktataulu&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;81&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Oppilaitostyypi jarjestys&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;146&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Oppilaitoksen omistajatyyppi jarjestys&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;212&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Oppilaitoksen opetuskieli jarjestys&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;192&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Oppilaitoksen kunta jarjestys&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;169&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Oppilaitoksen maakunta jarjestys&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;189&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Vuosiluokka jarjestys&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;130&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Erityisen tuen päätös jarjestys&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;177&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Opetuksen toteutuspaikka jarjestys&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;201&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Oppimäärän yksilöllistäminen jarjestys&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;211&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Pidennetty oppivelvollisuus jarjestys&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;204&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Joustava perusopetus jarjestys&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;182&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Kuljetusetuus jarjestys&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;140&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Majoitusetuus jarjestys&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;142&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Tehostettu tuki jarjestys&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;148&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Tukimuoto jarjestys&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;124&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Vieraskielisyys jarjestys&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;143&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Sukupuoli jarjestys&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;120&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Statistikår&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;78&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Läroanstalt&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;84&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Utbildningsanordnare&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;132&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Läroanstaltstyp&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;105&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Läroanstaltens ägartyp&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;142&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Läroanstaltens undervisningsspråk&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;196&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Läroanstaltens kommun&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;143&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Läroanstaltens landskap&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;146&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Åldersklass&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;83&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Beslut om särskilt stöd&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;136&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Undervisning plats&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;118&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Individualiserad lärokurs&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;146&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Förlängd läroplikt&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;112&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Flexibel grundläggande utbildning&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;190&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Skolskjuts, förmån&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;118&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Inkvarteringsförmån&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;128&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Intensifierat stöd&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;113&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Form av stöd&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;93&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Främmande modersmål&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;140&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Kön&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;48&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Statistical year&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;101&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Educational institution&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;135&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Education provider&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;120&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Type of institution&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;117&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Type of institution owner&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;150&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Language of the institution&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;159&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Municipality of the institution&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;167&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Region of the institution&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;145&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Year class&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;78&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Resolution on special support&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;170&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Teaching location&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;113&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Individualization of curriculum&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;171&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Extended compulsory ed.&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;152&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Flexible basic education&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;143&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Transport benefit&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;114&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Accommodation benefit&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;142&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Intensified support&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;121&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Form of support&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;107&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Foreign language&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;113&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Gender&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;65&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "  &lt;/ColumnWidths&gt;",
                  "  &lt;ColumnDisplayIndex&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Tilastovuosi&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;0&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Oppilaitos&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;1&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Opetuksen järjestäjä&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;2&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Oppilaitostyypi&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;3&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Oppilaitoksen omistajatyyppi&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;4&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Oppilaitoksen opetuskieli&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;5&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Oppilaitoksen kunta&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;6&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Oppilaitoksen maakunta&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;7&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Vuosiluokka&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;8&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Erityisen tuen päätös&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;9&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Opetuksen toteutuspaikka&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;10&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Oppimäärän yksilöllistäminen&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;11&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Pidennetty oppivelvollisuus&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;12&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Joustava perusopetus&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;13&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Kuljetusetuus&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;14&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Majoitusetuus&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;15&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Tehostettu tuki&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;16&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Tukimuoto&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;17&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Vieraskielisyys&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;18&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Sukupuoli&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;19&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;lkm&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;20&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Faktataulu&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;21&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Oppilaitostyypi jarjestys&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;22&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Oppilaitoksen omistajatyyppi jarjestys&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;23&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Oppilaitoksen opetuskieli jarjestys&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;24&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Oppilaitoksen kunta jarjestys&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;25&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Oppilaitoksen maakunta jarjestys&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;26&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Vuosiluokka jarjestys&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;27&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Erityisen tuen päätös jarjestys&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;28&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Opetuksen toteutuspaikka jarjestys&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;29&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Oppimäärän yksilöllistäminen jarjestys&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;30&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Pidennetty oppivelvollisuus jarjestys&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;31&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Joustava perusopetus jarjestys&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;32&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Kuljetusetuus jarjestys&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;33&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Majoitusetuus jarjestys&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;34&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Tehostettu tuki jarjestys&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;35&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Tukimuoto jarjestys&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;36&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Vieraskielisyys jarjestys&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;37&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Sukupuoli jarjestys&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;38&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Statistikår&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;39&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Läroanstalt&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;40&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Utbildningsanordnare&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;41&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Läroanstaltstyp&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;42&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Läroanstaltens ägartyp&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;43&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Läroanstaltens undervisningsspråk&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;44&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Läroanstaltens kommun&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;45&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Läroanstaltens landskap&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;46&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Åldersklass&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;47&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Beslut om särskilt stöd&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;48&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Undervisning plats&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;49&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Individualiserad lärokurs&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;50&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Förlängd läroplikt&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;51&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Flexibel grundläggande utbildning&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;52&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Skolskjuts, förmån&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;53&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Inkvarteringsförmån&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;54&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Intensifierat stöd&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;55&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Form av stöd&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;56&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Främmande modersmål&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;57&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Kön&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;58&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Statistical year&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;59&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Educational institution&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;60&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Education provider&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;61&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Type of institution&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;62&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Type of institution owner&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;63&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Language of the institution&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;64&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Municipality of the institution&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;65&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Region of the institution&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;66&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Year class&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;67&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Resolution on special support&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;68&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Teaching location&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;69&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Individualization of curriculum&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;70&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Extended compulsory ed.&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;71&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Flexible basic education&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;72&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Transport benefit&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;73&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Accommodation benefit&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;74&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Intensified support&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;75&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Form of support&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;76&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Foreign language&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;77&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Gender&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;78&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "  &lt;/ColumnDisplayIndex&gt;",
                  "  &lt;ColumnFrozen /&gt;",
                  "  &lt;ColumnChecked&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Opetuksen toteutuspaikka&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Opetuksen toteutuspaikka jarjestys&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Statistikår&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Läroanstalt&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Utbildningsanordnare&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Läroanstaltstyp&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Läroanstaltens ägartyp&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Läroanstaltens undervisningsspråk&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Läroanstaltens kommun&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Läroanstaltens landskap&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Åldersklass&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Beslut om särskilt stöd&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Undervisning plats&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Individualiserad lärokurs&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Förlängd läroplikt&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Flexibel grundläggande utbildning&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Skolskjuts, förmån&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Inkvarteringsförmån&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Intensifierat stöd&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Form av stöd&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Främmande modersmål&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Kön&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Oppilaitos&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Statistical year&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Educational institution&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Education provider&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Type of institution&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Type of institution owner&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Language of the institution&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Municipality of the institution&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Region of the institution&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Year class&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Resolution on special support&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Teaching location&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Individualization of curriculum&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Extended compulsory ed.&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Flexible basic education&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Transport benefit&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Accommodation benefit&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Intensified support&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Form of support&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Foreign language&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Gender&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Tilastovuosi&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Opetuksen järjestäjä&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Oppilaitostyypi&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Oppilaitoksen omistajatyyppi&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Oppilaitoksen opetuskieli&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Oppilaitoksen kunta&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Oppilaitoksen maakunta&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Vuosiluokka&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Erityisen tuen päätös&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Oppimäärän yksilöllistäminen&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Pidennetty oppivelvollisuus&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Joustava perusopetus&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Kuljetusetuus&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Majoitusetuus&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Tehostettu tuki&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Tukimuoto&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Vieraskielisyys&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Sukupuoli&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;lkm&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Faktataulu&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Oppilaitostyypi jarjestys&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Oppilaitoksen omistajatyyppi jarjestys&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Oppilaitoksen opetuskieli jarjestys&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Oppilaitoksen kunta jarjestys&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Oppilaitoksen maakunta jarjestys&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Vuosiluokka jarjestys&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Erityisen tuen päätös jarjestys&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Oppimäärän yksilöllistäminen jarjestys&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Pidennetty oppivelvollisuus jarjestys&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Joustava perusopetus jarjestys&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Kuljetusetuus jarjestys&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Majoitusetuus jarjestys&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Tehostettu tuki jarjestys&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Tukimuoto jarjestys&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Vieraskielisyys jarjestys&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Sukupuoli jarjestys&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "  &lt;/ColumnChecked&gt;",
                  "  &lt;ColumnFilter /&gt;",
                  "  &lt;SelectionFilter /&gt;",
                  "  &lt;FilterParameters /&gt;",
                  "  &lt;IsSortDescending&gt;false&lt;/IsSortDescending&gt;",
                  "&lt;/TableWidgetGridSerialization&gt;]]&gt;&lt;/AnnotationContent&gt;&lt;/Gemini&gt;"
                ]
              },
              {
                "name": "TableWidgetSourceTable"
              },
              {
                "name": "QueryEditorSerialization"
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Kaikki oppilaat",
            "expression": "calculate([Kaikki oppilaat2],all(Muuttujat[Erityinen tuki]),all(Muuttujat[Erityinen tuki2]))",
            "formatString": "#,0"
          },
          {
            "name": "Erityisen tuen oppilaat",
            "expression": "calculate([Kaikki oppilaat2],Muuttujat[Erityisen tuen päätös]=\"Erityisen tuen päätös\")",
            "formatString": "#,0"
          },
          {
            "name": "Tehostetun tuen oppilaat",
            "expression": "calculate([Kaikki oppilaat2],Muuttujat[Erityinen tuki]=\"Tehostetun tuen oppimissuunnitelma\",Muuttujat[Erityinen tuki2]=\"Tehostetun tuen oppimissuunnitelma\")",
            "formatString": "#,0"
          },
          {
            "name": "Vieraskieliset erityisen tuen oppilaat",
            "expression": "calculate([Kaikki oppilaat2],Muuttujat[Vieraskielisyys]=\"Vieraskieliset (äidinkieli muu kuin suomi, ruotsi, saame tai romani ja viittomakieli)\",Muuttujat[Erityisen tuen päätös]=\"Erityisen tuen päätös\")",
            "formatString": "#,0"
          },
          {
            "name": "Kaikki vieraskieliset oppilaat",
            "expression": "calculate([Kaikki oppilaat2],Muuttujat[Vieraskielisyys]=\"Vieraskieliset (äidinkieli muu kuin suomi, ruotsi, saame tai romani ja viittomakieli)\",all(Muuttujat[Erityinen tuki]),all(Muuttujat[Erityinen tuki2]))",
            "formatString": "#,0"
          },
          {
            "name": "Vieraskielisten erityisen tuen oppilaiden osuus kaikista vieraskielisistä",
            "expression": [
              "var osa = [Vieraskieliset erityisen tuen oppilaat]",
              "var kaikki = [Kaikki vieraskieliset oppilaat]",
              "return IF(osa = BLANK(), BLANK(),\t",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, \"0.0 %\"",
              ", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Erityisen tuen oppilaiden osuus kaikista oppilaista",
            "expression": [
              "var osa = [Erityisen tuen oppilaat]",
              "var kaikki = [Kaikki oppilaat]",
              "return IF(osa = BLANK(), BLANK(),\t",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, \"0.0 %\"",
              ", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Tehostetun tuen oppilaiden osuus kaikista oppilaista",
            "expression": [
              "var osa = [Tehostetun tuen oppilaat]",
              "var kaikki = [Kaikki oppilaat]",
              "return IF(osa = BLANK(), BLANK(),\t",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, \"0.0 %\"",
              ", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Osuus kaikista erityisen tuen oppilaista",
            "expression": [
              "var osa = [Erityisen tuen oppilaat]",
              "var kaikki = CALCULATE([Kaikki oppilaat2],ALL(Muuttujat[Opetuksen toteutuspaikka]),Muuttujat[Erityisen tuen päätös]=\"Erityisen tuen päätös\")",
              "return IF(osa = BLANK(), BLANK(),\t",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, \"0.0 %\"",
              ", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Erityisen tuen oppilaiden osuus kaikista tuen piirissä olevista",
            "expression": [
              "var osa = [Erityisen tuen oppilaat]",
              "var kaikki = [Kaikki oppilaat2]",
              "return IF(osa = BLANK(), BLANK(),\t",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, \"0.0 %\"",
              ", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Osuus erityisen tuen oppilaista",
            "expression": [
              "var osa = [Erityisen tuen oppilaat]",
              "var kaikki = CALCULATE([Kaikki oppilaat2],ALL(Muuttujat[Oppimäärän yksilöllistäminen]),Muuttujat[Erityisen tuen päätös]=\"Erityisen tuen päätös\")",
              "return IF(osa = BLANK(), BLANK(),\t",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, \"0.0 %\"",
              ", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Jopo-oppilaat",
            "expression": "CALCULATE([Kaikki oppilaat2],Muuttujat[Joustava perusopetus]=\"oppilas joustavassa perusopetuksessa\")",
            "formatString": "#,0"
          },
          {
            "name": "Jopo-oppilaiden osuus kaikista oppilaista",
            "expression": [
              "var osa = [Jopo-oppilaat]",
              "var kaikki = CALCULATE([Kaikki oppilaat2],ALL(Muuttujat[Joustava perusopetus]))",
              "return IF(osa = BLANK(), BLANK(),\t",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, \"0.0 %\"",
              ", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Kuljetusetuutta saavat oppilaat",
            "expression": "CALCULATE([Kaikki oppilaat2],Muuttujat[Kuljetusetuus]=\"Kuljetusetuus\")",
            "formatString": "#,0"
          },
          {
            "name": "Majoitusetuutta saavat oppilaat",
            "expression": "CALCULATE([Kaikki oppilaat2],Muuttujat[Majoitusetuus]=\"Majoitusetuus\",all(Muuttujat[Faktataulu]))",
            "formatString": "#,0"
          },
          {
            "name": "Kuljetusetuutta saavien osuus kaikista oppilaista",
            "expression": [
              "var osa = [Kuljetusetuutta saavat oppilaat]",
              "var kaikki = [Kaikki oppilaat2]",
              "return IF(osa = BLANK(), BLANK(),\t",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, \"0.0 %\"",
              ", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Majoitusetuutta saavien osuus kaikista oppilaista",
            "expression": [
              "var osa = [Majoitusetuutta saavat oppilaat]",
              "var kaikki = [Kaikki oppilaat2]",
              "return IF(osa = BLANK(), BLANK(),\t",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, \"0.0 %\"",
              ", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Tehostetun tuen oppilaiden osuus kaikista tuen piirissä olevista",
            "expression": [
              "var osa = [Tehostetun tuen oppilaat]",
              "var kaikki = [Kaikki oppilaat2]",
              "return IF(osa = BLANK(), BLANK(),\t",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, \"0.0 %\"",
              ", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Kaikki oppilaat2",
            "expression": [
              "var summa = SUM([lkm])",
              "return IF(summa = 0, BLANK(), IF(summa < 5, \"1-4\", MROUND(summa, 3)))"
            ],
            "formatString": "#,0",
            "isHidden": true
          },
          {
            "name": "Andel som får skolskjutsförmån",
            "expression": "[Kuljetusetuutta saavien osuus kaikista oppilaista]",
            "formatString": "#,0.0 %;-#,0.0 %;#,0.0 %"
          },
          {
            "name": "Of all pupils, the share that receive transport benefit",
            "expression": "[Kuljetusetuutta saavien osuus kaikista oppilaista]",
            "formatString": "#,0.0 %;-#,0.0 %;#,0.0 %"
          },
          {
            "name": "Andel som får inkvarteringsförmån",
            "expression": "[Majoitusetuutta saavien osuus kaikista oppilaista]",
            "formatString": "#,0.0 %;-#,0.0 %;#,0.0 %"
          },
          {
            "name": "Of all pupils, the share that receive accommodation benefit",
            "expression": "[Majoitusetuutta saavien osuus kaikista oppilaista]",
            "formatString": "#,0.0 %;-#,0.0 %;#,0.0 %"
          },
          {
            "name": "Elever som får skolskjutsförmån",
            "expression": "[Kuljetusetuutta saavat oppilaat]",
            "formatString": "#,0"
          },
          {
            "name": "Pupils who receive transport benefit",
            "expression": "[Kuljetusetuutta saavat oppilaat]",
            "formatString": "#,0"
          },
          {
            "name": "Elever som får inkvarteringsförmån",
            "expression": "[Majoitusetuutta saavat oppilaat]",
            "formatString": "#,0"
          },
          {
            "name": "Pupils who receive accommodation benefit",
            "expression": "[Majoitusetuutta saavat oppilaat]",
            "formatString": "#,0"
          },
          {
            "name": "Samtliga elever",
            "expression": "[Kaikki oppilaat]",
            "formatString": "#,0"
          },
          {
            "name": "All pupils",
            "expression": "[Kaikki oppilaat]",
            "formatString": "#,0"
          },
          {
            "name": "Elever med ett främmande modersmål som får särskilt stöd",
            "expression": "calculate([Kaikki oppilaat2],Muuttujat[Vieraskielisyys]=\"Vieraskieliset (äidinkieli muu kuin suomi, ruotsi, saame tai romani ja viittomakieli)\",Muuttujat[Erityisen tuen päätös]=\"Erityisen tuen päätös\")",
            "formatString": "#,0"
          },
          {
            "name": "Foreign-language pupils receiving special support",
            "expression": "calculate([Kaikki oppilaat2],Muuttujat[Vieraskielisyys]=\"Vieraskieliset (äidinkieli muu kuin suomi, ruotsi, saame tai romani ja viittomakieli)\",Muuttujat[Erityisen tuen päätös]=\"Erityisen tuen päätös\")",
            "formatString": "#,0"
          },
          {
            "name": "Samtliga elever med ett främmande modersmål",
            "expression": "calculate([Kaikki oppilaat2],Muuttujat[Vieraskielisyys]=\"Vieraskieliset (äidinkieli muu kuin suomi, ruotsi, saame tai romani ja viittomakieli)\",all(Muuttujat[Erityinen tuki]),all(Muuttujat[Erityinen tuki2]))",
            "formatString": "#,0"
          },
          {
            "name": "All foreign-language pupils",
            "expression": "calculate([Kaikki oppilaat2],Muuttujat[Vieraskielisyys]=\"Vieraskieliset (äidinkieli muu kuin suomi, ruotsi, saame tai romani ja viittomakieli)\",all(Muuttujat[Erityinen tuki]),all(Muuttujat[Erityinen tuki2]))",
            "formatString": "#,0"
          },
          {
            "name": "Jopo-elever",
            "expression": "CALCULATE([Kaikki oppilaat2],Muuttujat[Joustava perusopetus]=\"oppilas joustavassa perusopetuksessa\")",
            "formatString": "#,0"
          },
          {
            "name": "Jopo-pupils",
            "expression": "CALCULATE([Kaikki oppilaat2],Muuttujat[Joustava perusopetus]=\"oppilas joustavassa perusopetuksessa\")",
            "formatString": "#,0"
          },
          {
            "name": "Elever som får särskilt stöd",
            "expression": "calculate([Kaikki oppilaat2],Muuttujat[Erityisen tuen päätös]=\"Erityisen tuen päätös\")",
            "formatString": "#,0"
          },
          {
            "name": "Pupils receiving special support",
            "expression": "calculate([Kaikki oppilaat2],Muuttujat[Erityisen tuen päätös]=\"Erityisen tuen päätös\")",
            "formatString": "#,0"
          },
          {
            "name": "Elever som får intensifierat stöd",
            "expression": "calculate([Kaikki oppilaat2],Muuttujat[Erityinen tuki]=\"Tehostetun tuen oppimissuunnitelma\",Muuttujat[Erityinen tuki2]=\"Tehostetun tuen oppimissuunnitelma\")",
            "formatString": "#,0"
          },
          {
            "name": "Pupils receiving intensified support",
            "expression": "calculate([Kaikki oppilaat2],Muuttujat[Erityinen tuki]=\"Tehostetun tuen oppimissuunnitelma\",Muuttujat[Erityinen tuki2]=\"Tehostetun tuen oppimissuunnitelma\")",
            "formatString": "#,0"
          },
          {
            "name": "Andel elever som får särskilt stöd",
            "expression": "[Erityisen tuen oppilaiden osuus kaikista oppilaista]",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Percentage of pupils receiving special support",
            "expression": "[Erityisen tuen oppilaiden osuus kaikista oppilaista]",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Andel elever som får intensifierat stöd",
            "expression": "[Tehostetun tuen oppilaiden osuus kaikista oppilaista]",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Percentage of pupils receiving intensified support",
            "expression": "[Tehostetun tuen oppilaiden osuus kaikista oppilaista]",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Andel jopo-elever",
            "expression": [
              "var osa = [Jopo-oppilaat]",
              "var kaikki = CALCULATE([Kaikki oppilaat2],ALL(Muuttujat[Flexibel grundläggande utbildning]))",
              "return IF(osa = BLANK(), BLANK(),\t",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, \"0.0 %\"",
              ", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Percentage of jopo-pupils",
            "expression": [
              "var osa = [Jopo-oppilaat]",
              "var kaikki = CALCULATE([Kaikki oppilaat2],ALL(Muuttujat[Flexible basic education]))",
              "return IF(osa = BLANK(), BLANK(),\t",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, \"0.0 %\"",
              ", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "The proportion of all pupils receiving special support",
            "expression": [
              "var osa = [Pupils receiving special support]",
              "var kaikki = CALCULATE([Kaikki oppilaat2],ALL(Muuttujat[Teaching location]),Muuttujat[Erityisen tuen päätös]=\"Erityisen tuen päätös\")",
              "return IF(osa = BLANK(), BLANK(),\t",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, \"0.0 %\"",
              ", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "The proportion of pupils receiving special support",
            "expression": [
              "var osa = [Pupils receiving special support]",
              "var kaikki = CALCULATE([Kaikki oppilaat2],ALL(Muuttujat[Individualization of curriculum]),Muuttujat[Erityisen tuen päätös]=\"Erityisen tuen päätös\")",
              "return IF(osa = BLANK(), BLANK(),\t",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, \"0.0 %\"",
              ", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Of all foreign-language pupils, the share that receive special support",
            "expression": "[Vieraskielisten erityisen tuen oppilaiden osuus kaikista vieraskielisistä]",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Of all pupils receiving support, the share that receive special support",
            "expression": "[Erityisen tuen oppilaiden osuus kaikista tuen piirissä olevista]",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Of all pupils receiving support, the share that receive intensified support",
            "expression": "[Tehostetun tuen oppilaiden osuus kaikista tuen piirissä olevista]",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Andel elever med ett främmande modersmål som får särskilt stöd av samtliga främmande modersmål",
            "expression": "[Vieraskielisten erityisen tuen oppilaiden osuus kaikista vieraskielisistä]",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Andel elever som får särskilt stöd av samtliga elever som får stöd",
            "expression": "[Erityisen tuen oppilaiden osuus kaikista tuen piirissä olevista]",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Andel elever som får intensifierat stöd av samtliga elever som får stöd",
            "expression": "[Tehostetun tuen oppilaiden osuus kaikista tuen piirissä olevista]",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Andel av samtliga elever som får särskilt stöd",
            "expression": [
              "var osa = [Elever som får särskilt stöd]",
              "var kaikki = CALCULATE([Kaikki oppilaat2],ALL(Muuttujat[Undervisningens plats]),Muuttujat[Erityisen tuen päätös]=\"Erityisen tuen päätös\")",
              "return IF(osa = BLANK(), BLANK(),\t",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, \"0.0 %\"",
              ", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Andel av alla elever som får särskilt stöd",
            "expression": [
              "var osa = [Elever som får särskilt stöd]",
              "var kaikki = CALCULATE([Kaikki oppilaat2],ALL(Muuttujat[Individualiserad lärokurs]),Muuttujat[Erityisen tuen päätös]=\"Erityisen tuen päätös\")",
              "return IF(osa = BLANK(), BLANK(),\t",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa = \"1-4\", IF(kaikki > 8000, \"0.0 %\"",
              ", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "osa / kaikki)))"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Erityistä tai tehostettua tukea saavien oppilaiden osuus (esiopetus)",
            "expression": [
              "var osa = calculate(calculate(sum([lkm]), Muuttujat[Erityisen tuen päätös]=\"Erityisen tuen päätös\") + calculate(sum([lkm]), Muuttujat[Erityinen tuki]=\"Tehostetun tuen oppimissuunnitelma\", Muuttujat[Erityinen tuki2]=\"Tehostetun tuen oppimissuunnitelma\"), Muuttujat[Vuosiluokka]=\"Esiopetus\", Muuttujat[Faktataulu]=\"Tehostettu tuki\")",
              "var kaikki = calculate([Kaikki oppilaat], Muuttujat[Vuosiluokka]=\"Esiopetus\", Muuttujat[Faktataulu]=\"Tehostettu tuki\")",
              "return IF(osa = 0, BLANK(),\t",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa < 5, IF(kaikki > 8000, \"0.0 %\"",
              ", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "MROUND(osa, 3) / kaikki)))"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Erityistä tai tehostettua tukea saavien oppilaiden osuus (1-9 luokat)",
            "expression": [
              "var osa = calculate(calculate(sum([lkm]), Muuttujat[Erityisen tuen päätös]=\"Erityisen tuen päätös\") + calculate(sum([lkm]), Muuttujat[Erityinen tuki]=\"Tehostetun tuen oppimissuunnitelma\", Muuttujat[Erityinen tuki2]=\"Tehostetun tuen oppimissuunnitelma\"), Muuttujat[Vuosiluokka]<>\"Esiopetus\", Muuttujat[Vuosiluokka]<>\"Lisäopetus\", Muuttujat[Faktataulu]=\"Tehostettu tuki\")",
              "var kaikki = calculate([Kaikki oppilaat], Muuttujat[Vuosiluokka]<>\"Esiopetus\", Muuttujat[Vuosiluokka]<>\"Lisäopetus\", Muuttujat[Faktataulu]=\"Tehostettu tuki\")",
              "return IF(osa = 0, BLANK(),\t",
              "IF(kaikki = \"1-4\", \"25 % – 100 %\",",
              "IF(osa < 5, IF(kaikki > 8000, \"0.0 %\"",
              ", CONCATENATE(FORMAT(1 / kaikki, \"0.0 % – \"), FORMAT(4 / kaikki, \"0.0 %\"))),",
              "MROUND(osa, 3) / kaikki)))"
            ],
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Andel elever som får intensifierat eller särskilt stöd (förskoleundervisning)",
            "expression": "[Erityistä tai tehostettua tukea saavien oppilaiden osuus (esiopetus)]",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Of all pupils in pre-primary education, the share that receive special or intensified support",
            "expression": "[Erityistä tai tehostettua tukea saavien oppilaiden osuus (esiopetus)]",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Andel elever som får intensifierat eller särskilt stöd (årskurserna 1–9)",
            "expression": "[Erityistä tai tehostettua tukea saavien oppilaiden osuus (1-9 luokat)]",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Of all pupils in grades 1–9, the share that receive special or intensified support",
            "expression": "[Erityistä tai tehostettua tukea saavien oppilaiden osuus (1-9 luokat)]",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Kaikki oppilaat_s",
            "expression": "IF([kytkin]=0, BLANK(), calculate([Kaikki oppilaat2_s],all(Muuttujat[Erityinen tuki]),all(Muuttujat[Erityinen tuki2])))",
            "formatString": "#,0"
          },
          {
            "name": "kytkin",
            "expression": "IF(LEFT(USERNAME(), 4) = \"DWI\\\", 1, 0)",
            "formatString": "0",
            "isHidden": true
          },
          {
            "name": "Erityisen tuen oppilaat_s",
            "expression": "IF([kytkin]=0, BLANK(), calculate([Kaikki oppilaat2_s],Muuttujat[Erityisen tuen päätös]=\"Erityisen tuen päätös\"))",
            "formatString": "#,0"
          },
          {
            "name": "Tehostetun tuen oppilaat_s",
            "expression": "IF([kytkin]=0, BLANK(), calculate([Kaikki oppilaat2_s],Muuttujat[Erityinen tuki]=\"Tehostetun tuen oppimissuunnitelma\",Muuttujat[Erityinen tuki2]=\"Tehostetun tuen oppimissuunnitelma\"))",
            "formatString": "#,0"
          },
          {
            "name": "Vieraskieliset erityisen tuen oppilaat_s",
            "expression": "IF([kytkin]=0, BLANK(), calculate([Kaikki oppilaat2_s],Muuttujat[Vieraskielisyys]=\"Vieraskieliset (äidinkieli muu kuin suomi, ruotsi, saame tai romani ja viittomakieli)\",Muuttujat[Erityisen tuen päätös]=\"Erityisen tuen päätös\"))",
            "formatString": "#,0"
          },
          {
            "name": "Kaikki vieraskieliset oppilaat_s",
            "expression": "IF([kytkin]=0, BLANK(), calculate([Kaikki oppilaat2_s],Muuttujat[Vieraskielisyys]=\"Vieraskieliset (äidinkieli muu kuin suomi, ruotsi, saame tai romani ja viittomakieli)\",all(Muuttujat[Erityinen tuki]),all(Muuttujat[Erityinen tuki2])))",
            "formatString": "#,0"
          },
          {
            "name": "Jopo-oppilaat_s",
            "expression": "IF([kytkin]=0, BLANK(), CALCULATE([Kaikki oppilaat2_s],Muuttujat[Joustava perusopetus]=\"oppilas joustavassa perusopetuksessa\"))",
            "formatString": "#,0"
          },
          {
            "name": "Kuljetusetuutta saavat oppilaat_s",
            "expression": "IF([kytkin]=0, BLANK(), CALCULATE([Kaikki oppilaat2_s], Muuttujat[Kuljetusetuus]=\"Kuljetusetuus\"))",
            "formatString": "#,0"
          },
          {
            "name": "Majoitusetuutta saavat oppilaat_s",
            "expression": "IF([kytkin]=0, BLANK(), CALCULATE([Kaikki oppilaat2_s], Muuttujat[Majoitusetuus]=\"Majoitusetuus\",all(Muuttujat[Faktataulu])))",
            "formatString": "#,0"
          },
          {
            "name": "Kaikki oppilaat2_s",
            "expression": "IF(SUM([lkm]) = 0, BLANK(), SUM([lkm]))",
            "formatString": "#,0",
            "isHidden": true
          },
          {
            "name": "Kuljetusetuutta saavien osuus kaikista oppilaista_s",
            "expression": "IF([kytkin]=0, BLANK(), [Kuljetusetuutta saavat oppilaat_s]/[Kaikki oppilaat2_s])",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Majoitusetuutta saavien osuus kaikista oppilaista_s",
            "expression": "IF([kytkin]=0, BLANK(), [Majoitusetuutta saavat oppilaat_s]/[Kaikki oppilaat2_s])",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Erityisen tuen oppilaiden osuus kaikista oppilaista_s",
            "expression": "IF([kytkin]=0, BLANK(), [Erityisen tuen oppilaat_s]/[Kaikki oppilaat_s])",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Tehostetun tuen oppilaiden osuus kaikista oppilaista_s",
            "expression": "IF([kytkin]=0, BLANK(), [Tehostetun tuen oppilaat_s]/[Kaikki oppilaat_s])",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Vieraskielisten erityisen tuen oppilaiden osuus kaikista vieraskielisistä_s",
            "expression": "IF([kytkin]=0, BLANK(), [Vieraskieliset erityisen tuen oppilaat_s]/[Kaikki vieraskieliset oppilaat_s])",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Jopo-oppilaiden osuus kaikista oppilaista_s",
            "expression": "IF([kytkin]=0, BLANK(), [Jopo-oppilaat_s]/CALCULATE([Kaikki oppilaat2_s],ALL(Muuttujat[Joustava perusopetus])))",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Osuus kaikista erityisen tuen oppilaista_s",
            "expression": "IF([kytkin]=0, BLANK(), [Erityisen tuen oppilaat_s]/CALCULATE([Kaikki oppilaat2_s],ALL(Muuttujat[Opetuksen toteutuspaikka]),Muuttujat[Erityisen tuen päätös]=\"Erityisen tuen päätös\"))",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Osuus erityisen tuen oppilaista_s",
            "expression": "IF([kytkin]=0, BLANK(), [Erityisen tuen oppilaat_s]/CALCULATE([Kaikki oppilaat2_s],ALL(Muuttujat[Oppimäärän yksilöllistäminen]),Muuttujat[Erityisen tuen päätös]=\"Erityisen tuen päätös\"))",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Erityisen tuen oppilaiden osuus kaikista tuen piirissä olevista_s",
            "expression": "IF([kytkin]=0, BLANK(), [Erityisen tuen oppilaat_s]/[Kaikki oppilaat2_s])",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Tehostetun tuen oppilaiden osuus kaikista tuen piirissä olevista_s",
            "expression": "IF([kytkin]=0, BLANK(), [Tehostetun tuen oppilaat_s]/[Kaikki oppilaat2_s])",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Erityistä tai tehostettua tukea saavien oppilaiden osuus (esiopetus)_s",
            "expression": "IF([kytkin]=0, BLANK(), calculate(calculate([Erityisen tuen oppilaat_s]+[Tehostetun tuen oppilaat_s],Muuttujat[Vuosiluokka]=\"Esiopetus\")/calculate([Kaikki oppilaat_s],Muuttujat[Vuosiluokka]=\"Esiopetus\"),Muuttujat[Faktataulu]=\"Tehostettu tuki\"))",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Erityistä tai tehostettua tukea saavien oppilaiden osuus (1-9 luokat)_s",
            "expression": "IF([kytkin]=0, BLANK(), calculate(calculate([Erityisen tuen oppilaat_s]+[Tehostetun tuen oppilaat_s],Muuttujat[Vuosiluokka]<>\"Esiopetus\",Muuttujat[Vuosiluokka]<>\"Lisäopetus\")/calculate([Kaikki oppilaat_s],Muuttujat[Vuosiluokka]<>\"Esiopetus\",Muuttujat[Vuosiluokka]<>\"Lisäopetus\"),Muuttujat[Faktataulu]=\"Tehostettu tuki\"))",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "v_f_tab_perusopetuksen_erityisopetus"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "      SELECT [dbo].[v_f_tab_perusopetuksen_erityisopetus].*   FROM [dbo].[v_f_tab_perusopetuksen_erityisopetus] "
          }
        ]
      }
    ],
    "cultures": [
      {
        "name": "en-US",
        "translations": {
          "model": {
            "name": "Model",
            "tables": [
              {
                "name": "Muuttujat",
                "translatedCaption": "Variables"
              }
            ]
          }
        }
      },
      {
        "name": "sv-SE",
        "translations": {
          "model": {
            "name": "Model",
            "tables": [
              {
                "name": "Muuttujat",
                "translatedCaption": "Variabler"
              }
            ]
          }
        }
      }
    ],
    "perspectives": [
      {
        "name": "Vieraskieliset",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Oppilaitoksen kunta"
              },
              {
                "name": "Oppilaitoksen maakunta"
              },
              {
                "name": "Erityinen tuki"
              },
              {
                "name": "Erityinen tuki2"
              },
              {
                "name": "Opetuksen järjestäjä"
              },
              {
                "name": "Oppilaitoksen omistajatyyppi"
              },
              {
                "name": "Pidennetty oppivelvollisuus"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Oppilaitoksen opetuskieli"
              },
              {
                "name": "Oppilaitostyypi"
              },
              {
                "name": "Vuosiluokka"
              }
            ],
            "measures": [
              {
                "name": "Vieraskieliset erityisen tuen oppilaat"
              },
              {
                "name": "Kaikki vieraskieliset oppilaat"
              },
              {
                "name": "Vieraskielisten erityisen tuen oppilaiden osuus kaikista vieraskielisistä"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Tehostettu ja erityinen",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Oppilaitoksen kunta"
              },
              {
                "name": "Oppilaitoksen maakunta"
              },
              {
                "name": "Erityinen tuki"
              },
              {
                "name": "Erityinen tuki2"
              },
              {
                "name": "Opetuksen järjestäjä"
              },
              {
                "name": "Oppilaitoksen omistajatyyppi"
              },
              {
                "name": "Pidennetty oppivelvollisuus"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Faktataulu"
              },
              {
                "name": "Oppilaitoksen opetuskieli"
              },
              {
                "name": "Oppilaitostyypi"
              },
              {
                "name": "Sukupuoli"
              },
              {
                "name": "Vuosiluokka"
              }
            ],
            "measures": [
              {
                "name": "Erityisen tuen oppilaat"
              },
              {
                "name": "Tehostetun tuen oppilaat"
              },
              {
                "name": "Erityisen tuen oppilaiden osuus kaikista oppilaista"
              },
              {
                "name": "Kaikki oppilaat"
              },
              {
                "name": "Tehostetun tuen oppilaiden osuus kaikista oppilaista"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Toteutuspaikka",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Oppilaitoksen kunta"
              },
              {
                "name": "Oppilaitoksen maakunta"
              },
              {
                "name": "Opetuksen järjestäjä"
              },
              {
                "name": "Oppilaitoksen omistajatyyppi"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Opetuksen toteutuspaikka"
              },
              {
                "name": "Faktataulu"
              },
              {
                "name": "Oppilaitoksen opetuskieli"
              },
              {
                "name": "Oppilaitostyypi"
              },
              {
                "name": "Vuosiluokka"
              }
            ],
            "measures": [
              {
                "name": "Erityisen tuen oppilaat"
              },
              {
                "name": "Osuus kaikista erityisen tuen oppilaista"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Yksilöllistäminen",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Oppilaitoksen kunta"
              },
              {
                "name": "Oppilaitoksen maakunta"
              },
              {
                "name": "Opetuksen järjestäjä"
              },
              {
                "name": "Oppilaitoksen omistajatyyppi"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Faktataulu"
              },
              {
                "name": "Oppilaitoksen opetuskieli"
              },
              {
                "name": "Oppilaitostyypi"
              },
              {
                "name": "Oppimäärän yksilöllistäminen"
              },
              {
                "name": "Vuosiluokka"
              }
            ],
            "measures": [
              {
                "name": "Erityisen tuen oppilaat"
              },
              {
                "name": "Osuus erityisen tuen oppilaista"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Tukimuoto",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Oppilaitoksen kunta"
              },
              {
                "name": "Oppilaitoksen maakunta"
              },
              {
                "name": "Opetuksen järjestäjä"
              },
              {
                "name": "Oppilaitoksen omistajatyyppi"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Faktataulu"
              },
              {
                "name": "Oppilaitoksen opetuskieli"
              },
              {
                "name": "Oppilaitostyypi"
              },
              {
                "name": "Tukimuoto"
              }
            ],
            "measures": [
              {
                "name": "Erityisen tuen oppilaat"
              },
              {
                "name": "Tehostetun tuen oppilaat"
              },
              {
                "name": "Erityisen tuen oppilaiden osuus kaikista tuen piirissä olevista"
              },
              {
                "name": "Tehostetun tuen oppilaiden osuus kaikista tuen piirissä olevista"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Jopo",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Oppilaitoksen kunta"
              },
              {
                "name": "Oppilaitoksen maakunta"
              },
              {
                "name": "Opetuksen järjestäjä"
              },
              {
                "name": "Oppilaitoksen omistajatyyppi"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Faktataulu"
              },
              {
                "name": "Oppilaitoksen opetuskieli"
              },
              {
                "name": "Oppilaitostyypi"
              },
              {
                "name": "Sukupuoli"
              }
            ],
            "measures": [
              {
                "name": "Kaikki oppilaat"
              },
              {
                "name": "Jopo-oppilaat"
              },
              {
                "name": "Jopo-oppilaiden osuus kaikista oppilaista"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Kuljetus ja majoitus",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Oppilaitoksen kunta"
              },
              {
                "name": "Oppilaitoksen maakunta"
              },
              {
                "name": "Erityisen tuen päätös"
              },
              {
                "name": "Opetuksen järjestäjä"
              },
              {
                "name": "Oppilaitoksen omistajatyyppi"
              },
              {
                "name": "Pidennetty oppivelvollisuus"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Faktataulu"
              },
              {
                "name": "Oppilaitoksen opetuskieli"
              },
              {
                "name": "Oppilaitostyypi"
              },
              {
                "name": "Vuosiluokka"
              }
            ],
            "measures": [
              {
                "name": "Kaikki oppilaat"
              },
              {
                "name": "Kuljetusetuutta saavat oppilaat"
              },
              {
                "name": "Kuljetusetuutta saavien osuus kaikista oppilaista"
              },
              {
                "name": "Majoitusetuutta saavien osuus kaikista oppilaista"
              },
              {
                "name": "Majoitusetuutta saavat oppilaat"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Kuljetus ja majoitusSV",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Beslut om särskilt stöd"
              },
              {
                "name": "Läroanstaltens landskap"
              },
              {
                "name": "Läroanstaltens undervisningsspråk"
              },
              {
                "name": "Undervisningsanordnare"
              },
              {
                "name": "Förlängd läroplikt"
              },
              {
                "name": "Läroanstaltstyp"
              },
              {
                "name": "Årskurs"
              },
              {
                "name": "Läroanstaltens kommun"
              },
              {
                "name": "Läroanstaltens ägartyp"
              },
              {
                "name": "Statistikår"
              },
              {
                "name": "Faktataulu"
              }
            ],
            "measures": [
              {
                "name": "Samtliga elever"
              },
              {
                "name": "Andel som får skolskjutsförmån"
              },
              {
                "name": "Elever som får skolskjutsförmån"
              },
              {
                "name": "Andel som får inkvarteringsförmån"
              },
              {
                "name": "Elever som får inkvarteringsförmån"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Kuljetus ja majoitusEN",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Municipality of the institution"
              },
              {
                "name": "Region of the institution"
              },
              {
                "name": "Year class"
              },
              {
                "name": "Type of institution"
              },
              {
                "name": "Education provider"
              },
              {
                "name": "Statistical year"
              },
              {
                "name": "Faktataulu"
              },
              {
                "name": "Extended compulsory ed."
              },
              {
                "name": "Language of the institution"
              },
              {
                "name": "Resolution on special support"
              },
              {
                "name": "Type of institution owner"
              }
            ],
            "measures": [
              {
                "name": "Of all pupils, the share that receive transport benefit"
              },
              {
                "name": "Pupils who receive transport benefit"
              },
              {
                "name": "All pupils"
              },
              {
                "name": "Of all pupils, the share that receive accommodation benefit"
              },
              {
                "name": "Pupils who receive accommodation benefit"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "VieraskielisetSV",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Erityinen tuki2"
              },
              {
                "name": "Läroanstaltens landskap"
              },
              {
                "name": "Läroanstaltens undervisningsspråk"
              },
              {
                "name": "Undervisningsanordnare"
              },
              {
                "name": "Förlängd läroplikt"
              },
              {
                "name": "Läroanstaltstyp"
              },
              {
                "name": "Årskurs"
              },
              {
                "name": "Särskilt stöd"
              },
              {
                "name": "Läroanstaltens kommun"
              },
              {
                "name": "Läroanstaltens ägartyp"
              },
              {
                "name": "Statistikår"
              },
              {
                "name": "Faktataulu"
              }
            ],
            "measures": [
              {
                "name": "Andel elever med ett främmande modersmål som får särskilt stöd av samtliga främmande modersmål"
              },
              {
                "name": "Elever med ett främmande modersmål som får särskilt stöd"
              },
              {
                "name": "Samtliga elever med ett främmande modersmål"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Tehostettu ja erityinenSV",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Erityinen tuki2"
              },
              {
                "name": "Läroanstaltens landskap"
              },
              {
                "name": "Läroanstaltens undervisningsspråk"
              },
              {
                "name": "Undervisningsanordnare"
              },
              {
                "name": "Förlängd läroplikt"
              },
              {
                "name": "Läroanstaltstyp"
              },
              {
                "name": "Årskurs"
              },
              {
                "name": "Särskilt stöd"
              },
              {
                "name": "Läroanstaltens kommun"
              },
              {
                "name": "Läroanstaltens ägartyp"
              },
              {
                "name": "Statistikår"
              },
              {
                "name": "Faktataulu"
              }
            ],
            "measures": [
              {
                "name": "Andel elever som får särskilt stöd"
              },
              {
                "name": "Elever som får särskilt stöd"
              },
              {
                "name": "Samtliga elever"
              },
              {
                "name": "Elever som får intensifierat stöd"
              },
              {
                "name": "Andel elever som får intensifierat stöd"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "ToteutuspaikkaSV",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Läroanstaltens landskap"
              },
              {
                "name": "Läroanstaltens undervisningsspråk"
              },
              {
                "name": "Undervisningsanordnare"
              },
              {
                "name": "Undervisningens plats"
              },
              {
                "name": "Läroanstaltstyp"
              },
              {
                "name": "Årskurs"
              },
              {
                "name": "Faktataulu"
              },
              {
                "name": "Läroanstaltens kommun"
              },
              {
                "name": "Läroanstaltens ägartyp"
              },
              {
                "name": "Statistikår"
              }
            ],
            "measures": [
              {
                "name": "Elever som får särskilt stöd"
              },
              {
                "name": "Andel av samtliga elever som får särskilt stöd"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "YksilöllistäminenSV",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Läroanstaltens landskap"
              },
              {
                "name": "Läroanstaltens undervisningsspråk"
              },
              {
                "name": "Undervisningsanordnare"
              },
              {
                "name": "Årskurs"
              },
              {
                "name": "Individualiserad lärokurs"
              },
              {
                "name": "Läroanstaltstyp"
              },
              {
                "name": "Faktataulu"
              },
              {
                "name": "Läroanstaltens kommun"
              },
              {
                "name": "Läroanstaltens ägartyp"
              },
              {
                "name": "Statistikår"
              }
            ],
            "measures": [
              {
                "name": "Elever som får särskilt stöd"
              },
              {
                "name": "Andel av alla elever som får särskilt stöd"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "TukimuotoSV",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Läroanstaltens landskap"
              },
              {
                "name": "Läroanstaltens undervisningsspråk"
              },
              {
                "name": "Undervisningsanordnare"
              },
              {
                "name": "Läroanstaltstyp"
              },
              {
                "name": "Faktataulu"
              },
              {
                "name": "Läroanstaltens kommun"
              },
              {
                "name": "Läroanstaltens ägartyp"
              },
              {
                "name": "Statistikår"
              },
              {
                "name": "Form av stöd"
              }
            ],
            "measures": [
              {
                "name": "Elever som får särskilt stöd"
              },
              {
                "name": "Elever som får intensifierat stöd"
              },
              {
                "name": "Andel elever som får intensifierat stöd av samtliga elever som får stöd"
              },
              {
                "name": "Andel elever som får särskilt stöd av samtliga elever som får stöd"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "JopoSV",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Läroanstaltens landskap"
              },
              {
                "name": "Läroanstaltens undervisningsspråk"
              },
              {
                "name": "Läroanstaltstyp"
              },
              {
                "name": "Faktataulu"
              },
              {
                "name": "Läroanstaltens kommun"
              },
              {
                "name": "Läroanstaltens ägartyp"
              },
              {
                "name": "Statistikår"
              },
              {
                "name": "Kön"
              }
            ],
            "measures": [
              {
                "name": "Samtliga elever"
              },
              {
                "name": "Jopo-elever"
              },
              {
                "name": "Andel jopo-elever"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "VieraskielisetEN",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Erityinen tuki2"
              },
              {
                "name": "Municipality of the institution"
              },
              {
                "name": "Region of the institution"
              },
              {
                "name": "Year class"
              },
              {
                "name": "Special support"
              },
              {
                "name": "Type of institution"
              },
              {
                "name": "Faktataulu"
              },
              {
                "name": "Education provider"
              },
              {
                "name": "Statistical year"
              },
              {
                "name": "Extended compulsory ed."
              },
              {
                "name": "Language of the institution"
              },
              {
                "name": "Type of institution owner"
              }
            ],
            "measures": [
              {
                "name": "Of all foreign-language pupils, the share that receive special support"
              },
              {
                "name": "All foreign-language pupils"
              },
              {
                "name": "Foreign-language pupils receiving special support"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Tehostettu ja erityinenEN",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Erityinen tuki2"
              },
              {
                "name": "Municipality of the institution"
              },
              {
                "name": "Region of the institution"
              },
              {
                "name": "Year class"
              },
              {
                "name": "Special support"
              },
              {
                "name": "Type of institution"
              },
              {
                "name": "Faktataulu"
              },
              {
                "name": "Education provider"
              },
              {
                "name": "Statistical year"
              },
              {
                "name": "Extended compulsory ed."
              },
              {
                "name": "Language of the institution"
              },
              {
                "name": "Type of institution owner"
              }
            ],
            "measures": [
              {
                "name": "All pupils"
              },
              {
                "name": "Percentage of pupils receiving intensified support"
              },
              {
                "name": "Percentage of pupils receiving special support"
              },
              {
                "name": "Pupils receiving intensified support"
              },
              {
                "name": "Pupils receiving special support"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "ToteutuspaikkaEN",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Municipality of the institution"
              },
              {
                "name": "Region of the institution"
              },
              {
                "name": "Year class"
              },
              {
                "name": "Teaching location"
              },
              {
                "name": "Type of institution"
              },
              {
                "name": "Education provider"
              },
              {
                "name": "Faktataulu"
              },
              {
                "name": "Statistical year"
              },
              {
                "name": "Language of the institution"
              },
              {
                "name": "Type of institution owner"
              }
            ],
            "measures": [
              {
                "name": "The proportion of all pupils receiving special support"
              },
              {
                "name": "Pupils receiving special support"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "YksilöllistäminenEN",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Municipality of the institution"
              },
              {
                "name": "Region of the institution"
              },
              {
                "name": "Year class"
              },
              {
                "name": "Individualization of curriculum"
              },
              {
                "name": "Type of institution"
              },
              {
                "name": "Education provider"
              },
              {
                "name": "Faktataulu"
              },
              {
                "name": "Statistical year"
              },
              {
                "name": "Language of the institution"
              },
              {
                "name": "Type of institution owner"
              }
            ],
            "measures": [
              {
                "name": "The proportion of pupils receiving special support"
              },
              {
                "name": "Pupils receiving special support"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "TukimuotoEN",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Municipality of the institution"
              },
              {
                "name": "Region of the institution"
              },
              {
                "name": "Form of support"
              },
              {
                "name": "Type of institution"
              },
              {
                "name": "Education provider"
              },
              {
                "name": "Faktataulu"
              },
              {
                "name": "Statistical year"
              },
              {
                "name": "Language of the institution"
              },
              {
                "name": "Type of institution owner"
              }
            ],
            "measures": [
              {
                "name": "Of all pupils receiving support, the share that receive intensified support"
              },
              {
                "name": "Pupils receiving intensified support"
              },
              {
                "name": "Pupils receiving special support"
              },
              {
                "name": "Of all pupils receiving support, the share that receive special support"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "JopoEN",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Municipality of the institution"
              },
              {
                "name": "Region of the institution"
              },
              {
                "name": "Type of institution"
              },
              {
                "name": "Education provider"
              },
              {
                "name": "Faktataulu"
              },
              {
                "name": "Statistical year"
              },
              {
                "name": "Language of the institution"
              },
              {
                "name": "Type of institution owner"
              },
              {
                "name": "Gender"
              }
            ],
            "measures": [
              {
                "name": "Percentage of jopo-pupils"
              },
              {
                "name": "All pupils"
              },
              {
                "name": "Jopo-pupils"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Indikaattori_esi",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Oppilaitoksen kunta"
              },
              {
                "name": "Oppilaitoksen maakunta"
              },
              {
                "name": "Opetuksen järjestäjä"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Sukupuoli"
              }
            ],
            "measures": [
              {
                "name": "Erityistä tai tehostettua tukea saavien oppilaiden osuus (esiopetus)"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Indikaattori_esiSV",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Läroanstaltens landskap"
              },
              {
                "name": "Undervisningsanordnare"
              },
              {
                "name": "Läroanstaltens kommun"
              },
              {
                "name": "Statistikår"
              },
              {
                "name": "Kön"
              }
            ],
            "measures": [
              {
                "name": "Andel elever som får intensifierat eller särskilt stöd (förskoleundervisning)"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Indikaattori_esiEN",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Municipality of the institution"
              },
              {
                "name": "Region of the institution"
              },
              {
                "name": "Education provider"
              },
              {
                "name": "Statistical year"
              },
              {
                "name": "Gender"
              }
            ],
            "measures": [
              {
                "name": "Of all pupils in pre-primary education, the share that receive special or intensified support"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Indikaattori_19",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Oppilaitoksen kunta"
              },
              {
                "name": "Oppilaitoksen maakunta"
              },
              {
                "name": "Opetuksen järjestäjä"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Sukupuoli"
              }
            ],
            "measures": [
              {
                "name": "Erityistä tai tehostettua tukea saavien oppilaiden osuus (1-9 luokat)"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Indikaattori_19SV",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Läroanstaltens landskap"
              },
              {
                "name": "Undervisningsanordnare"
              },
              {
                "name": "Läroanstaltens kommun"
              },
              {
                "name": "Statistikår"
              },
              {
                "name": "Kön"
              }
            ],
            "measures": [
              {
                "name": "Andel elever som får intensifierat eller särskilt stöd (årskurserna 1–9)"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Indikaattori_19EN",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Municipality of the institution"
              },
              {
                "name": "Region of the institution"
              },
              {
                "name": "Education provider"
              },
              {
                "name": "Statistical year"
              },
              {
                "name": "Gender"
              }
            ],
            "measures": [
              {
                "name": "Of all pupils in grades 1–9, the share that receive special or intensified support"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      }
    ],
    "roles": [
      {
        "name": "Testi",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "DWI\\T_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1732"
          },
          {
            "memberName": "DWI\\Z_P_Antero_Read_TAB",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-4156"
          },
          {
            "memberName": "DWI\\Z_T_Antero_Read_TAB",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-4155"
          },
          {
            "memberName": "DWI\\Z_P_Antero_Full_Read_TAB",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-2272"
          }
        ]
      },
      {
        "name": "Tuotanto",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "DWI\\P_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1733"
          },
          {
            "memberName": "DWI\\Z_P_Antero_Read_TAB",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-4156"
          },
          {
            "memberName": "DWI\\Z_T_Antero_Read_TAB",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-4155"
          },
          {
            "memberName": "DWI\\Z_P_Antero_Full_Read_TAB",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-2272"
          }
        ]
      }
    ]
  },
  "id": "SemanticModel"
}