{
  "name": "SemanticModel",
  "compatibilityLevel": 1200,
  "model": {
    "culture": "fi-FI",
    "dataSources": [
      {
        "name": "ANTERO",
        "connectionString": "Provider=SQLNCLI11;Data Source=dwitvipusql16;Initial Catalog=ANTERO;Integrated Security=SSPI;Persist Security Info=false",
        "impersonationMode": "impersonateServiceAccount",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "Muuttujat",
        "columns": [
          {
            "name": "Utbildningsområde",
            "dataType": "string",
            "sourceColumn": "Utbildningsområde",
            "sourceProviderType": "Char",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Field of education",
            "dataType": "string",
            "sourceColumn": "Field of education",
            "sourceProviderType": "Char",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "tili_taso0_fi",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "tili_taso0_fi"
          },
          {
            "name": "tili_taso1_fi",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "tili_taso1_fi"
          },
          {
            "name": "tili_taso2_fi",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "tili_taso2_fi"
          },
          {
            "name": "tili_taso3_fi",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "tili_taso3_fi"
          },
          {
            "name": "tili_taso4_fi",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "tili_taso4_fi"
          },
          {
            "name": "tili_taso0_sv",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "tili_taso0_sv"
          },
          {
            "name": "tili_taso1_sv",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "tili_taso1_sv"
          },
          {
            "name": "tili_taso2_sv",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "tili_taso2_sv"
          },
          {
            "name": "tili_taso3_sv",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "tili_taso3_sv"
          },
          {
            "name": "tili_taso4_sv",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "tili_taso4_sv"
          },
          {
            "name": "tili_taso0_en",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "tili_taso0_en"
          },
          {
            "name": "tili_taso1_en",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "tili_taso1_en"
          },
          {
            "name": "tili_taso2_en",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "tili_taso2_en"
          },
          {
            "name": "tili_taso3_en",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "tili_taso3_en"
          },
          {
            "name": "tili_taso4_en",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "tili_taso4_en"
          },
          {
            "name": "arvo",
            "dataType": "int64",
            "sourceColumn": "arvo",
            "formatString": "#,0.00 \"€\";-#,0.00 \"€\";#,0.00 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1035\" DisplayName=\"€ Finnish (Finland)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "Toiminto_nimi_fi",
            "dataType": "string",
            "sourceColumn": "toiminto_nimi_fi"
          },
          {
            "name": "Tilastovuosi",
            "dataType": "int64",
            "sourceColumn": "Tilastovuosi",
            "displayFolder": "Aikamuuttujat"
          },
          {
            "name": "Koulutusala",
            "dataType": "string",
            "sourceColumn": "Koulutusala",
            "sortByColumn": "Koodit_koulutusala",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Aineisto",
            "dataType": "string",
            "sourceColumn": "Aineisto"
          },
          {
            "name": "Statistikår",
            "dataType": "int64",
            "sourceColumn": "Statistikår"
          },
          {
            "name": "Universitet",
            "dataType": "string",
            "sourceColumn": "Universitet"
          },
          {
            "name": "Material typ",
            "dataType": "string",
            "sourceColumn": "Material typ"
          },
          {
            "name": "Statistical year",
            "dataType": "int64",
            "sourceColumn": "Statistical year"
          },
          {
            "name": "University",
            "dataType": "string",
            "sourceColumn": "University"
          },
          {
            "name": "Material type",
            "dataType": "string",
            "sourceColumn": "Material type"
          },
          {
            "name": "Koodit_yliopisto",
            "dataType": "string",
            "sourceColumn": "Koodit_yliopisto"
          },
          {
            "name": "Koodit_koulutusala",
            "dataType": "string",
            "sourceColumn": "Koodit_koulutusala"
          },
          {
            "name": "Koodit_aineisto",
            "dataType": "string",
            "sourceColumn": "Koodit_aineisto"
          },
          {
            "name": "tili_taso5_fi",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "tili_taso5_fi"
          },
          {
            "name": "tili_taso5_sv",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "tili_taso5_sv"
          },
          {
            "name": "tili_taso5_en",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "tili_taso5_en"
          },
          {
            "name": "Konserni",
            "dataType": "string",
            "sourceColumn": "konserni",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Ohjauksenala_sv",
            "dataType": "string",
            "sourceColumn": "Ohjauksenala_sv"
          },
          {
            "name": "Ohjauksenala_en",
            "dataType": "string",
            "sourceColumn": "Ohjauksenala_en"
          },
          {
            "name": "Ohjauksen ala",
            "dataType": "string",
            "sourceColumn": "Ohjauksenala",
            "sortByColumn": "Koodit_ohjauksenala",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "type": "calculated",
            "name": "Suodatus tilastovuosi",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "Muuttujat[Tilastovuosi]",
            "displayFolder": "Aikamuuttujat"
          },
          {
            "name": "Koodit_ohjauksenala",
            "dataType": "int64",
            "sourceColumn": "Koodit_ohjauksenala"
          },
          {
            "type": "calculated",
            "name": "Tarkennettu toiminto",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "",
              "SWITCH(TRUE(),Muuttujat[tili_taso5_fi]=\"Harjoittelu harjoittelukoulun ulkopuolella\",\"Harjoittelu harjoittelukoulun ulkopuolella\",",
              "Muuttujat[tili_taso5_fi]=\"Harjoittelu harjoittelukoulussa\",\"Harjoittelu harjoittelukoulussa\",",
              "Muuttujat[tili_taso5_fi]=\"Opettajankoulutuksen kehittäminen\",\"Opettajankoulutuksen kehittäminen\",",
              "Muuttujat[tili_taso5_fi]=\"Esiopetus\",\"Esiopetus\",",
              "Muuttujat[tili_taso5_fi]=\"Lukiokoulutus\",\"Lukiokoulutus\",",
              "Muuttujat[tili_taso5_fi]=\"Perusopetus\",\"Perusopetus\",",
              "Muuttujat[tili_taso5_fi]=\"Muut tehtävät\",\"Muut tehtävät\",",
              "Muuttujat[tili_taso5_fi]=\"Kansallisen kulttuuriperinnön tallettaminen ja ylläpito\",\"Kansallisen kulttuuriperinnön tallettaminen ja ylläpito\",",
              "Muuttujat[tili_taso5_fi]=\"Kansalliset palvelut kirjastoille sekä korkeakoulusektorille\",\"Kansalliset palvelut kirjastoille sekä korkeakoulusektorille\",",
              "Muuttujat[tili_taso5_fi]=\"Muu täydennyskoulutus\",\"Muu täydennyskoulutus\",",
              "Muuttujat[tili_taso5_fi]=\"Tutkintojen osat (maksuasetuksen mukaiset)\",\"Tutkintojen osat (maksuasetuksen mukaiset)\",",
              "Muuttujat[tili_taso5_fi]=\"Muut tutkintojen osat ja tilauskoulutus\",\"Muut tutkintojen osat ja tilauskoulutus\",",
              "Muuttujat[tili_taso5_fi]=\"Erikoistumiskoulutus\",\"Erikoistumiskoulutus\",",
              "Muuttujat[tili_taso5_fi]=\"Perustutkintokoulutus\",\"Perustutkintokoulutus\",",
              "Muuttujat[tili_taso5_fi]=\"Perustutkintojen osat\",\"Perustutkintojen osat\",",
              "Muuttujat[tili_taso5_fi]=\"Muu koulutus\",\"Muu koulutus\",",
              "Muuttujat[tili_taso5_fi]=\"Ammatillinen opettajankoulutus\",\"Ammatillinen opettajankoulutus\",",
              "Muuttujat[tili_taso5_fi]=\"Erillislakien mukaiset julkisoikeudelliset suoritteet\",\"Erillislakien mukaiset julkisoikeudelliset suoritteet\",",
              "Muuttujat[tili_taso5_fi]=\"Muut yleistoiminnot\",\"Muut yleistoiminnot\",",
              "Muuttujat[tili_taso5_fi]=\"Ylempi AMK-koulutus\",\"Ylempi AMK-koulutus\",",
              "Muuttujat[tili_taso5_fi]=\"Jatkotutkintokoulutus\",\"Jatkotutkintokoulutus\",",
              "Muuttujat[tili_taso5_fi]=\"Taiteellinen toiminta\",\"Taiteellinen toiminta\",",
              "Muuttujat[tili_taso5_fi]=\"Tutkimus- ja kehitystoiminta\",\"Tutkimus- ja kehitystoiminta\",",
              "Muuttujat[tili_taso5_fi]=\"Tieteellinen tutkimus\",\"Tieteellinen tutkimus\"",
              "",
              "\t)"
            ],
            "displayFolder": "Kustannuslaji"
          },
          {
            "type": "calculated",
            "name": "Toiminto",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "",
              "SWITCH(TRUE(),Muuttujat[tili_taso5_fi]=\"Harjoittelu harjoittelukoulun ulkopuolella\",\"Opettajankoulutus ja kehitystehtävät\",",
              "Muuttujat[tili_taso5_fi]=\"Harjoittelu harjoittelukoulussa\",\"Opettajankoulutus ja kehitystehtävät\",",
              "Muuttujat[tili_taso5_fi]=\"Opettajankoulutuksen kehittäminen\",\"Opettajankoulutus ja kehitystehtävät\",",
              "Muuttujat[tili_taso5_fi]=\"Esiopetus\",\"Opetustehtävät\",",
              "Muuttujat[tili_taso5_fi]=\"Lukiokoulutus\",\"Opetustehtävät\",",
              "Muuttujat[tili_taso5_fi]=\"Perusopetus\",\"Opetustehtävät\",",
              "Muuttujat[tili_taso5_fi]=\"Muut tehtävät\",\"Kansalliskirjasto toiminto\",",
              "Muuttujat[tili_taso5_fi]=\"Kansallisen kulttuuriperinnön tallettaminen ja ylläpito\",\"Kansalliskirjasto toiminto\",",
              "Muuttujat[tili_taso5_fi]=\"Kansalliset palvelut kirjastoille sekä korkeakoulusektorille\",\"Kansalliskirjasto toiminto\",",
              "Muuttujat[tili_taso5_fi]=\"Muu täydennyskoulutus\",\"Koulutustoiminta\",",
              "Muuttujat[tili_taso5_fi]=\"Tutkintojen osat (maksuasetuksen mukaiset)\",\"Koulutustoiminta\",",
              "Muuttujat[tili_taso5_fi]=\"Muut tutkintojen osat ja tilauskoulutus\",\"Koulutustoiminta\",",
              "Muuttujat[tili_taso5_fi]=\"Erikoistumiskoulutus\",\"Koulutustoiminta\",",
              "Muuttujat[tili_taso5_fi]=\"Perustutkintokoulutus\",\"Koulutustoiminta\",",
              "Muuttujat[tili_taso5_fi]=\"Perustutkintojen osat\",\"Koulutustoiminta\",",
              "Muuttujat[tili_taso5_fi]=\"Muu koulutus\",\"Koulutustoiminta\",",
              "Muuttujat[tili_taso5_fi]=\"Ammatillinen opettajankoulutus\",\"Koulutustoiminta\",",
              "Muuttujat[tili_taso5_fi]=\"Erillislakien mukaiset julkisoikeudelliset suoritteet\",\"Muu yhteiskunnallinen toiminta\",",
              "Muuttujat[tili_taso5_fi]=\"Muut yleistoiminnot\",\"Muu yhteiskunnallinen toiminta\",",
              "Muuttujat[tili_taso5_fi]=\"Jatkotutkintokoulutus\",\"Tutkimus ja tutkimukseen rinnastettavissa oleva taiteellinen toiminta\",",
              "Muuttujat[tili_taso5_fi]=\"Ylempi AMK-koulutus\",\"Tutkimus ja tutkimukseen rinnastettavissa oleva taiteellinen toiminta\",",
              "Muuttujat[tili_taso5_fi]=\"Taiteellinen toiminta\",\"Tutkimus ja tutkimukseen rinnastettavissa oleva taiteellinen toiminta\",",
              "Muuttujat[tili_taso5_fi]=\"Tieteellinen tutkimus\",\"Tutkimus ja tutkimukseen rinnastettavissa oleva taiteellinen toiminta\",",
              "Muuttujat[tili_taso5_fi]=\"Tutkimus- ja kehitystoiminta\",\"Tutkimus ja tutkimukseen rinnastettavissa oleva taiteellinen toiminta\"",
              "",
              "\t)"
            ],
            "displayFolder": "Kustannuslaji"
          },
          {
            "type": "calculated",
            "name": "Päätoiminto",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "",
              "SWITCH(TRUE(),Muuttujat[tili_taso5_fi]=\"Harjoittelu harjoittelukoulun ulkopuolella\",\"Harjoittelukoulu\",",
              "Muuttujat[tili_taso5_fi]=\"Harjoittelu harjoittelukoulussa\",\"Harjoittelukoulu\",",
              "Muuttujat[tili_taso5_fi]=\"Opettajankoulutuksen kehittäminen\",\"Harjoittelukoulu\",",
              "Muuttujat[tili_taso5_fi]=\"Esiopetus\",\"Harjoittelukoulu\",",
              "Muuttujat[tili_taso5_fi]=\"Lukiokoulutus\",\"Harjoittelukoulu\",",
              "Muuttujat[tili_taso5_fi]=\"Perusopetus\",\"Harjoittelukoulu\",",
              "Muuttujat[tili_taso5_fi]=\"Muut tehtävät\",\"Kansalliskirjasto toiminto\",",
              "Muuttujat[tili_taso5_fi]=\"Kansallisen kulttuuriperinnön tallettaminen ja ylläpito\",\"Kansalliskirjasto toiminto\",",
              "Muuttujat[tili_taso5_fi]=\"Kansalliset palvelut kirjastoille sekä korkeakoulusektorille\",\"Kansalliskirjasto toiminto\",",
              "Muuttujat[tili_taso5_fi]=\"Muu täydennyskoulutus\",\"Koulutustoiminta\",",
              "Muuttujat[tili_taso5_fi]=\"Tutkintojen osat (maksuasetuksen mukaiset)\",\"Koulutustoiminta\",",
              "Muuttujat[tili_taso5_fi]=\"Muut tutkintojen osat ja tilauskoulutus\",\"Koulutustoiminta\",",
              "Muuttujat[tili_taso5_fi]=\"Erikoistumiskoulutus\",\"Koulutustoiminta\",",
              "Muuttujat[tili_taso5_fi]=\"Perustutkintokoulutus\",\"Koulutustoiminta\",",
              "Muuttujat[tili_taso5_fi]=\"Muu koulutus\",\"Koulutustoiminta\",",
              "Muuttujat[tili_taso5_fi]=\"Ammatillinen opettajankoulutus\",\"Koulutustoiminta\",",
              "Muuttujat[tili_taso5_fi]=\"Perustutkintojen osat\",\"Koulutustoiminta\",",
              "Muuttujat[tili_taso5_fi]=\"Erillislakien mukaiset julkisoikeudelliset suoritteet\",\"Muu yhteiskunnallinen toiminta\",",
              "Muuttujat[tili_taso5_fi]=\"Muut yleistoiminnot\",\"Muu yhteiskunnallinen toiminta\",",
              "Muuttujat[tili_taso5_fi]=\"Jatkotutkintokoulutus\",\"Tutkimus ja tutkimukseen rinnastettavissa oleva taiteellinen toiminta\",",
              "Muuttujat[tili_taso5_fi]=\"Taiteellinen toiminta\",\"Tutkimus ja tutkimukseen rinnastettavissa oleva taiteellinen toiminta\",",
              "Muuttujat[tili_taso5_fi]=\"Tieteellinen tutkimus\",\"Tutkimus ja tutkimukseen rinnastettavissa oleva taiteellinen toiminta\",",
              "Muuttujat[tili_taso5_fi]=\"Ylempi AMK-koulutus\",\"Tutkimus ja tutkimukseen rinnastettavissa oleva taiteellinen toiminta\",",
              "Muuttujat[tili_taso5_fi]=\"Tutkimus- ja kehitystoiminta\",\"Tutkimus ja tutkimukseen rinnastettavissa oleva taiteellinen toiminta\"",
              "\t)"
            ],
            "displayFolder": "Kustannuslaji"
          },
          {
            "type": "calculated",
            "name": "Koodit_päätoiminto",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": [
              "    ",
              "SWITCH(TRUE(),Muuttujat[tili_taso5_fi]=\"Harjoittelu harjoittelukoulun ulkopuolella\",\"5\",    ",
              "Muuttujat[tili_taso5_fi]=\"Harjoittelu harjoittelukoulussa\",\"5\",    ",
              "Muuttujat[tili_taso5_fi]=\"Opettajankoulutuksen kehittäminen\",\"5\",    ",
              "Muuttujat[tili_taso5_fi]=\"Esiopetus\",\"5\",    ",
              "Muuttujat[tili_taso5_fi]=\"Lukiokoulutus\",\"5\",    ",
              "Muuttujat[tili_taso5_fi]=\"Perusopetus\",\"5\",    ",
              "Muuttujat[tili_taso5_fi]=\"Muut tehtävät\",\"6\",    ",
              "Muuttujat[tili_taso5_fi]=\"Kansallisen kulttuuriperinnön tallettaminen ja ylläpito\",\"6\",    ",
              "Muuttujat[tili_taso5_fi]=\"Kansalliset palvelut kirjastoille sekä korkeakoulusektorille\",\"6\",    ",
              "Muuttujat[tili_taso5_fi]=\"Muu koulutus\",\"1\",    ",
              "Muuttujat[tili_taso5_fi]=\"Perustutkintojen osat\",\"1\",    ",
              "Muuttujat[tili_taso5_fi]=\"Perustutkintokoulutus\",\"1\",    ",
              "Muuttujat[tili_taso5_fi]=\"Erillislakien mukaiset julkisoikeudelliset suoritteet\",\"4\",    ",
              "Muuttujat[tili_taso5_fi]=\"Yleistoiminnot\",\"4\",    ",
              "Muuttujat[tili_taso5_fi]=\"Taiteellinen toiminta\",\"3\",    ",
              "Muuttujat[tili_taso5_fi]=\"Tieteellinen ja taiteellinen jatkotutkintokoulutus\",\"2\",    ",
              "Muuttujat[tili_taso5_fi]=\"Tieteellinen tutkimus\",\"2\"    ",
              "    )"
            ]
          },
          {
            "name": "d6.erittely_nimi_fi",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "d6.erittely_nimi_fi"
          },
          {
            "name": "Korkeakoulu",
            "dataType": "string",
            "sourceColumn": "Korkeakoulu",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "tili_koodi",
            "dataType": "string",
            "sourceColumn": "tili_koodi"
          },
          {
            "name": "Sektori",
            "dataType": "string",
            "sourceColumn": "Sektori",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "type": "calculated",
            "name": "Toiminnon nimi",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "",
              "SWITCH(TRUE(),Muuttujat[Toiminto_nimi_fi]=\"Koulutustoiminta\",\"A) Koulutustoiminta\",",
              "",
              "Muuttujat[Toiminto_nimi_fi]=\"Tutkimus- ja kehitystoiminta\",\"B) Tutkimus- ja kehitystoiminta\",",
              "Muuttujat[Toiminto_nimi_fi]=\"Tutkimustoiminta\",\"B) Tutkimustoiminta\",",
              "Muuttujat[Toiminto_nimi_fi]=\"Muu yhteiskunnallinen toiminta\",\"C) Muu yhteiskunnallinen toiminta\",",
              "Muuttujat[Toiminto_nimi_fi]=\"Harjoittelukoulu\",\"D) Harjoittelukoulu\",",
              "Muuttujat[Toiminto_nimi_fi]=\"Kansalliskirjasto\",\"E) Kansalliskirjasto\",",
              "Muuttujat[Toiminto_nimi_fi]=\"Toiminnot yhteensä\",\"Toiminnot yhteensä\"",
              "\t)",
              ""
            ],
            "displayFolder": "Toimintolaji"
          }
        ],
        "partitions": [
          {
            "name": "AMK_TALOUS",
            "dataView": "full",
            "source": {
              "query": " SELECT [dw].[v_st_talous_yhteinen].* FROM [dw].[v_st_talous_yhteinen] ",
              "dataSource": "ANTERO"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit_aineisto</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>103</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit_koulutusala</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>120</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit_yliopisto</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>105</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Material type</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>93</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Utbildningsområde</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>118</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>University</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>78</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Statistical year</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>101</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Field of education</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>115</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Material typ</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>87</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Universitet</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>82</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>arvo</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>52</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso4_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>91</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso3_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>91</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso2_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>91</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso1_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>91</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso0_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>91</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso4_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>90</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso3_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>90</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso2_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>90</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso1_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>90</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso0_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>90</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso4_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>85</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso3_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>85</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso2_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>85</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso1_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>85</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso0_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>85</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Statistikår</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>78</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Aineisto</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>68</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusala</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>85</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>d6.erittely_nimi_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>116</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>toiminto_nimi_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>104</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tilastovuosi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>86</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso5_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>85</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso5_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>90</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso5_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>91</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Konserni</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>71</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Ohjauksenala</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>95</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Ohjauksenala_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>112</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Ohjauksenala_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>113</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit_ohjauksenala</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>129</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Korkeakoulu</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>88</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_koodi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>71</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Sektori</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>63</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit_aineisto</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>30</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit_koulutusala</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>29</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit_yliopisto</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>28</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Material type</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>27</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Utbildningsområde</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>University</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>26</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Statistical year</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>25</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Field of education</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Material typ</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>24</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Universitet</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>23</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>arvo</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>17</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso4_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>16</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso3_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>15</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso2_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>14</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso1_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>13</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso0_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>12</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso4_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>11</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso3_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>10</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso2_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>9</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso1_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>8</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso0_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>7</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso4_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>6</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso3_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>5</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso2_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso1_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso0_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Statistikår</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>22</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Aineisto</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>21</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusala</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>20</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>d6.erittely_nimi_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>39</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>toiminto_nimi_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>18</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tilastovuosi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>19</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso5_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>31</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso5_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>32</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso5_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>33</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Konserni</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>34</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Ohjauksenala</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>35</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Ohjauksenala_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>36</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Ohjauksenala_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>37</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit_ohjauksenala</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>38</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Korkeakoulu</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>40</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_koodi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>41</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Sektori</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>42</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Statistical year</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>arvo</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso4_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso3_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso2_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso1_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso0_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso4_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso3_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso2_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso1_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso0_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso4_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso3_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso2_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso1_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso0_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Material typ</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Universitet</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Statistikår</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Aineisto</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>toiminto_nimi_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusala</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>d6.erittely_nimi_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tilastovuosi</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>University</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Material type</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit_yliopisto</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit_koulutusala</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit_aineisto</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso5_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso5_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso5_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Ohjauksenala</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Ohjauksenala_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Ohjauksenala_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit_ohjauksenala</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Korkeakoulu</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_koodi</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Sektori</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Korkeakoulujen valtionrahoitus",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"yolaki49\", OR([tili_koodi] =\"valtio\",[tili_koodi] =\"okmperus\")) ))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\A) Liikevaihto"
          },
          {
            "name": "Muut sijoitustoiminnan tuotot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"srmuutul\",[tili_koodi] =\"MUUTTUOTOT_3\")))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\G) Sijoitustoiminta\\Varsinaisen sijoitustoiminnan tuotot"
          },
          {
            "name": "Osuus osakkuusyhtiöiden tuloksesta (voitosta/tappiosta, +/-)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"vtosuust\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\A) Liikevaihto"
          },
          {
            "name": "Suomen Akatemia",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"akatemia3\",[tili_koodi] =\"akatemia\")))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\B) Avustustuottojen jaottelu"
          },
          {
            "name": "Business Finland",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi]=\"BusinessFinland\",[tili_koodi] =\"BusinessFinland3\")))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\B) Avustustuottojen jaottelu"
          },
          {
            "name": "Muu OKM",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"muuokm3\",[tili_koodi] =\"muuokm\")))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\B) Avustustuottojen jaottelu"
          },
          {
            "name": "Muu valtio (pl. Business Finland, Akatemia, Sosiaaliturvarahastot ja muu OKM)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"muuvaltio\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\B) Avustustuottojen jaottelu"
          },
          {
            "name": "Kunnat ja kuntayhtymät",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"kunnat3\",[tili_koodi] =\"kunnat\")))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\B) Avustustuottojen jaottelu"
          },
          {
            "name": "Muu julkinen hallinto",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"muujulkh\",[tili_koodi] =\"sosturvarah\")))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\B) Avustustuottojen jaottelu"
          },
          {
            "name": "Voittoa tavoittelemattomat yhteisöt (kirkot, säätiöt, puolueet, rahastot)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"vyhteiso\",[tili_koodi] =\"vottavoittelematon\")))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\B) Avustustuottojen jaottelu"
          },
          {
            "name": "Kotimaiset yritykset",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"kotiyritys\",[tili_koodi] =\"kyrityst\")))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\B) Avustustuottojen jaottelu"
          },
          {
            "name": "Kotimaiset rahoituslaitokset",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"kotirah\",[tili_koodi] =\"krahalt\")))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\B) Avustustuottojen jaottelu"
          },
          {
            "name": "Kotitaloudet",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"kotitalous\",OR([tili_koodi] =\"kotitalt\",[tili_koodi] =\"kotilahj\"  ))))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\B) Avustustuottojen jaottelu"
          },
          {
            "name": "EU-rahoitus",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"eurah\",[tili_koodi] =\"eusuora\")))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\B) Avustustuottojen jaottelu"
          },
          {
            "name": "Euroopan Unionin maat, yritysrahoitus",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"eurahyrit\",[tili_koodi] =\"euyritys\")))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\B) Avustustuottojen jaottelu"
          },
          {
            "name": "Euroopan Unionin maat, muu rahoitus",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"eurahmuu\",[tili_koodi] =\"eumuut\")))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\B) Avustustuottojen jaottelu"
          },
          {
            "name": "Muut ulkomaat, yritysrahoitus ",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"muuulkyritys\",[tili_koodi] =\"ulkyrity\")))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\B) Avustustuottojen jaottelu"
          },
          {
            "name": "Muut ulkomaat, muu rahoitus",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"muuulkmuurah\",[tili_koodi] =\"ulkmuu\")))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\B) Avustustuottojen jaottelu"
          },
          {
            "name": "Ulkomainen liiketoiminta",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"ULKLIIKTOIM\",[tili_koodi] =\"YVARULKOT\")))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\C) Ulkomainen liiketoiminta"
          },
          {
            "name": "Palkat ja palkkiot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"palkkak\",OR([tili_koodi] =\"palkat\",[tili_koodi] =\"palkat_ja_palkkiot\"))))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\E) Kulut\\Henkilöstökulut"
          },
          {
            "name": "Henkilöstösivukulut: Eläkekulut",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"elakekulut\",OR([tili_koodi] =\"elakekulut2\",[tili_koodi] =\"elakek\"))))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\E) Kulut\\Henkilöstökulut"
          },
          {
            "name": "Henkilöstösivukulut: Muut henkilösivukulut",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"muusivuk\", [tili_koodi] =\"msivukulut\")))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\E) Kulut\\Henkilöstökulut"
          },
          {
            "name": "Muut kulut yhteensä",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat',[tili_koodi] =\"muutkulutyht\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\E) Kulut"
          },
          {
            "name": "Tarvikkeet ja tavarat",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"tavaosto\",[tili_koodi] =\"aitata\")))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\E) Kulut\\Muut kulut"
          },
          {
            "name": "Palvelujen ostot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"palvosto\",OR([tili_koodi] =\"ulkopuoliset_palvelut\",OR([tili_koodi] =\"ostotilaik\",[tili_koodi] =\"ulkpal\")))))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\E) Kulut\\Muut kulut"
          },
          {
            "name": "Tilakustannukset",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"muutilak\",[tili_koodi] =\"tilakustannukset\")))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\E) Kulut\\Muut kulut"
          },
          {
            "name": "Kone- ja laitevuokrat",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"konelaite\",[tili_koodi] =\"konevuok\")))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\E) Kulut\\Muut kulut"
          },
          {
            "name": "Muut varsinaisen toiminnan kulut",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"muutkulut\",[tili_koodi] =\"vtmuuk\")))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\E) Kulut\\Muut kulut"
          },
          {
            "name": "Keräysten ja lahjoitusten tuotot: kotitaloudet",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"KERLAHJKOTI\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\F) Varainhankinta\\Varainhankinnan tuotot"
          },
          {
            "name": "Keräysten ja lahjoitusten tuotot: yritykset",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"KERLAHJYRIT\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\F) Varainhankinta\\Varainhankinnan tuotot"
          },
          {
            "name": "Keräysten ja lahjoitusten tuotot: muut",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat',[tili_koodi] =\"KERLAHJMUU\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\F) Varainhankinta\\Varainhankinnan tuotot"
          },
          {
            "name": "Varainhankinnan liiketoiminnan tuotot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"vhliiket\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\F) Varainhankinta\\Varainhankinnan tuotot"
          },
          {
            "name": "Muut varainhankinnan tuotot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"vhmuutul\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\F) Varainhankinta\\Varainhankinnan tuotot"
          },
          {
            "name": "Varainhankinnan liiketoiminnan kulut",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"vhliikek\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\F) Varainhankinta\\Varainhankinnan kulut"
          },
          {
            "name": "Muut varainhankinnan kulut",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"vhmuuk\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\F) Varainhankinta\\Varainhankinnan kulut"
          },
          {
            "name": "Osinkotuotot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"osinkot\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\G) Sijoitustoiminta\\Varsinaisen sijoitustoiminnan tuotot"
          },
          {
            "name": "Korkotuotot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"korkot\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\G) Sijoitustoiminta\\Varsinaisen sijoitustoiminnan tuotot"
          },
          {
            "name": "Myyntituotot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"mvoitto\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\G) Sijoitustoiminta\\Varsinaisen sijoitustoiminnan tuotot"
          },
          {
            "name": "Vuokratuotot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"vuokrat\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\G) Sijoitustoiminta\\Varsinaisen sijoitustoiminnan tuotot"
          },
          {
            "name": "Korkokulut",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"korkok\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\G) Sijoitustoiminta\\Varsinaisen sijoitustoiminnan kulut"
          },
          {
            "name": "Vuokrakulut (vastikkeet)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"vastikek\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\G) Sijoitustoiminta\\Varsinaisen sijoitustoiminnan kulut"
          },
          {
            "name": "Myyntitappiot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"mtappio\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\G) Sijoitustoiminta\\Varsinaisen sijoitustoiminnan kulut"
          },
          {
            "name": "Tuotot osuuksista saman konsernin yrityksissä",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"konstuot\",[tili_koodi] =\"TUOTOSUUKSISTAKONS\")))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\H) Rahoitustoiminta\\Rahoitustuotot"
          },
          {
            "name": "Tuotot osuuksista omistusyhteysyrityksissä",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"tuotosuu\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\H) Rahoitustoiminta\\Rahoitustuotot"
          },
          {
            "name": "Tuotot muista pysyvien vastaavien sijoituksista",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"tuototmuilt\",[tili_koodi] =\"TUOTOTMUISTA\")))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\H) Rahoitustoiminta\\Rahoitustuotot"
          },
          {
            "name": "Arvonalentumisten palautukset",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"arvalpal\",[tili_koodi] =\"ARVONALENTUMISETPAL\")))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\H) Rahoitustoiminta\\Rahoitustuotot"
          },
          {
            "name": "Arvonalentumiset muiden pysyvien vastaavien sijoituksista",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"arvovastaasijo\",[tili_koodi] =\"ARVONALENTUMISETPYSSIJ\")))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\H) Rahoitustoiminta\\Rahoituskulut"
          },
          {
            "name": "Arvonalentumiset vaihtuvien vastaavien rahoitusarvopapereista",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"arvovaihtvastrah\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\H) Rahoitustoiminta\\Rahoituskulut"
          },
          {
            "name": "Korkokulut ja rahoituskulut",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"korkrahkulumuut\",[tili_koodi] =\"KORKOKULUTRAHKULUT\")))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\H) Rahoitustoiminta\\Rahoituskulut"
          },
          {
            "name": "Korkokulut ja rahoituskulut saman konsernin yrityksille",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"korkrahkulukons\",[tili_koodi] =\"KORKOKULUTRAHKULUTSAMA\")))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\H) Rahoitustoiminta\\Rahoituskulut"
          },
          {
            "name": "Omakatteisten rahastojen muutos yhteensä",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"omakrahm\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\J) Omakatteisten rahastojen muutos"
          },
          {
            "name": "LIIKEVOITTO (TAPPIO)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"lvoitto\",[tili_koodi] =\"vtjaama\")))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\K) Tilikauden tulos"
          },
          {
            "name": "VOITTO (TAPPIO) ENNEN TILINPÄÄTÖS-SIIRTOJA JA VEROJA",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"voitenveroja\",[tili_koodi] =\"VOITTOENTILP\")))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\K) Tilikauden tulos"
          },
          {
            "name": "Poistoeron muutos (+/-)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"poistoem\",OR([tili_koodi] =\"poistoero\",([tili_koodi] =\"poistoeron_lisays\")))))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\K) Tilikauden tulos"
          },
          {
            "name": "Tuloverot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"tulovero\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\K) Tilikauden tulos"
          },
          {
            "name": "Konserni: Vähemmistöosuudet",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"vtvahem\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\K) Tilikauden tulos"
          },
          {
            "name": "Liikevaihto",
            "expression": "CALCULATE([Avustustuotot]+[Korkeakoulujen valtionrahoitus]+[Liiketoiminnan tuotot]+[Muut tuotot]+[Osuus osakkuusyhtiöiden tuloksesta (voitosta/tappiosta, +/-)])",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\A) Liikevaihto"
          },
          {
            "name": "Avustustuotot",
            "expression": "CALCULATE([Business Finland]+[EU-rahoitus]+[Euroopan Unionin maat, muu rahoitus]+[Euroopan Unionin maat, yritysrahoitus]+[Kotimaiset rahoituslaitokset]+[Kotimaiset yritykset]+[Kotitaloudet]+[Kunnat ja kuntayhtymät]+[Muu julkinen hallinto]+[Muu OKM]+[Muu valtio (pl. Business Finland, Akatemia, Sosiaaliturvarahastot ja muu OKM)]+[Muut ulkomaat, muu rahoitus]+[Muut ulkomaat, yritysrahoitus ]+[Suomen Akatemia]+[Voittoa tavoittelemattomat yhteisöt (kirkot, säätiöt, puolueet, rahastot)]+[Konserni; Avustustuotot])",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\A) Liikevaihto"
          },
          {
            "name": "Konserni; Henkilöstökulut",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', AND([Konserni]=\"Kyllä\",OR([tili_koodi] =\"hlokuluy\",[tili_koodi] =\"HLOKULUYHT\"))))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\E) Kulut\\Henkilöstökulut"
          },
          {
            "name": "Poistot ja arvonalentumiset",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat',  OR([tili_koodi] =\"poistot2\",OR([tili_koodi] =\"poistot\",[tili_koodi] =\"suunnitelman_mukaiset_poistot\"))))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\E) Kulut"
          },
          {
            "name": "Varsinaisen sijoitustoiminnan tuotot yhteensä",
            "expression": "CALCULATE([Korkotuotot]+[Muut sijoitustoiminnan tuotot]+[Myyntituotot]+[Osinkotuotot]+[Vuokratuotot])",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\G) Sijoitustoiminta"
          },
          {
            "name": "Varsinaisen sijoitustoiminnan kulut yhteensä",
            "expression": "CALCULATE([Korkokulut]+[Muut sijoitustoiminnan kulut]+[Myyntitappiot]+[Vuokrakulut (vastikkeet)])",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\G) Sijoitustoiminta"
          },
          {
            "name": "Varsinaisen sijoitustoiminnan tuotto",
            "expression": "CALCULATE([Varsinaisen sijoitustoiminnan tuotot yhteensä]-[Varsinaisen sijoitustoiminnan kulut yhteensä]+[Käyvän arvon muutos (+/-)])",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\G) Sijoitustoiminta"
          },
          {
            "name": "Rahoitustuotot ja -kulut (netto)",
            "expression": "CALCULATE([Rahoitustuotot yhteensä]-[Rahoituskulut yhteensä])",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\H) Rahoitustoiminta"
          },
          {
            "name": "Rahoitustuotot yhteensä",
            "expression": "CALCULATE([Arvonalentumisten palautukset]+[Tuotot muista pysyvien vastaavien sijoituksista]+[Tuotot osuuksista omistusyhteysyrityksissä]+[Tuotot osuuksista saman konsernin yrityksissä]+[Muut korko- ja rahoitustuotot])",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\H) Rahoitustoiminta"
          },
          {
            "name": "Rahoituskulut yhteensä",
            "expression": "CALCULATE([Korkokulut ja rahoituskulut saman konsernin yrityksille]+[Arvonalentumiset muiden pysyvien vastaavien sijoituksista]+[Arvonalentumiset vaihtuvien vastaavien rahoitusarvopapereista]+[Korkokulut ja rahoituskulut])",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\H) Rahoitustoiminta"
          },
          {
            "name": "Kulut yhteensä",
            "expression": "CALCULATE([Henkilöstökulut yhteensä]+[Muut kulut yhteensä]+[Poistot ja arvonalentumiset])",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\E) Kulut"
          },
          {
            "name": "Sidottujen rahastojen muutos yhteensä",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"sidottrm\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\I) Sidottujen rahastojen muutos"
          },
          {
            "name": "Maksuasetuksen perusteella perittävät maksut",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"MAKSUASETUS\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\D) Muut tuotot"
          },
          {
            "name": "Lukukausimaksut",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"LUKUKAUSIMAKSUT\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\D) Muut tuotot"
          },
          {
            "name": "Pysyväisluontoinen yhteistyö koulutuksen tukitoimintojen järjestämisessä kahden verotonta koulutusta antavan oppilaitoksen välillä",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"PYSYVAISLUONTOINEN\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\D) Muut tuotot"
          },
          {
            "name": "Muut muut tuotot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"MUUTMUUTTUOT\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\D) Muut tuotot"
          },
          {
            "name": "Siirto sidotusta rahastosta",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"SIIRTOSIDOTUSTA\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\I) Sidottujen rahastojen muutos"
          },
          {
            "name": "Siirto sidottuun rahastoon",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"SIIRTOSIDOTTUUN\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\I) Sidottujen rahastojen muutos"
          },
          {
            "name": "Siirto rahastosta",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"SIIRTORAHASTOSTA\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\J) Omakatteisten rahastojen muutos"
          },
          {
            "name": "Siirto rahastoon",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"SIIRTORAHASTOON\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\J) Omakatteisten rahastojen muutos"
          },
          {
            "name": "Keräysten ja lahjoitusten kulut",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"KERLAHJKULU\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\F) Varainhankinta\\Varainhankinnan kulut"
          },
          {
            "name": "Lahjoitusten tuotot: muut",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat',[tili_koodi] =\"muulahj\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\F) Varainhankinta\\Varainhankinnan tuotot\\Lahjoitusten tuotot (historia)"
          },
          {
            "name": "Lahjoitusten tuotot: kotitaloudet",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"kotilahj\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\F) Varainhankinta\\Varainhankinnan tuotot\\Lahjoitusten tuotot (historia)"
          },
          {
            "name": "Lahjoitusten tuotot: yritykset",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"yritlahj\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\F) Varainhankinta\\Varainhankinnan tuotot\\Lahjoitusten tuotot (historia)"
          },
          {
            "name": "Käyvän arvon muutos (+/-)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"KVARVONMUUTOS\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\G) Sijoitustoiminta"
          },
          {
            "name": "Liiketoiminnan tuotot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"vtliiket\",[tili_koodi] =\"liiktuotot\")))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\A) Liikevaihto"
          },
          {
            "name": "Muut tuotot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"muuttuot\",[tili_koodi] =\"vtmuutul\")))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\A) Liikevaihto"
          },
          {
            "name": "Muut korko- ja rahoitustuotot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"MUUTKORKORAHTUOTOT\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\H) Rahoitustoiminta\\Rahoitustuotot"
          },
          {
            "name": "Muut sijoitustoiminnan kulut",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"srmuuk\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\G) Sijoitustoiminta\\Varsinaisen sijoitustoiminnan kulut"
          },
          {
            "name": "TILIKAUDEN VOITTO (TAPPIO)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"TILIKJAAM\",[tili_koodi] =\"TILVOITTO\")))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\K) Tilikauden tulos"
          },
          {
            "name": "Varainhankinnan kulut yhteensä",
            "description": "Tuloslaskelma\\F) Varainhankinta",
            "expression": "CALCULATE([Keräysten ja lahjoitusten kulut]+[Muut varainhankinnan kulut]+[Varainhankinnan liiketoiminnan kulut])",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\F) Varainhankinta"
          },
          {
            "name": "Varainhankinnan tuotot yhteensä",
            "expression": "CALCULATE([Keräysten ja lahjoitusten tuotot: kotitaloudet]+[Keräysten ja lahjoitusten tuotot: muut]+[Keräysten ja lahjoitusten tuotot: yritykset]+[Muut varainhankinnan tuotot]+[Varainhankinnan liiketoiminnan tuotot])",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\F) Varainhankinta"
          },
          {
            "name": "Varainhankinta, nettotuotto",
            "expression": "CALCULATE([Varainhankinnan tuotot yhteensä]-[Varainhankinnan kulut yhteensä])",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\F) Varainhankinta"
          },
          {
            "name": "Käyvän arvon rahasto",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"kayvanar\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\B) Vastattavaa\\Oma pääoma\\Muut rahastot"
          },
          {
            "name": "Kehittämismenot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"kehmenot\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\C) Vastaavaa\\Pysyvät vastaavat\\Aineettomat hyödykkeet"
          },
          {
            "name": "Aineettomat oikeudet",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"aineetoi\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\C) Vastaavaa\\Pysyvät vastaavat\\Aineettomat hyödykkeet"
          },
          {
            "name": "Liikearvo",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"liikear\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\C) Vastaavaa\\Pysyvät vastaavat\\Aineettomat hyödykkeet"
          },
          {
            "name": "Konserni-liikearvo",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"kliikear\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\C) Vastaavaa\\Pysyvät vastaavat\\Aineettomat hyödykkeet"
          },
          {
            "name": "Muut aineettomat hyödykkeet",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"muupmeno\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\C) Vastaavaa\\Pysyvät vastaavat\\Aineettomat hyödykkeet"
          },
          {
            "name": "Ennakkomaksut",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"ahennakk\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\C) Vastaavaa\\Pysyvät vastaavat\\Aineettomat hyödykkeet"
          },
          {
            "name": "Maa- ja vesialueet",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"maavesi\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\C) Vastaavaa\\Pysyvät vastaavat\\Aineelliset hyödykkeet"
          },
          {
            "name": "Rakennukset ja rakennelmat",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"rakennus\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\C) Vastaavaa\\Pysyvät vastaavat\\Aineelliset hyödykkeet"
          },
          {
            "name": "Koneet ja kalusto",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"koneet\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\C) Vastaavaa\\Pysyvät vastaavat\\Aineelliset hyödykkeet"
          },
          {
            "name": "Muut aineelliset hyödykkeet",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"muuainh\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\C) Vastaavaa\\Pysyvät vastaavat\\Aineelliset hyödykkeet"
          },
          {
            "name": "Ennakkomaksut ja keskeneräiset hankinnat",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"ennakesk\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\C) Vastaavaa\\Pysyvät vastaavat\\Aineelliset hyödykkeet"
          },
          {
            "name": "Osuudet saman konsernin yrityksissä (sijoitukset)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"osuuskon\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\C) Vastaavaa\\Pysyvät vastaavat\\Sijoitukset"
          },
          {
            "name": "Saamiset saman konsernin yrityksiltä",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"saamikon\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\C) Vastaavaa\\Pysyvät vastaavat\\Sijoitukset"
          },
          {
            "name": "Osuudet omistusyhteys-yrityksissä",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"osuusoyy\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\C) Vastaavaa\\Pysyvät vastaavat\\Sijoitukset"
          },
          {
            "name": "Saamiset omistusyhteys-yrityksiltä",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"saamioyy\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\C) Vastaavaa\\Pysyvät vastaavat\\Sijoitukset"
          },
          {
            "name": "Muut osakkeet ja osuudet (sijoitukset)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"muutosak\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\C) Vastaavaa\\Pysyvät vastaavat\\Sijoitukset"
          },
          {
            "name": "Muut saamiset (sijoitukset)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"muutsaam\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\C) Vastaavaa\\Pysyvät vastaavat\\Sijoitukset"
          },
          {
            "name": "Omakatteisten rahastojen varat",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"okrvarat\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\C) Vastaavaa\\Pysyvät vastaavat"
          },
          {
            "name": "Aineet ja tarvikkeet",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"aineet\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\C) Vastaavaa\\Vaihtuvat vastaavat\\Vaihto-omaisuus"
          },
          {
            "name": "Keskeneräiset tuotteet",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"keskener\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\C) Vastaavaa\\Vaihtuvat vastaavat\\Vaihto-omaisuus"
          },
          {
            "name": "Valmiit tuotteet/ tavarat",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"valmiit\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\C) Vastaavaa\\Vaihtuvat vastaavat\\Vaihto-omaisuus"
          },
          {
            "name": "Muu vaihto-omaisuus",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"muuvom\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\C) Vastaavaa\\Vaihtuvat vastaavat\\Vaihto-omaisuus"
          },
          {
            "name": "Ennakkomaksut (vaihto-omaisuus)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"voennakk\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\C) Vastaavaa\\Vaihtuvat vastaavat\\Vaihto-omaisuus"
          },
          {
            "name": "Osuudet saman konsernin yrityksissä (rahoitusarvopaperit)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"raposuus\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\C) Vastaavaa\\Vaihtuvat vastaavat\\Rahoitusarvopaperit"
          },
          {
            "name": "Muut osakkeet ja osuudet (rahoitusarvopaperit)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"raposakk\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\C) Vastaavaa\\Vaihtuvat vastaavat\\Rahoitusarvopaperit"
          },
          {
            "name": "Muut arvopaperit (rahoitusarvopaperit)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"muuarvop\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\C) Vastaavaa\\Vaihtuvat vastaavat\\Rahoitusarvopaperit"
          },
          {
            "name": "Rahat ja pankkisaamiset (vaihtuvat)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"rahatps\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\C) Vastaavaa\\Vaihtuvat vastaavat"
          },
          {
            "name": "Vastaavaa yhteensä",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso1_fi]=\"Vastaavaa\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tase\\C) Vastaavaa"
          },
          {
            "name": "Osake-, osuus- tai muu vastaava pääoma / peruspääoma",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"peruspo\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\B) Vastattavaa\\Oma pääoma"
          },
          {
            "name": "Pääomarahasto",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"PORAH\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\B) Vastattavaa\\Oma pääoma"
          },
          {
            "name": "Ylikurssirahasto",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"YKRAH\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\B) Vastattavaa\\Oma pääoma"
          },
          {
            "name": "Arvonkorotusrahasto",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"arvonkr\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\B) Vastattavaa\\Oma pääoma"
          },
          {
            "name": "Sijoitetun vapaan oman pääoman rahasto",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"SIJVAPRAH\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\B) Vastattavaa\\Oma pääoma\\Muut rahastot"
          },
          {
            "name": "Vararahasto",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"VARARAH\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\B) Vastattavaa\\Oma pääoma\\Muut rahastot"
          },
          {
            "name": "Yhtiöjärjestyksen tai sääntöjen mukaiset rahastot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"YJRAH\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\B) Vastattavaa\\Oma pääoma\\Muut rahastot"
          },
          {
            "name": "Omakatteiset rahastot ",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"okarahas\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\B) Vastattavaa\\Oma pääoma\\Muut rahastot"
          },
          {
            "name": "Muut sidotut rahastot ",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"msirahas\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\B) Vastattavaa\\Oma pääoma\\Muut rahastot"
          },
          {
            "name": "Toimintapääoma",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"toimpo\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\B) Vastattavaa\\Oma pääoma\\Muut rahastot"
          },
          {
            "name": "Muut vapaat rahastot (esim. sijoitusrahasto)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"vaprahas\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\B) Vastattavaa\\Oma pääoma\\Muut rahastot"
          },
          {
            "name": "Edellisten tilikausien voitto (tappio)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"edtilvo\",[tili_koodi] =\"edjaama\")))",
            "formatString": "#,0",
            "displayFolder": "Tase\\B) Vastattavaa\\Oma pääoma\\Muu oma pääoma"
          },
          {
            "name": "Tilikauden voitto (tai tappio)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"tkvoitto\",[tili_koodi] =\"tkjaama\")))",
            "formatString": "#,0",
            "displayFolder": "Tase\\B) Vastattavaa\\Oma pääoma\\Muu oma pääoma"
          },
          {
            "name": "Oma pääoma yhteensä",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso2_fi]=\"OMA PÄÄOMA\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tase\\B) Vastattavaa\\Oma pääoma"
          },
          {
            "name": "Vähemmistöosuudet (konserni)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"tavahem\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\B) Vastattavaa\\Oma pääoma"
          },
          {
            "name": "Poistoero",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"tpskerty\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\B) Vastattavaa\\Tilinpäätössiirtymät ja pakolliset varaukset\\Tilinpäätössiirtymät"
          },
          {
            "name": "Verotusperäiset varaukset",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"VEROPVARA\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\B) Vastattavaa\\Tilinpäätössiirtymät ja pakolliset varaukset\\Tilinpäätössiirtymät"
          },
          {
            "name": "Eläkevaraukset",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"elakvara\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\B) Vastattavaa\\Tilinpäätössiirtymät ja pakolliset varaukset\\Pakolliset varaukset"
          },
          {
            "name": "Verovaraukset",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"verovara\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\B) Vastattavaa\\Tilinpäätössiirtymät ja pakolliset varaukset\\Pakolliset varaukset"
          },
          {
            "name": "Muut pakolliset varaukset",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"mpakvara\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\B) Vastattavaa\\Tilinpäätössiirtymät ja pakolliset varaukset\\Pakolliset varaukset"
          },
          {
            "name": "Konsernireservi",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"kreservi\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\B) Vastattavaa\\Tilinpäätössiirtymät ja pakolliset varaukset"
          },
          {
            "name": "Omakatteisten rahastojen velat",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"okrvelat\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\B) Vastattavaa\\Vieras pääoma"
          },
          {
            "name": "Vastattavaa yhteensä",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso1_fi]=\"Vastattavaa\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tase\\B) Vastattavaa"
          },
          {
            "name": "Omakatteisten rahastojen sijoitukset yhteensä",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"okrsijyh\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\E) Tilastokeskuksen tarkentavat tiedot"
          },
          {
            "name": "Rahasto-osuudet",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"okrrahas\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\E) Tilastokeskuksen tarkentavat tiedot"
          },
          {
            "name": "Muut osakkeet ja osuudet",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"okrosakk\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\E) Tilastokeskuksen tarkentavat tiedot"
          },
          {
            "name": "Muut arvopaperit",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"okrmuuap\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\E) Tilastokeskuksen tarkentavat tiedot"
          },
          {
            "name": "Rahat ja pankkisaamiset",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"okrrjaps\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\E) Tilastokeskuksen tarkentavat tiedot"
          },
          {
            "name": "Muut varat",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"okrmuutv\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\E) Tilastokeskuksen tarkentavat tiedot"
          },
          {
            "name": "Kompensoitavat perustoiminnan alv-menot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"kompperusalvm\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\D) Arvonlisäverot"
          },
          {
            "name": "Saadut alv-kompensaatiot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"saadalvkomp\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\D) Arvonlisäverot"
          },
          {
            "name": "Arvonlisäverosaatava/-velka",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"alvsaavel\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\D) Arvonlisäverot"
          },
          {
            "name": "Omavaraisuusaste",
            "expression": "[Oma pääoma yhteensä]/([Vastaavaa yhteensä]-[Lyhytaikaiset saadut ennakot])",
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Tase\\A) Johdetut mittarit"
          },
          {
            "name": "Lyhytaikaiset myyntisaamiset",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"lmyyntis\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\C) Vastaavaa\\Vaihtuvat vastaavat\\Lyhytaikaiset saamiset"
          },
          {
            "name": "Lyhytaikaiset saamiset saman konsernin yrityksiltä",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"lskonser\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\C) Vastaavaa\\Vaihtuvat vastaavat\\Lyhytaikaiset saamiset"
          },
          {
            "name": "Lyhytaikaiset saamiset omistusyhteysyrityksiltä",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"lsoyyrit\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\C) Vastaavaa\\Vaihtuvat vastaavat\\Lyhytaikaiset saamiset"
          },
          {
            "name": "Lyhytaikaiset lainasaamiset",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"llainas\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\C) Vastaavaa\\Vaihtuvat vastaavat\\Lyhytaikaiset saamiset"
          },
          {
            "name": "Lyhytaikaiset laskennalliset verosaamiset",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"llveros\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\C) Vastaavaa\\Vaihtuvat vastaavat\\Lyhytaikaiset saamiset"
          },
          {
            "name": "Lyhytaikaiset muut saamiset",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"lmuuts\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\C) Vastaavaa\\Vaihtuvat vastaavat\\Lyhytaikaiset saamiset"
          },
          {
            "name": "Lyhytaikaiset siirtosaamiset",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"lsiirtos\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\C) Vastaavaa\\Vaihtuvat vastaavat\\Lyhytaikaiset saamiset"
          },
          {
            "name": "Lyhytaikaiset pääomalainat",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"lpaaomal\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\B) Vastattavaa\\Vieras pääoma\\Lyhytaikainen vieras pääoma"
          },
          {
            "name": "Lyhytaikaiset joukkovelkakirjalainat",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"ljvelkal\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\B) Vastattavaa\\Vieras pääoma\\Lyhytaikainen vieras pääoma"
          },
          {
            "name": "Lyhytaikaiset vaihtovelkakirjalainat",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"lvvelkal\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\B) Vastattavaa\\Vieras pääoma\\Lyhytaikainen vieras pääoma"
          },
          {
            "name": "Lyhytaikaiset lainat rahoituslaitoksilta",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"llrahala\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\B) Vastattavaa\\Vieras pääoma\\Lyhytaikainen vieras pääoma"
          },
          {
            "name": "Lyhytaikaiset eläkelainat",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"lelakel\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\B) Vastattavaa\\Vieras pääoma\\Lyhytaikainen vieras pääoma"
          },
          {
            "name": "Lyhytaikaiset saadut ennakot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"lsaadute\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\B) Vastattavaa\\Vieras pääoma\\Lyhytaikainen vieras pääoma"
          },
          {
            "name": "Lyhytaikaiset ostovelat",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"lostovel\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\B) Vastattavaa\\Vieras pääoma\\Lyhytaikainen vieras pääoma"
          },
          {
            "name": "Lyhytaikaiset rahoitusvekselit",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"lrveksel\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\B) Vastattavaa\\Vieras pääoma\\Lyhytaikainen vieras pääoma"
          },
          {
            "name": "Lyhytaikaiset velat saman konsernin yrityksille",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"lvkonser\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\B) Vastattavaa\\Vieras pääoma\\Lyhytaikainen vieras pääoma"
          },
          {
            "name": "Lyhytaikaiset velat omistusyhteysyrityksille",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"lvoyyrit\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\B) Vastattavaa\\Vieras pääoma\\Lyhytaikainen vieras pääoma"
          },
          {
            "name": "Lyhytaikaiset muut velat",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"lmuutvel\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\B) Vastattavaa\\Vieras pääoma\\Lyhytaikainen vieras pääoma"
          },
          {
            "name": "Lyhytaikaiset siirtovelat",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"lsiirtov\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\B) Vastattavaa\\Vieras pääoma\\Lyhytaikainen vieras pääoma"
          },
          {
            "name": "Lyhytaikaiset laskennaliset verovelat",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"llverove\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\B) Vastattavaa\\Vieras pääoma\\Lyhytaikainen vieras pääoma"
          },
          {
            "name": "Pitkäaikaiset myyntisaamiset",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"pmyyntis\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\C) Vastaavaa\\Vaihtuvat vastaavat\\Pitkäaikaiset saamiset"
          },
          {
            "name": "Pitkäaikaiset saamiset saman konsernin yrityksiltä",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"pskonser\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\C) Vastaavaa\\Vaihtuvat vastaavat\\Pitkäaikaiset saamiset"
          },
          {
            "name": "Pitkäaikaiset saamiset omistusyhteysyrityksiltä",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"psoyyrit\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\C) Vastaavaa\\Vaihtuvat vastaavat\\Pitkäaikaiset saamiset"
          },
          {
            "name": "Pitkäaikaiset lainasaamiset",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"plainas\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\C) Vastaavaa\\Vaihtuvat vastaavat\\Pitkäaikaiset saamiset"
          },
          {
            "name": "Pitkäaikaiset laskennalliset verosaamiset",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"plveros\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\C) Vastaavaa\\Vaihtuvat vastaavat\\Pitkäaikaiset saamiset"
          },
          {
            "name": "Pitkäaikaiset muut saamiset",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"pmuuts\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\C) Vastaavaa\\Vaihtuvat vastaavat\\Pitkäaikaiset saamiset"
          },
          {
            "name": "Pitkäaikaiset siirtosaamiset",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"psiirtos\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\C) Vastaavaa\\Vaihtuvat vastaavat\\Pitkäaikaiset saamiset"
          },
          {
            "name": "Pitkäaikaiset pääomalainat",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"ppaaomal\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\B) Vastattavaa\\Vieras pääoma\\Pitkäaikainen vieras pääoma"
          },
          {
            "name": "Pitkäaikaiset joukkovelkakirjalainat",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"pjvelkal\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\B) Vastattavaa\\Vieras pääoma\\Pitkäaikainen vieras pääoma"
          },
          {
            "name": "Pitkäaikaiset vaihtovelkakirjalainat",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"pvvelkal\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\B) Vastattavaa\\Vieras pääoma\\Pitkäaikainen vieras pääoma"
          },
          {
            "name": "Pitkäaikaiset lainat rahoituslaitoksilta",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"plrahala\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\B) Vastattavaa\\Vieras pääoma\\Pitkäaikainen vieras pääoma"
          },
          {
            "name": "Pitkäaikaiset eläkelainat",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"pelakel\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\B) Vastattavaa\\Vieras pääoma\\Pitkäaikainen vieras pääoma"
          },
          {
            "name": "Pitkäaikaiset saadut ennakot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"psaadute\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\B) Vastattavaa\\Vieras pääoma\\Pitkäaikainen vieras pääoma"
          },
          {
            "name": "Pitkäaikaiset ostovelat",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"postovel\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\B) Vastattavaa\\Vieras pääoma\\Pitkäaikainen vieras pääoma"
          },
          {
            "name": "Pitkäaikaiset rahoitusvekselit",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"prveksel\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\B) Vastattavaa\\Vieras pääoma\\Pitkäaikainen vieras pääoma"
          },
          {
            "name": "Pitkäaikaiset velat saman konsernin yrityksille",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"pvkonser\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\B) Vastattavaa\\Vieras pääoma\\Pitkäaikainen vieras pääoma"
          },
          {
            "name": "Pitkäaikaiset velat omistusyhteysyrityksille",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"pvoyyrit\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\B) Vastattavaa\\Vieras pääoma\\Pitkäaikainen vieras pääoma"
          },
          {
            "name": "Pitkäaikaiset muut velat",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"pmuutvel\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\B) Vastattavaa\\Vieras pääoma\\Pitkäaikainen vieras pääoma"
          },
          {
            "name": "Pitkäaikaiset siirtovelat",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"psiirtov\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\B) Vastattavaa\\Vieras pääoma\\Pitkäaikainen vieras pääoma"
          },
          {
            "name": "Pitkäaikaiset laskennaliset verovelat",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"plverove\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\B) Vastattavaa\\Vieras pääoma\\Pitkäaikainen vieras pääoma"
          },
          {
            "name": "Maksuvalmius",
            "expression": "(CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tase\"), FILTER(Muuttujat,[tili_taso3_fi]=\"Lyhytaikaiset saamiset\"))+CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tase\"), FILTER(Muuttujat,[tili_taso3_fi]=\"Rahoitusarvopaperit\"))+[Rahat ja pankkisaamiset (vaihtuvat)])/(CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tase\"), FILTER(Muuttujat,[tili_taso3_fi]=\"Lyhytaikainen vieras pääoma\"))-[Lyhytaikaiset saadut ennakot])",
            "formatString": "#,0.00",
            "displayFolder": "Tase\\A) Johdetut mittarit"
          },
          {
            "name": "Toimintapääoman suhde omaan pääomaan",
            "expression": "([Toimintapääoma]+[Edellisten tilikausien voitto (tappio)]+[Tilikauden voitto (tai tappio)])/[Oma pääoma yhteensä]",
            "formatString": "#,0.0 %;-#,0.0 %;#,0.0 %",
            "displayFolder": "Tase\\A) Johdetut mittarit"
          },
          {
            "name": "Korkeakoulun ALV-kulut yhteensä pl liiketoiminta",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Yliopiston alv-kulut yhteensä (pl. liiketoiminta)\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\L) OKM:n tarkentavat tiedot"
          },
          {
            "name": "OKM kompensoitava ALV",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"OKM:n kompensoitava alv\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\L) OKM:n tarkentavat tiedot"
          },
          {
            "name": "Harjoittelujen kotikuntakorvauksiin sisältyvä ALV",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Harj.koulujen kotikuntakorvauksiin sisältyvä alv\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\L) OKM:n tarkentavat tiedot"
          },
          {
            "name": "Muiden rajoittajien kompensoimat ALV",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Muiden rahoittajien kompensoimat alv\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\L) OKM:n tarkentavat tiedot"
          },
          {
            "name": "VM rahoitus harjoittelukouluille",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"VM:n rahoitus harjoittelukouluille\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\L) OKM:n tarkentavat tiedot"
          },
          {
            "name": "OKM rahoitus harjoittelukouluille",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"OKM:n rahoitus harjoittelukouluille\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\L) OKM:n tarkentavat tiedot"
          },
          {
            "name": "Harjoittelukoulun liiketoiminnan kulut",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Harjoittelukoulun liiketoiminnan kulut\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\L) OKM:n tarkentavat tiedot"
          },
          {
            "name": "Tutkimusmenot yhteensä",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso0_fi]=\"Tutkimusmenot\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot"
          },
          {
            "name": "Ulkopuolinen rahoitus yhteensä",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso1_fi]=\"Kotimainen ulkopuolinen rahoitus\"),[arvo])+SUMX(FILTER(Muuttujat,[tili_taso1_fi]=\"Ulkomainen ulkopuolinen rahoitus\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot"
          },
          {
            "name": "Suomen Akatemia ",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tutkimusmenot\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Suomen Akatemia\"))",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot\\Kotimainen ulkopuolinen rahoitus"
          },
          {
            "name": "Opetus- ja kulttuuriministeriö",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Muu opetus- ja kulttuuriministeriö\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot\\Kotimainen ulkopuolinen rahoitus"
          },
          {
            "name": "Business Finland ",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tutkimusmenot\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Business Finland\"))",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot\\Kotimainen ulkopuolinen rahoitus"
          },
          {
            "name": "Työ- ja elinkeinoministeriö",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Muu työ- ja elinkeinoministeriö\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot\\Kotimainen ulkopuolinen rahoitus"
          },
          {
            "name": "Ulkoasiainministeriö",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Ulkoasiainministeriö\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot\\Kotimainen ulkopuolinen rahoitus"
          },
          {
            "name": "Oikeusministeriö",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Oikeusministeriö\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot\\Kotimainen ulkopuolinen rahoitus"
          },
          {
            "name": "Sisäasiainministeriö",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Sisäasiainministeriö\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot\\Kotimainen ulkopuolinen rahoitus"
          },
          {
            "name": "Puolustusministeriö",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Puolustusministeriö\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot\\Kotimainen ulkopuolinen rahoitus"
          },
          {
            "name": "Valtiovarainministeriö",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Valtiovarainministeriö\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot\\Kotimainen ulkopuolinen rahoitus"
          },
          {
            "name": "Maa- ja metsätalousministeriö",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Maa- ja metsätalousministeriö\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot\\Kotimainen ulkopuolinen rahoitus"
          },
          {
            "name": "Liikenne- ja viestintäministeriö",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Liikenne- ja viestintäministeriö\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot\\Kotimainen ulkopuolinen rahoitus"
          },
          {
            "name": "Sosiaali- ja terveysministeriö",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Sosiaali- ja terveysministeriö\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot\\Kotimainen ulkopuolinen rahoitus"
          },
          {
            "name": "Ympäristöministeriö",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Ympäristöministeriö\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot\\Kotimainen ulkopuolinen rahoitus"
          },
          {
            "name": "Kunnat ja kuntainliitot",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Kunnat ja kuntainliitot\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot\\Kotimainen ulkopuolinen rahoitus"
          },
          {
            "name": "Muu julkinen rahoitus",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Muu julkinen rahoitus\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot\\Kotimainen ulkopuolinen rahoitus"
          },
          {
            "name": "Kotimaiset yksityiset rahastot ja säätiöt",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Kotimaiset yksityiset rahastot ja säätiöt\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot\\Kotimainen ulkopuolinen rahoitus"
          },
          {
            "name": "Kotimaiset yritykset ",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tutkimusmenot\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Kotimaiset yritykset\"))",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot\\Kotimainen ulkopuolinen rahoitus"
          },
          {
            "name": "Ulkomaiset yritykset",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Ulkomaiset yritykset\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot\\Ulkomainen ulkopuolinen rahoitus"
          },
          {
            "name": "EU-puiteohjelmarahoitus ja muu laadullisesti kilpailtu EU-rahoitus",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"EU-puiteohjelmarahoitus ja muu laadullisesti kilpailtu EU-rahoitus\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot\\Ulkomainen ulkopuolinen rahoitus"
          },
          {
            "name": "EAKR-rahoitus",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"EAKR- rahoitus\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot\\Ulkomainen ulkopuolinen rahoitus"
          },
          {
            "name": "ESR-rahoitus",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"ESR-rahoitus\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot\\Ulkomainen ulkopuolinen rahoitus"
          },
          {
            "name": "Muu EU-rahoitus",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Muu EU-rahoitus\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot\\Ulkomainen ulkopuolinen rahoitus"
          },
          {
            "name": "Ulkomaiset rahastot ja säätiöt",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Ulkomaiset rahastot ja säätiöt\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot\\Ulkomainen ulkopuolinen rahoitus"
          },
          {
            "name": "Kansainväliset järjestöt",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Kansainväliset järjestöt\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot\\Ulkomainen ulkopuolinen rahoitus"
          },
          {
            "name": "Muu ulkomainen rahoitus",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Muu ulkomainen rahoitus\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot\\Ulkomainen ulkopuolinen rahoitus"
          },
          {
            "name": "Perustutkintokoulutus",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Perustutkintokoulutus\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Varsinaisen toiminnan kustannukset\\Koulutus"
          },
          {
            "name": "Perustutkintojen osat",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Perustutkintojen osat\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Varsinaisen toiminnan kustannukset\\Koulutus"
          },
          {
            "name": "Muu koulutus",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Muu koulutus\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Varsinaisen toiminnan kustannukset\\Koulutus"
          },
          {
            "name": "Tutkimus yhteensä",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso1_fi]=\"Tutkimus\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Varsinaisen toiminnan kustannukset\\Tutkimus"
          },
          {
            "name": "Tieteellinen tutkimus",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Tieteellinen tutkimus\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Varsinaisen toiminnan kustannukset\\Tutkimus"
          },
          {
            "name": "Tieteellinen ja taiteellinen jatkotutkintokoulutus",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Tieteellinen ja taiteellinen jatkotutkintokoulutus\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Varsinaisen toiminnan kustannukset\\Tutkimus"
          },
          {
            "name": "Muu yhteiskunnallinen toiminta yhteensä",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso1_fi]=\"Muu yhteiskunnallinen toiminta\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Varsinaisen toiminnan kustannukset\\Muu yhteiskunnallinen toiminta yhteensä"
          },
          {
            "name": "Koulutus yhteensä",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso1_fi]=\"Koulutus\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Varsinaisen toiminnan kustannukset\\Koulutus"
          },
          {
            "name": "Korkeakoulun varsinaisen toiminnan kustannukset yhteensä",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso0_fi]=\"Varsinaisen toiminnan kustannukset\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Varsinaisen toiminnan kustannukset"
          },
          {
            "name": "Korkeakoulun oma rahoitus yhteensä",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tutkimusmenot\"), FILTER(Muuttujat,OR([tili_taso5_fi]=\"Yliopiston oma rahoitus yhteensä\",[tili_taso5_fi]=\"Ammattikorkeakoulun oma rahoitus\")))",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot"
          },
          {
            "name": "Liiketoiminnan liikevaihto",
            "expression": "SUMX(FILTER(Muuttujat,[tili_koodi]=\"lt_liikevaihto\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma"
          },
          {
            "name": "Valmiiden ja keskeneräisten tuotteiden varastojen lisäys tai vähennys",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Valmiiden ja keskeneräisten tuotteiden varastojen lisäys tai vähennys\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Liikevaihto"
          },
          {
            "name": "Valmistus omaan käyttöön",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Valmistus omaan käyttöön\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Liikevaihto"
          },
          {
            "name": "Liiketoiminnan muut tuotot",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Liiketoiminnan muut tuotot\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Liikevaihto"
          },
          {
            "name": "Materiaalit ja palvelut yhteensä",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Liiketoiminnan tuloslaskelma\"), FILTER(Muuttujat,[tili_taso2_fi]=\"Materiaalit ja palvelut\"))",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Liikevaihto"
          },
          {
            "name": "Aineet, tarvikkeet ja tavarat yhteensä",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Liiketoiminnan tuloslaskelma\"), FILTER(Muuttujat,[tili_taso3_fi]=\"Aineet, tarvikkeet ja tavarat\"))",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Liikevaihto\\Materiaalit ja palvelut"
          },
          {
            "name": "Ostot tilikauden aikana (Tiedot liiketoiminnasta)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Liiketoiminnan tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Ostot tilikauden aikana\"))",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Liikevaihto\\Materiaalit ja palvelut"
          },
          {
            "name": "Varastojen lisäys tai vähennys",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Varastojen lisäys tai vähennys\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Liikevaihto\\Materiaalit ja palvelut"
          },
          {
            "name": "Ulkopuoliset palvelut (Tiedot liiketoiminnasta)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Liiketoiminnan tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Ulkopuoliset palvelut\"))",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Liikevaihto\\Materiaalit ja palvelut"
          },
          {
            "name": "Liiketoiminnan palkat ja palkkiot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Liiketoiminnan tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Palkat ja palkkiot\"))",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Liikevaihto\\Henkilöstökulut"
          },
          {
            "name": "Liiketoiminnan henkilöstösivukulut yhteensä",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Liiketoiminnan tuloslaskelma\"), FILTER(Muuttujat,[tili_taso3_fi]=\"Henkilöstösivukulut\"))",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Liikevaihto\\Henkilöstökulut"
          },
          {
            "name": "Liiketoiminnan eläkekulut",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Liiketoiminnan tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Eläkekulut\"))",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Liikevaihto\\Henkilöstökulut"
          },
          {
            "name": "Liiketoiminnan muut henkilöstösivukulut",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Liiketoiminnan tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Muut henkilöstösivukulut\"))",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Liikevaihto\\Henkilöstökulut"
          },
          {
            "name": "Poistot ja arvonalentumiset yhteensä",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Liiketoiminnan tuloslaskelma\"), FILTER(Muuttujat,[tili_koodi]=\"poistot_ja_arvonalennukset\"))",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Liikevaihto"
          },
          {
            "name": "Suunnitelman mukaiset poistot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Liiketoiminnan tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Suunnitelman mukaiset poistot\"))",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Liikevaihto\\Poistot ja arvonalentumiset"
          },
          {
            "name": "Arvonalentumiset pysyvien vastaavien hyödykkeistä ",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Liiketoiminnan tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Arvonalentumiset pysyvien vastaavien hyödykkeistä\"))",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Liikevaihto\\Poistot ja arvonalentumiset"
          },
          {
            "name": "Vaihtuvien vastaavien poikkeukselliset arvonalentumiset",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Liiketoiminnan tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Vaihtuvien vastaavien poikkeukselliset arvonalentumiset\"))",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Liikevaihto\\Poistot ja arvonalentumiset"
          },
          {
            "name": "Liiketoiminnan muut kulut",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Liiketoiminnan muut kulut\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Liikevaihto"
          },
          {
            "name": "Liikevoitto tai tappio",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Liikevoitto (-tappio)\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma"
          },
          {
            "name": "Rahoitustuotot ja -kulut yhteensä",
            "expression": "SUMX(FILTER(Muuttujat,Muuttujat[tili_koodi]=\"rahoitustuotot_ja_kulut\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma"
          },
          {
            "name": "Tuotot osuuksista saman konsernin yrityksissä ",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Liiketoiminnan tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Tuotot osuuksista saman konsernin yrityksissä\"))",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Rahoitustuotot ja -kulut"
          },
          {
            "name": "Tuotot osuuksista omistusyhteysyrityksissä ",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Tuotot osuuksista omistusyhteysyrityksissä\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Rahoitustuotot ja -kulut"
          },
          {
            "name": "Tuotot muista pysyvien vastaavien sijoituksista yhteensä ",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso2_fi]=\"Tuotot muista pysyvien vastaavien sijoituksista\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Rahoitustuotot ja -kulut"
          },
          {
            "name": "Tuotot muista pysyvien vastaavien sijoituksista saman konsernin yrityksiltä",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Tuotot muista pysyvien vastaavien sijoituksista saman konsernin yrityksiltä\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Rahoitustuotot ja -kulut\\Tuotot muista pysyvien vastaavien sijoituksista"
          },
          {
            "name": "Tuotot muista pysyvien vastaavien sijoituksista muilta ",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Tuotot muista pysyvien vastaavien sijoituksista muilta\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Rahoitustuotot ja -kulut\\Tuotot muista pysyvien vastaavien sijoituksista"
          },
          {
            "name": "Muut korko- ja rahoitustuotot yhteensä",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso2_fi]=\"Muut korko- ja rahoitustuotot\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Rahoitustuotot ja -kulut"
          },
          {
            "name": "Muut korko- ja rahoitustuotot saman konsernin yrityksiltä",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Muut korko- ja rahoitustuotot saman konsernin yrityksiltä\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Rahoitustuotot ja -kulut\\Muut korko- ja rahoitustuotot"
          },
          {
            "name": "Muut korko- ja rahoitustuotot muilta",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Muut korko- ja rahoitustuotot muilta\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Rahoitustuotot ja -kulut\\Muut korko- ja rahoitustuotot"
          },
          {
            "name": "Arvonalentumiset pysyvien vastaavien sijoituksista ",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Liiketoiminnan tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Arvonalentumiset pysyvien vastaavien sijoituksista\"))",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Rahoitustuotot ja -kulut"
          },
          {
            "name": "Arvonalentumiset vaihtuvien vastaavien rahoitusarvopapereista ",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Liiketoiminnan tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Arvonalentumiset vaihtuvien vastaavien rahoitusarvopapereista\"))",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Rahoitustuotot ja -kulut"
          },
          {
            "name": "Korkokulut ja muut rahoituskulut yhteensä",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso2_fi]=\"Korkokulut ja muut rahoituskulut\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Rahoitustuotot ja -kulut"
          },
          {
            "name": "Korkokulut ja muut rahoituskulut saman konsernin yrityksille",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Korkokulut ja muut rahoituskulut saman konsernin yrityksille\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Rahoitustuotot ja -kulut\\Korkokulut ja muut rahoituskulut muille"
          },
          {
            "name": "Korkokulut ja muut rahoituskulut muille",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Korkokulut ja muut rahoituskulut muille\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Rahoitustuotot ja -kulut\\Korkokulut ja muut rahoituskulut muille"
          },
          {
            "name": "Voitto tai tappio ennen satunnaisia eriä",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso5_fi]=\"Voitto (tappio) ennen satunnaisia eriä\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma"
          },
          {
            "name": "Satunnaiset erät yhteensä",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Liiketoiminnan tuloslaskelma\"), FILTER(Muuttujat,[tili_taso1_fi]=\"Satunnaiset erät\"))",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Satunnaiset erät"
          },
          {
            "name": "Liiketoiminnan satunnaiset tuotot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Liiketoiminnan tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Satunnaiset tuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Satunnaiset erät"
          },
          {
            "name": "Liiketoiminnan satunnaiset kulut",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Liiketoiminnan tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Satunnaiset kulut\"))",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Satunnaiset erät"
          },
          {
            "name": "Voitto tai tappio ennen tilinpäätössiirtoja ja veroja",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Liiketoiminnan tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Voitto (tappio) ennen tilinpäätössiirtoja ja veroja\"))",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma"
          },
          {
            "name": "Tilinpäätössiirrot (ml. tuloverot)",
            "expression": "CALCULATE([Poistoeron muutos (+/-)]+[Sidottujen rahastojen muutos yhteensä]+[Omakatteisten rahastojen muutos yhteensä]-[Tuloverot]+[Konserni: Vähemmistöosuudet])",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\K) Tilikauden tulos"
          },
          {
            "name": "Poistoeron lisäys tai vähennys",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Liiketoiminnan tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Poistoeron lisäys (-) tai vähennys (+)\"))",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Tilinpäätössiirrot ja verot"
          },
          {
            "name": "Vapaaehtoisten varausten lisäys tai vähennys",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Liiketoiminnan tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Vapaaehtoisten varausten lisäys (-) tai vähennys (+)\"))",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Tilinpäätössiirrot ja verot"
          },
          {
            "name": "Liiketoiminnan tuloverot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Liiketoiminnan tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Tuloverot\"))",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Tilinpäätössiirrot ja verot"
          },
          {
            "name": "Muut välittömät verot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Liiketoiminnan tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Muut välittömät verot\"))",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Tilinpäätössiirrot ja verot"
          },
          {
            "name": "Tilikauden voitto tai tappio",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Liiketoiminnan tuloslaskelma\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Tilikauden voitto (tappio)\"))",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma"
          },
          {
            "name": "Ministeriöt yhteensä",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso4_fi]=\"Ulkoasiainministeriö\"),[arvo])+SUMX(FILTER(Muuttujat,[tili_taso4_fi]=\"Oikeusministeriö\"),[arvo])+SUMX(FILTER(Muuttujat,[tili_taso4_fi]=\"Sisäasiainministeriö\"),[arvo])+SUMX(FILTER(Muuttujat,[tili_taso4_fi]=\"Puolustusministeriö\"),[arvo])+SUMX(FILTER(Muuttujat,[tili_taso4_fi]=\"Valtiovarainministeriö \"),[arvo])+SUMX(FILTER(Muuttujat,[tili_taso4_fi]=\"Maa- ja metsätalousministeriö\"),[arvo])+SUMX(FILTER(Muuttujat,[tili_taso4_fi]=\"Liikenne- ja viestintäministeriö\"),[arvo])+SUMX(FILTER(Muuttujat,[tili_taso4_fi]=\"Sosiaali- ja terveysministeriö\"),[arvo])+SUMX(FILTER(Muuttujat,[tili_taso4_fi]=\"Ympäristöministeriö\"),[arvo])+SUMX(FILTER(Muuttujat,[tili_taso4_fi]=\"Muu opetus- ja kulttuuriministeriö\"),[arvo])+SUMX(FILTER(Muuttujat,[tili_taso4_fi]=\"Muu työ- ja elinkeinoministeriö\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot\\Kotimainen ulkopuolinen rahoitus"
          },
          {
            "name": "Henkilöstökulut yhteensä",
            "expression": "CALCULATE([Henkilöstösivukulut: Eläkekulut]+[Henkilöstösivukulut: Muut henkilösivukulut]+[Palkat ja palkkiot]+[Konserni; Henkilöstökulut])",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\E) Kulut"
          },
          {
            "name": "Konserni; Avustustuotot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', AND( [tili_koodi] =\"avustust\",[Konserni]=\"Kyllä\")))",
            "displayFolder": "Tuloslaskelma\\B) Avustustuottojen jaottelu"
          },
          {
            "name": "Sijoitus-ja rahoitustoiminta, nettotuotto",
            "expression": "CALCULATE([Varsinaisen sijoitustoiminnan tuotot yhteensä]-[Varsinaisen sijoitustoiminnan kulut yhteensä]+[Rahoitustuotot ja -kulut (netto)]+ [Käyvän arvon muutos (+/-)])",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\G) Sijoitustoiminta"
          },
          {
            "name": "Kotimaiset korkeakoulut",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tutkimusmenot\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Kotimaiset korkeakoulut\"))",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot\\Kotimainen ulkopuolinen rahoitus"
          },
          {
            "name": "Perusrahoitus",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Tutkimusmenot\"), FILTER(Muuttujat,[tili_taso5_fi]=\"Perusrahoitus\"))",
            "formatString": "#,0",
            "displayFolder": "Tutkimusmenot"
          },
          {
            "name": "(Summa) - Lyhytaikaiset saamiset",
            "expression": "1",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Liikevaihto\\Materiaalit ja palvelut"
          },
          {
            "name": "Liiketoiminnan henkilöstökulut",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Liiketoiminnan tuloslaskelma\"), FILTER(Muuttujat,[tili_koodi]=\"henkilostokulut\"))",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Liikevaihto"
          },
          {
            "name": "Tilinpäätössiirrot (liiketoiminta)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Liiketoiminnan tuloslaskelma\"), FILTER(Muuttujat,[tili_koodi]=\"tilinpaatossiirrot\"))",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma\\Tilinpäätössiirrot ja verot"
          },
          {
            "name": "Tilinpäätössiirrot ja verot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_taso0_fi] = \"Liiketoiminnan tuloslaskelma\"), FILTER(Muuttujat,OR([tili_koodi]=\"tilinpaatossiirrot\",OR([tili_koodi]=\"muut_valittomat_verot\",([tili_koodi]=\"tuloverot\")))))",
            "formatString": "#,0",
            "displayFolder": "Liiketoiminnan tuloslaskelma"
          },
          {
            "name": "Varsinaisen toiminnan tuotot yhteensä",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Toiminnot yhteensä\"), FILTER('Muuttujat', [tili_taso1_fi] = \"Tuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Toiminnot yhteensä\\Tuotot"
          },
          {
            "name": "Varsinaisen toiminnan tuotot yhteensä (koulutus)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Koulutustoiminta\"), FILTER('Muuttujat', [tili_taso1_fi] = \"Tuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Koulutus\\Tuotot"
          },
          {
            "name": "Varsinaisen toiminnan tuotot yhteensä (tutkimus)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Tutkimustoiminta\"), FILTER('Muuttujat', [tili_taso1_fi] = \"Tuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Tutkimus\\Tuotot"
          },
          {
            "name": "Varsinaisen toiminnan tuotot yhteensä (taiteellinen toiminta)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Taiteellinen toiminta\"), FILTER('Muuttujat', [tili_taso1_fi] = \"Tuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Taiteellinen toiminta\\Tuotot"
          },
          {
            "name": "Varsinaisen toiminnan tuotot yhteensä (muu yhteiskunnallinen toiminta)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Muu yhteiskunnallinen toiminta\"), FILTER('Muuttujat', [tili_taso1_fi] = \"Tuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Muu yhteiskunnallinen toiminta\\Tuotot"
          },
          {
            "name": "Varsinaisen toiminnan tuotot yhteensä (harjoittelukoulut)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Harjoittelukoulu\"), FILTER('Muuttujat', [tili_taso1_fi] = \"Tuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Harjoittelukoulut\\Tuotot"
          },
          {
            "name": "Varsinaisen liiketoiminnan tuotot yhteensä (kansalliskirjasto)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Kansalliskirjasto\"), FILTER('Muuttujat', [tili_taso1_fi] = \"Tuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Kansalliskirjasto\\Tuotot"
          },
          {
            "name": "Avustustuotot (toiminnot yhteensä)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Toiminnot yhteensä\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Avustustuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Toiminnot yhteensä\\Tuotot"
          },
          {
            "name": "Avustustuotot (koulutus)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Koulutustoiminta\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Avustustuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Koulutus\\Tuotot"
          },
          {
            "name": "Avustustuotot (tutkimus)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Tutkimustoiminta\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Avustustuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Tutkimus\\Tuotot"
          },
          {
            "name": "Avustustuotot (taiteellinen toiminta)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Taiteellinen toiminta\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Avustustuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Taiteellinen toiminta\\Tuotot"
          },
          {
            "name": "Avustustuotot (muu yhteiskunnallinen toiminta)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Muu yhteiskunnallinen toiminta\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Avustustuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Muu yhteiskunnallinen toiminta\\Tuotot"
          },
          {
            "name": "Avustustuotot (harjoittelukoulut)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Harjoittelukoulu\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Avustustuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Harjoittelukoulut\\Tuotot"
          },
          {
            "name": "Avustustuotot (kansalliskirjasto)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Kansalliskirjasto\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Avustustuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Kansalliskirjasto\\Tuotot"
          },
          {
            "name": "Liiketoiminnan tuotot (toiminnot yhteensä)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Toiminnot yhteensä\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Liiketoiminnan tuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Toiminnot yhteensä\\Tuotot"
          },
          {
            "name": "Liiketoiminnan tuotot (koulutus)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Koulutustoiminta\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Liiketoiminnan tuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Koulutus\\Tuotot"
          },
          {
            "name": "Liiketoiminnan tuotot (tutkimus)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Tutkimustoiminta\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Liiketoiminnan tuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Tutkimus\\Tuotot"
          },
          {
            "name": "Liiketoiminnan tuotot (taiteellinen toiminta)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Taiteellinen toiminta\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Liiketoiminnan tuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Taiteellinen toiminta\\Tuotot"
          },
          {
            "name": "Liiketoiminnan tuotot (muu yhteiskunnallinen toiminta)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Muu yhteiskunnallinen toiminta\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Liiketoiminnan tuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Muu yhteiskunnallinen toiminta\\Tuotot"
          },
          {
            "name": "Liiketoiminnan tuotot (harjoittelukoulut)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Harjoittelukoulu\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Liiketoiminnan tuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Harjoittelukoulut\\Tuotot"
          },
          {
            "name": "Liiketoiminnan tuotot (kansalliskirjasto)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Kansalliskirjasto\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Liiketoiminnan tuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Kansalliskirjasto\\Tuotot"
          },
          {
            "name": "Muut tuotot (toiminnot yhteensä)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Toiminnot yhteensä\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Muut tuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Toiminnot yhteensä\\Tuotot"
          },
          {
            "name": "Muut tuotot (koulutus)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Koulutustoiminta\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Muut tuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Koulutus\\Tuotot"
          },
          {
            "name": "Muut tuotot (tutkimus)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Tutkimustoiminta\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Muut tuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Tutkimus\\Tuotot"
          },
          {
            "name": "Muut tuotot (taiteellinen toiminta)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Taiteellinen toiminta\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Muut tuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Taiteellinen toiminta\\Tuotot"
          },
          {
            "name": "Muut tuotot (muu yhteiskunnallinen toiminta)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Muu yhteiskunnallinen toiminta\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Muut tuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Muu yhteiskunnallinen toiminta\\Tuotot"
          },
          {
            "name": "Muut tuotot (harjoittelukoulut)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Harjoittelukoulu\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Muut tuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Harjoittelukoulut\\Tuotot"
          },
          {
            "name": "Muut tuotot (kansalliskirjasto)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Kansalliskirjasto\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Muut tuotot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Kansalliskirjasto\\Tuotot"
          },
          {
            "name": "Kulut yhteensä (kaikki toiminnot)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Toiminnot yhteensä\"), FILTER('Muuttujat', [tili_taso1_fi] = \"Kulut\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Toiminnot yhteensä\\Kulut"
          },
          {
            "name": "Kulut yhteensä (koulutus)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Koulutustoiminta\"), FILTER('Muuttujat', [tili_taso1_fi] = \"Kulut\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Koulutus\\Kulut"
          },
          {
            "name": "Kulut yhteensä (tutkimus)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Tutkimustoiminta\"), FILTER('Muuttujat', [tili_taso1_fi] = \"Kulut\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Tutkimus\\Kulut"
          },
          {
            "name": "Kulut yhteensä (taiteellinen toiminta)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Taiteellinen toiminta\"), FILTER('Muuttujat', [tili_taso1_fi] = \"Kulut\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Taiteellinen toiminta\\Kulut"
          },
          {
            "name": "Kulut yhteensä (muu yhteiskunnallinen toiminta)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Muu yhteiskunnallinen toiminta\"), FILTER('Muuttujat', [tili_taso1_fi] = \"Kulut\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Muu yhteiskunnallinen toiminta\\Kulut"
          },
          {
            "name": "Kulut yhteensä (harjoittelukoulut)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Harjoittelukoulu\"), FILTER('Muuttujat', [tili_taso1_fi] = \"Kulut\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Harjoittelukoulut\\Kulut"
          },
          {
            "name": "Kulut yhteensä (kansalliskirjasto)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Kansalliskirjasto\"), FILTER('Muuttujat', [tili_taso1_fi] = \"Kulut\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Kansalliskirjasto\\Kulut"
          },
          {
            "name": "Kulut yhteensä (yhteiskulut)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Yhteiskulut\"), FILTER('Muuttujat', [tili_taso1_fi] = \"Kulut\"),FILTER('Muuttujat',[tili_taso2_fi] = \"Kulut\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Yhteiskulut\\Kulut"
          },
          {
            "name": "Henkilöstökulut (toiminnot yhteensä)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Toiminnot yhteensä\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Henkilöstökulut\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Toiminnot yhteensä\\Kulut"
          },
          {
            "name": "Henkilöstökulut (koulutus)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Koulutustoiminta\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Henkilöstökulut\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Koulutus\\Kulut"
          },
          {
            "name": "Henkilöstökulut (tutkimus)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Tutkimustoiminta\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Henkilöstökulut\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Tutkimus\\Kulut"
          },
          {
            "name": "Henkilöstökulut (taiteellinen toiminta)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Taiteellinen toiminta\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Henkilöstökulut\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Taiteellinen toiminta\\Kulut"
          },
          {
            "name": "Henkilöstökulut (muu yhteiskunnallinen toiminta)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Muu yhteiskunnallinen toiminta\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Henkilöstökulut\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Muu yhteiskunnallinen toiminta\\Kulut"
          },
          {
            "name": "Henkilöstökulut (harjoittelukoulut)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Harjoittelukoulu\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Henkilöstökulut\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Harjoittelukoulut\\Kulut"
          },
          {
            "name": "Henkilöstökulut (kansalliskirjasto)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Kansalliskirjasto\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Henkilöstökulut\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Kansalliskirjasto\\Kulut"
          },
          {
            "name": "Henkilöstökulut (yhteiskulut)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Yhteiskulut\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Henkilöstökulut\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Yhteiskulut\\Kulut"
          },
          {
            "name": "Poistot (toiminnot yhteensä)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Toiminnot yhteensä\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Poistot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Toiminnot yhteensä\\Kulut"
          },
          {
            "name": "Poistot (koulutus)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Koulutustoiminta\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Poistot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Koulutus\\Kulut"
          },
          {
            "name": "Poistot (tutkimus)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Tutkimustoiminta\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Poistot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Tutkimus\\Kulut"
          },
          {
            "name": "Poistot (taiteellinen toiminta)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Taiteellinen toiminta\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Poistot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Taiteellinen toiminta\\Kulut"
          },
          {
            "name": "Poistot (muu yhteiskunnallinen toiminta)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Muu yhteiskunnallinen toiminta\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Poistot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Muu yhteiskunnallinen toiminta\\Kulut"
          },
          {
            "name": "Poistot (harjoittelukoulut)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Harjoittelukoulu\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Poistot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Harjoittelukoulut\\Kulut"
          },
          {
            "name": "Poistot (kansalliskirjasto)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Kansalliskirjasto\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Poistot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Kansalliskirjasto\\Kulut"
          },
          {
            "name": "Poistot (yhteiskulut)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Yhteiskulut\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Poistot\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Yhteiskulut\\Kulut"
          },
          {
            "name": "Muut kulut (toiminnot yhteensä)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Toiminnot yhteensä\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Muut kulut\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Toiminnot yhteensä\\Kulut"
          },
          {
            "name": "Muut kulut (koulutus)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Koulutustoiminta\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Muut kulut\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Koulutus\\Kulut"
          },
          {
            "name": "Muut kulut (tutkimus)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Tutkimustoiminta\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Muut kulut\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Tutkimus\\Kulut"
          },
          {
            "name": "Muut kulut (taiteellinen toiminta)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Taiteellinen toiminta\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Muut kulut\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Taiteellinen toiminta\\Kulut"
          },
          {
            "name": "Muut kulut (muu yhteiskunnallinen toiminta)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Muu yhteiskunnallinen toiminta\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Muut kulut\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Muu yhteiskunnallinen toiminta\\Kulut"
          },
          {
            "name": "Muut kulut (harjoittelukoulut)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Harjoittelukoulu\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Muut kulut\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Harjoittelukoulut\\Kulut"
          },
          {
            "name": "Muut kulut (kansalliskirjasto)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Kansalliskirjasto\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Muut kulut\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Kansalliskirjasto\\Kulut"
          },
          {
            "name": "Muut kulut (yhteiskulut)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Yhteiskulut\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Muut kulut\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Yhteiskulut\\Kulut"
          },
          {
            "name": "Osuus yhteisistä kuluista (koulutus)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Koulutustoiminta\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Osuus yhteisistä kuluista\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Koulutus\\Kulut"
          },
          {
            "name": "Osuus yhteisistä kuluista (tutkimus)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Tutkimustoiminta\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Osuus yhteisistä kuluista\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Tutkimus\\Kulut"
          },
          {
            "name": "Osuus yhteisista kuluista (taiteellinen toiminta)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Taiteellinen toiminta\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Osuus yhteisistä kuluista\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Taiteellinen toiminta\\Kulut"
          },
          {
            "name": "Osuus yhteisistä kuluista (muu yhteiskunnallinen toiminta)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Muu yhteiskunnallinen toiminta\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Osuus yhteisistä kuluista\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Muu yhteiskunnallinen toiminta\\Kulut"
          },
          {
            "name": "Osuus yhteisista kuluista (harjoittelukoulut)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Harjoittelukoulu\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Osuus yhteisistä kuluista\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Harjoittelukoulut\\Kulut"
          },
          {
            "name": "Osuus yhteisista kuluista (kansalliskirjasto)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Kansalliskirjasto\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Osuus yhteisistä kuluista\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Kansalliskirjasto\\Kulut"
          },
          {
            "name": "Osuus yhteisistä kuluista (yhteiskulut)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [Toiminto_nimi_fi] = \"Yhteiskulut\"), FILTER('Muuttujat', [tili_taso5_fi] = \"Osuus yhteisistä kuluista\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely\\Yhteiskulut\\Kulut"
          },
          {
            "name": "Korkeakoulujen valtionrahoitus (toiminnot)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"kkvaltrah\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely"
          },
          {
            "name": "Avustustuotot (toiminnot)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"ttavustu\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely"
          },
          {
            "name": "Liiketoiminnan tuotot (toiminnot)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"liiketuo\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely"
          },
          {
            "name": "Muut tuotot (toiminnot)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"muuttuot2\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely"
          },
          {
            "name": "Varsinaisen toiminnan tuotot yhteensä (toiminnot)",
            "expression": "CALCULATE([Korkeakoulujen valtionrahoitus (toiminnot)]+[Avustustuotot (toiminnot)]+[Liiketoiminnan tuotot (toiminnot)]+[Muut tuotot (toiminnot)])",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely"
          },
          {
            "name": "Kulut yhteensä (toiminnot)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"kulutyht\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely"
          },
          {
            "name": "Kuluista katettu omakatteisista rahastoista tai sidotuista rahastoista (toiminnot)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"kulkat\"))",
            "formatString": "#,0",
            "displayFolder": "Toimintokohtainen erittely"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dw].[v_st_talous_yhteinen].* FROM [dw].[v_st_talous_yhteinen] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "v_st_talous_yhteinen"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dw"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Koodit_aineisto</string>",
              "      </key>",
              "      <value>",
              "        <int>103</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit_koulutusala</string>",
              "      </key>",
              "      <value>",
              "        <int>120</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit_yliopisto</string>",
              "      </key>",
              "      <value>",
              "        <int>105</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Material type</string>",
              "      </key>",
              "      <value>",
              "        <int>93</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Utbildningsområde</string>",
              "      </key>",
              "      <value>",
              "        <int>118</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>University</string>",
              "      </key>",
              "      <value>",
              "        <int>78</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Statistical year</string>",
              "      </key>",
              "      <value>",
              "        <int>101</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Field of education</string>",
              "      </key>",
              "      <value>",
              "        <int>115</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Material typ</string>",
              "      </key>",
              "      <value>",
              "        <int>87</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Universitet</string>",
              "      </key>",
              "      <value>",
              "        <int>82</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>arvo</string>",
              "      </key>",
              "      <value>",
              "        <int>52</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso4_en</string>",
              "      </key>",
              "      <value>",
              "        <int>91</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso3_en</string>",
              "      </key>",
              "      <value>",
              "        <int>91</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso2_en</string>",
              "      </key>",
              "      <value>",
              "        <int>91</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso1_en</string>",
              "      </key>",
              "      <value>",
              "        <int>91</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso0_en</string>",
              "      </key>",
              "      <value>",
              "        <int>91</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso4_sv</string>",
              "      </key>",
              "      <value>",
              "        <int>90</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso3_sv</string>",
              "      </key>",
              "      <value>",
              "        <int>90</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso2_sv</string>",
              "      </key>",
              "      <value>",
              "        <int>90</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso1_sv</string>",
              "      </key>",
              "      <value>",
              "        <int>90</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso0_sv</string>",
              "      </key>",
              "      <value>",
              "        <int>90</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso4_fi</string>",
              "      </key>",
              "      <value>",
              "        <int>85</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso3_fi</string>",
              "      </key>",
              "      <value>",
              "        <int>85</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso2_fi</string>",
              "      </key>",
              "      <value>",
              "        <int>85</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso1_fi</string>",
              "      </key>",
              "      <value>",
              "        <int>85</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso0_fi</string>",
              "      </key>",
              "      <value>",
              "        <int>85</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Statistikår</string>",
              "      </key>",
              "      <value>",
              "        <int>78</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Aineisto</string>",
              "      </key>",
              "      <value>",
              "        <int>68</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusala</string>",
              "      </key>",
              "      <value>",
              "        <int>85</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>d6.erittely_nimi_fi</string>",
              "      </key>",
              "      <value>",
              "        <int>116</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>toiminto_nimi_fi</string>",
              "      </key>",
              "      <value>",
              "        <int>104</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tilastovuosi</string>",
              "      </key>",
              "      <value>",
              "        <int>86</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso5_fi</string>",
              "      </key>",
              "      <value>",
              "        <int>85</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso5_sv</string>",
              "      </key>",
              "      <value>",
              "        <int>90</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso5_en</string>",
              "      </key>",
              "      <value>",
              "        <int>91</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Konserni</string>",
              "      </key>",
              "      <value>",
              "        <int>71</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ohjauksenala</string>",
              "      </key>",
              "      <value>",
              "        <int>95</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ohjauksenala_sv</string>",
              "      </key>",
              "      <value>",
              "        <int>112</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ohjauksenala_en</string>",
              "      </key>",
              "      <value>",
              "        <int>113</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit_ohjauksenala</string>",
              "      </key>",
              "      <value>",
              "        <int>129</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Korkeakoulu</string>",
              "      </key>",
              "      <value>",
              "        <int>88</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_koodi</string>",
              "      </key>",
              "      <value>",
              "        <int>71</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Sektori</string>",
              "      </key>",
              "      <value>",
              "        <int>63</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Koodit_aineisto</string>",
              "      </key>",
              "      <value>",
              "        <int>30</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit_koulutusala</string>",
              "      </key>",
              "      <value>",
              "        <int>29</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit_yliopisto</string>",
              "      </key>",
              "      <value>",
              "        <int>28</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Material type</string>",
              "      </key>",
              "      <value>",
              "        <int>27</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Utbildningsområde</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>University</string>",
              "      </key>",
              "      <value>",
              "        <int>26</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Statistical year</string>",
              "      </key>",
              "      <value>",
              "        <int>25</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Field of education</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Material typ</string>",
              "      </key>",
              "      <value>",
              "        <int>24</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Universitet</string>",
              "      </key>",
              "      <value>",
              "        <int>23</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>arvo</string>",
              "      </key>",
              "      <value>",
              "        <int>17</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso4_en</string>",
              "      </key>",
              "      <value>",
              "        <int>16</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso3_en</string>",
              "      </key>",
              "      <value>",
              "        <int>15</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso2_en</string>",
              "      </key>",
              "      <value>",
              "        <int>14</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso1_en</string>",
              "      </key>",
              "      <value>",
              "        <int>13</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso0_en</string>",
              "      </key>",
              "      <value>",
              "        <int>12</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso4_sv</string>",
              "      </key>",
              "      <value>",
              "        <int>11</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso3_sv</string>",
              "      </key>",
              "      <value>",
              "        <int>10</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso2_sv</string>",
              "      </key>",
              "      <value>",
              "        <int>9</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso1_sv</string>",
              "      </key>",
              "      <value>",
              "        <int>8</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso0_sv</string>",
              "      </key>",
              "      <value>",
              "        <int>7</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso4_fi</string>",
              "      </key>",
              "      <value>",
              "        <int>6</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso3_fi</string>",
              "      </key>",
              "      <value>",
              "        <int>5</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso2_fi</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso1_fi</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso0_fi</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Statistikår</string>",
              "      </key>",
              "      <value>",
              "        <int>22</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Aineisto</string>",
              "      </key>",
              "      <value>",
              "        <int>21</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusala</string>",
              "      </key>",
              "      <value>",
              "        <int>20</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>d6.erittely_nimi_fi</string>",
              "      </key>",
              "      <value>",
              "        <int>39</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>toiminto_nimi_fi</string>",
              "      </key>",
              "      <value>",
              "        <int>18</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tilastovuosi</string>",
              "      </key>",
              "      <value>",
              "        <int>19</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso5_fi</string>",
              "      </key>",
              "      <value>",
              "        <int>31</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso5_sv</string>",
              "      </key>",
              "      <value>",
              "        <int>32</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso5_en</string>",
              "      </key>",
              "      <value>",
              "        <int>33</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Konserni</string>",
              "      </key>",
              "      <value>",
              "        <int>34</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ohjauksenala</string>",
              "      </key>",
              "      <value>",
              "        <int>35</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ohjauksenala_sv</string>",
              "      </key>",
              "      <value>",
              "        <int>36</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ohjauksenala_en</string>",
              "      </key>",
              "      <value>",
              "        <int>37</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit_ohjauksenala</string>",
              "      </key>",
              "      <value>",
              "        <int>38</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Korkeakoulu</string>",
              "      </key>",
              "      <value>",
              "        <int>40</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_koodi</string>",
              "      </key>",
              "      <value>",
              "        <int>41</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Sektori</string>",
              "      </key>",
              "      <value>",
              "        <int>42</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Statistical year</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>arvo</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso4_en</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso3_en</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso2_en</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso1_en</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso0_en</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso4_sv</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso3_sv</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso2_sv</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso1_sv</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso0_sv</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso4_fi</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso3_fi</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso2_fi</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso1_fi</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso0_fi</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Material typ</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Universitet</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Statistikår</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Aineisto</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>toiminto_nimi_fi</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusala</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>d6.erittely_nimi_fi</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tilastovuosi</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>University</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Material type</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit_yliopisto</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit_koulutusala</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit_aineisto</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso5_fi</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso5_sv</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso5_en</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ohjauksenala</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ohjauksenala_sv</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ohjauksenala_en</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit_ohjauksenala</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Korkeakoulu</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_koodi</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Sektori</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Sarakeleveys",
        "columns": [
          {
            "name": "Sarakeleveys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Sarakeleveys",
            "sourceProviderType": "Char",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "leveys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "leveys",
            "sourceProviderType": "Char",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Sarakeleveys",
            "dataView": "full",
            "source": {
              "query": " SELECT [dw].[Sarakeleveys].* FROM [dw].[Sarakeleveys] ",
              "dataSource": "ANTERO"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Sarakeleveys</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>94</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>leveys</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>61</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Sarakeleveys</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>leveys</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked />",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dw].[Sarakeleveys].* FROM [dw].[Sarakeleveys] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Sarakeleveys"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dw"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Sarakeleveys</string>",
              "      </key>",
              "      <value>",
              "        <int>94</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>leveys</string>",
              "      </key>",
              "      <value>",
              "        <int>61</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Sarakeleveys</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>leveys</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked />",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      }
    ],
    "perspectives": [
      {
        "name": "Toimintokohtainen erittely",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Korkeakoulu"
              },
              {
                "name": "Sektori"
              },
              {
                "name": "Toiminnon nimi"
              },
              {
                "name": "Suodatus tilastovuosi"
              }
            ],
            "measures": [
              {
                "name": "Avustustuotot (toiminnot)"
              },
              {
                "name": "Kulut yhteensä (toiminnot)"
              },
              {
                "name": "Liiketoiminnan tuotot (toiminnot)"
              },
              {
                "name": "Muut tuotot (toiminnot)"
              },
              {
                "name": "Varsinaisen toiminnan tuotot yhteensä (toiminnot)"
              },
              {
                "name": "Korkeakoulujen valtionrahoitus (toiminnot)"
              },
              {
                "name": "Kuluista katettu omakatteisista rahastoista tai sidotuista rahastoista (toiminnot)"
              }
            ]
          }
        ]
      },
      {
        "name": "Tutkimusrahoitus",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Koulutusala"
              },
              {
                "name": "Ohjauksen ala"
              },
              {
                "name": "Suodatus tilastovuosi"
              },
              {
                "name": "Korkeakoulu"
              },
              {
                "name": "Sektori"
              }
            ],
            "measures": [
              {
                "name": "Business Finland "
              },
              {
                "name": "EAKR-rahoitus"
              },
              {
                "name": "ESR-rahoitus"
              },
              {
                "name": "EU-puiteohjelmarahoitus ja muu laadullisesti kilpailtu EU-rahoitus"
              },
              {
                "name": "Kansainväliset järjestöt"
              },
              {
                "name": "Kotimaiset korkeakoulut"
              },
              {
                "name": "Kotimaiset yksityiset rahastot ja säätiöt"
              },
              {
                "name": "Kotimaiset yritykset "
              },
              {
                "name": "Kunnat ja kuntainliitot"
              },
              {
                "name": "Liikenne- ja viestintäministeriö"
              },
              {
                "name": "Maa- ja metsätalousministeriö"
              },
              {
                "name": "Muu EU-rahoitus"
              },
              {
                "name": "Muu julkinen rahoitus"
              },
              {
                "name": "Muu ulkomainen rahoitus"
              },
              {
                "name": "Oikeusministeriö"
              },
              {
                "name": "Opetus- ja kulttuuriministeriö"
              },
              {
                "name": "Puolustusministeriö"
              },
              {
                "name": "Sisäasiainministeriö"
              },
              {
                "name": "Sosiaali- ja terveysministeriö"
              },
              {
                "name": "Suomen Akatemia "
              },
              {
                "name": "Työ- ja elinkeinoministeriö"
              },
              {
                "name": "Ulkoasiainministeriö"
              },
              {
                "name": "Ulkomaiset rahastot ja säätiöt"
              },
              {
                "name": "Ulkomaiset yritykset"
              },
              {
                "name": "Ulkopuolinen rahoitus yhteensä"
              },
              {
                "name": "Valtiovarainministeriö"
              },
              {
                "name": "Ympäristöministeriö"
              },
              {
                "name": "Korkeakoulun oma rahoitus yhteensä"
              },
              {
                "name": "Ministeriöt yhteensä"
              },
              {
                "name": "Tutkimusmenot yhteensä"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Tuloslaskelma",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Suodatus tilastovuosi"
              },
              {
                "name": "Korkeakoulu"
              },
              {
                "name": "Konserni"
              },
              {
                "name": "Sektori"
              }
            ],
            "measures": [
              {
                "name": "Korkokulut ja rahoituskulut saman konsernin yrityksille"
              },
              {
                "name": "Arvonalentumiset muiden pysyvien vastaavien sijoituksista"
              },
              {
                "name": "Arvonalentumiset vaihtuvien vastaavien rahoitusarvopapereista"
              },
              {
                "name": "Arvonalentumisten palautukset"
              },
              {
                "name": "Avustustuotot"
              },
              {
                "name": "Business Finland"
              },
              {
                "name": "EU-rahoitus"
              },
              {
                "name": "Euroopan Unionin maat, muu rahoitus"
              },
              {
                "name": "Euroopan Unionin maat, yritysrahoitus"
              },
              {
                "name": "Konserni; Henkilöstökulut"
              },
              {
                "name": "Henkilöstösivukulut: Eläkekulut"
              },
              {
                "name": "Henkilöstösivukulut: Muut henkilösivukulut"
              },
              {
                "name": "Keräysten ja lahjoitusten tuotot: kotitaloudet"
              },
              {
                "name": "Keräysten ja lahjoitusten tuotot: muut"
              },
              {
                "name": "Keräysten ja lahjoitusten tuotot: yritykset"
              },
              {
                "name": "Kone- ja laitevuokrat"
              },
              {
                "name": "Konserni: Vähemmistöosuudet"
              },
              {
                "name": "Korkeakoulujen valtionrahoitus"
              },
              {
                "name": "Korkokulut"
              },
              {
                "name": "Korkokulut ja rahoituskulut"
              },
              {
                "name": "Korkotuotot"
              },
              {
                "name": "Kotimaiset rahoituslaitokset"
              },
              {
                "name": "Kotimaiset yritykset"
              },
              {
                "name": "Kotitaloudet"
              },
              {
                "name": "Kunnat ja kuntayhtymät"
              },
              {
                "name": "LIIKEVOITTO (TAPPIO)"
              },
              {
                "name": "Liikevaihto"
              },
              {
                "name": "Varsinaisen sijoitustoiminnan tuotot yhteensä"
              },
              {
                "name": "Varsinaisen sijoitustoiminnan kulut yhteensä"
              },
              {
                "name": "Varsinaisen sijoitustoiminnan tuotto"
              },
              {
                "name": "Rahoitustuotot ja -kulut (netto)"
              },
              {
                "name": "Muu julkinen hallinto"
              },
              {
                "name": "Muu OKM"
              },
              {
                "name": "Muu valtio (pl. Business Finland, Akatemia, Sosiaaliturvarahastot ja muu OKM)"
              },
              {
                "name": "Muut kulut yhteensä"
              },
              {
                "name": "Muut sijoitustoiminnan tuotot"
              },
              {
                "name": "Muut ulkomaat, muu rahoitus"
              },
              {
                "name": "Muut ulkomaat, yritysrahoitus "
              },
              {
                "name": "Muut varainhankinnan kulut"
              },
              {
                "name": "Muut varainhankinnan tuotot"
              },
              {
                "name": "Muut varsinaisen toiminnan kulut"
              },
              {
                "name": "Myyntitappiot"
              },
              {
                "name": "Myyntituotot"
              },
              {
                "name": "Omakatteisten rahastojen muutos yhteensä"
              },
              {
                "name": "Osinkotuotot"
              },
              {
                "name": "Osuus osakkuusyhtiöiden tuloksesta (voitosta/tappiosta, +/-)"
              },
              {
                "name": "Palkat ja palkkiot"
              },
              {
                "name": "Palvelujen ostot"
              },
              {
                "name": "Poistoeron muutos (+/-)"
              },
              {
                "name": "Poistot ja arvonalentumiset"
              },
              {
                "name": "Suomen Akatemia"
              },
              {
                "name": "Tarvikkeet ja tavarat"
              },
              {
                "name": "Tilakustannukset"
              },
              {
                "name": "Tuloverot"
              },
              {
                "name": "Tuotot muista pysyvien vastaavien sijoituksista"
              },
              {
                "name": "Tuotot osuuksista omistusyhteysyrityksissä"
              },
              {
                "name": "Tuotot osuuksista saman konsernin yrityksissä"
              },
              {
                "name": "Ulkomainen liiketoiminta"
              },
              {
                "name": "Varainhankinnan liiketoiminnan kulut"
              },
              {
                "name": "Varainhankinnan liiketoiminnan tuotot"
              },
              {
                "name": "VOITTO (TAPPIO) ENNEN TILINPÄÄTÖS-SIIRTOJA JA VEROJA"
              },
              {
                "name": "Voittoa tavoittelemattomat yhteisöt (kirkot, säätiöt, puolueet, rahastot)"
              },
              {
                "name": "Vuokrakulut (vastikkeet)"
              },
              {
                "name": "Vuokratuotot"
              },
              {
                "name": "Rahoituskulut yhteensä"
              },
              {
                "name": "Kulut yhteensä"
              },
              {
                "name": "Rahoitustuotot yhteensä"
              },
              {
                "name": "Sidottujen rahastojen muutos yhteensä"
              },
              {
                "name": "Liiketoiminnan tuotot"
              },
              {
                "name": "Muut tuotot"
              },
              {
                "name": "Muut sijoitustoiminnan kulut"
              },
              {
                "name": "Keräysten ja lahjoitusten kulut"
              },
              {
                "name": "Käyvän arvon muutos (+/-)"
              },
              {
                "name": "Lahjoitusten tuotot: kotitaloudet"
              },
              {
                "name": "Lahjoitusten tuotot: muut"
              },
              {
                "name": "Lahjoitusten tuotot: yritykset"
              },
              {
                "name": "Lukukausimaksut"
              },
              {
                "name": "Maksuasetuksen perusteella perittävät maksut"
              },
              {
                "name": "Muut korko- ja rahoitustuotot"
              },
              {
                "name": "Muut muut tuotot"
              },
              {
                "name": "Pysyväisluontoinen yhteistyö koulutuksen tukitoimintojen järjestämisessä kahden verotonta koulutusta antavan oppilaitoksen välillä"
              },
              {
                "name": "Siirto rahastoon"
              },
              {
                "name": "Siirto rahastosta"
              },
              {
                "name": "Siirto sidottuun rahastoon"
              },
              {
                "name": "Siirto sidotusta rahastosta"
              },
              {
                "name": "TILIKAUDEN VOITTO (TAPPIO)"
              },
              {
                "name": "Varainhankinnan kulut yhteensä"
              },
              {
                "name": "Varainhankinnan tuotot yhteensä"
              },
              {
                "name": "Varainhankinta, nettotuotto"
              },
              {
                "name": "Harjoittelujen kotikuntakorvauksiin sisältyvä ALV"
              },
              {
                "name": "Harjoittelukoulun liiketoiminnan kulut"
              },
              {
                "name": "Muiden rajoittajien kompensoimat ALV"
              },
              {
                "name": "OKM kompensoitava ALV"
              },
              {
                "name": "OKM rahoitus harjoittelukouluille"
              },
              {
                "name": "VM rahoitus harjoittelukouluille"
              },
              {
                "name": "Korkeakoulun ALV-kulut yhteensä pl liiketoiminta"
              },
              {
                "name": "Henkilöstökulut yhteensä"
              },
              {
                "name": "Konserni; Avustustuotot"
              },
              {
                "name": "Sijoitus-ja rahoitustoiminta, nettotuotto"
              },
              {
                "name": "Tilinpäätössiirrot (ml. tuloverot)"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Varsinaisen toiminnan kustannukset pivot",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Ohjauksen ala"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Tarkennettu toiminto"
              },
              {
                "name": "Päätoiminto"
              },
              {
                "name": "Toiminto"
              },
              {
                "name": "Korkeakoulu"
              },
              {
                "name": "Konserni"
              },
              {
                "name": "Sektori"
              },
              {
                "name": "Suodatus tilastovuosi"
              }
            ],
            "measures": [
              {
                "name": "Korkeakoulun varsinaisen toiminnan kustannukset yhteensä"
              }
            ]
          }
        ]
      },
      {
        "name": "Tase",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Konserni"
              },
              {
                "name": "Korkeakoulu"
              },
              {
                "name": "Sektori"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Suodatus tilastovuosi"
              }
            ],
            "measures": [
              {
                "name": "Aineet ja tarvikkeet"
              },
              {
                "name": "Aineettomat oikeudet"
              },
              {
                "name": "Arvonkorotusrahasto"
              },
              {
                "name": "Edellisten tilikausien voitto (tappio)"
              },
              {
                "name": "Eläkevaraukset"
              },
              {
                "name": "Ennakkomaksut"
              },
              {
                "name": "Ennakkomaksut (vaihto-omaisuus)"
              },
              {
                "name": "Ennakkomaksut ja keskeneräiset hankinnat"
              },
              {
                "name": "Kehittämismenot"
              },
              {
                "name": "Keskeneräiset tuotteet"
              },
              {
                "name": "Koneet ja kalusto"
              },
              {
                "name": "Konserni-liikearvo"
              },
              {
                "name": "Konsernireservi"
              },
              {
                "name": "Liikearvo"
              },
              {
                "name": "Maa- ja vesialueet"
              },
              {
                "name": "Muu vaihto-omaisuus"
              },
              {
                "name": "Muut aineelliset hyödykkeet"
              },
              {
                "name": "Muut aineettomat hyödykkeet"
              },
              {
                "name": "Muut arvopaperit"
              },
              {
                "name": "Muut arvopaperit (rahoitusarvopaperit)"
              },
              {
                "name": "Muut osakkeet ja osuudet"
              },
              {
                "name": "Muut osakkeet ja osuudet (rahoitusarvopaperit)"
              },
              {
                "name": "Muut osakkeet ja osuudet (sijoitukset)"
              },
              {
                "name": "Muut pakolliset varaukset"
              },
              {
                "name": "Muut saamiset (sijoitukset)"
              },
              {
                "name": "Muut sidotut rahastot "
              },
              {
                "name": "Muut vapaat rahastot (esim. sijoitusrahasto)"
              },
              {
                "name": "Muut varat"
              },
              {
                "name": "Oma pääoma yhteensä"
              },
              {
                "name": "Omakatteiset rahastot "
              },
              {
                "name": "Omakatteisten rahastojen sijoitukset yhteensä"
              },
              {
                "name": "Omakatteisten rahastojen varat"
              },
              {
                "name": "Omakatteisten rahastojen velat"
              },
              {
                "name": "Osake-, osuus- tai muu vastaava pääoma / peruspääoma"
              },
              {
                "name": "Osuudet omistusyhteys-yrityksissä"
              },
              {
                "name": "Osuudet saman konsernin yrityksissä (rahoitusarvopaperit)"
              },
              {
                "name": "Osuudet saman konsernin yrityksissä (sijoitukset)"
              },
              {
                "name": "Poistoero"
              },
              {
                "name": "Pääomarahasto"
              },
              {
                "name": "Rahasto-osuudet"
              },
              {
                "name": "Rahat ja pankkisaamiset"
              },
              {
                "name": "Rahat ja pankkisaamiset (vaihtuvat)"
              },
              {
                "name": "Rakennukset ja rakennelmat"
              },
              {
                "name": "Saamiset omistusyhteys-yrityksiltä"
              },
              {
                "name": "Saamiset saman konsernin yrityksiltä"
              },
              {
                "name": "Sijoitetun vapaan oman pääoman rahasto"
              },
              {
                "name": "Tilikauden voitto (tai tappio)"
              },
              {
                "name": "Toimintapääoma"
              },
              {
                "name": "Valmiit tuotteet/ tavarat"
              },
              {
                "name": "Vararahasto"
              },
              {
                "name": "Vastaavaa yhteensä"
              },
              {
                "name": "Vastattavaa yhteensä"
              },
              {
                "name": "Verotusperäiset varaukset"
              },
              {
                "name": "Verovaraukset"
              },
              {
                "name": "Vähemmistöosuudet (konserni)"
              },
              {
                "name": "Yhtiöjärjestyksen tai sääntöjen mukaiset rahastot"
              },
              {
                "name": "Ylikurssirahasto"
              },
              {
                "name": "Lyhytaikaiset eläkelainat"
              },
              {
                "name": "Lyhytaikaiset joukkovelkakirjalainat"
              },
              {
                "name": "Lyhytaikaiset lainat rahoituslaitoksilta"
              },
              {
                "name": "Lyhytaikaiset muut velat"
              },
              {
                "name": "Lyhytaikaiset ostovelat"
              },
              {
                "name": "Lyhytaikaiset pääomalainat"
              },
              {
                "name": "Lyhytaikaiset rahoitusvekselit"
              },
              {
                "name": "Lyhytaikaiset saadut ennakot"
              },
              {
                "name": "Lyhytaikaiset siirtovelat"
              },
              {
                "name": "Lyhytaikaiset vaihtovelkakirjalainat"
              },
              {
                "name": "Lyhytaikaiset velat omistusyhteysyrityksille"
              },
              {
                "name": "Lyhytaikaiset velat saman konsernin yrityksille"
              },
              {
                "name": "Pitkäaikaiset muut velat"
              },
              {
                "name": "Pitkäaikaiset ostovelat"
              },
              {
                "name": "Pitkäaikaiset rahoitusvekselit"
              },
              {
                "name": "Pitkäaikaiset saadut ennakot"
              },
              {
                "name": "Pitkäaikaiset velat omistusyhteysyrityksille"
              },
              {
                "name": "Pitkäaikaiset velat saman konsernin yrityksille"
              },
              {
                "name": "Pitkäaikaiset eläkelainat"
              },
              {
                "name": "Pitkäaikaiset joukkovelkakirjalainat"
              },
              {
                "name": "Pitkäaikaiset lainasaamiset"
              },
              {
                "name": "Pitkäaikaiset lainat rahoituslaitoksilta"
              },
              {
                "name": "Pitkäaikaiset laskennaliset verovelat"
              },
              {
                "name": "Pitkäaikaiset laskennalliset verosaamiset"
              },
              {
                "name": "Pitkäaikaiset muut saamiset"
              },
              {
                "name": "Pitkäaikaiset myyntisaamiset"
              },
              {
                "name": "Pitkäaikaiset pääomalainat"
              },
              {
                "name": "Pitkäaikaiset saamiset omistusyhteysyrityksiltä"
              },
              {
                "name": "Pitkäaikaiset saamiset saman konsernin yrityksiltä"
              },
              {
                "name": "Pitkäaikaiset siirtosaamiset"
              },
              {
                "name": "Pitkäaikaiset siirtovelat"
              },
              {
                "name": "Pitkäaikaiset vaihtovelkakirjalainat"
              },
              {
                "name": "Lyhytaikaiset lainasaamiset"
              },
              {
                "name": "Lyhytaikaiset laskennalliset verosaamiset"
              },
              {
                "name": "Lyhytaikaiset laskennaliset verovelat"
              },
              {
                "name": "Lyhytaikaiset muut saamiset"
              },
              {
                "name": "Lyhytaikaiset myyntisaamiset"
              },
              {
                "name": "Lyhytaikaiset saamiset omistusyhteysyrityksiltä"
              },
              {
                "name": "Lyhytaikaiset saamiset saman konsernin yrityksiltä"
              },
              {
                "name": "Lyhytaikaiset siirtosaamiset"
              },
              {
                "name": "Omavaraisuusaste"
              },
              {
                "name": "Maksuvalmius"
              },
              {
                "name": "Toimintapääoman suhde omaan pääomaan"
              }
            ]
          }
        ]
      },
      {
        "name": "Liiketoiminnan tuloslaskelma",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Korkeakoulu"
              },
              {
                "name": "Sektori"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Suodatus tilastovuosi"
              }
            ],
            "measures": [
              {
                "name": "Liiketoiminnan muut kulut"
              },
              {
                "name": "Liiketoiminnan muut tuotot"
              },
              {
                "name": "Liiketoiminnan liikevaihto"
              },
              {
                "name": "Liikevoitto tai tappio"
              },
              {
                "name": "Poistot ja arvonalentumiset yhteensä"
              },
              {
                "name": "Rahoitustuotot ja -kulut yhteensä"
              },
              {
                "name": "Tilikauden voitto tai tappio"
              },
              {
                "name": "Valmiiden ja keskeneräisten tuotteiden varastojen lisäys tai vähennys"
              },
              {
                "name": "Valmistus omaan käyttöön"
              },
              {
                "name": "Voitto tai tappio ennen tilinpäätössiirtoja ja veroja"
              },
              {
                "name": "Liiketoiminnan henkilöstökulut"
              },
              {
                "name": "Tilinpäätössiirrot ja verot"
              }
            ]
          }
        ]
      }
    ],
    "roles": [
      {
        "name": "Testi",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "DWI\\T_VIPU_SSAS_DB_R",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1751"
          },
          {
            "memberName": "DWI\\T_VIPU_SSAS_DB_R_TK",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1753"
          },
          {
            "memberName": "DWI\\Z_T_Antero_Read_TAB",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-4155"
          },
          {
            "memberName": "DWI\\Z_P_Antero_Read_TAB",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-4156"
          },
          {
            "memberName": "DWI\\T_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1732"
          }
        ]
      },
      {
        "name": "Tuotanto",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "DWI\\P_VIPU_SSAS_DB_R",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1752"
          },
          {
            "memberName": "DWI\\P_VIPU_SSAS_DB_R_TK",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1754"
          },
          {
            "memberName": "NT AUTHORITY\\IUSR",
            "memberId": "S-1-5-17"
          },
          {
            "memberName": "DWI\\Z_T_Antero_Read_TAB",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-4155"
          },
          {
            "memberName": "DWI\\Z_P_Antero_Read_TAB",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-4156"
          },
          {
            "memberName": "DWI\\P_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1733"
          }
        ]
      }
    ]
  },
  "id": "SemanticModel"
}