{
  "name": "SemanticModel",
  "compatibilityLevel": 1200,
  "model": {
    "culture": "fi-FI",
    "dataSources": [
      {
        "name": "ANTERO",
        "connectionString": "Provider=SQLNCLI11;Data Source=dwitvipusql16;Initial Catalog=ANTERO;Integrated Security=SSPI;Persist Security Info=false",
        "impersonationMode": "impersonateServiceAccount",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "Muuttujat",
        "columns": [
          {
            "name": "Utbildningsområde",
            "dataType": "string",
            "sourceColumn": "Utbildningsområde",
            "sourceProviderType": "Char",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Field of education",
            "dataType": "string",
            "sourceColumn": "Field of education",
            "sourceProviderType": "Char",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "tili_taso0_fi",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "tili_taso0_fi"
          },
          {
            "name": "tili_taso1_fi",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "tili_taso1_fi"
          },
          {
            "name": "tili_taso2_fi",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "tili_taso2_fi"
          },
          {
            "name": "tili_taso3_fi",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "tili_taso3_fi"
          },
          {
            "name": "tili_taso4_fi",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "tili_taso4_fi"
          },
          {
            "name": "tili_taso0_sv",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "tili_taso0_sv"
          },
          {
            "name": "tili_taso1_sv",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "tili_taso1_sv"
          },
          {
            "name": "tili_taso2_sv",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "tili_taso2_sv"
          },
          {
            "name": "tili_taso3_sv",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "tili_taso3_sv"
          },
          {
            "name": "tili_taso4_sv",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "tili_taso4_sv"
          },
          {
            "name": "tili_taso0_en",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "tili_taso0_en"
          },
          {
            "name": "tili_taso1_en",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "tili_taso1_en"
          },
          {
            "name": "tili_taso2_en",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "tili_taso2_en"
          },
          {
            "name": "tili_taso3_en",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "tili_taso3_en"
          },
          {
            "name": "tili_taso4_en",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "tili_taso4_en"
          },
          {
            "name": "arvo",
            "dataType": "int64",
            "sourceColumn": "arvo",
            "formatString": "#,0.00 \"€\";-#,0.00 \"€\";#,0.00 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1035\" DisplayName=\"€ Finnish (Finland)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "toiminto_nimi_fi",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "toiminto_nimi_fi"
          },
          {
            "name": "Tilastovuosi",
            "dataType": "int64",
            "sourceColumn": "Tilastovuosi",
            "displayFolder": "Aikamuuttujat"
          },
          {
            "name": "Koulutusala",
            "dataType": "string",
            "sourceColumn": "Koulutusala",
            "sortByColumn": "Koodit_koulutusala",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "name": "Aineisto",
            "dataType": "string",
            "sourceColumn": "Aineisto"
          },
          {
            "name": "Statistikår",
            "dataType": "int64",
            "sourceColumn": "Statistikår"
          },
          {
            "name": "Universitet",
            "dataType": "string",
            "sourceColumn": "Universitet"
          },
          {
            "name": "Material typ",
            "dataType": "string",
            "sourceColumn": "Material typ"
          },
          {
            "name": "Statistical year",
            "dataType": "int64",
            "sourceColumn": "Statistical year"
          },
          {
            "name": "University",
            "dataType": "string",
            "sourceColumn": "University"
          },
          {
            "name": "Material type",
            "dataType": "string",
            "sourceColumn": "Material type"
          },
          {
            "name": "Koodit_yliopisto",
            "dataType": "string",
            "sourceColumn": "Koodit_yliopisto"
          },
          {
            "name": "Koodit_koulutusala",
            "dataType": "string",
            "sourceColumn": "Koodit_koulutusala"
          },
          {
            "name": "Koodit_aineisto",
            "dataType": "string",
            "sourceColumn": "Koodit_aineisto"
          },
          {
            "name": "tili_taso5_fi",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "tili_taso5_fi"
          },
          {
            "name": "tili_taso5_sv",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "tili_taso5_sv"
          },
          {
            "name": "tili_taso5_en",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "tili_taso5_en"
          },
          {
            "name": "Konserni",
            "dataType": "string",
            "sourceColumn": "konserni",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "Ohjauksenala_sv",
            "dataType": "string",
            "sourceColumn": "Ohjauksenala_sv"
          },
          {
            "name": "Ohjauksenala_en",
            "dataType": "string",
            "sourceColumn": "Ohjauksenala_en"
          },
          {
            "name": "Ohjauksen ala",
            "dataType": "string",
            "sourceColumn": "Ohjauksenala",
            "sortByColumn": "Koodit_ohjauksenala",
            "displayFolder": "Koulutusmuuttujat"
          },
          {
            "type": "calculated",
            "name": "Suodatus tilastovuosi",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "Muuttujat[Tilastovuosi]",
            "displayFolder": "Aikamuuttujat"
          },
          {
            "name": "Koodit_ohjauksenala",
            "dataType": "int64",
            "sourceColumn": "Koodit_ohjauksenala"
          },
          {
            "type": "calculated",
            "name": "Tarkennettu toiminto",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "",
              "SWITCH(TRUE(),",
              "Muuttujat[tili_taso5_fi]=\"Esiopetus\",\"Esiopetus\",",
              "Muuttujat[tili_taso5_fi]=\"Perusopetus\",\"Perusopetus\",",
              "Muuttujat[tili_taso5_fi]=\"Lukiokoulutus\",\"Lukiokoulutus\",",
              "Muuttujat[tili_taso5_fi]=\"Harjoittelu harjoittelukoulussa\",\"Harjoittelu harjoittelukoulussa\",",
              "Muuttujat[tili_taso5_fi]=\"Harjoittelu harjoittelukoulun ulkopuolella\",\"Harjoittelu harjoittelukoulun ulkopuolella\",",
              "Muuttujat[tili_taso5_fi]=\"Opettajankoulutuksen kehittäminen\",\"Opettajankoulutuksen kehittäminen\",",
              "Muuttujat[tili_taso5_fi]=\"Perustutkintokoulutus\",\"Perustutkintokoulutus\",",
              "Muuttujat[tili_taso5_fi]=\"Perustutkintojen osat\",\"Perustutkintojen osat\",",
              "Muuttujat[tili_taso5_fi]=\"Muu koulutus\",\"Muu koulutus\",",
              "Muuttujat[tili_taso5_fi]=\"Tieteellinen tutkimus\",\"Tieteellinen tutkimus\",",
              "Muuttujat[tili_taso5_fi]=\"Tieteellinen ja taiteellinen jatkotutkintokoulutus\",\"Tieteellinen ja taiteellinen jatkotutkintokoulutus\",",
              "Muuttujat[tili_taso5_fi]=\"Erillislakien mukaiset julkisoikeudelliset suoritteet\",\"Erillislakien mukaiset julkisoikeudelliset suoritteet\",",
              "Muuttujat[tili_taso5_fi]=\"Taiteellinen toiminta\",\"Taiteellinen toiminta\",",
              "Muuttujat[tili_taso5_fi]=\"Yleistoiminnot\",\"Yleistoiminnot\",",
              "Muuttujat[tili_taso5_fi]=\"Yliopistolain mukaiset kansalliskirjastotehtävät yhteensä\",\"Yliopistolain mukaiset kansalliskirjastotehtävät yhteensä\",",
              "Muuttujat[tili_taso5_fi]=\"Kansallisen kulttuuriperinnön tallettaminen ja ylläpito\",\"Kansallisen kulttuuriperinnön tallettaminen ja ylläpito\",",
              "Muuttujat[tili_taso5_fi]=\"Muut tehtävät\",\"Muut tehtävät\",",
              "Muuttujat[tili_taso5_fi]=\"Kansalliset palvelut kirjastoille sekä korkeakoulusektorille\",\"Kansalliset palvelut kirjastoille sekä korkeakoulusektorille\"",
              ")"
            ],
            "displayFolder": "Kustannuslaji"
          },
          {
            "type": "calculated",
            "name": "Toiminto",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "",
              "SWITCH(TRUE(),Muuttujat[tili_taso5_fi]=\"Harjoittelu harjoittelukoulun ulkopuolella\",\"Opettajankoulutus ja kehitystehtävät\",",
              "Muuttujat[tili_taso5_fi]=\"Harjoittelu harjoittelukoulussa\",\"Opettajankoulutus ja kehitystehtävät\",",
              "Muuttujat[tili_taso5_fi]=\"Opettajankoulutuksen kehittäminen\",\"Opettajankoulutus ja kehitystehtävät\",",
              "Muuttujat[tili_taso5_fi]=\"Esiopetus\",\"Opetustehtävät\",",
              "Muuttujat[tili_taso5_fi]=\"Lukiokoulutus\",\"Opetustehtävät\",",
              "Muuttujat[tili_taso5_fi]=\"Perusopetus\",\"Opetustehtävät\",",
              "Muuttujat[tili_taso5_fi]=\"Muut tehtävät\",\"Muut tehtävät\",",
              "Muuttujat[tili_taso5_fi]=\"Kansallisen kulttuuriperinnön tallettaminen ja ylläpito\",\"Yliopistolain mukaiset kansalliskirjastotehtävät\",",
              "Muuttujat[tili_taso5_fi]=\"Kansalliset palvelut kirjastoille sekä korkeakoulusektorille\",\"Yliopistolain mukaiset kansalliskirjastotehtävät\",",
              "Muuttujat[tili_taso5_fi]=\"Muu koulutus\",\"Muu koulutus\",",
              "Muuttujat[tili_taso5_fi]=\"Perustutkintojen osat\",\"Perustutkintojen osat\",",
              "Muuttujat[tili_taso5_fi]=\"Perustutkintokoulutus\",\"Perustutkintokoulutus\",",
              "Muuttujat[tili_taso5_fi]=\"Erillislakien mukaiset julkisoikeudelliset suoritteet\",\"Erillislakien mukaiset julkisoikeudelliset suoritteet\",",
              "Muuttujat[tili_taso5_fi]=\"Yleistoiminnot\",\"Yleistoiminnot\",",
              "Muuttujat[tili_taso5_fi]=\"Taiteellinen toiminta\",\"Taiteellinen toiminta\",",
              "Muuttujat[tili_taso5_fi]=\"Tieteellinen ja taiteellinen jatkotutkintokoulutus\",\"Tieteellinen ja taiteellinen jatkotutkintokoulutus\",",
              "Muuttujat[tili_taso5_fi]=\"Tieteellinen tutkimus\",\"Tieteellinen tutkimus\"",
              "\t)",
              ""
            ],
            "displayFolder": "Kustannuslaji"
          },
          {
            "type": "calculated",
            "name": "Päätoiminto",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "",
              "SWITCH(TRUE(),Muuttujat[tili_taso5_fi]=\"Harjoittelu harjoittelukoulun ulkopuolella\",\"Harjoittelukoulu\",",
              "Muuttujat[tili_taso5_fi]=\"Harjoittelu harjoittelukoulussa\",\"Harjoittelukoulu\",",
              "Muuttujat[tili_taso5_fi]=\"Opettajankoulutuksen kehittäminen\",\"Harjoittelukoulu\",",
              "Muuttujat[tili_taso5_fi]=\"Esiopetus\",\"Harjoittelukoulu\",",
              "Muuttujat[tili_taso5_fi]=\"Lukiokoulutus\",\"Harjoittelukoulu\",",
              "Muuttujat[tili_taso5_fi]=\"Perusopetus\",\"Harjoittelukoulu\",",
              "Muuttujat[tili_taso5_fi]=\"Muut tehtävät\",\"Kansalliskirjasto\",",
              "Muuttujat[tili_taso5_fi]=\"Kansallisen kulttuuriperinnön tallettaminen ja ylläpito\",\"Kansalliskirjasto\",",
              "Muuttujat[tili_taso5_fi]=\"Kansalliset palvelut kirjastoille sekä korkeakoulusektorille\",\"Kansalliskirjasto\",",
              "Muuttujat[tili_taso5_fi]=\"Muu koulutus\",\"Koulutus\",",
              "Muuttujat[tili_taso5_fi]=\"Perustutkintojen osat\",\"Koulutus\",",
              "Muuttujat[tili_taso5_fi]=\"Perustutkintokoulutus\",\"Koulutus\",",
              "Muuttujat[tili_taso5_fi]=\"Erillislakien mukaiset julkisoikeudelliset suoritteet\",\"Muu yhteiskunnallinen toiminta\",",
              "Muuttujat[tili_taso5_fi]=\"Yleistoiminnot\",\"Muu yhteiskunnallinen toiminta\",",
              "Muuttujat[tili_taso5_fi]=\"Taiteellinen toiminta\",\"Taiteellinen toiminta\",",
              "Muuttujat[tili_taso5_fi]=\"Tieteellinen ja taiteellinen jatkotutkintokoulutus\",\"Tutkimus\",",
              "Muuttujat[tili_taso5_fi]=\"Tieteellinen tutkimus\",\"Tutkimus\"",
              "\t)",
              ""
            ],
            "displayFolder": "Kustannuslaji"
          },
          {
            "type": "calculated",
            "name": "Koodit_päätoiminto",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": [
              "    ",
              "SWITCH(TRUE(),Muuttujat[tili_taso5_fi]=\"Harjoittelu harjoittelukoulun ulkopuolella\",\"5\",    ",
              "Muuttujat[tili_taso5_fi]=\"Harjoittelu harjoittelukoulussa\",\"5\",    ",
              "Muuttujat[tili_taso5_fi]=\"Opettajankoulutuksen kehittäminen\",\"5\",    ",
              "Muuttujat[tili_taso5_fi]=\"Esiopetus\",\"5\",    ",
              "Muuttujat[tili_taso5_fi]=\"Lukiokoulutus\",\"5\",    ",
              "Muuttujat[tili_taso5_fi]=\"Perusopetus\",\"5\",    ",
              "Muuttujat[tili_taso5_fi]=\"Muut tehtävät\",\"6\",    ",
              "Muuttujat[tili_taso5_fi]=\"Kansallisen kulttuuriperinnön tallettaminen ja ylläpito\",\"6\",    ",
              "Muuttujat[tili_taso5_fi]=\"Kansalliset palvelut kirjastoille sekä korkeakoulusektorille\",\"6\",    ",
              "Muuttujat[tili_taso5_fi]=\"Muu koulutus\",\"1\",    ",
              "Muuttujat[tili_taso5_fi]=\"Perustutkintojen osat\",\"1\",    ",
              "Muuttujat[tili_taso5_fi]=\"Perustutkintokoulutus\",\"1\",    ",
              "Muuttujat[tili_taso5_fi]=\"Erillislakien mukaiset julkisoikeudelliset suoritteet\",\"4\",    ",
              "Muuttujat[tili_taso5_fi]=\"Yleistoiminnot\",\"4\",    ",
              "Muuttujat[tili_taso5_fi]=\"Taiteellinen toiminta\",\"3\",    ",
              "Muuttujat[tili_taso5_fi]=\"Tieteellinen ja taiteellinen jatkotutkintokoulutus\",\"2\",    ",
              "Muuttujat[tili_taso5_fi]=\"Tieteellinen tutkimus\",\"2\"    ",
              "    )"
            ]
          },
          {
            "name": "d6.erittely_nimi_fi",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "d6.erittely_nimi_fi"
          },
          {
            "name": "Korkeakoulu",
            "dataType": "string",
            "sourceColumn": "Korkeakoulu",
            "displayFolder": "Organisaatiomuuttujat"
          },
          {
            "name": "tili_koodi",
            "dataType": "string",
            "sourceColumn": "tili_koodi"
          },
          {
            "name": "Sektori",
            "dataType": "string",
            "sourceColumn": "Sektori",
            "displayFolder": "Organisaatiomuuttujat"
          }
        ],
        "partitions": [
          {
            "name": "AMK_TALOUS",
            "dataView": "full",
            "source": {
              "query": " SELECT [dw].[v_st_talous_yhteinen].* FROM [dw].[v_st_talous_yhteinen] ",
              "dataSource": "ANTERO"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit_aineisto</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>103</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit_koulutusala</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>120</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit_yliopisto</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>105</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Material type</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>93</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Utbildningsområde</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>118</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>University</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>78</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Statistical year</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>101</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Field of education</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>115</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Material typ</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>87</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Universitet</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>82</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>arvo</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>52</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso4_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>91</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso3_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>91</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso2_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>91</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso1_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>91</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso0_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>91</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso4_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>90</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso3_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>90</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso2_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>90</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso1_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>90</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso0_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>90</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso4_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>85</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso3_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>85</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso2_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>85</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso1_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>85</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso0_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>85</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Statistikår</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>78</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Aineisto</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>68</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusala</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>85</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>d6.erittely_nimi_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>116</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>toiminto_nimi_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>104</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tilastovuosi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>86</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso5_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>85</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso5_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>90</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso5_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>91</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Konserni</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>71</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Ohjauksenala</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>95</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Ohjauksenala_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>112</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Ohjauksenala_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>113</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit_ohjauksenala</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>129</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Korkeakoulu</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>88</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_koodi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>71</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Sektori</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>63</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit_aineisto</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>30</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit_koulutusala</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>29</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit_yliopisto</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>28</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Material type</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>27</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Utbildningsområde</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>University</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>26</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Statistical year</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>25</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Field of education</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Material typ</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>24</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Universitet</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>23</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>arvo</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>17</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso4_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>16</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso3_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>15</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso2_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>14</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso1_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>13</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso0_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>12</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso4_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>11</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso3_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>10</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso2_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>9</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso1_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>8</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso0_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>7</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso4_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>6</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso3_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>5</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso2_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso1_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso0_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Statistikår</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>22</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Aineisto</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>21</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusala</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>20</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>d6.erittely_nimi_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>39</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>toiminto_nimi_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>18</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tilastovuosi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>19</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso5_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>31</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso5_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>32</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso5_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>33</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Konserni</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>34</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Ohjauksenala</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>35</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Ohjauksenala_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>36</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Ohjauksenala_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>37</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit_ohjauksenala</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>38</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Korkeakoulu</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>40</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_koodi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>41</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Sektori</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>42</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Statistical year</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>arvo</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso4_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso3_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso2_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso1_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso0_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso4_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso3_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso2_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso1_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso0_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso4_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso3_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso2_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso1_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso0_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Material typ</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Universitet</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Statistikår</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Aineisto</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>toiminto_nimi_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koulutusala</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>d6.erittely_nimi_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tilastovuosi</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>University</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Material type</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit_yliopisto</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit_koulutusala</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit_aineisto</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso5_fi</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso5_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_taso5_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Ohjauksenala</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Ohjauksenala_sv</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Ohjauksenala_en</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Koodit_ohjauksenala</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Korkeakoulu</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>tili_koodi</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Sektori</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Korkeakoulujen valtionrahoitus",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"yolaki49\", OR([tili_koodi] =\"valtio\",[tili_koodi] =\"okmperus\")) ))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Liikevaihto"
          },
          {
            "name": "Muut sijoitustoiminnan tuotot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"srmuutul\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Sijoitustoiminta\\Varsinaisen sijoitustoiminnan tuotot"
          },
          {
            "name": "Osuus osakkuusyhtiöiden tuloksesta (voitosta/tappiosta, +/-)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', or([tili_koodi] =\"OSUUSTULOS\",[tili_koodi] =\"vtosuust\")))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Liikevaihto"
          },
          {
            "name": "Suomen Akatemia",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"akatemia3\",[tili_koodi] =\"akatemia\")))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Avustustuottojen jaottelu"
          },
          {
            "name": "Business Finland",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi]=\"BusinessFinland\",[tili_koodi] =\"BusinessFinland3\")))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Avustustuottojen jaottelu"
          },
          {
            "name": "Muu OKM",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"muuokm3\",OR([tili_koodi] =\"MUUOKM2\",[tili_koodi] =\"muuokm\"))))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Avustustuottojen jaottelu"
          },
          {
            "name": "Muu valtio (pl. Business Finland, Akatemia, Sosiaaliturvarahastot ja muu OKM)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"muuvaltio\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Avustustuottojen jaottelu"
          },
          {
            "name": "Kunnat ja kuntayhtymät",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"kunnat3\",[tili_koodi] =\"kunnat\")))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Avustustuottojen jaottelu"
          },
          {
            "name": "Muu julkinen hallinto",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"muujulkh\",[tili_koodi] =\"sosturvarah\")))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Avustustuottojen jaottelu"
          },
          {
            "name": "Voittoa tavoittelemattomat yhteisöt (kirkot, säätiöt, puolueet, rahastot)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"vyhteiso\",[tili_koodi] =\"vottavoittelematon\")))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Avustustuottojen jaottelu"
          },
          {
            "name": "Kotimaiset yritykset",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"kotiyritys\",[tili_koodi] =\"kyrityst\")))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Avustustuottojen jaottelu"
          },
          {
            "name": "Kotimaiset rahoituslaitokset",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"kotirah\",[tili_koodi] =\"krahalt\")))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Avustustuottojen jaottelu"
          },
          {
            "name": "Kotitaloudet",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"kotitalous\",[tili_koodi] =\"kotitalt\"  )))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Avustustuottojen jaottelu"
          },
          {
            "name": "EU-rahoitus",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"eurah\",[tili_koodi] =\"eusuora\")))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Avustustuottojen jaottelu"
          },
          {
            "name": "Euroopan Unionin maat, yritysrahoitus",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"eurahyrit\",[tili_koodi] =\"euyritys\")))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Avustustuottojen jaottelu"
          },
          {
            "name": "Euroopan Unionin maat, muu rahoitus",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"eurahmuu\",[tili_koodi] =\"eumuut\")))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Avustustuottojen jaottelu"
          },
          {
            "name": "Muut ulkomaat, yritysrahoitus ",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"muuulkyritys\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Avustustuottojen jaottelu"
          },
          {
            "name": "Muut ulkomaat, muu rahoitus",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"muuulkmuurah\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Avustustuottojen jaottelu"
          },
          {
            "name": "Ulkomainen liiketoiminta",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"YVARULKOT\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Ulkomainen liiketoiminta"
          },
          {
            "name": "Palkat ja palkkiot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"palkkak\",OR([tili_koodi] =\"palkat\",[tili_koodi] =\"palkat_ja_palkkiot\"))))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Kulut\\Henkilöstökulut"
          },
          {
            "name": "Henkilöstösivukulut: Eläkekulut",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"elakekulut\",OR([tili_koodi] =\"elakekulut2\",[tili_koodi] =\"elakek\"))))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Kulut\\Henkilöstökulut"
          },
          {
            "name": "Henkilöstösivukulut: Muut henkilösivukulut",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"muusivuk\", [tili_koodi] =\"muut_henkilostosivukulut\")))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Kulut\\Henkilöstökulut"
          },
          {
            "name": "Muut kulut yhteensä",
            "expression": "CALCULATE([Kone- ja laitevuokrat]+[Muut varsinaisen toiminnan kulut]+[Palvelujen ostot]+[Tarvikkeet ja tavarat]+[Tilakustannukset])",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Kulut"
          },
          {
            "name": "Tarvikkeet ja tavarat",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"tavaosto\",[tili_koodi] =\"aitata\")))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Kulut\\Muut kulut"
          },
          {
            "name": "Palvelujen ostot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"palvosto\",OR([tili_koodi] =\"ulkopuoliset_palvelut\",[tili_koodi] =\"ulkpal\"))))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Kulut\\Muut kulut"
          },
          {
            "name": "Tilakustannukset",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"muutilak\",[tili_koodi] =\"tilakustannukset\")))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Kulut\\Muut kulut"
          },
          {
            "name": "Kone- ja laitevuokrat",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"konelaite\",[tili_koodi] =\"konevuok\")))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Kulut\\Muut kulut"
          },
          {
            "name": "Muut varsinaisen toiminnan kulut",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"muutkulut\",[tili_koodi] =\"vtmuuk\")))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Kulut\\Muut kulut"
          },
          {
            "name": "Keräysten ja lahjoitusten tuotot: kotitaloudet",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"KERLAHJKOTI\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Varainhankinta\\Varainhankinnan tuotot"
          },
          {
            "name": "Keräysten ja lahjoitusten tuotot: yritykset",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"KERLAHJYRIT\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Varainhankinta\\Varainhankinnan tuotot"
          },
          {
            "name": "Keräysten ja lahjoitusten tuotot: muut",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat',[tili_koodi] =\"KERLAHJMUU\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Varainhankinta\\Varainhankinnan tuotot"
          },
          {
            "name": "Varainhankinnan liiketoiminnan tuotot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"vhliiket\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Varainhankinta\\Varainhankinnan tuotot"
          },
          {
            "name": "Muut varainhankinnan tuotot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"vhmuutul\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Varainhankinta\\Varainhankinnan tuotot"
          },
          {
            "name": "Varainhankinnan liiketoiminnan kulut",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"vhliikek\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Varainhankinta\\Varainhankinnan kulut"
          },
          {
            "name": "Muut varainhankinnan kulut",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"vhmuuk\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Varainhankinta\\Varainhankinnan kulut"
          },
          {
            "name": "Osinkotuotot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"osinkot\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Sijoitustoiminta\\Varsinaisen sijoitustoiminnan tuotot"
          },
          {
            "name": "Korkotuotot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"korkot\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Sijoitustoiminta\\Varsinaisen sijoitustoiminnan tuotot"
          },
          {
            "name": "Myyntituotot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"mvoitto\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Sijoitustoiminta\\Varsinaisen sijoitustoiminnan tuotot"
          },
          {
            "name": "Vuokratuotot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"vuokrat\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Sijoitustoiminta\\Varsinaisen sijoitustoiminnan tuotot"
          },
          {
            "name": "Korkokulut",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"korkok\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Sijoitustoiminta\\Varsinaisen sijoitustoiminnan kulut"
          },
          {
            "name": "Vuokrakulut (vastikkeet)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"vastikek\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Sijoitustoiminta\\Varsinaisen sijoitustoiminnan kulut"
          },
          {
            "name": "Myyntitappiot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"mtappio\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Sijoitustoiminta\\Varsinaisen sijoitustoiminnan kulut"
          },
          {
            "name": "Tuotot osuuksista saman konsernin yrityksissä",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"konstuot\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Rahoitustoiminta\\Rahoitustuotot"
          },
          {
            "name": "Tuotot osuuksista omistusyhteysyrityksissä",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"tuotosuu\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Rahoitustoiminta\\Rahoitustuotot"
          },
          {
            "name": "Tuotot muista pysyvien vastaavien sijoituksista",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"tuototmuilt\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Rahoitustoiminta\\Rahoitustuotot"
          },
          {
            "name": "Arvonalentumisten palautukset",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"arvalpal\",[tili_koodi] =\"ARVONALENTUMISETPAL\")))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Rahoitustoiminta\\Rahoitustuotot"
          },
          {
            "name": "Arvonalentumiset muiden pysyvien vastaavien sijoituksista",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"arvovastaasijo\",[tili_koodi] =\"ARVONALENTUMISETPYSSIJ\")))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Rahoitustoiminta\\Rahoituskulut"
          },
          {
            "name": "Arvonalentumiset vaihtuvien vastaavien rahoitusarvopapereista",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"arvovaihtvastrah\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Rahoitustoiminta\\Rahoituskulut"
          },
          {
            "name": "Korkokulut ja rahoituskulut",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"korkrahkulumuut\",[tili_koodi] =\"KORKOKULUTRAHKULUT\")))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Rahoitustoiminta\\Rahoituskulut"
          },
          {
            "name": "Korkokulut ja rahoituskulut saman konsernin yrityksille",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"korkrahkulukons\",[tili_koodi] =\"KORKOKULUTRAHKULUTSAMA\")))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Rahoitustoiminta\\Rahoituskulut"
          },
          {
            "name": "Omakatteisten rahastojen muutos yhteensä",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"omakrahm\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Omakatteisten rahastojen muutos"
          },
          {
            "name": "LIIKEVOITTO (TAPPIO)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"lvoitto\",[tili_koodi] =\"vtjaama\")))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Tilikauden tulos"
          },
          {
            "name": "VOITTO (TAPPIO) ENNEN TILINPÄÄTÖS-SIIRTOJA JA VEROJA",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"voitenveroja\",[tili_koodi] =\"VOITTOENTILP\")))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Tilikauden tulos"
          },
          {
            "name": "Poistoeron muutos (+/-)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"poistoem\",OR([tili_koodi] =\"poistoero\",([tili_koodi] =\"poistoeron_lisays\")))))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Tilikauden tulos"
          },
          {
            "name": "Tuloverot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"tulovero\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Tilikauden tulos"
          },
          {
            "name": "Konserni: Vähemmistöosuudet",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"vtvahem\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Tilikauden tulos"
          },
          {
            "name": "Liikevaihto",
            "expression": "CALCULATE([Avustustuotot]+[Korkeakoulujen valtionrahoitus]+[Liiketoiminnan tuotot]+[Muut tuotot]+[Osuus osakkuusyhtiöiden tuloksesta (voitosta/tappiosta, +/-)])",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Liikevaihto"
          },
          {
            "name": "Avustustuotot",
            "expression": "CALCULATE([Business Finland]+[EU-rahoitus]+[Euroopan Unionin maat, muu rahoitus]+[Euroopan Unionin maat, yritysrahoitus]+[Kotimaiset rahoituslaitokset]+[Kotimaiset yritykset]+[Kotitaloudet]+[Kunnat ja kuntayhtymät]+[Muu julkinen hallinto]+[Muu OKM]+[Muu valtio (pl. Business Finland, Akatemia, Sosiaaliturvarahastot ja muu OKM)]+[Muut ulkomaat, muu rahoitus]+[Muut ulkomaat, yritysrahoitus ]+[Suomen Akatemia]+[Voittoa tavoittelemattomat yhteisöt (kirkot, säätiöt, puolueet, rahastot)])",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Liikevaihto"
          },
          {
            "name": "Henkilöstökulut yhteensä",
            "expression": "CALCULATE([Henkilöstösivukulut: Eläkekulut]+[Henkilöstösivukulut: Muut henkilösivukulut]+[Palkat ja palkkiot])",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Kulut"
          },
          {
            "name": "Poistot ja arvonalentumiset",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat',  OR([tili_koodi] =\"poistot2\",OR([tili_koodi] =\"poistot\",[tili_koodi] =\"suunnitelman_mukaiset_poistot\"))))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Kulut"
          },
          {
            "name": "Varsinaisen sijoitustoiminnan tuotot yhteensä",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"srliiket\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Sijoitustoiminta"
          },
          {
            "name": "Varsinaisen sijoitustoiminnan kulut yhteensä",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"srliikek\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Sijoitustoiminta"
          },
          {
            "name": "Varsinaisen sijoitustoiminnan tuotto",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"vhjaama\",[tili_koodi] =\"vhjaama\")))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Sijoitustoiminta"
          },
          {
            "name": "Rahoitustuotot ja -kulut (netto)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"srjaama\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Rahoitustoiminta"
          },
          {
            "name": "Rahoitustuotot yhteensä",
            "expression": "CALCULATE([Arvonalentumisten palautukset]+[Tuotot muista pysyvien vastaavien sijoituksista]+[Tuotot osuuksista omistusyhteysyrityksissä]+[Tuotot osuuksista saman konsernin yrityksissä])",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Rahoitustoiminta"
          },
          {
            "name": "Rahoituskulut yhteensä",
            "expression": "CALCULATE([Korkokulut ja rahoituskulut saman konsernin yrityksille]+[Arvonalentumiset muiden pysyvien vastaavien sijoituksista]+[Arvonalentumiset vaihtuvien vastaavien rahoitusarvopapereista]+[Korkokulut ja rahoituskulut])",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Rahoitustoiminta"
          },
          {
            "name": "Kulut yhteensä",
            "expression": "CALCULATE([Henkilöstökulut yhteensä]+[Muut kulut yhteensä]+[Poistot ja arvonalentumiset])",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Kulut"
          },
          {
            "name": "Sidottujen rahastojen muutos yhteensä",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"sidottrm\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Sidottujen rahastojen muutos"
          },
          {
            "name": "Maksuasetuksen perusteella perittävät maksut",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"MAKSUASETUS\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Muut tuotot"
          },
          {
            "name": "Lukukausimaksut",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"LUKUKAUSIMAKSUT\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Muut tuotot"
          },
          {
            "name": "Pysyväisluontoinen yhteistyö koulutuksen tukitoimintojen järjestämisessä kahden verotonta koulutusta antavan oppilaitoksen välillä",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"PYSYVAISLUONTOINEN\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Muut tuotot"
          },
          {
            "name": "Muut muut tuotot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"MUUTMUUTTUOT\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Muut tuotot"
          },
          {
            "name": "Siirto sidotusta rahastosta",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"SIIRTOSIDOTUSTA\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Sidottujen rahastojen muutos"
          },
          {
            "name": "Siirto sidottuun rahastoon",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"SIIRTOSIDOTTUUN\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Sidottujen rahastojen muutos"
          },
          {
            "name": "Siirto rahastosta",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"SIIRTORAHASTOSTA\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Omakatteisten rahastojen muutos"
          },
          {
            "name": "Siirto rahastoon",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"SIIRTORAHASTOON\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Omakatteisten rahastojen muutos"
          },
          {
            "name": "Keräysten ja lahjoitusten kulut",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"KERLAHJKULU\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Varainhankinta\\Varainhankinnan kulut"
          },
          {
            "name": "Lahjoitusten tuotot: muut",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat',[tili_koodi] =\"muulahj\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Varainhankinta\\Varainhankinnan tuotot\\Lahjoitusten tuotot (historia)"
          },
          {
            "name": "Lahjoitusten tuotot: kotitaloudet",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"kotilahj\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Varainhankinta\\Varainhankinnan tuotot\\Lahjoitusten tuotot (historia)"
          },
          {
            "name": "Lahjoitusten tuotot: yritykset",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"yritlahj\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Varainhankinta\\Varainhankinnan tuotot\\Lahjoitusten tuotot (historia)"
          },
          {
            "name": "Käyvän arvon muutos (+/-)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"KVARVONMUUTOS\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Sijoitustoiminta"
          },
          {
            "name": "Liiketoiminnan tuotot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"vtliiket\",[tili_koodi] =\"liiktuotot\")))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Liikevaihto"
          },
          {
            "name": "Muut tuotot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"muuttuot\",[tili_koodi] =\"vtmuutul\")))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Liikevaihto"
          },
          {
            "name": "Muut korko- ja rahoitustuotot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"MUUTKORKORAHTUOTOT\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Rahoitustoiminta\\Rahoitustuotot"
          },
          {
            "name": "Muut sijoitustoiminnan kulut",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"srmuuk\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Sijoitustoiminta\\Varsinaisen sijoitustoiminnan kulut"
          },
          {
            "name": "Liikevaihto (Tehty Liikevaihto2 koodilla)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"Liikevaihto\",[tili_koodi] =\"LIIKEVAIHTO2\")))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Liikevaihto"
          },
          {
            "name": "TILIKAUDEN VOITTO (TAPPIO)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', OR([tili_koodi] =\"TILIKJAAM\",[tili_koodi] =\"TILVOITTO\")))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Tilikauden tulos"
          },
          {
            "name": "Varainhankinnan kulut yhteensä",
            "description": "Tuloslaskelma\\Varainhankinta",
            "expression": "CALCULATE([Keräysten ja lahjoitusten kulut]+[Muut varainhankinnan kulut]+[Varainhankinnan liiketoiminnan kulut])",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Varainhankinta"
          },
          {
            "name": "Varainhankinnan tuotot yhteensä",
            "expression": "CALCULATE([Keräysten ja lahjoitusten tuotot: kotitaloudet]+[Keräysten ja lahjoitusten tuotot: muut]+[Keräysten ja lahjoitusten tuotot: yritykset]+[Muut varainhankinnan tuotot]+[Varainhankinnan liiketoiminnan tuotot])",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Varainhankinta"
          },
          {
            "name": "Varainhankinnan tuotto",
            "expression": "CALCULATE([Varainhankinnan tuotot yhteensä]-[Varainhankinnan kulut yhteensä])",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Varainhankinta"
          },
          {
            "name": "Käyvän arvon rahasto",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"kayvanar\"))",
            "formatString": "#,0",
            "displayFolder": "Tuloslaskelma\\Sijoitustoiminta"
          },
          {
            "name": "Kehittämismenot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"kehmenot\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastaavaa\\Pysyvät vastaavat\\Aineettomat hyödykkeet"
          },
          {
            "name": "Aineettomat oikeudet",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"aineetoi\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastaavaa\\Pysyvät vastaavat\\Aineettomat hyödykkeet"
          },
          {
            "name": "Liikearvo",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"liikear\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastaavaa\\Pysyvät vastaavat\\Aineettomat hyödykkeet"
          },
          {
            "name": "Konserni-liikearvo",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"kliikear\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastaavaa\\Pysyvät vastaavat\\Aineettomat hyödykkeet"
          },
          {
            "name": "Muut aineettomat hyödykkeet",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"muupmeno\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastaavaa\\Pysyvät vastaavat\\Aineettomat hyödykkeet"
          },
          {
            "name": "Ennakkomaksut",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"ahennakk\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastaavaa\\Pysyvät vastaavat\\Aineettomat hyödykkeet"
          },
          {
            "name": "Maa- ja vesialueet",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"maavesi\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastaavaa\\Pysyvät vastaavat\\Aineelliset hyödykkeet"
          },
          {
            "name": "Rakennukset ja rakennelmat",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"rakennus\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastaavaa\\Pysyvät vastaavat\\Aineelliset hyödykkeet"
          },
          {
            "name": "Koneet ja kalusto",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"koneet\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastaavaa\\Pysyvät vastaavat\\Aineelliset hyödykkeet"
          },
          {
            "name": "Muut aineelliset hyödykkeet",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"muuainh\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastaavaa\\Pysyvät vastaavat\\Aineelliset hyödykkeet"
          },
          {
            "name": "Ennakkomaksut ja keskeneräiset hankinnat",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"ennakesk\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastaavaa\\Pysyvät vastaavat\\Aineelliset hyödykkeet"
          },
          {
            "name": "Osuudet saman konsernin yrityksissä (sijoitukset)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"osuuskon\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastaavaa\\Pysyvät vastaavat\\Sijoitukset"
          },
          {
            "name": "Saamiset saman konsernin yrityksiltä",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"saamikon\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastaavaa\\Pysyvät vastaavat\\Sijoitukset"
          },
          {
            "name": "Osuudet omistusyhteys-yrityksissä",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"osuusoyy\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastaavaa\\Pysyvät vastaavat\\Sijoitukset"
          },
          {
            "name": "Saamiset omistusyhteys-yrityksiltä",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"saamioyy\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastaavaa\\Pysyvät vastaavat\\Sijoitukset"
          },
          {
            "name": "Muut osakkeet ja osuudet (sijoitukset)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"muutosak\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastaavaa\\Pysyvät vastaavat\\Sijoitukset"
          },
          {
            "name": "Muut saamiset (sijoitukset)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"muutsaam\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastaavaa\\Pysyvät vastaavat\\Sijoitukset"
          },
          {
            "name": "Omakatteisten rahastojen varat",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"okrvarat\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastaavaa\\Pysyvät vastaavat"
          },
          {
            "name": "Aineet ja tarvikkeet",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"aineet\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastaavaa\\Vaihtuvat vastaavat\\Vaihto-omaisuus"
          },
          {
            "name": "Keskeneräiset tuotteet",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"keskener\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastaavaa\\Vaihtuvat vastaavat\\Vaihto-omaisuus"
          },
          {
            "name": "Valmiit tuotteet/ tavarat",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"valmiit\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastaavaa\\Vaihtuvat vastaavat\\Vaihto-omaisuus"
          },
          {
            "name": "Muu vaihto-omaisuus",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"muuvom\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastaavaa\\Vaihtuvat vastaavat\\Vaihto-omaisuus"
          },
          {
            "name": "Ennakkomaksut (vaihto-omaisuus)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"voennakk\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastaavaa\\Vaihtuvat vastaavat\\Vaihto-omaisuus"
          },
          {
            "name": "Osuudet saman konsernin yrityksissä (rahoitusarvopaperit)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"raposuus\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastaavaa\\Vaihtuvat vastaavat\\Rahoitusarvopaperit"
          },
          {
            "name": "Muut osakkeet ja osuudet (rahoitusarvopaperit)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"raposakk\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastaavaa\\Vaihtuvat vastaavat\\Rahoitusarvopaperit"
          },
          {
            "name": "Muut arvopaperit (rahoitusarvopaperit)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"muuarvop\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastaavaa\\Vaihtuvat vastaavat\\Rahoitusarvopaperit"
          },
          {
            "name": "Rahat ja pankki-saamiset (vaihtuvat)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"rahatps\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastaavaa\\Vaihtuvat vastaavat"
          },
          {
            "name": "Vastaavaa yhteensä",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso1_fi]=\"Vastattavaa\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastaavaa"
          },
          {
            "name": "Osake-, osuus- tai muu vastaava pääoma / peruspääoma",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"peruspo\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastattavaa\\Oma pääoma"
          },
          {
            "name": "Pääomarahasto",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"PORAH\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastattavaa\\Oma pääoma"
          },
          {
            "name": "Ylikurssirahasto",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"YKRAH\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastattavaa\\Oma pääoma"
          },
          {
            "name": "Arvonkorotus-rahasto",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"arvonkr\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastattavaa\\Oma pääoma"
          },
          {
            "name": "Sijoitetun vapaan oman pääoman rahasto",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"SIJVAPRAH\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastattavaa\\Oma pääoma\\Muut rahastot"
          },
          {
            "name": "Vararahasto",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"VARARAH\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastattavaa\\Oma pääoma\\Muut rahastot"
          },
          {
            "name": "Yhtiöjärjestyksen tai sääntöjen mukaiset rahastot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"YJRAH\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastattavaa\\Oma pääoma\\Muut rahastot"
          },
          {
            "name": "Omakatteiset rahastot ",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"okarahas\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastattavaa\\Oma pääoma\\Muut rahastot"
          },
          {
            "name": "Muut sidotut rahastot ",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"msirahas\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastattavaa\\Oma pääoma\\Muut rahastot"
          },
          {
            "name": "Toimintapääoma",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"toimpo\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastattavaa\\Oma pääoma\\Muut rahastot"
          },
          {
            "name": "Muut vapaat rahastot (esim. sijoitusrahasto)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"vaprahas\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastattavaa\\Oma pääoma\\Muut rahastot"
          },
          {
            "name": "Edellisten tilikausien voitto (tappio)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"edtilvo\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastattavaa\\Oma pääoma\\Muu oma pääoma"
          },
          {
            "name": "Tilikauden voitto (tai tappio)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"tkvoitto\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastattavaa\\Oma pääoma\\Muu oma pääoma"
          },
          {
            "name": "Oma pääoma yhteensä",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso2_fi]=\"OMA PÄÄOMA\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastattavaa\\Oma pääoma"
          },
          {
            "name": "Vähemmistö- osuudet (konserni)",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"tavahem\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastattavaa\\Tilinpäätössiirtymät ja pakolliset varaukset\\Muu oma pääoma"
          },
          {
            "name": "Poistoero",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"tpskerty\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastattavaa\\Tilinpäätössiirtymät ja pakolliset varaukset\\Tilinpäätössiirtymät"
          },
          {
            "name": "Verotusperäiset varaukset",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"VEROPVARA\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastattavaa\\Tilinpäätössiirtymät ja pakolliset varaukset\\Tilinpäätössiirtymät"
          },
          {
            "name": "Eläkevaraukset",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"elakvara\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastattavaa\\Tilinpäätössiirtymät ja pakolliset varaukset\\Pakolliset varaukset"
          },
          {
            "name": "Verovaraukset",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"verovara\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastattavaa\\Tilinpäätössiirtymät ja pakolliset varaukset\\Pakolliset varaukset"
          },
          {
            "name": "Muut pakolliset varaukset",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"mpakvara\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastattavaa\\Tilinpäätössiirtymät ja pakolliset varaukset\\Pakolliset varaukset"
          },
          {
            "name": "Konsernireservi",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"kreservi\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastattavaa\\Tilinpäätössiirtymät ja pakolliset varaukset"
          },
          {
            "name": "Omakatteisten rahastojen velat",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"okrvelat\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastattavaa\\Vieras pääoma"
          },
          {
            "name": "Vastattavaa yhteensä",
            "expression": "SUMX(FILTER(Muuttujat,[tili_taso1_fi]=\"Vastattavaa\"),[arvo])",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastattavaa"
          },
          {
            "name": "Omakatteisten rahastojen sijoitukset yhteensä",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"okrsijyh\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Tilastokeskuksen tarkentavat tiedot"
          },
          {
            "name": "Rahasto-osuudet",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"okrrahas\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Tilastokeskuksen tarkentavat tiedot"
          },
          {
            "name": "Muut osakkeet ja osuudet",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"okrosakk\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Tilastokeskuksen tarkentavat tiedot"
          },
          {
            "name": "Muut arvopaperit",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"okrmuuap\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Tilastokeskuksen tarkentavat tiedot"
          },
          {
            "name": "Rahat ja pankki-saamiset",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"okrrjaps\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Tilastokeskuksen tarkentavat tiedot"
          },
          {
            "name": "Muut varat",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"okrmuutv\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Tilastokeskuksen tarkentavat tiedot"
          },
          {
            "name": "Kompensoitavat perustoiminnan alv-menot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"kompperusalvm\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Arvonlisäverot"
          },
          {
            "name": "Saadut alv-kompensaatiot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"saadalvkomp\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Arvonlisäverot"
          },
          {
            "name": "Arvonlisäverosaatava/-velka",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"alvsaavel\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Arvonlisäverot"
          },
          {
            "name": "Omavaraisuusaste",
            "expression": "[Oma pääoma yhteensä]/([Vastaavaa yhteensä]-[Lyhytaikaiset saadut ennakot])",
            "formatString": "0.0 %;-0.0 %;0.0 %",
            "displayFolder": "Tase\\Johdetut mittarit"
          },
          {
            "name": "Lyhytaikaiset myyntisaamiset",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"lmyyntis\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastaavaa\\Vaihtuvat vastaavat\\Lyhytaikaiset saamiset"
          },
          {
            "name": "Lyhytaikaiset saamiset saman konsernin yrityksiltä",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"lskonser\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastaavaa\\Vaihtuvat vastaavat\\Lyhytaikaiset saamiset"
          },
          {
            "name": "Lyhytaikaiset saamiset omistusyhteysyrityksiltä",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"lsoyyrit\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastaavaa\\Vaihtuvat vastaavat\\Lyhytaikaiset saamiset"
          },
          {
            "name": "Lyhytaikaiset lainasaamiset",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"llainas\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastaavaa\\Vaihtuvat vastaavat\\Lyhytaikaiset saamiset"
          },
          {
            "name": "Lyhytaikaiset laskennalliset verosaamiset",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"llveros\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastaavaa\\Vaihtuvat vastaavat\\Lyhytaikaiset saamiset"
          },
          {
            "name": "Lyhytaikaiset muut saamiset",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"lmuuts\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastaavaa\\Vaihtuvat vastaavat\\Lyhytaikaiset saamiset"
          },
          {
            "name": "Lyhytaikaiset siirtosaamiset",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"lsiirtos\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastaavaa\\Vaihtuvat vastaavat\\Lyhytaikaiset saamiset"
          },
          {
            "name": "Lyhytaikaiset pääomalainat",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"lpaaomal\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastattavaa\\Vieras pääoma\\Lyhytaikainen vieras pääoma"
          },
          {
            "name": "Lyhytaikaiset joukkovelkakirjalainat",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"ljvelkal\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastattavaa\\Vieras pääoma\\Lyhytaikainen vieras pääoma"
          },
          {
            "name": "Lyhytaikaiset vaihtovelkakirjalainat",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"lvvelkal\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastattavaa\\Vieras pääoma\\Lyhytaikainen vieras pääoma"
          },
          {
            "name": "Lyhytaikaiset lainat rahoituslaitoksilta",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"llrahala\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastattavaa\\Vieras pääoma\\Lyhytaikainen vieras pääoma"
          },
          {
            "name": "Lyhytaikaiset eläkelainat",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"lelakel\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastattavaa\\Vieras pääoma\\Lyhytaikainen vieras pääoma"
          },
          {
            "name": "Lyhytaikaiset saadut ennakot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"lsaadute\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastattavaa\\Vieras pääoma\\Lyhytaikainen vieras pääoma"
          },
          {
            "name": "Lyhytaikaiset ostovelat",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"lostovel\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastattavaa\\Vieras pääoma\\Lyhytaikainen vieras pääoma"
          },
          {
            "name": "Lyhytaikaiset rahoitusvekselit",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"lrveksel\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastattavaa\\Vieras pääoma\\Lyhytaikainen vieras pääoma"
          },
          {
            "name": "Lyhytaikaiset velat saman konsernin yrityksille",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"lvkonser\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastattavaa\\Vieras pääoma\\Lyhytaikainen vieras pääoma"
          },
          {
            "name": "Lyhytaikaiset velat omistusyhteysyrityksille",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"lvoyyrit\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastattavaa\\Vieras pääoma\\Lyhytaikainen vieras pääoma"
          },
          {
            "name": "Lyhytaikaiset muut velat",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"lmuutvel\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastattavaa\\Vieras pääoma\\Lyhytaikainen vieras pääoma"
          },
          {
            "name": "Lyhytaikaiset siirtovelat",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"lsiirtov\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastattavaa\\Vieras pääoma\\Lyhytaikainen vieras pääoma"
          },
          {
            "name": "Lyhytaikaiset laskennaliset verovelat",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"llverove\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastattavaa\\Vieras pääoma\\Lyhytaikainen vieras pääoma"
          },
          {
            "name": "Pitkäaikaiset myyntisaamiset",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"pmyyntis\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastaavaa\\Vaihtuvat vastaavat\\Pitkäaikaiset saamiset"
          },
          {
            "name": "Pitkäaikaiset saamiset saman konsernin yrityksiltä",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"pskonser\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastaavaa\\Vaihtuvat vastaavat\\Pitkäaikaiset saamiset"
          },
          {
            "name": "Pitkäaikaiset saamiset omistusyhteysyrityksiltä",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"psoyyrit\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastaavaa\\Vaihtuvat vastaavat\\Pitkäaikaiset saamiset"
          },
          {
            "name": "Pitkäaikaiset lainasaamiset",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"plainas\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastaavaa\\Vaihtuvat vastaavat\\Pitkäaikaiset saamiset"
          },
          {
            "name": "Pitkäaikaiset laskennalliset verosaamiset",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"plveros\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastaavaa\\Vaihtuvat vastaavat\\Pitkäaikaiset saamiset"
          },
          {
            "name": "Pitkäaikaiset muut saamiset",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"pmuuts\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastaavaa\\Vaihtuvat vastaavat\\Pitkäaikaiset saamiset"
          },
          {
            "name": "Pitkäaikaiset siirtosaamiset",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"psiirtos\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastaavaa\\Vaihtuvat vastaavat\\Pitkäaikaiset saamiset"
          },
          {
            "name": "Pitkäaikaiset pääomalainat",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"ppaaomal\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastattavaa\\Vieras pääoma\\Pitkäaikainen vieras pääoma"
          },
          {
            "name": "Pitkäaikaiset joukkovelkakirjalainat",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"pjvelkal\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastattavaa\\Vieras pääoma\\Pitkäaikainen vieras pääoma"
          },
          {
            "name": "Pitkäaikaiset vaihtovelkakirjalainat",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"pvvelkal\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastattavaa\\Vieras pääoma\\Pitkäaikainen vieras pääoma"
          },
          {
            "name": "Pitkäaikaiset lainat rahoituslaitoksilta",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"plrahala\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastattavaa\\Vieras pääoma\\Pitkäaikainen vieras pääoma"
          },
          {
            "name": "Pitkäaikaiset eläkelainat",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"pelakel\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastattavaa\\Vieras pääoma\\Pitkäaikainen vieras pääoma"
          },
          {
            "name": "Pitkäaikaiset saadut ennakot",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"psaadute\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastattavaa\\Vieras pääoma\\Pitkäaikainen vieras pääoma"
          },
          {
            "name": "Pitkäaikaiset ostovelat",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"postovel\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastattavaa\\Vieras pääoma\\Pitkäaikainen vieras pääoma"
          },
          {
            "name": "Pitkäaikaiset rahoitusvekselit",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"prveksel\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastattavaa\\Vieras pääoma\\Pitkäaikainen vieras pääoma"
          },
          {
            "name": "Pitkäaikaiset velat saman konsernin yrityksille",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"pvkonser\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastattavaa\\Vieras pääoma\\Pitkäaikainen vieras pääoma"
          },
          {
            "name": "Pitkäaikaiset velat omistusyhteysyrityksille",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"pvoyyrit\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastattavaa\\Vieras pääoma\\Pitkäaikainen vieras pääoma"
          },
          {
            "name": "Pitkäaikaiset muut velat",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"pmuutvel\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastattavaa\\Vieras pääoma\\Pitkäaikainen vieras pääoma"
          },
          {
            "name": "Pitkäaikaiset siirtovelat",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"psiirtov\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastattavaa\\Vieras pääoma\\Pitkäaikainen vieras pääoma"
          },
          {
            "name": "Pitkäaikaiset laskennaliset verovelat",
            "expression": "CALCULATE(SUM([arvo]), FILTER('Muuttujat', [tili_koodi] =\"plverove\"))",
            "formatString": "#,0",
            "displayFolder": "Tase\\Vastattavaa\\Vieras pääoma\\Pitkäaikainen vieras pääoma"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dw].[v_st_talous_yhteinen].* FROM [dw].[v_st_talous_yhteinen] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "v_st_talous_yhteinen"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dw"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Koodit_aineisto</string>",
              "      </key>",
              "      <value>",
              "        <int>103</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit_koulutusala</string>",
              "      </key>",
              "      <value>",
              "        <int>120</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit_yliopisto</string>",
              "      </key>",
              "      <value>",
              "        <int>105</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Material type</string>",
              "      </key>",
              "      <value>",
              "        <int>93</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Utbildningsområde</string>",
              "      </key>",
              "      <value>",
              "        <int>118</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>University</string>",
              "      </key>",
              "      <value>",
              "        <int>78</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Statistical year</string>",
              "      </key>",
              "      <value>",
              "        <int>101</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Field of education</string>",
              "      </key>",
              "      <value>",
              "        <int>115</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Material typ</string>",
              "      </key>",
              "      <value>",
              "        <int>87</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Universitet</string>",
              "      </key>",
              "      <value>",
              "        <int>82</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>arvo</string>",
              "      </key>",
              "      <value>",
              "        <int>52</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso4_en</string>",
              "      </key>",
              "      <value>",
              "        <int>91</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso3_en</string>",
              "      </key>",
              "      <value>",
              "        <int>91</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso2_en</string>",
              "      </key>",
              "      <value>",
              "        <int>91</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso1_en</string>",
              "      </key>",
              "      <value>",
              "        <int>91</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso0_en</string>",
              "      </key>",
              "      <value>",
              "        <int>91</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso4_sv</string>",
              "      </key>",
              "      <value>",
              "        <int>90</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso3_sv</string>",
              "      </key>",
              "      <value>",
              "        <int>90</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso2_sv</string>",
              "      </key>",
              "      <value>",
              "        <int>90</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso1_sv</string>",
              "      </key>",
              "      <value>",
              "        <int>90</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso0_sv</string>",
              "      </key>",
              "      <value>",
              "        <int>90</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso4_fi</string>",
              "      </key>",
              "      <value>",
              "        <int>85</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso3_fi</string>",
              "      </key>",
              "      <value>",
              "        <int>85</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso2_fi</string>",
              "      </key>",
              "      <value>",
              "        <int>85</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso1_fi</string>",
              "      </key>",
              "      <value>",
              "        <int>85</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso0_fi</string>",
              "      </key>",
              "      <value>",
              "        <int>85</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Statistikår</string>",
              "      </key>",
              "      <value>",
              "        <int>78</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Aineisto</string>",
              "      </key>",
              "      <value>",
              "        <int>68</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusala</string>",
              "      </key>",
              "      <value>",
              "        <int>85</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>d6.erittely_nimi_fi</string>",
              "      </key>",
              "      <value>",
              "        <int>116</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>toiminto_nimi_fi</string>",
              "      </key>",
              "      <value>",
              "        <int>104</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tilastovuosi</string>",
              "      </key>",
              "      <value>",
              "        <int>86</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso5_fi</string>",
              "      </key>",
              "      <value>",
              "        <int>85</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso5_sv</string>",
              "      </key>",
              "      <value>",
              "        <int>90</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso5_en</string>",
              "      </key>",
              "      <value>",
              "        <int>91</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Konserni</string>",
              "      </key>",
              "      <value>",
              "        <int>71</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ohjauksenala</string>",
              "      </key>",
              "      <value>",
              "        <int>95</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ohjauksenala_sv</string>",
              "      </key>",
              "      <value>",
              "        <int>112</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ohjauksenala_en</string>",
              "      </key>",
              "      <value>",
              "        <int>113</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit_ohjauksenala</string>",
              "      </key>",
              "      <value>",
              "        <int>129</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Korkeakoulu</string>",
              "      </key>",
              "      <value>",
              "        <int>88</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_koodi</string>",
              "      </key>",
              "      <value>",
              "        <int>71</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Sektori</string>",
              "      </key>",
              "      <value>",
              "        <int>63</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Koodit_aineisto</string>",
              "      </key>",
              "      <value>",
              "        <int>30</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit_koulutusala</string>",
              "      </key>",
              "      <value>",
              "        <int>29</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit_yliopisto</string>",
              "      </key>",
              "      <value>",
              "        <int>28</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Material type</string>",
              "      </key>",
              "      <value>",
              "        <int>27</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Utbildningsområde</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>University</string>",
              "      </key>",
              "      <value>",
              "        <int>26</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Statistical year</string>",
              "      </key>",
              "      <value>",
              "        <int>25</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Field of education</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Material typ</string>",
              "      </key>",
              "      <value>",
              "        <int>24</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Universitet</string>",
              "      </key>",
              "      <value>",
              "        <int>23</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>arvo</string>",
              "      </key>",
              "      <value>",
              "        <int>17</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso4_en</string>",
              "      </key>",
              "      <value>",
              "        <int>16</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso3_en</string>",
              "      </key>",
              "      <value>",
              "        <int>15</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso2_en</string>",
              "      </key>",
              "      <value>",
              "        <int>14</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso1_en</string>",
              "      </key>",
              "      <value>",
              "        <int>13</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso0_en</string>",
              "      </key>",
              "      <value>",
              "        <int>12</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso4_sv</string>",
              "      </key>",
              "      <value>",
              "        <int>11</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso3_sv</string>",
              "      </key>",
              "      <value>",
              "        <int>10</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso2_sv</string>",
              "      </key>",
              "      <value>",
              "        <int>9</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso1_sv</string>",
              "      </key>",
              "      <value>",
              "        <int>8</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso0_sv</string>",
              "      </key>",
              "      <value>",
              "        <int>7</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso4_fi</string>",
              "      </key>",
              "      <value>",
              "        <int>6</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso3_fi</string>",
              "      </key>",
              "      <value>",
              "        <int>5</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso2_fi</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso1_fi</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso0_fi</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Statistikår</string>",
              "      </key>",
              "      <value>",
              "        <int>22</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Aineisto</string>",
              "      </key>",
              "      <value>",
              "        <int>21</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusala</string>",
              "      </key>",
              "      <value>",
              "        <int>20</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>d6.erittely_nimi_fi</string>",
              "      </key>",
              "      <value>",
              "        <int>39</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>toiminto_nimi_fi</string>",
              "      </key>",
              "      <value>",
              "        <int>18</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tilastovuosi</string>",
              "      </key>",
              "      <value>",
              "        <int>19</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso5_fi</string>",
              "      </key>",
              "      <value>",
              "        <int>31</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso5_sv</string>",
              "      </key>",
              "      <value>",
              "        <int>32</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso5_en</string>",
              "      </key>",
              "      <value>",
              "        <int>33</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Konserni</string>",
              "      </key>",
              "      <value>",
              "        <int>34</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ohjauksenala</string>",
              "      </key>",
              "      <value>",
              "        <int>35</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ohjauksenala_sv</string>",
              "      </key>",
              "      <value>",
              "        <int>36</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ohjauksenala_en</string>",
              "      </key>",
              "      <value>",
              "        <int>37</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit_ohjauksenala</string>",
              "      </key>",
              "      <value>",
              "        <int>38</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Korkeakoulu</string>",
              "      </key>",
              "      <value>",
              "        <int>40</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_koodi</string>",
              "      </key>",
              "      <value>",
              "        <int>41</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Sektori</string>",
              "      </key>",
              "      <value>",
              "        <int>42</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Statistical year</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>arvo</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso4_en</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso3_en</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso2_en</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso1_en</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso0_en</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso4_sv</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso3_sv</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso2_sv</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso1_sv</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso0_sv</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso4_fi</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso3_fi</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso2_fi</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso1_fi</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso0_fi</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Material typ</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Universitet</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Statistikår</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Aineisto</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>toiminto_nimi_fi</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koulutusala</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>d6.erittely_nimi_fi</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tilastovuosi</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>University</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Material type</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit_yliopisto</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit_koulutusala</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit_aineisto</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso5_fi</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso5_sv</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_taso5_en</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ohjauksenala</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ohjauksenala_sv</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Ohjauksenala_en</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Koodit_ohjauksenala</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Korkeakoulu</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>tili_koodi</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Sektori</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Sarakeleveys",
        "columns": [
          {
            "name": "Sarakeleveys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Sarakeleveys",
            "sourceProviderType": "Char",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "leveys",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "leveys",
            "sourceProviderType": "Char",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Sarakeleveys",
            "dataView": "full",
            "source": {
              "query": " SELECT [dw].[Sarakeleveys].* FROM [dw].[Sarakeleveys] ",
              "dataSource": "ANTERO"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Sarakeleveys</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>94</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>leveys</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>61</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Sarakeleveys</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>leveys</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked />",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dw].[Sarakeleveys].* FROM [dw].[Sarakeleveys] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Sarakeleveys"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dw"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Sarakeleveys</string>",
              "      </key>",
              "      <value>",
              "        <int>94</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>leveys</string>",
              "      </key>",
              "      <value>",
              "        <int>61</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Sarakeleveys</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>leveys</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked />",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      }
    ],
    "perspectives": [
      {
        "name": "Tuloslaskelma _vanha",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Suodatus tilastovuosi"
              },
              {
                "name": "Korkeakoulu"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Tuloslaskelma yliopisto 1",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Konserni"
              },
              {
                "name": "Suodatus tilastovuosi"
              },
              {
                "name": "Korkeakoulu"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Toimintokohtainen erittely",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Suodatus tilastovuosi"
              },
              {
                "name": "Korkeakoulu"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Tutkimusrahoitus",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Koulutusala"
              },
              {
                "name": "Ohjauksen ala"
              },
              {
                "name": "Suodatus tilastovuosi"
              },
              {
                "name": "Korkeakoulu"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Varsinaisen toiminnan kustannukset",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Koulutusala"
              },
              {
                "name": "Ohjauksen ala"
              },
              {
                "name": "Suodatus tilastovuosi"
              },
              {
                "name": "Koodit_aineisto"
              },
              {
                "name": "Korkeakoulu"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Tuloslaskelma",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Suodatus tilastovuosi"
              },
              {
                "name": "Korkeakoulu"
              },
              {
                "name": "Konserni"
              },
              {
                "name": "Sektori"
              }
            ],
            "measures": [
              {
                "name": "Korkokulut ja rahoituskulut saman konsernin yrityksille"
              },
              {
                "name": "Arvonalentumiset muiden pysyvien vastaavien sijoituksista"
              },
              {
                "name": "Arvonalentumiset vaihtuvien vastaavien rahoitusarvopapereista"
              },
              {
                "name": "Arvonalentumisten palautukset"
              },
              {
                "name": "Avustustuotot"
              },
              {
                "name": "Business Finland"
              },
              {
                "name": "EU-rahoitus"
              },
              {
                "name": "Euroopan Unionin maat, muu rahoitus"
              },
              {
                "name": "Euroopan Unionin maat, yritysrahoitus"
              },
              {
                "name": "Henkilöstökulut yhteensä"
              },
              {
                "name": "Henkilöstösivukulut: Eläkekulut"
              },
              {
                "name": "Henkilöstösivukulut: Muut henkilösivukulut"
              },
              {
                "name": "Keräysten ja lahjoitusten tuotot: kotitaloudet"
              },
              {
                "name": "Keräysten ja lahjoitusten tuotot: muut"
              },
              {
                "name": "Keräysten ja lahjoitusten tuotot: yritykset"
              },
              {
                "name": "Kone- ja laitevuokrat"
              },
              {
                "name": "Konserni: Vähemmistöosuudet"
              },
              {
                "name": "Korkeakoulujen valtionrahoitus"
              },
              {
                "name": "Korkokulut"
              },
              {
                "name": "Korkokulut ja rahoituskulut"
              },
              {
                "name": "Korkotuotot"
              },
              {
                "name": "Kotimaiset rahoituslaitokset"
              },
              {
                "name": "Kotimaiset yritykset"
              },
              {
                "name": "Kotitaloudet"
              },
              {
                "name": "Kunnat ja kuntayhtymät"
              },
              {
                "name": "LIIKEVOITTO (TAPPIO)"
              },
              {
                "name": "Liikevaihto"
              },
              {
                "name": "Varsinaisen sijoitustoiminnan tuotot yhteensä"
              },
              {
                "name": "Varsinaisen sijoitustoiminnan kulut yhteensä"
              },
              {
                "name": "Varsinaisen sijoitustoiminnan tuotto"
              },
              {
                "name": "Rahoitustuotot ja -kulut (netto)"
              },
              {
                "name": "Muu julkinen hallinto"
              },
              {
                "name": "Muu OKM"
              },
              {
                "name": "Muu valtio (pl. Business Finland, Akatemia, Sosiaaliturvarahastot ja muu OKM)"
              },
              {
                "name": "Muut kulut yhteensä"
              },
              {
                "name": "Muut sijoitustoiminnan tuotot"
              },
              {
                "name": "Muut ulkomaat, muu rahoitus"
              },
              {
                "name": "Muut ulkomaat, yritysrahoitus "
              },
              {
                "name": "Muut varainhankinnan kulut"
              },
              {
                "name": "Muut varainhankinnan tuotot"
              },
              {
                "name": "Muut varsinaisen toiminnan kulut"
              },
              {
                "name": "Myyntitappiot"
              },
              {
                "name": "Myyntituotot"
              },
              {
                "name": "Omakatteisten rahastojen muutos yhteensä"
              },
              {
                "name": "Osinkotuotot"
              },
              {
                "name": "Osuus osakkuusyhtiöiden tuloksesta (voitosta/tappiosta, +/-)"
              },
              {
                "name": "Palkat ja palkkiot"
              },
              {
                "name": "Palvelujen ostot"
              },
              {
                "name": "Poistoeron muutos (+/-)"
              },
              {
                "name": "Poistot ja arvonalentumiset"
              },
              {
                "name": "Suomen Akatemia"
              },
              {
                "name": "Tarvikkeet ja tavarat"
              },
              {
                "name": "Tilakustannukset"
              },
              {
                "name": "Tuloverot"
              },
              {
                "name": "Tuotot muista pysyvien vastaavien sijoituksista"
              },
              {
                "name": "Tuotot osuuksista omistusyhteysyrityksissä"
              },
              {
                "name": "Tuotot osuuksista saman konsernin yrityksissä"
              },
              {
                "name": "Ulkomainen liiketoiminta"
              },
              {
                "name": "Varainhankinnan liiketoiminnan kulut"
              },
              {
                "name": "Varainhankinnan liiketoiminnan tuotot"
              },
              {
                "name": "VOITTO (TAPPIO) ENNEN TILINPÄÄTÖS-SIIRTOJA JA VEROJA"
              },
              {
                "name": "Voittoa tavoittelemattomat yhteisöt (kirkot, säätiöt, puolueet, rahastot)"
              },
              {
                "name": "Vuokrakulut (vastikkeet)"
              },
              {
                "name": "Vuokratuotot"
              },
              {
                "name": "Rahoituskulut yhteensä"
              },
              {
                "name": "Kulut yhteensä"
              },
              {
                "name": "Rahoitustuotot yhteensä"
              },
              {
                "name": "Sidottujen rahastojen muutos yhteensä"
              },
              {
                "name": "Liiketoiminnan tuotot"
              },
              {
                "name": "Muut tuotot"
              },
              {
                "name": "Muut sijoitustoiminnan kulut"
              },
              {
                "name": "Keräysten ja lahjoitusten kulut"
              },
              {
                "name": "Käyvän arvon muutos (+/-)"
              },
              {
                "name": "Lahjoitusten tuotot: kotitaloudet"
              },
              {
                "name": "Lahjoitusten tuotot: muut"
              },
              {
                "name": "Lahjoitusten tuotot: yritykset"
              },
              {
                "name": "Liikevaihto (Tehty Liikevaihto2 koodilla)"
              },
              {
                "name": "Lukukausimaksut"
              },
              {
                "name": "Maksuasetuksen perusteella perittävät maksut"
              },
              {
                "name": "Muut korko- ja rahoitustuotot"
              },
              {
                "name": "Muut muut tuotot"
              },
              {
                "name": "Pysyväisluontoinen yhteistyö koulutuksen tukitoimintojen järjestämisessä kahden verotonta koulutusta antavan oppilaitoksen välillä"
              },
              {
                "name": "Siirto rahastoon"
              },
              {
                "name": "Siirto rahastosta"
              },
              {
                "name": "Siirto sidottuun rahastoon"
              },
              {
                "name": "Siirto sidotusta rahastosta"
              },
              {
                "name": "TILIKAUDEN VOITTO (TAPPIO)"
              },
              {
                "name": "Varainhankinnan kulut yhteensä"
              },
              {
                "name": "Varainhankinnan tuotot yhteensä"
              },
              {
                "name": "Varainhankinnan tuotto"
              },
              {
                "name": "Käyvän arvon rahasto"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Varsinaisen toiminnan kustannukset pivot",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Koulutusala"
              },
              {
                "name": "Ohjauksen ala"
              },
              {
                "name": "Suodatus tilastovuosi"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Tarkennettu toiminto"
              },
              {
                "name": "Päätoiminto"
              },
              {
                "name": "Toiminto"
              },
              {
                "name": "Koodit_päätoiminto"
              },
              {
                "name": "Korkeakoulu"
              }
            ]
          }
        ]
      },
      {
        "name": "Tase yliopisto",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Konserni"
              },
              {
                "name": "Suodatus tilastovuosi"
              },
              {
                "name": "Tilastovuosi"
              },
              {
                "name": "Korkeakoulu"
              }
            ]
          },
          {
            "name": "Sarakeleveys",
            "columns": [
              {
                "name": "leveys"
              },
              {
                "name": "Sarakeleveys"
              }
            ]
          }
        ]
      },
      {
        "name": "Tase",
        "tables": [
          {
            "name": "Muuttujat",
            "columns": [
              {
                "name": "Konserni"
              },
              {
                "name": "Korkeakoulu"
              },
              {
                "name": "Sektori"
              },
              {
                "name": "Tilastovuosi"
              }
            ],
            "measures": [
              {
                "name": "Aineet ja tarvikkeet"
              },
              {
                "name": "Aineettomat oikeudet"
              },
              {
                "name": "Arvonkorotus-rahasto"
              },
              {
                "name": "Arvonlisäverosaatava/-velka"
              },
              {
                "name": "Edellisten tilikausien voitto (tappio)"
              },
              {
                "name": "Eläkevaraukset"
              },
              {
                "name": "Ennakkomaksut"
              },
              {
                "name": "Ennakkomaksut (vaihto-omaisuus)"
              },
              {
                "name": "Ennakkomaksut ja keskeneräiset hankinnat"
              },
              {
                "name": "Kehittämismenot"
              },
              {
                "name": "Keskeneräiset tuotteet"
              },
              {
                "name": "Kompensoitavat perustoiminnan alv-menot"
              },
              {
                "name": "Koneet ja kalusto"
              },
              {
                "name": "Konserni-liikearvo"
              },
              {
                "name": "Konsernireservi"
              },
              {
                "name": "Liikearvo"
              },
              {
                "name": "Maa- ja vesialueet"
              },
              {
                "name": "Muu vaihto-omaisuus"
              },
              {
                "name": "Muut aineelliset hyödykkeet"
              },
              {
                "name": "Muut aineettomat hyödykkeet"
              },
              {
                "name": "Muut arvopaperit"
              },
              {
                "name": "Muut arvopaperit (rahoitusarvopaperit)"
              },
              {
                "name": "Muut osakkeet ja osuudet"
              },
              {
                "name": "Muut osakkeet ja osuudet (rahoitusarvopaperit)"
              },
              {
                "name": "Muut osakkeet ja osuudet (sijoitukset)"
              },
              {
                "name": "Muut pakolliset varaukset"
              },
              {
                "name": "Muut saamiset (sijoitukset)"
              },
              {
                "name": "Muut sidotut rahastot "
              },
              {
                "name": "Muut vapaat rahastot (esim. sijoitusrahasto)"
              },
              {
                "name": "Muut varat"
              },
              {
                "name": "Oma pääoma yhteensä"
              },
              {
                "name": "Omakatteiset rahastot "
              },
              {
                "name": "Omakatteisten rahastojen sijoitukset yhteensä"
              },
              {
                "name": "Omakatteisten rahastojen varat"
              },
              {
                "name": "Omakatteisten rahastojen velat"
              },
              {
                "name": "Osake-, osuus- tai muu vastaava pääoma / peruspääoma"
              },
              {
                "name": "Osuudet omistusyhteys-yrityksissä"
              },
              {
                "name": "Osuudet saman konsernin yrityksissä (rahoitusarvopaperit)"
              },
              {
                "name": "Osuudet saman konsernin yrityksissä (sijoitukset)"
              },
              {
                "name": "Poistoero"
              },
              {
                "name": "Pääomarahasto"
              },
              {
                "name": "Rahasto-osuudet"
              },
              {
                "name": "Rahat ja pankki-saamiset"
              },
              {
                "name": "Rahat ja pankki-saamiset (vaihtuvat)"
              },
              {
                "name": "Rakennukset ja rakennelmat"
              },
              {
                "name": "Saadut alv-kompensaatiot"
              },
              {
                "name": "Saamiset omistusyhteys-yrityksiltä"
              },
              {
                "name": "Saamiset saman konsernin yrityksiltä"
              },
              {
                "name": "Sijoitetun vapaan oman pääoman rahasto"
              },
              {
                "name": "Tilikauden voitto (tai tappio)"
              },
              {
                "name": "Toimintapääoma"
              },
              {
                "name": "Valmiit tuotteet/ tavarat"
              },
              {
                "name": "Vararahasto"
              },
              {
                "name": "Vastaavaa yhteensä"
              },
              {
                "name": "Vastattavaa yhteensä"
              },
              {
                "name": "Verotusperäiset varaukset"
              },
              {
                "name": "Verovaraukset"
              },
              {
                "name": "Vähemmistö- osuudet (konserni)"
              },
              {
                "name": "Yhtiöjärjestyksen tai sääntöjen mukaiset rahastot"
              },
              {
                "name": "Ylikurssirahasto"
              },
              {
                "name": "Lyhytaikaiset eläkelainat"
              },
              {
                "name": "Lyhytaikaiset joukkovelkakirjalainat"
              },
              {
                "name": "Lyhytaikaiset lainasaamiset"
              },
              {
                "name": "Lyhytaikaiset lainat rahoituslaitoksilta"
              },
              {
                "name": "Lyhytaikaiset laskennaliset verovelat"
              },
              {
                "name": "Lyhytaikaiset laskennalliset verosaamiset"
              },
              {
                "name": "Lyhytaikaiset muut saamiset"
              },
              {
                "name": "Lyhytaikaiset muut velat"
              },
              {
                "name": "Lyhytaikaiset myyntisaamiset"
              },
              {
                "name": "Lyhytaikaiset ostovelat"
              },
              {
                "name": "Lyhytaikaiset pääomalainat"
              },
              {
                "name": "Lyhytaikaiset rahoitusvekselit"
              },
              {
                "name": "Lyhytaikaiset saadut ennakot"
              },
              {
                "name": "Lyhytaikaiset saamiset omistusyhteysyrityksiltä"
              },
              {
                "name": "Lyhytaikaiset saamiset saman konsernin yrityksiltä"
              },
              {
                "name": "Lyhytaikaiset siirtosaamiset"
              },
              {
                "name": "Lyhytaikaiset siirtovelat"
              },
              {
                "name": "Lyhytaikaiset vaihtovelkakirjalainat"
              },
              {
                "name": "Lyhytaikaiset velat omistusyhteysyrityksille"
              },
              {
                "name": "Lyhytaikaiset velat saman konsernin yrityksille"
              },
              {
                "name": "Pitkäaikaiset eläkelainat"
              },
              {
                "name": "Pitkäaikaiset joukkovelkakirjalainat"
              },
              {
                "name": "Pitkäaikaiset lainasaamiset"
              },
              {
                "name": "Pitkäaikaiset lainat rahoituslaitoksilta"
              },
              {
                "name": "Pitkäaikaiset laskennaliset verovelat"
              },
              {
                "name": "Pitkäaikaiset laskennalliset verosaamiset"
              },
              {
                "name": "Pitkäaikaiset muut saamiset"
              },
              {
                "name": "Pitkäaikaiset muut velat"
              },
              {
                "name": "Pitkäaikaiset myyntisaamiset"
              },
              {
                "name": "Pitkäaikaiset ostovelat"
              },
              {
                "name": "Pitkäaikaiset pääomalainat"
              },
              {
                "name": "Pitkäaikaiset rahoitusvekselit"
              },
              {
                "name": "Pitkäaikaiset saadut ennakot"
              },
              {
                "name": "Pitkäaikaiset saamiset omistusyhteysyrityksiltä"
              },
              {
                "name": "Pitkäaikaiset saamiset saman konsernin yrityksiltä"
              },
              {
                "name": "Pitkäaikaiset siirtosaamiset"
              },
              {
                "name": "Pitkäaikaiset siirtovelat"
              },
              {
                "name": "Pitkäaikaiset vaihtovelkakirjalainat"
              },
              {
                "name": "Pitkäaikaiset velat omistusyhteysyrityksille"
              },
              {
                "name": "Pitkäaikaiset velat saman konsernin yrityksille"
              },
              {
                "name": "Omavaraisuusaste"
              }
            ]
          }
        ]
      }
    ],
    "roles": [
      {
        "name": "Testi",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "DWI\\T_VIPU_SSAS_DB_R",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1751"
          },
          {
            "memberName": "DWI\\T_VIPU_SSAS_DB_R_TK",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1753"
          },
          {
            "memberName": "DWI\\Z_T_Antero_Read_TAB",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-4155"
          },
          {
            "memberName": "DWI\\Z_P_Antero_Read_TAB",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-4156"
          },
          {
            "memberName": "DWI\\T_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1732"
          }
        ]
      },
      {
        "name": "Tuotanto",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "DWI\\P_VIPU_SSAS_DB_R",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1752"
          },
          {
            "memberName": "DWI\\P_VIPU_SSAS_DB_R_TK",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1754"
          },
          {
            "memberName": "NT AUTHORITY\\IUSR",
            "memberId": "S-1-5-17"
          },
          {
            "memberName": "DWI\\Z_T_Antero_Read_TAB",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-4155"
          },
          {
            "memberName": "DWI\\Z_P_Antero_Read_TAB",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-4156"
          },
          {
            "memberName": "DWI\\P_SP_Excel_S_Read",
            "memberId": "S-1-5-21-2196741920-3238685902-2581541251-1733"
          }
        ]
      }
    ]
  },
  "id": "SemanticModel"
}